### ISSUE TITLE
jhipster entity fails spectaculary

### ISSUE THREAD

**Issue by jkoorts** [jhipster/generator-jhipster#10005]
v6.1.1

Running "jhipster entity" shows stacktrace 

C:\dev\java\bikebuddy\service-oemgateway>jhipster entity
INFO! Using JHipster version installed locally in current project's node_modules
INFO! Executing jhipster:entity
INFO! Options: from-cli: true
Did not provide required argument name!
Error: Did not provide required argument name!
    at _arguments.forEach (C:\dev\java\bikebuddy\service-oemgateway\node_modules\yeoman-generator\lib\index.js:372:11)
    at Array.forEach (<anonymous>)
    at EntityGenerator.checkRequiredArgs (C:\dev\java\bikebuddy\service-oemgateway\node_modules\yeoman-generator\lib\index.js:366:21)
    at EntityGenerator.parseOptions (C:\dev\java\bikebuddy\service-oemgateway\node_modules\yeoman-generator\lib\index.js:351:10)
    at EntityGenerator.argument (C:\dev\java\bikebuddy\service-oemgateway\node_modules\yeoman-generator\lib\index.js:274:10)
    at new EntityGenerator (C:\dev\java\bikebuddy\service-oemgateway\node_modules\generator-jhipster\generators\entity\index.js:41:14)
    at Environment.instantiate (C:\dev\java\bikebuddy\service-oemgateway\node_modules\yeoman-environment\lib\environment.js:429:12)
    at Environment.create (C:\dev\java\bikebuddy\service-oemgateway\node_modules\yeoman-environment\lib\environment.js:407:17)
    at Environment.run (C:\dev\java\bikebuddy\service-oemgateway\node_modules\yeoman-environment\lib\environment.js:464:28)
    at runYoCommand (C:\dev\java\bikebuddy\service-oemgateway\node_modules\generator-jhipster\cli\cli.js:46:13)

Expected: A nice failure message

**Comment by deepu105** [comment]
Did you read the failure message" it clearly says `Did not provide required argument name!
Error: Did not provide required argument name!` And no we need stack trace so that it's helpful for advanced users to identify where issue comes from.

**Comment by jkoorts** [comment]
I did read it. But calc.exe does not throw a stacktrace, neither does mysql.exe

**Comment by deepu105** [comment]
But that doesn't mean anything. Our aim is to provide a useful tool so the focus is more on utility rather than being nice to look at.
