### ISSUE TITLE
jjwt-api and jjwt-impl are scope -> runtime causing java.lang.NoSuchMethodError: 'int io.jsonwebtoken.SignatureAlgorithm.getMinKeyLength()'

### ISSUE THREAD

**Issue by mikebski** [jhipster/generator-jhipster#10416]
##### **Overview of the issue**

When I generate my project, I get the following in my POM
```
<dependency>
            <groupId>io.jsonwebtoken</groupId>
            <artifactId>jjwt-impl</artifactId>
            <scope>runtime</scope>
        </dependency>
        <dependency>
            <groupId>io.jsonwebtoken</groupId>
            <artifactId>jjwt-jackson</artifactId>
            <scope>runtime</scope>
</dependency>

```

I build with ` ./mvnw package -Pprod verify jib:dockerBuild`

Then, I run in Docker with ``

Then, I get this:

 | Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'tokenProvider' defined in file [/app/classes/com/mulchr/security/jwt/TokenProvider.class]: Invocation of init method failed; nested exception is java.lang.NoSuchMethodError: 'int io.jsonwebtoken.SignatureAlgorithm.getMinKeyLength()'
mulchr-app_1         |  at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1778)
mulchr-app_1         |  at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:593)
mulchr-app_1         |  at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:515)
mulchr-app_1         |  at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320)
mulchr-app_1         |  at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
mulchr-app_1         |  at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318)
mulchr-app_1         |  at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
mulchr-app_1         |  at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:277)
mulchr-app_1         |  at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1251)
mulchr-app_1         |  at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1171)
mulchr-app_1         |  at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:857)
mulchr-app_1         |  at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:760)
mulchr-app_1         |  ... 23 common frames omitted
mulchr-app_1         | Caused by: java.lang.NoSuchMethodError: 'int io.jsonwebtoken.SignatureAlgorithm.getMinKeyLength()'
mulchr-app_1         |  at io.jsonwebtoken.security.Keys.hmacShaKeyFor(Keys.java:69)
mulchr-app_1         |  at com.mulchr.security.jwt.TokenProvider.afterPropertiesSet(TokenProvider.kt:47)
mulchr-app_1         |  at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1837)
mulchr-app_1         |  at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1774)
mulchr-app_1         |  ... 34 common frames omitted

##### **Motivation for or Use Case**

It's a bug b/c it should work in Docker...

##### **Reproduce the error**

See the bug description

##### **Related issues**

None found

##### **Suggest a Fix**

Add these as regular reps and not runtime scope

##### **JHipster Version(s)**

v6.1.2

##### **JHipster configuration**

INFO! Using JHipster version installed locally in current project's node_modules
INFO! Executing jhipster:info
INFO! Options: from-cli: true
Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
mulchr@0.0.0 /Users/mike/code/public/jh-mulchr2
├── generator-jhipster@6.1.2 
└─┬ generator-jhipster-kotlin@1.0.0
  └── generator-jhipster@6.1.2  deduped

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "enableHibernateCache": true,
    "enableSwaggerCodegen": false,
    "enableTranslation": true,
    "jhiPrefix": "jhi",
    "languages": [
      "en",
      "fr"
    ],
    "messageBroker": false,
    "nativeLanguage": "en",
    "packageName": "com.mulchr",
    "packageFolder": "com/mulchr",
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "serviceDiscoveryType": false,
    "skipClient": false,
    "skipServer": false,
    "testFrameworks": [],
    "websocket": false,
    "applicationType": "monolith",
    "baseName": "mulchr",
    "authenticationType": "jwt",
    "buildTool": "maven",
    "clientFramework": "react",
    "jhipsterVersion": "6.1.2",
    "skipUserManagement": false,
    "clientPackageManager": "npm",
    "cacheProvider": "ehcache",
    "serverPort": "8080",
    "useSass": true,
    "clientTheme": "none",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [
      {
        "name": "generator-jhipster-kotlin",
        "version": "1.0.0"
      }
    ],
    "blueprint": "generator-jhipster-kotlin",
    "blueprintVersion": "1.0.0"
  },
  "entities": [
    "Person",
    "Product",
    "ContactInformation"
  ],
  "generator-jhipster-kotlin": {
    "jhipsterVersion": "6.1.2",
    "applicationType": "monolith",
    "baseName": "mulchr",
    "packageName": "com.mulchr",
    "packageFolder": "com/mulchr",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "bXktc2VjcmV0LXRva2VuLXRvLWNoYW5nZS1pbi1wcm9kdWN0aW9uLWFuZC10by1rZWVwLWluLWEtc2VjdXJlLXBsYWNl",
    "enableTranslation": true
  }
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity Person {
  name String required,
  address String required,
  lat Float required,
  lng Float required,
  active Boolean required,
  acceptedTosInstant Instant,
  deliveryInstructions String
}
entity Product {
  name String required unique,
  description String required
}
entity ContactInformation {
  info String required unique,
  validated Boolean required,
  contactType ContactType required,
  activationKey String
}
enum ContactType {
  EMAIL,
  PHONE
}

relationship OneToOne {
  Person{user(login)} to User
}
relationship ManyToOne {
  ContactInformation{person(name)} to Person
}
relationship ManyToMany {
  Person{receiveProducts} to Product{receivers},
  Person{provideProducts} to Product{providers}
}

dto Person, Product, ContactInformation with mapstruct
paginate Person, Product, ContactInformation with infinite-scroll
service Person, Product, ContactInformation with serviceClass
filter Person, Product, ContactInformation

</pre>
</details>

##### **Environment and Tools**

openjdk version "1.8.0_212"
OpenJDK Runtime Environment Corretto-8.212.04.1 (build 1.8.0_212-b04)
OpenJDK 64-Bit Server VM Corretto-8.212.04.1 (build 25.212-b04, mixed mode)

git version 2.21.0

node: v10.15.3

npm: 6.9.0

yeoman: 3.1.0

Docker version 19.03.1, build 74b1e89

docker-compose version 1.24.1, build 4667896b

INFO! Congratulations, JHipster execution is complete!

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

N/A (I think...)

##### **Browsers and Operating System**

On a Mac with OSX but I doubt it's relevant

-   [x ] Checking this box is mandatory (this is just to show you read everything)

**Comment by pascalgrimaud** [comment]
@mikebski : did you use jhipster-kotlin blueprint ?

**Comment by vishal423** [comment]
I can see `generator-jhipster-kotlin` in the `yeoman` configurations. We should move it to the `kotlin` blueprint repository.
