### ISSUE TITLE
Error running jhipster --blueprint kotlin command

### ISSUE THREAD

**Issue by arabbani** [jhipster/generator-jhipster#10417]
##### **Overview of the issue**

Jhipster is reporting that the `generator-jhipster-kotlin` is not installed while running the ` jhipster --blueprint kotlin` command, even though `generator-jhipster-kotlin` is installed.

> I am using yarn

Here is the full cli output:
`
jhipster --blueprint kotlin
INFO! No custom commands found within blueprint: generator-jhipster-kotlin
INFO! Using JHipster version installed globally
INFO! Running default command
INFO! Executing jhipster:app
INFO! Options: blueprint: kotlin, from-cli: true
WARNING! --blueprint option is deprecated. Please use --blueprints instead

        ██╗ ██╗   ██╗ ████████╗ ███████╗   ██████╗ ████████╗ ████████╗ ███████╗
        ██║ ██║   ██║ ╚══██╔══╝ ██╔═══██╗ ██╔════╝ ╚══██╔══╝ ██╔═════╝ ██╔═══██╗
        ██║ ████████║    ██║    ███████╔╝ ╚█████╗     ██║    ██████╗   ███████╔╝
  ██╗   ██║ ██╔═══██║    ██║    ██╔════╝   ╚═══██╗    ██║    ██╔═══╝   ██╔══██║
  ╚██████╔╝ ██║   ██║ ████████╗ ██║       ██████╔╝    ██║    ████████╗ ██║  ╚██╗
   ╚═════╝  ╚═╝   ╚═╝ ╚═══════╝ ╚═╝       ╚═════╝     ╚═╝    ╚═══════╝ ╚═╝   ╚═╝

                            https://www.jhipster.tech

Welcome to JHipster v6.3.0
Application files will be generated in folder: D:\
 _______________________________________________________________________________________________________________

  Documentation for creating an application is at https://www.jhipster.tech/creating-an-app/
  If you find JHipster useful, consider sponsoring the project at https://opencollective.com/generator-jhipster
 _______________________________________________________________________________________________________________

events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: The generator-jhipster-kotlin blueprint provided is not installed. Please install it using command npm i -g generator-jhipster-kotlin.
    at Environment.error (C:\Users\Arif Rabbani\AppData\Local\Yarn\Data\global\node_modules\yeoman-environment\lib\environment.js:176:40)
    at module.exports.error (C:\Users\Arif Rabbani\AppData\Local\Yarn\Data\global\node_modules\generator-jhipster\generators\generator-base.js:1451:18)
    at shelljs.exec (C:\Users\Arif Rabbani\AppData\Local\Yarn\Data\global\node_modules\generator-jhipster\generators\generator-base-private.js:839:22)
    at C:\Users\Arif Rabbani\AppData\Local\Yarn\Data\global\node_modules\shelljs\src\exec.js:121:9
    at ChildProcess.exithandler (child_process.js:285:7)
    at ChildProcess.emit (events.js:198:13)
    at maybeClose (internal/child_process.js:982:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
Emitted 'error' event at:
    at Environment.error (C:\Users\Arif Rabbani\AppData\Local\Yarn\Data\global\node_modules\yeoman-environment\lib\environment.js:178:15)
    at module.exports.error (C:\Users\Arif Rabbani\AppData\Local\Yarn\Data\global\node_modules\generator-jhipster\generators\generator-base.js:1451:18)
    [... lines matching original stack trace ...]
    at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
`

##### **JHipster Version(s)**

JHipster v6.3.0

##### **Environment and Tools**

openjdk version "11.0.4" 2019-07-16
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.4+11)
Eclipse OpenJ9 VM AdoptOpenJDK (build openj9-0.15.1, JRE 11 Windows 10 amd64-64-Bit Compressed References 20190717_282 (JIT enabled, AOT enabled)
OpenJ9   - 0f66c6431
OMR      - ec782f26
JCL      - fa49279450 based on jdk-11.0.4+11)

git version 2.19.0.windows.1

node: v10.16.1

npm: 6.4.1

yeoman: 3.1.0

yarn: 1.17.3

##### **Browsers and Operating System**

Windows 10

-   [  ] Checking this box is mandatory (this is just to show you read everything)

**Comment by clement26695** [comment]
Hi @arabbani !

Thank you for reporting this. Would it be possible to give us a few more details : 

- Could you rerun the command with `--debug` flag and print the output here ? 
- Is generator-jhipster installed locally or globally ? 
- Is generator-jhipster-kotlin installed locally or globally ?

Thank you

**Comment by arabbani** [comment]
jhipster --blueprint kotlin --debug
INFO! No custom commands found within blueprint: generator-jhipster-kotlin
INFO! Using JHipster version installed globally
INFO! Debug logging is on
DEBUG!  No command specified. Running default
INFO! Running default command
DEBUG!  cmd: app
DEBUG!  args:
DEBUG!  opts:
DEBUG!  cmdArgs:
INFO! Executing jhipster:app
INFO! Options: blueprint: kotlin, debug: true, from-cli: true
WARNING! --blueprint option is deprecated. Please use --blueprints instead


        ██╗ ██╗   ██╗ ████████╗ ███████╗   ██████╗ ████████╗ ████████╗ ███████╗
        ██║ ██║   ██║ ╚══██╔══╝ ██╔═══██╗ ██╔════╝ ╚══██╔══╝ ██╔═════╝ ██╔═══██╗
        ██║ ████████║    ██║    ███████╔╝ ╚█████╗     ██║    ██████╗   ███████╔╝
  ██╗   ██║ ██╔═══██║    ██║    ██╔════╝   ╚═══██╗    ██║    ██╔═══╝   ██╔══██║
  ╚██████╔╝ ██║   ██║ ████████╗ ██║       ██████╔╝    ██║    ████████╗ ██║  ╚██╗
   ╚═════╝  ╚═╝   ╚═╝ ╚═══════╝ ╚═╝       ╚═════╝     ╚═╝    ╚═══════╝ ╚═╝   ╚═╝

                            https://www.jhipster.tech

Welcome to JHipster v6.3.0
Application files will be generated in folder: D:\
 _______________________________________________________________________________________________________________

  Documentation for creating an application is at https://www.jhipster.tech/creating-an-app/
  If you find JHipster useful, consider sponsoring the project at https://opencollective.com/generator-jhipster
 _______________________________________________________________________________________________________________

events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: The generator-jhipster-kotlin blueprint provided is not installed. Please install it using command npm i -g generator-jhipster-kotlin.
    at Environment.error (C:\Users\Arif Rabbani\AppData\Local\Yarn\Data\global\node_modules\yeoman-environment\lib\environment.js:176:40)
    at module.exports.error (C:\Users\Arif Rabbani\AppData\Local\Yarn\Data\global\node_modules\generator-jhipster\generators\generator-base.js:1451:18)
    at shelljs.exec (C:\Users\Arif Rabbani\AppData\Local\Yarn\Data\global\node_modules\generator-jhipster\generators\generator-base-private.js:839:22)
    at C:\Users\Arif Rabbani\AppData\Local\Yarn\Data\global\node_modules\shelljs\src\exec.js:121:9
    at ChildProcess.exithandler (child_process.js:285:7)
    at ChildProcess.emit (events.js:198:13)
    at maybeClose (internal/child_process.js:982:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
Emitted 'error' event at:
    at Environment.error (C:\Users\Arif Rabbani\AppData\Local\Yarn\Data\global\node_modules\yeoman-environment\lib\environment.js:178:15)
    at module.exports.error (C:\Users\Arif Rabbani\AppData\Local\Yarn\Data\global\node_modules\generator-jhipster\generators\generator-base.js:1451:18)
    [... lines matching original stack trace ...]
    at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)

**Comment by arabbani** [comment]
Everything is installed globally

**Comment by pascalgrimaud** [comment]
Unless there is a problem in generator-jhipster, I think this ticket should go to jhipster-kotlin blueprint
