### ISSUE TITLE
Build fail at npm install with JHipster 2.1.0 on Windows

### ISSUE THREAD

**Issue by Kwaq** [jhipster/generator-jhipster#1058]
I'm doing clean installation with default option and build is failing due to npm install error.

In version 2.1.0 node-pom-parser was used to obtain project version from pom.xml.
node-pom-parser uses node-expat which uses node-gyp. 
As it turns out, a lot stuff has to be installed to use node-gyp on Windows: https://github.com/TooTallNate/node-gyp#installation. 

I don't have Windows SDK installed and I presume that that might be the cause of the error below.

If that's the case, then price of usage of node-pom-parser on Windows is high.

```bat
> node-expat@2.3.4 install D:\work\workspace\idea\temp\node_modules\node-pom-parser\node_modules\node-expat
> node-gyp rebuild


D:\work\workspace\idea\temp\node_modules\node-pom-parser\node_modules\node-expat>node "D:\work\tools\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\n
ode_modules\node-gyp\bin\node-gyp.js" rebuild
gyp ERR! configure error
gyp ERR! stack Error: spawn ENOENT
gyp ERR! stack     at errnoException (child_process.js:1011:11)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:802:34)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "node" "D:\\work\\tools\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\work\workspace\idea\temp\node_modules\node-pom-parser\node_modules\node-expat
gyp ERR! node -v v0.10.36
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok
npm WARN prefer global yo@1.4.5 should be installed with -g

> yo@1.4.5 postinstall D:\work\workspace\idea\temp\node_modules\yo
> yodoctor


Yeoman Doctor
Running sanity checks on your system

√ Global configuration file is valid
√ NODE_PATH matches the npm root
√ No .bowerrc file in home directory
√ No .yo-rc.json file in home directory

Everything looks all right!
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "D:\\work\\tools\\nodejs\\\\node.exe" "D:\\work\\tools\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v0.10.36
npm ERR! npm  v2.3.0
npm ERR! code ELIFECYCLE

npm ERR! node-expat@2.3.4 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-expat@2.3.4 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the node-expat package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-expat
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\work\workspace\idea\temp\npm-debug.log
Loading "Gruntfile.js" tasks...ERROR
>> Error: Cannot find module 'node-pom-parser'
Warning: Task "ngconstant:dev" not found. Use --force to continue.

Aborted due to warnings.
```

**Comment by jdubois** [comment]
@andidev I think you added this tool, can you have a look?
This is the biggest issue with Node, it's not OS-independant, we already had a ton of issues with that.

-> if it really blocks people from using JHipster on Windows, we must correct this, or remove this, ASAP

**Comment by andidev** [comment]
I can fix this tonight. We can use the same regex search approach as with gulp. Did not know about these kind of problems with node.
@Kwaq could you please verify that generating a project with gulp works on Windows so that I do not copy another implementation that does not work on Windows.

**Comment by Kwaq** [comment]
@andidev Generating project with Gulp fails with same error as it also uses node-pom-parser module.

**Comment by andidev** [comment]
@Kwaq Sorry, I meant Gradle not gulp. Could you please try generatirng again?

**Comment by andidev** [comment]
The fix will probably be a really nasty beast =)
Not sure how to parse the version in pom.xml in a way. The Gradle version parsing is not that beautiful either.

**Comment by Kwaq** [comment]
@andidev Generation with Gradle works.

**Comment by Kwaq** [comment]
@andidev I would replace the node-pom-parser with Maven resources filtering and grunt-properties-reader. You could create app.properties that would contain project version which then could be read by Grunt.

**Comment by andidev** [comment]
Thanks, then I'll do the quickfix tonight @jdubois .
The quickfix will parse the second occurence of the version tag in the java pom.xml and present it as the application version in the navbar. (the first occurence it the version of the parent pom)

We need to try to find a xml parsing library that works under Windows to do it the right way.
@Kwaq could you maybe help us test this feature later?

**Comment by jdubois** [comment]
OK:

- If you have a good fix please test it well and explain it in your PR -> I'm sorry but I don't have much time tonight
- If it fails I'll rollback the commit that did this problem (but I will need to find it first!)

I'm sorry but if the generator fails for everyone on Windows, we can't stay too long in this situation.

**Comment by andidev** [comment]
In case you need to roll it back you will have to roll the following PRs back
#1050 
#1052

**Comment by atomfrede** [comment]
@andidev I can take my working laptop home today, so I can verify your changes also on a windows machine if you like.

**Comment by andidev** [comment]
@atomfrede thanks, that would be nice

**Comment by kbjp** [comment]
I'm using jhipster 2.1.1 but it looks like node-gyp is still required in this version... and node-gyp itself requires Visual-Studio express...3.5GB ! ...not really lightweight. :S 
Am I missing anything ?
kbjp

**Comment by atomfrede** [comment]
I'll try it during the day again with my windows machine if it works with the official release. Are you using maven + grunt?

**Comment by atomfrede** [comment]
Just checked it with a fresh installed jhipster. There is still some error message during setup, but it finish successfully. Both ``grunt serve`` and ``mvn spring-boot:run`` works as expected. I don't have visual studio installed, but I guess somewhere on my machine there is .net framework, don't know if this is important.

**Comment by andidev** [comment]
Please provide the console prints for the errors.

**Comment by atomfrede** [comment]
They are in german (don't know why microsoft localizes *every*thing), but if it helps, give me a little time, as I'm on my way to the office.

**Comment by kbjp** [comment]
>>There is still some error message during setup, but it finish successfully.
Oh, sorry, looks like I missed the fact that, nowadays, "Fatal error" is just another way to say "successful". :-) ...apologies, bad joke.
Ok, maybe things run just fine by ignoring node-gyp rebuild errors, but for old-school boys like me who like clean builds, I had to install python (2.73) and visual-studio express to make those error messages disappear...seems a bit over-killing.
Basically I followed below post to make it work:
http://stackoverflow.com/questions/21365714/nodejs-error-installing-with-npm
(note that, according to that post, the node-gyp dependencies are much "heavier" on windows than unix)
Regards
kbjp

**Comment by atomfrede** [comment]
The first lines indicate a fatal error, saying, that ``VCBuild.exe`` can't be loaded. Nevertheless its done without errors at the end (what was not the case before @andidev provided the quickfix). Both 
``mvn spring-boot:run`` and ``grunt serve`` are working and the version number is visible in the navigation bar.


```
d:\mvn-grunt\node_modules\karma\node_modules\socket.io\node_modules\socket.io-client\node_modules\ws>node "c:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild
Die Projekte in dieser Projektmappe werden nacheinander erstellt. Um eine parallele Erstellung zu ermöglichen, müssen Sie den Schalter "/m" hinzufügen.
MSBUILD : error MSB3428: Die Visual C++-Komponente "VCBuild.exe" konnte nicht geladen werden. Um dieses Problem zu beheben, installieren Sie entweder 1) .NET Framework 2.0 SDK oder 2) Microsoft Visual Studio 2005 oder 3) fügen Sie den Spei cherort der Komponente zum Systempfad hinzu, falls er vom Standardspeicherort abweicht.  [d:\mvn-grunt\node_modules\karma\node_modules\socket.io\node_modules\socket.io-client\node_modules\ws\build\binding.sln]
MSBUILD : error MSB3428: Die Visual C++-Komponente "VCBuild.exe" konnte nicht geladen werden. Um dieses Problem zu beheben, installieren Sie entweder 1) .NET Framework 2.0 SDK oder 2) Microsoft Visual Studio 2005 oder 3) fügen Sie den Spei cherort der Komponente zum Systempfad hinzu, falls er vom Standardspeicherort abweicht.  [d:\mvn-grunt\node_modules\karma\node_modules\socket.io\node_modules\socket.io-client\node_modules\ws\build\binding.sln]
|
> pngquant-bin@2.0.3 postinstall d:\mvn-grunt\node_modules\grunt-contrib-imagemin\node_modules\imagemin\node_modules\imagemin-pngquant\node_modules\pngquant-bin
> node lib/install.js

  √ pngquant pre-build test passed successfully

> jpegtran-bin@2.0.2 postinstall d:\mvn-grunt\node_modules\grunt-contrib-imagemin\node_modules\imagemin\node_modules\imagemin-jpegtran\node_modules\jpegtran-bin
> node lib/install.js

  √ jpegtran pre-build test passed successfully
/


> optipng-bin@2.0.4 postinstall d:\mvn-grunt\node_modules\grunt-contrib-imagemin\node_modules\imagemin\node_modules\imagemin-optipng\node_modules\optipng-bin
> node lib/install.js

  √ optipng pre-build test passed successfully

> gifsicle@2.0.1 postinstall d:\mvn-grunt\node_modules\grunt-contrib-imagemin\node_modules\imagemin\node_modules\imagemin-gifsicle\node_modules\gifsicle
> node lib/install.js

  √ gifsicle pre-build test passed successfully

npm WARN prefer global yo@1.3.3 should be installed with -g

> yo@1.3.3 postinstall d:\mvn-grunt\node_modules\yo
> yodoctor


Yeoman Doctor
Running sanity checks on your system

√ Global configuration file is valid
√ NODE_PATH matches the npm root
√ No .bowerrc file in home directory
√ No .yo-rc.json file in home directory

Everything looks all right!
karma-script-launcher@0.1.0 node_modules\karma-script-launcher

karma-chrome-launcher@0.1.7 node_modules\karma-chrome-launcher

karma-html2js-preprocessor@0.1.0 node_modules\karma-html2js-preprocessor

grunt-wiredep@2.0.0 node_modules\grunt-wiredep

grunt-rev@0.1.0 node_modules\grunt-rev

grunt-karma@0.10.1 node_modules\grunt-karma

grunt-text-replace@0.4.0 node_modules\grunt-text-replace

grunt-contrib-clean@0.6.0 node_modules\grunt-contrib-clean
└── rimraf@2.2.8

zeparser@0.0.7 node_modules\zeparser

grunt-concurrent@1.0.0 node_modules\grunt-concurrent
├── async@0.9.0
└── pad-stdio@1.0.0 (lpad@1.0.0)

event-stream@3.2.1 node_modules\event-stream
├── stream-combiner@0.0.4
├── duplexer@0.1.1
├── from@0.1.3
├── pause-stream@0.0.11
├── map-stream@0.1.0
├── split@0.2.10
└── through@2.3.6

time-grunt@1.0.0 node_modules\time-grunt
├── date-time@1.0.0
├── figures@1.3.5
├── text-table@0.2.0
├── hooker@0.2.3
├── pretty-ms@1.0.0 (parse-ms@1.0.0, get-stdin@3.0.2)
└── chalk@0.5.1 (escape-string-regexp@1.0.2, ansi-styles@1.1.0, supports-color@0.2.0, has-ansi@0.1.0, strip-ansi@0.3.0)

grunt-ng-constant@1.0.0 node_modules\grunt-ng-constant
├── tosource@0.1.3
└── jju@1.1.0

grunt-cli@0.1.13 node_modules\grunt-cli
├── resolve@0.3.1
├── nopt@1.0.10 (abbrev@1.0.5)
└── findup-sync@0.1.3 (glob@3.2.11)

jshint-stylish@1.0.0 node_modules\jshint-stylish
├── log-symbols@1.0.1
├── text-table@0.2.0
├── string-length@1.0.0 (strip-ansi@2.0.1)
└── chalk@0.5.1 (ansi-styles@1.1.0, supports-color@0.2.0, escape-string-regexp@1.0.2, has-ansi@0.1.0, strip-ansi@0.3.0)

grunt-usemin@3.0.0 node_modules\grunt-usemin
├── debug@2.1.1 (ms@0.6.2)
└── chalk@0.5.1 (ansi-styles@1.1.0, supports-color@0.2.0, strip-ansi@0.3.0, escape-string-regexp@1.0.2, has-ansi@0.1.0)

grunt-build-control@0.2.2 node_modules\grunt-build-control
└── shelljs@0.2.6

grunt-contrib-concat@0.5.0 node_modules\grunt-contrib-concat
├── source-map@0.1.43 (amdefine@0.1.0)
└── chalk@0.5.1 (ansi-styles@1.1.0, escape-string-regexp@1.0.2, supports-color@0.2.0, has-ansi@0.1.0, strip-ansi@0.3.0)

load-grunt-tasks@2.0.0 node_modules\load-grunt-tasks
├── multimatch@2.0.0 (array-differ@1.0.0, array-union@1.0.1, minimatch@2.0.1)
└── findup-sync@0.2.1 (glob@4.3.5)

grunt-contrib-copy@0.7.0 node_modules\grunt-contrib-copy
└── chalk@0.5.1 (supports-color@0.2.0, escape-string-regexp@1.0.2, ansi-styles@1.1.0, strip-ansi@0.3.0, has-ansi@0.1.0)

lodash@2.4.1 node_modules\lodash

grunt-contrib-watch@0.6.1 node_modules\grunt-contrib-watch
├── async@0.2.10
├── tiny-lr-fork@0.0.5 (debug@0.7.4, faye-websocket@0.4.4, noptify@0.0.3, qs@0.5.6)
└── gaze@0.5.1 (globule@0.1.0)

requirejs@2.1.15 node_modules\requirejs

karma-requirejs@0.2.2 node_modules\karma-requirejs

grunt-modernizr@0.6.0 node_modules\grunt-modernizr
├── colors@0.6.2
├── promised-io@0.3.4
├── uglify-js@1.3.3
└── request@2.27.0 (json-stringify-safe@5.0.0, forever-agent@0.5.2, aws-sign@0.3.0, qs@0.6.6, tunnel-agent@0.3.0, oauth-sign@0.3.0, cookie-jar@0.3.0, mime@1.2.11, node-uuid@1.4.2, form-data@0.1.4, http-signature@0.10.1, hawk@1.0.0)

karma-phantomjs-launcher@0.1.4 node_modules\karma-phantomjs-launcher
└── phantomjs@1.9.15 (which@1.0.8, progress@1.1.8, kew@0.4.0, request-progress@0.3.1, fs-extra@0.16.3, adm-zip@0.4.4, npmconf@2.0.9, request@2.42.0)

grunt-contrib-htmlmin@0.3.0 node_modules\grunt-contrib-htmlmin
├── pretty-bytes@0.1.2
├── chalk@0.4.0 (has-color@0.1.7, ansi-styles@1.0.0, strip-ansi@0.1.1)
└── html-minifier@0.6.9 (relateurl@0.2.6, change-case@2.1.6, clean-css@2.2.23, cli@0.6.5, uglify-js@2.4.16)

grunt-connect-proxy@0.1.10 node_modules\grunt-connect-proxy
├── lodash@0.9.2
└── http-proxy@0.10.4 (colors@0.6.2, pkginfo@0.3.0, optimist@0.6.1, utile@0.2.1)

grunt-angular-templates@0.5.7 node_modules\grunt-angular-templates
└── html-minifier@0.6.9 (relateurl@0.2.6, change-case@2.1.6, clean-css@2.2.23, cli@0.6.5, uglify-js@2.4.16)

grunt-contrib-connect@0.9.0 node_modules\grunt-contrib-connect
├── connect-livereload@0.5.2
├── opn@1.0.1
├── async@0.9.0
├── portscanner@1.0.0 (async@0.1.15)
└── connect@2.28.3 (utils-merge@1.0.0, cookie@0.1.2, fresh@0.2.4, pause@0.0.1, cookie-signature@1.0.5, response-time@2.2.0, vhost@3.0.0, basic-auth-connect@1.0.0, on-headers@1.0.0, bytes@1.0.0, media-typer@0.3.0, parseurl@1.3.0, cookie-parser@1.3.3, depd@1.0.0, qs@2.3.3, connect-timeout@1.5.0, http-errors@1.2.8, method-override@2.3.1, debug@2.1.1, finalhandler@0.3.3, express-session@1.10.2, csurf@1.6.6, type-is@1.5.6, serve-favicon@2.2.0, morgan@1.5.1, serve-static@1.8.1, body-parser@1.10.2, multiparty@3.3.2, compression@1.3.1, serve-index@1.6.1, errorhandler@1.3.3)

grunt-svgmin@2.0.0 node_modules\grunt-svgmin
├── log-symbols@1.0.1
├── pretty-bytes@1.0.2 (get-stdin@1.0.0)
├── each-async@1.1.1 (onetime@1.0.0, set-immediate-shim@1.0.0)
├── chalk@0.5.1 (escape-string-regexp@1.0.2, ansi-styles@1.1.0, supports-color@0.2.0, has-ansi@0.1.0, strip-ansi@0.3.0)
└── svgo@0.5.0 (whet.extend@0.9.9, colors@1.0.3, coa@0.4.1, sax@0.6.1, js-yaml@3.2.5)

wiredep@2.2.2 node_modules\wiredep
├── propprop@0.3.0
├── minimist@1.1.0
├── through2@0.6.3 (xtend@4.0.0, readable-stream@1.0.33)
├── chalk@0.5.1 (escape-string-regexp@1.0.2, supports-color@0.2.0, ansi-styles@1.1.0, strip-ansi@0.3.0, has-ansi@0.1.0)
├── glob@4.3.5 (inherits@2.0.1, once@1.3.1, inflight@1.0.4, minimatch@2.0.1)
└── bower-config@0.5.2 (osenv@0.0.3, graceful-fs@2.0.3, optimist@0.6.1, mout@0.9.1)

grunt@0.4.5 node_modules\grunt
├── dateformat@1.0.2-1.2.3
├── which@1.0.8
├── getobject@0.1.0
├── eventemitter2@0.4.14
├── rimraf@2.2.8
├── colors@0.6.2
├── async@0.1.22
├── grunt-legacy-util@0.2.0
├── hooker@0.2.3
├── nopt@1.0.10 (abbrev@1.0.5)
├── exit@0.1.2
├── glob@3.1.21 (inherits@1.0.0, graceful-fs@1.2.3)
├── minimatch@0.2.14 (sigmund@1.0.0, lru-cache@2.5.0)
├── coffee-script@1.3.3
├── underscore.string@2.2.1
├── lodash@0.9.2
├── iconv-lite@0.2.11
├── js-yaml@2.0.5 (argparse@0.1.16, esprima@1.0.4)
├── grunt-legacy-log@0.1.1 (underscore.string@2.3.3, lodash@2.4.1)
└── findup-sync@0.1.3 (glob@3.2.11, lodash@2.4.1)

grunt-contrib-jshint@0.10.0 node_modules\grunt-contrib-jshint
├── hooker@0.2.3
└── jshint@2.5.11 (strip-json-comments@1.0.2, underscore@1.6.0, exit@0.1.2, console-browserify@1.1.0, minimatch@1.0.0, shelljs@0.3.0, cli@0.6.5, htmlparser2@3.8.2)

xml2js@0.4.4 node_modules\xml2js
├── sax@0.6.1
└── xmlbuilder@2.4.6 (lodash-node@2.4.1)

grunt-contrib-cssmin@0.11.0 node_modules\grunt-contrib-cssmin
├── chalk@0.5.1 (ansi-styles@1.1.0, escape-string-regexp@1.0.2, strip-ansi@0.3.0, supports-color@0.2.0, has-ansi@0.1.0)
├── clean-css@3.0.8 (commander@2.5.1, source-map@0.1.43)
└── maxmin@1.0.0 (figures@1.3.5, pretty-bytes@1.0.2, gzip-size@1.0.0)

jasmine-core@2.1.3 node_modules\jasmine-core

karma-jasmine@0.3.5 node_modules\karma-jasmine

grunt-ng-annotate@0.9.2 node_modules\grunt-ng-annotate
└── ng-annotate@0.15.4 (tryor@0.1.2, alter@0.2.0, simple-fmt@0.1.0, simple-is@0.2.0, stringset@0.2.1, stringmap@0.2.2, stable@0.1.5, convert-source-map@0.4.1, ordered-ast-traverse@1.1.1, source-map@0.1.43, optimist@0.6.1, acorn@0.11.0)

grunt-contrib-uglify@0.7.0 node_modules\grunt-contrib-uglify
├── uri-path@0.0.2
├── chalk@0.5.1 (escape-string-regexp@1.0.2, supports-color@0.2.0, ansi-styles@1.1.0, has-ansi@0.1.0, strip-ansi@0.3.0)
├── uglify-js@2.4.16 (uglify-to-browserify@1.0.2, async@0.2.10, optimist@0.3.7, source-map@0.1.34)
└── maxmin@1.0.0 (figures@1.3.5, pretty-bytes@1.0.2, gzip-size@1.0.0)

grunt-autoprefixer@2.2.0 node_modules\grunt-autoprefixer
├── diff@1.2.2
├── chalk@0.5.1 (ansi-styles@1.1.0, escape-string-regexp@1.0.2, supports-color@0.2.0, has-ansi@0.1.0, strip-ansi@0.3.0)
└── autoprefixer-core@5.1.1 (num2fraction@1.0.1, browserslist@0.2.0, postcss@4.0.3, caniuse-db@1.0.30000062)

bower@1.3.12 node_modules\bower
├── is-root@1.0.0
├── junk@1.0.0
├── stringify-object@1.0.0
├── abbrev@1.0.5
├── chmodr@0.1.0
├── which@1.0.8
├── osenv@0.1.0
├── archy@0.0.2
├── opn@1.0.1
├── bower-logger@0.2.2
├── bower-endpoint-parser@0.2.2
├── lockfile@1.0.0
├── nopt@3.0.1
├── retry@0.6.0
├── tmp@0.0.23
├── request-progress@0.3.0 (throttleit@0.0.2)
├── q@1.0.1
├── lru-cache@2.5.0
├── shell-quote@1.4.2 (array-filter@0.0.1, array-map@0.0.0, array-reduce@0.0.0, jsonify@0.0.0)
├── chalk@0.5.0 (escape-string-regexp@1.0.2, ansi-styles@1.1.0, supports-color@0.2.0, has-ansi@0.1.0, strip-ansi@0.3.0)
├── semver@2.3.2
├── bower-json@0.4.0 (intersect@0.0.3, deep-extend@0.2.11, graceful-fs@2.0.3)
├── p-throttler@0.1.0 (q@0.9.7)
├── promptly@0.2.0 (read@1.0.5)
├── bower-config@0.5.2 (osenv@0.0.3, graceful-fs@2.0.3, optimist@0.6.1)
├── rimraf@2.2.8
├── graceful-fs@3.0.5
├── fstream@1.0.4 (inherits@2.0.1)
├── fstream-ignore@1.0.2 (inherits@2.0.1, minimatch@2.0.1)
├── decompress-zip@0.0.8 (mkpath@0.1.0, nopt@2.2.1, touch@0.0.2, readable-stream@1.1.13, binary@0.3.0)
├── glob@4.0.6 (inherits@2.0.1, once@1.3.1, minimatch@1.0.0)
├── mkdirp@0.5.0 (minimist@0.0.8)
├── request@2.42.0 (caseless@0.6.0, json-stringify-safe@5.0.0, aws-sign2@0.5.0, forever-agent@0.5.2, oauth-sign@0.4.0, stringstream@0.0.4, tunnel-agent@0.4.0, qs@1.2.2, mime-types@1.0.2, node-uuid@1.4.2, form-data@0.1.4, http-signature@0.10.1, hawk@1.1.1, tough-cookie@0.12.1, bl@0.9.4)
├── cardinal@0.4.0 (redeyed@0.4.4)
├── bower-registry-client@0.2.3 (graceful-fs@2.0.3, request-replay@0.2.0, lru-cache@2.3.1, mkdirp@0.3.5, async@0.2.10, request@2.51.0)
├── mout@0.9.1
├── tar-fs@0.5.2 (pump@0.3.5, tar-stream@0.4.7)
├── handlebars@2.0.0 (optimist@0.3.7, uglify-js@2.3.6)
├── inquirer@0.7.1 (figures@1.3.5, through@2.3.6, mute-stream@0.0.4, readline2@0.1.1, cli-color@0.3.2, rx@2.3.24)
├── update-notifier@0.2.0 (semver-diff@0.1.0, string-length@0.1.2, latest-version@0.2.0, configstore@0.3.2)
└── insight@0.4.3 (object-assign@1.0.0, async@0.9.0, chalk@0.5.1, lodash.debounce@2.4.1, tough-cookie@0.12.1, configstore@0.3.2, os-name@1.0.3, inquirer@0.6.0)

karma@0.12.31 node_modules\karma
├── di@0.0.1
├── rimraf@2.2.8
├── graceful-fs@2.0.3
├── mime@1.2.11
├── colors@0.6.2
├── q@0.9.7
├── minimatch@0.2.14 (sigmund@1.0.0, lru-cache@2.5.0)
├── optimist@0.6.1 (wordwrap@0.0.2, minimist@0.0.10)
├── source-map@0.1.43 (amdefine@0.1.0)
├── chokidar@1.0.0-rc3 (async-each@0.1.6, is-binary-path@1.0.0, glob-parent@1.0.0, anymatch@1.1.0, readdirp@1.3.0)
├── glob@3.2.11 (inherits@2.0.1, minimatch@0.3.0)
├── log4js@0.6.22 (semver@1.1.4, async@0.2.10, readable-stream@1.0.33)
├── http-proxy@0.10.4 (pkginfo@0.3.0, utile@0.2.1)
├── useragent@2.0.10 (lru-cache@2.2.4)
├── connect@2.26.6 (cookie@0.1.2, fresh@0.2.4, pause@0.0.1, cookie-signature@1.0.5, response-time@2.0.1, vhost@3.0.0, bytes@1.0.0, basic-auth-connect@1.0.0, on-headers@1.0.0, media-typer@0.3.0, parseurl@1.3.0, cookie-parser@1.3.3, depd@0.4.5, connect-timeout@1.3.0, method-override@2.2.0, qs@2.2.4, finalhandler@0.2.0, debug@2.0.0, morgan@1.3.2, csurf@1.6.6, express-session@1.8.2, serve-static@1.6.4, serve-favicon@2.1.7, body-parser@1.8.4, multiparty@3.3.2, type-is@1.5.6, serve-index@1.2.1, compression@1.1.2, errorhandler@1.2.4)
└── socket.io@0.9.16 (base64id@0.1.0, policyfile@0.0.4, redis@0.7.3, socket.io-client@0.9.16)

grunt-contrib-imagemin@0.9.2 node_modules\grunt-contrib-imagemin
├── async@0.9.0
├── pretty-bytes@1.0.2 (get-stdin@1.0.0)
├── chalk@0.5.1 (escape-string-regexp@1.0.2, ansi-styles@1.1.0, supports-color@0.2.0, strip-ansi@0.3.0, has-ansi@0.1.0)
└── imagemin@3.1.0 (get-stdin@3.0.2, optional@0.1.2, stream-combiner@0.2.1, vinyl@0.4.6, through2@0.6.3, meow@2.1.0, concat-stream@1.4.7, vinyl-fs@0.3.13, imagemin-svgo@4.0.2, imagemin-pngquant@4.0.0, imagemin-jpegtran@4.0.0, imagemin-optipng@4.2.0, imagemin-gifsicle@4.1.0)

yo@1.3.3 node_modules\yo
├── is-root@1.0.0
├── sudo-block@1.1.0
├── fullname@1.0.0
├── opn@1.0.1
├── async@0.9.0
├── string-length@1.0.0 (strip-ansi@2.0.1)
├── chalk@0.5.1 (escape-string-regexp@1.0.2, ansi-styles@1.1.0, supports-color@0.2.0, strip-ansi@0.3.0, has-ansi@0.1.0)
├── underscore.string@2.4.0
├── yeoman-character@1.0.1 (supports-color@1.2.0)
├── shelljs@0.3.0
├── nopt@3.0.1 (abbrev@1.0.5)
├── findup@0.1.5 (commander@2.1.0, colors@0.6.2)
├── yosay@1.0.2 (ansi-regex@1.1.0, ansi-styles@2.0.0, strip-ansi@2.0.1, pad-component@0.0.1, word-wrap@1.0.0, minimist@1.1.0, taketalk@1.0.0)
├── multiline@1.0.2 (strip-indent@1.0.0)
├── update-notifier@0.2.2 (is-npm@1.0.0, semver-diff@2.0.0, latest-version@1.0.0)
├── configstore@0.3.2 (object-assign@2.0.0, xdg-basedir@1.0.1, user-home@1.1.1, osenv@0.1.0, graceful-fs@3.0.5, uuid@2.0.1, mkdirp@0.5.0, js-yaml@3.2.5)
├── yeoman-doctor@1.3.1 (log-symbols@1.0.1, object-values@1.0.0, user-home@1.1.1, each-async@1.1.1, twig@0.7.2)
├── insight@0.4.3 (object-assign@1.0.0, os-name@1.0.3, tough-cookie@0.12.1, lodash.debounce@2.4.1, request@2.52.0, inquirer@0.6.0)
├── yeoman-environment@1.2.1 (log-symbols@1.0.1, diff@1.2.2, untildify@1.0.0, text-table@0.2.0, grouped-queue@0.3.0, debug@2.1.1, globby@1.1.0, mem-fs@1.0.1, inquirer@0.8.0)
└── yeoman-generator@0.17.7 (dargs@2.1.0, diff@1.2.2, class-extend@0.1.1, rimraf@2.2.8, text-table@0.2.0, mime@1.2.11, isbinaryfile@2.0.3, debug@1.0.4, grouped-queue@0.3.0, cross-spawn@0.2.3, mkdirp@0.5.0, run-async@0.1.0, iconv-lite@0.4.6, glob@4.3.5, github-username@1.1.1, findup-sync@0.1.3, file-utils@0.2.1, cheerio@0.17.0, request@2.52.0, download@1.0.7, gruntfile-editor@0.2.0, inquirer@0.7.3)

generator-jhipster@2.1.1 node_modules\generator-jhipster
├── shelljs@0.3.0
├── chalk@0.5.1 (escape-string-regexp@1.0.2, ansi-styles@1.1.0, supports-color@0.2.0, strip-ansi@0.3.0, has-ansi@0.1.0)
├── underscore.string@2.3.3
├── cheerio@0.17.0 (dom-serializer@0.0.1, entities@1.1.1, htmlparser2@3.7.3, CSSselect@0.4.1)
├── insight@0.4.3 (object-assign@1.0.0, async@0.9.0, lodash.debounce@2.4.1, os-name@1.0.3, tough-cookie@0.12.1, configstore@0.3.2, request@2.52.0, inquirer@0.6.0)
└── yeoman-generator@0.17.7 (dargs@2.1.0, diff@1.2.2, class-extend@0.1.1, rimraf@2.2.8, text-table@0.2.0, mime@1.2.11, async@0.9.0, isbinaryfile@2.0.3, grouped-queue@0.3.0, run-async@0.1.0, cross-spawn@0.2.3, nopt@3.0.1, debug@1.0.4, mkdirp@0.5.0, iconv-lite@0.4.6, findup-sync@0.1.3, github-username@1.1.1, glob@4.3.5, file-utils@0.2.1, request@2.52.0, gruntfile-editor@0.2.0, download@1.0.7, inquirer@0.7.3)
Running "ngconstant:dev" (ngconstant) task
Creating module jhipsterApp at src/main/webapp/scripts/app/app.constants.js...OK

Running "wiredep:app" (wiredep) task

Running "wiredep:test" (wiredep) task

Done, without errors.


Execution Time (2015-02-02 07:36:01 UTC)
loading tasks    31ms  ██████████████████████████ 13%
ngconstant:dev   14ms  ████████████ 6%
wiredep:app     174ms  ██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████ 71%
wiredep:test     26ms  ██████████████████████ 11%
Total 246ms
```

**Comment by andidev** [comment]
@atomfrede 
The first line seems to hint that it is a karma dependency that causes this error. 

A Google search results in the following issue reported in the karma project. We are not the only ones with this problem. 

I have no time looking into it more right now but as some mentioned in that issue it seems that karma falls back on javascript if the native bindings fails.
