### ISSUE TITLE
Initial schema creation fails with Oracle 18c XE

### ISSUE THREAD

**Issue by pmverma** [jhipster/generator-jhipster#10726]
##### **Overview of the issue**

Initial schema creation fails when the Oracle DB (at least for 18c XE) is used.

```
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'liquibase' defined in class path resource [com/mycompany/myapp/config/LiquibaseConfiguration.class]: Invocation of init method failed; nested exception is liquibase.exception.MigrationFailedException: Migration failed for change set config/liquibase/changelog/00000000000000_initial_schema.xml::00000000000001::jhipster:
     Reason: java.lang.NullPointerException
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1778)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:593)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:515)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:307)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveReference(BeanDefinitionValueResolver.java:303)
	... 98 common frames omitted
Caused by: liquibase.exception.MigrationFailedException: Migration failed for change set config/liquibase/changelog/00000000000000_initial_schema.xml::00000000000001::jhipster:
     Reason: java.lang.NullPointerException
	at liquibase.changelog.ChangeSet.execute(ChangeSet.java:637)
	at liquibase.changelog.visitor.UpdateVisitor.visit(UpdateVisitor.java:53)
	at liquibase.changelog.ChangeLogIterator.run(ChangeLogIterator.java:83)
	at liquibase.Liquibase.update(Liquibase.java:202)
	at liquibase.Liquibase.update(Liquibase.java:179)
	at liquibase.integration.spring.SpringLiquibase.performUpdate(SpringLiquibase.java:353)
	at liquibase.integration.spring.SpringLiquibase.afterPropertiesSet(SpringLiquibase.java:305)
	at org.springframework.boot.autoconfigure.liquibase.DataSourceClosingSpringLiquibase.afterPropertiesSet(DataSourceClosingSpringLiquibase.java:46)
	at io.github.jhipster.config.liquibase.AsyncSpringLiquibase.initDb(AsyncSpringLiquibase.java:118)
	at io.github.jhipster.config.liquibase.AsyncSpringLiquibase.afterPropertiesSet(AsyncSpringLiquibase.java:103)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1837)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1774)
	... 107 common frames omitted
Caused by: java.lang.NullPointerException: null
	at liquibase.change.core.LoadDataChange.retrieveMissingColumnLoadTypes(LoadDataChange.java:628)
	at liquibase.change.core.LoadDataChange.generateStatements(LoadDataChange.java:283)
	at liquibase.database.AbstractJdbcDatabase.executeStatements(AbstractJdbcDatabase.java:1209)
	at liquibase.changelog.ChangeSet.execute(ChangeSet.java:600)
	... 118 common frames omitted
```

##### **Motivation for or Use Case**

A fresh app must starts normally.

##### **Reproduce the error**

- Generate a fresh new app selecting Oracle
- Start the app and it will fail

##### **Suggest a Fix**

Add column definition inside `loadData` tag.
Fix from sample app https://github.com/pmverma/jhipster-hypersistence-oracle/commit/2b2dafe5bc5451f7503e7757ed17c9f9940edf6d
This will fix for Oracle, however, I have not tested for other DBs by adding column definition.

##### **JHipster Version(s)**

```
jhipster@0.0.0 /Users/sierra/github/temp/jh-ho-oracle
└── generator-jhipster@6.4.1 

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "enableHibernateCache": true,
    "enableSwaggerCodegen": false,
    "enableTranslation": false,
    "jhiPrefix": "jhi",
    "languages": [
      "en",
      "fr"
    ],
    "messageBroker": false,
    "nativeLanguage": "en",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "prodDatabaseType": "oracle",
    "searchEngine": false,
    "serviceDiscoveryType": false,
    "skipClient": true,
    "skipServer": false,
    "testFrameworks": [],
    "websocket": false,
    "applicationType": "monolith",
    "baseName": "jhipster",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "ehcache",
    "buildTool": "maven",
    "useSass": true,
    "jhipsterVersion": "6.4.1",
    "skipUserManagement": false,
    "clientPackageManager": "npm",
    "clientFramework": "angularX",
    "clientTheme": "none",
    "clientThemeVariant": "",
    "jwtSecretKey": "bXktc2VjcmV0LXRva2VuLXRvLWNoYW5nZS1pbi1wcm9kdWN0aW9uLWFuZC10by1rZWVwLWluLWEtc2VjdXJlLXBsYWNl",
    "embeddableLaunchScript": false,
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [],
    "blueprints": []
  },
  "entities": [
    "EFive",
    "EFour",
    "EOne",
    "ESix",
    "EThree",
    "ETwo"
  ]
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity EFive {
  five String required
}
entity EFour {
  four AnyBlob required
}
entity EOne {
  one String required unique
}
entity ESix {
  six String required
}
entity EThree {
  three Instant required
}
entity ETwo {
  two Integer required
}
relationship OneToOne {
  ESix{user} to User with useJPADerivedIdentifier,
  EThree{user} to User
}
relationship OneToMany {
  EOne{eTwoO required} to ETwo{eOne required}
}
relationship ManyToOne {
  ETwo{eTwoT} to EOne
}
relationship ManyToMany {
  EFour{eFive} to EFive{eFour}
}

paginate EFive with pagination
paginate EOne with infinite-scroll
paginate ETwo with pager
service EFive, EFour, EOne, ESix, EThree, ETwo with serviceImpl
dto EThree with mapstruct

</pre>
</details>

##### **Environment and Tools**

openjdk version "1.8.0_222"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_222-b10)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.222-b10, mixed mode)

git version 2.20.1 (Apple Git-117)

node: v10.14.2

npm: 6.11.2

yeoman: 3.1.0

Docker version 19.03.2, build 6a30dfc

docker-compose version 1.24.1, build 4667896b

##### **Browsers and Operating System**

-   [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by pascalgrimaud** [comment]
@pmverma : as there is few user using Oracle, I think you're the only one can fix it.
Maybe apply your fix only for Oracle, so it won't impact the other DB ?

**Comment by pmverma** [comment]
I will do a PR.
I think it should not impact other DBs.

**Comment by pascalgrimaud** [comment]
Adding a bounty as it's a bug

**Comment by pmverma** [comment]
Bounty claimed https://opencollective.com/generator-jhipster/expenses/14056
