### ISSUE TITLE
Protractor with entity serviceClass + Pagination + DTO

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/generator-jhipster#10806]
##### **Overview of the issue**

Current builds failed during e2e tests.
Here an extract of logs:

```
  EntityWithServiceClassPaginationAndDTO e2e test
    1) should load EntityWithServiceClassPaginationAndDTOS
    2) should load create EntityWithServiceClassPaginationAndDTO page
    3) should create and save EntityWithServiceClassPaginationAndDTOS
    4) should delete last EntityWithServiceClassPaginationAndDTO
```

```
  150 passing (3m)
  4 failing
  1) EntityWithServiceClassPaginationAndDTO e2e test
       should load EntityWithServiceClassPaginationAndDTOS:
     TimeoutError: Wait timed out after 5000ms
      at /home/travis/app/node_modules/selenium-webdriver/lib/promise.js:2201:17
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:93:5)
  2) EntityWithServiceClassPaginationAndDTO e2e test
       should load create EntityWithServiceClassPaginationAndDTO page:
     NoSuchElementError: No element found using locator: By(css selector, *[id="jh-create-entity"])
      at /home/travis/app/node_modules/protractor/built/element.js:814:27
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:93:5)Error
      at ElementArrayFinder.applyAction_ (node_modules/protractor/built/element.js:459:27)
      at ElementArrayFinder.<computed> [as click] (node_modules/protractor/built/element.js:91:29)
      at ElementFinder.<computed> [as click] (node_modules/protractor/built/element.js:831:22)
      at EntityWithServiceClassPaginationAndDTOComponentsPage.<anonymous> (src/test/javascript/e2e/entities/entity-with-service-class-pagination-and-dto/entity-with-service-class-pagination-and-dto.page-object.ts:13:37)
      at Generator.next (<anonymous>)
      at /home/travis/app/node_modules/tslib/tslib.js:110:75
      at new Promise (<anonymous>)
      at Object.__awaiter (node_modules/tslib/tslib.js:106:16)
      at EntityWithServiceClassPaginationAndDTOComponentsPage.clickOnCreateButton (src/test/javascript/e2e/entities/entity-with-service-class-pagination-and-dto/entity-with-service-class-pagination-and-dto.page-object.ts:12:24)
      at Object.<anonymous> (src/test/javascript/e2e/entities/entity-with-service-class-pagination-and-dto/entity-with-service-class-pagination-and-dto.spec.ts:28:68)
  3) EntityWithServiceClassPaginationAndDTO e2e test
       should create and save EntityWithServiceClassPaginationAndDTOS:
     NoSuchElementError: No element found using locator: By(css selector, *[id="jh-create-entity"])
      at /home/travis/app/node_modules/protractor/built/element.js:814:27
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:93:5)Error
      at ElementArrayFinder.applyAction_ (node_modules/protractor/built/element.js:459:27)
      at ElementArrayFinder.<computed> [as click] (node_modules/protractor/built/element.js:91:29)
      at ElementFinder.<computed> [as click] (node_modules/protractor/built/element.js:831:22)
      at EntityWithServiceClassPaginationAndDTOComponentsPage.<anonymous> (src/test/javascript/e2e/entities/entity-with-service-class-pagination-and-dto/entity-with-service-class-pagination-and-dto.page-object.ts:13:37)
      at Generator.next (<anonymous>)
      at /home/travis/app/node_modules/tslib/tslib.js:110:75
      at new Promise (<anonymous>)
      at Object.__awaiter (node_modules/tslib/tslib.js:106:16)
      at EntityWithServiceClassPaginationAndDTOComponentsPage.clickOnCreateButton (src/test/javascript/e2e/entities/entity-with-service-class-pagination-and-dto/entity-with-service-class-pagination-and-dto.page-object.ts:12:24)
      at Object.<anonymous> (src/test/javascript/e2e/entities/entity-with-service-class-pagination-and-dto/entity-with-service-class-pagination-and-dto.spec.ts:35:68)
  4) EntityWithServiceClassPaginationAndDTO e2e test
       should delete last EntityWithServiceClassPaginationAndDTO:
     NoSuchElementError: Index out of bound. Trying to access element at index: -1, but there are only 0 elements that match locator By(css selector, jhi-entity-with-service-class-pagination-and-dto div table .btn-danger)
      at /home/travis/app/node_modules/protractor/built/element.js:274:27
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:93:5)Error
      at ElementArrayFinder.applyAction_ (node_modules/protractor/built/element.js:459:27)
      at ElementArrayFinder.<computed> [as click] (node_modules/protractor/built/element.js:91:29)
      at ElementFinder.<computed> [as click] (node_modules/protractor/built/element.js:831:22)
      at EntityWithServiceClassPaginationAndDTOComponentsPage.<anonymous> (src/test/javascript/e2e/entities/entity-with-service-class-pagination-and-dto/entity-with-service-class-pagination-and-dto.page-object.ts:18:45)
      at Generator.next (<anonymous>)
      at /home/travis/app/node_modules/tslib/tslib.js:110:75
      at new Promise (<anonymous>)
      at Object.__awaiter (node_modules/tslib/tslib.js:106:16)
      at EntityWithServiceClassPaginationAndDTOComponentsPage.clickOnLastDeleteButton (src/test/javascript/e2e/entities/entity-with-service-class-pagination-and-dto/entity-with-service-class-pagination-and-dto.page-object.ts:17:24)
      at Object.<anonymous> (src/test/javascript/e2e/entities/entity-with-service-class-pagination-and-dto/entity-with-service-class-pagination-and-dto.spec.ts:45:68)
```

##### **Motivation for or Use Case**

Fix the build

##### **Reproduce the error**

Here the full logs:
https://travis-ci.org/jhipster/generator-jhipster/jobs/614243881

**Comment by MathieuAA** [comment]
Maybe [this](https://github.com/angular/protractor/blob/master/docs/timeouts.md) can help us understand

**Comment by SudharakaP** [comment]
I can take a look at this today evening if someone isn't already looking at it. 😄

**Comment by pascalgrimaud** [comment]
@SudharakaP : I don't think it's related to timeout. I believe there is a real issue here but I didn't manage to reproduce locally.
I already restart the build 6 or 7 times and it always failed for EntityWithServiceClassPaginationAndDTO

**Comment by SudharakaP** [comment]
@pascalgrimaud : Agreed. I am trying to find that root cause currently :thinking:

**Comment by SudharakaP** [comment]
@kaidohallik : Wonderful, thanks! That fixed it :smile:

**Comment by kaidohallik** [comment]
As better fix https://github.com/jhipster/generator-jhipster/pull/10820 is also merged then I'm claiming bounty: https://opencollective.com/generator-jhipster/expenses/12569

And seems that this is already approved before I could add this comment :)

**Comment by pascalgrimaud** [comment]
yes, I approuved it, as I know your email :)
