### ISSUE TITLE
Unable to generate Entities with ManyToMany relationship

### ISSUE THREAD

**Issue by skmaingi** [jhipster/generator-jhipster#10978]
##### **Overview of the issue**

Unable to generate entities with ManyToMany relationships after upgrading JHipster

##### **Motivation for or Use Case**

When I try to generate entities with ManyToMany relationship using JHipster version 6.5.1, I get an error "Can't add invalid relationship ... only bidirectionality is supported".
JHipster version 6.4.1 can generate entities without issues.

##### **Reproduce the error**

1. Install latest JHipster generator: _npm install -g generator-jhipster_
2. Create JDL file with ManyToMany relationship
3. Run _jhipster import-jdl ./jdl/jhipster-jdl.jh_

Error:

INFO! Using JHipster version installed locally in current project's node_modules
INFO! Executing import-jdl ./jdl/jhipster-jdl.jh
INFO! Options: from-cli: true, inline: 
INFO! Found .yo-rc.json on path. This is an existing app
INFO! The JDL is being parsed.
warn: In the One-to-Many relationship from ItemF to ItemG, only bidirectionality is supported for a One-to-Many association. The other side will be automatically added.
Error: Can't add invalid relationship. Error: In the Many-to-Many relationship from Set to ItemA, only bidirectionality is supported. The injected field in the source entity is 'itemA' and the injected field in the destination entity is not set.
Error while parsing applications and entities from the JDL Error: Can't add invalid relationship. Error: In the Many-to-Many relationship from Set to ItemA, only bidirectionality is supported. The injected field in the source entity is 'itemA' and the injected field in the destination entity is not set.
Error: Can't add invalid relationship. Error: In the Many-to-Many relationship from Set to ItemA, only bidirectionality is supported. The injected field in the source entity is 'itemA' and the injected field in the destination entity is not set.
    at ValidatedJDLObject.addRelationship (/home/ubuntu/ProjectA/node_modules/jhipster-core/lib/core/validated_jdl_object.js:102:13)
    at fillAssociations (/home/ubuntu/ProjectA/node_modules/jhipster-core/lib/parsers/document_parser.js:289:15)
    at Object.parseFromConfigurationObject (/home/ubuntu/ProjectA/node_modules/jhipster-core/lib/parsers/document_parser.js:67:3)
    at getJDLObject (/home/ubuntu/ProjectA/node_modules/jhipster-core/lib/jdl/jdl_importer.js:110:25)
    at Object.import (/home/ubuntu/ProjectA/node_modules/jhipster-core/lib/jdl/jdl_importer.js:88:25)
    at JDLProcessor.importJDL (/home/ubuntu/ProjectA/node_modules/generator-jhipster/cli/import-jdl.js:70:41)
    at JDLProcessor.importJDL (/home/ubuntu/ProjectA/node_modules/generator-jhipster/cli/import-jdl.js:298:38)
    at module.exports (/home/ubuntu/ProjectA/node_modules/generator-jhipster/cli/import-jdl.js:465:21)
    at Command.command.allowUnknownOption.description.action.args (/home/ubuntu/ProjectA/node_modules/generator-jhipster/cli/cli.js:71:36)
    at Command.listener (/home/ubuntu/ProjectA/node_modules/generator-jhipster/node_modules/commander/index.js:315:8)

##### **Suggest a Fix**

Use JHipster version 6.4.1

##### **JHipster Version(s)**

6.5.1

##### **JHipster configuration**

  <details>
  <summary>JDL definitions</summary>
  <pre>
     entity ItemF {
    name String required maxlength(100)
}
entity ItemG {
    name String required maxlength(30)
}
entity ItemA {
    name String required maxlength(100)
}
entity Set {
    name String required maxlength(100)
 }
relationship OneToMany {
	ItemF{itemG(name)} to ItemG
}
relationship ManyToMany {
	Set{itemA} to ItemA
}
paginate Set with infinite-scroll
service all with serviceImpl

  </pre>
  </details>

##### **Browsers and Operating System**

Ubuntu Xenial

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by skmaingi** [comment]
Fix:
Removed injected fields in source and destination entities
