### ISSUE TITLE
Import of JDL exported with the generator causes errors

### ISSUE THREAD

**Issue by poolebu** [jhipster/generator-jhipster#10970]
##### **Overview of the issue**
Error trying to import `jdl` file originally creating using: `jhipster export-jdl` which generated the file `app.jdl`. 

Here are 2 errors that I got among other similar ones, all related to the `application.config` section of the jdl. After a few of these, I just edited the `application.config` section manually to the original simpler version I used at the beginning of the project.

Error 1
```
poolebu@DESKTOP-ENCTN1G:~/lab/fasm/jhipster$ jhipster import-jdl app.jdl
INFO! Using JHipster version installed globally
INFO! Executing import-jdl app.jdl
INFO! Options: from-cli: true
INFO! The JDL is being parsed.
error: Error message:
        unexpected character: ->/<- at offset: 292, skipped 1 characters.
SyntaxError: Error: unexpected character: ->/<- at offset: 292, skipped 1 characters.
Error while parsing applications and entities from the JDL SyntaxError: Error: unexpected character: ->/<- at offset: 292, skipped 1 characters.
SyntaxError: Error: unexpected character: ->/<- at offset: 292, skipped 1 characters.
    at callApiMethod (/usr/lib/node_modules/generator-jhipster/node_modules/jhipster-core/lib/readers/jdl_reader.js:88:11)
    at parse (/usr/lib/node_modules/generator-jhipster/node_modules/jhipster-core/lib/readers/jdl_reader.js:72:10)
    at Object.parseFromFiles (/usr/lib/node_modules/generator-jhipster/node_modules/jhipster-core/lib/readers/jdl_reader.js:41:10)
    at parseFiles (/usr/lib/node_modules/generator-jhipster/node_modules/jhipster-core/lib/jdl/jdl_importer.js:82:20)
    at JDLImporter.import (/usr/lib/node_modules/generator-jhipster/node_modules/jhipster-core/lib/jdl/jdl_importer.js:64:30)
    at JDLProcessor.importJDL (/usr/lib/node_modules/generator-jhipster/cli/import-jdl.js:76:41)
    at JDLProcessor.importJDL (/usr/lib/node_modules/generator-jhipster/cli/import-jdl.js:296:38)
    at module.exports (/usr/lib/node_modules/generator-jhipster/cli/import-jdl.js:450:21)
    at Command.command.allowUnknownOption.description.action.args (/usr/lib/node_modules/generator-jhipster/cli/cli.js:72:36)
    at Command.listener (/usr/lib/node_modules/generator-jhipster/node_modules/commander/index.js:315:8)
```

Error 2, after deleting the `packageFolder es/fasm` line in the file, this one appeared:

```
SyntaxError: Error: MismatchedTokenException: Expecting --> '}' <-- but found --> '.' <--
        at line: 28, column: 22
Error while parsing applications and entities from the JDL SyntaxError: Error: MismatchedTokenException: Expecting --> '}' <-- but found --> '.' <--
        at line: 28, column: 22

```

##### **Motivation for or Use Case**

I needed to recreate a project because we needed to change the root folder which broke further use of the generator for all kinds of reasons, I suspect related to the `baseName` variable. 

##### **Reproduce the error**

Use jhipster `import-jdl app.jdl` with this generated file: 
[app.jdl.txt](https://github.com/jhipster/generator-jhipster/files/3971746/app.jdl.txt)

##### **JHipster Version(s)**

`"generator-jhipster": "6.5.1"`

##### **JHipster configuration**

```
Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
fasm@0.0.1-SNAPSHOT /mnt/c/Users/Usuario/Documents/GitHub/fasm/jhipster
└── generator-jhipster@6.5.1

```


##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**


<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "enableHibernateCache": true,
    "enableSwaggerCodegen": false,
    "enableTranslation": true,
    "jhiPrefix": "jhi",
    "languages": [
      "es",
      "en"
    ],
    "messageBroker": false,
    "nativeLanguage": "es",
    "packageName": "es.fasm",
    "packageFolder": "es/fasm",
    "prodDatabaseType": "mysql",
    "searchEngine": "elasticsearch",
    "serviceDiscoveryType": false,
    "skipClient": false,
    "skipServer": false,
    "testFrameworks": [],
    "websocket": false,
    "baseName": "fasm",
    "applicationType": "monolith",
    "authenticationType": "jwt",
    "cacheProvider": "ehcache",
    "buildTool": "maven",
    "clientFramework": "angularX",
    "serverPort": "8085",
    "skipUserManagement": false,
    "jhipsterVersion": "6.5.1",
    "clientPackageManager": "npm",
    "clientTheme": "none",
    "clientThemeVariant": "",
    "useSass": true,
    "jwtSecretKey": "XXXXXXXXXXXXXXXXXX",
    "embeddableLaunchScript": false,
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "blueprints": [],
    "otherModules": []
  },
  "entities": [
    "Actividad",
    "Agrupacion",
    "Area",
    "Asistencia",
    "Aula",
    "Beneficiario",
    "BusquedaDeBeneficiario",
    "CentroDeActividad",
    "Incidencia",
    "InstrumentoRol",
    "Locacion",
    "Objetivo",
    "Profile",
    "Seccion",
    "TipoDeActividad"
  ]
}
</pre>
</details>


##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
/**
 * not an ignored comment
 */
entity Actividad {
  nombre String required,
  estado EstadoActividad,
  descripcion TextBlob,
  fechaDeInicio Instant,
  fechaDeFin Instant
}
entity Agrupacion {
  nombre String required,
  descripcion TextBlob
}
entity Area {
  nombre String required,
  descripcion TextBlob
}
/**
 * Task entity.\n@author The Catwizard Team.\nPara registrar asistencias, y hacer reportes conjunto\nConjunto con busqueda de beneficiario
 */
entity Asistencia {
  asistencia Boolean required
}
entity Aula {
  nombre String required,
  descripcion String,
  capacidad String
}
entity Beneficiario {
  nombre String required,
  apellido String,
  fechaDeNacimiento Instant,
  fechaDeCreacion Instant,
  fechaDeUltimaActualizacion Instant required,
  foto ImageBlob,
  estado EstadoBeneficiario
}
/**
 * Task entity.\n@author The Catwizard Team.\nClase especial, usada como DTO para crear busqueda,\npero tambien como historicos para reportes tales como\n\nREPORTE  ASISTENCIA AGRUPACIÓN: Ejemplo 39% de asistencia\nen el mes de abril para la agrupacion camerata.\nPromedio de personas asistidas / promedio de participantes\n\nREPORTE  PARTICIPANTES AGRUPACIÓN: Ejemplo, 9 personas\nasistidas en el mes de abril para la agrupacion camerata.\nDicho de otra forma, cuantas personas han asistido al menos\na una clase en el mes de abril.
 */
entity BusquedaDeBeneficiario {
  centroNombre String,
  centroId Long,
  agrupacionNombre String,
  agrupacionId Long,
  seccionNombre String,
  seccionId Long,
  areaNombre String,
  areaId Long,
  nivelNombre String,
  nivelId Long,
  instrumentNombre String,
  instrumentId Long,
  /**
   * usado para calcular participantes y asistencia mensual
   */
  numberOfResults Long,
  groupQuery Boolean
}
entity CentroDeActividad {
  nombre String required,
  telefono String,
  nombreDeContacto String,
  emailDeContacto String
}
entity Incidencia {
  resumen String required,
  descripcion TextBlob,
  image ImageBlob,
  fecha Instant
}
entity InstrumentoRol {
  nombre String required,
  siglas String required
}
entity Locacion {
  nombre String,
  direccion String required,
  codigoPostal String,
  ciudad String,
  pais String
}
entity Objetivo {
  nombre String,
  descripcion String
}
/**
 * Task entity.\n@author The Catwizard Team.\n\nUSER ROLES notes\nADMIN,\nMAC, RESPONSABLE DE AGRUPACION, DIRECTOR DE CENTRO, COORDINADOR DE AREA\nDIRECTOR ARTISTICO
 */
entity Profile {
  nombre String required,
  apellido String,
  email String,
  telefono String
}
/**
 * Task entity.\n@author The Catwizard Team.\nEjemplos: Cuerdas, Percusion, Voces
 */
entity Seccion {
  nombre String required
}
entity TipoDeActividad {
  nombre String required,
  descripcion String,
  color String
}
enum EstadoActividad {
  Creando,
  Publicado,
  Pendiente,
  Cerrado,
  Borrado
}
enum EstadoBeneficiario {
  ACTIVO,
  INACTIVO,
  BORRADO
}

relationship OneToOne {
  CentroDeActividad{locacion(direccion)} to Locacion{centroDeActividad},
  Profile{user(login)} to User
}
relationship OneToMany {
  TipoDeActividad{actividad} to Actividad{tipoDeActividad(nombre)},
  Locacion{actividad} to Actividad{locacion(nombre)},
  Actividad{asistencia} to Asistencia{actividad(nombre)},
  Beneficiario{asistencia} to Asistencia{beneficiario(nombre)},
  CentroDeActividad{beneficiario} to Beneficiario{centroDeActividad(nombre)},
  Actividad{busquedaDeBeneficiario} to BusquedaDeBeneficiario{actividad},
  Actividad{incidencia} to Incidencia{actividad(nombre)},
  Actividad{objetivo} to Objetivo{actividad(nombre)},
  Area{seccion} to Seccion{area(nombre)}
}
relationship ManyToOne {
  Actividad{area(nombre)} to Area,
  Actividad{seccion(nombre)} to Seccion,
  Actividad{aula(nombre)} to Aula,
  Actividad{agrupacion(nombre)} to Agrupacion
}
relationship ManyToMany {
  Actividad{actividadProfile(nombre)} to Profile{profileActividad},
  Actividad{instrumentoRol(nombre)} to InstrumentoRol{actividad},
  Agrupacion{beneficiario(nombre)} to Beneficiario{agrupacion},
  Area{beneficiario(nombre)} to Beneficiario{area},
  Aula{centroDeActividad(nombre)} to CentroDeActividad{aula},
  Beneficiario{instrumentoRol(nombre)} to InstrumentoRol{beneficiario},
  Incidencia{beneficiario(nombre)} to Beneficiario{incidencia},
  InstrumentoRol{seccion(nombre)} to Seccion{instrumentoRol},
  Seccion{centroDeActividad(nombre)} to CentroDeActividad{seccion}
}

paginate Actividad, Asistencia, Beneficiario, BusquedaDeBeneficiario, Incidencia, Locacion, Profile with pagination
service Actividad, Agrupacion, Beneficiario, BusquedaDeBeneficiario, Profile with serviceClass
search Actividad, Beneficiario, BusquedaDeBeneficiario, Incidencia, Locacion, Profile with elasticsearch
filter Actividad

</pre>
</details>


##### **Environment and Tools**

openjdk version "1.8.0_222"
OpenJDK Runtime Environment (build 1.8.0_222-8u222-b10-1ubuntu1~18.04.1-b10)
OpenJDK 64-Bit Server VM (build 25.222-b10, mixed mode)

git version 2.17.1

node: v10.16.3

npm: 6.9.0

yeoman: 3.1.1

yarn: 1.17.3

Docker version 19.03.2, build 6a30dfc

docker-compose version 1.23.2, build 1110ad0
```
##### **Browsers and Operating System**

WSL Ubuntu 18.04.3 LTS/ windows 10

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by MathieuAA** [comment]
Hi, this is fixed in JCore, but not yet released.
See https://github.com/jhipster/jhipster-core/issues/411

**Comment by MathieuAA** [comment]
I'll release before the end of the week (most likely tomorrow or the day after if I find the time)
