### ISSUE TITLE
MapStruct annotation not generate the default Spring component

### ISSUE THREAD

**Issue by p4535992** [jhipster/generator-jhipster#11170]
##### **Overview of the issue**

```
org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'xxx.mapper.SegnalazioneMapper' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {}
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.raiseNoMatchingBeanFound(DefaultListableBeanFactory.java:1662)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1221)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1175)
	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:857)
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:760)
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:218)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1340)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1186)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:555)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:515)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:847)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:877)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:549)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:142)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:775)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:316)
	at xxx.main(XXXApp.java:82)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.devtools.restart.RestartLauncher.run(RestartLauncher.java:49)

2020-01-24 08:42:24.215 ERROR 4184 --- [  restartedMain] o.s.b.d.LoggingFailureAnalysisReporter   : 

***************************
APPLICATION FAILED TO START
***************************

Description:

Parameter 1 of constructor in xxx.service.impl.SegnalazioneServiceImpl required a bean of type 'xxx.mapper.SegnalazioneMapper' that could not be found.


Action:

Consider defining a bean of type 'xxx.mapper.SegnalazioneMapper' in your configuration.
```
##### **Motivation for or Use Case**

I create a simple jdl file where i put the line of code

```
// Use Data Transfert Objects (DTO)
dto * with mapstruct
```
because i want to generate all the mapper interface class java with Mapstruct annotation.

##### **Reproduce the error**

1) IMPORTANT i use Openjdk 1.8, Eclipse (version 2019-06) ide e maven

2) BEFORE EVERYTHING i know this is a recurring error asking already many times, and i have tried the suggestions like modification of the maven-compiler-plugin o installation of m2e-apt or mapstruct extension on eclipse, but the error still there.

3) Create a Jhipster project with the standard commands

4) import the following jdl with the command "jhipster import-jdl" on the same directory of the project.

```
entity Stato {
   name String required
}

entity Canale {
   name String required
}

entity Segnalazione {
    assegnatario String required
}

relationship OneToOne {
    Segnalazione{stato} to Stato,
    Segnalazione{canale} to Canale
}

paginate Segnalazione,Stato,Canale with pagination
paginate Segnalazione with infinite-scroll

service Stato with serviceClass
service Canale with serviceClass

// Use Data Transfert Objects (DTO)
dto * with mapstruct

// Set service options to all
service all with serviceImpl

// Set an angular suffix
angularSuffix * with xxx
```

3) After all the entity are created with succes try to start the spring boot application server and you should get the same error.

##### **Related issues**

https://github.com/jhipster/generator-jhipster/issues/6403
https://github.com/jhipster/generator-jhipster/issues/3268

##### **Suggest a Fix**

I fix the erorr by creating a explicit java class implementation for the mapstruct annotation for example:
This is generated from jhipster
```java
@Mapper(componentModel = "spring", uses = {}, unmappedTargetPolicy = ReportingPolicy.WARN)
public interface CanaleMapper extends EntityMapper<CanaleDTO, Canale> {
    default Canale fromId(Long id) {
        if (id == null) {
            return null;
        }
        Canale canale = new Canale();
        canale.setId(id);
        return canale;
    }
}
```

This is what i done for make spring boot found the implementation (very simple implementation).

```java
@Component
public class CanaleMapperImpl implements CanaleMapper{

	@Override
	public Canale toEntity(CanaleDTO dto) {
		Canale canale = new Canale();
		canale.setId(dto.getId());
		canale.setName(dto.getName());
		return canale;
	}

	@Override
	public CanaleDTO toDto(Canale entity) {
		CanaleDTO canaleDTO = new CanaleDTO();
		canaleDTO.setId(entity.getId());
		canaleDTO.setName(entity.getName());
		return canaleDTO;
	}

	@Override
	public List<Canale> toEntity(List<CanaleDTO> dtoList) {
		List<Canale> list = new ArrayList<Canale>();
		for(CanaleDTO dto: dtoList) {
			list.add(toEntity(dto));
		}
		return list;
	}

	@Override
	public List<CanaleDTO> toDto(List<Canale> entityList) {
		List<CanaleDTO> list = new ArrayList<CanaleDTO>();
		for(Canale entity: entityList) {
			list.add(toDto(entity));
		}
		return list;
	}

}
```
##### **JHipster Version(s)**

6.6.0

##### **JHipster Version(s)**

```
xxx@0.0.1-SNAPSHOT C:\ws-5.2.3\SPRINGBOOT\xxx
`-- generator-jhipster@6.6.0

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**
<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "applicationType": "monolith",
    "gitCompany": "",
    "baseName": "XXX",
    "packageName": "xxx",
    "packageFolder": "xxx/gateway",
    "serverPort": 8080,
    "serviceDiscoveryType": false,
    "authenticationType": "session",
    "uaaBaseName": "../uaa",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "postgresql",
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "enableSwaggerCodegen": "true",
    "messageBroker": false,
    "buildTool": "maven",
    "useSass": true,
    "clientPackageManager": "npm",
    "testFrameworks": [],
    "enableTranslation": true,
    "nativeLanguage": "it",
    "languages": ["en", "it"],
    "clientFramework": "angularX",
    "jhiPrefix": "jhi",
    "jhipsterVersion": "6.6.0",
    "rememberMeKey": "YourJWTSecretKeyWasReplacedByThisMeaninglessTextByTheJHipsterInfoCommandForObviousSecurityReasons",
    "embeddableLaunchScript": false,
    "clientTheme": "none",
    "creationTimestamp": 1579281582852,
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [],
    "blueprints": []
  }
}

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity Segnalazione {
  assegnatario String required
}
entity Stato {
  name String required
}
entity Canale {
  name String required
}
relationship OneToOne {
  Segnalazione{stato} to Stato,
  Segnalazione{canale} to Canale
}

dto Segnalazione, Stato, Canale with mapstruct
paginate Segnalazione with infinite-scroll
paginate Stato, Canale with pagination
service Segnalazione, Stato, Canale with serviceImpl
angularSuffix Segnalazione, Stato, Canale with xxx

</pre>
</details>

##### **Environment and Tools**

openjdk version "1.8.0_232"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_232-b09)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.232-b09, mixed mode)

git version 2.24.0.windows.2

node: v12.13.0

npm: 6.12.0

yeoman: 3.1.0

yarn: 1.3.2

##### **Browsers and Operating System**

S.O. Windows 10
It's not a browser realted problem but a server spring boot problem

-   [ X] Checking this box is mandatory (this is just to show you read everything)

**Comment by atomfrede** [comment]
Does it work when building and running from the command line?

**Comment by p4535992** [comment]
The spring-boot command from console it's seem doing fine. 
So i guess it's just some ide problem.
Sorry for the inconvenience.
