### ISSUE TITLE
Elastic Search on Kubernetes - AccessDeniedException

### ISSUE THREAD

**Issue by saturnism** [jhipster/generator-jhipster#11302]
##### **Overview of the issue**

If ES deployment starts (increasing resource restriction), then it crashes with exception:
```
Caused by: java.nio.file.AccessDeniedException: /usr/share/elasticsearch/data/nodes
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:90) ~[?:?]
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111) ~[?:?]
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116) ~[?:?]
	at sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:389) ~[?:?]
	at java.nio.file.Files.createDirectory(Files.java:693) ~[?:?]
	at java.nio.file.Files.createAndCheckIsDirectory(Files.java:800) ~[?:?]
	at java.nio.file.Files.createDirectories(Files.java:786) ~[?:?]
	at org.elasticsearch.env.NodeEnvironment.lambda$new$0(NodeEnvironment.java:273) ~[elasticsearch-6.8.6.jar:6.8.6]
	at org.elasticsearch.env.NodeEnvironment$NodeLock.<init>(NodeEnvironment.java:206) ~[elasticsearch-6.8.6.jar:6.8.6]
	at org.elasticsearch.env.NodeEnvironment.<init>(NodeEnvironment.java:270) ~[elasticsearch-6.8.6.jar:6.8.6]
	at org.elasticsearch.node.Node.<init>(Node.java:296) ~[elasticsearch-6.8.6.jar:6.8.6]
	at org.elasticsearch.node.Node.<init>(Node.java:266) ~[elasticsearch-6.8.6.jar:6.8.6]
	at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:212) ~[elasticsearch-6.8.6.jar:6.8.6]
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:212) ~[elasticsearch-6.8.6.jar:6.8.6]
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:333) ~[elasticsearch-6.8.6.jar:6.8.6]
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:159) ~[elasticsearch-6.8.6.jar:6.8.6]
	... 6 more
```

##### **Motivation for or Use Case**

ES should work on Kubernetes.

##### **Reproduce the error**

https://github.com/jhipster/jdl-samples/blob/master/microservices-blog-store.jh

##### **Related issues**

#11301 

##### **Suggest a Fix**

TBD

##### **JHipster Version(s)**

6.7.0

##### **JHipster configuration**

https://github.com/jhipster/jdl-samples/blob/master/microservices-blog-store.jh

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

https://github.com/jhipster/jdl-samples/blob/master/microservices-blog-store.jh

##### **Browsers and Operating System**

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by saturnism** [comment]
https://github.com/elastic/helm-charts/issues/137

**Comment by pascalgrimaud** [comment]
fixed by https://github.com/jhipster/generator-jhipster/pull/11303
