### ISSUE TITLE
IntelliJ run exception

### ISSUE THREAD

**Issue by fontanellif** [jhipster/generator-jhipster#1135]
When i try to run a clean jhipster project in intellij IDEA 14 i get this exception:

```sh
[INFO] com.mycompany.myapp.config.MetricsConfiguration - Initializing Metrics JMX reporting
[WARN] io.undertow.websockets.jsr - UT026009: XNIO worker was not set on WebSocketDeploymentInfo, the default worker will be used
[WARN] org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext - Exception encountered during context initialization - cancelling refresh attempt
org.springframework.context.ApplicationContextException: Unable to start embedded container; nested exception is java.lang.ClassCastException: org.apache.tomcat.websocket.WsWebSocketContainer cannot be cast to io.undertow.websockets.jsr.ServerWebSocketContainer
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.onRefresh(EmbeddedWebApplicationContext.java:133) [spring-boot-1.2.1.RELEASE.jar:1.2.1.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:474) ~[spring-context-4.1.4.RELEASE.jar:4.1.4.RELEASE]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:118) [spring-boot-1.2.1.RELEASE.jar:1.2.1.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:691) [spring-boot-1.2.1.RELEASE.jar:1.2.1.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:321) [spring-boot-1.2.1.RELEASE.jar:1.2.1.RELEASE]
	at com.mycompany.myapp.Application.main(Application.java:57) [classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_31]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_31]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_31]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[na:1.8.0_31]
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:134) [idea_rt.jar:na]
Caused by: java.lang.ClassCastException: org.apache.tomcat.websocket.WsWebSocketContainer cannot be cast to io.undertow.websockets.jsr.ServerWebSocketContainer
```
This is the .yo-rc.json file
```sh
{
  "generator-jhipster": {
    "baseName": "jhipster",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "authenticationType": "oauth2",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": "hazelcast",
    "websocket": "spring-websocket",
    "databaseType": "sql",
    "devDatabaseType": "h2Memory",
    "prodDatabaseType": "mysql",
    "useCompass": false,
    "buildTool": "maven",
    "frontendBuilder": "grunt",
    "javaVersion": "8",
    "rememberMeKey": "9323f0e6dd69f1a10a8b56553f4463522cfe665c"
  }
}
```

**Comment by jdubois** [comment]
This is because you use Undertow and Websockets

Undertow does not support Websockets, Tomcat does -> Spring Websockets only works on top of an app server that supports Websockets

**Comment by mrtinkz** [comment]
I am a little confused, I get the same error too, Undertow claims that it provides full support for Web Sockets, including JSR-356 support.

**Comment by mrtinkz** [comment]
Ok, not sure if this was a problem. I was able to run my application. All I had to make sure is to have undertow in my project classpath.

1. Exclude the tomcat from websocket 
      <dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-websocket</artifactId>
			<version>${spring-boot.version}</version>
			<exclusions>
				<exclusion>
					<groupId>org.springframework.boot</groupId>
					<artifactId>spring-boot-starter-tomcat</artifactId>
				</exclusion>
			</exclusions>
		</dependency>

2. Add undertow.

                 <dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-undertow</artifactId>
			<version>${spring-boot.version}</version>
			<scope>provided</scope>
		</dependency>

I usually configured the undertow/tomcat with the profiles as a better practice.

**Comment by padewitte** [comment]
I had the same problem. I activate both dev and fats profile. Just use one profile at a time.

**Comment by mrtinkz** [comment]
Glad it worked.
