### ISSUE TITLE
Error deploying to Azure Spring Cloud locally

### ISSUE THREAD

**Issue by yucwan** [jhipster/generator-jhipster#11454]
##### **Overview of the issue**

Deploying application...
× Deployment failed!
 Error: Command failed: az spring-cloud app deploy --resource-group yuchensp --service yuchensp --name yucjhapp --jar-path target/*.jar
Command group 'spring-cloud' is in preview. It may be changed/removed in a future release.
WARNING: This command usually takes minutes to run. Add '--verbose' parameter if needed.
WARNING: [1/3] Requesting for upload URL
WARNING: [2/3] Uploading package to blob
ERROR: The command failed with an unexpected error. Here is the traceback:

ERROR: [WinError 123] The filename, directory name, or volume label syntax is incorrect: 'target/*.jar'
Traceback (most recent call last):
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-3pnsb50r\knack\knack\cli.py", line 206, in invoke
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-3pnsb50r\azure-cli-core\azure\cli\core\commands\__init__.py", line 608, in execute
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-3pnsb50r\azure-cli-core\azure\cli\core\commands\__init__.py", line 666, in _run_jobs_serially
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-3pnsb50r\azure-cli-core\azure\cli\core\commands\__init__.py", line 659, in _run_job
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-3pnsb50r\six\six.py", line 703, in reraise
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-3pnsb50r\azure-cli-core\azure\cli\core\commands\__init__.py", line 636, in _run_job
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-3pnsb50r\azure-cli-core\azure\cli\core\commands\__init__.py", line 306, in __call__
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-3pnsb50r\azure-cli-core\azure\cli\core\__init__.py", line 493, in default_command_handler
  File "C:\Users\yucwan\.azure\cliextensions\spring-cloud\azext_spring_cloud\custom.py", line 334, in app_deploy
    True)
  File "C:\Users\yucwan\.azure\cliextensions\spring-cloud\azext_spring_cloud\custom.py", line 993, in _app_deploy
    file_service.create_file_from_path(share_name, None, relative_path, path)
  File "C:\Users\yucwan\.azure\cliextensions\spring-cloud\azext_spring_cloud\azure_storage_file\fileservice.py", line 1942, in create_file_from_path
    count = path.getsize(local_file_path)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\genericpath.py", line 50, in getsize
    return os.stat(filename).st_size
OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: 'target/*.jar'
WARNING:
To open an issue, please run: 'az feedback'

INFO! Congratulations, JHipster execution is complete!

##### **Browsers and Operating System**

-   [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by pascalgrimaud** [comment]
can you provide all information plz ? just use `jhipster info`

**Comment by jdubois** [comment]
Yes, maybe you have nothing under `target` because you used Gradle, there is no way to know without `jhipster info`

**Comment by jdubois** [comment]
Oh it's you @yucwan !! Don't hesitate to do a Teams call with me

**Comment by yucwan** [comment]
C:\Users\yucwan\Documents\vsworks\jh>jhipster info
INFO! Using JHipster version installed locally in current project's node_modules
INFO! Executing jhipster:info
INFO! Options: from-cli: true
Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
yuc@0.0.0 C:\Users\yucwan\Documents\vsworks\jh
`-- generator-jhipster@6.8.0

```


##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**


<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.mycompany.myapp"
    },
    "jhipsterVersion": "6.8.0",
    "applicationType": "monolith",
    "baseName": "yuc",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "ehcache",
    "enableHibernateCache": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Memory",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "bXktc2VjcmV0LXRva2VuLXRvLWNoYW5nZS1pbi1wcm9kdWN0aW9uLWFuZC10by1rZWVwLWluLWEtc2VjdXJlLXBsYWNl",
    "embeddableLaunchScript": false,
    "useSass": true,
    "clientPackageManager": "npm",
    "skipClient": true,
    "creationTimestamp": 1583820269143,
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [],
    "enableTranslation": false,
    "blueprints": [],
    "azureSpringCloudAppName": "yucjhapp",
    "azureSpringCloudDeploymentType": "local"
  }
}

</pre>
</details>


##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>


##### **Environment and Tools**

openjdk version "1.8.0_232"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_232-b09)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.232-b09, mixed mode)

git version 2.21.0.windows.1

node: v12.16.1

npm: 6.13.4

INFO! Congratulations, JHipster execution is complete!

**Comment by yucwan** [comment]
I believe the problem is that the az command to deploy jar doesn't support path like /*.jar. I tried this command and:

C:\Users\yucwan\Documents\vsworks\jh> az spring-cloud app deploy --resource-group yuchensp --service yuchensp --name yucjhapp --jar-path target/*.jar
Command group 'spring-cloud' is in preview. It may be changed/removed in a future release.
This command usually takes minutes to run. Add '--verbose' parameter if needed.
[1/3] Requesting for upload URL
[2/3] Uploading package to blob
The command failed with an unexpected error. Here is the traceback:

[WinError 123] The filename, directory name, or volume label syntax is incorrect: 'target/*.jar'
Traceback (most recent call last):
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-3pnsb50r\knack\knack\cli.py", line 206, in invoke
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-3pnsb50r\azure-cli-core\azure\cli\core\commands\__init__.py", line 608, in execute
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-3pnsb50r\azure-cli-core\azure\cli\core\commands\__init__.py", line 666, in _run_jobs_serially
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-3pnsb50r\azure-cli-core\azure\cli\core\commands\__init__.py", line 659, in _run_job
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-3pnsb50r\six\six.py", line 703, in reraise
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-3pnsb50r\azure-cli-core\azure\cli\core\commands\__init__.py", line 636, in _run_job
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-3pnsb50r\azure-cli-core\azure\cli\core\commands\__init__.py", line 306, in __call__
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-3pnsb50r\azure-cli-core\azure\cli\core\__init__.py", line 493, in default_command_handler
  File "C:\Users\yucwan\.azure\cliextensions\spring-cloud\azext_spring_cloud\custom.py", line 334, in app_deploy
    True)
  File "C:\Users\yucwan\.azure\cliextensions\spring-cloud\azext_spring_cloud\custom.py", line 993, in _app_deploy
    file_service.create_file_from_path(share_name, None, relative_path, path)
  File "C:\Users\yucwan\.azure\cliextensions\spring-cloud\azext_spring_cloud\azure_storage_file\fileservice.py", line 1942, in create_file_from_path
    count = path.getsize(local_file_path)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\genericpath.py", line 50, in getsize
    return os.stat(filename).st_size
OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: 'target/*.jar'

To open an issue, please run: 'az feedback'

C:\Users\yucwan\Documents\vsworks\jh> az spring-cloud app deploy --resource-group yuchensp --service yuchensp --name yucjhapp --jar-path target/yuc-0.0.1-SNAPSHOT.jar
Command group 'spring-cloud' is in preview. It may be changed/removed in a future release.
This command usually takes minutes to run. Add '--verbose' parameter if needed.
[1/3] Requesting for upload URL
[2/3] Uploading package to blob
[3/3] Updating deployment in app 'yucjhapp' (this operation can take a while to complete)
{
  "id": "/subscriptions/9618899a-d996-4557-8db9-111178846eb2/resourceGroups/yuchensp/providers/Microsoft.AppPlatform/Spring/yuchensp/apps/yucjhapp/deployments/default",
  "name": "default",
  "properties": {
    "active": true,
    "appName": "yucjhapp",
    "createdTime": null,
    "deploymentSettings": {
      "cpu": 1,
      "environmentVariables": null,
      "instanceCount": 1,
      "jvmOptions": null,
      "memoryInGb": 1,
      "runtimeVersion": "Java_8"
    },
    "instances": [
      {
        "discoveryStatus": "UP",
        "name": "yucjhapp-default-8-57bbffbf8b-vjbgs",
        "reason": null,
        "status": "Retiring"
      },
      {
        "discoveryStatus": "DOWN",
        "name": "yucjhapp-default-8-84888d6f77-6w7rn",
        "reason": "Not ready for connecting",
        "status": "Starting"
      }
    ],
    "provisioningState": "Succeeded",
    "source": {
      "artifactSelector": null,
      "relativePath": "resources/e389af5bad23a74c612f01e1c698616d5e787249b446f28171c735d6adb59d63-2020031008-7492e27a-4e1f-4850-873a-985eb65c8dbe",
      "type": "Jar",
      "version": null
    },
    "status": "Upgrading"
  },
  "resourceGroup": "yuchensp",
  "type": "Microsoft.AppPlatform/Spring/apps/deployments"
}

**Comment by pascalgrimaud** [comment]
It means there are 2 issues at this line:
https://github.com/jhipster/generator-jhipster/blob/master/generators/azure-spring-cloud/index.js#L424
- it should not be `target` for `Gradle`
- it should not use `*.jar`

**Comment by jdubois** [comment]
The good news: I improved Gradle support (the PR is linked into this ticket)
The bad news: it deploys correctly using "*.jar"

So @yucwan I need to your help to better understand... Maybe that's because you are on Windows??
Could you run `jhipster info` on your project, and post the result here, so I have your exact configuration?

**Comment by yucwan** [comment]
> C:\Users\yucwan\Documents\vsworks\jh>jhipster info
> INFO! Using JHipster version installed locally in current project's node_modules
> INFO! Executing jhipster:info
> INFO! Options: from-cli: true
> Welcome to the JHipster Information Sub-Generator
> JHipster Version(s)
> yuc@0.0.0 C:\Users\yucwan\Documents\vsworks\jh
> `-- generator-jhipster@6.8.0
> 
> 
> JHipster configuration, a .yo-rc.json file generated in the root folder
> 
> .yo-rc.json file
> 
> 
> JDL for the Entity configuration(s) entityName.json files generated in the .jhipster directory
> 
> JDL entity definitions
> 
> 
> Environment and Tools
> openjdk version "1.8.0_232"
> OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_232-b09)
> OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.232-b09, mixed mode)
> git version 2.21.0.windows.1
> node: v12.16.1
> npm: 6.13.4
> INFO! Congratulations, JHipster execution is complete!

@jdubois yes here is the jhipster info

**Comment by jdubois** [comment]
@yucwan that's weird, you should have much more information, typically the content of your `.yo-rc.json` (well, not the exact content, we remove sensitive information first).
Do you have that file in your directory?

**Comment by yucwan** [comment]
Yes:

{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.mycompany.myapp"
    },
    "jhipsterVersion": "6.8.0",
    "applicationType": "monolith",
    "baseName": "yuc",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "ehcache",
    "enableHibernateCache": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Memory",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "xxx",
    "embeddableLaunchScript": false,
    "useSass": true,
    "clientPackageManager": "npm",
    "skipClient": true,
    "creationTimestamp": 1583820269143,
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [],
    "enableTranslation": false,
    "blueprints": [],
    "azureSpringCloudAppName": "yucjhapp",
    "azureSpringCloudDeploymentType": "local"
  }
}

**Comment by jdubois** [comment]
Sorry, I forgot about this!
I just tested and I could deploy the application without any issue, using the current `master` branch. So I'm not sure what happened, but this bug looks to be fixed!

This is why I'm closing this, and also I'm not claiming the money as 1) I work for Microsoft and that's part of my work and 2) I didn't do much
