### ISSUE TITLE
Liquibase problem with OneToOne relationship and/or Unique fields

### ISSUE THREAD

**Issue by nury-garryyev** [jhipster/generator-jhipster#11467]
##### **Overview of the issue**

I created the JHipster project with the jh file. Everything works fine. I run `mvn liquibase:diff` command and added a newly created changelog.xml file to master.xml. It gives an error:

```
2020-03-12 11:59:13.415 ERROR 7836 --- [   abpay-task-1] liquibase.changelog.ChangeSet            : Change Set config/liquibase/changelog/20200312055920_changelog.xml::1583992782487-1::Nury (generated) failed.  Error: ERROR: constraint "uc_cash_collectiondevice_id_col" of relation "cash_collection" does not exist [Failed SQL: ALTER TABLE public.cash_collection DROP CONSTRAINT UC_CASH_COLLECTIONDEVICE_ID_COL]
2020-03-12 11:59:13.431 ERROR 7836 --- [   abpay-task-1] i.g.j.c.liquibase.AsyncSpringLiquibase   : Liquibase could not start correctly, your database is NOT ready: Migration failed for change set config/liquibase/changelog/20200312055920_changelog.xml::1583992782487-1::Nury (generated):
     Reason: liquibase.exception.DatabaseException: ERROR: constraint "uc_cash_collectiondevice_id_col" of relation "cash_collection" does not exist [Failed SQL: ALTER TABLE public.cash_collection DROP CONSTRAINT UC_CASH_COLLECTIONDEVICE_ID_COL]

liquibase.exception.MigrationFailedException: Migration failed for change set config/liquibase/changelog/20200312055920_changelog.xml::1583992782487-1::Nury (generated):
     Reason: liquibase.exception.DatabaseException: ERROR: constraint "uc_cash_collectiondevice_id_col" of relation "cash_collection" does not exist [Failed SQL: ALTER TABLE public.cash_collection DROP CONSTRAINT UC_CASH_COLLECTIONDEVICE_ID_COL]
	at liquibase.changelog.ChangeSet.execute(ChangeSet.java:637)
	at liquibase.changelog.visitor.UpdateVisitor.visit(UpdateVisitor.java:53)
	at liquibase.changelog.ChangeLogIterator.run(ChangeLogIterator.java:83)
	at liquibase.Liquibase.update(Liquibase.java:202)
	at liquibase.Liquibase.update(Liquibase.java:179)
	at liquibase.integration.spring.SpringLiquibase.performUpdate(SpringLiquibase.java:353)
	at liquibase.integration.spring.SpringLiquibase.afterPropertiesSet(SpringLiquibase.java:305)
	at org.springframework.boot.autoconfigure.liquibase.DataSourceClosingSpringLiquibase.afterPropertiesSet(DataSourceClosingSpringLiquibase.java:46)
	at io.github.jhipster.config.liquibase.AsyncSpringLiquibase.initDb(AsyncSpringLiquibase.java:118)
	at io.github.jhipster.config.liquibase.AsyncSpringLiquibase.lambda$afterPropertiesSet$0(AsyncSpringLiquibase.java:93)
	at io.github.jhipster.async.ExceptionHandlingAsyncTaskExecutor.lambda$createWrappedRunnable$1(ExceptionHandlingAsyncTaskExecutor.java:78)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: liquibase.exception.DatabaseException: ERROR: constraint "uc_cash_collectiondevice_id_col" of relation "cash_collection" does not exist [Failed SQL: ALTER TABLE public.cash_collection DROP CONSTRAINT UC_CASH_COLLECTIONDEVICE_ID_COL]
	at liquibase.executor.jvm.JdbcExecutor$ExecuteStatementCallback.doInStatement(JdbcExecutor.java:356)
	at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:57)
	at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:125)
	at liquibase.database.AbstractJdbcDatabase.execute(AbstractJdbcDatabase.java:1229)
	at liquibase.database.AbstractJdbcDatabase.executeStatements(AbstractJdbcDatabase.java:1211)
	at liquibase.changelog.ChangeSet.execute(ChangeSet.java:600)
	... 13 common frames omitted
Caused by: org.postgresql.util.PSQLException: ERROR: constraint "uc_cash_collectiondevice_id_col" of relation "cash_collection" does not exist
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2505)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2241)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:310)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:447)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:368)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:309)
	at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:295)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:272)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:267)
	at com.zaxxer.hikari.pool.ProxyStatement.execute(ProxyStatement.java:95)
	at com.zaxxer.hikari.pool.HikariProxyStatement.execute(HikariProxyStatement.java)
	at liquibase.executor.jvm.JdbcExecutor$ExecuteStatementCallback.doInStatement(JdbcExecutor.java:352)
	... 18 common frames omitted
```

##### **Motivation for or Use Case**

I didn't do any changes to DB, entities, and relationships. Despite this, the `mvn liquibase:diff` command creates a changelog.xml file. ***In this changelog.xml file, one thing caught my attention.  All these fields in the changelog are UNIQUE fields.***
Why this error occurs? How to fix this issue?
```
<?xml version="1.1" encoding="UTF-8" standalone="no"?>
<databaseChangeLog xmlns="http://www.liquibase.org/xml/ns/dbchangelog" xmlns:ext="http://www.liquibase.org/xml/ns/dbchangelog-ext" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.liquibase.org/xml/ns/dbchangelog-ext http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-ext.xsd http://www.liquibase.org/xml/ns/dbchangelog http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-3.6.xsd">
    <changeSet author="Nury (generated)" id="1583992782487-1">
        <dropUniqueConstraint constraintName="UC_CASH_COLLECTIONDEVICE_ID_COL" tableName="cash_collection"/>
        <addUniqueConstraint columnNames="device_id" constraintName="UC_CASH_COLLECTIONDEVICE_ID_COL" tableName="cash_collection"/>
    </changeSet>
    <changeSet author="Nury (generated)" id="1583992782487-2">
        <dropUniqueConstraint constraintName="UC_JHI_USEREMAIL_COL" tableName="jhi_user"/>
        <addUniqueConstraint columnNames="email" constraintName="UC_JHI_USEREMAIL_COL" tableName="jhi_user"/>
    </changeSet>
    <changeSet author="Nury (generated)" id="1583992782487-3">
        <dropUniqueConstraint constraintName="UC_JHI_USERLOGIN_COL" tableName="jhi_user"/>
        <addUniqueConstraint columnNames="login" constraintName="UC_JHI_USERLOGIN_COL" tableName="jhi_user"/>
    </changeSet>
    <changeSet author="Nury (generated)" id="1583992782487-4">
        <dropUniqueConstraint constraintName="UC_PROVIDERPROTOCOL_ID_COL" tableName="provider"/>
        <addUniqueConstraint columnNames="protocol_id" constraintName="UC_PROVIDERPROTOCOL_ID_COL" tableName="provider"/>
    </changeSet>
    <changeSet author="Nury (generated)" id="1583992782487-5">
        <dropUniqueConstraint constraintName="UC_USER_EXTRAUSER_ID_COL" tableName="user_extra"/>
        <addUniqueConstraint columnNames="user_id" constraintName="UC_USER_EXTRAUSER_ID_COL" tableName="user_extra"/>
    </changeSet>
</databaseChangeLog>
```

##### **Reproduce the error**

Create a JHipster project. Run `mvn liquibase:diff` command. Add changelog.xml to master.xml. Build the project.

##### **JHipster Version(s)**

```
-- generator-jhipster@6.7.1

```

##### **JHipster configuration**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.abpay"
    },
    "jhipsterVersion": "6.7.1",
    "applicationType": "monolith",
    "baseName": "abpay",
    "packageName": "com.abpay",
    "packageFolder": "com/abpay",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "websocket": "spring-websocket",
    "databaseType": "sql",
    "devDatabaseType": "postgresql",
    "prodDatabaseType": "postgresql",
    "searchEngine": "elasticsearch",
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "bXktc2VjcmV0LXRva2VuLXRvLWNoYW5nZS1pbi1wcm9kdWN0aW9uLWFuZC10by1rZWVwLWluLWEtc2VjdXJlLXBsYWNl",
    "embeddableLaunchScript": false,
    "creationTimestamp": 1581574715458,
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [],
    "enableTranslation": false,
    "clientPackageManager": "npm",
    "blueprints": [],
    "skipClient": true
  }
}

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity Provider {
  code String required minlength(3),
  shortName String required,
  fullName String,
  address String,
  email String,
  phoneNumber String,
  website String,
  logo ImageBlob,
  availableBalance Double,
  isActive Boolean
}

entity Protocol {
  protocolName String required,
  protocolAccount String,
  protocolAccountLabel String,
  protocolAccountPassword String,
  protocolAccountPasswordLabel String,
  apiUrl String,
  apiUrlLabel String,
  apiDocumentationUrl String
}

entity UserExtra

entity Device {
  type DeviceType,
  code String,
  name String,
  location String,
  state String,
  clientSoftwareVersion String,
  billCount String,
  maxBillCount String,
  token String,
  isEnabled Boolean,
  isActive Boolean,
  password String
}

entity CashCollection {
  referenceId String,
  timestamp Instant,
  transactionCount Integer,
  billCount Integer,
  totalAmount Double,
  billHistogram String,
  state String
}

relationship OneToOne {
  Provider{protocol} to Protocol{provider},
  UserExtra{user} to User,
  CashCollection{device} to Device{cashCollection}
}

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_65"
Java(TM) SE Runtime Environment (build 1.8.0_65-b17)
Java HotSpot(TM) 64-Bit Server VM (build 25.65-b01, mixed mode)

git version 2.25.0.windows.1

node: v10.16.3

npm: 6.9.0

yeoman: 3.1.1

yarn: 1.19.1

##### **Browsers and Operating System**

Windows 8.1

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by pmverma** [comment]
Possibly related to #10887 


> **In this changelog.xml file, one thing caught my attention. All these fields in the changelog are UNIQUE fields.**

Your attention is right because OneToOne relationship is achieved using UNIQUE constraint. Isn't it?

**Comment by pmverma** [comment]
I was not able to reproduce this issue with `version 6.8.0`
I think the unique constraints issue is resolved. The only changeSet I ever get after `liquibase:diff` is 

```
<?xml version="1.1" encoding="UTF-8" standalone="no"?>
<databaseChangeLog xmlns="http://www.liquibase.org/xml/ns/dbchangelog" xmlns:ext="http://www.liquibase.org/xml/ns/dbchangelog-ext" xmlns:pro="http://www.liquibase.org/xml/ns/pro" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.liquibase.org/xml/ns/dbchangelog-ext http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-ext.xsd http://www.liquibase.org/xml/ns/pro http://www.liquibase.org/xml/ns/pro/liquibase-pro-3.8.xsd http://www.liquibase.org/xml/ns/dbchangelog http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-3.8.xsd">
    <changeSet author="p.mohan (generated)" id="1584077662335-1">
        <alterSequence sequenceName="sequence_generator"/>
    </changeSet>
</databaseChangeLog>
```
Again this do not have any real change so it's fine.

We recently have updated liquibase version.
@nury-garryyev Can you try with `version 6.8.0`.

**Comment by nury-garryyev** [comment]
> I was not able to reproduce this issue with `version 6.8.0`
> I think the unique constraints issue is resolved. The only changeSet I ever get after `liquibase:diff` is
> 
> ```
> <?xml version="1.1" encoding="UTF-8" standalone="no"?>
> <databaseChangeLog xmlns="http://www.liquibase.org/xml/ns/dbchangelog" xmlns:ext="http://www.liquibase.org/xml/ns/dbchangelog-ext" xmlns:pro="http://www.liquibase.org/xml/ns/pro" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.liquibase.org/xml/ns/dbchangelog-ext http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-ext.xsd http://www.liquibase.org/xml/ns/pro http://www.liquibase.org/xml/ns/pro/liquibase-pro-3.8.xsd http://www.liquibase.org/xml/ns/dbchangelog http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-3.8.xsd">
>     <changeSet author="p.mohan (generated)" id="1584077662335-1">
>         <alterSequence sequenceName="sequence_generator"/>
>     </changeSet>
> </databaseChangeLog>
> ```
> 
> Again this do not have any real change so it's fine.
> 
> We recently have updated liquibase version.
> @nury-garryyev Can you try with `version 6.8.0`.

I couldn't reproduce this issue with  `version 6.8.0`. But I am using  `version 6.7.1` in my current project. Do you have any suggestions on how to fix this unique constraints issue with `version 6.7.1`.

**Comment by pmverma** [comment]
@nury-garryyev Thanks for your testing. I would rather update liquibase as it will fix the issue.

**Comment by pmverma** [comment]
This issue no longer valid after v6.8.0
