### ISSUE TITLE
Unable to start the application from IntelliJ

### ISSUE THREAD

**Issue by knowings** [jhipster/generator-jhipster#11531]
##### **Overview of the issue**

I generate the application, apply IDE configuration as recommended, fixed some IT and build an external stack for development with the help of the generated `docker-compose` files.
Then I added a run configuration in IntelliJ with specific configuration for keycloak and ElasticSearch.

I started the application through the IDE and waited the process to die with the following stack trace:

```
2020-03-31 13:49:02.018 ERROR 24440 --- [  restartedMain] o.s.boot.SpringApplication               : Application run failed

org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'batchQueryService' defined in file [C:\Sources\tfs\Outils\portail\portal\target\classes\com\everial\tardis\portal\service\BatchQueryService.class]: Unsatisfied dependency expressed through constructor parameter 2; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'batchSearchRepository': Invocation of init method failed; nested exception is org.springframework.data.mapping.MappingException: Attempt to add id property private java.lang.String com.everial.tardis.portal.domain.InventoryLine.document but already have property private java.lang.Long com.everial.tardis.portal.domain.InventoryLine.id registered as id. Check your mapping configuration!
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:798)
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:228)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1358)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1204)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:557)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:517)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:879)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:878)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:550)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:141)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:747)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315)
	at com.everial.tardis.portal.PortalApp.main(PortalApp.java:63)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.boot.devtools.restart.RestartLauncher.run(RestartLauncher.java:49)
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'batchSearchRepository': Invocation of init method failed; nested exception is org.springframework.data.mapping.MappingException: Attempt to add id property private java.lang.String com.everial.tardis.portal.domain.InventoryLine.document but already have property private java.lang.Long com.everial.tardis.portal.domain.InventoryLine.id registered as id. Check your mapping configuration!
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1796)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:595)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:517)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1287)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1207)
	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:885)
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:789)
	... 22 common frames omitted
Caused by: org.springframework.data.mapping.MappingException: Attempt to add id property private java.lang.String com.everial.tardis.portal.domain.InventoryLine.document but already have property private java.lang.Long com.everial.tardis.portal.domain.InventoryLine.id registered as id. Check your mapping configuration!
	at org.springframework.data.mapping.model.BasicPersistentEntity.returnPropertyIfBetterIdPropertyCandidateOrNull(BasicPersistentEntity.java:266)
	at org.springframework.data.mapping.model.BasicPersistentEntity.addPersistentProperty(BasicPersistentEntity.java:218)
	at org.springframework.data.elasticsearch.core.mapping.SimpleElasticsearchPersistentEntity.addPersistentProperty(SimpleElasticsearchPersistentEntity.java:190)
	at org.springframework.data.elasticsearch.core.mapping.SimpleElasticsearchPersistentEntity.addPersistentProperty(SimpleElasticsearchPersistentEntity.java:52)
	at org.springframework.data.mapping.context.AbstractMappingContext$PersistentPropertyCreator.createAndRegisterProperty(AbstractMappingContext.java:538)
	at org.springframework.data.mapping.context.AbstractMappingContext$PersistentPropertyCreator.doWith(AbstractMappingContext.java:506)
	at org.springframework.util.ReflectionUtils.doWithFields(ReflectionUtils.java:705)
	at org.springframework.data.mapping.context.AbstractMappingContext.addPersistentEntity(AbstractMappingContext.java:374)
	at java.base/java.util.Collections$SingletonSet.forEach(Collections.java:4797)
	at org.springframework.data.mapping.context.AbstractMappingContext$PersistentPropertyCreator.createAndRegisterProperty(AbstractMappingContext.java:548)
	at org.springframework.data.mapping.context.AbstractMappingContext$PersistentPropertyCreator.doWith(AbstractMappingContext.java:506)
	at org.springframework.util.ReflectionUtils.doWithFields(ReflectionUtils.java:705)
	at org.springframework.data.mapping.context.AbstractMappingContext.addPersistentEntity(AbstractMappingContext.java:374)
	at org.springframework.data.mapping.context.AbstractMappingContext.getPersistentEntity(AbstractMappingContext.java:248)
	at org.springframework.data.mapping.context.AbstractMappingContext.getPersistentEntity(AbstractMappingContext.java:191)
	at org.springframework.data.mapping.context.AbstractMappingContext.getPersistentEntity(AbstractMappingContext.java:85)
	at org.springframework.data.repository.core.support.RepositoryFactoryBeanSupport.lambda$afterPropertiesSet$4(RepositoryFactoryBeanSupport.java:295)
	at java.base/java.util.Optional.ifPresent(Optional.java:183)
	at org.springframework.data.repository.core.support.RepositoryFactoryBeanSupport.afterPropertiesSet(RepositoryFactoryBeanSupport.java:295)
	at org.springframework.data.elasticsearch.repository.support.ElasticsearchRepositoryFactoryBean.afterPropertiesSet(ElasticsearchRepositoryFactoryBean.java:67)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1855)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1792)
	... 33 common frames omitted


Process finished with exit code 0
```

As far as I understood, a SearchRepository  failed to start for mysterious reason... I tried to define the ElasticSearch mapping with the use of `@org.springframework.data.elasticsearch.annotations.Mapping`. 

##### **Motivation for or Use Case**

The use case is quite simple: get the application running ! :smile:

##### **Reproduce the error**

I don't how I get to this state, I used with success a similar approach in a prototype of the application a couple of months ago (jhipster v6.6.0).

##### **Related issues**

I haven't found any.

##### **Suggest a Fix**

As far as I know, it might be due to:
* Newer version of a library (Jest or springdata)
* Changes in configuration (found some in `ElasticsearchConfiguration`)
* Version of ElasticSearch (currently using `docker.elastic.co/elasticsearch/elasticsearch:6.8.6`)
* My bad (of course !!!)

##### **JHipster Version(s)**

6.8.0

##### **JHipster configuration**

Unless it is absolutly necessary, i'd prefer keep those data for me.

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

Unless it is absolutly necessary, i'd prefer keep especially those data for me.

##### **Environment and Tools**

openjdk version "11.0.6" 2020-01-14
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.6+10)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.6+10, mixed mode)

git version 2.25.1.windows.1

node: v12.16.1

npm: 6.13.4

yeoman: 3.1.1

Docker version 19.03.8, build afacb8b

docker-compose version 1.25.4, build 8d51620a

##### **Browsers and Operating System**

Windows 10 and browser isn't relevant.

-   [X] Checking this box is mandatory (this is just to show you read everything)

**Comment by knowings** [comment]
So I think it's my bad after all 😅 

As explained on [S.O](https://stackoverflow.com/questions/60004445/mappingexceptionattempt-to-add-id-after-upgrading-to-spring-boot-2-2-x ):  **NEVER** use a field with name `document` when using ElasticSearch...

I'll try to rename the field and see if it's the solution

**Comment by knowings** [comment]
At last, it starts !

The solution was to use the annotation @Field("whatever but not document").

**Comment by dali010** [comment]
> At last, it starts !
> 
> The solution was to use the annotation @field("whatever but not document").

thanks it worked for me
