### ISSUE TITLE
Identical stacktraces for builds involving infinispan

### ISSUE THREAD

**Issue by MathieuAA** [jhipster/generator-jhipster#11629]
Two different builds:
  - [From #11606](https://github.com/jhipster/generator-jhipster/pull/11606/checks?check_run_id=602335602)
  - [From #11588](https://github.com/jhipster/generator-jhipster/pull/11588/checks?check_run_id=607930809)

We see this stacktrace every time, but the builds still pass (or fail for unrelated reasons, but let's not care about the failing ones):
```
2020-04-22T09:56:32.6320852Z java.lang.IllegalArgumentException: No marshaller registered for Java type org.hibernate.cache.internal.CacheKeyImplementation
2020-04-22T09:56:32.6321233Z 	at org.infinispan.protostream.impl.SerializationContextImpl.getMarshallerDelegate(SerializationContextImpl.java:279)
2020-04-22T09:56:32.6321990Z 	at org.infinispan.protostream.WrappedMessage.writeMessage(WrappedMessage.java:240)
2020-04-22T09:56:32.6322310Z 	at org.infinispan.protostream.ProtobufUtil.toWrappedStream(ProtobufUtil.java:196)
2020-04-22T09:56:32.6322693Z 	at org.infinispan.marshall.persistence.impl.PersistenceMarshallerImpl.objectToBuffer(PersistenceMarshallerImpl.java:157)
2020-04-22T09:56:32.6323449Z 	at org.infinispan.marshall.persistence.impl.PersistenceMarshallerImpl.objectToByteBuffer(PersistenceMarshallerImpl.java:137)
2020-04-22T09:56:32.6323741Z 	at org.infinispan.marshall.persistence.impl.PersistenceMarshallerImpl.objectToByteBuffer(PersistenceMarshallerImpl.java:145)
2020-04-22T09:56:32.6323976Z 	at org.infinispan.marshall.core.GlobalMarshaller.writeRawUnknown(GlobalMarshaller.java:638)
2020-04-22T09:56:32.6324332Z 	at org.infinispan.marshall.core.GlobalMarshaller.writeUnknown(GlobalMarshaller.java:627)
2020-04-22T09:56:32.6324568Z 	at org.infinispan.marshall.core.GlobalMarshaller.writeUnknown(GlobalMarshaller.java:618)
2020-04-22T09:56:32.6324785Z 	at org.infinispan.marshall.core.GlobalMarshaller.writeNonNullableObject(GlobalMarshaller.java:384)
2020-04-22T09:56:32.6325008Z 	at org.infinispan.marshall.core.GlobalMarshaller.writeNullableObject(GlobalMarshaller.java:352)
2020-04-22T09:56:32.6325220Z 	at org.infinispan.marshall.core.BytesObjectOutput.writeObject(BytesObjectOutput.java:26)
2020-04-22T09:56:32.6325424Z 	at org.infinispan.commons.marshall.MarshallUtil.marshallArray(MarshallUtil.java:191)
2020-04-22T09:56:32.6325659Z 	at org.infinispan.hibernate.cache.commons.util.EndInvalidationCommand.writeTo(EndInvalidationCommand.java:67)
2020-04-22T09:56:32.6325898Z 	at org.infinispan.marshall.exts.ReplicableCommandExternalizer.writeCommandParameters(ReplicableCommandExternalizer.java:70)
...
```

Possible fix described [here](https://stackoverflow.com/questions/58815818/infinispan-10-0-1-final-no-marshaller-registered-for-java-type-java-util-uuid).

**Comment by MathieuAA** [comment]
@ecostanzi Hi! I've noticed you've updated the dependency from v9 to v10 and I'm wondering if you have an idea about this one?

**Comment by ecostanzi** [comment]
@MathieuAA hi! No idea now, but the link with the fix is useful. I'll have a look

**Comment by MathieuAA** [comment]
Thank you!!
