### ISSUE TITLE
Angular in dev mode is broken

### ISSUE THREAD

**Issue by kaidohallik** [jhipster/generator-jhipster#11755]
##### **Overview of the issue**

If generating Angular app with current master and starting Angular app in dev mode by `npm start` then error occurs and app is not started.

```
ERROR in   Error: Child compilation failed:
  Module parse failed: Unexpected character '@' (1:0)
  You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file.   See https://webpack.js.org/concepts#loaders
  > @keyframes lds-pacman-1 {
  |   0% {
  |     -webkit-transform: rotate(0deg);:
  SyntaxError: Unexpected character '@' (1:0)

  - compiler.js:79
    [jhipster-sorting-icon]/[html-webpack-plugin]/lib/compiler.js:79:16

  - Compiler.js:343
    [jhipster-sorting-icon]/[webpack]/lib/Compiler.js:343:11

  - Compiler.js:681
    [jhipster-sorting-icon]/[webpack]/lib/Compiler.js:681:15


  - Hook.js:154 AsyncSeriesHook.lazyCompileHook
    [jhipster-sorting-icon]/[tapable]/lib/Hook.js:154:20

  - Compiler.js:678
    [jhipster-sorting-icon]/[webpack]/lib/Compiler.js:678:31


  - Hook.js:154 AsyncSeriesHook.lazyCompileHook
    [jhipster-sorting-icon]/[tapable]/lib/Hook.js:154:20

  - Compilation.js:1423
    [jhipster-sorting-icon]/[webpack]/lib/Compilation.js:1423:35


  - Hook.js:154 AsyncSeriesHook.lazyCompileHook
    [jhipster-sorting-icon]/[tapable]/lib/Hook.js:154:20

  - Compilation.js:1414
    [jhipster-sorting-icon]/[webpack]/lib/Compilation.js:1414:32


  - Hook.js:154 AsyncSeriesHook.lazyCompileHook
    [jhipster-sorting-icon]/[tapable]/lib/Hook.js:154:20

  - Compilation.js:1409
    [jhipster-sorting-icon]/[webpack]/lib/Compilation.js:1409:36



i ｢wdm｣: Failed to compile.
```

Seems to be regression from #11655: https://github.com/jhipster/generator-jhipster/pull/11655/files#diff-e4d800620d73178a8f853c368c1d5011L107-R107

Seems that `loading.css` in not understood correctly by `webpack` any more in `html-loader` version `1.1.0`.

Prod build is working fine.

Tried some solutions.

Solution 1. After using `html-loader` old version 0.5.5 app is starting successfully.

Solution 2. Tried to copy additional configuration from `webpack.prod.js` to `webpack.dev.js`:
```
        {
          test: /\.css$/,
          use: ['to-string-loader', 'css-loader']
        },
```
and app started but some strange error about malformed url in console:
```
URIError: URI malformed
    at decodeURIComponent (<anonymous>)
    at C:\projects\teest\jhipster-sorting-icon\node_modules\serve-index\index.js:113:15
    at C:\projects\teest\jhipster-sorting-icon\node_modules\webpack-dev-server\lib\Server.js:417:32
    at Layer.handle [as handle_request] (C:\projects\teest\jhipster-sorting-icon\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\projects\teest\jhipster-sorting-icon\node_modules\express\lib\router\index.js:317:13)
    at C:\projects\teest\jhipster-sorting-icon\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (C:\projects\teest\jhipster-sorting-icon\node_modules\express\lib\router\index.js:335:12)
    at next (C:\projects\teest\jhipster-sorting-icon\node_modules\express\lib\router\index.js:275:10)
    at SendStream.error (C:\projects\teest\jhipster-sorting-icon\node_modules\express\node_modules\serve-static\index.js:121:7)
    at SendStream.emit (events.js:310:20)
    at SendStream.error (C:\projects\teest\jhipster-sorting-icon\node_modules\express\node_modules\send\index.js:270:17)
    at SendStream.pipe (C:\projects\teest\jhipster-sorting-icon\node_modules\express\node_modules\send\index.js:520:10)
    at serveStatic (C:\projects\teest\jhipster-sorting-icon\node_modules\express\node_modules\serve-static\index.js:125:12)
    at Layer.handle [as handle_request] (C:\projects\teest\jhipster-sorting-icon\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\projects\teest\jhipster-sorting-icon\node_modules\express\lib\router\index.js:317:13)
    at C:\projects\teest\jhipster-sorting-icon\node_modules\express\lib\router\index.js:284:7
```

##### **Motivation for or Use Case**

Angular app should work also in dev mode.

##### **Reproduce the error**

Generate Angular app and start with `npm start`.

##### **Related issues**

Regression from #11655

##### **Suggest a Fix**

Two possible solutions:
* quick fix is to revert this change: https://github.com/jhipster/generator-jhipster/pull/11655/files#diff-e4d800620d73178a8f853c368c1d5011L107-R107
* better fix is to try to reconfigure dev build so that the new version of the `html-loader` is working fine

##### **JHipster Version(s)**

```
jhipster@0.0.1-SNAPSHOT C:\projects\teest\jhipster-sorting-icon
`-- generator-jhipster@6.8.0  -> c:\projects\kaido-github\generator-jhipster

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.mycompany.myapp",
      "nativeLanguage": "et"
    },
    "jhipsterVersion": "6.8.0",
    "applicationType": "monolith",
    "baseName": "jhipster",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "gradle",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "YourJWTSecretKeyWasReplacedByThisMeaninglessTextByTheJHipsterInfoCommandForObviousSecurityReasons",
    "embeddableLaunchScript": false,
    "useSass": true,
    "clientPackageManager": "npm",
    "clientFramework": "angularX",
    "clientTheme": "none",
    "clientThemeVariant": "",
    "creationTimestamp": 1589105597581,
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [],
    "enableTranslation": true,
    "nativeLanguage": "et",
    "languages": ["et"],
    "blueprints": []
  }
}

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_231"
Java(TM) SE Runtime Environment (build 1.8.0_231-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.231-b11, mixed mode)

git version 2.26.2.windows.1

node: v12.16.2

npm: 6.11.3

yeoman: 3.1.1

yarn: 1.17.3

Docker version 19.03.8, build afacb8b

docker-compose version 1.25.4, build 8d51620a

##### **Browsers and Operating System**

Windows 10

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by kaidohallik** [comment]
In `html-loader` config is line:
```
                exclude: /(src\/main\/webapp\/index.html)/
```
So `index.html` should be ignored by `html-loader`, but is not ignored any more at least in Windows.  
So it can be Windows specific and maybe can be solved by improving this exclude line.

**Comment by kaidohallik** [comment]
In JHipster Webpack `utils.js` module is function `root` for resolving path. So after changing exclude line to:
```
exclude: utils.root('src/main/webapp/index.html')
```
app is starting successfully in dev mode and no errors in console.  
Doing PR.
