### ISSUE TITLE
"No resolvable bootstrap urls given in bootstrap.servers" - Kafka

### ISSUE THREAD

**Issue by vw98075** [jhipster/generator-jhipster#11758]
##### **Overview of the issue**

An error on Kafka straight from the box

##### **Motivation for or Use Case**

Generating a microservice application with Kafka

##### **Reproduce the error**

1. generate a microservices with Kafka
2. build a docker image of the application with a command 
```
./mvnw -ntp -Pprod verify jib:dockerBuild
```
3. create a docker-compose directory and run 
```
jhipster docker-compose
```
based on the Jhipster document.

4. run 
```
docker-compose up
```
The first notable error message:
```
kafka_1      | kafka.common.InconsistentBrokerIdException: Configured broker.id 2 doesn't match stored broker.id 1 in meta.properties. If you moved your data, make sure your configured broker.id matches. If you intend to create a new broker, you should remove all data in your data directories (log.dirs).
```
and
```
jhipster_1   | 2020-05-11 02:51:43.665  WARN 1 --- [           main] ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'jhipsterKafkaResource' defined in file [/app/classes/com/<...>/web/rest/JhipsterKafkaResource.class]: Bean instantiation via constructor failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.<...>.web.rest.JhipsterKafkaResource]: Constructor threw exception; nested exception is org.apache.kafka.common.KafkaException: Failed to construct kafka producer
jhipster_1   | 2020-05-11 02:51:43.689 ERROR 1 --- [           main] o.s.boot.SpringApplication               : Application run failed
jhipster_1   | 
jhipster_1   | org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'jhipsterKafkaResource' defined in file [/app/classes/com/<...>/web/rest/JhipsterKafkaResource.class]: Bean instantiation via constructor failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.<...>.web.rest.JhipsterKafkaResource]: Constructor threw exception; nested exception is org.apache.kafka.common.KafkaException: Failed to construct kafka producer
jhipster_1   | 	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:314)
jhipster_1   | 	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:295)
jhipster_1   | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1358)
jhipster_1   | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1204)
jhipster_1   | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:557)
jhipster_1   | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:517)
jhipster_1   | 	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323)
jhipster_1   | 	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
jhipster_1   | 	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321)
jhipster_1   | 	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
jhipster_1   | 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:879)
jhipster_1   | 	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:878)
jhipster_1   | 	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:550)
jhipster_1   | 	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:141)
jhipster_1   | 	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:747)
jhipster_1   | 	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397)
jhipster_1   | 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315)
jhipster_1   | 	at com.vw.example.microservices.kafka.sammple.JhipsterApp.main(JhipsterApp.java:62)
jhipster_1   | Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.vw.example.microservices.kafka.sammple.web.rest.JhipsterKafkaResource]: Constructor threw exception; nested exception is org.apache.kafka.common.KafkaException: Failed to construct kafka producer
jhipster_1   | 	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:216)
jhipster_1   | 	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:117)
jhipster_1   | 	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:310)
jhipster_1   | 	... 17 common frames omitted
jhipster_1   | Caused by: org.apache.kafka.common.KafkaException: Failed to construct kafka producer
jhipster_1   | 	at org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:432)
jhipster_1   | 	at org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:270)
jhipster_1   | 	at com.vw.example.microservices.kafka.sammple.web.rest.JhipsterKafkaResource.<init>(JhipsterKafkaResource.java:35)
jhipster_1   | 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
jhipster_1   | 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
jhipster_1   | 	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
jhipster_1   | 	at java.base/java.lang.reflect.Constructor.newInstance(Unknown Source)
jhipster_1   | 	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:203)
jhipster_1   | 	... 19 common frames omitted
jhipster_1   | Caused by: org.apache.kafka.common.config.ConfigException: No resolvable bootstrap urls given in bootstrap.servers
jhipster_1   | 	at org.apache.kafka.clients.ClientUtils.parseAndValidateAddresses(ClientUtils.java:88)
jhipster_1   | 	at org.apache.kafka.clients.ClientUtils.parseAndValidateAddresses(ClientUtils.java:47)
jhipster_1   | 	at org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:407)
jhipster_1   | 	... 26 common frames omitted
```

##### **JHipster Version(s)**

6.8.0

##### **JHipster configuration**

```
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.myapp"
    },
    "jhipsterVersion": "6.8.0",
    "applicationType": "microservice",
    "baseName": "jhipster",
    "packageName": "com.myapp",
    "packageFolder": "com/myapp",
    "serverPort": "8081",
    "authenticationType": "jwt",
    "cacheProvider": "no",
    "enableHibernateCache": false,
    "websocket": false,
    "databaseType": "no",
    "devDatabaseType": "no",
    "prodDatabaseType": "no",
    "searchEngine": false,
    "messageBroker": "kafka",
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "ZjBiYWRlODIyZDVkZTVkYzA3YTkwZDUwZTZjZjRlMzZiOGM4NDc5NTQ0MzVkZmZiZDY4ZTI2Yzc4ZDNkMWJjYWM5MzBmYWJmNTg2MGM4NzM3NzlkOTkyMzIyY2FmODA2NTBiYmQ1ZjliMzQyZGQ5YTdhOTRjMTM0MjA2MDY4ZWM=",
    "embeddableLaunchScript": false,
    "creationTimestamp": 1589165168805,
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [],
    "enableTranslation": false,
    "clientPackageManager": "npm",
    "blueprints": [],
    "skipClient": true,
    "skipUserManagement": true
  }
}

```

##### **Browsers and Operating System**

Linux Mint

-   [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by vw98075** [comment]
I already provide all steps for problem reproduction. Is something missing?

**Comment by atomfrede** [comment]
@vw98075 Nothing is missing. We just need time to work on that and reproduce it on our own such that we can reproduce it too (if you  mean the added label).

**Comment by Shaolans** [comment]
I tried to reproduce this issue but I could only reproduce it once (the first time)..
I can't get the issue by doing the exact same steps as you mentionned.

**Comment by pascalgrimaud** [comment]
I already encountered this because the Kafka broken didn't start correctly, or I started the application to quickly.
Then, as we can't reproduce, I'm closing this issue.
Feel free to provide more details and steps to reproduce if you think there is a real issue here.

**Comment by mrsegen** [comment]
I just encountered this. Generated via 6.10.1. It would be good for the generated application to not fail if kafka fails. 

_Caveat: I'm new to kafka and currently understand it as a tool for inter-service communication._ If that's right, it would seem strange for 1 service to fail if the separately-run communication service would be unavailable.

In case it's helpful to whoever eventually figures out what's going, I'll share the `.yo-rc.json` and the part of the application part of the `.jdl`
```json
{
  "generator-jhipster": {
    "authenticationType": "oauth2",
    "cacheProvider": "ehcache",
    "clientFramework": "angularX",
    "serverPort": "8002",
    "serviceDiscoveryType": false,
    "skipUserManagement": true,
    "baseName": "inventory",
    "buildTool": "gradle",
    "databaseType": "sql",
    "devDatabaseType": "mssql",
    "enableHibernateCache": true,
    "enableSwaggerCodegen": true,
    "enableTranslation": false,
    "jhiPrefix": "jhi",
    "languages": ["en", "fr"],
    "messageBroker": "kafka",
    "nativeLanguage": "en",
    "prodDatabaseType": "mssql",
    "searchEngine": "elasticsearch",
    "skipClient": false,
    "testFrameworks": ["protractor", "cucumber", "gatling"],
    "websocket": "spring-websocket",
    "applicationType": "monolith",
    "packageName": "com.herzog.tps.inventory",
    "packageFolder": "com/herzog/tps/inventory",
    "useSass": true,
    "jhipsterVersion": "6.10.1",
    "creationTimestamp": 1597859100648,
    "skipServer": false,
    "clientPackageManager": "npm",
    "clientTheme": "none",
    "clientThemeVariant": "",
    "embeddableLaunchScript": false,
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [],
    "blueprints": []
  },
  "entities": [
    "BaselineBulkItem",
    "BaselineSerializedItem",
    "Manufacturer",
    "QuantityType",
    "ItemCategory",
    "Location",
    "BulkItem",
    "SerializedItem"
  ]
}
```

```jdl
application {
    config {
        applicationType monolith
        authenticationType oauth2
        baseName inventory
        buildTool gradle
        devDatabaseType mssql
        enableSwaggerCodegen true
        enableTranslation false
        messageBroker kafka
        packageName com.herzog.tps.inventory
        prodDatabaseType mssql
        searchEngine elasticsearch
        serverPort 8002
        testFrameworks [protractor, cucumber, gatling]
        useSass true
        websocket spring-websocket
    }
    entities *
}
```

**Comment by pascalgrimaud** [comment]
@mrsegen : can you provide all steps to reproduce the issue ? And add the stacktrace too plz ?

**Comment by mrsegen** [comment]
@pascalgrimaud , sure!

Steps taken:

1. Put JDL file in blank directory.
2. Run `jhipster import-jdl ./[application].jdl`
3. Attempt to run ./gradlew, but abort and switch to `./gradlew bootJar -Pprod jibDockerBuild` (in preparation for running it all with docker-compose). 
4. Encounter error and change `jib_plugin_version=2.4.0` to `jib_plugin_version=2.4.0` in [application]/gradle.properties as recommended [here](https://github.com/GoogleContainerTools/jib/issues/2535#issuecomment-670692614).
5. Provide a `jib { to { ... } }` within [application]/build.gradle (and associated variables in [application]/gradle.properties) for a private docker registry.
6. Run `jhipster ci-cd` to add a Jenkinspipe line
7. Run `npm audit fix`
8. Attempt `docker-compose -f src/main/docker/app.yml up -d` and discover that docker_[application]-app_1 was dying because mssql took to long to start. Thus, change `JHIPSTER_SLEEP=30` to `JHIPSTER_SLEEP=90` under [inventory]-app's environment variables in [application]/src/main/docker/app.yml
9. Attempt `docker-compose -f src/main/docker/app.yml up -d` and find that docker_[application]-app_1 and docker_kafka_1 each exited.

For the docker_[application]-app_1 container, stack trace (with pertinent preceding logs) are:
```
2020-08-20 13:51:54.136 WARN 1 --- [ main] org.apache.kafka.clients.ClientUtils : Couldn't resolve server kafka:9092 from bootstrap.servers as DNS resolution failed for kafka

2020-08-20 13:51:54.138 INFO 1 --- [ main] o.a.k.clients.producer.KafkaProducer : [Producer clientId=producer-1] Closing the Kafka producer with timeoutMillis = 0 ms.

2020-08-20 13:51:54.140 WARN 1 --- [ main] ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'inventoryKafkaResource' defined in file [/app/classes/com/herzog/tps/inventory/web/rest/InventoryKafkaResource.class]: Bean instantiation via constructor failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.herzog.tps.inventory.web.rest.InventoryKafkaResource]: Constructor threw exception; nested exception is org.apache.kafka.common.KafkaException: Failed to construct kafka producer

2020-08-20 13:51:54.242 ERROR 1 --- [ main] o.s.boot.SpringApplication : Application run failed


org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'inventoryKafkaResource' defined in file [/app/classes/com/herzog/tps/inventory/web/rest/InventoryKafkaResource.class]: Bean instantiation via constructor failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.herzog.tps.inventory.web.rest.InventoryKafkaResource]: Constructor threw exception; nested exception is org.apache.kafka.common.KafkaException: Failed to construct kafka producer

at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:314)

at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:295)

at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1358)

at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1204)

at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:557)

at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:517)

at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323)

at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:226)

at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321)

at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)

at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:895)

at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:878)

at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:550)

at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:141)

at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:747)

at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397)

at org.springframework.boot.SpringApplication.run(SpringApplication.java:315)

at com.herzog.tps.inventory.InventoryApp.main(InventoryApp.java:63)

Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.herzog.tps.inventory.web.rest.InventoryKafkaResource]: Constructor threw exception; nested exception is org.apache.kafka.common.KafkaException: Failed to construct kafka producer

at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:217)

at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:117)

at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:310)

... 17 common frames omitted

Caused by: org.apache.kafka.common.KafkaException: Failed to construct kafka producer

at org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:433)

at org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:270)

at com.herzog.tps.inventory.web.rest.InventoryKafkaResource.<init>(InventoryKafkaResource.java:35)

at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)

at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)

at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)

at java.base/java.lang.reflect.Constructor.newInstance(Unknown Source)

at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:204)

... 19 common frames omitted

Caused by: org.apache.kafka.common.config.ConfigException: No resolvable bootstrap urls given in bootstrap.servers

at org.apache.kafka.clients.ClientUtils.parseAndValidateAddresses(ClientUtils.java:88)

at org.apache.kafka.clients.ClientUtils.parseAndValidateAddresses(ClientUtils.java:47)

at org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:408)

... 26 common frames omitted
```

For docker_kafka_1, it's full output before exiting was:
```
===> ENV Variables ...

ALLOW_UNSIGNED=false

COMPONENT=kafka

CONFLUENT_DEB_VERSION=1

CONFLUENT_PLATFORM_LABEL=

CONFLUENT_VERSION=5.5.0

CUB_CLASSPATH=/etc/confluent/docker/docker-utils.jar

HOME=/root

HOSTNAME=e4909b0cf0f0

KAFKA_ADVERTISED_HOST_NAME=kafka

KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092

KAFKA_BROKER_ID=1

KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT

KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT

KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1

KAFKA_VERSION=

KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181

LANG=C.UTF-8

PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

PWD=/

PYTHON_PIP_VERSION=8.1.2

PYTHON_VERSION=2.7.9-1

SCALA_VERSION=2.12

SHLVL=1

ZULU_OPENJDK_VERSION=8=8.38.0.13

_=/usr/bin/env



===> User

uid=0(root) gid=0(root) groups=0(root)

===> Configuring ...

===> Running preflight checks ...

===> Check if /var/lib/kafka/data is writable ...

===> Check if Zookeeper is healthy ...

[main] INFO org.apache.zookeeper.ZooKeeper - Client environment:zookeeper.version=3.5.7-f0fdd52973d373ffd9c86b81d99842dc2c7f660e, built on 02/10/2020 11:30 GMT

[main] INFO org.apache.zookeeper.ZooKeeper - Client environment:host.name=e4909b0cf0f0

[main] INFO org.apache.zookeeper.ZooKeeper - Client environment:java.version=1.8.0_212

[main] INFO org.apache.zookeeper.ZooKeeper - Client environment:java.vendor=Azul Systems, Inc.

[main] INFO org.apache.zookeeper.ZooKeeper - Client environment:java.home=/usr/lib/jvm/zulu-8-amd64/jre

[main] INFO org.apache.zookeeper.ZooKeeper - Client environment:java.class.path=/etc/confluent/docker/docker-utils.jar

[main] INFO org.apache.zookeeper.ZooKeeper - Client environment:java.library.path=/usr/java/packages/lib/amd64:/usr/lib64:/lib64:/lib:/usr/lib

[main] INFO org.apache.zookeeper.ZooKeeper - Client environment:java.io.tmpdir=/tmp

[main] INFO org.apache.zookeeper.ZooKeeper - Client environment:java.compiler=<NA>

[main] INFO org.apache.zookeeper.ZooKeeper - Client environment:os.name=Linux

[main] INFO org.apache.zookeeper.ZooKeeper - Client environment:os.arch=amd64

[main] INFO org.apache.zookeeper.ZooKeeper - Client environment:os.version=4.19.104-microsoft-standard

[main] INFO org.apache.zookeeper.ZooKeeper - Client environment:user.name=root

[main] INFO org.apache.zookeeper.ZooKeeper - Client environment:user.home=/root

[main] INFO org.apache.zookeeper.ZooKeeper - Client environment:user.dir=/

[main] INFO org.apache.zookeeper.ZooKeeper - Client environment:os.memory.free=185MB

[main] INFO org.apache.zookeeper.ZooKeeper - Client environment:os.memory.max=2814MB

[main] INFO org.apache.zookeeper.ZooKeeper - Client environment:os.memory.total=190MB

[main] INFO org.apache.zookeeper.ZooKeeper - Initiating client connection, connectString=zookeeper:2181 sessionTimeout=40000 watcher=io.confluent.admin.utils.ZookeeperConnectionWatcher@cc34f4d

[main] INFO org.apache.zookeeper.common.X509Util - Setting -D jdk.tls.rejectClientInitiatedRenegotiation=true to disable client-initiated TLS renegotiation

[main] INFO org.apache.zookeeper.ClientCnxnSocket - jute.maxbuffer value is 4194304 Bytes

[main] INFO org.apache.zookeeper.ClientCnxn - zookeeper.request.timeout value is 0. feature enabled=

[main-SendThread(zookeeper:2181)] INFO org.apache.zookeeper.ClientCnxn - Opening socket connection to server zookeeper/172.22.0.7:2181. Will not attempt to authenticate using SASL (unknown error)

[main-SendThread(zookeeper:2181)] INFO org.apache.zookeeper.ClientCnxn - Socket connection established, initiating session, client: /172.22.0.2:54476, server: zookeeper/172.22.0.7:2181

[main] ERROR io.confluent.admin.utils.ClusterStatus - Timed out waiting for connection to Zookeeper server [zookeeper:2181].

[main-SendThread(zookeeper:2181)] WARN org.apache.zookeeper.ClientCnxn - Client session timed out, have not heard from server in 40000ms for sessionid 0x0

[main] INFO org.apache.zookeeper.ZooKeeper - Session: 0x0 closed

[main-EventThread] INFO org.apache.zookeeper.ClientCnxn - EventThread shut down for session: 0x0
```

**Comment by pascalgrimaud** [comment]
I'm reopening it and will try to reproduce
thx for all steps

**Comment by mrsegen** [comment]
Also the docker_zookeeper_1 had this at the bottom of its output:
```
[2020-08-20 13:50:07,525] WARN Exception causing close of session 0x0: ZooKeeperServer not running (org.apache.zookeeper.server.NIOServerCnxn)

[2020-08-20 13:50:07,526] WARN Unexpected exception (org.apache.zookeeper.server.WorkerService)

java.lang.NullPointerException

at org.apache.zookeeper.server.ZooKeeperServer.removeCnxn(ZooKeeperServer.java:135)

at org.apache.zookeeper.server.NIOServerCnxn.close(NIOServerCnxn.java:602)

at org.apache.zookeeper.server.NIOServerCnxn.doIO(NIOServerCnxn.java:375)

at org.apache.zookeeper.server.NIOServerCnxnFactory$IOWorkRequest.doWork(NIOServerCnxnFactory.java:530)

at org.apache.zookeeper.server.WorkerService$ScheduledWorkRequest.run(WorkerService.java:155)

at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)

at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)

at java.lang.Thread.run(Thread.java:748)
```

Though on another docker-compose attempt, after running `./gradlew bootJar -Pprod jibDockerBuild`, I could not reproduce the full issue. However:
 - The above zookeeper output still occurred
 - The above docker_[application]-app_1 output still occurred, but the application ran (but had separate seemingly unrelated issues with the app directing browser to http://keycloak:9080/... when clicking Sign In

On an additional docker-compose attempt:
 - The zookeeper output still occurred, but the docker_[application]-app_1 output did not occur.

**Comment by mrsegen** [comment]
@pascalgrimaud I have a (further tangential) follow up question: Where in the JHipster repositories is the 30 second default that's generated at `src/main/docker/app.yml` defined? You [might recall](https://github.com/pascalgrimaud/jh-issue-11758/commit/42a331cff981339cfed3f00c2d2505e313b73816) that this was too small because of a 60 second wait that happens in the mssql container.

**Comment by pascalgrimaud** [comment]
The logic is here:
https://github.com/jhipster/generator-jhipster/blob/master/generators/server/templates/src/main/docker/app.yml.ejs#L74-L81

So you're right about mssql app. It should be increase to 60
