### ISSUE TITLE
Subgenerators. Error: Did not provide required argument name

### ISSUE THREAD

**Issue by Selectorrr** [jhipster/generator-jhipster#1179]
```
OS Windows 7 x64
node --version
v0.12.0
npm --version
2.5.1
yo --version
1.3.3
JHipster v2.3.0 
```
```
C:\Users\Selector\Desktop\weather>yo jhipster:entity
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: Did not provide required argument ←[1mname←[22m!
    at EntityGenerator.<anonymous> (C:\Users\Selector\Desktop\jhipster\generator-jhipster-2.3.0\node_modules\yeoman-generator\lib\base.js:324:33)
    at Array.forEach (native)
    at EntityGenerator.Base.checkRequiredArgs (C:\Users\Selector\Desktop\jhipster\generator-jhipster-2.3.0\node_modules\yeoman-generator\lib\base.js:320:19)
    at EntityGenerator.argument (C:\Users\Selector\Desktop\jhipster\generator-jhipster-2.3.0\node_modules\yeoman-generator\lib\base.js:290:8)
    at EntityGenerator.module.exports.Base.extend.constructor (C:\Users\Selector\Desktop\jhipster\generator-jhipster-2.3.0\node_modules\yeoman-generator\lib\nam
ed-base.js:20:10)
    at new EntityGenerator (C:\Users\Selector\Desktop\jhipster\generator-jhipster-2.3.0\entity\index.js:12:33)
    at Environment.instantiate (C:\Users\Selector\AppData\Roaming\npm\node_modules\yo\node_modules\yeoman-environment\lib\environment.js:282:10)
    at Environment.create (C:\Users\Selector\AppData\Roaming\npm\node_modules\yo\node_modules\yeoman-environment\lib\environment.js:259:15)
    at Environment.run (C:\Users\Selector\AppData\Roaming\npm\node_modules\yo\node_modules\yeoman-environment\lib\environment.js:318:24)
    at C:\Users\Selector\AppData\Roaming\npm\node_modules\yo\cli.js:110:9
```

**Comment by jdubois** [comment]
You need to generate your app first, "yo jhipster"

And if you did, we need your .yo-rc.conf file so we know which options you selected

**Comment by gmarziou** [comment]
Maybe he just forgot to add the entity name "yo jhipster:entity" instead of "yo jhipster:entity something"

**Comment by Selectorrr** [comment]
@gmarziou you are right, thanks!
