### ISSUE TITLE
User details are getting null || On React client 

### ISSUE THREAD

**Issue by grajuu** [jhipster/generator-jhipster#11792]
Hey @pascalgrimaud  ,  and @pascalgrimaud 

   I tried generate project with the JDL below, am facing an issue pulling the login "User" Details in "React + Gateway " microservices arch.
The User details are coming as **"null"**
 I discussed this issue [https://github.com/jhipster/jdl-samples/issues/24](url)  this morning, 

Mapping issue "one-to-one"  with React is still existing ..?

```
My local Jhipster version is
jhipster --version
INFO! Using JHipster version installed locally in current project's node_modules
6.8.0

```
Can you please help me in this.
--Thanks.

--JDL 

```
application {
  config {
    baseName gateway,
    packageName com.sample.gateway,
    applicationType gateway,
    authenticationType oauth2,
    prodDatabaseType postgresql,
    searchEngine elasticsearch,
    serviceDiscoveryType eureka,
    testFrameworks [protractor],
    buildTool maven,
    clientFramework react,
    nativeLanguage en,
    languages [en, es] 
  }
  entities Members, Rewards, Address, Product, ProductCategory, ProductOrder, OrderItem, Invoice, Shipment
}

application {
  config {
    baseName school,
    packageName com.sample.users,
    applicationType microservice,
    authenticationType oauth2,
    prodDatabaseType postgresql,
    searchEngine elasticsearch,
    buildTool maven,
    serverPort 8081,
    serviceDiscoveryType eureka
  }
  entities Members, Rewards, Address
}

application {
  config {
    baseName store,
    packageName com.sample.store,
    applicationType microservice,
    authenticationType oauth2,
    databaseType mongodb,
    devDatabaseType mongodb,
    prodDatabaseType mongodb,
    searchEngine elasticsearch,
    buildTool maven,
    enableHibernateCache false,
    serverPort 8082,
    serviceDiscoveryType eureka
  }
 entities Product, ProductCategory, ProductOrder, OrderItem
}

application {
  config {
    baseName invoice,
    applicationType microservice,
    packageName com.sample.invoice,
    authenticationType oauth2,
    prodDatabaseType postgresql,
    buildTool maven,
    serverPort 8083,
    serviceDiscoveryType eureka
  }
  entities Invoice, Shipment
}


// Customer for the store
entity Members {
  firstName String required,
    lastName String required,
    gender Gender required,
    who Who required,
    email String required pattern(/^[^@\s]+@[^@\s]+\.[^@\s]+$/)
    age BigDecimal
}
// Address table for both Student and Faculty 
entity Address{
  addressLine1 String,
    addressLine2 String,
    city String,
    country String,
    primaryPhone String ,
    secondryPhone String
}
enum Gender {
  MALE, FEMALE, OTHER
}
enum Who {
  STUDENT, FACULTY, ADMIN
}
entity Rewards {
  facultyName String ,
        studentName String,
        timestamp ZonedDateTime required,
        rewardReceved BigDecimal,
        date Instant required,
        content TextBlob required
}
/**
 * Entities for store microservice
 */
// Product sold by the Online store 
entity Product {
  name String required
    description String
    price BigDecimal required min(0)
    size Size required
    image ImageBlob
}
enum Size {
  S, M, L, XL, XXL
}
entity ProductCategory {
  name String required,
    description String
}
entity ProductOrder {
  placedDate Instant required,
    email String required pattern(/^[^@\s]+@[^@\s]+\.[^@\s]+$/),
    status OrderStatus required,
    code String required,
    invoiceId Long,
    customer String required
}
enum OrderStatus {
  COMPLETED, PENDING, CANCELLED
}
entity OrderItem {
  quantity Integer required min(0)
    totalPrice BigDecimal required min(0)
    status OrderItemStatus required
}
enum OrderItemStatus {
  AVAILABLE, OUT_OF_STOCK, BACK_ORDER
}
/* Entities for Invoice microservice */
entity Invoice {
  code String required
    date Instant required
    details String
    status InvoiceStatus required
    paymentMethod PaymentMethod required
    paymentDate Instant required
    paymentAmount BigDecimal required
}
enum InvoiceStatus {
  PAID, ISSUED, CANCELLED
}
entity Shipment {
  trackingCode String
    date Instant required
    details String
}
enum PaymentMethod {
  CREDIT_CARD, CASH_ON_DELIVERY, PAYPAL
}
/* Entities for notification microservice */
entity Notification {
  date Instant required
    details String
    sentDate Instant required
    format NotificationType required
    userId Long required
    productId Long required
}
enum NotificationType {
  EMAIL, SMS, PARCEL
}
relationship ManyToOne {
  OrderItem{product(name) required} to Product
}
relationship OneToMany {
  Members{address} to Address{members(email) required} ,
  Members{rewards} to Rewards{members(email) required} ,
  ProductOrder{orderItem} to OrderItem{order(code) required} , 
  ProductCategory{product} to Product{productCategory(name)},
  Invoice{shipment} to Shipment{invoice(code) required}
}
relationship OneToOne {
  Members{user(login) required} to User
}
service Invoice, Shipment, Product, ProductCategory, ProductOrder, OrderItem with serviceClass
paginate Invoice, Shipment, Product, Members, ProductOrder, OrderItem with pagination
// MicroServices 
microservice Product, ProductOrder, ProductCategory, OrderItem with store
microservice Members, Address, Rewards with school
microservice Invoice, Shipment with invoice
microservice Notification with notification
// will be created under 'docker-compose' folder
deployment {
  deploymentType docker-compose
  appsFolders [gateway, school, store, invoice]
  dockerRepositoryName "govindraju9999"
  consoleOptions [zipkin]
}
```
 
**Exception in Logger**

`Bad Request: Validation failed for argument [0] in public org.springframework.http.ResponseEntity<com.samplel.users.domain.Members> com.sample.users.web.rest.MembersResource.createMembers(com.sample.users.domain.Members) throws java.net.URISyntaxException: [Field error in object 'members' on field 'user': rejected value [null]; codes [NotNull.members.user,NotNull.user,NotNull.com.sample.users.domain.User,NotNull]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [members.user,user]; arguments []; default message [user]]; default message [must not be null]]
`

**Comment by MathieuAA** [comment]
This error looks like #11514, the fix will be released for v6.9.0

**Comment by grajuu** [comment]
Hey @MathieuAA ,

         am not sure, should i re-open here,   


I update version
```
$jhipster --version
INFO! Using JHipster version installed globally
6.9.0    
```
but am facing 

issue while saving above JDL microservice  "school"

![image](https://user-images.githubusercontent.com/44188062/82232046-afd83300-994b-11ea-993a-4bb20dca73fe.png)


```
javax.validation.ConstraintViolationException: Validation failed for classes [com.tis.school.users.domain.User] during persist time for groups [javax.validation.groups.Default, ]
List of constraint violations:[
        ConstraintViolationImpl{interpolatedMessage='must not be null', propertyPath=login, rootBeanClass=class com.tis.school.users.domain.User, messageTemplate='{javax.validation.constraints.NotNull.message}'}
]

```

Full trace below :

```
org.springframework.transaction.TransactionSystemException: Could not commit JPA transaction; nested exception is javax.persistence.RollbackException: Error while committing the transaction
        at org.springframework.orm.jpa.JpaTransactionManager.doCommit(JpaTransactionManager.java:543)
        at org.springframework.transaction.support.AbstractPlatformTransactionManager.processCommit(AbstractPlatformTransactionManager.java:743)
        at org.springframework.transaction.support.AbstractPlatformTransactionManager.commit(AbstractPlatformTransactionManager.java:711)
        at org.springframework.transaction.interceptor.TransactionAspectSupport.commitTransactionAfterReturning(TransactionAspectSupport.java:631)
        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:385)
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:118)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
        at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:139)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
        at org.springframework.data.jpa.repository.support.CrudMethodMetadataPostProcessor$CrudMethodMetadataPopulatingMethodInterceptor.invoke(CrudMethodMetadataPostProcessor.java:178)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
        at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:95)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212)
        at com.sun.proxy.$Proxy234.save(Unknown Source)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
        at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:344)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:198)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
        at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:139)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212)
        at com.sun.proxy.$Proxy234.save(Unknown Source)
        at com.tis.school.users.web.rest.MembersResource.createMembers(MembersResource.java:74)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:190)
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138)
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:105)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:879)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:793)
        at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1040)
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:943)
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
        at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:523)
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:590)
        at io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:74)
        at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:129)
        at org.springframework.web.filter.CorsFilter.doFilterInternal(CorsFilter.java:92)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
        at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
        at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:320)
        at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:126)
        at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:90)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
        at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:118)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
        at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:137)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
        at org.springframework.security.oauth2.client.web.OAuth2AuthorizationCodeGrantFilter.doFilterInternal(OAuth2AuthorizationCodeGrantFilter.java:146)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
        at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:111)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
        at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:158)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
        at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:63)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
        at org.springframework.security.oauth2.server.resource.web.BearerTokenAuthenticationFilter.doFilterInternal(BearerTokenAuthenticationFilter.java:130)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
        at org.springframework.security.oauth2.client.web.OAuth2AuthorizationRequestRedirectFilter.doFilterInternal(OAuth2AuthorizationRequestRedirectFilter.java:160)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
        at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:116)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
        at org.springframework.security.web.header.HeaderWriterFilter.doHeadersAfter(HeaderWriterFilter.java:92)
        at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:77)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
        at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:105)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
        at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:56)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
        at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:215)
        at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:178)
        at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:358)
        at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:271)
        at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
        at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
        at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
        at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
        at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
        at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
        at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
        at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
        at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:109)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
        at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
        at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
        at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
        at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
        at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
        at io.undertow.servlet.handlers.FilterHandler.handleRequest(FilterHandler.java:84)
        at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62)
        at io.undertow.servlet.handlers.ServletChain$1.handleRequest(ServletChain.java:68)
        at io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36)
        at io.undertow.servlet.handlers.RedirectDirHandler.handleRequest(RedirectDirHandler.java:68)
        at io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:132)
        at io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57)
        at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
        at io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46)
        at io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:64)
        at io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:60)
        at io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:77)
        at io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43)
        at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
        at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
        at io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:269)
        at io.undertow.servlet.handlers.ServletInitialHandler.access$100(ServletInitialHandler.java:78)
        at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:133)
        at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:130)
        at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:48)
        at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
        at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:249)
        at io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:78)
        at io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:99)
        at io.undertow.server.Connectors.executeRootHandler(Connectors.java:376)
        at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:830)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
Caused by: javax.persistence.RollbackException: Error while committing the transaction
        at org.hibernate.internal.ExceptionConverterImpl.convertCommitException(ExceptionConverterImpl.java:81)
        at org.hibernate.engine.transaction.internal.TransactionImpl.commit(TransactionImpl.java:104)
        at org.springframework.orm.jpa.JpaTransactionManager.doCommit(JpaTransactionManager.java:534)
        ... 134 common frames omitted
Caused by: javax.validation.ConstraintViolationException: Validation failed for classes [com.tis.school.users.domain.User] during persist time for groups [javax.validation.groups.Default, ]
List of constraint violations:[
        ConstraintViolationImpl{interpolatedMessage='must not be null', propertyPath=login, rootBeanClass=class com.tis.school.users.domain.User, messageTemplate='{javax.validation.constraints.NotNull.message}'}
]
        at org.hibernate.cfg.beanvalidation.BeanValidationEventListener.validate(BeanValidationEventListener.java:140)
        at org.hibernate.cfg.beanvalidation.BeanValidationEventListener.onPreInsert(BeanValidationEventListener.java:80)
        at org.hibernate.action.internal.EntityInsertAction.preInsert(EntityInsertAction.java:227)
        at org.hibernate.action.internal.EntityInsertAction.execute(EntityInsertAction.java:100)
        at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:604)
        at org.hibernate.engine.spi.ActionQueue.lambda$executeActions$1(ActionQueue.java:478)
        at java.base/java.util.LinkedHashMap.forEach(Unknown Source)
        at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:475)
        at org.hibernate.event.internal.AbstractFlushingEventListener.performExecutions(AbstractFlushingEventListener.java:348)
        at org.hibernate.event.internal.DefaultFlushEventListener.onFlush(DefaultFlushEventListener.java:40)
        at org.hibernate.event.service.internal.EventListenerGroupImpl.fireEventOnEachListener(EventListenerGroupImpl.java:102)
        at org.hibernate.internal.SessionImpl.doFlush(SessionImpl.java:1352)
        at org.hibernate.internal.SessionImpl.managedFlush(SessionImpl.java:443)
        at org.hibernate.internal.SessionImpl.flushBeforeTransactionCompletion(SessionImpl.java:3202)
        at org.hibernate.internal.SessionImpl.beforeTransactionCompletion(SessionImpl.java:2370)
        at org.hibernate.engine.jdbc.internal.JdbcCoordinatorImpl.beforeTransactionCompletion(JdbcCoordinatorImpl.java:447)
        at org.hibernate.resource.transaction.backend.jdbc.internal.JdbcResourceLocalTransactionCoordinatorImpl.beforeCompletionCallback(JdbcResourceLocalTransactionCoordinatorImpl.java:183)
        at org.hibernate.resource.transaction.backend.jdbc.internal.JdbcResourceLocalTransactionCoordinatorImpl.access$300(JdbcResourceLocalTransactionCoordinatorImpl.java:40)
        at org.hibernate.resource.transaction.backend.jdbc.internal.JdbcResourceLocalTransactionCoordinatorImpl$TransactionDriverControlImpl.commit(JdbcResourceLocalTransactionCoordinatorImpl.java:281)
        at org.hibernate.engine.transaction.internal.TransactionImpl.commit(TransactionImpl.java:101)
        ... 135 common frames omitted
```

---- May be is it because of   LOGIN_REGEX. patron ..?

**Comment by MathieuAA** [comment]
Weird... what about what @SudharakaP suggested:
> Please refer to the above PR and all you have to do is replace the line entity.user = users[values.user] by entity.user = values.user within the customer-update.tsx class (in store app).

**Comment by MathieuAA** [comment]
BTW, are you sure you upgraded to the latest version?

**Comment by grajuu** [comment]
:D  Yes , i did 

![image](https://user-images.githubusercontent.com/44188062/82235053-dac48600-994f-11ea-95b1-c19c2a37277e.png)

Hope this helps.

**Comment by MathieuAA** [comment]
And your app uses the latest version?

**Comment by grajuu** [comment]
Yes it does , as far as i know,
i generated with latest version so eventually it should.

let me know where i can find that i.e command to find app version or jhipster  Registry can help ..?

**Comment by grajuu** [comment]
> Weird... what about what @SudharakaP suggested:
> 
> > Please refer to the above PR and all you have to do is replace the line entity.user = users[values.user] by entity.user = values.user within the customer-update.tsx class (in store app).

 ```
};
      entity.user = values.user;

```
it's already fetching from template.

**Comment by MathieuAA** [comment]
Alright, I guess we should reopen it then and try to reproduce this

**Comment by grajuu** [comment]
@MathieuAA  did you get a chance to reproduce this ..? with above JDL .
Please let me know when you get a chance.

**Comment by MathieuAA** [comment]
I'll have more time tonight.

**Comment by ruddell** [comment]
It's reproducible, and related to the OAuth2 User mapping code in the microservice.  

In Angular, we pass the whole User object `"user": {"id": "1", "login": "system", "firstName": "System" .... }`

In React we only pass the ID `"user":{"id":"1"}`, which results in an invalid `User` since `login` is a required field.  This is because the value returned from the `select` box only returns the `id`.  

Fixed by finding the user in `props.user` with the matching id.

```
-      entity.user = values.user.id;
+      entity.user = props.users.find(user => user.id === values.user.id);
```

I also can't seem to select users other than `system` in the dropdown, even though I logged into an Okta account which should have synced to the database. I may be missing something here though, did not look into this.

**Comment by grajuu** [comment]
Is it merged to current version.?

**Comment by ruddell** [comment]
@grajuu It will be in the next release after the pull request is merged.

You can also make the change manually to workaround the issue until the next release. You can see the required change in my last comment.

**Comment by grajuu** [comment]
Sure @ruddell i will try that, 
How about selecting users other than system ..?
--Thanks

**Comment by ruddell** [comment]
@grajuu The "Selecting users other than system" issue is here: https://github.com/jhipster/generator-jhipster/issues/11836

**Comment by grajuu** [comment]
Then we are good with Saving part with above suggested changes. 
--Thanks.
