### ISSUE TITLE
Reactive Microservices doesn't work in Docker Compose

### ISSUE THREAD

**Issue by mraible** [jhipster/generator-jhipster#11819]
##### **Overview of the issue**

There's an error in the gateway on startup when using Docker Compose to run a reactive microservice architecture.

```
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'webFluxRequestHandlerProvider' defined in URL [jar:file:/app/libs/springfox-spring-webflux-3.0.0-SNAPSHOT.jar!/springfox/documentation/spring/web/plugins/WebFluxRequestHandlerProvider.class]: 
Unsatisfied dependency expressed through constructor parameter 1; nested exception is org.springframework.beans.factory.BeanCreationException: 
Error creating bean with name 'webEndpointReactiveHandlerMapping' defined in class path resource [org/springframework/boot/actuate/autoconfigure/endpoint/web/reactive/WebFluxEndpointManagementContextConfiguration.class]: 
Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: 
Failed to instantiate [org.springframework.boot.actuate.endpoint.web.reactive.WebFluxEndpointHandlerMapping]: 
Factory method 'webEndpointReactiveHandlerMapping' threw exception; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: 
Error creating bean with name 'gatewayControllerEndpoint' defined in class path resource 
[org/springframework/cloud/gateway/config/GatewayAutoConfiguration$GatewayActuatorConfiguration.class]: 
Unsatisfied dependency expressed through method 'gatewayControllerEndpoint' parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'gatewayMetricFilter' defined in class path resource 
[org/springframework/cloud/gateway/config/GatewayMetricsAutoConfiguration.class]: Unsatisfied dependency expressed through method 'gatewayMetricFilter' parameter 0; nested exception is org.springframework.beans.factory.NoUniqueBeanDefinitionException: 
No qualifying bean of type 'io.micrometer.core.instrument.MeterRegistry' available: expected 
single matching bean but found 2: prometheusMeterRegistry,consoleLoggingRegistry

2020-05-19 03:07:17.885 ERROR 1 --- [ main] o.s.b.d.LoggingFailureAnalysisReporter :

***************************

APPLICATION FAILED TO START

Description:

Parameter 0 of method gatewayMetricFilter in org.springframework.cloud.gateway.config.GatewayMetricsAutoConfiguration required a single bean, but 2 were found:

- prometheusMeterRegistry: defined by method 'prometheusMeterRegistry' in class path resource [org/springframework/boot/actuate/autoconfigure/metrics/export/prometheus/PrometheusMetricsExportAutoConfiguration.class]

- consoleLoggingRegistry: defined by method 'consoleLoggingRegistry' in class path resource [io/github/jhipster/config/metric/JHipsterLoggingMetricsExportConfiguration.class]

Action:

Consider marking one of the beans as @Primary, updating the consumer to accept multiple beans, or using @Qualifier to identify the bean that should be consumed
```

##### **Motivation for or Use Case**

I have a demo where I show how to create microservices with JHipster. I'm trying to adapt it to use reactive. 

##### **Reproduce the error**

1. Create apps by importing the following JDL:

```
application {
  config {
    baseName gateway,
    reactive true,
    packageName com.okta.developer.gateway,
    applicationType gateway,
    authenticationType oauth2,
    databaseType neo4j,
    devDatabaseType neo4j,
    prodDatabaseType neo4j,
    enableHibernateCache false,
    serviceDiscoveryType eureka,
    testFrameworks [protractor]
  }
  entities Blog, Post, Tag, Product
}

application {
  config {
    baseName blog,
    reactive true,
    packageName com.okta.developer.blog,
    applicationType microservice,
    authenticationType oauth2,
    databaseType couchbase,
    devDatabaseType couchbase,
    prodDatabaseType couchbase,
    enableHibernateCache false,
    serverPort 8081,
    serviceDiscoveryType eureka
  }
  entities Blog, Post, Tag
}

application {
  config {
    baseName store,
    reactive true,
    packageName com.okta.developer.store,
    applicationType microservice,
    authenticationType oauth2,
    databaseType mongodb,
    devDatabaseType mongodb,
    prodDatabaseType mongodb,
    enableHibernateCache false,
    serverPort 8082,
    serviceDiscoveryType eureka
  }
  entities Product
}

entity Blog {
  name String required minlength(3),
  handle String required minlength(2)
}

entity Post {
  title String required,
  content TextBlob required,
  date Instant required
}

entity Tag {
  name String required minlength(2)
}

entity Product {
  title String required,
  price BigDecimal required min(0),
  image ImageBlob
}

relationship ManyToOne {
  Blog{user(login)} to User,
  Post{blog(name)} to Blog
}

relationship ManyToMany {
  Post{tag(name)} to Tag{post}
}

paginate Post, Tag with infinite-scroll
paginate Product with pagination

microservice Product with store
microservice Blog, Post, Tag with blog

deployment {
  deploymentType docker-compose
  appsFolders [gateway, blog, store]
  dockerRepositoryName "mraible"
  monitoring elk
  consoleOptions [zipkin]
}
```

Then, create Docker containers for each project.

```
./mvnw package -Pprod -DskipTests jib:dockerBuild
```

Finally, cd into the `docker-compose` directory and run `docker-compose up`. 

##### **JHipster Version(s)**

6.9.0

**Comment by atomfrede** [comment]
Do you set `jhipster.metrics.logs.enabled` to false? I guess we can remove https://github.com/jhipster/jhipster/blob/master/jhipster-framework/src/main/java/io/github/jhipster/config/metric/JHipsterLoggingMetricsExportConfiguration.java soon as we have removed dropwizard by now, or do I remember wrong?

**Comment by mraible** [comment]
Where do I need to set this? In the gateway or in JHipster Registry / Spring Cloud Config so it applies to all apps?

**Comment by vishal423** [comment]
In generated applications, `jhipster.metrics.logs.enabled` should be set to `false` by default https://github.com/jhipster/generator-jhipster/blob/0e4b8dc74087603bc781ce2d9983251722af0314/generators/server/templates/src/main/resources/config/application-prod.yml.ejs#L360 , however, in the `docker-compose` cloud config, it's `true` by default https://github.com/jhipster/generator-jhipster/blob/0e4b8dc74087603bc781ce2d9983251722af0314/generators/docker-compose/templates/central-server-config/application.yml.ejs#L36  To temporarily resolve the issue, you can disable that in the cloud-config configuration.

**Comment by atomfrede** [comment]
Thanks @vishal423 you've been faster :) 

https://github.com/jhipster/generator-jhipster/blob/master/generators/docker-compose/templates/central-server-config/application.yml.ejs#L34

Should be false imho too.

**Comment by vishal423** [comment]
I think the better solution should be to also check for `prometheus` enablement

**Comment by atomfrede** [comment]
Prometheus is enabled by default if I am not mistaken

**Comment by vishal423** [comment]
It's a bit cluttered. If you use docker-compose, then, it's enabled as default

**Comment by atomfrede** [comment]
Thats true, but from reading the documentation I would expect it to be enabled by default everywhere. Anyways checking of prometheus was selected and disable the console exporter and when elk is selected we should disable prometheus, wdyt?

**Comment by vishal423** [comment]
sounds good to me

**Comment by mraible** [comment]
If I change `docker-compose/central-server-config/application.yml` to disable metrics, the gateway starts up.

```yaml
jhipster:
  ...
  metrics:
    logs: # report metrics in the logs
      enabled: false
```

However, when it redirects back to the app after login with Keycloak, it fails to connect to Neo4j.

<img width="1118" alt="Screen Shot 2020-05-19 at 9 09 11 AM" src="https://user-images.githubusercontent.com/17892/82343946-b1881200-99b0-11ea-8385-e48ac48b587a.png">

The error in the logs is:

```
gateway_1                     | 2020-05-19 15:08:57.611 ERROR 1 --- [o4jDriverIO-2-7] a.w.r.e.AbstractErrorWebExceptionHandler : [008fe07a-10]  500 Server Error for HTTP GET "/login/oauth2/code/oidc?state=GGFuKVg8DurzBnD9jJWydAB8DtmWKTANKb6v8AzFAk8%3D&session_state=1ad847f1-3f4b-40df-ab3d-b738f4a97a39&code=6eac56e7-a3fe-4ac8-9977-02fc8855394f.1ad847f1-3f4b-40df-ab3d-b738f4a97a39.1eabef67-6473-4ba8-b07c-14bdbae4aaed"
gateway_1                     |
gateway_1                     | org.neo4j.driver.exceptions.ServiceUnavailableException: Unable to connect to localhost:7687, ensure the database is running and that there is a working network connection to it.
gateway_1                     | 	at org.neo4j.driver.internal.async.connection.ChannelConnectedListener.databaseUnavailableError(ChannelConnectedListener.java:76)
gateway_1                     | 	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException:
gateway_1                     | Error has been observed at the following site(s):
```

**Comment by mraible** [comment]
The metrics issue doesn't seem to be related to Neo4j. If I try it with MongoDB in the gateway, it fails too:

```
2020-05-19 15:28:37.087 WARN 1 --- [ main] onfigReactiveWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'webFluxRequestHandlerProvider' defined in URL [jar:file:/app/libs/springfox-spring-webflux-3.0.0-SNAPSHOT.jar!/springfox/documentation/spring/web/plugins/WebFluxRequestHandlerProvider.class]: 
Unsatisfied dependency expressed through constructor parameter 1; nested exception is org.springframework.beans.factory.BeanCreationException: 
Error creating bean with name 'webEndpointReactiveHandlerMapping' defined in class path resource [org/springframework/boot/actuate/autoconfigure/endpoint/web/reactive/WebFluxEndpointManagementContextConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.boot.actuate.endpoint.web.reactive.WebFluxEndpointHandlerMapping]: Factory method 'webEndpointReactiveHandlerMapping' threw exception; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'gatewayControllerEndpoint' defined in class path resource [org/springframework/cloud/gateway/config/GatewayAutoConfiguration$GatewayActuatorConfiguration.class]: Unsatisfied dependency expressed through method 'gatewayControllerEndpoint' parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'gatewayMetricFilter' defined in class path resource [org/springframework/cloud/gateway/config/GatewayMetricsAutoConfiguration.class]: Unsatisfied dependency expressed through method 'gatewayMetricFilter' parameter 0; nested exception is org.springframework.beans.factory.NoUniqueBeanDefinitionException: No qualifying bean of type 'io.micrometer.core.instrument.MeterRegistry' available: expected single matching bean but found 2: prometheusMeterRegistry,consoleLoggingRegistry

2020-05-19 15:28:39.357 ERROR 1 --- [ main] o.s.b.d.LoggingFailureAnalysisReporter :

***************************

APPLICATION FAILED TO START

Description:

Parameter 0 of method gatewayMetricFilter in org.springframework.cloud.gateway.config.GatewayMetricsAutoConfiguration required a single bean, but 2 were found:

- prometheusMeterRegistry: defined by method 'prometheusMeterRegistry' in class path resource [org/springframework/boot/actuate/autoconfigure/metrics/export/prometheus/PrometheusMetricsExportAutoConfiguration.class]

- consoleLoggingRegistry: defined by method 'consoleLoggingRegistry' in class path resource [io/github/jhipster/config/metric/JHipsterLoggingMetricsExportConfiguration.class]

Action:

Consider marking one of the beans as @Primary, updating the consumer to accept multiple beans, or using @Qualifier to identify the bean that should be consumed
```

I'll try this PR to see if it fixed it.

**Comment by atomfrede** [comment]
See my comment in the pr. Neo4j is missing in docker compose subgenerator. Will take care of it within the pr

**Comment by atomfrede** [comment]
@mraible The neo4 config is now generated correctly. Still working on the multiple metrics exporter registries, but I will have a solution tonight :)

**Comment by mraible** [comment]
@atomfrede Great! Let me know when you're finished and I can test.

**Comment by atomfrede** [comment]
I have disabled the console reporting for gateway apps only as they seem not to work with multiple metric registries. I tried 
* disable prom and simple metrics exporter -> `NoOpMetricsExporter` is used, which can be disabled
* disable spring cloud gateway metrics -> still `NoOpMetricsExporer` conflicts with the console exporter

Therefore I have created a special config file, such that only the gateway has disabled the console reporting, all other apps behave as before when using elk as monitoring stack.

Result after running `docker-compose up`:

![Peek 2020-05-20 00-09](https://user-images.githubusercontent.com/203401/82383803-d753fc00-9a2e-11ea-9e9b-7a8ca26b29b6.gif)

**Comment by mraible** [comment]
@atomfrede I tried updating from your `11819-docker-compose-monitoring-fixes` branch and tests fail when I build a Docker image for the gateway app.

```
./mvnw -ntp -Pprod verify jib:dockerBuild
```

It seems like it's in an endless loop.

```
***************************
APPLICATION FAILED TO START
***************************

Description:

Parameter 0 of constructor in com.okta.developer.gateway.service.AuditEventService required a bean named 'reactiveNeo4jTemplate' that could not be found.


Action:

Consider defining a bean named 'reactiveNeo4jTemplate' in your configuration.

2020-05-19 18:21:54.265 ERROR 43024 --- [           main] o.s.test.context.TestContextManager      : Caught exception while allowing TestExecutionListener [org.springframework.boot.test.autoconfigure.SpringBootDependencyInjectionTestExecutionListener@7c72d717] to prepare test instance [com.okta.developer.gateway.web.rest.AuditResourceIT@61367c46]

java.lang.IllegalStateException: Failed to load ApplicationContext
	at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContext(DefaultCacheAwareContextLoaderDelegate.java:132)
	at org.springframework.test.context.support.DefaultTestContext.getApplicationContext(DefaultTestContext.java:123)
	at org.springframework.test.context.support.DependencyInjectionTestExecutionListener.injectDependencies(DependencyInjectionTestExecutionListener.java:118)
	at org.springframework.test.context.support.DependencyInjectionTestExecutionListener.prepareTestInstance(DependencyInjectionTestExecutionListener.java:83)
	at org.springframework.boot.test.autoconfigure.SpringBootDependencyInjectionTestExecutionListener.prepareTestInstance(SpringBootDependencyInjectionTestExecutionListener.java:43)
	at org.springframework.test.context.TestContextManager.prepareTestInstance(TestContextManager.java:244)
	at org.springframework.test.context.junit.jupiter.SpringExtension.postProcessTestInstance(SpringExtension.java:98)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.lambda$invokeTestInstancePostProcessors$5(ClassBasedTestDescriptor.java:337)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.executeAndMaskThrowable(ClassBasedTestDescriptor.java:342)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.lambda$invokeTestInstancePostProcessors$6(ClassBasedTestDescriptor.java:337)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1654)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.StreamSpliterators$WrappingSpliterator.forEachRemaining(StreamSpliterators.java:312)
	at java.base/java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:735)
	at java.base/java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:734)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.invokeTestInstancePostProcessors(ClassBasedTestDescriptor.java:336)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.instantiateAndPostProcessTestInstance(ClassBasedTestDescriptor.java:259)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.lambda$testInstancesProvider$2(ClassBasedTestDescriptor.java:252)
	at java.base/java.util.Optional.orElseGet(Optional.java:369)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.lambda$testInstancesProvider$3(ClassBasedTestDescriptor.java:251)
	at org.junit.jupiter.engine.execution.TestInstancesProvider.getTestInstances(TestInstancesProvider.java:29)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$prepare$0(TestMethodTestDescriptor.java:106)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.prepare(TestMethodTestDescriptor.java:105)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.prepare(TestMethodTestDescriptor.java:69)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$prepare$1(NodeTestTask.java:107)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.prepare(NodeTestTask.java:107)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:75)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:229)
	at org.junit.platform.launcher.core.DefaultLauncher.lambda$execute$6(DefaultLauncher.java:197)
	at org.junit.platform.launcher.core.DefaultLauncher.withInterceptedStreams(DefaultLauncher.java:211)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:191)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:128)
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invokeAllTests(JUnitPlatformProvider.java:154)
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invoke(JUnitPlatformProvider.java:127)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:377)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:138)
	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:465)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:451)
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'securityConfiguration' defined in file [/Users/mraible/reactive-apps/gateway/target/classes/com/okta/developer/gateway/config/SecurityConfiguration.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'auditEventService' defined in file [/Users/mraible/reactive-apps/gateway/target/classes/com/okta/developer/gateway/service/AuditEventService.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'persistenceAuditEventRepository': Cannot resolve reference to bean 'reactiveNeo4jTemplate' while setting bean property 'neo4jOperations'; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No bean named 'reactiveNeo4jTemplate' available
```

**Comment by atomfrede** [comment]
That might be already on master the case, properly because of the change to dynamic property sources (daily build fails too will have a look). I build it with skip tests as you did first.

**Comment by atomfrede** [comment]
@mraible Try again please. I reverted the dynamic property source and I now remember I tried that already and it just didn't work.

**Comment by mraible** [comment]
I tried again and now I'm getting an error from couchbase when building the `blog` container.

```
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'couchmove' defined in class path resource [com/okta/developer/blog/config/DatabaseConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.github.couchmove.Couchmove]: Factory method 'couchmove' threw exception; nested exception is com.couchbase.client.java.error.CannotRetryException: maximum number of attempts reached after 3 retries
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:656)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:636)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1338)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1177)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:557)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:517)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:226)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:895)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:878)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:550)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:747)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315)
	at org.springframework.boot.test.context.SpringBootContextLoader.loadContext(SpringBootContextLoader.java:124)
	at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContextInternal(DefaultCacheAwareContextLoaderDelegate.java:99)
	at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContext(DefaultCacheAwareContextLoaderDelegate.java:124)
	... 66 common frames omitted
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.github.couchmove.Couchmove]: Factory method 'couchmove' threw exception; nested exception is com.couchbase.client.java.error.CannotRetryException: maximum number of attempts reached after 3 retries
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:651)
	... 84 common frames omitted
Caused by: com.couchbase.client.java.error.CannotRetryException: maximum number of attempts reached after 3 retries
```

**Comment by atomfrede** [comment]
Its again the tests, right? Whats going on there? I will test later too and keep you updated (but it seems not related to the docker compose issue). Can you try if building the apps without tests and see if at least now the docker compose setup is correct?

**Comment by mraible** [comment]
Yes, it's the tests. I tried again and it worked this time. Maybe testcontainers is flaky for couchbase?

**Comment by mraible** [comment]
@atomfrede I can confirm that your branch fixes this issue.

```
➜  gateway git:(master) npm run e2e

> gateway@0.0.1-SNAPSHOT e2e /Users/mraible/reactive-apps/gateway
> protractor src/test/javascript/protractor.conf.js

[10:06:18] I/launcher - Running 1 instances of WebDriver
[10:06:18] I/direct - Using ChromeDriver directly...


  account
    ✓ should fail to login with bad password (2182ms)
    ✓ should login successfully with admin account (3770ms)
    ✓ should navigate to 404 not found error page on non existing route and show user own navbar if valid authentication exists

  administration
    ✓ should load metrics
    ✓ should load health
    ✓ should load configuration
    ✓ should load audits
    ✓ should load logs

  Blog e2e test
    ✓ should load Blogs (2051ms)
    ✓ should load create Blog page
    ✓ should create and save Blogs (6412ms)
    ✓ should delete last Blog (5280ms)

  Post e2e test
    ✓ should load Posts
    ✓ should load create Post page
    ✓ should create and save Posts (5918ms)
    ✓ should delete last Post (5251ms)

  Tag e2e test
    ✓ should load Tags
    ✓ should load create Tag page
    ✓ should create and save Tags (5444ms)
    ✓ should delete last Tag (5229ms)

  Product e2e test
    ✓ should load Products
    ✓ should load create Product page
    ✓ should create and save Products (5799ms)
    ✓ should delete last Product


  24 passing (1m)

[10:07:32] I/launcher - 0 instance(s) of WebDriver still running
[10:07:32] I/launcher - chrome #01 passed
Execution time: 1 min. 15 s.
```

**Comment by atomfrede** [comment]
The problem with failing couchbase tests are due to some Testcontainers/timeout issue or a "real" bug?

**Comment by mraible** [comment]
@atomfrede I'm not sure. I didn't investigate closely.

**Comment by atomfrede** [comment]
I just did tree runs and it worked every time without any problems.

**Comment by mraible** [comment]
@atomfrede In that case, ship it! 🚀

**Comment by atomfrede** [comment]
Done :rocket:

**Comment by jul13n-cfm7** [comment]
Hello, i have exactly the same parameter 0 error.
Unfortunately upgrade to 6.9.1 did not solve the issue for me.
I am trying to create a reactive gateway application with no database.
Can you help ? Manually playing with boolean for prometheus did not help either.
Many thanks in advance
I joined the yo-rc.json file for exact generation parameters

[config.txt](https://github.com/jhipster/generator-jhipster/files/4715591/config.txt)

**Comment by atomfrede** [comment]
Are you using docker compose too with central configuration server?

**Comment by jul13n-cfm7** [comment]
Hello. No i am simply using a docker image and starting the application. I mapped registry, console and keycloak through variable.

**Comment by atomfrede** [comment]
How did you create the docker image? Can you run the application locally? Did you use the docker-compose deployment generator?

**Comment by jul13n-cfm7** [comment]
The docker image is created with following maven goal : ./mvnw -DskipTests -Pprod -Pzipkin package verify jib:build ... We just use a custom image (that we use for all our microservices) and the registry is private

**Comment by atomfrede** [comment]
In that case can you provide an exact step by step reproducer? Can you check if the gateway has the correct parameters somehow? (obviously setting them didn't work in your case).

**Comment by jul13n-cfm7** [comment]
I'll work on it and get back to you. Many thanks

**Comment by jul13n-cfm7** [comment]
I am trying to review the config yml file embedded in the application. Can you please tell me the important ones that are relevant with the problem "Parameter 0 of method gatewayMetricFilter..." ?

**Comment by atomfrede** [comment]
At least for the original issue you need to disable the exporting of metrics to the logs via 
```
jhipster:
  metrics:
    logs: # do report metrics in the logs for gateway applications
      enabled: false 
```

**Comment by jul13n-cfm7** [comment]
Since i have generated with 6.9.1 i checked and it is set to false

**Comment by atomfrede** [comment]
And what is your exact runtime configuration? Can you start the gateway via maven/gradle? With your ide?

**Comment by jul13n-cfm7** [comment]
I have generated a gateway from scratch with no modifications and have sucessfully launched it with docker so the generator is not involved.

I have compared all yml files under config in my real applications and except the way to connect to registry and keycloak i did not see any difference.

I cannot test from my IDE with keycloak and registry, there are in AWS and for registry inside fargate so not accessible.

**Comment by jul13n-cfm7** [comment]
I am using Java 11 and Maven 3.6 and a specific docker image as base but this last one is working other microservices including another gateway application (but generated with Jhipster 6.6 and so no reactive

**Comment by jul13n-cfm7** [comment]
Actually i just noticed that the error message is not exactly the same, it does not involved the same logging 

```
Parameter 0 of method gatewayMetricFilter in org.springframework.cloud.gateway.config.GatewayMetricsAutoConfiguration required a single bean, but 2 were found:
- simpleMeterRegistry: defined by method 'simpleMeterRegistry' in class path resource [org/springframework/boot/actuate/autoconfigure/metrics/export/simple/SimpleMetricsExportAutoConfiguration.class]	
- consoleLoggingRegistry: defined by method 'consoleLoggingRegistry' in class path resource [io/github/jhipster/config/metric/JHipsterLoggingMetricsExportConfiguration.class]
```

**Comment by atomfrede** [comment]
What is the registry? The jhipster registry? If yes, that is your config server and may hold a configuration overwriting `jhipster.metrics.logs.enabled: false` from the local configuration file. So the metrics export is enabled again. 

See the PR for details: https://github.com/jhipster/generator-jhipster/pull/11822/files

It created a dedicated configuration file for the central configuration service which is used by the gatewayway application.

**Comment by jul13n-cfm7** [comment]
Good point ! I was effectively talking about jhipster registry. I checked files in cloud config server.
I have no specific files for my applications so it should take configuration in application.xml or in application-dev.xml i do not aussi metrics overriding :-(

**Comment by atomfrede** [comment]
Happy to help. I hope my explanation is more or less correct without looking up the docs. Before the application beans are loaded the central config server is asked for configurations and these are merged with the local ones and then used to start and populate the application beans.

**Comment by jul13n-cfm7** [comment]
OK i'll check that every thing is running as expected. I cannot say if in my configuration i use prometheus or not ? Do you know ?

**Comment by atomfrede** [comment]
Prometheus is enabled by default. See our documentation here https://www.jhipster.tech/monitoring/#configuring-metrics-forwarding
