### ISSUE TITLE
Application should not start when liquibase fails to start with dev profile.

### ISSUE THREAD

**Issue by mshima** [jhipster/generator-jhipster#11949]
##### **Overview of the issue**

When liquibase files contains errors, the application starts despite the error.
This causes the application to be on an unpredictable state.

##### **Motivation for or Use Case**

If the application starts it should run correctly.

##### **Reproduce the error**

- Create an all default jhipster app
- Remove `name="id"` from `src/main/resources/config/liquibase/changelog/00000000000000_initial_schema.xml`
- Start the application `./mvnw`
- Despite liquibase error, the application is started and listening at port 8080

```
2020-06-17 17:12:23.900  INFO 89217 --- [  restartedMain] com.mycompany.myapp.LiquibaseErrorApp    : Started LiquibaseErrorApp in 9.78 seconds (JVM running for 10.306)
2020-06-17 17:12:23.906  INFO 89217 --- [  restartedMain] com.mycompany.myapp.LiquibaseErrorApp    :
----------------------------------------------------------
	Application 'liquibase_error' is running! Access URLs:
	Local: 		http://localhost:8080/
	External: 	http://127.0.0.1:8080/
	Profile(s): 	[dev, swagger]
----------------------------------------------------------
2020-06-17 17:12:24.697 ERROR 89217 --- [se-error-task-1] i.g.j.c.liquibase.AsyncSpringLiquibase   : Liquibase could not start correctly, your database is NOT ready: Validation Failed:
     1 changes have validation failures
          column 'name' is required for all columns, config/liquibase/changelog/00000000000000_initial_schema.xml::00000000000001::jhipster


liquibase.exception.ValidationFailedException: Validation Failed:
     1 changes have validation failures
          column 'name' is required for all columns, config/liquibase/changelog/00000000000000_initial_schema.xml::00000000000001::jhipster
	at liquibase.changelog.DatabaseChangeLog.validate(DatabaseChangeLog.java:288)
	at liquibase.Liquibase.update(Liquibase.java:198)
	at liquibase.Liquibase.update(Liquibase.java:179)
	at liquibase.integration.spring.SpringLiquibase.performUpdate(SpringLiquibase.java:366)
	at liquibase.integration.spring.SpringLiquibase.afterPropertiesSet(SpringLiquibase.java:314)
	at org.springframework.boot.autoconfigure.liquibase.DataSourceClosingSpringLiquibase.afterPropertiesSet(DataSourceClosingSpringLiquibase.java:46)
	at io.github.jhipster.config.liquibase.AsyncSpringLiquibase.initDb(AsyncSpringLiquibase.java:118)
	at io.github.jhipster.config.liquibase.AsyncSpringLiquibase.lambda$afterPropertiesSet$0(AsyncSpringLiquibase.java:93)
	at io.github.jhipster.async.ExceptionHandlingAsyncTaskExecutor.lambda$createWrappedRunnable$1(ExceptionHandlingAsyncTaskExecutor.java:78)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)


2020-06-17 17:12:30.956 DEBUG 89217 --- [  XNIO-1 task-7] c.m.m.r.CustomAuditEventRepository       : Enter: add() with argument[s] = [AuditEvent [timestamp=2020-06-17T20:12:30.945Z, principal=anonymousUser, type=AUTHORIZATION_FAILURE, data={details=org.springframework.security.web.authentication.WebAuthenticationDetails@957e: RemoteIpAddress: 127.0.0.1; SessionId: null, type=org.springframework.security.access.AccessDeniedException, message=Access is denied}]]
```

##### **Browsers and Operating System**

-   [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by murdos** [comment]
That's probably because liquibase is launched asynchronously during startup.
Since it only happens with the `dev` profile, I'm not sure this is really an issue. It's better to have an application that always starts faster, since having liquibase errors is not frequent.

**Comment by mshima** [comment]
Probably happens with Heroku profile too.
It probably can be fixed without disabling async.

**Comment by PierreBesson** [comment]
Even if it is started asyncronously, we could call force close the spring application context if it failed to load properly (remember it is only for dev) : https://www.baeldung.com/spring-boot-shutdown#1-close-the-current-application-context

**Comment by pascalgrimaud** [comment]
In fact, Liquibase started asynchronously in dev, not in prod profile.
Anyway, if I remember well, it's start asynchronously with heroku profile too, to allow applications to start with free tier. Otherwise, when it tooks too much time, the applications won't start...

FYI, you can remove the async here:
https://github.com/jhipster/generator-jhipster/blob/master/generators/server/templates/src/main/java/package/config/LiquibaseConfiguration.java.ejs#L70

That's what I did for all my real projects
