### ISSUE TITLE
Can't run integration tests of the application using redis

### ISSUE THREAD

**Issue by topikachu** [jhipster/generator-jhipster#12012]
##### **Overview of the issue**

Can't run integration tests of the application using Redis. The application fails to start because it can't connect to the Redis.
```Java
Caused by: org.redisson.client.RedisConnectionException: Unable to connect to Redis server: localhost/127.0.0.1:6379
	at org.redisson.connection.pool.ConnectionPool$1.lambda$run$0(ConnectionPool.java:159)
	at org.redisson.misc.RedissonPromise.lambda$onComplete$0(RedissonPromise.java:183)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:577)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:551)
```
##### **Motivation for or Use Case**

All integration tests fail. I can't move forward to develop.

##### **Reproduce the error**

Create a monolithic application that uses Redis as cache. Run integration tests. Test fails because of
```java 
Caused by: org.redisson.client.RedisConnectionException: Unable to connect to Redis server: localhost/127.0.0.1:6379
```

##### **Suggest a Fix**

Current Jhipster uses Testcontainers to startup a Redis server.  
Both the startup and @DynamicPropertySource code are in a Junit Extension.   
However, the @DynamicPropertySource method can't be recognized by Spring, because it must be in the test class.

##### **JHipster Version(s)**

```
jhipster  --version
INFO! Using JHipster version installed globally
6.9.1
```
##### **JHipster configuration**

```
INFO! Using JHipster version installed locally in current project's node_modules
INFO! Executing jhipster:info
INFO! Options: from-cli: true
Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
sam@0.0.1-SNAPSHOT /Users/**/git/template/sam-template
└── generator-jhipster@6.9.1

```


##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**


<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.xxx.yyy",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "6.9.1",
    "applicationType": "monolith",
    "baseName": "sam",
    "packageName": "com.xxx.yyy",
    "packageFolder": "com/xxx/yyy",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "redis",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Memory",
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "YourJWTSecretKeyWasReplacedByThisMeaninglessTextByTheJHipsterInfoCommandForObviousSecurityReasons",
    "embeddableLaunchScript": false,
    "useSass": true,
    "clientPackageManager": "npm",
    "clientFramework": "react",
    "clientTheme": "cerulean",
    "clientThemeVariant": "primary",
    "creationTimestamp": 1593313640874,
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [],
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": ["en"],
    "blueprints": [],
    "appsFolders": ["sam-template"],
    "directoryPath": "../",
    "dockerRepositoryName": "",
    "dockerPushCommand": "docker push",
    "kubernetesNamespace": "default",
    "kubernetesServiceType": "Ingress",
    "ingressType": "nginx",
    "ingressDomain": "192.168.99.100.nip.io",
    "monitoring": "prometheus",
    "istio": false
  }
}

</pre>
</details>


##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>


##### **Environment and Tools**

openjdk version "11.0.7" 2020-04-14
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.7+10)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.7+10, mixed mode)

git version 2.17.0

node: v12.18.1

npm: 6.14.5

yeoman: 3.1.0

yarn: 1.6.0

Docker version 19.03.8, build afacb8b

docker-compose version 1.25.5, build 8a1c60f6

INFO! Congratulations, JHipster execution is complete!
```
##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

N/A
##### **Browsers and Operating System**

No OS related issue
-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by atomfrede** [comment]
I can reproduce it. I would suggest we do the same approach as we have for neo4j setting properties in the redis extensions.
