### ISSUE TITLE
Email addresses are NULL in users.csv file

### ISSUE THREAD

**Issue by Rosetjau** [jhipster/generator-jhipster#1224]
Hi,

in the current version of JHipster (2.5.1) the users.csv file does not supply any value for the "email" column; however the initial Liquibase changelog (00000000000000_initial_schema.xml) generates a unique constraint on the email column, which can cause problems for many databases.

I believe the correct course of action would be to keep the unique constraint on the column and inserting some random emails in the csv file.

**Comment by jdubois** [comment]
Yes you are correct, but I can't reproduce your issue: which database are you using?

In the meantime I'm closing this as I can't reproduce.

**Comment by Rosetjau** [comment]
I'm using MS SQL Server 2012. I know, it isn't a DBMS supported out of the box by JHiptser but it's the DBMS of choice in my company, and my first task when creating a new project with JHipster was to switch from MySQL to SQL Server.

The application fails to start and throws the following exception:
`Caused by: com.microsoft.sqlserver.jdbc.SQLServerException: Violation of UNIQUE KEY constraint 'UQ__T_USER__AB6E6164C83765C0'. Cannot insert duplicate key in object 'dbo.T_USER'. The duplicate key value is (<NULL>).
	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:216)
	at com.microsoft.sqlserver.jdbc.TDSTokenHandler.onEOF(tdsparser.java:254)
	at com.microsoft.sqlserver.jdbc.TDSParser.parse(tdsparser.java:84)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.getNextResult(SQLServerStatement.java:1517)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.doExecuteStatement(SQLServerStatement.java:799)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement$StmtExecCmd.doExecute(SQLServerStatement.java:696)
	at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:5696)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:1716)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeCommand(SQLServerStatement.java:180)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeStatement(SQLServerStatement.java:155)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.execute(SQLServerStatement.java:669)
	at com.zaxxer.hikari.proxy.StatementProxy.execute(StatementProxy.java:83)
	at com.zaxxer.hikari.proxy.StatementJavassistProxy.execute(StatementJavassistProxy.java)
	at liquibase.executor.jvm.JdbcExecutor$ExecuteStatementCallback.doInStatement(JdbcExecutor.java:314)
	... 119 more`

If I edit the users.csv file and supply a value for the email column everything works perfectly.

**Comment by jdubois** [comment]
OK, this is not supported, but still you are correct -> I'm reopening this and testing this with MySQL, but of course I won't be able to guarantee it works on MS SQL Server!

**Comment by jdubois** [comment]
One of my ideas was to generate a random name (using the same crypto function as we already use for generating the "remember me" token), and use it to generate random emails usable from mailinator.com

But I guess this could be a security risk: if someone gets your admin email (which isn't well protected, for example using a REST endpoint - it's not ignored in JSON like the password), he can use mailinator to reset your password
