### ISSUE TITLE
Problem with db migration in Reactive application

### ISSUE THREAD

**Issue by Faelivrinx** [jhipster/generator-jhipster#12274]
##### **Overview of the issue**

I generate project with Reactor support and it's looks like db schema hasn't create. I'm trying to login with default credentials after run application, but some exceptions with SQL statements appears.

##### **Motivation for or Use Case**

It should work properly if project builds fine.

##### **Reproduce the error**

Create applications with Reactive support, Posgress as a production db, h2 in-memory as dev db and just try to login.

```
2020-08-19 17:25:00.672 DEBUG 17388 --- [oundedElastic-3] org.fooder.web.rest.UserJWTController    : Exit: authorize() with result = Mono.map ⇢ at org.fooder.web.rest.UserJWTController.authorize(UserJWTController.java:51)
2020-08-19 17:25:00.760 DEBUG 17388 --- [or-http-epoll-3] o.f.security.DomainUserDetailsService    : Authenticating admin
2020-08-19 17:25:00.785 DEBUG 17388 --- [sword-encoder-1] org.fooder.service.AuditEventService     : Enter: saveAuthenticationError() with argument[s] = [admin, org.springframework.data.r2dbc.BadSqlGrammarException: executeMany; bad SQL grammar [SELECT * FROM jhi_user u LEFT JOIN jhi_user_authority ua ON u.id=ua.user_id WHERE u.login = :login]; nested exception is io.r2dbc.spi.R2dbcBadGrammarException: [42102] [42S02] Table "JHI_USER" not found; SQL statement:
SELECT * FROM jhi_user u LEFT JOIN jhi_user_authority ua ON u.id=ua.user_id WHERE u.login = $1 [42102-200]]
2020-08-19 17:25:00.788  WARN 17388 --- [sword-encoder-1] org.fooder.service.AuditEventService     : Event data for message too long (355) has been truncated to 255. Consider increasing column width.
2020-08-19 17:25:00.793 DEBUG 17388 --- [sword-encoder-1] org.fooder.service.AuditEventService     : Exit: saveAuthenticationError() with result = Flux.last ⇢ at org.fooder.service.AuditEventService.saveAuthenticationError(AuditEventService.java:133)
2020-08-19 17:25:00.814 ERROR 17388 --- [sword-encoder-1] o.z.problem.spring.common.AdviceTraits   : Internal Server Error

org.springframework.data.r2dbc.BadSqlGrammarException: executeMany; bad SQL grammar [INSERT INTO jhi_persistent_audit_event (principal, event_date, event_type) VALUES ($1, $2, $3)]; nested exception is io.r2dbc.spi.R2dbcBadGrammarException: [42102] [42S02] Table "JHI_PERSISTENT_AUDIT_EVENT" not found; SQL statement:
INSERT INTO jhi_persistent_audit_event (principal, event_date, event_type) VALUES ($1, $2, $3) [42102-200]
	at org.springframework.data.r2dbc.support.R2dbcExceptionSubclassTranslator.doTranslate(R2dbcExceptionSubclassTranslator.java:84)
	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 

```

##### **Suggest a Fix**

I'm not sure that reactive spring support liquidebase migrations. I can take a look at it.

##### **JHipster Version(s)**

v6.10.1

##### **JHipster configuration**
No additional configuration

##### **Browsers and Operating System**

Ubuntu 20.04.1 LTS, Google Chrome 

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by pascalgrimaud** [comment]
can you post the `jhipster info` plz ?

**Comment by mraible** [comment]
@Faelivrinx Can you please try this again with the latest code and see if it works?

**Comment by mraible** [comment]
@gzsombor Do you have any advice on how to solve this issue? I ask because you're our resident r2dbc guru. :)

**Comment by Faelivrinx** [comment]
@mraible I've checked with version 6.10.3 and still the same problem

**Comment by mraible** [comment]
I checked with JHipster 6.10.5 and you're right, this issue still exists.

```
2020-11-09 18:00:34.316 ERROR 77116 --- [sword-encoder-1] o.z.problem.spring.common.AdviceTraits   : Internal Server Error

org.springframework.data.r2dbc.BadSqlGrammarException: executeMany; bad SQL grammar [INSERT INTO jhi_persistent_audit_event (principal, event_date, event_type) VALUES ($1, $2, $3)]; nested exception is io.r2dbc.spi.R2dbcBadGrammarException: [42102] [42S02] Table "JHI_PERSISTENT_AUDIT_EVENT" not found; SQL statement:
INSERT INTO jhi_persistent_audit_event (principal, event_date, event_type) VALUES ($1, $2, $3) [42102-200]
	at org.springframework.data.r2dbc.support.R2dbcExceptionSubclassTranslator.doTranslate(R2dbcExceptionSubclassTranslator.java:84)
	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException:
Assembly trace from producer [reactor.core.publisher.MonoError] :
```

I also tried with the current main branch. It does NOT happen there. It sounds like we might need to backport some code to the 6.x branch or get a beta release of v7 out the door.

**Comment by mraible** [comment]
Can you please try again with JHipster v7 beta 1? You can also try the `main` branch if you want Spring Boot 2.4 support.

**Comment by Faelivrinx** [comment]
I've just checked `7.0.0-beta.1` and seems to work fine! 👍
It looks like the way of determining DB name has changed since the `2.3.8` spring-boot, so the issue disappeared

**Comment by mraible** [comment]
Thanks for checking @Faelivrinx. I'm closing this issue since it seems to be resolved.
