### ISSUE TITLE
error at the begining of "jhipster" generator command

### ISSUE THREAD

**Issue by elkassar** [jhipster/generator-jhipster#12351]
##### **Overview of the issue**
I get the following stack trace while I'm trying to generate jhipster application:

INFO! Using JHipster version installed globally
events.js:196
      throw er; // Unhandled 'error' event
      ^

Error: Errors Detected in CST Visitor <CstPrettierPrinter>:
	Missing visitor method: <unannPrimitiveTypeWithOptionalDimsSuffix> on CstPrettierPrinter CST Visitor.
    at CstPrettierPrinter.validateVisitor (/usr/local/lib/node_modules/generator-jhipster/node_modules/java-parser/node_modules/chevrotain/lib/src/parse/cst/cst_visitor.js:59:23)
    at new CstPrettierPrinter (/usr/local/lib/node_modules/generator-jhipster/node_modules/prettier-plugin-java/src/cst-printer.js:29:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/generator-jhipster/node_modules/prettier-plugin-java/src/cst-printer.js:133:23)
    at Module._compile (internal/modules/cjs/loader.js:1128:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
    at Module.load (internal/modules/cjs/loader.js:983:32)
    at Function.Module._load (internal/modules/cjs/loader.js:891:14)
    at Module.require (internal/modules/cjs/loader.js:1023:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/generator-jhipster/node_modules/prettier-plugin-java/src/printer.js:2:31)
Emitted 'error' event on Environment instance at:
    at Environment.error (/usr/local/lib/node_modules/generator-jhipster/node_modules/yeoman-environment/lib/environment.js:293:12)
    at Environment.create (/usr/local/lib/node_modules/generator-jhipster/node_modules/yeoman-environment/lib/environment.js:615:19)
    at /usr/local/lib/node_modules/generator-jhipster/cli/cli.js:74:31
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (/usr/local/lib/node_modules/generator-jhipster/cli/cli.js:62:29)
    at Module._compile (internal/modules/cjs/loader.js:1128:30)
    [... lines matching original stack trace ...]
    at Module.require (internal/modules/cjs/loader.js:1023:19)

##### **JHipster Version(s)**
generator-jhipster@6.10.1

##### **Browsers and Operating System**

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by pascalgrimaud** [comment]
I confirm the issue. It comes from prettier, so it's an external lib.
But we need to try to fix the dependencies

**Comment by pascalgrimaud** [comment]
cc @clementdessoude : not sure if it's related to your last release of prettier-java ?

**Comment by clementdessoude** [comment]
Oh, yes it is... It comes from lerna and not using fix dependencies. Can you try to upgrade the prettier-plugin-java to 0.8.1 please?

**Comment by pascalgrimaud** [comment]
@clementdessoude : just tried and it doesn't change anything :(

**Comment by pascalgrimaud** [comment]
FYI, just merged https://github.com/jhipster/generator-jhipster/pull/12353 into master

**Comment by clementdessoude** [comment]
@pascalgrimaud I created the PR for the v6_maintenance branch

**Comment by pascalgrimaud** [comment]
Should be fixed with new release of prettier-java
