### ISSUE TITLE
jhipster abstract class configuration in changelog.xml

### ISSUE THREAD

**Issue by houcine8** [jhipster/generator-jhipster#1246]
I have an inheritance relationship between these 4 classes:
superclass : AbstractLink
subclass : LinkConditional - LinkMultiple - LinkSimple
after generation of changelog.xml file through "mvn liquibase:diff"
I have the following result:
```
<changeSet author="saturne (generated)" id="1426077799600-16">
      <createTable tableName="LinkConditional">
         <column autoIncrement="true" name="id" type="BIGINT">
            <constraints primaryKey="true" primaryKeyName="AbstractLinkPK"/>
         </column>
         <column name="nextStep_id" type="BIGINT"/>
         <column name="previousStep_id" type="BIGINT"/>
         <column name="condition" type="VARCHAR(255)"/>
         <column name="name" type="VARCHAR(255)"/>
      </createTable>
   </changeSet>
   <changeSet author="saturne (generated)" id="1426077799600-17">
      <createTable tableName="LinkMultiple">
         <column autoIncrement="true" name="id" type="BIGINT">
            <constraints primaryKey="true" primaryKeyName="AbstractLinkPK"/>
         </column>
         <column name="nextStep_id" type="BIGINT"/>
         <column name="previousStep_id" type="BIGINT"/>
         <column name="condition" type="VARCHAR(255)"/>
      </createTable>
   </changeSet>
   <changeSet author="saturne (generated)" id="1426077799600-18">
      <createTable tableName="LinkSimple">
         <column autoIncrement="true" name="id" type="BIGINT">
            <constraints primaryKey="true" primaryKeyName="AbstractLinkPK"/>
         </column>
         <column name="nextStep_id" type="BIGINT"/>
         <column name="previousStep_id" type="BIGINT"/>
      </createTable>
   </changeSet>
```
And when I use mvn spring-boot:run to generate the data model I met the following problem :
```
Caused by: liquibase.exception.MigrationFailedException: Migration failed for change set classpath:config/liquibase/changelog/20150311124259_changelog.xml::1426077799600-17::saturne (generated):
     Reason: liquibase.exception.DatabaseException: org.postgresql.util.PSQLException: ERREUR: la relation ½ AbstractLinkPK ╗ existe dÚjÓ
        at liquibase.changelog.ChangeSet.execute(ChangeSet.java:586)
        at liquibase.changelog.visitor.UpdateVisitor.visit(UpdateVisitor.java:43)
        at liquibase.changelog.ChangeLogIterator.run(ChangeLogIterator.java:73)
        at liquibase.Liquibase.update(Liquibase.java:200)
        at liquibase.integration.spring.SpringLiquibase.performUpdate(SpringLiquibase.java:353)
        at liquibase.integration.spring.SpringLiquibase.afterPropertiesSet(SpringLiquibase.java:317)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1625)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1562)
        ... 107 more
```

Any help please?
Thank you.

**Comment by jdubois** [comment]
- this is a Liquibase issue (we don't support inheritance when doing the generation), please submit your bug report to Liquibase
- from the error message: the relationship already exists, so maybe your changelog was already applied? Does this work on an empty database?

**Comment by houcine8** [comment]
I have not tried with an empty database. I will try right now

**Comment by houcine8** [comment]
I still have the same problem I'll ride it to Liquibase

**Comment by houcine8** [comment]
So what should I do if I want to create this scenario entities ?

**Comment by jdubois** [comment]
I have no idea: we don't support inheritance, and of course that should work if you code it, but I have no idea what you have done.

**Comment by houcine8** [comment]
Ok thank you

**Comment by houcine8** [comment]
Finally I resolve it
Just add (strategy = GenerationType.TABLE) to GeneratedValue annotation like this
```
@Entity
@Inheritance(strategy = InheritanceType.TABLE_PER_CLASS)
public abstract class AbstractLink {

    @Id
    @GeneratedValue(strategy = GenerationType.TABLE)
    private Long id;
    @ManyToOne(fetch = FetchType.LAZY)
    private Step previousStep;
    @ManyToOne(fetch = FetchType.LAZY)
    private Step nextStep;
}
```
