### ISSUE TITLE
errors when creating many-to-many relationship

### ISSUE THREAD

**Issue by oceanio** [jhipster/generator-jhipster#1258]
Hi, I have errors when creating a simple many-to-many relationship

``` 
$yo jhipster:entity country
The entity country is being created.
Generating field #1
[?] Do you want to add a field to your entity? Yes
[?] What is the name of your field? name
[?] What is the type of your field? String
===========Country==============
name (String)
Generating field #2
[?] Do you want to add a field to your entity? No
===========Country==============
name (String)
Generating relationships with other entities
[?] Do you want to add a relationship to another entity? Yes
[?] What is the name of the other entity? area
[?] What is the name of the relationship? area
[?] What is the type of the relationship? many-to-many
[?] Is this entity the owner of the relationship? No
===========Country==============
name (String)
-------------------
area - area (many-to-many)
Generating relationships with other entities
[?] Do you want to add a relationship to another entity? No
===========Country==============
name (String)
-------------------
area - area (many-to-many)
[?] Do you want pagination on your entity? No
...

$yo jhipster:entity area
The entity area is being created.
Generating field #1
[?] Do you want to add a field to your entity? Yes
[?] What is the name of your field? name
[?] What is the type of your field? String
===========Area==============
name (String)
Generating field #2
[?] Do you want to add a field to your entity? No
===========Area==============
name (String)
Generating relationships with other entities
[?] Do you want to add a relationship to another entity? Yes
[?] What is the name of the other entity? country
[?] What is the name of the relationship? country
[?] What is the type of the relationship? many-to-many
[?] Is this entity the owner of the relationship? Yes
/usr/local/share/npm/lib/node_modules/yo/node_modules/yeoman-generator/node_modules/inquirer/lib/prompts/base.js:173
 return (str.length < 1 || /([a-z])$/i.test(str) ? str + ":" : str).trim() + "
                                                                    ^
TypeError: undefined is not a function
    at Prompt.suffix (/usr/local/share/npm/lib/node_modules/yo/node_modules/yeoman-generator/node_modules/inquirer/lib/prompts/base.js:173:70)
    at /usr/local/share/npm/lib/node_modules/yo/node_modules/lodash/dist/lodash.js:5296:33
    at Prompt.getQuestion (/usr/local/share/npm/lib/node_modules/yo/node_modules/yeoman-generator/node_modules/inquirer/lib/prompts/base.js:184:52)
    at Prompt.render (/usr/local/share/npm/lib/node_modules/yo/node_modules/yeoman-generator/node_modules/inquirer/lib/prompts/input.js:52:22)
    at Prompt._run (/usr/local/share/npm/lib/node_modules/yo/node_modules/yeoman-generator/node_modules/inquirer/lib/prompts/input.js:40:8)
    at Prompt.run (/usr/local/share/npm/lib/node_modules/yo/node_modules/yeoman-generator/node_modules/inquirer/lib/prompts/base.js:70:8)
    at /usr/local/share/npm/lib/node_modules/yo/node_modules/yeoman-generator/node_modules/inquirer/lib/ui/prompt.js:87:14
    at Object.utils.runAsync (/usr/local/share/npm/lib/node_modules/yo/node_modules/yeoman-generator/node_modules/inquirer/lib/utils/utils.js:44:5)
    at PromptUI.onEachPrompt (/usr/local/share/npm/lib/node_modules/yo/node_modules/yeoman-generator/node_modules/inquirer/lib/ui/prompt.js:85:9)
    at /usr/local/share/npm/lib/node_modules/yo/node_modules/async/lib/async.js:227:13
```

here is my node version and yo verison
```
$ node -v
v0.12.0
$ npm -v
2.7.1
```

i tried with both version 2.6.0 and version 2.5.2

anyone, can help me figure out what wrong with this?

**Comment by jdubois** [comment]
I'm sorry but I can't reproduce your issue... I'm also using the latest version of yo (1.4.6), are you using the same version? (yo --version)

**Comment by oceanio** [comment]
yes, I am using yo 1.4.6. I change to ubuntu 14.04, and it's alright. But on my desktop, which is a mac, it went wrong. I clean my node/npm installation, and reinstall with 0.10.25 node, it produces this error:
```
/usr/local/share/npm/lib/node_modules/yo/node_modules/yeoman-generator/node_modules/inquirer/lib/prompts/base.js:173
 return (str.length < 1 || /([a-z])$/i.test(str) ? str + ":" : str).trim() + "
                                                                    ^
TypeError: Object function (response) {
                return 'When you display this relationship with AngularJS, which field from \'' + response.otherEntityName + '\' do you want to use?'
            } has no method 'trim'
    at Prompt.suffix (/usr/local/share/npm/lib/node_modules/yo/node_modules/yeoman-generator/node_modules/inquirer/lib/prompts/base.js:173:70)
    at /usr/local/share/npm/lib/node_modules/yo/node_modules/lodash/dist/lodash.js:5296:33
    at Prompt.getQuestion (/usr/local/share/npm/lib/node_modules/yo/node_modules/yeoman-generator/node_modules/inquirer/lib/prompts/base.js:184:52)
    at Prompt.render (/usr/local/share/npm/lib/node_modules/yo/node_modules/yeoman-generator/node_modules/inquirer/lib/prompts/input.js:52:22)
    at Prompt._run (/usr/local/share/npm/lib/node_modules/yo/node_modules/yeoman-generator/node_modules/inquirer/lib/prompts/input.js:40:8)
    at Prompt.run (/usr/local/share/npm/lib/node_modules/yo/node_modules/yeoman-generator/node_modules/inquirer/lib/prompts/ba
```

**Comment by oceanio** [comment]
I solved my problem. my npm installation is a little messy, i totally clean my mac, delete *all* nodejs files. And it works.
