### ISSUE TITLE
`jhipster jdl` command looks at `master` instead of `main` branch

### ISSUE THREAD

**Issue by mraible** [jhipster/generator-jhipster#12808]
##### **Overview of the issue**

I added a new `reactive-ms` JDL to our jdl-samples repository tonight and then tried to use it with:

```
jhipster jdl reactive-ms
```

It fails:

```
INFO! Using JHipster version installed globally
INFO! Downloading file: https://raw.githubusercontent.com/jhipster/jdl-samples/master/reactive-ms.jdl
Error: Error downloading https://raw.githubusercontent.com/jhipster/jdl-samples/master/reactive-ms.jdl: 404 - Not Found
    at ClientRequest.<anonymous> (/usr/local/lib/node_modules/generator-jhipster/cli/jdl.js:44:35)
    at Object.onceWrapper (events.js:421:26)
    at ClientRequest.emit (events.js:314:20)
    at ClientRequest.EventEmitter.emit (domain.js:486:12)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:640:27)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:119:17)
    at TLSSocket.socketOnData (_http_client.js:509:22)
    at TLSSocket.emit (events.js:314:20)
    at TLSSocket.EventEmitter.emit (domain.js:486:12)
    at addChunk (_stream_readable.js:307:12)
Execution time: 3 s.
```

##### **Motivation for or Use Case**

This command should work.

##### **Reproduce the error**

```
npm i -g generator-jhipster
take apps
jhipster jdl reactive-ms
```

##### **Related issues**

The recent change to use `main` as the default branch.

##### **Suggest a Fix**

Change branch name and do a new release or (even better) release an alpha or beta of 7.0!

##### **JHipster Version(s)**

6.10.4

**Comment by alwinaswin** [comment]
no answer
