### ISSUE TITLE
index.html not being generated properly

### ISSUE THREAD

**Issue by JeffSherman** [jhipster/generator-jhipster#1280]
Version: 2.6.0

Options: all default except for mongo

Issue: index.html does not include many js files (including angular), e.g. I get

All the scripts are missing.  Also, I get the following error creating an app which I'm not sure is relevant to this problem: 
Error: spawn grunt ENOENT
    at exports._errnoException (util.js:746:11)
    at Process.ChildProcess._handle.onexit (child_process.js:1046:32)
    at child_process.js:1137:20
    at process._tickCallback (node.js:355:11)

Please let me know if there's anything else I can provide.

**Comment by JeffSherman** [comment]
I've resolved this issue. I skipped doing the following:
npm install -g grunt-cli

Once that's installed, everything works as expected. It might be worth putting some checking in place for these types of dependencies. Maybe something to include in https://github.com/jhipster/generator-jhipster/issues/1112
