### ISSUE TITLE
Entity generation will fail for field name `account`

### ISSUE THREAD

**Issue by pmverma** [jhipster/generator-jhipster#13006]
##### **Overview of the issue**

Entity generation will fail for field name `account`.

```
events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: Copying template D:\temp\node_modules\generator-jhipster\generators\entity-server\templates/src/main/resources/config/liquibase/fake-data/table.csv.ejs failed. [TypeError: D:\temp\node_modules\generator-jhipster\generators\entity-server\templates\src\main\resources\config\liquibase\fake-data\table.csv.ejs:19
    17|  limitations under the License.
    18| -%>
 >> 19| <%_
    20| let table = [];
    21|
    22| // Generate CSV header

this.faker.commerce.account is not a function]
    at module.exports.error (D:\temp\node_modules\generator-jhipster\generators\generator-base.js:1590:15)
    at D:\temp\node_modules\generator-jhipster\generators\utils.js:256:23
    at tryHandleCache (D:\temp\node_modules\ejs\lib\ejs.js:275:14)
    at Object.exports.renderFile (D:\temp\node_modules\ejs\lib\ejs.js:489:10)
    at Object.renderContent (D:\temp\node_modules\generator-jhipster\generators\utils.js:252:9)
    at module.exports.template (D:\temp\node_modules\generator-jhipster\generators\generator-base-private.js:769:23)
    at D:\temp\node_modules\generator-jhipster\generators\generator-base.js:2040:42
    at Array.forEach (<anonymous>)
    at module.exports.writeFilesToDisk (D:\temp\node_modules\generator-jhipster\generators\generator-base.js:2002:45)
    at module.exports.writeServerFiles (D:\temp\node_modules\generator-jhipster\generators\entity-server\files.js:345:18)
Emitted 'error' event on  instance at:
    at Immediate.<anonymous> (D:\temp\node_modules\yeoman-generator\lib\index.js:1007:20)
    at processImmediate (internal/timers.js:456:21)

```
##### **Motivation for or Use Case**

Entity generation should work without error.

##### **Reproduce the error**

1. On a generated app run `jhipster entity MyEntity` and create a field name `account`. Generation will fail.

##### **Suggest a Fix**

It seems the `account` function has move to under finance category in faker.js
In `generator-jhipster\generators\entity-server\templates\src\main\resources\config\liquibase\fake-data\table.csv.ejs`,
Change `this.faker.commerce.account()` to `this.faker.finance.account()`

##### **JHipster Version(s)**

```
temp@0.0.1-SNAPSHOT D:\temp
`-- generator-jhipster@6.10.5

```

##### **Environment and Tools**

java version "11.0.8" 2020-07-14 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.8+10-LTS)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.8+10-LTS, mixed mode)

git version 2.28.0.windows.1

node: v12.18.4

npm: 6.14.6

yeoman: 3.1.1
##### **Browsers and Operating System**

-   [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by Hawkurane** [comment]
Hello, I managed to reproduce the error but only on the release version. The main version does not have this behaviour.
Do you think it's worth fixing it on the v6.x_maintenance branch?
