### ISSUE TITLE
Creating a reactive microservices architecture fails with main branch

### ISSUE THREAD

**Issue by mraible** [jhipster/generator-jhipster#13027]
##### **Overview of the issue**

During my Twitch stream yesterday, I tried to generate a reactive microservices architecture using the following JDL.

```
application {
  config {
    baseName gateway,
    reactive true,
    packageName com.okta.developer.gateway,
    applicationType gateway,
    authenticationType jwt,
    databaseType neo4j,
    devDatabaseType neo4j,
    prodDatabaseType neo4j,
    enableHibernateCache false,
    serviceDiscoveryType eureka,
    testFrameworks [protractor]
  }
  entities Blog, Post, Tag, Product
}

application {
  config {
    baseName blog,
    reactive true,
    packageName com.okta.developer.blog,
    applicationType microservice,
    authenticationType oauth2,
    databaseType couchbase,
    devDatabaseType couchbase,
    prodDatabaseType couchbase,
    enableHibernateCache false,
    serverPort 8081,
    serviceDiscoveryType eureka
  }
  entities Blog, Post, Tag
}

application {
  config {
    baseName store,
    reactive true,
    packageName com.okta.developer.store,
    applicationType microservice,
    authenticationType oauth2,
    databaseType mongodb,
    devDatabaseType mongodb,
    prodDatabaseType mongodb,
    enableHibernateCache false,
    serverPort 8082,
    serviceDiscoveryType eureka
  }
  entities Product
}

entity Blog {
  name String required minlength(3),
  handle String required minlength(2)
}

entity Post {
  title String required,
  content TextBlob required,
  date Instant required
}

entity Tag {
  name String required minlength(2)
}

entity Product {
  title String required,
  price BigDecimal required min(0),
  image ImageBlob
}

relationship ManyToOne {
  Blog{user(login)} to User,
  Post{blog(name)} to Blog
}

relationship ManyToMany {
  Post{tag(name)} to Tag{post}
}

paginate Post, Tag with infinite-scroll
paginate Product with pagination

microservice Product with store
microservice Blog, Post, Tag with blog

deployment {
  deploymentType docker-compose
  appsFolders [gateway, blog, store]
  dockerRepositoryName "mraible"
  monitoring elk
  consoleOptions [zipkin]
}
```

It failed with the following error:

```
INFO! Using JHipster version installed globally
INFO! Executing import-jdl /Users/mraible/Downloads/jhipster-jdl.jdl
error: Syntax error message:
	MismatchedTokenException: Expecting --> '}' <-- but found --> 'consoleOptions' <--
	at line: 93, column: 3
Error during import-jdl: Error: MismatchedTokenException: Expecting --> '}' <-- but found --> 'consoleOptions' <--
	at line: 93, column: 3
Error: MismatchedTokenException: Expecting --> '}' <-- but found --> 'consoleOptions' <--
	at line: 93, column: 3
    at throwParserError (/Users/mraible/dev/generator-jhipster/jdl/parsing/api.js:73:11)
    at getCst (/Users/mraible/dev/generator-jhipster/jdl/parsing/api.js:56:9)
    at Object.parse (/Users/mraible/dev/generator-jhipster/jdl/parsing/api.js:39:17)
    at callApiMethod (/Users/mraible/dev/generator-jhipster/jdl/readers/jdl-reader.js:98:34)
    at parse (/Users/mraible/dev/generator-jhipster/jdl/readers/jdl-reader.js:84:27)
    at Object.parseFromFiles (/Users/mraible/dev/generator-jhipster/jdl/readers/jdl-reader.js:43:12)
    at parseFiles (/Users/mraible/dev/generator-jhipster/jdl/jdl-importer.js:124:22)
    at createImporterFromFiles (/Users/mraible/dev/generator-jhipster/jdl/jdl-importer.js:59:21)
    at JDLProcessor.importJDL (/Users/mraible/dev/generator-jhipster/cli/import-jdl.js:354:24)
    at module.exports (/Users/mraible/dev/generator-jhipster/cli/import-jdl.js:463:21)
ERROR! Error during import-jdl: MismatchedTokenException: Expecting --> '}' <-- but found --> 'consoleOptions' <--
	at line: 93, column: 3
Error: Error during import-jdl: MismatchedTokenException: Expecting --> '}' <-- but found --> 'consoleOptions' <--
	at line: 93, column: 3
    at module.exports (/Users/mraible/dev/generator-jhipster/cli/import-jdl.js:480:31)
    at /Users/mraible/dev/generator-jhipster/cli/jdl.js:61:51
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Promise.all (index 0)
```

##### **Motivation for or Use Case**

It was embarrassing to have a generation fail for a JDL that works fine with generator-jhipster@6.10.5. Because I was flustered with the failure, I installed 6.10.5 to fix. I think if the error message was better, I might've been able to fix it. 

##### **Reproduce the error**

Use the JDL above with the main branch.

##### **JHipster Version(s)**

v7. Works with 6.10.6. 

##### **Browsers and Operating System**

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by MathieuAA** [comment]
The option was removed, see 0d838cb008dfebe7948dcddf97b3937aee4a3644 for more info, part of #12414.

**Comment by MathieuAA** [comment]
> It was embarrassing to have a generation fail for a JDL that works fine with generator-jhipster@6.10.5. Because I was flustered with the failure, I installed 6.10.5 to fix. I think if the error message was better, I might've been able to fix it.

Sorry to hear that. There's an issue in the [documentation](https://www.jhipster.tech/jdl/deployments#available-deployment-options): `consoleOptions` still is in the supported option list...
I'm creating a PR to fix it.

**Comment by mraible** [comment]
@MathieuAA This error has tripped me up twice this week, and I consider myself a power user. First, it was because of a `useSass` option and now this. In the 6.x version, there wasn't a stack trace. To make migrating to 7.x easier, can we just output a warning that the option is no longer available and will be ignored?

**Comment by MathieuAA** [comment]
I'll see what I can do.

**Comment by MathieuAA** [comment]
@mraible I'm opening a new issue about this matter to keep track of it, and assigning myself to it.
About `consoleOptions`, I'll create a PR later today after I improve the error message, unless you beat me to it and open a PR before I do.

**Comment by MathieuAA** [comment]
@mraible all 3 PRs are submitted.

**Comment by mraible** [comment]
Thanks, @MathieuAA! ❤️
