### ISSUE TITLE
Remove metrics-spark-reporter-1.2.jar with Java 7, as it is a Java 8 JAR

### ISSUE THREAD

**Issue by viniciusboson** [jhipster/generator-jhipster#1303]
Hi,

I'm trying to deploy a JHispter generated application out-of-the-box on JBOSS 7.5.
My set up environment is `java version 1.7.X`, `JHipster 1.4.5` and `Jboss Eap 6.4 (AS 7.5.0)`.
When i was creating the application, i chose Java 7 compliance. 
There first error that i got was due a `guava 15.0` version incompatibility with `CDI 1.0`

```
18:27:33,346 ERROR [org.jboss.msc.service.fail] (MSC service thread 1-5) MSC000001: Failed to start service jboss.deployment.unit."jhipster-0.0.1-SNAPSHOT.war".WeldStartService: org.jboss.msc.service.StartException in service jboss.deployment.unit."jhipster-0.0.1-SNAPSHOT.war".WeldStartService: Failed to start service
	at org.jboss.msc.service.ServiceControllerImpl$StartTask.run(ServiceControllerImpl.java:1936) [jboss-msc-1.1.5.Final-redhat-1.jar:1.1.5.Final-redhat-1]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [rt.jar:1.7.0_75]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [rt.jar:1.7.0_75]
	at java.lang.Thread.run(Thread.java:745) [rt.jar:1.7.0_75]
Caused by: org.jboss.weld.exceptions.DeploymentException: WELD-001408 Unsatisfied dependencies for type [Set<Service>] with qualifiers [@Default] at injection point [[parameter 1] of [constructor] @Inject com.google.common.util.concurrent.ServiceManager(Set<Service>)]
	at org.jboss.weld.bootstrap.Validator.validateInjectionPoint(Validator.java:315)
	at org.jboss.weld.bootstrap.Validator.validateInjectionPoint(Validator.java:284)
	at org.jboss.weld.bootstrap.Validator.validateBean(Validator.java:147)
	at org.jboss.weld.bootstrap.Validator.validateRIBean(Validator.java:167)
	at org.jboss.weld.bootstrap.Validator.validateBeans(Validator.java:386)
	at org.jboss.weld.bootstrap.Validator.validateDeployment(Validator.java:371)
	at org.jboss.weld.bootstrap.WeldBootstrap.validateBeans(WeldBootstrap.java:379)
	at org.jboss.as.weld.WeldStartService.start(WeldStartService.java:64)
	at org.jboss.msc.service.ServiceControllerImpl$StartTask.startService(ServiceControllerImpl.java:1980) [jboss-msc-1.1.5.Final-redhat-1.jar:1.1.5.Final-redhat-1]
	at org.jboss.msc.service.ServiceControllerImpl$StartTask.run(ServiceControllerImpl.java:1913) [jboss-msc-1.1.5.Final-redhat-1.jar:1.1.5.Final-redhat-1]
	... 3 more
```
	
I cant find anymore the closed related issue but the solution is to a classifier `<classifier>cdi1.0</classifier>` for this dependecy.

The next error is a dependency with metrics-spark-reporter-1.2.jar which was compiled for a Java 8 version.

```
11:18:25,275 WARN  [org.jboss.modules] (ServerService Thread Pool -- 72) Failed to define class fr.ippon.spark.metrics.SparkReporter in Module "deployment.centralsindico-0.0.1-SNAPSHOT.war:main" from Service Module Loader: java.lang.UnsupportedClassVersionError: fr/ippon/spark/metrics/SparkReporter : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method) [rt.jar:1.7.0_75]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:800) [rt.jar:1.7.0_75]
	at org.jboss.modules.ModuleClassLoader.doDefineOrLoadClass(ModuleClassLoader.java:361) [jboss-modules.jar:1.3.6.Final-redhat-1]
	at org.jboss.modules.ModuleClassLoader.defineClass(ModuleClassLoader.java:482) [jboss-modules.jar:1.3.6.Final-redhat-1]
	at org.jboss.modules.ModuleClassLoader.loadClassLocal(ModuleClassLoader.java:277) [jboss-modules.jar:1.3.6.Final-redhat-1]
	at org.jboss.modules.ModuleClassLoader$1.loadClassLocal(ModuleClassLoader.java:92) [jboss-modules.jar:1.3.6.Final-redhat-1]
	at org.jboss.modules.Module.loadModuleClass(Module.java:568) [jboss-modules.jar:1.3.6.Final-redhat-1]
	at org.jboss.modules.ModuleClassLoader.findClass(ModuleClassLoader.java:205) [jboss-modules.jar:1.3.6.Final-redhat-1]
	at org.jboss.modules.ConcurrentClassLoader.performLoadClassUnchecked(ConcurrentClassLoader.java:459) [jboss-modules.jar:1.3.6.Final-redhat-1]
	at org.jboss.modules.ConcurrentClassLoader.performLoadClassChecked(ConcurrentClassLoader.java:408) [jboss-modules.jar:1.3.6.Final-redhat-1]
	at org.jboss.modules.ConcurrentClassLoader.performLoadClass(ConcurrentClassLoader.java:389) [jboss-modules.jar:1.3.6.Final-redhat-1]
	at org.jboss.modules.ConcurrentClassLoader.loadClass(ConcurrentClassLoader.java:134) [jboss-modules.jar:1.3.6.Final-redhat-1]
	at org.springframework.util.ClassUtils.forName(ClassUtils.java:249) [spring-core-4.1.4.RELEASE.jar:4.1.4.RELEASE]
	at org.springframework.util.ClassUtils.isPresent(ClassUtils.java:326) [spring-core-4.1.4.RELEASE.jar:4.1.4.RELEASE]
	at org.springframework.boot.autoconfigure.condition.OnClassCondition$MatchType$2.matches(OnClassCondition.java:123) [spring-boot-autoconfigure-1.2.1.RELEASE.jar:1.2.1.RELEASE]
	at org.springframework.boot.autoconfigure.condition.OnClassCondition.getMatchingClasses(OnClassCondition.java:94) [spring-boot-autoconfigure-1.2.1.RELEASE.jar:1.2.1.RELEASE]
	at org.springframework.boot.autoconfigure.condition.OnClassCondition.getMatchOutcome(OnClassCondition.java:51) [spring-boot-autoconfigure-1.2.1.RELEASE.jar:1.2.1.RELEASE]
	at org.springframework.boot.autoconfigure.condition.SpringBootCondition.matches(SpringBootCondition.java:45) [spring-boot-autoconfigure-1.2.1.RELEASE.jar:1.2.1.RELEASE]
	at org.springframework.context.annotation.ConditionEvaluator.shouldSkip(ConditionEvaluator.java:102) [spring-context-4.1.4.RELEASE.jar:4.1.4.RELEASE]
	at org.springframework.context.annotation.ConditionEvaluator.shouldSkip(ConditionEvaluator.java:81) [spring-context-4.1.4.RELEASE.jar:4.1.4.RELEASE]
	at org.springframework.context.annotation.ConditionEvaluator.shouldSkip(ConditionEvaluator.java:64) [spring-context-4.1.4.RELEASE.jar:4.1.4.RELEASE]
	at org.springframework.context.annotation.ClassPathScanningCandidateComponentProvider.isConditionMatch(ClassPathScanningCandidateComponentProvider.java:363) [spring-context-4.1.4.RELEASE.jar:4.1.4.RELEASE]
	at org.springframework.context.annotation.ClassPathScanningCandidateComponentProvider.isCandidateComponent(ClassPathScanningCandidateComponentProvider.java:347) [spring-context-4.1.4.RELEASE.jar:4.1.4.RELEASE]
	at org.springframework.context.annotation.ClassPathScanningCandidateComponentProvider.findCandidateComponents(ClassPathScanningCandidateComponentProvider.java:280) [spring-context-4.1.4.RELEASE.jar:4.1.4.RELEASE]
	at org.springframework.context.annotation.ClassPathBeanDefinitionScanner.doScan(ClassPathBeanDefinitionScanner.java:248) [spring-context-4.1.4.RELEASE.jar:4.1.4.RELEASE]
	at org.springframework.context.annotation.ComponentScanAnnotationParser.parse(ComponentScanAnnotationParser.java:140) [spring-context-4.1.4.RELEASE.jar:4.1.4.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassParser.doProcessConfigurationClass(ConfigurationClassParser.java:262) [spring-context-4.1.4.RELEASE.jar:4.1.4.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassParser.processConfigurationClass(ConfigurationClassParser.java:226) [spring-context-4.1.4.RELEASE.jar:4.1.4.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassParser.parse(ConfigurationClassParser.java:193) [spring-context-4.1.4.RELEASE.jar:4.1.4.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassParser.parse(ConfigurationClassParser.java:163) [spring-context-4.1.4.RELEASE.jar:4.1.4.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassPostProcessor.processConfigBeanDefinitions(ConfigurationClassPostProcessor.java:306) [spring-context-4.1.4.RELEASE.jar:4.1.4.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassPostProcessor.postProcessBeanDefinitionRegistry(ConfigurationClassPostProcessor.java:239) [spring-context-4.1.4.RELEASE.jar:4.1.4.RELEASE]
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanDefinitionRegistryPostProcessors(PostProcessorRegistrationDelegate.java:254) [spring-context-4.1.4.RELEASE.jar:4.1.4.RELEASE]
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:94) [spring-context-4.1.4.RELEASE.jar:4.1.4.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:606) [spring-context-4.1.4.RELEASE.jar:4.1.4.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:462) [spring-context-4.1.4.RELEASE.jar:4.1.4.RELEASE]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:118) [spring-boot-1.2.1.RELEASE.jar:1.2.1.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:691) [spring-boot-1.2.1.RELEASE.jar:1.2.1.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:321) [spring-boot-1.2.1.RELEASE.jar:1.2.1.RELEASE]
	at org.springframework.boot.context.web.SpringBootServletInitializer.run(SpringBootServletInitializer.java:117) [spring-boot-1.2.1.RELEASE.jar:1.2.1.RELEASE]
	at org.springframework.boot.context.web.SpringBootServletInitializer.createRootApplicationContext(SpringBootServletInitializer.java:108) [spring-boot-1.2.1.RELEASE.jar:1.2.1.RELEASE]
	at org.springframework.boot.context.web.SpringBootServletInitializer.onStartup(SpringBootServletInitializer.java:68) [spring-boot-1.2.1.RELEASE.jar:1.2.1.RELEASE]
	at org.springframework.web.SpringServletContainerInitializer.onStartup(SpringServletContainerInitializer.java:175) [spring-web-4.1.4.RELEASE.jar:4.1.4.RELEASE]
	at org.jboss.as.web.deployment.JBossContextConfig.lifecycleEvent(JBossContextConfig.java:187) [jboss-as-web-7.5.0.Final-redhat-17.jar:7.5.0.Final-redhat-17]
	at org.apache.catalina.util.LifecycleSupport.fireLifecycleEvent(LifecycleSupport.java:115) [jbossweb-7.5.4.Final-redhat-1.jar:7.5.4.Final-redhat-1]
	at org.apache.catalina.core.StandardContext.start(StandardContext.java:3775) [jbossweb-7.5.4.Final-redhat-1.jar:7.5.4.Final-redhat-1]
	at org.jboss.as.web.deployment.WebDeploymentService.doStart(WebDeploymentService.java:163) [jboss-as-web-7.5.0.Final-redhat-17.jar:7.5.0.Final-redhat-17]
	at org.jboss.as.web.deployment.WebDeploymentService.access$000(WebDeploymentService.java:61) [jboss-as-web-7.5.0.Final-redhat-17.jar:7.5.0.Final-redhat-17]
	at org.jboss.as.web.deployment.WebDeploymentService$1.run(WebDeploymentService.java:96) [jboss-as-web-7.5.0.Final-redhat-17.jar:7.5.0.Final-redhat-17]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) [rt.jar:1.7.0_75]
	at java.util.concurrent.FutureTask.run(FutureTask.java:262) [rt.jar:1.7.0_75]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [rt.jar:1.7.0_75]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [rt.jar:1.7.0_75]
	at java.lang.Thread.run(Thread.java:745) [rt.jar:1.7.0_75]
	at org.jboss.threads.JBossThread.run(JBossThread.java:122)
```
	
I've donwloaded this source and have tried to compile it for a java 7 version but it's not possible.

First, how would be the best manner to disable this metric which is coupled with JHipster ?
Second, since i chose a java 7 version generation, wouldn't it be better to be generated with 
another metric reporter aproach ?

Note: Deploying the same application on Tomcat 8.0 works fine.

**Comment by sdoxsee** [comment]
First issue has a fix here: https://issues.jboss.org/browse/WFLY-2861

You need to add a WEB-INF folder direclty under src/main/webapp that has either beans.xml or jboss-deployment-structure.xml to exclude the weld subsystem

Second issue...I'm not sure as I'm using java 8

**Comment by jdubois** [comment]
As @sdoxsee gave a fix I'm closing this.
JBoss is well-known for its broken classloader, but if we can make it work on JBoss it's of course better -> @viniciusboson can you post an update if you have any good/bad comments following the fix?

**Comment by viniciusboson** [comment]
@jdubois, The solution gave by @sdoxsee  was about the first issue that i've already over passed it.
The actual issue is about Jhipster dependency on a java 1.8 compiled library despite of the fact that it was generated towards java 7 version.
In this way, i believe that we still have an issue.

**Comment by jdubois** [comment]
OK, I will check to remove the lib in Java 7

**Comment by jdubois** [comment]
I'm renaming the issue in this case, because this is a different subject
