### ISSUE TITLE
Websocket port configuration

### ISSUE THREAD

**Issue by prestonvanloon** [jhipster/generator-jhipster#1321]
How can the websocket port be changed? 
Openshift allows plain WebSockets ws:// on port 8000 and for secured connections wss:// port 8443. 

When spring tries to bind to 8080, it fails.

**Comment by jdubois** [comment]
It works the same way on Pivotal CloudFoundry, which uses port 4443 for secured websockets, and not 80 or 443 -> I don't how it works, but I don't have any issue on CloudFoundry, and indeed I should have the same issue as you.

Do you have a stacktrace? Or can you try connecting directly to that port?

**Comment by prestonvanloon** [comment]
Here's the top of the stack:
```
[WARN] org.springframework.core.io.support.PathMatchingResourcePatternResolver - Skipping [/var/lib/openshift/5515b694fcf933c3a300002b/app-root/runtime/repo/webapps/ROOT.war] because it does not denote a directory
[INFO] com.machinepowered.mothership.config.MetricsConfiguration - Initializing Metrics JMX reporting
[INFO] com.machinepowered.mothership.Application - Running with Spring profile(s) : [dev]
[INFO] com.machinepowered.mothership.config.WebConfigurer - Web application configuration, using profiles: [dev]
[INFO] com.machinepowered.mothership.config.WebConfigurer - Web application fully configured
[INFO] com.machinepowered.mothership.config.ThymeleafConfiguration - loading non-reloadable mail messages resources
[ERROR] org.apache.coyote.http11.Http11NioProtocol - Failed to start end point associated with ProtocolHandler ["http-nio-8080"]
java.net.SocketException: Permission denied
	at sun.nio.ch.Net.bind0(Native Method) ~[na:1.7.0_75]
	at sun.nio.ch.Net.bind(Net.java:444) ~[na:1.7.0_75]
	at sun.nio.ch.Net.bind(Net.java:436) ~[na:1.7.0_75]
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:214) ~[na:1.7.0_75]
	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74) ~[na:1.7.0_75]
	at org.apache.tomcat.util.net.NioEndpoint.bind(NioEndpoint.java:473) ~[tomcat-embed-core-7.0.59.jar!/:7.0.59]
	at org.apache.tomcat.util.net.AbstractEndpoint.start(AbstractEndpoint.java:653) ~[tomcat-embed-core-7.0.59.jar!/:7.0.59]
	at org.apache.coyote.AbstractProtocol.start(AbstractProtocol.java:449) ~[tomcat-embed-core-7.0.59.jar!/:7.0.59]
	at org.apache.catalina.connector.Connector.startInternal(Connector.java:1007) [tomcat-embed-core-7.0.59.jar!/:7.0.59]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150) [tomcat-embed-core-7.0.59.jar!/:7.0.59]
	at org.apache.catalina.core.StandardService.addConnector(StandardService.java:241) [tomcat-embed-core-7.0.59.jar!/:7.0.59]
	at org.springframework.boot.context.embedded.tomcat.TomcatEmbeddedServletContainer.addPreviouslyRemovedConnectors(TomcatEmbeddedServletContainer.java:186) [spring-boot-1.2.2.RELEASE.jar!/:1.2.2.RELEASE]
	at org.springframework.boot.context.embedded.tomcat.TomcatEmbeddedServletContainer.start(TomcatEmbeddedServletContainer.java:149) [spring-boot-1.2.2.RELEASE.jar!/:1.2.2.RELEASE]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.startEmbeddedServletContainer(EmbeddedWebApplicationContext.java:288) [spring-boot-1.2.2.RELEASE.jar!/:1.2.2.RELEASE]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.finishRefresh(EmbeddedWebApplicationContext.java:141) [spring-boot-1.2.2.RELEASE.jar!/:1.2.2.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:483) [spring-context-4.1.5.RELEASE.jar!/:4.1.5.RELEASE]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:118) [spring-boot-1.2.2.RELEASE.jar!/:1.2.2.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:686) [spring-boot-1.2.2.RELEASE.jar!/:1.2.2.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:320) [spring-boot-1.2.2.RELEASE.jar!/:1.2.2.RELEASE]
	at com.machinepowered.mothership.Application.main(Application.java:57) [classes!/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.7.0_75]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[na:1.7.0_75]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_75]
	at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_75]
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:53) [ROOT.war:0.0.1-SNAPSHOT]
	at java.lang.Thread.run(Thread.java:745) [na:1.7.0_75]
[ERROR] org.apache.catalina.core.StandardService - Failed to start connector [Connector[org.apache.coyote.http11.Http11NioProtocol-8080]]
```

I'm trying to launch the built WAR file on a tomcat 7 openshift gear. 
According to this: https://blog.openshift.com/paas-websockets/
The websocket has to be on port 8000 or 8443

**Comment by jdubois** [comment]
I would only change the server port, in that case.

I'm not sure how you are supposed to do it -> on Spring Boot it's the "server.port" property (see http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html ) but if you deploy on Tomcat then this must be changed in the Tomcat conf

As we normally deploy an executable WAR, what you do might be better -> if you have feedback, when you get it working, it will be valuable for us

**Comment by prestonvanloon** [comment]
I'll see if I can figure it out. The jbossews 2.0 (tomcat 7) gear requires the app to report to 8080. So I can't just change the whole server port. The reason for doing it like this instead of DIY is that jbossews is scalable on openshift.

**Comment by jdubois** [comment]
Yes I want this exactly for the same reason as you -> I did a DIY install as that's what's vert.x is doing, and as it's a JBoss project I thought they knew what they were doing... and that was a mistake!

In our case we are just deploying a normal app using Websockets, I hope this is documented somewhere (it was documented for Heroku, but not for CloudFoundry, so let's hope it's better with OpenShift!)

**Comment by prestonvanloon** [comment]
I can't get it to bind to 8000 either. 

```
[ERROR] org.apache.coyote.http11.Http11NioProtocol - Failed to start end point associated with ProtocolHandler ["http-nio-8000"]
java.net.SocketException: Permission denied
```

Giving up on this. I'm either going to abandon websockets for this project or switch to something else

**Comment by jdubois** [comment]
Bad news :-(

I'm closing this as we don't have a solution.

**Comment by asishpmathew** [comment]
The port is already used by some services.Change port number in application-dev.yml/appliaction-prod.yml.  I had faced the same issue!

**Comment by prestonvanloon** [comment]
@asishpmathew can you post your application-prod.yml? Which port value did you change?
