### ISSUE TITLE
Strange Java error causes client to fail translation lookup

### ISSUE THREAD

**Issue by verrol** [jhipster/generator-jhipster#1337]
I have a very simple app with one entity. It uses MongoDB.  I started to test with with both Chrome and FireFox using 'grunt server'.

I logged in from each browser, one as 'admin' and the other as 'user'. Created two records. I edit one of the records, save changes. The record wasn't updated. Then I notice the console error and UI. The use had had the translation name, but not the translated string. See error below and screenshot attached. **NOTE**: I was still logged in.

[DEBUG] com.test.app.security.UserDetailsService - Authenticating admin
[DEBUG] com.test.app.aop.logging.LoggingAspect - Enter: com.test.app.web.rest.VendorResource.getAll() with argument[s] = [2, 20]
[DEBUG] com.test.app.aop.logging.LoggingAspect - Exit: com.test.app.web.rest.VendorResource.getAll() with result = <200 OK,[],{X-Total-Count=[2], Link=[</api/vendors?page=1&per_page=20>; rel="prev",</api/vendors?page=1&per_page=20>; rel="last",</api/vendors?page=1&per_page=20>; rel="first"]}>
[ERROR] org.springframework.messaging.simp.annotation.support.SimpAnnotationMethodMessageHandler - Unhandled exception
org.springframework.messaging.simp.annotation.support.MissingSessionUserException: No "user" header in message
	at org.springframework.messaging.simp.annotation.support.PrincipalMethodArgumentResolver.resolveArgument(PrincipalMethodArgumentResolver.java:42) ~[spring-messaging-4.1.5.RELEASE.jar:4.1.5.RELEASE]
	at org.springframework.messaging.handler.invocation.HandlerMethodArgumentResolverComposite.resolveArgument(HandlerMethodArgumentResolverComposite.java:77) ~[spring-messaging-4.1.5.RELEASE.jar:4.1.5.RELEASE]
	at org.springframework.messaging.handler.invocation.InvocableHandlerMethod.getMethodArgumentValues(InvocableHandlerMethod.java:127) ~[spring-messaging-4.1.5.RELEASE.jar:4.1.5.RELEASE]
	at org.springframework.messaging.handler.invocation.InvocableHandlerMethod.invoke(InvocableHandlerMethod.java:100) ~[spring-messaging-4.1.5.RELEASE.jar:4.1.5.RELEASE]
	at org.springframework.messaging.handler.invocation.AbstractMethodMessageHandler.handleMatch(AbstractMethodMessageHandler.java:451) [spring-messaging-4.1.5.RELEASE.jar:4.1.5.RELEASE]
	at org.springframework.messaging.simp.annotation.support.SimpAnnotationMethodMessageHandler.handleMatch(SimpAnnotationMethodMessageHandler.java:443) [spring-messaging-4.1.5.RELEASE.jar:4.1.5.RELEASE]
	at org.springframework.messaging.simp.annotation.support.SimpAnnotationMethodMessageHandler.handleMatch(SimpAnnotationMethodMessageHandler.java:82) [spring-messaging-4.1.5.RELEASE.jar:4.1.5.RELEASE]
	at org.springframework.messaging.handler.invocation.AbstractMethodMessageHandler.handleMessageInternal(AbstractMethodMessageHandler.java:412) [spring-messaging-4.1.5.RELEASE.jar:4.1.5.RELEASE]
	at org.springframework.messaging.handler.invocation.AbstractMethodMessageHandler.handleMessage(AbstractMethodMessageHandler.java:350) [spring-messaging-4.1.5.RELEASE.jar:4.1.5.RELEASE]
	at org.springframework.messaging.support.ExecutorSubscribableChannel$SendTask.run(ExecutorSubscribableChannel.java:135) [spring-messaging-4.1.5.RELEASE.jar:4.1.5.RELEASE]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_25]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_25]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_25]

![screen shot 2015-04-03 at 6 19 51 am](https://cloud.githubusercontent.com/assets/1181207/6982720/4364e2fe-d9ca-11e4-915c-8cae9c4f54bd.png)

**Comment by jdubois** [comment]
-Your exception "MissingSessionUserException" looks strange: are you using Websockets? It looks like you have a security error with Websockets, and this should be solved in 2.7.0 (which was release this afternoon!), with the migration to Spring Security 4.

- "grunt server" is deprecated, you should use "grunt serve"

- Using "grunt serve" you will use a proxy to access your application, so Websockets will not work anyway (this is another ticket)
