### ISSUE TITLE
React unable to delete certain entities when using React

### ISSUE THREAD

**Issue by mraible** [jhipster/generator-jhipster#13385]
##### **Overview of the issue**

I created a microservices architecture using JHipster 7 beta 0 and React for the frontend. Here's the JDL I'm using:

```
application {
  config {
    baseName gateway
    reactive true
    clientFramework react 
    packageName com.okta.developer.gateway
    applicationType gateway
    authenticationType oauth2
    prodDatabaseType postgresql
    serviceDiscoveryType eureka
    testFrameworks [cypress,gatling]
  }
  entities Blog, Post, Tag, Product
}

application {
  config {
    baseName blog
    reactive true
    packageName com.okta.developer.blog
    applicationType microservice
    authenticationType oauth2
    databaseType neo4j
    devDatabaseType neo4j
    prodDatabaseType neo4j
    enableHibernateCache false
    serverPort 8081
    serviceDiscoveryType eureka
  }
  entities Blog, Post, Tag
}

application {
  config {
    baseName store
    reactive true
    packageName com.okta.developer.store
    applicationType microservice
    authenticationType oauth2
    databaseType mongodb
    devDatabaseType mongodb
    prodDatabaseType mongodb
    enableHibernateCache false
    searchEngine elasticsearch
    serverPort 8082
    serviceDiscoveryType eureka
  }
  entities Product
}

entity Blog {
  name String required minlength(3),
  handle String required minlength(2)
}

entity Post {
  title String required
  content TextBlob required
  date Instant required
}

entity Tag {
  name String required minlength(2)
}

entity Product {
  title String required,
  price BigDecimal required min(0),
  image ImageBlob
}

relationship ManyToOne {
  Blog{user(login)} to User,
  Post{blog(name)} to Blog
}

relationship ManyToMany {
  Post{tag(name)} to Tag{post}
}

paginate Post, Tag with infinite-scroll
paginate Product with pagination

microservice Product with store
microservice Blog, Post, Tag with blog
```

I start all the required services and apps with the following commands:

```
cd gateway
jhkeycloakup
# wait 20 seconds for Keycloak to start up
jhregistryup
jhpostgresqlup
./mvnw -Pprod
```

New terminal:
```
cd ../blog
jhneo4jup
./mvnw 
```

New terminal:
```
cd ../store
jhmongoup
jhesup
./mvnw
```

Most entities work, except for `Post`. If you try to delete one, it results in a 500 error. It's interesting because the error happens before I click the confirmation delete. Maybe the confirm dialog isn't being used?

Stack trace from the blog app:

```
java.lang.IllegalArgumentException: Authentication object cannot be null
	at org.springframework.security.access.expression.SecurityExpressionRoot.<init>(SecurityExpressionRoot.java:60)
	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException:
Assembly trace from producer [reactor.core.publisher.MonoFlatMap] :
	reactor.core.publisher.Mono.flatMap(Mono.java:2787)
	org.springframework.web.reactive.result.method.InvocableHandlerMethod.invoke(InvocableHandlerMethod.java:137)
Error has been observed at the following site(s):
	|_  Mono.flatMap ⇢ at org.springframework.web.reactive.result.method.InvocableHandlerMethod.invoke(InvocableHandlerMethod.java:137)
	|_    Mono.defer ⇢ at org.springframework.web.reactive.result.method.annotation.RequestMappingHandlerAdapter.handle(RequestMappingHandlerAdapter.java:199)
	|_     Mono.then ⇢ at org.springframework.web.reactive.result.method.annotation.RequestMappingHandlerAdapter.handle(RequestMappingHandlerAdapter.java:199)
	|_ Mono.doOnNext ⇢ at org.springframework.web.reactive.result.method.annotation.RequestMappingHandlerAdapter.handle(RequestMappingHandlerAdapter.java:200)
	|_ Mono.doOnNext ⇢ at org.springframework.web.reactive.result.method.annotation.RequestMappingHandlerAdapter.handle(RequestMappingHandlerAdapter.java:201)
Stack trace:
		at org.springframework.security.access.expression.SecurityExpressionRoot.<init>(SecurityExpressionRoot.java:60)
		at org.springframework.security.data.repository.query.SecurityEvaluationContextExtension$1.<init>(SecurityEvaluationContextExtension.java:108)
		at org.springframework.security.data.repository.query.SecurityEvaluationContextExtension.getRootObject(SecurityEvaluationContextExtension.java:108)
		at org.springframework.security.data.repository.query.SecurityEvaluationContextExtension.getRootObject(SecurityEvaluationContextExtension.java:81)
		at org.springframework.data.spel.ExtensionAwareEvaluationContextProvider$EvaluationContextExtensionAdapter.<init>(ExtensionAwareEvaluationContextProvider.java:369)
		at org.springframework.data.spel.ExtensionAwareEvaluationContextProvider.lambda$toAdapters$2(ExtensionAwareEvaluationContextProvider.java:159)
		at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
		at java.base/java.util.stream.SortedOps$SizedRefSortingSink.end(SortedOps.java:357)
		at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
		at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
		at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
		at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
		at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
		at org.springframework.data.spel.ExtensionAwareEvaluationContextProvider.toAdapters(ExtensionAwareEvaluationContextProvider.java:160)
		at org.springframework.data.spel.ExtensionAwareEvaluationContextProvider.access$000(ExtensionAwareEvaluationContextProvider.java:65)
		at org.springframework.data.spel.ExtensionAwareEvaluationContextProvider$ExtensionAwarePropertyAccessor.<init>(ExtensionAwareEvaluationContextProvider.java:182)
		at org.springframework.data.spel.ExtensionAwareEvaluationContextProvider.getEvaluationContext(ExtensionAwareEvaluationContextProvider.java:110)
		at org.springframework.data.repository.query.ExtensionAwareQueryMethodEvaluationContextProvider.getEvaluationContext(ExtensionAwareQueryMethodEvaluationContextProvider.java:88)
		at org.springframework.data.repository.query.SpelEvaluator.evaluate(SpelEvaluator.java:59)
		at org.neo4j.springframework.data.repository.query.ReactiveStringBasedNeo4jQuery.bindParameters(ReactiveStringBasedNeo4jQuery.java:163)
		at org.neo4j.springframework.data.repository.query.ReactiveStringBasedNeo4jQuery.prepareQuery(ReactiveStringBasedNeo4jQuery.java:152)
		at org.neo4j.springframework.data.repository.query.AbstractReactiveNeo4jQuery.execute(AbstractReactiveNeo4jQuery.java:66)
		at org.springframework.data.repository.core.support.QueryExecutorMethodInterceptor$QueryMethodInvoker.invoke(QueryExecutorMethodInterceptor.java:195)
		at org.springframework.data.repository.core.support.QueryExecutorMethodInterceptor.doInvoke(QueryExecutorMethodInterceptor.java:152)
		at org.springframework.data.repository.core.support.QueryExecutorMethodInterceptor.invoke(QueryExecutorMethodInterceptor.java:130)
		at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
		at org.neo4j.springframework.data.repository.support.ReactivePersistenceExceptionTranslationInterceptor.invoke(ReactivePersistenceExceptionTranslationInterceptor.java:74)
		at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
		at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:367)
		at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:118)
		at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
		at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:139)
		at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
		at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:95)
		at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
		at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212)
		at com.sun.proxy.$Proxy166.findOneWithEagerRelationships(Unknown Source)
		at com.okta.developer.blog.web.rest.PostResource.getPost(PostResource.java:200)
		at com.okta.developer.blog.web.rest.PostResource$$FastClassBySpringCGLIB$$f52b2d5e.invoke(<generated>)
		at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
		at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:771)
		at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
		at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)
		at org.springframework.aop.aspectj.AspectJAfterThrowingAdvice.invoke(AspectJAfterThrowingAdvice.java:62)
		at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
		at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)
		at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:88)
		at com.okta.developer.blog.aop.logging.LoggingAspect.logAround(LoggingAspect.java:105)
		at jdk.internal.reflect.GeneratedMethodAccessor95.invoke(Unknown Source)
```

This also fails when running `npm run e2e` in the gateway. Cypress output:

```
  Post e2e test
    ✓ should load Posts (1688ms)
    ✓ should load details Post page (1174ms)
    ✓ should load create Post page (1055ms)
    ✓ should load edit Post page (1077ms)
    ✓ should create an instance of Post (3035ms)
    (Attempt 1 of 3) should delete last instance of Post
    (Attempt 2 of 3) should delete last instance of Post
    1) should delete last instance of Post


  5 passing (31s)
  1 failing

  1) Post e2e test
       should delete last instance of Post:

      Timed out retrying
      + expected - actual

      -5
      +4
```

NOTE: If I generate the same stack using Angular or Vue for the UI, it works, and all tests pass.

```
✔  All specs passed!                        00:54       28       28
```

##### **Motivation for or Use Case**

I expect to be able to create a microservices architecture with React for the UI and all my entity tests to pass.

##### **JHipster Version(s)**

7.0.0-beta.0

**Comment by qmonmert** [comment]
@mraible the bug comes from `PostResource.java`:
``` 
@GetMapping("/posts/{id}")
public Mono<ResponseEntity<Post>> getPost(@PathVariable String id) {
    log.debug("REST request to get Post : {}", id);
    Mono<Post> post = postRepository.findOneWithEagerRelationships(id);
    return ResponseUtil.wrapOrNotFound(post);
}
```

If you update the method `getPost` with that, you don't have the bug
``` 
@GetMapping("/posts/{id}")
public Mono<ResponseEntity<Post>> getPost(@PathVariable String id) {
    log.debug("REST request to get Post : {}", id);
    // Mono<Post> post = postRepository.findOneWithEagerRelationships(id);
    Mono<Post> post = postRepository.findById(id);
    return ResponseUtil.wrapOrNotFound(post);
}
```
but you lose the eager properties on the `getPost` ...

So the problem seems to be the cypher query (but seems to be good):
``` 
@Query("MATCH (e:Post {id: $id}) RETURN e")
Mono<Post> findOneWithEagerRelationships(String id);
``` 
not valid in your case (maybe microservice? proxy?)

I try some fixes without success ...

**Comment by mraible** [comment]
Are you sure it's a server-side issue? It works with Angular and Vue, which makes me think it's a React issue.

**Comment by qmonmert** [comment]
ah, strange that it works with Angular and Vue 🤔

**Comment by qmonmert** [comment]
Indeed it works with Angular

**Comment by mraible** [comment]
Keep it open please.

**Comment by mraible** [comment]
Tested today with the `main` branch. This is still an issue. `npm run e2e` fails with the above JDL.

**Comment by mraible** [comment]
Still happens last time I checked.

**Comment by mraible** [comment]
I think this is still an issue.

**Comment by mraible** [comment]
I tested this today with the JDL above and JHipster v7.0.1. Deleting posts works in Chrome and `npm run e2e` passes, so I'm closing this issue.
