### ISSUE TITLE
JHipster 7.beta.0 - productList.map is not a function

### ISSUE THREAD

**Issue by saturnism** [jhipster/generator-jhipster#13434]
##### **Overview of the issue**

Generated app from https://github.com/jhipster/jdl-samples/blob/main/microservices-blog-store.jh

The "Product" entity page displayed an error with details:

```
An unexpected error has occurred.
Details
TypeError: productList.map is not a function

    at Product (http://35.223.117.127:8080/app/vendors.chunk.js:100684:20)
    at Connect(Product) (http://35.223.117.127:8080/app/vendors.chunk.js:100684:20)
    at ErrorBoundary (eval at ES6ProxyComponentFactory (http://35.223.117.127:8080/app/vendors.chunk.js:100189:10), <anonymous>:14:7)
    at Route (eval at ES6ProxyComponentFactory (http://35.223.117.127:8080/app/vendors.chunk.js:100189:10), <anonymous>:14:7)
    at ErrorBoundaryRoute (http://35.223.117.127:8080/app/vendors.chunk.js:100684:20)
    at Switch (eval at ES6ProxyComponentFactory (http://35.223.117.127:8080/app/vendors.chunk.js:100189:10), <anonymous>:14:7)
    at Routes (http://35.223.117.127:8080/app/vendors.chunk.js:100684:20)
    at ErrorBoundary (eval at ES6ProxyComponentFactory (http://35.223.117.127:8080/app/vendors.chunk.js:100189:10), <anonymous>:14:7)
    at Route (eval at ES6ProxyComponentFactory (http://35.223.117.127:8080/app/vendors.chunk.js:100189:10), <anonymous>:14:7)
    at ErrorBoundaryRoute (http://35.223.117.127:8080/app/vendors.chunk.js:100684:20)
    at Switch (eval at ES6ProxyComponentFactory (http://35.223.117.127:8080/app/vendors.chunk.js:100189:10), <anonymous>:14:7)
    at div
    at Routes (http://35.223.117.127:8080/app/vendors.chunk.js:100684:20)
    at ErrorBoundary (eval at ES6ProxyComponentFactory (http://35.223.117.127:8080/app/vendors.chunk.js:100189:10), <anonymous>:14:7)
    at Route (eval at ES6ProxyComponentFactory (http://35.223.117.127:8080/app/vendors.chunk.js:100189:10), <anonymous>:14:7)
    at PrivateRouteComponent (http://35.223.117.127:8080/app/vendors.chunk.js:100684:20)
    at Connect(PrivateRouteComponent) (http://35.223.117.127:8080/app/vendors.chunk.js:100684:20)
    at Switch (eval at ES6ProxyComponentFactory (http://35.223.117.127:8080/app/vendors.chunk.js:100189:10), <anonymous>:14:7)
    at div
    at Routes
    at ErrorBoundary (eval at ES6ProxyComponentFactory (http://35.223.117.127:8080/app/vendors.chunk.js:100189:10), <anonymous>:14:7)
    at div
    at Card (http://35.223.117.127:8080/app/vendors.chunk.js:100684:20)
    at div
    at div
    at Router (eval at ES6ProxyComponentFactory (http://35.223.117.127:8080/app/vendors.chunk.js:100189:10), <anonymous>:14:7)
    at BrowserRouter (eval at ES6ProxyComponentFactory (http://35.223.117.127:8080/app/vendors.chunk.js:100189:10), <anonymous>:14:7)
    at App (http://35.223.117.127:8080/app/vendors.chunk.js:100684:20)
    at AppContainer (eval at ES6ProxyComponentFactory (http://35.223.117.127:8080/app/vendors.chunk.js:100189:10), <anonymous>:14:7)
    at HotExportedApp (eval at ES6ProxyComponentFactory (http://35.223.117.127:8080/app/vendors.chunk.js:100189:10), <anonymous>:14:7)
    at Connect(HotExportedApp) (http://35.223.117.127:8080/app/vendors.chunk.js:100684:20)
    at div
    at Provider (http://35.223.117.127:8080/app/vendors.chunk.js:100684:20)
    at ErrorBoundary (eval at ES6ProxyComponentFactory (http://35.223.117.127:8080/app/vendors.chunk.js:100189:10), <anonymous>:14:7)

```

##### **Motivation for or Use Case**

To ensure the sample works.

##### **Reproduce the error**

1. Install JHipster 7 beta
2. generate apps from https://github.com/jhipster/jdl-samples/blob/main/microservices-blog-store.jh
3. fix oauth2, or don't use oauth2
4. fix #13432 
5. deploy manifests

##### **Related issues**

N/A

##### **Suggest a Fix**

N/A

##### **JHipster Version(s)**

7.0.0.beta.0

##### **JHipster configuration**

https://github.com/jhipster/jdl-samples/blob/main/microservices-blog-store.jh

**Comment by mraible** [comment]
@saturnism I created a new set of apps with JHipster 7 beta 0 and the JDL you mentioned. I started all the relevant Docker containers, then ran `./mvnw` in each project. I'm unable to reproduce this issue.

Here are the results of `docker ps`:

```
CONTAINER ID   IMAGE                                                 COMMAND                   CREATED         STATUS         PORTS                                                                                                NAMES
46f204f1798c   jboss/keycloak:11.0.1                                 "/opt/jboss/tools/do…"    9 minutes ago   Up 9 minutes   8080/tcp, 127.0.0.1:9080->9080/tcp, 127.0.0.1:9443->9443/tcp, 8443/tcp, 127.0.0.1:10990->10990/tcp   docker_keycloak_1
7fd576364dbb   jhipster/jhipster-registry:v6.5.0                     "/bin/sh -c 'echo \"T…"   9 minutes ago   Up 8 minutes   127.0.0.1:8761->8761/tcp                                                                             docker_jhipster-registry_1
40f6c0604e27   postgres:13.1                                         "docker-entrypoint.s…"    2 weeks ago     Up 9 minutes   127.0.0.1:5432->5432/tcp                                                                             docker_gateway-postgresql_1
26ea64e394db   docker.elastic.co/elasticsearch/elasticsearch:7.6.2   "/usr/local/bin/dock…"    2 weeks ago     Up 9 minutes   127.0.0.1:9200->9200/tcp, 127.0.0.1:9300->9300/tcp                                                   docker_store-elasticsearch_1
8302810263c4   mongo:4.4.2                                           "docker-entrypoint.s…"    2 weeks ago     Up 9 minutes   127.0.0.1:27017->27017/tcp                                                                           docker_store-mongodb_1
```

And here's a screenshot of my browser showing no issues.

![image](https://user-images.githubusercontent.com/17892/104080194-e537d680-51e3-11eb-9fc2-e58c1dbbb8ab.png)

Are there other steps I need to do to reproduce this issue?

**Comment by saturnism** [comment]
ah, i think i remember. the original jdl uses the default frontend generator which is angular, the jdl i tested w/ was using react.

```
application {
  config {
    baseName gateway,
    packageName com.okta.developer.gateway,
    applicationType gateway,
    authenticationType oauth2,
    prodDatabaseType postgresql,
    serviceDiscoveryType eureka,
    testFrameworks [protractor],
    clientFramework react
  }
  entities Blog, Post, Tag, Product
}

application {
  config {
    baseName blog,
    packageName com.okta.developer.blog,
    applicationType microservice,
    authenticationType oauth2,
    prodDatabaseType postgresql,
    serverPort 8081,
    serviceDiscoveryType eureka
  }
  entities Blog, Post, Tag
}

application {
  config {
    baseName store,
    packageName com.okta.developer.store,
    applicationType microservice,
    authenticationType oauth2,
    databaseType mongodb,
    devDatabaseType mongodb,
    prodDatabaseType mongodb,
    enableHibernateCache false,
    searchEngine elasticsearch,
    serverPort 8082,
    serviceDiscoveryType eureka
  }
  entities Product
}

entity Blog {
  name String required minlength(3),
  handle String required minlength(2)
}

entity Post {
  title String required,
  content TextBlob required,
  date Instant required
}

entity Tag {
  name String required minlength(2)
}

entity Product {
  title String required,
  price BigDecimal required min(0),
  image ImageBlob
}

relationship ManyToOne {
  Blog{user(login)} to User,
  Post{blog(name)} to Blog
}

relationship ManyToMany {
  Post{tag(name)} to Tag{post}
}

paginate Post, Tag with infinite-scroll
paginate Product with pagination

microservice Product with store
microservice Blog, Post, Tag with blog


```

**Comment by mraible** [comment]
@saturnism Are you running this locally or in a cloud environment? I just tried it locally and it works fine, which makes me think it's related to some sort of Kubernetes configuration. 

https://user-images.githubusercontent.com/17892/104233767-b0a86280-540f-11eb-9f89-ba459f3d61b5.mp4

**Comment by saturnism** [comment]
it was in the cloud. interesting.

**Comment by saturnism** [comment]
not an issue w/ https://github.com/mraible/choose-jhipster/blob/main/apps.jdl

closing for now.
