### ISSUE TITLE
Creating a blog app with reactive + MySQL doesn't compile

### ISSUE THREAD

**Issue by mraible** [jhipster/generator-jhipster#13467]
##### **Overview of the issue**

If you create a simple blog monolith with reactive and MySQL, it fails to compile.

```
[INFO] --- maven-compiler-plugin:3.8.1:compile (default-compile) @ blog ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 68 source files to /Users/mraible/dev/choose-mono/target/classes
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] /Users/mraible/dev/choose-mono/src/main/java/com/jhipster/demo/blog/repository/BlogRepositoryInternalImpl.java:[5,51] cannot find symbol
  symbol:   class UserRowMapper
  location: package com.jhipster.demo.blog.repository.rowmapper
[ERROR] /Users/mraible/dev/choose-mono/src/main/java/com/jhipster/demo/blog/repository/BlogRepositoryInternalImpl.java:[40,19] cannot find symbol
  symbol:   class UserRowMapper
  location: class com.jhipster.demo.blog.repository.BlogRepositoryInternalImpl
[ERROR] /Users/mraible/dev/choose-mono/src/main/java/com/jhipster/demo/blog/repository/BlogRepositoryInternalImpl.java:[50,9] cannot find symbol
  symbol:   class UserRowMapper
  location: class com.jhipster.demo.blog.repository.BlogRepositoryInternalImpl
[INFO] 3 errors
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
```

##### **Motivation for or Use Case**

I like to show off new features in JHipster. ;)

##### **Reproduce the error**

Create an app with the following JDL, then run `./mvnw`.

```
application {
  config {
    baseName blog
    applicationType monolith
    authenticationType oauth2
    packageName com.jhipster.demo.blog
    prodDatabaseType mysql
    cacheProvider hazelcast
    buildTool maven
    clientFramework vue
    reactive true
    testFrameworks [cypress]
  }
  entities *
}

entity Blog {
  name String required minlength(3)
  handle String required minlength(2)
}

entity Post {
  title String required
  content TextBlob required
  date Instant required
}

entity Tag {
  name String required minlength(2)
}

relationship ManyToOne {
  Blog{user(login)} to User
  Post{blog(name)} to Blog
}

relationship ManyToMany {
  Post{tag(name)} to Tag{entry}
}

paginate Post, Tag with infinite-scroll
```

##### **Suggest a Fix**

It looks like the `UserRowMapper` is missing, so maybe it just needs to be added?

![image](https://user-images.githubusercontent.com/17892/104263969-e10bf300-5447-11eb-8a68-9e773322772b.png)

##### **JHipster Version(s)**

7.0 beta 0

**Comment by mraible** [comment]
I was able to fix these compile errors by adding a `UserRowMapper` and changing `User.id` to `String` rather than `Long`.

```diff
Index: src/main/java/com/jhipster/demo/blog/repository/rowmapper/UserRowMapper.java
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/src/main/java/com/jhipster/demo/blog/repository/rowmapper/UserRowMapper.java b/src/main/java/com/jhipster/demo/blog/repository/rowmapper/UserRowMapper.java
new file mode 100644
--- /dev/null	(date 1610420826340)
+++ b/src/main/java/com/jhipster/demo/blog/repository/rowmapper/UserRowMapper.java	(date 1610420826340)
@@ -0,0 +1,40 @@
+package com.jhipster.demo.blog.repository.rowmapper;
+
+import com.jhipster.demo.blog.domain.User;
+import com.jhipster.demo.blog.service.ColumnConverter;
+import io.r2dbc.spi.Row;
+import org.springframework.stereotype.Service;
+
+import java.util.function.BiFunction;
+
+/**
+ * Converter between {@link Row} to {@link User}, with proper type conversions.
+ */
+@Service
+public class UserRowMapper implements BiFunction<Row, String, User> {
+    private final ColumnConverter converter;
+
+    public UserRowMapper(ColumnConverter converter) {
+        this.converter = converter;
+    }
+
+    /**
+     * Take a {@link Row} and a column prefix, and extract all the fields.
+     *
+     * @return the {@link User} stored in the database.
+     */
+    @Override
+    public User apply(Row row, String prefix) {
+        User entity = new User();
+        entity.setId(row.get(prefix + "_id", String.class));
+        entity.setLogin(converter.fromRow(row, prefix + "_login", String.class));
+        entity.setFirstName(converter.fromRow(row, prefix + "_first_name", String.class));
+        entity.setLastName(converter.fromRow(row, prefix + "_last_name", String.class));
+        entity.setEmail(converter.fromRow(row, prefix + "_email", String.class));
+        entity.setActivated(Boolean.TRUE.equals(converter.fromRow(row, prefix + "_activated", Boolean.class)));
+        entity.setLangKey(converter.fromRow(row, prefix + "_lang_key", String.class));
+        entity.setImageUrl(converter.fromRow(row, prefix + "_image_url", String.class));
+        return entity;
+    }
+
+}
Index: src/main/java/com/jhipster/demo/blog/domain/Blog.java
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/src/main/java/com/jhipster/demo/blog/domain/Blog.java b/src/main/java/com/jhipster/demo/blog/domain/Blog.java
--- a/src/main/java/com/jhipster/demo/blog/domain/Blog.java	(revision e51b5779941ed3273013484f491b52a02a3aba99)
+++ b/src/main/java/com/jhipster/demo/blog/domain/Blog.java	(date 1610420960513)
@@ -32,7 +32,7 @@
     private User user;
 
     @Column("user_id")
-    private Long userId;
+    private String userId;
 
     // jhipster-needle-entity-add-field - JHipster will add fields here
     public Long getId() {
@@ -89,11 +89,11 @@
         this.userId = user != null ? user.getId() : null;
     }
 
-    public Long getUserId() {
+    public String getUserId() {
         return this.userId;
     }
 
-    public void setUserId(Long user) {
+    public void setUserId(String user) {
         this.userId = user;
     }
 
Index: src/main/java/com/jhipster/demo/blog/repository/rowmapper/BlogRowMapper.java
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/src/main/java/com/jhipster/demo/blog/repository/rowmapper/BlogRowMapper.java b/src/main/java/com/jhipster/demo/blog/repository/rowmapper/BlogRowMapper.java
--- a/src/main/java/com/jhipster/demo/blog/repository/rowmapper/BlogRowMapper.java	(revision e51b5779941ed3273013484f491b52a02a3aba99)
+++ b/src/main/java/com/jhipster/demo/blog/repository/rowmapper/BlogRowMapper.java	(date 1610420968092)
@@ -28,7 +28,7 @@
         entity.setId(converter.fromRow(row, prefix + "_id", Long.class));
         entity.setName(converter.fromRow(row, prefix + "_name", String.class));
         entity.setHandle(converter.fromRow(row, prefix + "_handle", String.class));
-        entity.setUserId(converter.fromRow(row, prefix + "_user_id", Long.class));
+        entity.setUserId(converter.fromRow(row, prefix + "_user_id", String.class));
         return entity;
     }
 }
```

**Comment by mraible** [comment]
If I try to add a new `Blog` entity, it fails with the following error.

```
2021-01-11 20:12:01.666 ERROR 83773 --- [ctor-http-nio-9] o.z.problem.spring.common.AdviceTraits   : Internal Server Error

org.springframework.data.r2dbc.BadSqlGrammarException: executeMany; bad SQL grammar [SELECT e.id AS e_id, e.name AS e_name, e.handle AS e_handle, e.user_id AS e_user_id, e_user.id AS user_id, e_user.login AS user_login, e_user.password_hash AS user_password, e_user.first_name AS user_first_name, e_user.last_name AS user_last_name, e_user.email AS user_email, e_user.activated AS user_activated, e_user.lang_key AS user_lang_key, e_user.image_url AS user_image_url, e_user.activation_key AS user_activation_key, e_user.reset_key AS user_reset_key, e_user.reset_date AS user_reset_date FROM blog e LEFT OUTER JOIN jhi_user AS e_user ON e.user_id = e_user.id]; nested exception is io.r2dbc.spi.R2dbcBadGrammarException: [42122] [42S22] Column "E_USER.PASSWORD_HASH" not found; SQL statement:
SELECT e.id AS e_id, e.name AS e_name, e.handle AS e_handle, e.user_id AS e_user_id, e_user.id AS user_id, e_user.login AS user_login, e_user.password_hash AS user_password, e_user.first_name AS user_first_name, e_user.last_name AS user_last_name, e_user.email AS user_email, e_user.activated AS user_activated, e_user.lang_key AS user_lang_key, e_user.image_url AS user_image_url, e_user.activation_key AS user_activation_key, e_user.reset_key AS user_reset_key, e_user.reset_date AS user_reset_date FROM blog e LEFT OUTER JOIN jhi_user AS e_user ON e.user_id = e_user.id [42122-200]
	at org.springframework.data.r2dbc.support.R2dbcExceptionSubclassTranslator.doTranslate(R2dbcExceptionSubclassTranslator.java:84)
	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException:
Assembly trace from producer [reactor.core.publisher.MonoError] :

Error has been observed at the following site(s):
	|_    Flux.onErrorMap ⇢ at org.springframework.data.r2dbc.core.DefaultDatabaseClient.inConnectionMany(DefaultDatabaseClient.java:200)
	|_   Flux.collectList ⇢ at com.jhipster.demo.blog.web.rest.BlogResource.getAllBlogs(BlogResource.java:156)
	|_     Mono.usingWhen ⇢ at org.springframework.transaction.interceptor.TransactionAspectSupport$ReactiveTransactionSupport.lambda$null$3(TransactionAspectSupport.java:870)
```

I believe this happens because the `PASSWORD_HASH` isn't a column when using OAuth 2.0. Commenting out the line that references this column, `activation_key`, and `reset_*`, in `UserRepository$UserSQLHelper` seems to solve it.

```java
class UserSqlHelper {

    static List<Expression> getColumns(Table table, String columnPrefix) {
        List<Expression> columns = new ArrayList<>();
        columns.add(Column.aliased("id", table, columnPrefix + "_id"));
        columns.add(Column.aliased("login", table, columnPrefix + "_login"));
        //columns.add(Column.aliased("password_hash", table, columnPrefix + "_password"));
        columns.add(Column.aliased("first_name", table, columnPrefix + "_first_name"));
        columns.add(Column.aliased("last_name", table, columnPrefix + "_last_name"));
        columns.add(Column.aliased("email", table, columnPrefix + "_email"));
        columns.add(Column.aliased("activated", table, columnPrefix + "_activated"));
        columns.add(Column.aliased("lang_key", table, columnPrefix + "_lang_key"));
        columns.add(Column.aliased("image_url", table, columnPrefix + "_image_url"));
        //columns.add(Column.aliased("activation_key", table, columnPrefix + "_activation_key"));
        //columns.add(Column.aliased("reset_key", table, columnPrefix + "_reset_key"));
        //columns.add(Column.aliased("reset_date", table, columnPrefix + "_reset_date"));

        return columns;
    }
}
```

`npm run e2e` passes too!

```
       Spec                                              Tests  Passing  Failing  Pending  Skipped
  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ ✔  administration/administration.spec.      00:05        4        4        -        -        - │
  │    ts                                                                                          │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  entity/blog.spec.ts                      00:18        6        6        -        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  entity/post.spec.ts                      00:18        6        6        -        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  entity/tag.spec.ts                       00:16        6        6        -        -        - │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘
    ✔  All specs passed!                        00:59       22       22        -        -        -

Execution time: 1 min. 15 s.
```
