### ISSUE TITLE
JHipster 7 beta.0 - mvn verify fails

### ISSUE THREAD

**Issue by saturnism** [jhipster/generator-jhipster#13479]
##### **Overview of the issue**

`mvn verify` fails for newly generated app

```
...
[ERROR] Tests run: 13, Failures: 2, Errors: 0, Skipped: 0, Time elapsed: 5.665 s <<< FAILURE! - in com.okta.developer.store.web.rest.ProductResourceIT
...
[ERROR] com.okta.developer.store.web.rest.ProductResourceIT.checkPriceIsRequired  Time elapsed: 0.03 s  <<< FAILURE!
java.lang.AssertionError:
Status expected:<400 BAD_REQUEST> but was:<500 INTERNAL_SERVER_ERROR>
...
[ERROR] Tests run: 9, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.148 s <<< FAILURE! - in com.okta.developer.store.web.rest.errors.ExceptionTranslatorIT
...
[ERROR]   ProductResourceIT.checkPriceIsRequired:173 Status expected:<400 BAD_REQUEST> but was:<500 INTERNAL_SERVER_ERROR>
...
[ERROR]   ProductResourceIT.checkTitleIsRequired:152 Status expected:<400 BAD_REQUEST> but was:<500 INTERNAL_SERVER_ERROR>
...
[ERROR]   ExceptionTranslatorIT.testMethodArgumentNotValid:59 JSON path "$.message" expected:<error.validation> but was:<error.http.500>
...
[ERROR] Tests run: 36, Failures: 3, Errors: 0, Skipped: 0
```

##### **Motivation for or Use Case**

Preparing for a demo.

##### **Reproduce the error**

1. generate app from jdl: https://raw.githubusercontent.com/mraible/choose-jhipster/main/apps.jdl
2. `cd store && ./mvnw verify`

##### **JHipster Version(s)**

7.0.0.beta.0

##### **JHipster configuration**

```
application {
  config {
    applicationType gateway
    baseName gateway
    clientFramework vue
    reactive true
    packageName com.okta.developer.gateway
    authenticationType oauth2
    prodDatabaseType postgresql
    serviceDiscoveryType eureka
    testFrameworks [cypress]
  }
  entities Blog, Post, Tag, Product
}

application {
  config {
    applicationType microservice
    baseName blog
    reactive true
    packageName com.okta.developer.blog
    authenticationType oauth2
    prodDatabaseType mysql
    serverPort 8081,
    serviceDiscoveryType eureka
  }
  entities Blog, Post, Tag
}

application {
  config {
    applicationType microservice
    baseName store
    reactive true
    packageName com.okta.developer.store
    authenticationType oauth2
    databaseType mongodb
    devDatabaseType mongodb
    prodDatabaseType mongodb
    enableHibernateCache false
    serverPort 8082
    serviceDiscoveryType eureka
  }
  entities Product
}

entity Blog {
  name String required minlength(3)
  handle String required minlength(2)
}

entity Post {
  title String required
  content TextBlob required
  date Instant required
}

entity Tag {
  name String required minlength(2)
}

entity Product {
  title String required
  price BigDecimal required min(0)
  image ImageBlob
}

relationship ManyToOne {
  Blog{user(login)} to User
  Post{blog(name)} to Blog
}

relationship ManyToMany {
  Post{tag(name)} to Tag{post}
}

paginate Post, Tag with infinite-scroll
paginate Product with pagination

microservice Product with store
microservice Blog, Post, Tag with blog

deployment {
  deploymentType docker-compose
  appsFolders [gateway, blog, store]
  dockerRepositoryName "mraible"
}

```

##### **Browsers and Operating System**

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by mraible** [comment]
It looks like it works for the `gateway` project (which is reactive + postgresql). 

```
[INFO] Built image to Docker daemon as gateway
[INFO]
[INFO] A new version of Jib (2.7.1) is available (currently using 2.7.0). Update your build configuration to use the latest features and fixes!
[INFO] https://github.com/GoogleContainerTools/jib/blob/master/jib-maven-plugin/CHANGELOG.md
[INFO] Please see https://github.com/GoogleContainerTools/jib/blob/master/docs/privacy.md for info on disabling this update check.
[INFO]
[INFO] Executing tasks:
[INFO] [==============================] 100.0% complete
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
```

I changed the `blog` project to use Couchbase and it fails even worse.
```
[INFO] Scanning for projects...
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[ERROR] 'dependencies.dependency.version' for com.couchbase.client:encryption:jar is missing. @ line 143, column 21
 @
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]
[ERROR]   The project com.okta.developer.blog:blog:0.0.1-SNAPSHOT (/Users/mraible/dev/choose-jhipster/blog/pom.xml) has 1 error
[ERROR]     'dependencies.dependency.version' for com.couchbase.client:encryption:jar is missing. @ line 143, column 21
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
```

I can confirm the `store` project fails with `./mvnw -ntp -Pprod verify jib:dockerBuild`:

```
[ERROR] Tests run: 9, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.166 s <<< FAILURE! - in com.okta.developer.store.web.rest.errors.ExceptionTranslatorIT
[ERROR] com.okta.developer.store.web.rest.errors.ExceptionTranslatorIT.testMethodArgumentNotValid  Time elapsed: 0.027 s  <<< FAILURE!
java.lang.AssertionError: JSON path "$.message" expected:<error.validation> but was:<error.http.500>
	at com.okta.developer.store.web.rest.errors.ExceptionTranslatorIT.testMethodArgumentNotValid(ExceptionTranslatorIT.java:59)

[INFO]
[INFO] Results:
[INFO]
[ERROR] Failures:
[ERROR]   ProductResourceIT.checkPriceIsRequired:173 Status expected:<400 BAD_REQUEST> but was:<500 INTERNAL_SERVER_ERROR>

> POST /api/products
> WebTestClient-Request-Id: [1]
> Content-Type: [application/json]
> Content-Length: [68]

{"title":"AAAAAAAAAA","image":"AA==","imageContentType":"image/jpg"}

< 500 INTERNAL_SERVER_ERROR Internal Server Error
< Vary: [Origin, Access-Control-Request-Method, Access-Control-Request-Headers]
< Content-Type: [application/problem+json]
< Content-Length: [221]
< Cache-Control: [no-cache, no-store, max-age=0, must-revalidate]
< Pragma: [no-cache]
< Expires: [0]
< X-Content-Type-Options: [nosniff]
< X-XSS-Protection: [1 ; mode=block]
< Feature-Policy: [geolocation 'none'; midi 'none'; sync-xhr 'none'; microphone 'none'; camera 'none'; magnetometer 'none'; gyroscope 'none'; fullscreen 'self'; payment 'none']
< Content-Security-Policy: [default-src 'self'; frame-src 'self' data:; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://storage.googleapis.com https://www.google-analytics.com; style-src 'self' 'unsafe-inline'; img-src 'self' data: https://www.google-analytics.com; font-src 'self' data:]
< Referrer-Policy: [strict-origin-when-cross-origin]

221 bytes of content.

[ERROR]   ProductResourceIT.checkTitleIsRequired:152 Status expected:<400 BAD_REQUEST> but was:<500 INTERNAL_SERVER_ERROR>

> POST /api/products
> WebTestClient-Request-Id: [1]
> Content-Type: [application/json]
> Content-Length: [57]

{"price":0,"image":"AA==","imageContentType":"image/jpg"}

< 500 INTERNAL_SERVER_ERROR Internal Server Error
< Vary: [Origin, Access-Control-Request-Method, Access-Control-Request-Headers]
< Content-Type: [application/problem+json]
< Content-Length: [221]
< Cache-Control: [no-cache, no-store, max-age=0, must-revalidate]
< Pragma: [no-cache]
< Expires: [0]
< X-Content-Type-Options: [nosniff]
< X-XSS-Protection: [1 ; mode=block]
< Feature-Policy: [geolocation 'none'; midi 'none'; sync-xhr 'none'; microphone 'none'; camera 'none'; magnetometer 'none'; gyroscope 'none'; fullscreen 'self'; payment 'none']
< Content-Security-Policy: [default-src 'self'; frame-src 'self' data:; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://storage.googleapis.com https://www.google-analytics.com; style-src 'self' 'unsafe-inline'; img-src 'self' data: https://www.google-analytics.com; font-src 'self' data:]
< Referrer-Policy: [strict-origin-when-cross-origin]

221 bytes of content.

[ERROR]   ExceptionTranslatorIT.testMethodArgumentNotValid:59 JSON path "$.message" expected:<error.validation> but was:<error.http.500>
[INFO]
[ERROR] Tests run: 36, Failures: 3, Errors: 0, Skipped: 0
```

**Comment by mraible** [comment]
It seems all tests in the `store` app are failing because we're using `@Valid` on entities and there's an i18n message lookup.

```
Stack trace:
		at java.base/java.io.RandomAccessFile.readBytes(RandomAccessFile.java)
		at java.base/java.io.RandomAccessFile.read(RandomAccessFile.java:406)
		at java.base/java.io.RandomAccessFile.readFully(RandomAccessFile.java:470)
		at java.base/java.util.zip.ZipFile$Source.readFullyAt(ZipFile.java:1298)
		at java.base/java.util.zip.ZipFile$ZipFileInputStream.initDataOffset(ZipFile.java:997)
		at java.base/java.util.zip.ZipFile$ZipFileInputStream.read(ZipFile.java:1012)
		at java.base/java.util.zip.ZipFile$ZipFileInflaterInputStream.fill(ZipFile.java:467)
		at java.base/java.util.zip.InflaterInputStream.read(InflaterInputStream.java:159)
		at java.base/java.io.InputStream.readNBytes(InputStream.java:490)
		at java.base/java.util.jar.JarFile.getBytes(JarFile.java:805)
		at java.base/java.util.jar.JarFile.checkForSpecialAttributes(JarFile.java:1005)
		at java.base/java.util.jar.JarFile.isMultiRelease(JarFile.java:388)
		at java.base/java.util.jar.JarFile.getEntry(JarFile.java:507)
		at java.base/sun.net.www.protocol.jar.URLJarFile.getEntry(URLJarFile.java:131)
		at java.base/sun.net.www.protocol.jar.JarURLConnection.connect(JarURLConnection.java:137)
		at java.base/sun.net.www.protocol.jar.JarURLConnection.getInputStream(JarURLConnection.java:155)
		at java.base/java.util.ResourceBundle$Control$1.run(ResourceBundle.java:3227)
		at java.base/java.util.ResourceBundle$Control$1.run(ResourceBundle.java:3216)
		at java.base/java.security.AccessController.doPrivileged(Native Method)
		at java.base/java.util.ResourceBundle$Control.newBundle(ResourceBundle.java:3215)
		at java.base/java.util.ResourceBundle.loadBundle(ResourceBundle.java:1994)
		at java.base/java.util.ResourceBundle.findBundle(ResourceBundle.java:1776)
		at java.base/java.util.ResourceBundle.findBundle(ResourceBundle.java:1728)
		at java.base/java.util.ResourceBundle.findBundle(ResourceBundle.java:1728)
		at java.base/java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1662)
		at java.base/java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1593)
		at java.base/java.util.ResourceBundle.getBundle(ResourceBundle.java:1284)
		at org.hibernate.validator.resourceloading.PlatformResourceBundleLocator.loadBundle(PlatformResourceBundleLocator.java:234)
		at org.hibernate.validator.resourceloading.PlatformResourceBundleLocator.doGetResourceBundle(PlatformResourceBundleLocator.java:199)
		at org.hibernate.validator.resourceloading.PlatformResourceBundleLocator.getResourceBundle(PlatformResourceBundleLocator.java:183)
		at org.hibernate.validator.messageinterpolation.AbstractMessageInterpolator.resolveMessage(AbstractMessageInterpolator.java:450)
		at org.hibernate.validator.messageinterpolation.AbstractMessageInterpolator.lambda$interpolateMessage$0(AbstractMessageInterpolator.java:399)
		at java.base/java.util.concurrent.ConcurrentMap.computeIfAbsent(ConcurrentMap.java:330)
		at org.hibernate.validator.messageinterpolation.AbstractMessageInterpolator.interpolateMessage(AbstractMessageInterpolator.java:399)
		at org.hibernate.validator.messageinterpolation.AbstractMessageInterpolator.interpolate(AbstractMessageInterpolator.java:355)
		at org.springframework.validation.beanvalidation.LocaleContextMessageInterpolator.interpolate(LocaleContextMessageInterpolator.java:51)
		at org.hibernate.validator.internal.engine.validationcontext.AbstractValidationContext.interpolate(AbstractValidationContext.java:313)
		at org.hibernate.validator.internal.engine.validationcontext.AbstractValidationContext.addConstraintFailure(AbstractValidationContext.java:230)
		at org.hibernate.validator.internal.engine.constraintvalidation.ConstraintTree.validateConstraints(ConstraintTree.java:79)
		at org.hibernate.validator.internal.metadata.core.MetaConstraint.doValidateConstraint(MetaConstraint.java:130)
		at org.hibernate.validator.internal.metadata.core.MetaConstraint.validateConstraint(MetaConstraint.java:123)
		at org.hibernate.validator.internal.engine.ValidatorImpl.validateMetaConstraint(ValidatorImpl.java:555)
		at org.hibernate.validator.internal.engine.ValidatorImpl.validateConstraintsForSingleDefaultGroupElement(ValidatorImpl.java:518)
		at org.hibernate.validator.internal.engine.ValidatorImpl.validateConstraintsForDefaultGroup(ValidatorImpl.java:488)
		at org.hibernate.validator.internal.engine.ValidatorImpl.validateConstraintsForCurrentGroup(ValidatorImpl.java:450)
		at org.hibernate.validator.internal.engine.ValidatorImpl.validateInContext(ValidatorImpl.java:400)
		at org.hibernate.validator.internal.engine.ValidatorImpl.validate(ValidatorImpl.java:172)
		at org.springframework.validation.beanvalidation.SpringValidatorAdapter.validate(SpringValidatorAdapter.java:117)
		at org.springframework.boot.autoconfigure.validation.ValidatorAdapter.validate(ValidatorAdapter.java:70)
		at org.springframework.validation.DataBinder.validate(DataBinder.java:889)
		at org.springframework.web.reactive.result.method.annotation.AbstractMessageReaderArgumentResolver.validate(AbstractMessageReaderArgumentResolver.java:256)
		at org.springframework.web.reactive.result.method.annotation.AbstractMessageReaderArgumentResolver.lambda$readBody$6(AbstractMessageReaderArgumentResolver.java:198)
```

**Comment by mraible** [comment]
If I change the `TestDTO` and `Product` entities from using `@NotNull` to `@NotNull(message = "must not be null")`, all tests pass. I'm not sure if this is the best solution.

**Comment by mraible** [comment]
@cbornet Does adding a default message to our `@NotNull` annotations sounds like a good solution to fix reactive tests that use validation?
