### ISSUE TITLE
Add Neo4j to Kubernetes/Helm deployment sub generators

### ISSUE THREAD

**Issue by saturnism** [jhipster/generator-jhipster#13477]
##### **Overview of the issue**

Generated new app with https://github.com/mraible/choose-jhipster/blob/main/apps.jdl, and ran `jhipster kubernetes`.

I did not build the container images first.

```
Checking Docker images in applications directories...
ls: no such file or directory: /Users/rayt/tmp/test1/blog/target/jib-cache
ls: no such file or directory: /Users/rayt/tmp/test1/gateway/target/jib-cache
ls: no such file or directory: /Users/rayt/tmp/test1/store/target/jib-cache
ERROR! generator.warning is not a function
TypeError: generator.warning is not a function
    at /Users/rayt/.nvm/versions/node/v12.20.1/lib/node_modules/generator-jhipster/generators/utils.js:254:23
    at tryHandleCache (/Users/rayt/.nvm/versions/node/v12.20.1/lib/node_modules/generator-jhipster/node_modules/ejs/lib/ejs.js:275:14)
    at Object.exports.renderFile (/Users/rayt/.nvm/versions/node/v12.20.1/lib/node_modules/generator-jhipster/node_modules/ejs/lib/ejs.js:489:10)
    at Object.renderContent (/Users/rayt/.nvm/versions/node/v12.20.1/lib/node_modules/generator-jhipster/generators/utils.js:250:9)
    at module.exports.template (/Users/rayt/.nvm/versions/node/v12.20.1/lib/node_modules/generator-jhipster/generators/generator-base-private.js:755:23)
    at module.exports.writeDeployments (/Users/rayt/.nvm/versions/node/v12.20.1/lib/node_modules/generator-jhipster/generators/kubernetes/files.js:36:26)
    at Object.<anonymous> (/Users/rayt/.nvm/versions/node/v12.20.1/lib/node_modules/generator-jhipster/node_modules/yeoman-generator/lib/index.js:991:25)
    at /Users/rayt/.nvm/versions/node/v12.20.1/lib/node_modules/generator-jhipster/node_modules/run-async/index.js:49:25
    at new Promise (<anonymous>)
    at /Users/rayt/.nvm/versions/node/v12.20.1/lib/node_modules/generator-jhipster/node_modules/run-async/index.js:26:19
```

##### **Motivation for or Use Case**

Preparing for a demo.

##### **Reproduce the error**

1. Generate apps with https://github.com/mraible/choose-jhipster/blob/main/apps.jdl
2. `mkdir k8s && cd k8s && jhipster kubernetes`

##### **Suggest a Fix**

1. If a template does not exist, rather than failing w/ obscured error, show which template is missing, etc.
2. add neo4j template

##### **JHipster Version(s)**

7.0.0.beta.0

##### **JHipster configuration**

```
application {
  config {
    applicationType gateway
    baseName gateway
    clientFramework vue
    reactive true
    packageName com.okta.developer.gateway
    authenticationType oauth2
    prodDatabaseType postgresql
    serviceDiscoveryType eureka
    testFrameworks [cypress]
  }
  entities Blog, Post, Tag, Product
}

application {
  config {
    applicationType microservice
    baseName blog
    reactive true
    packageName com.okta.developer.blog
    authenticationType oauth2
    databaseType neo4j
    devDatabaseType neo4j
    prodDatabaseType neo4j
    enableHibernateCache false
    serverPort 8081,
    serviceDiscoveryType eureka
  }
  entities Blog, Post, Tag
}

application {
  config {
    applicationType microservice
    baseName store
    reactive true
    packageName com.okta.developer.store
    authenticationType oauth2
    databaseType mongodb
    devDatabaseType mongodb
    prodDatabaseType mongodb
    enableHibernateCache false
    serverPort 8082
    serviceDiscoveryType eureka
  }
  entities Product
}

entity Blog {
  name String required minlength(3)
  handle String required minlength(2)
}

entity Post {
  title String required
  content TextBlob required
  date Instant required
}

entity Tag {
  name String required minlength(2)
}

entity Product {
  title String required
  price BigDecimal required min(0)
  image ImageBlob
}

relationship ManyToOne {
  Blog{user(login)} to User
  Post{blog(name)} to Blog
}

relationship ManyToMany {
  Post{tag(name)} to Tag{post}
}

paginate Post, Tag with infinite-scroll
paginate Product with pagination

microservice Product with store
microservice Blog, Post, Tag with blog

deployment {
  deploymentType docker-compose
  appsFolders [gateway, blog, store]
  dockerRepositoryName "mraible"
}
```

##### **Browsers and Operating System**

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by saturnism** [comment]
It looks like the issue is with `neo4j`, there is no template for neo4j deployment.

**Comment by atomfrede** [comment]
Is this the same as https://github.com/jhipster/generator-jhipster/issues/11731 or is here more?

**Comment by mraible** [comment]
@atomfrede Yes, I believe so.

**Comment by pascalgrimaud** [comment]
@atomfrede : I closed the other ticket as this one contains a JDL so it's more completed
