### ISSUE TITLE
Reactive gateway fails to connects to PostgreSQL

### ISSUE THREAD

**Issue by mraible** [jhipster/generator-jhipster#13532]
##### **Overview of the issue**

```
gateway_1             | org.postgresql.util.PSQLException: Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
gateway_1             | 	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:303)
gateway_1             | 	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:51)
gateway_1             | 	at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:225)
gateway_1             | 	at org.postgresql.Driver.makeConnection(Driver.java:465)
gateway_1             | 	at org.postgresql.Driver.connect(Driver.java:264)
```

##### **Motivation for or Use Case**

You should be able to run a reactive microservices architecture with Docker Compose.

##### **Reproduce the error**

Create an app with the following JDL and start it with Docker Compose.

```
application {
  config {
    baseName gateway
    reactive true
    packageName com.okta.developer.gateway
    applicationType gateway
    authenticationType oauth2
    buildTool gradle
    clientFramework vue
    prodDatabaseType postgresql
    serviceDiscoveryType eureka
    testFrameworks [protractor]
  }
  entities Blog, Post, Tag, Product
}

application {
  config {
    baseName blog
    reactive true
    packageName com.okta.developer.blog
    applicationType microservice
    authenticationType oauth2
    buildTool gradle
    databaseType neo4j
    devDatabaseType neo4j
    prodDatabaseType neo4j
    enableHibernateCache false
    serverPort 8081
    serviceDiscoveryType eureka
  }
  entities Blog, Post, Tag
}

application {
  config {
    baseName store
    reactive true
    packageName com.okta.developer.store
    applicationType microservice
    authenticationType oauth2
    buildTool gradle
    databaseType mongodb
    devDatabaseType mongodb
    prodDatabaseType mongodb
    enableHibernateCache false
    serverPort 8082
    serviceDiscoveryType eureka
  }
  entities Product
}

entity Blog {
  name String required minlength(3)
  handle String required minlength(2)
}

entity Post {
  title String required
  content TextBlob required
  date Instant required
}

entity Tag {
  name String required minlength(2)
}

entity Product {
  title String required
  price BigDecimal required min(0)
  image ImageBlob
}

relationship ManyToOne {
  Blog{user(login)} to User
  Post{blog(name)} to Blog
}

relationship ManyToMany {
  Post{tag(name)} to Tag{post}
}

paginate Post, Tag with infinite-scroll
paginate Product with pagination

microservice Product with store
microservice Blog, Post, Tag with blog

deployment {
  deploymentType docker-compose
  appsFolders [gateway, blog, store]
  dockerRepositoryName "mraible"
}
```

##### **Suggest a Fix**

The gateway's config has `SPRING_DATASOURCE_URL` in `docker-compose.yml`. This should probably be R2DBC.

##### **JHipster Version(s)**

`main` branch

**Comment by mraible** [comment]
Fixed in https://github.com/jhipster/generator-jhipster/pull/13530/files#diff-1bfaf6e31fe218cd507027450c04913b93f510df3f63b4a2ea84163c6423e9fbR44.
