### ISSUE TITLE
Incremental Changelog: update for fake-data

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/generator-jhipster#13688]
##### **Overview of the issue**

After updating the JDL, there is a new CSV file for updating fake-data which is not correct. The `id` is missing

##### **Motivation for or Use Case**

With that, the application can't start correctly, and failed with:

```
2021-01-22 17:26:03.761 ERROR 29883 --- [  burger-task-1] t.j.c.liquibase.AsyncSpringLiquibase     : Liquibase could not start correctly, your database is NOT ready: liquibase.exception.MigrationFailedException: Migration failed for change set config/liquibase/changelog/20210122162347_updated_entity_migrate_Beer.xml::20210122162347-columns-faker::jhipster:
     Reason: liquibase.exception.DatabaseException: ERROR: null value in column "id" of relation "beer" violates not-null constraint
  Détail : Failing row contains (null, null, Shoes incentivize).
  Où : SQL statement "INSERT INTO public.beer (description) VALUES ('Shoes incentivize')"
PL/pgSQL function inline_code_block line 5 at SQL statement [Failed SQL: (0) DO
$$
BEGIN
UPDATE public.beer SET description = 'Shoes incentivize' WHERE id is NULL;
IF not found THEN
INSERT INTO public.beer (description) VALUES ('Shoes incentivize');
END IF;
END;
$$
LANGUAGE plpgsql;]

liquibase.exception.LiquibaseException: liquibase.exception.MigrationFailedException: Migration failed for change set config/liquibase/changelog/20210122162347_updated_entity_migrate_Beer.xml::20210122162347-columns-faker::jhipster:
     Reason: liquibase.exception.DatabaseException: ERROR: null value in column "id" of relation "beer" violates not-null constraint
  Détail : Failing row contains (null, null, Shoes incentivize).
  Où : SQL statement "INSERT INTO public.beer (description) VALUES ('Shoes incentivize')"
PL/pgSQL function inline_code_block line 5 at SQL statement [Failed SQL: (0) DO
$$
BEGIN
UPDATE public.beer SET description = 'Shoes incentivize' WHERE id is NULL;
IF not found THEN
INSERT INTO public.beer (description) VALUES ('Shoes incentivize');
END IF;
END;
$$
LANGUAGE plpgsql;]
	at liquibase.changelog.ChangeLogIterator.run(ChangeLogIterator.java:124)
	at liquibase.Liquibase.lambda$null$0(Liquibase.java:275)
	at liquibase.Scope.lambda$child$0(Scope.java:160)
	at liquibase.Scope.child(Scope.java:169)
	at liquibase.Scope.child(Scope.java:159)
	at liquibase.Scope.child(Scope.java:138)
	at liquibase.Scope.child(Scope.java:222)
	at liquibase.Liquibase.lambda$update$1(Liquibase.java:274)
	at liquibase.Scope.lambda$child$0(Scope.java:160)
	at liquibase.Scope.child(Scope.java:169)
	at liquibase.Scope.child(Scope.java:159)
	at liquibase.Scope.child(Scope.java:138)
	at liquibase.Liquibase.runInScope(Liquibase.java:2277)
	at liquibase.Liquibase.update(Liquibase.java:215)
	at liquibase.Liquibase.update(Liquibase.java:201)
	at liquibase.integration.spring.SpringLiquibase.performUpdate(SpringLiquibase.java:321)
	at liquibase.integration.spring.SpringLiquibase.afterPropertiesSet(SpringLiquibase.java:269)
	at org.springframework.boot.autoconfigure.liquibase.DataSourceClosingSpringLiquibase.afterPropertiesSet(DataSourceClosingSpringLiquibase.java:46)
	at tech.jhipster.config.liquibase.AsyncSpringLiquibase.initDb(AsyncSpringLiquibase.java:118)
	at tech.jhipster.config.liquibase.AsyncSpringLiquibase.lambda$afterPropertiesSet$0(AsyncSpringLiquibase.java:93)
	at tech.jhipster.async.ExceptionHandlingAsyncTaskExecutor.lambda$createWrappedRunnable$1(ExceptionHandlingAsyncTaskExecutor.java:78)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: liquibase.exception.MigrationFailedException: Migration failed for change set config/liquibase/changelog/20210122162347_updated_entity_migrate_Beer.xml::20210122162347-columns-faker::jhipster:
     Reason: liquibase.exception.DatabaseException: ERROR: null value in column "id" of relation "beer" violates not-null constraint
  Détail : Failing row contains (null, null, Shoes incentivize).
  Où : SQL statement "INSERT INTO public.beer (description) VALUES ('Shoes incentivize')"
PL/pgSQL function inline_code_block line 5 at SQL statement [Failed SQL: (0) DO
$$
BEGIN
UPDATE public.beer SET description = 'Shoes incentivize' WHERE id is NULL;
IF not found THEN
INSERT INTO public.beer (description) VALUES ('Shoes incentivize');
END IF;
END;
$$
LANGUAGE plpgsql;]
	at liquibase.changelog.ChangeSet.execute(ChangeSet.java:670)
	at liquibase.changelog.visitor.UpdateVisitor.visit(UpdateVisitor.java:49)
	at liquibase.changelog.ChangeLogIterator$2.lambda$null$0(ChangeLogIterator.java:111)
	at liquibase.Scope.lambda$child$0(Scope.java:160)
	at liquibase.Scope.child(Scope.java:169)
	at liquibase.Scope.child(Scope.java:159)
	at liquibase.Scope.child(Scope.java:138)
	at liquibase.changelog.ChangeLogIterator$2.lambda$run$1(ChangeLogIterator.java:110)
	at liquibase.Scope.lambda$child$0(Scope.java:160)
	at liquibase.Scope.child(Scope.java:169)
	at liquibase.Scope.child(Scope.java:159)
	at liquibase.Scope.child(Scope.java:138)
	at liquibase.Scope.child(Scope.java:222)
	at liquibase.changelog.ChangeLogIterator$2.run(ChangeLogIterator.java:94)
	at liquibase.Scope.lambda$child$0(Scope.java:160)
	at liquibase.Scope.child(Scope.java:169)
	at liquibase.Scope.child(Scope.java:159)
	at liquibase.Scope.child(Scope.java:138)
	at liquibase.Scope.child(Scope.java:222)
	at liquibase.Scope.child(Scope.java:226)
	at liquibase.changelog.ChangeLogIterator.run(ChangeLogIterator.java:66)
	... 23 common frames omitted
Caused by: liquibase.exception.DatabaseException: ERROR: null value in column "id" of relation "beer" violates not-null constraint
  Détail : Failing row contains (null, null, Shoes incentivize).
  Où : SQL statement "INSERT INTO public.beer (description) VALUES ('Shoes incentivize')"
PL/pgSQL function inline_code_block line 5 at SQL statement [Failed SQL: (0) DO
$$
BEGIN
UPDATE public.beer SET description = 'Shoes incentivize' WHERE id is NULL;
IF not found THEN
INSERT INTO public.beer (description) VALUES ('Shoes incentivize');
END IF;
END;
$$
LANGUAGE plpgsql;]
	at liquibase.executor.jvm.JdbcExecutor$ExecuteStatementCallback.doInStatement(JdbcExecutor.java:398)
	at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:82)
	at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:154)
	at liquibase.database.AbstractJdbcDatabase.execute(AbstractJdbcDatabase.java:1272)
	at liquibase.database.AbstractJdbcDatabase.executeStatements(AbstractJdbcDatabase.java:1254)
	at liquibase.changelog.ChangeSet.execute(ChangeSet.java:635)
	... 43 common frames omitted
Caused by: org.postgresql.util.PSQLException: ERROR: null value in column "id" of relation "beer" violates not-null constraint
  Détail : Failing row contains (null, null, Shoes incentivize).
  Où : SQL statement "INSERT INTO public.beer (description) VALUES ('Shoes incentivize')"
PL/pgSQL function inline_code_block line 5 at SQL statement
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2553)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2285)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:323)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:473)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:393)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:322)
	at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:308)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:284)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:279)
	at com.zaxxer.hikari.pool.ProxyStatement.execute(ProxyStatement.java:95)
	at com.zaxxer.hikari.pool.HikariProxyStatement.execute(HikariProxyStatement.java)
	at liquibase.executor.jvm.JdbcExecutor$ExecuteStatementCallback.doInStatement(JdbcExecutor.java:394)
	... 48 common frames omitted

```

##### **Reproduce the error**

- generate a project with PostgreSQL, using this command: `jhipster --incremental-changelog`
- create an entity with JDL
- start the application to apply the change in database with liquibase
- stop the application
- add a new field in entity
- regenerate the entity with JDL
- start the application

Here an extract of `20210122162347_updated_entity_migrate_Beer.xml` :

```xml
        <loadUpdateData
                  file="config/liquibase/fake-data/20210122162347_entity_beer.csv"
                  separator=";"
                  onlyUpdate="true"
                  primaryKey="id"
                  tableName="beer">
            <column name="id" type="numeric"/>
            <column name="description" type="string"/>
            <!-- jhipster-needle-liquibase-add-loadcolumn - JHipster (and/or extensions) can add load columns here -->
        </loadUpdateData>
```

The generated CSV: `20210122162347_entity_beer.csv`

```csv
description
Shoes incentivize
aggregate
Samoa Central
Club methodology
Chicken
violet
IB Bike
Metal
Avon AGP
navigating Outdoors exuding
```

Here my 1st JDL:

```
entity Beer {
  name String
}
```

Here the 2nd JDL:

```
entity Beer {
  name String
  description String
}
```

##### **JHipster Version(s)**

```
burger@0.0.0 /home/pgrimaud/tmp/07-burger
└── generator-jhipster@7.0.0-beta.1 

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "blueprints": [],
    "otherModules": [],
    "applicationType": "monolith",
    "baseName": "burger",
    "jhipsterVersion": "7.0.0-beta.1",
    "skipClient": false,
    "skipServer": false,
    "skipUserManagement": false,
    "skipCheckLengthOfIdentifier": false,
    "skipFakeData": false,
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "testFrameworks": [],
    "pages": [],
    "creationTimestamp": 1611332114127,
    "promptValues": {
      "packageName": "io.github.pascalgrimaud",
      "nativeLanguage": "en"
    },
    "serviceDiscoveryType": false,
    "reactive": false,
    "authenticationType": "jwt",
    "packageName": "io.github.pascalgrimaud",
    "serverPort": "8080",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "databaseType": "sql",
    "devDatabaseType": "postgresql",
    "prodDatabaseType": "postgresql",
    "buildTool": "maven",
    "serverSideOptions": [],
    "websocket": false,
    "searchEngine": false,
    "messageBroker": false,
    "enableSwaggerCodegen": false,
    "clientFramework": "vue",
    "withAdminUi": true,
    "clientTheme": "none",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "packageFolder": "io/github/pascalgrimaud",
    "jwtSecretKey": "YourJWTSecretKeyWasReplacedByThisMeaninglessTextByTheJHipsterInfoCommandForObviousSecurityReasons",
    "clientPackageManager": "npm",
    "clientThemeVariant": "",
    "languages": ["en"],
    "entities": ["Beer"],
    "lastLiquibaseTimestamp": 1611332627000,
    "incrementalChangelog": true
  }
}

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity Beer {
  name String
  description String
}

</pre>
</details>

##### **Environment and Tools**

openjdk version "11.0.9.1" 2020-11-04
OpenJDK Runtime Environment (build 11.0.9.1+1-Ubuntu-0ubuntu1.18.04)
OpenJDK 64-Bit Server VM (build 11.0.9.1+1-Ubuntu-0ubuntu1.18.04, mixed mode, sharing)

git version 2.30.0

node: v14.15.4

npm: 6.14.10

yeoman: 3.1.1

Docker version 19.03.8, build afacb8b7f0

docker-compose version 1.27.3, build 4092ae5d

INFO! Congratulations, JHipster execution is complete!

**Comment by pascalgrimaud** [comment]
I tried to work on this, but didn't manage to find a solution for now.
That's why I opened the ticket and I think you'll know exactly how to fix it @mshima :)

**Comment by mshima** [comment]
I will take a look.
