### ISSUE TITLE
Migrate Gateway to Reactive

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/generator-jhipster#13855]
##### **Overview of the issue**

Since Spring Boot 2.4, the communication between gateway and microservices is broken.

It has been detected by JDLMS builds here:
- https://github.com/hipster-labs/jhipster-daily-builds/actions?query=workflow%3A%22JDLMS+Hazelcast+MySQL%22

![jdlms_broken_sb24](https://user-images.githubusercontent.com/9156882/107064059-61b9d700-67db-11eb-8ea0-d4196aedc82a.png)

##### **Motivation for or Use Case**

Some stacktrace:

```
store_1              | 2021-02-05 16:52:00.515  WARN 1 --- [  XNIO-1 task-3] o.s.c.n.z.filters.post.SendErrorFilter   : Error during filtering
store_1              | 
store_1              | com.netflix.zuul.exception.ZuulException: Forwarding error
store_1              | 	at org.springframework.cloud.netflix.zuul.filters.route.RibbonRoutingFilter.handleException(RibbonRoutingFilter.java:198)
store_1              | 	at org.springframework.cloud.netflix.zuul.filters.route.RibbonRoutingFilter.forward(RibbonRoutingFilter.java:173)
store_1              | 	at org.springframework.cloud.netflix.zuul.filters.route.RibbonRoutingFilter.run(RibbonRoutingFilter.java:119)
store_1              | 	at com.netflix.zuul.ZuulFilter.runFilter(ZuulFilter.java:117)
store_1              | 	at com.netflix.zuul.FilterProcessor.processZuulFilter(FilterProcessor.java:193)
store_1              | 	at com.netflix.zuul.FilterProcessor.runFilters(FilterProcessor.java:157)
store_1              | 	at com.netflix.zuul.FilterProcessor.route(FilterProcessor.java:118)
store_1              | 	at com.netflix.zuul.ZuulRunner.route(ZuulRunner.java:96)
store_1              | 	at com.netflix.zuul.http.ZuulServlet.route(ZuulServlet.java:116)
store_1              | 	at com.netflix.zuul.http.ZuulServlet.service(ZuulServlet.java:81)
store_1              | 	at org.springframework.web.servlet.mvc.ServletWrappingController.handleRequestInternal(ServletWrappingController.java:166)
store_1              | 	at org.springframework.cloud.netflix.zuul.web.ZuulController.handleRequest(ZuulController.java:45)
store_1              | 	at org.springframework.web.servlet.mvc.SimpleControllerHandlerAdapter.handle(SimpleControllerHandlerAdapter.java:52)
store_1              | 	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1060)
store_1              | 	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:962)
store_1              | 	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
store_1              | 	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898)
store_1              | 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:497)
store_1              | 	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
store_1              | 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:584)
store_1              | 	at io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:74)
store_1              | 	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:129)
store_1              | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:113)
store_1              | 	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
store_1              | 	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
store_1              | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:327)
store_1              | 	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:115)
store_1              | 	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:81)
store_1              | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
store_1              | 	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:119)
store_1              | 	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:113)
store_1              | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
store_1              | 	at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:126)
store_1              | 	at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:81)
store_1              | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
store_1              | 	at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:105)
store_1              | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
store_1              | 	at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:149)
store_1              | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
store_1              | 	at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:63)
store_1              | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
store_1              | 	at com.jhipster.demo.store.security.jwt.JWTFilter.doFilter(JWTFilter.java:37)
store_1              | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
store_1              | 	at org.springframework.web.filter.CorsFilter.doFilterInternal(CorsFilter.java:91)
store_1              | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
store_1              | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
store_1              | 	at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:103)
store_1              | 	at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:89)
store_1              | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
store_1              | 	at org.springframework.security.web.header.HeaderWriterFilter.doHeadersAfter(HeaderWriterFilter.java:90)
store_1              | 	at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:75)
store_1              | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
store_1              | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
store_1              | 	at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:110)
store_1              | 	at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:80)
store_1              | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
store_1              | 	at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:55)
store_1              | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
store_1              | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
store_1              | 	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:211)
store_1              | 	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:183)
store_1              | 	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:358)
store_1              | 	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:271)
store_1              | 	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
store_1              | 	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
store_1              | 	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
store_1              | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
store_1              | 	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
store_1              | 	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
store_1              | 	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
store_1              | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
store_1              | 	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
store_1              | 	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
store_1              | 	at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:93)
store_1              | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
store_1              | 	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
store_1              | 	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
store_1              | 	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
store_1              | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
store_1              | 	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
store_1              | 	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
store_1              | 	at io.undertow.servlet.handlers.FilterHandler.handleRequest(FilterHandler.java:84)
store_1              | 	at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62)
store_1              | 	at io.undertow.servlet.handlers.ServletChain$1.handleRequest(ServletChain.java:68)
store_1              | 	at io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36)
store_1              | 	at io.undertow.servlet.handlers.RedirectDirHandler.handleRequest(RedirectDirHandler.java:68)
store_1              | 	at io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:117)
store_1              | 	at io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57)
store_1              | 	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
store_1              | 	at io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46)
store_1              | 	at io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:64)
store_1              | 	at io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:60)
store_1              | 	at io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:77)
store_1              | 	at io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43)
store_1              | 	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
store_1              | 	at io.undertow.servlet.handlers.SendErrorPageHandler.handleRequest(SendErrorPageHandler.java:52)
store_1              | 	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
store_1              | 	at io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:269)
store_1              | 	at io.undertow.servlet.handlers.ServletInitialHandler.access$100(ServletInitialHandler.java:78)
store_1              | 	at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:133)
store_1              | 	at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:130)
store_1              | 	at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:48)
store_1              | 	at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
store_1              | 	at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:249)
store_1              | 	at io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:78)
store_1              | 	at io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:99)
store_1              | 	at io.undertow.server.Connectors.executeRootHandler(Connectors.java:387)
store_1              | 	at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:841)
store_1              | 	at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
store_1              | 	at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2019)
store_1              | 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1558)
store_1              | 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1449)
store_1              | 	at java.base/java.lang.Thread.run(Unknown Source)
store_1              | Caused by: com.netflix.client.ClientException: Load balancer does not have available server for client: crm
store_1              | 	at com.netflix.loadbalancer.LoadBalancerContext.getServerFromLoadBalancer(LoadBalancerContext.java:483)
store_1              | 	at com.netflix.loadbalancer.reactive.LoadBalancerCommand$1.call(LoadBalancerCommand.java:184)
store_1              | 	at com.netflix.loadbalancer.reactive.LoadBalancerCommand$1.call(LoadBalancerCommand.java:180)
store_1              | 	at rx.Observable.unsafeSubscribe(Observable.java:10327)
store_1              | 	at rx.internal.operators.OnSubscribeConcatMap.call(OnSubscribeConcatMap.java:94)
store_1              | 	at rx.internal.operators.OnSubscribeConcatMap.call(OnSubscribeConcatMap.java:42)
store_1              | 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
store_1              | 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
store_1              | 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
store_1              | 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
store_1              | 	at rx.Observable.subscribe(Observable.java:10423)
store_1              | 	at rx.Observable.subscribe(Observable.java:10390)
store_1              | 	at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:443)
store_1              | 	at rx.observables.BlockingObservable.single(BlockingObservable.java:340)
store_1              | 	at com.netflix.client.AbstractLoadBalancerAwareClient.executeWithLoadBalancer(AbstractLoadBalancerAwareClient.java:112)
store_1              | 	at org.springframework.cloud.netflix.zuul.filters.route.support.AbstractRibbonCommand.run(AbstractRibbonCommand.java:221)
store_1              | 	at org.springframework.cloud.netflix.zuul.filters.route.support.AbstractRibbonCommand.run(AbstractRibbonCommand.java:55)
store_1              | 	at com.netflix.hystrix.HystrixCommand$2.call(HystrixCommand.java:302)
store_1              | 	at com.netflix.hystrix.HystrixCommand$2.call(HystrixCommand.java:298)
store_1              | 	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:46)
store_1              | 	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:35)
store_1              | 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
store_1              | 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
store_1              | 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
store_1              | 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
store_1              | 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
store_1              | 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
store_1              | 	at rx.Observable.unsafeSubscribe(Observable.java:10327)
store_1              | 	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:51)
store_1              | 	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:35)
store_1              | 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
store_1              | 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
store_1              | 	at rx.Observable.unsafeSubscribe(Observable.java:10327)
store_1              | 	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:41)
store_1              | 	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:30)
store_1              | 	at rx.Observable.unsafeSubscribe(Observable.java:10327)
store_1              | 	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:41)
store_1              | 	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:30)
store_1              | 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
store_1              | 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
store_1              | 	at rx.Observable.unsafeSubscribe(Observable.java:10327)
store_1              | 	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:41)
store_1              | 	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:30)
store_1              | 	at rx.Observable.unsafeSubscribe(Observable.java:10327)
store_1              | 	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:41)
store_1              | 	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:30)
store_1              | 	at rx.Observable.unsafeSubscribe(Observable.java:10327)
store_1              | 	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:41)
store_1              | 	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:30)
store_1              | 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
store_1              | 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
store_1              | 	at rx.Observable.unsafeSubscribe(Observable.java:10327)
store_1              | 	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:51)
store_1              | 	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:35)
store_1              | 	at rx.Observable.unsafeSubscribe(Observable.java:10327)
store_1              | 	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
store_1              | 	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
store_1              | 	at rx.Observable.unsafeSubscribe(Observable.java:10327)
store_1              | 	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:41)
store_1              | 	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:30)
store_1              | 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
store_1              | 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
store_1              | 	at rx.Observable.unsafeSubscribe(Observable.java:10327)
store_1              | 	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:41)
store_1              | 	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:30)
store_1              | 	at rx.Observable.unsafeSubscribe(Observable.java:10327)
store_1              | 	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:51)
store_1              | 	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:35)
store_1              | 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
store_1              | 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
store_1              | 	at rx.Observable.subscribe(Observable.java:10423)
store_1              | 	at rx.Observable.subscribe(Observable.java:10390)
store_1              | 	at rx.internal.operators.BlockingOperatorToFuture.toFuture(BlockingOperatorToFuture.java:51)
store_1              | 	at rx.observables.BlockingObservable.toFuture(BlockingObservable.java:410)
store_1              | 	at com.netflix.hystrix.HystrixCommand.queue(HystrixCommand.java:378)
store_1              | 	at com.netflix.hystrix.HystrixCommand.execute(HystrixCommand.java:344)
store_1              | 	at org.springframework.cloud.netflix.zuul.filters.route.RibbonRoutingFilter.forward(RibbonRoutingFilter.java:167)
store_1              | 	... 111 common frames omitted
store_1              | 
```

![registry](https://user-images.githubusercontent.com/9156882/107063784-10a9e300-67db-11eb-87e7-047190669443.png)

![gateway_routes](https://user-images.githubusercontent.com/9156882/107063798-130c3d00-67db-11eb-8b3a-d6c55dfa39dd.png)

![jdlms_broken](https://user-images.githubusercontent.com/9156882/107062416-92007600-67d9-11eb-82be-b40e08ef5347.png)

![invoices_500](https://user-images.githubusercontent.com/9156882/107063867-2b7c5780-67db-11eb-9ac3-a2a06be7842d.png)

##### **Reproduce the error**

Use this JDL:

```
application {
 config {
   baseName store,
   applicationType gateway,
   packageName com.jhipster.demo.store,
   serviceDiscoveryType eureka,
   authenticationType jwt,
   prodDatabaseType mysql,
   cacheProvider hazelcast,
   buildTool gradle,
   clientFramework angularX,
   enableSwaggerCodegen true,
   testFrameworks [cypress]
 }
 entities *
}

application {
 config {
   baseName crm,
   applicationType microservice,
   packageName com.jhipster.demo.crm,
   serviceDiscoveryType eureka,
   authenticationType jwt,
   prodDatabaseType postgresql,
   buildTool maven,
   searchEngine elasticsearch,
   serverPort 8081,
   skipUserManagement true
 }
 entities *
}

entity Product {
   name String required
   description String
   price BigDecimal required min(0)
   size Size required
   image ImageBlob
}
enum Size {
   S, M, L, XL, XXL
}
entity Customer {
   firstName String required
   lastName String required
   gender Gender required
   email String required pattern(/[a-z0-9._+-]{1,20}@[a-z0-9]{3,15}\.[a-z]{2,4}/)
   phone String required
   addressLine1 String required
   addressLine2 String
   city String required
   country String required
}
enum Gender {
   MALE, FEMALE, OTHER
}
entity ProductOrder {
   placedDate Instant required
   status OrderStatus required
   code String required
   invoiceId String
}
enum OrderStatus {
   COMPLETED, PENDING, CANCELLED
}
entity OrderItem {
   quantity Integer required min(0)
   totalPrice BigDecimal required min(0)
   status OrderItemStatus required
}
enum OrderItemStatus {
   AVAILABLE, OUT_OF_STOCK, BACK_ORDER
}
relationship ManyToOne {
OrderItem{product(name) required} to Product
}
relationship OneToMany {
  Customer{order} to ProductOrder{customer(email) required},
  ProductOrder{orderItem} to OrderItem{order(code) required}
}

service Product, Customer, ProductOrder, OrderItem with serviceClass
paginate Product, Customer, ProductOrder, OrderItem with pagination

/* Entities for Invoice microservice */
entity Invoice {
   code String required
   date Instant required
   details String
   status InvoiceStatus required
   paymentMethod PaymentMethod required
   paymentDate Instant required
   paymentAmount BigDecimal required
}
enum InvoiceStatus {
   PAID, ISSUED, CANCELLED
}
entity Shipment {
   trackingCode String
   date Instant required
   details String
}
enum PaymentMethod {
   CREDIT_CARD, CASH_ON_DELIVERY, PAYPAL
}
relationship OneToMany {
   Invoice{shipment} to Shipment{invoice(code) required}
}
service Invoice, Shipment with serviceClass
paginate Invoice, Shipment with pagination
microservice Customer, Product, ProductOrder, OrderItem, Invoice, Shipment with crm

// will be created under 'docker-compose' folder
deployment {
   deploymentType docker-compose,
   appsFolders [store, crm],
   dockerRepositoryName "hipsterslabs"
   monitoring no,
   serviceDiscoveryType eureka
}

// will be created under 'kubernetes' folder
deployment {
   deploymentType kubernetes,
   appsFolders [store, crm]
   dockerRepositoryName "hipsterslabs",
   gatewayType zuul,
   monitoring no,
   serviceDiscoveryType eureka
   kubernetesNamespace jhipster,
   kubernetesServiceType LoadBalancer,
   istio false
}

```
- jhipster jdl microservice-demo.jdl
- cd crm && ./mvnw -Pprod -DskipTests verify jib:dockerBuild
- cd store && ./gradlew bootJar -Pprod jibDockerBuild -x test
- cd docker-compose && docker-compose up -d

##### **JHipster Version(s)**

Current master at https://github.com/jhipster/generator-jhipster/commit/c3b6a0e2084fa7e5a213ce6c639cd98d1e7b4d05

##### **Environment and Tools**

openjdk version "11.0.9.1" 2020-11-04
OpenJDK Runtime Environment (build 11.0.9.1+1-Ubuntu-0ubuntu1.18.04)
OpenJDK 64-Bit Server VM (build 11.0.9.1+1-Ubuntu-0ubuntu1.18.04, mixed mode, sharing)

git version 2.30.0

node: v14.15.4

npm: 6.14.10

yeoman: 3.1.1

Docker version 19.03.8, build afacb8b7f0

docker-compose version 1.27.3, build 4092ae5d

- [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by pascalgrimaud** [comment]
I'm adding a bounty on this, as it must be fixed otherwise, a new release beta.2 can't be done :-(

cc @mraible

**Comment by mraible** [comment]
I can take a look in a few hours.

**Comment by mraible** [comment]
I'm able to reproduce the problem, but not sure how to fix it. If you look at `application.yml` in IntelliJ, it seems to indicate that the first couple of properties are invalid.

<img width="442" alt="Screen Shot 2021-02-05 at 10 39 45 PM" src="https://user-images.githubusercontent.com/17892/107110192-1d423180-6803-11eb-926b-fea122af3669.png">

If you look at [Spring's Guides](https://spring.io/guides/gs/client-side-load-balancing/), you'll see that using Ribbon is deprecated.

> Spring Cloud Netflix Ribbon is now deprecated. To see a demo of the currently recommended client-side-load-balancing approach, please check [this guide](https://spring.io/guides/gs/spring-cloud-loadbalancer/).

**Comment by pascalgrimaud** [comment]
Yes, I spent a couple of hours the last night and it seems related to load balancing with ribbon.
I tried different config but didn't manage to find the good one

**Comment by pascalgrimaud** [comment]
I tried the same config with Reactive :
- communication between microservices works
- swagger ui is broken

So I wonder if our microservices stack can work without Spring Cloud Gateway + Spring Cloud LoadBalancer ?

@juliensadaoui @PierreBesson @nassimerrahoui

**Comment by mshima** [comment]
This could be useful https://github.com/spring-cloud-samples/spring-cloud-intro-demo.

**Comment by pascalgrimaud** [comment]
Thanks @mshima, I saw similar code too, but it relies on Spring Cloud Gateway:
https://github.com/spring-cloud-samples/spring-cloud-intro-demo/blob/master/gateway-proxy/pom.xml#L26

And we use Spring Cloud Gateway only for Reactive:
https://github.com/jhipster/generator-jhipster/blob/main/generators/server/templates/pom.xml.ejs#L787

For now, it's my conclusion : when we select Gateway, we must force Reactive, which is still in Beta

**Comment by mshima** [comment]
@pascalgrimaud yep, the spring cloud core is built on reactive.
```
Spring Cloud Gateway features:
- Built on Spring Framework 5, Project Reactor and Spring Boot 2.0
```

Ribbon support seems to be removed already.
https://stackoverflow.com/questions/65469735/versions-spring-boot-spring-cloud-ribbon-not-working

Probably jhipster gateway imperative and jhipster-registry will have to migrate away from ribbon and adopt spring-cloud reactive implementation.

**Comment by mraible** [comment]
Spring Cloud no longer manages Netflix dependencies, but we still have them in our dependencies. 

https://github.com/jhipster/jhipster-bom/blob/main/jhipster-dependencies/pom.xml#L620

I still think we should be able to use Ribbon with our non-reactive stack.

**Comment by pascalgrimaud** [comment]
> I still think we should be able to use Ribbon with our non-reactive stack.

I hope too, otherwise, we'll have to force reactive for Gateway

**Comment by mraible** [comment]
I don't see a problem with using Spring Cloud Gateway for both reactive and non-reactive, but I'll continue to try and fix this.

**Comment by jdubois** [comment]
Yes, we should migrate to Spring Cloud Gateway and Spring Cloud LoadBalancer anyway.
Zulu and Ribbon aren’t maintained, so they will only be trouble...

**Comment by mraible** [comment]
I [asked about this on Twitter](https://twitter.com/mraible/status/1358447993842667521) this morning and got confirmation from a couple of the main Spring Cloud contributors. Using Spring Cloud Gateway is the way forward.

There is a [request for a Spring MVC version of Spring Cloud Gateway](https://github.com/spring-cloud/spring-cloud-gateway/issues/36) we could revisit in the future if there's any demand for it.

I propose we remove the `reactive` prompt when creating a gateway and make it reactive-only to get past this issue.

**Comment by pascalgrimaud** [comment]
Ok let's do it
I think we donner have other choice

**Comment by mraible** [comment]
I can start this tomorrow. Today is an unofficial holiday in the US (Super Bowl Sunday). 🍻

**Comment by rkhalyleh** [comment]
I encountered the same error when started use spring cloud 2020.0.1, and spring boot 2.4. Based on official spring cloud docs, they 
removed some modules from spring-cloud-netflix, such as zuul and ribbon ... . So I started use Spring Cloud Gateway, and it worked well so far.

**Comment by pascalgrimaud** [comment]
@mraible : it's ok, I can take it as it's mainly for prompts, JDL and configuration
About broken Swagger with Gateway+Reactive, I think we can take the similar code from JHCC -> cc @nassimerrahoui

**Comment by nassimerrahoui** [comment]
@mraible @pascalgrimaud : I can add the fix for Swagger Gateway+Reactive after the first fix, the idea is similar than before with SwaggerBasePathRewritingFilter but instead of using Zuul filter, we use a Spring Cloud Gateway filter like here : https://github.com/jhipster/jhipster-control-center/blob/main/src/main/java/tech/jhipster/controlcenter/config/apidoc/ModifyServersOpenApiFilter.java

**Comment by pascalgrimaud** [comment]
@mraible : there are more work than expected, but the work is in progress

I'd like to know if it's normal when we force reactive for gateway, there is **no cache provider** ?
Because, there are some question about cache, but the result is:

```yaml
"cacheProvider": "no"
```

**Comment by jdubois** [comment]
@pascalgrimaud I believe it's much more complicated to make the cache provider work in a reactive environment

**Comment by mraible** [comment]
@pascalgrimaud I'm not sure about that as I've never done any work on JHipster related to caching. I imagine if there's a database, there will be a cache, but I'm not sure.

I also started look into it last night, but only made it as far as adding the following in `generators/server/index.js`:

```js
// Force reactive for gateway apps
if (config.applicationType === 'gateway') {
  config.reactive = true;
}

if (config.authenticationType === 'oauth2') {
  config.skipUserManagement = true;
}
```

Let me know if there's anything I can do to help.

**Comment by pascalgrimaud** [comment]
Cache support for Reactive application is not done yet, from what I saw in configuration, so I'll remove the question from prompts, thanks for the input @jdubois 

@mraible, what's already done:
- remove prompt about Reactive with Gateway
- force Reactive in JDL, when choosing Gateway
- fix npm test

Still in WIP:
- clean old files related to old Gateway
- remove deprecated dependencies in jhipster-bom
- update all samples in CI
- update all samples in daily builds
- update JDL samples
- update documentation

I'm fine at the moment, just need a couple of days

**Comment by mraible** [comment]
Sounds good. Just so you're aware, I'm going on vacation this Saturday and will be offline for two weeks. I'll be back in action on March 1.

**Comment by pascalgrimaud** [comment]
I'm reopening this, as there are still some work before finishing it

**Comment by pascalgrimaud** [comment]
All work related to force Reactive Gateway is done. So this ticket can be closed

**Comment by pascalgrimaud** [comment]
Bug bounty claimed at https://opencollective.com/generator-jhipster/expenses/34812
