### ISSUE TITLE
GAE deployment fails due to spring-boot-thin-launcher missing

### ISSUE THREAD

**Issue by JayJayBinks** [jhipster/generator-jhipster#13886]
##### **Overview of the issue**

Trying to deploy the application to Google App Engine with
`mvnw package appengine:deploy -DskipTests -Pgae,prod,prod-gae`

Getting Maven error:
```
[INFO] --- spring-boot-thin-maven-plugin:1.0.23.RELEASE:resolve (resolve) @ klara ---
[INFO] Deploying: C:\Users\profi\IdeaProjects\bvn\target\klara-0.0.1-SNAPSHOT.jar
[INFO] Copying: klara-0.0.1-SNAPSHOT.jar to C:\Users\profi\IdeaProjects\bvn\target\appengine-staging
Exception in thread "main" java.lang.IllegalStateException: Cannot locate launcher: ./repository/org/springframework/boot/experimental/spring-boot-thin-launcher/1.0.23.RELEASE/spring-boot-thin-launcher-1.0.23.RELEASE-exec.jar
        at org.springframework.boot.loader.wrapper.ThinJarWrapper.launch(ThinJarWrapper.java:132)
        at org.springframework.boot.loader.wrapper.ThinJarWrapper.main(ThinJarWrapper.java:107)

```

##### **JHipster Version(s)**

```
klara@0.0.1-SNAPSHOT C:\Users\profi\IdeaProjects\bvn
`-- generator-jhipster@7.0.0-beta.1

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "blueprints": [],
    "otherModules": [],
    "applicationType": "monolith",
    "baseName": "klara",
    "jhipsterVersion": "7.0.0-beta.1",
    "skipClient": false,
    "skipServer": false,
    "skipUserManagement": true,
    "skipCheckLengthOfIdentifier": false,
    "skipFakeData": false,
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "testFrameworks": [],
    "pages": [],
    "creationTimestamp": 1611430480855,
    "promptValues": {
      "packageName": "de.bvn.klara",
      "nativeLanguage": "de"
    },
    "serviceDiscoveryType": false,
    "reactive": false,
    "authenticationType": "oauth2",
    "packageName": "de.bvn.klara",
    "serverPort": "8080",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "databaseType": "sql",
    "devDatabaseType": "postgresql",
    "prodDatabaseType": "postgresql",
    "buildTool": "maven",
    "serverSideOptions": [],
    "websocket": false,
    "searchEngine": false,
    "messageBroker": false,
    "enableSwaggerCodegen": false,
    "clientFramework": "react",
    "withAdminUi": true,
    "clientTheme": "cerulean",
    "clientThemeVariant": "primary",
    "enableTranslation": true,
    "nativeLanguage": "de",
    "packageFolder": "de/bvn/klara",
    "clientPackageManager": "npm",
    "languages": ["de"],
    "entities": ["Wohnung", "ApplicationUser", "Bild", "KlaraNachricht"],
    "lastLiquibaseTimestamp": 1611430660000,
    "appFolder": "bvn",
    "appsFolders": ["bvn"],
    "directoryPath": "../",
    "monitoring": "no",
    "jwtSecretKey": "YourJWTSecretKeyWasReplacedByThisMeaninglessTextByTheJHipsterInfoCommandForObviousSecurityReasons",
    "gcpProjectId": "playground-s-11-c880bccf",
    "gcpCloudSqlInstanceName": "playground-s-11-c880bccf:europe-west2:klara",
    "gcpCloudSqlUserName": "root",
    "gcpCloudSqlDatabaseName": "klara",
    "gaeServiceName": "default",
    "gaeLocation": "europe-west3",
    "gaeInstanceClass": "F4",
    "gaeScalingType": "automatic",
    "gaeMinInstances": "0",
    "gaeMaxInstances": "2",
    "gaeCloudSQLInstanceNeeded": "Y"
  }
}
</pre>
</details>

##### **Environment and Tools**

java version "11.0.3" 2019-04-16 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.3+12-LTS)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.3+12-LTS, mixed mode)

git version 2.18.0.windows.1

node: v14.15.1

npm: 6.14.9

Docker version 20.10.2, build 2291f61

docker-compose version 1.27.4, build 40524192

INFO! Congratulations, JHipster execution is complete!

##### **Browsers and Operating System**

Win 10

- [ x] Checking this box is mandatory (this is just to show you read everything)

**Comment by JayJayBinks** [comment]
FYI:
When i copy the `spring-boot-thin-launcher-1.0.23.RELEASE-exec.jar` from my local maven to `./repository/org/springframework/boot/experimental/spring-boot-thin-launcher/1.0.23.RELEASE/spring-boot-thin-launcher-1.0.23.RELEASE-exec.jar` the build is working fine

**Comment by JayJayBinks** [comment]
Never mind, the application is behind a proxy and so the jar cancould not be downloaded
