### ISSUE TITLE
useSass isn't recognized as an application option in the 7.0.0-beta.1

### ISSUE THREAD

**Issue by vw98075** [jhipster/generator-jhipster#13947]
##### **Reproduce the error**
With a jdl file https://github.com/jhipster/jdl-samples/blob/main/blog.jh as app.jdl

Run 
```
jhipster import-jdl app.jdl
```
You will get the following error:
```
INFO! Executing import-jdl app.jdl
error: Syntax error message:
	MismatchedTokenException: Found an invalid token 'useSass', at line: 10 and column: 5.
	Please make sure your JDL content does not use invalid characters, keywords or options.
Error during import-jdl: Error: MismatchedTokenException: Found an invalid token 'useSass', at line: 10 and column: 5.
	Please make sure your JDL content does not use invalid characters, keywords or options.
Error: MismatchedTokenException: Found an invalid token 'useSass', at line: 10 and column: 5.
	Please make sure your JDL content does not use invalid characters, keywords or options.
    at throwErrorAboutInvalidToken (/home/oem/.nvm/versions/node/v15.5.0/lib/node_modules/generator-jhipster/jdl/parsing/api.js:85:11)
    at throwParserError (/home/oem/.nvm/versions/node/v15.5.0/lib/node_modules/generator-jhipster/jdl/parsing/api.js:72:9)
    at getCst (/home/oem/.nvm/versions/node/v15.5.0/lib/node_modules/generator-jhipster/jdl/parsing/api.js:57:9)
    at Object.parse (/home/oem/.nvm/versions/node/v15.5.0/lib/node_modules/generator-jhipster/jdl/parsing/api.js:40:17)
    at callApiMethod (/home/oem/.nvm/versions/node/v15.5.0/lib/node_modules/generator-jhipster/jdl/readers/jdl-reader.js:98:34)
    at parse (/home/oem/.nvm/versions/node/v15.5.0/lib/node_modules/generator-jhipster/jdl/readers/jdl-reader.js:84:27)
    at Object.parseFromFiles (/home/oem/.nvm/versions/node/v15.5.0/lib/node_modules/generator-jhipster/jdl/readers/jdl-reader.js:43:12)
    at parseFiles (/home/oem/.nvm/versions/node/v15.5.0/lib/node_modules/generator-jhipster/jdl/jdl-importer.js:127:22)
    at createImporterFromFiles (/home/oem/.nvm/versions/node/v15.5.0/lib/node_modules/generator-jhipster/jdl/jdl-importer.js:60:21)
    at JDLProcessor.importJDL (/home/oem/.nvm/versions/node/v15.5.0/lib/node_modules/generator-jhipster/cli/import-jdl.js:354:24)
ERROR! Error during import-jdl: MismatchedTokenException: Found an invalid token 'useSass', at line: 10 and column: 5.
	Please make sure your JDL content does not use invalid characters, keywords or options.
Error: Error during import-jdl: MismatchedTokenException: Found an invalid token 'useSass', at line: 10 and column: 5.
	Please make sure your JDL content does not use invalid characters, keywords or options.
    at module.exports (/home/oem/.nvm/versions/node/v15.5.0/lib/node_modules/generator-jhipster/cli/import-jdl.js:480:31)
    at /home/oem/.nvm/versions/node/v15.5.0/lib/node_modules/generator-jhipster/cli/jdl.js:61:51
    at processTicksAndRejections (node:internal/process/task_queues:93:5)
    at async Promise.all (index 0)
```

##### **JHipster Version(s)**
 7.0.0-beta.1

##### **Browsers and Operating System**

- [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by pascalgrimaud** [comment]
useSass is deprecated since long time, so it needed to be deleted
