### ISSUE TITLE
Unique index or primary key violation in H2

### ISSUE THREAD

**Issue by vw98075** [jhipster/generator-jhipster#13949]
##### **Overview of the issue**

running Deepu's sample https://dev.to/adyen/building-an-e-commerce-application-using-java-react-2iln with two replacements: PostgreSql instead of Mysql, Vue instead of React.

```
2021-02-13 20:36:46.262  WARN 346 --- [   store-task-1] t.j.c.liquibase.AsyncSpringLiquibase     : Starting Liquibase asynchronously, your database might not be ready at startup!
2021-02-13 20:36:50.915 ERROR 346 --- [   store-task-1] t.j.c.liquibase.AsyncSpringLiquibase     : Liquibase could not start correctly, your database is NOT ready: liquibase.exception.MigrationFailedException: Migration failed for change set config/liquibase/changelog/20210214043542_added_entity_CustomerDetails.xml::20210214043542-1-data::jhipster:
     Reason: liquibase.exception.DatabaseException: org.h2.jdbc.JdbcBatchUpdateException: Unique index or primary key violation: "PUBLIC.UX_CUSTOMER_DETAILS__USER_ID_INDEX_E ON PUBLIC.CUSTOMER_DETAILS(USER_ID) VALUES 1"; SQL statement:
INSERT INTO PUBLIC.customer_details(id, gender, phone, address_line_1, address_line_2, city, country, user_id) VALUES(?, ?, ?, ?, ?, ?, ?, ?) [23505-200]

liquibase.exception.LiquibaseException: liquibase.exception.MigrationFailedException: Migration failed for change set config/liquibase/changelog/20210214043542_added_entity_CustomerDetails.xml::20210214043542-1-data::jhipster:
     Reason: liquibase.exception.DatabaseException: org.h2.jdbc.JdbcBatchUpdateException: Unique index or primary key violation: "PUBLIC.UX_CUSTOMER_DETAILS__USER_ID_INDEX_E ON PUBLIC.CUSTOMER_DETAILS(USER_ID) VALUES 1"; SQL statement:
INSERT INTO PUBLIC.customer_details(id, gender, phone, address_line_1, address_line_2, city, country, user_id) VALUES(?, ?, ?, ?, ?, ?, ?, ?) [23505-200]
        at liquibase.changelog.ChangeLogIterator.run(ChangeLogIterator.java:124)
        at liquibase.Liquibase.lambda$null$0(Liquibase.java:275)
        at liquibase.Scope.lambda$child$0(Scope.java:160)
        at liquibase.Scope.child(Scope.java:169)
        at liquibase.Scope.child(Scope.java:159)
        at liquibase.Scope.child(Scope.java:138)
        at liquibase.Scope.child(Scope.java:222)
        at liquibase.Liquibase.lambda$update$1(Liquibase.java:274)
        at liquibase.Scope.lambda$child$0(Scope.java:160)
        at liquibase.Scope.child(Scope.java:169)
        at liquibase.Scope.child(Scope.java:159)
        at liquibase.Scope.child(Scope.java:138)
        at liquibase.Liquibase.runInScope(Liquibase.java:2277)
        at liquibase.Liquibase.update(Liquibase.java:215)
        at liquibase.Liquibase.update(Liquibase.java:201)
        at liquibase.integration.spring.SpringLiquibase.performUpdate(SpringLiquibase.java:321)
        at liquibase.integration.spring.SpringLiquibase.afterPropertiesSet(SpringLiquibase.java:269)
        at org.springframework.boot.autoconfigure.liquibase.DataSourceClosingSpringLiquibase.afterPropertiesSet(DataSourceClosingSpringLiquibase.java:46)
        at tech.jhipster.config.liquibase.AsyncSpringLiquibase.initDb(AsyncSpringLiquibase.java:118)
        at tech.jhipster.config.liquibase.AsyncSpringLiquibase.lambda$afterPropertiesSet$0(AsyncSpringLiquibase.java:93)
        at tech.jhipster.async.ExceptionHandlingAsyncTaskExecutor.lambda$createWrappedRunnable$1(ExceptionHandlingAsyncTaskExecutor.java:78)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
        at java.base/java.lang.Thread.run(Thread.java:832)
Caused by: liquibase.exception.MigrationFailedException: Migration failed for change set config/liquibase/changelog/20210214043542_added_entity_CustomerDetails.xml::20210214043542-1-data::jhipster:
     Reason: liquibase.exception.DatabaseException: org.h2.jdbc.JdbcBatchUpdateException: Unique index or primary key violation: "PUBLIC.UX_CUSTOMER_DETAILS__USER_ID_INDEX_E ON PUBLIC.CUSTOMER_DETAILS(USER_ID) VALUES 1"; SQL statement:
INSERT INTO PUBLIC.customer_details(id, gender, phone, address_line_1, address_line_2, city, country, user_id) VALUES(?, ?, ?, ?, ?, ?, ?, ?) [23505-200]
        at liquibase.changelog.ChangeSet.execute(ChangeSet.java:670)
        at liquibase.changelog.visitor.UpdateVisitor.visit(UpdateVisitor.java:49)
        at liquibase.changelog.ChangeLogIterator$2.lambda$null$0(ChangeLogIterator.java:111)
        at liquibase.Scope.lambda$child$0(Scope.java:160)
        at liquibase.Scope.child(Scope.java:169)
        at liquibase.Scope.child(Scope.java:159)
        at liquibase.Scope.child(Scope.java:138)
        at liquibase.changelog.ChangeLogIterator$2.lambda$run$1(ChangeLogIterator.java:110)
        at liquibase.Scope.lambda$child$0(Scope.java:160)
        at liquibase.Scope.child(Scope.java:169)
        at liquibase.Scope.child(Scope.java:159)
        at liquibase.Scope.child(Scope.java:138)
        at liquibase.Scope.child(Scope.java:222)
        at liquibase.changelog.ChangeLogIterator$2.run(ChangeLogIterator.java:94)
        at liquibase.Scope.lambda$child$0(Scope.java:160)
        at liquibase.Scope.child(Scope.java:169)
        at liquibase.Scope.child(Scope.java:159)
        at liquibase.Scope.child(Scope.java:138)
        at liquibase.Scope.child(Scope.java:222)
        at liquibase.Scope.child(Scope.java:226)
        at liquibase.changelog.ChangeLogIterator.run(ChangeLogIterator.java:66)
        ... 23 common frames omitted
Caused by: liquibase.exception.DatabaseException: org.h2.jdbc.JdbcBatchUpdateException: Unique index or primary key violation: "PUBLIC.UX_CUSTOMER_DETAILS__USER_ID_INDEX_E ON PUBLIC.CUSTOMER_DETAILS(USER_ID) VALUES 1"; SQL statement:
INSERT INTO PUBLIC.customer_details(id, gender, phone, address_line_1, address_line_2, city, country, user_id) VALUES(?, ?, ?, ?, ?, ?, ?, ?) [23505-200]
        at liquibase.statement.ExecutablePreparedStatementBase.execute(ExecutablePreparedStatementBase.java:82)
        at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:140)
        at liquibase.database.AbstractJdbcDatabase.execute(AbstractJdbcDatabase.java:1272)
        at liquibase.database.AbstractJdbcDatabase.executeStatements(AbstractJdbcDatabase.java:1254)
        at liquibase.changelog.ChangeSet.execute(ChangeSet.java:635)
        ... 43 common frames omitted
Caused by: org.h2.jdbc.JdbcBatchUpdateException: Unique index or primary key violation: "PUBLIC.UX_CUSTOMER_DETAILS__USER_ID_INDEX_E ON PUBLIC.CUSTOMER_DETAILS(USER_ID) VALUES 1"; SQL statement:
INSERT INTO PUBLIC.customer_details(id, gender, phone, address_line_1, address_line_2, city, country, user_id) VALUES(?, ?, ?, ?, ?, ?, ?, ?) [23505-200]
        at org.h2.jdbc.JdbcPreparedStatement.executeBatch(JdbcPreparedStatement.java:1235)
        at com.zaxxer.hikari.pool.ProxyStatement.executeBatch(ProxyStatement.java:128)
        at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeBatch(HikariProxyPreparedStatement.java)
        at liquibase.statement.BatchDmlExecutablePreparedStatement.executePreparedStatement(BatchDmlExecutablePreparedStatement.java:64)
        at liquibase.statement.ExecutablePreparedStatementBase.execute(ExecutablePreparedStatementBase.java:80)
        ... 47 common frames omitted
```

##### **JHipster Version(s)**

7.0.0-beta.1

##### **Browsers and Operating System**

- [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by mshima** [comment]
Seems duplicate of https://github.com/jhipster/generator-jhipster/issues/14158.
Should be fixed in current main branch.
