### ISSUE TITLE
gulp serve fails - headers already sent

### ISSUE THREAD

**Issue by marksmall** [jhipster/generator-jhipster#1396]
Not sure if this is a bug with jhipster or BrowserSync, I recently started investigating jhipster.  I am using:

> npm -v
> 2.7.5
> node -v
> v0.12.2
> bower -v
> 1.4.1
 
I ran: **yo jhipster**, everything worked as expected.  I then ran: **mvn spring:boot run**, again the app started and I was able to use it on: **http://127..00.1:8080**.

The problem I see is when using **gulp serve**

gulp serve                                                                                                                            
[22:42:55] Using gulpfile ~/dev/projects/testbench/gulp-jhipster/gulpfile.js
[22:42:55] Starting 'watch'...
[22:42:55] Finished 'watch' after 78 ms
[22:42:55] Starting 'serve'...
[22:42:55] Starting 'wiredep:test'...
[22:42:55] Finished 'serve' after 16 ms
[22:42:56] Finished 'wiredep:test' after 88 ms
[22:42:56] Starting 'wiredep:app'...
[22:42:56] Finished 'wiredep:app' after 66 ms
[22:42:56] Starting 'ngconstant:dev'...
[22:42:56] Starting 'compass'...
[22:42:56] Finished 'ngconstant:dev' after 127 ms
identical src/main/webapp/assets/styles/main.css 

[22:42:57] Finished 'compass' after 1.36 s
[22:42:57] Starting 'styles'...
[BS] 2 files changed (documentation.css, main.css)
[22:42:57] Finished 'styles' after 18 ms
[BS] Access URLs:
 -------------------------------------
       Local: http://localhost:9000
    External: http://192.168.0.70:9000
 -------------------------------------
          UI: http://localhost:3001
 UI External: http://192.168.0.70:3001
 -------------------------------------
[BS] Serving files from: src/main/webapp/

This seems fine although I expected BrowserSync to automatically open the browser with the app.  I therefore opened **http://localhost:9000** and get:

Error: Can't set headers after they are sent.
    at SendStream.headersAlreadySent (/home/msmall/dev/projects/testbench/gulp-jhipster/node_modules/browser-sync/node_modules/serve-static/node_modules/send/index.js:319:13)
    at SendStream.send (/home/msmall/dev/projects/testbench/gulp-jhipster/node_modules/browser-sync/node_modules/serve-static/node_modules/send/index.js:501:17)
    at /home/msmall/dev/projects/testbench/gulp-jhipster/node_modules/browser-sync/node_modules/serve-static/node_modules/send/index.js:645:12
    at FSReqWrap.oncomplete (fs.js:95:15)
Error: Can't set headers after they are sent.
    at SendStream.headersAlreadySent (/home/msmall/dev/projects/testbench/gulp-jhipster/node_modules/browser-sync/node_modules/serve-static/node_modules/send/index.js:319:13)
    at SendStream.send (/home/msmall/dev/projects/testbench/gulp-jhipster/node_modules/browser-sync/node_modules/serve-static/node_modules/send/index.js:501:17)
    at onstat (/home/msmall/dev/projects/testbench/gulp-jhipster/node_modules/browser-sync/node_modules/serve-static/node_modules/send/index.js:600:10)
    at FSReqWrap.oncomplete (fs.js:95:15)

I can't tell if this is a problem with **jhipster 2.7.0** or **BrowserSync 2.2.3**

**Comment by fclaeys** [comment]
Hello,
I submitted a PR to fix this issue #1390, this issue is linked to #1214

**Comment by jdubois** [comment]
As the PR is merged I'm closing this
