### ISSUE TITLE
Error while parsing applications and entities from the JDL TypeError: Cannot read property 'setOptions' of undefined

### ISSUE THREAD

**Issue by Ebraheem-Alrabeea** [jhipster/generator-jhipster#13973]
##### **Overview of the issue**

It is appear after trying to generate the application from JDL file.

TypeError: Cannot read property 'setOptions' of undefined
Error while parsing applications and entities from the JDL TypeError: Cannot read property 'setOptions' of undefined
TypeError: Cannot read property 'setOptions' of undefined
    at /usr/local/lib/node_modules/generator-jhipster/node_modules/jhipster-core/lib/converters/JDLToJSON/jdl_with_applications_to_json_converter.js:136:26
    at Map.forEach (<anonymous>)
    at setOptions (/usr/local/lib/node_modules/generator-jhipster/node_modules/jhipster-core/lib/converters/JDLToJSON/jdl_with_applications_to_json_converter.js:135:27)
    at Object.convert (/usr/local/lib/node_modules/generator-jhipster/node_modules/jhipster-core/lib/converters/JDLToJSON/jdl_with_applications_to_json_converter.js:61:3)
    at importApplicationsAndEntities (/usr/local/lib/node_modules/generator-jhipster/node_modules/jhipster-core/lib/jdl/jdl_importer.js:243:72)
    at Object.import (/usr/local/lib/node_modules/generator-jhipster/node_modules/jhipster-core/lib/jdl/jdl_importer.js:113:23)
    at JDLProcessor.importJDL (/usr/local/lib/node_modules/generator-jhipster/cli/import-jdl.js:54:41)
    at JDLProcessor.importJDL (/usr/local/lib/node_modules/generator-jhipster/cli/import-jdl.js:288:38)
    at module.exports (/usr/local/lib/node_modules/generator-jhipster/cli/import-jdl.js:412:21)
    at /usr/local/lib/node_modules/generator-jhipster/cli/jdl.js:93:51
Error during import-jdl: Cannot read property 'setOptions' of undefined
TypeError: Cannot read property 'setOptions' of undefined
    at /usr/local/lib/node_modules/generator-jhipster/node_modules/jhipster-core/lib/converters/JDLToJSON/jdl_with_applications_to_json_converter.js:136:26
    at Map.forEach (<anonymous>)
    at setOptions (/usr/local/lib/node_modules/generator-jhipster/node_modules/jhipster-core/lib/converters/JDLToJSON/jdl_with_applications_to_json_converter.js:135:27)
    at Object.convert (/usr/local/lib/node_modules/generator-jhipster/node_modules/jhipster-core/lib/converters/JDLToJSON/jdl_with_applications_to_json_converter.js:61:3)
    at importApplicationsAndEntities (/usr/local/lib/node_modules/generator-jhipster/node_modules/jhipster-core/lib/jdl/jdl_importer.js:243:72)
    at Object.import (/usr/local/lib/node_modules/generator-jhipster/node_modules/jhipster-core/lib/jdl/jdl_importer.js:113:23)
    at JDLProcessor.importJDL (/usr/local/lib/node_modules/generator-jhipster/cli/import-jdl.js:54:41)
    at JDLProcessor.importJDL (/usr/local/lib/node_modules/generator-jhipster/cli/import-jdl.js:288:38)
    at module.exports (/usr/local/lib/node_modules/generator-jhipster/cli/import-jdl.js:412:21)
    at /usr/local/lib/node_modules/generator-jhipster/cli/jdl.js:93:51
Error: Error during import-jdl: Cannot read property 'setOptions' of undefined
    at module.exports (/usr/local/lib/node_modules/generator-jhipster/cli/import-jdl.js:428:31)
    at /usr/local/lib/node_modules/generator-jhipster/cli/jdl.js:93:51
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

##### **Motivation for or Use Case**

I can't generate my application.

##### **Reproduce the error**

create a microservice application with gateway, add new entity with preserved name (store, order) 

##### **Suggest a Fix**

  
In the file that throw the exception:
 /usr/local/lib/node_modules/generator-jhipster/node_modules/jhipster-core/lib/converters/JDLToJSON/jdl_with_applications_to_json_converter.js

The line number 136:
entities[entityName].setOptions(optionContent);

I think the problem is the entities array does not contains the new entity name with prefix.

##### **JHipster Version(s)**

v6.10.5

##### **JHipster configuration**

INFO! Using JHipster version installed globally
INFO! Executing jhipster:info
Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
ebraheem@ /home/ebraheem
└── (empty)

```

cat: no such file or directory: .yo-rc.json

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

openjdk version "1.8.0_275"
OpenJDK Runtime Environment (build 1.8.0_275-b01)
OpenJDK 64-Bit Server VM (build 25.275-b01, mixed mode)

git version 2.29.2

node: v14.15.4

npm: 7.5.4

yarn: 1.22.10

Docker version 20.10.2, build 2291f61

docker-compose version 1.27.4, build unknown

INFO! Congratulations, JHipster execution is complete!

##### **Browsers and Operating System**

Fedora Linux

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by MathieuAA** [comment]
Hello there, can you provide the JDL file? So that it's easier for us to reproduce and hopefully fix any issue.
Thanks

**Comment by Ebraheem-Alrabeea** [comment]
I don't know why, but the code is generated successfully after updating npm to latest and deleting jhipster global library and install it again.

**Comment by fishcleaner** [comment]
Hello,
I have the same issue and it's blocking!
I noticed that excluding the DTO with Mapstruct the generation works fine but the thing is that we need DTOs.
I am using JHipster v7.2.0 , node v14.17.6.
Could you please solve this ASAP or propose a workaround ? I have already tried to remove JHipster and re-install it.

[data-model.jdl.txt](https://github.com/jhipster/generator-jhipster/files/7236635/data-model.jdl.txt)

**Comment by Brouilles** [comment]
Same here. With Java project and also jHipster.Net.

**Comment by Brouilles** [comment]
My JDL file here
[shop.jdl.txt](https://github.com/jhipster/generator-jhipster/files/7587293/shop.jdl.txt)
