### ISSUE TITLE
Cannot deploy application with postgres to Cloud Foundry 

### ISSUE THREAD

**Issue by davykiala** [jhipster/generator-jhipster#1401]
1. I've generate an application (eds). I choose Postgres as dev database and prod database.
![capture d ecran 2015-04-21 a 22 45 54](https://cloud.githubusercontent.com/assets/4395342/7262533/c07e29c6-e87a-11e4-947a-6bbe5f641037.png)

The application is correctly generated but when i deploy the application to CloudFoundry i have an strange error.
![capture d ecran 2015-04-21 a 22 49 32](https://cloud.githubusercontent.com/assets/4395342/7262552/f509b8f4-e87a-11e4-833d-a7ded0443bea.png)

-----> Uploading droplet (87M)

0 de 1 d'instances en cours, 1 démarrage

0 de 1 d'instances en cours, 1 arrêté

0 de 1 d'instances en cours, 1 arrêté

0 de 1 d'instances en cours, 1 arrêté

0 de 1 d'instances en cours, 1 arrêté

0 de 1 d'instances en cours, 1 arrêté

0 de 1 d'instances en cours, 1 arrêté

0 de 1 d'instances en cours, 1 arrêté

0 de 1 d'instances en cours, 1 démarrage

0 de 1 d'instances en cours, 1 arrêté

0 de 1 d'instances en cours, 1 arrêté

0 de 1 d'instances en cours, 1 arrêté

0 de 1 d'instances en cours, 1 en défaut

RATÉ
Lancer échoué

TIP: utiliser 'cf logs eds --recent' pour plus d'informations

✖ { [Error: Command failed: /bin/sh -c cf push -f ./deploy/cloudfoundry/manifest.yml -p target/*.war
]
  killed: false,
  code: 1,
  signal: null,
  cmd: '/bin/sh -c cf push -f ./deploy/cloudfoundry/manifest.yml -p target/*.war' }

2. I've generate an application (mysql). I choose MySQL as dev database and prod database.
![capture d ecran 2015-04-21 a 23 08 35](https://cloud.githubusercontent.com/assets/4395342/7262622/6c1b02a4-e87b-11e4-9cf6-fea61710c56c.png)

Then i deploy to cloudfoundry 
![capture d ecran 2015-04-21 a 23 13 16](https://cloud.githubusercontent.com/assets/4395342/7262751/3c9cd844-e87c-11e4-8cf6-966f4e60ab24.png)
-----> Uploading droplet (88M)

0 de 1 d'instances en cours, 1 démarrage

0 de 1 d'instances en cours, 1 démarrage

0 de 1 d'instances en cours, 1 démarrage

1 de 1 d'instances en cours
Application démarrée

OK

Application mysqlapp a été démarrée avec la commande `SERVER_PORT=$PORT $PWD/.java-buildpack/open_jdk_jre/bin/java -cp $PWD/.:$PWD/.java-buildpack/postgresql_jdbc/postgresql_jdbc-9.4.1201.jar:$PWD/.java-buildpack/spring_auto_reconfiguration/spring_auto_reconfiguration-1.7.0_RELEASE.jar -Djava.io.tmpdir=$TMPDIR -XX:OnOutOfMemoryError=$PWD/.java-buildpack/open_jdk_jre/bin/killjava.sh -Xmx768M -Xms768M -XX:MaxMetaspaceSize=104857K -XX:MetaspaceSize=104857K -Xss1M org.springframework.boot.loader.WarLauncher`

Santé et état de l'application mysqlapp de l'org ..... / espace development en tant que ...

OK

État: started
instances: 1/1
utilisation: 1G x 1 instances
URLs: mysqlapp.cfapps.io
dernier téléchargement: Tue Apr 21 21:15:05 UTC 2015

     state        depuis                   cpu    mémoire      disque          details   
#0   fonctionne   2015-04-21 11:16:21 PM   0.0%   670M de 1G   179.8M sur 1G      

I don't understand why the application with postgres cannot be deployed but the mysql is deployed without error.

**Comment by jdubois** [comment]
Concerning the MySQL part: ElephantSQL is a Postgresql database -> it doesn't fully work

- CloudFoundry automatically reconfigures your datasource: I'm surprised this even works, but you have your MySQL datasource reconfigured as a PostgreSQL datasource. Crazy stuff!
- As long as you use SQL queries that work on both databases, that can work -> this is indeed very limited, if you create a new entity I would be surprised that this works.

Anyway that's just an incredible luck that you select a MySQL database and then run this on a PostgreSQL cloud service, and that this works!!

But this doesn't explain your first issue: you should have more logs than a "command failed", because here we have not explanation on what happens. Can you check your logs again?

**Comment by davykiala** [comment]
I've cheked logs. Here is the content from cloud foundry user interface: 

2015-04-21T20:50:43.000+00:00 [API] OUT Created app with guid 85a00bdc-dc37-4d03-a3d6-071bc6de0350
2015-04-21T20:51:32.000+00:00 [STG] OUT -----> Downloaded app package (44M)
2015-04-21T20:51:35.000+00:00 [STG] OUT -----> Java Buildpack Version: v3.0 | https://github.com/cloudfoundry/java-buildpack.git#3bd15e1
2015-04-21T20:52:08.000+00:00 [DEA] OUT Starting app instance (index 0) with guid 85a00bdc-dc37-4d03-a3d6-071bc6de0350
2015-04-21T20:52:14.000+00:00 [App/0] ERR java.util.zip.ZipException: error in opening zip file
2015-04-21T20:52:14.000+00:00 [App/0] ERR at java.util.zip.ZipFile.open(Native Method)
2015-04-21T20:52:14.000+00:00 [App/0] ERR at org.springframework.boot.loader.jar.JarFile.<init>(JarFile.java:117)
2015-04-21T20:52:14.000+00:00 [App/0] ERR at org.springframework.boot.loader.Launcher.launch(Launcher.java:60)
2015-04-21T20:53:33.000+00:00 [DEA] OUT Starting app instance (index 0) with guid 85a00bdc-dc37-4d03-a3d6-071bc6de0350
2015-04-21T20:53:38.000+00:00 [App/0] ERR at java.util.jar.JarFile.<init>(JarFile.java:166)
2015-04-21T20:53:38.000+00:00 [App/0] ERR at org.springframework.boot.loader.archive.JarFileArchive.<init>(JarFileArchive.java:61)
2015-04-21T20:53:38.000+00:00 [App/0] ERR at org.springframework.boot.loader.archive.ExplodedArchive.getNestedArchives(ExplodedArchive.java:142)
2015-04-21T20:53:38.000+00:00 [App/0] ERR at org.springframework.boot.loader.ExecutableArchiveLauncher.getClassPathArchives(ExecutableArchiveLauncher.java:74)
2015-04-21T20:53:38.000+00:00 [App/0] ERR at org.springframework.boot.loader.Launcher.launch(Launcher.java:60)
2015-04-21T20:53:38.000+00:00 [App/0] OUT 
2015-04-21T20:55:40.000+00:00 [App/0] ERR java.util.zip.ZipException: error in opening zip file
2015-04-21T20:55:40.000+00:00 [App/0] ERR at org.springframework.boot.loader.archive.ExplodedArchive.getNestedArchives(ExplodedArchive.java:142)
2015-04-21T20:55:40.000+00:00 [App/0] ERR at org.springframework.boot.loader.ExecutableArchiveLauncher.getClassPathArchives(ExecutableArchiveLauncher.java:74)
2015-04-21T20:55:40.000+00:00 [App/0] ERR at org.springframework.boot.loader.Launcher.launch(Launcher.java:60)
2015-04-21T21:00:01.000+00:00 [App/0] ERR at java.util.zip.ZipFile.<init>(ZipFile.java:220)
2015-04-21T21:00:01.000+00:00 [App/0] ERR at java.util.jar.JarFile.<init>(JarFile.java:130)
2015-04-21T21:00:01.000+00:00 [App/0] ERR at org.springframework.boot.loader.archive.JarFileArchive.<init>(JarFileArchive.java:57)
2015-04-21T21:00:01.000+00:00 [App/0] ERR at org.springframework.boot.loader.Launcher.launch(Launcher.java:60)
2015-04-21T21:13:50.000+00:00 [App/0] ERR at org.springframework.boot.loader.jar.JarFile.<init>(JarFile.java:95)
2015-04-21T21:13:50.000+00:00 [DEA] ERR Instance (index 0) failed to start accepting connections
2015-04-21T20:52:14.000+00:00 [API] OUT App instance exited with guid 85a00bdc-dc37-4d03-a3d6-071bc6de0350 payload: {"cc_partition"=>"default", "droplet"=>"85a00bdc-dc37-4d03-a3d6-071bc6de0350", "version"=>"246ea7aa-776a-473a-b9cf-4fe4c73cdc49", "instance"=>"8a324c3f3f884692995ee4158fb22e2b", "index"=>0, "reason"=>"CRASHED", "exit_status"=>1, "exit_description"=>"failed to accept connections within health check timeout", "crash_timestamp"=>1429649534}
2015-04-21T20:52:49.000+00:00 [API] OUT App instance exited with guid 85a00bdc-dc37-4d03-a3d6-071bc6de0350 payload: {"cc_partition"=>"default", "droplet"=>"85a00bdc-dc37-4d03-a3d6-071bc6de0350", "version"=>"246ea7aa-776a-473a-b9cf-4fe4c73cdc49", "instance"=>"3289f41aa31c4179bb74a2b9852afa76", "index"=>0, "reason"=>"CRASHED", "exit_status"=>1, "exit_description"=>"failed to accept connections within health check timeout", "crash_timestamp"=>1429649569}
2015-04-21T20:54:28.000+00:00 [DEA] ERR Instance (index 0) failed to start accepting connections
2015-04-21T21:05:30.000+00:00 [API] OUT App instance exited with guid 85a00bdc-dc37-4d03-a3d6-071bc6de0350 payload: {"cc_partition"=>"default", "droplet"=>"85a00bdc-dc37-4d03-a3d6-071bc6de0350", "version"=>"246ea7aa-776a-473a-b9cf-4fe4c73cdc49", "instance"=>"5623b7053bbd46d5ba4c80faed0c78c5", "index"=>0, "reason"=>"CRASHED", "exit_status"=>1, "exit_description"=>"failed to accept connections within health check timeout", "crash_timestamp"=>1429650330}
2015-04-21T21:13:50.000+00:00 [API] OUT App instance exited with guid 85a00bdc-dc37-4d03-a3d6-071bc6de0350 payload: {"cc_partition"=>"default", "droplet"=>"85a00bdc-dc37-4d03-a3d6-071bc6de0350", "version"=>"246ea7aa-776a-473a-b9cf-4fe4c73cdc49", "instance"=>"480ce072fa044d50942e0d44adf75868", "index"=>0, "reason"=>"CRASHED", "exit_status"=>1, "exit_description"=>"failed to accept connections within health check timeout", "crash_timestamp"=>1429650830}
2015-04-21T20:51:39.000+00:00 [STG] OUT -----> Downloading Spring Auto Reconfiguration 1.7.0_RELEASE from https://download.run.pivotal.io/auto-reconfiguration/auto-reconfiguration-1.7.0_RELEASE.jar (0.0s)
2015-04-21T20:52:14.000+00:00 [API] OUT App instance exited with guid 85a00bdc-dc37-4d03-a3d6-071bc6de0350 payload: {"cc_partition"=>"default", "droplet"=>"85a00bdc-dc37-4d03-a3d6-071bc6de0350", "version"=>"246ea7aa-776a-473a-b9cf-4fe4c73cdc49", "instance"=>"8a324c3f3f884692995ee4158fb22e2b", "index"=>0, "reason"=>"CRASHED", "exit_status"=>1, "exit_description"=>"failed to accept connections within health check timeout", "crash_timestamp"=>1429649534}
2015-04-21T20:52:14.000+00:00 [App/0] ERR at java.util.zip.ZipFile.<init>(ZipFile.java:220)
2015-04-21T20:52:14.000+00:00 [App/0] ERR at java.util.zip.ZipFile.<init>(ZipFile.java:150)
2015-04-21T20:52:14.000+00:00 [App/0] ERR at org.springframework.boot.loader.jar.JarFile.<init>(JarFile.java:95)
2015-04-21T20:52:14.000+00:00 [App/0] ERR at org.springframework.boot.loader.archive.JarFileArchive.<init>(JarFileArchive.java:57)
2015-04-21T20:52:14.000+00:00 [App/0] ERR at org.springframework.boot.loader.WarLauncher.main(WarLauncher.java:61)
2015-04-21T20:52:14.000+00:00 [App/0] OUT 
2015-04-21T20:53:38.000+00:00 [App/0] ERR java.util.zip.ZipException: error in opening zip file
2015-04-21T20:53:38.000+00:00 [App/0] ERR at java.util.zip.ZipFile.open(Native Method)
2015-04-21T20:53:38.000+00:00 [App/0] ERR at org.springframework.boot.loader.jar.JarFile.<init>(JarFile.java:117)
2015-04-21T20:53:38.000+00:00 [App/0] ERR at org.springframework.boot.loader.archive.ExplodedArchive.getNestedArchive(ExplodedArchive.java:155)
2015-04-21T20:54:28.000+00:00 [API] OUT App instance exited with guid 85a00bdc-dc37-4d03-a3d6-071bc6de0350 payload: {"cc_partition"=>"default", "droplet"=>"85a00bdc-dc37-4d03-a3d6-071bc6de0350", "version"=>"246ea7aa-776a-473a-b9cf-4fe4c73cdc49", "instance"=>"cb26919f24854710820a6848ecb29521", "index"=>0, "reason"=>"CRASHED", "exit_status"=>1, "exit_description"=>"failed to accept connections within health check timeout", "crash_timestamp"=>1429649668}
2015-04-21T20:55:33.000+00:00 [DEA] OUT Starting app instance (index 0) with guid 85a00bdc-dc37-4d03-a3d6-071bc6de0350
2015-04-21T20:55:40.000+00:00 [App/0] ERR at java.util.jar.JarFile.<init>(JarFile.java:166)
2015-04-21T20:55:40.000+00:00 [App/0] ERR at org.springframework.boot.loader.archive.JarFileArchive.<init>(JarFileArchive.java:61)
2015-04-21T20:55:40.000+00:00 [DEA] ERR Instance (index 0) failed to start accepting connections
2015-04-21T21:00:01.000+00:00 [App/0] ERR at org.springframework.boot.loader.jar.JarFile.<init>(JarFile.java:117)
2015-04-21T21:00:01.000+00:00 [App/0] ERR at org.springframework.boot.loader.ExecutableArchiveLauncher.getClassPathArchives(ExecutableArchiveLauncher.java:74)
2015-04-21T21:00:01.000+00:00 [App/0] ERR at org.springframework.boot.loader.WarLauncher.main(WarLauncher.java:61)
2015-04-21T21:00:01.000+00:00 [DEA] ERR Instance (index 0) failed to start accepting connections
2015-04-21T21:13:50.000+00:00 [App/0] ERR at java.util.zip.ZipFile.open(Native Method)
2015-04-21T21:13:50.000+00:00 [App/0] ERR at java.util.zip.ZipFile.<init>(ZipFile.java:220)
2015-04-21T21:13:50.000+00:00 [App/0] ERR at org.springframework.boot.loader.jar.JarFile.<init>(JarFile.java:104)
2015-04-21T21:13:50.000+00:00 [App/0] ERR at org.springframework.boot.loader.archive.JarFileArchive.<init>(JarFileArchive.java:61)
2015-04-21T21:13:50.000+00:00 [App/0] ERR at org.springframework.boot.loader.archive.JarFileArchive.<init>(JarFileArchive.java:57)
2015-04-21T21:13:50.000+00:00 [App/0] ERR at org.springframework.boot.loader.ExecutableArchiveLauncher.getClassPathArchives(ExecutableArchiveLauncher.java:74)
2015-04-21T20:51:29.000+00:00 [DEA] OUT Got staging request for app with id 85a00bdc-dc37-4d03-a3d6-071bc6de0350
2015-04-21T20:51:39.000+00:00 [STG] OUT Expanding Open Jdk JRE to .java-buildpack/open_jdk_jre (1.4s)
2015-04-21T20:52:14.000+00:00 [App/0] ERR at org.springframework.boot.loader.archive.ExplodedArchive.getNestedArchives(ExplodedArchive.java:142)
2015-04-21T20:53:38.000+00:00 [App/0] ERR at java.util.zip.ZipFile.<init>(ZipFile.java:220)
2015-04-21T20:53:38.000+00:00 [App/0] ERR at java.util.zip.ZipFile.<init>(ZipFile.java:150)
2015-04-21T20:53:38.000+00:00 [App/0] ERR at org.springframework.boot.loader.jar.JarFile.<init>(JarFile.java:95)
2015-04-21T20:53:38.000+00:00 [DEA] ERR Instance (index 0) failed to start accepting connections
2015-04-21T20:53:38.000+00:00 [API] OUT App instance exited with guid 85a00bdc-dc37-4d03-a3d6-071bc6de0350 payload: {"cc_partition"=>"default", "droplet"=>"85a00bdc-dc37-4d03-a3d6-071bc6de0350", "version"=>"246ea7aa-776a-473a-b9cf-4fe4c73cdc49", "instance"=>"9201600de4444931b6704aac843fd049", "index"=>0, "reason"=>"CRASHED", "exit_status"=>1, "exit_description"=>"failed to accept connections within health check timeout", "crash_timestamp"=>1429649618}
2015-04-21T20:55:40.000+00:00 [App/0] ERR at java.util.zip.ZipFile.open(Native Method)
2015-04-21T20:55:40.000+00:00 [App/0] ERR at java.util.zip.ZipFile.<init>(ZipFile.java:150)
2015-04-21T20:55:40.000+00:00 [App/0] ERR at org.springframework.boot.loader.jar.JarFile.<init>(JarFile.java:117)
2015-04-21T20:55:40.000+00:00 [App/0] ERR at org.springframework.boot.loader.jar.JarFile.<init>(JarFile.java:95)
2015-04-21T21:00:01.000+00:00 [App/0] ERR at java.util.zip.ZipFile.<init>(ZipFile.java:150)
2015-04-21T21:00:01.000+00:00 [App/0] ERR at org.springframework.boot.loader.jar.JarFile.<init>(JarFile.java:104)
2015-04-21T21:13:50.000+00:00 [App/0] ERR java.util.zip.ZipException: error in opening zip file
2015-04-21T21:13:50.000+00:00 [App/0] ERR at java.util.zip.ZipFile.<init>(ZipFile.java:150)
2015-04-21T21:13:50.000+00:00 [App/0] ERR at org.springframework.boot.loader.jar.JarFile.<init>(JarFile.java:117)
2015-04-21T21:13:50.000+00:00 [App/0] ERR at org.springframework.boot.loader.archive.ExplodedArchive.getNestedArchive(ExplodedArchive.java:155)
2015-04-21T20:51:37.000+00:00 [STG] OUT -----> Downloading Open Jdk JRE 1.8.0_40 from https://download.run.pivotal.io/openjdk/trusty/x86_64/openjdk-1.8.0_40.tar.gz (2.1s)
2015-04-21T20:52:14.000+00:00 [App/0] ERR at java.util.jar.JarFile.<init>(JarFile.java:130)
2015-04-21T20:52:14.000+00:00 [App/0] ERR at org.springframework.boot.loader.jar.JarFile.<init>(JarFile.java:104)
2015-04-21T20:52:14.000+00:00 [App/0] ERR at org.springframework.boot.loader.archive.ExplodedArchive.getNestedArchive(ExplodedArchive.java:155)
2015-04-21T20:53:38.000+00:00 [App/0] ERR at org.springframework.boot.loader.archive.JarFileArchive.<init>(JarFileArchive.java:57)
2015-04-21T20:55:40.000+00:00 [App/0] ERR at java.util.zip.ZipFile.<init>(ZipFile.java:220)
2015-04-21T20:55:40.000+00:00 [App/0] ERR at java.util.jar.JarFile.<init>(JarFile.java:130)
2015-04-21T20:55:40.000+00:00 [App/0] ERR at org.springframework.boot.loader.jar.JarFile.<init>(JarFile.java:104)
2015-04-21T20:55:40.000+00:00 [App/0] ERR at org.springframework.boot.loader.archive.JarFileArchive.<init>(JarFileArchive.java:57)
2015-04-21T20:55:40.000+00:00 [App/0] ERR at org.springframework.boot.loader.archive.ExplodedArchive.getNestedArchive(ExplodedArchive.java:155)
2015-04-21T20:55:40.000+00:00 [App/0] OUT 
2015-04-21T20:55:40.000+00:00 [API] OUT App instance exited with guid 85a00bdc-dc37-4d03-a3d6-071bc6de0350 payload: {"cc_partition"=>"default", "droplet"=>"85a00bdc-dc37-4d03-a3d6-071bc6de0350", "version"=>"246ea7aa-776a-473a-b9cf-4fe4c73cdc49", "instance"=>"e1e2add134b84e21a1c06bea9de5a32c", "index"=>0, "reason"=>"CRASHED", "exit_status"=>1, "exit_description"=>"failed to accept connections within health check timeout", "crash_timestamp"=>1429649740}
2015-04-21T21:00:01.000+00:00 [App/0] ERR java.util.zip.ZipException: error in opening zip file
2015-04-21T21:00:01.000+00:00 [App/0] ERR at java.util.zip.ZipFile.open(Native Method)
2015-04-21T21:00:01.000+00:00 [App/0] ERR at java.util.jar.JarFile.<init>(JarFile.java:166)
2015-04-21T21:00:01.000+00:00 [App/0] ERR at org.springframework.boot.loader.archive.JarFileArchive.<init>(JarFileArchive.java:61)
2015-04-21T21:00:01.000+00:00 [App/0] OUT 
2015-04-21T21:13:50.000+00:00 [App/0] ERR at java.util.jar.JarFile.<init>(JarFile.java:166)
2015-04-21T21:13:50.000+00:00 [App/0] ERR at org.springframework.boot.loader.archive.ExplodedArchive.getNestedArchives(ExplodedArchive.java:142)
2015-04-21T21:13:50.000+00:00 [App/0] ERR at org.springframework.boot.loader.WarLauncher.main(WarLauncher.java:61)
2015-04-21T20:51:53.000+00:00 [STG] OUT -----> Uploading droplet (87M)
2015-04-21T20:52:14.000+00:00 [DEA] ERR Instance (index 0) failed to start accepting connections
2015-04-21T20:52:14.000+00:00 [App/0] ERR at java.util.jar.JarFile.<init>(JarFile.java:166)
2015-04-21T20:52:14.000+00:00 [App/0] ERR at org.springframework.boot.loader.archive.JarFileArchive.<init>(JarFileArchive.java:61)
2015-04-21T20:52:14.000+00:00 [App/0] ERR at org.springframework.boot.loader.ExecutableArchiveLauncher.getClassPathArchives(ExecutableArchiveLauncher.java:74)
2015-04-21T20:52:49.000+00:00 [API] OUT App instance exited with guid 85a00bdc-dc37-4d03-a3d6-071bc6de0350 payload: {"cc_partition"=>"default", "droplet"=>"85a00bdc-dc37-4d03-a3d6-071bc6de0350", "version"=>"246ea7aa-776a-473a-b9cf-4fe4c73cdc49", "instance"=>"3289f41aa31c4179bb74a2b9852afa76", "index"=>0, "reason"=>"CRASHED", "exit_status"=>1, "exit_description"=>"failed to accept connections within health check timeout", "crash_timestamp"=>1429649569}
2015-04-21T20:53:38.000+00:00 [App/0] ERR at java.util.jar.JarFile.<init>(JarFile.java:130)
2015-04-21T20:53:38.000+00:00 [App/0] ERR at org.springframework.boot.loader.jar.JarFile.<init>(JarFile.java:104)
2015-04-21T20:53:38.000+00:00 [App/0] ERR at org.springframework.boot.loader.WarLauncher.main(WarLauncher.java:61)
2015-04-21T20:55:40.000+00:00 [App/0] ERR at org.springframework.boot.loader.WarLauncher.main(WarLauncher.java:61)
2015-04-21T20:59:53.000+00:00 [DEA] OUT Starting app instance (index 0) with guid 85a00bdc-dc37-4d03-a3d6-071bc6de0350
2015-04-21T21:00:01.000+00:00 [App/0] ERR at org.springframework.boot.loader.jar.JarFile.<init>(JarFile.java:95)
2015-04-21T21:00:01.000+00:00 [App/0] ERR at org.springframework.boot.loader.archive.ExplodedArchive.getNestedArchive(ExplodedArchive.java:155)
2015-04-21T21:00:01.000+00:00 [App/0] ERR at org.springframework.boot.loader.archive.ExplodedArchive.getNestedArchives(ExplodedArchive.java:142)
2015-04-21T21:13:50.000+00:00 [App/0] ERR at java.util.jar.JarFile.<init>(JarFile.java:130)
2015-04-21T21:13:50.000+00:00 [App/0] ERR at org.springframework.boot.loader.Launcher.launch(Launcher.java:60)
2015-04-21T21:13:50.000+00:00 [App/0] OUT 
2015-04-21T20:52:43.000+00:00 [DEA] OUT Starting app instance (index 0) with guid 85a00bdc-dc37-4d03-a3d6-071bc6de0350
2015-04-21T20:57:20.000+00:00 [DEA] ERR Instance (index 0) failed to start accepting connections
2015-04-21T20:57:20.000+00:00 [API] OUT App instance exited with guid 85a00bdc-dc37-4d03-a3d6-071bc6de0350 payload: {"cc_partition"=>"default", "droplet"=>"85a00bdc-dc37-4d03-a3d6-071bc6de0350", "version"=>"246ea7aa-776a-473a-b9cf-4fe4c73cdc49", "instance"=>"3cdc0e5ed5284e7c9c0399251568b186", "index"=>0, "reason"=>"CRASHED", "exit_status"=>1, "exit_description"=>"failed to accept connections within health check timeout", "crash_timestamp"=>1429649840}
2015-04-21T21:00:01.000+00:00 [API] OUT App instance exited with guid 85a00bdc-dc37-4d03-a3d6-071bc6de0350 payload: {"cc_partition"=>"default", "droplet"=>"85a00bdc-dc37-4d03-a3d6-071bc6de0350", "version"=>"246ea7aa-776a-473a-b9cf-4fe4c73cdc49", "instance"=>"c59452ec00ce4e6288e611e9880e43c8", "index"=>0, "reason"=>"CRASHED", "exit_status"=>1, "exit_description"=>"failed to accept connections within health check timeout", "crash_timestamp"=>1429650001}
2015-04-21T21:00:01.000+00:00 [API] OUT App instance exited with guid 85a00bdc-dc37-4d03-a3d6-071bc6de0350 payload: {"cc_partition"=>"default", "droplet"=>"85a00bdc-dc37-4d03-a3d6-071bc6de0350", "version"=>"246ea7aa-776a-473a-b9cf-4fe4c73cdc49", "instance"=>"c59452ec00ce4e6288e611e9880e43c8", "index"=>0, "reason"=>"CRASHED", "exit_status"=>1, "exit_description"=>"failed to accept connections within health check timeout", "crash_timestamp"=>1429650001}
2015-04-21T21:04:33.000+00:00 [DEA] OUT Starting app instance (index 0) with guid 85a00bdc-dc37-4d03-a3d6-071bc6de0350
2015-04-21T21:05:30.000+00:00 [DEA] ERR Instance (index 0) failed to start accepting connections
2015-04-21T20:51:31.000+00:00 [API] OUT Updated app with guid 85a00bdc-dc37-4d03-a3d6-071bc6de0350 ({"state"=>"STARTED"})
2015-04-21T20:53:38.000+00:00 [API] OUT App instance exited with guid 85a00bdc-dc37-4d03-a3d6-071bc6de0350 payload: {"cc_partition"=>"default", "droplet"=>"85a00bdc-dc37-4d03-a3d6-071bc6de0350", "version"=>"246ea7aa-776a-473a-b9cf-4fe4c73cdc49", "instance"=>"9201600de4444931b6704aac843fd049", "index"=>0, "reason"=>"CRASHED", "exit_status"=>1, "exit_description"=>"failed to accept connections within health check timeout", "crash_timestamp"=>1429649618}
2015-04-21T20:54:28.000+00:00 [API] OUT App instance exited with guid 85a00bdc-dc37-4d03-a3d6-071bc6de0350 payload: {"cc_partition"=>"default", "droplet"=>"85a00bdc-dc37-4d03-a3d6-071bc6de0350", "version"=>"246ea7aa-776a-473a-b9cf-4fe4c73cdc49", "instance"=>"cb26919f24854710820a6848ecb29521", "index"=>0, "reason"=>"CRASHED", "exit_status"=>1, "exit_description"=>"failed to accept connections within health check timeout", "crash_timestamp"=>1429649668}
2015-04-21T20:57:20.000+00:00 [API] OUT App instance exited with guid 85a00bdc-dc37-4d03-a3d6-071bc6de0350 payload: {"cc_partition"=>"default", "droplet"=>"85a00bdc-dc37-4d03-a3d6-071bc6de0350", "version"=>"246ea7aa-776a-473a-b9cf-4fe4c73cdc49", "instance"=>"3cdc0e5ed5284e7c9c0399251568b186", "index"=>0, "reason"=>"CRASHED", "exit_status"=>1, "exit_description"=>"failed to accept connections within health check timeout", "crash_timestamp"=>1429649840}
2015-04-21T21:05:30.000+00:00 [API] OUT App instance exited with guid 85a00bdc-dc37-4d03-a3d6-071bc6de0350 payload: {"cc_partition"=>"default", "droplet"=>"85a00bdc-dc37-4d03-a3d6-071bc6de0350", "version"=>"246ea7aa-776a-473a-b9cf-4fe4c73cdc49", "instance"=>"5623b7053bbd46d5ba4c80faed0c78c5", "index"=>0, "reason"=>"CRASHED", "exit_status"=>1, "exit_description"=>"failed to accept connections within health check timeout", "crash_timestamp"=>1429650330}
2015-04-21T21:13:50.000+00:00 [API] OUT App instance exited with guid 85a00bdc-dc37-4d03-a3d6-071bc6de0350 payload: {"cc_partition"=>"default", "droplet"=>"85a00bdc-dc37-4d03-a3d6-071bc6de0350", "version"=>"246ea7aa-776a-473a-b9cf-4fe4c73cdc49", "instance"=>"480ce072fa044d50942e0d44adf75868", "index"=>0, "reason"=>"CRASHED", "exit_status"=>1, "exit_description"=>"failed to accept connections within health check timeout", "crash_timestamp"=>1429650830}
2015-04-21T20:50:46.000+00:00 [API] OUT Updated app with guid 85a00bdc-dc37-4d03-a3d6-071bc6de0350 ({"route"=>"460c1746-d7b5-4f4f-bc8e-fe8dd89d6aba"})
2015-04-21T20:55:40.000+00:00 [API] OUT App instance exited with guid 85a00bdc-dc37-4d03-a3d6-071bc6de0350 payload: {"cc_partition"=>"default", "droplet"=>"85a00bdc-dc37-4d03-a3d6-071bc6de0350", "version"=>"246ea7aa-776a-473a-b9cf-4fe4c73cdc49", "instance"=>"e1e2add134b84e21a1c06bea9de5a32c", "index"=>0, "reason"=>"CRASHED", "exit_status"=>1, "exit_description"=>"failed to accept connections within health check timeout", "crash_timestamp"=>1429649740}
2015-04-21T20:57:13.000+00:00 [DEA] OUT Starting app instance (index 0) with guid 85a00bdc-dc37-4d03-a3d6-071bc6de0350

**Comment by jdubois** [comment]
According to the logs your application just timed out: no idea what happens, but it is too slow to start. A normal JHipster app should start in 20/30 seconds, of course this depends on a lot of parameters, but it shouldn't time out (I've never experienced this myself).
Are you using Pivotal's CF? Maybe you're using a very small machine?

**Comment by davykiala** [comment]
I am using Pivotal Cloud Foundry. I have 1Go as memory. 
Maybe you're using a very small machine? You mean my machine ? 
I don't know why the time out never appear when i select the mysql database.

**Comment by jdubois** [comment]
OK we use the same setup (Pivotal CF, 1 Go), and I never had a timeout. Did you try several times? Maybe that was just bad luck when deploying?

**Comment by davykiala** [comment]
I've created many applications with this configuration and i have the same problem. Could you try and make choose as i did ?

**Comment by jdubois** [comment]
Excepted from the token-based authentication, I have exactly the same setup as you, currently running. I doubt this can make a difference.

**Comment by davykiala** [comment]
I've tried again and still have the same error.

**Comment by jdubois** [comment]
I'm sorry but I still can't reproduce your issue.

- I have created the same app as you, with token authent and Postgresql
- I uploaded it to Pivotal's CF

No issue at all...

As at the beginning you were trying to deploy a MySQL application on a Postgresql instance, are you sure you deploy to the right database?

Otherwise I just can't reproduce your issue.
