### ISSUE TITLE
java 1.6 compliant

### ISSUE THREAD

**Issue by alpoza** [jhipster/generator-jhipster#1406]
¿Is posible get jhipster java 1.6 compliant? I change generated classes with `diamond operator is not supported in -source 1.6 compilation errors`, but get a Tomcat exception:

```
java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:53)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.IllegalStateException: Tomcat connector in failed state
        at org.springframework.boot.context.embedded.tomcat.TomcatEmbeddedServletContainer.start(TomcatEmbeddedServletContainer.java:157)
        at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.startEmbeddedServletContainer(EmbeddedWebApplicationContext.java:288)
        at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.finishRefresh(EmbeddedWebApplicationContext.java:141)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:483)
        at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:118)
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:686)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:320)
        at com.isban.Application.main(Application.java:59)
        ... 6 more
```

**Comment by atomfrede** [comment]
JHipster only supports java 7 and 8. Sooner or later java 7 support will be removed, so I think supporting java 6 won't happen. Why do you require java 6 compliance?

**Comment by jdubois** [comment]
No, we will not support 1.6.
It's outdated, and you should not use it.

**Comment by alpoza** [comment]
OK. Thanx.
