### ISSUE TITLE
Error looking for otherEntity User

### ISSUE THREAD

**Issue by EnziinSystem** [jhipster/generator-jhipster#14436]
I use JHipster 7.0.0 with JDL file:
```
application {
  config {
    baseName gate,
    applicationType gateway,
    packageName com.enziin.gate,
    authenticationType jwt,
    serviceDiscoveryType eureka,
    serverPort 8080,
    prodDatabaseType mysql,
    clientFramework react,
    clientPackageManager npm,
    buildTool maven,
    cacheProvider hazelcast,
    jhiPrefix gate
  }
  entities Book, Chapter
}

application {
  config {
    baseName book,
    applicationType microservice,
    packageName com.enziin.book,
    authenticationType jwt,
    prodDatabaseType mysql,
    serviceDiscoveryType eureka,
    serverPort 8081,
    buildTool maven,
    jhiPrefix book
  }
  entities Book, Chapter
}

entity Book {
    name String required minlength(3),
    description TextBlob required
}

entity Chapter {
  title String required,
  content TextBlob required,
}

relationship ManyToOne {
  Book{user(login)} to User,
  Chapter{book(name)} to Book
}

paginate Book with infinite-scroll
paginate Chapter with pagination

microservice Book, Chapter with book
```
This is a simple models: 
User has many Book
Book has many Chapter

The error message:
```
INFO! Using JHipster version installed globally
INFO! Executing import-jdl shop.jdl
INFO! The JDL is being parsed.
warn: An Entity name 'User' was used: 'User' is an entity created by default by JHipster. All relationships toward it will be kept but any attributes and relationships from it will be disregarded.
INFO! Found entities: Book, Chapter.
INFO! The JDL has been successfully parsed
INFO! Generating 2 applications.
This is an existing project, using the configuration from your .yo-rc.json file 
to re-generate the project...

This is an existing project, using the configuration from your .yo-rc.json file 
to re-generate the project...


Found the .jhipster/Book.json configuration file, entity can be automatically generated!


Found the .jhipster/Chapter.json configuration file, entity can be automatically generated!

     info changelogDate is missing in .jhipster/Book.json, using 20210324030351 as fallback
     info changelogDate is missing in .jhipster/Chapter.json, using 20210324030451 as fallback

Found the .jhipster/Book.json configuration file, entity can be automatically generated!

     info Creating changelog for entities Book,Chapter

Found the .jhipster/Chapter.json configuration file, entity can be automatically generated!

     info changelogDate is missing in .jhipster/Book.json, using 20210324030351 as fallback
     info changelogDate is missing in .jhipster/Chapter.json, using 20210324030451 as fallback
     info Creating changelog for entities Book,Chapter
ERROR! Error looking for otherEntity User
Error: Error looking for otherEntity User
    at /usr/lib/node_modules/generator-jhipster/generators/entity/index.js:530:19
    at Array.forEach (<anonymous>)
    at EntityGenerator.loadRelationships (/usr/lib/node_modules/generator-jhipster/generators/entity/index.js:526:36)
    at Object.<anonymous> (/usr/lib/node_modules/generator-jhipster/node_modules/yeoman-generator/lib/index.js:1009:25)
    at /usr/lib/node_modules/generator-jhipster/node_modules/run-async/index.js:49:25
    at new Promise (<anonymous>)
    at /usr/lib/node_modules/generator-jhipster/node_modules/run-async/index.js:26:19
    at runLoop.add.once.once (/usr/lib/node_modules/generator-jhipster/node_modules/yeoman-generator/lib/index.js:1010:11)
    at Immediate.<anonymous> (/usr/lib/node_modules/generator-jhipster/node_modules/grouped-queue/lib/subqueue.js:48:34)
    at processImmediate (internal/timers.js:461:21)
INFO! Generator app child process exited with code 1
ERROR! Error executing app --reproducible --no-force --with-entities --no-dry-run --no-whitespace --no-bail --no-skip-regenerate --no-skip-yo-resolve --from-jdl --no-skip-cache --no-skip-install --no-force-install --no-ask-answered --no-defaults --no-skip-git
Error: Error executing app --reproducible --no-force --with-entities --no-dry-run --no-whitespace --no-bail --no-skip-regenerate --no-skip-yo-resolve --from-jdl --no-skip-cache --no-skip-install --no-force-install --no-ask-answered --no-defaults --no-skip-git
    at ChildProcess.<anonymous> (/usr/lib/node_modules/generator-jhipster/cli/import-jdl.js:183:16)
```

**Comment by memetrusidovski** [comment]
Is there any plan to add support for JWT to microservices?
