### ISSUE TITLE
Module hooks are not working in 7.0.0

### ISSUE THREAD

**Issue by kaidohallik** [jhipster/generator-jhipster#14473]
##### **Overview of the issue**

JHipster can have module hooks in file `.jhipster/modules/jhi-hooks.json`.
A few months ago I updated some modules to JHipster version v7.0.0-beta.0 and module hooks were working then.
Now I updated those modules to JHipster version v7.0.0 (using current `main` branch) and module hooks are not working any more.

When module called by hook first time runs Yeoman memory file system `write` method then the error `'Cannot read property 'add' of undefined'` occurs in:
https://github.com/jhipster/generator-jhipster/blob/73397d93fd4eaea71299efd9ed7aa91a31b95924/generators/bootstrap/index.js#L118

Error is caught in:
https://github.com/jhipster/generator-jhipster/blob/73397d93fd4eaea71299efd9ed7aa91a31b95924/generators/needle-base.js#L27-L34

After that no more errors and debugging shows that changes are made in the memory file system. But files in the memory file system are not written into disk any more.

##### **Motivation for or Use Case**

If using JHipster modules then module hooks is very useful feature.
If modules are still supported then also hooks should be supported.

##### **Reproduce the error**

Migrate some JHipster module to support JHipster v7.0.0 and then run generator with hook to this module enabled.

##### **Related issues**

Seems to be regression from #14193

##### **JHipster Version(s)**

Current `main` branch.

##### **Browsers and Operating System**

Windows 10.

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by pascalgrimaud** [comment]
Adding a bounty as it's a bug and needed to be fixed at the same time than upgrading the module to v7

**Comment by vishal423** [comment]
I also encountered an issue while upgrading the `svelte` blueprint. I noticed an issue of `this.configOptions.sharedEntities.User` (defined inside `bootstrap` sub-generator) not being available in `server` sub-generator. For time being, I work around by copying the code from `bootstrap` sub-generator, but, would like to check if that's necessary or an issue in code over here.

**Comment by mshima** [comment]
@kaidohallik is there a way to reproduce the problem?
Are you using `jhipster run` instead of `yo`?

**Comment by kaidohallik** [comment]
@mshima I created draft PR for entity audit module: https://github.com/hipster-labs/generator-jhipster-entity-audit/pull/164

Steps to reproduce with this branch:
* generate application with JHipster
* link generator-jhipster-entity-audit from this branch
* link generator-jhipster-entity-audit in generated application
* run `yo jhipster-entity-audit` - all is working fine, entity audit support is added
* regenerate application (module is automatically used through generated hook): `jhipster --force`

Last step produces error:
```
ERROR! Cannot read property 'add' of undefined
TypeError: Cannot read property 'add' of undefined
    at module.exports._queueCommit (C:\projects\kaido-github\generator-jhipster\generators\bootstrap\index.js:118:18)
    at Store.<anonymous> (C:\projects\kaido-github\generator-jhipster\generators\bootstrap\index.js:104:53)
    at Object.onceWrapper (events.js:422:26)
    at Store.emit (events.js:327:22)
    at Store.add (C:\projects\kaido-github\generator-jhipster\node_modules\mem-fs\index.js:40:10)
    at EditionInterface.module.exports [as write] (C:\projects\kaido-github\generator-jhipster\node_modules\mem-fs-editor\lib\actions\write.js:16:14)
    at EditionInterface.module.exports [as writeJSON] (C:\projects\kaido-github\generator-jhipster\node_modules\mem-fs-editor\lib\actions\write-json.js:8:15)
    at Storage._persist (C:\projects\kaido-github\generator-jhipster\node_modules\yeoman-generator\lib\util\storage.js:128:13)
    at Storage.set (C:\projects\kaido-github\generator-jhipster\node_modules\yeoman-generator\lib\util\storage.js:181:10)
    at module.exports.updateYeomanConfig (C:\projects\kaido-github\generator-jhipster-entity-audit\generators\app\index.js:166:21)
    at Object.<anonymous> (C:\projects\kaido-github\generator-jhipster\node_modules\yeoman-generator\lib\index.js:1009:25)
    at C:\projects\kaido-github\generator-jhipster\node_modules\run-async\index.js:49:25
    at new Promise (<anonymous>)
    at C:\projects\kaido-github\generator-jhipster\node_modules\run-async\index.js:26:19
    at runLoop.add.once.once (C:\projects\kaido-github\generator-jhipster\node_modules\yeoman-generator\lib\index.js:1010:11)
    at Immediate.<anonymous> (C:\projects\kaido-github\generator-jhipster\node_modules\grouped-queue\lib\subqueue.js:48:34)
```

**Comment by mshima** [comment]
@kaidohallik thanks for the example.
Let me know if there is any other problem.

**Comment by kaidohallik** [comment]
@mshima just tested and working fine, thanks a lot for fixing this so quickly!

**Comment by mshima** [comment]
@pascalgrimaud bounty claimed https://opencollective.com/generator-jhipster/expenses/41129

**Comment by pascalgrimaud** [comment]
@mshima : approved
