### ISSUE TITLE
shortMessage: 'Command failed with exit code 1: npm install'

### ISSUE THREAD

**Issue by EnziinSystem** [jhipster/generator-jhipster#14600]
My environment:
```
$ node -v
v14.16.0
$ npm -v
7.8.0
JHipster v7.0.1
```
Create an application:
```
$ jhipster

? Which *type* of application would you like to create? Monolithic application (recommended for simple projects)
? What is the base name of your application? book
? Do you want to make it reactive with Spring WebFlux? No
? What is your default Java package name? com.enziin.book
? Which *type* of authentication would you like to use? JWT authentication (stateless, with a token)
? Which *type* of database would you like to use? SQL (H2, PostgreSQL, MySQL, MariaDB, Oracle, MSSQL)
? Which *production* database would you like to use? MySQL
? Which *development* database would you like to use? H2 with disk-based persistence
? Which cache do you want to use? (Spring cache abstraction) Ehcache (local cache, for a single node)
? Do you want to use Hibernate 2nd level cache? Yes
? Would you like to use Maven or Gradle for building the backend? Maven
? Do you want to use the JHipster Registry to configure, monitor and scale your application? No
? Which other technologies would you like to use? Elasticsearch as search engine, WebSockets using Spring Websocket, Apache Kafka as asynchronous messages broker, API first development using
 OpenAPI-generator
? Which *Framework* would you like to use for the client? React
? Do you want to generate the admin UI? Yes
? Would you like to use a Bootswatch theme (https://bootswatch.com/)? Default JHipster
? Would you like to enable internationalization support? Yes
? Please choose the native language of the application English
? Please choose additional languages to install Vietnamese
? Besides JUnit and Jest, which testing frameworks would you like to use? Cypress
? Would you like to install other generators from the JHipster Marketplace? No

KeyStore 'src/main/resources/config/tls/keystore.p12' generated successfully.

   create .prettierrc
   create .prettierignore
   create .gitattributes
   create .editorconfig
   create .gitignore
   create sonar-project.properties
...
Running npm install for you to install the required dependencies.
npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://github.com/npm/cli/issues>

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/kevin/.npm/_logs/2021-04-07T03_41_37_926Z-debug.log
ERROR! Command failed with exit code 1: npm install
Error: Command failed with exit code 1: npm install
    at makeError (/usr/lib/node_modules/generator-jhipster/node_modules/yeoman-environment/node_modules/execa/lib/error.js:59:11)
    at handlePromise (/usr/lib/node_modules/generator-jhipster/node_modules/yeoman-environment/node_modules/execa/index.js:114:26)
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  shortMessage: 'Command failed with exit code 1: npm install',
  command: 'npm install',
  exitCode: 1,
  signal: undefined,
  signalDescription: undefined,
  stdout: undefined,
  stderr: undefined,
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}
```

**Comment by mraible** [comment]
If there was a `.yo-rc.json` file generated, can you please include it in your description? Also, what OS are you running?

**Comment by mraible** [comment]
Closing due to lack of response.
