### ISSUE TITLE
Micrometer 1.6.x doesn't support the Prometheus client 0.10.x 

### ISSUE THREAD

**Issue by mehmetcuneyit** [jhipster/generator-jhipster#14620]
##### **Overview of the issue**
Microservices depend , (created with Jhipster 7.0.1)
- package: io.micrometer.micrometer-registry-prometheus version: 1.6.5
- package: io.prometheus.simpleclient version: 0.10.0

Micrometer 1.6.x (latest) doesn't support the Prometheus client 0.10.x and it causes a runtime error when using Spring Batch 4.3.2 with a simple job configuration 

##### **Motivation for or Use Case**

The batch jobs are never executed due to the error

##### **Reproduce the error**

1. Create a microservice with Jhipster 7.0.1
2. Add spring-boot-starter-batch package

```
<dependency>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-batch</artifactId>
</dependency>
```

3. Create a sample entity 
4. Create ItemReader, ItemProcessor, ItemWriter with spring batch job configuration 
5. Create liquibase changeset by adding the sqlFile https://stackoverflow.com/a/58854924
6. Run ./mvnw
7. The jobs don't run 
```
2021-04-09 04:25:14.299 ERROR 76876 --- [er-scheduling-1] o.s.s.s.TaskUtils$LoggingErrorHandler    : Unexpected error occurred in scheduled task

java.lang.NoSuchFieldError: UNTYPED
        at io.micrometer.prometheus.MicrometerCollector.describe(MicrometerCollector.java:100)
        at io.prometheus.client.CollectorRegistry.collectorNames(CollectorRegistry.java:98)
        at io.prometheus.client.CollectorRegistry.register(CollectorRegistry.java:50)
        at io.prometheus.client.Collector.register(Collector.java:175)
        at io.micrometer.prometheus.PrometheusMeterRegistry.lambda$applyToCollector$16(PrometheusMeterRegistry.java:412)
        at java.base/java.util.concurrent.ConcurrentHashMap.compute(ConcurrentHashMap.java:1947)
        at io.micrometer.prometheus.PrometheusMeterRegistry.applyToCollector(PrometheusMeterRegistry.java:408)
        at io.micrometer.prometheus.PrometheusMeterRegistry.newLongTaskTimer(PrometheusMeterRegistry.java:221)
        at io.micrometer.core.instrument.MeterRegistry$More.lambda$longTaskTimer$0(MeterRegistry.java:878)
        at io.micrometer.core.instrument.MeterRegistry.getOrCreateMeter(MeterRegistry.java:614)
        at io.micrometer.core.instrument.MeterRegistry.registerMeterIfNecessary(MeterRegistry.java:568)
        at io.micrometer.core.instrument.MeterRegistry.access$600(MeterRegistry.java:77)
        at io.micrometer.core.instrument.MeterRegistry$More.longTaskTimer(MeterRegistry.java:876)
        at io.micrometer.core.instrument.LongTaskTimer$Builder.register(LongTaskTimer.java:407)
        at io.micrometer.core.instrument.composite.CompositeLongTaskTimer.registerNewMeter(CompositeLongTaskTimer.java:98)
        at io.micrometer.core.instrument.composite.CompositeLongTaskTimer.registerNewMeter(CompositeLongTaskTimer.java:30)
        at io.micrometer.core.instrument.composite.AbstractCompositeMeter.add(AbstractCompositeMeter.java:66)
        at java.base/java.lang.Iterable.forEach(Iterable.java:75)
        at java.base/java.util.Collections$SetFromMap.forEach(Collections.java:5581)
        at io.micrometer.core.instrument.composite.CompositeMeterRegistry.lambda$new$0(CompositeMeterRegistry.java:65)
        at io.micrometer.core.instrument.composite.CompositeMeterRegistry.lock(CompositeMeterRegistry.java:184)
        at io.micrometer.core.instrument.composite.CompositeMeterRegistry.lambda$new$1(CompositeMeterRegistry.java:65)
        at io.micrometer.core.instrument.MeterRegistry.getOrCreateMeter(MeterRegistry.java:624)
        at io.micrometer.core.instrument.MeterRegistry.registerMeterIfNecessary(MeterRegistry.java:568)
        at io.micrometer.core.instrument.MeterRegistry.access$600(MeterRegistry.java:77)
        at io.micrometer.core.instrument.MeterRegistry$More.longTaskTimer(MeterRegistry.java:876)
        at io.micrometer.core.instrument.LongTaskTimer$Builder.register(LongTaskTimer.java:407)
        at org.springframework.batch.core.metrics.BatchMetrics.createLongTaskTimer(BatchMetrics.java:88)
        at org.springframework.batch.core.job.AbstractJob.execute(AbstractJob.java:304)
        at org.springframework.batch.core.launch.support.SimpleJobLauncher$1.run(SimpleJobLauncher.java:149)
        at org.springframework.core.task.SyncTaskExecutor.execute(SyncTaskExecutor.java:50)
        at org.springframework.batch.core.launch.support.SimpleJobLauncher.run(SimpleJobLauncher.java:140)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:344)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:198)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
        at org.springframework.batch.core.configuration.annotation.SimpleBatchConfiguration$PassthruAdvice.invoke(SimpleBatchConfiguration.java:128)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:215)
        at com.sun.proxy.$Proxy225.run(Unknown Source)
        at com.vendorlytic.tracker.config.BatchConfiguration.run(BatchConfiguration.java:100)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)

```
##### **Related issues**

Here is the issue from the Micrometer repo, and the explanation https://github.com/micrometer-metrics/micrometer/issues/2555

##### **Suggest a Fix**

Explicitly add the Promethous client with version 0.9.0  
```
<dependency>
    <groupId>io.prometheus</groupId>
     <artifactId>simpleclient</artifactId>
     <version>0.9.0</version>
</dependency>
```

##### **JHipster Version(s)**

Jhipster 7.0.1

##### **Browsers and Operating System**
Linux 5.4.0-60

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by DanielFran** [comment]
@mehmetcuneyit Thanks for sharing the issue detail.
I will rollback to previous 0.9.0 version and update it only with next 1.7 micrometer version.

Until we release next version, you can exclude and add manually the correct dependency.
