### ISSUE TITLE
azure-app-service missing location argument for app-insights

### ISSUE THREAD

**Issue by mcleandaniel** [jhipster/generator-jhipster#14863]
##### **Overview of the issue**

Azure Application Insights instance does not exist, creating it...
Error: Command failed: az monitor app-insights component create --app blog-insights --resource-group jhipster
ERROR: the following arguments are required: --location/-l

TRY THIS:
az monitor app-insights component create --app demoApp --location westus2 --kind web -g demoRg --application-type web --retention-time 120
Create a component with kind web and location.

https://aka.ms/cli_ref
Read more about the command in reference docs

    at ChildProcess.exithandler (child_process.js:308:12)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1048:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5) {
  killed: false,
  code: 2,
  signal: null,
  cmd: 'az monitor app-insights component create --app blog-insights --resource-group jhipster'
}
/home/HOME/workspace/jhipster7-demo/node_modules/generator-jhipster/generators/generator-base.js:1787
    throw new Error(`${msg}`);
    ^

Error: Could not create the Azure Application Insights instance
    at module.exports.error (/home/HOME/workspace/jhipster7-demo/node_modules/generator-jhipster/generators/generator-base.js:1787:11)
    at /home/HOME/workspace/jhipster7-demo/node_modules/generator-jhipster/generators/azure-app-service/index.js:429:26
    at ChildProcess.exithandler (child_process.js:315:5)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1048:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)

##### **Suggest a Fix**

Add a location prompt to configuration

##### **JHipster Version(s)**

7.0.1

##### **Browsers and Operating System**

- [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by jdubois** [comment]
Thanks @atomfrede ! I will indeed have a look, but for me the future for deploying to Azure is https://nubesgen.com/ and I believe I will deprecate this sub-generator at some point.

**Comment by jdubois** [comment]
Ah wrong idea, we only recommend this, and don't force it. OK, let's add a new prompt.
