### ISSUE TITLE
Correct 'npm test' in the generator project

### ISSUE THREAD

**Issue by jdubois** [jhipster/generator-jhipster#1509]
When running 'npm test' on the generator-jhipster project, the tests are OK, but there are strange errors being thrown.

**Comment by deepu105** [comment]
Below is what I get, are you seeing the same?

```
PS D:\projects\git\generator-jhipster> npm test

> generator-jhipster@2.11.0 test D:\projects\git\generator-jhipster
> mocha --reporter spec

child_process: customFds option is deprecated, use stdio instead.


  jhipster generator

 _     _   ___   __  _____  ____  ___       __  _____   __    __    _
| |_| | | | |_) ( (`  | |  | |_  | |_)     ( (`  | |   / /\  / /`  | |_/
|_| | |_| |_|   _)_)  |_|  |_|__ |_| \     _)_)  |_|  /_/--\ \_\_, |_| \
                             ____  ___   ___
                            | |_  / / \ | |_)
                            |_|   \_\_/ |_| \
              _    __    _       __        ___   ____  _      __
             | |  / /\  \ \  /  / /\      | | \ | |_  \ \  / ( (`
           \_|_| /_/--\  \_\/  /_/--\     |_|_/ |_|__  \_\/  _)_)


Welcome to the JHipster Generator v2.11.0

   create package.json
   create bower.json
   create README.md
   create .bowerrc
   create .gitignore
   create .gitattributes
   create Gruntfile.js
   create pom.xml
   create src\main\resources\banner.txt
   create src\main\resources\.h2.server.properties
   create src\main\resources\templates\error.html
   create src\main\resources\logback.xml
   create src\main\resources\config\application.yml
   create src\main\resources\config\application-dev.yml
   create src\main\resources\config\application-prod.yml
   create src\main\resources\config\liquibase\changelog\00000000000000_initial_schema.xml
   create src\main\resources\config\liquibase\master.xml
   create src\main\resources\config\liquibase\users.csv
   create src\main\resources\config\liquibase\authorities.csv
   create src\main\resources\config\liquibase\users_authorities.csv
   create src\main\resources\mails\activationEmail.html
   create src\main\resources\mails\passwordResetEmail.html
   create src\main\java\com\mycompany\myapp\Application.java
   create src\main\java\com\mycompany\myapp\ApplicationWebXml.java
   create src\main\java\com\mycompany\myapp\aop\logging\LoggingAspect.java
   create src\main\java\com\mycompany\myapp\config\apidoc\package-info.java
   create src\main\java\com\mycompany\myapp\config\apidoc\SwaggerConfiguration.java
   create src\main\java\com\mycompany\myapp\async\package-info.java
   create src\main\java\com\mycompany\myapp\async\ExceptionHandlingAsyncTaskExecutor.java
   create src\main\java\com\mycompany\myapp\config\package-info.java
   create src\main\java\com\mycompany\myapp\config\AsyncConfiguration.java
   create src\main\java\com\mycompany\myapp\config\CacheConfiguration.java
   create src\main\java\com\mycompany\myapp\config\Constants.java
   create src\main\java\com\mycompany\myapp\config\CloudDatabaseConfiguration.java
   create src\main\java\com\mycompany\myapp\config\DatabaseConfiguration.java
   create src\main\java\com\mycompany\myapp\config\JacksonConfiguration.java
    1) creates expected files
   create src\main\java\com\mycompany\myapp\config\LocaleConfiguration.java
   create src\main\java\com\mycompany\myapp\config\LoggingAspectConfiguration.java
   create src\main\java\com\mycompany\myapp\config\MailConfiguration.java
   create src\main\java\com\mycompany\myapp\config\MetricsConfiguration.java
   create src\main\java\com\mycompany\myapp\config\SecurityConfiguration.java
   create src\main\java\com\mycompany\myapp\config\ThymeleafConfiguration.java
   create src\main\java\com\mycompany\myapp\config\WebConfigurer.java
   create src\main\java\com\mycompany\myapp\config\audit\package-info.java
   create src\main\java\com\mycompany\myapp\config\audit\AuditEventConverter.java
   create src\main\java\com\mycompany\myapp\config\locale\package-info.java
identical src\main\java\com\mycompany\myapp\config\locale\AngularCookieLocaleResolver.java
identical src\main\java\com\mycompany\myapp\config\metrics\package-info.java
identical src\main\java\com\mycompany\myapp\config\metrics\DatabaseHealthIndicator.java
identical src\main\java\com\mycompany\myapp\config\metrics\JavaMailHealthIndicator.java
identical src\main\java\com\mycompany\myapp\config\metrics\JHipsterHealthIndicatorConfiguration.java
identical src\main\java\com\mycompany\myapp\domain\package-info.java
identical src\main\java\com\mycompany\myapp\domain\AbstractAuditingEntity.java
identical src\main\java\com\mycompany\myapp\domain\Authority.java
identical src\main\java\com\mycompany\myapp\domain\PersistentAuditEvent.java
identical src\main\java\com\mycompany\myapp\domain\PersistentToken.java
identical src\main\java\com\mycompany\myapp\domain\User.java
identical src\main\java\com\mycompany\myapp\domain\util\CustomLocalDateSerializer.java
identical src\main\java\com\mycompany\myapp\domain\util\CustomDateTimeSerializer.java
identical src\main\java\com\mycompany\myapp\domain\util\CustomDateTimeDeserializer.java
identical src\main\java\com\mycompany\myapp\domain\util\ISO8601LocalDateDeserializer.java
identical src\main\java\com\mycompany\myapp\repository\package-info.java
identical src\main\java\com\mycompany\myapp\repository\AuthorityRepository.java
identical src\main\java\com\mycompany\myapp\repository\CustomAuditEventRepository.java
identical src\main\java\com\mycompany\myapp\repository\PersistenceAuditEventRepository.java
identical src\main\java\com\mycompany\myapp\repository\UserRepository.java
identical src\main\java\com\mycompany\myapp\repository\PersistentTokenRepository.java
identical src\main\java\com\mycompany\myapp\security\package-info.java
identical src\main\java\com\mycompany\myapp\security\AjaxAuthenticationFailureHandler.java
identical src\main\java\com\mycompany\myapp\security\AjaxAuthenticationSuccessHandler.java
identical src\main\java\com\mycompany\myapp\security\AjaxLogoutSuccessHandler.java
identical src\main\java\com\mycompany\myapp\security\AuthoritiesConstants.java
identical src\main\java\com\mycompany\myapp\security\CustomPersistentRememberMeServices.java
identical src\main\java\com\mycompany\myapp\security\Http401UnauthorizedEntryPoint.java
identical src\main\java\com\mycompany\myapp\security\SecurityUtils.java
identical src\main\java\com\mycompany\myapp\security\SpringSecurityAuditorAware.java
identical src\main\java\com\mycompany\myapp\security\UserDetailsService.java
identical src\main\java\com\mycompany\myapp\security\UserNotActivatedException.java
identical src\main\java\com\mycompany\myapp\service\package-info.java
identical src\main\java\com\mycompany\myapp\service\AuditEventService.java
identical src\main\java\com\mycompany\myapp\service\UserService.java
identical src\main\java\com\mycompany\myapp\service\MailService.java
identical src\main\java\com\mycompany\myapp\service\util\RandomUtil.java
identical src\main\java\com\mycompany\myapp\web\filter\package-info.java
identical src\main\java\com\mycompany\myapp\web\filter\CachingHttpHeadersFilter.java
identical src\main\java\com\mycompany\myapp\web\filter\StaticResourcesProductionFilter.java
identical src\main\java\com\mycompany\myapp\web\filter\CsrfCookieGeneratorFilter.java
identical src\main\java\com\mycompany\myapp\web\filter\gzip\package-info.java
identical src\main\java\com\mycompany\myapp\web\filter\gzip\GzipResponseHeadersNotModifiableException.java
identical src\main\java\com\mycompany\myapp\web\filter\gzip\GZipResponseUtil.java
identical src\main\java\com\mycompany\myapp\web\filter\gzip\GZipServletFilter.java
identical src\main\java\com\mycompany\myapp\web\filter\gzip\GZipServletOutputStream.java
identical src\main\java\com\mycompany\myapp\web\filter\gzip\GZipServletResponseWrapper.java
identical src\main\java\com\mycompany\myapp\web\propertyeditors\package-info.java
identical src\main\java\com\mycompany\myapp\web\propertyeditors\LocaleDateTimeEditor.java
identical src\main\java\com\mycompany\myapp\web\rest\dto\package-info.java
identical src\main\java\com\mycompany\myapp\web\rest\dto\LoggerDTO.java
identical src\main\java\com\mycompany\myapp\web\rest\dto\UserDTO.java
identical src\main\java\com\mycompany\myapp\web\rest\util\PaginationUtil.java
identical src\main\java\com\mycompany\myapp\web\rest\package-info.java
identical src\main\java\com\mycompany\myapp\web\rest\AccountResource.java
identical src\main\java\com\mycompany\myapp\web\rest\AuditResource.java
identical src\main\java\com\mycompany\myapp\web\rest\LogsResource.java
    2) "before each" hook
identical src\main\java\com\mycompany\myapp\web\rest\UserResource.java
identical src\test\java\com\mycompany\myapp\security\SecurityUtilsTest.java
identical src\test\java\com\mycompany\myapp\service\UserServiceTest.java

  jhipster generator
identical src\test\java\com\mycompany\myapp\web\rest\AccountResourceTest.java
identical src\test\java\com\mycompany\myapp\web\rest\TestUtil.java
identical src\test\java\com\mycompany\myapp\web\rest\UserResourceTest.java
    √ can be imported without blowing up
 conflict src\test\resources\config\application.yml
? Overwrite src\test\resources\config\application.yml? (Ynaxdh)

  1 passing (4s)
  2 failing

  1) jhipster generator creates expected files:
     Error: timeout of 2000ms exceeded
      at null.<anonymous> (D:\Projects\GIT\generator-jhipster\node_modules\mocha\lib\runnable.js:158:19)
      at Timer.listOnTimeout (timers.js:110:15)

  2) jhipster generator "before each" hook:
     Error: EBUSY, rmdir 'D:\projects\git\generator-jhipster\test\temp'
      at Error (native)





npm ERR! Test failed.  See above for more details.
PS D:\projects\git\generator-jhipster>
```

**Comment by jdubois** [comment]
There's also [this error](https://travis-ci.org/jhipster/generator-jhipster/builds/63838354#L516) we can see on Travis CI

**Comment by jdubois** [comment]
Fixed

**Comment by khouloudkhadija** [comment]
Sorry I don't if this is the right place to ask this question but I don't understand "npm test" what did this command do exactly ? Could you please explain

**Comment by gmarziou** [comment]
You're correct, it's not the right place. This command runs tests on the generator itself, it's useful only if you plan to contribute to the generator project.

**Comment by khouloudkhadija** [comment]
That is exactly what I'm doing, I'm trying to modify  the source code of the jhipster generator and  when I run this command I have different errors (npm ERR! Test failed. See above for more details.) and I don't understand the cause of these errors specially that I didn't make a big modification, I just modified a html file to test it. (Sorry but where can I ask and get more information about the subject since this is not the right place to do it )

**Comment by gmarziou** [comment]
First thing it to check that the test passed before you make any change, if they did not pass then maybe it's temporary and we're working on it or your node environment is broken. 
Ask your question  on gitter or stackoverflow as explained here: http://jhipster.github.io/help/
