### ISSUE TITLE
yo jhipster doesn't work on second app -- lubuntu in virtualbox

### ISSUE THREAD

**Issue by dereklin** [jhipster/generator-jhipster#1518]
I just found jhipster today and trying it out on my lubuntu box on virtualbox.  At first try, I mkdir jhipster and yo jhipster, and chose postgresql as my development database.  The installation seemed ok.  But then when I ran the app, there was a database login problem.  I couldn't find documentation on how to set up postgressql...

So I deleted the app.  And then I mkdir myapp and cd myapp.  Then I yo jhipster.  This time, the installation is running on my home directory, and the installation failed.

I then mkdir otherfolder and try yo jhipster on otherfolder, the same thing happened.  The installation was running on my home directory.  It seems like it's "resuming" the previous installation.

What can I do to start fresh?

P.S.:
I tried yo uninstall -g generator-jhipster and install again

Here is the latest error:

module.js:338
    throw err;
          ^
Error: Cannot find module 'isarray'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/derek/node_modules/gulp-util/node_modules/multipipe/node_modules/duplexer2/node_modules/readable-stream/lib/_stream_readable.js:25:15)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)

**Comment by dereklin** [comment]
I deleted some hidden files and it fixed the particular build problem.
