### ISSUE TITLE
Gateway does not compile when no database is selected

### ISSUE THREAD

**Issue by hundredplusfive** [jhipster/generator-jhipster#15507]
##### **Overview of the issue**

I am trying to create a API gateway application based off Spring Cloud API gateway. However, upon running the command "mvnw", the build succeeded with the following compilation error.

**Error thrown**
```
2021-06-29 17:40:42.157  WARN 22184 --- [  restartedMain] onfigReactiveWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'gatewaySwaggerResourcesProvider' defined in file [D:\projects\gatewayapp\target\classes\com\gwa\config\apidocs\GatewaySwaggerResourcesProvider.class]: Unsatisfied dependency expressed through constructor parameter 1; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'inMemorySwaggerResourcesProvider' defined in URL [jar:file:/C:/Users/onezerofive/.m2/repository/io/springfox/springfox-swagger-common/3.0.0/springfox-swagger-common-3.0.0.jar!/springfox/documentation/swagger/web/InMemorySwaggerResourcesProvider.class]: Bean instantiation via constructor failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [springfox.documentation.swagger.web.InMemorySwaggerResourcesProvider]: Constructor threw exception; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'openAPISpringfoxApiDocket' defined in class path resource [tech/jhipster/config/apidoc/SpringfoxAutoConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [springfox.documentation.spring.web.plugins.Docket]: Factory method 'openAPISpringfoxApiDocket' threw exception; nested exception is java.lang.NoClassDefFoundError: org/springframework/data/domain/Pageable
2021-06-29 17:40:42.223 ERROR 22184 --- [  restartedMain] o.s.boot.SpringApplication               : Application run failed

org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'gatewaySwaggerResourcesProvider' defined in file [D:\projects\gatewayapp\target\classes\com\gwa\config\apidocs\GatewaySwaggerResourcesProvider.class]: Unsatisfied dependency expressed through constructor parameter 1; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'inMemorySwaggerResourcesProvider' defined in URL [jar:file:/C:/Users/onezerofive/.m2/repository/io/springfox/springfox-swagger-common/3.0.0/springfox-swagger-common-3.0.0.jar!/springfox/documentation/swagger/web/InMemorySwaggerResourcesProvider.class]: Bean instantiation via constructor failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [springfox.documentation.swagger.web.InMemorySwaggerResourcesProvider]: Constructor threw exception; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'openAPISpringfoxApiDocket' defined in class path resource [tech/jhipster/config/apidoc/SpringfoxAutoConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [springfox.documentation.spring.web.plugins.Docket]: Factory method 'openAPISpringfoxApiDocket' threw exception; nested exception is java.lang.NoClassDefFoundError: org/springframework/data/domain/Pageable
        at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:800)
        at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:229)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1354)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1204)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:564)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:524)
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:944)
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:918)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583)
        at org.springframework.boot.web.reactive.context.ReactiveWebServerApplicationContext.refresh(ReactiveWebServerApplicationContext.java:63)
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:771)
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:763)
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:438)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:339)
        at com.GatewayappApp.main(GatewayappApp.java:68)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.springframework.boot.devtools.restart.RestartLauncher.run(RestartLauncher.java:49)
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'inMemorySwaggerResourcesProvider' defined in URL [jar:file:/C:/Users/onezerofive/.m2/repository/io/springfox/springfox-swagger-common/3.0.0/springfox-swagger-common-3.0.0.jar!/springfox/documentation/swagger/web/InMemorySwaggerResourcesProvider.class]: Bean instantiation via constructor failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [springfox.documentation.swagger.web.InMemorySwaggerResourcesProvider]: Constructor threw exception; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'openAPISpringfoxApiDocket' defined in class path resource [tech/jhipster/config/apidoc/SpringfoxAutoConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [springfox.documentation.spring.web.plugins.Docket]: Factory method 'openAPISpringfoxApiDocket' threw exception; nested exception is java.lang.NoClassDefFoundError: org/springframework/data/domain/Pageable
        at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:315)
        at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:296)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1354)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1204)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:564)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:524)
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
        at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1380)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1300)
        at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:887)
        at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:791)
        ... 23 common frames omitted
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [springfox.documentation.swagger.web.InMemorySwaggerResourcesProvider]: Constructor threw exception; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'openAPISpringfoxApiDocket' defined in class path resource [tech/jhipster/config/apidoc/SpringfoxAutoConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [springfox.documentation.spring.web.plugins.Docket]: Factory method 'openAPISpringfoxApiDocket' threw exception; nested exception is java.lang.NoClassDefFoundError: org/springframework/data/domain/Pageable
        at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:225)
        at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:117)
        at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:311)
        ... 37 common frames omitted
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'openAPISpringfoxApiDocket' defined in class path resource [tech/jhipster/config/apidoc/SpringfoxAutoConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [springfox.documentation.spring.web.plugins.Docket]: Factory method 'openAPISpringfoxApiDocket' threw exception; nested exception is java.lang.NoClassDefFoundError: org/springframework/data/domain/Pageable
        at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:658)
        at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:638)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1334)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1177)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:564)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:524)
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
        at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1154)
        at org.springframework.plugin.core.support.AbstractTypeAwareSupport$BeansOfTypeTargetSource.lambda$getBeansOfTypeExcept$1(AbstractTypeAwareSupport.java:224)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
        at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
        at org.springframework.plugin.core.support.AbstractTypeAwareSupport$BeansOfTypeTargetSource.getBeansOfTypeExcept(AbstractTypeAwareSupport.java:225)
        at org.springframework.plugin.core.support.AbstractTypeAwareSupport$BeansOfTypeTargetSource.getTarget(AbstractTypeAwareSupport.java:204)
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:195)
        at com.sun.proxy.$Proxy137.stream(Unknown Source)
        at org.springframework.plugin.core.PluginRegistrySupport.initialize(PluginRegistrySupport.java:78)
        at org.springframework.plugin.core.OrderAwarePluginRegistry.initialize(OrderAwarePluginRegistry.java:216)
        at org.springframework.plugin.core.PluginRegistrySupport.getPlugins(PluginRegistrySupport.java:60)
        at org.springframework.plugin.core.SimplePluginRegistry.getPlugins(SimplePluginRegistry.java:100)
        at springfox.documentation.spring.web.plugins.DocumentationPluginsManager.documentationPlugins(DocumentationPluginsManager.java:105)
        at springfox.documentation.swagger.web.InMemorySwaggerResourcesProvider.<init>(InMemorySwaggerResourcesProvider.java:62)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
        at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:212)
        ... 39 common frames omitted
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [springfox.documentation.spring.web.plugins.Docket]: Factory method 'openAPISpringfoxApiDocket' threw exception; nested exception is java.lang.NoClassDefFoundError: org/springframework/data/domain/Pageable
        at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185)
        at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:653)
        ... 73 common frames omitted
Caused by: java.lang.NoClassDefFoundError: org/springframework/data/domain/Pageable
        at tech.jhipster.config.apidoc.customizer.JHipsterSpringfoxCustomizer.customize(JHipsterSpringfoxCustomizer.java:94)
        at tech.jhipster.config.apidoc.SpringfoxAutoConfiguration.lambda$openAPISpringfoxApiDocket$0(SpringfoxAutoConfiguration.java:113)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
        at tech.jhipster.config.apidoc.SpringfoxAutoConfiguration.openAPISpringfoxApiDocket(SpringfoxAutoConfiguration.java:113)
        at tech.jhipster.config.apidoc.SpringfoxAutoConfiguration$$EnhancerBySpringCGLIB$$5a9fc64b.CGLIB$openAPISpringfoxApiDocket$3(<generated>)
        at tech.jhipster.config.apidoc.SpringfoxAutoConfiguration$$EnhancerBySpringCGLIB$$5a9fc64b$$FastClassBySpringCGLIB$$92e637e7.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:244)
        at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:331)
        at tech.jhipster.config.apidoc.SpringfoxAutoConfiguration$$EnhancerBySpringCGLIB$$5a9fc64b.openAPISpringfoxApiDocket(<generated>)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154)
        ... 74 common frames omitted
Caused by: java.lang.ClassNotFoundException: org.springframework.data.domain.Pageable
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        ... 88 common frames omitted
```

##### **Motivation for or Use Case**

The error states that it cannot find the CLASS file for "org.springframework.data.domain.Pageable". Which is indeed true, I couldn't find any JAR or CLASS following that pathname.

However, I checked it up online, it seems that this particular CLASS file is part of a JAR under "org.springframework.data.spring-data-commons". As a matter of fact, I have that JAR and within it contains the problematic CLASS file.

##### **Reproduce the error**

I followed [this](https://www.youtube.com/watch?v=oNagVFsfBqY) tutorial on setting up a Spring Cloud API gateway.

Files edited/created
1. Commented away these related lines in _WebConfigurer.java_ in ... src/main/java/com/gwa/config
... ReactivePageableHandlerMethodArgumentResolver
... ReactiveSortHandlerMethodArgumentResolver

*prior to step 1
This compilation issue came about 
`src/main/java/com/mycompany/myapp/config/WebConfigurer.java:[13,36] package org.springframework.data.web does not exist`

I looked into the WebConfigurer.java file, there were some comment pointing to a function mentioning "TODO: remove when this is supported in spring-boot"... thus, I commented away and the build progressed till the current juncture of this post

2. Created a _main.java_ file in ... src/main/java/com/gwa/web/rest
3. Edited the _application-dev.yml_ and _application-prd.yml_ in ... src/main/resources/config

##### **Related issues**

NA

##### **Suggest a Fix**

As highlighted by the "caused by". I believe the solution, is to modify the file that dictates the errored path and re-point to the correct dependency.

##### **JHipster Version(s)**

Currently using 7.1 but this issue occurred in 7.0.1 too.

##### **JHipster configuration**

**jhipster info**
INFO! Using JHipster version installed locally in current project's node_modules
Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
gatewayapp@0.0.1-SNAPSHOT D:\projects\gatewayapp
`-- (empty)

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "blueprints": [],
    "otherModules": [],
    "applicationType": "gateway",
    "baseName": "gatewayapp",
    "jhipsterVersion": "7.1.0",
    "skipClient": false,
    "skipServer": false,
    "skipUserManagement": true,
    "skipCheckLengthOfIdentifier": false,
    "skipFakeData": false,
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "testFrameworks": [],
    "pages": [],
    "creationTimestamp": 1623998011866,
    "serviceDiscoveryType": "eureka",
    "reactive": true,
    "authenticationType": "jwt",
    "packageName": "com.gwa",
    "serverPort": "8088",
    "cacheProvider": "no",
    "enableHibernateCache": false,
    "databaseType": "no",
    "buildTool": "maven",
    "serverSideOptions": [],
    "websocket": false,
    "searchEngine": false,
    "messageBroker": false,
    "enableSwaggerCodegen": false,
    "clientFramework": "angularX",
    "withAdminUi": true,
    "clientTheme": "none",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "packageFolder": "com/gwa",
    "jwtSecretKey": "YourJWTSecretKeyWasReplacedByThisMeaninglessTextByTheJHipsterInfoCommandForObviousSecurityReasons",
    "devDatabaseType": "no",
    "prodDatabaseType": "no",
    "clientPackageManager": "npm",
    "clientThemeVariant": "",
    "languages": ["en"],
    "devServerPort": 4200
  }
}

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

openjdk version "11.0.3" 2019-04-16
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.3+7)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.3+7, mixed mode)

node: v14.17.0

npm: 6.14.13

No change to package.json was detected. No package manager install will be executed.
Congratulations, JHipster execution is complete!
Sponsored with ❤️  by @oktadev.

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

NA

##### **Browsers and Operating System**

Browser: Chrome
Operating System: Windows 10

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by mraible** [comment]
If I use your `.yo-rc.json` to create a project, it fails to compile.

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project gatewayapp: Compilation failure: Compilation failure:
[ERROR] /Users/mraible/15507/src/main/java/com/gwa/config/WebConfigurer.java:[12,36] package org.springframework.data.web does not exist
[ERROR] /Users/mraible/15507/src/main/java/com/gwa/config/WebConfigurer.java:[13,36] package org.springframework.data.web does not exist
```

I believe this is caused by having no database:

```json
    "devDatabaseType": "no",
    "prodDatabaseType": "no",
```

If I change these to use PostgreSQL, there's a single compile error:

```
[ERROR] /Users/mraible/15507/src/main/java/com/gwa/web/rest/AccountResource.java:[67,43] cannot find symbol
[ERROR]   symbol:   variable Principal
[ERROR]   location: class com.gwa.web.rest.AccountResource
```

If I fix this, the test fails to compile:

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:testCompile (default-testCompile) on project gatewayapp: Compilation failure: Compilation failure:
[ERROR] /Users/mraible/15507/src/test/java/com/gwa/web/rest/AccountResourceIT.java:[50,9] cannot find symbol
[ERROR]   symbol:   variable webTestClient
[ERROR]   location: class com.gwa.web.rest.AccountResourceIT
[ERROR] /Users/mraible/15507/src/test/java/com/gwa/web/rest/AccountResourceIT.java:[63,9] cannot find symbol
[ERROR]   symbol:   variable webTestClient
[ERROR]   location: class com.gwa.web.rest.AccountResourceIT
```

If I fix that (by changing `webTestClient` to `accountWebTestClient`), it startups up just fine.

```
----------------------------------------------------------
	Application 'gatewayapp' is running! Access URLs:
	Local: 		http://localhost:8088/
	External: 	http://127.0.0.1:8088/
	Profile(s): 	[dev, api-docs]
----------------------------------------------------------
```

Since there are compilation issues, I tried the following .`yo-rc.json` with the latest code from the `main` branch.

```json
{
  "generator-jhipster": {
    "blueprints": [],
    "otherModules": [],
    "applicationType": "gateway",
    "baseName": "gatewayapp",
    "jhipsterVersion": "7.1.0",
    "skipClient": false,
    "skipServer": false,
    "skipUserManagement": true,
    "skipCheckLengthOfIdentifier": false,
    "skipFakeData": false,
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "testFrameworks": [],
    "pages": [],
    "creationTimestamp": 1623998011866,
    "serviceDiscoveryType": "eureka",
    "reactive": true,
    "authenticationType": "jwt",
    "packageName": "com.gwa",
    "serverPort": "8088",
    "cacheProvider": "no",
    "enableHibernateCache": false,
    "databaseType": "sql",
    "buildTool": "maven",
    "serverSideOptions": [],
    "websocket": false,
    "searchEngine": false,
    "messageBroker": false,
    "enableSwaggerCodegen": false,
    "clientFramework": "angularX",
    "withAdminUi": true,
    "clientTheme": "none",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "packageFolder": "com/gwa",
    "jwtSecretKey": "YourJWTSecretKeyWasReplacedByThisMeaninglessTextByTheJHipsterInfoCommandForObviousSecurityReasons",
    "devDatabaseType": "postgresql",
    "prodDatabaseType": "postgresql",
    "clientPackageManager": "npm",
    "clientThemeVariant": "",
    "languages": ["en"],
    "devServerPort": 4200
  }
}
```

This fails to compile too. :(

**Comment by mraible** [comment]
I'm going to change this issue's title to no database is failing. This seems to be confirmed by our daily builds. 

https://github.com/hipster-labs/jhipster-daily-builds/actions/runs/1122400940

**Comment by yuvarajsanjeevi** [comment]
I have fixed the issue. would like to raise the pull request. please give permission

**Comment by gmarziou** [comment]
@yuvarajsanjeevi you don't need any permission to submit a pull request. Have you read https://github.com/jhipster/generator-jhipster/blob/main/CONTRIBUTING.md
