### ISSUE TITLE
Gateway application docker-compose failing on M1 Processor

### ISSUE THREAD

**Issue by sang-w0o** [jhipster/generator-jhipster#15565]
##### **Overview of the issue**

- Tried to create a Gateway Application using JHipster, but got errors as shown below.
- Before I hit `docker-compose` command, below log was shown saying that application was generated successfully.

```
BUILD SUCCESSFUL in 2m 10s
2 actionable tasks: 2 executed
Application successfully committed to Git from /Users/sangwoo/Desktop/MSA_Example/gateway.

If you find JHipster useful consider sponsoring the project https://www.jhipster.tech/sponsors/

Server application generated successfully.

Run your Spring Boot application:
./gradlew

Client application generated successfully.

Start your Webpack development server with:
 npm start


> gateway@0.0.0 clean-www
> rimraf build/resources/main/static/app/{src,build/}

Congratulations, JHipster execution is complete!
Sponsored with ❤️  by @oktadev.
```

- After I hit `docker-compuse -f src/main/docker/jhipster-registry/yml up`, below stack trace was shown.

```
docker-compose -f src/main/docker/jhipster-registry.yml up
[+] Running 8/8
 ⠿ jhipster-registry Pulled                                                                                                            12.6s
   ⠿ 345e3491a907 Pull complete                                                                                                         4.2s
   ⠿ 57671312ef6f Pull complete                                                                                                         4.3s
   ⠿ 5e9250ddb7d0 Pull complete                                                                                                         4.3s
   ⠿ 592ec2d7c137 Pull complete                                                                                                         5.0s
   ⠿ 73231ab3afed Pull complete                                                                                                         7.3s
   ⠿ e3e28b75ac83 Pull complete                                                                                                         7.4s
   ⠿ e644c106180b Pull complete                                                                                                         8.2s
[+] Running 1/1
 ⠿ Container docker_jhipster-registry_1  Started                                                                                        3.1s
Attaching to jhipster-registry_1
jhipster-registry_1  | The JHipster Registry will start in 0s...
jhipster-registry_1  | Picked up _JAVA_OPTIONS: -Xmx512m -Xms256m
jhipster-registry_1  | 2021-07-05 12:07:18.442  WARN 12 --- [           main] s.c.a.AnnotationConfigApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'configurationPropertiesBeans' defined in class path resource [org/springframework/cloud/autoconfigure/ConfigurationPropertiesRebinderAutoConfiguration.class]: BeanPostProcessor before instantiation of bean failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.retry.annotation.RetryConfiguration': Initialization of bean failed; nested exception is org.springframework.cglib.core.CodeGenerationException: java.lang.ClassFormatError-->Illegal class name "java/lang/Class[]" in class file org/springframework/retry/annotation/RetryConfiguration$$FastClassBySpringCGLIB$$f40d30c0
jhipster-registry_1  | 2021-07-05 12:07:18.491 ERROR 12 --- [           main] o.s.boot.SpringApplication               : Application run failed
jhipster-registry_1  |
jhipster-registry_1  | org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'configurationPropertiesBeans' defined in class path resource [org/springframework/cloud/autoconfigure/ConfigurationPropertiesRebinderAutoConfiguration.class]: BeanPostProcessor before instantiation of bean failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.retry.annotation.RetryConfiguration': Initialization of bean failed; nested exception is org.springframework.cglib.core.CodeGenerationException: java.lang.ClassFormatError-->Illegal class name "java/lang/Class[]" in class file org/springframework/retry/annotation/RetryConfiguration$$FastClassBySpringCGLIB$$f40d30c0
jhipster-registry_1  | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:512)
jhipster-registry_1  | 	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323)
jhipster-registry_1  | 	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:226)
jhipster-registry_1  | 	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321)
jhipster-registry_1  | 	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:207)
jhipster-registry_1  | 	at org.springframework.context.support.PostProcessorRegistrationDelegate.registerBeanPostProcessors(PostProcessorRegistrationDelegate.java:241)
jhipster-registry_1  | 	at org.springframework.context.support.AbstractApplicationContext.registerBeanPostProcessors(AbstractApplicationContext.java:722)
jhipster-registry_1  | 	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:535)
jhipster-registry_1  | 	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:747)
jhipster-registry_1  | 	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397)
jhipster-registry_1  | 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315)
jhipster-registry_1  | 	at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:140)
jhipster-registry_1  | 	at org.springframework.cloud.bootstrap.BootstrapApplicationListener.bootstrapServiceContext(BootstrapApplicationListener.java:212)
jhipster-registry_1  | 	at org.springframework.cloud.bootstrap.BootstrapApplicationListener.onApplicationEvent(BootstrapApplicationListener.java:117)
jhipster-registry_1  | 	at org.springframework.cloud.bootstrap.BootstrapApplicationListener.onApplicationEvent(BootstrapApplicationListener.java:74)
jhipster-registry_1  | 	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)
jhipster-registry_1  | 	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)
jhipster-registry_1  | 	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
jhipster-registry_1  | 	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:127)
jhipster-registry_1  | 	at org.springframework.boot.context.event.EventPublishingRunListener.environmentPrepared(EventPublishingRunListener.java:76)
jhipster-registry_1  | 	at org.springframework.boot.SpringApplicationRunListeners.environmentPrepared(SpringApplicationRunListeners.java:53)
jhipster-registry_1  | 	at org.springframework.boot.SpringApplication.prepareEnvironment(SpringApplication.java:345)
jhipster-registry_1  | 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:308)
jhipster-registry_1  | 	at io.github.jhipster.registry.JHipsterRegistryApp.main(JHipsterRegistryApp.java:71)
jhipster-registry_1  | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
jhipster-registry_1  | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
jhipster-registry_1  | 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
jhipster-registry_1  | 	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
jhipster-registry_1  | 	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
jhipster-registry_1  | 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
jhipster-registry_1  | 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:51)
jhipster-registry_1  | 	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:52)
jhipster-registry_1  | Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.retry.annotation.RetryConfiguration': Initialization of bean failed; nested exception is org.springframework.cglib.core.CodeGenerationException: java.lang.ClassFormatError-->Illegal class name "java/lang/Class[]" in class file org/springframework/retry/annotation/RetryConfiguration$$FastClassBySpringCGLIB$$f40d30c0
jhipster-registry_1  | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:603)
jhipster-registry_1  | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:517)
jhipster-registry_1  | 	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323)
jhipster-registry_1  | 	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:226)
jhipster-registry_1  | 	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321)
jhipster-registry_1  | 	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:207)
jhipster-registry_1  | 	at org.springframework.aop.framework.autoproxy.BeanFactoryAdvisorRetrievalHelper.findAdvisorBeans(BeanFactoryAdvisorRetrievalHelper.java:91)
jhipster-registry_1  | 	at org.springframework.aop.framework.autoproxy.AbstractAdvisorAutoProxyCreator.findCandidateAdvisors(AbstractAdvisorAutoProxyCreator.java:109)
jhipster-registry_1  | 	at org.springframework.aop.aspectj.annotation.AnnotationAwareAspectJAutoProxyCreator.findCandidateAdvisors(AnnotationAwareAspectJAutoProxyCreator.java:92)
jhipster-registry_1  | 	at org.springframework.aop.aspectj.autoproxy.AspectJAwareAdvisorAutoProxyCreator.shouldSkip(AspectJAwareAdvisorAutoProxyCreator.java:101)
jhipster-registry_1  | 	at org.springframework.aop.framework.autoproxy.AbstractAutoProxyCreator.postProcessBeforeInstantiation(AbstractAutoProxyCreator.java:251)
jhipster-registry_1  | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInstantiation(AbstractAutowireCapableBeanFactory.java:1141)
jhipster-registry_1  | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.resolveBeforeInstantiation(AbstractAutowireCapableBeanFactory.java:1114)
jhipster-registry_1  | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:506)
jhipster-registry_1  | 	... 31 common frames omitted
jhipster-registry_1  | Caused by: org.springframework.cglib.core.CodeGenerationException: java.lang.ClassFormatError-->Illegal class name "java/lang/Class[]" in class file org/springframework/retry/annotation/RetryConfiguration$$FastClassBySpringCGLIB$$f40d30c0
jhipster-registry_1  | 	at org.springframework.cglib.core.ReflectUtils.defineClass(ReflectUtils.java:514)
jhipster-registry_1  | 	at org.springframework.cglib.core.AbstractClassGenerator.generate(AbstractClassGenerator.java:363)
jhipster-registry_1  | 	at org.springframework.cglib.core.AbstractClassGenerator$ClassLoaderData$3.apply(AbstractClassGenerator.java:110)
jhipster-registry_1  | 	at org.springframework.cglib.core.AbstractClassGenerator$ClassLoaderData$3.apply(AbstractClassGenerator.java:108)
jhipster-registry_1  | 	at org.springframework.cglib.core.internal.LoadingCache$2.call(LoadingCache.java:54)
jhipster-registry_1  | 	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
jhipster-registry_1  | 	at org.springframework.cglib.core.internal.LoadingCache.createEntry(LoadingCache.java:61)
jhipster-registry_1  | 	at org.springframework.cglib.core.internal.LoadingCache.get(LoadingCache.java:34)
jhipster-registry_1  | 	at org.springframework.cglib.core.AbstractClassGenerator$ClassLoaderData.get(AbstractClassGenerator.java:134)
jhipster-registry_1  | 	at org.springframework.cglib.core.AbstractClassGenerator.create(AbstractClassGenerator.java:319)
jhipster-registry_1  | 	at org.springframework.cglib.reflect.FastClass$Generator.create(FastClass.java:65)
jhipster-registry_1  | 	at org.springframework.cglib.proxy.MethodProxy.helper(MethodProxy.java:135)
jhipster-registry_1  | 	at org.springframework.cglib.proxy.MethodProxy.init(MethodProxy.java:76)
jhipster-registry_1  | 	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:242)
jhipster-registry_1  | 	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanFactoryAwareMethodInterceptor.intercept(ConfigurationClassEnhancer.java:249)
jhipster-registry_1  | 	at org.springframework.retry.annotation.RetryConfiguration$$EnhancerBySpringCGLIB$$a04ffc8f.setBeanFactory(<generated>)
jhipster-registry_1  | 	at org.springframework.context.annotation.ConfigurationClassPostProcessor$ImportAwareBeanPostProcessor.postProcessProperties(ConfigurationClassPostProcessor.java:448)
jhipster-registry_1  | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1422)
jhipster-registry_1  | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:594)
jhipster-registry_1  | 	... 44 common frames omitted
jhipster-registry_1  | Caused by: java.lang.ClassFormatError: Illegal class name "java/lang/Class[]" in class file org/springframework/retry/annotation/RetryConfiguration$$FastClassBySpringCGLIB$$f40d30c0
jhipster-registry_1  | 	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
jhipster-registry_1  | 	at java.base/java.lang.System$2.defineClass(Unknown Source)
jhipster-registry_1  | 	at java.base/java.lang.invoke.MethodHandles$Lookup.defineClass(Unknown Source)
jhipster-registry_1  | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
jhipster-registry_1  | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
jhipster-registry_1  | 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
jhipster-registry_1  | 	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
jhipster-registry_1  | 	at org.springframework.cglib.core.ReflectUtils.defineClass(ReflectUtils.java:509)
jhipster-registry_1  | 	... 62 common frames omitted
jhipster-registry_1  |
jhipster-registry_1  | 2021-07-05 12:07:18.498 ERROR 12 --- [           main] o.s.boot.SpringApplication               : Application run failed
jhipster-registry_1  |
jhipster-registry_1  | org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'configurationPropertiesBeans' defined in class path resource [org/springframework/cloud/autoconfigure/ConfigurationPropertiesRebinderAutoConfiguration.class]: BeanPostProcessor before instantiation of bean failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.retry.annotation.RetryConfiguration': Initialization of bean failed; nested exception is org.springframework.cglib.core.CodeGenerationException: java.lang.ClassFormatError-->Illegal class name "java/lang/Class[]" in class file org/springframework/retry/annotation/RetryConfiguration$$FastClassBySpringCGLIB$$f40d30c0
jhipster-registry_1  | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:512)
jhipster-registry_1  | 	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323)
jhipster-registry_1  | 	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:226)
jhipster-registry_1  | 	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321)
jhipster-registry_1  | 	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:207)
jhipster-registry_1  | 	at org.springframework.context.support.PostProcessorRegistrationDelegate.registerBeanPostProcessors(PostProcessorRegistrationDelegate.java:241)
jhipster-registry_1  | 	at org.springframework.context.support.AbstractApplicationContext.registerBeanPostProcessors(AbstractApplicationContext.java:722)
jhipster-registry_1  | 	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:535)
jhipster-registry_1  | 	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:747)
jhipster-registry_1  | 	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397)
jhipster-registry_1  | 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315)
jhipster-registry_1  | 	at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:140)
jhipster-registry_1  | 	at org.springframework.cloud.bootstrap.BootstrapApplicationListener.bootstrapServiceContext(BootstrapApplicationListener.java:212)
jhipster-registry_1  | 	at org.springframework.cloud.bootstrap.BootstrapApplicationListener.onApplicationEvent(BootstrapApplicationListener.java:117)
jhipster-registry_1  | 	at org.springframework.cloud.bootstrap.BootstrapApplicationListener.onApplicationEvent(BootstrapApplicationListener.java:74)
jhipster-registry_1  | 	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)
jhipster-registry_1  | 	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)
jhipster-registry_1  | 	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
jhipster-registry_1  | 	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:127)
jhipster-registry_1  | 	at org.springframework.boot.context.event.EventPublishingRunListener.environmentPrepared(EventPublishingRunListener.java:76)
jhipster-registry_1  | 	at org.springframework.boot.SpringApplicationRunListeners.environmentPrepared(SpringApplicationRunListeners.java:53)
jhipster-registry_1  | 	at org.springframework.boot.SpringApplication.prepareEnvironment(SpringApplication.java:345)
jhipster-registry_1  | 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:308)
jhipster-registry_1  | 	at io.github.jhipster.registry.JHipsterRegistryApp.main(JHipsterRegistryApp.java:71)
jhipster-registry_1  | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
jhipster-registry_1  | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
jhipster-registry_1  | 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
jhipster-registry_1  | 	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
jhipster-registry_1  | 	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
jhipster-registry_1  | 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
jhipster-registry_1  | 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:51)
jhipster-registry_1  | 	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:52)
jhipster-registry_1  | Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.retry.annotation.RetryConfiguration': Initialization of bean failed; nested exception is org.springframework.cglib.core.CodeGenerationException: java.lang.ClassFormatError-->Illegal class name "java/lang/Class[]" in class file org/springframework/retry/annotation/RetryConfiguration$$FastClassBySpringCGLIB$$f40d30c0
jhipster-registry_1  | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:603)
jhipster-registry_1  | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:517)
jhipster-registry_1  | 	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323)
jhipster-registry_1  | 	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:226)
jhipster-registry_1  | 	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321)
jhipster-registry_1  | 	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:207)
jhipster-registry_1  | 	at org.springframework.aop.framework.autoproxy.BeanFactoryAdvisorRetrievalHelper.findAdvisorBeans(BeanFactoryAdvisorRetrievalHelper.java:91)
jhipster-registry_1  | 	at org.springframework.aop.framework.autoproxy.AbstractAdvisorAutoProxyCreator.findCandidateAdvisors(AbstractAdvisorAutoProxyCreator.java:109)
jhipster-registry_1  | 	at org.springframework.aop.aspectj.annotation.AnnotationAwareAspectJAutoProxyCreator.findCandidateAdvisors(AnnotationAwareAspectJAutoProxyCreator.java:92)
jhipster-registry_1  | 	at org.springframework.aop.aspectj.autoproxy.AspectJAwareAdvisorAutoProxyCreator.shouldSkip(AspectJAwareAdvisorAutoProxyCreator.java:101)
jhipster-registry_1  | 	at org.springframework.aop.framework.autoproxy.AbstractAutoProxyCreator.postProcessBeforeInstantiation(AbstractAutoProxyCreator.java:251)
jhipster-registry_1  | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInstantiation(AbstractAutowireCapableBeanFactory.java:1141)
jhipster-registry_1  | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.resolveBeforeInstantiation(AbstractAutowireCapableBeanFactory.java:1114)
jhipster-registry_1  | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:506)
jhipster-registry_1  | 	... 31 common frames omitted
jhipster-registry_1  | Caused by: org.springframework.cglib.core.CodeGenerationException: java.lang.ClassFormatError-->Illegal class name "java/lang/Class[]" in class file org/springframework/retry/annotation/RetryConfiguration$$FastClassBySpringCGLIB$$f40d30c0
jhipster-registry_1  | 	at org.springframework.cglib.core.ReflectUtils.defineClass(ReflectUtils.java:514)
jhipster-registry_1  | 	at org.springframework.cglib.core.AbstractClassGenerator.generate(AbstractClassGenerator.java:363)
jhipster-registry_1  | 	at org.springframework.cglib.core.AbstractClassGenerator$ClassLoaderData$3.apply(AbstractClassGenerator.java:110)
jhipster-registry_1  | 	at org.springframework.cglib.core.AbstractClassGenerator$ClassLoaderData$3.apply(AbstractClassGenerator.java:108)
jhipster-registry_1  | 	at org.springframework.cglib.core.internal.LoadingCache$2.call(LoadingCache.java:54)
jhipster-registry_1  | 	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
jhipster-registry_1  | 	at org.springframework.cglib.core.internal.LoadingCache.createEntry(LoadingCache.java:61)
jhipster-registry_1  | 	at org.springframework.cglib.core.internal.LoadingCache.get(LoadingCache.java:34)
jhipster-registry_1  | 	at org.springframework.cglib.core.AbstractClassGenerator$ClassLoaderData.get(AbstractClassGenerator.java:134)
jhipster-registry_1  | 	at org.springframework.cglib.core.AbstractClassGenerator.create(AbstractClassGenerator.java:319)
jhipster-registry_1  | 	at org.springframework.cglib.reflect.FastClass$Generator.create(FastClass.java:65)
jhipster-registry_1  | 	at org.springframework.cglib.proxy.MethodProxy.helper(MethodProxy.java:135)
jhipster-registry_1  | 	at org.springframework.cglib.proxy.MethodProxy.init(MethodProxy.java:76)
jhipster-registry_1  | 	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:242)
jhipster-registry_1  | 	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanFactoryAwareMethodInterceptor.intercept(ConfigurationClassEnhancer.java:249)
jhipster-registry_1  | 	at org.springframework.retry.annotation.RetryConfiguration$$EnhancerBySpringCGLIB$$a04ffc8f.setBeanFactory(<generated>)
jhipster-registry_1  | 	at org.springframework.context.annotation.ConfigurationClassPostProcessor$ImportAwareBeanPostProcessor.postProcessProperties(ConfigurationClassPostProcessor.java:448)
jhipster-registry_1  | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1422)
jhipster-registry_1  | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:594)
jhipster-registry_1  | 	... 44 common frames omitted
jhipster-registry_1  | Caused by: java.lang.ClassFormatError: Illegal class name "java/lang/Class[]" in class file org/springframework/retry/annotation/RetryConfiguration$$FastClassBySpringCGLIB$$f40d30c0
jhipster-registry_1  | 	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
jhipster-registry_1  | 	at java.base/java.lang.System$2.defineClass(Unknown Source)
jhipster-registry_1  | 	at java.base/java.lang.invoke.MethodHandles$Lookup.defineClass(Unknown Source)
jhipster-registry_1  | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
jhipster-registry_1  | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
jhipster-registry_1  | 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
jhipster-registry_1  | 	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
jhipster-registry_1  | 	at org.springframework.cglib.core.ReflectUtils.defineClass(ReflectUtils.java:509)
jhipster-registry_1  | 	... 62 common frames omitted
jhipster-registry_1  |
jhipster-registry_1 exited with code 1
```

##### **Motivation for or Use Case**

- This is clearly a bug, because I did not modify a single file after the project was generated by JHipster.

##### **Reproduce the error**

- N/A (Trying to create Gateway application on M1 Processor?)

##### **JHipster Version(s)**

- JHipster v7.1.0
- generator-jhipster@7.1.0

##### **JHipster configuration**

- `jhipster info`

```
INFO! Using JHipster version installed locally in current project's node_modules
Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

gateway@0.0.0 /Users/sangwoo/Desktop/MSA_Example/gateway
└── generator-jhipster@7.1.0


##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**


<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "applicationType": "gateway",
    "baseName": "gateway",
    "jhipsterVersion": "7.1.0",
    "skipClient": false,
    "skipServer": false,
    "skipUserManagement": false,
    "skipCheckLengthOfIdentifier": false,
    "skipFakeData": false,
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "testFrameworks": [],
    "blueprints": [],
    "otherModules": [],
    "pages": [],
    "creationTimestamp": 1625486556132,
    "serviceDiscoveryType": "eureka",
    "reactive": true,
    "authenticationType": "jwt",
    "packageName": "com.sangwoo.gateway",
    "serverPort": "8080",
    "cacheProvider": "no",
    "enableHibernateCache": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Memory",
    "prodDatabaseType": "mariadb",
    "buildTool": "gradle",
    "serverSideOptions": [],
    "websocket": false,
    "searchEngine": false,
    "messageBroker": false,
    "enableSwaggerCodegen": false,
    "clientFramework": "vue",
    "withAdminUi": true,
    "clientTheme": "none",
    "enableTranslation": true,
    "nativeLanguage": "ko",
    "packageFolder": "com/sangwoo/gateway",
    "jwtSecretKey": "YourJWTSecretKeyWasReplacedByThisMeaninglessTextByTheJHipsterInfoCommandForObviousSecurityReasons",
    "devServerPort": 9060,
    "clientPackageManager": "npm",
    "clientThemeVariant": "",
    "languages": ["ko"]
  }
}

</pre>
</details>


##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>


##### **Environment and Tools**

openjdk version "1.8.0_282"
OpenJDK Runtime Environment (Zulu 8.52.0.23-CA-macos-aarch64) (build 1.8.0_282-b08)
OpenJDK 64-Bit Server VM (Zulu 8.52.0.23-CA-macos-aarch64) (build 25.282-b08, mixed mode)

git version 2.24.3 (Apple Git-128)

node: v16.4.1

npm: 7.18.1

Docker version 20.10.7, build f0df350


No change to package.json was detected. No package manager install will be executed.
Congratulations, JHipster execution is complete!
Sponsored with ❤️  by @oktadev.
```

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

- No files exist in `.jhipster` directory.

##### **Browsers and Operating System**

- OS: Mac OS Big Sur 11.2 (M1, ARM Processor)

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by sang-w0o** [comment]
I just found out that I also get the error below.

```
The JHipster Registry will start in 0s...

#

# A fatal error has been detected by the Java Runtime Environment:

#

# SIGSEGV (0xb) at pc=0x0000004017b458a0, pid=12, tid=15

#

# JRE version: OpenJDK Runtime Environment AdoptOpenJDK-11.0.11+9 (11.0.11+9) (build 11.0.11+9)

# Java VM: OpenJDK 64-Bit Server VM AdoptOpenJDK-11.0.11+9 (11.0.11+9, mixed mode, tiered, compressed oops, g1 gc, linux-amd64)

# Problematic frame:

# J 495 c1 java.net.URL.<init>(Ljava/net/URL;Ljava/lang/String;Ljava/net/URLStreamHandler;)V java.base@11.0.11 (543 bytes) @ 0x0000004017b458a0 [0x0000004017b45880+0x0000000000000020]

#

# No core dump will be written. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again

#

# An error report file with more information is saved as:

# //hs_err_pid12.log


Picked up _JAVA_OPTIONS: -Xmx512m -Xms256m

qemu: uncaught target signal 6 (Aborted) - core dumped

Aborted


Compiled method (c1) 2513 702 2 java.net.JarURLConnection::parseSpecs (134 bytes)

total in heap [0x0000004017bb2790,0x0000004017bb3668] = 3800

relocation [0x0000004017bb2908,0x0000004017bb2a10] = 264

main code [0x0000004017bb2a20,0x0000004017bb31a0] = 1920

stub code [0x0000004017bb31a0,0x0000004017bb32a0] = 256

metadata [0x0000004017bb32a0,0x0000004017bb32e0] = 64

scopes data [0x0000004017bb32e0,0x0000004017bb3488] = 424

scopes pcs [0x0000004017bb3488,0x0000004017bb3638] = 432

dependencies [0x0000004017bb3638,0x0000004017bb3640] = 8

nul chk table [0x0000004017bb3640,0x0000004017bb3668] = 40

Compiled method (c1) 2514 681 ! 2 java.util.zip.ZipFile::close (44 bytes)

total in heap [0x0000004017bad490,0x0000004017badae8] = 1624

relocation [0x0000004017bad608,0x0000004017bad658] = 80

main code [0x0000004017bad660,0x0000004017bad940] = 736

stub code [0x0000004017bad940,0x0000004017bad990] = 80

metadata [0x0000004017bad990,0x0000004017bad998] = 8

scopes data [0x0000004017bad998,0x0000004017bad9e0] = 72

scopes pcs [0x0000004017bad9e0,0x0000004017bada60] = 128

dependencies [0x0000004017bada60,0x0000004017bada68] = 8

handler table [0x0000004017bada68,0x0000004017badad8] = 112

nul chk table [0x0000004017badad8,0x0000004017badae8] = 16

Could not load hsdis-amd64.so; library not loadable; PrintAssembly is disabled

#

# If you would like to submit a bug report, please visit:

# https://github.com/AdoptOpenJDK/openjdk-support/issues
```

**Comment by mshima** [comment]
See https://github.com/jhipster/jhipster-registry/issues/500

**Comment by sang-w0o** [comment]
Using `-XX:UseSSE=2` option in `_JAVA_OPTIONS_` solved this issue :(
