### ISSUE TITLE
string literal is expected 

### ISSUE THREAD

**Issue by zmhbh** [jhipster/generator-jhipster#15578]
##### **Overview of the issue**

Related to JDL - deployment, when I specify ingressType as nginx, it shows this 'Error: Error during import-jdl: A string literal is expected, but found: "nginx"
	at line: 9, column: 16'

##### **Motivation for or Use Case**

I cannot generate script for deployment of kubernetes

##### **Reproduce the error**

deployment {
  deploymentType kubernetes
  directoryPath "../../"
  appsFolders [notification]
  dockerRepositoryName "registry.cn-shanghai.aliyuncs.com/jhipster"
  serviceDiscoveryType no
  istio true
  kubernetesServiceType Ingress
  ingressType  nginx
  kubernetesNamespace jhipster
  ingressDomain "app-api.jhipster.com"
}

just import this jdl

##### **Related issues**

N/A

##### **Suggest a Fix**

N/A

##### **JHipster Version(s)**
7.1.0

##### **Browsers and Operating System**

MacOS

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by MukhinAlexey** [comment]
The same issue for me on my MacOS BigSur 11.2.2 with JHipster 7.1.0

`ERROR! Error during import-jdl: A string literal is expected, but found: "nginx"`

More of a stack trace

`
error: Syntax error message:
	A string literal is expected, but found: "nginx"
	at line: 80, column: 15
Error during import-jdl: Error: A string literal is expected, but found: "nginx"
	at line: 80, column: 15
Error: A string literal is expected, but found: "nginx"
	at line: 80, column: 15
    at throwSyntaxError (/usr/local/lib/node_modules/generator-jhipster/jdl/parsing/api.js:89:9)
    at getCst (/usr/local/lib/node_modules/generator-jhipster/jdl/parsing/api.js:63:5)
    at Object.parse (/usr/local/lib/node_modules/generator-jhipster/jdl/parsing/api.js:40:15)
    at callApiMethod (/usr/local/lib/node_modules/generator-jhipster/jdl/readers/jdl-reader.js:98:30)
    at parse (/usr/local/lib/node_modules/generator-jhipster/jdl/readers/jdl-reader.js:84:25)
    at Object.parseFromFiles (/usr/local/lib/node_modules/generator-jhipster/jdl/readers/jdl-reader.js:43:10)
    at parseFiles (/usr/local/lib/node_modules/generator-jhipster/jdl/jdl-importer.js:132:20)
    at createImporterFromFiles (/usr/local/lib/node_modules/generator-jhipster/jdl/jdl-importer.js:64:19)
    at JDLProcessor.importJDL (/usr/local/lib/node_modules/generator-jhipster/cli/import-jdl.js:368:18)
    at module.exports (/usr/local/lib/node_modules/generator-jhipster/cli/import-jdl.js:512:17)
ERROR! Error during import-jdl: A string literal is expected, but found: "nginx"
	at line: 80, column: 15
Error: Error during import-jdl: A string literal is expected, but found: "nginx"
	at line: 80, column: 15
    at module.exports (/usr/local/lib/node_modules/generator-jhipster/cli/import-jdl.js:527:27)
    at /usr/local/lib/node_modules/generator-jhipster/cli/jdl.js:61:49
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Promise.all (index 0)
`

**Comment by MathieuAA** [comment]
Hello, thanks for the report. I'll handle it.

**Comment by MathieuAA** [comment]
The fix has been merged, and the doc has been updated too. Thanks again for the report.
