### ISSUE TITLE
Failed to start with newly generated microservice with hazelcast

### ISSUE THREAD

**Issue by Piscenois** [jhipster/generator-jhipster#15686]
##### **Overview of the issue**

When I start newly created microservice + hazelcast project I get this error output :
<pre>
[...]AdoptOpenJDK\jdk-11.0.11.9-hotspot\bin\java.exe -XX:TieredStopAtLevel=1 -noverify -Dspring.output.ansi.enabled=always "-javaagent:C:\Program Files\JetBrains\IntelliJ IDEA 2021.1\lib\idea_rt.jar=52496:C:\Program Files\JetBrains\IntelliJ IDEA 2021.1\bin" -Dcom.sun.management.jmxremote -Dspring.jmx.enabled=true -Dspring.liveBeansView.mbeanDomain -Dspring.application.admin.enabled=true -Dfile.encoding=UTF-8 @C:\Users\geuzet.SQLIGROUP\AppData\Local\Temp\idea_arg_file1402173280 com.mycompany.myapp.TestHazelcastApp

        ██╗ ██╗   ██╗ ████████╗ ███████╗   ██████╗ ████████╗ ████████╗ ███████╗
        ██║ ██║   ██║ ╚══██╔══╝ ██╔═══██╗ ██╔════╝ ╚══██╔══╝ ██╔═════╝ ██╔═══██╗
        ██║ ████████║    ██║    ███████╔╝ ╚█████╗     ██║    ██████╗   ███████╔╝
  ██╗   ██║ ██╔═══██║    ██║    ██╔════╝   ╚═══██╗    ██║    ██╔═══╝   ██╔══██║
  ╚██████╔╝ ██║   ██║ ████████╗ ██║       ██████╔╝    ██║    ████████╗ ██║  ╚██╗
   ╚═════╝  ╚═╝   ╚═╝ ╚═══════╝ ╚═╝       ╚═════╝     ╚═╝    ╚═══════╝ ╚═╝   ╚═╝

:: JHipster 🤓  :: Running Spring Boot 2.4.7 ::
:: https://www.jhipster.tech ::

2021-07-19 09:13:02.955 DEBUG 15220 --- [kground-preinit] org.jboss.logging                        : Logging Provider: org.jboss.logging.Log4j2LoggerProvider
2021-07-19 09:13:02.987  INFO 15220 --- [  restartedMain] com.mycompany.myapp.TestHazelcastApp     : Starting TestHazelcastApp using Java 11.0.11 on L550188 with PID 15220 (L:\Sirius\Sirius\jhipster-tmp\testHazelcast\build\classes\java\main started by geuzet in L:\Sirius\Sirius\jhipster-tmp\testHazelcast)
2021-07-19 09:13:02.989 DEBUG 15220 --- [  restartedMain] com.mycompany.myapp.TestHazelcastApp     : Running with Spring Boot v2.4.7, Spring v5.3.8
2021-07-19 09:13:02.989  INFO 15220 --- [  restartedMain] com.mycompany.myapp.TestHazelcastApp     : The following profiles are active: dev,api-docs
2021-07-19 09:13:07.103 DEBUG 15220 --- [  restartedMain] jdk.event.security                       : X509Certificate: Alg:SHA1withDSA, Serial:10, Subject:CN=JCE Code Signing CA, OU=Java Software Code Signing, O=Sun Microsystems Inc, L=Palo Alto, ST=CA, C=US, Issuer:CN=JCE Code Signing CA, OU=Java Software Code Signing, O=Sun Microsystems Inc, L=Palo Alto, ST=CA, C=US, Key type:DSA, Length:1024, Cert Id:1776909028, Valid from:25/04/2001 09:00, Valid until:25/04/2020 09:00
2021-07-19 09:13:07.105 DEBUG 15220 --- [  restartedMain] jdk.event.security                       : X509Certificate: Alg:SHA1withDSA, Serial:47f, Subject:CN=Legion of the Bouncy Castle Inc., OU=Java Software Code Signing, O=Sun Microsystems Inc, Issuer:CN=JCE Code Signing CA, OU=Java Software Code Signing, O=Sun Microsystems Inc, L=Palo Alto, ST=CA, C=US, Key type:DSA, Length:1024, Cert Id:-2023852845, Valid from:11/03/2017 02:15, Valid until:25/04/2020 09:00
2021-07-19 09:13:07.118 DEBUG 15220 --- [  restartedMain] jdk.event.security                       : X509Certificate: Alg:SHA1withRSA, Serial:3019a023aff58b16bd6d5eae617f066, Subject:CN=DigiCert Timestamp Responder, O=DigiCert, C=US, Issuer:CN=DigiCert Assured ID CA-1, OU=www.digicert.com, O=DigiCert Inc, C=US, Key type:RSA, Length:2048, Cert Id:-499520198, Valid from:22/10/2014 02:00, Valid until:22/10/2024 02:00
2021-07-19 09:13:07.119 DEBUG 15220 --- [  restartedMain] jdk.event.security                       : X509Certificate: Alg:SHA1withRSA, Serial:6fdf9039603adea000aeb3f27bbba1b, Subject:CN=DigiCert Assured ID CA-1, OU=www.digicert.com, O=DigiCert Inc, C=US, Issuer:CN=DigiCert Assured ID Root CA, OU=www.digicert.com, O=DigiCert Inc, C=US, Key type:RSA, Length:2048, Cert Id:-1111363278, Valid from:10/11/2006 01:00, Valid until:10/11/2021 01:00
2021-07-19 09:13:07.151 DEBUG 15220 --- [  restartedMain] jdk.event.security                       : X509Certificate: Alg:SHA256withRSA, Serial:3c9eb1fc89f733d3, Subject:CN=JCE Code Signing CA, OU=Java Software Code Signing, O=Oracle Corporation, Issuer:CN=JCE Code Signing CA, OU=Java Software Code Signing, O=Oracle Corporation, Key type:RSA, Length:2048, Cert Id:-1250580323, Valid from:07/07/2016 01:48, Valid until:31/12/2030 01:00
2021-07-19 09:13:07.156 DEBUG 15220 --- [  restartedMain] jdk.event.security                       : X509Certificate: Alg:SHA256withRSA, Serial:4efb7bc62e2b049e, Subject:CN=Legion of the Bouncy Castle Inc., OU=Java Software Code Signing, O=Oracle Corporation, Issuer:CN=JCE Code Signing CA, OU=Java Software Code Signing, O=Oracle Corporation, Key type:DSA, Length:2048, Cert Id:-654023182, Valid from:11/03/2017 02:07, Valid until:11/03/2022 02:07
2021-07-19 09:13:07.159 DEBUG 15220 --- [  restartedMain] jdk.event.security                       : X509Certificate: Alg:SHA256withRSA, Serial:4cd3f8568ae76c61bb0fe7160cca76d, Subject:CN=TIMESTAMP-SHA256-2019-10-15, O="DigiCert, Inc.", C=US, Issuer:CN=DigiCert SHA2 Assured ID Timestamping CA, OU=www.digicert.com, O=DigiCert Inc, C=US, Key type:RSA, Length:2048, Cert Id:380147180, Valid from:01/10/2019 02:00, Valid until:17/10/2030 02:00
2021-07-19 09:13:07.160 DEBUG 15220 --- [  restartedMain] jdk.event.security                       : X509Certificate: Alg:SHA256withRSA, Serial:aa125d6d6321b7e41e405da3697c215, Subject:CN=DigiCert SHA2 Assured ID Timestamping CA, OU=www.digicert.com, O=DigiCert Inc, C=US, Issuer:CN=DigiCert Assured ID Root CA, OU=www.digicert.com, O=DigiCert Inc, C=US, Key type:RSA, Length:2048, Cert Id:-1680473293, Valid from:07/01/2016 13:00, Valid until:07/01/2031 13:00
2021-07-19 09:13:07.506 DEBUG 15220 --- [  restartedMain] i.m.c.u.i.logging.InternalLoggerFactory  : Using SLF4J as the default logging framework
2021-07-19 09:13:07.694  INFO 15220 --- [  restartedMain] c.mycompany.myapp.config.WebConfigurer   : Web application configuration, using profiles: dev
2021-07-19 09:13:07.694 DEBUG 15220 --- [  restartedMain] c.mycompany.myapp.config.WebConfigurer   : Initialize H2 console
2021-07-19 09:13:07.705  INFO 15220 --- [  restartedMain] c.mycompany.myapp.config.WebConfigurer   : Web application fully configured
2021-07-19 09:13:07.831 DEBUG 15220 --- [  restartedMain] c.m.myapp.config.AsyncConfiguration      : Creating Async Task Executor
2021-07-19 09:13:07.875 DEBUG 15220 --- [  restartedMain] c.m.myapp.config.LiquibaseConfiguration  : Configuring Liquibase
2021-07-19 09:13:08.024  WARN 15220 --- [azelcast-task-1] t.j.c.liquibase.AsyncSpringLiquibase     : Starting Liquibase asynchronously, your database might not be ready at startup!
2021-07-19 09:13:08.066 DEBUG 15220 --- [  restartedMain] c.m.myapp.config.CacheConfiguration      : Configuring Hazelcast
2021-07-19 09:13:08.082  WARN 15220 --- [  restartedMain] c.h.i.impl.HazelcastInstanceFactory      : Hazelcast is starting in a Java modular environment (Java 9 and newer) but without proper access to required Java packages. Use additional Java arguments to provide Hazelcast access to Java internal API. The internal API access is used to get the best performance results. Arguments to be used:
 --add-modules java.se --add-exports java.base/jdk.internal.ref=ALL-UNNAMED --add-opens java.base/java.lang=ALL-UNNAMED --add-opens java.base/java.nio=ALL-UNNAMED --add-opens java.base/sun.nio.ch=ALL-UNNAMED --add-opens java.management/sun.management=ALL-UNNAMED --add-opens jdk.management/com.sun.management.internal=ALL-UNNAMED
2021-07-19 09:13:08.196  INFO 15220 --- [  restartedMain] com.hazelcast.system                     : [127.0.0.1]:5701 [dev] [4.1.1] Hazelcast 4.1.1 (20201222 - 27af558) starting at [127.0.0.1]:5701
2021-07-19 09:13:08.692  INFO 15220 --- [  restartedMain] c.h.s.d.integration.DiscoveryService     : [127.0.0.1]:5701 [dev] [4.1.1] No discovery strategy is applicable for auto-detection
2021-07-19 09:13:08.763  WARN 15220 --- [  restartedMain] com.hazelcast.instance.impl.Node         : [127.0.0.1]:5701 [dev] [4.1.1] Hazelcast is bound to 127.0.0.1 and loop-back mode is disabled in the configuration. This could cause multicast auto-discovery issues and render it unable to work. Check your network connectivity, try to enable the loopback mode and/or force -Djava.net.preferIPv4Stack=true on your JVM.
2021-07-19 09:13:08.766 ERROR 15220 --- [  restartedMain] com.hazelcast.instance.impl.Node         : [127.0.0.1]:5701 [dev] [4.1.1] error setting options

java.net.SocketException: error setting options
	at java.base/java.net.TwoStacksPlainDatagramSocketImpl.join(Native Method)
	at java.base/java.net.AbstractPlainDatagramSocketImpl.join(AbstractPlainDatagramSocketImpl.java:216)
	at java.base/java.net.MulticastSocket.joinGroup(MulticastSocket.java:328)
	at com.hazelcast.internal.cluster.impl.MulticastService.createMulticastService(MulticastService.java:145)
	at com.hazelcast.instance.impl.Node.<init>(Node.java:272)
	at com.hazelcast.instance.impl.HazelcastInstanceImpl.createNode(HazelcastInstanceImpl.java:148)
	at com.hazelcast.instance.impl.HazelcastInstanceImpl.<init>(HazelcastInstanceImpl.java:117)
	at com.hazelcast.instance.impl.HazelcastInstanceFactory.constructHazelcastInstance(HazelcastInstanceFactory.java:211)
	at com.hazelcast.instance.impl.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:190)
	at com.hazelcast.instance.impl.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:128)
	at com.hazelcast.core.Hazelcast.newHazelcastInstance(Hazelcast.java:57)
	at com.mycompany.myapp.config.CacheConfiguration.hazelcastInstance(CacheConfiguration.java:78)
	at com.mycompany.myapp.config.CacheConfiguration$$EnhancerBySpringCGLIB$$ea3d4568.CGLIB$hazelcastInstance$3(<generated>)
	at com.mycompany.myapp.config.CacheConfiguration$$EnhancerBySpringCGLIB$$ea3d4568$$FastClassBySpringCGLIB$$71295c2c.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:244)
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:331)
	at com.mycompany.myapp.config.CacheConfiguration$$EnhancerBySpringCGLIB$$ea3d4568.hazelcastInstance(<generated>)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:653)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:638)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1334)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1177)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:564)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:524)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:322)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
	at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1154)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:908)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:144)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:771)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:763)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:438)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:339)
	at com.mycompany.myapp.TestHazelcastApp.main(TestHazelcastApp.java:69)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.boot.devtools.restart.RestartLauncher.run(RestartLauncher.java:49)

2021-07-19 09:13:08.767  INFO 15220 --- [  restartedMain] com.hazelcast.instance.impl.Node         : [127.0.0.1]:5701 [dev] [4.1.1] Using Multicast discovery
2021-07-19 09:13:08.771 ERROR 15220 --- [  restartedMain] com.hazelcast.instance.impl.Node         : [127.0.0.1]:5701 [dev] [4.1.1] Node creation failed

java.lang.NullPointerException: null
	at com.hazelcast.internal.cluster.impl.MulticastJoiner.<init>(MulticastJoiner.java:52)
	at com.hazelcast.instance.impl.Node.createJoiner(Node.java:829)
	at com.hazelcast.instance.impl.DefaultNodeContext.createJoiner(DefaultNodeContext.java:142)
	at com.hazelcast.instance.impl.Node.<init>(Node.java:273)
	at com.hazelcast.instance.impl.HazelcastInstanceImpl.createNode(HazelcastInstanceImpl.java:148)
	at com.hazelcast.instance.impl.HazelcastInstanceImpl.<init>(HazelcastInstanceImpl.java:117)
	at com.hazelcast.instance.impl.HazelcastInstanceFactory.constructHazelcastInstance(HazelcastInstanceFactory.java:211)
	at com.hazelcast.instance.impl.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:190)
	at com.hazelcast.instance.impl.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:128)
	at com.hazelcast.core.Hazelcast.newHazelcastInstance(Hazelcast.java:57)
	at com.mycompany.myapp.config.CacheConfiguration.hazelcastInstance(CacheConfiguration.java:78)
	at com.mycompany.myapp.config.CacheConfiguration$$EnhancerBySpringCGLIB$$ea3d4568.CGLIB$hazelcastInstance$3(<generated>)
	at com.mycompany.myapp.config.CacheConfiguration$$EnhancerBySpringCGLIB$$ea3d4568$$FastClassBySpringCGLIB$$71295c2c.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:244)
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:331)
	at com.mycompany.myapp.config.CacheConfiguration$$EnhancerBySpringCGLIB$$ea3d4568.hazelcastInstance(<generated>)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:653)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:638)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1334)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1177)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:564)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:524)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:322)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
	at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1154)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:908)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:144)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:771)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:763)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:438)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:339)
	at com.mycompany.myapp.TestHazelcastApp.main(TestHazelcastApp.java:69)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.boot.devtools.restart.RestartLauncher.run(RestartLauncher.java:49)

2021-07-19 09:13:08.771  INFO 15220 --- [  restartedMain] com.hazelcast.instance.impl.Node         : [127.0.0.1]:5701 [dev] [4.1.1] Shutting down connection manager...
2021-07-19 09:13:08.774  INFO 15220 --- [  restartedMain] com.hazelcast.instance.impl.Node         : [127.0.0.1]:5701 [dev] [4.1.1] Shutting down node engine...
2021-07-19 09:13:08.776  INFO 15220 --- [  restartedMain] c.hazelcast.instance.impl.NodeExtension  : [127.0.0.1]:5701 [dev] [4.1.1] Destroying node NodeExtension.
2021-07-19 09:13:08.780  WARN 15220 --- [  restartedMain] ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'hazelcastInstance' defined in class path resource [com/mycompany/myapp/config/CacheConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.hazelcast.core.HazelcastInstance]: Factory method 'hazelcastInstance' threw exception; nested exception is java.lang.NullPointerException
2021-07-19 09:13:08.780  INFO 15220 --- [  restartedMain] c.m.myapp.config.CacheConfiguration      : Closing Cache Manager
2021-07-19 09:13:08.856 ERROR 15220 --- [  restartedMain] o.s.boot.SpringApplication               : Application run failed

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'hazelcastInstance' defined in class path resource [com/mycompany/myapp/config/CacheConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.hazelcast.core.HazelcastInstance]: Factory method 'hazelcastInstance' threw exception; nested exception is java.lang.NullPointerException
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:658)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:638)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1334)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1177)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:564)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:524)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:322)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
	at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1154)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:908)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:144)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:771)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:763)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:438)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:339)
	at com.mycompany.myapp.TestHazelcastApp.main(TestHazelcastApp.java:69)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.boot.devtools.restart.RestartLauncher.run(RestartLauncher.java:49)
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.hazelcast.core.HazelcastInstance]: Factory method 'hazelcastInstance' threw exception; nested exception is java.lang.NullPointerException
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:653)
	... 25 common frames omitted
Caused by: java.lang.NullPointerException: null
	at com.hazelcast.internal.cluster.impl.MulticastJoiner.<init>(MulticastJoiner.java:52)
	at com.hazelcast.instance.impl.Node.createJoiner(Node.java:829)
	at com.hazelcast.instance.impl.DefaultNodeContext.createJoiner(DefaultNodeContext.java:142)
	at com.hazelcast.instance.impl.Node.<init>(Node.java:273)
	at com.hazelcast.instance.impl.HazelcastInstanceImpl.createNode(HazelcastInstanceImpl.java:148)
	at com.hazelcast.instance.impl.HazelcastInstanceImpl.<init>(HazelcastInstanceImpl.java:117)
	at com.hazelcast.instance.impl.HazelcastInstanceFactory.constructHazelcastInstance(HazelcastInstanceFactory.java:211)
	at com.hazelcast.instance.impl.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:190)
	at com.hazelcast.instance.impl.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:128)
	at com.hazelcast.core.Hazelcast.newHazelcastInstance(Hazelcast.java:57)
	at com.mycompany.myapp.config.CacheConfiguration.hazelcastInstance(CacheConfiguration.java:78)
	at com.mycompany.myapp.config.CacheConfiguration$$EnhancerBySpringCGLIB$$ea3d4568.CGLIB$hazelcastInstance$3(<generated>)
	at com.mycompany.myapp.config.CacheConfiguration$$EnhancerBySpringCGLIB$$ea3d4568$$FastClassBySpringCGLIB$$71295c2c.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:244)
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:331)
	at com.mycompany.myapp.config.CacheConfiguration$$EnhancerBySpringCGLIB$$ea3d4568.hazelcastInstance(<generated>)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154)
	... 26 common frames omitted

Skipping auto-registration
2021-07-19 09:13:09.384 DEBUG 15220 --- [azelcast-task-1] t.j.c.liquibase.AsyncSpringLiquibase     : Liquibase has updated your database in 1359 ms

Process finished with exit code 1

</pre>

##### **Reproduce the error**

Create a project of type microservices with hazelcast cache enabled. Start the application.

##### **Suggest a Fix**

Modifying the class `CacheConfiguration`, method `hazelcastInstance(JHipsterProperties jHipsterProperties)` solves the problem.
Add this line inside the block `if (env.acceptsProfiles(Profiles.of(JHipsterConstants.SPRING_PROFILE_DEVELOPMENT)))`:
<pre>
            config.getNetworkConfig().getJoin().getAutoDetectionConfig().setEnabled(false);
</pre>

##### **JHipster Version(s)**

```
test-hazelcast@0.0.0 L:\jhipster-tmp\testHazelcast
`-- generator-jhipster@7.1.0

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "applicationType": "microservice",
    "baseName": "testHazelcast",
    "jhipsterVersion": "7.1.0",
    "skipClient": true,
    "withAdminUi": false,
    "skipUserManagement": true,
    "skipServer": false,
    "skipCheckLengthOfIdentifier": false,
    "skipFakeData": false,
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "testFrameworks": [],
    "blueprints": [],
    "otherModules": [],
    "pages": [],
    "creationTimestamp": 1626424506645,
    "serviceDiscoveryType": false,
    "reactive": false,
    "authenticationType": "jwt",
    "packageName": "com.mycompany.myapp",
    "serverPort": "8081",
    "cacheProvider": "hazelcast",
    "enableHibernateCache": true,
    "databaseType": "sql",
    "devDatabaseType": "h2Memory",
    "prodDatabaseType": "postgresql",
    "buildTool": "gradle",
    "serverSideOptions": [],
    "websocket": false,
    "searchEngine": false,
    "messageBroker": false,
    "enableSwaggerCodegen": false,
    "enableTranslation": false,
    "nativeLanguage": "fr",
    "packageFolder": "com/mycompany/myapp",
    "jwtSecretKey": "YourJWTSecretKeyWasReplacedByThisMeaninglessTextByTheJHipsterInfoCommandForObviousSecurityReasons",
    "languages": ["en", "fr"],
    "entities": ["EntiteExemple", "EntiteExempleSub"],
    "lastLiquibaseTimestamp": 1626443163000
  }
}

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity EntiteExemple {
  typeString String
  typeInstant Instant
  typeLong Long
  typeInteger Integer
  typeBigDecimal BigDecimal
  typeFloat Float
  typeDouble Double
  typeBoolean Boolean
  typeLocalDate LocalDate
  typeZonedDateTime ZonedDateTime
  typeDuration Duration
  typeUUID UUID
  typeEnum EnumStatut
  typeBlob AnyBlob
  typeAnyBlob AnyBlob
  typeImageBlob ImageBlob
  typeTextBlob TextBlob
}
entity EntiteExempleSub {
  nom String
}
enum EnumStatut {
  ACTIVE,
  DESACTIVE,
  NOT_AVAILABLE
}

relationship OneToMany {
  EntiteExemple{entiteExempleSub} to EntiteExempleSub{entiteExemple}
}

dto EntiteExemple, EntiteExempleSub with mapstruct
paginate EntiteExemple, EntiteExempleSub with pagination
service EntiteExemple, EntiteExempleSub with serviceImpl
microservice EntiteExemple, EntiteExempleSub with testHazelcast
clientRootFolder EntiteExemple, EntiteExempleSub with testHazelcast

</pre>
</details>

##### **Environment and Tools**

openjdk version "11.0.11" 2021-04-20
OpenJDK Runtime Environment AdoptOpenJDK-11.0.11+9 (build 11.0.11+9)
OpenJDK 64-Bit Server VM AdoptOpenJDK-11.0.11+9 (build 11.0.11+9, mixed mode)

node: v14.16.1

npm: 7.19.1

Docker version 20.10.7, build f0df350

docker-compose version 1.29.2, build 5becea4c

No change to package.json was detected. No package manager install will be executed.
Congratulations, JHipster execution is complete!
Sponsored with ❤️  by @oktadev.
  </pre>
  </details>

**Comment by mraible** [comment]
I created a new project with your `.yo-rc.json` and JDL. Then, I started Hazelcast Management Center.

```
docker-compose -f src/main/docker/hazelcast-management-center.yml up
```

Then, I started the app with `./gradlew`. Everything starts up just fine.

```
----------------------------------------------------------
        Application 'testHazelcast' is running! Access URLs:
        Local:          http://localhost:8081/
        External:       http://127.0.0.1:8081/
        Profile(s):     [dev, api-docs]
----------------------------------------------------------
```

**Comment by Piscenois** [comment]
Thank you @mraible .
I thought I didn't need an Hazelcast instance in local development. My mistake.
