### ISSUE TITLE
DB Columns Are Not Removed After Removing Fields In Entity

### ISSUE THREAD

**Issue by vw98075** [jhipster/generator-jhipster#15746]
##### **Overview of the issue**

After removing two fields of an entity in a JDL file, I import the file again. In the app, all related changes occur. The H2 in the dev environment still has the related two columns. When I start up the app, there are related error messages on the console.
```
2021-07-26 10:35:32.749 ERROR 8155 --- [myapp-task-1] t.j.c.liquibase.AsyncSpringLiquibase     : Liquibase could not start correctly, your database is NOT ready: Validation Failed:
     2 change sets check sum
          config/liquibase/changelog/20210723160034_added_entity_JobCandidateRepo.xml::20210723160034-1::jhipster was: 8:0a73f97f04dcd9fcffcb1e7ee9f4e6d3 but is now: 8:6d1a135f1ba726a7764d80aa06df6233
          config/liquibase/changelog/20210723160034_added_entity_JobCandidateRepo.xml::20210723160034-1-data::jhipster was: 8:c49891029109e7dca50756a3afd68680 but is now: 8:447088b7a003b9a63260dd25fee9af06


liquibase.exception.ValidationFailedException: Validation Failed:
     2 change sets check sum
          config/liquibase/changelog/20210723160034_added_entity_JobCandidateRepo.xml::20210723160034-1::jhipster was: 8:0a73f97f04dcd9fcffcb1e7ee9f4e6d3 but is now: 8:6d1a135f1ba726a7764d80aa06df6233
          config/liquibase/changelog/20210723160034_added_entity_JobCandidateRepo.xml::20210723160034-1-data::jhipster was: 8:c49891029109e7dca50756a3afd68680 but is now: 8:447088b7a003b9a63260dd25fee9af06

        at liquibase.changelog.DatabaseChangeLog.validate(DatabaseChangeLog.java:299)
        at liquibase.Liquibase.lambda$update$1(Liquibase.java:237)
        at liquibase.Scope.lambda$child$0(Scope.java:160)
        at liquibase.Scope.child(Scope.java:169)
        at liquibase.Scope.child(Scope.java:159)
        at liquibase.Scope.child(Scope.java:138)
        at liquibase.Liquibase.runInScope(Liquibase.java:2369)
        at liquibase.Liquibase.update(Liquibase.java:217)
        at liquibase.Liquibase.update(Liquibase.java:203)
        at liquibase.integration.spring.SpringLiquibase.performUpdate(SpringLiquibase.java:321)
        at liquibase.integration.spring.SpringLiquibase.afterPropertiesSet(SpringLiquibase.java:275)
        at org.springframework.boot.autoconfigure.liquibase.DataSourceClosingSpringLiquibase.afterPropertiesSet(DataSourceClosingSpringLiquibase.java:46)
        at tech.jhipster.config.liquibase.AsyncSpringLiquibase.initDb(AsyncSpringLiquibase.java:118)
        at tech.jhipster.config.liquibase.AsyncSpringLiquibase.lambda$afterPropertiesSet$0(AsyncSpringLiquibase.java:93)
        at tech.jhipster.async.ExceptionHandlingAsyncTaskExecutor.lambda$createWrappedRunnable$1(ExceptionHandlingAsyncTaskExecutor.java:78)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
```

##### **JHipster configuration**

```
{
  "generator-jhipster": {
    "applicationType": "monolith",
    "baseName": "myapp",
    "jhipsterVersion": "7.1.0",
    "skipClient": false,
    "skipServer": false,
    "skipUserManagement": false,
    "skipCheckLengthOfIdentifier": false,
    "skipFakeData": false,
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "testFrameworks": ["cypress", "gatling"],
    "blueprints": [],
    "otherModules": [],
    "pages": [],
    "creationTimestamp": 1625095262715,
    "serviceDiscoveryType": false,
    "reactive": false,
    "authenticationType": "jwt",
    "packageName": "com.abc.myapp",
    "serverPort": "8080",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "postgresql",
    "buildTool": "gradle",
    "serverSideOptions": [],
    "websocket": false,
    "searchEngine": false,
    "messageBroker": false,
    "enableSwaggerCodegen": false,
    "clientFramework": "vue",
    "withAdminUi": true,
    "clientTheme": "cosmo",
    "clientThemeVariant": "primary",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "packageFolder": "com/abc/myapp",
    "jwtSecretKey": "NThkZDg5YjE3OTkxNGU2YjUzNjAwODMwZjY4ODRiYmIyOWVkN2Q0NmZhMjZhNDU4MmQyYTQ5NDcxOWZlODRjY2ZhYWE5NjNjZWJkZDUyYzljYTU0NmU0OGExZDY4N2EwZjljZWQwMTliYWU3NGZiZTQ3NDQ1MGIwOTNjZDU3NmE=",
    "devServerPort": 9060,
    "clientPackageManager": "npm",
    "languages": ["en", "es"]
  }
}
```

##### **Browsers and Operating System**

- [x ] Checking this box is mandatory (this is just to show you read everything)

**Comment by gmarziou** [comment]
This is normal, Liquibase changesets are supposed to be immutable, cehck our doc https://www.jhipster.tech/development/  or https://stackoverflow.com/questions/43207163/jhipster-liquibase-validation-error-after-modify-entity/

Since Jhipster 7, you can also use incremental changelogs: https://www.jhipster.tech/creating-an-app/#would-you-like-to-use-incremental-liquibase-changelogs
