### ISSUE TITLE
Google Keycloak integration

### ISSUE THREAD

**Issue by mmuruev** [jhipster/generator-jhipster#15821]
In freshly generated project failed authentificate with keycloak.. I'm using latest JH 7.1.0 , local authentication is fine. But google refuses provide the keys.  I'm really not sure that this is JH fault.  Maybe it just not going to work with localhost anyway.

```
20:20:51,805 INFO  [org.jboss.as] (Controller Boot Thread) WFLYSRV0060: Http management interface listening on http://127.0.0.1:10990/management
2021-08-02T20:20:51.805609786Z 20:20:51,805 INFO  [org.jboss.as] (Controller Boot Thread) WFLYSRV0051: Admin console listening on http://127.0.0.1:10990
2021-08-02T20:36:34.889495557Z 20:36:34,888 WARN  [org.keycloak.connections.httpclient.DefaultHttpClientFactory] (default task-4) TruststoreProvider is disabled
2021-08-02T20:36:35.392411574Z 20:36:35,390 ERROR [org.keycloak.broker.oidc.AbstractOAuth2IdentityProvider] (default task-4) Failed to make identity provider oauth callback: org.keycloak.broker.provider.IdentityBrokerException: No access_token from server.
2021-08-02T20:36:35.392458419Z 	at org.keycloak.keycloak-services@12.0.4//org.keycloak.broker.oidc.OIDCIdentityProvider.verifyAccessToken(OIDCIdentityProvider.java:515)
2021-08-02T20:36:35.392462461Z 	at org.keycloak.keycloak-services@12.0.4//org.keycloak.broker.oidc.OIDCIdentityProvider.getFederatedIdentity(OIDCIdentityProvider.java:360)
2021-08-02T20:36:35.392465058Z 	at org.keycloak.keycloak-services@12.0.4//org.keycloak.broker.oidc.AbstractOAuth2IdentityProvider$Endpoint.authResponse(AbstractOAuth2IdentityProvider.java:475)
2021-08-02T20:36:35.392467591Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2021-08-02T20:36:35.392490120Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2021-08-02T20:36:35.392492576Z 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2021-08-02T20:36:35.392494988Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
2021-08-02T20:36:35.392497361Z 	at org.jboss.resteasy.resteasy-jaxrs@3.13.2.Final//org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:138)
2021-08-02T20:36:35.392499831Z 	at org.jboss.resteasy.resteasy-jaxrs@3.13.2.Final//org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:543)
2021-08-02T20:36:35.392502334Z 	at org.jboss.resteasy.resteasy-jaxrs@3.13.2.Final//org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:432)
2021-08-02T20:36:35.392504771Z 	at org.jboss.resteasy.resteasy-jaxrs@3.13.2.Final//org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$0(ResourceMethodInvoker.java:393)
2021-08-02T20:36:35.392507243Z 	at org.jboss.resteasy.resteasy-jaxrs@3.13.2.Final//org.jboss.resteasy.core.interception.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:358)
2021-08-02T20:36:35.392509692Z 	at org.jboss.resteasy.resteasy-jaxrs@3.13.2.Final//org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:395)
2021-08-02T20:36:35.392512943Z 	at org.jboss.resteasy.resteasy-jaxrs@3.13.2.Final//org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:364)
2021-08-02T20:36:35.392515428Z 	at org.jboss.resteasy.resteasy-jaxrs@3.13.2.Final//org.jboss.resteasy.core.ResourceLocatorInvoker.invokeOnTargetObject(ResourceLocatorInvoker.java:150)
2021-08-02T20:36:35.392517863Z 	at org.jboss.resteasy.resteasy-jaxrs@3.13.2.Final//org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:110)
2021-08-02T20:36:35.392520302Z 	at org.jboss.resteasy.resteasy-jaxrs@3.13.2.Final//org.jboss.resteasy.core.ResourceLocatorInvoker.invokeOnTargetObject(ResourceLocatorInvoker.java:141)
2021-08-02T20:36:35.392522794Z 	at org.jboss.resteasy.resteasy-jaxrs@3.13.2.Final//org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:104)
2021-08-02T20:36:35.392525390Z 	at org.jboss.resteasy.resteasy-jaxrs@3.13.2.Final//org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:440)
2021-08-02T20:36:35.392528641Z 	at org.jboss.resteasy.resteasy-jaxrs@3.13.2.Final//org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:229)
2021-08-02T20:36:35.392532608Z 	at org.jboss.resteasy.resteasy-jaxrs@3.13.2.Final//org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:135)
2021-08-02T20:36:35.392535151Z 	at org.jboss.resteasy.resteasy-jaxrs@3.13.2.Final//org.jboss.resteasy.core.interception.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:358)
2021-08-02T20:36:35.392537612Z 	at org.jboss.resteasy.resteasy-jaxrs@3.13.2.Final//org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:138)
2021-08-02T20:36:35.392540038Z 	at org.jboss.resteasy.resteasy-jaxrs@3.13.2.Final//org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:215)
2021-08-02T20:36:35.392542504Z 	at org.jboss.resteasy.resteasy-jaxrs@3.13.2.Final//org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.service(ServletContainerDispatcher.java:245)
2021-08-02T20:36:35.392544974Z 	at org.jboss.resteasy.resteasy-jaxrs@3.13.2.Final//org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:61)
2021-08-02T20:36:35.392547465Z 	at org.jboss.resteasy.resteasy-jaxrs@3.13.2.Final//org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:56)
2021-08-02T20:36:35.392550159Z 	at javax.servlet.api@2.0.0.Final//javax.servlet.http.HttpServlet.service(HttpServlet.java:590)
2021-08-02T20:36:35.392552518Z 	at io.undertow.servlet@2.2.2.Final//io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:74)
2021-08-02T20:36:35.392554891Z 	at io.undertow.servlet@2.2.2.Final//io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:129)
2021-08-02T20:36:35.392557306Z 	at org.keycloak.keycloak-wildfly-extensions@12.0.4//org.keycloak.provider.wildfly.WildFlyRequestFilter.lambda$doFilter$0(WildFlyRequestFilter.java:41)
2021-08-02T20:36:35.392559825Z 	at org.keycloak.keycloak-services@12.0.4//org.keycloak.services.filters.AbstractRequestFilter.filter(AbstractRequestFilter.java:43)
2021-08-02T20:36:35.392562277Z 	at org.keycloak.keycloak-wildfly-extensions@12.0.4//org.keycloak.provider.wildfly.WildFlyRequestFilter.doFilter(WildFlyRequestFilter.java:39)
2021-08-02T20:36:35.392564726Z 	at io.undertow.servlet@2.2.2.Final//io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
2021-08-02T20:36:35.392567285Z 	at io.undertow.servlet@2.2.2.Final//io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
2021-08-02T20:36:35.392569762Z 	at io.undertow.servlet@2.2.2.Final//io.undertow.servlet.handlers.FilterHandler.handleRequest(FilterHandler.java:84)
2021-08-02T20:36:35.392572111Z 	at io.undertow.servlet@2.2.2.Final//io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62)
2021-08-02T20:36:35.392574568Z 	at io.undertow.servlet@2.2.2.Final//io.undertow.servlet.handlers.ServletChain$1.handleRequest(ServletChain.java:68)
2021-08-02T20:36:35.392576879Z 	at io.undertow.servlet@2.2.2.Final//io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36)
2021-08-02T20:36:35.392582250Z 	at org.wildfly.extension.undertow@21.0.2.Final//org.wildfly.extension.undertow.security.SecurityContextAssociationHandler.handleRequest(SecurityContextAssociationHandler.java:78)
2021-08-02T20:36:35.392584954Z 	at io.undertow.core@2.2.2.Final//io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
2021-08-02T20:36:35.392587441Z 	at io.undertow.servlet@2.2.2.Final//io.undertow.servlet.handlers.RedirectDirHandler.handleRequest(RedirectDirHandler.java:68)
```

**Comment by mraible** [comment]
Can you please provide steps to reproduce this issue?

**Comment by mmuruev** [comment]
Yes. I just generated a monolith project with keycloack empty one. Added google account in keycloak. 
- sign in link -> google -> fail on the page and this error in keycloak. 
The application runs in docker.

**Comment by mraible** [comment]
Do you have the `.yo-rc.json` you used to create your project. Or a JDL file? 

Also, please provide the steps you're using to add the user in Keycloak. Are you also using Google Social Login with Keycloak or something like that? I haven't tried that before so you might have better luck talking to the Keycloak folks.

**Comment by mmuruev** [comment]
Yes, I have. 

```{
  "generator-jhipster": {
    "applicationType": "monolith",
    "baseName": "bos",
    "jhipsterVersion": "7.1.0",
    "skipClient": false,
    "skipServer": false,
    "skipUserManagement": true,
    "skipCheckLengthOfIdentifier": false,
    "skipFakeData": false,
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "testFrameworks": ["gatling"],
    "blueprints": [],
    "otherModules": [],
    "pages": [],
    "creationTimestamp": 1627324179111,
    "serviceDiscoveryType": false,
    "reactive": true,
    "authenticationType": "oauth2",
    "packageName": "org.bos.platform",
    "serverPort": "8080",
    "cacheProvider": "no",
    "enableHibernateCache": false,
    "databaseType": "mongodb",
    "buildTool": "gradle",
    "serverSideOptions": [],
    "websocket": false,
    "searchEngine": false,
    "messageBroker": false,
    "enableSwaggerCodegen": false,
    "clientFramework": "vue",
    "withAdminUi": true,
    "clientTheme": "cerulean",
    "clientThemeVariant": "dark",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "packageFolder": "org/bos/platform",
    "devDatabaseType": "mongodb",
    "prodDatabaseType": "mongodb",
    "devServerPort": 9060,
    "clientPackageManager": "npm",
    "languages": ["en", "et", "ru"]
  }
}
