### ISSUE TITLE
failure running local blueprint with local jhipster 

### ISSUE THREAD

**Issue by jhcao23** [jhipster/generator-jhipster#15917]
##### **Overview of the issue**

I'm trying follow the instruction [Create a Blueprint -> Running local blueprint with local jhipster](https://www.jhipster.tech/modules/creating-a-blueprint/#running-local-blueprint-version-for-development) but always get a failure. My suspect is JHipster does not provide a nicely friendly interface to blueprint?

##### **Motivation for or Use Case**
Sometimes we need both local jhipster and local official blueprint (such as kotlin or ionic) to develop our project.

Let's try to use kotlin blueprint as local one example:
1. `cd $HOME/git/;`
2. `git clone https://github.com/jhipster/generator-jhipster.git && git clone https://github.com/jhipster/jhipster-kotlin.git;`
3. `cd $HOME/git/generator-jhipster && npm link;`
4. `cd $HOME/git/jhipster-kotlin && npm link && npm link generator-jhipster;`
5. `cd $HOME/git; mkdir test4; cd test4; cp ~/Downloads/jhipster-jdl.jdl .; `
6. `jhipster jdl jhipster-jdl.jdl --blueprints kotlin --skip-jhipster-dependencies;`

_npm linking jhipster before or after linking khipster does not matter, either way throws errors._
_using either yarn or npm results in errors._

##### **Reproduce the error**
```
Error running generator app: Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './generators/app' is not defined by "exports" in /Users/john/git/jhipster-kotlin/node_modules/generator-jhipster/package.json
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './generators/app' is not defined by "exports" in /Users/john/git/jhipster-kotlin/node_modules/generator-jhipster/package.json
    at throwExportsNotFound (internal/modules/esm/resolve.js:299:9)
    at packageExportsResolve (internal/modules/esm/resolve.js:522:3)
    at resolveExports (internal/modules/cjs/loader.js:449:36)
    at Function.Module._findPath (internal/modules/cjs/loader.js:489:31)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:875:27)
    at Function.Module._load (internal/modules/cjs/loader.js:745:27)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/Users/john/git/jhipster-kotlin/generators/app/index.js:20:23)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at requireOrImport (/Users/john/git/generator-jhipster/node_modules/yeoman-environment/lib/util/esm.js:14:14) {
  code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
}
```

##### **JHipster Version(s)**
latest: `7.1.0`

##### **Browsers and Operating System**
- macOS Big Sur
- node: v14.17.4
- npm: 6.14.14
- yarn: 1.22.11

**Comment by mshima** [comment]
Should be fixed by https://github.com/jhipster/generator-jhipster/pull/15982
