### ISSUE TITLE
Husky install fails when creating reactive microservices

### ISSUE THREAD

**Issue by mraible** [jhipster/generator-jhipster#16172]
##### **Overview of the issue**

Create a new directory and microservice projects in it. `husky install` fails.

```
> blog@0.0.0 prepare
> husky install


> store@0.0.0 prepare
> husky install

.git can't be found (see https://git.io/Jc3F9)
npm ERR! code 1
npm ERR! path /Users/mraible/Downloads/reactive-stack/blog
npm ERR! command failed
npm ERR! command sh -c husky install

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/mraible/.npm/_logs/2021-09-05T13_58_12_704Z-debug.log
.git can't be found (see https://git.io/Jc3F9)
npm ERR! code 1
npm ERR! path /Users/mraible/Downloads/reactive-stack/store
npm ERR! command failed
npm ERR! command sh -c husky install
ERROR! Command failed with exit code 1: npm install
Error: Command failed with exit code 1: npm install
```

##### **Motivation for or Use Case**

It's no fun seeing stack traces when generating JHipster apps.

##### **Reproduce the error**

```
take reactive-ms
git init # initialize git, so apps aren't created with their own .git
jhipster jdl reactive-ms
```

##### **Related issues**

#16055 

##### **JHipster Version(s)**

`main` branch

##### **Workaround**

Remove `"prepare": "husky install"` from each `package.json`.

**Comment by pascalgrimaud** [comment]
It looks like each microservices need their own .git folder, so indeed, it's not nice

**Comment by mraible** [comment]
I also saw some Cypress tests that are "pending". It seems that fake data is no longer loaded and might be causing this.

<img width="1420" alt="Screen Shot 2021-09-05 at 8 17 31 AM" src="https://user-images.githubusercontent.com/17892/132130249-eed37e2e-e12c-481e-adfc-ac08d56ba673.png">

**Comment by pascalgrimaud** [comment]
So these issues need to be fixed, before the next release

**Comment by mshima** [comment]
The git repository is in the parent.
I will take a look at this.

> I also saw some Cypress tests that are "pending". It seems that fake data is no longer loaded and might be causing this.

Should be fixed by https://github.com/jhipster/generator-jhipster/issues/14103, but never finished the implementation.

**Comment by mraible** [comment]
This still happens. Steps to reproduce:

```
take reactive-stack
git init
jhipster jdl reactive-ms
```

Error:

```
> store@0.0.0 prepare
> husky install


> blog@0.0.0 prepare
> husky install

.git can't be found (see https://git.io/Jc3F9)
npm ERR! code 1
npm ERR! path /Users/mraible/Downloads/new-stack/store
npm ERR! command failed
npm ERR! command sh -c husky install
.git can't be found (see https://git.io/Jc3F9)

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/mraible/.npm/_logs/2021-09-07T16_08_26_544Z-debug.log
npm ERR! code 1
npm ERR! path /Users/mraible/Downloads/new-stack/blog
npm ERR! command failed
npm ERR! command sh -c husky install
ERROR! Command failed with exit code 1: npm install
Error: Command failed with exit code 1: npm install
    at makeError (/Users/mraible/dev/generator-jhipster/node_modules/yeoman-environment/node_modules/execa/lib/error.js:59:11)
    at handlePromise (/Users/mraible/dev/generator-jhipster/node_modules/yeoman-environment/node_modules/execa/index.js:114:26)
    at processTicksAndRejections (internal/process/task_queues.js:95:5) {
  shortMessage: 'Command failed with exit code 1: npm install',
  command: 'npm install',
  exitCode: 1,
  signal: undefined,
  signalDescription: undefined,
  stdout: undefined,
  stderr: undefined,
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/mraible/.npm/_logs/2021-09-07T16_08_26_612Z-debug.log
INFO! Generator app child process exited with code 1
ERROR! Error executing app --reproducible --no-force --with-entities --no-dry-run --no-whitespace --no-bail --no-install-path --no-skip-regenerate --no-skip-yo-resolve --from-jdl --no-skip-cache --no-skip-install --no-force-install --no-ask-answered --no-defaults --no-skip-git
Error: Error executing app --reproducible --no-force --with-entities --no-dry-run --no-whitespace --no-bail --no-install-path --no-skip-regenerate --no-skip-yo-resolve --from-jdl --no-skip-cache --no-skip-install --no-force-install --no-ask-answered --no-defaults --no-skip-git
    at ChildProcess.<anonymous> (/Users/mraible/dev/generator-jhipster/cli/import-jdl.js:194:16)
    at ChildProcess.emit (events.js:376:20)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
ERROR! Command failed with exit code 1: npm install
Error: Command failed with exit code 1: npm install
    at makeError (/Users/mraible/dev/generator-jhipster/node_modules/yeoman-environment/node_modules/execa/lib/error.js:59:11)
    at handlePromise (/Users/mraible/dev/generator-jhipster/node_modules/yeoman-environment/node_modules/execa/index.js:114:26)
    at processTicksAndRejections (internal/process/task_queues.js:95:5) {
  shortMessage: 'Command failed with exit code 1: npm install',
  command: 'npm install',
  exitCode: 1,
  signal: undefined,
  signalDescription: undefined,
  stdout: undefined,
  stderr: undefined,
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
```

**Comment by mshima** [comment]
What `take reactive-stack` is suppose to do?
Could not reproduce using
```
git init
jhipster jdl reactive-ms
```

**Comment by mraible** [comment]
`take` is an alias for `mkdir` and `cd`. So it's the same as the following:

```
mkdir reactive-stack
cd reactive-stack
git init
jhipster jdl reactive-ms
```

I just tried again with the `main` branch and it works. I must've been using a released version before.
