### ISSUE TITLE
Cannot monitor JHipster app on Heroku with New Relic

### ISSUE THREAD

**Issue by mraible** [jhipster/generator-jhipster#1619]
When I first started deploying my JHipster application to Heroku, I did it with using "git push heroku master". Now when I try this, I get errors and the build fails. I'm using JHipster 2.16.0.

With Gradle:

```
remote:        :compileJava
remote:        :compileScala UP-TO-DATE
remote:        :bower FAILED
remote:
remote:        FAILURE: Build failed with an exception.
remote:
remote:        * What went wrong:
remote:        Execution failed for task ':bower'.
remote:        > A problem occurred starting process 'command 'bower''
```

Buildpacks:

```
1. https://github.com/heroku/heroku-buildpack-gradle.git
2. https://github.com/heroku/heroku-buildpack-nodejs.git
```

With Maven:

```
remote:        [INFO] node version :
remote:        [INFO] ------------------------------------------------------------------------
remote:        [INFO] BUILD FAILURE
remote:        [INFO] ------------------------------------------------------------------------
remote:        [INFO] Total time: 18.979 s
remote:        [INFO] Finished at: 2015-06-17T23:43:11+00:00
remote:        [INFO] Final Memory: 39M/551M
remote:        [INFO] ------------------------------------------------------------------------
remote:        [ERROR] Failed to execute goal com.github.trecloux:yeoman-maven-plugin:0.4:build 
    (run-frontend-build) on project jhipster-blog: Error during : node --version: Cannot run program 
    "node" (in directory "/tmp/build_b176f8a7fe8ada92be7b260818c8886a"): error=2, No such file or 
    directory -> [Help 1]
remote:        [ERROR]
```

Buildpacks:

```
1. https://github.com/heroku/heroku-buildpack-java.git
2. https://github.com/heroku/heroku-buildpack-nodejs.git
```

Now that I'm using `heroku deploy:jar`, there's no way to add a newrelic.jar to my project and use it to enable New Relic monitoring.

Here's the documentation for enabling New Relic on Heroku:

https://devcenter.heroku.com/articles/newrelic#java-installation-and-configuration

I'm opening this ticket in hopes of finding a way to monitor my JHipster application with New Relic.

**Comment by jdubois** [comment]
Looks like you need to enter a credit card to test New Relic, which I am not ready to do!
Normally you should just click somewhere on the dashboard to add the monitoring -> if it doesn't, can you post a stacktrace? Or maybe cross-post this to the New Relic ticket system, if there is one that is openly accessible to everyone?

**Comment by mraible** [comment]
The problem is that you need to upload a newrelic.jar as part of your application. See instructions at:

https://devcenter.heroku.com/articles/newrelic#java-installation-and-configuration

Since the new deployment model for JHipster/Heroku only uploads a single WAR, it's not possible to add the newrelic.jar as well.

**Comment by deepu105** [comment]
@mraible is this still an issue? its been open for a while so im closing it. Plz reopen this if you think its a JHipster issue. cheers

**Comment by mraible** [comment]
This is still an issue. I can see two ways to fix it on Heroku:

1. Get the source deploy working so I can "git push heroku" and have the build happen there. This is how JHipster's Heroku support used to work.
2. Figure out how to deploy two JARs on Heroku using the heroku-deploy plugin.

I've opened a support ticket with Heroku to try and solve this from their side.

**Comment by jkutner** [comment]
To include the New Relic agent JAR in the slug, run a command like this:

```
$ heroku deploy:jar --jar jhipsterapp.jar --includes newrelic-agent.jar
```

Then modify your `Procfile` to include the `-javaagent:newrelic-agent.jar` option.

To deploy by pushing the source code, you can follow this guide:
http://jkutner.github.io/2015/05/25/jhipster-heroku-git.html

**Comment by mraible** [comment]
@jkutner Is it possible to include multiple files with '--includes'? I need to upload newrelic.jar and newrelic.yml (for license key). I tried `--includes newrelic.*`, but it only picks up the newrelic.jar.

**Comment by jkutner** [comment]
@mraible yes. you can provide a `File.pathSeparator` delimited list

**Comment by mraible** [comment]
On second thought, maybe I don't need to upload both newrelic.jar and newrelic.yml. It looks like I have the following environment variables set.

````
JAVA_OPTS:                   -javaagent:newrelic.jar
MAVEN_CUSTOM_OPTS:           -Pprod,heroku -DskipTests
NEW_RELIC_APP_NAME:          My Application
NEW_RELIC_LICENSE_KEY:       xxx
NEW_RELIC_LOG:               stdout
````

However, I'm not seeing any activity in my New Relic console.

**Comment by jkutner** [comment]
@mraible i hear that a lot from people. and in my experience, it sometimes takes a few tries for New Relic to pick up the app. I think it's a problem on their end.

**Comment by jkutner** [comment]
oh, and if you're deploying with Maven, you can just use the `maven-dependency-plugin` to copy the agent JAR into the slug. I'll try to find an example of that.

**Comment by jkutner** [comment]
Scroll down to "Java agent installation with Maven" https://docs.newrelic.com/docs/agents/java-agent/installation/java-agent-heroku

**Comment by mraible** [comment]
@jkutner It doesn't appear like my JAVA_OPTS is getting picked up. when I start my app, I see the following message:

````
2015-10-21T16:59:23.093857+00:00 heroku[web.1]: Starting process with command `java -jar target/*.war --spring.profiles.active=prod,heroku --server.port=41484 --jhipster.metrics.jmx.enabled=false --spring.datasource.jmx-enabled=false --spring.jmx.enabled=false --management.security.enabled=false --endpoints.jmx.enabled=false --spring.datasource.max-active=5`
2015-10-21T16:59:24.055045+00:00 app[web.1]: [INFO] org.jhipster.book.config.CacheConfiguration - Closing Cache Manager
2015-10-21T16:59:24.038373+00:00 app[web.1]: [INFO] org.jhipster.book.config.CacheConfiguration - Remove Cache Manager metrics
2015-10-21T16:59:25.247545+00:00 app[web.1]: Picked up JAVA_TOOL_OPTIONS: -Xmx768m -Dfile.encoding=UTF-8
2015-10-21T16:59:25.243848+00:00 app[web.1]: Setting JAVA_TOOL_OPTIONS defaults based on dyno size. Custom settings will override them.
```

There's nothing in here these messages (or other startup messages) that indicate newrelic.jar is being picked up. 

Should I have `--javaagent:newrelic.jar` in my `Procfile` instead?

**Comment by jkutner** [comment]
`JAVA_OPTS` won't be automatically picked up by the JVM. It's only a convention used by a lot of frameworks, so you'd have to explicitly put it in the `java` command. Or you could override JAVA_TOOL_OPTIONS and I think _JAVA_OPTIONS works too, but I'm unsure of the precedence between those..

**Comment by jkutner** [comment]
We could put `$JAVA_OPTS` in the default `Procfile` jhipster generates.

**Comment by mraible** [comment]
I think adding `$JAVA_OPTS` to the generated `Procfile` would be a good idea. However, I noticed that after adding `-javaagent` that it expects the configuration file too. 

```
2015-10-21T17:16:16.231316+00:00 heroku[web.1]: Starting process with command `java -javaagent:newrelic.jar -jar target/*.war --spring.profiles.active=prod,heroku --server.port=38622 --jhipster.metrics.jmx.enabled=false --spring.datasource.jmx-enabled=false --spring.jmx.enabled=false --management.security.enabled=false --endpoints.jmx.enabled=false --spring.datasource.max-active=5`
2015-10-21T17:16:17.221377+00:00 app[web.1]: [INFO] org.jhipster.book.config.CacheConfiguration - Remove Cache Manager metrics
2015-10-21T17:16:17.235626+00:00 app[web.1]: [INFO] org.jhipster.book.config.CacheConfiguration - Closing Cache Manager
2015-10-21T17:16:18.130289+00:00 app[web.1]: Picked up JAVA_TOOL_OPTIONS: -Xmx768m -Dfile.encoding=UTF-8
2015-10-21T17:16:18.124970+00:00 app[web.1]: Setting JAVA_TOOL_OPTIONS defaults based on dyno size. Custom settings will override them.
2015-10-21T17:16:18.601463+00:00 heroku[web.1]: Process exited with status 143
2015-10-21T17:16:19.011792+00:00 app[web.1]: Oct 21, 2015 17:16:19 +0000 [3 1] com.newrelic ERROR: Unable to start New Relic agent: com.newrelic.agent.config.ConfigurationException: Failed to find the configuration file
2015-10-21T17:16:19.011797+00:00 app[web.1]: com.newrelic.agent.config.ConfigurationException: Failed to find the configuration file
2015-10-21T17:16:19.011799+00:00 app[web.1]: 	at com.newrelic.agent.config.ConfigServiceFactory.getConfigFile(ConfigServiceFactory.java:57) ~[newrelic.jar:3.21.0]
2015-10-21T17:16:19.011800+00:00 app[web.1]: 	at com.newrelic.agent.config.ConfigServiceFactory.createConfigService(ConfigServiceFactory.java:28) ~[newrelic.jar:3.21.0]
```

The [documentation](https://docs.newrelic.com/docs/agents/java-agent/installation/java-agent-heroku#java-config) made me think that the `newrelic.yml` wasn't necessary b/c the config variables were set.

The good news is I was able to use the following command:

```
heroku deploy:jar --jar target/*.war --includes newrelic.jar:newrelic.yml
```

And everything works now!

However, my logs are now filled with a bunch of New Relic messages:

```
2015-10-21T17:23:34.704508+00:00 app[web.1]: [DEBUG] global - http-outgoing-15 << "HTTP/1.1 200 OK[\r][\n]"
2015-10-21T17:23:34.706760+00:00 app[web.1]: [DEBUG] global - Connection [id: 15][route: {s}->https://collector-189.newrelic.com:443] can be kept alive indefinitely
2015-10-21T17:23:34.706923+00:00 app[web.1]: [DEBUG] global - Connection released: [id: 15][route: {s}->https://collector-189.newrelic.com:443][total kept alive: 1; route allocated: 1 of 2; total allocated: 1 of 20]
2015-10-21T17:23:34.707037+00:00 app[web.1]: [DEBUG] global - Connection manager is shutting down
2015-10-21T17:23:34.707159+00:00 app[web.1]: [DEBUG] global - http-outgoing-15: Close connection
2015-10-21T17:23:34.707587+00:00 app[web.1]: [DEBUG] global - http-outgoing-15: Close connection
2015-10-21T17:23:34.707686+00:00 app[web.1]: [DEBUG] global - Connection manager shut down
```

However, I believe I can configure this in the `newrelic.yml` file. The only strange thing is these messages show debug and my `newrelic.yml` shows `info`:

```
  # The agent uses its own log file to keep its logging
  # separate from that of your application.  Specify the log level here.
  # This setting is dynamic, so changes do not require restarting your application.
  # The levels in increasing order of verboseness are:
  #   off, severe, warning, info, fine, finer, finest
  # Default is info.
  log_level: info
```
