### ISSUE TITLE
TLS profile doesn't work with Gradle

### ISSUE THREAD

**Issue by mraible** [jhipster/generator-jhipster#16196]
##### **Overview of the issue**

I created a microservice architecture using the latest `main` branch and tried to run the gateway with [TLS](https://www.jhipster.tech/tls/).

```
./gradlew -Ptls
```

If fails to start:

```
Caused by: javax.net.ssl.SSLException: failed to set cipher suite: [TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256, TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384, TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA, TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA, TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256, TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384, TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256, TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384, TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA, TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA, TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256, TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384, TLS_DHE_RSA_WITH_AES_128_GCM_SHA256, TLS_DHE_RSA_WITH_AES_256_GCM_SHA384, TLS_DHE_RSA_WITH_AES_128_CBC_SHA, TLS_DHE_RSA_WITH_AES_256_CBC_SHA, TLS_DHE_RSA_WITH_AES_128_CBC_SHA256, TLS_DHE_RSA_WITH_AES_256_CBC_SHA256]
        at io.netty.handler.ssl.ReferenceCountedOpenSslContext.<init>(ReferenceCountedOpenSslContext.java:309)
        at io.netty.handler.ssl.OpenSslContext.<init>(OpenSslContext.java:45)
        at io.netty.handler.ssl.OpenSslServerContext.<init>(OpenSslServerContext.java:349)
        at io.netty.handler.ssl.OpenSslServerContext.<init>(OpenSslServerContext.java:336)
        at io.netty.handler.ssl.SslContext.newServerContextInternal(SslContext.java:473)
        at io.netty.handler.ssl.SslContextBuilder.build(SslContextBuilder.java:606)
        at reactor.netty.tcp.AbstractProtocolSslContextSpec.sslContext(AbstractProtocolSslContextSpec.java:53)
        at reactor.netty.tcp.SslProvider.<init>(SslProvider.java:366)
        ... 21 common frames omitted
Caused by: java.lang.IllegalArgumentException: unsupported cipher suite: TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256(ECDHE-ECDSA-AES128-SHA256)
        at io.netty.handler.ssl.CipherSuiteConverter.convertToCipherStrings(CipherSuiteConverter.java:470)
        at io.netty.handler.ssl.ReferenceCountedOpenSslContext.<init>(ReferenceCountedOpenSslContext.java:295)
        ... 28 common frames omitted
```

##### **Motivation for or Use Case**

It should work as explained in the docs.

##### **Reproduce the error**

```
jhipster jdl reactive-ms
cd gateway
jhkeycloakup
jhregistryup
./gradlew -Ptls
```

##### **JHipster Version(s)**

`main` branch.

##### **Browsers and Operating System**

macOS Big Sur 11.5.2

**Comment by atomfrede** [comment]
Removing all ["weak" cypher suites using DHE](https://ciphersuite.info/cs/TLS_DHE_RSA_WITH_AES_256_CBC_SHA256/) key exchanges seem to do the trick. Looks like a netty or boring ssl update removed these cyphers from supported suites.

![image](https://user-images.githubusercontent.com/203401/132398875-7453d40d-ba0b-4c79-b7ee-66a97b0649b3.png)
