### ISSUE TITLE
 jhipster import-jdl crashes with Error running generator entities: Error: Enumeration values must be passed to get the formatted values.

### ISSUE THREAD

**Issue by naris** [jhipster/generator-jhipster#16308]
##### **Overview of the issue**

I have a simple jdl that defines a single entity with only String, Number, Integer & LocalDate fields.
When running  jhipster import-jdl on the file it crashes with:

jhipster import-jdl  .\src\main\resources\jdl\programme.jdl                                                                                           ─╯ 
INFO! Using JHipster version installed locally in current project's node_modules
INFO! No custom sharedOptions found within blueprint: generator-jhipster-primeng-blueprint at C:/src/metadater/node_modules/generator-jhipster-primeng-blueprint
INFO! No custom commands found within blueprint: generator-jhipster-primeng-blueprint at C:/src/metadater/node_modules/generator-jhipster-primeng-blueprint
INFO! Executing import-jdl .\src\main\resources\jdl\programme.jdl
INFO! The JDL is being parsed.
Blueprints are being used, the JDL validation phase is skipped.
INFO! Found entities: Programme.
INFO! The JDL has been successfully parsed
INFO! Generating 0 applications.
INFO! Generating 1 entity.
INFO! Generating entities for application undefined in a new parallel process

Found the .jhipster\Programme.json configuration file, entity can be automatically generated!

     info Creating changelog for entities Programme
     info Using blueprint generator-jhipster-primeng-blueprint for entity-client subgenerator
     info Using blueprint generator-jhipster-primeng-blueprint for entity-i18n subgenerator
Error running generator entities: Error: Enumeration values must be passed to get the formatted values.
Error: Enumeration values must be passed to get the formatted values.
    at getEnumValuesWithCustomValues (C:\src\metadater\node_modules\generator-jhipster\utils\field.js:335:11)
    at prepareFieldForTemplates (C:\src\metadater\node_modules\generator-jhipster\utils\field.js:241:24)
    at C:\src\metadater\node_modules\generator-jhipster\generators\entity\index.js:582:11
    at Array.forEach (<anonymous>)
    at EntityGenerator.prepareFieldsForTemplates (C:\src\metadater\node_modules\generator-jhipster\generators\entity\index.js:581:29)
    at Object.<anonymous> (C:\src\metadater\node_modules\yeoman-generator\lib\index.js:1009:25)
    at C:\src\metadater\node_modules\run-async\index.js:49:25
    at new Promise (<anonymous>)
    at C:\src\metadater\node_modules\run-async\index.js:26:19
    at runLoop.add.once.once (C:\src\metadater\node_modules\yeoman-generator\lib\index.js:1010:11)
    at Immediate.<anonymous> (C:\src\metadater\node_modules\grouped-queue\lib\subqueue.js:48:34)
    at processImmediate (internal/timers.js:461:21)
ERROR! Enumeration values must be passed to get the formatted values.
Error: Enumeration values must be passed to get the formatted values.
    at getEnumValuesWithCustomValues (C:\src\metadater\node_modules\generator-jhipster\utils\field.js:335:11)
    at prepareFieldForTemplates (C:\src\metadater\node_modules\generator-jhipster\utils\field.js:241:24)
    at C:\src\metadater\node_modules\generator-jhipster\generators\entity\index.js:582:11
    at Array.forEach (<anonymous>)
    at EntityGenerator.prepareFieldsForTemplates (C:\src\metadater\node_modules\generator-jhipster\generators\entity\index.js:581:29)
    at Object.<anonymous> (C:\src\metadater\node_modules\yeoman-generator\lib\index.js:1009:25)
    at C:\src\metadater\node_modules\run-async\index.js:49:25
    at new Promise (<anonymous>)
    at C:\src\metadater\node_modules\run-async\index.js:26:19
    at runLoop.add.once.once (C:\src\metadater\node_modules\yeoman-generator\lib\index.js:1010:11)
    at Immediate.<anonymous> (C:\src\metadater\node_modules\grouped-queue\lib\subqueue.js:48:34)
    at processImmediate (internal/timers.js:461:21)

##### **Motivation for or Use Case**

This prevents me from using any entities and/or JDL

##### **Reproduce the error**

install jhipster
install primeng-bluprint from https://github.com/elhoutico/jhipster-primeng-blueprint
create a jhipster project with the primeng-blueprint:
jhipster --blueprints primeng-blueprint --skip-checks

Create this JDL file

entity Programme (gref_programme) {
	programmeId Number required,
    metadataStatusLcd Number,
    countryCd String maxlength(5),
    waveNo Integer,
    progStartDt LocalDate,
    progEndDt LocalDate,
    updtDt LocalDate,
    updtQuestionerId Integer,
    progShortNm String maxlength(50),
    progLongNm String maxlength(255),
    refreshedFlg String maxlength(1)
}

attempt to import it
jhipster import-jdl  programme.jdl 

##### **Related issues**

Searching for "Error: Enumeration values must be passed to get the formatted values." yields nothing

##### **Suggest a Fix**

I have no suggested fix.

##### **JHipster Version(s)**

7.0.1

##### **JHipster configuration**

jhipster import-jdl  .\src\main\resources\jdl\programme.jdl If you have a JDL please wrap it in below structure
  <details>
  <summary>JDL definitions</summary>
  <pre>
     JDL content here
  </pre>
  </details>
-->

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

.jhipster directory is empty

##### **Browsers and Operating System**

Windoows 10 Enterprise 1909

- [X] Checking this box is mandatory (this is just to show you read everything)

**Comment by naris** [comment]
This is PEBCAK, Number is not a valid type in JDL
