### ISSUE TITLE
Unable to Upgrade to 7.2.0

### ISSUE THREAD

**Issue by vw98075** [jhipster/generator-jhipster#16317]
##### **Overview of the issue**

I installed the 7.1.0 about three months ago. Due to a few bugs in the release, I need to upgrade to a newer release as I have learned that those bugs are fixed in the release. I get the error when I tried to do the upgrade.
```
 % jhipster upgrade
INFO! Using JHipster version installed globally
ERROR! This seems to be an app blueprinted project with jhipster 6.6.0 bug (https://github.com/jhipster/generator-jhipster/issues/11045), you should pass --blueprints to jhipster upgrade commmand.
Error: This seems to be an app blueprinted project with jhipster 6.6.0 bug (https://github.com/jhipster/generator-jhipster/issues/11045), you should pass --blueprints to jhipster upgrade commmand.
    at module.exports.error (/usr/local/lib/node_modules/generator-jhipster/generators/generator-base.js:1823:11)
    at new module.exports (/usr/local/lib/node_modules/generator-jhipster/generators/upgrade/index.js:94:12)
    at Environment.instantiate (/usr/local/lib/node_modules/generator-jhipster/node_modules/yeoman-environment/lib/environment.js:802:23)
    at Environment.create (/usr/local/lib/node_modules/generator-jhipster/node_modules/yeoman-environment/lib/environment.js:774:17)
    at instantiateAndRun (/usr/local/lib/node_modules/generator-jhipster/node_modules/yeoman-environment/lib/environment.js:987:36)
    at Environment.run (/usr/local/lib/node_modules/generator-jhipster/node_modules/yeoman-environment/lib/environment.js:1004:12)
    at JHipsterCommand.<anonymous> (/usr/local/lib/node_modules/generator-jhipster/cli/program.js:190:20)
    at JHipsterCommand.listener [as _actionHandler] (/usr/local/lib/node_modules/generator-jhipster/node_modules/commander/lib/command.js:488:17)
    at /usr/local/lib/node_modules/generator-jhipster/node_modules/commander/lib/command.js:1207:65
    at JHipsterCommand._chainOrCall (/usr/local/lib/node_modules/generator-jhipster/node_modules/commander/lib/command.js:1124:12)
```
I don't know how a bug in 6.6.0 shows up 7.2.0.

##### **Browsers and Operating System**

- [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by atomfrede** [comment]
Can you try `jhipster upgrade --blueprints` as the message suggests?

**Comment by mshima** [comment]
`.yo-rc.json` looks missing or invalid.
We need to improve error message.

**Comment by vw98075** [comment]
I pull our repo in the new directory this morning. The upgrade command runs smoothly. Very strange. Anyway, I guess this ticket can be closed.

**Comment by pascalgrimaud** [comment]
Ok thanks for the feedbacks
Don't hesitate to comment this ticket and we can reopen it if needed
