### ISSUE TITLE
On application startup, SpringApplicationShutdownHook fails with ArrayIndexOutOfBoundsException when connection to MongoDB times out 

### ISSUE THREAD

**Issue by nagarajasr** [jhipster/generator-jhipster#16334]
##### **Overview of the issue**

On application startup, SpringApplicationShutdownHook fails with ArrayIndexOutOfBoundsException when connection to MongoDB times out (for e.g., DB is not running)

Stack trace:
```
[INFO] Attaching agents: []

        ██╗ ██╗   ██╗ ████████╗ ███████╗   ██████╗ ████████╗ ████████╗ ███████╗
        ██║ ██║   ██║ ╚══██╔══╝ ██╔═══██╗ ██╔════╝ ╚══██╔══╝ ██╔═════╝ ██╔═══██╗
        ██║ ████████║    ██║    ███████╔╝ ╚█████╗     ██║    ██████╗   ███████╔╝
  ██╗   ██║ ██╔═══██║    ██║    ██╔════╝   ╚═══██╗    ██║    ██╔═══╝   ██╔══██║
  ╚██████╔╝ ██║   ██║ ████████╗ ██║       ██████╔╝    ██║    ████████╗ ██║  ╚██╗
   ╚═════╝  ╚═╝   ╚═╝ ╚═══════╝ ╚═╝       ╚═════╝     ╚═╝    ╚═══════╝ ╚═╝   ╚═╝

:: JHipster ?  :: Running Spring Boot 2.5.4 ::
:: https://www.jhipster.tech ::

2021-09-18 15:22:28.641  INFO 17348 --- [  restartedMain] com.infosys.sos.studio.SosStudioApp      : The following profiles are active: dev,api-docs
2021-09-18 15:22:31.561 DEBUG 17348 --- [  restartedMain] jdk.event.security                       : X509Certificate: Alg:SHA1withDSA, Serial:10, Subject:CN=JCE Code Signing CA, OU=Java Software Code Signing, O=Sun Microsystems Inc, L=Palo Alto, ST=CA, C=US, Issuer:CN=JCE Code Signing CA, OU=Java Software Code Signing, O=Sun Microsystems Inc, L=Palo Alto, ST=CA, C=US, Key type:DSA, Length:1024, Cert Id:1776909028, Valid from:4/25/01, 12:30 PM, Valid until:4/25/20, 12:30 PM
2021-09-18 15:22:31.568 DEBUG 17348 --- [  restartedMain] jdk.event.security                       : X509Certificate: Alg:SHA1withDSA, Serial:47f, Subject:CN=Legion of the Bouncy Castle Inc., OU=Java Software Code Signing, O=Sun Microsystems Inc, Issuer:CN=JCE Code Signing CA, OU=Java Software Code Signing, O=Sun Microsystems Inc, L=Palo Alto, ST=CA, C=US, Key type:DSA, Length:1024, Cert Id:-2023852845, Valid from:3/11/17, 6:45 AM, Valid until:4/25/20, 12:30 PM
2021-09-18 15:22:31.596 DEBUG 17348 --- [  restartedMain] jdk.event.security                       : X509Certificate: Alg:SHA1withRSA, Serial:3019a023aff58b16bd6d5eae617f066, Subject:CN=DigiCert Timestamp Responder, O=DigiCert, C=US, Issuer:CN=DigiCert Assured ID CA-1, OU=www.digicert.com, O=DigiCert Inc, C=US, Key type:RSA, Length:2048, Cert Id:-499520198, Valid from:10/22/14, 5:30 AM, Valid until:10/22/24, 5:30 AM
2021-09-18 15:22:31.601 DEBUG 17348 --- [  restartedMain] jdk.event.security                       : X509Certificate: Alg:SHA1withRSA, Serial:6fdf9039603adea000aeb3f27bbba1b, Subject:CN=DigiCert Assured ID CA-1, OU=www.digicert.com, O=DigiCert Inc, C=US, Issuer:CN=DigiCert Assured ID Root CA, OU=www.digicert.com, O=DigiCert Inc, C=US, Key type:RSA, Length:2048, Cert Id:-1111363278, Valid from:11/10/06, 5:30 AM, Valid until:11/10/21, 5:30 AM
2021-09-18 15:22:31.643 DEBUG 17348 --- [  restartedMain] jdk.event.security                       : X509Certificate: Alg:SHA256withRSA, Serial:3c9eb1fc89f733d3, Subject:CN=JCE Code Signing CA, OU=Java Software Code Signing, O=Oracle Corporation, Issuer:CN=JCE Code Signing CA, OU=Java Software Code Signing, O=Oracle Corporation, Key type:RSA, Length:2048, Cert Id:-1250580323, Valid from:7/7/16, 5:18 AM, Valid until:12/31/30, 5:30 AM
2021-09-18 15:22:31.647 DEBUG 17348 --- [  restartedMain] jdk.event.security                       : X509Certificate: Alg:SHA256withRSA, Serial:4efb7bc62e2b049e, Subject:CN=Legion of the Bouncy Castle Inc., OU=Java Software Code Signing, O=Oracle Corporation, Issuer:CN=JCE Code Signing CA, OU=Java Software Code Signing, O=Oracle Corporation, Key type:DSA, Length:2048, Cert Id:-654023182, Valid from:3/11/17, 6:37 AM, Valid until:3/11/22, 6:37 AM
2021-09-18 15:22:31.652 DEBUG 17348 --- [  restartedMain] jdk.event.security                       : X509Certificate: Alg:SHA256withRSA, Serial:4cd3f8568ae76c61bb0fe7160cca76d, Subject:CN=TIMESTAMP-SHA256-2019-10-15, O="DigiCert, Inc.", C=US, Issuer:CN=DigiCert SHA2 Assured ID Timestamping CA, OU=www.digicert.com, O=DigiCert Inc, C=US, Key type:RSA, Length:2048, Cert Id:380147180, Valid from:10/1/19, 5:30 AM, Valid until:10/17/30, 5:30 AM
2021-09-18 15:22:31.656 DEBUG 17348 --- [  restartedMain] jdk.event.security                       : X509Certificate: Alg:SHA256withRSA, Serial:aa125d6d6321b7e41e405da3697c215, Subject:CN=DigiCert SHA2 Assured ID Timestamping CA, OU=www.digicert.com, O=DigiCert Inc, C=US, Issuer:CN=DigiCert Assured ID Root CA, OU=www.digicert.com, O=DigiCert Inc, C=US, Key type:RSA, Length:2048, Cert Id:-1680473293, Valid from:1/7/16, 5:30 PM, Valid until:1/7/31, 5:30 PM
2021-09-18 15:22:31.961 DEBUG 17348 --- [  restartedMain] i.m.c.u.i.logging.InternalLoggerFactory  : Using SLF4J as the default logging framework
2021-09-18 15:22:32.128 DEBUG 17348 --- [  restartedMain] c.i.sos.studio.config.WebConfigurer      : Registering CORS filter
2021-09-18 15:22:32.170  INFO 17348 --- [  restartedMain] c.i.sos.studio.config.WebConfigurer      : Web application configuration, using profiles: dev
2021-09-18 15:22:32.172  INFO 17348 --- [  restartedMain] c.i.sos.studio.config.WebConfigurer      : Web application fully configured
2021-09-18 15:22:32.376 DEBUG 17348 --- [  restartedMain] c.i.s.studio.security.jwt.TokenProvider  : Using a Base64-encoded JWT secret key
2021-09-18 15:22:33.619 DEBUG 17348 --- [  restartedMain] c.ehcache.core.Ehcache-usersByLogin      : Initialize successful.
2021-09-18 15:22:33.650 DEBUG 17348 --- [  restartedMain] c.ehcache.core.Ehcache-usersByEmail      : Initialize successful.
2021-09-18 15:22:34.593 DEBUG 17348 --- [  restartedMain] t.j.c.apidoc.SpringfoxAutoConfiguration  : Starting OpenAPI docs
2021-09-18 15:22:34.602 DEBUG 17348 --- [  restartedMain] t.j.c.apidoc.SpringfoxAutoConfiguration  : Started OpenAPI docs in 7 ms
2021-09-18 15:22:34.642 DEBUG 17348 --- [  restartedMain] c.i.s.studio.config.AsyncConfiguration   : Creating Async Task Executor
2021-09-18 15:23:04.734  WARN 17348 --- [  restartedMain] ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'connectionDriver' defined in class path resource [com/github/cloudyrock/mongock/driver/mongodb/springdata/v3/config/SpringDataMongoV3Context.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.github.cloudyrock.mongock.driver.api.driver.ConnectionDriver]: Factory method 'connectionDriver' threw exception; nested exception is com.mongodb.MongoTimeoutException: Timed out after 30000 ms while waiting to connect. Client view of cluster state is {type=UNKNOWN, servers=[{address=localhost:27017, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSocketOpenException: Exception opening socket}, caused by {java.net.ConnectException: Connection refused: connect}}]
2021-09-18 15:23:04.750 DEBUG 17348 --- [  restartedMain] c.ehcache.core.Ehcache-usersByEmail      : Close successful.
2021-09-18 15:23:04.752 DEBUG 17348 --- [  restartedMain] c.ehcache.core.Ehcache-usersByLogin      : Close successful.
2021-09-18 15:23:04.825 ERROR 17348 --- [  restartedMain] o.s.boot.SpringApplication               : Application run failed

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'connectionDriver' defined in class path resource [com/github/cloudyrock/mongock/driver/mongodb/springdata/v3/config/SpringDataMongoV3Context.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.github.cloudyrock.mongock.driver.api.driver.ConnectionDriver]: Factory method 'connectionDriver' threw exception; nested exception is com.mongodb.MongoTimeoutException: Timed out after 30000 ms while waiting to connect. Client view of cluster state is {type=UNKNOWN, servers=[{address=localhost:27017, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSocketOpenException: Exception opening socket}, caused by {java.net.ConnectException: Connection refused: connect}}]
        at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:658)
        at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:638)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1334)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1177)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:564)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:524)
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:944)
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:918)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583)
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:145)
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:754)
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:434)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:338)
        at com.infosys.sos.studio.SosStudioApp.main(SosStudioApp.java:68)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.springframework.boot.devtools.restart.RestartLauncher.run(RestartLauncher.java:49)
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.github.cloudyrock.mongock.driver.api.driver.ConnectionDriver]: Factory method 'connectionDriver' threw exception; nested exception is com.mongodb.MongoTimeoutException: Timed out after 30000 ms while waiting to connect. Client view of cluster state is {type=UNKNOWN, servers=[{address=localhost:27017, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSocketOpenException: Exception opening socket}, caused by {java.net.ConnectException: Connection refused: connect}}]
        at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185)
        at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:653)
        ... 22 common frames omitted
Caused by: com.mongodb.MongoTimeoutException: Timed out after 30000 ms while waiting to connect. Client view of cluster state is {type=UNKNOWN, servers=[{address=localhost:27017, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSocketOpenException: Exception opening socket}, caused by {java.net.ConnectException: Connection refused: connect}}]
        at com.mongodb.internal.connection.BaseCluster.getDescription(BaseCluster.java:177)
        at com.mongodb.internal.connection.SingleServerCluster.getDescription(SingleServerCluster.java:41)
        at com.mongodb.client.internal.MongoClientDelegate.getConnectedClusterDescription(MongoClientDelegate.java:127)
        at com.mongodb.client.internal.MongoClientDelegate.createClientSession(MongoClientDelegate.java:87)
        at com.mongodb.client.internal.MongoClientDelegate$DelegateOperationExecutor.getClientSession(MongoClientDelegate.java:258)
        at com.mongodb.client.internal.MongoClientDelegate$DelegateOperationExecutor.execute(MongoClientDelegate.java:162)
        at com.mongodb.client.internal.MongoIterableImpl.execute(MongoIterableImpl.java:135)
        at com.mongodb.client.internal.MongoIterableImpl.iterator(MongoIterableImpl.java:92)
        at com.mongodb.client.internal.MongoIterableImpl.forEach(MongoIterableImpl.java:121)
        at com.github.cloudyrock.mongock.driver.mongodb.sync.v4.repository.MongoSync4RepositoryBase.getResidualKeys(MongoSync4RepositoryBase.java:77)
        at com.github.cloudyrock.mongock.driver.mongodb.sync.v4.repository.MongoSync4RepositoryBase.isIndexFine(MongoSync4RepositoryBase.java:65)
        at com.github.cloudyrock.mongock.driver.mongodb.sync.v4.repository.MongoSync4RepositoryBase.ensureIndex(MongoSync4RepositoryBase.java:52)
        at com.github.cloudyrock.mongock.driver.mongodb.sync.v4.repository.MongoSync4RepositoryBase.initialize(MongoSync4RepositoryBase.java:43)
        at com.github.cloudyrock.mongock.driver.core.driver.ConnectionDriverBase.initialize(ConnectionDriverBase.java:40)
        at com.github.cloudyrock.mongock.driver.mongodb.springdata.v3.config.SpringDataMongoV3Context.connectionDriver(SpringDataMongoV3Context.java:27)
        at com.github.cloudyrock.mongock.driver.mongodb.springdata.v3.config.SpringDataMongoV3Context$$EnhancerBySpringCGLIB$$1df3f05e.CGLIB$connectionDriver$0(<generated>)
        at com.github.cloudyrock.mongock.driver.mongodb.springdata.v3.config.SpringDataMongoV3Context$$EnhancerBySpringCGLIB$$1df3f05e$$FastClassBySpringCGLIB$$e5a297d5.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:244)
        at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:331)
        at com.github.cloudyrock.mongock.driver.mongodb.springdata.v3.config.SpringDataMongoV3Context$$EnhancerBySpringCGLIB$$1df3f05e.connectionDriver(<generated>)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154)
        ... 23 common frames omitted

Exception in thread "SpringApplicationShutdownHook" java.lang.ArrayIndexOutOfBoundsException: arraycopy: length -2 is negative
        at java.base/java.lang.System.arraycopy(Native Method)
        at java.base/java.util.ArrayList.shiftTailOverGap(ArrayList.java:778)
        at java.base/java.util.ArrayList.batchRemove(ArrayList.java:871)
        at java.base/java.util.ArrayList.retainAll(ArrayList.java:843)
        at ch.qos.logback.classic.LoggerContext.resetListenersExceptResetResistant(LoggerContext.java:305)
        at ch.qos.logback.classic.LoggerContext.reset(LoggerContext.java:227)
        at ch.qos.logback.classic.LoggerContext.stop(LoggerContext.java:348)
        at org.springframework.boot.logging.logback.LogbackLoggingSystem.lambda$getShutdownHandler$0(LogbackLoggingSystem.java:284)
        at java.base/java.lang.Iterable.forEach(Iterable.java:75)
        at org.springframework.boot.SpringApplicationShutdownHook.run(SpringApplicationShutdownHook.java:102)
        at java.base/java.lang.Thread.run(Thread.java:834)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:13 min
[INFO] Finished at: 2021-09-18T15:23:05+05:30
[INFO] ------------------------------------------------------------------------


```

##### **Motivation for or Use Case**

Shutdown hook

##### **Reproduce the error**

Try to start a JHipster monolithic application using MongoDB for persistence without a running database

##### **Related issues**

No related issue could be found in Github issues.

##### **JHipster Version(s)**

7.2.0

##### **JHipster configuration**

jhipster info
INFO! Using JHipster version installed locally in current project's node_modules
Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
my-app@0.0.1-SNAPSHOT D:\me\projects\my-app
`-- generator-jhipster@7.2.0

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "applicationType": "monolith",
    "baseName": "sos_studio",
    "jhipsterVersion": "7.2.0",
    "skipClient": false,
    "skipServer": false,
    "skipUserManagement": false,
    "skipCheckLengthOfIdentifier": false,
    "skipFakeData": false,
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "testFrameworks": ["cypress", "gatling", "cucumber"],
    "blueprints": [],
    "otherModules": [],
    "pages": [],
    "creationTimestamp": 1631949175709,
    "serviceDiscoveryType": "no",
    "reactive": false,
    "authenticationType": "jwt",
    "packageName": "com.blah.blah.blah",
    "serverPort": "8080",
    "cacheProvider": "ehcache",
    "enableHibernateCache": false,
    "databaseType": "mongodb",
    "devDatabaseType": "mongodb",
    "prodDatabaseType": "mongodb",
    "buildTool": "maven",
    "serverSideOptions": [],
    "websocket": false,
    "searchEngine": false,
    "messageBroker": false,
    "enableSwaggerCodegen": false,
    "clientFramework": "angularX",
    "withAdminUi": true,
    "clientTheme": "cosmo",
    "clientThemeVariant": "primary",
    "enableTranslation": false,
    "nativeLanguage": "en",
    "jwtSecretKey": "YourJWTSecretKeyWasReplacedByThisMeaninglessTextByTheJHipsterInfoCommandForObviousSecurityReasons",
    "devServerPort": 4200,
    "clientPackageManager": "npm",
    "enableGradleEnterprise": false,
    "languages": ["en", "fr"],
    "cypressCoverage": false
  }
}

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

openjdk version "11.0.9" 2020-10-20 LTS
OpenJDK Runtime Environment Zulu11.43+21-NV (build 11.0.9+11-LTS)
OpenJDK 64-Bit Server VM Zulu11.43+21-NV (build 11.0.9+11-LTS, mixed mode)

git version 2.23.0.windows.5

node: v14.17.6

npm: 7.24.0

No change to package.json was detected. No package manager install will be executed.
Congratulations, JHipster execution is complete!
Sponsored with ❤️  by @oktadev.

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

not relevant

##### **Browsers and Operating System**

Windows 10. Not a browser issue

- [X] Checking this box is mandatory (this is just to show you read everything)

**Comment by pascalgrimaud** [comment]
What do you expect from the logs ?
As the database is down, I think it's normal there is a stacktrace, and it depends on this lib

**Comment by pascalgrimaud** [comment]
So nothing related to JHipster here, it's related to cloudyrock mongock lib
