### ISSUE TITLE
Error on Heroku deploy using Hazelcast ( master branch )

### ISSUE THREAD

**Issue by phouverneyuff** [jhipster/generator-jhipster#1647]
@jdubois , after update the jhipster to master (we update hazelcast and we changed how to initialize one instance) and to update my app, when deploying to the heroku, the following error occur:

```LOG
config.hazelcast.HazelcastCacheRegionFactory - Starting up HazelcastCacheRegionFactory
2015-06-25T04:02:40.117480+00:00 app[web.1]: [WARN] org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext - Exception encountered during context initialization - cancelling refresh attempt
2015-06-25T04:02:40.117485+00:00 app[web.1]: org.springframework.context.ApplicationContextException: Unable to start embedded container; nested exception is org.springframework.boot.context.embedded.EmbeddedServletContainerException: Unable to start embedded Tomcat
2015-06-25T04:02:40.117488+00:00 app[web.1]: 	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.onRefresh(EmbeddedWebApplicationContext.java:133) [spring-boot-1.2.4.RELEASE.jar!/:1.2.4.RELEASE]
2015-06-25T04:02:40.117490+00:00 app[web.1]: 	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:474) ~[spring-context-4.1.6.RELEASE.jar!/:4.1.6.RELEASE]
2015-06-25T04:02:40.117492+00:00 app[web.1]: 	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:118) [spring-boot-1.2.4.RELEASE.jar!/:1.2.4.RELEASE]
2015-06-25T04:02:40.117495+00:00 app[web.1]: 	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:686) [spring-boot-1.2.4.RELEASE.jar!/:1.2.4.RELEASE]
2015-06-25T04:02:40.117497+00:00 app[web.1]: 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:320) [spring-boot-1.2.4.RELEASE.jar!/:1.2.4.RELEASE]
2015-06-25T04:02:40.117499+00:00 app[web.1]: 	at br.com.bpssolucoes.Application.main(Application.java:72) [classes!/:na]
2015-06-25T04:02:40.117502+00:00 app[web.1]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_40-'cedar14']
2015-06-25T04:02:40.117504+00:00 app[web.1]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_40-'cedar14']
2015-06-25T04:02:40.117506+00:00 app[web.1]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_40-'cedar14']
2015-06-25T04:02:40.117508+00:00 app[web.1]: 	at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_40-'cedar14']
2015-06-25T04:02:40.117510+00:00 app[web.1]: 	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:53) [meupedido-0.1.0.war:na]
2015-06-25T04:02:40.117511+00:00 app[web.1]: 	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_40-'cedar14']
2015-06-25T04:02:40.117514+00:00 app[web.1]: Caused by: org.springframework.boot.context.embedded.EmbeddedServletContainerException: Unable to start embedded Tomcat

...


	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.onRefresh(EmbeddedWebApplicationContext.java:130) [spring-boot-1.2.4.RELEASE.jar!/:1.2.4.RELEASE]
2015-06-25T04:38:08.274455+00:00 app[web.1]: 	... 11 common frames omitted
2015-06-25T04:38:08.274467+00:00 app[web.1]: Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.security.config.annotation.web.configuration.WebSecurityConfiguration': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire method: public void org.springframework.security.config.annotation.web.configuration.WebSecurityConfiguration.setFilterChainProxySecurityConfigurer(org.springframework.security.config.annotation.ObjectPostProcessor,java.util.List) throws java.lang.Exception; nested exception is org.springframework.beans.factory.BeanExpressionException: Expression parsing failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'securityConfiguration': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: private org.springframework.security.core.userdetails.UserDetailsService br.com.bpssolucoes.config.SecurityConfiguration.userDetailsService; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'userDetailsService': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: private br.com.bpssolucoes.repository.UserRepository br.com.bpssolucoes.security.UserDetailsService.userRepository; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'userRepository': Cannot create inner bean '(inner bean)#31c32fef' of type [org.springframework.orm.jpa.SharedEntityManagerCreator] while setting bean property 'entityManager'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name '(inner bean)#31c32fef': Cannot resolve reference to bean 'entityManagerFactory' while setting constructor argument; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'entityManagerFactory' defined in class path resource [org/springframework/boot/autoconfigure/orm/jpa/HibernateJpaAutoConfiguration.class]: Invocation of init method failed; nested exception is org.hibernate.service.spi.ServiceException: Unable to create requested service [org.hibernate.engine.spi.CacheImplementor]
2015-06-25T04:38:08.274469+00:00 app[web.1]: 	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:334) ~[spring-beans-4.1.6.RELEASE.jar!/:4.1.6.RELEASE]

```

My .yo-rc.json
```json
{
  "generator-jhipster": {
    "baseName": "test",
    "packageName": "com.test",
    "packageFolder": "com/test",
    "authenticationType": "oauth2",
    "hibernateCache": "hazelcast",
    "clusteredHttpSession": "no",
    "websocket": "no",
    "databaseType": "sql",
    "devDatabaseType": "h2Memory",
    "prodDatabaseType": "postgresql",
    "searchEngine": "no",
    "useCompass": false,
    "buildTool": "gradle",
    "frontendBuilder": "grunt",
    "javaVersion": "8",
    "rememberMeKey": "REMOVED",
    "enableTranslation": true
  }
}%    
```

I created on branch in my app that works and other that not. 
I changed between them and I confirmed that the problem is with jhipster version.

**Comment by jdubois** [comment]
This is not exactly your issue, but I don't think you can have Hazelcast working with Heroku: Heroku works on top of AWS, so you can't do multicast. I don't know how you could have your distributed cache to work.

**Comment by phouverneyuff** [comment]
Maybe using Redis

**Comment by phouverneyuff** [comment]
@jdubois , using the version 2.16.1 it's works fine.

I tested again using Hibernate Hazelcast and works.

You can see that I'm using Heroku and Hibernate Hazelcast.

```log
.MulticastJoiner - [172.17.198.90]:5701 [dev] [3.4] 
2015-06-25T12:10:10.900995+00:00 app[web.1]: 
2015-06-25T12:10:10.900999+00:00 app[web.1]: Members [1] {
2015-06-25T12:10:10.900998+00:00 app[web.1]: 
2015-06-25T12:10:10.901002+00:00 app[web.1]: 	Member [172.17.198.90]:5701 this
2015-06-25T12:10:10.901004+00:00 app[web.1]: }
2015-06-25T12:10:10.901005+00:00 app[web.1]: 
2015-06-25T12:10:11.003209+00:00 app[web.1]: [INFO] com.hazelcast.core.LifecycleService - [172.17.198.90]:5701 [dev] [3.4] Address[172.17.198.90]:5701 is STARTED
2015-06-25T12:10:12.128294+00:00 app[web.1]: [DEBUG] org.jboss.logging - Logging Provider: org.jboss.logging.Slf4jLoggerProvider
2015-06-25T12:10:12.567220+00:00 app[web.1]: [DEBUG] br.com.bpssolucoes.config.AsyncConfiguration - Creating Async Task Executor
2015-06-25T12:10:13.523561+00:00 app[web.1]: [DEBUG] br.com.bpssolucoes.config.MetricsConfiguration - Registering JVM gauges
2015-06-25T12:10:24.817610+00:00 app[web.1]: [INFO] br.com.bpssolucoes.config.HerokuDatabaseConfiguration - Using Heroku, parsing their $DATABASE_URL to use it with JDBC
2015-06-25T12:10:24.817171+00:00 app[web.1]: [DEBUG] br.com.bpssolucoes.config.HerokuDatabaseConfiguration - Configuring Heroku Datasource
2015-06-25T12:10:34.443405+00:00 app[web.1]: [DEBUG] br.com.bpssolucoes.config.DatabaseConfiguration - Configuring Liquibase
```

**Comment by jdubois** [comment]
Great news @phouverneyuff !! I didn't think this could work, thanks!

**Comment by phouverneyuff** [comment]
@jdubois great!!!!!!!!!!!!!!!!!
