### ISSUE TITLE
GitError  Error  spawn git ENOENT

### ISSUE THREAD

**Issue by snifferchess** [jhipster/generator-jhipster#16544]
When tried to generate  using  [https://start.jhipster.tech/generate-application](url), return me error:
`Sending request to the server...
Generating application in repository snifferchess/exemplo-modelo-vacinacao
Creating GitHub repository
GitHub repository created!
Creating `.yo-rc.json` file
Running JHipster
INFO! Using JHipster version installed globally
GitError: Error: spawn git ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:269:19)
    at onErrorNT (internal/child_process.js:467:16)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
    at Object.action (/usr/local/share/.config/yarn/global/node_modules/simple-git/src/lib/plugins/error-detection.plugin.js:30:33)
    at PluginStore.exec (/usr/local/share/.config/yarn/global/node_modules/simple-git/src/lib/plugins/plugin-store.js:21:33)
    at /usr/local/share/.config/yarn/global/node_modules/simple-git/src/lib/runners/git-executor-chain.js:95:45
    at new Promise (<anonymous>)
    at GitExecutorChain.handleTaskData (/usr/local/share/.config/yarn/global/node_modules/simple-git/src/lib/runners/git-executor-chain.js:93:16)
    at GitExecutorChain.<anonymous> (/usr/local/share/.config/yarn/global/node_modules/simple-git/src/lib/runners/git-executor-chain.js:77:46)
    at Generator.next (<anonymous>)
    at fulfilled (/usr/local/share/.config/yarn/global/node_modules/simple-git/src/lib/runners/git-executor-chain.js:5:58) {
  task: {
    commands: [ 'rev-parse', '--is-inside-work-tree' ],
    format: 'utf-8',
    onError: [Function: onError],
    parser: [Function: parser]
  }
}`

**Comment by swarajsaaj** [comment]
This is related to https://github.com/jhipster/jhipster-online/issues/319
@SudharakaP I guess the docker image fix (missing git) is not yet deployed, can you deploy its please?

**Comment by beaglegit** [comment]
Thank you,  but it is necessary to have an image in the docker to do through the jhipster-online ?

**Comment by SudharakaP** [comment]
> This is related to [jhipster/jhipster-online#319](https://github.com/jhipster/jhipster-online/issues/319) @SudharakaP I guess the docker image fix (missing git) is not yet deployed, can you deploy its please?

Thanks for the ping. I'll do this today. 👍🏽

**Comment by swarajsaaj** [comment]
>Thank you, but it is necessary to have an image in the docker to do through the jhipster-online ?

@beaglegit There is no hard dependency of jhipster-online project on docker, it can run even as a standalone jar,  but the [https://start.jhipster.tech/](https://start.jhipster.tech/) instance is deployed in docker which was missing git installation.

**Comment by SudharakaP** [comment]
Done. This is fixed now with the new deployment. Sorry about the wait btw, past couple of weeks have been busy. 👍🏽
