### ISSUE TITLE
Importing new entity from JDL file and more fails when ".yo-rc.json" is out of sync

### ISSUE THREAD

**Issue by ksilz** [jhipster/generator-jhipster#16613]
##### **Overview of the issue**

Importing an entity from a JDL file fails when the `entities` array  of `.yo-rc.json` contains an entity that has no matching file in the `.jhipster` directory:
````
% jhipster import-jdl src/main/jdl/model.jdl
INFO! Using JHipster version installed locally in current project's node_modules
INFO! Executing import-jdl src/main/jdl/model.jdl
INFO! The JDL is being parsed.
info: The dto option is set for Thing, the 'serviceClass' value for the 'service' is gonna be set for this entity if no other value has been set.
info: The dto option is set for AnotherThing, the 'serviceClass' value for the 'service' is gonna be set for this entity if no other value has been set.
INFO! Found entities: AnotherThing.
INFO! The JDL has been successfully parsed
INFO! Generating 0 applications.
INFO! Generating 1 entity.
INFO! Generating entities for application undefined in a new parallel process
Error running generator entities: TypeError: Cannot read property 'changelogDate' of undefined
TypeError: Cannot read property 'changelogDate' of undefined
    at isBefore (/Users/karsten/workspaces/open-source/jhipster/issue-entity-out-of-sync/node_modules/generator-jhipster/generators/generator-base.js:1594:28)
    at Array.sort (<anonymous>)
    at module.exports.getExistingEntities (/Users/karsten/workspaces/open-source/jhipster/issue-entity-out-of-sync/node_modules/generator-jhipster/generators/generator-base.js:1616:8)
    at module.exports.getExistingEntityNames (/Users/karsten/workspaces/open-source/jhipster/issue-entity-out-of-sync/node_modules/generator-jhipster/generators/generator-base.js:1569:17)
    at new module.exports (/Users/karsten/workspaces/open-source/jhipster/issue-entity-out-of-sync/node_modules/generator-jhipster/generators/entities/index.js:108:36)
    at Environment.instantiate (/Users/karsten/workspaces/open-source/jhipster/issue-entity-out-of-sync/node_modules/yeoman-environment/lib/environment.js:802:23)
    at Environment.create (/Users/karsten/workspaces/open-source/jhipster/issue-entity-out-of-sync/node_modules/yeoman-environment/lib/environment.js:774:17)
    at instantiateAndRun (/Users/karsten/workspaces/open-source/jhipster/issue-entity-out-of-sync/node_modules/yeoman-environment/lib/environment.js:987:36)
    at Environment.run (/Users/karsten/workspaces/open-source/jhipster/issue-entity-out-of-sync/node_modules/yeoman-environment/lib/environment.js:1004:12)
    at runGenerator (/Users/karsten/workspaces/open-source/jhipster/issue-entity-out-of-sync/node_modules/generator-jhipster/cli/import-jdl.js:169:8)
ERROR! Cannot read property 'changelogDate' of undefined
TypeError: Cannot read property 'changelogDate' of undefined
    at isBefore (/Users/karsten/workspaces/open-source/jhipster/issue-entity-out-of-sync/node_modules/generator-jhipster/generators/generator-base.js:1594:28)
    at Array.sort (<anonymous>)
    at module.exports.getExistingEntities (/Users/karsten/workspaces/open-source/jhipster/issue-entity-out-of-sync/node_modules/generator-jhipster/generators/generator-base.js:1616:8)
    at module.exports.getExistingEntityNames (/Users/karsten/workspaces/open-source/jhipster/issue-entity-out-of-sync/node_modules/generator-jhipster/generators/generator-base.js:1569:17)
    at new module.exports (/Users/karsten/workspaces/open-source/jhipster/issue-entity-out-of-sync/node_modules/generator-jhipster/generators/entities/index.js:108:36)
    at Environment.instantiate (/Users/karsten/workspaces/open-source/jhipster/issue-entity-out-of-sync/node_modules/yeoman-environment/lib/environment.js:802:23)
    at Environment.create (/Users/karsten/workspaces/open-source/jhipster/issue-entity-out-of-sync/node_modules/yeoman-environment/lib/environment.js:774:17)
    at instantiateAndRun (/Users/karsten/workspaces/open-source/jhipster/issue-entity-out-of-sync/node_modules/yeoman-environment/lib/environment.js:987:36)
    at Environment.run (/Users/karsten/workspaces/open-source/jhipster/issue-entity-out-of-sync/node_modules/yeoman-environment/lib/environment.js:1004:12)
    at runGenerator (/Users/karsten/workspaces/open-source/jhipster/issue-entity-out-of-sync/node_modules/generator-jhipster/cli/import-jdl.js:169:8)
~/workspaces/open-source/jhipster/issue-entity-out-of-sync %% 
````

This also breaks `jhipster info`:
````
 % jhipster info 
INFO! Using JHipster version installed locally in current project's node_modules
Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
entity-out-of-sync@0.0.1-SNAPSHOT /Users/karsten/workspaces/open-source/jhipster/issue-entity-out-of-sync
└── generator-jhipster@7.2.0

```


##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**


<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "applicationType": "monolith",
    "baseName": "entityOutOfSync",
    "jhipsterVersion": "7.2.0",
    "skipClient": false,
    "skipServer": false,
    "skipUserManagement": false,
    "skipCheckLengthOfIdentifier": false,
    "skipFakeData": false,
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "testFrameworks": [],
    "blueprints": [],
    "otherModules": [],
    "pages": [],
    "creationTimestamp": 1633688526374,
    "serviceDiscoveryType": "no",
    "reactive": false,
    "authenticationType": "jwt",
    "packageName": "com.betterprojectsfaster.opensource.jhipster.entityoutofsync",
    "serverPort": "8080",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "postgresql",
    "buildTool": "gradle",
    "serverSideOptions": [],
    "websocket": false,
    "searchEngine": false,
    "messageBroker": false,
    "enableSwaggerCodegen": false,
    "clientFramework": "angularX",
    "withAdminUi": true,
    "clientTheme": "none",
    "enableTranslation": false,
    "nativeLanguage": "en",
    "jwtSecretKey": "YourJWTSecretKeyWasReplacedByThisMeaninglessTextByTheJHipsterInfoCommandForObviousSecurityReasons",
    "devServerPort": 4200,
    "clientPackageManager": "npm",
    "clientThemeVariant": "",
    "enableGradleEnterprise": false,
    "languages": ["en", "fr"],
    "entities": ["Thing", "Blah"],
    "lastLiquibaseTimestamp": 1633689355000
  }
}

</pre>
</details>


##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

Cannot read property 'changelogDate' of undefined
ERROR!
Error while parsing entities to JDL

Error:
Error while parsing entities to JDL

    at module.exports.error (/Users/karsten/workspaces/open-source/jhipster/issue-entity-out-of-sync/node_modules/generator-jhipster/generators/generator-base.js:1823:11)
    at module.exports.generateJDLFromEntities (/Users/karsten/workspaces/open-source/jhipster/issue-entity-out-of-sync/node_modules/generator-jhipster/generators/generator-base-private.js:1045:12)
    at module.exports.displayEntities (/Users/karsten/workspaces/open-source/jhipster/issue-entity-out-of-sync/node_modules/generator-jhipster/generators/info/index.js:78:26)
    at Object.<anonymous> (/Users/karsten/workspaces/open-source/jhipster/issue-entity-out-of-sync/node_modules/yeoman-generator/lib/index.js:1024:25)
    at /Users/karsten/workspaces/open-source/jhipster/issue-entity-out-of-sync/node_modules/run-async/index.js:49:25
    at new Promise (<anonymous>)
    at /Users/karsten/workspaces/open-source/jhipster/issue-entity-out-of-sync/node_modules/run-async/index.js:26:19
    at runLoop.add.once.once (/Users/karsten/workspaces/open-source/jhipster/issue-entity-out-of-sync/node_modules/yeoman-generator/lib/index.js:1025:11)
    at Immediate.<anonymous> (/Users/karsten/workspaces/open-source/jhipster/issue-entity-out-of-sync/node_modules/grouped-queue/lib/subqueue.js:48:34)
    at processImmediate (internal/timers.js:464:21)
%
````

##### **Motivation for or Use Case**

When working with different branches, the `.yo-rc.json` file and the `.jhipster` directory can get out of sync. If so, the user cannot import entities anymore - a showstopper. It's not obvious that cleaning up the `.yo-rc.json` file is the solution.

##### **Reproduce the error**

- Clone https://github.com/ksilz/jhipster-entity-out-of-sync
- Run `jhipster import-jdl src/main/jdl/model.jdl` to see the error

##### **Related issues**

[This issue](https://github.com/hipster-labs/generator-jhipster-entity-audit/issues/91) describes the same problem but has no repo to 

##### **Suggest a Fix**

The error is in [this line](https://github.com/jhipster/generator-jhipster/blob/main/generators/generator-base.js#L1594).  Something along the lines of this may be a quick fix:

````
  return e1?.definition?.changelogDate - e2?.definition?.changelogDate;
````

##### **JHipster Version(s)**

7.2.0

##### **JHipster Version(s)**

```
entity-out-of-sync@0.0.1-SNAPSHOT /Users/karsten/workspaces/open-source/jhipster/issue-entity-out-of-sync
└── generator-jhipster@7.2.0

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "applicationType": "monolith",
    "baseName": "entityOutOfSync",
    "jhipsterVersion": "7.2.0",
    "skipClient": false,
    "skipServer": false,
    "skipUserManagement": false,
    "skipCheckLengthOfIdentifier": false,
    "skipFakeData": false,
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "testFrameworks": [],
    "blueprints": [],
    "otherModules": [],
    "pages": [],
    "creationTimestamp": 1633688526374,
    "serviceDiscoveryType": "no",
    "reactive": false,
    "authenticationType": "jwt",
    "packageName": "com.betterprojectsfaster.opensource.jhipster.entityoutofsync",
    "serverPort": "8080",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "postgresql",
    "buildTool": "gradle",
    "serverSideOptions": [],
    "websocket": false,
    "searchEngine": false,
    "messageBroker": false,
    "enableSwaggerCodegen": false,
    "clientFramework": "angularX",
    "withAdminUi": true,
    "clientTheme": "none",
    "enableTranslation": false,
    "nativeLanguage": "en",
    "jwtSecretKey": "YourJWTSecretKeyWasReplacedByThisMeaninglessTextByTheJHipsterInfoCommandForObviousSecurityReasons",
    "devServerPort": 4200,
    "clientPackageManager": "npm",
    "clientThemeVariant": "",
    "enableGradleEnterprise": false,
    "languages": [
      "en",
      "fr"
    ],
    "entities": [
      "Thing"
    ],
    "lastLiquibaseTimestamp": 1633689355000
  }
}

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity Thing {
  enableSomething Boolean required
}
dto Thing with mapstruct
paginate Thing with pagination
service Thing with serviceImpl

</pre>
</details>

##### **Environment and Tools**

openjdk version "16.0.2" 2021-07-20
OpenJDK Runtime Environment Temurin-16.0.2+7 (build 16.0.2+7)
OpenJDK 64-Bit Server VM Temurin-16.0.2+7 (build 16.0.2+7, mixed mode, sharing)

git version 2.33.0

node: v14.18.0

npm: 7.24.2

Docker version 20.10.8, build 3967b7d

docker-compose version 1.29.2, build 5becea4c

##### **Browsers and Operating System**
macOS Big Sur 11.6

- [X] Checking this box is mandatory (this is just to show you read everything)

**Comment by DanielFran** [comment]
@ksilz Can you please confirm if it is still an issue with latest version?

**Comment by ksilz** [comment]
@DanielFran Sorry, still on JHipster 7.6.0. Will be at least a couple of weeks before I can test this.
