### ISSUE TITLE
Jhipster upgrade fails

### ISSUE THREAD

**Issue by salimAbdulIt** [jhipster/generator-jhipster#16620]
##### **Overview of the issue**

I installed 7.1.0 and created a project from that version. Now I want to upgrade it to the last version and I get the error when I tried to do the upgrade.

`Error: This seems to be an app blueprinted project with jhipster 6.6.0 bug (https://github.com/jhipster/generator-jhipster/issues/11045), you should pass --blueprints to jhipster upgrade commmand.
    at module.exports.error (C:\Users\Admin\AppData\Roaming\npm\node_modules\generator-jhipster\generators\generator-base.js:1823:11)
    at new module.exports (C:\Users\Admin\AppData\Roaming\npm\node_modules\generator-jhipster\generators\upgrade\index.js:94:12)
    at Environment.instantiate (C:\Users\Admin\AppData\Roaming\npm\node_modules\generator-jhipster\node_modules\yeoman-environment\lib\environment.js:802:23)
    at Environment.create (C:\Users\Admin\AppData\Roaming\npm\node_modules\generator-jhipster\node_modules\yeoman-environment\lib\environment.js:774:17)
    at instantiateAndRun (C:\Users\Admin\AppData\Roaming\npm\node_modules\generator-jhipster\node_modules\yeoman-environment\lib\environment.js:987:36)
    at Environment.run (C:\Users\Admin\AppData\Roaming\npm\node_modules\generator-jhipster\node_modules\yeoman-environme    at JHipsterCommand.<anonymous> (C:\Users\Admin\AppData\Roaming\npm\node_modules\generator-jhipster\cli\program.js:190:20)
    at JHipsterCommand.listener [as _actionHandler] (C:\Users\Admin\AppData\Roaming\npm\node_modules\generator-jhipster\node_modules\commander\lib\command.js:488:17)
    at C:\Users\Admin\AppData\Roaming\npm\node_modules\generator-jhipster\node_modules\commander\lib\command.js:1207:65
    at JHipsterCommand._chainOrCall (C:\Users\Admin\AppData\Roaming\npm\node_modules\generator-jhipster\node_modules\commander\lib\command.js:1124:12)`
##### **Motivation for or Use Case**

I tried to execute the command with --blueprints and a new error was thrown.

`C:\Users\Admin\AppData\Roaming\npm\node_modules\generator-jhipster\cli\environment-builder.js:199
      blueprintNames.push(...process.argv[indexOfBlueprintsArgv + 1].split(','));
                                                                     ^

TypeError: Cannot read property 'split' of undefined
    at EnvironmentBuilder._getBlueprintsFromArgv (C:\Users\Admin\AppData\Roaming\npm\node_modules\generator-jhipster\cli\environment-builder.js:199:70)
    at EnvironmentBuilder._getAllBlueprintsWithVersion (C:\Users\Admin\AppData\Roaming\npm\node_modules\generator-jhipster\cli\environment-builder.js:225:33)
    at EnvironmentBuilder._loadBlueprints (C:\Users\Admin\AppData\Roaming\npm\node_modules\generator-jhipster\cli\environment-builder.js:118:40)
-builder.js:73:8)
    at buildJHipster (C:\Users\Admin\AppData\Roaming\npm\node_modules\generator-jhipster\cli\program.js:197:35)
    at runJHipster (C:\Users\Admin\AppData\Roaming\npm\node_modules\generator-jhipster\cli\program.js:213:10)
    at Object.<anonymous> (C:\Users\Admin\AppData\Roaming\npm\node_modules\generator-jhipster\cli\cli.js:23:18)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)`

**Comment by justingloeckl** [comment]
I had the same problem while updating from 7.1.0 to 7.2.0. I did a manual upgrade.
Same problem when i now try to update from 7.2.0 to 7.3.0.

I dug into the generator code and found that the problem has something to do with the entities that jhipster has found and the ones that are definied. There is a check that failes because the object that is put into the split function is undefined.
