### ISSUE TITLE
JHipster tutorial: build failure

### ISSUE THREAD

**Issue by MastaP** [jhipster/generator-jhipster#1676]
Hi,

I tried to follow the quickstart https://jhipster.github.io/presentation/#/6/2 , answered the questions as follows:

```
Welcome to the JHipster Generator v2.17.0

? (1/15) What is the base name of your application? jhipster_second
? (2/15) What is your default Java package name? com.mycompany.myapp
? (3/15) Do you want to use Java 8? Yes (use Java 8)
? (4/15) Which *type* of authentication would you like to use? HTTP Session Authentication (stateful, default Spring Security mechanism)
? (5/15) Which *type* of database would you like to use? SQL (H2, MySQL, PostgreSQL, Oracle)
? (6/15) Which *production* database would you like to use? MySQL
? (7/15) Which *development* database would you like to use? H2 in-memory with Web console
? (8/15) Do you want to use Hibernate 2nd level cache? No
? (9/15) Do you want to use a search engine in your application? No
? (10/15) Do you want to use clustered HTTP sessions? No
? (11/15) Do you want to use WebSockets? No
? (12/15) Would you like to use Maven or Gradle for building the backend? Maven (recommended)
? (13/15) Would you like to use Grunt or Gulp.js for building the frontend? Grunt (recommended)
? (14/15) Would you like to use the Compass CSS Authoring Framework? Yes
? (15/15) Would you like to enable translation support with Angular Translate? No
```

build failed.

```
...
generator-jhipster@2.17.0 node_modules/generator-jhipster
├── html-wiring@1.1.0
├── chalk@1.0.0 (ansi-styles@2.1.0, escape-string-regexp@1.0.3, supports-color@1.3.1, strip-ansi@2.0.1, has-ansi@1.0.3)
├── shelljs@0.5.0
├── mkdirp@0.5.1 (minimist@0.0.8)
├── ejs@2.3.1
├── underscore.string@3.0.3
├── cheerio@0.19.0 (dom-serializer@0.1.0, entities@1.1.1, css-select@1.0.0, htmlparser2@3.8.3)
├── insight@0.6.0 (object-assign@2.1.1, lodash.debounce@3.1.1, async@0.9.2, configstore@1.2.0, os-name@1.0.3, tough-cookie@1.2.0, request@2.58.0, inquirer@0.8.5)
├── yeoman-generator@0.20.1 (read-chunk@1.0.1, detect-conflict@1.0.0, yeoman-welcome@1.0.1, path-is-absolute@1.0.0, xdg-basedir@1.0.1, yeoman-assert@2.0.0, user-home@1.1.1, diff@1.4.0, text-table@0.2.0, mime@1.3.4, dargs@4.0.1, istextorbinary@1.0.2, async@0.9.2, debug@2.2.0, nopt@3.0.3, run-async@0.1.0, shelljs@0.4.0, cli-table@0.3.1, through2@0.6.5, pretty-bytes@1.0.4, dateformat@1.0.11, glob@5.0.13, findup-sync@0.2.1, mem-fs-editor@2.0.2, rimraf@2.4.1, cross-spawn@0.4.1, github-username@2.0.0, class-extend@0.1.1, download@4.1.2, yeoman-environment@1.2.5, gruntfile-editor@1.0.0, sinon@1.15.4, lodash@3.10.0, inquirer@0.8.5)
└── yo@1.4.6 (titleize@1.0.0, array-uniq@1.0.2, figures@1.3.5, user-home@1.1.1, opn@1.0.2, humanize-string@1.0.1, sort-on@1.2.2, yeoman-character@1.0.1, async@0.9.2, string-length@1.0.0, cross-spawn@0.2.9, root-check@1.0.0, findup@0.1.5, yosay@1.0.4, meow@3.3.0, update-notifier@0.3.2, got@2.9.2, npm-keyword@1.2.0, package-json@1.2.0, fullname@1.1.0, configstore@0.3.2, insight@0.5.3, yeoman-environment@1.2.5, yeoman-doctor@1.4.0, inquirer@0.8.5)

grunt-browser-sync@2.1.2 node_modules/grunt-browser-sync
└── browser-sync@2.7.13 (async-each-series@0.1.1, longest@1.0.1, query-string@2.3.0, emitter-steward@0.0.1, ucfirst@0.0.1, opn@2.0.1, dev-ip@1.0.1, pad-left@1.0.2, ua-parser-js@0.7.7, foxy@11.0.4, portscanner@1.0.0, serve-static@1.10.0, meow@3.3.0, connect@3.4.0, browser-sync-client@2.2.1, immutable@3.7.4, resp-modifier@4.0.2, anymatch@1.3.0, serve-index@1.7.0, easy-extender@2.3.1, eazy-logger@2.1.2, localtunnel@1.5.1, lodash@3.10.0, chokidar@1.0.3, socket.io@1.3.5, browser-sync-ui@0.5.12)
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: spawn grunt ENOENT
    at exports._errnoException (util.js:746:11)
    at Process.ChildProcess._handle.onexit (child_process.js:1053:32)
    at child_process.js:1144:20
    at process._tickCallback (node.js:355:11)
```

**Comment by gmarziou** [comment]
Looks like a nodeJS environment issue, rather than following the presentation, I recommend that you [follow the official doc](https://jhipster.github.io/installation.html).

**Comment by jdubois** [comment]
Yes, this is an installation error -> I know it's annoying for you @MastaP but we can't provide support for third-party tools, on which we rely (and yes, I'm disappointed by NPM comparing to Maven! But they have some new video tutorials which are great)
