### ISSUE TITLE
Duplicated Hazelcast instances

### ISSUE THREAD

**Issue by radamanth** [jhipster/generator-jhipster#1688]
Hi.

I'm starting a new project with Jhipster, I'm using this configuration : 

 .yo-rc.json 
```json
{
  "generator-jhipster": {
    "baseName": "backoffice",
    "packageName": "fr.company.backoffice",
    "packageFolder": "fr/company/backoffice",
    "authenticationType": "xauth",
    "hibernateCache": "no",
    "clusteredHttpSession": "hazelcast",
    "websocket": "no",
    "databaseType": "mongodb",
    "devDatabaseType": "mongodb",
    "prodDatabaseType": "mongodb",
    "searchEngine": "no",
    "useCompass": true,
    "buildTool": "maven",
    "frontendBuilder": "grunt",
    "javaVersion": "8",
    "enableTranslation": true,
    "rememberMeKey": "whateverwhateverwhatever"
  }
}
```

I'm using 
**jhipster version** :  2.17.0

**java version** :  "1.8.0_45"
Java(TM) SE Runtime Environment (build 1.8.0_45-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.45-b02, mixed mode)

**Npm** 2.12.1
**Node ** v0.12.2

I'm on Ubuntu 14.04 

But when I Launch *mvn spring-boot:run* just after project initialisation I get this error : 

```
mvn spring-boot:run 
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building backoffice 0.0.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] >>> spring-boot-maven-plugin:1.2.4.RELEASE:run (default-cli) > test-compile @ backoffice >>>
[INFO] 
[INFO] --- maven-enforcer-plugin:1.3.1:enforce (enforce-versions) @ backoffice ---
[INFO] 
[INFO] --- maven-processor-plugin:2.2.4:process (process) @ backoffice ---
[WARNING] diagnostic: warning: The following options were not recognized by any processor: '[mapstruct.defaultComponentModel, mapstruct.suppressGeneratorTimestamp]'
[INFO] 
[INFO] --- yeoman-maven-plugin:0.4:build (run-grunt) @ backoffice ---
[INFO] node version :
v0.12.2
[INFO] npm version :
2.12.1
[INFO] --------------------------------------
[INFO]          NPM INSTALL
[INFO] --------------------------------------
[INFO] bower version :
1.4.1
[INFO] --------------------------------------
[INFO]          BOWER INSTALL --NO-COLOR
[INFO] --------------------------------------
[INFO] grunt version :
grunt-cli v0.1.13
grunt v0.4.5
[INFO] --------------------------------------
[INFO]          GRUNT COMPASS:SERVER --FORCE
[INFO] --------------------------------------
Running "compass:server" (compass) task
    write src/main/webapp/assets/styles/main.css (3.726s)

Done, without errors.


Execution Time (2015-07-06 08:00:53 UTC)
loading tasks   61ms  ▇ 1%
compass:server  4.2s  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 99%
Total 4.2s

[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ backoffice ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 4 resources
[INFO] Copying 9 resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ backoffice ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 83 source files to /home/radamanth/devenv/sources/company/backoffice/target/classes
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ backoffice ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 2 resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ backoffice ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 6 source files to /home/radamanth/devenv/sources/company/backoffice/target/test-classes
[INFO] 
[INFO] <<< spring-boot-maven-plugin:1.2.4.RELEASE:run (default-cli) < test-compile @ backoffice <<<
[INFO] 
[INFO] --- spring-boot-maven-plugin:1.2.4.RELEASE:run (default-cli) @ backoffice ---
[INFO] Attaching agents: []
Listening for transport dt_socket at address: 5005
[INFO] fr.company.backoffice.Application - Starting Application on radamanth-G751JY with PID 23259 (/home/radamanth/devenv/sources/company/backoffice/target/classes started by radamanth in /home/radamanth/devenv/sources/company/backoffice)
[DEBUG] fr.company.backoffice.Application - Running with Spring Boot v1.2.4.RELEASE, Spring v4.1.6.RELEASE
[DEBUG] org.jboss.logging - Logging Provider: org.jboss.logging.Slf4jLoggerProvider
[DEBUG] fr.company.backoffice.config.AsyncConfiguration - Creating Async Task Executor
[DEBUG] fr.company.backoffice.config.MetricsConfiguration - Registering JVM gauges
[INFO] fr.company.backoffice.config.MetricsConfiguration - Initializing Metrics JMX reporting
[DEBUG] fr.company.backoffice.config.MailConfiguration - Configuring mail server
[INFO] fr.company.backoffice.Application - Running with Spring profile(s) : [dev]
[INFO] fr.company.backoffice.config.WebConfigurer - Web application configuration, using profiles: [dev]
[DEBUG] fr.company.backoffice.config.WebConfigurer - Registering Clustered Http Session Filter
[DEBUG] fr.company.backoffice.config.WebConfigurer - Initializing Metrics registries
[DEBUG] fr.company.backoffice.config.WebConfigurer - Registering Metrics Filter
[DEBUG] fr.company.backoffice.config.WebConfigurer - Registering Metrics Servlet
[INFO] fr.company.backoffice.config.WebConfigurer - Web application fully configured
[INFO] com.hazelcast.web.ClusteredSessionService - Retrying the connection!!
[INFO] com.hazelcast.config.XmlConfigLocator - Loading 'hazelcast-default.xml' from classpath.
[INFO] com.hazelcast.web.HazelcastInstanceLoader - getOrCreateHazelcastInstance for session replication, using name 'backoffice'
[INFO] com.hazelcast.instance.DefaultAddressPicker - [LOCAL] [dev] [3.4.3] Prefer IPv4 stack is true.
[INFO] com.hazelcast.instance.DefaultAddressPicker - [LOCAL] [dev] [3.4.3] Picked Address[192.168.100.46]:5701, using socket ServerSocket[addr=/0:0:0:0:0:0:0:0,localport=5701], bind any local is true
[INFO] com.hazelcast.spi.OperationService - [192.168.100.46]:5701 [dev] [3.4.3] Backpressure is disabled
[INFO] com.hazelcast.spi.impl.BasicOperationScheduler - [192.168.100.46]:5701 [dev] [3.4.3] Starting with 4 generic operation threads and 8 partition operation threads.
[INFO] com.hazelcast.system - [192.168.100.46]:5701 [dev] [3.4.3] Hazelcast 3.4.3 (20150616 - bc77eaf) starting at Address[192.168.100.46]:5701
[INFO] com.hazelcast.system - [192.168.100.46]:5701 [dev] [3.4.3] Copyright (C) 2008-2014 Hazelcast.com
[INFO] com.hazelcast.instance.Node - [192.168.100.46]:5701 [dev] [3.4.3] Creating MulticastJoiner
[INFO] com.hazelcast.core.LifecycleService - [192.168.100.46]:5701 [dev] [3.4.3] Address[192.168.100.46]:5701 is STARTING
[DEBUG] sun.net.www.protocol.http.HttpURLConnection - sun.net.www.MessageHeader@7488e3115 pairs: {GET /version.jsp?version=3.4.3&m=e20df8f0-7f6c-4563-87e1-5799ccb94670&e=false&l=NULL&p=maven&c=e77989ed21758e78331b20e477fc5582&crsz=A&cssz=A HTTP/1.1: null}{User-Agent: Mozilla/5.0}{Host: versioncheck.hazelcast.com}{Accept: text/html, image/gif, image/jpeg, *; q=.2, */*; q=.2}{Connection: keep-alive}
[DEBUG] sun.net.www.protocol.http.HttpURLConnection - sun.net.www.MessageHeader@2d003948 pairs: {null: HTTP/1.1 200 OK}{Date: Mon, 06 Jul 2015 08:04:08 GMT}{Server: Apache-Coyote/1.1}{Content-Type: text/xml;charset=UTF-8}{Vary: Accept-Encoding}{Keep-Alive: timeout=5, max=100}{Connection: Keep-Alive}{Transfer-Encoding: chunked}
[INFO] com.hazelcast.cluster.impl.MulticastJoiner - [192.168.100.46]:5701 [dev] [3.4.3] 


Members [1] {
	Member [192.168.100.46]:5701 this
}

[INFO] com.hazelcast.core.LifecycleService - [192.168.100.46]:5701 [dev] [3.4.3] Address[192.168.100.46]:5701 is STARTED
[INFO] com.hazelcast.web.ClusteredSessionService - Successfully Connected!
[INFO] fr.company.backoffice.config.ThymeleafConfiguration - loading non-reloadable mail messages resources
[DEBUG] fr.company.backoffice.config.DatabaseConfiguration - Configuring Mongeez
[INFO] org.mongeez.reader.FilesetXMLReader - Num of changefiles 2
[INFO] org.mongeez.ChangeSetExecutor - ChangeSet already executed: ChangeSet-1
[INFO] org.mongeez.ChangeSetExecutor - ChangeSet already executed: ChangeSet-2
[DEBUG] fr.company.backoffice.config.CacheConfiguration - No cache
[DEBUG] fr.company.backoffice.config.CacheConfiguration - Configuring Hazelcast
[WARN] org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext - Exception encountered during context initialization - cancelling refresh attempt
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'hazelcastInstance' defined in class path resource [fr/company/backoffice/config/CacheConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.hazelcast.core.HazelcastInstance]: Factory method 'hazelcastInstance' threw exception; nested exception is com.hazelcast.core.DuplicateInstanceNameException: HazelcastInstance with name 'backoffice' already exists!
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:599) ~[spring-beans-4.1.6.RELEASE.jar:4.1.6.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1119) ~[spring-beans-4.1.6.RELEASE.jar:4.1.6.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1014) ~[spring-beans-4.1.6.RELEASE.jar:4.1.6.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:504) ~[spring-beans-4.1.6.RELEASE.jar:4.1.6.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:476) ~[spring-beans-4.1.6.RELEASE.jar:4.1.6.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:303) ~[spring-beans-4.1.6.RELEASE.jar:4.1.6.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230) ~[spring-beans-4.1.6.RELEASE.jar:4.1.6.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:299) ~[spring-beans-4.1.6.RELEASE.jar:4.1.6.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:194) ~[spring-beans-4.1.6.RELEASE.jar:4.1.6.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:755) ~[spring-beans-4.1.6.RELEASE.jar:4.1.6.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:757) ~[spring-context-4.1.6.RELEASE.jar:4.1.6.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:480) ~[spring-context-4.1.6.RELEASE.jar:4.1.6.RELEASE]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:118) [spring-boot-1.2.4.RELEASE.jar:1.2.4.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:686) [spring-boot-1.2.4.RELEASE.jar:1.2.4.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:320) [spring-boot-1.2.4.RELEASE.jar:1.2.4.RELEASE]
	at fr.company.backoffice.Application.main(Application.java:70) [classes/:na]
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.hazelcast.core.HazelcastInstance]: Factory method 'hazelcastInstance' threw exception; nested exception is com.hazelcast.core.DuplicateInstanceNameException: HazelcastInstance with name 'backoffice' already exists!
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:189) ~[spring-beans-4.1.6.RELEASE.jar:4.1.6.RELEASE]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:588) ~[spring-beans-4.1.6.RELEASE.jar:4.1.6.RELEASE]
	... 15 common frames omitted
Caused by: com.hazelcast.core.DuplicateInstanceNameException: HazelcastInstance with name 'backoffice' already exists!
	at com.hazelcast.instance.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:132) ~[hazelcast-3.4.3.jar:3.4.3]
	at com.hazelcast.instance.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:112) ~[hazelcast-3.4.3.jar:3.4.3]
	at fr.company.backoffice.config.CacheConfiguration.hazelcastInstance(CacheConfiguration.java:70) ~[classes/:na]
	at fr.company.backoffice.config.CacheConfiguration$$EnhancerBySpringCGLIB$$f5418b95.CGLIB$hazelcastInstance$1(<generated>) ~[spring-core-4.1.6.RELEASE.jar:na]
	at fr.company.backoffice.config.CacheConfiguration$$EnhancerBySpringCGLIB$$f5418b95$$FastClassBySpringCGLIB$$6db3a6ac.invoke(<generated>) ~[spring-core-4.1.6.RELEASE.jar:na]
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228) ~[spring-core-4.1.6.RELEASE.jar:4.1.6.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:309) ~[spring-context-4.1.6.RELEASE.jar:4.1.6.RELEASE]
	at fr.company.backoffice.config.CacheConfiguration$$EnhancerBySpringCGLIB$$f5418b95.hazelcastInstance(<generated>) ~[spring-core-4.1.6.RELEASE.jar:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_45]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_45]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_45]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_45]
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:162) ~[spring-beans-4.1.6.RELEASE.jar:4.1.6.RELEASE]
	... 16 common frames omitted
[INFO] fr.company.backoffice.config.CacheConfiguration - Closing Cache Manager
[INFO] com.hazelcast.core.LifecycleService - [192.168.100.46]:5701 [dev] [3.4.3] Address[192.168.100.46]:5701 is SHUTTING_DOWN
[INFO] com.hazelcast.instance.Node - [192.168.100.46]:5701 [dev] [3.4.3] Shutting down multicast service...
[INFO] com.hazelcast.instance.Node - [192.168.100.46]:5701 [dev] [3.4.3] Shutting down connection manager...
[INFO] com.hazelcast.instance.Node - [192.168.100.46]:5701 [dev] [3.4.3] Shutting down node engine...
[INFO] com.hazelcast.instance.NodeExtension - [192.168.100.46]:5701 [dev] [3.4.3] Destroying node NodeExtension.
[INFO] com.hazelcast.instance.Node - [192.168.100.46]:5701 [dev] [3.4.3] Hazelcast Shutdown is completed in 135 ms.
[INFO] com.hazelcast.core.LifecycleService - [192.168.100.46]:5701 [dev] [3.4.3] Address[192.168.100.46]:5701 is SHUTDOWN
[ERROR] org.springframework.boot.SpringApplication - Application startup failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'hazelcastInstance' defined in class path resource [fr/company/backoffice/config/CacheConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.hazelcast.core.HazelcastInstance]: Factory method 'hazelcastInstance' threw exception; nested exception is com.hazelcast.core.DuplicateInstanceNameException: HazelcastInstance with name 'backoffice' already exists!
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:599) ~[spring-beans-4.1.6.RELEASE.jar:4.1.6.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1119) ~[spring-beans-4.1.6.RELEASE.jar:4.1.6.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1014) ~[spring-beans-4.1.6.RELEASE.jar:4.1.6.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:504) ~[spring-beans-4.1.6.RELEASE.jar:4.1.6.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:476) ~[spring-beans-4.1.6.RELEASE.jar:4.1.6.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:303) ~[spring-beans-4.1.6.RELEASE.jar:4.1.6.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230) ~[spring-beans-4.1.6.RELEASE.jar:4.1.6.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:299) ~[spring-beans-4.1.6.RELEASE.jar:4.1.6.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:194) ~[spring-beans-4.1.6.RELEASE.jar:4.1.6.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:755) ~[spring-beans-4.1.6.RELEASE.jar:4.1.6.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:757) ~[spring-context-4.1.6.RELEASE.jar:4.1.6.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:480) ~[spring-context-4.1.6.RELEASE.jar:4.1.6.RELEASE]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:118) ~[spring-boot-1.2.4.RELEASE.jar:1.2.4.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:686) ~[spring-boot-1.2.4.RELEASE.jar:1.2.4.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:320) ~[spring-boot-1.2.4.RELEASE.jar:1.2.4.RELEASE]
	at fr.company.backoffice.Application.main(Application.java:70) [classes/:na]
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.hazelcast.core.HazelcastInstance]: Factory method 'hazelcastInstance' threw exception; nested exception is com.hazelcast.core.DuplicateInstanceNameException: HazelcastInstance with name 'backoffice' already exists!
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:189) ~[spring-beans-4.1.6.RELEASE.jar:4.1.6.RELEASE]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:588) ~[spring-beans-4.1.6.RELEASE.jar:4.1.6.RELEASE]
	... 15 common frames omitted
Caused by: com.hazelcast.core.DuplicateInstanceNameException: HazelcastInstance with name 'backoffice' already exists!
	at com.hazelcast.instance.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:132) ~[hazelcast-3.4.3.jar:3.4.3]
	at com.hazelcast.instance.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:112) ~[hazelcast-3.4.3.jar:3.4.3]
	at fr.company.backoffice.config.CacheConfiguration.hazelcastInstance(CacheConfiguration.java:70) ~[classes/:na]
	at fr.company.backoffice.config.CacheConfiguration$$EnhancerBySpringCGLIB$$f5418b95.CGLIB$hazelcastInstance$1(<generated>) ~[spring-core-4.1.6.RELEASE.jar:na]
	at fr.company.backoffice.config.CacheConfiguration$$EnhancerBySpringCGLIB$$f5418b95$$FastClassBySpringCGLIB$$6db3a6ac.invoke(<generated>) ~[spring-core-4.1.6.RELEASE.jar:na]
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228) ~[spring-core-4.1.6.RELEASE.jar:4.1.6.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:309) ~[spring-context-4.1.6.RELEASE.jar:4.1.6.RELEASE]
	at fr.company.backoffice.config.CacheConfiguration$$EnhancerBySpringCGLIB$$f5418b95.hazelcastInstance(<generated>) ~[spring-core-4.1.6.RELEASE.jar:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_45]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_45]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_45]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_45]
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:162) ~[spring-beans-4.1.6.RELEASE.jar:4.1.6.RELEASE]
	... 16 common frames omitted
Exception in thread "main" org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'hazelcastInstance' defined in class path resource [fr/company/backoffice/config/CacheConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.hazelcast.core.HazelcastInstance]: Factory method 'hazelcastInstance' threw exception; nested exception is com.hazelcast.core.DuplicateInstanceNameException: HazelcastInstance with name 'backoffice' already exists!
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:599)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1119)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1014)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:504)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:476)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:303)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:299)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:194)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:755)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:757)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:480)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:118)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:686)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:320)
	at fr.company.backoffice.Application.main(Application.java:70)
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.hazelcast.core.HazelcastInstance]: Factory method 'hazelcastInstance' threw exception; nested exception is com.hazelcast.core.DuplicateInstanceNameException: HazelcastInstance with name 'backoffice' already exists!
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:189)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:588)
	... 15 more
Caused by: com.hazelcast.core.DuplicateInstanceNameException: HazelcastInstance with name 'backoffice' already exists!
	at com.hazelcast.instance.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:132)
	at com.hazelcast.instance.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:112)
	at fr.company.backoffice.config.CacheConfiguration.hazelcastInstance(CacheConfiguration.java:70)
	at fr.company.backoffice.config.CacheConfiguration$$EnhancerBySpringCGLIB$$f5418b95.CGLIB$hazelcastInstance$1(<generated>)
	at fr.company.backoffice.config.CacheConfiguration$$EnhancerBySpringCGLIB$$f5418b95$$FastClassBySpringCGLIB$$6db3a6ac.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228)
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:309)
	at fr.company.backoffice.config.CacheConfiguration$$EnhancerBySpringCGLIB$$f5418b95.hazelcastInstance(<generated>)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:162)
	... 16 more
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 30.558 s
[INFO] Finished at: 2015-07-06T10:01:13+02:00
[INFO] Final Memory: 45M/530M
[INFO] ------------------------------------------------------------------------

```
Any idea why ? 

I found this #1604 But that was solved in the 2.17.0

Regards.

Tony

**Comment by jdubois** [comment]
Yes, for some reason the "ConfigureAfter" annotation doesn't work correctly: I'm going to force this, by injecting the Hazelcast instead.

**Comment by radamanth** [comment]
:+1: 
Thx for the fast patching !

**Comment by veejayendraa** [comment]
Issue is still coming with 2.26.1 version of Jhipster.
