### ISSUE TITLE
Error [ERR_MULTIPLE_CALLBACK]: Callback called multiple times

### ISSUE THREAD

**Issue by RobertBurrellDonkin** [jhipster/generator-jhipster#16918]
##### On MacOS X (7.3.1 and head) and Amazon Linux (head) no seeing Error [ERR_MULTIPLE_CALLBACK]: Callback called multiple times

    Error [ERR_MULTIPLE_CALLBACK]: Callback called multiple times
      at NodeError (node:internal/errors:371:5)
      at onFinish (node:internal/streams/writable:668:37)
      at processTicksAndRejections (node:internal/process/task_queues:82:21)
      at runNextTicks (node:internal/process/task_queues:65:3)
      at listOnTimeout (node:internal/timers:526:9)
      at processTimers (node:internal/timers:500:7)

Independently reported by https://stackoverflow.com/questions/69835351/jhipster-version-7-3-1-latest-having-error-in-node-during-the-code-generation

##### **Motivation for or Use Case**

Errors prevents generation

##### **Reproduce the error**

1. Create Cloud9 Environment
2. ```npm install && npm install -g eslint && npm test```

```
  5924 passing (18m)
  37 pending
  12 failing

  1) JHipster generator
       Default configuration with
         AngularX
           "before all" hook for "creates expected default files for angularX":
     Error [ERR_MULTIPLE_CALLBACK]: Callback called multiple times
      at NodeError (node:internal/errors:371:5)
      at onFinish (node:internal/streams/writable:668:37)
      at processTicksAndRejections (node:internal/process/task_queues:82:21)
      at runNextTicks (node:internal/process/task_queues:65:3)
      at listOnTimeout (node:internal/timers:526:9)
      at processTimers (node:internal/timers:500:7)

  2) JHipster generator with required configuration
       "before all" hook for "writes additional default config to .yo-rc.json":
     Error [ERR_MULTIPLE_CALLBACK]: Callback called multiple times
      at NodeError (node:internal/errors:371:5)
      at onFinish (node:internal/streams/writable:668:37)
      at processTicksAndRejections (node:internal/process/task_queues:82:21)
      at runNextTicks (node:internal/process/task_queues:65:3)
      at listOnTimeout (node:internal/timers:526:9)
      at processTimers (node:internal/timers:500:7)

  3) JHipster application generator with blueprint
       generate application with a version-compatible blueprint
         "before all" hook for "creates expected default files for server and angularX":
     Error [ERR_MULTIPLE_CALLBACK]: Callback called multiple times
      at NodeError (node:internal/errors:371:5)
      at onFinish (node:internal/streams/writable:668:37)
      at processTicksAndRejections (node:internal/process/task_queues:82:21)
      at runNextTicks (node:internal/process/task_queues:65:3)
      at listOnTimeout (node:internal/timers:526:9)
      at processTimers (node:internal/timers:500:7)

  4) JHipster application generator with blueprint
       generating application with a git blueprint
         should succeed:
     Error [ERR_MULTIPLE_CALLBACK]: Callback called multiple times
      at NodeError (node:internal/errors:371:5)
      at onFinish (node:internal/streams/writable:668:37)
      at processTicksAndRejections (node:internal/process/task_queues:82:21)
      at runNextTicks (node:internal/process/task_queues:65:3)
      at listOnTimeout (node:internal/timers:526:9)
      at processTimers (node:internal/timers:500:7)

  5) JHipster application generator with blueprint
       generate application with a peer version-compatible blueprint
         "before all" hook for "creates expected default files for server and angularX":
     Error [ERR_MULTIPLE_CALLBACK]: Callback called multiple times
      at NodeError (node:internal/errors:371:5)
      at onFinish (node:internal/streams/writable:668:37)
      at processTicksAndRejections (node:internal/process/task_queues:82:21)
      at runNextTicks (node:internal/process/task_queues:65:3)
      at listOnTimeout (node:internal/timers:526:9)
      at processTimers (node:internal/timers:500:7)

  6) JHipster entity generator with multiple blueprints
       generate entity with multiple blueprints option 'generator-jhipster-my-client-blueprint,generator-jhipster-my-server-blueprint'
         creates expected files from jhipster app generator:

      AssertionError [ERR_ASSERTION]: README.md, no such file or directory
      + expected - actual

      -false
      +true
      
      at /home/ec2-user/environment/generator-jhipster/node_modules/yeoman-assert/index.js:56:12
      at Array.forEach (<anonymous>)
      at Function.assert.file (node_modules/yeoman-assert/index.js:54:26)
      at Context.<anonymous> (test/blueprint/multiple-blueprints.spec.js:152:16)
      at processImmediate (node:internal/timers:464:21)

  7) JHipster entity generator with multiple blueprints
       generate entity with multiple blueprints option 'my-client-blueprint,my-server-blueprint'
         creates expected files from jhipster app generator:

      AssertionError [ERR_ASSERTION]: README.md, no such file or directory
      + expected - actual

      -false
      +true
      
      at /home/ec2-user/environment/generator-jhipster/node_modules/yeoman-assert/index.js:56:12
      at Array.forEach (<anonymous>)
      at Function.assert.file (node_modules/yeoman-assert/index.js:54:26)
      at Context.<anonymous> (test/blueprint/multiple-blueprints.spec.js:152:16)
      at processImmediate (node:internal/timers:464:21)

  8) JHipster application generator with scoped blueprint
       generate monolith application with scoped blueprint
         "before all" hook for "creates expected default files for server and angularX":
     Error [ERR_MULTIPLE_CALLBACK]: Callback called multiple times
      at NodeError (node:internal/errors:371:5)
      at onFinish (node:internal/streams/writable:668:37)
      at processTicksAndRejections (node:internal/process/task_queues:82:21)
      at runNextTicks (node:internal/process/task_queues:65:3)
      at listOnTimeout (node:internal/timers:526:9)
      at processTimers (node:internal/timers:500:7)

  9) jhipster cli with jdl fork
       generates entities
         should succeed:
     Error: Timeout of 30000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/home/ec2-user/environment/generator-jhipster/test/cli/jdl-fork.spec.js)
      at listOnTimeout (node:internal/timers:557:17)
      at processTimers (node:internal/timers:500:7)

  10) jhipster cli with jdl fork
       generates an application with deployments
         should succeed:
     Error: Timeout of 60000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/home/ec2-user/environment/generator-jhipster/test/cli/jdl-fork.spec.js)
      at listOnTimeout (node:internal/timers:557:17)
      at processTimers (node:internal/timers:500:7)

  11) JHipster generator
       Default configuration with
         Custom prettier
           "before all" hook for "writes custom .prettierrc":
     Error [ERR_MULTIPLE_CALLBACK]: Callback called multiple times
      at NodeError (node:internal/errors:371:5)
      at onFinish (node:internal/streams/writable:668:37)
      at processTicksAndRejections (node:internal/process/task_queues:82:21)
      at runNextTicks (node:internal/process/task_queues:65:3)
      at listOnTimeout (node:internal/timers:526:9)
      at processTimers (node:internal/timers:500:7)

  12) JHipster upgrade generator
       default application
         "before all" hook for "creates expected files for default configuration":
     Error [ERR_MULTIPLE_CALLBACK]: Callback called multiple times
      at NodeError (node:internal/errors:371:5)
      at onFinish (node:internal/streams/writable:668:37)
      at processTicksAndRejections (node:internal/process/task_queues:82:21)
      at runNextTicks (node:internal/process/task_queues:65:3)
      at listOnTimeout (node:internal/timers:526:9)
      at processTimers (node:internal/timers:500:7)
```

##### **Related issues**

None found by search

##### **Suggest a Fix**

Feels like I'd need to invest a lot of time in regression testing. Hopefully someone might have a clue. 

##### **JHipster Version(s)**

Observed on 7.3.1 and HEAD

##### **JHipster configuration**

Occurs when ```npm test``` run on head

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

Occurs when ```npm test``` run on head

##### **Browsers and Operating System**

Replicated on MacOSX and AmazonLinux2

- [X] Checking this box is mandatory (this is just to show you read everything)

**Comment by mraible** [comment]
What version of Node.js are you using? We only support v14 right now.

**Comment by RobertBurrellDonkin** [comment]
% node --version
v16.13.0

**Comment by RobertBurrellDonkin** [comment]
Give me a sec to check AWS...

**Comment by RobertBurrellDonkin** [comment]
$ node --version
v17.0.1

**Comment by RobertBurrellDonkin** [comment]
Let me try switching AWS to v14

**Comment by RobertBurrellDonkin** [comment]
Hey @mraible 

On MacOSX I get now:

```
You are running Node version 14.9.0
JHipster requires Node version ^12.20.0 || ^14.13.1 || >=16.0.0
Please update your version of Node.
```

So I updated to the latest and greatest node. Which led ```npm test``` to fail. 

Is it worthwhile dropping the ```>=16.0.0``` until #16744 is merged in ...?

**Comment by mraible** [comment]
> Is it worthwhile dropping the >=16.0.0 until #16744 is merged in ...?

Yes, I think so.
