### ISSUE TITLE
Error when using blueprints

### ISSUE THREAD

**Issue by deepu105** [jhipster/generator-jhipster#16989]
While trying to run a blueprint (I have to say it's been a while since I did this and I don't even recognize my own code :wink: and quite tired of debugging all the Istio stuff, so may be I missed something obvious) there are these errors

```
(node:547505) [DEP0148] DeprecationWarning: Use of deprecated folder mapping "./generators/" in the "exports" field module resolution of the package at /home/deepu/Workspace/jhipster/generator-jhipster-istio/node_modules/generator-jhipster/package.json.
Update this package.json to use a subpath pattern like "./generators/*".
(Use `node --trace-deprecation ...` to show where the warning was created)
Error running generator app: TypeError: jhContext.setupServerOptions is not a function
TypeError: jhContext.setupServerOptions is not a function
    at new module.exports (/home/deepu/Workspace/jhipster/generator-jhipster-istio/generators/server/index.js:18:19)
    at Environment.instantiate (/home/deepu/Workspace/jhipster/generator-jhipster/node_modules/yeoman-environment/lib/environment.js:804:23)
    at Environment.create (/home/deepu/Workspace/jhipster/generator-jhipster/node_modules/yeoman-environment/lib/environment.js:776:17)
    at JHipsterServerGenerator.composeWith (/home/deepu/Workspace/jhipster/generator-jhipster/node_modules/yeoman-generator/lib/index.js:1239:42)
    at JHipsterServerGenerator._composeBlueprint (/home/deepu/Workspace/jhipster/generator-jhipster/generators/generator-base-blueprint.js:383:37)
    at /home/deepu/Workspace/jhipster/generator-jhipster/generators/generator-base-blueprint.js:250:41
    at Array.forEach (<anonymous>)
    at JHipsterServerGenerator.instantiateBlueprints (/home/deepu/Workspace/jhipster/generator-jhipster/generators/generator-base-blueprint.js:249:18)
    at new JHipsterServerGenerator (/home/deepu/Workspace/jhipster/generator-jhipster/generators/server/index.js:79:49)
```

JHipster version: 7.3.1 main branch
Blueprint generator version: main branch

**Comment by deepu105** [comment]
Ok seems like this function is no longer present, so we need to update the blueprint generator

**Comment by mshima** [comment]
My proposal is to move the blueprint generator into generator-jhipster https://github.com/jhipster/generator-jhipster/issues/15869.
IMO jhipster should drop the use of `yo` command.

**Comment by deepu105** [comment]
I agree @mshima

**Comment by deepu105** [comment]
Keep open

Thanks & Regards,
Deepu
