### ISSUE TITLE
Since JHipster v2.18, mapstruct brokes Java 7 comptatibility

### ISSUE THREAD

**Issue by MatthieuLebigre** [jhipster/generator-jhipster#1722]
Hello,
I think with JHipster 2.18, the comptatibility with Java 7 is broken:
I have updated my project to JHipster, and my app is not starting anymore. Here is the exception :

    Exception in thread "main" org.springframework.beans.factory.BeanDefinitionStoreException: Failed to read candidate component class: URL [jar:file:/C:/Users/lebigrem/.m2/repository/io/springfox/springfox-swagger2/2.0.3/springfox-swagger2-2.0.3.jar!/springfox/documentation/swagger2/mappers/LicenseMapper$License.class]; nested exception is java.lang.UnsupportedClassVersionError: org/mapstruct/Qualifier : Unsupported major.minor version 52.0
	at org.springframework.context.annotation.ClassPathScanningCandidateComponentProvider.findCandidateComponents(ClassPathScanningCandidateComponentProvider.java:303)
	at org.springframework.context.annotation.ClassPathBeanDefinitionScanner.doScan(ClassPathBeanDefinitionScanner.java:248)
	at org.springframework.context.annotation.ComponentScanAnnotationParser.parse(ComponentScanAnnotationParser.java:140)
	at org.springframework.context.annotation.ConfigurationClassParser.doProcessConfigurationClass(ConfigurationClassParser.java:266)
	at org.springframework.context.annotation.ConfigurationClassParser.processConfigurationClass(ConfigurationClassParser.java:230)
	at org.springframework.context.annotation.ConfigurationClassParser.processImports(ConfigurationClassParser.java:486)
	at org.springframework.context.annotation.ConfigurationClassParser.doProcessConfigurationClass(ConfigurationClassParser.java:276)
	at org.springframework.context.annotation.ConfigurationClassParser.processConfigurationClass(ConfigurationClassParser.java:230)
	at org.springframework.context.annotation.ConfigurationClassParser.parse(ConfigurationClassParser.java:189)
	at org.springframework.context.annotation.ConfigurationClassParser.doProcessConfigurationClass(ConfigurationClassParser.java:270)
	at org.springframework.context.annotation.ConfigurationClassParser.processConfigurationClass(ConfigurationClassParser.java:230)
	at org.springframework.context.annotation.ConfigurationClassParser.parse(ConfigurationClassParser.java:197)
	at org.springframework.context.annotation.ConfigurationClassParser.parse(ConfigurationClassParser.java:166)
	at org.springframework.context.annotation.ConfigurationClassPostProcessor.processConfigBeanDefinitions(ConfigurationClassPostProcessor.java:306)
	at org.springframework.context.annotation.ConfigurationClassPostProcessor.postProcessBeanDefinitionRegistry(ConfigurationClassPostProcessor.java:239)
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanDefinitionRegistryPostProcessors(PostProcessorRegistrationDelegate.java:254)
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:94)
	at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:606)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:462)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:118)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:686)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:320)
	at com.videotron.mtl.redevance.Application.main(Application.java:72)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)
    Caused by: java.lang.UnsupportedClassVersionError: org/mapstruct/Qualifier : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at org.springframework.core.type.classreading.RecursiveAnnotationAttributesVisitor.visitEnd(RecursiveAnnotationAttributesVisitor.java:47)
	at org.springframework.asm.ClassReader.readAnnotationValues(ClassReader.java:1802)
	at org.springframework.asm.ClassReader.accept(ClassReader.java:648)
	at org.springframework.asm.ClassReader.accept(ClassReader.java:508)
	at org.springframework.core.type.classreading.SimpleMetadataReader.<init>(SimpleMetadataReader.java:64)
	at org.springframework.core.type.classreading.SimpleMetadataReaderFactory.getMetadataReader(SimpleMetadataReaderFactory.java:98)
	at org.springframework.core.type.classreading.CachingMetadataReaderFactory.getMetadataReader(CachingMetadataReaderFactory.java:102)
	at org.springframework.context.annotation.ClassPathScanningCandidateComponentProvider.findCandidateComponents(ClassPathScanningCandidateComponentProvider.java:279)
	... 27 more

If I remove the mapstruct dependency from my pom.xml, the app is starting without exception.

**Comment by jdubois** [comment]
MapStruct is not supported on Java 7

- You don't have the option if you select "Java 7"
- It's also documented [here](http://jhipster.github.io/using_dtos.html)

So I don't know what you did, but it's normal that MapStruct doesn't work on Java 7 -> this is why I'm closing this

Then, I would be interested to know how you managed to use MapStruct with Java 7, as the option isn't available.

**Comment by atomfrede** [comment]
@jdubois Shouldn't this be added for ``java8`` option only? Its not guarded by any if statement (same for gradle by the way as I only copied the dependencies from 
```
<dependency>
 <groupId>org.mapstruct</groupId>
 <artifactId>mapstruct-jdk8</artifactId>
   <version>${mapstruct.version}</version>
</dependency>
```

**Comment by MatthieuLebigre** [comment]
It's indeed what I removed from my pom. I didn't select any option, just rerun "yo jhipster" on my existing app.

**Comment by jdubois** [comment]
Good point! I'm reopening this!

**Comment by gunnarmorling** [comment]
> Then, I would be interested to know how you managed to use MapStruct with Java 7, as the option isn't available.

I guess you figured this already, but just in case. There are two different annotation artifacts provided by MapStruct: _org.mapstruct:mapstruct_ for JDK 6/7 and _org.mapstruct:mapstruct-jdk8_ for JDK 8 and beyond. The annotation processor module works with either of them.

**Comment by jdubois** [comment]
Oh, when I said MapStruct isn't supported in Java 7: I meant, "with JHipster". Basically, we don't code anything new with Java 7, as it's EOL'd.

As we had a few Java 8-specific code with MapStruct, we removed the option to use MapStruct when the Java 7 option is selected.

MapStruct, of course, could work with Java 7, it's just that we didn't spent time on implementing our code for Java 7.
