### ISSUE TITLE
An error on test for a freshly generated application

### ISSUE THREAD

**Issue by vw98075** [jhipster/generator-jhipster#1732]
After a few of creating application iterations, I think it is a good practice to run a test before doing anything. I get an error after a fresh application is generated. I don't have the cache option possibly due to my MongoDB selection. 

C:\Users\me\workspace-sts-my-projects\myapp>gradlew test
:generateMainMapperClasses
:compileJava
:compileScala UP-TO-DATE
:bower
:processResources
:classes
:compileTestJava
:compileTestScala UP-TO-DATE
:processTestResources
:testClasses
:test
Exception in thread "Thread-16" java.lang.IllegalStateException: Shutdown in progress
        at java.lang.ApplicationShutdownHooks.add(ApplicationShutdownHooks.java:66)
        at java.lang.Runtime.addShutdownHook(Runtime.java:211)
        at de.flapdoodle.embed.process.io.file.FileCleaner.forceDeleteOnExit(FileCleaner.java:49)
        at de.flapdoodle.embed.process.io.file.Files.forceDelete(Files.java:119)
        at de.flapdoodle.embed.process.store.ArtifactStore.removeFileSet(ArtifactStore.java:91)
        at de.flapdoodle.embed.process.store.CachingArtifactStore$FilesWithCounter.forceDelete(CachingArtifactStore.java:151)
        at de.flapdoodle.embed.process.store.CachingArtifactStore.removeAll(CachingArtifactStore.java:94)
        at de.flapdoodle.embed.process.store.CachingArtifactStore$CacheCleaner.run(CachingArtifactStore.java:171)
        at java.lang.Thread.run(Thread.java:744)
[INFO] com.mycompany.myapp.config.CacheConfiguration - Closing Cache Manager

**Comment by gmarziou** [comment]
if you're talking of the IllegalStateException on application shutdown, I got it often but it's harmless.
Nothing to worry about and I don't think it made your tests to fail.

**Comment by vw98075** [comment]
Thanks for your quick response. I will ignore this error. BTW, the most of test on Rest fail after I change Spring Boot to the latest version 1.3.0.M2. And the application is running fine on Use operations.

com.mycompany.myapp.web.rest.AccountResourceTest > testRegisterAdminIsIgnored FAILED
    java.lang.AssertionError at AccountResourceTest.java:307

com.mycompany.myapp.web.rest.AccountResourceTest > testRegisterDuplicateEmail FAILED
    java.lang.AssertionError at AccountResourceTest.java:277

com.mycompany.myapp.web.rest.AccountResourceTest > testRegisterDuplicateLogin FAILED
    java.lang.AssertionError at AccountResourceTest.java:241

com.mycompany.myapp.web.rest.AccountResourceTest > testRegisterValid FAILED
    java.lang.AssertionError at AccountResourceTest.java:166

com.mycompany.myapp.web.rest.UserResourceTest > testGetExistingUser FAILED
    java.lang.AssertionError at UserResourceTest.java:52
[INFO] com.mycompany.myapp.config.CacheConfiguration - Closing Cache Manager

**Comment by jdubois** [comment]
For Spring Boot 1.3.0 we didn't do any test yet -> that's good to know, but that's normal if it fails at the moment
