### ISSUE TITLE
cypress generator: code coverage error

### ISSUE THREAD

**Issue by marcolafranca** [jhipster/generator-jhipster#17506]
##### **Overview of the issue**

In JHipster wizard, if I enable cypress code coverage, then I get an error in project project creation.
![image](https://user-images.githubusercontent.com/29198466/148375175-5ae674ec-2bdb-4f5c-94e6-04bc299f71be.png)

```
ERROR! Error parsing file src\test\javascript\cypress\plugins\index.ts: SyntaxError: ';' expected. (27:4)
  25 |       return launchOptions;
  26 |     }
> 27 |   });
     |    ^
  28 |
  29 |   on('task', {
  30 |     lighthouse: lighthouse((lighthouseReport) => {

At: 1: // ***********************************************************
2: // This example plugins/index.js can be used to load plugins
3: //
4: // You can change the location of this file or turn off loading
5: // the plugins file with the 'pluginsFile' configuration option.
6: //
7: // You can read more here:
8: // https://on.cypress.io/plugins-guide
9: // ***********************************************************
10:
11: // This function is called when a project is opened or re-opened (e.g. due to
12: // the project's config changing)
13: import fs = require('fs');
14: import { lighthouse, pa11y, prepareAudit } from 'cypress-audit';
15: import ReportGenerator = require('lighthouse/report/generator/report-generator');
16: /**
17:  * @type {Cypress.PluginConfig}
18:  */
19: module.exports = (on, config) => {
20:   // `on` is used to hook into various events Cypress emits
21: // `config` is the resolved Cypress config  on('before:browser:launch', (browser, launchOptions) => {
22:     prepareAudit(launchOptions);
23:     if (browser.name === 'chrome' && browser.isHeadless) {
24:       launchOptions.args.push('--disable-gpu');
25:       return launchOptions;
26:     }
27:   });
28:
29:   on('task', {
30:     lighthouse: lighthouse((lighthouseReport) => {
31:       !fs.existsSync('target/cypress') && fs.mkdirSync('target/cypress', { recursive: true });
32:       fs.writeFileSync('target/cypress/lhreport.html', ReportGenerator.generateReport(lighthouseReport.lhr, 'html'));
33:     }),
34:     pa11y: pa11y(),
35:   });
36:     require('@cypress/code-coverage/task')(on, config);
37:     return config;
38: }
39:
Error: Error parsing file src\test\javascript\cypress\plugins\index.ts: SyntaxError: ';' expected. (27:4)
  25 |       return launchOptions;
  26 |     }
> 27 |   });
     |    ^
  28 |
  29 |   on('task', {
  30 |     lighthouse: lighthouse((lighthouseReport) => {

At: 1: // ***********************************************************
2: // This example plugins/index.js can be used to load plugins
3: //
4: // You can change the location of this file or turn off loading
5: // the plugins file with the 'pluginsFile' configuration option.
6: //
7: // You can read more here:
8: // https://on.cypress.io/plugins-guide
9: // ***********************************************************
10:
11: // This function is called when a project is opened or re-opened (e.g. due to
12: // the project's config changing)
13: import fs = require('fs');
14: import { lighthouse, pa11y, prepareAudit } from 'cypress-audit';
15: import ReportGenerator = require('lighthouse/report/generator/report-generator');
16: /**
17:  * @type {Cypress.PluginConfig}
18:  */
19: module.exports = (on, config) => {
20:   // `on` is used to hook into various events Cypress emits
21: // `config` is the resolved Cypress config  on('before:browser:launch', (browser, launchOptions) => {
22:     prepareAudit(launchOptions);
23:     if (browser.name === 'chrome' && browser.isHeadless) {
24:       launchOptions.args.push('--disable-gpu');
25:       return launchOptions;
26:     }
27:   });
28:
29:   on('task', {
30:     lighthouse: lighthouse((lighthouseReport) => {
31:       !fs.existsSync('target/cypress') && fs.mkdirSync('target/cypress', { recursive: true });
32:       fs.writeFileSync('target/cypress/lhreport.html', ReportGenerator.generateReport(lighthouseReport.lhr, 'html'));
33:     }),
34:     pa11y: pa11y(),
35:   });
36:     require('@cypress/code-coverage/task')(on, config);
37:     return config;
38: }
39:
    at patternSpy.dot (C:\Users\marco_ye\AppData\Roaming\npm\node_modules\generator-jhipster\generators\generator-transforms.js:79:15)
    at async PTransform.transform [as _transform] (C:\Users\marco_ye\AppData\Roaming\npm\node_modules\generator-jhipster\node_modules\p-transform\index.js:127:7)
    at async PTransform.queuedTransform (C:\Users\marco_ye\AppData\Roaming\npm\node_modules\generator-jhipster\node_modules\p-transform\index.js:88:26)
    at async run (C:\Users\marco_ye\AppData\Roaming\npm\node_modules\generator-jhipster\node_modules\p-queue\dist\index.js:163:29)
   create src\main\webapp\i18n\en\logs.json
   create src\test\javascript\cypress\fixtures\integration-test.png
```

##### **Motivation for or Use Case**

I think it may be a bug related to the cypress generator

##### **Reproduce the error**

Just launch the JHipster wizard with " Would you like to generate code coverage for Cypress tests? [Experimental]" to "Yes"

##### **JHipster Version(s)**

JHipster v7.5.0

##### **JHipster configuration**

```
##### **JHipster Version(s)**

smartharvest@0.0.1-SNAPSHOT C:\Users\marco_ye\dev\projects\smartisland\smartharvest
`-- (empty)


##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**


<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "applicationType": "monolith",
    "baseName": "smartharvest",
    "jhipsterVersion": "7.5.0",
    "skipUserManagement": false,
    "skipCheckLengthOfIdentifier": false,
    "skipFakeData": false,
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "testFrameworks": ["cypress"],
    "blueprints": [],
    "otherModules": [],
    "pages": [],
    "creationTimestamp": 1641466616382,
    "serviceDiscoveryType": "no",
    "reactive": false,
    "authenticationType": "jwt",
    "packageName": "it.cloudtec.smartharvest",
    "serverPort": "8080",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "databaseType": "sql",
    "devDatabaseType": "mysql",
    "prodDatabaseType": "mysql",
    "buildTool": "maven",
    "serverSideOptions": [],
    "websocket": false,
    "searchEngine": false,
    "messageBroker": false,
    "enableSwaggerCodegen": false,
    "clientFramework": "angularX",
    "withAdminUi": true,
    "clientTheme": "none",
    "enableTranslation": true,
    "nativeLanguage": "it",
    "jwtSecretKey": "YourJWTSecretKeyWasReplacedByThisMeaninglessTextByTheJHipsterInfoCommandForObviousSecurityReasons",
    "devServerPort": 4200,
    "clientPackageManager": "npm",
    "clientThemeVariant": "",
    "languages": ["it", "en"],
    "enableGradleEnterprise": false,
    "cypressCoverage": true
  }
}

</pre>
</details>


##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>


##### **Environment and Tools**

openjdk version "17.0.1" 2021-10-19
OpenJDK Runtime Environment Temurin-17.0.1+12 (build 17.0.1+12)
OpenJDK 64-Bit Server VM Temurin-17.0.1+12 (build 17.0.1+12, mixed mode, sharing)

git version 2.30.2.windows.1

node: v16.13.1

npm: 8.1.2


No change to package.json was detected. No package manager install will be executed.
```

##### **Browsers and Operating System**

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by mshima** [comment]
You can use `--ignore-errors` and fix the generated code.
