### ISSUE TITLE
node-gyp

### ISSUE THREAD

**Issue by roaned** [jhipster/generator-jhipster#1767]
Hi, i try to install jhipster. But everytime i have this problem:
```
> bufferutil@1.1.0 install C:\projects\java\jhipster\testPulito\node_modules\browser-sync\node_modules\socket.io\node_modules\engine.io\node_modules\ws\node_modules\bufferutil
> node-gyp rebuild

/
C:\projects\java\jhipster\testPulito\node_modules\browser-sync\node_modules\socket.io\node_modules\engine.io\node_modules\ws\node_modules\bufferutil>if not defined npm_config_node_gyp (node "C:\Program Files (x86)\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  bufferutil.cc
     Creazione della libreria C:\projects\java\jhipster\testPulito\node_modules\browser-sync\node_modules\socket.io\node_modules\engine.io\node_modules\ws\node_modules\bufferutil\build\Release\bufferutil.lib e dell'oggetto C:\projects\java\jhipster\testPulito\node_modules\browser-sync\node_modules\socket.io\node_modules\engine.io\node_modules\ws\node_modules\bufferutil\build\Release\bufferutil.exp in corso...
  Generazione codice in corso...
  Generazione codice terminata
LINK : fatal error LNK1123: errore durante la conversione in COFF: file non valido o danneggiato [C:\projects\java\jhipster\testPulito\node_modules\browser-sync\node_modules\socket.io\node_modules\engine.io\node_modules\ws\node_modules\bufferutil\build\bufferutil.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "node" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\projects\java\jhipster\testPulito\node_modules\browser-sync\node_modules\socket.io\node_modules\engine.io\node_modules\ws\node_modules\bufferutil
gyp ERR! node -v v0.12.7
gyp ERR! node-gyp -v v2.0.1
gyp ERR! not ok
npm WARN optional dep failed, continuing utf-8-validate@1.1.0


> utf-8-validate@1.1.0 install C:\projects\java\jhipster\testPulito\node_modules\browser-sync\node_modules\socket.io\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\node_modules\utf-8-validate
> node-gyp rebuild

/
C:\projects\java\jhipster\testPulito\node_modules\browser-sync\node_modules\socket.io\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\node_modules\utf-8-validate>if not defined npm_config_node_gyp (node "C:\Program Files (x86)\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppBuild.targets(308,5): error MSB3491: Could not write lines to file "Release\obj\validation\validation.tlog\validation.lastbuildstate". The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters. [C:\projects\java\jhipster\testPulito\node_modules\browser-sync\node_modules\socket.io\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\node_modules\utf-8-validate\build\validation.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "node" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\projects\java\jhipster\testPulito\node_modules\browser-sync\node_modules\socket.io\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\node_modules\utf-8-validate
gyp ERR! node -v v0.12.7
gyp ERR! node-gyp -v v2.0.1
gyp ERR! not ok
npm WARN optional dep failed, continuing bufferutil@1.1.0


> bufferutil@1.1.0 install C:\projects\java\jhipster\testPulito\node_modules\browser-sync\node_modules\socket.io\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\node_modules\bufferutil
> node-gyp rebuild
```

i install express 2013 and python 27, that are requirments of node-gyp. Can explain where i was wrong?

**Comment by jdubois** [comment]
I don't know about node-gyp, it seems to come from BrowserSync : can you also send this ticket to BrowserSync, and link it here?

**Comment by gmarziou** [comment]
Welcome to the joy of Node on Windows.

Windows has a maximal length of 248 chars for a path and npm uses a tree as structure of node_modules folder, it will become flatter with npm 3.0,. 

So either you try to shorten as much as possible the path of your project 'C:\projects\java\jhipster\testPulito' -> 'C:\testPulito' or you try to [install npm 3 beta](https://github.com/felixrieseberg/npm-windows-upgrade)

Anyway, as @jdubois said, it's not a JHipster issue.


C:\projects\java\jhipster\testPulito\node_modules\browser-sync\node_modules\socket.io\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\node_modules\utf-8-validate\build\validation.vcxproj]

**Comment by roaned** [comment]
@gmarziou i put the folder in disk C but i have the same error. I install npm 3, but when i see versione, i use anyway npm version 2.11.3. 

@jdubois ok now i send ticket to BrowserSync.

**Comment by roaned** [comment]
my bad, i didn't done a good research. So i have a big problem with this visual studio version. I try to install UBUNTU. Thank you for help me :)

**Comment by jdubois** [comment]
OK, as @gmarziou wrote, this is a Windows issue, with the file path being too long.

**Comment by cagreek** [comment]
Suggestion to install npm 3 worked for me.

Thank you gmarziou

**Comment by deepu105** [comment]
@gmarziou I guess with npm 3 it will be much better not just for windows. I hate the way npm piles up dependency in a tree with lots of duplicates a typical project would end up with millions of files and thats bad for so many reasons. Bower got it right with flat structure and atlast npm team has realised the architecture flaw and is following suite.

And by the way its a myth that majority of developers doesn't use windows. Infact the wide majprity uses windows, most of the top 10 IT companies in terms of employee strength use windows as primary development machines (not talking about deployment infra)
So even if it sucks everyone has to somehow support it to have a wider reach
