### ISSUE TITLE
"Command failed with exit code 127: npm run clean-www" After Upgrading

### ISSUE THREAD

**Issue by vw98075** [jhipster/generator-jhipster#17743]
##### **Overview of the issue**

After upgrading the JHipster generator to the 7.6.0 version from the 7.3.1, I upgrade my project with the command 
```
jhipster --with-entities
```
It took me near two days to walk through the process. I get the following error at the end.
```

No change to package.json was detected. No package manager install will be executed.
Found commits in Git from /Users/me/workspace/myapp. So we assume this is application regeneration. Therefore automatic Git commit is not done. You can do Git commit manually.

If you find JHipster useful consider sponsoring the project https://www.jhipster.tech/sponsors/

Server application generated successfully.

Run your Spring Boot application:
./mvnw

Client application generated successfully.

Start your Webpack development server with:
 npm start


> myapp@0.0.0 clean-www
> rimraf target/classes/static/app/{src,target/}

sh: rimraf: command not found
ERROR! Command failed with exit code 127: npm run clean-www
Error: Command failed with exit code 127: npm run clean-www
    at makeError (/Users/me/.nvm/versions/node/v14.18.1/lib/node_modules/generator-jhipster/node_modules/execa/lib/error.js:59:11)
    at Function.module.exports.sync (/Users/me/.nvm/versions/node/v14.18.1/lib/node_modules/generator-jhipster/node_modules/execa/index.js:188:17)
    at JHipsterClientGenerator.spawnCommand.spawnCommandSync (/Users/me/.nvm/versions/node/v14.18.1/lib/node_modules/generator-jhipster/node_modules/yeoman-generator/lib/actions/spawn-command.js:35:16)
    at JHipsterClientGenerator.end (/Users/me/.nvm/versions/node/v14.18.1/lib/node_modules/generator-jhipster/generators/client/index.js:435:16)
    at Object.<anonymous> (/Users/me/.nvm/versions/node/v14.18.1/lib/node_modules/generator-jhipster/node_modules/yeoman-generator/lib/index.js:1097:23)
    at /Users/me/.nvm/versions/node/v14.18.1/lib/node_modules/generator-jhipster/node_modules/run-async/index.js:49:25
    at new Promise (<anonymous>)
    at /Users/me/.nvm/versions/node/v14.18.1/lib/node_modules/generator-jhipster/node_modules/run-async/index.js:26:19
    at /Users/me/.nvm/versions/node/v14.18.1/lib/node_modules/generator-jhipster/node_modules/yeoman-generator/lib/index.js:1098:9
    at new Promise (<anonymous>) {
  shortMessage: 'Command failed with exit code 127: npm run clean-www',
  command: 'npm run clean-www',
  exitCode: 127,
  signal: undefined,
  signalDescription: undefined,
  stdout: undefined,
  stderr: undefined,
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}
``` 
Based on a suggestion on https://stackify.dev/551074-sh-1-rimraf-not-found-whenever-i-run-npm-run-build-within-vagrant-installed-o,  I add 
```
"rimraf": "./node_modules/rimraf/bin.js"
```
into the package.json file without luck.

Also, I am wondering whether I should generate a new project with a new version of the generator and migrate any custom changes in the future or not as it takes too much time on the project upgrading.

##### **JHipster Version(s)**

7.6.0

##### **JHipster configuration**

```
{
  "generator-jhipster": {
    "applicationType": "monolith",
    "authenticationType": "oauth2",
    "baseName": "my app",
    "blueprints": [],
    "buildTool": "maven",
    "cacheProvider": "ehcache",
    "clientFramework": "vue",
    "clientPackageManager": "npm",
    "clientTheme": "lux",
    "clientThemeVariant": "primary",
    "creationTimestamp": 1626276896721,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "devServerPort": 9060,
    "dtoSuffix": "DTO",
    "enableGradleEnterprise": false,
    "enableHibernateCache": true,
    "enableSwaggerCodegen": false,
    "enableTranslation": true,
    "entities": […],
    "entitySuffix": "",
    "jhiPrefix": "jhi",
    "jhipsterVersion": "7.6.0",
    "languages": ["en", "es"],
    "lastLiquibaseTimestamp": 1641510171000,
    "messageBroker": false,
    "nativeLanguage": "en",
    "otherModules": [],
    "packageFolder": "com/abc/myapp",
    "packageName": "com.abc.myapp",
    "pages": [],
    "prodDatabaseType": "postgresql",
    "reactive": false,
    "searchEngine": false,
    "serverPort": "8080",
    "serverSideOptions": [],
    "serviceDiscoveryType": false,
    "skipCheckLengthOfIdentifier": false,
    "skipClient": false,
    "skipFakeData": false,
    "skipServer": false,
    "skipUserManagement": true,
    "testFrameworks": ["cypress", "gatling"],
    "websocket": false,
    "withAdminUi": true
  }
}

```
##### **Browsers and Operating System**

- [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by mshima** [comment]
Npm repository is missing.
You should run `npm install`

**Comment by sharonmil** [comment]
same here I'm running on windows using all defaults possible
