### ISSUE TITLE
`jhipster upgrade` fails to upgrade v5 project to v7

### ISSUE THREAD

**Issue by mraible** [jhipster/generator-jhipster#18097]
##### **Overview of the issue**

I'm trying to upgrade my [21-Points Health](https://github.com/mraible/21-points) application to use JHipster 7. It fails with the following error:

```
ERROR! Cannot read properties of undefined (reading 'json-stringify')
```

Full stack trace:

```
✔ Installed generator-jhipster@7.7.0
Skipping blueprint update since no blueprint has been detected
     info Removing /Users/mraible/dev/21-points/.editorconfig
     info Removing /Users/mraible/dev/21-points/.gitattributes
     info Removing /Users/mraible/dev/21-points/.gitignore
     info Removing /Users/mraible/dev/21-points/.huskyrc
     info Removing /Users/mraible/dev/21-points/.prettierignore
     info Removing /Users/mraible/dev/21-points/.prettierrc
     info Removing /Users/mraible/dev/21-points/README.md
     info Removing /Users/mraible/dev/21-points/angular.json
     info Removing /Users/mraible/dev/21-points/build.gradle
     info Removing /Users/mraible/dev/21-points/gradle
     info Removing /Users/mraible/dev/21-points/gradle.properties
     info Removing /Users/mraible/dev/21-points/gradlew
     info Removing /Users/mraible/dev/21-points/gradlew.bat
     info Removing /Users/mraible/dev/21-points/package.json
     info Removing /Users/mraible/dev/21-points/postcss.config.js
     info Removing /Users/mraible/dev/21-points/proxy.conf.json
     info Removing /Users/mraible/dev/21-points/settings.gradle
     info Removing /Users/mraible/dev/21-points/src
     info Removing /Users/mraible/dev/21-points/tsconfig-aot.json
     info Removing /Users/mraible/dev/21-points/tsconfig.json
     info Removing /Users/mraible/dev/21-points/tslint.json
     info Removing /Users/mraible/dev/21-points/webpack
✔ Cleaned up project directory
Regenerating application with JHipster 7.7.0...
/Users/mraible/dev/21-points/node_modules/.bin
     info "/Users/mraible/dev/21-points/node_modules/.bin/jhipster" --with-entities --force --skip-install --skip-git --ignore-errors --no-insight
INFO! Switching to JHipster installed locally in current project's node repository (node_modules)

        ██╗ ██╗   ██╗ ████████╗ ███████╗   ██████╗ ████████╗ ████████╗ ███████╗
        ██║ ██║   ██║ ╚══██╔══╝ ██╔═══██╗ ██╔════╝ ╚══██╔══╝ ██╔═════╝ ██╔═══██╗
        ██║ ████████║    ██║    ███████╔╝ ╚█████╗     ██║    ██████╗   ███████╔╝
  ██╗   ██║ ██╔═══██║    ██║    ██╔════╝   ╚═══██╗    ██║    ██╔═══╝   ██╔══██║
  ╚██████╔╝ ██║   ██║ ████████╗ ██║       ██████╔╝    ██║    ████████╗ ██║  ╚██╗
   ╚═════╝  ╚═╝   ╚═╝ ╚═══════╝ ╚═╝       ╚═════╝     ╚═╝    ╚═══════╝ ╚═╝   ╚═╝
                            https://www.jhipster.tech
Welcome to JHipster v7.7.0

ERROR! Cannot read properties of undefined (reading 'json-stringify')
TypeError: Cannot read properties of undefined (reading 'json-stringify')
    at Object.<anonymous> (/Users/mraible/dev/21-points/node_modules/prettier-plugin-packagejson/lib/index.js:4:23)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1155:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/Users/mraible/dev/21-points/node_modules/generator-jhipster/generators/generator-transforms.js:24:35)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1155:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/Users/mraible/dev/21-points/node_modules/generator-jhipster/generators/bootstrap/index.js:36:61)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
ERROR! Something went wrong while generating project! Error: Command failed: "/Users/mraible/dev/21-points/node_modules/.bin/jhipster" --with-entities --force --skip-install --skip-git --ignore-errors --no-insight
Error: Something went wrong while generating project! Error: Command failed: "/Users/mraible/dev/21-points/node_modules/.bin/jhipster" --with-entities --force --skip-install --skip-git --ignore-errors --no-insight
    at module.exports.error (/usr/local/lib/node_modules/generator-jhipster/generators/generator-base.js:1868:11)
    at module.exports._generate (/usr/local/lib/node_modules/generator-jhipster/generators/upgrade/index.js:176:12)
    at module.exports._regenerate (/usr/local/lib/node_modules/generator-jhipster/generators/upgrade/index.js:192:10)
    at module.exports.generateWithTargetVersion (/usr/local/lib/node_modules/generator-jhipster/generators/upgrade/index.js:480:14)
    at Object.<anonymous> (/usr/local/lib/node_modules/generator-jhipster/node_modules/yeoman-generator/lib/index.js:1097:23)
    at /usr/local/lib/node_modules/generator-jhipster/node_modules/run-async/index.js:49:25
    at new Promise (<anonymous>)
    at /usr/local/lib/node_modules/generator-jhipster/node_modules/run-async/index.js:26:19
    at /usr/local/lib/node_modules/generator-jhipster/node_modules/yeoman-generator/lib/index.js:1098:9
    at new Promise (<anonymous>)
```

##### **Motivation for or Use Case**

It'd be really slick if I could update 21-Point Health quickly and easily. 

##### **Reproduce the error**

Clone the project and run `jhipster upgrade` in it.

**Comment by mraible** [comment]
I tried answering no to the blueprints question.

```
? Unify blueprints configurations? No
```

Unfortunately, the same error happens.

**Comment by zhyd1997** [comment]
Hi @mraible 

I can not reproduce the issue:

```shell
npx jhipster upgrade
```
<img width="1026" alt="npx jhipster upgrade" src="https://user-images.githubusercontent.com/31362988/159136455-bd321f02-17e6-4d13-b721-bdcb722acf8e.png">

**Comment by mraible** [comment]
@zhyd1997 I just tried again with `jhipster upgrade`.

<img width="1442" alt="Screen Shot 2022-03-21 at 21 21 25" src="https://user-images.githubusercontent.com/17892/159401423-de0214b0-1e6d-4662-8572-5928d75e4523.png">

If I try `npx jhipster upgrade`, it works!

<img width="1442" alt="Screen Shot 2022-03-21 at 21 39 36" src="https://user-images.githubusercontent.com/17892/159403991-b1727950-fd40-4444-b0d5-6715b7692f48.png">

If I try `npm install` or `./gradlew`, it fails, but that's because I need to resolve merge conflicts. Thanks!

<img width="1442" alt="Screen Shot 2022-03-21 at 21 40 03" src="https://user-images.githubusercontent.com/17892/159404040-e01499e4-a0cf-43bc-a99c-c95c898adca7.png">

**Comment by zhyd1997** [comment]
@mraible 
I'm glad if it solved your problem!

**Comment by mraible** [comment]
@zhyd1997 Can you update the [updating an application](https://www.jhipster.tech/upgrading-an-application/) documentation? I'll award this issue's bug bounty for better docs!

**Comment by zhyd1997** [comment]
@mraible Submitted a PR.

**Comment by vishal423** [comment]
Does this mean every `jhipster` command now needs to be executed via `npx` command? Any idea why behavior got changed recently?

**Comment by mraible** [comment]
> Does this mean every `jhipster` command now needs to be executed via `npx` command? Any idea why behavior got changed recently?

I'm not sure, maybe @mshima knows? My guess is `jhipster upgrade` might start with the locally installed JHipster whereas `npx jhipster upgrade` uses the latest version.

**Comment by zhyd1997** [comment]
@mshima 

```bash
git clone https://github.com/mraible/21-points.git
npm i generator-jhipster@version -g # step1
```

version is in [**5.4.2**, **6.6.0**, **7.0.0-beta.0**]

```bash
cp -R 21-points test-jhipster
cd test-jhipster
jhipster upgrade
fi success 
  cd ..
  rm -rf test-jhipster
  goto step1
```

the same error above started at `@7.0.0-beta.0` (this version has **5k** commits and **2k+** files changed), 
<img width="1229" alt="version comparison" src="https://user-images.githubusercontent.com/31362988/159627073-f92081c4-d0c2-4718-b44f-edb94cdc7416.png">


the last v6 version `@6.10.5` passed if answering blueprints with '**No**', the same as `@6.10.4`, `@6.10.3`,

 `@7.0.0-beta.0` failed even I answered '**No**'.

**Comment by zhyd1997** [comment]
@mshima 

but `npx jhipster upgrade` works with '**Yes**'.

Seems that it's strange.🤔
