### ISSUE TITLE
MongoDb repos with ElasticSearch.

### ISSUE THREAD

**Issue by Selectorrr** [jhipster/generator-jhipster#1810]
I think they are not compatible.
Example: https://github.com/Selectorrr/petsroom-jh
```
Caused by: org.springframework.data.mapping.PropertyReferenceException: No property insert found for type User!
	at org.springframework.data.mapping.PropertyPath.<init>(PropertyPath.java:75)
	at org.springframework.data.mapping.PropertyPath.create(PropertyPath.java:327)
	at org.springframework.data.mapping.PropertyPath.create(PropertyPath.java:307)
	at org.springframework.data.mapping.PropertyPath.from(PropertyPath.java:270)
	at org.springframework.data.mapping.PropertyPath.from(PropertyPath.java:241)
	at org.springframework.data.repository.query.parser.Part.<init>(Part.java:76)
	at org.springframework.data.repository.query.parser.PartTree$OrPart.<init>(PartTree.java:235)
	at org.springframework.data.repository.query.parser.PartTree$Predicate.buildTree(PartTree.java:373)
	at org.springframework.data.repository.query.parser.PartTree$Predicate.<init>(PartTree.java:353)
	at org.springframework.data.repository.query.parser.PartTree.<init>(PartTree.java:84)
	at org.springframework.data.elasticsearch.repository.query.ElasticsearchPartQuery.<init>(ElasticsearchPartQuery.java:40)
	at org.springframework.data.elasticsearch.repository.support.ElasticsearchRepositoryFactory$ElasticsearchQueryLookupStrategy.resolveQuery(ElasticsearchRepositoryFactory.java:117)
	at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.<init>(RepositoryFactorySupport.java:369)
	at org.springframework.data.repository.core.support.RepositoryFactorySupport.getRepository(RepositoryFactorySupport.java:192)
	at org.springframework.data.repository.core.support.RepositoryFactoryBeanSupport.initAndReturn(RepositoryFactoryBeanSupport.java:239)
	at org.springframework.data.repository.core.support.RepositoryFactoryBeanSupport.afterPropertiesSet(RepositoryFactoryBeanSupport.java:225)
	at org.springframework.data.elasticsearch.repository.support.ElasticsearchRepositoryFactoryBean.afterPropertiesSet(ElasticsearchRepositoryFactoryBean.java:54)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1633)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1570)

```

**Comment by jdubois** [comment]
Yes, it's written here in the documentation: http://jhipster.github.io/using_elasticsearch.html

"This option has some limitations [...] It only works with SQL databases".

Also, you shouldn't have the option available with the generator: if you choose MongoDB, you can't choose ElasticSearch. I've tested it in the latest version and it works this way.

BTW, you should read our guidelines, and send your generator options and versions, that makes it quite difficult to answer you correctly here.

**Comment by RoryHunter** [comment]
The error message above seems to originate with the Elasticsearch repository scanning - I brute-forced an app into using Mongo and Elastic, and got the same error message. It went away after I moved all the Mongo repositories into a subpackage. :confused:
