### ISSUE TITLE
Error creating bean with name 'liquibase' defined in class path resource Reason: java.lang.IndexOutOfBoundsException: Index 0 out of bounds for   length 0

### ISSUE THREAD

**Issue by rjbgaspar** [jhipster/generator-jhipster#18512]
##### **Overview of the issue**

Error creating liquibase bean with prod profile activate, after connect to jaguar-mssql (mcr.microsoft.com/mssql/server:2019-CU15-ubuntu-20.04 image)
Please see the stack trace
<details>
    <summary>Stack trace</summary>
<pre>
:: JHipster   🤓  :: Running Spring Boot 2.6.6   ::
:: https://www.jhipster.tech ::
 
2022-04-28 12:17:48.492  INFO 1 --- [           main] com.gv.jaguar.JaguarApp                  : The following 2 profiles   are active: "prod", "api-docs"
2022-04-28 12:17:53.511  WARN 1 --- [           main]   o.s.data.convert.CustomConversions         : Registering converter from class java.util.BitSet to class   java.lang.Boolean as reading converter although it doesn't convert from a   store-supported type! You might want to check your annotation setup at the   converter implementation.
2022-04-28 12:18:00.600  WARN 1 --- [           main]   onfigReactiveWebServerApplicationContext : Exception encountered during   context initialization - cancelling refresh attempt:   org.springframework.beans.factory.BeanCreationException: Error creating bean   with name 'liquibase' defined in class path resource   [com/gv/jaguar/config/LiquibaseConfiguration.class]: Invocation of init   method failed; nested exception is liquibase.exception.LiquibaseException:   liquibase.exception.MigrationFailedException: Migration failed for change set   config/liquibase/changelog/00000000000000_initial_schema.xml::00000000000001::jhipster:
Reason: java.lang.IndexOutOfBoundsException: Index 0 out of bounds for   length 0
2022-04-28 12:18:00.747 ERROR 1 ---   [           main]   o.s.boot.SpringApplication                 : Application run failed
 
org.springframework.beans.factory.BeanCreationException:   Error creating bean with name 'liquibase' defined in class path resource   [com/gv/jaguar/config/LiquibaseConfiguration.class]: Invocation of init   method failed; nested exception is liquibase.exception.LiquibaseException:   liquibase.exception.MigrationFailedException: Migration failed for change set   config/liquibase/changelog/00000000000000_initial_schema.xml::00000000000001::jhipster:
Reason: java.lang.IndexOutOfBoundsException: Index 0 out of bounds for   length 0
at   org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1804)
at   org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:620)
at   org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
at   org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
at   org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
at   org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
at   org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
at   org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:953)
at   org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:918)
at   org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583)
at   org.springframework.boot.web.reactive.context.ReactiveWebServerApplicationContext.refresh(ReactiveWebServerApplicationContext.java:64)
at   org.springframework.boot.SpringApplication.refresh(SpringApplication.java:740)
at   org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:415)
at   org.springframework.boot.SpringApplication.run(SpringApplication.java:303)
at   com.gv.jaguar.JaguarApp.main(JaguarApp.java:69)
Caused by:   liquibase.exception.LiquibaseException:   liquibase.exception.MigrationFailedException: Migration failed for change set   config/liquibase/changelog/00000000000000_initial_schema.xml::00000000000001::jhipster:
Reason: java.lang.IndexOutOfBoundsException: Index 0 out of bounds for   length 0
at   liquibase.changelog.ChangeLogIterator.run(ChangeLogIterator.java:124)
at   liquibase.Liquibase.lambda$null$0(Liquibase.java:265)
at   liquibase.Scope.lambda$child$0(Scope.java:177)
at liquibase.Scope.child(Scope.java:186)
at liquibase.Scope.child(Scope.java:176)
at liquibase.Scope.child(Scope.java:155)
at liquibase.Scope.child(Scope.java:240)
at   liquibase.Liquibase.lambda$update$1(Liquibase.java:264)
at   liquibase.Scope.lambda$child$0(Scope.java:177)
at liquibase.Scope.child(Scope.java:186)
at liquibase.Scope.child(Scope.java:176)
at liquibase.Scope.child(Scope.java:155)
at   liquibase.Liquibase.runInScope(Liquibase.java:2404)
at   liquibase.Liquibase.update(Liquibase.java:211)
at   liquibase.Liquibase.update(Liquibase.java:197)
at   liquibase.integration.spring.SpringLiquibase.performUpdate(SpringLiquibase.java:314)
at   liquibase.integration.spring.SpringLiquibase.afterPropertiesSet(SpringLiquibase.java:269)
at   org.springframework.boot.autoconfigure.liquibase.DataSourceClosingSpringLiquibase.afterPropertiesSet(DataSourceClosingSpringLiquibase.java:46)
at   tech.jhipster.config.liquibase.AsyncSpringLiquibase.initDb(AsyncSpringLiquibase.java:118)
at   tech.jhipster.config.liquibase.AsyncSpringLiquibase.afterPropertiesSet(AsyncSpringLiquibase.java:103)
at   org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1863)
at   org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1800)
... 14 common frames omitted
Caused by:   liquibase.exception.MigrationFailedException: Migration failed for change set   config/liquibase/changelog/00000000000000_initial_schema.xml::00000000000001::jhipster:
Reason: java.lang.IndexOutOfBoundsException: Index 0 out of bounds for   length 0
at   liquibase.changelog.ChangeSet.execute(ChangeSet.java:695)
at   liquibase.changelog.visitor.UpdateVisitor.visit(UpdateVisitor.java:49)
at   liquibase.changelog.ChangeLogIterator$2.lambda$null$0(ChangeLogIterator.java:111)
at   liquibase.Scope.lambda$child$0(Scope.java:177)
at liquibase.Scope.child(Scope.java:186)
at liquibase.Scope.child(Scope.java:176)
at liquibase.Scope.child(Scope.java:155)
at   liquibase.changelog.ChangeLogIterator$2.lambda$run$1(ChangeLogIterator.java:110)
at   liquibase.Scope.lambda$child$0(Scope.java:177)
at liquibase.Scope.child(Scope.java:186)
at liquibase.Scope.child(Scope.java:176)
at liquibase.Scope.child(Scope.java:155)
at liquibase.Scope.child(Scope.java:240)
at   liquibase.changelog.ChangeLogIterator$2.run(ChangeLogIterator.java:94)
at   liquibase.Scope.lambda$child$0(Scope.java:177)
at liquibase.Scope.child(Scope.java:186)
at liquibase.Scope.child(Scope.java:176)
at liquibase.Scope.child(Scope.java:155)
at liquibase.Scope.child(Scope.java:240)
at liquibase.Scope.child(Scope.java:244)
at   liquibase.changelog.ChangeLogIterator.run(ChangeLogIterator.java:66)
... 35 common frames omitted
Caused by:   java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
at   java.base/jdk.internal.util.Preconditions.outOfBounds(Unknown Source)
at   java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Unknown   Source)
at   java.base/jdk.internal.util.Preconditions.checkIndex(Unknown Source)
at   java.base/java.util.Objects.checkIndex(Unknown Source)
at   java.base/java.util.ArrayList.get(Unknown Source)
at   liquibase.ext.mssql.change.LoadDataChangeMssql.generateStatements(LoadDataChangeMssql.java:28)
at   liquibase.database.AbstractJdbcDatabase.executeStatements(AbstractJdbcDatabase.java:1259)
at   liquibase.changelog.ChangeSet.execute(ChangeSet.java:660)
... 55 common frames omitted
</pre>
</details>

##### **Motivation for or Use Case**

Start a new project with microservice architecture, MSSQL server as a production database using docker

##### **Reproduce the error**

Create a new project and select:
    -baseName jaguar
    -reactive true
    -packageName com.gv.jaguar
    -applicationType gateway
    -authenticationType oauth2
    -buildTool maven
    -clientFramework vue
    -prodDatabaseType mssql
    -serviceDiscoveryType eureka
    -serverPort 50080

When you finished the project creation, build the gateway image and use docker compose to start keycloak, jhipster-registry,  jaguar and jaguar-mssql.

##### **Related issues**
Not applicable

##### **Suggest a Fix**
Not applicable

##### **JHipster Version(s)**
[Release 7.8.1](https://www.jhipster.tech/2022/04/07/jhipster-release-7.8.1.html)

##### **JHipster configuration**
Out of the box setup, just create a new project from scratch.

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**
No entities were added.

##### **Browsers and Operating System**
Win10 with WSL

**Comment by egvimo** [comment]
I have exactly the same issue, but with version 7.6.0.
As a workaround I've moved the `loadData` section to a separate change set and removed the "empty" imports (I don't need them anyway):

```xml
<changeSet id="00000000000001-data" author="jhipster" dbms="!mssql">
    <loadData
                file="config/liquibase/data/authority.csv"
                separator=";"
                tableName="jhi_authority"
                usePreparedStatements="true">
        <column name="name" type="string"/>
    </loadData>
</changeSet>
```

**Comment by egvimo** [comment]
Related: #16667

**Comment by DanielFran** [comment]
Fixed in https://github.com/jhipster/generator-jhipster/pull/18513
