### ISSUE TITLE
Upgrade monolith (angular) from 7.5.0 to 7.8.1 fails

### ISSUE THREAD

**Issue by crowne** [jhipster/generator-jhipster#18895]
##### **Overview of the issue**

My current version of jhipster installed globally is 7.5.0
I generated a default angular monolith and then tried to `jhipster upgrade`
It failed with the error below:

```
✔ Merge done!
git diff --name-only --diff-filter=U package.json
    force .yo-rc.json
    force .yo-rc-global.json
Installing dependencies, please wait...
     info Removing the node_modules directory
     info Removing C:\org\APP-2.0.2\appdomain\node_modules
     info npm install
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR!
npm ERR! While resolving: appdomain@0.0.1-SNAPSHOT
npm ERR! Found: @angular/common@13.1.1
npm ERR! node_modules/@angular/common
npm ERR!   @angular/common@"13.3.1" from the root project
npm ERR!   peer @angular/common@"13.1.1" from @angular/forms@13.1.1
npm ERR!   node_modules/@angular/forms
npm ERR!     @angular/forms@"13.3.1" from the root project
npm ERR!     peer @angular/forms@"^13.0.0" from @ng-bootstrap/ng-bootstrap@11.0.0
npm ERR!     node_modules/@ng-bootstrap/ng-bootstrap
npm ERR!       @ng-bootstrap/ng-bootstrap@"12.0.1" from the root project
npm ERR!   5 more (@angular/platform-browser, @angular/router, ...)
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! @angular/common@"13.3.1" from the root project
npm ERR!
npm ERR! Conflicting peer dependency: @angular/core@13.3.1
npm ERR! node_modules/@angular/core
npm ERR!   peer @angular/core@"13.3.1" from @angular/common@13.3.1
npm ERR!   node_modules/@angular/common
npm ERR!     @angular/common@"13.3.1" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See C:\Users\user.name\AppData\Local\npm-cache\eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\user.name\AppData\Local\npm-cache\_logs\2022-06-13T13_46_49_885Z-debug.log
ERROR! npm install failed.
Error: npm install failed.
    at module.exports.error (C:\util\nodejs\node-v16.13.2-win-x64\node_modules\generator-jhipster\generators\generator-base.js:1827:11)
    at module.exports.install (C:\util\nodejs\node-v16.13.2-win-x64\node_modules\generator-jhipster\generators\upgrade\index.js:512:14)
    at Object.<anonymous> (C:\util\nodejs\node-v16.13.2-win-x64\node_modules\generator-jhipster\node_modules\yeoman-generator\lib\index.js:1024:25)
    at C:\util\nodejs\node-v16.13.2-win-x64\node_modules\generator-jhipster\node_modules\run-async\index.js:49:25
    at new Promise (<anonymous>)
    at C:\util\nodejs\node-v16.13.2-win-x64\node_modules\generator-jhipster\node_modules\run-async\index.js:26:19
    at runLoop.add.once.once (C:\util\nodejs\node-v16.13.2-win-x64\node_modules\generator-jhipster\node_modules\yeoman-generator\lib\index.js:1025:11)
    at Immediate.<anonymous> (C:\util\nodejs\node-v16.13.2-win-x64\node_modules\generator-jhipster\node_modules\grouped-queue\lib\subqueue.js:48:34)
    at processImmediate (node:internal/timers:464:21)
```

##### **Motivation for or Use Case**

I expected the upgrade to work.
I generated another default monolith app, and set the client framework to React
and that app upgraded without issues

##### **Reproduce the error**

1. Install jhipster 7.5.0
2. generate a monolith, accept all defaults
3. jhipster upgrade

##### **JHipster Version(s)**

7.5.0

##### **Browsers and Operating System**

Windows 10 Version 21H2

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by mraible** [comment]
If you try `npx jhipster upgrade`, does it work?

**Comment by crowne** [comment]
That gives a different error:  

✔ Merge done!
git diff --name-only --diff-filter=U package.json
    force .yo-rc-global.json
    force .yo-rc.json
Installing dependencies, please wait...
     info Removing the node_modules directory
     info Removing C:\org\APP-2.0.2\apptmp2\node_modules
     info npm install
node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module 'C:\org\APP-2.0.2\apptmp2\node_modules\shelljs\src\exec-child.js'
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
ERROR! ENOENT: no such file or directory, open 'C:\Users\USER~1.NAM\AppData\Local\Temp\shelljs_64ea57663d34d025f9a0'
Error [ShellJSInternalError]: ENOENT: no such file or directory, open 'C:\Users\USER~1.NAM\AppData\Local\Temp\shelljs_64ea57663d34d025f9a0'
    at Object.openSync (node:fs:585:3)
    at Object.readFileSync (node:fs:453:35)
    at execSync (C:\org\APP-2.0.2\apptmp2\node_modules\shelljs\src\exec.js:89:17)
    at Object._exec (C:\org\APP-2.0.2\apptmp2\node_modules\shelljs\src\exec.js:205:12)
    at Object.exec (C:\org\APP-2.0.2\apptmp2\node_modules\shelljs\src\common.js:335:23)
    at module.exports.install (C:\org\APP-2.0.2\apptmp2\node_modules\generator-jhipster\generators\upgrade\index.js:510:34)
    at Object.<anonymous> (C:\org\APP-2.0.2\apptmp2\node_modules\yeoman-generator\lib\index.js:1024:25)
    at C:\org\APP-2.0.2\apptmp2\node_modules\run-async\index.js:49:25
    at new Promise (<anonymous>)
    at C:\org\APP-2.0.2\apptmp2\node_modules\run-async\index.js:26:19 {
  errno: -4058,
  syscall: 'open',
  code: 'ENOENT',
  path: 'C:\\Users\\USER~1.NAM\\AppData\\Local\\Temp\\shelljs_64ea57663d34d025f9a0'
}

**Comment by Tcharl** [comment]
delete your `node_modules` folder, deletes your `package.lock`, then `npm install` and `jhipster upgrade`
