### ISSUE TITLE
Cannot fix

### ISSUE THREAD

**Issue by CTaylorEason** [jhipster/generator-jhipster#18910]
Hi,

I'm having an issue with my local host. 

I went through the steps that JHipster provided, but when I run the backend and frontend, this is the error that I get. I did not change anything in the code -- every line was autogenerated by JHipster. 

I'm using PostgreSQL (local host) for my database, Java (of course) for the backend, and React for the frontend. 

Here is the error in the stack trace for the backend:

2022-06-10 12:30:50.822 WARN [testwebsite,,] 26240 --- [ XNIO-1 task-2] o.z.problem.spring.common.AdviceTraits : Unauthorized: Full authentication is required to access this resource
2022-06-10 12:30:50.857 ERROR [testwebsite,,] 26240 --- [ XNIO-1 task-1] o.z.problem.spring.common.AdviceTraits : Internal Server Error

org.springframework.web.util.NestedServletException: Handler dispatch failed; nested exception is java.io.IOError: java.io.FileNotFoundException: Invalid file path
at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1082)
at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:963)
at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898)
at javax.servlet.http.HttpServlet.service(HttpServlet.java:497)
at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
at javax.servlet.http.HttpServlet.service(HttpServlet.java:584)
...

I'm running this on a local host in postgresql, and trying to access it on google chrome, but I keep running into this error.http.500. The tables have be built in the database by jhipster, and all my code for that has been built by jhipster too. I just can't access it via npm start. I'm running both the backend via ./mvnw and then running the frontend on a new terminal with npm start. it pulls up on localhost 9000 like normal but looks like this:

![Screenshot 2022-06-10 123547](https://user-images.githubusercontent.com/74200516/173617961-e6a8d62e-c54a-47f3-bf2c-0ca8405788b8.png)

the frontend stack trace says there is something to do with my browser sync:

Error: Cannot find module 'browser-sync-client/dist/index.min.js'
Require stack:

C:\codingprojects\testwebsite\node_modules\browser-sync\dist\snippet.js
C:\codingprojects\testwebsite\node_modules\browser-sync\dist\hooks.js
C:\codingprojects\testwebsite\node_modules\browser-sync\dist\browser-sync.js
C:\codingprojects\testwebsite\node_modules\browser-sync\dist\index.js
C:\codingprojects\testwebsite\node_modules\browser-sync-webpack-plugin\lib\BrowserSyncPlugin.js
C:\codingprojects\testwebsite\node_modules\browser-sync-webpack-plugin\index.js
C:\codingprojects\testwebsite\webpack\webpack.dev.js
C:\codingprojects\testwebsite\node_modules\webpack-cli\lib\webpack-cli.js
C:\codingprojects\testwebsite\node_modules\webpack-cli\lib\bootstrap.js
C:\codingprojects\testwebsite\node_modules\webpack-cli\bin\cli.js
C:\codingprojects\testwebsite\node_modules\webpack\bin\webpack.js
at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
at Function.resolve (node:internal/modules/cjs/helpers:108:19)
at C:\codingprojects\testwebsite\node_modules\browser-sync\dist\snippet.js:87:52
at C:\codingprojects\testwebsite\node_modules\browser-sync-client\index.js:59:39
at Array.reduce ()
at processItems (C:\codingprojects\testwebsite\node_modules\browser-sync-client\index.js:54:10)
at C:\codingprojects\testwebsite\node_modules\browser-sync-client\index.js:89:22
at call (C:\codingprojects\testwebsite\node_modules\connect\index.js:239:7)
at next (C:\codingprojects\testwebsite\node_modules\connect\index.js:183:5)
at next (C:\codingprojects\testwebsite\node_modules\connect\index.js:161:14)

I have no idea what is going on. Could someone please help me resolve this on my local host?

**Comment by emilpaw** [comment]
Could you provide the information required in the issue template?

**Comment by paris0120** [comment]
I guess you didn't have keycloak

**Comment by Tcharl** [comment]
Did you `npm install` before `npm start`?
Can you post your jdl or jhispter conf (.yo-rc and .jhipster folder)?
