### ISSUE TITLE
Cassandra and date validation rules

### ISSUE THREAD

**Issue by sfoubert** [jhipster/generator-jhipster#1903]
Generating entity for cassandra with Date field and validation rules gives this error :
```
TypeError: Cannot read property 'indexOf' of undefined
    at Object.prompts.when (d:\Profiles\sfoubert\AppData\Roaming\npm\node_modules\generator-jhipster\entity\index.js:305:48)
    at Object.utils.runAsync (d:\Profiles\sfoubert\AppData\Roaming\npm\node_modules\yo\node_modules\inquirer\lib\utils\utils.js:29:22)
    at d:\Profiles\sfoubert\AppData\Roaming\npm\node_modules\yo\node_modules\inquirer\lib\ui\prompt.js:131:13
    at tryCatcher (d:\Profiles\sfoubert\AppData\Roaming\npm\node_modules\yo\node_modules\inquirer\node_modules\rx\dist\rx.js:567:29)
    at setDisposable (d:\Profiles\sfoubert\AppData\Roaming\npm\node_modules\yo\node_modules\inquirer\node_modules\rx\dist\rx.js:5233:36)
    at AnonymousObservable.s [as _subscribe] (d:\Profiles\sfoubert\AppData\Roaming\npm\node_modules\yo\node_modules\inquirer\node_modules\rx\dist\rx.js:5250:11)
    at AnonymousObservable.Rx.Observable.observableProto.subscribe.observableProto.forEach (d:\Profiles\sfoubert\AppData\Roaming\npm\node_modules\yo\node_modules\inquirer\node_modules\rx\dist\rx.js:1976:19)
    at d:\Profiles\sfoubert\AppData\Roaming\npm\node_modules\yo\node_modules\inquirer\node_modules\rx\dist\rx.js:2449:21
    at tryCatcher (d:\Profiles\sfoubert\AppData\Roaming\npm\node_modules\yo\node_modules\inquirer\node_modules\rx\dist\rx.js:567:29)
    at setDisposable (d:\Profiles\sfoubert\AppData\Roaming\npm\node_modules\yo\node_modules\inquirer\node_modules\rx\dist\rx.js:5233:36)
```
Indeed, response.fieldType 'Date' is not handled for fieldValidateRules only 'DateTime'

**Comment by sfoubert** [comment]
Sorry, i had to update my generator 2.16.1 to last version (2.19)
The commit https://github.com/jhipster/generator-jhipster/commit/9200ad9fcdc3e11dea4296819ab1769e9ac703fd#diff-ae050cf19ecf93f86e9bbdcad125936b
fix the problem
