### ISSUE TITLE
Enabling Sleuth in microservice/gateway application results in NoSuchMethodError during startup

### ISSUE THREAD

**Issue by aneri90** [jhipster/generator-jhipster#19334]
##### **Overview of the issue**

Generated application (tested with type microservice and gateway) throws NoSuchMethodError during startup when enabling spring cloud sleuth.

<pre>
Exception in thread "restartedMain" java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:119)
	at java.base/java.lang.reflect.Method.invoke(Method.java:577)
	at org.springframework.boot.devtools.restart.RestartLauncher.run(RestartLauncher.java:49)
Caused by: java.lang.NoSuchMethodError: 'boolean io.prometheus.client.exemplars.tracer.common.SpanContextSupplier.isSampled()'
	at io.prometheus.client.exemplars.DefaultExemplarSampler.doSample(DefaultExemplarSampler.java:46)
	at io.prometheus.client.exemplars.DefaultExemplarSampler.sample(DefaultExemplarSampler.java:34)
	at io.micrometer.prometheus.PrometheusCounter.updateExemplar(PrometheusCounter.java:79)
	at io.micrometer.prometheus.PrometheusCounter.increment(PrometheusCounter.java:58)
	at io.micrometer.core.instrument.Counter.increment(Counter.java:38)
	at io.micrometer.core.instrument.binder.logging.MetricsTurboFilter.decide(LogbackMetrics.java:193)
	at ch.qos.logback.classic.spi.TurboFilterList.getTurboFilterChainDecision(TurboFilterList.java:49)
	at ch.qos.logback.classic.LoggerContext.getTurboFilterChainDecision_0_3OrMore(LoggerContext.java:269)
	at ch.qos.logback.classic.Logger.filterAndLog_0_Or3Plus(Logger.java:373)
	at ch.qos.logback.classic.Logger.log(Logger.java:765)
	at org.apache.commons.logging.LogAdapter$Slf4jLocationAwareLog.error(LogAdapter.java:433)
	at org.springframework.boot.SpringApplication.reportFailure(SpringApplication.java:824)
	at org.springframework.boot.SpringApplication.handleRunFailure(SpringApplication.java:788)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:318)
	at com.mycompany.myapp.AppApp.main(AppApp.java:70)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	... 2 more
Exception in thread "SpringApplicationShutdownHook" java.lang.NoSuchMethodError: 'boolean io.prometheus.client.exemplars.tracer.common.SpanContextSupplier.isSampled()'
	at io.prometheus.client.exemplars.DefaultExemplarSampler.doSample(DefaultExemplarSampler.java:46)
	at io.prometheus.client.exemplars.DefaultExemplarSampler.sample(DefaultExemplarSampler.java:34)
	at io.micrometer.prometheus.PrometheusCounter.updateExemplar(PrometheusCounter.java:79)
	at io.micrometer.prometheus.PrometheusCounter.increment(PrometheusCounter.java:58)
	at io.micrometer.core.instrument.Counter.increment(Counter.java:38)
	at io.micrometer.core.instrument.binder.logging.MetricsTurboFilter.decide(LogbackMetrics.java:202)
	at ch.qos.logback.classic.spi.TurboFilterList.getTurboFilterChainDecision(TurboFilterList.java:49)
	at ch.qos.logback.classic.LoggerContext.getTurboFilterChainDecision_0_3OrMore(LoggerContext.java:269)
	at ch.qos.logback.classic.Logger.filterAndLog_0_Or3Plus(Logger.java:373)
	at ch.qos.logback.classic.Logger.log(Logger.java:765)
	at org.apache.commons.logging.LogAdapter$Slf4jLocationAwareLog.debug(LogAdapter.java:468)
	at org.springframework.context.support.AbstractApplicationContext.doClose(AbstractApplicationContext.java:1049)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.doClose(ServletWebServerApplicationContext.java:174)
	at org.springframework.context.support.AbstractApplicationContext.close(AbstractApplicationContext.java:1021)
	at org.springframework.boot.SpringApplicationShutdownHook.closeAndWait(SpringApplicationShutdownHook.java:145)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at org.springframework.boot.SpringApplicationShutdownHook.run(SpringApplicationShutdownHook.java:114)
	at java.base/java.lang.Thread.run(Thread.java:833)
</pre>
##### **Motivation for or Use Case**

Restore sleuth and zipkin in generated application.

##### **Reproduce the error**

1. Generate an application with either microservice or gateway type (or with attacched .yo-rc)
2. Enable sleuth and zipkin in application-dev.yml: `spring.sleuth.enabled: true` `spring.zipkin.enabled: true`
3. Start supporting services: `docker compose -f src/main/docker/postgresql.yml -f src/main/docker/zipkin.yml up`
4. Start application: `./mvnw -Pdev,zipkin`

##### **Suggest a Fix**

The issues seems caused by a conflict in the versions declared for `io.prometheus:simpleclient:jar:0.16`.
<details>
<summary>mvn dependency:tree</summary>
<pre>
[INFO] +- io.micrometer:micrometer-registry-prometheus:jar:1.9.2:compile
[INFO] |  \- io.prometheus:simpleclient_common:jar:0.15.0:compile
[INFO] |     \- <b>io.prometheus:simpleclient:jar:0.16.0:compile</b>
[INFO] |        +- io.prometheus:simpleclient_tracer_otel:jar:0.15.0:compile
[INFO] |        |  \- io.prometheus:simpleclient_tracer_common:jar:0.15.0:compile
[INFO] |        \- io.prometheus:simpleclient_tracer_otel_agent:jar:0.15.0:compile
</pre>
</details>

This issue seems to be caused by `tech.jhipster.jhipster-dependencies` that is forcing the [0.16.0](https://github.com/jhipster/jhipster-bom/blob/c7b05ce562c519989a4d772d4fc8e07ce67b388d/jhipster-dependencies/pom.xml#L71) version. 

I solved with a workaround in my application by forcing `io.prometheus:simpleclient:jar:0.15.0` in my pom.xml 

##### **JHipster Version(s)**

<pre>
app@0.0.0 /home/jhipster/app
└── generator-jhipster@7.9.2
</pre>

##### **JHipster configuration**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "applicationType": "microservice",
    "authenticationType": "jwt",
    "baseName": "app",
    "blueprints": [],
    "buildTool": "maven",
    "cacheProvider": "hazelcast",
    "creationTimestamp": 1659598044411,
    "databaseType": "sql",
    "devDatabaseType": "postgresql",
    "dtoSuffix": "DTO",
    "enableGradleEnterprise": false,
    "enableHibernateCache": true,
    "enableSwaggerCodegen": false,
    "enableTranslation": false,
    "entitySuffix": "",
    "jhiPrefix": "jhi",
    "jhipsterVersion": "7.9.2",
    "jwtSecretKey": "YourJWTSecretKeyWasReplacedByThisMeaninglessTextByTheJHipsterInfoCommandForObviousSecurityReasons",
    "languages": ["en", "fr"],
    "messageBroker": false,
    "microfrontend": false,
    "microfrontends": [],
    "nativeLanguage": "en",
    "otherModules": [],
    "packageName": "com.mycompany.myapp",
    "pages": [],
    "prodDatabaseType": "postgresql",
    "reactive": false,
    "searchEngine": false,
    "serverPort": "8081",
    "serverSideOptions": [],
    "serviceDiscoveryType": "no",
    "skipCheckLengthOfIdentifier": false,
    "skipClient": true,
    "skipFakeData": false,
    "skipUserManagement": true,
    "testFrameworks": [],
    "websocket": false,
    "withAdminUi": false
  }
}

</pre>
</details>

##### **Environment and Tools**

openjdk version "11.0.16" 2022-07-19
OpenJDK Runtime Environment Temurin-11.0.16+8 (build 11.0.16+8)
OpenJDK 64-Bit Server VM Temurin-11.0.16+8 (build 11.0.16+8, mixed mode)

git version 2.25.1

node: v16.16.0

npm: 7.24.2

##### **Browsers and Operating System**

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by UbaidurRehman1** [comment]
Hi @deepu105 
Can you please assign this issue to me. I'd like to spend my weekend on this issue as I recently fixed similar type of issue. 

Thanks

**Comment by UbaidurRehman1** [comment]
Hi @vishal423 

## Quick Fix
The quickest and smallest fix is to change `prometheus-simpleclient.version` from 0.16.0 to 0.15.0 in [jhipster-dependencies](https://github.com/jhipster/jhipster-bom/blob/main/jhipster-dependencies/pom.xml). 

The resultant dependency tree is following on changing `prometheus-simpleclient.version` from 0.16.0 to 0.15.0:

```
[INFO] |  +- (io.micrometer:micrometer-core:jar:1.9.2:compile - omitted for duplicate)
[INFO] |  \- io.prometheus:simpleclient_common:jar:0.15.0:compile
[INFO] |     \- io.prometheus:simpleclient:jar:0.15.0:compile
[INFO] |        +- io.prometheus:simpleclient_tracer_otel:jar:0.15.0:compile
[INFO] |        |  \- io.prometheus:simpleclient_tracer_common:jar:0.15.0:compile
[INFO] |        \- io.prometheus:simpleclient_tracer_otel_agent:jar:0.15.0:compile
[INFO] |           \- (io.prometheus:simpleclient_tracer_common:jar:0.15.0:compile - omitted for duplicate)

```
so, here we can see the dependency version for each `io.prometheus` artifact is 0.15.0 and it fixed the issue. 

## Another Fix
(I didn't test it yet)
I was thinking to migrate all artifacts of `io.prometheus` to 0.16.0 by changing version of `io.micrometer:micrometer-core` to 1.9.3, but `io.micrometer:micrometer-core:1.9.3` has dependency on `io.prometheus:simpleclient_common:0.15.0`, so we will get the same issue again. 

But, I can give it a try locally by changing  dependency version of `simpleclient_common` to 0.16.0 for `io.micrometer:micrometer-core:1.9.3`. 

**Let me know your thoughts please about Quick fix and Another fix?** 

Thanks

**Comment by vishal423** [comment]
I think downgrading to a compatible version should be fine. @DanielFran, do you agree with this?

Irrespective of this change, I also suggest adding a CI test to detect such failures in a future dependency upgrade.

**Comment by DanielFran** [comment]
@vishal423 @UbaidurRehman1 created PR to downgrade the version to 0.15.0

Can you take care of the test to avoid regressions?

**Comment by dalyc** [comment]
This is my solution until this is fixed...

```
        <dependency>
            <groupId>io.micrometer</groupId>
            <artifactId>micrometer-registry-prometheus</artifactId>
<!-- start of workaround for 7.9.2 jhipster versioning issue           -->
            <exclusions>
                <exclusion>
                    <groupId>io.prometheus</groupId>
                    <artifactId>simpleclient_common</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>io.prometheus</groupId>
            <artifactId>simpleclient_common</artifactId>
            <version>0.16.0</version>
            <exclusions>
                <exclusion>
                    <groupId>io.prometheus</groupId>
                    <artifactId>simpleclient_tracer_otel</artifactId>
                </exclusion>
               <exclusion>
                    <groupId>io.prometheus</groupId>
                    <artifactId>simpleclient_tracer_otel_agent</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>io.prometheus</groupId>
            <artifactId>simpleclient_tracer_otel</artifactId>
            <version>0.16.0</version>
<!-- end of workaround for 7.9.2 jhipster versioning issue - delete all between comments         -->
        </dependency>

```

**Comment by dalyc** [comment]
Would bumping the simpleclient_bom version fix this issue? The following is taken from the 7.9.2 dependencies on mvnrepository.com 

![image](https://user-images.githubusercontent.com/946190/185005975-7721eb1f-49b2-426d-b7c4-4dcdea1c1746.png)

**Comment by AdamLevy123** [comment]
> 



> This is my solution until this is fixed... keeping simpleclient_common at 0.16
> 
> ```
>         <dependency>
>             <groupId>io.micrometer</groupId>
>             <artifactId>micrometer-registry-prometheus</artifactId>
> 
>             <exclusions>
>                 <exclusion>
>                     <groupId>io.prometheus</groupId>
>                     <artifactId>simpleclient_common</artifactId>
>                 </exclusion>
>             </exclusions>
>         </dependency>
>         <dependency>
>             <groupId>io.prometheus</groupId>
>             <artifactId>simpleclient_common</artifactId>
>             <version>0.16.0</version>
>             <exclusions>
>                 <exclusion>
>                     <groupId>io.prometheus</groupId>
>                     <artifactId>simpleclient_tracer_otel</artifactId>
>                 </exclusion>
>                <exclusion>
>                     <groupId>io.prometheus</groupId>
>                     <artifactId>simpleclient_tracer_otel_agent</artifactId>
>                 </exclusion>
>             </exclusions>
>         </dependency>
>         <dependency>
>             <groupId>io.prometheus</groupId>
>             <artifactId>simpleclient_tracer_otel</artifactId>
>             <version>0.16.0</version>
> 
>         </dependency>
> ```

that one gives me:

`Exception in thread "SpringApplicationShutdownHook" 
java.lang.AbstractMethodError: Receiver class org.springframework.cloud.sleuth.instrument.prometheus.LazySleuthSpanContextSupplier 
does not define or inherit an implementation of the resolved method 'abstract boolean isSampled()' 
of interface io.prometheus.client.exemplars.tracer.common.SpanContextSupplier.    
	at io.prometheus.client.exemplars.DefaultExemplarSampler.doSample(DefaultExemplarSampler.java:46)    
	at io.prometheus.client.exemplars.DefaultExemplarSampler.sample(DefaultExemplarSampler.java:34)    
	at io.micrometer.prometheus.PrometheusCounter.updateExemplar(PrometheusCounter.java:79)    
	at io.micrometer.prometheus.PrometheusCounter.increment(PrometheusCounter.java:58)    
	at io.micrometer.core.instrument.Counter.increment(Counter.java:38)    
	at io.micrometer.core.instrument.binder.logging.MetricsTurboFilter.decide(LogbackMetrics.java:202)    
	at ch.qos.logback.classic.spi.TurboFilterList.getTurboFilterChainDecision(TurboFilterList.java:49)    
	at ch.qos.logback.classic.LoggerContext.getTurboFilterChainDecision_0_3OrMore(LoggerContext.java:269)    
	at ch.qos.logback.classic.Logger.filterAndLog_0_Or3Plus(Logger.java:373)    at ch.qos.logback.classic.Logger.log(Logger.java:765)    
	at org.apache.commons.logging.LogAdapter$Slf4jLocationAwareLog.debug(LogAdapter.java:468)    
	at org.springframework.context.support.AbstractApplicationContext.doClose(AbstractApplicationContext.java:1049)    
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.doClose(ServletWebServerApplicationContext.java:174)    
	at org.springframework.context.support.AbstractApplicationContext.close(AbstractApplicationContext.java:1021)    
	at org.springframework.boot.SpringApplicationShutdownHook.closeAndWait(SpringApplicationShutdownHook.java:145)    
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)    
	at org.springframework.boot.SpringApplicationShutdownHook.run(SpringApplicationShutdownHook.java:114)    
	at java.base/java.lang.Thread.run(Thread.java:833)
Disconnected from the target VM, address: '127.0.0.1:53299', transport: 'socket'`

**Comment by AdamLevy123** [comment]
> This is my solution until this is fixed... keeping simpleclient_common at 0.16
> 
> ```
>         <dependency>
>             <groupId>io.micrometer</groupId>
>             <artifactId>micrometer-registry-prometheus</artifactId>
> 
>             <exclusions>
>                 <exclusion>
>                     <groupId>io.prometheus</groupId>
>                     <artifactId>simpleclient_common</artifactId>
>                 </exclusion>
>             </exclusions>
>         </dependency>
>         <dependency>
>             <groupId>io.prometheus</groupId>
>             <artifactId>simpleclient_common</artifactId>
>             <version>0.16.0</version>
>             <exclusions>
>                 <exclusion>
>                     <groupId>io.prometheus</groupId>
>                     <artifactId>simpleclient_tracer_otel</artifactId>
>                 </exclusion>
>                <exclusion>
>                     <groupId>io.prometheus</groupId>
>                     <artifactId>simpleclient_tracer_otel_agent</artifactId>
>                 </exclusion>
>             </exclusions>
>         </dependency>
>         <dependency>
>             <groupId>io.prometheus</groupId>
>             <artifactId>simpleclient_tracer_otel</artifactId>
>             <version>0.16.0</version>
> 
>         </dependency>
> ```

that one gives me:

> Exception in thread "SpringApplicationShutdownHook" 
> java.lang.AbstractMethodError: Receiver class org.springframework.cloud.sleuth.instrument.prometheus.LazySleuthSpanContextSupplier 
> does not define or inherit an implementation of the resolved method 'abstract boolean isSampled()' 
> of interface io.prometheus.client.exemplars.tracer.common.SpanContextSupplier.    
> 	at io.prometheus.client.exemplars.DefaultExemplarSampler.doSample(DefaultExemplarSampler.java:46)    
> 	at io.prometheus.client.exemplars.DefaultExemplarSampler.sample(DefaultExemplarSampler.java:34)    
> 	at io.micrometer.prometheus.PrometheusCounter.updateExemplar(PrometheusCounter.java:79)    
> 	at io.micrometer.prometheus.PrometheusCounter.increment(PrometheusCounter.java:58)    
> 	at io.micrometer.core.instrument.Counter.increment(Counter.java:38)    
> 	at io.micrometer.core.instrument.binder.logging.MetricsTurboFilter.decide(LogbackMetrics.java:202)    
> 	at ch.qos.logback.classic.spi.TurboFilterList.getTurboFilterChainDecision(TurboFilterList.java:49)    
> 	at ch.qos.logback.classic.LoggerContext.getTurboFilterChainDecision_0_3OrMore(LoggerContext.java:269)    
> 	at ch.qos.logback.classic.Logger.filterAndLog_0_Or3Plus(Logger.java:373)    at ch.qos.logback.classic.Logger.log(Logger.java:765)    
> 	at org.apache.commons.logging.LogAdapter$Slf4jLocationAwareLog.debug(LogAdapter.java:468)    
> 	at org.springframework.context.support.AbstractApplicationContext.doClose(AbstractApplicationContext.java:1049)    
> 	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.doClose(ServletWebServerApplicationContext.java:174)    
> 	at org.springframework.context.support.AbstractApplicationContext.close(AbstractApplicationContext.java:1021)    
> 	at org.springframework.boot.SpringApplicationShutdownHook.closeAndWait(SpringApplicationShutdownHook.java:145)    
> 	at java.base/java.lang.Iterable.forEach(Iterable.java:75)    
> 	at org.springframework.boot.SpringApplicationShutdownHook.run(SpringApplicationShutdownHook.java:114)    
> 	at java.base/java.lang.Thread.run(Thread.java:833)
> Disconnected from the target VM, address: '127.0.0.1:53299', transport: 'socket'

**Comment by dalyc** [comment]
Thanks for letting me know Adam. I'm not actually using Sleuth - my issue was a dependency convergence issue so I'll remove my comment from here.
