### ISSUE TITLE
Logging in with Auth0 fails

### ISSUE THREAD

**Issue by mraible** [jhipster/generator-jhipster#19582]
##### **Overview of the issue**

I configured my app to use Auth0 and when I try to login, it results in an error:

```
Caused by: javax.persistence.RollbackException: Error while committing the transaction
        at org.hibernate.internal.ExceptionConverterImpl.convertCommitException(ExceptionConverterImpl.java:81)
        at org.hibernate.engine.transaction.internal.TransactionImpl.commit(TransactionImpl.java:104)
        at org.springframework.orm.jpa.JpaTransactionManager.doCommit(JpaTransactionManager.java:562)
        ... 171 common frames omitted
Caused by: javax.validation.ConstraintViolationException: Validation failed for classes [com.auth0.flickr2.domain.User] during persist time for groups [javax.validation.groups.Default, ]
List of constraint violations:[
        ConstraintViolationImpl{interpolatedMessage='must match "^(?>[a-zA-Z0-9!$&*+=?^_`{|}~.-]+@[a-zA-Z0-9-]+(?:\.[a-zA-Z0-9-]+)*)|(?>[_.@A-Za-z0-9-]+)$"', propertyPath=login, rootBeanClass=class com.auth0.flickr2.domain.User, messageTemplate='{javax.validation.constraints.Pattern.message}'}
]
        at org.hibernate.cfg.beanvalidation.BeanValidationEventListener.validate(BeanValidationEventListener.java:140)
        at org.hibernate.cfg.beanvalidation.BeanValidationEventListener.onPreInsert(BeanValidationEventListener.java:80)
        at org.hibernate.action.internal.EntityInsertAction.preInsert(EntityInsertAction.java:214)
        at org.hibernate.action.internal.EntityInsertAction.execute(EntityInsertAction.java:100)
        at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:604)
        at org.hibernate.engine.spi.ActionQueue.lambda$executeActions$1(ActionQueue.java:478)
        at java.base/java.util.LinkedHashMap.forEach(LinkedHashMap.java:721)
        at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:475)
        at org.hibernate.event.internal.AbstractFlushingEventListener.performExecutions(AbstractFlushingEventListener.java:344)
        at org.hibernate.event.internal.DefaultFlushEventListener.onFlush(DefaultFlushEventListener.java:40)
        at org.hibernate.event.service.internal.EventListenerGroupImpl.fireEventOnEachListener(EventListenerGroupImpl.java:99)
        at org.hibernate.internal.SessionImpl.doFlush(SessionImpl.java:1362)
        at org.hibernate.internal.SessionImpl.managedFlush(SessionImpl.java:453)
        at org.hibernate.internal.SessionImpl.flushBeforeTransactionCompletion(SessionImpl.java:3212)
        at org.hibernate.internal.SessionImpl.beforeTransactionCompletion(SessionImpl.java:2380)
        at org.hibernate.engine.jdbc.internal.JdbcCoordinatorImpl.beforeTransactionCompletion(JdbcCoordinatorImpl.java:448)
        at org.hibernate.resource.transaction.backend.jdbc.internal.JdbcResourceLocalTransactionCoordinatorImpl.beforeCompletionCallback(JdbcResourceLocalTransactionCoordinatorImpl.java:183)
        at org.hibernate.resource.transaction.backend.jdbc.internal.JdbcResourceLocalTransactionCoordinatorImpl.access$300(JdbcResourceLocalTransactionCoordinatorImpl.java:40)
        at org.hibernate.resource.transaction.backend.jdbc.internal.JdbcResourceLocalTransactionCoordinatorImpl$TransactionDriverControlImpl.commit(JdbcResourceLocalTransactionCoordinatorImpl.java:281)
        at org.hibernate.engine.transaction.internal.TransactionImpl.commit(TransactionImpl.java:101)
        ... 172 common frames omitted
```

##### **Motivation for or Use Case**

It used to work when I last tried it.

##### **Reproduce the error**

Create an app, integrate it with Auth0, try to login.

##### **Suggest a Fix**

In `UserService.java`, change the following conditional:

```java
if (username != null) {
    user.setLogin(username);
} else if (user.getLogin() == null) {
    user.setLogin(user.getId());
}
```

To this:

```java
if (username != null) {
    user.setLogin(username);
} else if (user.getLogin() == null) {
    // special handling for Auth0
    if (sub.contains("|")) {
        user.setLogin(details.get("email").toString());
    } else {
        user.setLogin(user.getId());
    }
}
```

##### **JHipster Version(s)**

7.3.1++

It still exists in the `main` branch.

**Comment by vishal423** [comment]
It seems a configuration issue on the `Auth0` side. Did you configure JHipster specific claims as documented over here https://www.jhipster.tech/security/#auth0 ?

**Comment by mraible** [comment]
That makes sense. I converted to using Actions as described in https://github.com/jhipster/jhipster.github.io/pull/1227. It seems I need a way to add this same logic to my action.

```js
user.preferred_username = user.email;
```

**Comment by mraible** [comment]
This seems to work:

```
api.idToken.setCustomClaim("preferred_username", event.user.email);
```

I'll close this issue. Thanks for the review @vishal423!
