### ISSUE TITLE
Error: Error parsing file src\main\webapp\app\layouts\error\error.route.ts: SyntaxError: ',' expected. (10:26)

### ISSUE THREAD

**Issue by maata32** [jhipster/generator-jhipster#20362]
##### **Browsers and Operating System**

- [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by mraible** [comment]
Can you please provide more information on how to reproduce this issue? If we can't repoduce it, we can't fix it!

**Comment by maata32** [comment]
Good morning The issue appears when I try to generate app with jhipster 7 9.3 and node18 on windows11 
Envoyé depuis Yahoo Mail pour Android 
 
  Le jeu., nov. 17, 2022 à 14:06, Matt ***@***.***> a écrit:   


Can you please provide more information on how to reproduce this issue? If we can't repoduce it, we can't fix it!

**Comment by ebousse** [comment]
Same error here using version `v8.0.0-beta.2`, here are my complete logs:

```
» jhipster

        ██╗ ██╗   ██╗ ████████╗ ███████╗   ██████╗ ████████╗ ████████╗ ███████╗
        ██║ ██║   ██║ ╚══██╔══╝ ██╔═══██╗ ██╔════╝ ╚══██╔══╝ ██╔═════╝ ██╔═══██╗
        ██║ ████████║    ██║    ███████╔╝ ╚█████╗     ██║    ██████╗   ███████╔╝
  ██╗   ██║ ██╔═══██║    ██║    ██╔════╝   ╚═══██╗    ██║    ██╔═══╝   ██╔══██║
  ╚██████╔╝ ██║   ██║ ████████╗ ██║       ██████╔╝    ██║    ████████╗ ██║  ╚██╗
   ╚═════╝  ╚═╝   ╚═╝ ╚═══════╝ ╚═╝       ╚═════╝     ╚═╝    ╚═══════╝ ╚═╝   ╚═╝
                            https://www.jhipster.tech
Welcome to JHipster v8.0.0-beta.2

 _______________________________________________________________________________________________________________

  Documentation for creating an application is at https://www.jhipster.tech/creating-an-app/

  Application files will be generated in folder: <redacted>/myApp
 _______________________________________________________________________________________________________________

? What is the base name of your application? myApp
? May JHipster anonymously report usage statistics to improve the tool over time? No
? Which *type* of application would you like to create? Monolithic application (recommended for simple projects)
? Would you like to enable internationalization support? No
? Please choose the native language of the application French
? Please choose additional languages to install 
? Do you want to make it reactive with Spring WebFlux? No
? What is your default Java package name? com.mycompany.myapp
? Which *type* of authentication would you like to use? JWT authentication (stateless, with a token)
? Which *type* of database would you like to use? SQL (H2, PostgreSQL, MySQL, MariaDB, Oracle, MSSQL)
? Which *production* database would you like to use? PostgreSQL
? Which *development* database would you like to use? H2 with disk-based persistence
? Which cache do you want to use? (Spring cache abstraction) Ehcache (local cache, for a single node)
? Do you want to use Hibernate 2nd level cache? No
? Would you like to use Maven or Gradle for building the backend? Maven
? Which other technologies would you like to use? 
? Which *Framework* would you like to use for the client? Angular
? Do you want to generate the admin UI? Yes
? Would you like to use a Bootswatch theme (https://bootswatch.com/)? Default JHipster
? Besides JUnit and Jest, which testing frameworks would you like to use? 
     info Génération d'une paire de clés RSA de 2 048 bits et d'un certificat auto-signé (SHA256withRSA) d'une validité de 99 999 jours
     info       pour : CN=Java Hipster, OU=Development, O=com.mycompany.myapp, L=, ST=, C=
     info KeyStore '<redacted>/myApp/src/main/resources/config/tls/keystore.p12' generated successfully.
✔ applying multi-step templates
✔ Git repository initialized.
✔ adding package-info.java files
✔ translating webapp
   create .prettierrc
   create .prettierignore
   create package.json
    force .yo-rc.json
   create .gitignore
   create .gitattributes
   create README.md
   create .editorconfig
   create sonar-project.properties
   create .lintstagedrc.js
   create .husky/pre-commit
   create npmw
   create npmw.cmd
   create src/main/resources/banner.txt
   create src/main/docker/jib/entrypoint.sh
   create checkstyle.xml
   create .devcontainer/Dockerfile
   create .devcontainer/devcontainer.json
   create pom.xml
   create src/main/java/com/mycompany/myapp/GeneratedByJHipster.java
   create src/main/resources/logback-spring.xml
   create src/main/resources/templates/error.html
   create src/main/resources/config/application.yml
   create src/main/resources/config/application-tls.yml
   create src/main/resources/config/application-dev.yml
   create src/main/resources/config/application-prod.yml
   create src/main/resources/i18n/messages.properties
   create src/main/java/com/mycompany/myapp/security/SpringSecurityAuditorAware.java
   create src/main/java/com/mycompany/myapp/security/SecurityUtils.java
   create src/main/java/com/mycompany/myapp/security/AuthoritiesConstants.java
   create src/main/java/com/mycompany/myapp/config/SecurityConfiguration.java
   create src/main/java/com/mycompany/myapp/MyApp.java
   create src/test/java/com/mycompany/myapp/security/SecurityUtilsUnitTest.java
   create src/test/java/com/mycompany/myapp/TechnicalStructureTest.java
   create src/test/java/com/mycompany/myapp/config/AsyncSyncConfiguration.java
   create src/test/java/com/mycompany/myapp/IntegrationTest.java
   create src/test/java/com/mycompany/myapp/config/SpringBootTestClassOrderer.java
   create src/main/java/com/mycompany/myapp/config/AsyncConfiguration.java
   create src/main/java/com/mycompany/myapp/aop/logging/LoggingAspect.java
   create src/main/java/com/mycompany/myapp/config/CRLFLogConverter.java
   create src/main/java/com/mycompany/myapp/config/DateTimeFormatConfiguration.java
   create src/main/java/com/mycompany/myapp/config/LoggingConfiguration.java
   create src/main/java/com/mycompany/myapp/config/ApplicationProperties.java
   create src/main/java/com/mycompany/myapp/config/JacksonConfiguration.java
   create src/main/java/com/mycompany/myapp/config/LoggingAspectConfiguration.java
   create src/main/java/com/mycompany/myapp/config/WebConfigurer.java
   create src/main/java/com/mycompany/myapp/config/Constants.java
   create src/main/java/com/mycompany/myapp/config/LocaleConfiguration.java
   create src/main/java/com/mycompany/myapp/domain/AbstractAuditingEntity.java
   create src/main/java/com/mycompany/myapp/web/rest/errors/BadRequestAlertException.java
   create src/main/java/com/mycompany/myapp/web/rest/errors/ErrorConstants.java
   create src/main/java/com/mycompany/myapp/web/rest/errors/ExceptionTranslator.java
   create src/main/java/com/mycompany/myapp/web/rest/errors/FieldErrorVM.java
   create src/main/java/com/mycompany/myapp/config/StaticResourcesWebConfiguration.java
   create src/test/java/com/mycompany/myapp/config/StaticResourcesWebConfigurerTest.java
   create src/main/java/com/mycompany/myapp/web/filter/SpaWebFilter.java
   create src/test/java/com/mycompany/myapp/web/filter/SpaWebFilterIT.java
   create src/test/java/com/mycompany/myapp/web/rest/TestUtil.java
   create src/test/java/com/mycompany/myapp/web/rest/errors/ExceptionTranslatorTestController.java
   create src/test/java/com/mycompany/myapp/web/rest/errors/ExceptionTranslatorIT.java
   create src/test/resources/logback.xml
   create src/test/resources/junit-platform.properties
   create src/test/resources/config/application.yml
   create src/main/java/com/mycompany/myapp/domain/Authority.java
   create src/main/java/com/mycompany/myapp/repository/AuthorityRepository.java
   create src/test/java/com/mycompany/myapp/web/rest/WithUnauthenticatedMockUser.java
   create src/main/java/com/mycompany/myapp/config/SecurityJwtConfiguration.java
   create src/main/java/com/mycompany/myapp/management/SecurityMetersService.java
   create src/test/java/com/mycompany/myapp/management/SecurityMetersServiceTests.java
   create src/test/java/com/mycompany/myapp/security/jwt/AuthenticationIntegrationTest.java
   create src/test/java/com/mycompany/myapp/security/jwt/JwtAuthenticationTestUtils.java
   create src/test/java/com/mycompany/myapp/security/jwt/TokenAuthenticationSecurityMetersIT.java
   create src/test/java/com/mycompany/myapp/security/jwt/TokenAuthenticationIT.java
   create src/main/java/com/mycompany/myapp/web/rest/vm/LoginVM.java
   create src/main/java/com/mycompany/myapp/web/rest/AuthenticateController.java
   create src/test/java/com/mycompany/myapp/web/rest/AuthenticateControllerIT.java
   create src/main/java/com/mycompany/myapp/web/rest/AccountResource.java
   create src/main/java/com/mycompany/myapp/web/rest/vm/ManagedUserVM.java
   create src/test/java/com/mycompany/myapp/web/rest/AccountResourceIT.java
   create src/main/java/com/mycompany/myapp/security/DomainUserDetailsService.java
   create src/main/java/com/mycompany/myapp/security/UserNotActivatedException.java
   create src/main/java/com/mycompany/myapp/service/MailService.java
   create src/main/java/com/mycompany/myapp/service/dto/PasswordChangeDTO.java
   create src/main/java/com/mycompany/myapp/service/EmailAlreadyUsedException.java
   create src/main/java/com/mycompany/myapp/service/InvalidPasswordException.java
   create src/main/java/com/mycompany/myapp/service/UsernameAlreadyUsedException.java
   create src/main/java/com/mycompany/myapp/web/rest/UserResource.java
   create src/main/java/com/mycompany/myapp/web/rest/vm/KeyAndPasswordVM.java
   create src/main/java/com/mycompany/myapp/web/rest/errors/EmailAlreadyUsedException.java
   create src/main/java/com/mycompany/myapp/web/rest/errors/InvalidPasswordException.java
   create src/main/java/com/mycompany/myapp/web/rest/errors/LoginAlreadyUsedException.java
   create src/test/java/com/mycompany/myapp/service/MailServiceIT.java
   create src/test/java/com/mycompany/myapp/security/DomainUserDetailsServiceIT.java
   create src/main/resources/templates/mail/activationEmail.html
   create src/main/resources/templates/mail/passwordResetEmail.html
   create src/main/resources/templates/mail/creationEmail.html
   create src/test/resources/templates/mail/activationEmail.html
   create src/test/resources/templates/mail/creationEmail.html
   create src/test/resources/templates/mail/passwordResetEmail.html
   create src/test/resources/templates/mail/testEmail.html
   create src/test/resources/i18n/messages_en.properties
   create src/main/java/com/mycompany/myapp/ApplicationWebXml.java
   create src/test/java/com/mycompany/myapp/config/WebConfigurerTest.java
   create src/test/java/com/mycompany/myapp/config/WebConfigurerTestController.java
   create src/main/webapp/content/images/jhipster_family_member_0.svg
   create src/main/webapp/content/images/jhipster_family_member_0_head-192.png
   create src/main/webapp/content/images/jhipster_family_member_0_head-256.png
   create src/main/webapp/content/images/jhipster_family_member_0_head-384.png
   create src/main/webapp/content/images/jhipster_family_member_1.svg
   create src/main/webapp/content/images/jhipster_family_member_0_head-512.png
   create src/main/webapp/content/images/jhipster_family_member_1_head-192.png
   create src/main/webapp/content/images/jhipster_family_member_1_head-256.png
   create src/main/webapp/content/images/jhipster_family_member_1_head-384.png
   create src/main/webapp/content/images/jhipster_family_member_1_head-512.png
   create src/main/webapp/content/images/jhipster_family_member_2.svg
   create src/main/webapp/content/images/jhipster_family_member_2_head-192.png
   create src/main/webapp/content/images/jhipster_family_member_2_head-256.png
   create src/main/webapp/content/images/jhipster_family_member_2_head-384.png
   create src/main/webapp/content/images/jhipster_family_member_2_head-512.png
   create src/main/webapp/content/images/jhipster_family_member_3.svg
   create src/main/webapp/content/images/jhipster_family_member_3_head-192.png
   create src/main/webapp/content/images/jhipster_family_member_3_head-256.png
   create src/main/webapp/content/images/jhipster_family_member_3_head-384.png
   create src/main/webapp/content/images/jhipster_family_member_3_head-512.png
   create src/main/webapp/content/images/logo-jhipster.png
   create src/main/webapp/favicon.ico
   create src/main/webapp/swagger-ui/dist/images/throbber.gif
   create .eslintignore
   create src/main/webapp/manifest.webapp
   create src/main/webapp/WEB-INF/web.xml
   create src/main/webapp/robots.txt
   create src/main/webapp/content/css/loading.css
   create src/main/webapp/index.html
   create src/main/webapp/404.html
   create mvnw.cmd
   create mvnw
   create src/main/webapp/swagger-ui/index.html
   create .mvn/wrapper/maven-wrapper.properties
   create .mvn/wrapper/maven-wrapper.jar
   create .mvn/jvm.config
   create src/main/docker/postgresql.yml
   create src/main/docker/jhipster-control-center.yml
   create src/main/docker/app.yml
   create src/main/docker/sonar.yml
   create src/main/docker/monitoring.yml
   create src/main/docker/prometheus/prometheus.yml
   create src/main/docker/grafana/provisioning/dashboards/dashboard.yml
   create src/main/docker/grafana/provisioning/dashboards/JVM.json
   create src/main/docker/grafana/provisioning/datasources/datasource.yml
   create src/main/java/com/mycompany/myapp/config/DatabaseConfiguration.java
   create src/test/java/com/mycompany/myapp/config/timezone/HibernateTimeZoneIT.java
   create src/test/java/com/mycompany/myapp/repository/timezone/DateTimeWrapper.java
   create src/test/java/com/mycompany/myapp/repository/timezone/DateTimeWrapperRepository.java
   create src/test/java/com/mycompany/myapp/config/EmbeddedSQL.java
   create src/test/java/com/mycompany/myapp/config/SqlTestContainer.java
   create src/test/java/com/mycompany/myapp/config/SqlTestContainersSpringContextCustomizerFactory.java
   create src/test/resources/config/application-testdev.yml
   create src/test/resources/config/application-testprod.yml
   create src/main/resources/.h2.server.properties
   create src/test/java/com/mycompany/myapp/config/PostgreSqlTestContainer.java
   create src/main/java/com/mycompany/myapp/config/CacheConfiguration.java
   create webpack/logo-jhipster.png
   create tsconfig.json
   create tsconfig.app.json
   create tsconfig.spec.json
   create jest.conf.js
   create .eslintrc.json
   create angular.json
   create ngsw-config.json
   create webpack/environment.js
   create webpack/webpack.custom.js
   create webpack/proxy.conf.js
   create src/main/webapp/content/scss/_bootstrap-variables.scss
   create src/main/webapp/content/scss/global.scss
   create src/main/webapp/content/scss/vendor.scss
   create src/main/webapp/main.ts
   create src/main/webapp/bootstrap.ts
   create src/main/webapp/declarations.d.ts
   create src/main/webapp/app/app.module.ts
   create src/main/webapp/app/app.constants.ts
   create src/main/webapp/app/app-routing.module.ts
   create src/main/webapp/app/app-page-title-strategy.ts
   create src/main/webapp/app/entities/entity-navbar-items.ts
   create src/main/webapp/app/entities/entity-routing.module.ts
   create src/main/webapp/app/home/home.component.ts
   create src/main/webapp/app/home/home.component.html
   create src/main/webapp/app/layouts/profiles/page-ribbon.component.ts
   create src/main/webapp/app/layouts/profiles/profile.service.ts
   create src/main/webapp/app/layouts/profiles/profile-info.model.ts
   create src/main/webapp/app/layouts/main/main.component.ts
   create src/main/webapp/app/layouts/main/main.component.html
   create src/main/webapp/app/layouts/main/main.module.ts
   create src/main/webapp/app/layouts/navbar/navbar-item.model.d.ts
   create src/main/webapp/app/layouts/navbar/navbar.component.ts
   create src/main/webapp/app/layouts/navbar/navbar.component.html
   create src/main/webapp/app/layouts/footer/footer.component.ts
   create src/main/webapp/app/layouts/footer/footer.component.html
ERROR! ERROR! Error parsing file src/main/webapp/app/layouts/error/error.route.ts: SyntaxError: ',' expected. (9:20)
   7 |     path: 'error',
   8 |     component: ErrorComponent,
>  9 |     title: 'Page d'erreur !',
     |                    ^
  10 |   },
  11 |   {
  12 |     path: 'accessdenied',

At: 1: import { Routes } from '@angular/router';
2: 
3: import ErrorComponent from './error.component';
4: 
5: export const errorRoute: Routes = [
6:   {
7:     path: 'error',
8:     component: ErrorComponent,
9:     title: 'Page d'erreur !',
10:   },
11:   {
12:     path: 'accessdenied',
13:     component: ErrorComponent,
14:     data: {
15:       errorMessage: 'Vous n'avez pas les droits pour accéder à cette page.',
16:     },
17:     title: 'Page d'erreur !',
18:   },
19:   {
20:     path: '404',
21:     component: ErrorComponent,
22:     data: {
23:       errorMessage: 'La page n'existe pas.',
24:     },
25:     title: 'Page d'erreur !',
26:   },
27:   {
28:     path: '**',
29:     redirectTo: '/404',
30:   },
31: ];
32: 
Error: Error parsing file src/main/webapp/app/layouts/error/error.route.ts: SyntaxError: ',' expected. (9:20)
   7 |     path: 'error',
   8 |     component: ErrorComponent,
>  9 |     title: 'Page d'erreur !',
     |                    ^
  10 |   },
  11 |   {
  12 |     path: 'accessdenied',

At: 1: import { Routes } from '@angular/router';
2: 
3: import ErrorComponent from './error.component';
4: 
5: export const errorRoute: Routes = [
6:   {
7:     path: 'error',
8:     component: ErrorComponent,
9:     title: 'Page d'erreur !',
10:   },
11:   {
12:     path: 'accessdenied',
13:     component: ErrorComponent,
14:     data: {
15:       errorMessage: 'Vous n'avez pas les droits pour accéder à cette page.',
16:     },
17:     title: 'Page d'erreur !',
18:   },
19:   {
20:     path: '404',
21:     component: ErrorComponent,
22:     data: {
23:       errorMessage: 'La page n'existe pas.',
24:     },
25:     title: 'Page d'erreur !',
26:   },
27:   {
28:     path: '**',
29:     redirectTo: '/404',
30:   },
31: ];
32: 
    at file://<redacted>/.npm-global/lib/node_modules/generator-jhipster/dist/generators/bootstrap/support/prettier-support.mjs:78:19
    at async Object.<anonymous> (file:///home/bousse-e/.npm-global/lib/node_modules/generator-jhipster/node_modules/p-transform/dist/index.js:13:5)
    at async file://<redacted>/.npm-global/lib/node_modules/generator-jhipster/node_modules/p-transform/dist/queue.js:68:28
    at async file://<redacted>/.npm-global/lib/node_modules/generator-jhipster/node_modules/p-queue/dist/index.js:118:36
```

**Comment by mshima** [comment]
Fixed in main https://github.com/jhipster/generator-jhipster/pull/23008
