### ISSUE TITLE
JHipster errors when run after clean installation

### ISSUE THREAD

**Issue by xbotuk** [jhipster/generator-jhipster#20622]
##### **Overview of the issue**

JHipster errors when run after clean installation. LTS versions of Node v18.12.1 NPM 8.19.2 used.

##### **Motivation for or Use Case**

Unable to run JHipster

##### **Reproduce the error**

Commands as below

C:\Users\User\t>node --version
v18.12.1

C:\Users\User\t>npm --version
8.19.2

C:\Users\User\t>jhipster -V
INFO! Using bundled JHipster
node:internal/modules/cjs/loader:535
      throw e;
      ^

Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './lib/util/namespace' is not defined by "exports" in E:\Programs\RT\node\lts\node_modules\generator-jhipster\node_modules\yeoman-environment\package.json
    at new NodeError (node:internal/errors:393:5)
    at throwExportsNotFound (node:internal/modules/esm/resolve:358:9)
    at packageExportsResolve (node:internal/modules/esm/resolve:668:3)
    at resolveExports (node:internal/modules/cjs/loader:529:36)
    at Module._findPath (node:internal/modules/cjs/loader:569:31)
    at Module._resolveFilename (node:internal/modules/cjs/loader:981:27)
    at Module._load (node:internal/modules/cjs/loader:841:27)
    at Module.require (node:internal/modules/cjs/loader:1061:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (E:\Programs\RT\node\lts\node_modules\generator-jhipster\utils\blueprint.js:19:25) {
  code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
}

Node.js v18.12.1

##### **JHipster Version(s)**

Latest version 7.9.3

**Comment by mraible** [comment]
Please use Node 16 to solve this issue.On Dec 17, 2022, at 05:06, xbotuk ***@***.***> wrote:﻿

Overview of the issue
JHipster errors when run after clean installation. LTS versions of Node v18.12.1 NPM 8.19.2 used.
Motivation for or Use Case
Unable to run JHipster
Reproduce the error
Commands as below
C:\Users\User\t>node --version
v18.12.1
C:\Users\User\t>npm --version
8.19.2
C:\Users\User\t>jhipster -V
INFO! Using bundled JHipster
node:internal/modules/cjs/loader:535
throw e;
^
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './lib/util/namespace' is not defined by "exports" in E:\Programs\RT\node\lts\node_modules\generator-jhipster\node_modules\yeoman-environment\package.json
at new NodeError (node:internal/errors:393:5)
at throwExportsNotFound (node:internal/modules/esm/resolve:358:9)
at packageExportsResolve (node:internal/modules/esm/resolve:668:3)
at resolveExports (node:internal/modules/cjs/loader:529:36)
at Module._findPath (node:internal/modules/cjs/loader:569:31)
at Module._resolveFilename (node:internal/modules/cjs/loader:981:27)
at Module._load (node:internal/modules/cjs/loader:841:27)
at Module.require (node:internal/modules/cjs/loader:1061:19)
at require (node:internal/modules/cjs/helpers:103:18)
at Object. (E:\Programs\RT\node\lts\node_modules\generator-jhipster\utils\blueprint.js:19:25) {
code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
}
Node.js v18.12.1
JHipster Version(s)
Latest version 7.9.3
