### ISSUE TITLE
PostgreSQL : problem for running in 2.22.0 ?

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/generator-jhipster#2102]
Hello, trying to run a sample project with postgresql, since the release 2.22.0

Project : dev:h2 + prod:postgresql
* start in dev profile => OK (with H2)
* start in prod profile => KO
```
[INFO] com.mycompany.myapp.config.MetricsConfiguration - Initializing Metrics JMX reporting
[ERROR] com.zaxxer.hikari.util.PropertyElf - Exception setting property url on target class org.postgresql.ds.PGSimpleDataSource
java.lang.reflect.InvocationTargetException: null
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_60]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_60]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_60]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_60]
	at com.zaxxer.hikari.util.PropertyElf.setProperty(PropertyElf.java:158) [HikariCP-2.4.1.jar:na]
	at com.zaxxer.hikari.util.PropertyElf.setTargetFromProperties(PropertyElf.java:64) [HikariCP-2.4.1.jar:na]
	at com.zaxxer.hikari.pool.PoolElf.initializeDataSource(PoolElf.java:154) [HikariCP-2.4.1.jar:na]
	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:113) [HikariCP-2.4.1.jar:na]
	at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:73) [HikariCP-2.4.1.jar:na]
	at com.mycompany.myapp.config.DatabaseConfiguration.dataSource(DatabaseConfiguration.java:77) [classes/:na]
	at com.mycompany.myapp.config.DatabaseConfiguration$$EnhancerBySpringCGLIB$$521eed26.CGLIB$dataSource$1(<generated>) [spring-core-4.1.7.RELEASE.jar:na]
```

Project : dev:postgresql + prod:postgresql
* start in dev profile => KO
* start in prod profile => KO

```
[ERROR] org.springframework.boot.context.embedded.tomcat.TomcatStarter - Error starting Tomcat context: org.springframework.beans.factory.BeanCreationException
[WARN] org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext - Exception encountered during context initialization - cancelling refresh attempt
org.springframework.context.ApplicationContextException: Unable to start embedded container; nested exception is org.springframework.boot.context.embedded.EmbeddedServletContainerException: Unable to start embedded Tomcat
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.onRefresh(EmbeddedWebApplicationContext.java:133) [spring-boot-1.2.6.RELEASE.jar:1.2.6.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:474) ~[spring-context-4.1.7.RELEASE.jar:4.1.7.RELEASE]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:118) [spring-boot-1.2.6.RELEASE.jar:1.2.6.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:687) [spring-boot-1.2.6.RELEASE.jar:1.2.6.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:321) [spring-boot-1.2.6.RELEASE.jar:1.2.6.RELEASE]
	at com.mycompany.myapp.Application.main(Application.java:76) [classes/:na]
Caused by: org.springframework.boot.context.embedded.EmbeddedServletContainerException: Unable to start embedded Tomcat
	at org.springframework.boot.context.embedded.tomcat.TomcatEmbeddedServletContainer.initialize(TomcatEmbeddedServletContainer.java:98) ~[spring-boot-1.2.6.RELEASE.jar:1.2.6.RELEASE]
	at org.springframework.boot.context.embedded.tomcat.TomcatEmbeddedServletContainer.<init>(TomcatEmbeddedServletContainer.java:75) ~[spring-boot-1.2.6.RELEASE.jar:1.2.6.RELEASE]
	at org.springframework.boot.context.embedded.tomcat.TomcatEmbeddedServletContainerFactory.getTomcatEmbeddedServletContainer(TomcatEmbeddedServletContainerFactory.java:378) ~[spring-boot-1.2.6.RELEASE.jar:1.2.6.RELEASE]
	at org.springframework.boot.context.embedded.tomcat.TomcatEmbeddedServletContainerFactory.getEmbeddedServletContainer(TomcatEmbeddedServletContainerFactory.java:155) ~[spring-boot-1.2.6.RELEASE.jar:1.2.6.RELEASE]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.createEmbeddedServletContainer(EmbeddedWebApplicationContext.java:157) [spring-boot-1.2.6.RELEASE.jar:1.2.6.RELEASE]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.onRefresh(EmbeddedWebApplicationContext.java:130) [spring-boot-1.2.6.RELEASE.jar:1.2.6.RELEASE]
	... 5 common frames omitted
```

I don't understand why the error is different...
The only solution I actually found is to use in application-dev.yml or application-prod.yml the configuration :
```
url: jdbc:postgresql://localhost:5432/<%=baseName%>
```

Is it correct ?
Why PostgreSQL doesn't use an url like MySQL ?

**Comment by jdubois** [comment]
This is because there was an error parsing the Postgresql URL with the driver -> I did this at the very beginning of JHipster, this might not be correct anymore. I also had the same issue with Heroku (the URL parser of the driver was buggy and threw some NPE when parsing the Heroku URL), so I had to recode the parser.

So to have this working currently, you need to use the jhipster.datasource.serverName property, which stores your database server name, and not use the URL -> this is what is generated by default, pointing to localhost

So we have several things here:

- Can you check it works with the default config, using  jhipster.datasource.serverName ?
- If you have it working with the URL, maybe all this doesn't have sense anymore -> can you confirm it works with just the URL? If yes, can you help migrate to use the URL?

**Comment by pascalgrimaud** [comment]
Sure. I'll have a look!

**Comment by pascalgrimaud** [comment]
http://docs.spring.io/spring-boot/docs/current-SNAPSHOT/reference/htmlsingle/#boot-features-embedded-database-support
> You don’t need to provide any connection URLs, simply include a build dependency to the embedded database that you want to use.

**Project : dev:h2 + prod:postgresql**

In production profile, although the url is empty in application-prod.yml
In DatabaseConfiguration.java, I have :
`dataSourceProperties.getUrl() = jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE`
What is "testdb" ? Default value ?
That's why databaseName and serverName can't be initialized !

**Project : dev:postgresql + prod:postgresql**

h2database with scope=test
In DatabaseConfiguration.java, when calling dataSourceProperties.getUrl() => error, not NPE

**My answers :**
1) it doesn't work with default config
2) there are 2 solutions :
* made test on serverName instead of dataSourceProperties.getUrl() in DatabaseConfiguration class
* use url: jdbc:postgresql://localhost:5432/<%=baseName%>
On my machine, just made a few tests, it seems to work well => but I had to confirm that. I will need more tests. Try to do it this WE.

Honestly, I prefer the 2nd solution, but how can I be sure the driver is correct today ? Did it change since the beginning of JHipster ?

**Comment by jdubois** [comment]
Thanks @pascalgrimaud -> yes the driver has been upgraded several times, I coded this 2 years ago! And it looks like it's now working with Heroku, so the parser must have been corrected.

-> yes if you can test with the URL, let's do it that way, like the other databases. That means we will have to update the Datasource configuration, as well as the YAML config (to remove the current JHipster specific property)
