### ISSUE TITLE
Command jhipster error in Windows starting from yeoman-environment 3.14.0 

### ISSUE THREAD

**Issue by kaidohallik** [jhipster/generator-jhipster#21165]
##### **Overview of the issue**

After linking current `main` branch of `generator-jhipster` and running `jhipster` in Windows Command Prompt error occurs:

```
c:\projektid\test\jhipster-test>jhipster
INFO! Using bundled JHipster
ERROR! Only URLs with a scheme in: file, data are supported by the default ESM loader. On Windows, absolute paths must be valid file:// URLs. Received protocol 'c:'
Error [ERR_UNSUPPORTED_ESM_URL_SCHEME]: Only URLs with a scheme in: file, data are supported by the default ESM loader. On Windows, absolute paths must be valid file:// URLs. Received protocol 'c:'
    at new NodeError (node:internal/errors:393:5)
    at throwIfUnsupportedURLScheme (node:internal/modules/esm/resolve:1026:11)
    at defaultResolve (node:internal/modules/esm/resolve:1106:3)
    at nextResolve (node:internal/modules/esm/loader:163:28)
    at ESMLoader.resolve (node:internal/modules/esm/loader:841:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:424:18)
    at ESMLoader.import (node:internal/modules/esm/loader:525:22)
    at importModuleDynamically (node:internal/modules/cjs/loader:1098:29)
    at importModuleDynamicallyWrapper (node:internal/vm/module:438:21)
    at importModuleDynamically (node:vm:389:46)
    at importModuleDynamicallyCallback (node:internal/process/esm_loader:35:14)
    at Object.importModule (C:\projektid\teegid\generator-jhipster\node_modules\yeoman-environment\lib\environment.js:568:50)
    at addCommandRootGeneratorOptions (file:///C:/projektid/teegid/generator-jhipster/dist/cli/program.mjs:87:49)
    at JHipsterCommand._lazyBuildCommandCallBack (file:///C:/projektid/teegid/generator-jhipster/dist/cli/program.mjs:186:23)
    at JHipsterCommand._parseCommand (file:///C:/projektid/teegid/generator-jhipster/dist/cli/jhipster-command.mjs:75:24)
    at C:\projektid\teegid\generator-jhipster\node_modules\commander\lib\command.js:1081:27 {
  code: 'ERR_UNSUPPORTED_ESM_URL_SCHEME'
}
```

##### **Motivation for or Use Case**

Command `jhipster` doesn't run in Windows Command Prompt.

##### **Reproduce the error**

Clone generator-jhipster and `npm link` in generator folder.

Create folder somewhere, run `npm link generator-jhipster` there and then run `jhipster`.

##### **Related issues**

Regression from https://github.com/jhipster/generator-jhipster/pull/21077 where yeoman-environment was updated from 3.13.0 to 3.14.1

Related PR in yeoman-environtment: https://github.com/yeoman/environment/pull/454

##### **Suggest a Fix**

Seems that `meta.resolved` in https://github.com/yeoman/environment/pull/454/files#diff-24984142d58a41889c987b60103bcd93653f3551f71f6cdf22b5762e885c9cd6R566 is in wrong format in Windows and needs to be converted.

##### **JHipster Version(s)**

Using latest main branch.

If using first commit before yeoman-environment update https://github.com/jhipster/generator-jhipster/commit/6dd66281f146198428a05e25a30d28da1194c529 then jhipster runs without errors.

##### **Browsers and Operating System**

Windows.

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by DanielFran** [comment]
@mshima Can you take a look please?

**Comment by mshima** [comment]
Should b e fixed in main.

**Comment by kaidohallik** [comment]
I confirm this is fixed in main. Thanks!
