### ISSUE TITLE
Blueprint generator exits with error

### ISSUE THREAD

**Issue by glewe** [jhipster/generator-jhipster#21274]
##### **Overview of the issue**

When I run a fresh `jhipster generate-blueprint` with default values (named it 'lsy-blueprint') it exists with the following error for each selected sub-generator:

```
  1) SubGenerator client of lsy-blueprint JHipster blueprint
       run
         "before all" hook for "should succeed":
     Error: Some blueprints were not found jhipster-lsy-blueprint, you should install them manually
      at JHipsterClientGenerator.error (node_modules\generator-jhipster\generators\generator-base.js:1937:11)
      at JHipsterClientGenerator._configureBlueprints (node_modules\generator-jhipster\generators\generator-base-blueprint.js:498:14)
      at JHipsterClientGenerator.composeWithBlueprints (node_modules\generator-jhipster\generators\generator-base-blueprint.js:428:12)
      at JHipsterClientGenerator._postConstruct (node_modules\generator-jhipster\generators\client\index.js:95:18)
      at Environment.instantiate (node_modules\generator-jhipster\node_modules\yeoman-environment\lib\environment.js:819:40)
      at Environment.create (node_modules\generator-jhipster\node_modules\yeoman-environment\lib\environment.js:778:17)
      at RunContext.build (node_modules\yeoman-test\lib\run-context.js:142:14)
      at RunContext.run (node_modules\yeoman-test\lib\run-context.js:210:10)
      at Context.<anonymous> (file:///d:/Lsy/cGroup/lsy-blueprint/generators/client/generator.spec.mjs:20:10)
      at processImmediate (node:internal/timers:466:21)
```

##### **Motivation for or Use Case**

The generation of a plain core blueprint should run through with no errors.

##### **Reproduce the error**

Run `jhipster generate-blueprint`

##### **Related issues**

None found

##### **Suggest a Fix**

n/a

##### **JHipster Version(s)**

7.9.3

##### **JHipster configuration**

Default

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

n/a

##### **Browsers and Operating System**

Windows 11

- [x] Checking this box is mandatory (this is just to show you read everything)

Best regards,
George

**Comment by mshima** [comment]
Lot's has changed at generate-blueprint.
I am closing the issue because I could not reproduce.
If the problem persist, please post the blueprint's `.yo-rc.json` file.
