### ISSUE TITLE
Error: Cannot find module 'infinity-agent'

### ISSUE THREAD

**Issue by TusharPandya** [jhipster/generator-jhipster#2138]
When I tried to follow instruction given on http://yeoman.io/codelab/setup.html and confirm installation using command "yo --version && bower --version && grunt --version" it gives me :
module.js:339
    throw err;
    ^

Error: Cannot find module 'infinity-agent'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/yo/node_modules/packagejson/node_modules/got/index.js:9:21)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)

**Comment by deepu105** [comment]
I guess u opened issue in wrong forum
