### ISSUE TITLE
Upgrade Keycloak dependency and realm configurations to v21.x

### ISSUE THREAD

**Issue by vishal423** [jhipster/generator-jhipster#21819]
##### **Overview of the feature request**

Upgrade Keycloak dependency, realm configurations to support v21.x

##### **Related issues or PR**

- [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by mraible** [comment]
@vishal423 I've had success using `npm link` and `jhipster jdl default --skip-jhipster-dependencies`. If that doesn't work, please let me know what error(s) you're seeing.

**Comment by vishal423** [comment]
I tried below steps:
- Executed `npm link` in the `JHipster` checkout directory.
- Created new directory and executed `npm link 'generator-jhipster'` to link with JHipster code
- `jhipster jdl default --skip-jhipster-dependencies` throws following error:
```
➜  jhipster jdl default --skip-jhipster-dependencies
WARNING! Since JHipster v8, the jhipster command will not use the locally installed generator-jhipster.
    If you want to execute the locally installed generator-jhipster, run: npx jhipster
ERROR! ERROR! Named export 'isReservedTableName' not found. The requested module '../../../jdl/jhipster/reserved-keywords.js' is a CommonJS module, which may not support a
ll module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from '../../../jdl/jhipster/reserved-keywords.js';                                                                                                              const { isReservedTableName } = pkg;

file:///Users/vishal/oss/jhipster/dist/generators/server/support/prepare-entity.mjs:21
import { isReservedTableName } from '../../../jdl/jhipster/reserved-keywords.js';
         ^^^^^^^^^^^^^^^^^^^
SyntaxError: Named export 'isReservedTableName' not found. The requested module '../../../jdl/jhipster/reserved-keywords.js' is a CommonJS module, which may not support al
l module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from '../../../jdl/jhipster/reserved-keywords.js';
const { isReservedTableName } = pkg;

    at ModuleJob._instantiate (node:internal/modules/esm/module_job:123:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:189:5)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:533:24)
    at async importModuleDynamicallyWrapper (node:internal/vm/module:438:15)
    at async addCommandRootGeneratorOptions (file:///Users/vishal/oss/jhipster/dist/cli/program.mjs:87:29)
    at async JHipsterCommand._lazyBuildCommandCallBack (file:///Users/vishal/oss/jhipster/dist/cli/program.mjs:184:17)
    at async JHipsterCommand._parseCommand (file:///Users/vishal/oss/jhipster/dist/cli/jhipster-command.mjs:75:13)
    at async JHipsterCommand.parseAsync (/Users/vishal/oss/jhipster/node_modules/commander/lib/command.js:935:5)                                                      
```
- And `npx jhipster jdl default --skip-jhipster-dependencies` throws the following error:
```
➜  npx jhipster jdl default --skip-jhipster-dependencies
WARNING! Since JHipster v8, the jhipster command will not use the locally installed generator-jhipster.
    If you want to execute the locally installed generator-jhipster, run: npx jhipster
ERROR! ERROR! Named export 'isReservedTableName' not found. The requested module '../../../jdl/jhipster/reserved-keywords.js' is a CommonJS module, which may not support a
ll module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from '../../../jdl/jhipster/reserved-keywords.js';
const { isReservedTableName } = pkg;

file:///Users/vishal/oss/jhipster/dist/generators/server/support/prepare-entity.mjs:21
import { isReservedTableName } from '../../../jdl/jhipster/reserved-keywords.js';
         ^^^^^^^^^^^^^^^^^^^
SyntaxError: Named export 'isReservedTableName' not found. The requested module '../../../jdl/jhipster/reserved-keywords.js' is a CommonJS module, which may not support al
l module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from '../../../jdl/jhipster/reserved-keywords.js';
const { isReservedTableName } = pkg;

    at ModuleJob._instantiate (node:internal/modules/esm/module_job:123:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:189:5)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:533:24)
    at async importModuleDynamicallyWrapper (node:internal/vm/module:438:15)
    at async addCommandRootGeneratorOptions (file:///Users/vishal/oss/jhipster/dist/cli/program.mjs:87:29)
    at async JHipsterCommand._lazyBuildCommandCallBack (file:///Users/vishal/oss/jhipster/dist/cli/program.mjs:184:17)
    at async JHipsterCommand._parseCommand (file:///Users/vishal/oss/jhipster/dist/cli/jhipster-command.mjs:75:13)
    at async JHipsterCommand.parseAsync (/Users/vishal/oss/jhipster/node_modules/commander/lib/command.js:935:5)                                                    
```

**Comment by BrayanMnz** [comment]
Hi @mraible @vishal423 just looking for an initial kick for this one, 
What are we expecting here  **_realm configurations to support v21.x_** ?

**Comment by vishal423** [comment]
@BrayanMnz, you can refer previous upgrades like this one https://github.com/jhipster/generator-jhipster/pull/20395

**Comment by vishal423** [comment]
@BrayanMnz , there is no explicit documentation to capture realm upgrade. You can follow the steps as laid in old issues like this [step # 2](https://github.com/jhipster/generator-jhipster/issues/20147) to do the upgrade, identify diff and apply back to realm template.

**Comment by BrayanMnz** [comment]
May you check the PR ? @vishal423 
https://github.com/jhipster/generator-jhipster/pull/21948
