### ISSUE TITLE
Administration menu doesn't work when creating micro frontends example with React

### ISSUE THREAD

**Issue by mraible** [jhipster/generator-jhipster#21990]
##### **Overview of the issue**

I tried re-creating my micro frontends example ([demo script](https://github.com/oktadev/auth0-micro-frontends-jhipster-example/blob/main/demo.adoc)) using a JDL that's [modified for v8](https://github.com/jhipster/jdl-samples/pull/52). 

I'm doing this because I want to use v8 (or the `main` branch) for my talk next week at Devoxx UK.

Here's the JDL:

```
application {
  config {
    baseName gateway
    reactive true
    packageName com.okta.developer.gateway
    applicationType gateway
    authenticationType oauth2
    buildTool gradle
    clientFramework react
    prodDatabaseType postgresql
    serviceDiscoveryType consul
    testFrameworks [cypress]
    microfrontends [blog, store]
  }
}

application {
  config {
    baseName blog
    reactive true
    packageName com.okta.developer.blog
    applicationType microservice
    authenticationType oauth2
    buildTool gradle
    clientFramework react
    databaseType neo4j
    enableHibernateCache false
    serverPort 8081
    serviceDiscoveryType consul
    testFrameworks [cypress]
  }
  entities Blog, Post, Tag
}

application {
  config {
    baseName store
    reactive true
    packageName com.okta.developer.store
    applicationType microservice
    authenticationType oauth2
    buildTool gradle
    clientFramework react
    databaseType mongodb
    enableHibernateCache false
    serverPort 8082
    serviceDiscoveryType consul
    testFrameworks [cypress]
  }
  entities Product
}

entity Blog {
  name String required minlength(3)
  handle String required minlength(2)
}

entity Post {
  title String required
  content TextBlob required
  date Instant required
}

entity Tag {
  name String required minlength(2)
}

entity Product {
  title String required
  price BigDecimal required min(0)
  image ImageBlob
}

relationship ManyToOne {
  Blog{user(login)} to User with builtInEntity
  Post{blog(name)} to Blog
}

relationship ManyToMany {
  Post{tag(name)} to Tag{post}
}

paginate Post, Tag with infinite-scroll
paginate Product with pagination

deployment {
  deploymentType docker-compose
  serviceDiscoveryType consul
  appsFolders [gateway, blog, store]
  dockerRepositoryName "mraible"
}

deployment {
  deploymentType kubernetes
  appsFolders [gateway, blog, store]
  clusteredDbApps [store]
  kubernetesNamespace demo
  kubernetesUseDynamicStorage true
  kubernetesStorageClassName ""
  serviceDiscoveryType consul
  dockerRepositoryName "mraible"
}
```

After building Docker containers for everything and starting with Docker Compose, I noticed the Admin menu in the gateway doesn't work.

- Admin > Gateway results in the error below.
- Admin API > Product API shows, but not blog. See 2nd screenshot below.
- The other menu items render a template, but no data.

<img width="1241" alt="Screenshot 2023-05-02 at 2 22 28 PM" src="https://user-images.githubusercontent.com/17892/235779261-9c5ef0cb-b7e9-4f5b-b5a8-207761b0a79f.png">

<img width="1241" alt="Screenshot 2023-05-02 at 2 26 44 PM" src="https://user-images.githubusercontent.com/17892/235779644-63afa709-43fd-4513-b994-931ebe7d1ea0.png">

##### **Motivation for or Use Case**

I'm pretty sure this worked with 7.9.3, but I could be wrong. 

##### **Reproduce the error**

Follow the steps in https://github.com/oktadev/auth0-micro-frontends-jhipster-example/blob/main/demo.adoc, but use v8.

##### **JHipster Version(s)**

`main` branch as of May 2, 2023

**Comment by mraible** [comment]
This issue doesn't happen when running `./gradlew`. If I run `./gradlew -Pprod`, it fails to build:

```
...
> gateway@0.0.1-SNAPSHOT webapp:build:prod
> webpack --config webpack/webpack.prod.js --progress=profile

<s> [webpack.Progress] 0%

<s> [webpack.Progress] 1% setup before run
<s> [webpack.Progress] 1% setup before run NodeEnvironmentPlugin
<s> [webpack.Progress] 1% setup before run
<s> [webpack.Progress] 2% setup run
<s> [webpack.Progress] 2% setup run webpack-cli
<s> [webpack.Progress] 2% setup run ESLintWebpackPlugin_1
<s> [webpack.Progress] 2% setup run ForkTsCheckerWebpackPlugin
<s> [webpack.Progress] 2% setup run
<s> [webpack.Progress] 4% setup normal module factory
<s> [webpack.Progress] 4% setup normal module factory
<s> [webpack.Progress] 5% setup context module factory
<s> [webpack.Progress] 5% setup context module factory
<s> [webpack.Progress] 6% setup before compile
<s> [webpack.Progress] 6% setup before compile ProgressPlugin
<s> [webpack.Progress] 6% setup before compile
<s> [webpack.Progress] 7% setup compile
<s> [webpack.Progress] 7% setup compile ExternalsPlugin
<s> [webpack.Progress] 7% setup compile ExternalsPlugin
<s> [webpack.Progress] 7% setup compile
<s> [webpack.Progress] 8% setup compilation
<s> [webpack.Progress] 8% setup compilation CopyPlugin
<s> [webpack.Progress] 8% setup compilation MergeJsonWebpackPlugin
<s> [webpack.Progress] 8% setup compilation mini-css-extract-plugin
<s> [webpack.Progress] 8% setup compilation GenerateSW
<s> [webpack.Progress] 8% setup compilation ArrayPushCallbackChunkFormatPlugin
<s> [webpack.Progress] 8% setup compilation JsonpChunkLoadingPlugin
<s> [webpack.Progress] 8% setup compilation StartupChunkDependenciesPlugin
<s> [webpack.Progress] 8% setup compilation ImportScriptsChunkLoadingPlugin
<s> [webpack.Progress] 8% setup compilation FetchCompileWasmPlugin
<s> [webpack.Progress] 8% setup compilation FetchCompileAsyncWasmPlugin
<s> [webpack.Progress] 8% setup compilation AssignLibraryPlugin
<s> [webpack.Progress] 8% setup compilation WorkerPlugin
<s> [webpack.Progress] 8% setup compilation SplitChunksPlugin
<s> [webpack.Progress] 8% setup compilation ResolverCachePlugin
<s> [webpack.Progress] 8% setup compilation ConsumeSharedPlugin
<s> [webpack.Progress] 8% setup compilation HtmlWebpackPlugin
<s> [webpack.Progress] 8% setup compilation
<s> [webpack.Progress] 9% setup compilation
<s> [webpack.Progress] 9% setup compilation ProgressPlugin
<s> [webpack.Progress] 9% setup compilation DefinePlugin
<s> [webpack.Progress] 9% setup compilation DefinePlugin
<s> [webpack.Progress] 9% setup compilation ForkTsCheckerWebpackPlugin
<s> [webpack.Progress] 9% setup compilation mini-css-extract-plugin
<s> [webpack.Progress] 9% setup compilation LoaderOptionsPlugin
/Users/mraible/Downloads/mfr/gateway/node_modules/webpack/lib/NormalModule.js:230
                        throw new TypeError(
                              ^

TypeError: The 'compilation' argument must be an instance of Compilation
    at Function.getCompilationHooks (/Users/mraible/Downloads/mfr/gateway/node_modules/webpack/lib/NormalModule.js:230:10)
    at /Users/mraible/Downloads/mfr/gateway/node_modules/webpack/lib/LoaderOptionsPlugin.js:56:17
    at _next1 (eval at create (/Users/mraible/Downloads/mfr/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:207:1)
    at Hook.eval [as call] (eval at create (/Users/mraible/Downloads/mfr/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:290:1)
    at Hook.CALL_DELEGATE [as _call] (/Users/mraible/Downloads/mfr/node_modules/tapable/lib/Hook.js:14:14)
    at Compiler.newCompilation (/Users/mraible/Downloads/mfr/node_modules/webpack/lib/Compiler.js:1125:26)
    at /Users/mraible/Downloads/mfr/node_modules/webpack/lib/Compiler.js:1169:29
    at Hook.eval [as callAsync] (eval at create (/Users/mraible/Downloads/mfr/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:22:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/Users/mraible/Downloads/mfr/node_modules/tapable/lib/Hook.js:18:14)
    at Compiler.compile (/Users/mraible/Downloads/mfr/node_modules/webpack/lib/Compiler.js:1164:28)
npm ERR! Lifecycle script `webapp:build:prod` failed with error:
npm ERR! Error: command failed
npm ERR!   in workspace: gateway@0.0.1-SNAPSHOT
npm ERR!   at location: /Users/mraible/Downloads/mfr/gateway
npm ERR! Lifecycle script `webapp:prod` failed with error:
npm ERR! Error: command failed
npm ERR!   in workspace: gateway@0.0.1-SNAPSHOT
npm ERR!   at location: /Users/mraible/Downloads/mfr/gateway
Error: write EPIPE
    at process.target._send (node:internal/child_process:867:20)
    at process.target.send (node:internal/child_process:740:19)
    at /Users/mraible/Downloads/mfr/node_modules/fork-ts-checker-webpack-plugin/lib/rpc/expose-rpc.js:27:31
    at new Promise (<anonymous>)
    at sendMessage (/Users/mraible/Downloads/mfr/node_modules/fork-ts-checker-webpack-plugin/lib/rpc/expose-rpc.js:19:38)
    at /Users/mraible/Downloads/mfr/node_modules/fork-ts-checker-webpack-plugin/lib/rpc/expose-rpc.js:60:27
    at Generator.next (<anonymous>)
    at fulfilled (/Users/mraible/Downloads/mfr/node_modules/fork-ts-checker-webpack-plugin/lib/rpc/expose-rpc.js:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  errno: -32,
  code: 'EPIPE',
  syscall: 'write'
}
Error: write EPIPE
    at process.target._send (node:internal/child_process:867:20)
    at process.target.send (node:internal/child_process:740:19)
    at /Users/mraible/Downloads/mfr/node_modules/fork-ts-checker-webpack-plugin/lib/rpc/expose-rpc.js:27:31
    at new Promise (<anonymous>)
    at sendMessage (/Users/mraible/Downloads/mfr/node_modules/fork-ts-checker-webpack-plugin/lib/rpc/expose-rpc.js:19:38)
    at /Users/mraible/Downloads/mfr/node_modules/fork-ts-checker-webpack-plugin/lib/rpc/expose-rpc.js:60:27
    at Generator.next (<anonymous>)
    at fulfilled (/Users/mraible/Downloads/mfr/node_modules/fork-ts-checker-webpack-plugin/lib/rpc/expose-rpc.js:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  errno: -32,
  code: 'EPIPE',
  syscall: 'write'
}

> Task :webapp FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':webapp'.
> Process 'command '/Users/mraible/Downloads/mfr/gateway/.gradle/npm/npm-v9.6.6/bin/npm'' finished with non-zero exit value 1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 7s
7 actionable tasks: 4 executed, 3 up-to-date
```

I'll add a bug bounty to try and get this fixed.

**Comment by mraible** [comment]
I was able to get `./gradlew -Pprod` to work in the gateway app by running `npm install` at the top level, followed by `./gradlew clean` and then `./gradlew -Pprod`. The admin menu works fine in this scenario. It still has issues when running in Docker Compose.

**Comment by mraible** [comment]
If I update `app.yml` from:

```yaml
- SPRING_R2DBC_URL=r2dbc:postgresql://gateway-postgresql:5432/gateway
- SPRING_LIQUIBASE_URL=jdbc:postgresql://gateway-postgresql:5432/gateway
```

to the following:

```yaml
- SPRING_R2DBC_URL=r2dbc:postgresql://postgresql:5432/gateway
- SPRING_LIQUIBASE_URL=jdbc:postgresql://postgresql:5432/gateway
```

And update `postgresql.yml` to have:

```yaml
healthcheck:
  test: ['CMD-SHELL', 'pg_isready -U $${POSTGRES_USER}']
```

It solves the problem. The admin menu also works as expected.

**Comment by mraible** [comment]
@mshima The above issue makes me think there's a bug in `getR2DBCUrl()` and `getJDBCUrl()` that's used by `app.yml`.

**Comment by mraible** [comment]
Today, I started getting a new error when trying to build:

```
ERROR in resolving fallback for shared module reactstrap
Module not found: Error: Can't resolve 'reactstrap' in '/Users/mraible/Downloads/mfr/node_modules/react-jhipster/lib/component/metrics'
```

I'm using the following command to create my project:

```
jhipster jdl reactive-mf-v8.jdl --monorepository --workspaces --skip-jhipster-dependencies
```

Is this a known issue?

**Comment by mraible** [comment]
If I use `--skip-install`, the issue with reactstrap doesn't happen.

**Comment by mshima** [comment]
> If I use `--skip-install`, the issue with reactstrap doesn't happen.

@mraible https://github.com/jhipster/generator-jhipster/pull/22089.

**Comment by mshima** [comment]
> @mshima The above issue makes me think there's a bug in `getR2DBCUrl()` and `getJDBCUrl()` that's used by `app.yml`.

https://github.com/jhipster/generator-jhipster/pull/22090.

**Comment by mraible** [comment]
If I build the gateway Docker image and run it with `app.yml`, the administration menu works as expected.

```
docker compose -f src/main/docker/app.yml up
```

However, if I run things from the `docker-compose` directory, the menu fails to render in the gateway. This seems pretty strange since it's the same Docker image.

**Comment by mshima** [comment]
Have you restarted the entire stack when switching to the docker-compose?
Services have different configurations.

**Comment by mraible** [comment]
@mshima I tried again this morning and had no Docker images running before I ran `docker compose up`. The issue still exists.

**Comment by mshima** [comment]
Have you tested against 7.9.3? Just curiosity if it’s a regression.
If the store app is stopped the admin menu works. Webpack defaults to load libs from store instead of the gateway.
I don’t know how to change this behavior (other than lazy load store app) and why react is behaving like that.

**Comment by mraible** [comment]
> Have you tested against 7.9.3? Just curiosity if it’s a regression.

@mshima I checked. This issue exists with JHipster v7.9.3 as well. If I stop the store, everything works, as you mentioned.
