### ISSUE TITLE
SecurityUtils getCurrentUser throws exception (properly filed)

### ISSUE THREAD

**Issue by amitjindal** [jhipster/generator-jhipster#2216]
Calling SecurityUtils.getCurrentUser() throws exception. This was called after login.

**Stack trace (Truncated as it seems useless after a few lines):**
```
[ERROR] com.none.aop.logging.LoggingAspect - Exception in com.none.web.rest.HelloResource.getAllHellos() with cause = null
java.lang.IllegalStateException: User not found!
	at com.none.security.SecurityUtils.getCurrentUser(SecurityUtils.java:79) ~[classes/:na]
	at com.none.web.rest.HelloResource.getAllHellos(HelloResource.java:104) ~[classes/:na]
	at com.none.web.rest.HelloResource$$FastClassBySpringCGLIB$$8f45c3a9.invoke(<generated>) ~[spring-core-4.2.2.RELEASE.jar:na]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204) ~[spring-core-4.2.2.RELEASE.jar:4.2.2.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:717) ~[spring-aop-4.2.2.RELEASE.jar:4.2.2.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157) [spring-aop-4.2.2.RELEASE.jar:4.2.2.RELEASE]
	at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:85) ~[spring-aop-4.2.2.RELEASE.jar:4.2.2.RELEASE]
	at com.none.aop.logging.LoggingAspect.logAround(LoggingAspect.java:51) ~[classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_31]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_31]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_31]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[na:1.8.0_31]
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:621) ~[spring-aop-4.2.2.RELEASE.jar:4.2.2.RELEASE]
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:610) ~[spring-aop-4.2.2.RELEASE.jar:4.2.2.RELEASE]
	at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:68) ~[spring-aop-4.2.2.RELEASE.jar:4.2.2.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) [spring-aop-4.2.2.RELEASE.jar:4.2.2.RELEASE]
	at org.springframework.aop.aspectj.AspectJAfterThrowingAdvice.invoke(AspectJAfterThrowingAdvice.java:58) ~[spring-aop-4.2.2.RELEASE.jar:4.2.2.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) [spring-aop-4.2.2.RELEASE.jar:4.2.2.RELEASE]
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99) ~[spring-tx-4.2.2.RELEASE.jar:4.2.2.RELEASE]
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:281) ~[spring-tx-4.2.2.RELEASE.jar:4.2.2.RELEASE]
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96) ~[spring-tx-4.2.2.RELEASE.jar:4.2.2.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) [spring-aop-4.2.2.RELEASE.jar:4.2.2.RELEASE]
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92) [spring-aop-4.2.2.RELEASE.jar:4.2.2.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) [spring-aop-4.2.2.RELEASE.jar:4.2.2.RELEASE]
```

**Motivation for or Use Case**
I need to get the current user and userid.
This is a bug because it should work

**JHipster Version(s)** 
JHipster version: Latest. Installed 5 minutes ago.    "generator-jhipster": "2.23.0"

**Is it a regression?**
Don't know. Probably not.

**JHipster configuration, a `.yo-rc.json` file generated in the root folder** 
Attached

**Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory** 
Attached at the end.
Also attached is the changed HelloResource. The only change is addition of a line and associated import:
```
import com.none.security.CustomUserDetails;
import com.none.security.SecurityUtils;
....
....
    public ResponseEntity<List<HelloDTO>> getAllHellos(Pageable pageable)
        throws URISyntaxException {
        Page<Hello> page = helloRepository.findAll(pageable);
        CustomUserDetails currentUser = SecurityUtils.getCurrentUser();  // <==== Causes exception
        HttpHeaders headers = PaginationUtil.generatePaginationHttpHeaders(page, "/api/hellos");
        .....
```

**Steps to reproduce:**
1) Create a fresh new jhipster project. Options I chose: SQL, H2db/MySQL, with Elastic Search, No translation
2) Create any entity. I created Hello with one field: name, string, no validation, with DTO, pagination
3) Add the call to getCurrentUser in GET (all entities) in HelloResource
4) Run the application
5) Login
6) Navigate to Entity > hello
7) Error is thrown

**Related issues** 
None known

**Suggest a Fix** 
None known. I tried to understand and found this:

Throwing exception from line 75-76,79 of SecurityUtils: IllegalStateException("User not found!")
I tried to debug this in IntelliJ, and while intellij shows authentication.getPrincipal() is an instance of CustomUserDetails, the instanceof operator fails and even the typecast results in an exception.

I also tried to change the code from:
```
if (authentication.getPrincipal() instanceof CustomUserDetails) {
    return (CustomUserDetails) authentication.getPrincipal();
```
To this:
```
Object principal = authentication.getPrincipal();
if (CustomUserDetails.class.isInstance(principal)) {
    return CustomUserDetails.class.cast(principal);
}
```
Didn't help.

**Attachments:**
Editor here is not allowing.
Gist here: https://gist.github.com/amitjindal/5df8f707b81fec6a9377

**Comment by jdubois** [comment]
Great, thanks! I merged some code related to this recently, there is probably a regression.

**Comment by jdubois** [comment]
I should have seen this earlier: #2291 is a duplicate from this one!!
But as you didn't write you were using OAuth2 I didn't see the link.

So this issue is very well documented here (a lot better than the other, it took me some time to find out what you already found!), but you can find the workaround and discussion on #2291 -> this is why I'm closing this one, as we should only have one ticket open and the other has the workaround

This is a really annoying issue, if you have time to work on this @amitjindal you're welcome!!

**Comment by micheljung** [comment]
Why was this closed? Doesn't seem to be solved.

From what I see, this can be caused by 533a40f which introduced `CustomUserDetails` but the JWT [`TokenProvider` still sets an instance of `User`](https://github.com/jhipster/generator-jhipster/blob/master/generators/server/templates/src/main/java/package/security/jwt/_TokenProvider.java#L80)

**Comment by jdubois** [comment]
It is closed because there is a duplicate, and by the way the duplicate is
also a mess....
We are all doing this for free: the reason why it is closed is that I am
not spending time on something which isn't clearly described.
Please, if you have an issue: open a new ticket and explain clearly the
issue.
