### ISSUE TITLE
[BUG] User Management edit user throws exception while saving email that is already in use.

### ISSUE THREAD

**Issue by priitl** [jhipster/generator-jhipster#2245]
<strong>Overview of the issue</strong>
User Management -> Edit User throws exception while saving email that is already in use. Same problem in Account -> Settings.

<pre>[ERROR] org.apache.catalina.core.ContainerBase.[Tomcat].[localhost].[/].[dispatcherServlet] - Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is org.springframework.dao.DataIntegrityViolationException: could not execute statement; SQL [n/a]; constraint [jhi_user_email_key]; nested exception is org.hibernate.exception.ConstraintViolationException: could not execute statement] with root cause
org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "jhi_user_email_key"
  Detail: Key (email)=(user@localhost) already exists.
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2182) ~[postgresql-9.4-1203-jdbc42.jar:9.4]
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1911) ~[postgresql-9.4-1203-jdbc42.jar:9.4]
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:173) ~[postgresql-9.4-1203-jdbc42.jar:9.4]
	at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:618) ~[postgresql-9.4-1203-jdbc42.jar:9.4]
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeWithFlags(AbstractJdbc2Statement.java:468) ~[postgresql-9.4-1203-jdbc42.jar:9.4]</pre>

<strong>JHipster Version(s)</strong>
Latest: 2.23.0

<strong>Reproduce the error</strong>
Try to save email that is used by another user. For example while logged in as admin, try to update your email to user@localhost in the sample app.

<strong>Suggest a Fix</strong>
Add same email validations to update user and update account endpoints that are used in register account endpoint.
<pre>.map(user -> new ResponseEntity<>("e-mail address already in use", HttpStatus.BAD_REQUEST))</pre>

**Comment by rkohel** [comment]
This issue applies to changing the login to a login that is already in use as well.

**Comment by deepu105** [comment]
@sendilkumarn can you check this?

**Comment by sendilkumarn** [comment]
@deepu105 checked in
