### ISSUE TITLE
Generator version [8.0.0-beta.1](https://www.npmjs.com/package/generator-jhipster/v/8.0.0-beta.1) available

### ISSUE THREAD

**Issue by anothergoodguy** [jhipster/generator-jhipster#22495]
Hi Team, 

Please not that I see the original issue was closed so creating a new one:

I have used the latest beta image on docker hub: `jhipster/jhipster:latest`

and when I try to upgrade my test app this is the set of errors I see:

```
|  ==> jhipster upgrade --skip-install
                           https://www.jhipster.tech
Welcome to JHipster v8.0.0-beta.1

Welcome to the JHipster Upgrade Sub-Generator
This will upgrade your current application codebase to the latest JHipster version
WARNING! No blueprints detected, skipping check of last blueprint version
INFO! Looking for latest generator-jhipster version...8.0.0-beta.1
npm notice
npm notice New major version of npm available! 7.24.2 -> 9.7.1
npm notice Changelog: <https://github.com/npm/cli/releases/tag/v9.7.1>
npm notice Run `npm install -g npm@9.7.1` to update!
npm notice
ERROR! An error occured while running jhipster:upgrade#checkLatestJhipsterVersion

INFO! Looking for latest generator-jhipster version...
WARNING! npm notice
npm notice New major version of npm available! 7.24.2 -> 9.7.1
npm notice Changelog: <https://github.com/npm/cli/releases/tag/v9.7.1>
npm notice Run `npm install -g npm@9.7.1` to update!
npm notice
ERROR! ERROR! Something went wrong fetching the latest generator-jhipster version number...
npm notice
npm notice New major version of npm available! 7.24.2 -> 9.7.1
npm notice Changelog: <https://github.com/npm/cli/releases/tag/v9.7.1>
npm notice Run `npm install -g npm@9.7.1` to update!
npm notice

Error: Something went wrong fetching the latest generator-jhipster version number...
npm notice
npm notice New major version of npm available! 7.24.2 -> 9.7.1
npm notice Changelog: <https://github.com/npm/cli/releases/tag/v9.7.1>
npm notice Run `npm install -g npm@9.7.1` to update!
npm notice

    at UpgradeGenerator._retrieveLatestVersion (file:///home/jhipster/generator-jhipster/dist/generators/upgrade/generator.mjs:213:19)
    at UpgradeGenerator.checkLatestJhipsterVersion (file:///home/jhipster/generator-jhipster/dist/generators/upgrade/generator.mjs:299:44)
    at UpgradeGenerator.executeTask (file:///home/jhipster/generator-jhipster/node_modules/yeoman-generator/dist/actions/lifecycle.js:240:26)
    at env.queueTask.once (file:///home/jhipster/generator-jhipster/node_modules/yeoman-generator/dist/actions/lifecycle.js:214:56)
    at runLoop.add.once (/home/jhipster/generator-jhipster/node_modules/yeoman-environment/lib/environment.js:1441:34)
    at Immediate.<anonymous> (/home/jhipster/generator-jhipster/node_modules/grouped-queue/lib/subqueue.js:48:34)
    at process.processImmediate (node:internal/timers:476:21)   ```

looks like it continues after a manual upgrade of npm with `npm install -g npm@9.7.1` need to check generated code still, will post if I see any issues



    Generator version [8.0.0-beta.1](https://www.npmjs.com/package/generator-jhipster/v/8.0.0-beta.1) available

_Originally posted by @DanielFran in https://github.com/jhipster/generator-jhipster/issues/20849#issuecomment-1586211280_

**Comment by mraible** [comment]
I tried `jhipster upgrade` on my [21-Points Health app](https://github.com/mraible/21-points). It looks like it worked.

<img width="1442" alt="Screenshot 2023-06-11 at 2 20 44 PM" src="https://github.com/jhipster/generator-jhipster/assets/17892/12075928-54c5-4a7a-ba70-b3b851c465be">

However, if I scroll up, there's an error. 

<img width="1442" alt="Screenshot 2023-06-11 at 2 22 16 PM" src="https://github.com/jhipster/generator-jhipster/assets/17892/41583551-78a8-449c-ab15-979068c9d133">

I checked, and no files were modified in my project. I'll add a bug bounty to this since I think it's important to try and make `jhipster upgrade` work.

**Comment by BrayanMnz** [comment]
@mraible @anothergoodguy 
Would you guys mind adding more detailed info? 

node version?
os? 
any additional info, I'll try to replicate it

**Comment by mshima** [comment]
There are a few bugs:
- node 18 is not supported by jhipster v7 and node 16 is not supported by jhipster v8. To upgrade from v7, its needed to run node 16 with `--skip-checks`.
- `--skip-checks` is not working at upgrade generator due to a conflict with base generator options.
- an yeoman-generator/yeoman-environment bug that a task failure is not stopping the queue. So the generation seems to succeed.

**Comment by hide212131** [comment]
Ah, just as I was about to write a comment, I realized that @mshima had already written about this...
It's a shame to waste it, so I'll write it down.

It's quite a forceful approach, but as a result of trial and error, the migration from v7 to v8 was completed without errors. I will write down what I did below.

1. The environment is as follows. Node needs to be v16. JHipster8 (hereafter v8) does not support node v16, so `--skip-checks` is required.
    ```sh
    $ node -v     
    v16.19.1
    $ jhipster -V --skip-checks
    WARNING! Since JHipster v8, the jhipster command will not use the locally installed generator-jhipster.
        If you want to execute the locally installed generator-jhipster, run: npx jhipster
    8.0.0-beta.1
    ```

2. Modify `generators/upgrade/generator.mjs`.
    - During the code generation of v8 in the middle of migration, `--skip-checks` needs to be enabled. For some reason, `--skip-checks` is not inherited by `UpgradeGenerator` (please let me know why), and I have directly modified the source as follows.
    https://github.com/jhipster/generator-jhipster/blob/a28c1cdeb46f6005b7f72fcd20917ac8d66480ad/generators/upgrade/generator.mjs#L195

    - In `_retrieveLatestVersion`, you need to prevent abnormal termination because there is a value in `pkgInfo.stderr` (the cause is still unknown). I commented out the `throw`. 
    https://github.com/jhipster/generator-jhipster/blob/a28c1cdeb46f6005b7f72fcd20917ac8d66480ad/generators/upgrade/generator.mjs#L231

3. Run the v8 jhipster command.
   `jhipster upgrade --skip-checks` 
   Note that it's not v7's `npx jhipster`. This is a different approach from past migrations, but it's necessary this time.

The reason why we need to do this is that in this migration, we need to solve the following problems at the same time.
- The source of migration, v7, requires node v16. [This is because errors occur with v18](https://github.com/jhipster/generator-jhipster/issues/19627).
- The destination of migration, v8, requires node v18 or above. Normally, v16 is not acceptable.

In order to solve this problem effectively, we need to modify the generator, but since v7 has already been released, we cannot modify it. Therefore, we need to modify v8 and run `jhipster upgrade`.

That's all for now.

**Comment by mshima** [comment]
> * node 18 is not supported by jhipster v7 and node 16 is not supported by jhipster v8. To upgrade from v7, it's needed to run node 16 with `--skip-checks`.

I will try to workaround in https://github.com/jhipster/generator-jhipster/issues/19779.

> * `--skip-checks` is not working at upgrade generator due to a conflict with base generator options.

Fixed in https://github.com/jhipster/generator-jhipster/pull/22528.

> * an yeoman-generator/yeoman-environment bug that a task failure is not stopping the queue. So the generation seems to succeed.

Fixed in `yeoman-generator@8.0.0-rc.2`

**Comment by mshima** [comment]
> Ah, just as I was about to write a comment, I realized that @mshima had already written about this... It's a shame to waste it, so I'll write it down.

Indeed that's a detailed explanation 😄

> It's quite a forceful approach, but as a result of trial and error, the migration from v7 to v8 was completed without errors. I will write down what I did below.
> 
> 1. The environment is as follows. Node needs to be v16. JHipster8 (hereafter v8) does not support node v16, so `--skip-checks` is required.
>    ```shell
>    $ node -v     
>    v16.19.1
>    $ jhipster -V --skip-checks
>    WARNING! Since JHipster v8, the jhipster command will not use the locally installed generator-jhipster.
>        If you want to execute the locally installed generator-jhipster, run: npx jhipster
>    8.0.0-beta.1
>    ```

This can be workaround by using package.json's overrides and force a new yeoman-environment.
I will investigate if it's doable at the wip blueprint.

> 2. Modify `generators/upgrade/generator.mjs`.
>    
>    * During the code generation of v8 in the middle of migration, `--skip-checks` needs to be enabled. For some reason, `--skip-checks` is not inherited by `UpgradeGenerator` (~please let me know why~ @mshima has already provided an answer), and I have directly modified the source as follows.
>      https://github.com/jhipster/generator-jhipster/blob/a28c1cdeb46f6005b7f72fcd20917ac8d66480ad/generators/upgrade/generator.mjs#L195
>    * In `_retrieveLatestVersion`, you need to prevent abnormal termination because there is a value in `pkgInfo.stderr` (the cause is still unknown). I commented out the `throw`.
>      https://github.com/jhipster/generator-jhipster/blob/a28c1cdeb46f6005b7f72fcd20917ac8d66480ad/generators/upgrade/generator.mjs#L231

I think it's a transient error like a temporary network error.

> 3. Run the v8 jhipster command.
>    `jhipster upgrade --skip-checks`
>    Note that it's not v7's `npx jhipster`. This is a different approach from past migrations, but it's necessary this time.
> 
> The reason why we need to do this is that in this migration, we need to solve the following problems at the same time.
> 
> * The source of migration, v7, requires node v16. [This is because errors occur with v18](https://github.com/jhipster/generator-jhipster/issues/19627).
> * The destination of migration, v8, requires node v18 or above. Normally, v16 is not acceptable.
> 
> In order to solve this problem effectively, we need to modify the generator, but since v7 has already been released, we cannot modify it. Therefore, we need to modify v8 and run `jhipster upgrade`.
> 
> That's all for now.

**Comment by mshima** [comment]
@DanielFran bounty claimed https://opencollective.com/generator-jhipster/expenses/163433.

**Comment by DanielFran** [comment]
@mshima approved
