### ISSUE TITLE
Generation fails with v8.0.0-beta.1

### ISSUE THREAD

**Issue by CodingSpiderFox** [jhipster/generator-jhipster#22582]
##### **Overview of the issue**

An error message appears during initial application generation:

```
ERROR! An error occured while running jhipster:server#addTestSpringFactory
ERROR! ERROR! Error editing file C:\Users\user\myapplication\src\test\resources\META-INF\spring.factories: Cannot read properties of null (reading 'match') at TypeError: Cannot read properties of null (reading 'match')
    at JHipsterServerGenerator.<anonymous> (file:///C:/ProgramData/nvm/v18.16.0/node_modules/generator-jhipster/dist/generators/base/support/write-files.mjs:29:32)
    at writeCallback (file:///C:/ProgramData/nvm/v18.16.0/node_modules/generator-jhipster/dist/generators/base/generator-base.mjs:411:58)
    at JHipsterServerGenerator.editFile (file:///C:/ProgramData/nvm/v18.16.0/node_modules/generator-jhipster/dist/generators/base/generator-base.mjs:425:16)
    at source.addTestSpringFactory (file:///C:/ProgramData/nvm/v18.16.0/node_modules/generator-jhipster/dist/generators/server/generator.mjs:291:26)
    at JHipsterServerGenerator.addTestSpringFactory (file:///C:/ProgramData/nvm/v18.16.0/node_modules/generator-jhipster/dist/generators/server/generator.mjs:516:28)
    at JHipsterServerGenerator.executeTask (file:///C:/ProgramData/nvm/v18.16.0/node_modules/generator-jhipster/node_modules/yeoman-generator/dist/actions/lifecycle.js:240:26)
    at env.queueTask.once (file:///C:/ProgramData/nvm/v18.16.0/node_modules/generator-jhipster/node_modules/yeoman-generator/dist/actions/lifecycle.js:214:56)
    at runLoop.add.once (C:\ProgramData\nvm\v18.16.0\node_modules\generator-jhipster\node_modules\yeoman-environment\lib\environment.js:1441:34)
    at Immediate._onImmediate (C:\ProgramData\nvm\v18.16.0\node_modules\generator-jhipster\node_modules\grouped-queue\lib\subqueue.js:48:34)
    at process.processImmediate (node:internal/timers:476:21)
Error: Error editing file C:\Users\user\myapplication\src\test\resources\META-INF\spring.factories: Cannot read properties of null (reading 'match') at TypeError: Cannot read properties of null (reading 'match')
    at JHipsterServerGenerator.<anonymous> (file:///C:/ProgramData/nvm/v18.16.0/node_modules/generator-jhipster/dist/generators/base/support/write-files.mjs:29:32)
    at writeCallback (file:///C:/ProgramData/nvm/v18.16.0/node_modules/generator-jhipster/dist/generators/base/generator-base.mjs:411:58)
    at JHipsterServerGenerator.editFile (file:///C:/ProgramData/nvm/v18.16.0/node_modules/generator-jhipster/dist/generators/base/generator-base.mjs:425:16)
    at source.addTestSpringFactory (file:///C:/ProgramData/nvm/v18.16.0/node_modules/generator-jhipster/dist/generators/server/generator.mjs:291:26)
    at JHipsterServerGenerator.addTestSpringFactory (file:///C:/ProgramData/nvm/v18.16.0/node_modules/generator-jhipster/dist/generators/server/generator.mjs:516:28)
    at JHipsterServerGenerator.executeTask (file:///C:/ProgramData/nvm/v18.16.0/node_modules/generator-jhipster/node_modules/yeoman-generator/dist/actions/lifecycle.js:240:26)
    at env.queueTask.once (file:///C:/ProgramData/nvm/v18.16.0/node_modules/generator-jhipster/node_modules/yeoman-generator/dist/actions/lifecycle.js:214:56)
    at runLoop.add.once (C:\ProgramData\nvm\v18.16.0\node_modules\generator-jhipster\node_modules\yeoman-environment\lib\environment.js:1441:34)
    at Immediate._onImmediate (C:\ProgramData\nvm\v18.16.0\node_modules\generator-jhipster\node_modules\grouped-queue\lib\subqueue.js:48:34)
    at process.processImmediate (node:internal/timers:476:21)
    at writeCallback (file:///C:/ProgramData/nvm/v18.16.0/node_modules/generator-jhipster/dist/generators/base/generator-base.mjs:419:27)
    at JHipsterServerGenerator.editFile (file:///C:/ProgramData/nvm/v18.16.0/node_modules/generator-jhipster/dist/generators/base/generator-base.mjs:425:16)
    at source.addTestSpringFactory (file:///C:/ProgramData/nvm/v18.16.0/node_modules/generator-jhipster/dist/generators/server/generator.mjs:291:26)
    at JHipsterServerGenerator.addTestSpringFactory (file:///C:/ProgramData/nvm/v18.16.0/node_modules/generator-jhipster/dist/generators/server/generator.mjs:516:28)
    at JHipsterServerGenerator.executeTask (file:///C:/ProgramData/nvm/v18.16.0/node_modules/generator-jhipster/node_modules/yeoman-generator/dist/actions/lifecycle.js:240:26)
    at env.queueTask.once (file:///C:/ProgramData/nvm/v18.16.0/node_modules/generator-jhipster/node_modules/yeoman-generator/dist/actions/lifecycle.js:214:56)
    at runLoop.add.once (C:\ProgramData\nvm\v18.16.0\node_modules\generator-jhipster\node_modules\yeoman-environment\lib\environment.js:1441:34)
    at Immediate.<anonymous> (C:\ProgramData\nvm\v18.16.0\node_modules\generator-jhipster\node_modules\grouped-queue\lib\subqueue.js:48:34)
    at process.processImmediate (node:internal/timers:476:21)
ERROR! An error occured while running jhipster:spring-cloud-stream#customizeApplicationForKafka
```

##### **Motivation for or Use Case**

Generation should always succeed

##### **Reproduce the error**

Generate in Windows 11 with the following settings

```
? What is the base name of your application? myapplication
? May JHipster anonymously report usage statistics to improve the tool over time? Yes
? Which *type* of application would you like to create? Microservice application
? Do you want to enable *microfrontends*? Yes
WARNING! Java 17, 18 or 19 are not found on your computer. Your Java version is: 1.8.0_372"
OpenJDK Runtime Environment Corretto-8.372.07.1 (build 1.8.0_372-b07)
OpenJDK 64-Bit Server VM Corretto-8.372.07.1 (build 25.372-b07, mixed
? Would you like to enable internationalization support? Yes
? Please choose the native language of the application German
? Please choose additional languages to install English, French
? Do you want to make it reactive with Spring WebFlux? No
? As you are running in a microservice architecture, on which port would like your server to run? It should be unique to
 avoid port conflicts. 8081
? What is your default Java package name? com.mycompany.myapp
? Which service discovery server do you want to use? Consul (recommended)
? Which *type* of authentication would you like to use? OAuth 2.0 / OIDC Authentication (stateful, works with Keycloak
and Okta)
? Which *type* of database would you like to use? MongoDB
? Which cache do you want to use? (Spring cache abstraction) Infinispan (hybrid cache, for multiple nodes)
? Would you like to use Maven or Gradle for building the backend? Maven
? Which other technologies would you like to use? Elasticsearch as search engine, Apache Kafka as asynchronous messages
broker, API first development using OpenAPI-generator
? Besides JUnit and Jest, which testing frameworks would you like to use? Cucumber
```

##### **JHipster configuration**

jhipster info
```
PS C:\Users\user\myapplication> jhipster info
WARNING! Since JHipster v8, the jhipster command will not use the locally installed generator-jhipster.
    If you want to execute the locally installed generator-jhipster, run: npx jhipster

        ██╗ ██╗   ██╗ ████████╗ ███████╗   ██████╗ ████████╗ ████████╗ ███████╗
        ██║ ██║   ██║ ╚══██╔══╝ ██╔═══██╗ ██╔════╝ ╚══██╔══╝ ██╔═════╝ ██╔═══██╗
        ██║ ████████║    ██║    ███████╔╝ ╚█████╗     ██║    ██████╗   ███████╔╝
  ██╗   ██║ ██╔═══██║    ██║    ██╔════╝   ╚═══██╗    ██║    ██╔═══╝   ██╔══██║
  ╚██████╔╝ ██║   ██║ ████████╗ ██║       ██████╔╝    ██║    ████████╗ ██║  ╚██╗
   ╚═════╝  ╚═╝   ╚═╝ ╚═══════╝ ╚═╝       ╚═════╝     ╚═╝    ╚═══════╝ ╚═╝   ╚═╝
                            https://www.jhipster.tech
Welcome to JHipster v8.0.0-beta.1

Welcome to the JHipster Information Sub-Generator


```
myapplication@0.0.0 C:\Users\user\myapplication
`-- generator-jhipster@8.0.0-beta.1
```


##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**


<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "applicationType": "microservice",
  "authenticationType": "oauth2",
  "baseName": "myapplication",
  "buildTool": "maven",
  "cacheProvider": "infinispan",
  "clientFramework": "no",
  "creationTimestamp": 1686990041090,
  "databaseType": "mongodb",
  "devDatabaseType": "mongodb",
  "dtoSuffix": "DTO",
  "enableGradleEnterprise": null,
  "enableHibernateCache": false,
  "enableSwaggerCodegen": true,
  "enableTranslation": true,
  "entities": [],
  "entitySuffix": "",
  "gradleEnterpriseHost": null,
  "jhiPrefix": "jhi",
  "jhipsterVersion": "8.0.0-beta.1",
  "languages": [
    "de",
    "en",
    "fr"
  ],
  "messageBroker": "kafka",
  "microfrontend": true,
  "microfrontends": [],
  "nativeLanguage": "de",
  "packageFolder": "com/mycompany/myapp",
  "packageName": "com.mycompany.myapp",
  "pages": [],
  "prodDatabaseType": "mongodb",
  "reactive": false,
  "searchEngine": "elasticsearch",
  "serverPort": 8081,
  "serverSideOptions": [
    "searchEngine:elasticsearch",
    "messageBroker:kafka",
    "enableSwaggerCodegen:true"
  ],
  "serviceDiscoveryType": "consul",
  "skipCheckLengthOfIdentifier": false,
  "skipClient": true,
  "skipFakeData": false,
  "skipUserManagement": true,
  "testFrameworks": [
    "cucumber"
  ],
  "websocket": "no",
  "withAdminUi": false
}
</pre>
</details>


##### **Environment and Tools**

openjdk version "1.8.0_372"
OpenJDK Runtime Environment Corretto-8.372.07.1 (build 1.8.0_372-b07)
OpenJDK 64-Bit Server VM Corretto-8.372.07.1 (build 25.372-b07, mixed mode)

git version 2.41.0.windows.1

node: v18.16.0
npm: 9.7.1

Docker version 24.0.2, build cb74dfc

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

    force .yo-rc.json

Congratulations, JHipster execution is complete!
If you find JHipster useful consider sponsoring the project https://www.jhipster.tech/sponsors/

Sponsored with ❤️  by @oktadev.
```

```

```

##### **Browsers and Operating System**

- [X] Checking this box is mandatory (this is just to show you read everything)

**Comment by anothergoodguy** [comment]
I am also getting a file not found error when trying to build a docker image on `main` branch. Here are the details:

```
docker build -t jhipster:8.0 .
[+] Building 326.3s (10/11)
 => [internal] load build definition from Dockerfile                                                                                                                                                                                                     0.1s
 => => transferring dockerfile: 2.18kB                                                                                                                                                                                                                   0.0s
 => [internal] load .dockerignore                                                                                                                                                                                                                        0.1s
 => => transferring context: 2B                                                                                                                                                                                                                          0.0s
 => resolve image config for docker.io/docker/dockerfile:1                                                                                                                                                                                               4.7s
 => CACHED docker-image://docker.io/docker/dockerfile:1@sha256:39b85bbfa7536a5feceb7372a0817649ecb2724562a38360f4d6a7782a409b14                                                                                                                          0.0s
 => [internal] load metadata for docker.io/library/eclipse-temurin:17-focal                                                                                                                                                                              3.2s
 => [internal] load build context                                                                                                                                                                                                                       10.8s
 => => transferring context: 8.19MB                                                                                                                                                                                                                      9.3s
 => CACHED [1/5] FROM docker.io/library/eclipse-temurin:17-focal@sha256:49092a946445870e6e8205043dd54f7e79fb8740a79a4648a3244c7a4a2adb41                                                                                                                 0.0s
 => => resolve docker.io/library/eclipse-temurin:17-focal@sha256:49092a946445870e6e8205043dd54f7e79fb8740a79a4648a3244c7a4a2adb41                                                                                                                        0.0s
 => [2/5] COPY . /home/jhipster/generator-jhipster                                                                                                                                                                                                      23.1s
 => [3/5] RUN   groupadd jhipster &&   useradd jhipster -s /bin/bash -m -g jhipster -G sudo &&   echo 'jhipster:jhipster' |chpasswd &&   mkdir /home/jhipster/app &&   export DEBIAN_FRONTEND=noninteractive &&   export TZ=EuropeParis &&   ln -snf   203.8s
 => ERROR [4/5] RUN   cd /home/jhipster/generator-jhipster &&   npm ci &&   npm install -g /home/jhipster/generator-jhipster &&   chown -R jhipster:jhipster     /home/jhipster     /usr/local/lib/node_modules &&   rm -rf     /home/jhipster/.cache/  79.8s
------
 > [4/5] RUN   cd /home/jhipster/generator-jhipster &&   npm ci &&   npm install -g /home/jhipster/generator-jhipster &&   chown -R jhipster:jhipster     /home/jhipster     /usr/local/lib/node_modules &&   rm -rf     /home/jhipster/.cache/     /var/lib/apt/lists/*     /tmp/*     /var/tmp/*:
#0 5.075 npm WARN EBADENGINE Unsupported engine {
#0 5.077 npm WARN EBADENGINE   package: 'generator-jhipster@8.0.0-beta.1',
#0 5.077 npm WARN EBADENGINE   required: { node: '^18.13.0 || >= 20.2.0', npm: '>=8.0.0' },
#0 5.077 npm WARN EBADENGINE   current: { node: 'v18.16.0', npm: '7.24.2' }
#0 5.080 npm WARN EBADENGINE }
#0 19.30 npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
#0 22.34 npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
#0 22.68 npm WARN deprecated har-validator@5.1.5: this library is no longer supported
#0 34.38 npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
#0 79.32 npm ERR! code ENOENT
#0 79.32 npm ERR! syscall chmod
**#0 79.32 npm ERR! path /home/jhipster/generator-jhipster/node_modules/fly-import/dist/bin.cjs
#0 79.32 npm ERR! errno -2
#0 79.32 npm ERR! enoent ENOENT: no such file or directory, chmod '/home/jhipster/generator-jhipster/node_modules/fly-**import/dist/bin.cjs'
#0 79.32 npm ERR! enoent This is related to npm not being able to find a file.
#0 79.32 npm ERR! enoent
#0 79.38
#0 79.38 npm ERR! A complete log of this run can be found in:
#0 79.38 npm ERR!     /root/.npm/_logs/2023-06-17T09_06_29_277Z-debug.log
------
Dockerfile:56
--------------------
  55 |
  56 | >>> RUN \
  57 | >>>   # install jhipster
  58 | >>>   cd /home/jhipster/generator-jhipster && \
  59 | >>>   npm ci && \
  60 | >>>   npm install -g /home/jhipster/generator-jhipster && \
  61 | >>>   # fix jhipster user permissions
  62 | >>>   chown -R jhipster:jhipster \
  63 | >>>     /home/jhipster \
  64 | >>>     /usr/local/lib/node_modules && \
  65 | >>>   # cleanup
  66 | >>>   rm -rf \
  67 | >>>     /home/jhipster/.cache/ \
  68 | >>>     /var/lib/apt/lists/* \
  69 | >>>     /tmp/* \
  70 | >>>     /var/tmp/*
  71 |
--------------------
ERROR: failed to solve: process "/bin/sh -c cd /home/jhipster/generator-jhipster &&   npm ci &&   npm install -g /home/jhipster/generator-jhipster &&   chown -R jhipster:jhipster     /home/jhipster     /usr/local/lib/node_modules &&   rm -rf     /home/jhipster/.cache/     /var/lib/apt/lists/*     /tmp/*     /var/tmp/*" did not complete successfully: exit code: 254
```

**Comment by JeroenAdam** [comment]
I'm getting the same, but everything works, this error relates to tests

**Comment by mshima** [comment]
Can be reproduced at daily builds: https://github.com/hipster-labs/jhipster-daily-builds/actions/workflows/windows.yaml

**Comment by mshima** [comment]
> I am also getting a file not found error when trying to build a docker image on `main` branch. Here are the details:
> 
> **0 79.32 npm ERR! path /home/jhipster/generator-jhipster/node_modules/fly-import/dist/bin.cjs #0 79.32 npm ERR! errno -2 #0 79.32 npm ERR! enoent ENOENT: no such file or directory, chmod '/home/jhipster/generator-jhipster/node_modules/fly-**import/dist/bin.cjs' #0 79.32 npm ERR! enoent This is related to npm not being able to find a file. #0 79.32 npm ERR! enoent**
> 
> ```
> docker build -t jhipster:8.0 .
> [+] Building 326.3s (10/11)
>  => [internal] load build definition from Dockerfile                                                                                                                                                                                                     0.1s
>  => => transferring dockerfile: 2.18kB                                                                                                                                                                                                                   0.0s
>  => [internal] load .dockerignore                                                                                                                                                                                                                        0.1s
>  => => transferring context: 2B                                                                                                                                                                                                                          0.0s
>  => resolve image config for docker.io/docker/dockerfile:1                                                                                                                                                                                               4.7s
>  => CACHED docker-image://docker.io/docker/dockerfile:1@sha256:39b85bbfa7536a5feceb7372a0817649ecb2724562a38360f4d6a7782a409b14                                                                                                                          0.0s
>  => [internal] load metadata for docker.io/library/eclipse-temurin:17-focal                                                                                                                                                                              3.2s
>  => [internal] load build context                                                                                                                                                                                                                       10.8s
>  => => transferring context: 8.19MB                                                                                                                                                                                                                      9.3s
>  => CACHED [1/5] FROM docker.io/library/eclipse-temurin:17-focal@sha256:49092a946445870e6e8205043dd54f7e79fb8740a79a4648a3244c7a4a2adb41                                                                                                                 0.0s
>  => => resolve docker.io/library/eclipse-temurin:17-focal@sha256:49092a946445870e6e8205043dd54f7e79fb8740a79a4648a3244c7a4a2adb41                                                                                                                        0.0s
>  => [2/5] COPY . /home/jhipster/generator-jhipster                                                                                                                                                                                                      23.1s
>  => [3/5] RUN   groupadd jhipster &&   useradd jhipster -s /bin/bash -m -g jhipster -G sudo &&   echo 'jhipster:jhipster' |chpasswd &&   mkdir /home/jhipster/app &&   export DEBIAN_FRONTEND=noninteractive &&   export TZ=EuropeParis &&   ln -snf   203.8s
>  => ERROR [4/5] RUN   cd /home/jhipster/generator-jhipster &&   npm ci &&   npm install -g /home/jhipster/generator-jhipster &&   chown -R jhipster:jhipster     /home/jhipster     /usr/local/lib/node_modules &&   rm -rf     /home/jhipster/.cache/  79.8s
> ------
>  > [4/5] RUN   cd /home/jhipster/generator-jhipster &&   npm ci &&   npm install -g /home/jhipster/generator-jhipster &&   chown -R jhipster:jhipster     /home/jhipster     /usr/local/lib/node_modules &&   rm -rf     /home/jhipster/.cache/     /var/lib/apt/lists/*     /tmp/*     /var/tmp/*:
> #0 5.075 npm WARN EBADENGINE Unsupported engine {
> #0 5.077 npm WARN EBADENGINE   package: 'generator-jhipster@8.0.0-beta.1',
> #0 5.077 npm WARN EBADENGINE   required: { node: '^18.13.0 || >= 20.2.0', npm: '>=8.0.0' },
> #0 5.077 npm WARN EBADENGINE   current: { node: 'v18.16.0', npm: '7.24.2' }
> #0 5.080 npm WARN EBADENGINE }
> #0 19.30 npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
> #0 22.34 npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
> #0 22.68 npm WARN deprecated har-validator@5.1.5: this library is no longer supported
> #0 34.38 npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
> #0 79.32 npm ERR! code ENOENT
> #0 79.32 npm ERR! syscall chmod
> **#0 79.32 npm ERR! path /home/jhipster/generator-jhipster/node_modules/fly-import/dist/bin.cjs
> #0 79.32 npm ERR! errno -2
> #0 79.32 npm ERR! enoent ENOENT: no such file or directory, chmod '/home/jhipster/generator-jhipster/node_modules/fly-**import/dist/bin.cjs'
> #0 79.32 npm ERR! enoent This is related to npm not being able to find a file.
> #0 79.32 npm ERR! enoent
> #0 79.38
> #0 79.38 npm ERR! A complete log of this run can be found in:
> #0 79.38 npm ERR!     /root/.npm/_logs/2023-06-17T09_06_29_277Z-debug.log
> ------
> Dockerfile:56
> --------------------
>   55 |
>   56 | >>> RUN \
>   57 | >>>   # install jhipster
>   58 | >>>   cd /home/jhipster/generator-jhipster && \
>   59 | >>>   npm ci && \
>   60 | >>>   npm install -g /home/jhipster/generator-jhipster && \
>   61 | >>>   # fix jhipster user permissions
>   62 | >>>   chown -R jhipster:jhipster \
>   63 | >>>     /home/jhipster \
>   64 | >>>     /usr/local/lib/node_modules && \
>   65 | >>>   # cleanup
>   66 | >>>   rm -rf \
>   67 | >>>     /home/jhipster/.cache/ \
>   68 | >>>     /var/lib/apt/lists/* \
>   69 | >>>     /tmp/* \
>   70 | >>>     /var/tmp/*
>   71 |
> --------------------
> ERROR: failed to solve: process "/bin/sh -c cd /home/jhipster/generator-jhipster &&   npm ci &&   npm install -g /home/jhipster/generator-jhipster &&   chown -R jhipster:jhipster     /home/jhipster     /usr/local/lib/node_modules &&   rm -rf     /home/jhipster/.cache/     /var/lib/apt/lists/*     /tmp/*     /var/tmp/*" did not complete successfully: exit code: 254
> ```

This a different bug.
