### ISSUE TITLE
Error when opening the openapi page

### ISSUE THREAD

**Issue by skin27** [jhipster/generator-jhipster#22654]
##### **Overview of the issue**

When open the openapi page (administration --> api) in the 8.0 beta1 an error is thrown.

Error

```
2023-06-23T16:14:05.367+02:00  WARN 4028 --- [tor-http-nio-20] r.netty.http.client.HttpClientConnect    : [e7a9fbd4-1, L:/127.0.0.1:50915 ! R:/127.0.0.1:8300] The connection observed an error

reactor.netty.http.client.PrematureCloseException: Connection prematurely closed BEFORE response

2023-06-23T16:14:05.374+02:00 ERROR 4028 --- [tor-http-nio-20] a.w.r.e.AbstractErrorWebExceptionHandler : [62be01b1-219]  500 Server Error for HTTP GET "/services/consul/management/jhiopenapigroups"

reactor.netty.http.client.PrematureCloseException: Connection prematurely closed BEFORE response
        Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException:
Assembly trace from producer [reactor.core.publisher.MonoCreate] :
        reactor.core.publisher.Mono.create(Mono.java:202)
        reactor.netty.http.client.HttpClientConnect$MonoHttpConnect.subscribe(HttpClientConnect.java:210)
Error has been observed at the following site(s):
        *_____________Mono.create ? at reactor.netty.http.client.HttpClientConnect$MonoHttpConnect.subscribe(HttpClientConnect.java:210)
        |_         Mono.retryWhen ? at reactor.netty.http.client.HttpClientConnect$MonoHttpConnect.subscribe(HttpClientConnect.java:275)
        *__________Flux.concatMap ? at reactor.util.retry.RetrySpec.lambda$generateCompanion$6(RetrySpec.java:360)
        |_       Flux.onErrorStop ? at reactor.util.retry.RetrySpec.lambda$generateCompanion$6(RetrySpec.java:379)
        *____Flux.deferContextual ? at reactor.util.retry.RetrySpec.generateCompanion(RetrySpec.java:357)
        *________Mono.flatMapMany ? at reactor.netty.http.client.HttpClientFinalizer.responseConnection(HttpClientFinalizer.java:102)
        *_______________Flux.then ? at org.springframework.cloud.gateway.filter.NettyRoutingFilter.filter(NettyRoutingFilter.java:198)
        *______________Mono.defer ? at org.springframework.cloud.gateway.handler.FilteringWebHandler$DefaultGatewayFilterChain.filter(FilteringWebHandler.java:113)
        *______________Mono.defer ? at org.springframework.cloud.gateway.handler.FilteringWebHandler$DefaultGatewayFilterChain.filter(FilteringWebHandler.java:113)
        *______________Mono.defer ? at org.springframework.cloud.gateway.handler.FilteringWebHandler$DefaultGatewayFilterChain.filter(FilteringWebHandler.java:113)
        *_______________Mono.then ? at org.springframework.cloud.gateway.filter.ReactiveLoadBalancerClientFilter.filter(ReactiveLoadBalancerClientFilter.java:148)
        |_         Mono.doOnError ? at org.springframework.cloud.gateway.filter.ReactiveLoadBalancerClientFilter.filter(ReactiveLoadBalancerClientFilter.java:149)
        |_       Mono.doOnSuccess ? at org.springframework.cloud.gateway.filter.ReactiveLoadBalancerClientFilter.filter(ReactiveLoadBalancerClientFilter.java:153)
        *______________Mono.defer ? at org.springframework.cloud.gateway.handler.FilteringWebHandler$DefaultGatewayFilterChain.filter(FilteringWebHandler.java:113)
        *______________Mono.defer ? at org.springframework.cloud.gateway.handler.FilteringWebHandler$DefaultGatewayFilterChain.filter(FilteringWebHandler.java:113)
        *______________Mono.defer ? at org.springframework.cloud.gateway.handler.FilteringWebHandler$DefaultGatewayFilterChain.filter(FilteringWebHandler.java:113)
        *____________Mono.flatMap ? at org.assimbly.gateway.security.jwt.JWTRelayGatewayFilterFactory.lambda$apply$0(JWTRelayGatewayFilterFactory.java:32)
        *______________Mono.defer ? at org.springframework.cloud.gateway.handler.FilteringWebHandler$DefaultGatewayFilterChain.filter(FilteringWebHandler.java:113)
        |_       Mono.doOnSuccess ? at org.springframework.cloud.gateway.filter.GatewayMetricsFilter.filter(GatewayMetricsFilter.java:75)
        |_         Mono.doOnError ? at org.springframework.cloud.gateway.filter.GatewayMetricsFilter.filter(GatewayMetricsFilter.java:76)
        *______________Mono.defer ? at org.springframework.cloud.gateway.handler.FilteringWebHandler$DefaultGatewayFilterChain.filter(FilteringWebHandler.java:113)
        *______________Mono.defer ? at org.springframework.cloud.gateway.handler.FilteringWebHandler$DefaultGatewayFilterChain.filter(FilteringWebHandler.java:113)
        *_______________Mono.then ? at org.springframework.cloud.gateway.filter.NettyWriteResponseFilter.filter(NettyWriteResponseFilter.java:69)
        |_        Mono.doOnCancel ? at org.springframework.cloud.gateway.filter.NettyWriteResponseFilter.filter(NettyWriteResponseFilter.java:101)
        |_         Mono.doOnError ? at org.springframework.cloud.gateway.filter.NettyWriteResponseFilter.filter(NettyWriteResponseFilter.java:102)
        *______________Mono.defer ? at org.springframework.cloud.gateway.handler.FilteringWebHandler$DefaultGatewayFilterChain.filter(FilteringWebHandler.java:113)
        *______________Mono.defer ? at org.springframework.cloud.gateway.handler.FilteringWebHandler$DefaultGatewayFilterChain.filter(FilteringWebHandler.java:113)
        *______________Mono.defer ? at org.springframework.cloud.gateway.handler.FilteringWebHandler$DefaultGatewayFilterChain.filter(FilteringWebHandler.java:113)
        |_         Mono.doFinally ? at org.springframework.cloud.gateway.filter.RemoveCachedBodyFilter.filter(RemoveCachedBodyFilter.java:35)
        *______________Mono.defer ? at org.springframework.cloud.gateway.handler.FilteringWebHandler$DefaultGatewayFilterChain.filter(FilteringWebHandler.java:113)
        *_______________Mono.then ? at org.springframework.web.reactive.result.SimpleHandlerAdapter.handle(SimpleHandlerAdapter.java:46)
        |_           Mono.flatMap ? at org.springframework.web.reactive.DispatcherHandler.handleRequestWith(DispatcherHandler.java:184)
        *____________Mono.flatMap ? at org.springframework.web.reactive.DispatcherHandler.handle(DispatcherHandler.java:154)
        *______________Mono.defer ? at org.springframework.web.server.handler.DefaultWebFilterChain.filter(DefaultWebFilterChain.java:106)
        |_             checkpoint ? org.springframework.web.cors.reactive.CorsWebFilter [DefaultWebFilterChain]
        *______________Mono.defer ? at org.springframework.web.server.handler.DefaultWebFilterChain.filter(DefaultWebFilterChain.java:106)
        |_             checkpoint ? org.assimbly.gateway.config.LocaleConfiguration$$Lambda$1380/0x000000080172d228 [DefaultWebFilterChain]
        *______________Mono.defer ? at org.springframework.web.server.handler.DefaultWebFilterChain.filter(DefaultWebFilterChain.java:106)
        |_             checkpoint ? org.springframework.cloud.gateway.filter.WeightCalculatorWebFilter [DefaultWebFilterChain]
        *______________Mono.defer ? at org.springframework.web.server.handler.DefaultWebFilterChain.filter(DefaultWebFilterChain.java:106)
        *______________Mono.defer ? at org.springframework.web.server.handler.DefaultWebFilterChain.filter(DefaultWebFilterChain.java:106)
        *______Mono.switchIfEmpty ? at org.springframework.security.web.server.authorization.AuthorizationWebFilter.filter(AuthorizationWebFilter.java:55)
        |_             checkpoint ? org.springframework.security.web.server.authorization.AuthorizationWebFilter [DefaultWebFilterChain]
        *______________Mono.defer ? at org.springframework.web.server.handler.DefaultWebFilterChain.filter(DefaultWebFilterChain.java:106)
        |_     Mono.onErrorResume ? at org.springframework.security.web.server.authorization.ExceptionTranslationWebFilter.filter(ExceptionTranslationWebFilter.java:52)
        |_             checkpoint ? org.springframework.security.web.server.authorization.ExceptionTranslationWebFilter [DefaultWebFilterChain]
        *______________Mono.defer ? at org.springframework.web.server.handler.DefaultWebFilterChain.filter(DefaultWebFilterChain.java:106)
        *_______________Mono.then ? at org.springframework.security.web.server.authentication.logout.LogoutWebFilter.filter(LogoutWebFilter.java:62)
        *______Mono.switchIfEmpty ? at org.springframework.security.web.server.authentication.logout.LogoutWebFilter.filter(LogoutWebFilter.java:62)
        |_               Mono.map ? at org.springframework.security.web.server.authentication.logout.LogoutWebFilter.filter(LogoutWebFilter.java:62)
        |_           Mono.flatMap ? at org.springframework.security.web.server.authentication.logout.LogoutWebFilter.filter(LogoutWebFilter.java:63)
        |_           Mono.flatMap ? at org.springframework.security.web.server.authentication.logout.LogoutWebFilter.filter(LogoutWebFilter.java:63)
        |_             checkpoint ? org.springframework.security.web.server.authentication.logout.LogoutWebFilter [DefaultWebFilterChain]
        *______________Mono.defer ? at org.springframework.web.server.handler.DefaultWebFilterChain.filter(DefaultWebFilterChain.java:106)
        *____________Mono.flatMap ? at org.springframework.security.web.server.savedrequest.ServerRequestCacheWebFilter.filter(ServerRequestCacheWebFilter.java:39)
        |_             checkpoint ? org.springframework.security.web.server.savedrequest.ServerRequestCacheWebFilter [DefaultWebFilterChain]
        *______________Mono.defer ? at org.springframework.web.server.handler.DefaultWebFilterChain.filter(DefaultWebFilterChain.java:106)
        |_             checkpoint ? org.springframework.security.web.server.context.SecurityContextServerWebExchangeWebFilter [DefaultWebFilterChain]
        *______________Mono.defer ? at org.springframework.web.server.handler.DefaultWebFilterChain.filter(DefaultWebFilterChain.java:106)
        *_______________Mono.then ? at org.springframework.security.web.server.authentication.AuthenticationWebFilter.onAuthenticationSuccess(AuthenticationWebFilter.java:135)
        |_      Mono.contextWrite ? at org.springframework.security.web.server.authentication.AuthenticationWebFilter.onAuthenticationSuccess(AuthenticationWebFilter.java:136)
        *____________Mono.flatMap ? at org.springframework.security.web.server.authentication.AuthenticationWebFilter.authenticate(AuthenticationWebFilter.java:124)
        |_         Mono.doOnError ? at org.springframework.security.web.server.authentication.AuthenticationWebFilter.authenticate(AuthenticationWebFilter.java:126)
        *____________Mono.flatMap ? at org.springframework.security.web.server.authentication.AuthenticationWebFilter.filter(AuthenticationWebFilter.java:114)
        |_     Mono.onErrorResume ? at org.springframework.security.web.server.authentication.AuthenticationWebFilter.filter(AuthenticationWebFilter.java:115)
        |_             checkpoint ? org.springframework.security.web.server.authentication.AuthenticationWebFilter [DefaultWebFilterChain]
        *______________Mono.defer ? at org.springframework.web.server.handler.DefaultWebFilterChain.filter(DefaultWebFilterChain.java:106)
        |_      Mono.contextWrite ? at org.springframework.security.web.server.context.ReactorContextWebFilter.filter(ReactorContextWebFilter.java:47)
        |_             checkpoint ? org.springframework.security.web.server.context.ReactorContextWebFilter [DefaultWebFilterChain]
        *______________Mono.defer ? at org.springframework.web.server.handler.DefaultWebFilterChain.filter(DefaultWebFilterChain.java:106)
        |_             checkpoint ? org.assimbly.gateway.web.filter.SpaWebFilter [DefaultWebFilterChain]
        *______________Mono.defer ? at org.springframework.web.server.handler.DefaultWebFilterChain.filter(DefaultWebFilterChain.java:106)
        |_             checkpoint ? org.springframework.security.web.server.header.HttpHeaderWriterWebFilter [DefaultWebFilterChain]
        *______________Mono.defer ? at org.springframework.web.server.handler.DefaultWebFilterChain.filter(DefaultWebFilterChain.java:106)
        |_      Mono.contextWrite ? at org.springframework.security.config.web.server.ServerHttpSecurity$ServerWebExchangeReactorContextWebFilter.filter(ServerHttpSecurity.java:3287)
        |_             checkpoint ? org.springframework.security.config.web.server.ServerHttpSecurity$ServerWebExchangeReactorContextWebFilter [DefaultWebFilterChain]
        *______________Mono.defer ? at org.springframework.web.server.handler.DefaultWebFilterChain.filter(DefaultWebFilterChain.java:106)
        *____________Mono.flatMap ? at org.springframework.security.web.server.WebFilterChainProxy.filter(WebFilterChainProxy.java:62)
        |_             checkpoint ? org.springframework.security.web.server.WebFilterChainProxy [DefaultWebFilterChain]
        *______________Mono.defer ? at org.springframework.web.server.handler.DefaultWebFilterChain.filter(DefaultWebFilterChain.java:106)
        |_          Mono.doOnEach ? at org.springframework.web.filter.reactive.ServerHttpObservationFilter.filter(ServerHttpObservationFilter.java:109)
        |_        Mono.doOnCancel ? at org.springframework.web.filter.reactive.ServerHttpObservationFilter.filter(ServerHttpObservationFilter.java:119)
        |_      Mono.contextWrite ? at org.springframework.web.filter.reactive.ServerHttpObservationFilter.filter(ServerHttpObservationFilter.java:123)
        *__Mono.transformDeferred ? at org.springframework.web.filter.reactive.ServerHttpObservationFilter.filter(ServerHttpObservationFilter.java:102)
        |_             checkpoint ? org.springframework.web.filter.reactive.ServerHttpObservationFilter [DefaultWebFilterChain]
        *______________Mono.defer ? at org.springframework.web.server.handler.DefaultWebFilterChain.filter(DefaultWebFilterChain.java:106)
        |_     Mono.onErrorResume ? at org.springframework.web.server.handler.ExceptionHandlingWebHandler.handle(ExceptionHandlingWebHandler.java:77)
        |_     Mono.onErrorResume ? at org.springframework.web.server.handler.ExceptionHandlingWebHandler.handle(ExceptionHandlingWebHandler.java:77)
        |_     Mono.onErrorResume ? at org.springframework.web.server.handler.ExceptionHandlingWebHandler.handle(ExceptionHandlingWebHandler.java:77)
        *______________Mono.error ? at org.springframework.web.server.handler.ExceptionHandlingWebHandler$CheckpointInsertingHandler.handle(ExceptionHandlingWebHandler.java:98)
        |_             checkpoint ? HTTP GET "/services/consul/management/jhiopenapigroups" [ExceptionHandlingWebHandler]
        *______________Mono.error ? at org.springframework.cloud.gateway.filter.headers.observation.ObservationClosingWebExceptionHandler.handle(ObservationClosingWebExceptionHandler.java:53)
        *______________Mono.error ? at tech.jhipster.web.rest.errors.ReactiveWebExceptionHandler.handle(ReactiveWebExceptionHandler.java:63)
Original Stack Trace:

2023-06-23T16:14:05.411+02:00  WARN 4028 --- [ctor-http-nio-1] r.netty.http.client.HttpClientConnect    : [eb6b4b13-1, L:/127.0.0.1:50916 ! R:/127.0.0.1:8300] The connection observed an error

reactor.netty.http.client.PrematureCloseException: Connection prematurely closed BEFORE response

2023-06-23T16:14:05.417+02:00 ERROR 4028 --- [ctor-http-nio-1] a.w.r.e.AbstractErrorWebExceptionHandler : [62be01b1-222]  500 Server Error for HTTP GET "/services/consul/v3/api-docs"

reactor.netty.http.client.PrematureCloseException: Connection prematurely closed BEFORE response
        Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException:
Assembly trace from producer [reactor.core.publisher.MonoCreate] :
        reactor.core.publisher.Mono.create(Mono.java:202)
        reactor.netty.http.client.HttpClientConnect$MonoHttpConnect.subscribe(HttpClientConnect.java:210)
Error has been observed at the following site(s):
        *_____________Mono.create ? at reactor.netty.http.client.HttpClientConnect$MonoHttpConnect.subscribe(HttpClientConnect.java:210)
        |_         Mono.retryWhen ? at reactor.netty.http.client.HttpClientConnect$MonoHttpConnect.subscribe(HttpClientConnect.java:275)
        *__________Flux.concatMap ? at reactor.util.retry.RetrySpec.lambda$generateCompanion$6(RetrySpec.java:360)
        |_       Flux.onErrorStop ? at reactor.util.retry.RetrySpec.lambda$generateCompanion$6(RetrySpec.java:379)
        *____Flux.deferContextual ? at reactor.util.retry.RetrySpec.generateCompanion(RetrySpec.java:357)
        *________Mono.flatMapMany ? at reactor.netty.http.client.HttpClientFinalizer.responseConnection(HttpClientFinalizer.java:102)
        *_______________Flux.then ? at org.springframework.cloud.gateway.filter.NettyRoutingFilter.filter(NettyRoutingFilter.java:198)
        *______________Mono.defer ? at org.springframework.cloud.gateway.handler.FilteringWebHandler$DefaultGatewayFilterChain.filter(FilteringWebHandler.java:113)
        *______________Mono.defer ? at org.springframework.cloud.gateway.handler.FilteringWebHandler$DefaultGatewayFilterChain.filter(FilteringWebHandler.java:113)
        *______________Mono.defer ? at org.springframework.cloud.gateway.handler.FilteringWebHandler$DefaultGatewayFilterChain.filter(FilteringWebHandler.java:113)
        *_______________Mono.then ? at org.springframework.cloud.gateway.filter.ReactiveLoadBalancerClientFilter.filter(ReactiveLoadBalancerClientFilter.java:148)
        |_         Mono.doOnError ? at org.springframework.cloud.gateway.filter.ReactiveLoadBalancerClientFilter.filter(ReactiveLoadBalancerClientFilter.java:149)
        |_       Mono.doOnSuccess ? at org.springframework.cloud.gateway.filter.ReactiveLoadBalancerClientFilter.filter(ReactiveLoadBalancerClientFilter.java:153)
        *______________Mono.defer ? at org.springframework.cloud.gateway.handler.FilteringWebHandler$DefaultGatewayFilterChain.filter(FilteringWebHandler.java:113)
        *______________Mono.defer ? at org.springframework.cloud.gateway.handler.FilteringWebHandler$DefaultGatewayFilterChain.filter(FilteringWebHandler.java:113)
        *______________Mono.defer ? at org.springframework.cloud.gateway.handler.FilteringWebHandler$DefaultGatewayFilterChain.filter(FilteringWebHandler.java:113)
        *____________Mono.flatMap ? at org.assimbly.gateway.security.jwt.JWTRelayGatewayFilterFactory.lambda$apply$0(JWTRelayGatewayFilterFactory.java:32)
        *______________Mono.defer ? at org.springframework.cloud.gateway.handler.FilteringWebHandler$DefaultGatewayFilterChain.filter(FilteringWebHandler.java:113)
        |_       Mono.doOnSuccess ? at org.springframework.cloud.gateway.filter.GatewayMetricsFilter.filter(GatewayMetricsFilter.java:75)
        |_         Mono.doOnError ? at org.springframework.cloud.gateway.filter.GatewayMetricsFilter.filter(GatewayMetricsFilter.java:76)
        *______________Mono.defer ? at org.springframework.cloud.gateway.handler.FilteringWebHandler$DefaultGatewayFilterChain.filter(FilteringWebHandler.java:113)
        *______________Mono.defer ? at org.springframework.cloud.gateway.handler.FilteringWebHandler$DefaultGatewayFilterChain.filter(FilteringWebHandler.java:113)
        *_______________Mono.then ? at org.springframework.cloud.gateway.filter.NettyWriteResponseFilter.filter(NettyWriteResponseFilter.java:69)
        |_        Mono.doOnCancel ? at org.springframework.cloud.gateway.filter.NettyWriteResponseFilter.filter(NettyWriteResponseFilter.java:101)
        |_         Mono.doOnError ? at org.springframework.cloud.gateway.filter.NettyWriteResponseFilter.filter(NettyWriteResponseFilter.java:102)
        *______________Mono.defer ? at org.springframework.cloud.gateway.handler.FilteringWebHandler$DefaultGatewayFilterChain.filter(FilteringWebHandler.java:113)
        *______________Mono.defer ? at org.springframework.cloud.gateway.handler.FilteringWebHandler$DefaultGatewayFilterChain.filter(FilteringWebHandler.java:113)
        *______________Mono.defer ? at org.springframework.cloud.gateway.handler.FilteringWebHandler$DefaultGatewayFilterChain.filter(FilteringWebHandler.java:113)
        |_         Mono.doFinally ? at org.springframework.cloud.gateway.filter.RemoveCachedBodyFilter.filter(RemoveCachedBodyFilter.java:35)
        *______________Mono.defer ? at org.springframework.cloud.gateway.handler.FilteringWebHandler$DefaultGatewayFilterChain.filter(FilteringWebHandler.java:113)
        *_______________Mono.then ? at org.springframework.web.reactive.result.SimpleHandlerAdapter.handle(SimpleHandlerAdapter.java:46)
        |_           Mono.flatMap ? at org.springframework.web.reactive.DispatcherHandler.handleRequestWith(DispatcherHandler.java:184)
        *____________Mono.flatMap ? at org.springframework.web.reactive.DispatcherHandler.handle(DispatcherHandler.java:154)
        *______________Mono.defer ? at org.springframework.web.server.handler.DefaultWebFilterChain.filter(DefaultWebFilterChain.java:106)
        |_             checkpoint ? org.springframework.web.cors.reactive.CorsWebFilter [DefaultWebFilterChain]
        *______________Mono.defer ? at org.springframework.web.server.handler.DefaultWebFilterChain.filter(DefaultWebFilterChain.java:106)
        |_             checkpoint ? org.assimbly.gateway.config.LocaleConfiguration$$Lambda$1380/0x000000080172d228 [DefaultWebFilterChain]
        *______________Mono.defer ? at org.springframework.web.server.handler.DefaultWebFilterChain.filter(DefaultWebFilterChain.java:106)
        |_             checkpoint ? org.springframework.cloud.gateway.filter.WeightCalculatorWebFilter [DefaultWebFilterChain]
        *______________Mono.defer ? at org.springframework.web.server.handler.DefaultWebFilterChain.filter(DefaultWebFilterChain.java:106)
        *______________Mono.defer ? at org.springframework.web.server.handler.DefaultWebFilterChain.filter(DefaultWebFilterChain.java:106)
        *______Mono.switchIfEmpty ? at org.springframework.security.web.server.authorization.AuthorizationWebFilter.filter(AuthorizationWebFilter.java:55)
        |_             checkpoint ? org.springframework.security.web.server.authorization.AuthorizationWebFilter [DefaultWebFilterChain]
        *______________Mono.defer ? at org.springframework.web.server.handler.DefaultWebFilterChain.filter(DefaultWebFilterChain.java:106)
        |_     Mono.onErrorResume ? at org.springframework.security.web.server.authorization.ExceptionTranslationWebFilter.filter(ExceptionTranslationWebFilter.java:52)
        |_             checkpoint ? org.springframework.security.web.server.authorization.ExceptionTranslationWebFilter [DefaultWebFilterChain]
        *______________Mono.defer ? at org.springframework.web.server.handler.DefaultWebFilterChain.filter(DefaultWebFilterChain.java:106)
        *_______________Mono.then ? at org.springframework.security.web.server.authentication.logout.LogoutWebFilter.filter(LogoutWebFilter.java:62)
        *______Mono.switchIfEmpty ? at org.springframework.security.web.server.authentication.logout.LogoutWebFilter.filter(LogoutWebFilter.java:62)
        |_               Mono.map ? at org.springframework.security.web.server.authentication.logout.LogoutWebFilter.filter(LogoutWebFilter.java:62)
        |_           Mono.flatMap ? at org.springframework.security.web.server.authentication.logout.LogoutWebFilter.filter(LogoutWebFilter.java:63)
        |_           Mono.flatMap ? at org.springframework.security.web.server.authentication.logout.LogoutWebFilter.filter(LogoutWebFilter.java:63)
        |_             checkpoint ? org.springframework.security.web.server.authentication.logout.LogoutWebFilter [DefaultWebFilterChain]
        *______________Mono.defer ? at org.springframework.web.server.handler.DefaultWebFilterChain.filter(DefaultWebFilterChain.java:106)
        *____________Mono.flatMap ? at org.springframework.security.web.server.savedrequest.ServerRequestCacheWebFilter.filter(ServerRequestCacheWebFilter.java:39)
        |_             checkpoint ? org.springframework.security.web.server.savedrequest.ServerRequestCacheWebFilter [DefaultWebFilterChain]
        *______________Mono.defer ? at org.springframework.web.server.handler.DefaultWebFilterChain.filter(DefaultWebFilterChain.java:106)
        |_             checkpoint ? org.springframework.security.web.server.context.SecurityContextServerWebExchangeWebFilter [DefaultWebFilterChain]
        *______________Mono.defer ? at org.springframework.web.server.handler.DefaultWebFilterChain.filter(DefaultWebFilterChain.java:106)
        *_______________Mono.then ? at org.springframework.security.web.server.authentication.AuthenticationWebFilter.onAuthenticationSuccess(AuthenticationWebFilter.java:135)
        |_      Mono.contextWrite ? at org.springframework.security.web.server.authentication.AuthenticationWebFilter.onAuthenticationSuccess(AuthenticationWebFilter.java:136)
        *____________Mono.flatMap ? at org.springframework.security.web.server.authentication.AuthenticationWebFilter.authenticate(AuthenticationWebFilter.java:124)
        |_         Mono.doOnError ? at org.springframework.security.web.server.authentication.AuthenticationWebFilter.authenticate(AuthenticationWebFilter.java:126)
        *____________Mono.flatMap ? at org.springframework.security.web.server.authentication.AuthenticationWebFilter.filter(AuthenticationWebFilter.java:114)
        |_     Mono.onErrorResume ? at org.springframework.security.web.server.authentication.AuthenticationWebFilter.filter(AuthenticationWebFilter.java:115)
        |_             checkpoint ? org.springframework.security.web.server.authentication.AuthenticationWebFilter [DefaultWebFilterChain]
        *______________Mono.defer ? at org.springframework.web.server.handler.DefaultWebFilterChain.filter(DefaultWebFilterChain.java:106)
        |_      Mono.contextWrite ? at org.springframework.security.web.server.context.ReactorContextWebFilter.filter(ReactorContextWebFilter.java:47)
        |_             checkpoint ? org.springframework.security.web.server.context.ReactorContextWebFilter [DefaultWebFilterChain]
        *______________Mono.defer ? at org.springframework.web.server.handler.DefaultWebFilterChain.filter(DefaultWebFilterChain.java:106)
        |_             checkpoint ? org.assimbly.gateway.web.filter.SpaWebFilter [DefaultWebFilterChain]
        *______________Mono.defer ? at org.springframework.web.server.handler.DefaultWebFilterChain.filter(DefaultWebFilterChain.java:106)
        |_             checkpoint ? org.springframework.security.web.server.header.HttpHeaderWriterWebFilter [DefaultWebFilterChain]
        *______________Mono.defer ? at org.springframework.web.server.handler.DefaultWebFilterChain.filter(DefaultWebFilterChain.java:106)
        |_      Mono.contextWrite ? at org.springframework.security.config.web.server.ServerHttpSecurity$ServerWebExchangeReactorContextWebFilter.filter(ServerHttpSecurity.java:3287)
        |_             checkpoint ? org.springframework.security.config.web.server.ServerHttpSecurity$ServerWebExchangeReactorContextWebFilter [DefaultWebFilterChain]
        *______________Mono.defer ? at org.springframework.web.server.handler.DefaultWebFilterChain.filter(DefaultWebFilterChain.java:106)
        *____________Mono.flatMap ? at org.springframework.security.web.server.WebFilterChainProxy.filter(WebFilterChainProxy.java:62)
        |_             checkpoint ? org.springframework.security.web.server.WebFilterChainProxy [DefaultWebFilterChain]
        *______________Mono.defer ? at org.springframework.web.server.handler.DefaultWebFilterChain.filter(DefaultWebFilterChain.java:106)
        |_          Mono.doOnEach ? at org.springframework.web.filter.reactive.ServerHttpObservationFilter.filter(ServerHttpObservationFilter.java:109)
        |_        Mono.doOnCancel ? at org.springframework.web.filter.reactive.ServerHttpObservationFilter.filter(ServerHttpObservationFilter.java:119)
        |_      Mono.contextWrite ? at org.springframework.web.filter.reactive.ServerHttpObservationFilter.filter(ServerHttpObservationFilter.java:123)
        *__Mono.transformDeferred ? at org.springframework.web.filter.reactive.ServerHttpObservationFilter.filter(ServerHttpObservationFilter.java:102)
        |_             checkpoint ? org.springframework.web.filter.reactive.ServerHttpObservationFilter [DefaultWebFilterChain]
        *______________Mono.defer ? at org.springframework.web.server.handler.DefaultWebFilterChain.filter(DefaultWebFilterChain.java:106)
        |_     Mono.onErrorResume ? at org.springframework.web.server.handler.ExceptionHandlingWebHandler.handle(ExceptionHandlingWebHandler.java:77)
        |_     Mono.onErrorResume ? at org.springframework.web.server.handler.ExceptionHandlingWebHandler.handle(ExceptionHandlingWebHandler.java:77)
        |_     Mono.onErrorResume ? at org.springframework.web.server.handler.ExceptionHandlingWebHandler.handle(ExceptionHandlingWebHandler.java:77)
        *______________Mono.error ? at org.springframework.web.server.handler.ExceptionHandlingWebHandler$CheckpointInsertingHandler.handle(ExceptionHandlingWebHandler.java:98)
        |_             checkpoint ? HTTP GET "/services/consul/v3/api-docs" [ExceptionHandlingWebHandler]
        *______________Mono.error ? at org.springframework.cloud.gateway.filter.headers.observation.ObservationClosingWebExceptionHandler.handle(ObservationClosingWebExceptionHandler.java:53)
        *______________Mono.error ? at tech.jhipster.web.rest.errors.ReactiveWebExceptionHandler.handle(ReactiveWebExceptionHandler.java:63)
Original Stack Trace:

2023-06-23T16:14:05.478+02:00 DEBUG 4028 --- [    parallel-13] o.springdoc.api.AbstractOpenApiResource  : Fetching openApi document from cache
```

##### **Reproduce the error**

Go to "Administration --> API" (and check the console).

##### **JHipster Version(s)**

8.0 beta1
##### **JHipster configuration**

{
  "generator-jhipster": {
    "applicationType": "gateway",
    "authenticationType": "jwt",
    "baseName": "gateway",
    "buildTool": "maven",
    "cacheProvider": "no",
    "clientFramework": "react",
    "clientTheme": "none",
    "creationTimestamp": 1687526845741,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "devServerPort": 9060,
    "dtoSuffix": "DTO",
    "enableGradleEnterprise": null,
    "enableHibernateCache": false,
    "enableSwaggerCodegen": false,
    "enableTranslation": false,
    "entities": [],
    "entitySuffix": "",
    "gradleEnterpriseHost": null,
    "jhiPrefix": "jhi",
    "jhipsterVersion": "8.0.0-beta.1",
    "jwtSecretKey": "YTFhY2FhNGUwZmUyOTIyOWNjMThlODhiOGFmN2ZhNjg4MDA3ZDU3ODIwMTYzMjhhY2RjNTc4N2ZhMGYxMDMyOWNlOGNkZTRhNmE3YjYxYjhiYjA4ZjZkYzUzZDY1ODlmNzQ5ZmUyY2IyNDE0NjBjZmNjYzVhYjgwN2EyNDVjNWE=",
    "messageBroker": false,
    "microfrontend": true,
    "microfrontends": [
      {
        "baseName": "manager"
      },
      {
        "baseName": "designer"
      }
    ],
    "nativeLanguage": "en",
    "packageFolder": "org/assimbly/gateway",
    "packageName": "org.assimbly.gateway",
    "pages": [],
    "prodDatabaseType": "postgresql",
    "reactive": true,
    "searchEngine": false,
    "serverPort": "8081",
    "serverSideOptions": [],
    "serviceDiscoveryType": "consul",
    "skipCheckLengthOfIdentifier": false,
    "skipClient": false,
    "skipFakeData": false,
    "skipUserManagement": false,
    "testFrameworks": [],
    "websocket": false,
    "withAdminUi": true
  }
}

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

No entities

##### **Browsers and Operating System**

OS Name	Microsoft Windows 10 Pro
Version	10.0.19044 Build 19044
System Model	Precision 5570
System Type	x64-based PC
Processor	12th Gen Intel(R) Core(TM) i7-12700H, 2300 Mhz, 14 Core(s), 20 Logical Processor(s)
Java: Eclipse Temurin 17.0.7
JHipster: 8.0.0-beta.1

- [x ] Checking this box is mandatory (this is just to show you read everything)

**Comment by mraible** [comment]
Do you have a JDL to reproduce this issue? It looks like you have some downstream microservices and those might be useful for debugging.

**Comment by skin27** [comment]
[gateway.zip](https://github.com/jhipster/generator-jhipster/files/11998943/gateway.zip)

**Comment by skin27** [comment]
I didn't use a JDL file / entities yet. It's a plain gateway and I didn't add any custom code yet. I attached the code (without node_modules) and all generated files. Hope this helps.

**Comment by mshima** [comment]
@DanielFran bounty claimed https://opencollective.com/generator-jhipster/expenses/165735.

**Comment by DanielFran** [comment]
@mshima approved
