### ISSUE TITLE
jhipster 7.9.3 error with namespace

### ISSUE THREAD

**Issue by JeffeVargasP** [jhipster/generator-jhipster#22774]
##### **Overview of the issue**

When you install the latest stable version of jhipster that's 7.9.3 via npm and try to execute jhipster cli or jhipster jdl <file.jdl> it's returning the error:

```INFO! Using bundled JHipster
node:internal/modules/cjs/loader:573
      throw e;
      ^

Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './lib/util/namespace' is not defined by "exports" in /home/$USER/.nvm/versions/node/v18.16.1/lib/node_modules/generator-jhipster/node_modules/yeoman-environment/package.json
    at new NodeError (node:internal/errors:399:5)
    at exportsNotFound (node:internal/modules/esm/resolve:361:10)
    at packageExportsResolve (node:internal/modules/esm/resolve:697:9)
    at resolveExports (node:internal/modules/cjs/loader:567:36)
    at Module._findPath (node:internal/modules/cjs/loader:636:31)
    at Module._resolveFilename (node:internal/modules/cjs/loader:1063:27)
    at Module._load (node:internal/modules/cjs/loader:922:27)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (/home/$USER/.nvm/versions/node/v18.16.1/lib/node_modules/generator-jhipster/utils/blueprint.js:19:25) {
  code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
}
```

```npm i -g generator-jhipster@7.9.3```
```jhipster```

And got the error.

##### **Suggest a Fix**

Edit the file in /home/$USER/.nvm/versions/node/v18.16.1/lib/node_modules/generator-jhipster/node_modules/yeoman-environment/package.json and add this code into the "exports":

    "./lib/util/namespace": "./lib/util/namespace.js",

##### **JHipster Version(s)**

generator-jhipster@7.9.3

###### **NodeJS Versions(s)**

node v18.16.1

###### **Java Version(s)**

openjdk 11.0.12 2021-07-20
OpenJDK Runtime Environment 18.9 (build 11.0.12+7)
OpenJDK 65-Bit Server VM 18.9 (build 11.0.12+7, mixed mode)

**Comment by mraible** [comment]
JHipster 7.x only works with Node 16. If you use Node 16, it should work.

**Comment by mraible** [comment]
Please re-open if Node 16 doesn't work for you.

**Comment by omprakash-sit** [comment]
still issue persist, i am getting below error with following version
{
  npm: '10.7.0',
  node: '22.1.0',
}
npm list -g --depth=0
C:\Program Files\nodejs -> .\
+-- check-peer-dependencies@4.3.0
+-- corepack@0.28.0
+-- depcheck@1.4.7
+-- generator-jhipster@8.8.0
+-- install-peerdeps@3.0.3
`-- npm@10.7.0

**Error:**
> jhipster
INFO! Using bundled JHipster
node:internal/modules/cjs/loader:640
      throw e;
      ^

Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './lib/util/namespace' is not defined by "exports" in C:\Users\OMPrakash\AppData\Roaming\npm\node_modules\generator-jhipster\node_modules\yeoman-environment\package.json
    at exportsNotFound (node:internal/modules/esm/resolve:303:10)
    at packageExportsResolve (node:internal/modules/esm/resolve:650:9)
    at resolveExports (node:internal/modules/cjs/loader:633:36)
    at Module._findPath (node:internal/modules/cjs/loader:723:31)
    at Module._resolveFilename (node:internal/modules/cjs/loader:1210:27)
    at Module._load (node:internal/modules/cjs/loader:1050:27)
    at Module.require (node:internal/modules/cjs/loader:1310:19)
    at require (node:internal/modules/helpers:179:18)
    at Object.<anonymous> (C:\Users\OMPrakash\AppData\Roaming\npm\node_modules\generator-jhipster\utils\blueprint.js:19:25)
    at Module._compile (node:internal/modules/cjs/loader:1480:14) {
  code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
}

Node.js v22.1.0
