### ISSUE TITLE
faker 8 faker.commerce.color broken

### ISSUE THREAD

**Issue by anothergoodguy** [jhipster/generator-jhipster#22876]
Tested after the fix in https://github.com/jhipster/generator-jhipster/pull/22865

Still Getting one `Warning` and One `Error``:

1. Warning: 

[@faker-js/faker]: faker.name is deprecated since v8.0 and will be removed in v10.0. Please use faker.person instead.

1. Error:

```
ERROR! An error occured while running jhipster:liquibase-changelogs#prepareFakeData
ERROR! ERROR! Invalid module method or definition: commerce.color
- faker.commerce.color is not a function
- faker.definitions.commerce.color is not an array
p [Error]: Invalid module method or definition: commerce.color
- faker.commerce.color is not a function
- faker.definitions.commerce.color is not an array
    at _.fake (file:///home/jhipster/generator-jhipster/node_modules/@faker-js/faker/dist/esm/chunk-2JBE4HP3.mjs:11:7179)
    at BootstrapApplicationBase.generateFakeDataForField (file:///home/jhipster/generator-jhipster/dist/generators/base-application/support/prepare-field.mjs:170:63)
    at field.generateFakeData (file:///home/jhipster/generator-jhipster/dist/generators/base-application/support/prepare-field.mjs:310:45)
    at file:///home/jhipster/generator-jhipster/dist/generators/liquibase-changelogs/generator.mjs:108:42
    at Array.forEach (<anonymous>)
    at DatabaseChangelogLiquibase.prepareFakeData (file:///home/jhipster/generator-jhipster/dist/generators/liquibase-changelogs/generator.mjs:91:28)
    at DatabaseChangelogLiquibase.executeTask (file:///home/jhipster/generator-jhipster/node_modules/yeoman-generator/dist/actions/lifecycle.js:240:26)
    at env.queueTask.once (file:///home/jhipster/generator-jhipster/node_modules/yeoman-generator/dist/actions/lifecycle.js:214:56)
    at runLoop.add.once (file:///home/jhipster/generator-jhipster/node_modules/yeoman-environment/dist/environment-base.js:383:23)
    at Immediate.<anonymous> (/home/jhipster/generator-jhipster/node_modules/grouped-queue/lib/subqueue.js:48:34)
    at process.processImmediate (node:internal/timers:476:21)
```
    
commenting the below snippet in `prepare-field.mjs` is allowing to proceed further, but that might not be the ideal solution.

```
else if (columnName === 'color') {
    fakeTemplate = 'commerce.color';
  }
```
Opening a new issue as the previous one was closed.

could you please advise on --skip-fake-data. not sure if it's considered during the initial steps or it's considered only during generation. It will be great if it can skip these validations also for running these experiments

_Originally posted by @anothergoodguy in https://github.com/jhipster/generator-jhipster/issues/22853#issuecomment-1636641128_

**Comment by anothergoodguy** [comment]
thanks!!
