### ISSUE TITLE
8.0.0-beta2 springboot vulnerabilities - need 6.0.3 but breaks LogoutConfigurer class

### ISSUE THREAD

**Issue by deammanickam** [jhipster/generator-jhipster#23099]
2023-08-08T12:23:14.235-04:00  WARN 33672 --- [  restartedMain] ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'org.springframework.security.config.annotation.web.configuration.WebSecurityConfiguration': Unsatisfied dependency expressed through method 'setFilterChains' parameter 0: Error creating bean with name 'filterChain' defined in class path resource [/config/SecurityConfiguration.class]: Failed to instantiate [org.springframework.security.web.SecurityFilterChain]: Factory method 'filterChain' threw exception with message: 'void org.springframework.security.web.authentication.logout.SecurityContextLogoutHandler.setSecurityContextRepository(org.springframework.security.web.context.SecurityContextRepository)' 
2023-08-08T12:23:14.245-04:00 DEBUG 33672 --- [nnection-reaper] s.a.a.h.a.i.conn.IdleConnectionReaper    : Reaper thread:

java.lang.InterruptedException: sleep interrupted
        at java.base/java.lang.Thread.sleep(Native Method)
        at software.amazon.awssdk.http.apache.internal.conn.IdleConnectionReaper$ReaperTask.run(IdleConnectionReaper.java:151)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)

2023-08-08T12:23:14.246-04:00 DEBUG 33672 --- [nnection-reaper] s.a.a.h.a.i.conn.IdleConnectionReaper    : Shutting down reaper thread.
2023-08-08T12:23:14.297-04:00 ERROR 33672 --- [  restartedMain] o.s.b.d.LoggingFailureAnalysisReporter   : ____***************************__APPLICATION FAILED TO START__***************************____Description:____An attempt was made to call a method that does not exist. The attempt was made from the followAdministrator@DESKTOP-702DO3U MINGW64

**Comment by mshima** [comment]
Please folllow issue instructions and provide info about system and reproduction steps.
