### ISSUE TITLE
Generator error on Node 20.6.0

### ISSUE THREAD

**Issue by deepu105** [jhipster/generator-jhipster#23417]
On Node.js v20.6.0 Generator is throwing the following error. This affects the v8.0.0-beta.3 and main branch

```
ERROR! An error occured while running jhipster:app#compose
ERROR! ERROR! common.register is not a function
TypeError: common.register is not a function
    at Object.<anonymous> (/home/deepu/.nvm/versions/node/v20.6.0/lib/node_modules/generator-jhipster/node_modules/shelljs/src/cat.js:4:8)
    at Module._compile (node:internal/modules/cjs/loader:1241:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1295:10)
    at Module.load (node:internal/modules/cjs/loader:1091:32)
    at Module._load (node:internal/modules/cjs/loader:938:12)
    at Module.require (node:internal/modules/cjs/loader:1115:19)
    at require (node:internal/modules/helpers:130:18)
    at /home/deepu/.nvm/versions/node/v20.6.0/lib/node_modules/generator-jhipster/node_modules/shelljs/shell.js:25:3
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (/home/deepu/.nvm/versions/node/v20.6.0/lib/node_modules/generator-jhipster/node_modules/shelljs/shell.js:24:23)
(node:341665) Warning: Accessing non-existent property 'register' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
ERROR! Unhandled promise rejection at:
FATAL! TypeError: common.register is not a function
```

**Comment by mshima** [comment]
Workaround is to downgrade to v20.5.1.

Dropping shelljs another error appears:
```
ERROR! ERROR! Cannot set property Argument of #<Object> which has only a getter
TypeError: Cannot set property Argument of #<Object> which has only a getter
    at Object.<anonymous> (/Users/mshima/git/generator-jhipster/node_modules/dockerfile-ast/lib/main.js:3:637)
    at Module._compile (node:internal/modules/cjs/loader:1241:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1295:10)
```

**Comment by deepu105** [comment]
Lets set the required nodejs version to < 20.6 until we have a solution
