### ISSUE TITLE
TypeError: Invalid Version: Node.js v18.17.1

### ISSUE THREAD

**Issue by TanvirRashidDon** [jhipster/generator-jhipster#23419]
##### **Overview of the issue**

I was trying to generate a project using `jhipster` command on my Ubuntu machine. Failed with below error 

Java version: openjdk version "17.0.8.1"
Node version: v18.17.1
```
/usr/lib/node_modules/generator-jhipster/node_modules/semver/classes/semver.js:38
      throw new TypeError(`Invalid Version: ${version}`)
      ^

TypeError: Invalid Version: 
    at new SemVer (/usr/lib/node_modules/generator-jhipster/node_modules/semver/classes/semver.js:38:13)
    at compare (/usr/lib/node_modules/generator-jhipster/node_modules/semver/functions/compare.js:3:32)
    at Object.lt (/usr/lib/node_modules/generator-jhipster/node_modules/semver/functions/lt.js:2:29)
    at /usr/lib/node_modules/generator-jhipster/generators/generator-base.js:2071:33
    at /usr/lib/node_modules/generator-jhipster/node_modules/shelljs/src/exec.js:139:9
    at ChildProcess.exithandler (node:child_process:411:7)
    at ChildProcess.emit (node:events:514:28)
    at maybeClose (node:internal/child_process:1091:16)
    at ChildProcess._handle.onexit (node:internal/child_process:302:5)

Node.js v18.17.1
```

##### **JHipster Version(s)**
7.9.4

##### **JHipster configuration**

Welcome to JHipster v7.9.4

Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**
cat: no such file or directory: .yo-rc.json

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

```
<details>
<summary>.yo-rc.json file</summary>
<pre>

</pre>
</details>


##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>


##### **Environment and Tools**

openjdk version "17.0.8.1" 2023-08-24
OpenJDK Runtime Environment (build 17.0.8.1+1-Ubuntu-0ubuntu122.04)
OpenJDK 64-Bit Server VM (build 17.0.8.1+1-Ubuntu-0ubuntu122.04, mixed mode, sharing)

git version 2.34.1

node: 
npm: 
Docker version 24.0.5, build ced0996


No change to package.json was detected. No package manager install will be executed.
Congratulations, JHipster execution is complete!
```

##### **Browsers and Operating System**
Ubuntu 22.04.3 LTS
- [ ✓] Checking this box is mandatory (this is just to show you read everything)

**Comment by mshima** [comment]
Probably a network error:
https://github.com/jhipster/generator-jhipster/blob/16c77fb9e0c024c6a87a0efc63954319ea882047/generators/generator-base.js#L2068

**Comment by TanvirRashidDon** [comment]
@mshima 
```
version@0.1.2 | Proprietary | deps: 1 | versions: 6
NodeJS package.json version number fetcher

dist
.tarball: https://registry.npmjs.org/version/-/version-0.1.2.tgz
.shasum: ab071b0e39c9a34e9308dd8cd7845795deeca70f
.integrity: sha512-pU32BxnlMpDnyR8SsRR8amiAmhBZQdTevjYFAMZ9W3eT2wWIJzfjKOH39O1eiCAW4brhyaXe3NpZNFpBAJR56Q==

dependencies:
request: 2.12.0 

maintainers:
- edwardhotchkiss <e@ingk.com>

dist-tags:
latest: 0.1.2  

published over a year ago by edwardhotchkiss <edwardhotchkiss@me.com>
```

**Comment by mshima** [comment]
So the output is different?
```
% npm show generator-jhipster version --fetch-retries 1 --fetch-retry-mintimeout 500 --fetch-retry-maxtimeout 500
7.9.4
```

**Comment by TanvirRashidDon** [comment]
Jhipster version in 7.9.4
```
npm show generator-jhipster version --fetch-retries 1 --fetch-retry-mintimeout 500 --fetch-retry-maxtimeout 500         ok 

7.9.4
```

**Comment by mshima** [comment]
For some reason your system seems to be returning `\n7.9.4` instead of `7.9.4`.
You can skip checks `jhipster --skip-checks`.

**Comment by TanvirRashidDon** [comment]
Thanks mate, it worked
