### ISSUE TITLE
i have this issue while jhipster and quarkus 

### ISSUE THREAD

**Issue by NIANG95** [jhipster/generator-jhipster#23428]
##### **Overview of the issue**

Caused by: org.h2.jdbc.JdbcSQLIntegrityConstraintViolationException: Violation d'index unique ou clé primaire: "PRIMARY KEY ON PUBLIC.CATEGORY(ID) ( /* key:1 */ CAST(1 AS BIGINT), 'Table')"
Unique index or primary key violation: "PRIMARY KEY ON PUBLIC.CATEGORY(ID) ( /* key:1 */ CAST(1 AS BIGINT), 'Table')"; SQL statement:
insert into category (id, libelle) values (default, ?) [23505-214]
        at org.h2.message.DbException.getJdbcSQLException(DbException.java:508)
        at org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
        at org.h2.message.DbException.get(DbException.java:223)
        at org.h2.message.DbException.get(DbException.java:199)
ngine.jdbc.internal.ResultSetReturnImpl.executeUpdate(ResultSetReturnImpl.java:197)
        ... 116 more

version jhipster 7.9.3

my jdl file : 

entity Product {
    designation String 
    prix Double 
    quantity Integer
}
 
entity Category {
    libelle String
}
 
relationship ManyToOne {
    Product{Category(libelle)} to Category
}
 

######### other need

Can somebody help me about how to desable faker in jhipster quarkus project i found that it is not the same procedure with jhipster springboot ?

Thanks

**Comment by deepu105** [comment]
@NIANG95 this is not enough information. Can you please follow the issue template and provide all the details asked for

**Comment by mshima** [comment]
Looks duplicated of https://github.com/jhipster/generator-jhipster/issues/23429.
- we need `jhipster info` output
- jhipster v7.9.3 may receive only critical updates.
- If you are using quarkus blueprint please post the issue at https://github.com/jhipster/generator-jhipster-quarkus/
