### ISSUE TITLE
Unique index or primary key violation

### ISSUE THREAD

**Issue by NIANG95** [jhipster/generator-jhipster#23429]
##### **Overview of the issue**

If i add a category in my application i show this error :

Caused by: org.h2.jdbc.JdbcSQLIntegrityConstraintViolationException: Violation d'index unique ou clé primaire: "PRIMARY KEY ON PUBLIC.CATEGORY(ID) ( /* key:1 / CAST(1 AS BIGINT), 'Table')"
Unique index or primary key violation: "PRIMARY KEY ON PUBLIC.CATEGORY(ID) ( / key:1 */ CAST(1 AS BIGINT), 'Table')"; SQL statement:
insert into category (id, libelle) values (default, ?) [23505-214]
at org.h2.message.DbException.getJdbcSQLException(DbException.java:508)
at org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
at org.h2.message.DbException.get(DbException.java:223)
at org.h2.message.DbException.get(DbException.java:199)
ngine.jdbc.internal.ResultSetReturnImpl.executeUpdate(ResultSetReturnImpl.java:197)
... 116 more
#######
my jdl file :

entity Product {
designation String
prix Double
quantity Integer
}

entity Category {
libelle String
}

relationship ManyToOne {
Product{Category(libelle)} to Category
}

##### **Motivation for or Use Case**

Because I am a beginner in jhipster and quarkus

##### **JHipster Version(s)**

7.9.3

##### **Browsers and Operating System**

- [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by mshima** [comment]
`jhipster info` output is required to reproduce.
jhipster v7.9.3 will not receive more development.
I will close for now.
If you post the required info we may have more idea.
