### ISSUE TITLE
HazelcastInstance with name already exist

### ISSUE THREAD

**Issue by lukasw44** [jhipster/generator-jhipster#2395]
Hi 

My system : 
- osx 
- maven 3.3.9
- java 1.8_65
And the jhipster configuration: 
```
{
  "generator-jhipster": {
    "baseName": "seed_www",
    "packageName": "it.seiton.seed",
    "packageFolder": "it/seiton/seed",
    "authenticationType": "oauth2",
    "hibernateCache": "hazelcast",
    "clusteredHttpSession": "hazelcast",
    "websocket": "spring-websocket",
    "databaseType": "sql",
    "devDatabaseType": "postgresql",
    "prodDatabaseType": "postgresql",
    "searchEngine": "elasticsearch",
    "useSass": true,
    "buildTool": "maven",
    "frontendBuilder": "grunt",
    "enableTranslation": true,
    "enableSocialSignIn": false,
    "rememberMeKey": "57c622ca20c10424df9daccdea7773e90b7e4539",
    "testFrameworks": [
      "gatling",
      "cucumber"
    ]
  }
}
```

there is a problem with hazelcast when i try run mvn clean install 

```
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
Caused by: org.springframework.context.ApplicationContextException: Unable to start embedded container; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'tomcatEmbeddedServletContainerFactory' defined in class path resource [org/springframework/boot/autoconfigure/web/EmbeddedServletContainerAutoConfiguration$EmbeddedTomcat.class]: Initialization of bean failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'webConfigurer': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: private com.hazelcast.core.HazelcastInstance it.seiton.seed.config.WebConfigurer.hazelcastInstance; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'hazelcastInstance' defined in class path resource [it/seiton/seed/config/CacheConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.hazelcast.core.HazelcastInstance]: Factory method 'hazelcastInstance' threw exception; nested exception is com.hazelcast.core.DuplicateInstanceNameException: HazelcastInstance with name 'seed_www' already exists!
        at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.onRefresh(EmbeddedWebApplicationContext.java:133)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:531)

```

**Comment by pascalgrimaud** [comment]
Just have a fast look.
Same issue : https://github.com/jhipster/generator-jhipster/issues/2228 with the cucumber order.
It seems that the PR https://github.com/jhipster/generator-jhipster/pull/2275/ resolved gradle only.

**Comment by jdubois** [comment]
Corrected by https://github.com/jhipster/generator-jhipster/commit/1084e4c2253a44cad597ab23774bf1f7dcc97e83
