### ISSUE TITLE
@Mapper produces BeanCreationException

### ISSUE THREAD

**Issue by arushijain45** [jhipster/generator-jhipster#2399]
I have created an application using JHipster with DTO enabled, mongo database, build system: gradle.
Without any changes in any of configuration file, I ran the application in spring.
I got following issue:

[WARN] org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext - Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'userProfileResource': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: private com.sample.jhipster.web.rest.mapper.UserProfileMapper com.sample.jhipster.web.rest.UserProfileResource.userProfileMapper; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type [com.sample.jhipster.web.rest.mapper.UserProfileMapper] found for dependency: expected at least 1 bean which qualifies as autowire candidate for this dependency. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true)}
[INFO] com.sample.jhipster.config.CacheConfiguration - Closing Cache Manager
[WARN] org.apache.catalina.loader.WebappClassLoaderBase - The web application [ROOT] appears to have started a thread named [cluster-1-localhost:27017] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 sun.misc.Unsafe.park(Native Method)
 java.util.concurrent.locks.LockSupport.parkNanos(Unknown Source)
 java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(Unknown Source)
 com.mongodb.ServerMonitor$ServerMonitorRunnable.waitForSignalOrTimeout(ServerMonitor.java:177)
 com.mongodb.ServerMonitor$ServerMonitorRunnable.waitForNext(ServerMonitor.java:158)
 com.mongodb.ServerMonitor$ServerMonitorRunnable.run(ServerMonitor.java:124)
 java.lang.Thread.run(Unknown Source)
[WARN] org.apache.catalina.loader.WebappClassLoaderBase - The web application [ROOT] appears to have started a thread named [MongoCleaner1930932235] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 java.lang.Thread.sleep(Native Method)
 com.mongodb.Mongo$CursorCleanerThread.run(Mongo.java:796)
[ERROR] org.springframework.boot.SpringApplication - Application startup failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'userProfileResource': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: private com.sample.jhipster.web.rest.mapper.UserProfileMapper com.sample.jhipster.web.rest.UserProfileResource.userProfileMapper; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type [com.sample.jhipster.web.rest.mapper.UserProfileMapper] found for dependency: expected at least 1 bean which qualifies as autowire candidate for this dependency. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true)}
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:334) ~[spring-beans-4.2.3.RELEASE.jar:4.2.3.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1214) ~[spring-beans-4.2.3.RELEASE.jar:4.2.3.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:543) ~[spring-beans-4.2.3.RELEASE.jar:4.2.3.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482) ~[spring-beans-4.2.3.RELEASE.jar:4.2.3.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306) ~[spring-beans-4.2.3.RELEASE.jar:4.2.3.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230) ~[spring-beans-4.2.3.RELEASE.jar:4.2.3.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302) ~[spring-beans-4.2.3.RELEASE.jar:4.2.3.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197) ~[spring-beans-4.2.3.RELEASE.jar:4.2.3.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:772) ~[spring-beans-4.2.3.RELEASE.jar:4.2.3.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:838) ~[spring-context-4.2.3.RELEASE.jar:4.2.3.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:537) ~[spring-context-4.2.3.RELEASE.jar:4.2.3.RELEASE]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:118) ~[spring-boot-1.3.0.RELEASE.jar:1.3.0.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:752) ~[spring-boot-1.3.0.RELEASE.jar:1.3.0.RELEASE]
	at org.springframework.boot.SpringApplication.doRun(SpringApplication.java:347) ~[spring-boot-1.3.0.RELEASE.jar:1.3.0.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:295) ~[spring-boot-1.3.0.RELEASE.jar:1.3.0.RELEASE]
	at com.sample.jhipster.Application.main(Application.java:74) [bin/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_65]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_65]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_65]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[na:1.8.0_65]
	at org.springframework.boot.devtools.restart.RestartLauncher.run(RestartLauncher.java:49) [spring-boot-devtools-1.3.0.RELEASE.jar:1.3.0.RELEASE]
Caused by: org.springframework.beans.factory.BeanCreationException: Could not autowire field: private com.sample.jhipster.web.rest.mapper.UserProfileMapper com.sample.jhipster.web.rest.UserProfileResource.userProfileMapper; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type [com.sample.jhipster.web.rest.mapper.UserProfileMapper] found for dependency: expected at least 1 bean which qualifies as autowire candidate for this dependency. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true)}
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:573) ~[spring-beans-4.2.3.RELEASE.jar:4.2.3.RELEASE]
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:88) ~[spring-beans-4.2.3.RELEASE.jar:4.2.3.RELEASE]
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:331) ~[spring-beans-4.2.3.RELEASE.jar:4.2.3.RELEASE]
	... 20 common frames omitted
Caused by: org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type [com.sample.jhipster.web.rest.mapper.UserProfileMapper] found for dependency: expected at least 1 bean which qualifies as autowire candidate for this dependency. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true)}
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.raiseNoSuchBeanDefinitionException(DefaultListableBeanFactory.java:1373) ~[spring-beans-4.2.3.RELEASE.jar:4.2.3.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1119) ~[spring-beans-4.2.3.RELEASE.jar:4.2.3.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1014) ~[spring-beans-4.2.3.RELEASE.jar:4.2.3.RELEASE]
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:545) ~[spring-beans-4.2.3.RELEASE.jar:4.2.3.RELEASE]
	... 22 common frames omitted

I could not find solution for this error. Any suggestion would be highly appreciated.

**Comment by gmarziou** [comment]
Looks like the mapstruct annotation processor did not generate UserProfileMapperImpl.java, could it be an issue with gradle only? Normally `gradlew compile` should execute mapstruct.gradle task which generates the mappers.

**Comment by atomfrede** [comment]
I can't reproduce it. The mapstrucht dto mapper is generated just find, both running ``gradlew bootRun`` and directly via ``gradlew compileJava`` My config:
```
{
  "generator-jhipster": {
    "baseName": "jhipster",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "authenticationType": "session",
    "hibernateCache": "no",
    "clusteredHttpSession": "no",
    "websocket": "no",
    "databaseType": "mongodb",
    "devDatabaseType": "mongodb",
    "prodDatabaseType": "mongodb",
    "searchEngine": "no",
    "useSass": false,
    "buildTool": "gradle",
    "frontendBuilder": "grunt",
    "enableTranslation": true,
    "enableSocialSignIn": false,
    "rememberMeKey": "433a8f965624da553817e26dc6f1c425642694b5",
    "testFrameworks": [
      "gatling"
    ]
  }
}
```

and I've created a simple entity:

```
{
    "relationships": [],
    "fields": [
        {
            "fieldId": 1,
            "fieldName": "name",
            "fieldType": "String"
        }
    ],
    "dto": "mapstruct",
    "pagination": "no"
}
```

**Comment by jdubois** [comment]
This is probably an IDE misconfiguration (I'm not saying this is easy to configure! See http://jhipster.github.io/using_dtos.html ), as @atomfrede couldn't reproduce it with Mvn/Gradle.

**Comment by nnimmaga** [comment]
We have been facing this issue - but sporadically.

It just throws out as we are not able to fix this issue.
We would just re generate the war & just hope/pray that this doesn't appear.

[WARN] org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext - Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'xxxxxxResource': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: private com.xxxx.web.rest.mapper.xxxxxxMapper com.xxxx.web.rest.xxxxxx.xxxxxxMapper; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type [com.waygum.mbaas.web.rest.mapper.xxxxxxxMapper] found for dependency: expected at least 1 bean which qualifies as autowire candidate for this dependency. Dependency annotations: {@javax.inject.Inject()}

**Comment by gmarziou** [comment]
Please don't comment an old closed issue and open a new one with required details.

**Comment by felipebcs** [comment]
If anyone land on this page looking for a possible solution:
I had a similar problem, but using Maven and Eclipse. At the end I realized that I hadn't read well the bottom of the "Configuring your IDE" page, which says about MapStruct, but I also had to add the _taget/generated-sources_ folder to my build path (as instructed on http://g00glen00b.be/mapstruct/ ).

**Comment by gmarziou** [comment]
Good point @felipebcs, if you think that doc could be improved  to make it more visible , don't hesitate to submit a pull request on https://github.com/jhipster/jhipster.github.io

**Comment by jdubois** [comment]
Yes, this part is so annoying.... That's the main downside of MaoStruct,
yet annotation postprocessors are supposed to be standard now!

Le 20 nov. 2016 11:21 AM, "Gaël Marziou" <notifications@github.com> a
écrit :

**Comment by syamsathyan** [comment]
Had the same issue (tried the whole day to apply all type of profile / annotation processing in Idea) Finally this worked ..
---------------------
I got rid of Mapping annotations.
Converted all Mappers to @Components.
Changed the Mapper interfaces to classes, and all methods to be public.
Rest of the JH Code worked like a charm.
/** 

teamRepository.findAllWithEagerRelationships().stream()
            .map(teamMapper::teamToTeamDTO)
            .collect(Collectors.toCollection(LinkedList::new));
**/

@jdubois - its worth thinking of an option to offer Bean based mappers (instead of Mapstruct), you get the ugly pojo mappings in a set of Classes, but without the annotation processors. Annotation processing did not work even with the lated Idea, so this was the only way i could make it work.

**Comment by ruddell** [comment]
@syamsathyan Please open a new ticket if you have issues or feature requests.  This is probably unrelated as it's from two years ago.

There was a recent change with gradle apps that causes this error, the fix is in a Pull Request under review.  Several people have reported success with the changes here:  https://github.com/jhipster/generator-jhipster/pull/6172/files
