### ISSUE TITLE
`jhipster upgrade` doesn't work on 21-Points Health project

### ISSUE THREAD

**Issue by mraible** [jhipster/generator-jhipster#24085]
##### **Overview of the issue**

I tried to upgrade [21-points](https://github.com/mraible/21-points) to JHipster 8.0.0 today.

##### **Motivation for or Use Case**

It'd be sweet if I could upgrade a JHipster 7 app to JHipster 8. 

##### **Reproduce the error**

After switching to Node 16, I ran:

```
git checkout -b jhipster-8
jhipster upgrade
```

The error is:

```
WARNING! Since JHipster v8, the jhipster command will not use the locally installed generator-jhipster.
    If you want to execute the locally installed generator-jhipster, run: npx jhipster

        ██╗ ██╗   ██╗ ████████╗ ███████╗   ██████╗ ████████╗ ████████╗ ███████╗
        ██║ ██║   ██║ ╚══██╔══╝ ██╔═══██╗ ██╔════╝ ╚══██╔══╝ ██╔═════╝ ██╔═══██╗
        ██║ ████████║    ██║    ███████╔╝ ╚█████╗     ██║    ██████╗   ███████╔╝
  ██╗   ██║ ██╔═══██║    ██║    ██╔════╝   ╚═══██╗    ██║    ██╔═══╝   ██╔══██║
  ╚██████╔╝ ██║   ██║ ████████╗ ██║       ██████╔╝    ██║    ████████╗ ██║  ╚██╗
   ╚═════╝  ╚═╝   ╚═╝ ╚═══════╝ ╚═╝       ╚═════╝     ╚═╝    ╚═══════╝ ╚═╝   ╚═╝
                            https://www.jhipster.tech
Welcome to JHipster v8.0.0

Welcome to the JHipster Upgrade Sub-Generator
This will upgrade your current application codebase to the latest JHipster version
WARNING! No blueprints detected, skipping check of last blueprint version
INFO! Looking for latest generator-jhipster version...
✔ New generator-jhipster version found: 8.0.0
✔ Git repository detected
✔ Created branch jhipster_upgrade
INFO! Removing /Users/mraible/dev/21-points/.browserslistrc
ERROR! An error occured while running jhipster:upgrade#prepareUpgradeBranch
INFO! Removing /Users/mraible/dev/21-points/.devcontainer
INFO! Removing /Users/mraible/dev/21-points/.editorconfig
INFO! Removing /Users/mraible/dev/21-points/.eslintignore
INFO! Removing /Users/mraible/dev/21-points/.eslintrc.json
INFO! Removing /Users/mraible/dev/21-points/.gitattributes
INFO! Removing /Users/mraible/dev/21-points/.github
INFO! Removing /Users/mraible/dev/21-points/.gitignore
INFO! Removing /Users/mraible/dev/21-points/.husky
INFO! Removing /Users/mraible/dev/21-points/.lintstagedrc.js
INFO! Removing /Users/mraible/dev/21-points/.prettierignore
INFO! Removing /Users/mraible/dev/21-points/.prettierrc
INFO! Removing /Users/mraible/dev/21-points/.yo-rc-global.json
INFO! Removing /Users/mraible/dev/21-points/Jenkinsfile
INFO! Removing /Users/mraible/dev/21-points/Procfile
INFO! Removing /Users/mraible/dev/21-points/README.md
INFO! Removing /Users/mraible/dev/21-points/SECURITY.md
INFO! Removing /Users/mraible/dev/21-points/UPGRADE.adoc
INFO! Removing /Users/mraible/dev/21-points/angular.json
INFO! Removing /Users/mraible/dev/21-points/build.gradle
INFO! Removing /Users/mraible/dev/21-points/checkstyle.xml
INFO! Removing /Users/mraible/dev/21-points/cypress.config.ts
INFO! Removing /Users/mraible/dev/21-points/gradle
INFO! Removing /Users/mraible/dev/21-points/gradle.properties
INFO! Removing /Users/mraible/dev/21-points/gradlew
INFO! Removing /Users/mraible/dev/21-points/gradlew.bat
INFO! Removing /Users/mraible/dev/21-points/heroku-deploy.sh
INFO! Removing /Users/mraible/dev/21-points/jest.conf.js
INFO! Removing /Users/mraible/dev/21-points/newrelic-agent.jar
INFO! Removing /Users/mraible/dev/21-points/newrelic.yml
INFO! Removing /Users/mraible/dev/21-points/ngsw-config.json
INFO! Removing /Users/mraible/dev/21-points/npmw
INFO! Removing /Users/mraible/dev/21-points/npmw.cmd
INFO! Removing /Users/mraible/dev/21-points/package-lock.json
INFO! Removing /Users/mraible/dev/21-points/package.json
INFO! Removing /Users/mraible/dev/21-points/settings.gradle
INFO! Removing /Users/mraible/dev/21-points/sonar-project.properties
INFO! Removing /Users/mraible/dev/21-points/src
INFO! Removing /Users/mraible/dev/21-points/system.properties
INFO! Removing /Users/mraible/dev/21-points/tsconfig.app.json
INFO! Removing /Users/mraible/dev/21-points/tsconfig.json
INFO! Removing /Users/mraible/dev/21-points/tsconfig.spec.json
INFO! Removing /Users/mraible/dev/21-points/webpack
✔ Cleaned up project directory
INFO! Installing generator-jhipster 7.9.3 locally
INFO! npm install generator-jhipster@7.9.3 --save-dev --no-package-lock --ignore-scripts --force
✔ Installed generator-jhipster@7.9.3
INFO! Skipping local blueprint installation since no blueprint has been detected
INFO! Regenerating application with JHipster 7.9.3...
INFO! "/Users/mraible/dev/21-points/node_modules/.bin/jhipster" --with-entities --force --skip-install --skip-git --ignore-errors --no-insight --skip-checks
ERROR! ERROR! Command failed with ENOENT: "/Users/mraible/dev/21-points/node_modules/.bin/jhipster" --with-entities --force --skip-install --skip-git --ignore-errors --no-insight --skip-checks
spawnSync "/Users/mraible/dev/21-points/node_modules/.bin/jhipster" ENOENT
Error: Command failed with ENOENT: "/Users/mraible/dev/21-points/node_modules/.bin/jhipster" --with-entities --force --skip-install --skip-git --ignore-errors --no-insight --skip-checks
spawnSync "/Users/mraible/dev/21-points/node_modules/.bin/jhipster" ENOENT
    at Object.spawnSync (node:internal/child_process:1119:20)
    at Object.spawnSync (node:child_process:847:24)
    at execaSync (file:///Users/mraible/.nvm/versions/node/v16.20.2/lib/node_modules/generator-jhipster/node_modules/execa/index.js:181:25)
    at execaCommandSync (file:///Users/mraible/.nvm/versions/node/v16.20.2/lib/node_modules/generator-jhipster/node_modules/execa/index.js:276:9)
    at UpgradeGenerator.spawnCommandSync (file:///Users/mraible/.nvm/versions/node/v16.20.2/lib/node_modules/generator-jhipster/node_modules/yeoman-generator/dist/actions/spawn-command.js:24:16)
    at UpgradeGenerator._generate (file:///Users/mraible/.nvm/versions/node/v16.20.2/lib/node_modules/generator-jhipster/dist/generators/upgrade/generator.mjs:124:29)
    at UpgradeGenerator._regenerate (file:///Users/mraible/.nvm/versions/node/v16.20.2/lib/node_modules/generator-jhipster/dist/generators/upgrade/generator.mjs:142:14)
    at UpgradeGenerator.prepareUpgradeBranch (file:///Users/mraible/.nvm/versions/node/v16.20.2/lib/node_modules/generator-jhipster/dist/generators/upgrade/generator.mjs:325:26)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async UpgradeGenerator.executeTask (file:///Users/mraible/.nvm/versions/node/v16.20.2/lib/node_modules/generator-jhipster/node_modules/yeoman-generator/dist/actions/lifecycle.js:244:13) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawnSync "/Users/mraible/dev/21-points/node_modules/.bin/jhipster"',
  path: '"/Users/mraible/dev/21-points/node_modules/.bin/jhipster"',
  spawnargs: [
    '--with-entities',
    '--force',
    '--skip-install',
    '--skip-git',
    '--ignore-errors',
    '--no-insight',
    '--skip-checks'
  ],
  originalMessage: 'spawnSync "/Users/mraible/dev/21-points/node_modules/.bin/jhipster" ENOENT',
  shortMessage: 'Command failed with ENOENT: "/Users/mraible/dev/21-points/node_modules/.bin/jhipster" --with-entities --force --skip-install --skip-git --ignore-errors --no-insight --skip-checks\n' +
    'spawnSync "/Users/mraible/dev/21-points/node_modules/.bin/jhipster" ENOENT',
  command: '"/Users/mraible/dev/21-points/node_modules/.bin/jhipster" --with-entities --force --skip-install --skip-git --ignore-errors --no-insight --skip-checks',
  escapedCommand: '"\\"/Users/mraible/dev/21-points/node_modules/.bin/jhipster\\"" --with-entities --force --skip-install --skip-git --ignore-errors --no-insight --skip-checks',
  exitCode: undefined,
  signal: undefined,
  signalDescription: undefined,
  stdout: '',
  stderr: '',
  cwd: '/Users/mraible/dev/21-points',
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}
Execution time: 7 s.
```

##### **JHipster Version(s)**

8.0.0

**Comment by mraible** [comment]
$500 to make `jhipster upgrade` work between v7 and v8.

**Comment by mshima** [comment]
I will extract upgrade into a new blueprint.

**Comment by mshima** [comment]
@mraible https://github.com/mshima/generator-jhipster-migrate

**Comment by DanielFran** [comment]
@mshima Why we should extract it as an external blueprint?
I believe it should be part of the project as a generator...

**Comment by mshima** [comment]
@DanielFran this was proposed at https://github.com/jhipster/generator-jhipster/issues/19779.
Not definitively a must, but something to consider.
Upgrade bugs are spotted post release, so it’s needed to wait for another release.
And as far as I remember almost every release have upgrade bugs.

We definitely should stabilize upgrade support as a blueprint and consider to move back later.
We can keep upgrade generator in sync with migrate implementation. It makes sense.

**Comment by mraible** [comment]
I tried @mshima's [migrate blueprint](https://github.com/mshima/generator-jhipster-migrate) on 21-Points Health. The following error happens:

```
===================== JHipster migrate =====================

Welcome to the JHipster Migrate Sub-Generator
This will help migrate your current application codebase
✔ created branch jhipster_migrate_source
✔ cleaned up project directory
⠋ regenerating source application Running local npx jhipster --force --skip-install --skip-git --ignore-errors --no-insight --skip-checks --with-entities --prefer-global
✖ successfully regenerated source application using JHipster current
ERROR! An error occured while running jhipster-migrate:migrate#prepareMigrateBranch
ERROR! ERROR! Command failed with exit code 1: npx jhipster --force --skip-install --skip-git --ignore-errors --no-insight --skip-checks --with-entities --prefer-global
Error: Command failed with exit code 1: npx jhipster --force --skip-install --skip-git --ignore-errors --no-insight --skip-checks --with-entities --prefer-global
    at makeError (file:///Users/mraible/dev/generator-jhipster-migrate/node_modules/yeoman-generator/node_modules/execa/lib/error.js:60:11)
    at handlePromise (file:///Users/mraible/dev/generator-jhipster-migrate/node_modules/yeoman-generator/node_modules/execa/index.js:124:26)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async default.regenerate (file:///Users/mraible/dev/generator-jhipster-migrate/generators/migrate/generator.js:519:9)
    at async default.prepareMigrateBranch (file:///Users/mraible/dev/generator-jhipster-migrate/generators/migrate/generator.js:312:11)
    at async default.executeTask (file:///Users/mraible/dev/generator-jhipster-migrate/node_modules/yeoman-generator/dist/actions/lifecycle.js:244:13)
    at async runLoop.add.once (file:///Users/mraible/dev/generator-jhipster-migrate/node_modules/yeoman-environment/dist/environment-base.js:381:17) {
  shortMessage: 'Command failed with exit code 1: npx jhipster --force --skip-install --skip-git --ignore-errors --no-insight --skip-checks --with-entities --prefer-global',
  command: 'npx jhipster --force --skip-install --skip-git --ignore-errors --no-insight --skip-checks --with-entities --prefer-global',
  escapedCommand: 'npx jhipster --force --skip-install --skip-git --ignore-errors --no-insight --skip-checks --with-entities --prefer-global',
  exitCode: 1,
  signal: undefined,
  signalDescription: undefined,
  stdout: undefined,
  stderr: undefined,
  cwd: '/Users/mraible/dev/21-points',
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}
```

I'm using Node v18.18.2.

**Comment by mraible** [comment]
Using Node 16, the results seem promising!

```
===================== JHipster migrate =====================

Welcome to the JHipster Migrate Sub-Generator
This will help migrate your current application codebase
✔ created branch jhipster_migrate_source
✔ cleaned up project directory
⠋ regenerating source application Running local npx jhipster --force --skip-install --skip-git --ignore-errors --no-insight --skip-checks --with-entities --prefer-global
✔ successfully regenerated source application using JHipster current
✔ applying prettier to source application
✔ applying prettier to actual application
✔ merged jhipster_migrate_source into main
✔ cleaned up project directory
✔ applying prettier to actual application
⠋ regenerating target application Running bundled /Users/mraible/dev/generator-jhipster-migrate/cli/cli.cjs app --force --skip-install --skip-git --ignore-errors --no-insight --skip-checks
✔ successfully regenerated target application using JHipster bundled
⠏ Merging changes back to mainERROR! Error creating migration merge
CONFLICTS: .gitignore:content, README.md:content, build.gradle:content, cypress.config.ts:content, package.json:content, src/main/java/org/jhipster/health/config/ApplicationProperties.java:content, src/main/java/org/jhipster/health/config/SecurityConfiguration.java:content, src/main/java/org/jhipster/health/repository/search/BloodPressureSearchRepository.java:content, src/main/java/org/jhipster/health/repository/search/PointsSearchRepository.java:content, src/main/java/org/jhipster/health/repository/search/PreferencesSearchRepository.java:content, src/main/java/org/jhipster/health/repository/search/WeightSearchRepository.java:content, src/main/java/org/jhipster/health/service/ElasticsearchIndexService.java:modify/delete, src/main/java/org/jhipster/health/web/rest/BloodPressureResource.java:content, src/main/java/org/jhipster/health/web/rest/ElasticsearchIndexResource.java:modify/delete, src/main/java/org/jhipster/health/web/rest/PointsResource.java:content, src/main/java/org/jhipster/health/web/rest/PreferencesResource.java:content, src/main/java/org/jhipster/health/web/rest/UserResource.java:content, src/main/java/org/jhipster/health/web/rest/WeightResource.java:content, src/main/resources/config/application.yml:content, src/main/webapp/app/app.module.ts:content, src/main/webapp/app/entities/blood-pressure/list/blood-pressure.component.html:content, src/main/webapp/app/entities/blood-pressure/list/blood-pressure.component.ts:content, src/main/webapp/app/entities/blood-pressure/update/blood-pressure-update.component.html:content, src/main/webapp/app/entities/entity-navbar-items.ts:content, src/main/webapp/app/entities/points/list/points.component.html:content, src/main/webapp/app/entities/points/update/points-update.component.html:content, src/main/webapp/app/entities/preferences/list/preferences.component.html:content, src/main/webapp/app/entities/preferences/update/preferences-update.component.html:content, src/main/webapp/app/entities/weight/list/weight.component.html:content, src/main/webapp/app/entities/weight/list/weight.component.ts:content, src/main/webapp/app/entities/weight/update/weight-update.component.html:content, src/main/webapp/app/home/home.component.html:content, src/main/webapp/app/home/home.component.spec.ts:content, src/main/webapp/app/home/home.module.ts:modify/delete, src/main/webapp/app/home/home.route.ts:modify/delete, src/main/webapp/app/layouts/main/main.component.spec.ts:content, src/main/webapp/app/layouts/main/main.component.ts:content, src/main/webapp/app/layouts/navbar/navbar.component.scss:content, src/main/webapp/content/scss/_bootstrap-variables.scss:content, src/main/webapp/content/scss/global.scss:content, src/main/webapp/i18n/fr/global.json:content, src/main/webapp/index.html:content, src/test/java/org/jhipster/health/web/rest/PointsResourceIT.java:content, src/test/javascript/cypress/e2e/entity/points.cy.ts:content, src/test/javascript/cypress/e2e/entity/preferences.cy.ts:content, src/test/javascript/cypress/plugins/index.ts:content, src/test/resources/logback.xml:content
✖ CONFLICTS: .gitignore:content, README.md:content, build.gradle:content, cypress.config.ts:content, package.json:content, src/main/java/org/jhipster/health/config/ApplicationProperties.java:content, src/main/java/org/jhipster/health/config/SecurityConfiguration.java:content, src/main/java/org/jhipster/health/repository/search/BloodPressureSearchRepository.java:content, src/main/java/org/jhipster/health/repository/search/PointsSearchRepository.java:content, src/main/java/org/jhipster/health/repository/search/PreferencesSearchRepository.java:content, src/main/java/org/jhipster/health/repository/search/WeightSearchRepository.java:content, src/main/java/org/jhipster/health/service/ElasticsearchIndexService.java:modify/delete, src/main/java/org/jhipster/health/web/rest/BloodPressureResource.java:content, src/main/java/org/jhipster/health/web/rest/ElasticsearchIndexResource.java:modify/delete, src/main/java/org/jhipster/health/web/rest/PointsResource.java:content, src/main/java/org/jhipster/health/web/rest/PreferencesResource.java:content, src/main/java/org/jhipster/health/web/rest/UserResource.java:content, src/main/java/org/jhipster/health/web/rest/WeightResource.java:content, src/main/resources/config/application.yml:content, src/main/webapp/app/app.module.ts:content, src/main/webapp/app/entities/blood-pressure/list/blood-pressure.component.html:content, src/main/webapp/app/entities/blood-pressure/list/blood-pressure.component.ts:content, src/main/webapp/app/entities/blood-pressure/update/blood-pressure-update.component.html:content, src/main/webapp/app/entities/entity-navbar-items.ts:content, src/main/webapp/app/entities/points/list/points.component.html:content, src/main/webapp/app/entities/points/update/points-update.component.html:content, src/main/webapp/app/entities/preferences/list/preferences.component.html:content, src/main/webapp/app/entities/preferences/update/preferences-update.component.html:content, src/main/webapp/app/entities/weight/list/weight.component.html:content, src/main/webapp/app/entities/weight/list/weight.component.ts:content, src/main/webapp/app/entities/weight/update/weight-update.component.html:content, src/main/webapp/app/home/home.component.html:content, src/main/webapp/app/home/home.component.spec.ts:content, src/main/webapp/app/home/home.module.ts:modify/delete, src/main/webapp/app/home/home.route.ts:modify/delete, src/main/webapp/app/layouts/main/main.component.spec.ts:content, src/main/webapp/app/layouts/main/main.component.ts:content, src/main/webapp/app/layouts/navbar/navbar.component.scss:content, src/main/webapp/content/scss/_bootstrap-variables.scss:content, src/main/webapp/content/scss/global.scss:content, src/main/webapp/i18n/fr/global.json:content, src/main/webapp/index.html:content, src/test/java/org/jhipster/health/web/rest/PointsResourceIT.java:content, src/test/javascript/cypress/e2e/entity/points.cy.ts:content, src/test/javascript/cypress/e2e/entity/preferences.cy.ts:content, src/test/javascript/cypress/plugins/index.ts:content, src/test/resources/logback.xml:content
✔ applying multi-step templates
✔ prettier configuration files commited to disk
     info Multiple customCommitTask tasks found (/Users/mraible/dev/21-points#jhipster-migrate:migrate, jhipster:bootstrap). Using the first.
✔ migrated successfully.
WARNING! please fix conflicts listed below and commit!
.gitignore
README.md
build.gradle
cypress.config.ts
package.json
src/main/java/org/jhipster/health/config/ApplicationProperties.java
src/main/java/org/jhipster/health/config/SecurityConfiguration.java
src/main/java/org/jhipster/health/repository/search/BloodPressureSearchRepository.java
src/main/java/org/jhipster/health/repository/search/PointsSearchRepository.java
src/main/java/org/jhipster/health/repository/search/PreferencesSearchRepository.java
src/main/java/org/jhipster/health/repository/search/WeightSearchRepository.java
src/main/java/org/jhipster/health/service/ElasticsearchIndexService.java
src/main/java/org/jhipster/health/web/rest/BloodPressureResource.java
src/main/java/org/jhipster/health/web/rest/ElasticsearchIndexResource.java
src/main/java/org/jhipster/health/web/rest/PointsResource.java
src/main/java/org/jhipster/health/web/rest/PreferencesResource.java
src/main/java/org/jhipster/health/web/rest/UserResource.java
src/main/java/org/jhipster/health/web/rest/WeightResource.java
src/main/resources/config/application.yml
src/main/webapp/app/app.module.ts
src/main/webapp/app/entities/blood-pressure/list/blood-pressure.component.html
src/main/webapp/app/entities/blood-pressure/list/blood-pressure.component.ts
src/main/webapp/app/entities/blood-pressure/update/blood-pressure-update.component.html
src/main/webapp/app/entities/entity-navbar-items.ts
src/main/webapp/app/entities/points/list/points.component.html
src/main/webapp/app/entities/points/update/points-update.component.html
src/main/webapp/app/entities/preferences/list/preferences.component.html
src/main/webapp/app/entities/preferences/update/preferences-update.component.html
src/main/webapp/app/entities/weight/list/weight.component.html
src/main/webapp/app/entities/weight/list/weight.component.ts
src/main/webapp/app/entities/weight/update/weight-update.component.html
src/main/webapp/app/home/home.component.html
src/main/webapp/app/home/home.component.spec.ts
src/main/webapp/app/home/home.module.ts
src/main/webapp/app/home/home.route.ts
src/main/webapp/app/layouts/main/main.component.spec.ts
src/main/webapp/app/layouts/main/main.component.ts
src/main/webapp/app/layouts/navbar/navbar.component.scss
src/main/webapp/content/scss/_bootstrap-variables.scss
src/main/webapp/content/scss/global.scss
src/main/webapp/i18n/fr/global.json
src/main/webapp/index.html
src/test/java/org/jhipster/health/web/rest/PointsResourceIT.java
src/test/javascript/cypress/e2e/entity/points.cy.ts
src/test/javascript/cypress/e2e/entity/preferences.cy.ts
src/test/javascript/cypress/plugins/index.ts
src/test/resources/logback.xml


Congratulations, JHipster execution is complete!
If you find JHipster useful consider sponsoring the project https://www.jhipster.tech/sponsors/

Thanks for using JHipster!
Execution time: 54 s.
```

**Comment by mshima** [comment]
@DanielFran bounty claimed https://opencollective.com/generator-jhipster/expenses/187985.

**Comment by DanielFran** [comment]
@mshima approved
