### ISSUE TITLE
MySQLNonTransientConnectionException with MySQL 5.7.9

### ISSUE THREAD

**Issue by piedrahitac** [jhipster/generator-jhipster#2450]
* **Overview of the issue**

After I upgraded my project to version 2.25.0 and made changes to the database I started getting the following stack traces when deploying my application using the dev profile.

I believe it is important to note that I also upgraded my database server to MySQL 5.7.9. I was using the 5.6 branch previously with version 2.23.1 and 2.24.0 of JHipster without any issue.

I think JHipster isn't really responsible for this issue, but maybe someone can reproduce it and direct me towards a solution.

```
2015-12-06 21:05:08.173  WARN 12346 --- [ gms-Executor-1] com.zaxxer.hikari.proxy.ConnectionProxy  : HikariPool-0 - Connection null, created Dec 06, 21:05:06.698, last release 1472ms ago, REMOVED marked as broken because of SQLSTATE(08003), ErrorCode(0)

com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: No operations allowed after connection closed.
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.8.0_65]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[na:1.8.0_65]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.8.0_65]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422) ~[na:1.8.0_65]
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:404) ~[mysql-connector-java-5.1.37.jar:5.1.37]
	at com.mysql.jdbc.Util.getInstance(Util.java:387) ~[mysql-connector-java-5.1.37.jar:5.1.37]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:919) ~[mysql-connector-java-5.1.37.jar:5.1.37]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:898) ~[mysql-connector-java-5.1.37.jar:5.1.37]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:887) ~[mysql-connector-java-5.1.37.jar:5.1.37]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:862) ~[mysql-connector-java-5.1.37.jar:5.1.37]
	at com.mysql.jdbc.ConnectionImpl.throwConnectionClosedException(ConnectionImpl.java:1237) ~[mysql-connector-java-5.1.37.jar:5.1.37]
```

```
2015-12-06 21:05:08.180  WARN 12346 --- [ gms-Executor-1] liquibase                                : Failed to restore the auto commit to true
2015-12-06 21:05:08.182 ERROR 12346 --- [ gms-Executor-1] c.t.g.c.liquibase.AsyncSpringLiquibase   : Liquibase could not start correctly, your database is NOT ready: com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: No operations allowed after connection closed.

liquibase.exception.DatabaseException: com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: No operations allowed after connection closed.
	at liquibase.database.jvm.JdbcConnection.setAutoCommit(JdbcConnection.java:363) ~[liquibase-core-3.4.1.jar:na]
	at liquibase.database.AbstractJdbcDatabase.close(AbstractJdbcDatabase.java:1172) ~[liquibase-core-3.4.1.jar:na]
	at liquibase.integration.spring.SpringLiquibase.afterPropertiesSet(SpringLiquibase.java:400) ~[liquibase-core-3.4.1.jar:na]
	at com.tybasoft.gms.config.liquibase.AsyncSpringLiquibase.initDb(AsyncSpringLiquibase.java:63) ~[classes/:na]
	at com.tybasoft.gms.config.liquibase.AsyncSpringLiquibase.lambda$afterPropertiesSet$43(AsyncSpringLiquibase.java:49) ~[classes/:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_65]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_65]
	at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_65]
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: No operations allowed after connection closed.
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.8.0_65]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[na:1.8.0_65]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.8.0_65]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422) ~[na:1.8.0_65]
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:404) ~[mysql-connector-java-5.1.37.jar:5.1.37]
	at com.mysql.jdbc.Util.getInstance(Util.java:387) ~[mysql-connector-java-5.1.37.jar:5.1.37]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:919) ~[mysql-connector-java-5.1.37.jar:5.1.37]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:898) ~[mysql-connector-java-5.1.37.jar:5.1.37]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:887) ~[mysql-connector-java-5.1.37.jar:5.1.37]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:862) ~[mysql-connector-java-5.1.37.jar:5.1.37]
	at com.mysql.jdbc.ConnectionImpl.throwConnectionClosedException(ConnectionImpl.java:1237) ~[mysql-connector-java-5.1.37.jar:5.1.37]
	at com.mysql.jdbc.ConnectionImpl.checkClosed(ConnectionImpl.java:1232) ~[mysql-connector-java-5.1.37.jar:5.1.37]
	at com.mysql.jdbc.ConnectionImpl.setAutoCommit(ConnectionImpl.java:4832) ~[mysql-connector-java-5.1.37.jar:5.1.37]
	at com.zaxxer.hikari.proxy.ConnectionProxy.setAutoCommit(ConnectionProxy.java:334) ~[HikariCP-2.4.1.jar:na]
	at com.zaxxer.hikari.proxy.HikariConnectionProxy.setAutoCommit(HikariConnectionProxy.java) ~[HikariCP-2.4.1.jar:na]
	at liquibase.database.jvm.JdbcConnection.setAutoCommit(JdbcConnection.java:361) ~[liquibase-core-3.4.1.jar:na]
	... 7 common frames omitted
```

* **JHipster Version(s)** 

2.25.0

* **JHipster configuration, a `.yo-rc.json` file generated in the root folder** 

```
{
  "generator-jhipster": {
    "baseName": "myapp",
    "packageName": "com.myapp",
    "packageFolder": "com/myapp",
    "authenticationType": "oauth2",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": "no",
    "websocket": "no",
    "databaseType": "sql",
    "devDatabaseType": "mysql",
    "prodDatabaseType": "mysql",
    "searchEngine": "no",
    "useSass": true,
    "buildTool": "maven",
    "frontendBuilder": "grunt",
    "enableTranslation": true,
    "enableSocialSignIn": false,
    "rememberMeKey": "obscured",
    "testFrameworks": []
  }
}
```

* **Browsers and Operating System** 

Fedora 23 and MySQL 5.7.9. I believe the database version is important here.

* **Reproduce the error** 

I created a new application to test and it happened straight away most of the time, but creating 4 or 5 entities always reproduced the error for me.

* **Related issues** 

I found issue #305 to be very similar, but it is a little dated and didn't really provide me with a solution.

**Comment by jdubois** [comment]
Can you put a clear title to your issue?

**Comment by piedrahitac** [comment]
Sorry about that, that was a temporary title and forgot to change it... I changed it now...

**Comment by atomfrede** [comment]
Looks strange, as our docker compose containers also use MySQL 5.7.9

**Comment by pascalgrimaud** [comment]
Yes it's strange.

@piedrahitac : can you create a *new* application with jhipster 2.25.0, mysql in dev, mysql 5.7.9 and try to reproduce your error ? Then, try adding 4 or 5 entities like your initial application

Maybe, can you show us your entities in .jhipster directory ?

**Comment by piedrahitac** [comment]
It is very strange indeed... But after more testing I think it has something to do with my entities and their relationship with the User entity. The question is why it didn't happen before.

For example, create a new application with 2.25.0, MySQL in dev and MySQL 5.7.9 and then generate the following entity named Empresa:

```
{
    "relationships": [
        {
            "relationshipId": 1,
            "relationshipName": "user",
            "otherEntityName": "user",
            "relationshipType": "one-to-many",
            "otherEntityRelationshipName": "empresa"
        }
    ],
    "fields": [
        {
            "fieldId": 1,
            "fieldName": "nombre",
            "fieldType": "String",
            "fieldValidateRules": [
                "required",
                "minlength",
                "maxlength"
            ],
            "fieldValidateRulesMinlength": "4",
            "fieldValidateRulesMaxlength": "64"
        },
        {
            "fieldId": 2,
            "fieldName": "imagen",
            "fieldType": "String",
            "fieldValidateRules": [
                "minlength",
                "maxlength"
            ],
            "fieldValidateRulesMinlength": "4",
            "fieldValidateRulesMaxlength": "64"
        }
    ],
    "changelogDate": "20151109165902",
    "dto": "no",
    "pagination": "no"
}
```

If you run the application right away the exception will show up, but if you add the relationship to the User domain object as @ManyToOne annotated field, recreate the schema and run the application again, things will work just fine.

I didn't have a problem with this before, and probably this is the expected behavior now, the thing is that I have plenty of entities with different types of relationships to the User entity, but not all of them are mapped, so now I have to check each one and see if all those mapping are necessary.

**Comment by piedrahitac** [comment]
So today I created my entities from scratch and upgraded to MySQL 5.7.10 and the issue seems to have disappeared.
