### ISSUE TITLE
Cannot read properties of undefined (reading 'originalField')

### ISSUE THREAD

**Issue by rjbgaspar** [jhipster/generator-jhipster#24544]
##### **Reproduce the error**

Run `jhipster jdl wasp.jdl`

```
(...)
Welcome to JHipster v8.1.0

INFO! Generating jdls wasp.jdl
     info Generating 2 applications
 _______________________________________________________________________________________________________________

  Documentation for creating an application is at https://www.jhipster.tech/creating-an-app/

  Application files will be generated in folder: /Users/rjbgaspar/code/wasp4/jaguar
 _______________________________________________________________________________________________________________

 _______________________________________________________________________________________________________________

  Documentation for creating an application is at https://www.jhipster.tech/creating-an-app/

  Application files will be generated in folder: /Users/rjbgaspar/code/wasp4/wildcat
 _______________________________________________________________________________________________________________

     info Generating 2,048 bit RSA key pair and self-signed certificate (SHA256withRSA) with a validity of 99,999 days
     info 	for: CN=Java Hipster, OU=Development, O=com.gv.jaguar, L=, ST=, C=
     info KeyStore '/Users/rjbgaspar/code/wasp4/jaguar/src/main/resources/config/tls/keystore.p12' generated successfully.
     info Generating 2,048 bit RSA key pair and self-signed certificate (SHA256withRSA) with a validity of 99,999 days
     info 	for: CN=Java Hipster, OU=Development, O=com.gv.wildcat, L=, ST=, C=
     info KeyStore '/Users/rjbgaspar/code/wasp4/wildcat/src/main/resources/config/tls/keystore.p12' generated successfully.
ERROR! An error occured while running jhipster:server#writeServerFiles
ERROR! An error occured while running jhipster:workspaces#generateApplications
ERROR! ERROR! /Users/rjbgaspar/.nvm/versions/node/v20.10.0/lib/node_modules/generator-jhipster/dist/generators/server/templates/src/main/java/_package_/_entityPackage_/service/mapper/_entityClass_Mapper.java.ejs:21
    19| package <%= entityAbsolutePackage %>.service.mapper;
    20| 
 >> 21| <%_
    22|   const getOriginalField = field => field.originalField || field;
    23|   const uuidMapMethod = dtoReferences.some(reference => reference.valueReference && reference.valueReference.field && reference.valueReference.field.fieldTypeUUID);
    24|   const byteMapMethod = dtoReferences.some(reference => reference.valueReference && reference.valueReference.field && reference.valueReference.field.fieldTypeBytes);

Cannot read properties of undefined (reading 'originalField')
TypeError: /Users/rjbgaspar/.nvm/versions/node/v20.10.0/lib/node_modules/generator-jhipster/dist/generators/server/templates/src/main/java/_package_/_entityPackage_/service/mapper/_entityClass_Mapper.java.ejs:21
    19| package <%= entityAbsolutePackage %>.service.mapper;
    20| 
 >> 21| <%_
    22|   const getOriginalField = field => field.originalField || field;
    23|   const uuidMapMethod = dtoReferences.some(reference => reference.valueReference && reference.valueReference.field && reference.valueReference.field.fieldTypeUUID);
    24|   const byteMapMethod = dtoReferences.some(reference => reference.valueReference && reference.valueReference.field && reference.valueReference.field.fieldTypeBytes);

Cannot read properties of undefined (reading 'originalField')
    at getOriginalField ("/Users/rjbgaspar/.nvm/versions/node/v20.10.0/lib/node_modules/generator-jhipster/dist/generators/server/templates/src/main/java/_package_/_entityPackage_/service/mapper/_entityClass_Mapper.java.ejs":17:43)
    at eval ("/Users/rjbgaspar/.nvm/versions/node/v20.10.0/lib/node_modules/generator-jhipster/dist/generators/server/templates/src/main/java/_package_/_entityPackage_/service/mapper/_entityClass_Mapper.java.ejs":30:101)
    at Array.some (<anonymous>)
    at eval ("/Users/rjbgaspar/.nvm/versions/node/v20.10.0/lib/node_modules/generator-jhipster/dist/generators/server/templates/src/main/java/_package_/_entityPackage_/service/mapper/_entityClass_Mapper.java.ejs":30:56)
    at Array.forEach (<anonymous>)
    at JHipsterServerGenerator.eval ("/Users/rjbgaspar/.nvm/versions/node/v20.10.0/lib/node_modules/generator-jhipster/dist/generators/server/templates/src/main/java/_package_/_entityPackage_/service/mapper/_entityClass_Mapper.java.ejs":29:23)
    at _entityClass_Mapper.java (/Users/rjbgaspar/.nvm/versions/node/v20.10.0/lib/node_modules/generator-jhipster/node_modules/ejs/lib/ejs.js:703:17)
    at exports.render (/Users/rjbgaspar/.nvm/versions/node/v20.10.0/lib/node_modules/generator-jhipster/node_modules/ejs/lib/ejs.js:425:37)
    at render (file:///Users/rjbgaspar/.nvm/versions/node/v20.10.0/lib/node_modules/generator-jhipster/node_modules/mem-fs-editor/dist/util.js:62:16)
    at MemFsEditor._processTpl (file:///Users/rjbgaspar/.nvm/versions/node/v20.10.0/lib/node_modules/generator-jhipster/node_modules/mem-fs-editor/dist/actions/copy-tpl.js:6:12) {
  path: '/Users/rjbgaspar/.nvm/versions/node/v20.10.0/lib/node_modules/generator-jhipster/dist/generators/server/templates/src/main/java/_package_/_entityPackage_/service/mapper/_entityClass_Mapper.java.ejs'
}
✔ applying multi-step templates
✔ Git repository initialized.
   create jaguar/.prettierrc
   create jaguar/.prettierignore
✔ prettier configuration files committed to disk
✔ loading translations
✔ updating package.json dependencies versions
✔ prettifying sonar-project.properties
✔ adding package-info.java files
✔ translating vue application
✔ converting vue translations
   create jaguar/.editorconfig
   create jaguar/sonar-project.properties
   create jaguar/package.json
    force jaguar/.yo-rc.json
   create jaguar/.husky/pre-commit
   create jaguar/npmw
   create jaguar/.lintstagedrc.cjs
   create jaguar/npmw.cmd
   create jaguar/src/main/resources/banner.txt
   create jaguar/src/main/docker/jib/entrypoint.sh
(...)
```
The wildcat microservice is not correctly generated! 

Also, I noticed that if you re-enter the command `jhipster jdl wasp.jdl`, the scaffold will be generated, but not correctly. For instance, entities are not generated and frontend is created (applicationType is microservice).

##### **JHipster configuration**
```
jhipster version 8.1.0

openjdk version "17.0.2" 2022-01-18
OpenJDK Runtime Environment (build 17.0.2+8-86)
OpenJDK 64-Bit Server VM (build 17.0.2+8-86, mixed mode, sharing)

git version 2.39.3 (Apple Git-145)

node: v20.10.0
npm: 10.2.3
Docker version 24.0.2, build cb74dfc
```

The following JDL can be use to demonstrate the issue

  <details>
  <summary>JDL definitions</summary>
  <pre>
    application {
      config {
        baseName jaguar
        reactive true
        packageName com.gv.jaguar
        applicationType gateway
        authenticationType oauth2
        buildTool maven
        clientFramework vue
        prodDatabaseType mssql
        serviceDiscoveryType eureka
        serverPort 50080
      }
    }
    
    application {
      config {
        baseName wildcat
        reactive true
        packageName com.gv.wildcat
        applicationType microservice
        authenticationType oauth2
        buildTool maven
        databaseType sql
        devDatabaseType h2Disk
        prodDatabaseType mssql
        enableHibernateCache false
        serverPort 50082
        serviceDiscoveryType eureka
      }
      entities *
    }
    
    @dto(mapstruct)
    @service(serviceClass)
    @readOnly
    entity Employee(FUNC1) {
        /**
         * The employee number
         */
        @fieldNameAsDatabaseColumn(NFUNC)
        @Id number String required unique
        @fieldNameAsDatabaseColumn(NOME)
        name String required
    }
    
    @dto(mapstruct)
    @service(serviceClass)
    @readOnly
    entity Image(IMAGENS) {
        /**
         * The image type
         */
        @fieldNameAsDatabaseColumn(TIPO)
        type Integer
        /**
         * The image code
         */
        @fieldNameAsDatabaseColumn(CODIGO)
        @Id code String required
        /**
         * The image type
         */
        @fieldNameAsDatabaseColumn(IMAGEM)
        image ImageBlob
    }
    relationship OneToOne {
        @Id Employee{Image required} to Image
    }
    
    @dto(mapstruct)
    @service(serviceClass)
    @readOnly
    entity CostCenter {
        @fieldNameAsDatabaseColumn(COD)
        @Id id String required
        @fieldNameAsDatabaseColumn(DESCR)
        description String
        @fieldNameAsDatabaseColumn(CCTB)
        code String
    }
    
    
    deployment {
      deploymentType docker-compose
      appsFolders [jaguar,wildcat]
      dockerRepositoryName "wasp"
    }
  </pre>
  </details>

##### **Browsers and Operating System**

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by mraible** [comment]
Can you please try with Node 18? Node 20 is not supported yet.

**Comment by rjbgaspar** [comment]
Hi @mraible,

Just tried with v18.19.0   (Latest LTS: Hydrogen) and it is the same:

##### **Environment and Tools**

openjdk version "17.0.2" 2022-01-18
OpenJDK Runtime Environment (build 17.0.2+8-86)
OpenJDK 64-Bit Server VM (build 17.0.2+8-86, mixed mode, sharing)

git version 2.39.3 (Apple Git-145)

node: v18.19.0
npm: 10.2.3

Docker version 24.0.2, build cb74dfc

**Comment by mraible** [comment]
I was able to reproduce this with Node v18.18.2. It seems to be related to `@dto(mapstruct)`. If I remove it from the JDL, there are no errors.

**Comment by mshima** [comment]
Composite ids are not supported. Some blueprints supports it.

**Comment by rjbgaspar** [comment]
Hello @mshima,

Why are you mentioning `Composite IDs`? The above JDL does not use them, or am I missing something?

This is a condensed version of the JDL that I use in one of my projects, and it works perfectly on version 7.9.4.

**Comment by JeSuisAlrick** [comment]
> Image has a composite id: `@Id code String required` and `@Id Employee{Image required} to Image`. I don’t know why it worked in v7.

@mshima, I'm getting this same error, but I'm not using composite keys. It happens only when I use `dto * with mapstruct`.

```
ERROR! An error occured while running jhipster:server#writeServerFiles
ERROR! ERROR! ~/.nvm/versions/node/v18.14.0/lib/node_modules/generator-jhipster/dist/generators/server/templates/src/main/java/_package_/_entityPackage_/service/mapper/_entityClass_Mapper.java.ejs:21
    19| package <%= entityAbsolutePackage %>.service.mapper;
    20| 
 >> 21| <%_
    22|   const getOriginalField = field => field.originalField || field;
    23|   const uuidMapMethod = dtoReferences.some(reference => reference.valueReference && reference.valueReference.field && reference.valueReference.field.fieldTypeUUID);
    24|   const byteMapMethod = dtoReferences.some(reference => reference.valueReference && reference.valueReference.field && reference.valueReference.field.fieldTypeBytes);

Cannot read properties of undefined (reading 'originalField')
```

**Comment by mshima** [comment]
@JeSuisAlrick you should create a new issue with reproduction steps.
