### ISSUE TITLE
Support for CRaC (Coordinated Restore at Checkpoint)

### ISSUE THREAD

**Issue by skin27** [jhipster/generator-jhipster#24581]
##### **Overview of the feature request**

Support CRaC  (Coordinated Restore at Checkpoint) . https://openjdk.org/projects/crac/

##### **Motivation for or Use Case**

JHipster uses Spring Boot as default server-side framework. The framework is great, but slow on startup. Recently, Spring Boot 3.2 got initial support for CRaC by default. Some resources:

- https://spring.io/blog/2023/11/23/spring-boot-3-2-0-available-now
- https://spring.io/blog/2023/10/16/runtime-efficiency-with-spring
- https://docs.spring.io/spring-boot/docs/current/reference/html/deployment.html#deployment.efficient

Basically, this means that developers can create Checkpoints (Snapshots of running applications) without modification of their code. This works when using pure Spring, but for JHipster applications not out the box. It doesn't work because JHipster user other technologies like h2 database etc. When making a checkpoint, you get something like the following:

```
jdk.internal.crac.mirror.CheckpointException
        Suppressed: jdk.internal.crac.mirror.impl.CheckpointOpenFileException: /root/.assimbly/logs/2023-12-06.assimbly.log
                at java.base/jdk.internal.crac.JDKFileResource.lambda$beforeCheckpoint$1(JDKFileResource.java:108)
                at java.base/jdk.internal.crac.mirror.Core.checkpointRestore1(Core.java:169)
                at java.base/jdk.internal.crac.mirror.Core.checkpointRestore(Core.java:286)
                at java.base/jdk.internal.crac.mirror.Core.checkpointRestoreInternal(Core.java:299)
        Suppressed: jdk.internal.crac.mirror.impl.CheckpointOpenSocketException: Socket[addr=0.0.0.0/0.0.0.0,port=0,localport=18088]
                at java.base/jdk.internal.crac.JDKSocketResourceBase.lambda$beforeCheckpoint$0(JDKSocketResourceBase.java:68)
                at java.base/jdk.internal.crac.mirror.Core.checkpointRestore1(Core.java:169)
                at java.base/jdk.internal.crac.mirror.Core.checkpointRestore(Core.java:286)
                at java.base/jdk.internal.crac.mirror.Core.checkpointRestoreInternal(Core.java:299)
        Suppressed: jdk.internal.crac.mirror.impl.CheckpointOpenFileException: /tmp/spring.log
                at java.base/jdk.internal.crac.JDKFileResource.lambda$beforeCheckpoint$1(JDKFileResource.java:108)
                at java.base/jdk.internal.crac.mirror.Core.checkpointRestore1(Core.java:169)
                at java.base/jdk.internal.crac.mirror.Core.checkpointRestore(Core.java:286)
                at java.base/jdk.internal.crac.mirror.Core.checkpointRestoreInternal(Core.java:299)
        Suppressed: jdk.internal.crac.mirror.impl.CheckpointOpenFileException: /root/.assimbly/db/gateway.trace.db
                at java.base/jdk.internal.crac.JDKFileResource.lambda$beforeCheckpoint$1(JDKFileResource.java:108)
                at java.base/jdk.internal.crac.mirror.Core.checkpointRestore1(Core.java:169)
                at java.base/jdk.internal.crac.mirror.Core.checkpointRestore(Core.java:286)
                at java.base/jdk.internal.crac.mirror.Core.checkpointRestoreInternal(Core.java:299)
        Suppressed: jdk.internal.crac.mirror.impl.CheckpointOpenFileException: /root/.assimbly/db/gateway.mv.db
                at java.base/jdk.internal.crac.JDKFileResource.lambda$beforeCheckpoint$1(JDKFileResource.java:108)
                at java.base/jdk.internal.crac.mirror.Core.checkpointRestore1(Core.java:169)
                at java.base/jdk.internal.crac.mirror.Core.checkpointRestore(Core.java:286)
                at java.base/jdk.internal.crac.mirror.Core.checkpointRestoreInternal(Core.java:299)
        Suppressed: jdk.internal.crac.mirror.impl.CheckpointOpenResourceException: FD fd=94 type=unknown path=anon_inode:inotify
                at java.base/jdk.internal.crac.mirror.Core.translateJVMExceptions(Core.java:117)
                at java.base/jdk.internal.crac.mirror.Core.checkpointRestore1(Core.java:188)
                at java.base/jdk.internal.crac.mirror.Core.checkpointRestore(Core.java:286)
                at java.base/jdk.internal.crac.mirror.Core.checkpointRestoreInternal(Core.java:299)
        Suppressed: jdk.internal.crac.mirror.impl.CheckpointOpenSocketException: FD fd=95 type=socket path=socket:[32477]
                at java.base/jdk.internal.crac.mirror.Core.translateJVMExceptions(Core.java:115)
                at java.base/jdk.internal.crac.mirror.Core.checkpointRestore1(Core.java:188)
                at java.base/jdk.internal.crac.mirror.Core.checkpointRestore(Core.java:286)
                at java.base/jdk.internal.crac.mirror.Core.checkpointRestoreInternal(Core.java:299)
        Suppressed: jdk.internal.crac.mirror.impl.CheckpointOpenSocketException: FD fd=96 type=socket path=socket:[32478]
                at java.base/jdk.internal.crac.mirror.Core.translateJVMExceptions(Core.java:115)
                at java.base/jdk.internal.crac.mirror.Core.checkpointRestore1(Core.java:188)
                at java.base/jdk.internal.crac.mirror.Core.checkpointRestore(Core.java:286)
                at java.base/jdk.internal.crac.mirror.Core.checkpointRestoreInternal(Core.java:299)
```

Would be great if JHipster generated apps can be used to create Checkpoints out of the box (thus the code is already adopted for CRaC without the need for users to do it themselves).

##### **Related issues or PR**

- [x ] Checking this box is mandatory (this is just to show you read everything)

**Comment by mraible** [comment]
Keep it open.

**Comment by skin27** [comment]
Note that since Spring Boot 3.2, at least this framework has support for CraC. To get other issues one need to run:

`jcmd example-jhipster-app.jar JDK.checkpoint` 

More details:

https://github.com/CRaC/docs/blob/master/README.md
