### ISSUE TITLE
After upgrade jhipster from 8.0.0 to 8.1.0 , the @Scheduled method hit null pointer.

### ISSUE THREAD

**Issue by terenceyeoh** [jhipster/generator-jhipster#24627]
##### **Overview of the issue**

After upgrade jhipster from 8.0.0 to 8.1.0 , the @Scheduled method hit null pointer. Below are the source code and the error message:

Source code: 
```java
    @Bean
    public Runnable idleConnectionMonitor(PoolingHttpClientConnectionManager pool) {
        return new Runnable() {
            @Override
            @Scheduled(fixedDelayString = "20000")
            public void run() {
                try {
                    // only if connection pool is initialised
                    if (pool != null) {
                        pool.closeExpired();
                        pool.closeIdle(TimeValue.ofMilliseconds(20000L));
                    }
                } catch (Exception e) {
                    // Exception block
                }
            }
        };
    }
```
    
Error Message:

```
 2023-12-20T14:31:34.911+08:00 ERROR 1928 --- [taskScheduler-4] o.s.s.s.TaskUtils$LoggingErrorHandler    : Unexpected error occurred in scheduled task 

java.lang.NullPointerException: null
	at java.base/java.util.Objects.requireNonNull(Objects.java:233)
	at io.micrometer.common.ImmutableKeyValue.<init>(ImmutableKeyValue.java:38)
	at io.micrometer.common.KeyValue.of(KeyValue.java:48)
	at io.micrometer.common.KeyValue.of(KeyValue.java:58)
	at org.springframework.scheduling.support.DefaultScheduledTaskObservationConvention.codeNamespace(DefaultScheduledTaskObservationConvention.java:64)
	at org.springframework.scheduling.support.DefaultScheduledTaskObservationConvention.getLowCardinalityKeyValues(DefaultScheduledTaskObservationConvention.java:56)
	at org.springframework.scheduling.support.DefaultScheduledTaskObservationConvention.getLowCardinalityKeyValues(DefaultScheduledTaskObservationConvention.java:31)
	at io.micrometer.observation.SimpleObservation.start(SimpleObservation.java:152)
	at io.micrometer.observation.Observation.observe(Observation.java:497)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:124)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.runAndReset$$$capture(FutureTask.java:358)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
```
 
##### **Reproduce the error**

Upgrade jhipster version to 8.1.0 then start the application, NPE will appear.

##### **JHipster Version(s)**

8.1.0

##### **Browsers and Operating System**

- [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by atomfrede** [comment]
It seems like some change with regards to spring boot 3.2 I guess. Did you check the spring changelog/migration guides with regard to changes in scheduled methods? The `idleConnectionMonitor` is not something jhipster generates, right?

**Comment by terenceyeoh** [comment]
Ok noted, thanks. Issue resolved when disabled the observability.

**Comment by jofisiva** [comment]
Can you please share the code changes to disable the observability it would be help
