### ISSUE TITLE
Error on adding a field with type Enum

### ISSUE THREAD

**Issue by sebeichholz** [jhipster/generator-jhipster#2463]
I am getting this error when I try to add a field of type "Enum" to a new entity:

```
TypeError: (intermediate value)(intermediate value)(intermediate value).trim is not a function
    at Prompt.suffix (/usr/local/share/npm/lib/node_modules/yo/node_modules/yeoman-generator/node_modules/inquirer/lib/prompts/base.js:173:70)
    at /usr/local/share/npm/lib/node_modules/yo/node_modules/lodash/dist/lodash.js:5296:33
    at Prompt.getQuestion (/usr/local/share/npm/lib/node_modules/yo/node_modules/yeoman-generator/node_modules/inquirer/lib/prompts/base.js:184:52)
    at Prompt.render (/usr/local/share/npm/lib/node_modules/yo/node_modules/yeoman-generator/node_modules/inquirer/lib/prompts/input.js:52:22)
    at Prompt._run (/usr/local/share/npm/lib/node_modules/yo/node_modules/yeoman-generator/node_modules/inquirer/lib/prompts/input.js:40:8)
    at Prompt.run (/usr/local/share/npm/lib/node_modules/yo/node_modules/yeoman-generator/node_modules/inquirer/lib/prompts/base.js:70:8)
    at /usr/local/share/npm/lib/node_modules/yo/node_modules/yeoman-generator/node_modules/inquirer/lib/ui/prompt.js:87:14
    at Object.utils.runAsync (/usr/local/share/npm/lib/node_modules/yo/node_modules/yeoman-generator/node_modules/inquirer/lib/utils/utils.js:44:5)
    at PromptUI.onEachPrompt (/usr/local/share/npm/lib/node_modules/yo/node_modules/yeoman-generator/node_modules/inquirer/lib/ui/prompt.js:85:9)
    at /usr/local/share/npm/lib/node_modules/yo/node_modules/async/lib/async.js:227:13
```

Steps to reproduce:
```
yo jhipster
yo jhipster:entity Game
 > [?] Do you want to add a field to your entity? (Y/n) Y
 > [?] What is the name of your field? enumField
 > [?] What is the type of your field?  Enumeration (Java enum type) 
 > [?] What is the class name of your enumeration? EnumClass
```
That creates the error shown above.

**Comment by sebeichholz** [comment]
I am using jhipster v2.25.0

**Comment by sebeichholz** [comment]
I am working on OSX El Capitan‎. I hope this does not correlate to the error :-(

"yo --version" says 1.1.2 which is strange, because "npm install --global yo" says something about "yo@1.5.0 "

**Comment by jdubois** [comment]
I can't reproduce it, and from reading the stacktrace that does seem like a Yo problem... So yes it could be an OS issue, we've had that kind of thing with Windows 10, but as I'm using Mac OS X El Capitan like you, we can rule this out.
When I do "yo --version" I get 1.5.0, so this looks like a better candidate for the bug: can you try updating this?

**Comment by sebeichholz** [comment]
I will try to, thanks for investigating.

**Comment by sebeichholz** [comment]
I managed to install JHipster in a Docker container.
Generating an entity works without errors. This issue can be closed.

Too bad that working with npm/yeoman is so unstable. I cannot get it to work on OS X (npm update does nothing) and installing npm and yeoman even did not work for me on a clean ubuntu-docker-container. 
I will try your jhipster-docker container.
