### ISSUE TITLE
executable war does not start because of an Hazelcast error

### ISSUE THREAD

**Issue by francescou** [jhipster/generator-jhipster#2492]
Hi, I've generated a project with **jhipster 2.25.0**, it works fine with the spring-boot maven plugin but I can't run the executable war. Here is the stacktrace:

```java
Caused by: java.lang.IllegalArgumentException: PortableFactory[-21] is already registered! com.hazelcast.concurrent.atomicreference.client.AtomicReferencePortableHook$1@50830296 -> com.hazelcast.concurrent.atomicreference.client.AtomicReferencePortableHook$1@1810e665
	at com.hazelcast.nio.serialization.PortableHookLoader.register(PortableHookLoader.java:84) ~[hazelcast-3.5.2.jar!/:3.5.2]
	at com.hazelcast.nio.serialization.PortableHookLoader.load(PortableHookLoader.java:51) ~[hazelcast-3.5.2.jar!/:3.5.2]
	at com.hazelcast.nio.serialization.PortableHookLoader.<init>(PortableHookLoader.java:41) ~[hazelcast-3.5.2.jar!/:3.5.2]
	at com.hazelcast.nio.serialization.SerializationServiceImpl.<init>(SerializationServiceImpl.java:126) ~[hazelcast-3.5.2.jar!/:3.5.2]
	at com.hazelcast.nio.serialization.DefaultSerializationServiceBuilder.createSerializationService(DefaultSerializationServiceBuilder.java:221) ~[hazelcast-3.5.2.jar!/:3.5.2]
	at com.hazelcast.nio.serialization.DefaultSerializationServiceBuilder.build(DefaultSerializationServiceBuilder.java:194) ~[hazelcast-3.5.2.jar!/:3.5.2]
	at com.hazelcast.instance.DefaultNodeExtension.createSerializationService(DefaultNodeExtension.java:113) ~[hazelcast-3.5.2.jar!/:3.5.2]
	at com.hazelcast.instance.Node.<init>(Node.java:160) ~[hazelcast-3.5.2.jar!/:3.5.2]
	at com.hazelcast.instance.HazelcastInstanceImpl.<init>(HazelcastInstanceImpl.java:120) ~[hazelcast-3.5.2.jar!/:3.5.2]
	at com.hazelcast.instance.HazelcastInstanceFactory.constructHazelcastInstance(HazelcastInstanceFactory.java:152) ~[hazelcast-3.5.2.jar!/:3.5.2]
	at com.hazelcast.instance.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:135) ~[hazelcast-3.5.2.jar!/:3.5.2]
	at com.hazelcast.instance.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:111) ~[hazelcast-3.5.2.jar!/:3.5.2]
	at com.mycompany.myapp.config.CacheConfiguration.hazelcastInstance(CacheConfiguration.java:67) ~[classes!/:na]
	at com.mycompany.myapp.config.CacheConfiguration$$EnhancerBySpringCGLIB$$5fcabef9.CGLIB$hazelcastInstance$1(<generated>) ~[classes!/:na]
	at com.mycompany.myapp.config.CacheConfiguration$$EnhancerBySpringCGLIB$$5fcabef9$$FastClassBySpringCGLIB$$51441501.invoke(<generated>) ~[classes!/:na]
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228) ~[spring-core-4.2.3.RELEASE.jar!/:4.2.3.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:318) ~[spring-context-4.2.3.RELEASE.jar!/:4.2.3.RELEASE]
	at com.mycompany.myapp.config.CacheConfiguration$$EnhancerBySpringCGLIB$$5fcabef9.hazelcastInstance(<generated>) ~[classes!/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_60]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_60]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_60]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_60]
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:162) ~[spring-beans-4.2.3.RELEASE.jar!/:4.2.3.RELEASE]
	... 149 common frames omitted
```

This is my _.yo-rc.json_

```json
{
  "generator-jhipster": {
    "baseName": "foo",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "authenticationType": "oauth2",
    "hibernateCache": "hazelcast",
    "clusteredHttpSession": "no",
    "websocket": "no",
    "databaseType": "sql",
    "devDatabaseType": "h2Memory",
    "prodDatabaseType": "postgresql",
    "searchEngine": "no",
    "useSass": false,
    "buildTool": "maven",
    "frontendBuilder": "grunt",
    "enableTranslation": true,
    "enableSocialSignIn": false,
    "rememberMeKey": "***",
    "testFrameworks": [
      "gatling"
    ]
  }
}

```

This issue could be related to issues #1958 and #1836

I did some investigation about this: upgrading _hazelcast.version_ to 3.5.4 does not fix the issue.

The problem, in my opinion, is that the Hazelcast instance is created only after the startup of TomcatEmbeddedWebappClassLoader.

Then, com.hazelcast.util.ServiceLoader#iterator will find two "distinct" serviceDefinitions:

1. jar:file:~/target/foo-0.0.1-SNAPSHOT.war!/WEB-INF/lib/hazelcast-3.5.2.jar!/META-INF/services/com.hazelcast.instance.NodeExtension

2. jar:war:file:~/target/foo-0.0.1-SNAPSHOT.war*/WEB-INF/lib/hazelcast-3.5.2.jar!/META-INF/services/com.hazelcast.instance.NodeExtension

Thank you for your great project!

**Comment by francescou** [comment]
fixed in v2.26.0
