### ISSUE TITLE
NPE executing liquibase:diff if oauth2 is selected as authentication method

### ISSUE THREAD

**Issue by Panthro** [jhipster/generator-jhipster#2517]
### Reproduce
 - create new jhipster project
 - select H2 in disk for dev environment  (not tested on mysql or other dbs)
 - select oauth2 as authentication method
 - `mvn` (to initialize the database)
 - `mvn liquibase:diff`

### Expected
a diff changelog

### Result
NPE during execution

```
[ERROR] Failed to execute goal org.liquibase:liquibase-maven-plugin:3.4.1:diff (default-cli) on project jhipster: Error setting up or running Liquibase: liquibase.command.CommandExecutionException: java.lang.NullPointerException -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.liquibase:liquibase-maven-plugin:3.4.1:diff (default-cli) on project jhipster: Error setting up or running Liquibase: liquibase.command.CommandExecutionException: java.lang.NullPointerException
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:216)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:862)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:286)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: Error setting up or running Liquibase: liquibase.command.CommandExecutionException: java.lang.NullPointerException
	at org.liquibase.maven.plugins.AbstractLiquibaseMojo.execute(AbstractLiquibaseMojo.java:398)
	at org.liquibase.maven.plugins.LiquibaseDatabaseDiff.execute(LiquibaseDatabaseDiff.java:146)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	... 20 more
Caused by: liquibase.exception.LiquibaseException: liquibase.command.CommandExecutionException: java.lang.NullPointerException
	at liquibase.integration.commandline.CommandLineUtils.doDiffToChangeLog(CommandLineUtils.java:197)
	at liquibase.integration.commandline.CommandLineUtils.doDiffToChangeLog(CommandLineUtils.java:174)
	at org.liquibase.maven.plugins.LiquibaseDatabaseDiff.performLiquibaseTask(LiquibaseDatabaseDiff.java:182)
	at org.liquibase.maven.plugins.AbstractLiquibaseMojo.execute(AbstractLiquibaseMojo.java:394)
	... 23 more
Caused by: liquibase.command.CommandExecutionException: java.lang.NullPointerException
	at liquibase.command.AbstractCommand.execute(AbstractCommand.java:13)
	at liquibase.integration.commandline.CommandLineUtils.doDiffToChangeLog(CommandLineUtils.java:195)
	... 26 more
Caused by: java.lang.NullPointerException
	at java.util.regex.Matcher.getTextLength(Matcher.java:1283)
	at java.util.regex.Matcher.reset(Matcher.java:309)
	at java.util.regex.Matcher.<init>(Matcher.java:229)
	at java.util.regex.Pattern.matcher(Pattern.java:1093)
	at liquibase.diff.output.StandardObjectChangeFilter$Filter.matches(StandardObjectChangeFilter.java:104)
	at liquibase.diff.output.StandardObjectChangeFilter.include(StandardObjectChangeFilter.java:70)
	at liquibase.diff.output.StandardObjectChangeFilter.includeMissing(StandardObjectChangeFilter.java:51)
	at liquibase.diff.output.changelog.ChangeGeneratorChain.fixMissing(ChangeGeneratorChain.java:28)
	at liquibase.diff.output.changelog.ChangeGeneratorFactory.fixMissing(ChangeGeneratorFactory.java:99)
	at liquibase.diff.output.changelog.DiffToChangeLog.generateChangeSets(DiffToChangeLog.java:140)
	at liquibase.diff.output.changelog.DiffToChangeLog.print(DiffToChangeLog.java:120)
	at liquibase.diff.output.changelog.DiffToChangeLog.print(DiffToChangeLog.java:71)
	at liquibase.diff.output.changelog.DiffToChangeLog.print(DiffToChangeLog.java:59)
	at liquibase.command.DiffToChangeLogCommand.run(DiffToChangeLogCommand.java:61)
	at liquibase.command.AbstractCommand.execute(AbstractCommand.java:8)
	... 27 more
```

**Comment by pascalgrimaud** [comment]
It's related to H2, because in pom.xml, at plugin liquibase-maven-plugin, we use `jdbc:h2:tcp://localhost:9092/./target/h2db/db/tmp` instead of the url in application-dev.yml

I think we have the same issue with gradle.

Do you want to do a PR, @Panthro ?

**Comment by Panthro** [comment]
This is actually a liquibase bug, I found out later.

I created an issue on __liquibase-hibernate__ (but the issue is actually on core, I didn't see before):
https://github.com/liquibase/liquibase-hibernate/issues/101

Then I created a pull request for __liquibase-core__:
https://github.com/liquibase/liquibase/pull/540

**Comment by pascalgrimaud** [comment]
I think we don't have the same error.
My .yo-rc.json :
```
{
  "generator-jhipster": {
    "baseName": "jhipster",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "authenticationType": "oauth2",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": "no",
    "websocket": "no",
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": "no",
    "useSass": false,
    "buildTool": "maven",
    "frontendBuilder": "grunt",
    "enableTranslation": true,
    "enableSocialSignIn": false,
    "rememberMeKey": "7c3a8ab8a83c08016b593638329ea03a04bcb9e0",
    "testFrameworks": [
      "gatling"
    ]
  }
}
```
then :
- start app with mvn
- stop app
- mvn liquibase:diff

My stackstrace :
```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 3.673s
[INFO] Finished at: Wed Dec 23 13:40:14 CET 2015
[INFO] Final Memory: 20M/332M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.liquibase:liquibase-maven-plugin:3.4.1:diff (default-cli) on project jhipster: Error setting up or running Liquibase: liquibase.exception.DatabaseException: org.h2.jdbc.JdbcSQLException: Connection is broken: "java.net.ConnectException: Connexion refusée: localhost:9092" [90067-190] -> [Help 1]
```

I made a change in my pom.xml file :
```
<driver>org.h2.Driver</driver>
<!--url>jdbc:h2:tcp://localhost:9092/./target/h2db/db/tmp</url-->
<url>jdbc:h2:file:./target/h2db/db/jhipster</url>
```

Then it's ok :
```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 6.563s
[INFO] Finished at: Wed Dec 23 13:42:47 CET 2015
[INFO] Final Memory: 30M/407M
[INFO] ------------------------------------------------------------------------
```

**Comment by pascalgrimaud** [comment]
Can you tell what is your <url> in your pom.xml ?
Do you have some entities ?

**Comment by Panthro** [comment]
I haven't changed anything from the original jhipster project:

so probably the url thing fixed it right?

The mentioned issues on liquibase are for another situation, but I was thinking they were related, because debugging it was throwing the same error in the exact same location, and once I did the liquibase:diff with my own modified version of liquibase the issue was gone

.yo-rc.json
```
{
  "generator-jhipster": {
    "baseName": "jhipster",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "authenticationType": "oauth2",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": "no",
    "websocket": "no",
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": "no",
    "useSass": false,
    "buildTool": "maven",
    "frontendBuilder": "grunt",
    "enableTranslation": true,
    "enableSocialSignIn": false,
    "rememberMeKey": "0f4a4f42b9a85ab43a3502a4e205d1c86c12d69c",
    "testFrameworks": [
      "gatling"
    ]
  }
}
```


.pom liquibase config
```
                 <configuration>
                    <changeLogFile>src/main/resources/config/liquibase/master.xml</changeLogFile>
                    <diffChangeLogFile>src/main/resources/config/liquibase/changelog/${maven.build.timestamp}_changelog.xml</diffChangeLogFile>
                    <driver>org.h2.Driver</driver>
                    <url>jdbc:h2:tcp://localhost:9092/./target/h2db/db/tmp</url>
                    <defaultSchemaName></defaultSchemaName>
                    <username></username>
                    <password></password>
                    <referenceUrl>hibernate:spring:com.mycompany.myapp.domain?dialect=org.hibernate.dialect.H2Dialect</referenceUrl>
                    <verbose>true</verbose>
                    <logging>debug</logging>
                    <diffExcludeObjects>oauth_access_token, oauth_approvals, oauth_client_details, oauth_client_token, oauth_code, oauth_refresh_token</diffExcludeObjects>
                </configuration>
```

**Comment by pascalgrimaud** [comment]
Yes, can you use the same url in your application-dev.yml ?
it should look like : jdbc:h2:file:./target/h2db/db/jhipster

**Comment by Panthro** [comment]
changing the url resulted in `[INFO] BUILD SUCCESS` :neckbeard:

seems that a PR can be easily done to fix it :feelsgood:

**Comment by Panthro** [comment]
btw, don't you think this should be added to travis? So issues like this would be picked up way earlier.

**Comment by pascalgrimaud** [comment]
Yes we could, but I don't think it's a good idea.
If we test the goal `liquibase:diff`, we have to do the same for the other, like `sonar:sonar` or `gatling:execute`.
The Travis build will be more complex and it does not worth, in my opinion.

So I let you do a PR to fix this (don't forget gradle too) ;)

**Comment by Panthro** [comment]
well, it's fully automated and it would avoid the scenario that there's a release with a broken structure (which is what jhipster is for in my opinion, create a better code skeleton) it's worth it.

Think about something, in my case I'm a experienced java developer, and I can find this kind of issues easily, can debug maven dependencies, etc etc etc until I find the issue and fix it.

But if a new developer tries to use jhipster to bootstrap the development of a new app and one of the things in the tutorial (such as liquibase:diff) fails, it's really hard to progress.

So, in my opinion, the jhipster team (and collaborators) should make sure the code released is not broken in any case.
I'll create a PR for testing liquibase:diff and if it plays well we resume the talking.

**Comment by Panthro** [comment]
PR for the bugfix in the h2 url is here #2530

**Comment by pascalgrimaud** [comment]
In fact, testing `liquibase:diff` is not so easy.
You have to start the app, to "init" the database, then stop the app and launch `liquibase:diff`.

I have a lot of problem to test if the app is started or not, so for now, I commented the curl test :
https://github.com/jhipster/generator-jhipster/blob/master/travis/scripts/05-run.sh#L15-L16

Sometimes, the app didn't start and is stuck, I explained it in this ticket https://github.com/jhipster/generator-jhipster/issues/2182
> The app can be stuck at `[INFO] com.mycompany.myapp.config.WebConfigurer - Web application fully configured`

**Comment by Panthro** [comment]
hummm I didn't think that travis would affect that much the environment afterall.

Ok, let's leave this discussion for a future time =)
