### ISSUE TITLE
JDL generation with builtInEntity on authority  in jHipster 8.1.0

### ISSUE THREAD

**Issue by bangaromaric** [jhipster/generator-jhipster#25316]
##### **Overview of the issue**

        ██╗ ██╗   ██╗ ████████╗ ███████╗   ██████╗ ████████╗ ████████╗ ███████╗
        ██║ ██║   ██║ ╚══██╔══╝ ██╔═══██╗ ██╔════╝ ╚══██╔══╝ ██╔═════╝ ██╔═══██╗
        ██║ ████████║    ██║    ███████╔╝ ╚█████╗     ██║    ██████╗   ███████╔╝
  ██╗   ██║ ██╔═══██║    ██║    ██╔════╝   ╚═══██╗    ██║    ██╔═══╝   ██╔══██║
  ╚██████╔╝ ██║   ██║ ████████╗ ██║       ██████╔╝    ██║    ████████╗ ██║  ╚██╗
   ╚═════╝  ╚═╝   ╚═╝ ╚═══════╝ ╚═╝       ╚═════╝     ╚═╝    ╚═══════╝ ╚═╝   ╚═╝
                            https://www.jhipster.tech
Welcome to JHipster v8.1.0

INFO! Generating jdls entity.jdl
     info Generating 1 application
 _______________________________________________________________________________________________________________

  Documentation for creating an application is at https://www.jhipster.tech/creating-an-app/

  Application files will be generated in folder: /media/banga/Android/dev/springboot/spring-geda
 _______________________________________________________________________________________________________________

WARNING! Search engine is enabled at entity level, but disabled at application level. Search engine will be disabled
WARNING! Search engine is enabled at entity level, but disabled at application level. Search engine will be disabled
ERROR! An error occured while running jhipster:bootstrap-application-base#loadingEntities
ERROR! ERROR! Error at entity Permission: could not find the entity authority
Error: Error at entity Permission: could not find the entity authority
    at loadEntitiesOtherSide (file:///home/banga/.nvm/versions/node/v20.9.0/lib/node_modules/generator-jhipster/dist/generators/base-application/support/relationship.mjs:60:23)
    at BootstrapApplicationBase.loadingEntities (file:///home/banga/.nvm/versions/node/v20.9.0/lib/node_modules/generator-jhipster/dist/generators/bootstrap-application-base/generator.mjs:204:37)
    at BootstrapApplicationBase.executeTask (file:///home/banga/.nvm/versions/node/v20.9.0/lib/node_modules/generator-jhipster/node_modules/yeoman-generator/dist/actions/lifecycle.js:244:26)
    at env.queueTask.once (file:///home/banga/.nvm/versions/node/v20.9.0/lib/node_modules/generator-jhipster/node_modules/yeoman-generator/dist/actions/lifecycle.js:218:56)
    at runLoop.add.once (file:///home/banga/.nvm/versions/node/v20.9.0/lib/node_modules/generator-jhipster/node_modules/yeoman-environment/dist/environment-base.js:384:23)
    at Immediate.<anonymous> (/home/banga/.nvm/versions/node/v20.9.0/lib/node_modules/generator-jhipster/node_modules/grouped-queue/lib/subqueue.js:48:34)
    at process.processImmediate (node:internal/timers:478:21)

##### **Motivation for or Use Case**

I want to generate my monolithic app with a Many-to-Many relationship between the entities **Permission** and **Authority**  , as mentioned in the [documentation](https://www.jhipster.tech/jdl/relationships#relationship-methods)  

##### **Reproduce the error**

application {
  config {
    baseName geda
    applicationType monolith
    packageName ga.aninf.geda
    authenticationType jwt
    prodDatabaseType postgresql
    devDatabaseType h2Memory
    buildTool maven
    clientFramework angularX
    nativeLanguage fr
    languages [en, fr]
    testFrameworks [ gatling ]
    clientTheme none
  }
  entities *
}

entity Utilisateur{
	id UUID
    matricule String 
    nomComplet String required
    telephone String required
} 

entity Permission{
	id UUID
    ressource  String required
    action String required
} 

relationship OneToOne {
    Utilisateur{compte(login) required} to User with builtInEntity
}

relationship ManyToMany {
    Permission {authority } to Authority with builtInEntity
}

##### **JHipster Version(s)**

8.1.0

##### **Environment and Tools**
openjdk version "21.0.1" 2023-10-17
OpenJDK Runtime Environment (build 21.0.1+12-29)
OpenJDK 64-Bit Server VM (build 21.0.1+12-29, mixed mode, sharing)

node: v20.9.0
npm: 10.2.5

##### **Browsers and Operating System**

Linux Mint 20.2 Cinnamon  and Chrome

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by mshima** [comment]
Relationship support with authority will land in 8.2.0 for angular.
