### ISSUE TITLE
Can not integrate gRPC to Jhipster project

### ISSUE THREAD

**Issue by tungthanhss** [jhipster/generator-jhipster#25488]
##### **Overview of the issue**
It'working normally with spring boot 3.x java 17 project. But not working with jhipster project. 
I followed as guide https://www.baeldung.com/spring-boot-grpc. 
I upload log and image
[log_grpc_error.txt](https://github.com/jhipster/generator-jhipster/files/14600445/log_grpc_error.txt)

![image](https://github.com/jhipster/generator-jhipster/assets/34281514/365a9721-351e-4da2-b016-25863bc1fd29)

##### **JHipster Version(s)**

 8.1.0

**Comment by tungthanhss** [comment]
Error still  happend on 8.6.0 

java.lang.ExceptionInInitializerError: null
	at io.grpc.netty.shaded.io.netty.channel.epoll.Epoll.<clinit>(Epoll.java:40)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:375)
	at io.grpc.netty.shaded.io.grpc.netty.Utils.isEpollAvailable(Utils.java:313)
	at io.grpc.netty.shaded.io.grpc.netty.Utils.<clinit>(Utils.java:117)
	at io.grpc.netty.shaded.io.grpc.netty.NettyServerBuilder.<clinit>(NettyServerBuilder.java:83)
	at net.devh.boot.grpc.server.serverfactory.ShadedNettyGrpcServerFactory.newServerBuilder(ShadedNettyGrpcServerFactory.java:78)
	at net.devh.boot.grpc.server.serverfactory.ShadedNettyGrpcServerFactory.newServerBuilder(ShadedNettyGrpcServerFactory.java:53)
	at net.devh.boot.grpc.server.serverfactory.AbstractGrpcServerFactory.createServer(AbstractGrpcServerFactory.java:65)
	at net.devh.boot.grpc.server.serverfactory.GrpcServerLifecycle.createAndStartGrpcServer(GrpcServerLifecycle.java:110)
	at net.devh.boot.grpc.server.serverfactory.GrpcServerLifecycle.start(GrpcServerLifecycle.java:71)
	at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:285)
	at org.springframework.context.support.DefaultLifecycleProcessor$LifecycleGroup.start(DefaultLifecycleProcessor.java:469)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at org.springframework.context.support.DefaultLifecycleProcessor.startBeans(DefaultLifecycleProcessor.java:257)
	at org.springframework.context.support.DefaultLifecycleProcessor.onRefresh(DefaultLifecycleProcessor.java:202)
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:981)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:627)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:146)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:754)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:456)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:335)
	at com.vnpt.fileservice.FileserviceApp.main(FileserviceApp.java:70)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.springframework.boot.devtools.restart.RestartLauncher.run(RestartLauncher.java:50)
Caused by: java.lang.IllegalStateException: Only supported on Linux
	at io.grpc.netty.shaded.io.netty.channel.epoll.Native.loadNativeLibrary(Native.java:317)
	at io.grpc.netty.shaded.io.netty.channel.epoll.Native.<clinit>(Native.java:85)
	... 28 common frames omitted
![image](https://github.com/user-attachments/assets/dbf5baba-f82b-454b-b66a-e4acd11afc43)
