### ISSUE TITLE
Error on Grunt Test - TypeError: sockets.forEach is not a function...

### ISSUE THREAD

**Issue by marcelinobadin** [jhipster/generator-jhipster#2621]
If you got this error, the solution for me was to upgrade __Karma to version 0.13.19__ (according to https://github.com/karma-runner/karma/issues/1782). 

After that, all tests passed.
```
Missing error handler on `socket`.
TypeError: sockets.forEach is not a function
    at disconnectBrowsers (/Users/Marcelino/Development/repos/newton/node_modules/karma/lib/server.js:314:13)
    at null.<anonymous> (/Users/Marcelino/Development/repos/newton/node_modules/karma/lib/server.js:291:7)
    at emitTwo (events.js:92:20)
    at emit (events.js:172:7)
    at emitRunCompleteIfAllBrowsersDone (/Users/Marcelino/Development/repos/newton/node_modules/karma/lib/server.js:256:12)
    at null.<anonymous> (/Users/Marcelino/Development/repos/newton/node_modules/karma/lib/server.js:278:9)
    at emitTwo (events.js:92:20)
    at emit (events.js:172:7)
    at onComplete (/Users/Marcelino/Development/repos/newton/node_modules/karma/lib/browser.js:142:13)
    at Socket.<anonymous> (/Users/Marcelino/Development/repos/newton/node_modules/karma/lib/events.js:13:22)
    at emitTwo (events.js:92:20)
    at Socket.emit (events.js:172:7)
    at Socket.onevent (/Users/Marcelino/Development/repos/newton/node_modules/socket.io/lib/socket.js:335:8)
    at Socket.onpacket (/Users/Marcelino/Development/repos/newton/node_modules/socket.io/lib/socket.js:295:12)
    at Client.ondecoded (/Users/Marcelino/Development/repos/newton/node_modules/socket.io/lib/client.js:193:14)
    at Decoder.Emitter.emit (/Users/Marcelino/Development/repos/newton/node_modules/component-emitter/index.js:134:20)
```

**Comment by pascalgrimaud** [comment]
Same issue here : https://github.com/jhipster/generator-jhipster/issues/2574
The fix already done : https://github.com/jhipster/generator-jhipster/pull/2580
I don't understand how our Travis build didn't detect that, probably an issue related to the use of cache, so I added a new test here : https://github.com/jhipster/generator-jhipster/issues/2596

**Comment by marcelinobadin** [comment]
Great, thanks. I did the upgrade from 2.25.0 to 2.26.2 and it didn't change to 0.13.19 version if this information helps you on something.

**Comment by pascalgrimaud** [comment]
Yes, it will change in the next release, 2.26.3 or 2.27.0
