### ISSUE TITLE
npm test ends with error.

### ISSUE THREAD

**Issue by mshima** [jhipster/generator-jhipster#27019]
##### **Overview of the issue**

npm test always ends with an error:
```
             ^

Error: ENOENT: no such file or directory, chdir '/home/runner/work/generator-jhipster/generator-jhipster' -> '/tmp/684e168451aa581d19b2518932589a7acf81e4e7'
    at wrappedChdir (node:internal/bootstrap/switches/does_own_process_state:130:14)
    at process.chdir (node:internal/worker:110:5)
    at process.chdir (/home/runner/work/generator-jhipster/generator-jhipster/node_modules/graceful-fs/polyfills.js:22:11)
    at process.chdir (/home/runner/work/generator-jhipster/generator-jhipster/node_modules/@pnpm/network.ca-file/node_modules/graceful-fs/polyfills.js:22:11)
    at BasicRunContext.restore (file:///home/runner/work/generator-jhipster/generator-jhipster/node_modules/yeoman-test/dist/run-context.js:164:21)
    at BasicRunContext.cleanupTemporaryDir (file:///home/runner/work/generator-jhipster/generator-jhipster/node_modules/yeoman-test/dist/run-context.js:183:14)
    at TestContext.startNewContext (file:///home/runner/work/generator-jhipster/generator-jhipster/node_modules/yeoman-test/dist/test-context.js:6:26)
    at process.cleanupTemporaryDir (file:///home/runner/work/generator-jhipster/generator-jhipster/node_modules/yeoman-test/dist/test-context.js:13:17)
    at process.emit (node:events:531:35)
    at process.exit (node:internal/process/per_thread:185:15)
    at _exit (/home/runner/work/generator-jhipster/generator-jhipster/node_modules/workerpool/src/worker.js:129:12)
    at worker.cleanupAndExit (/home/runner/work/generator-jhipster/generator-jhipster/node_modules/workerpool/src/worker.js:133:12)
    at process.<anonymous> (/home/runner/work/generator-jhipster/generator-jhipster/node_modules/workerpool/src/worker.js:148:19)
    at process.emit (node:events:519:28)
    at emit (node:internal/child_process:951:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'chdir',
  path: '/home/runner/work/generator-jhipster/generator-jhipster',
  dest: '/tmp/684e168451aa581d19b2518932589a7acf81e4e7'
}
```

##### **Browsers and Operating System**

- [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by mraible** [comment]
I was able to reproduce this today. Adding bug bounty.

**Comment by emilpaw** [comment]
I figured out it's caused by the changes in this commit: 5ff7466277abaf593ea61d156d653b06d5e2389f

My guess is that the new way how `execa` is mocked in `check-java.spec.ts` isn't working as expected and mocks `execa` in a way that some command related to the temporary folder is not executed. I'm looking further into this.
