### ISSUE TITLE
The initially generated app doesn't run

### ISSUE THREAD

**Issue by vw98075** [jhipster/generator-jhipster#27470]
##### **Overview of the issue**

After running the generating command "jhipster", the app doesn't run with the command "./gradlew" due to the following errors:
```
:: JHipster 🤓  :: Running Spring Boot 3.3.4 :: Startup profile(s) dev ::                                                          
:: https://www.jhipster.tech ::                                                                                                    

2024-10-01T17:04:25.431-07:00  INFO 96257 --- [  restartedMain] com.abc.foo.FooApp            : Starting FooApp using Java 22.0.2 with PID 96257 (/home/tkw/workspace/myapp-2024-sept/build/classes/java/main started by tkw in /home/tkw/workspace/myapp-2024-sept) 
2024-10-01T17:04:25.431-07:00 DEBUG 96257 --- [  restartedMain] com.abc.foo.FooApp            : Running with Spring Boot v3.3.4, Spring v6.1.13 
2024-10-01T17:04:25.432-07:00  INFO 96257 --- [  restartedMain] com.abc.foo.FooApp            : The following 2 profiles are active: "dev", "api-docs" 
2024-10-01T17:04:25.506-07:00 DEBUG 96257 --- [  restartedMain] java.lang.ProcessBuilder                 : ProcessBuilder.start(): pid: 96287, dir: null, cmd: "docker" 

java.lang.RuntimeException: ProcessBuilder.start() debug
        at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1147)
        at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1089)
        at org.springframework.boot.docker.compose.core.ProcessRunner.startProcess(ProcessRunner.java:105)
        at org.springframework.boot.docker.compose.core.ProcessRunner.run(ProcessRunner.java:87)
        at org.springframework.boot.docker.compose.core.ProcessRunner.run(ProcessRunner.java:74)
        at org.springframework.boot.docker.compose.core.DockerCli$DockerCommands.getDockerCommand(DockerCli.java:135)
        at org.springframework.boot.docker.compose.core.DockerCli$DockerCommands.<init>(DockerCli.java:129)
        at org.springframework.boot.docker.compose.core.DockerCli.lambda$new$0(DockerCli.java:65)
        at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1228)
        at org.springframework.boot.docker.compose.core.DockerCli.<init>(DockerCli.java:64)
        at org.springframework.boot.docker.compose.core.DockerCompose.get(DockerCompose.java:92)
        at org.springframework.boot.docker.compose.lifecycle.DockerComposeLifecycleManager.getDockerCompose(DockerComposeLifecycleManager.java:156)
        at org.springframework.boot.docker.compose.lifecycle.DockerComposeLifecycleManager.start(DockerComposeLifecycleManager.java:111)
        at org.springframework.boot.docker.compose.lifecycle.DockerComposeListener.onApplicationEvent(DockerComposeListener.java:53)
        at org.springframework.boot.docker.compose.lifecycle.DockerComposeListener.onApplicationEvent(DockerComposeListener.java:35)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:185)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:178)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:156)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:138)
        at org.springframework.boot.context.event.EventPublishingRunListener.multicastInitialEvent(EventPublishingRunListener.java:136)
        at org.springframework.boot.context.event.EventPublishingRunListener.contextLoaded(EventPublishingRunListener.java:98)
        at org.springframework.boot.SpringApplicationRunListeners.lambda$contextLoaded$4(SpringApplicationRunListeners.java:72)
        at java.base/java.lang.Iterable.forEach(Iterable.java:75)
        at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:118)
        at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:112)
        at org.springframework.boot.SpringApplicationRunListeners.contextLoaded(SpringApplicationRunListeners.java:72)
        at org.springframework.boot.SpringApplication.prepareContext(SpringApplication.java:433)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:334)
        at com.abc.foo.FooApp.main(FooApp.java:70)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
        at org.springframework.boot.devtools.restart.RestartLauncher.run(RestartLauncher.java:50)

2024-10-01T17:04:26.485-07:00 DEBUG 96257 --- [  restartedMain] java.lang.ProcessBuilder                 : ProcessBuilder.start(): pid: 96304, dir: null, cmd: "docker" 

java.lang.RuntimeException: ProcessBuilder.start() debug
        at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1147)
        at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1089)
        at org.springframework.boot.docker.compose.core.ProcessRunner.startProcess(ProcessRunner.java:105)
        at org.springframework.boot.docker.compose.core.ProcessRunner.run(ProcessRunner.java:87)
        at org.springframework.boot.docker.compose.core.ProcessRunner.run(ProcessRunner.java:74)
        at org.springframework.boot.docker.compose.core.DockerCli$DockerCommands.getDockerComposeCommand(DockerCli.java:155)
        at org.springframework.boot.docker.compose.core.DockerCli$DockerCommands.<init>(DockerCli.java:130)
        at org.springframework.boot.docker.compose.core.DockerCli.lambda$new$0(DockerCli.java:65)
        at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1228)
        at org.springframework.boot.docker.compose.core.DockerCli.<init>(DockerCli.java:64)
        at org.springframework.boot.docker.compose.core.DockerCompose.get(DockerCompose.java:92)
        at org.springframework.boot.docker.compose.lifecycle.DockerComposeLifecycleManager.getDockerCompose(DockerComposeLifecycleManager.java:156)
        at org.springframework.boot.docker.compose.lifecycle.DockerComposeLifecycleManager.start(DockerComposeLifecycleManager.java:111)
        at org.springframework.boot.docker.compose.lifecycle.DockerComposeListener.onApplicationEvent(DockerComposeListener.java:53)
        at org.springframework.boot.docker.compose.lifecycle.DockerComposeListener.onApplicationEvent(DockerComposeListener.java:35)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:185)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:178)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:156)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:138)
        at org.springframework.boot.context.event.EventPublishingRunListener.multicastInitialEvent(EventPublishingRunListener.java:136)
        at org.springframework.boot.context.event.EventPublishingRunListener.contextLoaded(EventPublishingRunListener.java:98)
        at org.springframework.boot.SpringApplicationRunListeners.lambda$contextLoaded$4(SpringApplicationRunListeners.java:72)
        at java.base/java.lang.Iterable.forEach(Iterable.java:75)
        at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:118)
        at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:112)
        at org.springframework.boot.SpringApplicationRunListeners.contextLoaded(SpringApplicationRunListeners.java:72)
        at org.springframework.boot.SpringApplication.prepareContext(SpringApplication.java:433)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:334)
        at com.abc.foo.FooApp.main(FooApp.java:70)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
        at org.springframework.boot.devtools.restart.RestartLauncher.run(RestartLauncher.java:50)

2024-10-01T17:04:26.642-07:00 DEBUG 96257 --- [  restartedMain] java.lang.ProcessBuilder                 : ProcessBuilder.start(): pid: 96329, dir: null, cmd: "docker-compose" 

java.lang.RuntimeException: ProcessBuilder.start() debug
        at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1147)
        at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1089)
        at org.springframework.boot.docker.compose.core.ProcessRunner.startProcess(ProcessRunner.java:105)
        at org.springframework.boot.docker.compose.core.ProcessRunner.run(ProcessRunner.java:87)
        at org.springframework.boot.docker.compose.core.ProcessRunner.run(ProcessRunner.java:74)
        at org.springframework.boot.docker.compose.core.DockerCli$DockerCommands.getDockerComposeCommand(DockerCli.java:165)
        at org.springframework.boot.docker.compose.core.DockerCli$DockerCommands.<init>(DockerCli.java:130)
        at org.springframework.boot.docker.compose.core.DockerCli.lambda$new$0(DockerCli.java:65)
        at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1228)
        at org.springframework.boot.docker.compose.core.DockerCli.<init>(DockerCli.java:64)
        at org.springframework.boot.docker.compose.core.DockerCompose.get(DockerCompose.java:92)
        at org.springframework.boot.docker.compose.lifecycle.DockerComposeLifecycleManager.getDockerCompose(DockerComposeLifecycleManager.java:156)
        at org.springframework.boot.docker.compose.lifecycle.DockerComposeLifecycleManager.start(DockerComposeLifecycleManager.java:111)
        at org.springframework.boot.docker.compose.lifecycle.DockerComposeListener.onApplicationEvent(DockerComposeListener.java:53)
        at org.springframework.boot.docker.compose.lifecycle.DockerComposeListener.onApplicationEvent(DockerComposeListener.java:35)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:185)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:178)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:156)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:138)
        at org.springframework.boot.context.event.EventPublishingRunListener.multicastInitialEvent(EventPublishingRunListener.java:136)
        at org.springframework.boot.context.event.EventPublishingRunListener.contextLoaded(EventPublishingRunListener.java:98)
        at org.springframework.boot.SpringApplicationRunListeners.lambda$contextLoaded$4(SpringApplicationRunListeners.java:72)
        at java.base/java.lang.Iterable.forEach(Iterable.java:75)
        at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:118)
        at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:112)
        at org.springframework.boot.SpringApplicationRunListeners.contextLoaded(SpringApplicationRunListeners.java:72)
        at org.springframework.boot.SpringApplication.prepareContext(SpringApplication.java:433)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:334)
        at com.abc.foo.FooApp.main(FooApp.java:70)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
        at org.springframework.boot.devtools.restart.RestartLauncher.run(RestartLauncher.java:50)

2024-10-01T17:04:28.189-07:00 ERROR 96257 --- [  restartedMain] o.s.boot.SpringApplication               : Application run failed 

org.springframework.boot.docker.compose.core.DockerOutputParseException: Failed to parse docker JSON:

> IDLE
        at org.springframework.boot.docker.compose.core.DockerJson.deserialize(DockerJson.java:81)
        at org.springframework.boot.docker.compose.core.DockerJson.deserialize(DockerJson.java:73)
        at org.springframework.boot.docker.compose.core.DockerCli$DockerCommands.getDockerComposeCommand(DockerCli.java:164)
        at org.springframework.boot.docker.compose.core.DockerCli$DockerCommands.<init>(DockerCli.java:130)
        at org.springframework.boot.docker.compose.core.DockerCli.lambda$new$0(DockerCli.java:65)
        at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1228)
        at org.springframework.boot.docker.compose.core.DockerCli.<init>(DockerCli.java:64)
        at org.springframework.boot.docker.compose.core.DockerCompose.get(DockerCompose.java:92)
        at org.springframework.boot.docker.compose.lifecycle.DockerComposeLifecycleManager.getDockerCompose(DockerComposeLifecycleManager.java:156)
        at org.springframework.boot.docker.compose.lifecycle.DockerComposeLifecycleManager.start(DockerComposeLifecycleManager.java:111)
        at org.springframework.boot.docker.compose.lifecycle.DockerComposeListener.onApplicationEvent(DockerComposeListener.java:53)
        at org.springframework.boot.docker.compose.lifecycle.DockerComposeListener.onApplicationEvent(DockerComposeListener.java:35)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:185)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:178)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:156)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:138)
        at org.springframework.boot.context.event.EventPublishingRunListener.multicastInitialEvent(EventPublishingRunListener.java:136)
        at org.springframework.boot.context.event.EventPublishingRunListener.contextLoaded(EventPublishingRunListener.java:98)
        at org.springframework.boot.SpringApplicationRunListeners.lambda$contextLoaded$4(SpringApplicationRunListeners.java:72)
        at java.base/java.lang.Iterable.forEach(Iterable.java:75)
        at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:118)
        at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:112)
        at org.springframework.boot.SpringApplicationRunListeners.contextLoaded(SpringApplicationRunListeners.java:72)
        at org.springframework.boot.SpringApplication.prepareContext(SpringApplication.java:433)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:334)
        at com.abc.foo.FooApp.main(FooApp.java:70)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
        at org.springframework.boot.devtools.restart.RestartLauncher.run(RestartLauncher.java:50)
Caused by: com.fasterxml.jackson.databind.exc.MismatchedInputException: No content to map due to end-of-input
 at [Source: REDACTED (`StreamReadFeature.INCLUDE_SOURCE_IN_LOCATION` disabled); line: 1]
        at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:59)
        at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:4996)
        at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4898)
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3848)
        at org.springframework.boot.docker.compose.core.DockerJson.deserialize(DockerJson.java:78)
        ... 28 common frames omitted

Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

For more on this, please refer to https://docs.gradle.org/8.10.2/userguide/command_line_interface.html#sec:command_line_warnings in the Gradle documentation.
```

##### **Motivation for or Use Case**

This issue blocks my work.

##### **JHipster Version(s)**

8.7.1
##### **JHipster configuration**

```
jhipster info
WARNING! Since JHipster v8, the jhipster command will not use the locally installed generator-jhipster.
    If you want to execute the locally installed generator-jhipster, run: npx jhipster

        ██╗ ██╗   ██╗ ████████╗ ███████╗   ██████╗ ████████╗ ████████╗ ███████╗
        ██║ ██║   ██║ ╚══██╔══╝ ██╔═══██╗ ██╔════╝ ╚══██╔══╝ ██╔═════╝ ██╔═══██╗
        ██║ ████████║    ██║    ███████╔╝ ╚█████╗     ██║    ██████╗   ███████╔╝
  ██╗   ██║ ██╔═══██║    ██║    ██╔════╝   ╚═══██╗    ██║    ██╔═══╝   ██╔══██║
  ╚██████╔╝ ██║   ██║ ████████╗ ██║       ██████╔╝    ██║    ████████╗ ██║  ╚██╗
   ╚═════╝  ╚═╝   ╚═╝ ╚═══════╝ ╚═╝       ╚═════╝     ╚═╝    ╚═══════╝ ╚═╝   ╚═╝
                            https://www.jhipster.tech
Welcome to JHipster v8.7.1

Welcome to the JHipster Information Sub-Generator



myapp@0.0.0 /home/tkw/workspace/myapp-2024-sept
└── generator-jhipster@8.7.1



##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**


<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "applicationType": "monolith",
    "authenticationType": "jwt",
    "baseName": "myapp",
    "buildTool": "gradle",
    "cacheProvider": "caffeine",
    "clientFramework": "vue",
    "clientTestFrameworks": [
      "cypress"
    ],
    "clientTheme": "spacelab",
    "clientThemeVariant": "light",
    "creationTimestamp": 1727807180935,
    "cypressAudit": true,
    "cypressCoverage": null,
    "databaseType": "sql",
    "devDatabaseType": "h2Memory",
    "devServerPort": 9060,
    "enableGradleEnterprise": false,
    "enableHibernateCache": true,
    "enableSwaggerCodegen": false,
    "enableTranslation": false,
    "entities": [],
    "feignClient": null,
    "gradleEnterpriseHost": null,
    "jhipsterVersion": "8.7.1",
    "messageBroker": false,
    "microfrontend": null,
    "microfrontends": [],
    "nativeLanguage": "en",
    "packageName": "com.abc.myapp",
    "prodDatabaseType": "postgresql",
    "reactive": false,
    "searchEngine": false,
    "serverPort": null,
    "serverSideOptions": [
      "websocket:spring-websocket"
    ],
    "serviceDiscoveryType": false,
    "syncUserWithIdp": null,
    "testFrameworks": [
      "cypress"
    ],
    "websocket": "spring-websocket",
    "withAdminUi": true
  }
}
</pre>
</details>


##### **Environment and Tools**

java version "22.0.2" 2024-07-16
Java(TM) SE Runtime Environment (build 22.0.2+9-70)
Java HotSpot(TM) 64-Bit Server VM (build 22.0.2+9-70, mixed mode, sharing)

git version 2.20.1

node: v20.6.1
npm: 10.8.2

Docker version 19.03.8, build 1b4342cd4c

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>


</pre>
</details>


Congratulations, JHipster execution is complete!
If you find JHipster useful consider sponsoring the project https://www.jhipster.tech/sponsors/

Thanks for using JHipster!
```
##### **Browsers and Operating System**

Deepin 20.3

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by mshima** [comment]
Fixed by https://github.com/jhipster/generator-jhipster/pull/27380.

**Comment by linelect** [comment]
The same RuntimeException in 8.7.3, but app starts and works

Macos, Java 21

2024-11-05T09:47:00.523+01:00 DEBUG 18277 --- [  restartedMain] java.lang.ProcessBuilder                 : ProcessBuilder.start(): pid: 18279, dir: null, cmd: "docker" 

java.lang.RuntimeException: ProcessBuilder.start() debug
        at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1147)
        at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1089)

**Comment by mraible** [comment]
I've seen this too. It only seems to happen on later JDK releases, but it doesn't stop the app from working.

**Comment by srinivasansuit** [comment]
I am also facing this issue on 8.8.0 version on windows with JDK21. Though app works fine, is there a way to fix/disable this exception?

**Comment by mraible** [comment]
@srinivasansuit Please don't comment on closed issues. It's better to open a new one and include the steps to reproduce.

**Comment by srinivasansuit** [comment]
Sure Matt, in future I will raise a new one.
By the way, the solution suggested in the close issue, helped to
address the issue. Thanks !
Regards,
Srini

**Comment by micobarac** [comment]
I have the same issue with JHIpster 8.9.0 and generated Spring Boot Cassandra app:

```
2025-03-19T09:24:30.290+01:00 DEBUG 9234 --- [  restartedMain] java.lang.ProcessBuilder                 : ProcessBuilder.start(): pid: 9240, dir: null, cmd: "docker" 

java.lang.RuntimeException: ProcessBuilder.start() debug
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1147)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1089)
	at org.springframework.boot.docker.compose.core.ProcessRunner.startProcess(ProcessRunner.java:106)
	at org.springframework.boot.docker.compose.core.ProcessRunner.run(ProcessRunner.java:88)
	at org.springframework.boot.docker.compose.core.ProcessRunner.run(ProcessRunner.java:75)
	at org.springframework.boot.docker.compose.core.DockerCli$DockerCommands.getDockerCommand(DockerCli.java:146)
	at org.springframework.boot.docker.compose.core.DockerCli$DockerCommands.<init>(DockerCli.java:140)
	at org.springframework.boot.docker.compose.core.DockerCli.lambda$new$0(DockerCli.java:66)
	at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1228)
	at org.springframework.boot.docker.compose.core.DockerCli.<init>(DockerCli.java:65)
	at org.springframework.boot.docker.compose.core.DockerCompose.get(DockerCompose.java:145)
	at org.springframework.boot.docker.compose.lifecycle.DockerComposeLifecycleManager.getDockerCompose(DockerComposeLifecycleManager.java:166)
	at org.springframework.boot.docker.compose.lifecycle.DockerComposeLifecycleManager.start(DockerComposeLifecycleManager.java:114)
	at org.springframework.boot.docker.compose.lifecycle.DockerComposeListener.onApplicationEvent(DockerComposeListener.java:53)
	at org.springframework.boot.docker.compose.lifecycle.DockerComposeListener.onApplicationEvent(DockerComposeListener.java:35)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:185)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:178)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:156)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:138)
	at org.springframework.boot.context.event.EventPublishingRunListener.multicastInitialEvent(EventPublishingRunListener.java:136)
	at org.springframework.boot.context.event.EventPublishingRunListener.contextLoaded(EventPublishingRunListener.java:98)
	at org.springframework.boot.SpringApplicationRunListeners.lambda$contextLoaded$4(SpringApplicationRunListeners.java:72)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:118)
	at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:112)
	at org.springframework.boot.SpringApplicationRunListeners.contextLoaded(SpringApplicationRunListeners.java:72)
	at org.springframework.boot.SpringApplication.prepareContext(SpringApplication.java:416)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:317)
	at com.logate.openprovider.JhipsterApp.main(JhipsterApp.java:69)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.springframework.boot.devtools.restart.RestartLauncher.run(RestartLauncher.java:50)
```

**Comment by micobarac** [comment]
Why is Docker process starting anyways???

**Comment by johannesmadja** [comment]
You may be able to choose not to display debug logs by adding this to your application.yml or application-{profile}.yml of your choice : 

logging:
  level:
    ROOT: info
    tech.jhipster: info
    org.hibernate.SQL: info
    com.yourpackage: info

you will see, only log info

**Comment by micobarac** [comment]
This happens with `JHIpster 9 Beta 3` too.

It is idiotic. On initial start, while waiting for containers to start and be healthy, there should be some simple message like "Waiting for..." not some damn exception!

It's a design failure on Spring Boot's part. The right UX should be like:

```
[Docker Compose] Waiting for cassandra to become healthy...
[Docker Compose] Cassandra is healthy, continuing startup...
```

Instead they're using a thrown-and-caught `RuntimeException` as a mechanism to capture a stack trace for a `DEBUG` log message. That's an abuse of exception handling — exceptions should signal exceptional conditions, not be used as a stack trace capture tool.
It's worth filing a `Spring Boot GitHub` issue. Given your team contributes back to open source, this could be another good one — the fix would be straightforward: replace the `RuntimeException` stack trace hack with a proper `Thread.currentThread().getStackTrace() `call, and add a clean `Waiting for...` progress message during the health check polling loop.

To suppress this abused exception, add this line to `logback-spring.xml`:

`<logger name="java.lang.ProcessBuilder" level="INFO"/>`
