### ISSUE TITLE
The 8.7.3 version doesn't run - " No content to map due to end-of-input ..."

### ISSUE THREAD

**Issue by vw98075** [jhipster/generator-jhipster#27850]
##### **Overview of the issue**

An initial blank project without any custom entities can not run with the command "./gradlew" due to the following error.
```
   ...
       at org.springframework.boot.devtools.restart.RestartLauncher.run(RestartLauncher.java:50)
Caused by: com.fasterxml.jackson.databind.exc.MismatchedInputException: No content to map due to end-of-input
 at [Source: REDACTED (`StreamReadFeature.INCLUDE_SOURCE_IN_LOCATION` disabled); line: 1]
        at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:59)
        at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:4996)
        at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4898)
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3848)
        at org.springframework.boot.docker.compose.core.DockerJson.deserialize(DockerJson.java:78)
```
This project doesn't ask for Docker. I don't know how Spring Docker compose caused the error.

##### **JHipster Version(s)**

8.7.3

##### **JHipster configuration**
```
>
{
  "generator-jhipster": {
    "applicationType": "monolith",
    "authenticationType": "jwt",
    "baseName": "abc",
    "buildTool": "gradle",
    "cacheProvider": "caffeine",
    "clientFramework": "vue",
    "clientTestFrameworks": [],
    "clientTheme": "spacelab",
    "clientThemeVariant": "light",
    "creationTimestamp": 1731266995273,
    "databaseType": "sql",
    "devDatabaseType": "h2Memory",
    "devServerPort": 9060,
    "enableGradleEnterprise": false,
    "enableHibernateCache": true,
    "enableSwaggerCodegen": false,
    "enableTranslation": false,
    "entities": [],
    "feignClient": null,
    "gradleEnterpriseHost": null,
    "jhipsterVersion": "8.7.3",
    "messageBroker": false,
    "microfrontend": null,
    "microfrontends": [],
    "nativeLanguage": "en",
    "packageName": "com.zzz.abc",
    "prodDatabaseType": "postgresql",
    "reactive": false,
    "searchEngine": false,
    "serverPort": null,
    "serverSideOptions": [
      "websocket:spring-websocket"
    ],
    "serviceDiscoveryType": false,
    "syncUserWithIdp": null,
    "testFrameworks": [],
    "websocket": "spring-websocket",
    "withAdminUi": true
  }
}
```

##### **Browsers and Operating System**

- [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by vw98075** [comment]
When will it be fixed? I am blocked.

**Comment by vw98075** [comment]
I understand that this issue is not currently planned. However, I wanted to highlight that this bug significantly impacts our project because it blocks our work. Any additional insights or workarounds would be greatly appreciated.

If fixing this bug is not feasible, could you suggest any potential workarounds or alternative approaches we could take?
