### ISSUE TITLE
Docker desktop needs to be running, but it's not in the getting started guide

### ISSUE THREAD

**Issue by dderbidge** [jhipster/generator-jhipster#28328]
The getting started documentation is **outdated** for getting JHipster working. During the last 6 months or so, changes have been made that require docker desktop to be running in the background for the web app to run. This needs to be added to the Getting Started page for JHipster. I think there are people that are just getting started with JHipster that don't continue investigating it because they can't get it running due to not having Docker Desktop installed. This might be different for other platforms; I'm using Windows. Please update the getting started guide to include Docker Desktop and to have it running in the background when running the commands to start it.

https://github.com/jhipster/jhipster.github.io/blob/main/docs/getting-started.mdx

**Comment by mraible** [comment]
Docker is only required if you choose certain options. For example, if you select H2 for your development database and JWT authentication, no external services are required and therefore Docker doesn't need to be running.

However, I agree that we should update the documentation and update the CLI to print this for applications requiring Docker in development mode. I'll add a bug bounty to this issue to get it fixed.

**Comment by mshima** [comment]
I suppose we should:
- Before dev database choice: print a warning if docker is not found. `Docker was not found, you can use H2 as development database in Docker-less environments`.
- Add `can be used without Docker` to H2 dbs labels.
- Add `requires Docker or manually configured db` to non H2 db labels.
- Print a warning in the end if a required Docker service was found.

**Comment by dderbidge** [comment]
Thanks for adding that! I should also have mentioned, to be even more clear, that if I selected every default setting when running the 'jhipster' command in the Windows command prompt, it won't run without Docker Desktop running in the background. I think 'recommended' is good wording, but it does seem like it's actually required now. I tried a lot of alternative selections and was not able to get any of them to work without Docker Desktop running.

I also tried to do what @mraible suggested of only selecting H2 as the database type. However, I wasn't able to do that. It asked for the production database type first, but it doesn't allow entering H2 for the production database type. So, naturally, I selected no database type. After I did that, it skipped the question about what type of database to use for development. It did not give me the option of selecting H2, since it skipped it, so I couldn't select it. Here's a look at the the selections I made (all of these were default settings except for the one about not using a database type):

```
√ What is the base name of your application? jhipstertest
√ Which *type* of application would you like to create? Monolithic application (recommended for simple projects)
√ What is your default Java package name? com.mycompany.myapp
√ Would you like to use Maven or Gradle for building the backend? Maven
√ Do you want to make it reactive with Spring WebFlux? No
√ Which *type* of authentication would you like to use? JWT authentication (stateless, with a token)
√ Besides JUnit, which testing frameworks would you like to use?
√ Which *type* of database would you like to use? No database
√ Which cache do you want to use? (Spring cache abstraction) Ehcache (local cache, for a single node)
√ Which other technologies would you like to use?
√ Which *framework* would you like to use for the client? Angular
√ Besides Jest/Vitest, which testing frameworks would you like to use?
√ Do you want to generate the admin UI? Yes
√ Would you like to use a Bootswatch theme (https://bootswatch.com/)? Default JHipster
√ Would you like to enable internationalization support? Yes
√ Please choose the native language of the application English
√ Please choose additional languages to install

```
----
I then tried compiling and running it:
```
mvnw
```

It failed to run, so I then opened Docker desktop and may have found another bug: it still didn't run. The error message said: 'No Docker Compose file found'...

Here's the output from the command line, starting from about where it should have started the server:

```
        ██╗ ██╗   ██╗ ████████╗ ███████╗   ██████╗ ████████╗ ████████╗ ███████╗
        ██║ ██║   ██║ ╚══██╔══╝ ██╔═══██╗ ██╔════╝ ╚══██╔══╝ ██╔═════╝ ██╔═══██╗
        ██║ ████████║    ██║    ███████╔╝ ╚█████╗     ██║    ██████╗   ███████╔╝
  ██╗   ██║ ██╔═══██║    ██║    ██╔════╝   ╚═══██╗    ██║    ██╔═══╝   ██╔══██║
  ╚██████╔╝ ██║   ██║ ████████╗ ██║       ██████╔╝    ██║    ████████╗ ██║  ╚██╗
   ╚═════╝  ╚═╝   ╚═╝ ╚═══════╝ ╚═╝       ╚═════╝     ╚═╝    ╚═══════╝ ╚═╝   ╚═╝

:: JHipster ?  :: Running Spring Boot 3.4.1 :: Startup profile(s) dev ::
:: https://www.jhipster.tech ::

2025-01-09T15:13:18.610-07:00 DEBUG 43476 --- [kground-preinit] org.jboss.logging                        : Logging Provider: org.jboss.logging.Slf4jLoggerProvider found via system property
2025-01-09T15:13:18.648-07:00  INFO 43476 --- [  restartedMain] com.mycompany.myapp.JhipstertestApp      : Starting JhipstertestApp using Java 21.0.5 with PID 43476 (D:\jhipstertest\target\classes started by dderb in D:\jhipstertest)
2025-01-09T15:13:18.649-07:00 DEBUG 43476 --- [  restartedMain] com.mycompany.myapp.JhipstertestApp      : Running with Spring Boot v3.4.1, Spring v6.2.1
2025-01-09T15:13:18.650-07:00  INFO 43476 --- [  restartedMain] com.mycompany.myapp.JhipstertestApp      : The following 2 profiles are active: "dev", "api-docs"
2025-01-09T15:13:18.802-07:00 ERROR 43476 --- [  restartedMain] o.s.boot.SpringApplication               : Application run failed

java.lang.IllegalStateException: No Docker Compose file found in directory 'D:\jhipstertest\.'
        at org.springframework.util.Assert.state(Assert.java:101)
        at org.springframework.boot.docker.compose.lifecycle.DockerComposeLifecycleManager.getComposeFile(DockerComposeLifecycleManager.java:153)
        at org.springframework.boot.docker.compose.lifecycle.DockerComposeLifecycleManager.start(DockerComposeLifecycleManager.java:111)
        at org.springframework.boot.docker.compose.lifecycle.DockerComposeListener.onApplicationEvent(DockerComposeListener.java:53)
        at org.springframework.boot.docker.compose.lifecycle.DockerComposeListener.onApplicationEvent(DockerComposeListener.java:35)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:185)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:178)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:156)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:138)
        at org.springframework.boot.context.event.EventPublishingRunListener.multicastInitialEvent(EventPublishingRunListener.java:136)
        at org.springframework.boot.context.event.EventPublishingRunListener.contextLoaded(EventPublishingRunListener.java:98)
        at org.springframework.boot.SpringApplicationRunListeners.lambda$contextLoaded$4(SpringApplicationRunListeners.java:72)
        at java.base/java.lang.Iterable.forEach(Iterable.java:75)
        at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:118)
        at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:112)
        at org.springframework.boot.SpringApplicationRunListeners.contextLoaded(SpringApplicationRunListeners.java:72)
        at org.springframework.boot.SpringApplication.prepareContext(SpringApplication.java:416)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:317)
        at com.mycompany.myapp.JhipstertestApp.main(JhipstertestApp.java:69)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
        at org.springframework.boot.devtools.restart.RestartLauncher.run(RestartLauncher.java:50)

[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  36.797 s
[INFO] Finished at: 2025-01-09T15:13:18-07:00
[INFO] ------------------------------------------------------------------------
```

**Comment by mshima** [comment]
@DanielFran bounty claimed https://opencollective.com/generator-jhipster/expenses/239500.

**Comment by DanielFran** [comment]
@mshima approved
