### ISSUE TITLE
How run jhipster gradle-project from Eclipse?

### ISSUE THREAD

**Issue by jpsw** [jhipster/generator-jhipster#2920]
I only find instructions how to run maven-project from Eclipse? ( http://jhipster.github.io/configuring-ide-eclipse/ )

I created a basic jhipster-app, selecting gradle as build-tool.

When I run: gradlew bootRun
it works fine.

I also imported as Gradle project into Eclipse.
But when I right-click the Application class in eclipse (with -Dspring.profiles.active=dev), I get the exceptions below.

Not able to figure this out....
Would be helpful if you could point to instructions for eclipse with _**gradle**_-project?

Any hints what I am missing?

......
	Caused by: org.springframework.beans.factory.BeanCreationException: Could not autowire field: private com.mycompany.myapp.web.rest.mapper.AuthorMapper com.mycompany.myapp.service.impl.AuthorServiceImpl.authorMapper; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type [com.mycompany.myapp.web.rest.mapper.AuthorMapper] found for dependency: expected at least 1 bean which qualifies as autowire candidate for this dependency. Dependency annotations: {@javax.inject.Inject()}
		at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:573) ~[spring-beans-4.2.4.RELEASE.jar:4.2.4.RELEASE]
		at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:88) ~[spring-beans-4.2.4.RELEASE.jar:4.2.4.RELEASE]
		at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:331) ~[spring-beans-4.2.4.RELEASE.jar:4.2.4.RELEASE]
		... 20 common frames omitted
	Caused by: org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type [com.mycompany.myapp.web.rest.mapper.AuthorMapper] found for dependency: expected at least 1 bean which qualifies as autowire candidate for this dependency. Dependency annotations: {@javax.inject.Inject()}
		at org.springframework.beans.factory.support.DefaultListableBeanFactory.raiseNoSuchBeanDefinitionException(DefaultListableBeanFactory.java:1373) ~[spring-beans-4.2.4.RELEASE.jar:4.2.4.RELEASE]
		at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1119) ~[spring-beans-4.2.4.RELEASE.jar:4.2.4.RELEASE]
		at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1014) ~[spring-beans-4.2.4.RELEASE.jar:4.2.4.RELEASE]
		at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:545) ~[spring-beans-4.2.4.RELEASE.jar:4.2.4.RELEASE]
		... 22 common frames omitted

**Comment by gmarziou** [comment]
Looks like you're missing the source code generated by MapStruct annotation processor for mapping AuthorDTO to Author entity: AuthorMapperImpl.
This is generated by gradle or maven build, try running it first. 
I can't help you more on this as I don't use Eclipse.

**Comment by jpsw** [comment]
Hmm...interesting...

As I wrote, I first had **gradlew bootRun** running OK, so I guess everything is already generated before I import in Eclipse.

But your hint helped me find a workaround...

When I _manually _add   **build/generated/source/apt/main**  
to the build-path in eclipse, it actually works....

**Comment by jpsw** [comment]
Anyways, thanks for help!

I guess this might be an issue with the eclipse gradle-plugin....
Perhaps add a note somewhere, though, to the jhipster IDE-integration documentation?

**Comment by jdubois** [comment]
Yes I neither use Gradle nor Eclipse, so any help here is welcome.

**Comment by deepu105** [comment]
I also switched to InteliJ long back, it just works with gradle OOB
@atomfrede what about you

**Comment by atomfrede** [comment]
Also using idea. Works fine out of box. @jpsw Are you using buildship?

**Comment by jpsw** [comment]
@atomfrede -- No, Im just using Eclipse JEE edition and installed from eclipse marketplace:
+ Gradle Integration for Eclipse
+ Gradle IDE pack

Does buildship-integration work better?

**Comment by jpsw** [comment]
Found the issue discussed in the apt-plugin project:

https://github.com/tbroyer/gradle-apt-plugin/issues/7

https://github.com/tbroyer/gradle-apt-plugin    (see not at the bottom: Usage with IDEs)
