### ISSUE TITLE
mvn clean -Pprod` makes grunt to fail

### ISSUE THREAD

**Issue by vancourse** [jhipster/generator-jhipster#3015]
> Please follow the issue template below for bug reports and quiries.
> Bug reports or quiries opened without any of these info will be **closed** without any explanation.
> For feature requests, label the title with [FEATURE] and explain your use case and ideas clearly below, you can remove sections which are not relevant.

##### **Overview of the issue**
Command:
 mvn clean install -Pprod 
dies with: 

~~~
[ERROR] Failed to execute goal com.github.trecloux:yeoman-maven-plugin:0.4:build (run-frontend-build) on project screener: Error during : grunt test --no-color: Process exited with an error: 3 (Exit value: 3) -> [Help 1]
~~~

Stack:

~~~
ERROR] Failed to execute goal com.github.trecloux:yeoman-maven-plugin:0.4:build (run-frontend-build) on project screener: Error during : grunt test --no-color: Process exited with an error: 3 (Exit value: 3) -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.github.trecloux:yeoman-maven-plugin:0.4:build (run-frontend-build) on project screener: Error during : grunt test --no-color
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:216)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:862)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:286)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: Error during : grunt test --no-color
	at com.github.trecloux.yeoman.YeomanMojo.executeCommand(YeomanMojo.java:127)
	at com.github.trecloux.yeoman.YeomanMojo.logAndExecuteCommand(YeomanMojo.java:108)
	at com.github.trecloux.yeoman.YeomanMojo.build(YeomanMojo.java:94)
	at com.github.trecloux.yeoman.YeomanMojo.execute(YeomanMojo.java:68)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	... 20 more
Caused by: org.apache.commons.exec.ExecuteException: Process exited with an error: 3 (Exit value: 3)
	at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:377)
	at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:160)
	at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:147)
	at com.github.trecloux.yeoman.YeomanMojo.executeCommand(YeomanMojo.java:125)
	... 25 more
~~~

##### **Motivation for or Use Case** 
Completed development; Now trying to push to production.

##### **JHipster Version(s)** 
2.27

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder** 

~~~json
{
  "generator-jhipster": {
    "baseName": "screener",
    "packageName": "com.getinsured.ms.screener",
    "packageFolder": "com/getinsured/ms/screener",
    "authenticationType": "session",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": "no",
    "websocket": "no",
    "databaseType": "sql",
    "devDatabaseType": "mysql",
    "prodDatabaseType": "mysql",
    "searchEngine": "no",
    "useSass": false,
    "buildTool": "maven",
    "frontendBuilder": "grunt",
    "enableTranslation": true,
    "enableSocialSignIn": false,
    "rememberMeKey": "",
    "testFrameworks": [
      "gatling"
    ]
  }
}
~~~

##### **Browsers and Operating System** 
Safari, Chrome on OSX
15.0.0 Darwin Kernel Version 15.0.0: Wed Aug 26 16:57:32 PDT 2015; root:xnu-3247.1.106~1/RELEASE_X86_64 x86_64

##### **Reproduce the error** 

mvn clean install -Pprod 

##### **Related issues** 
Yes, regression. Similar issue was filed: #1146 on Feb 13th 2015.

**Comment by gmarziou** [comment]
Release 2.27.1 has a fix for grunt and gulp prod builds.

http://jhipster.github.io/2016/02/23/jhipster-release-2.27.1.html

install new version with `npm -g install generator-jhipster`

go to your project directory and run  `yo jhispter`, overwrite your files (of course they must  comitted first) then merge changes related to build process.

**Comment by gmarziou** [comment]
Or if you feel incomrtabe with this, start from an empty directory copy your project's .yo-rc.json file into it, run `yo jhipster`, check that production build works and then copy build files to your project.
