### ISSUE TITLE
Error with findByUserIsCurrentUser generated by entity subgenerator

### ISSUE THREAD

**Issue by thiagogcm** [jhipster/generator-jhipster#3147]
##### **Overview of the issue**
When using the method findByUserIsCurrentUser generated by the entity subgenator:
Ex:
```
@Query("select pdfdoc from Pdfdoc pdfdoc where pdfdoc.user.login = ?#{principal.username}")
List<Pdfdoc> findByUserIsCurrentUser();
```

I get the following error: 

org.springframework.expression.spel.SpelEvaluationException: EL1008E:(pos 10): Property or field 'username' cannot be found on object of type 'java.lang.String' - maybe not public?
        at org.springframework.expression.spel.ast.PropertyOrFieldReference.readProperty(PropertyOrFieldReference.java:224)
        at org.springframework.expression.spel.ast.PropertyOrFieldReference.getValueInternal(PropertyOrFieldReference.java:94)
        at org.springframework.expression.spel.ast.PropertyOrFieldReference.access$000(PropertyOrFieldReference.java:46)
        at org.springframework.expression.spel.ast.PropertyOrFieldReference$AccessorLValue.getValue(PropertyOrFieldReference.java:374)
        at org.springframework.expression.spel.ast.CompoundExpression.getValueInternal(CompoundExpression.java:88)
        at org.springframework.expression.spel.ast.SpelNodeImpl.getTypedValue(SpelNodeImpl.java:131)
        at org.springframework.expression.spel.standard.SpelExpression.getValue(SpelExpression.java:299)
        at org.springframework.data.jpa.repository.query.SpelExpressionStringQueryParameterBinder.evaluateExpression(SpelExpressionStringQueryParameterBinder.java:131)
        at org.springframework.data.jpa.repository.query.SpelExpressionStringQueryParameterBinder.potentiallyBindExpressionParameters(SpelExpressionStringQueryParameterBinder.java:89)
        at org.springframework.data.jpa.repository.query.SpelExpressionStringQueryParameterBinder.bind(SpelExpressionStringQueryParameterBinder.java:69)
        at org.springframework.data.jpa.repository.query.ParameterBinder.bindAndPrepare(ParameterBinder.java:172)
        at org.springframework.data.jpa.repository.query.ParameterBinder.bindAndPrepare(ParameterBinder.java:163)
        at org.springframework.data.jpa.repository.query.AbstractStringBasedJpaQuery.doCreateQuery(AbstractStringBasedJpaQuery.java:78)
        at org.springframework.data.jpa.repository.query.AbstractJpaQuery.createQuery(AbstractJpaQuery.java:169)
        at org.springframework.data.jpa.repository.query.JpaQueryExecution$CollectionExecution.doExecute(JpaQueryExecution.java:114)
        at org.springframework.data.jpa.repository.query.JpaQueryExecution.execute(JpaQueryExecution.java:78)
        at org.springframework.data.jpa.repository.query.AbstractJpaQuery.doExecute(AbstractJpaQuery.java:100)
        at org.springframework.data.jpa.repository.query.AbstractJpaQuery.execute(AbstractJpaQuery.java:91)
        at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.doInvoke(RepositoryFactorySupport.java:462)
        at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.invoke(RepositoryFactorySupport.java:440)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
        at org.springframework.data.projection.DefaultMethodInvokingMethodInterceptor.invoke(DefaultMethodInvokingMethodInterceptor.java:61)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
        at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99)
        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:281)
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
        at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:136)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
        at org.springframework.data.jpa.repository.support.CrudMethodMetadataPostProcessor$CrudMethodMetadataPopulatingMethodInterceptor.invoke(CrudMethodMetadataPostProcessor.java:131)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
        at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:208)
        at com.sun.proxy.$Proxy153.findByUserIsCurrentUser(Unknown Source)
        at org.cryptocert.web.rest.PdfdocResource.getAllPdfdocs(PdfdocResource.java:109)
        at org.cryptocert.web.rest.PdfdocResource$$FastClassBySpringCGLIB$$45bb57d5.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:720)
.
.
.
##### **Motivation for or Use Case** 
Unexpected behavior

##### **JHipster Version(s)** 
Latest master

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder** 
```
{
  "generator-jhipster": {
    "jhipsterVersion": "2.27.0",
    "baseName": "CryptoCert",
    "packageName": "org.cryptocert",
    "packageFolder": "org/cryptocert",
    "authenticationType": "jwt",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": "no",
    "websocket": "no",
    "databaseType": "sql",
    "devDatabaseType": "postgresql",
    "prodDatabaseType": "postgresql",
    "searchEngine": "elasticsearch",
    "buildTool": "gradle",
    "enableSocialSignIn": false,
    "useSass": false,
    "applicationType": "monolith",
    "testFrameworks": [
      "cucumber",
      "protractor"
    ],
    "enableTranslation": false
  }
}
```

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory** 

```
{
    "relationships": [
        {
            "relationshipName": "user",
            "otherEntityName": "user",
            "relationshipType": "many-to-one",
            "otherEntityField": "login"
        }
    ],
    "fields": [
        {
            "fieldName": "file",
            "fieldType": "byte[]",
            "fieldTypeBlobContent": "any",
            "fieldValidateRules": [
                "required"
            ]
        },
        {
            "fieldName": "name",
            "fieldType": "String",
            "fieldValidateRules": [
                "required"
            ]
        },
        {
            "fieldName": "reason",
            "fieldType": "String"
        }
    ],
    "changelogDate": "20160313201223",
    "dto": "no",
    "service": "no",
    "entityTableName": "pdfdoc",
    "pagination": "no"
}
```

##### **Browsers and Operating System** 
Does not apply

##### **Reproduce the error** 
Generate an entity and use the the method findByUserIsCurrentUser

##### **Related issues** 
None

##### **Suggest a Fix** 

removing the username property from the principal in the query solved the issue, but I`m not sure this is correct

**Comment by deepu105** [comment]
can you check if this works with session based auth?

**Comment by deepu105** [comment]
cc @jdubois this is with JWT so might be a bug

**Comment by jdubois** [comment]
Yes I haven't got the time to check, but there is one logical explanation.
With JWT you haven't got a User object, as it works without the user management code - that's the whole point of JWT, and why microservices scales with JWT!
So with Spring Security, instead of having a "Pincipal" on which you can get the username, you just got a "Principal" which is a String (and that String is the user's login). So that request would fail. It should be coded without the ".username" when JWT is used.
-> @thiagogcm can you check with removing the ".username"?

**Comment by ruddell** [comment]
I looked into the issue and by removing the .username, the query is successful and findByUserisCurrentUser returns the correct results.

**Comment by poolebu** [comment]
I ran into this exact same error when creating a test for a service . I chose the `"authenticationType": "session"`. Not jwt.

Tried to authenticate in the test like:

```
// Log User
        SecurityContext securityContext = SecurityContextHolder.createEmptyContext();
        securityContext.setAuthentication(new UsernamePasswordAuthenticationToken("admin", "admin"));
        SecurityContextHolder.setContext(securityContext);
        Authentication authentication = SecurityContextHolder.getContext().getAuthentication();

        // Get all the requests
        restRequestMockMvc.perform(get("/api/requests-logged-user").with(authentication(authentication)))
            .andExpect(status().isOk())
.
.
.
```
It was fixed after removing the `.username`
Just reporting in case it's a bug .

**Comment by poolebu** [comment]
Update: If I remove the .username the query does not work, somehow the test did not give error, but the query did not return what it suppose to. If compiled and tested using swager's request, it gives internal error. 

Currently I'm ignoring the test untill I can figure whats wrong. Here is how I'm doing the test
