### ISSUE TITLE
App should fail when unable to connect to Registry

### ISSUE THREAD

**Issue by gmarziou** [jhipster/generator-jhipster#3176]
##### **Overview of the issue**

Microservices apps and gateways should fail when unable to connect to Registry

##### **Suggest a Fix** 

By setting this in bootstrap.yml

     spring.cloud.config.fail-fast: true

App will fail this way:

~~~
java.lang.IllegalStateException: Could not locate PropertySource and the fail fast property is set, failing
	at org.springframework.cloud.config.client.ConfigServicePropertySourceLocator.locate(ConfigServicePropertySourceLocator.java:110)

Caused by: org.springframework.web.client.ResourceAccessException: I/O error on GET request for "http://localhost:8761/config/srv1/dev/master": Connection refused; nested exception is java.net.ConnectException: Connection refused
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:607)

Caused by: java.net.ConnectException: Connection refused


~~~

**Comment by jdubois** [comment]
Excellent !!!
Is there also an option to wait a couple of minutes and retry?

**Comment by gmarziou** [comment]
Yes there is a retry but I haven't tested it yet and it's important because I'm wondering whether it can fail fast also later after app successfully started and when registry goes down.

**Comment by PierreBesson** [comment]
I just tested it and there is no retry.

**Comment by PierreBesson** [comment]
Spoken too fast, it seems that there is a retry config...

**Comment by cm325** [comment]
I'm getting this error, but don't understand what to fix, I'm running jhipster for the first time

**Comment by jdubois** [comment]
Please open up a new ticket if you have a bug.

**Comment by matamagu** [comment]
I too get the same error.. I am trying build a microservices application following the instructions in https://www.youtube.com/watch?v=m0eZcfLHQyg

Here are the steps I followed..

1) Started JHipster Registr -> SUCCESS
2) Built a simple microservice. The application fails with below error message...


2016-06-22 10:56:43.796 ERROR 3456 --- [  restartedMain] o.s.boot.SpringApplication               : Application startup failed

java.lang.IllegalStateException: Could not locate PropertySource and the fail fast property is set, failing

**Comment by jdubois** [comment]
Please open up a ticket if you have a bug!
