### ISSUE TITLE
Error on create an app with jhipster bower.json

### ISSUE THREAD

**Issue by bosofelipe** [jhipster/generator-jhipster#3208]
##### **Overview of the issue**

Not work the jhispter project creation

##### **Motivation for or Use Case** 

I need create an app but bower crash the creation

##### **JHipster Version(s)** 

last version

##### **Reproduce the error** 

When i run "yo jhipster" show this error

```
   create bower.json
fs.js:584
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: EACCES: permission denied, open '/home/felipeboso/Documentos/Code/newkoalapp/bower.json'
    at Error (native)
    at Object.fs.openSync (fs.js:584:18)
    at Object.fs.writeFileSync (fs.js:1224:33)
    at write (/usr/lib/node_modules/generator-jhipster/node_modules/mem-fs-editor/lib/actions/commit.js:14:6)
    at DestroyableTransform._transform (/usr/lib/node_modules/generator-jhipster/node_modules/mem-fs-editor/lib/actions/commit.js:43:7)
    at DestroyableTransform.Transform._read (/usr/lib/node_modules/generator-jhipster/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:159:10)
    at DestroyableTransform.Transform._write (/usr/lib/node_modules/generator-jhipster/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:147:83)
    at doWrite (/usr/lib/node_modules/generator-jhipster/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:313:64)
    at writeOrBuffer (/usr/lib/node_modules/generator-jhipster/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:302:5)
    at DestroyableTransform.Writable.write (/usr/lib/node_modules/generator-jhipster/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:241:11)
```

What do I do?

**Comment by deepu105** [comment]
This is not a JHipster issue, look at the error logs, seems like you are executing something on a directory where you do not have access. If you are on mac/linux try with sudo else try to run in a folder where you have access

**Comment by bosofelipe** [comment]
Sorry I just run chmod 777 on folder an app working now!

tks @deepu105 !
