### ISSUE TITLE
"No qualifying bean of type [**Mapper] found for dependency" when use DTO

### ISSUE THREAD

**Issue by spyhunter88** [jhipster/generator-jhipster#3255]
Basically, the Mapper instance does not Inject into Service.
It does not start when startup in Eclipse after I add DTO, I don't know the many-to-one relationship cause this or not, but this exception come from Mapper in DTO.

Of course it runs from Eclipse before I add Entity with DTO.

```
2016-03-25 13:37:50.357  WARN 900 --- [  restartedMain] ationConfigEmbeddedWebApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'requirementService': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: private claimman2.web.rest.mapper.RequirementMapper claimman2.service.RequirementService.requirementMapper; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type [claimman2.web.rest.mapper.RequirementMapper] found for dependency: expected at least 1 bean which qualifies as autowire candidate for this dependency. Dependency annotations: {@javax.inject.Inject()}
2016-03-25 13:37:50.363  INFO 900 --- [  restartedMain] claimman2.config.CacheConfiguration      : Remove Cache Manager metrics
2016-03-25 13:37:50.372  INFO 900 --- [  restartedMain] claimman2.config.CacheConfiguration      : Closing Cache Manager
2016-03-25 13:37:50.372  WARN 900 --- [  restartedMain] .s.c.a.CommonAnnotationBeanPostProcessor : Invocation of destroy method failed on bean with name 'cacheConfiguration': java.lang.NullPointerException
2016-03-25 13:37:50.416  WARN 900 --- [ost-startStop-1] o.a.c.loader.WebappClassLoaderBase       : The web application [ROOT] appears to have started a thread named [Abandoned connection cleanup thread] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 java.lang.Object.wait(Native Method)
 java.lang.ref.ReferenceQueue.remove(Unknown Source)
 com.mysql.jdbc.AbandonedConnectionCleanupThread.run(AbandonedConnectionCleanupThread.java:43)
2016-03-25 13:37:50.418  WARN 900 --- [ost-startStop-1] o.a.c.loader.WebappClassLoaderBase       : Failed to check for ThreadLocal references for web application [ROOT]

java.lang.UnsupportedOperationException: null
	at com.zaxxer.hikari.util.FastList.iterator(FastList.java:209)
	at org.apache.catalina.loader.WebappClassLoaderBase.loadedByThisOrChild(WebappClassLoaderBase.java:2170)
	at org.apache.catalina.loader.WebappClassLoaderBase.checkThreadLocalMapForLeaks(WebappClassLoaderBase.java:2080)
	at org.apache.catalina.loader.WebappClassLoaderBase.checkThreadLocalsForLeaks(WebappClassLoaderBase.java:2035)
	at org.apache.catalina.loader.WebappClassLoaderBase.clearReferences(WebappClassLoaderBase.java:1550)
	at org.apache.catalina.loader.WebappClassLoaderBase.stop(WebappClassLoaderBase.java:1496)
	at org.apache.catalina.loader.WebappLoader.stopInternal(WebappLoader.java:446)
	at org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:224)
	at org.apache.catalina.core.StandardContext.stopInternal(StandardContext.java:5517)
	at org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:224)
	at org.apache.catalina.core.ContainerBase$StopChild.call(ContainerBase.java:1424)
	at org.apache.catalina.core.ContainerBase$StopChild.call(ContainerBase.java:1413)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

2016-03-25 13:37:50.440 ERROR 900 --- [  restartedMain] o.s.boot.SpringApplication               : Application startup failed

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'requirementService': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: private claimman2.web.rest.mapper.RequirementMapper claimman2.service.RequirementService.requirementMapper; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type [claimman2.web.rest.mapper.RequirementMapper] found for dependency: expected at least 1 bean which qualifies as autowire candidate for this dependency. Dependency annotations: {@javax.inject.Inject()}
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:334)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1214)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:543)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:772)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:839)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:538)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:118)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:766)
	at org.springframework.boot.SpringApplication.createAndRefreshContext(SpringApplication.java:361)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:307)
	at claimman2.Claimman2App.main(Claimman2App.java:69)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.springframework.boot.devtools.restart.RestartLauncher.run(RestartLauncher.java:49)
Caused by: org.springframework.beans.factory.BeanCreationException: Could not autowire field: private claimman2.web.rest.mapper.RequirementMapper claimman2.service.RequirementService.requirementMapper; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type [claimman2.web.rest.mapper.RequirementMapper] found for dependency: expected at least 1 bean which qualifies as autowire candidate for this dependency. Dependency annotations: {@javax.inject.Inject()}
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:573)
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:88)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:331)
	... 20 common frames omitted
Caused by: org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type [claimman2.web.rest.mapper.RequirementMapper] found for dependency: expected at least 1 bean which qualifies as autowire candidate for this dependency. Dependency annotations: {@javax.inject.Inject()}
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.raiseNoSuchBeanDefinitionException(DefaultListableBeanFactory.java:1373)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1119)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1014)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:545)
	... 22 common frames omitted

2016-03-25 13:37:50.449  WARN 900 --- [  restartedMain] o.s.boot.SpringApplication               : Error handling failed (Error creating bean with name 'delegatingApplicationListener' defined in class path resource [org/springframework/security/config/annotation/web/configuration/WebSecurityConfiguration.class]: BeanPostProcessor before instantiation of bean failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.cache.annotation.ProxyCachingConfiguration': Initialization of bean failed; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No bean named 'org.springframework.context.annotation.ConfigurationClassPostProcessor.importRegistry' is defined)

```

##### **JHipster Version(s)** 
JHipster 3.0.0

My yo.rc.json
```
{
  "generator-jhipster": {
    "jhipsterVersion": "3.0.0",
    "baseName": "claimman2",
    "packageName": "claimman2",
    "packageFolder": "claimman2",
    "serverPort": "8080",
    "authenticationType": "session",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": "no",
    "websocket": "no",
    "databaseType": "sql",
    "devDatabaseType": "h2Memory",
    "prodDatabaseType": "mysql",
    "searchEngine": "no",
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "rememberMeKey": "",
    "useSass": false,
    "applicationType": "monolith",
    "testFrameworks": [
      "gatling"
    ],
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en"
    ]
  }
}
```

And the entity config:
Claim
```
{
    "relationships": [
        {
            "relationshipName": "requirement",
            "otherEntityName": "requirement",
            "relationshipType": "one-to-many",
            "otherEntityRelationshipName": "claim"
        },
        {
            "relationshipName": "checkPoint",
            "otherEntityName": "checkPoint",
            "relationshipType": "one-to-many",
            "otherEntityRelationshipName": "claim"
        },
        {
            "relationshipName": "payment",
            "otherEntityName": "payment",
            "relationshipType": "one-to-many",
            "otherEntityRelationshipName": "claim"
        },
        {
            "relationshipName": "paymentAllocation",
            "otherEntityName": "paymentAllocation",
            "relationshipType": "one-to-many",
            "otherEntityRelationshipName": "claim"
        }
    ],
    "fields": [
        {
            "fieldName": "buName",
            "fieldType": "String"
        },
        {
            "fieldName": "participantClaim",
            "fieldType": "String"
        },
        {
            "fieldName": "unitClaim",
            "fieldType": "String"
        },
        {
            "fieldName": "receiptAccount",
            "fieldType": "String"
        },
        {
            "fieldName": "prepaid",
            "fieldType": "Boolean"
        },
        {
            "fieldName": "ftgProgramCode",
            "fieldType": "String",
            "fieldValidateRules": []
        },
        {
            "fieldName": "vendorProgramCode",
            "fieldType": "String"
        },
        {
            "fieldName": "programName",
            "fieldType": "String"
        },
        {
            "fieldName": "programType",
            "fieldType": "String"
        },
        {
            "fieldName": "paymentMethod",
            "fieldType": "String"
        },
        {
            "fieldName": "requireClaimdoc",
            "fieldType": "Boolean"
        },
        {
            "fieldName": "vendorName",
            "fieldType": "String"
        },
        {
            "fieldName": "productLine",
            "fieldType": "String"
        },
        {
            "fieldName": "startDate",
            "fieldType": "LocalDate",
            "fieldValidateRules": [
                "required"
            ]
        },
        {
            "fieldName": "endDate",
            "fieldType": "LocalDate",
            "fieldValidateRules": [
                "required"
            ]
        },
        {
            "fieldName": "claimDeadlineDate",
            "fieldType": "LocalDate"
        },
        {
            "fieldName": "status",
            "fieldType": "Integer"
        },
        {
            "fieldName": "editStatus",
            "fieldType": "String"
        },
        {
            "fieldName": "claimType",
            "fieldType": "String"
        },
        {
            "fieldName": "note",
            "fieldType": "String"
        },
        {
            "fieldName": "programContent",
            "fieldType": "String"
        },
        {
            "fieldName": "claimCurrencyUnit",
            "fieldType": "String"
        },
        {
            "fieldName": "exchangeRate",
            "fieldType": "Double"
        },
        {
            "fieldName": "claimItem",
            "fieldType": "String"
        },
        {
            "fieldName": "promiseAmount",
            "fieldType": "Double"
        },
        {
            "fieldName": "promiseDate",
            "fieldType": "LocalDate"
        },
        {
            "fieldName": "submitClaimAmount",
            "fieldType": "Double"
        },
        {
            "fieldName": "submitClaimDate",
            "fieldType": "LocalDate"
        },
        {
            "fieldName": "vendorConfirmAmount",
            "fieldType": "Double"
        },
        {
            "fieldName": "vendorConfirmDate",
            "fieldType": "LocalDate"
        },
        {
            "fieldName": "currentAvailableAmount",
            "fieldType": "Double"
        },
        {
            "fieldName": "currentAvailableDate",
            "fieldType": "LocalDate"
        },
        {
            "fieldName": "createBy",
            "fieldType": "Integer"
        },
        {
            "fieldName": "createTime",
            "fieldType": "LocalDate"
        },
        {
            "fieldName": "lastEditBy",
            "fieldType": "Integer"
        },
        {
            "fieldName": "lastEditTime",
            "fieldType": "LocalDate"
        },
        {
            "fieldName": "lastApproveBy",
            "fieldType": "Integer"
        },
        {
            "fieldName": "lastApproveTime",
            "fieldType": "LocalDate"
        },
        {
            "fieldName": "previousStatus",
            "fieldType": "String"
        }
    ],
    "changelogDate": "20160325032030",
    "dto": "no",
    "service": "serviceClass",
    "entityTableName": "claim",
    "pagination": "no"
}
```
and Requirement
```
{
    "relationships": [
        {
            "relationshipName": "claim",
            "otherEntityName": "claim",
            "relationshipType": "many-to-one",
            "otherEntityField": "id"
        }
    ],
    "fields": [
        {
            "fieldName": "name",
            "fieldType": "String"
        },
        {
            "fieldName": "operation",
            "fieldType": "String"
        },
        {
            "fieldName": "target",
            "fieldType": "Double"
        },
        {
            "fieldName": "unit",
            "fieldType": "String"
        },
        {
            "fieldName": "reportDate",
            "fieldType": "LocalDate"
        },
        {
            "fieldName": "actualAmount",
            "fieldType": "Double"
        },
        {
            "fieldName": "claimAmount",
            "fieldType": "Double"
        },
        {
            "fieldName": "note",
            "fieldType": "String"
        },
        {
            "fieldName": "createBy",
            "fieldType": "Integer"
        },
        {
            "fieldName": "createTime",
            "fieldType": "LocalDate"
        },
        {
            "fieldName": "lastEditBy",
            "fieldType": "Integer"
        },
        {
            "fieldName": "lastEditTime",
            "fieldType": "LocalDate"
        },
        {
            "fieldName": "lastUpdateCheckId",
            "fieldType": "Integer"
        }
    ],
    "changelogDate": "20160325054308",
    "dto": "mapstruct",
    "service": "serviceClass",
    "entityTableName": "requirement",
    "pagination": "no"
}
```

**Comment by spyhunter88** [comment]
Sorry, I can not compile by maven because multiple JAVA JRE, then then target/generated-source does not appear. This now be resolved.
