### ISSUE TITLE
Gulp test fails on Ubuntu

### ISSUE THREAD

**Issue by ARAtIntBitTech** [jhipster/generator-jhipster#3303]
When I do a gulp test, the project fails with the below error.

> Error: spyOn could not find an object to spy upon for logout()
>         at /workspace/WebServices/src/test/javascript/spec/components/auth/auth.services.spec.js:9
>     TypeError: 'undefined' is not an object (evaluating '$httpBackend.verifyNoOutstandingExpectation')
>         at /workspace/WebServices/src/test/javascript/spec/components/auth/auth.services.spec.js:9
> PhantomJS 1.9.8 (Linux 0.0.0): Executed 53 of 53 (53 FAILED) (0 secs / 0.776 secs)
> PhantomJS 1.9.8 (Linux 0.0.0): Executed 53 of 53 (53 FAILED) ERROR (1 min 8.425 secs / 0.776 secs)
> [20:17:05] 'test' errored after 1.23 min

~~~json
{
  "generator-jhipster": {
    "baseName": "HelloWebServices",
    "packageName": "com.intbit.hello",
    "packageFolder": "com/intbit/hello",
    "authenticationType": "oauth2",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": "no",
    "websocket": "no",
    "databaseType": "sql",
    "devDatabaseType": "postgresql",
    "prodDatabaseType": "postgresql",
    "searchEngine": "no",
    "useSass": false,
    "buildTool": "maven",
    "frontendBuilder": "gulp",
    "enableTranslation": true,
    "enableSocialSignIn": false,
    "testFrameworks": [
      "gatling"
    ]
  }
}
~~~

JHipster Version(s)
v2.27.2

Ubuntu LTS 14.04

The same code when executed on OSX works. So is there anything different/particular that we need to install in Ubuntu.

**Comment by pascalgrimaud** [comment]
Just tested with our [devbox](https://github.com/jhipster/jhipster-devbox) (Ubuntu 14.04 LTS) and it works well
Can you check all install tools like I did.
If it doesn't work, can you test with our Devbox ?

```shell
vagrant@vagrant-ubuntu-trusty-64:~/workspace$ java --version
Unrecognized option: --version
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
vagrant@vagrant-ubuntu-trusty-64:~/workspace$ java -version
java version "1.8.0_66"
Java(TM) SE Runtime Environment (build 1.8.0_66-b17)
Java HotSpot(TM) 64-Bit Server VM (build 25.66-b17, mixed mode)
vagrant@vagrant-ubuntu-trusty-64:~/workspace$ node -v
v4.2.2
vagrant@vagrant-ubuntu-trusty-64:~/workspace$ npm -v
3.5.1
vagrant@vagrant-ubuntu-trusty-64:~/workspace$ bower -v
1.6.8
vagrant@vagrant-ubuntu-trusty-64:~/workspace$ yo --version
1.5.0
vagrant@vagrant-ubuntu-trusty-64:~/workspace$ gulp -v
[21:04:58] CLI version 3.9.0
[21:04:58] Local version 3.9.0
```

```shell
vagrant@vagrant-ubuntu-trusty-64:~/workspace/test/07-test$ gulp test
[21:09:11] Using gulpfile ~/workspace/test/07-test/gulpfile.js
[21:09:11] Starting 'wiredep:test'...
[21:09:11] Starting 'ngconstant:dev'...
[21:09:11] Finished 'ngconstant:dev' after 165 ms
[21:09:11] Finished 'wiredep:test' after 186 ms
[21:09:11] Starting 'test'...
30 03 2016 21:09:14.607:INFO [karma]: Karma v0.13.19 server started at http://localhost:9876/
30 03 2016 21:09:14.613:INFO [launcher]: Starting browser PhantomJS
30 03 2016 21:09:14.971:INFO [PhantomJS 1.9.8 (Linux 0.0.0)]: Connected on socket /#iV9IaE1bG1AMrQjiAAAA with id 93985682
30 03 2016 21:09:15.772:WARN [web-server]: 404: /bower_components/angular-i18n/angular-locale_en.js
 PhantomJS 1.9.8 (Linux 0.0.0): Executed 10 of 40 SUCCESS (0 secs / 0.322 secs)
.
DUMP: 'background-color: rgb(153, 255, 0); '
 PhantomJS 1.9.8 (Linux 0.0.0): Executed 40 of 40 SUCCESS (0 secs / 0.993 secs)
.
PhantomJS 1.9.8 (Linux 0.0.0): Executed 40 of 40 SUCCESS (2.598 secs / 0.993 secs)
[21:09:20] Finished 'test' after 8.58 s
vagrant@vagrant-ubuntu-trusty-64:~/workspace/test/07-test$ cat .yo-rc.json 
{
  "generator-jhipster": {
    "baseName": "HelloWebServices",
    "packageName": "com.intbit.hello",
    "packageFolder": "com/intbit/hello",
    "authenticationType": "oauth2",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": "no",
    "websocket": "no",
    "databaseType": "sql",
    "devDatabaseType": "postgresql",
    "prodDatabaseType": "postgresql",
    "searchEngine": "no",
    "useSass": false,
    "buildTool": "maven",
    "frontendBuilder": "gulp",
    "enableTranslation": true,
    "enableSocialSignIn": false,
    "testFrameworks": [
      "gatling"
    ],
    "rememberMeKey": "c90d54f57b5fac2b7a469c62c8d2f5ddcf52d384"
  }
}vagrant@vagrant-ubuntu-trusty-64:~/workspace/test/07-test$
```

**Comment by ARAtIntBitTech** [comment]
@pascalgrimaud 
I just got the versions for each component on my machine

```
ar@ar-server:~/Documents/STSWorkspace/WebServices$ java -version
openjdk version "1.8.0_72-internal"
OpenJDK Runtime Environment (build 1.8.0_72-internal-b15)
OpenJDK 64-Bit Server VM (build 25.72-b15, mixed mode)
ar@ar-server:~/Documents/STSWorkspace/WebServices$ node -v
v5.8.0
ar@ar-server:~/Documents/STSWorkspace/WebServices$ npm -v
3.8.3
ar@ar-server:~/Documents/STSWorkspace/WebServices$ bower -v
1.7.7
ar@ar-server:~/Documents/STSWorkspace/WebServices$ yo --version
1.7.0
ar@ar-server:~/Documents/STSWorkspace/WebServices$ gulp -v
[19:46:24] CLI version 3.9.1
[19:46:24] Local version 3.9.0
ar@ar-server:~/Documents/STSWorkspace/WebServices$ gulp test > gulptest.txt
ar@ar-server:~/Documents/STSWorkspace/WebServices$ cat .yo-rc.json 
{
  "generator-jhipster": {
    "baseName": "WebServices",
    "packageName": "com.intbit.hello",
    "packageFolder": "com/intbit/hello",
    "authenticationType": "oauth2",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": "no",
    "websocket": "no",
    "databaseType": "sql",
    "devDatabaseType": "postgresql",
    "prodDatabaseType": "postgresql",
    "searchEngine": "no",
    "useSass": false,
    "buildTool": "maven",
    "frontendBuilder": "gulp",
    "enableTranslation": true,
    "enableSocialSignIn": false,
    "testFrameworks": [
      "gatling"
    ]
  }
}
```

The code in the file that has the problem

STSWorkspace/WebServices/src/test/javascript/spec/components/auth/auth.services.sp‌​ec.js
```
'use strict';

describe('Service Tests', function () {
    beforeEach(mockI18nCalls);
    beforeEach(mockScriptsCalls);

    describe('Auth', function () {
        var $httpBackend, spiedLocalStorageService, authService, spiedAuthServerProvider;

        beforeEach(inject(function($injector, localStorageService, Auth, AuthServerProvider) {
            $httpBackend = $injector.get('$httpBackend');
            spiedLocalStorageService = $injector.get(localStorageService);
            authService = $injector.get(Auth);
            spiedAuthServerProvider = $injector.get(AuthServerProvider);

            $httpBackend.expectPOST(/api\/logout\?cacheBuster=\d+/).respond(200, '');
        }));
        //make sure no expectations were missed in your tests.
        //(e.g. expectGET or expectPOST)
        afterEach(function() {
            $httpBackend.verifyNoOutstandingExpectation();
            $httpBackend.verifyNoOutstandingRequest();
        });
        
        it('should call backend on logout then call authServerProvider.logout', function(){
            //GIVEN
            //Set spy
            spyOn(spiedAuthServerProvider, 'logout').and.callThrough();
            spyOn(spiedLocalStorageService, "clearAll").and.callThrough();

            //WHEN
            authService.logout();
            //flush the backend to "execute" the request to do the expectedGET assertion.
            $httpBackend.flush();

            //THEN
            expect(spiedAuthServerProvider.logout).toHaveBeenCalled();
            expect(spiedLocalStorageService.clearAll).toHaveBeenCalled();
        });

    });
});
```

Last few lines of the output when I executed gulp test > test.txt. It produced a 27mb file ...

```
b04e2d6db7fd0eda37042440c%3A1801%0A%20%20%20%20at%20http%3A%2F%2Flocalhost%3A9876%2Fabsolute%2Fhome%2Far%2FDocuments%2FWorkspace%2FWebServices%2Fnode_modules%2Fjasmine-core%2Flib%2Fjasmine-core%2Fjasmine.js%3F578a1e5ff14db21b04e2d6db7fd0eda37042440c%3A1745%0A%20%20%20%20at%20http%3A%2F%2Flocalhost%3A9876%2Fabsolute%2Fhome%2Far%2FDocuments%2FWorkspace%2FWebServices%2Fnode_modules%2Fjasmine-core%2Flib%2Fjasmine-core%2Fjasmine.js%3F578a1e5ff14db21b04e2d6db7fd0eda37042440c%3A2348
	    at /home/ar/Documents/Workspace/WebServices/src/main/webapp/bower_components/angular/angular.js:9
	    at forEach (/home/ar/Documents/Workspace/WebServices/src/main/webapp/bower_components/angular/angular.js:9)
	    at loadModules (/home/ar/Documents/Workspace/WebServices/src/main/webapp/bower_components/angular/angular.js:9)
	    at createInjector (/home/ar/Documents/Workspace/WebServices/src/main/webapp/bower_components/angular/angular.js:9)
	    at workFn (/home/ar/Documents/Workspace/WebServices/src/main/webapp/bower_components/angular-mocks/angular-mocks.js:9)
	Error: spyOn could not find an object to spy upon for logout()
	    at /home/ar/Documents/Workspace/WebServices/src/test/javascript/spec/components/auth/auth.services.spec.js:9
	TypeError: 'undefined' is not an object (evaluating '$httpBackend.verifyNoOutstandingExpectation')
	    at /home/ar/Documents/Workspace/WebServices/src/test/javascript/spec/components/auth/auth.services.spec.js:9
PhantomJS 1.9.8 (Linux 0.0.0): Executed 53 of 53 (53 FAILED) (0 secs / 0.817 secs)
PhantomJS 1.9.8 (Linux 0.0.0): Executed 53 of 53 (53 FAILED) ERROR (3.097 secs / 0.817 secs)
[1A[2KPhantomJS 1.9.8 (Linux 0.0.0): Executed 53 of 53 (53 FAILED) ERROR (3.097 secs / 0.817 secs)
[19:47:17] 'test' errored after 6.92 s
[19:47:17] Error: 1
    at formatError (/usr/local/lib/node_modules/gulp/bin/gulp.js:169:10)
    at Gulp.<anonymous> (/usr/local/lib/node_modules/gulp/bin/gulp.js:195:15)
    at emitOne (events.js:90:13)
    at Gulp.emit (events.js:182:7)
    at Gulp.Orchestrator._emitTaskDone (/home/ar/Documents/Workspace/WebServices/node_modules/gulp/node_modules/orchestrator/index.js:264:8)
    at /home/ar/Documents/Workspace/WebServices/node_modules/gulp/node_modules/orchestrator/index.js:275:23
    at finish (/home/ar/Documents/Workspace/WebServices/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:21:8)
    at cb (/home/ar/Documents/Workspace/WebServices/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:29:3)
    at removeAllListeners (/home/ar/Documents/Workspace/WebServices/node_modules/karma/lib/server.js:333:7)
    at Server.<anonymous> (/home/ar/Documents/Workspace/WebServices/node_modules/karma/lib/server.js:344:9)
    at Server.g (events.js:273:16)
    at emitNone (events.js:85:20)
    at Server.emit (events.js:179:7)
    at emitCloseNT (net.js:1527:8)
    at _combinedTickCallback (node.js:374:13)
    at process._tickCallback (node.js:401:11)
```

**Comment by deepu105** [comment]
Pascal he is using JH 2.x version I guess

**Comment by pascalgrimaud** [comment]
@deepu105 : yes, I tried to reproduce on 2.27.2

@ARAtIntBitTech : the main difference I can see, is the node+npm version. I used a node LTS instead of the latest => can you give a try with LTS?

**Comment by PierreBesson** [comment]
@ARAtIntBitTech, I have failed to reproduce the error.

**Comment by deepu105** [comment]
It does seem like a node environment issue, but I'm getting a different
error
>
> 31 03 2016 16:26:22.167:ERROR [launcher]: No binary for PhantomJS browser
> on your platform.
>   Please, set "PHANTOMJS_BIN" env variable.


Thanks & Regards,
Deepu

**Comment by wmarques** [comment]
Same as @pascalgrimaud, tried with JHipster Devbox and works well with 2.27.0. I'm trying to update node

**Comment by pascalgrimaud** [comment]
I'm closing this issue, as I think it's a environment problem, and none of us manage to reproduce your issue.
Plz give a try to our Devbox and reopen this ticket if you have the same error
