### ISSUE TITLE
Wrong dependencies on spring cloud

### ISSUE THREAD

**Issue by gmarziou** [jhipster/generator-jhipster#3316]
##### **Overview of the issue**

The way we declare our dependencies on spring-cloud is wrong.

I found it by having this exception in a gateway:

~~~
java.lang.NoSuchMethodError: com.netflix.servo.monitor.Monitors.isObjectRegistered(Ljava/lang/String;Ljava/lang/Object;)Z
	at com.netflix.discovery.shared.transport.decorator.RetryableEurekaHttpClient.shutdown(RetryableEurekaHttpClient.java:91)
	at com.netflix.discovery.shared.transport.TransportUtils.shutdown(TransportUtils.java:40)
	at com.netflix.discovery.shared.transport.decorator.SessionedEurekaHttpClient.execute(SessionedEurekaHttpClient.java:70)
	at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator.sendHeartBeat(EurekaHttpClientDecorator.java:89)
	at com.netflix.discovery.DiscoveryClient.renew(DiscoveryClient.java:823)
	at com.netflix.discovery.DiscoveryClient$HeartbeatThread.run(DiscoveryClient.java:1379)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
~~~

This was due to using com.netflix.servo:servo-core:jar:0.7.2 rather than 0.10.1

According this recent issue, the right way to depend on spring-boot is by importing their bom:

https://github.com/spring-cloud/spring-cloud-netflix/issues/938

##### **JHipster Version(s)** 

3.0 today's master

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder** 

~~~json
{
  "generator-jhipster": {
    "jhipsterVersion": "3.0.0",
    "baseName": "gateway",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "authenticationType": "jwt",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": "no",
    "websocket": "no",
    "databaseType": "sql",
    "devDatabaseType": "h2Memory",
    "prodDatabaseType": "postgresql",
    "searchEngine": "no",
    "buildTool": "maven",
    "jwtSecretKey": "8236c1377cd345f2a83c41efbd726577389066a1",
    "useSass": false,
    "enableTranslation": false,
    "applicationType": "gateway",
    "testFrameworks": [],
    "enableSocialSignIn": false,
    "serverPort": 8080,
    "jhiPrefix": "jhi"
  }
}
~~~

##### **Suggest a Fix** 

I will submit a PR for maven, I'll need some help for gradle.

Import the bom and do not use ${spring-cloud.version} in dependencies like this:

~~~xml
    <properties>
        <spring-cloud.version>Brixton.RC1</spring-cloud.version>
    </properties>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.springframework.cloud</groupId>
                <artifactId>spring-cloud-dependencies</artifactId>
                <version>${spring-cloud.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <dependencies>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-zuul</artifactId>
        </dependency>
~~~

**Comment by jhulick** [comment]
@gmarziou This is similar to the issue on the registry I created a PR for: https://github.com/jhipster/jhipster-registry/pull/20. Using Spring Cloud Release Train management, plus your suggestions for boot, might need to be checked on all the jhipster-* repos.

**Comment by gmarziou** [comment]
Yes it's similar, using the "parent" approach makes sense for the registry as it is a spring cloud only app, for the generator the dependencyManagement is probably easier in order to manage both monolith and microservices apps.
