### ISSUE TITLE
Not able to start the project after creating the custom entties

### ISSUE THREAD

**Issue by sparun160782** [jhipster/generator-jhipster#3349]
Hi All

##### **Overview of the issue**
I have created an application with help of JHipster, it was fine while initial start of the application.

After creating the custom entity I have encountered 2 issues

##### **JHipster Version**  - 3

**First Issue ::** Not able to find the entity in the classpath the exception given below but this issue has been cleared by cleaning the project

```
c.m.s.c.liquibase.AsyncSpringLiquibase  [0;39m Liquibase could not start correctly, your database is NOT ready: liquibase.exception.SetupException: Error Reading Migration File: class path resource [config/liquibase/changelog/20160403132658_added_entity_School.xml] cannot be resolved to URL because it does not exist

liquibase.exception.ChangeLogParseException: liquibase.exception.SetupException: Error Reading Migration File: class path resource [config/liquibase/changelog/20160403132658_added_entity_School.xml] cannot be resolved to URL because it does not exist
    at liquibase.parser.core.xml.AbstractChangeLogParser.parse(AbstractChangeLogParser.java:27)
    at liquibase.Liquibase.getDatabaseChangeLog(Liquibase.java:227)
    at liquibase.Liquibase.update(Liquibase.java:202)
    at liquibase.Liquibase.update(Liquibase.java:192)
    at liquibase.integration.spring.SpringLiquibase.performUpdate(SpringLiquibase.java:434)
    at liquibase.integration.spring.SpringLiquibase.afterPropertiesSet(SpringLiquibase.java:391)
    at com.masscom.school.config.liquibase.AsyncSpringLiquibase.initDb(AsyncSpringLiquibase.java:66)
    at com.masscom.school.config.liquibase.AsyncSpringLiquibase.lambda$0(AsyncSpringLiquibase.java:49)
    at com.masscom.school.async.ExceptionHandlingAsyncTaskExecutor.lambda$1(ExceptionHandlingAsyncTaskExecutor.java:47)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at java.lang.Thread.run(Unknown Source)
Caused by: liquibase.exception.SetupException: Error Reading Migration File: class path resource [config/liquibase/changelog/20160403132658_added_entity_School.xml] cannot be resolved to URL because it does not exist
    at liquibase.changelog.DatabaseChangeLog.handleChildNode(DatabaseChangeLog.java:269)
    at liquibase.changelog.DatabaseChangeLog.load(DatabaseChangeLog.java:230)
    at liquibase.parser.core.xml.AbstractChangeLogParser.parse(AbstractChangeLogParser.java:25)
    ... 11 common frames omitted
Caused by: liquibase.exception.ChangeLogParseException: Error Reading Migration File: class path resource [config/liquibase/changelog/20160403132658_added_entity_School.xml] cannot be resolved to URL because it does not exist
    at liquibase.parser.core.xml.XMLChangeLogSAXParser.parseToNode(XMLChangeLogSAXParser.java:112)
    at liquibase.parser.core.xml.AbstractChangeLogParser.parse(AbstractChangeLogParser.java:17)
    at liquibase.changelog.DatabaseChangeLog.include(DatabaseChangeLog.java:404)
    at liquibase.changelog.DatabaseChangeLog.handleChildNode(DatabaseChangeLog.java:267)
    ... 13 common frames omitted
Caused by: java.io.FileNotFoundException: class path resource [config/liquibase/changelog/20160403132658_added_entity_School.xml] cannot be resolved to URL because it does not exist
    at org.springframework.core.io.ClassPathResource.getURL(ClassPathResource.java:187)
    at liquibase.integration.spring.SpringLiquibase$SpringResourceOpener.getResourcesAsStream(SpringLiquibase.java:164)
    at liquibase.util.StreamUtil.singleInputStream(StreamUtil.java:182)
    at liquibase.parser.core.xml.XMLChangeLogSAXParser.parseToNode(XMLChangeLogSAXParser.java:93)
    ... 16 common frames omitted

36mcom.masscom.school.SchoolRegApp  [0;39m Running with Spring profile(s) : [dev]
[2m2016-04-03 19:46:15.678[0;39m [32mDEBUG[0;39m [35m8604[0;39m [2m---[0;39m [2m[  restartedMain][0;39m [36mc.m.school.config.CacheConfiguration    [0;39m [2m:[0;39m Starting Ehcache
[2m2016-04-03 19:46:15.681[0;39m [32mDEBUG[0;39m [35m8604[0;39m [2m---[0;39m [2m[  restartedMain][0;39m [36mc.m.school.config.CacheConfiguration    [0;39m [2m:[0;39m Registering Ehcache Metrics gauges
[2m2016-04-03 19:46:16.388[0;39m [32mDEBUG[0;39m [35m8604[0;39m [2m---[0;39m [2m[  restartedMain][0;39m [36mc.m.s.c.apidoc.SwaggerConfiguration     [0;39m [2m:[0;39m Starting Swagger
[2m2016-04-03 19:46:16.404[0;39m [32mDEBUG[0;39m [35m8604[0;39m [2m---[0;39m [2m[  restartedMain][0;39m [36mc.m.s.c.apidoc.SwaggerConfiguration     [0;39m [2m:[0;39m Started Swagger in 16 ms
[2m2016-04-03 19:46:18.139[0;39m [32m INFO[0;39m [35m8604[0;39m [2m---[0;39m [2m[  restartedMain][0;39m [36mcom.masscom.school.SchoolRegApp         [0;39m [2m:[0;39m Started SchoolRegApp in 19.116 seconds (JVM running for 20.052)
[2m2016-04-03 19:46:18.146[0;39m [32m INFO[0;39m [35m8604[0;39m [2m---[0;39m [2m[  restartedMain][0;39m [36mcom.masscom.school.SchoolRegApp         [0;39m [2m:[0;39m 
----------------------------------------------------------
    Application 'SchoolRegApp' is running! Access URLs:
    Local:      http://127.0.0.1:8080
    External:   http://192.168.0.105:8080
----------------------------------------------------------
[2m2016-04-03 19:48:20.199[0;39m [32mDEBUG[0;39m [35m8604[0;39m [2m---[0;39m [2m[nio-8080-exec-4][0;39m [36mc.m.school.aop.logging.LoggingAspect    [0;39m [2m:[0;39m Enter: org.springframework.boot.actuate.audit.AuditEventRepository.add() with argument[s] = [AuditEvent [timestamp=Sun Apr 03 19:48:20 IST 2016, principal=anonymousUser, type=AUTHORIZATION_FAILURE, data={type=org.springframework.security.access.AccessDeniedException, message=Access is denied}]]
[2m2016-04-03 19:48:20.200[0;39m [32mDEBUG[0;39m [35m8604[0;39m [2m---[0;39m [2m[nio-8080-exec-4][0;39m [36mc.m.school.aop.logging.LoggingAspect    [0;39m [2m:[0;39m Exit: org.springframework.boot.actuate.audit.AuditEventRepository.add() with result = null
[2m2016-04-03 19:48:20.215[0;39m [32mDEBUG[0;39m [35m8604[0;39m [2m---[0;39m [2m[nio-8080-exec-4][0;39m [36mc.m.s.s.Http401UnauthorizedEntryPoint   [0;39m [2m:[0;39m Pre-authenticated entry point called. Rejecting access
```

**Second Issue ::** After the cleaning Now I'm unable to start the server due bean exception.

```

mc.m.s.c.liquibase.AsyncSpringLiquibase  [0;39m [2m:[0;39m Starting Liquibase asynchronously, your database might not be ready at startup!
mo.a.c.c.C.[Tomcat].[localhost].[/]      [0;39m [2m:[0;39m Exception starting filter springSecurityFilterChain

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.security.config.annotation.web.configuration.WebSecurityConfiguration': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire method: public void org.springframework.security.config.annotation.web.configuration.WebSecurityConfiguration.setFilterChainProxySecurityConfigurer(org.springframework.security.config.annotation.ObjectPostProcessor,java.util.List) throws java.lang.Exception; nested exception is org.springframework.beans.factory.BeanExpressionException: Expression parsing failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'securityConfiguration': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: private org.springframework.security.core.userdetails.UserDetailsService com.masscom.school.config.SecurityConfiguration.userDetailsService; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'userDetailsService': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: private com.masscom.school.repository.UserRepository com.masscom.school.security.UserDetailsService.userRepository; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'userRepository': Cannot create inner bean '(inner bean)#668eb90d' of type [org.springframework.orm.jpa.SharedEntityManagerCreator] while setting bean property 'entityManager'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name '(inner bean)#668eb90d': Cannot resolve reference to bean 'entityManagerFactory' while setting constructor argument; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'entityManagerFactory' defined in class path resource [org/springframework/boot/autoconfigure/orm/jpa/HibernateJpaAutoConfiguration.class]: Invocation of init method failed; nested exception is javax.persistence.PersistenceException: [PersistenceUnit: default] Unable to build Hibernate SessionFactory
    at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:334)
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1214)
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:543)
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482)
    at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
    at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
    at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
    at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
    at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:368)
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1123)
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1018)
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:510)
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482)
```

**.yo-rc.json**

```
{
  "generator-jhipster": {
    "jhipsterVersion": "3.0.0",
    "baseName": "SchoolRegApp",
    "packageName": "com.masscom.school",
    "packageFolder": "com/masscom/school",
    "serverPort": "8080",
    "authenticationType": "session",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": "no",
    "websocket": "no",
    "databaseType": "sql",
    "devDatabaseType": "mysql",
    "prodDatabaseType": "mysql",
    "searchEngine": "no",
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "rememberMeKey": "c1b390eb1883ce6a2fb57017b2e108a50e46379f",
    "useSass": false,
    "applicationType": "monolith",
    "testFrameworks": [
      "gatling"
    ],
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en",
      "fr",
      "hi",
      "ta"
    ]
  }
}

```

**I have created three entities below I have given all the three entities**

**_1. Parent.json 2. School.json 3. Student.json_**

**Parent.json**
----------------------

```
{
    "relationships": [
        {
            "relationshipName": "student",
            "otherEntityName": "student",
            "relationshipType": "one-to-many",
            "otherEntityRelationshipName": "parent"
        }
    ],
    "fields": [
        {
            "fieldName": "fathername",
            "fieldType": "String",
            "fieldValidateRules": [
                "required",
                "maxlength"
            ],
            "fieldValidateRulesMaxlength": "30"
        },
        {
            "fieldName": "fatherOccupation",
            "fieldType": "String",
            "fieldValidateRules": [
                "required",
                "maxlength"
            ],
            "fieldValidateRulesMaxlength": "15"
        },
        {
            "fieldName": "mothername",
            "fieldType": "String",
            "fieldValidateRules": [
                "required",
                "maxlength"
            ],
            "fieldValidateRulesMaxlength": "30"
        },
        {
            "fieldName": "motherOccupation",
            "fieldType": "String",
            "fieldValidateRules": [
                "required",
                "maxlength"
            ],
            "fieldValidateRulesMaxlength": "15"
        },
        {
            "fieldName": "primaryContactNo",
            "fieldType": "String",
            "fieldValidateRules": [
                "required",
                "maxlength"
            ],
            "fieldValidateRulesMaxlength": "15"
        },
        {
            "fieldName": "secondaryContactNo",
            "fieldType": "String",
            "fieldValidateRules": [
                "required",
                "maxlength"
            ],
            "fieldValidateRulesMaxlength": "15"
        },
        {
            "fieldName": "emergencyContactNo",
            "fieldType": "String",
            "fieldValidateRules": [
                "required",
                "maxlength"
            ],
            "fieldValidateRulesMaxlength": "15"
        },
        {
            "fieldName": "aadharNo",
            "fieldType": "String",
            "fieldValidateRules": [
                "required",
                "maxlength"
            ],
            "fieldValidateRulesMaxlength": "12"
        },
        {
            "fieldName": "doorno",
            "fieldType": "String",
            "fieldValidateRules": [
                "required",
                "maxlength"
            ],
            "fieldValidateRulesMaxlength": "10"
        },
        {
            "fieldName": "streetNoName",
            "fieldType": "String",
            "fieldValidateRules": [
                "required",
                "maxlength"
            ],
            "fieldValidateRulesMaxlength": "20"
        },
        {
            "fieldName": "city",
            "fieldType": "String",
            "fieldValidateRules": [
                "required",
                "maxlength"
            ],
            "fieldValidateRulesMaxlength": "15"
        },
        {
            "fieldName": "district",
            "fieldType": "String",
            "fieldValidateRules": [
                "required",
                "maxlength"
            ],
            "fieldValidateRulesMaxlength": "15"
        },
        {
            "fieldName": "stateName",
            "fieldType": "String",
            "fieldValidateRules": [
                "required",
                "maxlength"
            ],
            "fieldValidateRulesMaxlength": "15"
        },
        {
            "fieldName": "pincode",
            "fieldType": "String",
            "fieldValidateRules": [
                "required",
                "maxlength"
            ],
            "fieldValidateRulesMaxlength": "6"
        },
        {
            "fieldName": "emailId",
            "fieldType": "String",
            "fieldValidateRules": [
                "required",
                "maxlength"
            ],
            "fieldValidateRulesMaxlength": "50"
        },
        {
            "fieldName": "siblings",
            "fieldType": "String",
            "fieldValidateRules": [
                "maxlength"
            ],
            "fieldValidateRulesMaxlength": "1"
        }
    ],
    "changelogDate": "20160403140820",
    "dto": "no",
    "service": "no",
    "entityTableName": "parent",
    "pagination": "pagination"
}

```

------------------------
**School.json**
--------------------------

```
{
    "relationships": [
        {
            "relationshipName": "student",
            "otherEntityName": "student",
            "relationshipType": "one-to-many",
            "otherEntityRelationshipName": "school"
        }
    ],
    "fields": [
        {
            "fieldName": "code",
            "fieldType": "String",
            "fieldValidateRules": [
                "required",
                "maxlength"
            ],
            "fieldValidateRulesMaxlength": "15"
        },
        {
            "fieldName": "name",
            "fieldType": "String",
            "fieldValidateRules": [
                "required",
                "maxlength"
            ],
            "fieldValidateRulesMaxlength": "250"
        },
        {
            "fieldName": "area",
            "fieldType": "String",
            "fieldValidateRules": [
                "required",
                "maxlength"
            ],
            "fieldValidateRulesMaxlength": "20"
        },
        {
            "fieldName": "primaryPhone",
            "fieldType": "String",
            "fieldValidateRules": [
                "required",
                "maxlength"
            ],
            "fieldValidateRulesMaxlength": "15"
        },
        {
            "fieldName": "secondaryPhone",
            "fieldType": "String",
            "fieldValidateRules": [
                "maxlength"
            ],
            "fieldValidateRulesMaxlength": "15"
        },
        {
            "fieldName": "thirdPhone",
            "fieldType": "String",
            "fieldValidateRules": [
                "maxlength"
            ],
            "fieldValidateRulesMaxlength": "15"
        },
        {
            "fieldName": "fourthPhone",
            "fieldType": "String",
            "fieldValidateRules": [
                "maxlength"
            ],
            "fieldValidateRulesMaxlength": "15"
        },
        {
            "fieldName": "board",
            "fieldType": "String",
            "fieldValidateRules": [
                "required",
                "maxlength"
            ],
            "fieldValidateRulesMaxlength": "10"
        },
        {
            "fieldName": "website",
            "fieldType": "String",
            "fieldValidateRules": [
                "required",
                "maxlength"
            ],
            "fieldValidateRulesMaxlength": "150"
        },
        {
            "fieldName": "emailId",
            "fieldType": "String",
            "fieldValidateRules": [
                "required",
                "maxlength"
            ],
            "fieldValidateRulesMaxlength": "50"
        },
        {
            "fieldName": "doorno",
            "fieldType": "String",
            "fieldValidateRules": [
                "required",
                "maxlength"
            ],
            "fieldValidateRulesMaxlength": "10"
        },
        {
            "fieldName": "streetNoName",
            "fieldType": "String",
            "fieldValidateRules": [
                "required",
                "maxlength"
            ],
            "fieldValidateRulesMaxlength": "20"
        },
        {
            "fieldName": "city",
            "fieldType": "String",
            "fieldValidateRules": [
                "required",
                "maxlength"
            ],
            "fieldValidateRulesMaxlength": "15"
        },
        {
            "fieldName": "district",
            "fieldType": "String",
            "fieldValidateRules": [
                "required",
                "maxlength"
            ],
            "fieldValidateRulesMaxlength": "15"
        },
        {
            "fieldName": "state",
            "fieldType": "String",
            "fieldValidateRules": [
                "required",
                "maxlength"
            ],
            "fieldValidateRulesMaxlength": "15"
        },
        {
            "fieldName": "pincode",
            "fieldType": "String",
            "fieldValidateRules": [
                "required",
                "maxlength"
            ],
            "fieldValidateRulesMaxlength": "6"
        },
        {
            "fieldName": "country",
            "fieldType": "String",
            "fieldValidateRules": [
                "required",
                "maxlength"
            ],
            "fieldValidateRulesMaxlength": "10"
        }
    ],
    "changelogDate": "20160403132658",
    "dto": "no",
    "service": "no",
    "entityTableName": "school",
    "pagination": "pagination"
}

```

-----------------------------

**Student.json**
-------------------------------

```
{
    "relationships": [],
    "fields": [
        {
            "fieldName": "regNo",
            "fieldType": "String",
            "fieldValidateRules": [
                "required",
                "maxlength"
            ],
            "fieldValidateRulesMaxlength": "15"
        },
        {
            "fieldName": "firstname",
            "fieldType": "String",
            "fieldValidateRules": [
                "required",
                "maxlength"
            ],
            "fieldValidateRulesMaxlength": "15"
        },
        {
            "fieldName": "lastname",
            "fieldType": "String",
            "fieldValidateRules": [
                "required",
                "maxlength"
            ],
            "fieldValidateRulesMaxlength": "15"
        },
        {
            "fieldName": "dob",
            "fieldType": "String",
            "fieldValidateRules": [
                "required",
                "maxlength"
            ],
            "fieldValidateRulesMaxlength": "10"
        },
        {
            "fieldName": "age",
            "fieldType": "String",
            "fieldValidateRules": [
                "required",
                "maxlength"
            ],
            "fieldValidateRulesMaxlength": "2"
        },
        {
            "fieldName": "religion",
            "fieldType": "String",
            "fieldValidateRules": [
                "required",
                "maxlength"
            ],
            "fieldValidateRulesMaxlength": "10"
        },
        {
            "fieldName": "nationality",
            "fieldType": "String",
            "fieldValidateRules": [
                "required",
                "maxlength"
            ],
            "fieldValidateRulesMaxlength": "10"
        },
        {
            "fieldName": "caste",
            "fieldType": "String",
            "fieldValidateRules": [
                "required",
                "maxlength"
            ],
            "fieldValidateRulesMaxlength": "10"
        },
        {
            "fieldName": "community",
            "fieldType": "String",
            "fieldValidateRules": [
                "required",
                "maxlength"
            ],
            "fieldValidateRulesMaxlength": "10"
        },
        {
            "fieldName": "bloodgroup",
            "fieldType": "String",
            "fieldValidateRules": [
                "required",
                "maxlength"
            ],
            "fieldValidateRulesMaxlength": "5"
        },
        {
            "fieldName": "standard",
            "fieldType": "String",
            "fieldValidateRules": [
                "required",
                "maxlength"
            ],
            "fieldValidateRulesMaxlength": "3"
        }
    ],
    "changelogDate": "20160403135101",
    "dto": "no",
    "service": "no",
    "entityTableName": "student",
    "pagination": "pagination"
}

```

--------------------------------

Could somebody help me on this issue.

Kindly let me know in case of more details.

**Comment by gmarziou** [comment]
@sparun160782 images of your config are useless, please replace them by text so that we can try to reproduce your problem.

Closing until you provide this information

**Comment by deepu105** [comment]
we will reopen once you provide the information in usable format (text)

**Comment by sparun160782** [comment]
Hi All

I have given the required format could you please provide your suggestions

**Comment by deepu105** [comment]
@sparun160782 you are trying to do a one way `one-to-many` relationship from parent and school to student. we do not support one way relationships out of the box check [docs here](https://jhipster.github.io/managing-relationships/#a-name3a-a-unidirectional-one-to-many-relationship)

I suggest you do a bi directional mapping
