### ISSUE TITLE
[Bug] Impossible to delete users that have oauth2 tokens associated with them

### ISSUE THREAD

**Issue by ddewaele** [jhipster/generator-jhipster#3378]
##### **Overview of the issue**

When generating an oauth2 jHipster monolithic app, it's impossible to delete a user when an oauth2 access token is present for that user.

```
Caused by: org.h2.jdbc.JdbcSQLException: Referential integrity constraint violation: "FK_OAUTH_ACCESS_TOKN_USER_NAME: PUBLIC.OAUTH_ACCESS_TOKEN FOREIGN KEY(USER_NAME) REFERENCES PUBLIC.JHI_USER(LOGIN) ('ddewaele2')"; SQL statement:
delete from jhi_user where id=? [23503-191]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.constraint.ConstraintReferential.checkRow(ConstraintReferential.java:426)
	at org.h2.constraint.ConstraintReferential.checkRowRefTable(ConstraintReferential.java:443)
	at org.h2.constraint.ConstraintReferential.checkRow(ConstraintReferential.java:318)
	at org.h2.table.Table.fireConstraints(Table.java:962)
	at org.h2.table.Table.fireAfterRow(Table.java:980)
	at org.h2.command.dml.Delete.update(Delete.java:100)
	at org.h2.command.CommandContainer.update(CommandContainer.java:98)
	at org.h2.command.Command.executeUpdate(Command.java:258)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(JdbcPreparedStatement.java:160)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:146)
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java)
	at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.executeUpdate(ResultSetReturnImpl.java:208)
	... 151 common frames omitted
```

##### **Motivation for or Use Case** 

Should be possible to delete users even if the user has access tokens.

##### **JHipster Version(s)** 

v3.0.0

##### **Steps to reproduce** 

- Create a new jHipster app with oauth2 authentication
- Create a new user (user1)
- Signup the new user (change pwd + login)
- Login with admin user and try to delete user1
- You'll get the error above

##### **Suggest a Fix** 

Oauth tokens need to be cleared from the ```OAUTH_ACCESS_TOKEN ``` (used by the ```JdbcTokenStore```) for the user.  This can be done in a couple of ways : 

- Executing a JPA native query to delete them (quick fix / short term)
- Modelling the Oauth tokens and using a domain object (long term solution, if it fits with the whole oauth2 / microservices strategy, and you ever want to implement tokens revocation flows)

**Comment by mleneveut** [comment]
or with a delete cascade when generating the SQL schema (for relational DB at least)
