### ISSUE TITLE
Docker-compose subgenerator adding Cassandra microservice fails

### ISSUE THREAD

**Issue by ruddell** [jhipster/generator-jhipster#3407]
##### **Overview of the issue**
Docker compose fails when adding a microservice with Cassandra to the docker config
```
Checking Docker images in applications' directories...
events.js:154
      throw er; // Unhandled 'error' event
      ^

TypeError: Cannot set property 'context' of undefined
    at module.exports.DockerComposeGenerator.extend.configuring.setAppsYaml (/Users/ruddell/Dev/Contrib/generator-jhipster/generators/docker-compose/index.js:307:58)
    at Object.<anonymous> (/Users/ruddell/Dev/Contrib/generator-jhipster/node_modules/yeoman-generator/lib/base.js:436:25)
    at /Users/ruddell/Dev/Contrib/generator-jhipster/node_modules/yeoman-generator/node_modules/run-async/index.js:24:25
    at /Users/ruddell/Dev/Contrib/generator-jhipster/node_modules/yeoman-generator/lib/base.js:448:8
    at processImmediate [as _immediateCallback] (timers.js:383:17)
```
##### **Motivation for or Use Case** 
I wanted to try out Cassandra with Docker
##### **JHipster Version(s)** 
Master (3.0.0 is fine)
##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder** 
```
{
  "generator-jhipster": {
    "jhipsterVersion": "3.0.0",
    "baseName": "casstest",
    "packageName": "com.jruddell.test",
    "packageFolder": "com/jruddell/test",
    "serverPort": "8085",
    "authenticationType": "jwt",
    "hibernateCache": "no",
    "databaseType": "cassandra",
    "devDatabaseType": "cassandra",
    "prodDatabaseType": "cassandra",
    "searchEngine": "no",
    "buildTool": "maven",
    "jwtSecretKey": "a310878c074bd02c67adc51c484c420978c039aa",
    "enableTranslation": false,
    "applicationType": "microservice",
    "testFrameworks": [
      "gatling"
    ],
    "jhiPrefix": "jhi",
    "skipClient": true,
    "skipUserManagement": true
  }
}
```
##### **OS** 
Mac
##### **How to Reproduce** 
 (gateway, registry, other microservices without Cassandra work fine)
```
mkdir docker-config casstest && cd casstest
yo jhipster #generate the above project
./mvnw package -Pprod -DskipTests docker:build #create the docker image
cd ../docker-config
yo jhipster:docker-compose #attempt to add the project to docker
```
##### **Suggest a Fix** 
@pascalgrimaud mentioned in another issue he was working on it

**Comment by jdubois** [comment]
As you are on the master branch, can you test with the 3.0 release? There has been much work recently on Cassandra support on the master branch (cc @raphaelbrugier ) so it depends when you did it, etc.

**Comment by pascalgrimaud** [comment]
@ruddell : I fixed the docker-compose sub generator, when there is a cassandra microservice.

But we can't run directly `docker-compose up` because cassandra microservice doesn't have a system like liquibase. I have to think if we should use the same system proposed by @raphaelbrugier for cassandra.yml -> this system creates automatically the tables in dev

Anyway, I didn't manage to run cassandra microservice. I start separately cassandra database and I encountered this error:
```
2016-04-17 14:19:09.484  WARN 12 --- [           main] com.datastax.driver.core.NettyUtil       : Found Netty's native epoll transport in the classpath, but epoll is not available. Using NIO instead.

java.lang.UnsatisfiedLinkError: no netty-transport-native-epoll in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1864)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:168)
	at io.netty.channel.epoll.Native.<clinit>(Native.java:49)
	at io.netty.channel.epoll.Epoll.<clinit>(Epoll.java:30)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at com.datastax.driver.core.NettyUtil.<clinit>(NettyUtil.java:68)
	at com.datastax.driver.core.NettyOptions.eventLoopGroup(NettyOptions.java:101)
	at com.datastax.driver.core.Connection$Factory.<init>(Connection.java:695)
	at com.datastax.driver.core.Cluster$Manager.init(Cluster.java:1286)
	at com.datastax.driver.core.Cluster.init(Cluster.java:159)
	at com.datastax.driver.core.Cluster.connect(Cluster.java:249)
	at com.datastax.driver.core.Cluster.connect(Cluster.java:282)
	at org.springframework.cassandra.config.CassandraCqlSessionFactoryBean.afterPropertiesSet(CassandraCqlSessionFactoryBean.java:82)
	at org.springframework.data.cassandra.config.CassandraSessionFactoryBean.afterPropertiesSet(CassandraSessionFactoryBean.java:43)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1637)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1574)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:545)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.findAutowireCandidates(DefaultListableBeanFactory.java:1192)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1116)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1014)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:545)
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:88)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:331)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1214)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:543)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:772)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:839)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:538)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:118)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:766)
	at org.springframework.boot.SpringApplication.createAndRefreshContext(SpringApplication.java:361)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:307)
	at com.mycompany.myapp.MscassandraApp.main(MscassandraApp.java:71)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:54)
	at java.lang.Thread.run(Thread.java:745)

2016-04-17 14:19:14.502  WARN 12 --- [           main] c.n.c.sources.URLConfigurationSource     : No URLs will be polled as dynamic configuration sources.
2016-04-17 14:19:14.513  WARN 12 --- [           main] c.n.c.sources.URLConfigurationSource     : No URLs will be polled as dynamic configuration sources.
```

Sorry, I'm on holidays since today, so I won't have time to investigate on it.

**Comment by ruddell** [comment]
@jdubois the docker-compose subgenerator works correctly with Cassandra on 3.0.0.

@pascalgrimaud I tested the referenced pull request and it fixes this issue, thank you.

**Comment by pascalgrimaud** [comment]
Thanks @ruddell :)
Let me know if u manage to run cassandra microservice or if u have the same error than me

**Comment by jd-carroll** [comment]
@pascalgrimaud What version of Docker Toolbox are you using?

Could jhipster/jhipster-registry#39 impact anything?

**Comment by pascalgrimaud** [comment]
@jd-carroll : I'm on Linux, with latest version of Docker and Docker Compose
I dont think it s related because you can use directly https://hub.docker.com/r/jhipster/jhipster-registry/

**Comment by raphaelbrugier** [comment]
Hi,

The referenced pull request fixed the generator issue, but I'm running on the same problem as @pascalgrimaud .
It seems not related to the missing setup of the keyspace/tables as I still have the issue after creating them manually.

I propose to close this issue with the pull request and open a new one dedicated to the missing lib problem?

**Comment by pascalgrimaud** [comment]
You re right Raphaël, it's another issue. Can you open another issue with the correct stacktrace plz?
I cant open it myself, it's hard to do it on my phone :)

**Comment by raphaelbrugier** [comment]
I'll create an issue for the problem of starting the Cassandra-service against a non-setup database.

I'll create another one for the second problem of the missing lib, but I just realized the log was a warning and the Cassandra driver seem to handle this correctly and fallback on another lib.
