### ISSUE TITLE
Cassandra driver error when starting Cassandra microsevice with docker-compose file

### ISSUE THREAD

**Issue by raphaelbrugier** [jhipster/generator-jhipster#3428]
##### **Overview of the issue**

When starting a Cassandra microservice with the docker-compose generated files, the following warning and stack trace appears in the log:

```
2016-04-19 14:16:59.249  INFO 7 --- [           main] c.j.test.config.MetricsConfiguration     : Initializing Metrics Log reporting
2016-04-19 14:17:05.551  INFO 7 --- [ost-startStop-1] com.mycompany.myapp.config.WebConfigurer   : Web application configuration, using profiles: [prod]
2016-04-19 14:17:05.579  INFO 7 --- [ost-startStop-1] com.mycompany.myapp.config.WebConfigurer   : Web application fully configured
2016-04-19 14:17:07.081  INFO 7 --- [ost-startStop-1] ccom.mycompany.myapp.CasstestApp            : Running with Spring profile(s) : [prod]
2016-04-19 14:17:08.003  INFO 7 --- [           main] c.j.test.config.LoggingConfiguration     : Initializing Logstash logging
2016-04-19 14:17:09.065  WARN 7 --- [           main] com.datastax.driver.core.NettyUtil       : Found Netty's native epoll transport in the classpath, but epoll is not available. Using NIO instead.
java.lang.UnsatisfiedLinkError: no netty-transport-native-epoll in java.library.path
at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1864)
at java.lang.Runtime.loadLibrary0(Runtime.java:870)
at java.lang.System.loadLibrary(System.java:1122)
at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:168)
at io.netty.channel.epoll.Native.<clinit>(Native.java:49)
at io.netty.channel.epoll.Epoll.<clinit>(Epoll.java:30)
at java.lang.Class.forName0(Native Method)
at java.lang.Class.forName(Class.java:264)
at com.datastax.driver.core.NettyUtil.<clinit>(NettyUtil.java:68)
at com.datastax.driver.core.NettyOptions.eventLoopGroup(NettyOptions.java:101)
at com.datastax.driver.core.Connection$Factory.<init>(Connection.java:695)
at com.datastax.driver.core.Cluster$Manager.init(Cluster.java:1286)
at com.datastax.driver.core.Cluster.init(Cluster.java:159)
at com.datastax.driver.core.Cluster.connect(Cluster.java:249)
at com.datastax.driver.core.Cluster.connect(Cluster.java:282)
at org.springframework.cassandra.config.CassandraCqlSessionFactoryBean.afterPropertiesSet(CassandraCqlSessionFactoryBean.java:82)
at org.springframework.data.cassandra.config.CassandraSessionFactoryBean.afterPropertiesSet(CassandraSessionFactoryBean.java:43)
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1637)
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1574)
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:545)
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482)
at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
at org.springframework.beans.factory.support.DefaultListableBeanFactory.findAutowireCandidates(DefaultListableBeanFactory.java:1192)
at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1116)
at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1014)
at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:545)
at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:88)
at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:331)
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1214)
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:543)
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482)
at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:772)
at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:839)
at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:538)
at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:118)
at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:766)
at org.springframework.boot.SpringApplication.createAndRefreshContext(SpringApplication.java:361)
at org.springframework.boot.SpringApplication.run(SpringApplication.java:307)
at com.mycompany.myapp.CasstestApp.main(CasstestApp.java:71)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:54)
at java.lang.Thread.run(Thread.java:
```

This does not seems to prevent the app to start, but the application is marked has _down_ in the registry and those can not be reached.

##### **JHipster Version(s)** 
master + fixes from #3420 +  manually workaround of #3427

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder** 

3 directories: 
- jhigate
- casstest (cassandra microservice)
- compose (docker-compose config)

**gateway:**
```
{
  "generator-jhipster": {
    "jhipsterVersion": "3.0.0",
    "baseName": "jhigate",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "hazelcast",
    "clusteredHttpSession": "no",
    "websocket": "no",
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": "no",
    "buildTool": "maven",
    "jwtSecretKey": "080bce90a1e6565afd977f09ce38b41dc315b080",
    "useSass": false,
    "applicationType": "gateway",
    "testFrameworks": [
      "gatling"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en"
    ]
  }
}
```

**cassandra microservice:**
```
{
  "generator-jhipster": {
    "jhipsterVersion": "3.0.0",
    "baseName": "casstest",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "8085",
    "authenticationType": "jwt",
    "hibernateCache": "no",
    "databaseType": "cassandra",
    "devDatabaseType": "cassandra",
    "prodDatabaseType": "cassandra",
    "searchEngine": "no",
    "buildTool": "maven",
    "jwtSecretKey": "a310878c074bd02c67adc51c484c420978c039aa",
    "enableTranslation": false,
    "applicationType": "microservice",
    "testFrameworks": [
      "gatling"
    ],
    "jhiPrefix": "jhi",
    "skipClient": true,
    "skipUserManagement": true,
    "clusteredHttpSession": "no",
    "websocket": "no",
    "enableSocialSignIn": false
  }
}
```

**compose:**
```
{
  "generator-jhipster": {
    "appsFolders": [
      "casstest",
      "jhigate"
    ],
    "directoryPath": "../",
    "useElk": true,
    "jwtSecretKey": "1523fb4eff5ba4c0966a8c69a10bd136e0a9d37d"
  }
}
```

##### **Browsers and Operating System** 
OS/X

##### **Reproduce the error** 

Run yo jhispter in app subdirectory
Run `./mvnw package -Pprod -DskipTests docker:build` in the gateway and casstest directories
Run `yo jhipster:docker-compose` in compose directory
Run `docker-compose up -d` in compose directory to start the cluster and all containers
Apply all cql scripts to the Cassandra cluster
Start the casstest service again: `docker-compose up -d casstest-app `

See the error in the logs.

**Comment by raphaelbrugier** [comment]
Some more investigation.
The warning is not preventing the application to start and to register correctly.

It is the same problem as described in the [cassandra mailing list](https://groups.google.com/a/lists.datastax.com/forum/#!topic/java-driver-user/QgwtAB7Mhn8).

In our case, netty-transport-native-epoll dependency is being brought by ribbon.

mvn dependency:tree extract:
```

[INFO] +- org.springframework.cloud:spring-cloud-starter-ribbon:jar:1.1.0.RC1:compile
[INFO] |  +- org.springframework.cloud:spring-cloud-netflix-core:jar:1.1.0.RC1:compile
[INFO] |  +- org.springframework.cloud:spring-cloud-starter-archaius:jar:1.1.0.RC1:compile
[INFO] |  |  +- com.netflix.archaius:archaius-core:jar:0.7.3:compile
[INFO] |  |  |  \- com.google.code.findbugs:jsr305:jar:3.0.1:runtime
[INFO] |  |  \- commons-configuration:commons-configuration:jar:1.8:compile
[INFO] |  |     \- commons-logging:commons-logging:jar:1.1.1:compile
[INFO] |  +- com.netflix.ribbon:ribbon:jar:2.1.3:compile
[INFO] |  |  +- com.netflix.ribbon:ribbon-transport:jar:2.1.3:runtime
[INFO] |  |  |  +- io.reactivex:rxnetty-contexts:jar:0.4.9:runtime
[INFO] |  |  |  \- io.reactivex:rxnetty-servo:jar:0.4.9:runtime
[INFO] |  |  \- io.reactivex:rxnetty:jar:0.4.9:runtime
[INFO] |  |     +- io.netty:netty-codec-http:jar:4.0.27.Final:runtime
[INFO] |  |     \- io.netty:netty-transport-native-epoll:jar:4.0.27.Final:runtime 
```

Excluding the dependency fixes the warning:

```
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-ribbon</artifactId>
            <exclusions>
                <exclusion>
                    <groupId>io.netty</groupId>
                    <artifactId>netty-transport-native-epoll</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
```

I don't think there is any impact to do this, as it is not used unless another lib is explicitly added with:

```
       <dependency>
            <groupId>io.netty</groupId>
            <artifactId>netty-transport-native-epoll</artifactId>
            <version>${netty.version}</version>
            <!-- Explicitly bring in the linux classifier, may fail on 32-bit linux -->
            <classifier>linux-x86_64</classifier>
            <scope>runtime</scope>
        </dependency>
```

**Comment by pascalgrimaud** [comment]
thanks for reporting and investigating on this, @raphaelbrugier 
I didn't have a look when using **Gradle** instead of Maven, I think it's the same problem, right ?

**Comment by raphaelbrugier** [comment]
I haven't tried with gradle, I will and let you know.

**Comment by raphaelbrugier** [comment]
I was able to exclude the dependency to epoll native, not by declaring the exclusion at the dependency level but in the configurations declaration however:

```
configurations {
    providedRuntime
    all*.exclude group: 'io.netty', module: 'netty-transport-native-epoll'
}
```

This didn't exclude it:
```
    compile(group: 'org.springframework.cloud', name: 'spring-cloud-starter-ribbon') {
        exclude(module: 'netty-transport-native-epoll')
    }
```

Anyway, when excluded the warning does not show anymore and the app can still starts and serve request without problem.

After exclusion:
```
./gradlew -Pprod dependencyInsight --dependency netty-transport-native-epoll
:dependencyInsight
No dependencies matching given input were found in configuration ':compile'
```

So I would suggest to exclude this dependency in both generated maven and gradle configuration.
If you are ok I can prepare a PR.

Fyi, my PR on the RxNetty project to fix the declaration to optional has been merged on the 0.5.X, but it will take a while before it is integrated in Ribbon, then spring-cloud I think.

**Comment by pascalgrimaud** [comment]
LGTM, but 1 question: this exclusion is needed only for microservice, isn't it? (so we won't change the monolithic Cassandra)

**Comment by raphaelbrugier** [comment]
Yes only for the monoservices, I don't think Ribbon is included in the monolithic anyway?

So for maven it will be part of the dependency declaration, and for gradle a special condition because the exclusion is at the configuration level.

**Comment by JinnaBalu** [comment]
Excluding below able to run app in dev, prod
```xml
<exclusions>
                <exclusion>
                    <groupId>io.netty</groupId>
                    <artifactId>netty-transport-native-epoll</artifactId>
                </exclusion>
            </exclusions> 
```
Issue with docker image, unable to run as container.
