### ISSUE TITLE
Error parsing JSON when response is 404

### ISSUE THREAD

**Issue by lusorio** [jhipster/generator-jhipster#3470]
##### **Overview of the issue**

In the generated rest controllers, when response is a HTTP 404, the `angular.fromJson()` method in the entities services fails due to an empty string in the body.

```
angular.js:13294 SyntaxError: Unexpected end of JSON input
    at Object.parse (native)
    at Object.fromJson (http://localhost:8080/bower_components/angular/angular.js:1285:14)
    at DiverProfile.$resource.get.transformResponse (http://localhost:8080/app/entities/diver-profile/diver-profile.service.js:16:36)
    at transformData (http://localhost:8080/bower_components/angular/angular.js:10262:12)
    at transformResponse (http://localhost:8080/bower_components/angular/angular.js:11054:21)
    at processQueue (http://localhost:8080/bower_components/angular/angular.js:15627:28)
    at http://localhost:8080/bower_components/angular/angular.js:15643:27
    at Scope.$eval (http://localhost:8080/bower_components/angular/angular.js:16895:28)
    at Scope.$digest (http://localhost:8080/bower_components/angular/angular.js:16711:31)
    at Scope.$apply (http://localhost:8080/bower_components/angular/angular.js:17003:24)(anonymous function) @ angular.js:13294(anonymous function) @ angular.js:10007processQueue @ angular.js:15635(anonymous function) @ angular.js:15643Scope.$eval @ angular.js:16895Scope.$digest @ angular.js:16711Scope.$apply @ angular.js:17003done @ angular.js:11324completeRequest @ angular.js:11522requestLoaded @ angular.js:11463
angular.js:13294 Broken interceptor detected: Config object not supplied in rejection:
 https://github.com/chieffancypants/angular-loading-bar/pull/50(anonymous function) @ angular.js:13294responseError @ loading-bar.js:135processQueue @ angular.js:15627(anonymous function) @ angular.js:15643Scope.$eval @ angular.js:16895Scope.$digest @ angular.js:16711Scope.$apply @ angular.js:17003done @ angular.js:11324completeRequest @ angular.js:11522requestLoaded @ angular.js:11463
```

##### **Motivation for or Use Case** 

As the response is created with `new ResponseEntity<>(HttpStatus.NOT_FOUND)` there is only headers in the response but no body to parse in client side.

##### **JHipster Version(s)** 

3.0.0

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder** 

```
{
  "generator-jhipster": {
    "jhipsterVersion": "3.0.0",
    "baseName": "test",
    "packageName": "com.test.api",
    "packageFolder": "com/test/api",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": "no",
    "websocket": "no",
    "databaseType": "sql",
    "devDatabaseType": "postgresql",
    "prodDatabaseType": "postgresql",
    "searchEngine": "no",
    "buildTool": "maven",
    "enableSocialSignIn": true,
    "jwtSecretKey": "",
    "useSass": true,
    "applicationType": "monolith",
    "testFrameworks": [
      "gatling",
      "cucumber",
      "protractor"
    ],
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en",
      "fr",
      "es"
    ]
  }
}
```

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory** 

Any generated entity

##### **Browsers and Operating System** 

OSX Yosemite / Chrome 50

##### **Reproduce the error** 

Just query any non existent entity which calls the `/api/entity/:id` mapped method and check the console

##### **Related issues** 

Didn't found

##### **Suggest a Fix** 

If you call an URI which is not mapped at all i.e `http://localhost:8080/api/idontexist` the response is also a 404 Not Found but this time it comes with some body on it. 

```
{
	"timestamp": "2016-04-25T21:23:58.101+0000",
	"status": 404,
	"error": "Not Found",
	"message": "No message available",
	"path": "/api/idontexist/"
}
```

Not sure if is Spring or Tomcat responding this but the fact is that `angular.fromJson()` parses it well. Also, the messages shown in the client side are correctly shown with the `No message available` but it would be nice to generate this kind of response inside the controllers.

**Comment by deepu105** [comment]
would you consider doing a PR?

**Comment by lusorio** [comment]
Sure, let me take a look to the possible solutions
