### ISSUE TITLE
gulp error at project generation

### ISSUE THREAD

**Issue by mkjasinski** [jhipster/generator-jhipster#3497]
Hi,

I have problem with project generation. After command `yo jhipster` and configuration for single app I see errors:

```
(node:58162) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
[09:19:46] Using gulpfile ~/workspace-java/jhipster/gulpfile.js
[09:19:46] Starting 'install'...
[09:19:46] Starting 'wiredep:test'...
[09:19:46] Starting 'wiredep:app'...
[09:19:46] Starting 'ngconstant:dev'...
[09:19:46] 'ngconstant:dev' errored after 97 ms
[09:19:46] Error in plugin 'gulp-tslint-log'
TypeError: Path must be a string. Received null
    at assertPath (path.js:7:11)
    at Object.dirname (path.js:1324:5)
    at getFilePath (/Users/mkjasinski/workspace-java/jhipster/node_modules/gulp-ng-constant-fork/index.js:95:27)
    at DestroyableTransform.objectStream [as _transform] (/Users/mkjasinski/workspace-java/jhipster/node_modules/gulp-ng-constant-fork/index.js:60:25)
    at DestroyableTransform.Transform._read (/Users/mkjasinski/workspace-java/jhipster/node_modules/gulp-ng-constant-fork/node_modules/readable-stream/lib/_stream_transform.js:184:10)
    at DestroyableTransform.Transform._write (/Users/mkjasinski/workspace-java/jhipster/node_modules/gulp-ng-constant-fork/node_modules/readable-stream/lib/_stream_transform.js:172:12)
    at doWrite (/Users/mkjasinski/workspace-java/jhipster/node_modules/gulp-ng-constant-fork/node_modules/readable-stream/lib/_stream_writable.js:237:10)
    at writeOrBuffer (/Users/mkjasinski/workspace-java/jhipster/node_modules/gulp-ng-constant-fork/node_modules/readable-stream/lib/_stream_writable.js:227:5)
    at DestroyableTransform.Writable.write (/Users/mkjasinski/workspace-java/jhipster/node_modules/gulp-ng-constant-fork/node_modules/readable-stream/lib/_stream_writable.js:194:11)
    at DestroyableTransform.Writable.end (/Users/mkjasinski/workspace-java/jhipster/node_modules/gulp-ng-constant-fork/node_modules/readable-stream/lib/_stream_writable.js:352:10)
    at ngConstantPlugin (/Users/mkjasinski/workspace-java/jhipster/node_modules/gulp-ng-constant-fork/index.js:33:16)
    at Gulp.<anonymous> (/Users/mkjasinski/workspace-java/jhipster/gulpfile.js:154:12)
    at module.exports (/Users/mkjasinski/workspace-java/jhipster/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/Users/mkjasinski/workspace-java/jhipster/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/Users/mkjasinski/workspace-java/jhipster/node_modules/orchestrator/index.js:214:10)
    at Gulp.Orchestrator.start (/Users/mkjasinski/workspace-java/jhipster/node_modules/orchestrator/index.js:134:8)
[09:19:46] Error in plugin 'run-sequence'
Message:
    An error occured in task 'ngconstant:dev'.
[09:19:46] Finished 'install' after 113 ms
[09:19:46] Finished 'wiredep:test' after 202 ms
[09:19:46] Finished 'wiredep:app' after 191 ms
```

`.yo-rc.json` file:

```json
{
  "generator-jhipster": {
    "jhipsterVersion": "3.1.0",
    "baseName": "jhipster",
    "packageName": "com.marcinjasinski.jhipster.app",
    "packageFolder": "com/marcinjasinski/jhipster/app",
    "serverPort": "8080",
    "authenticationType": "session",
    "hibernateCache": "no",
    "clusteredHttpSession": "no",
    "websocket": "no",
    "databaseType": "sql",
    "devDatabaseType": "h2Memory",
    "prodDatabaseType": "postgresql",
    "searchEngine": "no",
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "rememberMeKey": "e5ed3141bb56cfab78c04849a2d6c6167e228966",
    "useSass": false,
    "applicationType": "monolith",
    "testFrameworks": [
      "gatling"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "pl",
    "languages": [
      "pl"
    ]
  }
}
```

Operating System - `Mac OSX 10.11.4`
npm version - `3.8.8`
gulp version - `3.9.1`

**Comment by jdubois** [comment]
- Can you put a better title?
- What is your node version?

**Comment by mkjasinski** [comment]
`$ node --version`
```
v6.0.0
```

**Comment by jdubois** [comment]
This is because we don't support v6.0.0

It was just released a few days ago, and it's stable, so we can't support it at the moment. This is why on the installation page we recommend always using an LTS version, it's the only stable version.

**Comment by willy-juisan** [comment]
What version of node.js that working for jhipster? Since in node.js homepage at current already using version 6.9.1 for the LTS.

**Comment by pascalgrimaud** [comment]
4.6.0 works perfectly, all our Travis builds use it.
But I didnt notice that 6.9.1 is now LTS, I think it's very recent.

**Comment by jdubois** [comment]
Yes it's very recent.
I'm using it, as well as 7.0.0 and it works, but I haven't tried all use
cases, so I would still be cautious.

Le 29 oct. 2016 7:36 AM, "Pascal Grimaud" <notifications@github.com> a
écrit :

4.6.0 works perfectly, all our Travis builds use it.
But I didnt notice that 6.9.1 is now LTS, I think it's very recent.

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub
<https://github.com/jhipster/generator-jhipster/issues/3497#issuecomment-257072652>,
or mute the thread

**Comment by jdubois** [comment]
FYI Node 7.0.0 doesn't work with the Kubernetes sub-generator (but 6.9.1 does!).
So yes, LTS is always preferred!
