### ISSUE TITLE
Admin can create user with invalid username

### ISSUE THREAD

**Issue by WhyINeedToFillUsername** [jhipster/generator-jhipster#3567]
##### **Overview of the issue**
Username (login) cannot contain special characters (`[_'.@a-z0-9-]+`). This is validated in user registation, however not validated in user management, so an administrator can create such an user and this leads to app errors:

```
2016-05-09 15:55:50.294 ERROR 8884 --- [io-8080-exec-10] c.c.f.k.t.aop.logging.LoggingAspect      : Exception in app.web.rest.UserResource.createUser() with cause = null and exception {}

java.net.URISyntaxException: Illegal character in path at index 17: /api/users/mezery vadi?
	at java.net.URI$Parser.fail(URI.java:2848)
	at java.net.URI$Parser.checkChars(URI.java:3021)
	at java.net.URI$Parser.parseHierarchical(URI.java:3105)
	at java.net.URI$Parser.parse(URI.java:3063)
	at java.net.URI.<init>(URI.java:588)
	at app.web.rest.UserResource.createUser(UserResource.java:134)
	at app.web.rest.UserResource$$FastClassBySpringCGLIB$$70f4f26d.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:720)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:85)
...
```

##### **Motivation for or Use Case** 
Administator creating new Users.

##### **JHipster Version(s)** 
`3.1.0`

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder** 
```
{
  "generator-jhipster": {
    "jhipsterVersion": "3.1.0",
...
    "serverPort": "8080",
    "authenticationType": "session",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": "no",
    "websocket": "no",
    "databaseType": "sql",
    "devDatabaseType": "postgresql",
    "prodDatabaseType": "postgresql",
    "searchEngine": "elasticsearch",
    "buildTool": "maven",
    "enableSocialSignIn": true,
...
    "useSass": true,
    "applicationType": "monolith",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en",
      "cs"
    ]
  }
}
```
##### **Browsers and Operating System** 
Opera, Chrome, Windows 7

##### **Reproduce the error** 
Run app, login as admin, create new user with login `"user name with spaces"`

##### **Suggest a Fix** 
Validate username input the same way as in account registration.

**Comment by deepu105** [comment]
would you like to do a PR?

Thanks & Regards,
Deepu

**Comment by WhyINeedToFillUsername** [comment]
Hi,

sorry but I'd fix only the front-end by copying the registration input, you did better job :)

Shouldn't be also the following code included for proper displaying the error messages (from app/account/register/register.html, with proper path to translation)?

```
<div ng-show="editForm.login.$dirty && editForm.login.$invalid">
    <p class="help-block"
       ng-show="editForm.login.$error.required">
        Your username is required.
    </p>
    <p class="help-block"
       ng-show="editForm.login.$error.minlength">
        Your username is required to be at least 1 character.
    </p>
    <p class="help-block"
       ng-show="editForm.login.$error.maxlength">
        Your username cannot be longer than 50 characters.
    </p>
    <p class="help-block"
       ng-show="editForm.login.$error.pattern">
        Your username can only contain lower-case letters and digits.
    </p>
</div>
```

Thank you
Tony

**Comment by deepu105** [comment]
Yes I missed that I guess, can you add that as a PR?

Thanks & Regards,
Deepu

**Comment by WhyINeedToFillUsername** [comment]
Well, I'm not sure about the i18n messages - where should the `Your username can only contain lower-case letters and digits.` (and alike) message go? It is already in `register.messages.validate.login.pattern`, but this file is not included in this state. I'd put it in `userManagement.validation.login.pattern`, which would require to change all the languages:

```
generators/client/templates/src/main/webapp/app/admin/user-management/_user-management-dialog.html:

<div ng-show="editForm.login.$invalid">
    <p class="help-block"
       ng-show="editForm.login.$error.required" translate="entity.validation.required">
        This field is required.
    </p>

    <p class="help-block"
       ng-show="editForm.login.$error.minlength" translate="userManagement.validation.login.minlength">
        Your username is required to be at least 1 character long.
    </p>

    <p class="help-block"
       ng-show="editForm.login.$error.maxlength" translate="entity.validation.maxlength"
       translate-value-max="50">
        This field cannot be longer than 50 characters.
    </p>

    <p class="help-block"
       ng-show="editForm.login.$error.pattern" translate="userManagement.validation.login.pattern">
        Your username can only contain lower-case letters and digits.
    </p>
</div>
```

I also don't know if the `ng-show="editForm.login.$dirty"` check is necessary (as in `generators/client/templates/src/main/webapp/app/account/register/register.html`), from what I understand the `editForm.login.$invalid` is enough.
