### ISSUE TITLE
Support Node 6.x

### ISSUE THREAD

**Issue by jdubois** [jhipster/generator-jhipster#3663]
It is clearly written in our docs to use an "LTS" version (so Node 4.x). It's also written on the NodeJS website that it's "recommended for most users". But I see in my stats lots of people trying to use JHipster with Node 5.x and 6.x.
Anyway, we need to upgrade at some point in time. Let's go straight to Node 6.x (5.x has never been stable and will never be).

So I'm starting this ticket to track down what needs to be done: let's first list the issues here, and if there are a lot of them, let's track them all one by one.

**Comment by atomfrede** [comment]
The last time I tried it on Arch with latest node 6.x at least for a monolithic application everything was working fine. Will check today an report any findings here.

**Comment by jdubois** [comment]
Oh good news @atomfrede , I thought it didn't work? Would be the easiest ticket ever :-)

**Comment by atomfrede** [comment]
I just updated some plugin: https://github.com/jhipster/generator-jhipster/pull/3564

But it was 2 weeks ago, so I''l check it today again with more configurations

**Comment by deepu105** [comment]
On windows there was some issue with node sass and nodejs 6 but I don't
think there is much we can do there, it has to be fixed by node sass/ node
guys. Other than that things are fine

**Comment by atomfrede** [comment]
A little status report:

Environment: 

* Arch Linux with Kernel 4.5.4
* node 6.2.0
* npm 3.9.3

* default: :heavy_check_mark: 
* default + sass: :heavy_check_mark: 
* default + no translations: :heavy_check_mark: 

So at least on linux everything looks fine so far I would say. Should I test some more configuration, especially microservices?

**Comment by cbornet** [comment]
Can't we let CI test that by a PR that we wouldn't merge ?

**Comment by jdubois** [comment]
Yes we could add some CI tests.
I thought this was totally failing - I'll test also on my Mac to be sure, but it looks OK! Thanks for all the testing @atomfrede

**Comment by jdubois** [comment]
I have `gulp test` not working on a fresh app generated using node 6.20 on my Mac.
Otherwise everything looks OK.
I'm going to have a look at running this in the CI.

**Comment by jdubois** [comment]
OK I'm giving up making it work in Travis....
So basically with Node 6.2:

- there are a few warnings
- `gulp test` is failing

I'm keeping this opened so we correct those, but it doesn't seem that bad after all!

**Comment by pascalgrimaud** [comment]
I put the log error from Travis:
```
if [ "$JHIPSTER" != "app-microservice" ]; then
  gulp test --no-notification
fi
(node:7798) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
[17:47:32] Using gulpfile ~/app/gulpfile.js
[17:47:32] Starting 'inject:test'...
[17:47:32] Starting 'ngconstant:dev'...
[17:47:32] Finished 'ngconstant:dev' after 151 ms
[17:47:32] gulp-inject 22 files into karma.conf.js.
[17:47:32] Finished 'inject:test' after 210 ms
[17:47:32] Starting 'test'...
31 05 2016 17:47:36.615:INFO [karma]: Karma v0.13.22 server started at http://localhost:9876/
31 05 2016 17:47:36.621:INFO [launcher]: Starting browser PhantomJS
31 05 2016 17:47:37.015:INFO [PhantomJS 2.1.1 (Linux 0.0.0)]: Connected on socket /#V9s4g9Fw53hbBmDFAAAA with id 85539866
31 05 2016 17:47:38.063:WARN [web-server]: 404: /i18n/angular-locale_en.js
PhantomJS 2.1.1 (Linux 0.0.0): Executed 0 of 60 SUCCESS (0 secs / 0 secs)
.Missing error handler on `socket`.
TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.dirname (path.js:1324:5)
    at specSuccess.specSkipped.specFailure (/home/travis/app/node_modules/karma-jenkins-reporter/index.js:97:31)
    at onSpecComplete (/home/travis/app/node_modules/karma/lib/reporters/base.js:78:12)
    at .<anonymous> (/home/travis/app/node_modules/karma/lib/events.js:13:22)
    at emitTwo (events.js:111:20)
    at emit (events.js:191:7)
    at onResult (/home/travis/app/node_modules/karma/lib/browser.js:216:13)
    at Socket.<anonymous> (/home/travis/app/node_modules/karma/lib/events.js:13:22)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:188:7)
    at Socket.onevent (/home/travis/app/node_modules/socket.io/lib/socket.js:335:8)
    at Socket.onpacket (/home/travis/app/node_modules/socket.io/lib/socket.js:295:12)
    at Client.ondecoded (/home/travis/app/node_modules/socket.io/lib/client.js:193:14)
    at Decoder.Emitter.emit (/home/travis/app/node_modules/component-emitter/index.js:134:20)
    at Decoder.add (/home/travis/app/node_modules/socket.io-parser/index.js:247:12)
31 05 2016 17:47:39.671:WARN [web-server]: 404: /i18n/angular-locale_en.js
31 05 2016 17:47:41.375:WARN [web-server]: 404: /i18n/angular-locale_en.js
31 05 2016 17:47:49.020:WARN [PhantomJS 2.1.1 (Linux 0.0.0)]: Disconnected (1 times)
PhantomJS 2.1.1 (Linux 0.0.0): Executed 1 of 60 DISCONNECTED (10.052 secs / 0.178 secs)
JS 2.1.1 (Linux 0.0.0): Executed 1 of 60 DISCONNECTED (10.052 secs / 0.178 secs)
```

**Comment by jdubois** [comment]
This is caused by https://github.com/actano/karma-jenkins-reporter which is deprecated now, anyway.
I'll try to replace it with https://github.com/karma-runner/karma-junit-reporter
