### ISSUE TITLE
JDL subgenerator create @Inject instead @Autowired annotation 

### ISSUE THREAD

**Issue by argoal** [jhipster/generator-jhipster#3676]
##### **Overview of the issue**
When running: yo jhipster:import-jdl jhipster-jdl.jh on a new generated app from  yo jhipster the app is not working.  The file jhipster-jdl.jh  is exported from http://jhipster.github.io/jdl-studio/

##### **Motivation for or Use Case** 

This is a bug because the app is not working and with a little fix everything is ok, I know this is an example but making it work would be nice.

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder** 
{
  "generator-jhipster": {
    "jhipsterVersion": "3.4.0",
    "baseName": "jdl",
    "packageName": "al.jdl",
    "packageFolder": "al/jdl",
    "serverPort": "8080",
    "authenticationType": "session",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": "no",
    "websocket": "spring-websocket",
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": "elasticsearch",
    "buildTool": "maven",
    "enableSocialSignIn": true,
    "rememberMeKey": "",
    "useSass": false,
    "applicationType": "monolith",
    "testFrameworks": [
      "gatling"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en"
    ]
  }
}

##### **Browsers and Operating System** 
Doesn't matter it is a spring configuration problem

##### **Reproduce the error** 
yo jhipster
yo jhipster:import-jdl jhipster-jdl.jh

##### **Related issues** 
I search by jdl and didn't find anything

##### **Suggest a Fix** 
use @Autowired annotation instead of @Inject in the employeeMapper object in EmployeeResource.java in package web.rest

**Comment by jdubois** [comment]
- The JDL isn't doing anything here, it's just generating JHipster config files -> if there is an issue here, it's related to JHipster, not the JDL
- @Autowired and @Inject basically do the same thing - there are some differences, of course, but I don't think that should cause a bug here

Of course, to answer you about @Autowired vs @Inject I need to have your stacktrace - can you give more information, here you just write "the app is not working". You must have a stacktrace, etc...

I'm putting this as "waiting for information" in the meantime

**Comment by argoal** [comment]
Here you go this is the error:

2016-06-01 16:37:13.796[0;39m [33m WARN[0;39m [35m10109[0;39m [2m---[0;39m [2m[ost-startStop-1][0;39m [36mo.a.c.loader.WebappClassLoaderBase      [0;39m [2m:[0;39m The web application [ROOT] appears to have started a thread named [Abandoned connection cleanup thread] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 java.lang.Object.wait(Native Method)
 java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:143)
 com.mysql.jdbc.AbandonedConnectionCleanupThread.run(AbandonedConnectionCleanupThread.java:43)
[2m2016-06-01 16:37:13.797[0;39m [33m WARN[0;39m [35m10109[0;39m [2m---[0;39m [2m[ost-startStop-1][0;39m [36mo.a.c.loader.WebappClassLoaderBase      [0;39m [2m:[0;39m The web application [ROOT] appears to have started a thread named [MVStore background writer nio:/home/ardi/Documents/jhipster/jdl/target/h2db/db/jdl.mv.db] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 java.lang.Object.wait(Native Method)
 org.h2.mvstore.MVStore$BackgroundWriterThread.run(MVStore.java:2684)
[2m2016-06-01 16:37:13.803[0;39m [31mERROR[0;39m [35m10109[0;39m [2m---[0;39m [2m[  restartedMain][0;39m [36mo.s.boot.SpringApplication              [0;39m [2m:[0;39m Application startup failed

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'employeeService': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: private al.jdl.web.rest.mapper.EmployeeMapper al.jdl.service.EmployeeService.employeeMapper; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type [al.jdl.web.rest.mapper.EmployeeMapper] found for dependency: expected at least 1 bean which qualifies as autowire candidate for this dependency. Dependency annotations: {@javax.inject.Inject()}
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:334)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1214)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:543)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:772)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:839)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:538)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:118)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:766)
	at org.springframework.boot.SpringApplication.createAndRefreshContext(SpringApplication.java:361)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:307)
	at al.jdl.JdlApp.main(JdlApp.java:64)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.springframework.boot.devtools.restart.RestartLauncher.run(RestartLauncher.java:49)
Caused by: org.springframework.beans.factory.BeanCreationException: Could not autowire field: private al.jdl.web.rest.mapper.EmployeeMapper al.jdl.service.EmployeeService.employeeMapper; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type [al.jdl.web.rest.mapper.EmployeeMapper] found for dependency: expected at least 1 bean which qualifies as autowire candidate for this dependency. Dependency annotations: {@javax.inject.Inject()}
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:573)
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:88)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:331)
	... 20 common frames omitted
Caused by: org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type [al.jdl.web.rest.mapper.EmployeeMapper] found for dependency: expected at least 1 bean which qualifies as autowire candidate for this dependency. Dependency annotations: {@javax.inject.Inject()}
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.raiseNoSuchBeanDefinitionException(DefaultListableBeanFactory.java:1373)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1119)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1014)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:545)
	... 22 common frames omitted

[2m2016-06-01 16:37:13.808[0;39m [33m WARN[0;39m [35m10109[0;39m [2m---[0;39m [2m[  restartedMain][0;39m [36mo.s.boot.SpringApplication              [0;39m [2m:[0;39m Error handling failed (Error creating bean with name 'delegatingApplicationListener' defined in class path resource [org/springframework/security/config/annotation/web/configuration/WebSecurityConfiguration.class]: BeanPostProcessor before instantiation of bean failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.cache.annotation.ProxyCachingConfiguration': Initialization of bean failed; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No bean named 'org.springframework.context.annotation.ConfigurationClassPostProcessor.importRegistry' is defined)

**Comment by jdubois** [comment]
From your stacktrace, Spring doesn't find the "employeeService" bean, are you sure it exists?
And it looks like you're using MapStruct, so for this you need to have the annotation post processor working, did you try running the app from Maven, using `./mvnw`?

**Comment by argoal** [comment]
Running the app through: ./mvnw gives no error and is ok, and now when I put back @Inject everything is working.

However I managed to reproduce the error and the steps are:
* mkdir jdltest
* cd jdltest
* yo jhipster
* import in STS as a maven project
* yo jhipster:import-jdl /home/ardi/jhipster-jdl.jh (overrite the files when asked by generator)
* Refresh project
* Run as Spring Boot App

And the stacktrace is:
09:30:25.321 [main] DEBUG org.springframework.beans.factory.config.YamlPropertiesFactoryBean - Loading from YAML: class path resource [config/application.yml]
09:30:25.372 [main] DEBUG org.springframework.beans.factory.config.YamlPropertiesFactoryBean - Merging document (no matchers set): {management={context-path=/management, health={mail={enabled=false}}}, spring={application={name=jdltest}, profiles={active=dev}, jpa={open-in-view=false, hibernate={ddl-auto=none, naming-strategy=org.springframework.boot.orm.jpa.hibernate.SpringNamingStrategy}}, messages={basename=i18n/messages}, mvc={favicon={enabled=false}}, thymeleaf={mode=XHTML}, social={google={clientId=xxx, clientSecret=xxx}, facebook={clientId=xxx, clientSecret=xxx}, twitter={clientId=xxx, clientSecret=xxx}}}, security={basic={enabled=false}}, jhipster={async={corePoolSize=2, maxPoolSize=50, queueCapacity=10000}, mail={from=jdltest@localhost}, swagger={title=jdltest API, description=jdltest API documentation, version=0.0.1, termsOfServiceUrl=null, contactName=null, contactUrl=null, contactEmail=null, license=null, licenseUrl=null}, social={redirectAfterSignIn=/#/home}, ribbon={displayOnActiveProfiles=dev}}}
09:30:25.372 [main] DEBUG org.springframework.beans.factory.config.YamlPropertiesFactoryBean - Loaded 1 document from YAML resource: class path resource [config/application.yml]
09:30:25.471 [restartedMain] DEBUG org.springframework.beans.factory.config.YamlPropertiesFactoryBean - Loading from YAML: class path resource [config/application.yml]
09:30:25.480 [restartedMain] DEBUG org.springframework.beans.factory.config.YamlPropertiesFactoryBean - Merging document (no matchers set): {management={context-path=/management, health={mail={enabled=false}}}, spring={application={name=jdltest}, profiles={active=dev}, jpa={open-in-view=false, hibernate={ddl-auto=none, naming-strategy=org.springframework.boot.orm.jpa.hibernate.SpringNamingStrategy}}, messages={basename=i18n/messages}, mvc={favicon={enabled=false}}, thymeleaf={mode=XHTML}, social={google={clientId=xxx, clientSecret=xxx}, facebook={clientId=xxx, clientSecret=xxx}, twitter={clientId=xxx, clientSecret=xxx}}}, security={basic={enabled=false}}, jhipster={async={corePoolSize=2, maxPoolSize=50, queueCapacity=10000}, mail={from=jdltest@localhost}, swagger={title=jdltest API, description=jdltest API documentation, version=0.0.1, termsOfServiceUrl=null, contactName=null, contactUrl=null, contactEmail=null, license=null, licenseUrl=null}, social={redirectAfterSignIn=/#/home}, ribbon={displayOnActiveProfiles=dev}}}
09:30:25.480 [restartedMain] DEBUG org.springframework.beans.factory.config.YamlPropertiesFactoryBean - Loaded 1 document from YAML resource: class path resource [config/application.yml]

  [32m      ██ [31m ██    ██  ████████  ███████    ██████  ████████  ████████  ███████
  [32m      ██ [31m ██    ██     ██     ██    ██  ██          ██     ██        ██    ██
  [32m      ██ [31m ████████     ██     ███████    █████      ██     ██████    ███████
  [32m██    ██ [31m ██    ██     ██     ██             ██     ██     ██        ██   ██
  [32m ██████  [31m ██    ██  ████████  ██        ██████      ██     ████████  ██    ██

[94m:: JHipster 🤓  :: Running Spring Boot 1.3.5.RELEASE ::
:: http://jhipster.github.io ::[39m

[2m2016-06-02 09:30:26.460[0;39m [32m INFO[0;39m [35m13329[0;39m [2m---[0;39m [2m[  restartedMain][0;39m [36mal.jdltest.JdltestApp                   [0;39m [2m:[0;39m Starting JdltestApp on workbox with PID 13329 (/home/ardi/Documents/jhipster/jdltest/target/classes started by ardi in /home/ardi/Documents/jhipster/jdltest)
[2m2016-06-02 09:30:26.462[0;39m [32mDEBUG[0;39m [35m13329[0;39m [2m---[0;39m [2m[  restartedMain][0;39m [36mal.jdltest.JdltestApp                   [0;39m [2m:[0;39m Running with Spring Boot v1.3.5.RELEASE, Spring v4.2.6.RELEASE
[2m2016-06-02 09:30:26.464[0;39m [32m INFO[0;39m [35m13329[0;39m [2m---[0;39m [2m[  restartedMain][0;39m [36mal.jdltest.JdltestApp                   [0;39m [2m:[0;39m The following profiles are active: dev
[2m2016-06-02 09:30:27.123[0;39m [32mDEBUG[0;39m [35m13329[0;39m [2m---[0;39m [2m[kground-preinit][0;39m [36morg.jboss.logging                       [0;39m [2m:[0;39m Logging Provider: org.jboss.logging.Slf4jLoggerProvider found via system property
[2m2016-06-02 09:30:31.060[0;39m [32mDEBUG[0;39m [35m13329[0;39m [2m---[0;39m [2m[  restartedMain][0;39m [36mal.jdltest.config.AsyncConfiguration    [0;39m [2m:[0;39m Creating Async Task Executor
[2m2016-06-02 09:30:31.566[0;39m [32mDEBUG[0;39m [35m13329[0;39m [2m---[0;39m [2m[  restartedMain][0;39m [36mal.jdltest.config.MetricsConfiguration  [0;39m [2m:[0;39m Registering JVM gauges
[2m2016-06-02 09:30:31.581[0;39m [32mDEBUG[0;39m [35m13329[0;39m [2m---[0;39m [2m[  restartedMain][0;39m [36mal.jdltest.config.MetricsConfiguration  [0;39m [2m:[0;39m Initializing Metrics JMX reporting
[2m2016-06-02 09:30:33.218[0;39m [32m INFO[0;39m [35m13329[0;39m [2m---[0;39m [2m[ost-startStop-1][0;39m [36mal.jdltest.config.WebConfigurer         [0;39m [2m:[0;39m Web application configuration, using profiles: [dev]
[2m2016-06-02 09:30:33.218[0;39m [32mDEBUG[0;39m [35m13329[0;39m [2m---[0;39m [2m[ost-startStop-1][0;39m [36mal.jdltest.config.WebConfigurer         [0;39m [2m:[0;39m Initializing Metrics registries
[2m2016-06-02 09:30:33.222[0;39m [32mDEBUG[0;39m [35m13329[0;39m [2m---[0;39m [2m[ost-startStop-1][0;39m [36mal.jdltest.config.WebConfigurer         [0;39m [2m:[0;39m Registering Metrics Filter
[2m2016-06-02 09:30:33.222[0;39m [32mDEBUG[0;39m [35m13329[0;39m [2m---[0;39m [2m[ost-startStop-1][0;39m [36mal.jdltest.config.WebConfigurer         [0;39m [2m:[0;39m Registering Metrics Servlet
[2m2016-06-02 09:30:33.224[0;39m [32mDEBUG[0;39m [35m13329[0;39m [2m---[0;39m [2m[ost-startStop-1][0;39m [36mal.jdltest.config.WebConfigurer         [0;39m [2m:[0;39m Initialize H2 console
[2m2016-06-02 09:30:33.225[0;39m [32m INFO[0;39m [35m13329[0;39m [2m---[0;39m [2m[ost-startStop-1][0;39m [36mal.jdltest.config.WebConfigurer         [0;39m [2m:[0;39m Web application fully configured
[2m2016-06-02 09:30:33.776[0;39m [32mDEBUG[0;39m [35m13329[0;39m [2m---[0;39m [2m[ost-startStop-1][0;39m [36mal.jdltest.config.DatabaseConfiguration [0;39m [2m:[0;39m Configuring Datasource
[2m2016-06-02 09:30:34.128[0;39m [32mDEBUG[0;39m [35m13329[0;39m [2m---[0;39m [2m[ost-startStop-1][0;39m [36mal.jdltest.config.DatabaseConfiguration [0;39m [2m:[0;39m Configuring Liquibase
[2m2016-06-02 09:30:34.159[0;39m [33m WARN[0;39m [35m13329[0;39m [2m---[0;39m [2m[test-Executor-1][0;39m [36ma.j.c.liquibase.AsyncSpringLiquibase    [0;39m [2m:[0;39m Starting Liquibase asynchronously, your database might not be ready at startup!
[2m2016-06-02 09:30:37.181[0;39m [33m WARN[0;39m [35m13329[0;39m [2m---[0;39m [2m[ost-startStop-1][0;39m [36mo.h.c.e.AbstractEhcacheRegionFactory    [0;39m [2m:[0;39m HHH020003: Could not find a specific ehcache configuration for cache named [al.jdltest.domain.Task]; using defaults.
[2m2016-06-02 09:30:37.211[0;39m [32mDEBUG[0;39m [35m13329[0;39m [2m---[0;39m [2m[test-Executor-1][0;39m [36ma.j.c.liquibase.AsyncSpringLiquibase    [0;39m [2m:[0;39m Started Liquibase in 3051 ms
[2m2016-06-02 09:30:37.316[0;39m [33m WARN[0;39m [35m13329[0;39m [2m---[0;39m [2m[ost-startStop-1][0;39m [36mo.h.c.e.AbstractEhcacheRegionFactory    [0;39m [2m:[0;39m HHH020003: Could not find a specific ehcache configuration for cache named [al.jdltest.domain.Department]; using defaults.
[2m2016-06-02 09:30:37.331[0;39m [33m WARN[0;39m [35m13329[0;39m [2m---[0;39m [2m[ost-startStop-1][0;39m [36mo.h.c.e.AbstractEhcacheRegionFactory    [0;39m [2m:[0;39m HHH020003: Could not find a specific ehcache configuration for cache named [al.jdltest.domain.JobHistory]; using defaults.
[2m2016-06-02 09:30:37.345[0;39m [33m WARN[0;39m [35m13329[0;39m [2m---[0;39m [2m[ost-startStop-1][0;39m [36mo.h.c.e.AbstractEhcacheRegionFactory    [0;39m [2m:[0;39m HHH020003: Could not find a specific ehcache configuration for cache named [al.jdltest.domain.Location]; using defaults.
[2m2016-06-02 09:30:37.362[0;39m [33m WARN[0;39m [35m13329[0;39m [2m---[0;39m [2m[ost-startStop-1][0;39m [36mo.h.c.e.AbstractEhcacheRegionFactory    [0;39m [2m:[0;39m HHH020003: Could not find a specific ehcache configuration for cache named [al.jdltest.domain.Job]; using defaults.
[2m2016-06-02 09:30:37.404[0;39m [33m WARN[0;39m [35m13329[0;39m [2m---[0;39m [2m[ost-startStop-1][0;39m [36mo.h.c.e.AbstractEhcacheRegionFactory    [0;39m [2m:[0;39m HHH020003: Could not find a specific ehcache configuration for cache named [al.jdltest.domain.SocialUserConnection]; using defaults.
[2m2016-06-02 09:30:37.420[0;39m [33m WARN[0;39m [35m13329[0;39m [2m---[0;39m [2m[ost-startStop-1][0;39m [36mo.h.c.e.AbstractEhcacheRegionFactory    [0;39m [2m:[0;39m HHH020003: Could not find a specific ehcache configuration for cache named [al.jdltest.domain.Employee]; using defaults.
[2m2016-06-02 09:30:37.439[0;39m [33m WARN[0;39m [35m13329[0;39m [2m---[0;39m [2m[ost-startStop-1][0;39m [36mo.h.c.e.AbstractEhcacheRegionFactory    [0;39m [2m:[0;39m HHH020003: Could not find a specific ehcache configuration for cache named [al.jdltest.domain.Region]; using defaults.
[2m2016-06-02 09:30:37.452[0;39m [33m WARN[0;39m [35m13329[0;39m [2m---[0;39m [2m[ost-startStop-1][0;39m [36mo.h.c.e.AbstractEhcacheRegionFactory    [0;39m [2m:[0;39m HHH020003: Could not find a specific ehcache configuration for cache named [al.jdltest.domain.Country]; using defaults.
[2m2016-06-02 09:30:37.474[0;39m [33m WARN[0;39m [35m13329[0;39m [2m---[0;39m [2m[ost-startStop-1][0;39m [36mo.h.c.e.AbstractEhcacheRegionFactory    [0;39m [2m:[0;39m HHH020003: Could not find a specific ehcache configuration for cache named [al.jdltest.domain.Task.jobs]; using defaults.
[2m2016-06-02 09:30:37.485[0;39m [33m WARN[0;39m [35m13329[0;39m [2m---[0;39m [2m[ost-startStop-1][0;39m [36mo.h.c.e.AbstractEhcacheRegionFactory    [0;39m [2m:[0;39m HHH020003: Could not find a specific ehcache configuration for cache named [al.jdltest.domain.Job.tasks]; using defaults.
[2m2016-06-02 09:30:37.493[0;39m [33m WARN[0;39m [35m13329[0;39m [2m---[0;39m [2m[ost-startStop-1][0;39m [36mo.h.c.e.AbstractEhcacheRegionFactory    [0;39m [2m:[0;39m HHH020003: Could not find a specific ehcache configuration for cache named [al.jdltest.domain.Department.employees]; using defaults.
[2m2016-06-02 09:30:37.499[0;39m [33m WARN[0;39m [35m13329[0;39m [2m---[0;39m [2m[ost-startStop-1][0;39m [36mo.h.c.e.AbstractEhcacheRegionFactory    [0;39m [2m:[0;39m HHH020003: Could not find a specific ehcache configuration for cache named [al.jdltest.domain.Employee.jobs]; using defaults.
[2m2016-06-02 09:30:38.639[0;39m [32m INFO[0;39m [35m13329[0;39m [2m---[0;39m [2m[ost-startStop-1][0;39m [36mal.jdltest.JdltestApp                   [0;39m [2m:[0;39m Running with Spring profile(s) : [dev]
[2m2016-06-02 09:30:39.281[0;39m [32mDEBUG[0;39m [35m13329[0;39m [2m---[0;39m [2m[  restartedMain][0;39m [36ma.j.config.social.SocialConfiguration   [0;39m [2m:[0;39m Configuring GoogleConnectionFactory
[2m2016-06-02 09:30:39.293[0;39m [32mDEBUG[0;39m [35m13329[0;39m [2m---[0;39m [2m[  restartedMain][0;39m [36ma.j.config.social.SocialConfiguration   [0;39m [2m:[0;39m Configuring FacebookConnectionFactory
[2m2016-06-02 09:30:39.298[0;39m [32mDEBUG[0;39m [35m13329[0;39m [2m---[0;39m [2m[  restartedMain][0;39m [36ma.j.config.social.SocialConfiguration   [0;39m [2m:[0;39m Configuring TwitterConnectionFactory
[2m2016-06-02 09:30:43.692[0;39m [33m WARN[0;39m [35m13329[0;39m [2m---[0;39m [2m[  restartedMain][0;39m [36mationConfigEmbeddedWebApplicationContext[0;39m [2m:[0;39m Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'employeeService': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: private al.jdltest.web.rest.mapper.EmployeeMapper al.jdltest.service.EmployeeService.employeeMapper; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type [al.jdltest.web.rest.mapper.EmployeeMapper] found for dependency: expected at least 1 bean which qualifies as autowire candidate for this dependency. Dependency annotations: {@javax.inject.Inject()}
[2m2016-06-02 09:30:43.872[0;39m [32m INFO[0;39m [35m13329[0;39m [2m---[0;39m [2m[  restartedMain][0;39m [36mal.jdltest.config.CacheConfiguration    [0;39m [2m:[0;39m Remove Cache Manager metrics
[2m2016-06-02 09:30:43.881[0;39m [32m INFO[0;39m [35m13329[0;39m [2m---[0;39m [2m[  restartedMain][0;39m [36mal.jdltest.config.CacheConfiguration    [0;39m [2m:[0;39m Closing Cache Manager
[2m2016-06-02 09:30:43.881[0;39m [33m WARN[0;39m [35m13329[0;39m [2m---[0;39m [2m[  restartedMain][0;39m [36m.s.c.a.CommonAnnotationBeanPostProcessor[0;39m [2m:[0;39m Invocation of destroy method failed on bean with name 'cacheConfiguration': java.lang.NullPointerException
[2m2016-06-02 09:30:43.927[0;39m [33m WARN[0;39m [35m13329[0;39m [2m---[0;39m [2m[ost-startStop-1][0;39m [36mo.a.c.loader.WebappClassLoaderBase      [0;39m [2m:[0;39m The web application [ROOT] appears to have started a thread named [Abandoned connection cleanup thread] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 java.lang.Object.wait(Native Method)
 java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:143)
 com.mysql.jdbc.AbandonedConnectionCleanupThread.run(AbandonedConnectionCleanupThread.java:43)
[2m2016-06-02 09:30:43.928[0;39m [33m WARN[0;39m [35m13329[0;39m [2m---[0;39m [2m[ost-startStop-1][0;39m [36mo.a.c.loader.WebappClassLoaderBase      [0;39m [2m:[0;39m The web application [ROOT] appears to have started a thread named [MVStore background writer nio:/home/ardi/Documents/jhipster/jdltest/target/h2db/db/jdltest.mv.db] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 java.lang.Object.wait(Native Method)
 org.h2.mvstore.MVStore$BackgroundWriterThread.run(MVStore.java:2684)
[2m2016-06-02 09:30:43.939[0;39m [31mERROR[0;39m [35m13329[0;39m [2m---[0;39m [2m[  restartedMain][0;39m [36mo.s.boot.SpringApplication              [0;39m [2m:[0;39m Application startup failed

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'employeeService': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: private al.jdltest.web.rest.mapper.EmployeeMapper al.jdltest.service.EmployeeService.employeeMapper; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type [al.jdltest.web.rest.mapper.EmployeeMapper] found for dependency: expected at least 1 bean which qualifies as autowire candidate for this dependency. Dependency annotations: {@javax.inject.Inject()}
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:334)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1214)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:543)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:772)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:839)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:538)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:118)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:766)
	at org.springframework.boot.SpringApplication.createAndRefreshContext(SpringApplication.java:361)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:307)
	at al.jdltest.JdltestApp.main(JdltestApp.java:64)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.springframework.boot.devtools.restart.RestartLauncher.run(RestartLauncher.java:49)
Caused by: org.springframework.beans.factory.BeanCreationException: Could not autowire field: private al.jdltest.web.rest.mapper.EmployeeMapper al.jdltest.service.EmployeeService.employeeMapper; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type [al.jdltest.web.rest.mapper.EmployeeMapper] found for dependency: expected at least 1 bean which qualifies as autowire candidate for this dependency. Dependency annotations: {@javax.inject.Inject()}
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:573)
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:88)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:331)
	... 20 common frames omitted
Caused by: org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type [al.jdltest.web.rest.mapper.EmployeeMapper] found for dependency: expected at least 1 bean which qualifies as autowire candidate for this dependency. Dependency annotations: {@javax.inject.Inject()}
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.raiseNoSuchBeanDefinitionException(DefaultListableBeanFactory.java:1373)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1119)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1014)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:545)
	... 22 common frames omitted

[2m2016-06-02 09:30:43.945[0;39m [33m WARN[0;39m [35m13329[0;39m [2m---[0;39m [2m[  restartedMain][0;39m [36mo.s.boot.SpringApplication              [0;39m [2m:[0;39m Error handling failed (Error creating bean with name 'delegatingApplicationListener' defined in class path resource [org/springframework/security/config/annotation/web/configuration/WebSecurityConfiguration.class]: BeanPostProcessor before instantiation of bean failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.cache.annotation.ProxyCachingConfiguration': Initialization of bean failed; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No bean named 'org.springframework.context.annotation.ConfigurationClassPostProcessor.importRegistry' is defined)


Now giving:
`./mvnw`

gives no error.


As you said there should be no diffrence between @Autowired and @Inject in this case, I would assume that there is a problem with Spring Boot App.

**Comment by jdubois** [comment]
OK, if it works with `./mvnw` then your issue is definitely because you have DTOs. Have a look at http://jhipster.github.io/using-dtos/ -> your issue is that your IDE isn't correctly configured to handle Mapstruct.
That's the annoying thing with Mapstruct, and that's why I still keep it has "beta". It works, but you need to do some black magic on some IDEs to have it work correctly.
