### ISSUE TITLE
Error PROD compilation JHipster

### ISSUE THREAD

**Issue by marco565** [jhipster/generator-jhipster#3732]
##### **Overview of the issue**

There is an error on the compilation just after the generation of the JHipster microservice gateway

##### **Motivation for or Use Case** 

I can't compile the application in PROD mode `./mvnw package -Pprod`

##### **JHipster Version(s)** 

I am using micro service gateway 3.4.1

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder** 

```JSON

  "generator-jhipster": {
    "jhipsterVersion": "3.4.1",
    "baseName": "testippondata",
    "packageName": "com.test.data",
    "packageFolder": "com/test/data",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "hazelcast",
    "clusteredHttpSession": "no",
    "websocket": "spring-websocket",
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "postgresql",
    "searchEngine": "no",
    "buildTool": "maven",
    "jwtSecretKey": "e031e32bdc9a54534c50a0c9ffe6265f0636f269",
    "useSass": true,
    "applicationType": "gateway",
    "testFrameworks": [
      "gatling"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en",
      "fr"
    ],
    "enableSocialSignIn": false
  }
```

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory** 

No entities

##### **Browsers and Operating System** 

Mac OSX

##### **Reproduce the error** 

`./mvnw package -Pprod`

** Error: **
```
[INFO] [15:33:31] Finished 'inject:troubleshoot' after 6.3 ms
[INFO] [15:33:31] Starting 'images'...
[INFO] [15:33:31] Starting 'sass'...
[INFO] [15:33:31] Starting 'html'...
[INFO] [15:33:32] Tested 3 tests, 3 passes, 0 failures: PASS
[ERROR] fs.js:839
[ERROR]   return binding.lstat(pathModule._makeLong(path));
[ERROR]                  ^
[ERROR]
[ERROR] Error: ENOENT: no such file or directory, lstat '/Users/mthebault/projets/dataforce/examples/src/main/webapp/app/templates.js'
[ERROR]     at Error (native)
[ERROR]     at Object.fs.lstatSync (fs.js:839:18)
[ERROR]     at DestroyableTransform.TransformStream [as _transform] (/Users/mthebault/projets/dataforce/examples/node_modules/gulp-header/index.js:38:12)
[ERROR]     at DestroyableTransform.Transform._read (/Users/mthebault/projets/dataforce/examples/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:159:10)
[ERROR]     at DestroyableTransform.Transform._write (/Users/mthebault/projets/dataforce/examples/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:147:83)
[ERROR]     at doWrite (/Users/mthebault/projets/dataforce/examples/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:313:64)
[ERROR]     at writeOrBuffer (/Users/mthebault/projets/dataforce/examples/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:302:5)
[ERROR]     at DestroyableTransform.Writable.write (/Users/mthebault/projets/dataforce/examples/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:241:11)
[ERROR]     at write (/Users/mthebault/projets/dataforce/examples/node_modules/gulp-concat/node_modules/readable-stream/lib/_stream_readable.js:623:24)
[ERROR]     at flow (/Users/mthebault/projets/dataforce/examples/node_modules/gulp-concat/node_modules/readable-stream/lib/_stream_readable.js:632:7)
[ERROR]     at DestroyableTransform.pipeOnReadable (/Users/mthebault/projets/dataforce/examples/node_modules/gulp-concat/node_modules/readable-stream/lib/_stream_readable.js:664:5)
[ERROR]     at emitNone (events.js:67:13)
[ERROR]     at DestroyableTransform.emit (events.js:166:7)
[ERROR]     at emitReadable_ (/Users/mthebault/projets/dataforce/examples/node_modules/gulp-concat/node_modules/readable-stream/lib/_stream_readable.js:448:10)
[ERROR]     at emitReadable (/Users/mthebault/projets/dataforce/examples/node_modules/gulp-concat/node_modules/readable-stream/lib/_stream_readable.js:444:5)
[ERROR]     at readableAddChunk (/Users/mthebault/projets/dataforce/examples/node_modules/gulp-concat/node_modules/readable-stream/lib/_stream_readable.js:187:9)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 21.328 s
[INFO] Finished at: 2016-06-17T15:33:32+02:00
[INFO] Final Memory: 54M/543M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.0:gulp (gulp build) on project testippondata: Failed to run task: 'gulp.js build --no-notification' failed. (error code 139) -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

```
##### **Related issues** 

No

##### **Suggest a Fix** 

The following file is not present in the application :
`Error: ENOENT: no such file or directory, lstat '/Users/mthebault/projets/dataforce/examples/src/main/webapp/app/templates.js'`

**Comment by deepu105** [comment]
we dont generate any file name `templates.js` in `webapp/app folder` did you make any changes or is it a default app? did you install gulp and node-sass?

**Comment by ruddell** [comment]
Several people in the Gitter chat noticed this too.  The cause is from another project referenced by gulp-angular-templatecache. https://github.com/miickel/gulp-angular-templatecache/issues/124 

The temporary solution is to add `"gulp-header": "1.8.2",` in package.json.

**Comment by AlexMinsk** [comment]
Now `"gulp-angular-templatecache": "1.9.0"` fix the issue.

**Comment by pascalgrimaud** [comment]
thanks @ruddell 
I confirm it too. I have the same issue, for every options, but only for build in production

**Comment by pascalgrimaud** [comment]
You're right, @AlexMinsk I will do the change

**Comment by pascalgrimaud** [comment]
@jdubois : I think a new minor release is needed -> currently, `mvn package -Pprod` doesn't work anymore in the last release, the problem comes from some changes in the lib 'gulp-angular-templatecache'

I fixed our Travis build to detect this

**Comment by deepu105** [comment]
Can someone PR a quick fix and may be we can release a patch

Thanks & regards,
Deepu

**Comment by jdubois** [comment]
OK this looks like a major issue.
I can do a release tomorrow if needed.

**Comment by JavierFuentes** [comment]
@ruddell's solution 

>
 add "gulp-header": "1.8.2", in package.json

works for me... thanks.

Set node version to exactly 4.3 in package.json and/or upgrade from 0.12 to 4.3 in travis.yml did not work for me.

**Comment by tibistibi** [comment]
adding:

         "gulp-angular-templatecache": "1.9.0",

to  /package.json worked for me :)
