### ISSUE TITLE
Microservices Sample Application not working!

### ISSUE THREAD

**Issue by matamagu** [jhipster/generator-jhipster#3762]
I am trying to build a simple microservices based application following the steps in the tutorial video..
https://www.youtube.com/watch?v=m0eZcfLHQyg

I could get the code for Jhipster Registry and the Registry app is up and running.
In the next step, I create a simple micro service with one database object. The microservice doesn't start.. It fails with below error messages....

I am new to JHipster.. I am not sure if i am missing something here.. Any help is highly appreciated.

:cleanResources
:processResources
:compileJava UP-TO-DATE
:compileScala UP-TO-DATE
:classes
:findMainClass
:bootRun
21:24:59.175 [main] DEBUG org.springframework.beans.factory.config.YamlPropertiesFactoryBean - Loading from YAML: class path resource [config/application.yml]
21:24:59.232 [main] DEBUG org.springframework.beans.factory.config.YamlPropertiesFactoryBean - Merging document (no matchers set): {eureka={instance={appname=programservice, instanceId=programservice:${spring.application.instance_id:${random.value}}}}, ribbon={eureka={enabled=true}}, management={context-path=/management, health={mail={enabled=false}}}, spring={application={name=programservice}, profiles={active=dev}, jpa={open-in-view=false, hibernate={ddl-auto=none, naming-strategy=org.springframework.boot.orm.jpa.hibernate.SpringNamingStrategy}}, messages={basename=i18n/messages}, mvc={favicon={enabled=false}}, thymeleaf={mode=XHTML}}, security={basic={enabled=false}}, jhipster={async={corePoolSize=2, maxPoolSize=50, queueCapacity=10000}, mail={from=programservice@localhost}, swagger={title=programservice API, description=programservice API documentation, version=0.0.1, termsOfServiceUrl=null, contactName=null, contactUrl=null, contactEmail=null, license=null, licenseUrl=null}, ribbon={displayOnActiveProfiles=dev}}}
21:24:59.232 [main] DEBUG org.springframework.beans.factory.config.YamlPropertiesFactoryBean - Loaded 1 document from YAML resource: class path resource [config/application.yml]
21:24:59.388 [restartedMain] DEBUG org.springframework.beans.factory.config.YamlPropertiesFactoryBean - Loading from YAML: class path resource [config/application.yml]
21:24:59.395 [restartedMain] DEBUG org.springframework.beans.factory.config.YamlPropertiesFactoryBean - Merging document (no matchers set): {eureka={instance={appname=programservice, instanceId=programservice:${spring.application.instance_id:${random.value}}}}, ribbon={eureka={enabled=true}}, management={context-path=/management, health={mail={enabled=false}}}, spring={application={name=programservice}, profiles={active=dev}, jpa={open-in-view=false, hibernate={ddl-auto=none, naming-strategy=org.springframework.boot.orm.jpa.hibernate.SpringNamingStrategy}}, messages={basename=i18n/messages}, mvc={favicon={enabled=false}}, thymeleaf={mode=XHTML}}, security={basic={enabled=false}}, jhipster={async={corePoolSize=2, maxPoolSize=50, queueCapacity=10000}, mail={from=programservice@localhost}, swagger={title=programservice API, description=programservice API documentation, version=0.0.1, termsOfServiceUrl=null, contactName=null, contactUrl=null, contactEmail=null, license=null, licenseUrl=null}, ribbon={displayOnActiveProfiles=dev}}}
21:24:59.395 [restartedMain] DEBUG org.springframework.beans.factory.config.YamlPropertiesFactoryBean - Loaded 1 document from YAML resource: class path resource [config/application.yml]
2016-06-23 21:25:01.773 DEBUG 6432 --- [kground-preinit] org.jboss.logging                        : Logging Provider: org.jboss.logging.Slf4jLoggerProvider found via system property

        ??  ??    ??  ????????  ???????    ??????  ????????  ????????  ???????
        ??  ??    ??     ??     ??    ??  ??          ??     ??        ??    ??
        ??  ????????     ??     ???????    ?????      ??     ??????    ???????
  ??    ??  ??    ??     ??     ??             ??     ??     ??        ??   ??
   ??????   ??    ??  ????????  ??        ??????      ??     ????????  ??    ??

:: JHipster ?  :: Running Spring Boot 1.3.5.RELEASE ::
:: http://jhipster.github.io ::

2016-06-23 21:25:03.316 DEBUG 6432 --- [  restartedMain] s.n.www.protocol.http.HttpURLConnection  : sun.net.www.MessageHeader@7fbbc8316 pairs: {GET /config/programservice/dev/master HTTP/1.1: null}{Accept: application/json, application/*+json}{Authorization: Basic YWRtaW46YWRtaW4=}{User-Agent: Java/1.8.0_91}{Host: localhost:8761}{Connection: keep-alive}
2016-06-23 21:25:03.328 DEBUG 6432 --- [  restartedMain] s.n.www.protocol.http.HttpURLConnection  : sun.net.www.MessageHeader@4373c45011 pairs: {null: HTTP/1.1 404 Not Found}{Server: Apache-Coyote/1.1}{X-Content-Type-Options: nosniff}{X-XSS-Protection: 1; mode=block}{Cache-Control: no-cache, no-store, max-age=0, must-revalidate}{Pragma: no-cache}{Expires: 0}{X-Application-Context: jhipster-registry:dev:8761}{Content-Type: application/json;charset=UTF-8}{Transfer-Encoding: chunked}{Date: Thu, 23 Jun 2016 15:55:02 GMT}
2016-06-23 21:25:04.358 DEBUG 6432 --- [  restartedMain] s.n.www.protocol.http.HttpURLConnection  : sun.net.www.MessageHeader@7b68917e6 pairs: {GET /config/programservice/dev/master HTTP/1.1: null}{Accept: application/json, application/*+json}{Authorization: Basic YWRtaW46YWRtaW4=}{User-Agent: Java/1.8.0_91}{Host: localhost:8761}{Connection: keep-alive}
2016-06-23 21:25:04.393 DEBUG 6432 --- [  restartedMain] s.n.www.protocol.http.HttpURLConnection  : sun.net.www.MessageHeader@5be4f07311 pairs: {null: HTTP/1.1 404 Not Found}{Server: Apache-Coyote/1.1}{X-Content-Type-Options: nosniff}{X-XSS-Protection: 1; mode=block}{Cache-Control: no-cache, no-store, max-age=0, must-revalidate}{Pragma: no-cache}{Expires: 0}{X-Application-Context: jhipster-registry:dev:8761}{Content-Type: application/json;charset=UTF-8}{Transfer-Encoding: chunked}{Date: Thu, 23 Jun 2016 15:55:04 GMT}
2016-06-23 21:25:05.518 DEBUG 6432 --- [  restartedMain] s.n.www.protocol.http.HttpURLConnection  : sun.net.www.MessageHeader@7ff1bc2d6 pairs: {GET /config/programservice/dev/master HTTP/1.1: null}{Accept: application/json, application/*+json}{Authorization: Basic YWRtaW46YWRtaW4=}{User-Agent: Java/1.8.0_91}{Host: localhost:8761}{Connection: keep-alive}
2016-06-23 21:25:05.548 DEBUG 6432 --- [  restartedMain] s.n.www.protocol.http.HttpURLConnection  : sun.net.www.MessageHeader@74f3499511 pairs: {null: HTTP/1.1 404 Not Found}{Server: Apache-Coyote/1.1}{X-Content-Type-Options: nosniff}{X-XSS-Protection: 1; mode=block}{Cache-Control: no-cache, no-store, max-age=0, must-revalidate}{Pragma: no-cache}{Expires: 0}{X-Application-Context: jhipster-registry:dev:8761}{Content-Type: application/json;charset=UTF-8}{Transfer-Encoding: chunked}{Date: Thu, 23 Jun 2016 15:55:05 GMT}
2016-06-23 21:25:06.776 DEBUG 6432 --- [  restartedMain] s.n.www.protocol.http.HttpURLConnection  : sun.net.www.MessageHeader@4bafd5146 pairs: {GET /config/programservice/dev/master HTTP/1.1: null}{Accept: application/json, application/*+json}{Authorization: Basic YWRtaW46YWRtaW4=}{User-Agent: Java/1.8.0_91}{Host: localhost:8761}{Connection: keep-alive}
2016-06-23 21:25:06.791 DEBUG 6432 --- [  restartedMain] s.n.www.protocol.http.HttpURLConnection  : sun.net.www.MessageHeader@3734d37a11 pairs: {null: HTTP/1.1 404 Not Found}{Server: Apache-Coyote/1.1}{X-Content-Type-Options: nosniff}{X-XSS-Protection: 1; mode=block}{Cache-Control: no-cache, no-store, max-age=0, must-revalidate}{Pragma: no-cache}{Expires: 0}{X-Application-Context: jhipster-registry:dev:8761}{Content-Type: application/json;charset=UTF-8}{Transfer-Encoding: chunked}{Date: Thu, 23 Jun 2016 15:55:06 GMT}
2016-06-23 21:25:08.151 DEBUG 6432 --- [  restartedMain] s.n.www.protocol.http.HttpURLConnection  : sun.net.www.MessageHeader@2b0757ab6 pairs: {GET /config/programservice/dev/master HTTP/1.1: null}{Accept: application/json, application/*+json}{Authorization: Basic YWRtaW46YWRtaW4=}{User-Agent: Java/1.8.0_91}{Host: localhost:8761}{Connection: keep-alive}
2016-06-23 21:25:08.186 DEBUG 6432 --- [  restartedMain] s.n.www.protocol.http.HttpURLConnection  : sun.net.www.MessageHeader@1e3520aa11 pairs: {null: HTTP/1.1 404 Not Found}{Server: Apache-Coyote/1.1}{X-Content-Type-Options: nosniff}{X-XSS-Protection: 1; mode=block}{Cache-Control: no-cache, no-store, max-age=0, must-revalidate}{Pragma: no-cache}{Expires: 0}{X-Application-Context: jhipster-registry:dev:8761}{Content-Type: application/json;charset=UTF-8}{Transfer-Encoding: chunked}{Date: Thu, 23 Jun 2016 15:55:08 GMT}
2016-06-23 21:25:09.678 DEBUG 6432 --- [  restartedMain] s.n.www.protocol.http.HttpURLConnection  : sun.net.www.MessageHeader@f8b8f156 pairs: {GET /config/programservice/dev/master HTTP/1.1: null}{Accept: application/json, application/*+json}{Authorization: Basic YWRtaW46YWRtaW4=}{User-Agent: Java/1.8.0_91}{Host: localhost:8761}{Connection: keep-alive}
2016-06-23 21:25:09.712 DEBUG 6432 --- [  restartedMain] s.n.www.protocol.http.HttpURLConnection  : sun.net.www.MessageHeader@7aa37aa811 pairs: {null: HTTP/1.1 404 Not Found}{Server: Apache-Coyote/1.1}{X-Content-Type-Options: nosniff}{X-XSS-Protection: 1; mode=block}{Cache-Control: no-cache, no-store, max-age=0, must-revalidate}{Pragma: no-cache}{Expires: 0}{X-Application-Context: jhipster-registry:dev:8761}{Content-Type: application/json;charset=UTF-8}{Transfer-Encoding: chunked}{Date: Thu, 23 Jun 2016 15:55:09 GMT}
2016-06-23 21:25:09.718 ERROR 6432 --- [  restartedMain] o.s.boot.SpringApplication               : Application startup failed

java.lang.IllegalStateException: Could not locate PropertySource and the fail fast property is set, failing
	at org.springframework.cloud.config.client.ConfigServicePropertySourceLocator.locate(ConfigServicePropertySourceLocator.java:110)
	at org.springframework.cloud.config.client.ConfigServicePropertySourceLocator$$FastClassBySpringCGLIB$$fa44b2a.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:720)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at org.springframework.retry.interceptor.RetryOperationsInterceptor$1.doWithRetry(RetryOperationsInterceptor.java:74)
	at org.springframework.retry.support.RetryTemplate.doExecute(RetryTemplate.java:263)
	at org.springframework.retry.support.RetryTemplate.execute(RetryTemplate.java:154)
	at org.springframework.retry.interceptor.RetryOperationsInterceptor.invoke(RetryOperationsInterceptor.java:101)
	at org.springframework.retry.annotation.AnnotationAwareRetryOperationsInterceptor.invoke(AnnotationAwareRetryOperationsInterceptor.java:118)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:655)
	at org.springframework.cloud.config.client.ConfigServicePropertySourceLocator$$EnhancerBySpringCGLIB$$c6bb1aa.locate(<generated>)
	at org.springframework.cloud.bootstrap.config.PropertySourceBootstrapConfiguration.initialize(PropertySourceBootstrapConfiguration.java:89)
	at org.springframework.boot.SpringApplication.applyInitializers(SpringApplication.java:640)
	at org.springframework.boot.SpringApplication.createAndRefreshContext(SpringApplication.java:343)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:307)
	at com.ge.brilliantlab.programservice.ProgramserviceApp.main(ProgramserviceApp.java:66)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.devtools.restart.RestartLauncher.run(RestartLauncher.java:49)

:bootRun FAILED

BUILD FAILED

Total time: 29.423 secs

**Comment by PierreBesson** [comment]
Your issue probably arise from your microservice being unable to connect to the Registry, please check that your `eureka.client.serviceUrl.defaultZone` property point to the url of your registry. 

Also please note that the issue tracker is not for support, it is a valuable tool for the team to track bugs, please ask your question in StackOverflow next time.
