### ISSUE TITLE
Unable to generate Entity using yo jhipster:entity (with latest version) , Please help Us

### ISSUE THREAD

**Issue by ranahasan** [jhipster/generator-jhipster#3829]
Please help us, When we tried to generate Entity using yo jhipster:entity , It shows  ->

/usr/lib/node_modules/generator-jhipster/generators/entity/index.js:12
const constants = require('../generator-constants'),
^^^^^
SyntaxError: Use of const in strict mode.
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.defineProperty.get [as jhipster:entity] (/usr/lib/node_modules/yo/node_modules/yeoman-environment/lib/store.js:40:23)
    at Store.get (/usr/lib/node_modules/yo/node_modules/yeoman-environment/lib/store.js:64:35)
    at Environment.get (/usr/lib/node_modules/yo/node_modules/yeoman-environment/lib/environment.js:259:21)

**Comment by deepu105** [comment]
​can you please follow our guidelines. what is your node version. This
seems like a node version issue you might be on a very old version which
doesnt support es6​


Thanks & Regards,
Deepu

**Comment by deepu105** [comment]
Please follow our [guidelines ](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md#issue) when opening issues if you want us to help you.
For bug reports please follow the template pre populated [here](https://github.com/jhipster/generator-jhipster/issues/new)
Open a new issue with proper details or update this issue with all details and request to re open.
Issues opened without proper details will be closed without explanation.

**Comment by ranahasan** [comment]
OK, Thank you for your response, still we are facing problem in latest version but old are working fine. I will again submit Issues as follow guidelines.
