### ISSUE TITLE
Remove the option to use microservices with the "skip-server" flag, as it doesn't make sense

### ISSUE THREAD

**Issue by jd-carroll** [jhipster/generator-jhipster#3864]
This morning I ran the following from a MacBook Pro at work:

```
$ npm install -g generator-jhipster yo

$ yo jhipster --skip-server

JHipster

Welcome to the JHipster Generator v3.5.0
Documentation for creating an application: https://jhipster.github.io/creating-an-app/
Application files will be generated in folder: /develop/ads-mobile/www/ng
? (1/16) Which *type* of application would you like to create? Microservice application
? (2/16) What is the base name of your application? ads
? (3/16) Would you like to enable internationalization support? No
? (4/16) Which testing frameworks would you like to use? (Press <space> to select)


readline.js:925
            throw err;
            ^

TypeError: Cannot read property 'checked' of undefined
    at Prompt.toggleChoice (/Users/CarroJD/.nvm/versions/node/v4.4.5/lib/node_modules/yo/node_modules/yeoman-environment/node_modules/inquirer/lib/prompts/checkbox.js:162:50)
    at Prompt.onSpaceKey (/Users/CarroJD/.nvm/versions/node/v4.4.5/lib/node_modules/yo/node_modules/yeoman-environment/node_modules/inquirer/lib/prompts/checkbox.js:157:8)
    at AnonymousObserver.Rx.AnonymousObserver.AnonymousObserver.next (/Users/CarroJD/.nvm/versions/node/v4.4.5/lib/node_modules/yo/node_modules/rx/dist/rx.js:1828:12)
    at AnonymousObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/Users/CarroJD/.nvm/versions/node/v4.4.5/lib/node_modules/yo/node_modules/rx/dist/rx.js:1762:31)
    at AnonymousObserver.tryCatcher (/Users/CarroJD/.nvm/versions/node/v4.4.5/lib/node_modules/yo/node_modules/rx/dist/rx.js:63:31)
    at AutoDetachObserverPrototype.next (/Users/CarroJD/.nvm/versions/node/v4.4.5/lib/node_modules/yo/node_modules/rx/dist/rx.js:5883:51)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/Users/CarroJD/.nvm/versions/node/v4.4.5/lib/node_modules/yo/node_modules/rx/dist/rx.js:1762:31)
    at AutoDetachObserver.tryCatcher (/Users/CarroJD/.nvm/versions/node/v4.4.5/lib/node_modules/yo/node_modules/rx/dist/rx.js:63:31)
    at AutoDetachObserverPrototype.next (/Users/CarroJD/.nvm/versions/node/v4.4.5/lib/node_modules/yo/node_modules/rx/dist/rx.js:5883:51)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/Users/CarroJD/.nvm/versions/node/v4.4.5/lib/node_modules/yo/node_modules/rx/dist/rx.js:1762:31)
```

**Comment by jd-carroll** [comment]
So I just tried to run `yo jhipster` (with out the `--skip-server`) and it only generated the server code...

```
$ yo jhipster

Welcome to the JHipster Generator v3.5.0
Documentation for creating an application: https://jhipster.github.io/creating-an-app/
Application files will be generated in folder: /develop/ads-mobile/www/ng
? (1/16) Which *type* of application would you like to create? Microservice application
? (2/16) What is the base name of your application? ads
? (3/16) As you are running in a microservice architecture, on which port would like your server to run? It should be unique to avoi
d port conflicts. 8081
? (4/16) What is your default Java package name? com.mycompany.myapp
? (5/16) Which *type* of authentication would you like to use? JWT authentication (stateless, with a token)
? (6/16) Which *type* of database would you like to use? Cassandra
? (7/16) Would you like to use Maven or Gradle for building the backend? Maven
? (8/16) Would you like to enable internationalization support? No
? (9/16) Which testing frameworks would you like to use? Gatling, Cucumber
   create README.md
   create .gitignore
   create .gitattributes
   create .editorconfig
   create .travis.yml
   create Jenkinsfile
   create src/main/docker/Dockerfile

...

   create src/test/java/com/mycompany/myapp/cucumber/CucumberTest.java
   create src/test/java/com/mycompany/myapp/cucumber/stepdefs/StepDefs.java

Server app generated successfully.

```

**Comment by jdubois** [comment]
Can you put a better title, your OS and Node versions, etc...

**Comment by jd-carroll** [comment]
Yeoman Version: 1.8.4

**Comment by jd-carroll** [comment]
Looks like the issue is selecting a project type other than `Monolithic`.  If you select anything other than `Monolithic` (and have `--skip-server`) you will encounter this error.  I've also reproduced these same conditions on `v3.4.2`.

**Comment by gmarziou** [comment]
Does it make a lot of sense to use this option with a gateway or a service?

**Comment by pascalgrimaud** [comment]
When there is "--skip-server", the user should not be able to select microservice.
As @gmarziou there is no sense !

**Comment by jdubois** [comment]
Indeed, there is no sense is doing a microservice with "skip-server"!
-> we should check for "skip-server" and remove that question, having automatically a monolith if it is selected.

**Comment by jdubois** [comment]
I renamed the ticket accordingly
