### ISSUE TITLE
Front end missing files in production profile

### ISSUE THREAD

**Issue by msellekAhmed** [jhipster/generator-jhipster#3914]
I developed an application using Jhipster V3.0

in dev profile and localy, everything works good, but when i switch to production profile to deploy the application in a distant virtual machine (centos) using docker I only get my footer visible.
there are no  error in the log, but when I inspect the front end, I find that some files are missing like :
- vendor.css
- main.css
- app.js

Since everything good in the dev profile locally, I wonder why its not working in the production profile (front end file missing in the war after running gradlew -Pprod bootRepackage)

I think that is due to my grunt version, that I cannot find in my package.json

here is my package.json file :

{
  "name": "hardisgeneco",
  "version": "0.0.0",
  "description": "Description for hardisgeneco",
  "private": true,
  "cacheDirectories": [
    "node_modules",
    "src/main/webapp/bower_components"
  ],
  "dependencies": {
    "bower": "^1.6.3"
  },
  "devDependencies": {
    "browser-sync": "2.11.2",
    "del": "2.2.0",
    "eslint-config-angular": "0.5.0",
    "eslint-plugin-angular": "1.0.0",
    "event-stream": "3.3.2",
    "generator-jhipster": "3.0.0",
    "gulp": "3.9.1",
    "gulp-angular-filesort": "1.1.1",
    "gulp-angular-templatecache": "1.8.0",
    "gulp-autoprefixer": "3.1.0",
    "gulp-changed": "1.3.0",
    "gulp-cssnano": "2.1.1",
    "gulp-eslint": "2.0.0",
    "gulp-flatten": "0.2.0",
    "gulp-footer": "1.0.5",
    "gulp-htmlmin": "1.3.0",
    "gulp-if": "2.0.0",
    "gulp-imagemin": "2.4.0",
    "gulp-inject": "3.0.0",
    "gulp-ng-annotate": "2.0.0",
    "gulp-ng-constant-fork": "0.4.1",
    "gulp-notify": "2.2.0",
    "gulp-plumber": "1.1.0",
    "gulp-rev": "7.0.0",
    "gulp-rev-replace": "^0.4.3",
    "gulp-sourcemaps": "1.6.0",
    "gulp-uglify": "1.5.3",
    "gulp-useref": "3.0.7",
    "jasmine-core": "2.4.1",
    "karma": "0.13.22",
    "karma-chrome-launcher": "0.2.3",
    "karma-coverage": "0.5.5",
    "karma-jasmine": "0.3.8",
    "karma-jenkins-reporter": "0.0.2",
    "karma-phantomjs-launcher": "1.0.0",
    "karma-script-launcher": "0.2.0",
    "lazypipe": "1.0.1",
    "lodash": "4.6.1",
    "map-stream": "0.0.6",
    "phantomjs-prebuilt": "2.1.4",
    "proxy-middleware": "0.15.0",
    "run-sequence": "1.1.5",
    "wiredep": "4.0.0",
    "yargs": "4.3.2"
  },
  "engines": {
    "node": "^4.3"
  },
  "scripts": {
    "test": "gulp test"
  }
}

and this is my .yo-rc file :
{
  "generator-jhipster": {
    "jhipsterVersion": "3.0.0",
    "baseName": "hardisgeneco",
    "packageName": "fr.hardis.ldap",
    "packageFolder": "fr/hardis/ldap",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "no",
    "clusteredHttpSession": "no",
    "websocket": "no",
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": "elasticsearch",
    "buildTool": "gradle",
    "enableSocialSignIn": false,
    "jwtSecretKey": "f968bbaf99303c35397b4162a229f8d6524cfbac",
    "useSass": false,
    "applicationType": "monolith",
    "testFrameworks": [
      "gatling"
    ],
In developpement I use windows 8 and in production i use centos with docker
Thnaks for your help

**Comment by jdubois** [comment]
There is no Grunt with JHipster v3.0.0, so that is definitely an issue if you are using Grunt :-)

Does this run OK on your local machine, when you do `gradlew -Pprod`?

**Comment by msellekAhmed** [comment]
Thanks for your answer,
in my local machine also when I run gradlew -Pprod bootRepackage, I get the footer only as when i deploy to the distant machine

**Comment by msellekAhmed** [comment]
I tried to run gradlew -Pprod 
I get the following log with an error :                                                                                                        :
C:\Users\ams1\workspace\hardisgeneco>gradlew -Pprod
:bower
:nodeSetup SKIPPED
:gulpBuildWithOpts
[15:13:46] Using gulpfile ~\workspace\hardisgeneco\gulpfile.js
[15:13:46] Starting 'clean'...
                                                                                              [15:13:47] Finished 'clean' after 399 ms
[15:13:47] Starting 'build'...
[15:13:47] Starting 'copy'...
                                                                                                                                                   [15:13:47] Starting 'wiredep:app'...
                                                                                                                                                   [15:13:47] Starting 'ngconstant:prod'...
                                                                                                                                                   [15:13:47] Starting 'languages'...
                                                                                                                                                   [15:13:47]                                                                                                                                          Finished 'ngconstant:prod' after 259 ms
                                                                                                                                                   [15:13:48] Finished 'languages' after 812 ms
                                                                                                                                                   [15:13:48]                                                                                                                                          Finished 'copy' after 1.28 s
                                                                                                                                                   [15:13:49] Finished 'wiredep:app' after 1.87 s
                                                                                                                                                   [15:13:49] Starting 'inject'...
                                                                                                                                                   [15:13:50]                                                                                                                                          gulp-inject 147 files into index.html.
                                                                                                                                                   [15:13:50] Finished 'inject' after 1.32 s
                                                                                                                                                   [15:13:50] Starting 'images'...
                                                                                                                                                   [15:13:50]                                                                                                                                          Starting 'styles'...
                                                                                                                                                   [15:13:50] Starting 'html'...
                                                                                                                                                   [15:13:50] Finished 'styles' after 12 ms
                                                                                                                                                   [15:13:50]                                                                                                                                          Finished 'images' after 79 ms
                                                                                                                                                   [15:13:50]                                                                                                                                          gulp-imagemin: Minified 0 images
                                                                                                                                                   [15:13:51] Finished 'html' after 604 ms
                                                                                                                                                   [15:13:51] Starting 'assets:prod'...
                                                                                                                                                   [15:13:52]                                                                                                                                          Finished 'assets:prod' after 1.94 s
[15:13:52] Finished 'build' after 5.77 s
                                                                                                                                                   :processResources                                                                                                                                   UP-TO-DATE
:compileJava
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
:compileScaUsing gulpfile ~\workspace\hardisgeneco\gulpfile.js
[15:14:56] Starting 'wiredep:test'...
[15:14:56] Starting 'ngconstant:dev'...
[15:14:56] Finished 'ngconstant:dev' after 23 ms
[15:14:56] Finished 'wiredep:test' after 138 ms
[15:14:56] Starting 'test'...
                                                                         02 08 2016 15:15:04.315:INFO [karma]: Karma v0.13.22 server started at http://localhost:9876/
                                                                         02 08 2016 15:15:04.324:INFO [launcher]: Starting browser PhantomJS
                                                                         02 08 2016 15:15:04.325:WARN [temp-dir]: Failed to create a temp dir at C:\Users\ams1\AppData\Local\Temp;C:\cygwin64\bin\karma-49101366
                                                                         02 08 2016 15:15:04.366:ERROR [launcher]: { [Error: ENOENT: no such file or directory, open 'C:\Users\ams1\AppData\Local\Temp;C:\cygwin64\bin\karma-49101366\capture.js']
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path: 'C:\\Users\\ams1\\AppData\\Local\\Temp;C:\\cygwin64\\bin\\karma-49101366\\capture.js' }
Error: ENOENT: no such file or directory, open 'C:\Users\ams1\AppData\Local\Temp;C:\cygwin64\bin\karma-49101366\capture.js'
    at Error (native)
    at Object.fs.openSync (fs.js:584:18)
    at Object.fs.writeFileSync (fs.js:1224:33)
    at Object._start (C:\Users\ams1\workspace\hardisgeneco\node_modules\karma-phantomjs-launcher\index.js:62:8)
    at Object.<anonymous> (C:\Users\ams1\workspace\hardisgeneco\node_modules\karma\lib\launchers\process.js:14:10)
    at emitOne (events.js:95:20)
    at Object.emit (events.js:182:7)
    at Object.start (C:\Users\ams1\workspace\hardisgeneco\node_modules\karma\lib\launchers\base.js:42:10)
    at C:\Users\ams1\workspace\hardisgeneco\node_modules\karma\lib\launcher.js:94:17
    at next (C:\Users\ams1\workspace\hardisgeneco\node_modules\batch\index.js:118:7)
    at Batch.end (C:\Users\ams1\workspace\hardisgeneco\node_modules\batch\index.js:154:5)
    at launch (C:\Users\ams1\workspace\hardisgeneco\node_modules\karma\lib\launcher.js:111:11)
    at invoke (C:\Users\ams1\workspace\hardisgeneco\node_modules\di\lib\injector.js:75:15)
    at Server.<anonymous> (C:\Users\ams1\workspace\hardisgeneco\node_modules\karma\lib\server.js:171:24)
    at Server.g (events.js:273:16)
    at emitNone (events.js:80:13)

> Building 80% > :gulp_test

and it stops at building 80%>:gulp_test

**Comment by jdubois** [comment]
Then you have the error: `Failed to create a temp dir` by PhantomJS.
It might be a Cygwin or Windows issue, or maybe PhantomJS has a specific issue on Windows (but I doubt it). Check also your permissions.
Anyway, the issue is that PhantomJS cannot create this temporary directory.

**Comment by deepu105** [comment]
Your build is failing coz if the failing karma tests. Seems like a
permission issue to me.

Thanks & regards,
Deepu
