### ISSUE TITLE
yo jhipster:entity apps throws exception

### ISSUE THREAD

**Issue by dgomesbr** [jhipster/generator-jhipster#404]
Hey guys, I'm giving a try to make a todo app as I've done in the past with other frameworks. After successfully create and run and App through `yo hipster`, I've tried to add an entity through:

`D:\dev\projects\properties-services>yo jhipster:entity apps`

The result (with apps or applications) is the same:

```
...\AppData\Roaming\npm\node_modules\generator-jhipster\nod
e_modules\yeoman-generator\lib\base.js:150
  Object.defineProperty(this, 'gruntfile', {
         ^
TypeError: Cannot redefine property: gruntfile
    at Function.defineProperty (native)
    at EntityGenerator.Base (...\Roaming\npm\node_modules\generator-jhipster\node_modules\yeoman-generator\lib\base.js:150:10)
    at EntityGenerator.module.exports.Base.extend.constructor (...\Roaming\npm\node_modules\generator-jhipster\node_modules\yeoman-generator\lib\named-base.js:19:10)
    at EntityGenerator.Generator (...\Roaming\npm\node_modules\generator-jhipster\script-base.js:10:33)
    at new EntityGenerator (...\Roaming\npm\node_modules\generator-jhipster\entity\index.js:11:14)
    at Environment.instantiate ...\Roaming\npm\node_modules\yo\node_modules\yeoman-generator\lib\env\index.js:269:10) at Environment.create (...\Roaming\npm\node_modules\yo\node_modules\yeoman-generator\lib\env\index.js:246:15)
    at Environment.run (...\Roaming\npm\node_modules\yo\node_modules\yeoman-generator\lib\env\index.js:305:24)
    at init (...\Roaming\npm\node_modules\yo\cli.js:113:7)
    at pre (...\Roaming\npm\node_modules\yo\cli.js:131:3)
```

Any thoughts?

**Comment by rafuch01** [comment]
this again . . .
/home/yeah/test/node_modules/generator-jhipster/generators/app/index.js:15

**Comment by rafuch01** [comment]
yeah@girla:~/test$ yo jhipster
/home/yeah/test/node_modules/generator-jhipster/generators/app/index.js:15
    constructor: function (...args) { // eslint-disable-line object-shorthand
                           ^^^

SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.defineProperty.get [as jhipster:app] (/usr/local/lib/node_modules/yo/node_modules/yeoman-environment/lib/store.js:40:23)
    at Store.get (/usr/local/lib/node_modules/yo/node_modules/yeoman-environment/lib/store.js:64:35)
    at Environment.get (/usr/local/lib/node_modules/yo/node_modules/yeoman-environment/lib/environment.js:262:16)
yeah@girla:~/test$

**Comment by deepu105** [comment]
Please open new issue if you have any instead of commenting on closed tickets
