### ISSUE TITLE
[Internal] Travis warnings

### ISSUE THREAD

**Issue by deepu105** [jhipster/generator-jhipster#4124]
I'm seeing some travis warnings recently
```
(node) warning: possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at TLSSocket.addListener (events.js:239:17)
    at TLSSocket.Readable.on (_stream_readable.js:680:33)
    at Request.<anonymous> (/home/travis/.nvm/versions/node/v4.5.0/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:153:7)
    at emitOne (events.js:77:13)
    at Request.emit (events.js:169:7)
    at ClientRequest.<anonymous> (/home/travis/.nvm/versions/node/v4.5.0/lib/node_modules/npm/node_modules/request/request.js:791:10)
    at emitOne (events.js:82:20)
    at ClientRequest.emit (events.js:169:7)
    at tickOnSocket (_http_client.js:523:7)
    at onSocketNT (_http_client.js:535:5)
```
here is a sample build https://travis-ci.org/jhipster/generator-jhipster/jobs/159353073#L1658

cc our travis expert @pascalgrimaud

**Comment by pascalgrimaud** [comment]
Yes, already saw it, few days ago. I dont think its related to our code, but related to a spécifications dependencies. 
I will try to find what is it, asap
Thx for report, @deepu105

**Comment by deepu105** [comment]
Im also seeing the below during `npm test`
`(!) #_ is deprecated. Require your own version of Lodash or underscore.string`

we do not use yeomans `this._` so i dont know from where this is coming

**Comment by pascalgrimaud** [comment]
1st point about: (node) warning: possible EventEmitter memory leak detected
There is a ticket here: https://github.com/npm/npm/issues/13806

I didn't have the problem with npm 3.10.6. Then, I update to 3.10.7 and got same warning on my local machine.
I think we can ignore them, until the new release 3.10.8 (which will be available very soon -> there is already the tag! https://github.com/npm/npm/tags)

**Comment by pascalgrimaud** [comment]
about the 2nd point: `(!) #_ is deprecated. Require your own version of Lodash or underscore.string`, just made a PR to fix that

**Comment by jdubois** [comment]
Closing as the PR is merged
