### ISSUE TITLE
Unable to build war package 

### ISSUE THREAD

**Issue by lukaphp** [jhipster/generator-jhipster#416]
When I execute the command "mvn -Pprod package", I got this error during grunt test --no-color.

Maybe something wrong with my node configuration ?

[ERROR] Failed to execute goal com.github.trecloux:yeoman-maven-plugin:0.2:build
 (run-grunt) on project jhipster: Error during : cmd /c grunt test --no-color: P
rocess exited with an error: 3 (Exit value: 3) -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal c
om.github.trecloux:yeoman-maven-plugin:0.2:build (run-grunt) on project jhipster
: Error during : cmd /c grunt test --no-color
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor
.java:216)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor
.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor
.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProje
ct(LifecycleModuleBuilder.java:108)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProje
ct(LifecycleModuleBuilder.java:76)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThre
adedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(Lifecycl
eStarter.java:116)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:361)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:155)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:584)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:213)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:157)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.
java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAcces
sorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Laun
cher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.jav
a:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(La
uncher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:
356)
Caused by: org.apache.maven.plugin.MojoExecutionException: Error during : cmd /c
 grunt test --no-color
        at com.github.trecloux.yeoman.YeomanMojo.executeCommand(YeomanMojo.java:
104)
        at com.github.trecloux.yeoman.YeomanMojo.logAndExecuteCommand(YeomanMojo
.java:85)
        at com.github.trecloux.yeoman.YeomanMojo.grunt(YeomanMojo.java:73)
        at com.github.trecloux.yeoman.YeomanMojo.execute(YeomanMojo.java:56)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(Default
BuildPluginManager.java:133)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor
.java:208)
        ... 19 more
Caused by: org.apache.commons.exec.ExecuteException: Process exited with an erro
r: 3 (Exit value: 3)
        at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecut
or.java:377)
        at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:
160)
        at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:
147)
        at com.github.trecloux.yeoman.YeomanMojo.executeCommand(YeomanMojo.java:
102)
        ... 24 more
[ERROR]
[ERROR]
[ERROR] For more information about the errors and possible solutions, please rea
d the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionE
xception

**Comment by qemweb** [comment]
hi guys,
what do you mean by " UX for phantom.js" ,
i am facing the same problem and can't resolv it for a week now, someone to help please,
here my error :

Failed to execute goal com.github.trecloux:yeoman-maven-plugin:0.4:build (run-grunt) on project cabinet-medical: Error during : node --version: Cannot run program "node" (in directory "/Users/retina/Dropbox/QEMWEB/WORK/PROJETS/LOGICIELS/hispter/cabinet_hipster_generate"): error=2, No such file or directory -> [Help 1]

**Comment by gmarziou** [comment]
Your problem is very different: node executable has not been found in your path.
When you run 'node --version' in a terminal what does it say?

**Comment by maodo** [comment]
I have the same error "failed to execute goal com.github.trecloux:yeoman-maven-plugin" when beginning with jhipster.
{
  "name": "pegasus",
  "version": "0.0.0",
  "description": "Description for pegasus",
  "private": true,
  "dependencies": {
  },
  "devDependencies": {
    "grunt": "0.4.5",
    "grunt-autoprefixer": "2.2.0",
    "grunt-build-control": "0.3.0",
    "grunt-wiredep": "2.0.0",
    "grunt-browser-sync": "2.1.3",
    "browser-sync": "2.9.6",
    "grunt-contrib-copy": "0.8.0",
    "grunt-contrib-clean": "0.6.0",
    "grunt-contrib-concat": "0.5.1",
    "grunt-contrib-cssmin": "0.11.0",
    "grunt-contrib-htmlmin": "0.4.0",
    "grunt-contrib-imagemin": "0.9.3",
    "grunt-contrib-jshint": "0.11.0",
    "grunt-contrib-uglify": "0.8.0",
    "grunt-contrib-watch": "0.6.1",
    "grunt-modernizr": "0.6.0",
    "grunt-ng-annotate": "0.10.0",
    "grunt-ng-constant": "1.1.0",
    "grunt-rev": "0.1.0",
    "grunt-svgmin": "2.0.1",
    "grunt-text-replace": "0.4.0",
    "grunt-usemin": "3.0.0",
    "grunt-angular-templates":"0.5.7",
    "load-grunt-tasks": "3.1.0",
    "grunt-karma": "0.11.0",
    "time-grunt": "1.1.0",
    "grunt-sass": "1.0.0",
    "event-stream": "3.3.1",
    "jshint-stylish": "1.0.1",
    "karma-script-launcher": "0.1.0",
    "karma-chrome-launcher": "0.1.12",
    "karma-html2js-preprocessor": "0.1.0",
    "karma-jasmine": "0.3.5",
    "karma-requirejs": "0.2.2",
    "karma-phantomjs-launcher": "0.2.0",
    "phantomjs": "1.9.17",
    "karma": "0.12.35",
    "karma-coverage": "0.4.2",
    "karma-jenkins-reporter": "0.0.2",
    "generator-jhipster": "2.21.1",
    "lodash": "2.4.1",
    "xml2js": "0.4.5",
    "yo": ">=1.3.0",
    "requirejs": "2.1",
    "jasmine-core": "2.1.0",
    "zeparser": "0.0.7",
    "wiredep": "2.2.2"
  },
  "engines": {
    "node": ">=0.12.0"
  },
  "scripts": {
    "test": "grunt test"
  }
}

**Comment by gmarziou** [comment]
@maodo don't use an old closed issue if you want to get some help and also provide log file.

**Comment by delkant** [comment]
Where can I find instructions for installing "UX for phantom.js" ?. Thanks!

**Comment by gmarziou** [comment]
this is a question for stackoverflow.

**Comment by jdubois** [comment]
why are you commenting on such an old issue?

**Comment by delkant** [comment]
Until now I didn't need to use my project in production mode, so I never tried this option before. Somebody talked about "UX for Phanthon.js" here, so I thought it may be useful to have a reference to this step here.  I'm sorry if I was wrong.

**Comment by arifdiu1** [comment]
ERROR] Failed to execute goal com.github.trecloux:yeoman-maven-plugin:0.4:build (run-grunt) on project step: Error during : bower install --no-color: Process exited with an error: 1 (Exit value: 1) -> [Help 1]

**Comment by atomfrede** [comment]
Please don't revive old issues. If you have an error take a look at your guidelines and open a new issue.
