### ISSUE TITLE
Unsatisfied dependency expressed error, created new app with cassandra and created cassndra database manually 

### ISSUE THREAD

**Issue by JinnaBalu** [jhipster/generator-jhipster#4397]
"C:\Program Files\Java\jdk1.8.0_91\bin\java" "-Dmaven.home=C:\Program Files (x86)\JetBrains\IntelliJ IDEA Community Edition 2016.2.5\plugins\maven\lib\maven3" "-Dclassworlds.conf=C:\Program Files (x86)\JetBrains\IntelliJ IDEA Community Edition 2016.2.5\plugins\maven\lib\maven3\bin\m2.conf" -Didea.launcher.port=7532 "-Didea.launcher.bin.path=C:\Program Files (x86)\JetBrains\IntelliJ IDEA Community Edition 2016.2.5\bin" -Dfile.encoding=UTF-8 -classpath "C:\Program Files (x86)\JetBrains\IntelliJ IDEA Community Edition 2016.2.5\plugins\maven\lib\maven3\boot\plexus-classworlds-2.4.jar;C:\Program Files (x86)\JetBrains\IntelliJ IDEA Community Edition 2016.2.5\lib\idea_rt.jar" com.intellij.rt.execution.application.AppMain org.codehaus.classworlds.Launcher -Didea.version=2016.2.5 org.springframework.boot:spring-boot-maven-plugin:1.4.1.RELEASE:run
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building Crowdsourcing 0.0.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] >>> spring-boot-maven-plugin:1.4.1.RELEASE:run (default-cli) @ crowdsourcing >>>
[INFO] 
[INFO] --- maven-resources-plugin:3.0.1:copy-resources (default-resources) @ crowdsourcing ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 4 resources
[INFO] Copying 12 resources
[INFO] 
[INFO] --- maven-resources-plugin:3.0.1:resources (default-resources) @ crowdsourcing ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 3 resources
[INFO] Copying 13 resources
[INFO] 
[INFO] --- maven-enforcer-plugin:1.4.1:enforce (enforce-versions) @ crowdsourcing ---
[INFO] 
[INFO] --- jacoco-maven-plugin:0.7.7.201606060606:prepare-agent (pre-unit-tests) @ crowdsourcing ---
[INFO] argLine set to -javaagent:C:\\Users\\Jinna\\.m2\\repository\\org\\jacoco\\org.jacoco.agent\\0.7.7.201606060606\\org.jacoco.agent-0.7.7.201606060606-runtime.jar=destfile=D:\\Products\\Yeoman\\Crowdsourcing\\target\\test-results\\coverage\\jacoco\\jacoco.exec -Djava.security.egd=file:/dev/./urandom -Xmx256m
[INFO] 
[INFO] --- maven-processor-plugin:2.2.4:process (process) @ crowdsourcing ---
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ crowdsourcing ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 74 source files to D:\Products\Yeoman\Crowdsourcing\target\classes
[INFO] 
[INFO] --- maven-resources-plugin:3.0.1:testResources (default-testResources) @ crowdsourcing ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 2 resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ crowdsourcing ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] <<< spring-boot-maven-plugin:1.4.1.RELEASE:run (default-cli) @ crowdsourcing <<<
[INFO] 
[INFO] --- spring-boot-maven-plugin:1.4.1.RELEASE:run (default-cli) @ crowdsourcing ---
[INFO] Attaching agents: []

        ??  ??    ??  ????????  ???????    ??????  ????????  ????????  ???????
        ??  ??    ??     ??     ??    ??  ??          ??     ??        ??    ??
        ??  ????????     ??     ???????    ?????      ??     ??????    ???????
  ??    ??  ??    ??     ??     ??             ??     ??     ??        ??   ??
   ??????   ??    ??  ????????  ??        ??????      ??     ????????  ??    ??

:: JHipster ?  :: Running Spring Boot 1.4.1.RELEASE ::
:: http://jhipster.github.io ::

2016-10-28 12:43:58.704  INFO 15796 --- [  restartedMain] c.w.crowdsourcing.CrowdsourcingApp       : Starting CrowdsourcingApp on Avance-LP10 with PID 15796 (D:\Products\Yeoman\Crowdsourcing\target\classes started by JBalu in D:\Products\Yeoman\Crowdsourcing)
2016-10-28 12:43:58.712 DEBUG 15796 --- [  restartedMain] c.w.crowdsourcing.CrowdsourcingApp       : Running with Spring Boot v1.4.1.RELEASE, Spring v4.3.3.RELEASE
2016-10-28 12:43:58.713  INFO 15796 --- [  restartedMain] c.w.crowdsourcing.CrowdsourcingApp       : The following profiles are active: swagger,dev
2016-10-28 12:43:58.898 DEBUG 15796 --- [kground-preinit] org.jboss.logging                        : Logging Provider: org.jboss.logging.Slf4jLoggerProvider found via system property
2016-10-28 12:44:09.655 DEBUG 15796 --- [  restartedMain] c.w.c.config.AsyncConfiguration          : Creating Async Task Executor
2016-10-28 12:44:10.513 DEBUG 15796 --- [  restartedMain] c.w.c.config.MetricsConfiguration        : Registering JVM gauges
2016-10-28 12:44:10.909 DEBUG 15796 --- [  restartedMain] c.w.c.config.MetricsConfiguration        : Initializing Metrics JMX reporting
2016-10-28 12:44:12.842  WARN 15796 --- [  restartedMain] io.undertow.websockets.jsr               : UT026009: XNIO worker was not set on WebSocketDeploymentInfo, the default worker will be used
2016-10-28 12:44:12.860  WARN 15796 --- [  restartedMain] io.undertow.websockets.jsr               : UT026010: Buffer pool was not set on WebSocketDeploymentInfo, the default pool will be used
2016-10-28 12:44:14.887  INFO 15796 --- [  restartedMain] c.w.crowdsourcing.config.WebConfigurer   : Web application configuration, using profiles: [swagger, dev]
2016-10-28 12:44:14.914 DEBUG 15796 --- [  restartedMain] c.w.crowdsourcing.config.WebConfigurer   : Initializing Metrics registries
2016-10-28 12:44:14.922 DEBUG 15796 --- [  restartedMain] c.w.crowdsourcing.config.WebConfigurer   : Registering Metrics Filter
2016-10-28 12:44:14.933 DEBUG 15796 --- [  restartedMain] c.w.crowdsourcing.config.WebConfigurer   : Registering Metrics Servlet
2016-10-28 12:44:14.974  INFO 15796 --- [  restartedMain] c.w.crowdsourcing.config.WebConfigurer   : Web application fully configured
2016-10-28 12:44:15.215  INFO 15796 --- [  restartedMain] c.w.crowdsourcing.CrowdsourcingApp       : Running with Spring profile(s) : [swagger, dev]
2016-10-28 12:44:20.039  WARN 15796 --- [  restartedMain] ationConfigEmbeddedWebApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'JHipsterHealthIndicatorConfiguration': Unsatisfied dependency expressed through field 'session'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'session' defined in class path resource [com/wisestep/crowdsourcing/config/cassandra/CassandraConfiguration.class]: Unsatisfied dependency expressed through method 'session' parameter 1; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'cluster' defined in class path resource [com/wisestep/crowdsourcing/config/cassandra/CassandraConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.datastax.driver.core.Cluster]: Factory method 'cluster' threw exception; nested exception is com.datastax.driver.core.exceptions.NoHostAvailableException: All host(s) tried for query failed (tried: localhost/0:0:0:0:0:0:0:1:9042 (com.datastax.driver.core.exceptions.TransportException: [localhost/0:0:0:0:0:0:0:1] Cannot connect), localhost/127.0.0.1:9042 (com.datastax.driver.core.exceptions.UnsupportedProtocolVersionException: [localhost/127.0.0.1:9042] Host does not support protocol version V4 but V3))
2016-10-28 12:44:20.065  INFO 15796 --- [  restartedMain] c.w.c.config.CacheConfiguration          : Closing Cache Manager
2016-10-28 12:44:20.076  WARN 15796 --- [  restartedMain] o.s.boot.SpringApplication               : Error handling failed (Error creating bean with name 'delegatingApplicationListener' defined in class path resource [org/springframework/security/config/annotation/web/configuration/WebSecurityConfiguration.class]: BeanPostProcessor before instantiation of bean failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.cache.annotation.ProxyCachingConfiguration': Initialization of bean failed; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No bean named 'org.springframework.context.annotation.ConfigurationClassPostProcessor.importRegistry' is defined)
2016-10-28 12:44:20.096 ERROR 15796 --- [  restartedMain] o.s.boot.SpringApplication               : Application startup failed

org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'JHipsterHealthIndicatorConfiguration': Unsatisfied dependency expressed through field 'session'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'session' defined in class path resource [com/wisestep/crowdsourcing/config/cassandra/CassandraConfiguration.class]: Unsatisfied dependency expressed through method 'session' parameter 1; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'cluster' defined in class path resource [com/wisestep/crowdsourcing/config/cassandra/CassandraConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.datastax.driver.core.Cluster]: Factory method 'cluster' threw exception; nested exception is com.datastax.driver.core.exceptions.NoHostAvailableException: All host(s) tried for query failed (tried: localhost/0:0:0:0:0:0:0:1:9042 (com.datastax.driver.core.exceptions.TransportException: [localhost/0:0:0:0:0:0:0:1] Cannot connect), localhost/127.0.0.1:9042 (com.datastax.driver.core.exceptions.UnsupportedProtocolVersionException: [localhost/127.0.0.1:9042] Host does not support protocol version V4 but V3))
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:569)
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:88)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:349)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1219)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:543)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:751)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:861)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:541)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:761)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:371)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315)
	at com.wisestep.crowdsourcing.CrowdsourcingApp.main(CrowdsourcingApp.java:64)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.devtools.restart.RestartLauncher.run(RestartLauncher.java:49)
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'session' defined in class path resource [com/wisestep/crowdsourcing/config/cassandra/CassandraConfiguration.class]: Unsatisfied dependency expressed through method 'session' parameter 1; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'cluster' defined in class path resource [com/wisestep/crowdsourcing/config/cassandra/CassandraConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.datastax.driver.core.Cluster]: Factory method 'cluster' threw exception; nested exception is com.datastax.driver.core.exceptions.NoHostAvailableException: All host(s) tried for query failed (tried: localhost/0:0:0:0:0:0:0:1:9042 (com.datastax.driver.core.exceptions.TransportException: [localhost/0:0:0:0:0:0:0:1] Cannot connect), localhost/127.0.0.1:9042 (com.datastax.driver.core.exceptions.UnsupportedProtocolVersionException: [localhost/127.0.0.1:9042] Host does not support protocol version V4 but V3))
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:749)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:467)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1128)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1023)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:510)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:207)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1128)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1056)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:566)
	... 22 common frames omitted
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'cluster' defined in class path resource [com/wisestep/crowdsourcing/config/cassandra/CassandraConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.datastax.driver.core.Cluster]: Factory method 'cluster' threw exception; nested exception is com.datastax.driver.core.exceptions.NoHostAvailableException: All host(s) tried for query failed (tried: localhost/0:0:0:0:0:0:0:1:9042 (com.datastax.driver.core.exceptions.TransportException: [localhost/0:0:0:0:0:0:0:1] Cannot connect), localhost/127.0.0.1:9042 (com.datastax.driver.core.exceptions.UnsupportedProtocolVersionException: [localhost/127.0.0.1:9042] Host does not support protocol version V4 but V3))
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:599)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1128)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1023)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:510)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:207)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1128)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1056)
	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:835)
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:741)
	... 35 common frames omitted
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.datastax.driver.core.Cluster]: Factory method 'cluster' threw exception; nested exception is com.datastax.driver.core.exceptions.NoHostAvailableException: All host(s) tried for query failed (tried: localhost/0:0:0:0:0:0:0:1:9042 (com.datastax.driver.core.exceptions.TransportException: [localhost/0:0:0:0:0:0:0:1] Cannot connect), localhost/127.0.0.1:9042 (com.datastax.driver.core.exceptions.UnsupportedProtocolVersionException: [localhost/127.0.0.1:9042] Host does not support protocol version V4 but V3))
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:189)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:588)
	... 48 common frames omitted
Caused by: com.datastax.driver.core.exceptions.NoHostAvailableException: All host(s) tried for query failed (tried: localhost/0:0:0:0:0:0:0:1:9042 (com.datastax.driver.core.exceptions.TransportException: [localhost/0:0:0:0:0:0:0:1] Cannot connect), localhost/127.0.0.1:9042 (com.datastax.driver.core.exceptions.UnsupportedProtocolVersionException: [localhost/127.0.0.1:9042] Host does not support protocol version V4 but V3))
	at com.datastax.driver.core.ControlConnection.reconnectInternal(ControlConnection.java:233)
	at com.datastax.driver.core.ControlConnection.connect(ControlConnection.java:79)
	at com.datastax.driver.core.Cluster$Manager.init(Cluster.java:1424)
	at com.datastax.driver.core.Cluster.init(Cluster.java:163)
	at com.wisestep.crowdsourcing.config.cassandra.CassandraConfiguration.cluster(CassandraConfiguration.java:80)
	at com.wisestep.crowdsourcing.config.cassandra.CassandraConfiguration$$EnhancerBySpringCGLIB$$5bc7760b.CGLIB$cluster$1(<generated>)
	at com.wisestep.crowdsourcing.config.cassandra.CassandraConfiguration$$EnhancerBySpringCGLIB$$5bc7760b$$FastClassBySpringCGLIB$$3e87bc65.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228)
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:356)
	at com.wisestep.crowdsourcing.config.cassandra.CassandraConfiguration$$EnhancerBySpringCGLIB$$5bc7760b.cluster(<generated>)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:162)
	... 49 common frames omitted

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1:19.273s
[INFO] Finished at: Fri Oct 28 12:44:22 IST 2016
[INFO] Final Memory: 39M/173M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.springframework.boot:spring-boot-maven-plugin:1.4.1.RELEASE:run (default-cli) on project crowdsourcing: Could not exec java: Application finished with exit code: 1 -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

Process finished with exit code 1

**Comment by jdubois** [comment]
You have installed Cassandra yourself, and as you can read from the log:

   Host does not support protocol version V4 but V3

So you're using an outdating version. It's probably possible to use it, but it's not a JHipster bug, please ask this on StackOverflow with the JHipster tag.

**Comment by JinnaBalu** [comment]
Thank you dubois, solved the issue: changed the version in CassandraConfiguration.java. saved my day.
