### ISSUE TITLE
I encountered an error in the implementation of yo !

### ISSUE THREAD

**Issue by swit1983** [jhipster/generator-jhipster#4455]
##### **Overview of the issue**
G:\kenlenecd>yo jhipster
F:\node-global\node_modules\yo\node_modules\rx-lite\rx.lite.js:75
    throw e;
    ^

Error: write EINVAL
    at exports._errnoException (util.js:1022:11)
    at WriteStream.Socket._writeGeneric (net.js:715:26)
    at WriteStream.Socket._write (net.js:734:8)
    at doWrite (_stream_writable.js:334:12)
    at writeOrBuffer (_stream_writable.js:320:5)
    at WriteStream.Writable.write (_stream_writable.js:247:11)
    at WriteStream.Socket.write (net.js:661:40)
    at MuteStream.ondata (stream.js:31:26)
    at emitOne (events.js:96:13)
    at MuteStream.emit (events.js:188:7)

I tried to execute a lot of instructions and Reinstall, but no effect, the error is still.
##### **Browsers and Operating System**

windows 10

**Comment by jdubois** [comment]
Depends on your version, etc....

**Comment by jdubois** [comment]
This ticket has been closed as the guidelines are not followed.

Tickets must follow our [Guidelines](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md#submitting-an-issue), as mentioned in:

1. our [Readme file on the front page of the project](https://github.com/jhipster/generator-jhipster/blob/master/README.md), 
2. the ["create a new ticket" page](https://github.com/jhipster/generator-jhipster/issues/new) and
3. our [Help page](http://jhipster.github.io/help/)

We have also created a template on the ["create a new ticket" page](https://github.com/jhipster/generator-jhipster/issues/new) to help you follow those guidelines.
