### ISSUE TITLE
mysql table creation fails when selecting more than one required field of type ZonedDateTime

### ISSUE THREAD

**Issue by lluiscanals** [jhipster/generator-jhipster#4471]
##### **Overview of the issue**
Table creation fails when selecting more than one required field of type ZonedDateTime.

```java
liquibase.exception.DatabaseException: Invalid default value for 'transit_time' [Failed SQL: CREATE TABLE tfrm.satellite (id BIGINT AUTO_INCREMENT NOT NULL, object_name VARCHAR(50) NOT NULL, rise_time timestamp NOT NULL, transit_time timestamp NOT NULL, set_time timestamp NOT NULL]
	at liquibase.executor.jvm.JdbcExecutor$ExecuteStatementCallback.doInStatement(JdbcExecutor.java:301)
	at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:55)
	at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:107)
	at liquibase.database.AbstractJdbcDatabase.execute(AbstractJdbcDatabase.java:1251)
	at liquibase.database.AbstractJdbcDatabase.executeStatements(AbstractJdbcDatabase.java:1234)
	at liquibase.changelog.ChangeSet.execute(ChangeSet.java:554)
	at liquibase.changelog.visitor.UpdateVisitor.visit(UpdateVisitor.java:51)
	at liquibase.changelog.ChangeLogIterator.run(ChangeLogIterator.java:73)
	at liquibase.Liquibase.update(Liquibase.java:212)
	at liquibase.Liquibase.update(Liquibase.java:192)
	at liquibase.integration.spring.SpringLiquibase.performUpdate(SpringLiquibase.java:434)
	at liquibase.integration.spring.SpringLiquibase.afterPropertiesSet(SpringLiquibase.java:391)
	at com.dualion.tfrm.config.liquibase.AsyncSpringLiquibase.initDb(AsyncSpringLiquibase.java:67)
	at com.dualion.tfrm.config.liquibase.AsyncSpringLiquibase.lambda$afterPropertiesSet$0(AsyncSpringLiquibase.java:50)
	at com.dualion.tfrm.async.ExceptionHandlingAsyncTaskExecutor.lambda$createWrappedRunnable$1(ExceptionHandlingAsyncTaskExecutor.java:47)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Invalid default value for 'transit_time'
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:404)
	at com.mysql.jdbc.Util.getInstance(Util.java:387)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:942)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3966)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3902)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2526)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2673)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2545)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2503)
	at com.mysql.jdbc.StatementImpl.executeInternal(StatementImpl.java:839)
	at com.mysql.jdbc.StatementImpl.execute(StatementImpl.java:739)
	at com.zaxxer.hikari.pool.ProxyStatement.execute(ProxyStatement.java:95)
	at com.zaxxer.hikari.pool.HikariProxyStatement.execute(HikariProxyStatement.java)
	at liquibase.executor.jvm.JdbcExecutor$ExecuteStatementCallback.doInStatement(JdbcExecutor.java:299)
	... 17 common frames omitted
```
##### **JHipster Version(s)**
3.10.0

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**
{
  "generator-jhipster": {
    "jhipsterVersion": "3.10.0",
    "baseName": "tfrm",
    "packageName": "com.dualion.tfrm",
    "packageFolder": "com/dualion/tfrm",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "mysql",
    "prodDatabaseType": "mysql",
    "searchEngine": "elasticsearch",
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "jwtSecretKey": "",
    "useSass": false,
    "applicationType": "monolith",
    "testFrameworks": [
      "gatling",
      "cucumber",
      "protractor"
    ],
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en",
      "ca",
      "es"
    ],
    "jhiPrefix": "jhi",
    "messageBroker": false,
    "serviceDiscoveryType": false
  }
}

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**
{
    "fields": [
        {
            "fieldName": "objectName",
            "fieldType": "String",
            "fieldValidateRules": [
                "required",
                "maxlength"
            ],
            "fieldValidateRulesMaxlength": "50"
        },
        {
            "fieldName": "riseTime",
            "fieldType": "ZonedDateTime",
            "fieldValidateRules": [
                "required"
            ]
        },
        {
            "fieldName": "transitTime",
            "fieldType": "ZonedDateTime",
            "fieldValidateRules": [
                "required"
            ]
        },
        {
            "fieldName": "setTime",
            "fieldType": "ZonedDateTime",
            "fieldValidateRules": [
                "required"
            ]
        }
    ],
    "changelogDate": "20160411182004",
    "dto": "mapstruct",
    "service": "serviceImpl",
    "entityTableName": "satellite",
    "pagination": "pagination"
}

##### **Browsers and Operating System**
MySQL 5.7.13. Windows 10.

**Comment by deepu105** [comment]
I think its a known limitation of MySQL where you cant have two columns of
date type with required on it


Thanks & Regards,
Deepu

**Comment by jdubois** [comment]
Yes and we already had this ticket in the past, have a look at the history
