### ISSUE TITLE
"TypeError: Invalid Version: 3.12.0" When creating new application 

### ISSUE THREAD

**Issue by Sarevok117** [jhipster/generator-jhipster#4613]
##### **Overview of the issue**

Just followed the Jhipster installation guide and tried to create a new project.
I'm using Windows 10 and I am behind a corporate proxy (I also followed the proxy configuration)
This is what I get :

```
C:\Users\lvuillaume\Desktop\mdp>yo jhipster

Welcome to the JHipster Generator v3.12.0
Documentation for creating an application: https://jhipster.github.io/creating-an-app/
Application files will be generated in folder: C:\Users\lvuillaume\Desktop\mdp
C:\Users\lvuillaume\AppData\Roaming\npm\node_modules\generator-jhipster\node_modules\semver\semver.js:293
    throw new TypeError('Invalid Version: ' + version);
    ^

TypeError: Invalid Version: 3.12.0

    at new SemVer (C:\Users\lvuillaume\AppData\Roaming\npm\node_modules\generator-jhipster\node_modules\semver\semver.js:293:11)
    at SemVer.compare (C:\Users\lvuillaume\AppData\Roaming\npm\node_modules\generator-jhipster\node_modules\semver\semver.js:342:13)
    at compare (C:\Users\lvuillaume\AppData\Roaming\npm\node_modules\generator-jhipster\node_modules\semver\semver.js:566:31)
    at Function.lt (C:\Users\lvuillaume\AppData\Roaming\npm\node_modules\generator-jhipster\node_modules\semver\semver.js:600:10)
    at constructor.<anonymous> (C:\Users\lvuillaume\AppData\Roaming\npm\node_modules\generator-jhipster\generators\generator-base.js:1333:35)
    at C:\Users\lvuillaume\AppData\Roaming\npm\node_modules\generator-jhipster\node_modules\shelljs\src\exec.js:180:7
    at ChildProcess.exithandler (child_process.js:202:7)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:885:16)
```
##### **Suggest a Fix**

I tried with my personal computer at home (Windows 7, no proxy, same versions) and I had no error.

##### **JHipster Version(s)**

This is the output of yo jhipster:info

```
Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

C:\Users\lvuillaume
-- (empty)


cat: no such file or directory: .yo-rc.json

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

yaml

##### **Entity configuration(s) entityName.json files generated in the .jhipster directory**

ls: no such file or directory: .jhipster/*.json

##### **Browsers and Operating System**

java version "1.8.0_111"
Java(TM) SE Runtime Environment (build 1.8.0_111-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.111-b14, mixed mode)
git version 2.11.0.windows.1
node: v7.2.0
npm: 3.10.9
bower: 1.8.0
gulp:
[10:49:31] CLI version 1.2.2
yeoman: 1.8.5
```
##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

No such file generated.

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

No such file generated.

##### **Browsers and Operating System**

Windows 10, Chrome

**Comment by ashakhov** [comment]
>node: v7.2.0
Try v6.9.1 LTS, JH doesn't work too well with "current" versions.

**Comment by cbornet** [comment]
We don't support node v7. Please try with LTS v6.

**Comment by Sarevok117** [comment]
I unistalled 7.2.0 and then installed 6.9.1 but it still reports the same error.

yo jhipster:info output :

```
##### **Browsers and Operating System**

java version "1.8.0_111"
Java(TM) SE Runtime Environment (build 1.8.0_111-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.111-b14, mixed mode)
git version 2.11.0.windows.1
node: v6.9.1
npm: 3.10.8
bower: 1.8.0
gulp:
[11:09:27] CLI version 1.2.2
yeoman: 1.8.5
```

yo jhipster output :

```
Welcome to the JHipster Generator v3.12.0
Documentation for creating an application: https://jhipster.github.io/creating-an-app/
Application files will be generated in folder: C:\Users\lvuillaume\Desktop\mdp
C:\Users\lvuillaume\AppData\Roaming\npm\node_modules\generator-jhipster\node_modules\semver\semver.js:293
    throw new TypeError('Invalid Version: ' + version);
    ^

TypeError: Invalid Version: 3.12.0
[0x7FFEE8C370E3] ANOMALY: use of REX.w is meaningless (default operand size is 64)

    at new SemVer (C:\Users\lvuillaume\AppData\Roaming\npm\node_modules\generator-jhipster\node_modules\semver\semver.js:293:11)
    at SemVer.compare (C:\Users\lvuillaume\AppData\Roaming\npm\node_modules\generator-jhipster\node_modules\semver\semver.js:342:13)
    at compare (C:\Users\lvuillaume\AppData\Roaming\npm\node_modules\generator-jhipster\node_modules\semver\semver.js:566:31)
    at Function.lt (C:\Users\lvuillaume\AppData\Roaming\npm\node_modules\generator-jhipster\node_modules\semver\semver.js:600:10)
    at constructor.<anonymous> (C:\Users\lvuillaume\AppData\Roaming\npm\node_modules\generator-jhipster\generators\generator-base.js:1333:35)
    at C:\Users\lvuillaume\AppData\Roaming\npm\node_modules\generator-jhipster\node_modules\shelljs\src\exec.js:180:7
    at ChildProcess.exithandler (child_process.js:197:7)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
```

**Comment by jdubois** [comment]
I googled your error and it looks like [an issue with your antivirus](http://www.areresearch.net/2016/09/win10-anomaly-use-of-rexw-is-meaningless.html), which would explain why you are the only one having this, and you can't reproduce the error at home.

**Comment by Sarevok117** [comment]
I killed the antivirus / firewall process and it worked.
Thanks.
