### ISSUE TITLE
Error on gulp test 

### ISSUE THREAD

**Issue by venkatesan-94** [jhipster/generator-jhipster#4696]
I am new to use Karma Unit Testing, I have a problem that gulp test gets error and all the test cases are getting failed including the generated test cases from jhipster.

##### **Overview of the issue**
When I run gulp test, I am getting the Error as below

```
[11:07:40] Starting 'inject:test'...
[11:07:40] Starting 'ngconstant:dev'...
[11:07:40] Finished 'ngconstant:dev' after 87 ms
[11:07:40] gulp-inject 27 files into karma.conf.js.
[11:07:40] Finished 'inject:test' after 155 ms
[11:07:40] Starting 'test'...
[32m16 12 2016 11:07:46.314:INFO [karma]: [39mKarma v1.2.0 server started at http://localhost:9876/
[32m16 12 2016 11:07:46.314:INFO [launcher]: [39mLaunching browser PhantomJS with unlimited concurrency
[32m16 12 2016 11:07:46.345:INFO [launcher]: [39mStarting browser PhantomJS
[32m16 12 2016 11:07:47.981:INFO [PhantomJS 2.1.1 (Windows 8 0.0.0)]: [39mConnected on socket /#2hpdlvilfyxYhKFjAAAA with id 21246536
PhantomJS 2.1.1 (Windows 8 0.0.0): Executed 0 of 67 SUCCESS (0 secs / 0 secs)
PhantomJS 2.1.1 (Windows 8 0.0.0) Controller Tests ActivationController calls Auth.activateAccount with the key from stateParams FAILED
	src/main/webapp/bower_components/angular/angular.js:9:139615
	forEach@src/main/webapp/bower_components/angular/angular.js:9:7090
	loadModules@src/main/webapp/bower_components/angular/angular.js:9:136826
	createInjector@src/main/webapp/bower_components/angular/angular.js:9:132232
	workFn@src/main/webapp/bower_components/angular-mocks/angular-mocks.js:9:157942
	inject@src/main/webapp/bower_components/angular-mocks/angular-mocks.js:9:156451
	mockApiAccountCall@src/test/javascript/spec/helpers/httpBackend.js:9:113
	loaded@http://localhost:9876/context.js:151:17
	src/main/webapp/bower_components/angular/angular.js:9:139615
	forEach@src/main/webapp/bower_components/angular/angular.js:9:7090
	loadModules@src/main/webapp/bower_components/angular/angular.js:9:136826
	createInjector@src/main/webapp/bower_components/angular/angular.js:9:132232
	workFn@src/main/webapp/bower_components/angular-mocks/angular-mocks.js:9:157942
	inject@src/main/webapp/bower_components/angular-mocks/angular-mocks.js:9:156451
	mockI18nCalls@src/test/javascript/spec/helpers/httpBackend.js:9:375
	loaded@http://localhost:9876/context.js:151:17
	src/main/webapp/bower_components/angular/angular.js:9:139615
	forEach@src/main/webapp/bower_components/angular/angular.js:9:7090
	loadModules@src/main/webapp/bower_components/angular/angular.js:9:136826
	createInjector@src/main/webapp/bower_components/angular/angular.js:9:132232
	workFn@src/main/webapp/bower_components/angular-mocks/angular-mocks.js:9:157942
	loaded@http://localhost:9876/context.js:151:17
	TypeError: undefined is not an object (evaluating 'MockAuth.activateAccount') in src/test/javascript/spec/app/account/activate/activate.controller.spec.js (line 9)
	src/test/javascript/spec/app/account/activate/activate.controller.spec.js:9:2014
	loaded@http://localhost:9876/context.js:151:17
[1A[2KPhantomJS 2.1.1 (Windows 8 0.0.0) Controller Tests ActivationController calls Auth.activateAccount with the key from stateParams FAILED
	src/main/webapp/bower_components/angular/angular.js:9:139615
	forEach@src/main/webapp/bower_components/angular/angular.js:9:7090
	loadModules@src/main/webapp/bower_components/angular/angular.js:9:136826
	createInjector@src/main/webapp/bower_components/angular/angular.js:9:132232
	workFn@src/main/webapp/bower_components/angular-mocks/angular-mocks.js:9:157942
	inject@src/main/webapp/bower_components/angular-mocks/angular-mocks.js:9:156451
	mockApiAccountCall@src/test/javascript/spec/helpers/httpBackend.js:9:113
	loaded@http://localhost:9876/context.js:151:17
	src/main/webapp/bower_components/angular/angular.js:9:139615
	forEach@src/main/webapp/bower_components/angular/angular.js:9:7090
	loadModules@src/main/webapp/bower_components/angular/angular.js:9:136826
	createInjector@src/main/webapp/bower_components/angular/angular.js:9:132232
	workFn@src/main/webapp/bower_components/angular-mocks/angular-mocks.js:9:157942
	inject@src/main/webapp/bower_components/angular-mocks/angular-mocks.js:9:156451
	mockI18nCalls@src/test/javascript/spec/helpers/httpBackend.js:9:375
	loaded@http://localhost:9876/context.js:151:17
	src/main/webapp/bower_components/angular/angular.js:9:139615
	forEach@src/main/webapp/bower_components/angular/angular.js:9:7090
	loadModules@src/main/webapp/bower_components/angular/angular.js:9:136826
	createInjector@src/main/webapp/bower_components/angular/angular.js:9:132232
	workFn@src/main/webapp/bower_components/angular-mocks/angular-mocks.js:9:157942
	loaded@http://localhost:9876/context.js:151:17
	TypeError: undefined is not an object (evaluating 'MockAuth.activateAccount') in src/test/javascript/spec/app/account/activate/activate.controller.spec.js (line 9)
	src/test/javascript/spec/app/account/activate/activate.controller.spec.js:9:2014
	loaded@http://localhost:9876/context.js:151:17
```
and so on completing like this,
```
PhantomJS 2.1.1 (Windows 8 0.0.0): Executed 67 of 67 (67 FAILED) ERROR (6.234 secs / 2.118 secs)
[1A[2KPhantomJS 2.1.1 (Windows 8 0.0.0): Executed 67 of 67 (67 FAILED) ERROR (6.234 secs / 2.118 secs)
[33m16 12 2016 11:08:08.943:WARN [launcher]: [39mPhantomJS was not killed in 2000 ms, sending SIGKILL.
[11:08:08] 'test' errored after 28 s
[11:08:08] Error: 1
    at formatError (C:\Users\M1032535\AppData\Roaming\npm\node_modules\gulp\bin\gulp.js:169:10)
    at Gulp.<anonymous> (C:\Users\M1032535\AppData\Roaming\npm\node_modules\gulp\bin\gulp.js:195:15)
    at emitOne (events.js:77:13)
    at Gulp.emit (events.js:169:7)
    at Gulp.Orchestrator._emitTaskDone (D:\Projects\AMS_Automation\atlas_3.8.0\node_modules\orchestrator\index.js:264:8)
    at D:\Projects\AMS_Automation\atlas_3.8.0\node_modules\orchestrator\index.js:275:23
    at finish (D:\Projects\AMS_Automation\atlas_3.8.0\node_modules\orchestrator\lib\runTask.js:21:8)
    at cb (D:\Projects\AMS_Automation\atlas_3.8.0\node_modules\orchestrator\lib\runTask.js:29:3)
    at removeAllListeners (D:\Projects\AMS_Automation\atlas_3.8.0\node_modules\karma\lib\server.js:379:7)
    at Server.<anonymous> (D:\Projects\AMS_Automation\atlas_3.8.0\node_modules\karma\lib\server.js:390:9)
    at Server.g (events.js:260:16)
    at emitNone (events.js:72:20)
    at Server.emit (events.js:166:7)
    at emitCloseNT (net.js:1521:8)
    at nextTickCallbackWith1Arg (node.js:431:9)
    at process._tickCallback (node.js:353:17)

```

##### **JHipster Version(s)**
3.8.0

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

> {
> 	"generator-jhipster": {
> 		"jhipsterVersion": "3.8.0",
> 		"baseName": "atlas",
> 		"packageName": "com.mindtree.ams.atlas",
> 		"packageFolder": "com/mindtree/ams/atlas",
> 		"serverPort": "8080",
> 		"authenticationType": "jwt",
> 		"hibernateCache": "ehcache",
> 		"clusteredHttpSession": false,
> 		"websocket": false,
> 		"databaseType": "sql",
> 		"devDatabaseType": "mysql",
> 		"prodDatabaseType": "mysql",
> 		"searchEngine": false,
> 		"buildTool": "maven",
> 		"enableSocialSignIn": false,
> 		"jwtSecretKey": "77891c0b6b7749d57fc8c307e7333ac3bdabfb82",
> 		"useSass": false,
> 		"applicationType": "monolith",
> 		"testFrameworks": [
> 			"gatling",
> 			"protractor"
> 		],
> 		"jhiPrefix": "jhi",
> 		"enableTranslation": false,
> 		"messageBroker": false
> 	}
> }

**Comment by pascalgrimaud** [comment]
Can you use yo jhipster:info to provide all information/version of node, npm etc?

**Comment by jdubois** [comment]
This ticket has been closed as the guidelines are not followed.

Tickets must follow our [Guidelines](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md#submitting-an-issue), as mentioned in:

1. our [Readme file on the front page of the project](https://github.com/jhipster/generator-jhipster/blob/master/README.md), 
2. the ["create a new ticket" page](https://github.com/jhipster/generator-jhipster/issues/new) and
3. our [Help page](http://jhipster.github.io/help/)

We have also created a template on the ["create a new ticket" page](https://github.com/jhipster/generator-jhipster/issues/new) to help you follow those guidelines.
