### ISSUE TITLE
[Microservice Generation] Generated microservice won't start

### ISSUE THREAD

**Issue by Smitty010** [jhipster/generator-jhipster#4720]
##### **Overview of the issue**

I generated a microservice using the latest jhipster release (as described below).  Without making any changes to the generated project, I run the microservice and get the following stack trace:

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'loggingConfiguration': Injection of autowired dependencies failed; nested exception is java.lang.IllegalArgumentException: Could not resolve placeholder 'server.port' in string value "${server.port}"
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:376)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1219)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:551)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:754)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:866)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:542)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:761)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:371)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315)
	at com.mainstreamdata.myapp.myappuserdbApp.main(myappuserdbApp.java:66)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.springframework.boot.devtools.restart.RestartLauncher.run(RestartLauncher.java:49)
Caused by: java.lang.IllegalArgumentException: Could not resolve placeholder 'server.port' in string value "${server.port}"
	at org.springframework.util.PropertyPlaceholderHelper.parseStringValue(PropertyPlaceholderHelper.java:174)
	at org.springframework.util.PropertyPlaceholderHelper.replacePlaceholders(PropertyPlaceholderHelper.java:126)
	at org.springframework.core.env.AbstractPropertyResolver.doResolvePlaceholders(AbstractPropertyResolver.java:219)
	at org.springframework.core.env.AbstractPropertyResolver.resolveRequiredPlaceholders(AbstractPropertyResolver.java:193)
	at org.springframework.context.support.PropertySourcesPlaceholderConfigurer$2.resolveStringValue(PropertySourcesPlaceholderConfigurer.java:172)
	at org.springframework.beans.factory.support.AbstractBeanFactory.resolveEmbeddedValue(AbstractBeanFactory.java:813)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1079)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1059)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:589)
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:88)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:370)
	... 20 common frames omitted

##### **Motivation for or Use Case**

It seems like the service should run the generated code without error

##### **Reproduce the error**

I'm assuming you could provide the same answers to the questions I did, import the project into eclipse and run it.

##### **Related issues**

I looked and didn't see one.

##### **Suggest a Fix**

Both application-dev.yml and application-prod.yml have server:port:8085.  I also verified that port 8085 is not in use on my machine (though the stack trace would indicate the problem occurred before it tried to start up on that port).

##### **JHipster Version(s)**

---------------------------------------------------------------------------------------
>yo jhipster:info
Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
C:\dev\jhipster\userdb
`-- (empty)

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folde
r**

```yaml
{
  "generator-jhipster": {
    "jhipsterVersion": "3.12.2",
    "baseName": "myappuserdb",
    "packageName": "com.mainstreamdata.myapp",
    "packageFolder": "com/mainstreamdata/myapp",
    "serverPort": "8085",
    "authenticationType": "jwt",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": "eureka",
    "buildTool": "gradle",
    "enableSocialSignIn": false,
    "jwtSecretKey": "6c1a6b4cf37d1c6eea8e2f2121a9dd9f1d3678bd",
    "enableTranslation": false,
    "applicationType": "microservice",
    "testFrameworks": [
      "gatling",
      "cucumber"
    ],
    "jhiPrefix": "jhi",
    "skipClient": true,
    "skipUserManagement": true
  }
}
```

##### **Entity configuration(s) `entityName.json` files generated in the `.jhips
ter` directory**

ls: no such file or directory: .jhipster/*.json

##### **Browsers and Operating System**

java version "1.8.0_111"
Java(TM) SE Runtime Environment (build 1.8.0_111-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.111-b14, mixed mode)

git version 2.8.2.windows.1

node: v6.9.2

npm: 3.10.9

bower: 1.8.0

gulp:
[17:26:13] CLI version 1.2.2

yeoman: 1.8.5

Docker version 1.8.2, build 0a8c2e3
----------------------------------------------------------------------------------------
##### Here are the answers to the questions the generator asked:
Welcome to the JHipster Generator v3.12.2
Documentation for creating an application: https://jhipster.github.io/creating-a
n-app/
Application files will be generated in folder: C:\dev\jhipster\userdb
? (1/14) Which *type* of application would you like to create? Microservice app
lication
? (2/14) What is the base name of your application? myappuserdb
? (3/14) Would you like to install other generators from the JHipster Market Pl
ace? No
? (3/14) As you are running in a microservice architecture, on which port would
 like your server to run? It should be unique to avoid port conflicts. 8085
? (4/14) What is your default Java package name? com.mainstreamdata.myapp
? (5/14) Which *type* of authentication would you like to use? JWT authenticati
on (stateless, with a token)
? (6/14) Which Service Discovery and Configuration solution would you like to u
se? JHipster Registry (using Eureka and Spring Cloud Config)
? (7/14) Which *type* of database would you like to use? SQL (H2, MySQL, MariaD
B, PostgreSQL, Oracle)
? (8/14) Which *production* database would you like to use? MySQL
? (9/14) Which *development* database would you like to use? H2 with disk-based
 persistence
? (10/14) Do you want to use Hibernate 2nd level cache? Yes, with ehcache (loca
l cache, for a single node)
? (11/14) Would you like to use Maven or Gradle for building the backend? Gradl
e
? (12/14) Which other technologies would you like to use? (Press <space> to sel
ect, <a> to toggle all, <i> to inverse selection)
? (13/14) Would you like to enable internationalization support? No
? (14/14) Which testing frameworks would you like to use? Gatling, Cucumber
   create README.md
   create .gitignore
   create .gitattributes
   create .editorconfig
   create .travis.yml
   create Jenkinsfile
   create src\main\docker\Dockerfile
   create src\main\docker\app.yml
   create src\main\docker\mysql.yml
   create src\main\docker\central-server-config\README.md
   create src\main\docker\jhipster-registry.yml
   create src\main\docker\central-server-config\docker-config\application.yml
   create src\main\docker\central-server-config\localhost-config\application.yml

   create src\main\docker\sonar.yml
   create build.gradle
   create settings.gradle
   create gradle.properties
   create gradle\sonar.gradle
   create gradle\docker.gradle
   create gradle\profile_dev.gradle
   create gradle\profile_prod.gradle
   create gradle\mapstruct.gradle
   create gradle\gatling.gradle
   create gradle\liquibase.gradle
   create gradlew
   create gradlew.bat
   create gradle\wrapper\gradle-wrapper.jar
   create gradle\wrapper\gradle-wrapper.properties
   create src\main\resources\banner.txt
   create src\main\resources\ehcache.xml
   create src\main\java\com\mainstreamdata\myapp\config\jcache\SpringCacheRegionF
actory.java
   create src\main\java\com\mainstreamdata\myapp\config\jcache\JCacheGaugeSet.jav
a
   create src\main\resources\.h2.server.properties
   create src\main\resources\templates\error.html
   create src\main\resources\logback-spring.xml
   create src\main\resources\config\application.yml
   create src\main\resources\config\application-dev.yml
   create src\main\resources\config\application-prod.yml
   create src\main\resources\config\liquibase\changelog\00000000000000_initial_s
chema.xml
   create src\main\resources\config\liquibase\master.xml
   create src\main\resources\i18n\messages.properties
   create src\main\java\com\mainstreamdata\myapp\security\SpringSecurityAuditorAw
are.java
   create src\main\java\com\mainstreamdata\myapp\security\SecurityUtils.java
   create src\main\java\com\mainstreamdata\myapp\security\AuthoritiesConstants.ja
va
   create src\main\java\com\mainstreamdata\myapp\security\jwt\TokenProvider.java
   create src\main\java\com\mainstreamdata\myapp\security\jwt\JWTConfigurer.java
   create src\main\java\com\mainstreamdata\myapp\security\jwt\JWTFilter.java
   create src\main\java\com\mainstreamdata\myapp\config\MicroserviceSecurityConfi
guration.java
   create src\main\resources\config\bootstrap.yml
   create src\main\resources\config\bootstrap-dev.yml
   create src\main\resources\config\bootstrap-prod.yml
   create src\main\java\com\mainstreamdata\myapp\config\metrics\SpectatorLogMetri
cWriter.java
   create src\main\java\com\mainstreamdata\myapp\myappuserdbApp.java
   create src\main\java\com\mainstreamdata\myapp\ApplicationWebXml.java
   create src\main\java\com\mainstreamdata\myapp\aop\logging\LoggingAspect.java
   create src\main\java\com\mainstreamdata\myapp\config\DefaultProfileUtil.java
   create src\main\java\com\mainstreamdata\myapp\config\apidoc\package-info.java
   create src\main\java\com\mainstreamdata\myapp\config\apidoc\SwaggerConfigurati
on.java
   create src\main\java\com\mainstreamdata\myapp\config\apidoc\PageableParameterB
uilderPlugin.java
   create src\main\java\com\mainstreamdata\myapp\async\package-info.java
   create src\main\java\com\mainstreamdata\myapp\async\ExceptionHandlingAsyncTask
Executor.java
   create src\main\java\com\mainstreamdata\myapp\config\package-info.java
   create src\main\java\com\mainstreamdata\myapp\config\AsyncConfiguration.java
   create src\main\java\com\mainstreamdata\myapp\config\CacheConfiguration.java
   create src\main\java\com\mainstreamdata\myapp\config\Constants.java
   create src\main\java\com\mainstreamdata\myapp\config\DateTimeFormatConfigurati
on.java
   create src\main\java\com\mainstreamdata\myapp\config\LoggingConfiguration.java

   create src\main\java\com\mainstreamdata\myapp\config\CloudDatabaseConfiguratio
n.java
   create src\main\java\com\mainstreamdata\myapp\config\DatabaseConfiguration.jav
a
   create src\main\java\com\mainstreamdata\myapp\config\audit\package-info.java
   create src\main\java\com\mainstreamdata\myapp\config\audit\AuditEventConverter
.java
   create src\main\java\com\mainstreamdata\myapp\config\JHipsterProperties.java
   create src\main\java\com\mainstreamdata\myapp\config\LocaleConfiguration.java
   create src\main\java\com\mainstreamdata\myapp\config\LoggingAspectConfiguratio
n.java
   create src\main\java\com\mainstreamdata\myapp\config\MetricsConfiguration.java

   create src\main\java\com\mainstreamdata\myapp\config\ThymeleafConfiguration.ja
va
   create src\main\java\com\mainstreamdata\myapp\config\WebConfigurer.java
   create src\main\java\com\mainstreamdata\myapp\config\locale\package-info.java
   create src\main\java\com\mainstreamdata\myapp\config\locale\AngularCookieLocal
eResolver.java
   create src\main\java\com\mainstreamdata\myapp\config\liquibase\AsyncSpringLiqu
ibase.java
   create src\main\java\com\mainstreamdata\myapp\config\liquibase\package-info.ja
va
   create src\main\java\com\mainstreamdata\myapp\domain\package-info.java
   create src\main\java\com\mainstreamdata\myapp\domain\util\JSR310DateConverters
.java
   create src\main\java\com\mainstreamdata\myapp\domain\util\FixedH2Dialect.java
   create src\main\java\com\mainstreamdata\myapp\domain\AbstractAuditingEntity.ja
va
   create src\main\java\com\mainstreamdata\myapp\domain\PersistentAuditEvent.java

   create src\main\java\com\mainstreamdata\myapp\repository\package-info.java
   create src\main\java\com\mainstreamdata\myapp\service\package-info.java
   create src\main\java\com\mainstreamdata\myapp\web\rest\errors\ErrorConstants.j
ava
   create src\main\java\com\mainstreamdata\myapp\web\rest\errors\CustomParameteri
zedException.java
   create src\main\java\com\mainstreamdata\myapp\web\rest\errors\ErrorVM.java
   create src\main\java\com\mainstreamdata\myapp\web\rest\errors\ExceptionTransla
tor.java
   create src\main\java\com\mainstreamdata\myapp\web\rest\errors\FieldErrorVM.jav
a
   create src\main\java\com\mainstreamdata\myapp\web\rest\errors\ParameterizedErr
orVM.java
   create src\main\java\com\mainstreamdata\myapp\web\filter\package-info.java
   create src\main\java\com\mainstreamdata\myapp\web\filter\CachingHttpHeadersFil
ter.java
   create src\main\java\com\mainstreamdata\myapp\web\rest\vm\package-info.java
   create src\main\java\com\mainstreamdata\myapp\web\rest\vm\LoggerVM.java
   create src\main\java\com\mainstreamdata\myapp\web\rest\util\HeaderUtil.java
   create src\main\java\com\mainstreamdata\myapp\web\rest\util\PaginationUtil.jav
a
   create src\main\java\com\mainstreamdata\myapp\web\rest\package-info.java
   create src\main\java\com\mainstreamdata\myapp\web\rest\LogsResource.java
   create src\main\java\com\mainstreamdata\myapp\web\rest\ProfileInfoResource.jav
a
   create src\test\java\com\mainstreamdata\myapp\web\rest\TestUtil.java
   create src\test\resources\config\application.yml
   create src\test\resources\logback-test.xml
   create src\test\resources\config\bootstrap.yml
   create src\test\resources\ehcache.xml
   create src\test\gatling\conf\gatling.conf
   create src\test\gatling\conf\logback.xml
   create src\test\java\com\mainstreamdata\myapp\cucumber\CucumberTest.java
   create src\test\java\com\mainstreamdata\myapp\cucumber\stepdefs\StepDefs.java

Server app generated successfully.

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**
I haven't created any database entities.

I couldn't find a .jhipster directory ("ls" wouldn't have worked anyway).

##### **Browsers and Operating System**

This was running on Windows 7.  I'm using eclipse 4.5.2 with buildship.  Never got to the browser

**Comment by Smitty010** [comment]
I realized the issue when I was driving home.  I assumed there would be a default spring profile.  Needed spring.profiles.active=dev somewhere (like an environment variable :) ).
