### ISSUE TITLE
Error creating bean with name 'entityManagerFactory' 

### ISSUE THREAD

**Issue by ERLP** [jhipster/generator-jhipster#4824]
When trying to start the jboss server, am getting the below exception and server comes to a halt after this exception. Can help to assist on this issue?

Env: Redhat Linux

[server=HornetQServerImpl::serverUUID=e0a7879b-bb97-11e6-927f-f791b5307ce3]]@14a8b8dc doing deliver. messageReferences=0
18:00:00,550 INFO  [stdout] (ServerService Thread Pool -- 62) 2017-01-07 18:00:00.550  WARN 8755 --- [read Pool -- 62] ationConfigEmbeddedWebApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'entityManagerFactory' defined in class path resource [org/springframework/boot/autoconfigure/orm/jpa/HibernateJpaAutoConfiguration.class]: Invocation of init method failed; nested exception is java.lang.NoSuchMethodError: org.jboss.logging.Logger.getMessageLogger(Ljava/lang/Class;Ljava/lang/String;)Ljava/lang/Object;
18:00:00,552 INFO  [com.hazelcast.core.LifecycleService] (ServerService Thread Pool -- 62) [127.0.0.1]:5701 [dev] [3.6.5] Address[127.0.0.1]:5701 is SHUTTING_DOWN
18:00:00,553 INFO  [com.hazelcast.instance.Node] (ServerService Thread Pool -- 62) [127.0.0.1]:5701 [dev] [3.6.5] Shutting down connection manager...
18:00:00,557 INFO  [com.hazelcast.instance.Node] (ServerService Thread Pool -- 62) [127.0.0.1]:5701 [dev] [3.6.5] Shutting down node engine...
18:00:00,575 INFO  [com.hazelcast.instance.NodeExtension] (ServerService Thread Pool -- 62) [127.0.0.1]:5701 [dev] [3.6.5] Destroying node NodeExtension.
18:00:00,575 INFO  [com.hazelcast.instance.Node] (ServerService Thread Pool -- 62) [127.0.0.1]:5701 [dev] [3.6.5] Hazelcast Shutdown is completed in 22 ms.
18:00:00,576 INFO  [com.hazelcast.core.LifecycleService] (ServerService Thread Pool -- 62) [127.0.0.1]:5701 [dev] [3.6.5] Address[127.0.0.1]:5701 is SHUTDOWN
18:00:00,576 INFO  [stdout] (ServerService Thread Pool -- 62) 2017-01-07 18:00:00.576  INFO 8755 --- [read Pool -- 62] c.s.cp.config.CacheConfiguration         : Closing Cache Manager
18:00:00,597 INFO  [stdout] (ServerService Thread Pool -- 62) 2017-01-07 18:00:00.597  WARN 8755 --- [read Pool -- 62] o.s.boot.SpringApplication               : Error handling failed (Error creating bean with name 'delegatingApplicationListener' defined in class path resource [org/springframework/security/config/annotation/web/configuration/WebSecurityConfiguration.class]: BeanPostProcessor before instantiation of bean failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'metaDataSourceAdvisor': Cannot resolve reference to bean 'methodSecurityMetadataSource' while setting constructor argument; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.security.config.annotation.method.configuration.GlobalMethodSecurityConfiguration': Initialization of bean failed; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No bean named 'org.springframework.context.annotation.ConfigurationClassPostProcessor.importRegistry' is defined)
18:00:00,610 INFO  [stdout] (ServerService Thread Pool -- 62) 2017-01-07 18:00:00.609 ERROR 8755 --- [read Pool -- 62] o.s.boot.SpringApplication               : Application startup failed
18:00:00,614 INFO  [stdout] (ServerService Thread Pool -- 62) 
18:00:00,615 INFO  [stdout] (ServerService Thread Pool -- 62) org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'entityManagerFactory' defined in class path resource [org/springframework/boot/autoconfigure/orm/jpa/HibernateJpaAutoConfiguration.class]: Invocation of init method failed; nested exception is java.lang.NoSuchMethodError: org.jboss.logging.Logger.getMessageLogger(Ljava/lang/Class;Ljava/lang/String;)Ljava/lang/Object;
18:00:00,615 INFO  [stdout] (ServerService Thread Pool -- 62) 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1583)
18:00:00,615 INFO  [stdout] (ServerService Thread Pool -- 62) 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:545)
18:00:00,615 INFO  [stdout] (ServerService Thread Pool -- 62) 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482)
18:00:00,615 INFO  [stdout] (ServerService Thread Pool -- 62) 	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
18:00:00,615 INFO  [stdout] (ServerService Thread Pool -- 62) 	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
18:00:00,615 INFO  [stdout] (ServerService Thread Pool -- 62) 	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
18:00:00,615 INFO  [stdout] (ServerService Thread Pool -- 62) 	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
18:00:00,615 INFO  [stdout] (ServerService Thread Pool -- 62) 	at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1076)
18:00:00,615 INFO  [stdout] (ServerService Thread Pool -- 62) 	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:851)
18:00:00,615 INFO  [stdout] (ServerService Thread Pool -- 62) 	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:541)
18:00:00,615 INFO  [stdout] (ServerService Thread Pool -- 62) 	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122)
18:00:00,615 INFO  [stdout] (ServerService Thread Pool -- 62) 	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:761)
18:00:00,616 INFO  [stdout] (ServerService Thread Pool -- 62) 	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:371)
18:00:00,616 INFO  [stdout] (ServerService Thread Pool -- 62) 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315)
18:00:00,616 INFO  [stdout] (ServerService Thread Pool -- 62) 	at org.springframework.boot.web.support.SpringBootServletInitializer.run(SpringBootServletInitializer.java:151)
18:00:00,616 INFO  [stdout] (ServerService Thread Pool -- 62) 	at org.springframework.boot.web.support.SpringBootServletInitializer.createRootApplicationContext(SpringBootServletInitializer.java:131)
18:00:00,616 INFO  [stdout] (ServerService Thread Pool -- 62) 	at org.springframework.boot.web.support.SpringBootServletInitializer.onStartup(SpringBootServletInitializer.java:86)
18:00:00,616 INFO  [stdout] (ServerService Thread Pool -- 62) 	at org.springframework.web.SpringServletContainerInitializer.onStartup(SpringServletContainerInitializer.java:169)
18:00:00,616 INFO  [stdout] (ServerService Thread Pool -- 62) 	at org.jboss.as.web.deployment.JBossContextConfig.lifecycleEvent(JBossContextConfig.java:181)
18:00:00,616 INFO  [stdout] (ServerService Thread Pool -- 62) 	at org.apache.catalina.util.LifecycleSupport.fireLifecycleEvent(LifecycleSupport.java:115)
18:00:00,616 INFO  [stdout] (ServerService Thread Pool -- 62) 	at org.apache.catalina.core.StandardContext.start(StandardContext.java:3772)
18:00:00,617 INFO  [stdout] (ServerService Thread Pool -- 62) 	at org.jboss.as.web.deployment.WebDeploymentService.doStart(WebDeploymentService.java:161)
18:00:00,617 INFO  [stdout] (ServerService Thread Pool -- 62) 	at org.jboss.as.web.deployment.WebDeploymentService.access$000(WebDeploymentService.java:59)
18:00:00,617 INFO  [stdout] (ServerService Thread Pool -- 62) 	at org.jboss.as.web.deployment.WebDeploymentService$1.run(WebDeploymentService.java:94)
18:00:00,617 INFO  [stdout] (ServerService Thread Pool -- 62) 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
18:00:00,617 INFO  [stdout] (ServerService Thread Pool -- 62) 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
18:00:00,617 INFO  [stdout] (ServerService Thread Pool -- 62) 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
18:00:00,617 INFO  [stdout] (ServerService Thread Pool -- 62) 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
18:00:00,617 INFO  [stdout] (ServerService Thread Pool -- 62) 	at java.lang.Thread.run(Thread.java:745)
18:00:00,617 INFO  [stdout] (ServerService Thread Pool -- 62) 	at org.jboss.threads.JBossThread.run(JBossThread.java:122)
18:00:00,619 INFO  [stdout] (ServerService Thread Pool -- 62) Caused by: java.lang.NoSuchMethodError: org.jboss.logging.Logger.getMessageLogger(Ljava/lang/Class;Ljava/lang/String;)Ljava/lang/Object;
18:00:00,619 INFO  [stdout] (ServerService Thread Pool -- 62) 	at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.<clinit>(EntityManagerFactoryBuilderImpl.java:121)
18:00:00,619 INFO  [stdout] (ServerService Thread Pool -- 62) 	at org.springframework.orm.jpa.vendor.SpringHibernateJpaPersistenceProvider.createContainerEntityManagerFactory(SpringHibernateJpaPersistenceProvider.java:54)
18:00:00,619 INFO  [stdout] (ServerService Thread Pool -- 62) 	at org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean.createNativeEntityManagerFactory(LocalContainerEntityManagerFactoryBean.java:353)
18:00:00,619 INFO  [stdout] (ServerService Thread Pool -- 62) 	at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.buildNativeEntityManagerFactory(AbstractEntityManagerFactoryBean.java:373)
18:00:00,619 INFO  [stdout] (ServerService Thread Pool -- 62) 	at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.afterPropertiesSet(AbstractEntityManagerFactoryBean.java:362)
18:00:00,619 INFO  [stdout] (ServerService Thread Pool -- 62) 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1642)
18:00:00,620 INFO  [stdout] (ServerService Thread Pool -- 62) 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1579)
18:00:00,620 INFO  [stdout] (ServerService Thread Pool -- 62) 	... 29 common frames omitted
18:00:00,621 INFO  [stdout] (ServerService Thread Pool -- 62) 
18:00:00,622 ERROR [org.jboss.web] (ServerService Thread Pool -- 62) JBAS018202: Error calling onStartup for servlet container initializer: org.springframework.web.SpringServletContainerInitializer: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'entityManagerFactory' defined in class path resource [org/springframework/boot/autoconfigure/orm/jpa/HibernateJpaAutoConfiguration.class]: Invocation of init method failed; nested exception is java.lang.NoSuchMethodError: org.jboss.logging.Logger.getMessageLogger(Ljava/lang/Class;Ljava/lang/String;)Ljava/lang/Object;
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1583) [spring-beans-4.3.3.RELEASE.jar:4.3.3.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:545) [spring-beans-4.3.3.RELEASE.jar:4.3.3.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482) [spring-beans-4.3.3.RELEASE.jar:4.3.3.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306) [spring-beans-4.3.3.RELEASE.jar:4.3.3.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230) [spring-beans-4.3.3.RELEASE.jar:4.3.3.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302) [spring-beans-4.3.3.RELEASE.jar:4.3.3.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197) [spring-beans-4.3.3.RELEASE.jar:4.3.3.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1076) [spring-context-4.3.3.RELEASE.jar:4.3.3.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:851) [spring-context-4.3.3.RELEASE.jar:4.3.3.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:541) [spring-context-4.3.3.RELEASE.jar:4.3.3.RELEASE]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122) [spring-boot-1.4.1.RELEASE.jar:1.4.1.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:761) [spring-boot-1.4.1.RELEASE.jar:1.4.1.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:371) [spring-boot-1.4.1.RELEASE.jar:1.4.1.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315) [spring-boot-1.4.1.RELEASE.jar:1.4.1.RELEASE]
	at org.springframework.boot.web.support.SpringBootServletInitializer.run(SpringBootServletInitializer.java:151) [spring-boot-1.4.1.RELEASE.jar:1.4.1.RELEASE]
	at org.springframework.boot.web.support.SpringBootServletInitializer.createRootApplicationContext(SpringBootServletInitializer.java:131) [spring-boot-1.4.1.RELEASE.jar:1.4.1.RELEASE]
	at org.springframework.boot.web.support.SpringBootServletInitializer.onStartup(SpringBootServletInitializer.java:86) [spring-boot-1.4.1.RELEASE.jar:1.4.1.RELEASE]
	at org.springframework.web.SpringServletContainerInitializer.onStartup(SpringServletContainerInitializer.java:169) [spring-web-4.3.3.RELEASE.jar:4.3.3.RELEASE]
	at org.jboss.as.web.deployment.JBossContextConfig.lifecycleEvent(JBossContextConfig.java:181) [jboss-as-web-7.4.3.Final-redhat-2.jar:7.4.3.Final-redhat-2]
	at org.apache.catalina.util.LifecycleSupport.fireLifecycleEvent(LifecycleSupport.java:115) [jbossweb-7.4.10.Final-redhat-1.jar:7.4.10.Final-redhat-1]
	at org.apache.catalina.core.StandardContext.start(StandardContext.java:3772) [jbossweb-7.4.10.Final-redhat-1.jar:7.4.10.Final-redhat-1]
	at org.jboss.as.web.deployment.WebDeploymentService.doStart(WebDeploymentService.java:161) [jboss-as-web-7.4.3.Final-redhat-2.jar:7.4.3.Final-redhat-2]
	at org.jboss.as.web.deployment.WebDeploymentService.access$000(WebDeploymentService.java:59) [jboss-as-web-7.4.3.Final-redhat-2.jar:7.4.3.Final-redhat-2]
	at org.jboss.as.web.deployment.WebDeploymentService$1.run(WebDeploymentService.java:94) [jboss-as-web-7.4.3.Final-redhat-2.jar:7.4.3.Final-redhat-2]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [rt.jar:1.8.0_40]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [rt.jar:1.8.0_40]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [rt.jar:1.8.0_40]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [rt.jar:1.8.0_40]
	at java.lang.Thread.run(Thread.java:745) [rt.jar:1.8.0_40]
	at org.jboss.threads.JBossThread.run(JBossThread.java:122)
Caused by: java.lang.NoSuchMethodError: org.jboss.logging.Logger.getMessageLogger(Ljava/lang/Class;Ljava/lang/String;)Ljava/lang/Object;
	at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.<clinit>(EntityManagerFactoryBuilderImpl.java:121) [hibernate-entitymanager-4.3.11.Final.jar:4.3.11.Final]
	at org.springframework.orm.jpa.vendor.SpringHibernateJpaPersistenceProvider.createContainerEntityManagerFactory(SpringHibernateJpaPersistenceProvider.java:54) [spring-orm-4.3.3.RELEASE.jar:4.3.3.RELEASE]
	at org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean.createNativeEntityManagerFactory(LocalContainerEntityManagerFactoryBean.java:353) [spring-orm-4.3.3.RELEASE.jar:4.3.3.RELEASE]
	at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.buildNativeEntityManagerFactory(AbstractEntityManagerFactoryBean.java:373) [spring-orm-4.3.3.RELEASE.jar:4.3.3.RELEASE]
	at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.afterPropertiesSet(AbstractEntityManagerFactoryBean.java:362) [spring-orm-4.3.3.RELEASE.jar:4.3.3.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1642) [spring-beans-4.3.3.RELEASE.jar:4.3.3.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1579) [spring-beans-4.3.3.RELEASE.jar:4.3.3.RELEASE]
	... 29 more

**Comment by deepu105** [comment]
This is a bug tracker and not a support channel
This ticket has been closed as the guidelines are not followed.

Tickets must follow our [Guidelines](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md#submitting-an-issue), as mentioned in:

1. our [Readme file on the front page of the project](https://github.com/jhipster/generator-jhipster/blob/master/README.md), 
2. the ["create a new ticket" page](https://github.com/jhipster/generator-jhipster/issues/new) and
3. our [Help page](http://jhipster.github.io/help/)

We have also created a template on the ["create a new ticket" page](https://github.com/jhipster/generator-jhipster/issues/new) to help you follow those guidelines.
