### ISSUE TITLE
microservice use mysql-docker insert unicode throw SQLException

### ISSUE THREAD

**Issue by anjia0532** [jhipster/generator-jhipster#4887]
exception like this

```java
java.sql.SQLException: Incorrect string value: '\xF0\x9F\x92\x94' for column 'xxx' at row 1  
    at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1073)  
    at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3593)  
    at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3525)  
    at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1986)  
    at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2140)  
    at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2620)  
    at com.mysql.jdbc.StatementImpl.executeUpdate(StatementImpl.java:1662)  
    at com.mysql.jdbc.StatementImpl.executeUpdate(StatementImpl.java:1581) 
```
PR #4886

**Comment by jdubois** [comment]
Closing as Pr is merged.
