### ISSUE TITLE
JHipster Websocket 

### ISSUE THREAD

**Issue by bahadyr** [jhipster/generator-jhipster#4892]
##### **Overview of the issue**

I have a jhipster generated spring boot web app. I added websocket support from spring boot site (https://spring.io/guides/gs/messaging-stomp-websocket/).

App fails when starting in a docker container. But work normally on localhost.

```springframework.beans.factory.BeanCreationException: Error creating bean with name 'resourceHandlerMapping' defined in class path resource [org/springframework/boot/autoconfigure/web/WebMvcAutoConfiguration$EnableWebMvcConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.web.servlet.HandlerMapping]: Factory method 'resourceHandlerMapping' threw exception; nested exception is java.lang.RuntimeException: java.io.FileNotFoundException: /app.war!/WEB-INF/lib/bootstrap-3.3.7.jar (No such file or directory)
staffservice_1   | 2017-01-18 09:14:57.636  INFO 6 --- [           main] c.t.s.config.CacheConfiguration          : Remove Cache Manager metrics
staffservice_1   | 2017-01-18 09:14:57.702  INFO 6 --- [           main] c.t.s.config.CacheConfiguration          : Closing Cache Manager
staffservice_1   | 2017-01-18 09:14:57.800 ERROR 6 --- [           main] o.s.boot.SpringApplication               : Application startup failed
staffservice_1   | 
staffservice_1   | org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'resourceHandlerMapping' defined in class path resource [org/springframework/boot/autoconfigure/web/WebMvcAutoConfiguration$EnableWebMvcConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.web.servlet.HandlerMapping]: Factory method 'resourceHandlerMapping' threw exception; nested exception is java.lang.RuntimeException: java.io.FileNotFoundException: /app.war!/WEB-INF/lib/bootstrap-3.3.7.jar (No such file or directory)
staffservice_1   | 	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:599)
staffservice_1   | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1127)
staffservice_1   | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1022)
staffservice_1   | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:510)
staffservice_1   | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482)
staffservice_1   | 	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
staffservice_1   | 	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
staffservice_1   | 	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
staffservice_1   | 	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
staffservice_1   | 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:778)
staffservice_1   | 	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:839)
staffservice_1   | 	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:538)
staffservice_1   | 	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:118)
staffservice_1   | 	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:760)
staffservice_1   | 	at org.springframework.boot.SpringApplication.createAndRefreshContext(SpringApplication.java:360)
staffservice_1   | 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:306)
staffservice_1   | 	at com.teammachine.staffrostering.ShiftworkApp.main(ShiftworkApp.java:70)
staffservice_1   | 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
staffservice_1   | 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
staffservice_1   | 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
staffservice_1   | 	at java.lang.reflect.Method.invoke(Method.java:498)
staffservice_1   | 	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:54)
staffservice_1   | 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:104)
staffservice_1   | 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:61)
staffservice_1   | 	at org.springframework.boot.loader.WarLauncher.main(WarLauncher.java:61)
staffservice_1   | Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.web.servlet.HandlerMapping]: Factory method 'resourceHandlerMapping' threw exception; nested exception is java.lang.RuntimeException: java.io.FileNotFoundException: /app.war!/WEB-INF/lib/bootstrap-3.3.7.jar (No such file or directory)
staffservice_1   | 	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:189)
staffservice_1   | 	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:588)
staffservice_1   | 	... 24 common frames omitted
staffservice_1   | Caused by: java.lang.RuntimeException: java.io.FileNotFoundException: /app.war!/WEB-INF/lib/bootstrap-3.3.7.jar (No such file or directory)
staffservice_1   | 	at org.webjars.urlprotocols.JarUrlProtocolHandler.getAssetPaths(JarUrlProtocolHandler.java:54)
staffservice_1   | 	at org.webjars.WebJarAssetLocator.getAssetPaths(WebJarAssetLocator.java:91)
staffservice_1   | 	at org.webjars.WebJarAssetLocator.getFullPathIndex(WebJarAssetLocator.java:121)
staffservice_1   | 	at org.webjars.WebJarAssetLocator.<init>(WebJarAssetLocator.java:152)
staffservice_1   | 	at org.springframework.web.servlet.resource.WebJarsResourceResolver.<init>(WebJarsResourceResolver.java:52)
staffservice_1   | 	at org.springframework.web.servlet.config.annotation.ResourceChainRegistration.getResourceResolvers(ResourceChainRegistration.java:108)
staffservice_1   | 	at org.springframework.web.servlet.config.annotation.ResourceHandlerRegistration.getRequestHandler(ResourceHandlerRegistration.java:164)
staffservice_1   | 	at org.springframework.web.servlet.config.annotation.ResourceHandlerRegistry.getHandlerMapping(ResourceHandlerRegistry.java:122)
staffservice_1   | 	at org.springframework.web.servlet.config.annotation.WebMvcConfigurationSupport.resourceHandlerMapping(WebMvcConfigurationSupport.java:448)
staffservice_1   | 	at org.springframework.boot.autoconfigure.web.WebMvcAutoConfiguration$EnableWebMvcConfiguration$$EnhancerBySpringCGLIB$$cb97aa79.CGLIB$resourceHandlerMapping$37(<generated>)
staffservice_1   | 	at org.springframework.boot.autoconfigure.web.WebMvcAutoConfiguration$EnableWebMvcConfiguration$$EnhancerBySpringCGLIB$$cb97aa79$$FastClassBySpringCGLIB$$23ebded4.invoke(<generated>)
staffservice_1   | 	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228)
staffservice_1   | 	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:356)
staffservice_1   | 	at org.springframework.boot.autoconfigure.web.WebMvcAutoConfiguration$EnableWebMvcConfiguration$$EnhancerBySpringCGLIB$$cb97aa79.resourceHandlerMapping(<generated>)
staffservice_1   | 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
staffservice_1   | 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
staffservice_1   | 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
staffservice_1   | 	at java.lang.reflect.Method.invoke(Method.java:498)
staffservice_1   | 	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:162)
staffservice_1   | 	... 25 common frames omitted
staffservice_1   | Caused by: java.io.FileNotFoundException: /app.war!/WEB-INF/lib/bootstrap-3.3.7.jar (No such file or directory)
staffservice_1   | 	at java.util.zip.ZipFile.open(Native Method)
staffservice_1   | 	at java.util.zip.ZipFile.<init>(ZipFile.java:219)
staffservice_1   | 	at java.util.zip.ZipFile.<init>(ZipFile.java:149)
staffservice_1   | 	at java.util.jar.JarFile.<init>(JarFile.java:166)
staffservice_1   | 	at java.util.jar.JarFile.<init>(JarFile.java:130)
staffservice_1   | 	at org.webjars.urlprotocols.JarUrlProtocolHandler.getAssetPaths(JarUrlProtocolHandler.java:36)
staffservice_1   | 	... 43 common frames omitted
staffservice_1   | 
staffservice_1   | java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
staffservice_1   | 	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:62)
staffservice_1   | 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:104)
staffservice_1   | 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:61)
staffservice_1   | 	at org.springframework.boot.loader.WarLauncher.main(WarLauncher.java:61)
staffservice_1   | Caused by: java.lang.reflect.InvocationTargetException
staffservice_1   | 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
staffservice_1   | 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
staffservice_1   | 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
staffservice_1   | 	at java.lang.reflect.Method.invoke(Method.java:498)
staffservice_1   | 	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:54)
staffservice_1   | 	... 3 more
staffservice_1   | Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'resourceHandlerMapping' defined in class path resource [org/springframework/boot/autoconfigure/web/WebMvcAutoConfiguration$EnableWebMvcConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.web.servlet.HandlerMapping]: Factory method 'resourceHandlerMapping' threw exception; nested exception is java.lang.RuntimeException: java.io.FileNotFoundException: /app.war!/WEB-INF/lib/bootstrap-3.3.7.jar (No such file or directory)
staffservice_1   | 	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:599)
staffservice_1   | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1127)
staffservice_1   | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1022)
staffservice_1   | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:510)
staffservice_1   | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482)
staffservice_1   | 	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
staffservice_1   | 	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
staffservice_1   | 	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
staffservice_1   | 	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
staffservice_1   | 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:778)
staffservice_1   | 	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:839)
staffservice_1   | 	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:538)
staffservice_1   | 	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:118)
staffservice_1   | 	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:760)
staffservice_1   | 	at org.springframework.boot.SpringApplication.createAndRefreshContext(SpringApplication.java:360)
staffservice_1   | 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:306)
staffservice_1   | 	at com.teammachine.staffrostering.ShiftworkApp.main(ShiftworkApp.java:70)
staffservice_1   | 	... 8 more
staffservice_1   | Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.web.servlet.HandlerMapping]: Factory method 'resourceHandlerMapping' threw exception; nested exception is java.lang.RuntimeException: java.io.FileNotFoundException: /app.war!/WEB-INF/lib/bootstrap-3.3.7.jar (No such file or directory)
staffservice_1   | 	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:189)
staffservice_1   | 	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:588)
staffservice_1   | 	... 24 more
staffservice_1   | Caused by: java.lang.RuntimeException: java.io.FileNotFoundException: /app.war!/WEB-INF/lib/bootstrap-3.3.7.jar (No such file or directory)
staffservice_1   | 	at org.webjars.urlprotocols.JarUrlProtocolHandler.getAssetPaths(JarUrlProtocolHandler.java:54)
staffservice_1   | 	at org.webjars.WebJarAssetLocator.getAssetPaths(WebJarAssetLocator.java:91)
staffservice_1   | 	at org.webjars.WebJarAssetLocator.getFullPathIndex(WebJarAssetLocator.java:121)
staffservice_1   | 	at org.webjars.WebJarAssetLocator.<init>(WebJarAssetLocator.java:152)
staffservice_1   | 	at org.springframework.web.servlet.resource.WebJarsResourceResolver.<init>(WebJarsResourceResolver.java:52)
staffservice_1   | 	at org.springframework.web.servlet.config.annotation.ResourceChainRegistration.getResourceResolvers(ResourceChainRegistration.java:108)
staffservice_1   | 	at org.springframework.web.servlet.config.annotation.ResourceHandlerRegistration.getRequestHandler(ResourceHandlerRegistration.java:164)
staffservice_1   | 	at org.springframework.web.servlet.config.annotation.ResourceHandlerRegistry.getHandlerMapping(ResourceHandlerRegistry.java:122)
staffservice_1   | 	at org.springframework.web.servlet.config.annotation.WebMvcConfigurationSupport.resourceHandlerMapping(WebMvcConfigurationSupport.java:448)
staffservice_1   | 	at org.springframework.boot.autoconfigure.web.WebMvcAutoConfiguration$EnableWebMvcConfiguration$$EnhancerBySpringCGLIB$$cb97aa79.CGLIB$resourceHandlerMapping$37(<generated>)
staffservice_1   | 	at org.springframework.boot.autoconfigure.web.WebMvcAutoConfiguration$EnableWebMvcConfiguration$$EnhancerBySpringCGLIB$$cb97aa79$$FastClassBySpringCGLIB$$23ebded4.invoke(<generated>)
staffservice_1   | 	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228)
staffservice_1   | 	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:356)
staffservice_1   | 	at org.springframework.boot.autoconfigure.web.WebMvcAutoConfiguration$EnableWebMvcConfiguration$$EnhancerBySpringCGLIB$$cb97aa79.resourceHandlerMapping(<generated>)
staffservice_1   | 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
staffservice_1   | 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
staffservice_1   | 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
staffservice_1   | 	at java.lang.reflect.Method.invoke(Method.java:498)
staffservice_1   | 	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:162)
staffservice_1   | 	... 25 more
staffservice_1   | Caused by: java.io.FileNotFoundException: /app.war!/WEB-INF/lib/bootstrap-3.3.7.jar (No such file or directory)
staffservice_1   | 	at java.util.zip.ZipFile.open(Native Method)
staffservice_1   | 	at java.util.zip.ZipFile.<init>(ZipFile.java:219)
staffservice_1   | 	at java.util.zip.ZipFile.<init>(ZipFile.java:149)
staffservice_1   | 	at java.util.jar.JarFile.<init>(JarFile.java:166)
staffservice_1   | 	at java.util.jar.JarFile.<init>(JarFile.java:130)
staffservice_1   | 	at org.webjars.urlprotocols.JarUrlProtocolHandler.getAssetPaths(JarUrlProtocolHandler.java:36)
staffservice_1   | 	... 43 more```

##### **Reproduce the error**

Generate jhipster web app.
Add classes from messaging-stomp-websocket example into app.
Put `"websocket": "spring-websocket",` in a .yo-rc.json
Run war application in a docker container.

**Comment by jdubois** [comment]
Please follow our guidelines.... We don't even have a version number here, how are we supposed to work!
Besides, I see in your stacktrace you use Webjars in your app, which is something we certainly don't do, so I have no idea what you did after generating the app.

**Comment by jdubois** [comment]
This ticket has been closed as the guidelines are not followed.

Tickets must follow our [Guidelines](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md#submitting-an-issue), as mentioned in:

1. our [Readme file on the front page of the project](https://github.com/jhipster/generator-jhipster/blob/master/README.md), 
2. the ["create a new ticket" page](https://github.com/jhipster/generator-jhipster/issues/new) and
3. our [Help page](http://jhipster.github.io/help/)

We have also created a template on the ["create a new ticket" page](https://github.com/jhipster/generator-jhipster/issues/new) to help you follow those guidelines.

**Comment by treyyoder** [comment]
@bahadyr Were you able to find a solution?

**Comment by bahadyr** [comment]
Thanks @treyyoder! Our team managed with some other solutions.

**Comment by treyyoder** [comment]
I resolved this by updating webjars.
 ``` 
 - compile 'org.webjars:webjars-locator:0.19'
 + compile group: 'org.webjars', name: 'webjars-locator', version: '0.32-1'```
