### ISSUE TITLE
Stack trace when searching an entity

### ISSUE THREAD

**Issue by jdanosborne** [jhipster/generator-jhipster#5001]
##### **Overview of the issue**
Doing a text search in any of my  generated entities causes a stack trace ...
```
17-01-28 16:54:40.115 ERROR 2416 --- [ XNIO-2 task-19] com.dan.jh.aop.logging.LoggingAspect  : Exception in com.dan.jh.web.rest.Gn_operatorResource.searchGn_operators() with cause = 'SearchParseException[No mapping found for [id] in order to sort on]' and exception = 'all shards failed'

org.elasticsearch.action.search.SearchPhaseExecutionException: all shards failed
    at org.elasticsearch.action.search.AbstractSearchAsyncAction.onFirstPhaseResult(AbstractSearchAsyncAction.java:206)
    at org.elasticsearch.action.search.AbstractSearchAsyncAction$1.onFailure(AbstractSearchAsyncAction.java:152)
    at org.elasticsearch.action.ActionListenerResponseHandler.handleException(ActionListenerResponseHandler.java:46)
    at org.elasticsearch.transport.TransportService$DirectResponseChannel.processException(TransportService.java:872)
    at org.elasticsearch.transport.TransportService$DirectResponseChannel.sendResponse(TransportService.java:850)
    at org.elasticsearch.transport.TransportService$4.onFailure(TransportService.java:387)
    at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:39)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
Caused by: org.elasticsearch.search.SearchParseException: No mapping found for [id] in order to sort on
    at org.elasticsearch.search.sort.SortParseElement.addSortField(SortParseElement.java:213)
    at org.elasticsearch.search.sort.SortParseElement.addCompoundSortField(SortParseElement.java:187)
    at org.elasticsearch.search.sort.SortParseElement.parse(SortParseElement.java:85)
    at org.elasticsearch.search.SearchService.parseSource(SearchService.java:856)
    at org.elasticsearch.search.SearchService.createContext(SearchService.java:667)
    at org.elasticsearch.search.SearchService.createAndPutContext(SearchService.java:633)
    at org.elasticsearch.search.SearchService.executeDfsPhase(SearchService.java:264)
    at org.elasticsearch.search.action.SearchServiceTransportAction$SearchDfsTransportHandler.messageReceived(SearchServiceTransportAction.java:360)
    at org.elasticsearch.search.action.SearchServiceTransportAction$SearchDfsTransportHandler.messageReceived(SearchServiceTransportAction.java:357)
    at org.elasticsearch.transport.TransportRequestHandler.messageReceived(TransportRequestHandler.java:33)
    at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:77)
    at org.elasticsearch.transport.TransportService$4.doRun(TransportService.java:376)
    at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
    ... 3 common frames omitted
```

##### **Motivation for or Use Case**

The search fails

##### **Reproduce the error**

Login, choose an entity from the Entities menu, enter some text in the search box and hit return.

##### **JHipster Version(s)**

3.12.1

##### **JHipster configuration**

Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
jh@0.0.0 /home/dan/jhipster2
└── generator-jhipster@3.12.1 

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

```yaml
{
  "generator-jhipster": {
    "jhipsterVersion": "3.12.1",
    "baseName": "jh",
    "packageName": "com.dan.jh",
    "packageFolder": "com/dan/jh",
    "serverPort": "8080",
    "authenticationType": "session",
    "hibernateCache": "no",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "mysql",
    "prodDatabaseType": "mysql",
    "searchEngine": "elasticsearch",
    "messageBroker": false,
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "rememberMeKey": "95664f2d596c9336298944c568047b8038e27f74",
    "useSass": false,
    "applicationType": "monolith",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en",
      "cs"
    ],
    "serviceDiscoveryType": false
  }
}
```

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

Gn_client.json

```yaml
{
    "fluentMethods": true,
    "relationships": [],
    "fields": [
        {
            "fieldName": "instanceId",
            "fieldType": "String",
            "fieldValidateRules": [
                "required",
                "maxlength"
            ],
            "fieldValidateRulesMaxlength": "5"
        },
        {
            "fieldName": "name",
            "fieldType": "String",
            "fieldValidateRules": [
                "required",
                "maxlength"
            ],
            "fieldValidateRulesMaxlength": "45"
        },
        {
            "fieldName": "xchangeUser",
            "fieldType": "String",
            "fieldValidateRules": [
                "required",
                "maxlength"
            ],
            "fieldValidateRulesMaxlength": "45"
        },
        {
            "fieldName": "xchangePSW",
            "fieldType": "String",
            "fieldValidateRules": [
                "required",
                "maxlength"
            ],
            "fieldValidateRulesMaxlength": "45"
        }
    ],
    "changelogDate": "20170124212716",
    "dto": "no",
    "service": "no",
    "entityTableName": "gn_client",
    "pagination": "pager"
}

```

Gn_operator.json

```yaml
{
    "fluentMethods": true,
    "relationships": [
        {
            "relationshipName": "gn_supplier",
            "otherEntityName": "gn_supplier",
            "relationshipType": "many-to-one",
            "otherEntityField": "supplierId"
        },
        {
            "relationshipName": "gn_client",
            "otherEntityName": "gn_client",
            "relationshipType": "many-to-one",
            "otherEntityField": "instanceId"
        }
    ],
    "fields": [
        {
            "fieldName": "supplierId",
            "fieldType": "String",
            "fieldValidateRules": [
                "required",
                "maxlength"
            ],
            "fieldValidateRulesMaxlength": "3"
        },
        {
            "fieldName": "supplierName",
            "fieldType": "String",
            "fieldValidateRules": [
                "required"
            ]
        },
        {
            "fieldName": "enabled",
            "fieldType": "String",
            "fieldValidateRules": [
                "required",
                "maxlength"
            ],
            "fieldValidateRulesMaxlength": "3"
        },
        {
            "fieldName": "instanceId",
            "fieldType": "String",
            "fieldValidateRules": [
                "required",
                "maxlength"
            ],
            "fieldValidateRulesMaxlength": "5"
        },
        {
            "fieldName": "logoRef",
            "fieldType": "String",
            "fieldValidateRules": [
                "maxlength"
            ],
            "fieldValidateRulesMaxlength": "100"
        },
        {
            "fieldName": "logoHyperlinkRef",
            "fieldType": "String",
            "fieldValidateRules": []
        },
        {
            "fieldName": "summary",
            "fieldType": "String",
            "fieldValidateRules": [
                "maxlength"
            ],
            "fieldValidateRulesMaxlength": "75"
        },
        {
            "fieldName": "fullDescription",
            "fieldType": "String"
        },
        {
            "fieldName": "sailingEnquiryInterval",
            "fieldType": "Integer"
        },
        {
            "fieldName": "axessUrl",
            "fieldType": "String",
            "fieldValidateRules": [
                "maxlength"
            ],
            "fieldValidateRulesMaxlength": "100"
        },
        {
            "fieldName": "sailingTimesUpdateDelay",
            "fieldType": "Integer"
        },
        {
            "fieldName": "accountCountry",
            "fieldType": "String",
            "fieldValidateRules": [
                "maxlength"
            ],
            "fieldValidateRulesMaxlength": "2"
        },
        {
            "fieldName": "termsAndConditionsUrl",
            "fieldType": "String"
        },
        {
            "fieldName": "embarkation",
            "fieldType": "String"
        }
    ],
    "changelogDate": "20170127120520",
    "dto": "no",
    "service": "no",
    "entityTableName": "gn_operator",
    "pagination": "pager"
}

```

Gn_supplier.json

```yaml
{
    "fluentMethods": true,
    "relationships": [],
    "fields": [
        {
            "fieldName": "supplierId",
            "fieldType": "String",
            "fieldValidateRules": [
                "required",
                "maxlength"
            ],
            "fieldValidateRulesMaxlength": "3"
        },
        {
            "fieldName": "supplierName",
            "fieldType": "String",
            "fieldValidateRules": [
                "required",
                "maxlength"
            ],
            "fieldValidateRulesMaxlength": "75"
        },
        {
            "fieldName": "flexibilityOfTravelDays",
            "fieldType": "Integer"
        },
        {
            "fieldName": "sailingTimesRequestDays",
            "fieldType": "Integer"
        }
    ],
    "changelogDate": "20170125210300",
    "dto": "no",
    "service": "no",
    "entityTableName": "gn_supplier",
    "pagination": "pager"
}

```

##### **Browsers and Operating System**

java version "1.8.0_121"
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)

git version 2.1.4

node: v5.1.0

npm: 3.3.12

bower: 1.8.0

gulp:
[12:35:09] CLI version 1.2.2
[12:35:09] Local version 3.9.1

yeoman: 1.8.5

yarn: 0.18.1

- [X] Checking this box is mandatory (this is just to show you read everything)

**Comment by jdubois** [comment]
Are you using the "dev" profile or the "prod" profile? How do you start Elasticsearch?

**Comment by jdanosborne** [comment]
dev and I'm not explicitly starting ElasticSearch - is it external to my jhipster app then?

**Comment by jdubois** [comment]
thanks @jdanosborne in that case it's even more simple! You should have an embedded Elasticsearch that starts automatically with your project - do you see this in your logs?
It might not be in sync with your database, that depends on what you did - as you use MySQL in dev, if you did a `mvn clean` you destroyed your Elasticsearch indexes, so it won't be in sync with what you have in MySQL.
So you either need to reindex, or accept that you won't find every data there is in MySQL.
A better solution would be to run an external Elasticsearch instance, so it works the same way as MySQL - and we provide a Docker configuration for Elasticsearch, next to the one for MySQL.
I'm pretty sure this is your issue, so I'm closing this, but don't hesitate to comment.

**Comment by jdanosborne** [comment]
Yes I did an mvn clean a little while ago. There is no reference to Elasticsearch in the logs  that I can see

```
2017-01-28 16:14:46.483 DEBUG 1963 --- [  restartedMain] c.dan.jh.config.MetricsConfiguration  : Monitoring the datasource
2017-01-28 16:14:46.484 DEBUG 1963 --- [  restartedMain] c.dan.jh.config.MetricsConfiguration  : Initializing Metrics JMX reporting
2017-01-28 16:14:47.677  WARN 1963 --- [  restartedMain] io.undertow.websockets.jsr               : UT026009: XNIO worker was not set on WebSocketDeploymentInfo, the default worker will be used
2017-01-28 16:14:47.678  WARN 1963 --- [  restartedMain] io.undertow.websockets.jsr               : UT026010: Buffer pool was not set on WebSocketDeploymentInfo, the default pool will be used
2017-01-28 16:14:48.230  INFO 1963 --- [  restartedMain] com.dan.jh.config.WebConfigurer       : Web application configuration, using profiles: [swagger, dev]
2017-01-28 16:14:48.231 DEBUG 1963 --- [  restartedMain] com.dan.jh.config.WebConfigurer       : Initializing Metrics registries
2017-01-28 16:14:48.235 DEBUG 1963 --- [  restartedMain] com.dan.jh.config.WebConfigurer       : Registering Metrics Filter
2017-01-28 16:14:48.236 DEBUG 1963 --- [  restartedMain] com.dan.jh.config.WebConfigurer       : Registering Metrics Servlet
2017-01-28 16:14:48.240  INFO 1963 --- [  restartedMain] com.dan.jh.config.WebConfigurer       : Web application fully configured
2017-01-28 16:14:48.591 DEBUG 1963 --- [  restartedMain] c.p.jh.config.DatabaseConfiguration      : Configuring Liquibase
2017-01-28 16:14:48.631  WARN 1963 --- [  jh-Executor-1] c.p.j.c.liquibase.AsyncSpringLiquibase   : Starting Liquibase asynchronously, your database might not be ready at startup!
2017-01-28 16:14:52.486 DEBUG 1963 --- [  jh-Executor-1] c.p.j.c.liquibase.AsyncSpringLiquibase   : Started Liquibase in 3853 ms
2017-01-28 16:14:53.048  INFO 1963 --- [  restartedMain] com.dan.jh.JhApp                      : Running with Spring profile(s) : [swagger, dev]
2017-01-28 16:14:53.068 DEBUG 1963 --- [  restartedMain] com.dan.jh.config.CacheConfiguration  : No cache
2017-01-28 16:15:07.333 DEBUG 1963 --- [  restartedMain] c.p.j.c.apidoc.SwaggerConfiguration      : Starting Swagger
2017-01-28 16:15:07.345 DEBUG 1963 --- [  restartedMain] c.p.j.c.apidoc.SwaggerConfiguration      : Started Swagger in 12 ms
2017-01-28 16:15:09.655  INFO 1963 --- [  restartedMain] com.dan.jh.JhApp                      : Started JhApp in 32.93 seconds (JVM running for 34.016)
2017-01-28 16:15:09.656  INFO 1963 --- [  restartedMain] com.dan.jh.JhApp                      : 
----------------------------------------------------------
    Application 'jh' is running! Access URLs:
    Local:      http://localhost:8080
    External:   http://127.0.1.1:8080
----------------------------------------------------------
```

I'll investigate an external Elasticsearch.

Many thanks!

**Comment by jdubois** [comment]
@jdanosborne in the admin menu, have a look at the "health" page, it should tell you if Elasticsearch is running

**Comment by jdanosborne** [comment]
Yes, says Status is UP. And there is data in target/elasticsearch/data but not target/elasticsearch/log

I tried setting elasticsearch/properties/http/enabled: true in application-dev.yml but had no effect - maybe that is for something else?

**Comment by jdubois** [comment]
If you did a `mvn clean` then you deleted everything, so you need to recreate your data - if you edit an entity, if should be saved again, maybe you could try this? Then there is a "reindexer" module, but I have never used it.

**Comment by ruddell** [comment]
If you need the information from your database back in embedded elasticsearch (which is cleared on `mvn clean`), use the [jhipster-elasticsearch-reindexer](https://www.npmjs.com/package/generator-jhipster-elasticsearch-reindexer).

Note that in production, the default configuration is to use an external elasticsearch [[docs](https://jhipster.github.io/using-elasticsearch/)].

**Comment by jdanosborne** [comment]
I had previously used option --regenerate for each entity. Now tried editing one by adding a column but same result.

I then installed that reindexer and that did the trick :)

Thanks!

**Comment by jdubois** [comment]
Oh the reindexer works? Good news!
