### ISSUE TITLE
Installation is failing with the below error

### ISSUE THREAD

**Issue by pankajppr** [jhipster/generator-jhipster#5011]
Installation is faliling giving the following error. 

Welcome to the JHipster Generator v3.12.2
Documentation for creating an application: https://jhipster.github.io/creating-an-app/
Application files will be generated in folder: C:\Users\panka\workspace\Hipster\generator-jhipster
WARNING! git is not found on your computer.

? (1/15) Which *type* of application would you like to create? Monolithic application (recommended for simple projects)
? (2/15) Which *Framework* would you like to use for the client? [BETA] Angular 2.x
? (3/15) What is the base name of your application? jhipster
? (4/15) Would you like to install other generators from the JHipster Marketplace? No
? (5/15) What is your default Java package name? com.testhip
? (6/15) Which *type* of authentication would you like to use? OAuth2 Authentication (stateless, with an OAuth2 server implementation)
? (7/15) Which *type* of database would you like to use? SQL (H2, MySQL, MariaDB, PostgreSQL, Oracle)
? (8/15) Which *production* database would you like to use? MySQL
? (9/15) Which *development* database would you like to use? MySQL
? (10/15) Do you want to use Hibernate 2nd level cache? Yes, with ehcache (local cache, for a single node)
? (11/15) Would you like to use Maven or Gradle for building the backend? Maven
? (12/15) Which other technologies would you like to use? (Press <space> to select, <a> to toggle all, <i> to inverse selection)
? (13/15) Would you like to use the LibSass stylesheet preprocessor for your CSS? No
? (14/15) Would you like to enable internationalization support? No
? (15/15) Besides JUnit and Karma, which testing frameworks would you like to use? (Press <space> to select, <a> to toggle all, <i> to inverse selection)
events.js:141
      throw er; // Unhandled 'error' event
      ^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode in C:\Users\panka\workspace\Hipster\generator-jhipster\generators\server\templates\_README.md while compiling ejs
    at Function (native)
    at Object.Template.compile (C:\Users\panka\workspace\Hipster\generator-jhipster\node_modules\ejs\lib\ejs.js:495:12)
    at Object.compile (C:\Users\panka\workspace\Hipster\generator-jhipster\node_modules\ejs\lib\ejs.js:306:16)
    at handleCache (C:\Users\panka\workspace\Hipster\generator-jhipster\node_modules\ejs\lib\ejs.js:169:18)
    at Object.exports.render (C:\Users\panka\workspace\Hipster\generator-jhipster\node_modules\ejs\lib\ejs.js:332:10)
    at copy.extend.process (C:\Users\panka\workspace\Hipster\generator-jhipster\node_modules\mem-fs-editor\lib\actions\copy-tpl.js:12:18)
    at applyProcessingFunc (C:\Users\panka\workspace\Hipster\generator-jhipster\node_modules\mem-fs-editor\lib\actions\copy.js:13:16)
    at EditionInterface.exports._copySingle (C:\Users\panka\workspace\Hipster\generator-jhipster\node_modules\mem-fs-editor\lib\actions\copy.js:51:16)
    at EditionInterface.exports.copy (C:\Users\panka\workspace\Hipster\generator-jhipster\node_modules\mem-fs-editor\lib\actions\copy.js:23:17)
    at EditionInterface.module.exports [as copyTpl] (C:\Users\panka\workspace\Hipster\generator-jhipster\node_modules\mem-fs-editor\lib\actions\copy-tpl.js:10:8)

Please sugguest.

**Comment by jdubois** [comment]
This ticket has been closed as the guidelines are not followed.

Tickets must follow our [Guidelines](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md#submitting-an-issue), as mentioned in:

1. our [Readme file on the front page of the project](https://github.com/jhipster/generator-jhipster/blob/master/README.md), 
2. the ["create a new ticket" page](https://github.com/jhipster/generator-jhipster/issues/new) and
3. our [Help page](http://jhipster.github.io/help/)

We have also created a template on the ["create a new ticket" page](https://github.com/jhipster/generator-jhipster/issues/new) to help you follow those guidelines.
