### ISSUE TITLE
Installation is failing with the SyntaxError: Block-scoped declarations error

### ISSUE THREAD

**Issue by pankajppr** [jhipster/generator-jhipster#5013]
- Please follow the issue template below for bug reports and feature requests.
- Tickets opened without any of these informations will be **closed** without any explanation.

##### **Overview of the issue**

Installation is faliling giving the following error. 

? (14/15) Would you like to enable internationalization support? No
? (15/15) Besides JUnit and Karma, which testing frameworks would you like to use? (Press <space> to select, <a> to toggle all, <i> to inverse selection)
events.js:141
      throw er; // Unhandled 'error' event
      ^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode in C:\Users\panka\workspace\Hipster\generator-jhipster\generators\server\templates\_README.md while compiling ejs
    at Function (native)
    at Object.Template.compile (C:\Users\panka\workspace\Hipster\generator-jhipster\node_modules\ejs\lib\ejs.js:495:12)
    at Object.compile (C:\Users\panka\workspace\Hipster\generator-jhipster\node_modules\ejs\lib\ejs.js:306:16)
    at handleCache (C:\Users\panka\workspace\Hipster\generator-jhipster\node_modules\ejs\lib\ejs.js:169:18)
    at Object.exports.render (C:\Users\panka\workspace\Hipster\generator-jhipster\node_modules\ejs\lib\ejs.js:332:10)
    at copy.extend.process (C:\Users\panka\workspace\Hipster\generator-jhipster\node_modules\mem-fs-editor\lib\actions\copy-tpl.js:12:18)
    at applyProcessingFunc (C:\Users\panka\workspace\Hipster\generator-jhipster\node_modules\mem-fs-editor\lib\actions\copy.js:13:16)
    at EditionInterface.exports._copySingle (C:\Users\panka\workspace\Hipster\generator-jhipster\node_modules\mem-fs-editor\lib\actions\copy.js:51:16)
    at EditionInterface.exports.copy (C:\Users\panka\workspace\Hipster\generator-jhipster\node_modules\mem-fs-editor\lib\actions\copy.js:23:17)
    at EditionInterface.module.exports [as copyTpl] (C:\Users\panka\workspace\Hipster\generator-jhipster\node_modules\mem-fs-editor\lib\actions\copy-tpl.js:10:8)

##### **Related issues**

No

##### **JHipster configuration**

C:\Users\panka\workspace\Hipster\generator-jhipster>yo jhipster:info
Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
generator-jhipster@3.12.2 C:\Users\panka\workspace\Hipster\generator-jhipster
`-- generator-jhipster@3.12.2  -> C:\Users\panka\workspace\Hipster\generator-jhipster extraneous

```

cat: no such file or directory: .yo-rc.json

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

```yaml

```

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

ls: no such file or directory: .jhipster/*.json

##### **Browsers and Operating System**

java version "1.8.0_111"
Java(TM) SE Runtime Environment (build 1.8.0_111-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.111-b14, mixed mode)

node: v4.4.7

npm: 4.1.2

bower: 1.8.0

gulp:
[22:23:43] CLI version 1.2.2

yeoman: 1.8.5

yarn: 0.19.1

##### **Browsers and Operating System**

Windows 10
- [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by jdubois** [comment]
This ticket has been closed as the guidelines are not followed.

Tickets must follow our [Guidelines](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md#submitting-an-issue), as mentioned in:

1. our [Readme file on the front page of the project](https://github.com/jhipster/generator-jhipster/blob/master/README.md), 
2. the ["create a new ticket" page](https://github.com/jhipster/generator-jhipster/issues/new) and
3. our [Help page](http://jhipster.github.io/help/)

We have also created a template on the ["create a new ticket" page](https://github.com/jhipster/generator-jhipster/issues/new) to help you follow those guidelines.

**Comment by deepu105** [comment]
@pankajppr I think you are on an older nodeJS version. Please try again with the latest nodeJS LTS version (6.9.2 I guess)

**Comment by pankajppr** [comment]
@deepu105  Thanks . it worked.

**Comment by gmarziou** [comment]
We should update node version requirement in generator-jhipster's package.json:

~~~
  "engines": {
    "node": ">=4.4.0",
    "npm": ">=2.14.2"
  },
~~~

**Comment by deepu105** [comment]
yes we should


Thanks & Regards,
Deepu
