### ISSUE TITLE
jhipster-generator heroku

### ISSUE THREAD

**Issue by arnogeismar** [jhipster/generator-jhipster#5098]
Since the commit bellow I am getting a dynoSize is not defined 

Creating Heroku deployment files
events.js:160
      throw er; // Unhandled 'error' event
      ^

ReferenceError: /Users/arnog/Documents/auction/auctioneer-api/node_modules/generator-jhipster/generators/heroku/templates/_Procfile:1
 >> 1| web: java $JAVA_OPTS <% if (applicationType == 'gateway' || dynoSize == 'Free') { %>-Xmx256m<% } %> -jar <% if (buildTool == 'maven') { %>target<% } %><% if (buildTool == 'gradle') { %>build/libs<% } %>/*.war --spring.profiles.active=prod,heroku --server.port=$PORT <% if (prodDatabaseType == 'mongodb') { %>--spring.data.mongodb.database=$(echo "$MONGODB_URI" | sed "s/^.*:[0-9]*\///g")<% } %>
    2| 

dynoSize is not defined
    at eval (eval at compile (/Users/arnog/Documents/auction/auctioneer-api/node_modules/ejs/lib/ejs.js:495:12), <anonymous>:10:44)
    at returnedFn (/Users/arnog/Documents/auction/auctioneer-api/node_modules/ejs/lib/ejs.js:524:17)
    at Object.exports.render (/Users/arnog/Documents/auction/auctioneer-api/node_modules/ejs/lib/ejs.js:332:37)
    at process (/Users/arnog/Documents/auction/auctioneer-api/node_modules/mem-fs-editor/lib/actions/copy-tpl.js:12:18)
    at applyProcessingFunc (/Users/arnog/Documents/auction/auctioneer-api/node_modules/mem-fs-editor/lib/actions/copy.js:13:16)
    at EditionInterface.exports._copySingle (/Users/arnog/Documents/auction/auctioneer-api/node_modules/mem-fs-editor/lib/actions/copy.js:51:16)
    at EditionInterface.exports.copy (/Users/arnog/Documents/auction/auctioneer-api/node_modules/mem-fs-editor/lib/actions/copy.js:23:17)
    at EditionInterface.module.exports [as copyTpl] (/Users/arnog/Documents/auction/auctioneer-api/node_modules/mem-fs-editor/lib/actions/copy-tpl.js:10:8)
    at constructor.template (/Users/arnog/Documents/auction/auctioneer-api/node_modules/yeoman-generator/lib/actions/actions.js:124:11)
    at constructor.copyHerokuFiles (/Users/arnog/Documents/auction/auctioneer-api/node_modules/generator-jhipster/generators/heroku/index.js:287:18)

This commit: 

Better memory defaults for Heroku dynos #5068
Merged	ruddell  merged 1 commit into jhipster:master from jkutner:master a day ago

**Comment by jkutner** [comment]
@arnogeismar can you confirm that my patch in #5106 fixes this? I wasn't able to reproduce but I think I know generally what was causing the problem. And I think i've nipped it. Thanks for reporting!
