### ISSUE TITLE
run jhipster:heroku show error

### ISSUE THREAD

**Issue by huiqiangyang** [jhipster/generator-jhipster#5108]
- OS:ubuntu14
- node: 6.9.5

```
yhq@yhq-Inspiron-5420:~/pro1703/huiblog$ sudo yo jhipster:heroku
[sudo] password for yhq: 
Heroku configuration is starting
? Name to deploy as: huiblog
? On which region do you want to deploy ? us

Initializing Git repository
初始化空的 Git 仓库于 /home/yhq/pro1703/huiblog/.git/


Installing Heroku CLI deployment plugin

Creating Heroku application and setting up node environment
heroku create huiblog
https://huiblog.herokuapp.com/ | https://git.heroku.com/huiblog.git

Provisioning addons
Created heroku-postgresql --as DATABASE

Creating Heroku deployment files
events.js:160
      throw er; // Unhandled 'error' event
      ^

ReferenceError: /home/yhq/pro1703/huiblog/node_modules/generator-jhipster/generators/heroku/templates/_Procfile:1
 >> 1| web: java $JAVA_OPTS <% if (applicationType == 'gateway' || dynoSize == 'Free') { %>-Xmx256m<% } %> -jar <% if (buildTool == 'maven') { %>target<% } %><% if (buildTool == 'gradle') { %>build/libs<% } %>/*.war --spring.profiles.active=prod,heroku --server.port=$PORT <% if (prodDatabaseType == 'mongodb') { %>--spring.data.mongodb.database=$(echo "$MONGODB_URI" | sed "s/^.*:[0-9]*\///g")<% } %>
    2| 

dynoSize is not defined
    at eval (eval at compile (/home/yhq/pro1703/huiblog/node_modules/ejs/lib/ejs.js:481:12), <anonymous>:10:44)
    at returnedFn (/home/yhq/pro1703/huiblog/node_modules/ejs/lib/ejs.js:512:17)
    at Object.exports.render (/home/yhq/pro1703/huiblog/node_modules/ejs/lib/ejs.js:316:37)
    at process (/home/yhq/pro1703/huiblog/node_modules/mem-fs-editor/lib/actions/copy-tpl.js:12:18)
    at applyProcessingFunc (/home/yhq/pro1703/huiblog/node_modules/mem-fs-editor/lib/actions/copy.js:13:16)
    at EditionInterface.exports._copySingle (/home/yhq/pro1703/huiblog/node_modules/mem-fs-editor/lib/actions/copy.js:51:16)
    at EditionInterface.exports.copy (/home/yhq/pro1703/huiblog/node_modules/mem-fs-editor/lib/actions/copy.js:23:17)
    at EditionInterface.module.exports [as copyTpl] (/home/yhq/pro1703/huiblog/node_modules/mem-fs-editor/lib/actions/copy-tpl.js:10:8)
    at constructor.template (/home/yhq/pro1703/huiblog/node_modules/yeoman-generator/lib/actions/actions.js:124:11)
    at constructor.copyHerokuFiles (/home/yhq/pro1703/huiblog/node_modules/generator-jhipster/generators/heroku/index.js:287:18)

```

**Comment by jdubois** [comment]
Duplicate #5098
Please follow the guidelines!
