### ISSUE TITLE
useSass option breaks the webpack build

### ISSUE THREAD

**Issue by romaindequidt** [jhipster/generator-jhipster#5165]
##### **Overview of the issue**

useSass option breaks the webpack build with the following error:

> ERROR in ./~/css-loader!./~/postcss-loader!./~/sass-loader!./src/main/webapp/content/scss/vendor.scss
> Module build failed: Error: ENOENT: no such file or directory, scandir '/home/user/jhipster/node_modules/node-sass/vendor'
>     at Error (native)
>     at Object.fs.readdirSync (fs.js:951:18)
>     at Object.getInstalledBinaries (/home/user/jhipster/node_modules/node-sass/lib/extensions.js:121:13)
>     at foundBinariesList (/home/user/jhipster/node_modules/node-sass/lib/errors.js:20:15)
>     at foundBinaries (/home/user/jhipster/node_modules/node-sass/lib/errors.js:15:5)
>     at Object.module.exports.missingBinary (/home/user/jhipster/node_modules/node-sass/lib/errors.js:45:5)
>     at module.exports (/home/user/jhipster/node_modules/node-sass/lib/binding.js:15:30)
>     at Object.<anonymous> (/home/user/jhipster/node_modules/node-sass/lib/index.js:14:35)
>     at Module._compile (module.js:570:32)
>     at Object.Module._extensions..js (module.js:579:10)
>     at Module.load (module.js:487:32)
>     at tryModuleLoad (module.js:446:12)
>     at Function.Module._load (module.js:438:3)
>     at Module.require (module.js:497:17)
>     at require (internal/module.js:20:19)
>     at Object.<anonymous> (/home/user/jhipster/node_modules/sass-loader/index.js:4:12)
>     at Module._compile (module.js:570:32)
>     at Object.Module._extensions..js (module.js:579:10)
>     at Module.load (module.js:487:32)
>     at tryModuleLoad (module.js:446:12)
>     at Function.Module._load (module.js:438:3)
>     at Module.require (module.js:497:17)
>     at require (internal/module.js:20:19)
>     at loadLoader (/home/user/jhipster/node_modules/loader-runner/lib/loadLoader.js:13:17)
>     at iteratePitchingLoaders (/home/user/jhipster/node_modules/loader-runner/lib/LoaderRunner.js:169:2)
>     at iteratePitchingLoaders (/home/user/jhipster/node_modules/loader-runner/lib/LoaderRunner.js:165:10)
>     at /home/user/jhipster/node_modules/loader-runner/lib/LoaderRunner.js:173:18
>     at loadLoader (/home/user/jhipster/node_modules/loader-runner/lib/loadLoader.js:36:3)
>     at iteratePitchingLoaders (/home/user/jhipster/node_modules/loader-runner/lib/LoaderRunner.js:169:2)
>     at iteratePitchingLoaders (/home/user/jhipster/node_modules/loader-runner/lib/LoaderRunner.js:165:10)
>  @ ./src/main/webapp/content/scss/vendor.scss 4:14-195
>  @ ./src/main/webapp/app/vendor.ts
>  @ dll vendor
> error Command failed with exit code 2.
> info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
> error Command failed with exit code 1.
> info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

##### **Reproduce the error**

$ yo jhipster
with the following .yo-rc.json

##### **JHipster Version(s)**

commit 39d32d3248cfa95760213a32cfb53287458be9a0

##### **JHipster configuration**

.yo-rc.json:

> {
>   "generator-jhipster": {
>     "jhipsterVersion": "4.0.2",
>     "baseName": "jhipster",
>     "packageName": "com.mycompany.myapp",
>     "packageFolder": "com/mycompany/myapp",
>     "serverPort": "8080",
>     "authenticationType": "session",
>     "hibernateCache": "ehcache",
>     "clusteredHttpSession": false,
>     "websocket": "spring-websocket",
>     "databaseType": "sql",
>     "devDatabaseType": "h2Disk",
>     "prodDatabaseType": "postgresql",
>     "searchEngine": false,
>     "messageBroker": false,
>     "serviceDiscoveryType": false,
>     "buildTool": "maven",
>     "enableSocialSignIn": false,
>     "rememberMeKey": "*****************",
>     "useSass": true,
>     "clientPackageManager": "yarn",
>     "applicationType": "monolith",
>     "clientFramework": "angular2",
>     "testFrameworks": [],
>     "jhiPrefix": "jhi",
>     "enableTranslation": true,
>     "nativeLanguage": "en",
>     "languages": [
>       "en",
>       "fr",
>       "de",
>       "it",
>       "es"
>     ]
>   }
> }
> 

- [X] Checking this box is mandatory (this is just to show you read everything)

**Comment by romaindequidt** [comment]
Actually, I got another error during generation time so I don't know if the problem really come from there. I'll retry en re-open issue if necessary
