### ISSUE TITLE
Commons VFS stack trace when running Mongobee in JAR

### ISSUE THREAD

**Issue by mraible** [jhipster/generator-jhipster#5171]
##### **Overview of the issue**

This doesn't seem to stop the application from working, but it does look like something is wrong. There's a stack trace on startup when using MonboDB.

```
2017-02-11 17:16:05.091  WARN 51969 --- [           main] org.reflections.Reflections              : could not create Dir using commons_vfs2 from url file:/Users/mraible/dev/jhipster-k8/cms/target/cms-0.0.1-SNAPSHOT.war. skipping.

java.lang.NoClassDefFoundError: org/apache/commons/vfs2/VFS
	at org.reflections.vfs.Vfs$DefaultUrlTypes$7.matches(Vfs.java:281)
	at org.reflections.vfs.Vfs.fromURL(Vfs.java:97)
	at org.reflections.vfs.Vfs.fromURL(Vfs.java:90)
	at org.reflections.Reflections.scan(Reflections.java:236)
	at org.reflections.Reflections.scan(Reflections.java:203)
	at org.reflections.Reflections.<init>(Reflections.java:128)
	at org.reflections.Reflections.<init>(Reflections.java:169)
	at org.reflections.Reflections.<init>(Reflections.java:142)
	at com.github.mongobee.utils.ChangeService.fetchChangeLogs(ChangeService.java:43)
	at com.github.mongobee.Mongobee.execute(Mongobee.java:142)
	at com.github.mongobee.Mongobee.afterPropertiesSet(Mongobee.java:117)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1687)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1624)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:555)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:483)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:761)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:866)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:542)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:762)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:372)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:316)
	at org.jhipster.cms.CmsApp.main(CmsApp.java:67)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
	at org.springframework.boot.loader.WarLauncher.main(WarLauncher.java:59)
Caused by: java.lang.ClassNotFoundException: org.apache.commons.vfs2.VFS
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:94)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 35 common frames omitted

2017-02-11 17:16:05.092  WARN 51969 --- [           main] org.reflections.Reflections              : could not create Vfs.Dir from url. ignoring the exception and continuing

org.reflections.ReflectionsException: could not create Vfs.Dir from url, no matching UrlType was found [file:/Users/mraible/dev/jhipster-k8/cms/target/cms-0.0.1-SNAPSHOT.war]
either use fromURL(final URL url, final List<UrlType> urlTypes) or use the static setDefaultURLTypes(final List<UrlType> urlTypes) or addDefaultURLTypes(UrlType urlType) with your specialized UrlType.
	at org.reflections.vfs.Vfs.fromURL(Vfs.java:108)
	at org.reflections.vfs.Vfs.fromURL(Vfs.java:90)
	at org.reflections.Reflections.scan(Reflections.java:236)
	at org.reflections.Reflections.scan(Reflections.java:203)
	at org.reflections.Reflections.<init>(Reflections.java:128)
	at org.reflections.Reflections.<init>(Reflections.java:169)
	at org.reflections.Reflections.<init>(Reflections.java:142)
	at com.github.mongobee.utils.ChangeService.fetchChangeLogs(ChangeService.java:43)
	at com.github.mongobee.Mongobee.execute(Mongobee.java:142)
	at com.github.mongobee.Mongobee.afterPropertiesSet(Mongobee.java:117)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1687)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1624)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:555)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:483)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:761)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:866)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:542)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:762)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:372)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:316)
	at org.jhipster.cms.CmsApp.main(CmsApp.java:67)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
	at org.springframework.boot.loader.WarLauncher.main(WarLauncher.java:59)

2017-02-11 17:16:05.479  INFO 51969 --- [           main] org.reflections.Reflections              : Reflections took 637 ms to scan 208 urls, producing 0 keys and 0 values
```

##### **Motivation for or Use Case**

Startup should be smooth w/o any stack traces.

##### **Reproduce the error**

1. Create an app with MongoDB.
2. Package the app with the prod profile. For example, `mvn package -Pprod`.
3. Run the app using `java -jar target/app.war`.

##### **JHipster Version(s)**

```
/Users/mraible/dev/jhipster-k8/cms
└── generator-jhipster@4.0.2

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

```yaml
{
  "generator-jhipster": {
    "jhipsterVersion": "4.0.2",
    "baseName": "cms",
    "packageName": "org.jhipster.cms",
    "packageFolder": "org/jhipster/cms",
    "serverPort": "8082",
    "authenticationType": "jwt",
    "hibernateCache": "no",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "mongodb",
    "devDatabaseType": "mongodb",
    "prodDatabaseType": "mongodb",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": "eureka",
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "jwtSecretKey": "7e097f603f9fc473d1fd4c997f6c1758be3cdd1a",
    "enableTranslation": true,
    "applicationType": "microservice",
    "testFrameworks": [
      "gatling"
    ],
    "jhiPrefix": "jhi",
    "skipClient": true,
    "skipUserManagement": true,
    "nativeLanguage": "en",
    "languages": [
      "en",
      "sv"
    ],
    "clientPackageManager": "yarn"
  }
}
```

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

Article.json

```yaml
{
    "fluentMethods": true,
    "relationships": [],
    "fields": [
        {
            "fieldName": "title",
            "fieldType": "String",
            "fieldValidateRules": [
                "required",
                "minlength"
            ],
            "fieldValidateRulesMinlength": "5"
        },
        {
            "fieldName": "author",
            "fieldType": "String",
            "fieldValidateRules": [
                "required"
            ]
        },
        {
            "fieldName": "content",
            "fieldType": "byte[]",
            "fieldTypeBlobContent": "text",
            "fieldValidateRules": [
                "required"
            ]
        }
    ],
    "dto": "no",
    "service": "no",
    "entityTableName": "article",
    "pagination": "pagination",
    "microserviceName": "cms",
    "searchEngine": false
}

```

##### **Browsers and Operating System**

java version "1.8.0_112"
Java(TM) SE Runtime Environment (build 1.8.0_112-b16)
Java HotSpot(TM) 64-Bit Server VM (build 25.112-b16, mixed mode)

git version 2.10.2

node: v6.9.5

npm: 3.10.10

yeoman: 1.8.5

yarn: 0.19.1

Docker version 1.13.0, build 49bf474

docker-compose version 1.10.0, build 4bd6f1a

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by mraible** [comment]
Maybe this is caused by the following line in `DatabaseConfiguration.java`? 

```java
// package to scan for migrations
mongobee.setChangeLogsScanPackage("org.jhipster.cms.config.dbmigrations");
```

This package doesn't exist in my project.

**Comment by jdubois** [comment]
You should have the package, that's how MongoBee populates the database.
Then, for a microservice that shouldn't be a big issue as the MongoDB collections will be created on the fly.

**Comment by jdubois** [comment]
Got it, I'll do a PR tonight.

**Comment by jdubois** [comment]
So the issue is that there is no MongoBee migration on a brand new microservice, as it doesn't have any user management code.
Of course, as soon as you add some entities, this folder will have migrations in it, so that's only very temporary.
I'm doing a PR to remove the warnings.

**Comment by mraible** [comment]
Just in case someone finds this ticket when googling, the stack trace still happens in JHipster 4.3.0:

```
2017-05-02 19:42:06.723  WARN 7 --- [           main] org.reflections.Reflections              : could not create Dir using commons_vfs2 from url file:/app.war. skipping.
2017-05-02T19:42:06.724902694Z 
java.lang.NoClassDefFoundError: org/apache/commons/vfs2/VFS
at org.reflections.vfs.Vfs$DefaultUrlTypes$7.matches(Vfs.java:281)
at org.reflections.vfs.Vfs.fromURL(Vfs.java:97)
at org.reflections.vfs.Vfs.fromURL(Vfs.java:90)
at org.reflections.Reflections.scan(Reflections.java:236)
at org.reflections.Reflections.scan(Reflections.java:203)
at org.reflections.Reflections.<init>(Reflections.java:128)
at org.reflections.Reflections.<init>(Reflections.java:169)
at org.reflections.Reflections.<init>(Reflections.java:142)
at com.github.mongobee.utils.ChangeService.fetchChangeLogs(ChangeService.java:43)
at com.github.mongobee.Mongobee.executeMigration(Mongobee.java:166)
at com.github.mongobee.Mongobee.execute(Mongobee.java:153)
at com.github.mongobee.Mongobee.afterPropertiesSet(Mongobee.java:123)
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1687)
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1624)
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:555)
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:483)
at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:761)
at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:866)
at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:542)
at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122)
at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:737)
at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:370)
at org.springframework.boot.SpringApplication.run(SpringApplication.java:314)
at org.jhipster.store.StoreApp.main(StoreApp.java:68)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
at org.springframework.boot.loader.WarLauncher.main(WarLauncher.java:59)
Caused by: java.lang.ClassNotFoundException: org.apache.commons.vfs2.VFS
at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:94)
at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
... 36 common frames omitted
2017-05-02T19:42:06.726899459Z 
2017-05-02 19:42:06.726  WARN 7 --- [           main] org.reflections.Reflections              : could not create Vfs.Dir from url. ignoring the exception and continuing
2017-05-02T19:42:06.728556232Z
```
