### ISSUE TITLE
CloudFoundry Generator doesn't work with MySQL

### ISSUE THREAD

**Issue by mraible** [jhipster/generator-jhipster#5205]
##### **Overview of the issue**

When I try to deploy a JHipster 4 app to Cloud Foundry, it fails.

```
[INFO] --- spring-boot-maven-plugin:1.4.4.RELEASE:repackage (default) @ blog ---

[INFO] ------------------------------------------------------------------------


[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------

[INFO] Total time: 02:07 min

[INFO] Finished at: 2017-02-14T13:06:12-07:00

[INFO] Final Memory: 64M/909M


[INFO] ------------------------------------------------------------------------


   create deploy/cloudfoundry/manifest.yml
   create src/main/resources/config/application-cloudfoundry.yml

Pushing the application to Cloud Foundry
Using manifest file ./deploy/cloudfoundry/manifest.yml


Creating app blogdemo in org jhipster.org / space development as matt@raibledesigns.com...

OK


Creating route blogdemo.cfapps.io...

OK


Binding blogdemo.cfapps.io to blogdemo...

OK


Uploading blogdemo...

Uploading app files from: /var/folders/_g/h5m4s5_50175ntlmwkf0hw9h0000gn/T/unzipped-app187254070

Uploading 1.8M, 354 files


Done uploading

OK

Binding service blogdemo to app blogdemo in org jhipster.org / space development as matt@raibledesigns.com...

OK


Starting app blogdemo in org jhipster.org / space development as matt@raibledesigns.com...

Creating container

Successfully created container

Downloading app package...

Downloaded app package (45.6M)
Staging...

-----> Java Buildpack Version: 03b493f | https://github.com/cloudfoundry/java-buildpack#03b493f

-----> Downloading Open Jdk JRE 1.8.0_121 from https://java-buildpack.cloudfoundry.org/openjdk/trusty/x86_64/openjdk-1.8.0_121.tar.gz (0.5s)

       Expanding Open Jdk JRE to .java-buildpack/open_jdk_jre (1.2s)

-----> Downloading Open JDK Like Memory Calculator 2.0.2_RELEASE from https://java-buildpack.cloudfoundry.org/memory-calculator/trusty/x86_64/memory-calculator-2.0.2_RELEASE.tar.gz (0.0s)

       Memory Settings: -Xss349K -Xmx681574K -XX:MaxMetaspaceSize=104857K -Xms681574K -XX:MetaspaceSize=104857K

-----> Downloading Container Certificate Trust Store 2.0.0_RELEASE from https://java-buildpack.cloudfoundry.org/container-certificate-trust-store/container-certificate-trust-store-2.0.0_RELEASE.jar (0.0s)

       Adding certificates to .java-buildpack/container_certificate_trust_store/truststore.jks (0.8s)

-----> Downloading Container Customizer 1.1.0_RELEASE from https://java-buildpack.cloudfoundry.org/container-customizer/container-customizer-1.1.0_RELEASE.jar (0.0s)

-----> Downloading Postgresql JDBC 9.4.1212 from https://java-buildpack.cloudfoundry.org/postgresql-jdbc/postgresql-jdbc-9.4.1212.jar (0.0s)

-----> Downloading Spring Auto Reconfiguration 1.10.0_RELEASE from https://java-buildpack.cloudfoundry.org/auto-reconfiguration/auto-reconfiguration-1.10.0_RELEASE.jar (0.0s)

Exit status 0
Staging complete

Uploading droplet, build artifacts cache...
Uploading build artifacts cache...
Uploading droplet...

Uploaded build artifacts cache (45.6M)

Uploaded droplet (91.6M)

Uploading complete

Destroying container

Successfully destroyed container



0 of 1 instances running, 1 starting

0 of 1 instances running, 1 starting

0 of 1 instances running, 1 starting

0 of 1 instances running, 1 starting

0 of 1 instances running, 1 starting

0 of 1 instances running, 1 starting

0 of 1 instances running, 1 starting

0 of 1 instances running, 1 starting

0 of 1 instances running, 1 starting

0 of 1 instances running, 1 starting

0 of 1 instances running, 1 crashed

FAILED
Error restarting application: Start unsuccessful

TIP: use 'cf logs blogdemo --recent' for more information

✖ { Error: Command failed: cf push -f ./deploy/cloudfoundry/manifest.yml -p target/*.war

    at ChildProcess.exithandler (child_process.js:206:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
  killed: false,
  code: 1,
  signal: null,
  cmd: 'cf push -f ./deploy/cloudfoundry/manifest.yml -p target/*.war' }

Your app should now be live
After application modification, repackage it with
	./mvnw package -DskipTests=true -B -Pprod
And then re-deploy it with
	cf push -f ./deploy/cloudfoundry/manifest.yml -p target/*.war
```

Cloud Foundry logs:

```
2017-02-14T13:13:11.33-0700 [APP/PROC/WEB/0]OUT         ██╗ ██╗   ██╗ ████████╗ ███████╗   ██████╗ ████████╗ ████████╗ ███████╗
2017-02-14T13:13:11.33-0700 [APP/PROC/WEB/0]OUT         ██║ ██║   ██║ ╚══██╔══╝ ██╔═══██╗ ██╔════╝ ╚══██╔══╝ ██╔═════╝ ██╔═══██╗
2017-02-14T13:13:11.33-0700 [APP/PROC/WEB/0]OUT         ██║ ████████║    ██║    ███████╔╝ ╚█████╗     ██║    ██████╗   ███████╔╝
2017-02-14T13:13:11.33-0700 [APP/PROC/WEB/0]OUT   ██╗   ██║ ██╔═══██║    ██║    ██╔════╝   ╚═══██╗    ██║    ██╔═══╝   ██╔══██║
2017-02-14T13:13:11.33-0700 [APP/PROC/WEB/0]OUT   ╚██████╔╝ ██║   ██║ ████████╗ ██║       ██████╔╝    ██║    ████████╗ ██║  ╚██╗
2017-02-14T13:13:11.33-0700 [APP/PROC/WEB/0]OUT    ╚═════╝  ╚═╝   ╚═╝ ╚═══════╝ ╚═╝       ╚═════╝     ╚═╝    ╚═══════╝ ╚═╝   ╚═╝
2017-02-14T13:13:11.33-0700 [APP/PROC/WEB/0]OUT :: JHipster 🤓  :: Running Spring Boot 1.4.4.RELEASE ::
2017-02-14T13:13:11.33-0700 [APP/PROC/WEB/0]OUT :: http://jhipster.github.io ::
2017-02-14T13:13:11.54-0700 [APP/PROC/WEB/0]OUT 2017-02-14 20:13:11.541  INFO 15 --- [           main] pertySourceApplicationContextInitializer : Adding 'cloud' PropertySource to ApplicationContext
2017-02-14T13:13:11.68-0700 [APP/PROC/WEB/0]OUT 2017-02-14 20:13:11.689  INFO 15 --- [           main] nfigurationApplicationContextInitializer : Adding cloud service auto-reconfiguration to ApplicationContext
2017-02-14T13:13:11.71-0700 [APP/PROC/WEB/0]OUT 2017-02-14 20:13:11.718  INFO 15 --- [           main] org.jhipster.blog.BlogApp                : Starting BlogApp on 0ad4a9d6-b9ed-4580-585e-26402edb83aa with PID 15 (/home/vcap/app/WEB-INF/classes started by vcap in /home/vcap/app)
2017-02-14T13:13:11.71-0700 [APP/PROC/WEB/0]OUT 2017-02-14 20:13:11.718  INFO 15 --- [           main] org.jhipster.blog.BlogApp                : The following profiles are active: prod,cloudfoundry,cloud
2017-02-14T13:13:15.25-0700 [APP/PROC/WEB/0]OUT 2017-02-14 20:13:15.251  INFO 15 --- [           main] urceCloudServiceBeanFactoryPostProcessor : Skipping auto-reconfiguring beans of type javax.sql.DataSource
2017-02-14T13:13:15.25-0700 [APP/PROC/WEB/0]OUT 2017-02-14 20:13:15.252  INFO 15 --- [           main] ongoCloudServiceBeanFactoryPostProcessor : Skipping auto-reconfiguring beans of type org.springframework.data.mongodb.MongoDbFactory
2017-02-14T13:13:15.25-0700 [APP/PROC/WEB/0]OUT 2017-02-14 20:13:15.252  INFO 15 --- [           main] bbitCloudServiceBeanFactoryPostProcessor : Skipping auto-reconfiguring beans of type org.springframework.amqp.rabbit.connection.ConnectionFactory
2017-02-14T13:13:15.25-0700 [APP/PROC/WEB/0]OUT 2017-02-14 20:13:15.252  INFO 15 --- [           main] edisCloudServiceBeanFactoryPostProcessor : Skipping auto-reconfiguring beans of type org.springframework.data.redis.connection.RedisConnectionFactory
2017-02-14T13:13:17.41-0700 [APP/PROC/WEB/0]OUT 2017-02-14 20:13:17.411  WARN 15 --- [           main] inkingEmbeddedServletContainerCustomizer : This is not a Tomcat container. Symbolically linked files will not be enabled for this application.
2017-02-14T13:13:18.25-0700 [APP/PROC/WEB/0]OUT 2017-02-14 20:13:18.250  INFO 15 --- [           main] org.jhipster.blog.config.WebConfigurer   : Web application configuration, using profiles: prod
2017-02-14T13:13:18.26-0700 [APP/PROC/WEB/0]OUT 2017-02-14 20:13:18.260  INFO 15 --- [           main] org.jhipster.blog.config.WebConfigurer   : Web application fully configured
2017-02-14T13:13:18.68-0700 [APP/PROC/WEB/0]OUT 2017-02-14 20:13:18.683  INFO 15 --- [           main] o.j.b.config.CloudDatabaseConfiguration  : Configuring JDBC datasource from a cloud provider
2017-02-14T13:13:19.90-0700 [APP/PROC/WEB/0]OUT 2017-02-14 20:13:19.908 DEBUG 15 --- [           main] i.g.j.c.liquibase.AsyncSpringLiquibase   : Starting Liquibase synchronously
2017-02-14T13:13:19.91-0700 [APP/PROC/WEB/0]OUT 2017-02-14 20:13:19.913  WARN 15 --- [           main] o.a.tomcat.jdbc.pool.ConnectionPool      : maxIdle is larger than maxActive, setting maxIdle to: 4
2017-02-14T13:13:21.48-0700 [APP/PROC/WEB/0]OUT 2017-02-14 20:13:21.485 ERROR 15 --- [           main] liquibase                                : classpath:config/liquibase/master.xml: classpath:config/liquibase/changelog/00000000000000_initial_schema.xml::00000000000001::jhipster: Change Set classpath:config/liquibase/changelog/00000000000000_initial_schema.xml::00000000000001::jhipster failed.  Error: ERROR: syntax error at or near "$"
2017-02-14T13:13:21.48-0700 [APP/PROC/WEB/0]OUT   Position: 382 [Failed SQL: CREATE TABLE public.jhi_user (id BIGSERIAL NOT NULL, login VARCHAR(50) NOT NULL, password_hash VARCHAR(60), first_name VARCHAR(50), last_name VARCHAR(50), email VARCHAR(100), image_url VARCHAR(256), activated BOOLEAN NOT NULL, lang_key VARCHAR(5), activation_key VARCHAR(20), reset_key VARCHAR(20), created_by VARCHAR(50) NOT NULL, created_date TIMESTAMP WITHOUT TIME ZONE DEFAULT ${now} NOT NULL, reset_date TIMESTAMP WITHOUT TIME ZONE, last_modified_by VARCHAR(50), last_modified_date TIMESTAMP WITHOUT TIME ZONE, CONSTRAINT PK_JHI_USER PRIMARY KEY (id), UNIQUE (email), UNIQUE (login))]
2017-02-14T13:13:21.49-0700 [APP/PROC/WEB/0]OUT 2017-02-14 20:13:21.497  WARN 15 --- [           main] ationConfigEmbeddedWebApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'liquibase' defined in class path resource [org/jhipster/blog/config/DatabaseConfiguration.class]: Invocation of init method failed; nested exception is liquibase.exception.MigrationFailedException: Migration failed for change set classpath:config/liquibase/changelog/00000000000000_initial_schema.xml::00000000000001::jhipster:
2017-02-14T13:13:21.49-0700 [APP/PROC/WEB/0]OUT      Reason: liquibase.exception.DatabaseException: ERROR: syntax error at or near "$"
2017-02-14T13:13:21.49-0700 [APP/PROC/WEB/0]OUT   Position: 382 [Failed SQL: CREATE TABLE public.jhi_user (id BIGSERIAL NOT NULL, login VARCHAR(50) NOT NULL, password_hash VARCHAR(60), first_name VARCHAR(50), last_name VARCHAR(50), email VARCHAR(100), image_url VARCHAR(256), activated BOOLEAN NOT NULL, lang_key VARCHAR(5), activation_key VARCHAR(20), reset_key VARCHAR(20), created_by VARCHAR(50) NOT NULL, created_date TIMESTAMP WITHOUT TIME ZONE DEFAULT ${now} NOT NULL, reset_date TIMESTAMP WITHOUT TIME ZONE, last_modified_by VARCHAR(50), last_modified_date TIMESTAMP WITHOUT TIME ZONE, CONSTRAINT PK_JHI_USER PRIMARY KEY (id), UNIQUE (email), UNIQUE (login))]
2017-02-14T13:13:21.50-0700 [APP/PROC/WEB/0]OUT 2017-02-14 20:13:21.506  WARN 15 --- [           main] o.s.boot.SpringApplication               : Error handling failed (Error creating bean with name 'delegatingApplicationListener' defined in class path resource [org/springframework/security/config/annotation/web/configuration/WebSecurityConfiguration.class]: BeanPostProcessor before instantiation of bean failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.cache.annotation.ProxyCachingConfiguration': Initialization of bean failed; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No bean named 'org.springframework.context.annotation.ConfigurationClassPostProcessor.importRegistry' available)
2017-02-14T13:13:21.51-0700 [APP/PROC/WEB/0]OUT 2017-02-14 20:13:21.513 ERROR 15 --- [           main] o.s.boot.SpringApplication               : Application startup failed
2017-02-14T13:13:21.51-0700 [APP/PROC/WEB/0]OUT org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'liquibase' defined in class path resource [org/jhipster/blog/config/DatabaseConfiguration.class]: Invocation of init method failed; nested exception is liquibase.exception.MigrationFailedException: Migration failed for change set classpath:config/liquibase/changelog/00000000000000_initial_schema.xml::00000000000001::jhipster:
2017-02-14T13:13:21.51-0700 [APP/PROC/WEB/0]OUT   Position: 382 [Failed SQL: CREATE TABLE public.jhi_user (id BIGSERIAL NOT NULL, login VARCHAR(50) NOT NULL, password_hash VARCHAR(60), first_name VARCHAR(50), last_name VARCHAR(50), email VARCHAR(100), image_url VARCHAR(256), activated BOOLEAN NOT NULL, lang_key VARCHAR(5), activation_key VARCHAR(20), reset_key VARCHAR(20), created_by VARCHAR(50) NOT NULL, created_date TIMESTAMP WITHOUT TIME ZONE DEFAULT ${now} NOT NULL, reset_date TIMESTAMP WITHOUT TIME ZONE, last_modified_by VARCHAR(50), last_modified_date TIMESTAMP WITHOUT TIME ZONE, CONSTRAINT PK_JHI_USER PRIMARY KEY (id), UNIQUE (email), UNIQUE (login))]
2017-02-14T13:13:21.51-0700 [APP/PROC/WEB/0]OUT 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1628)
2017-02-14T13:13:21.51-0700 [APP/PROC/WEB/0]OUT 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:555)
2017-02-14T13:13:21.51-0700 [APP/PROC/WEB/0]OUT 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:483)
2017-02-14T13:13:21.51-0700 [APP/PROC/WEB/0]OUT 	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
2017-02-14T13:13:21.51-0700 [APP/PROC/WEB/0]OUT 	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:296)
2017-02-14T13:13:21.51-0700 [APP/PROC/WEB/0]OUT 	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:762)
2017-02-14T13:13:21.51-0700 [APP/PROC/WEB/0]OUT 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:316)
2017-02-14T13:13:21.51-0700 [APP/PROC/WEB/0]OUT      Reason: liquibase.exception.DatabaseException: ERROR: syntax error at or near "$"
2017-02-14T13:13:21.51-0700 [APP/PROC/WEB/0]OUT 	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
2017-02-14T13:13:21.51-0700 [APP/PROC/WEB/0]OUT 	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
2017-02-14T13:13:21.51-0700 [APP/PROC/WEB/0]OUT 	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
2017-02-14T13:13:21.51-0700 [APP/PROC/WEB/0]OUT 	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
2017-02-14T13:13:21.51-0700 [APP/PROC/WEB/0]OUT 	at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1081)
2017-02-14T13:13:21.51-0700 [APP/PROC/WEB/0]OUT 	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:856)
2017-02-14T13:13:21.51-0700 [APP/PROC/WEB/0]OUT 	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:542)
2017-02-14T13:13:21.51-0700 [APP/PROC/WEB/0]OUT 	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122)
2017-02-14T13:13:21.51-0700 [APP/PROC/WEB/0]OUT 	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:372)
2017-02-14T13:13:21.51-0700 [APP/PROC/WEB/0]OUT 	at org.jhipster.blog.BlogApp.main(BlogApp.java:65)
2017-02-14T13:13:21.51-0700 [APP/PROC/WEB/0]OUT 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2017-02-14T13:13:21.51-0700 [APP/PROC/WEB/0]OUT 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2017-02-14T13:13:21.51-0700 [APP/PROC/WEB/0]OUT 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2017-02-14T13:13:21.51-0700 [APP/PROC/WEB/0]OUT 	at java.lang.reflect.Method.invoke(Method.java:498)
2017-02-14T13:13:21.51-0700 [APP/PROC/WEB/0]OUT 	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
2017-02-14T13:13:21.51-0700 [APP/PROC/WEB/0]OUT 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
2017-02-14T13:13:21.51-0700 [APP/PROC/WEB/0]OUT 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
2017-02-14T13:13:21.51-0700 [APP/PROC/WEB/0]OUT 	at org.springframework.boot.loader.WarLauncher.main(WarLauncher.java:59)
2017-02-14T13:13:21.51-0700 [APP/PROC/WEB/0]OUT Caused by: liquibase.exception.MigrationFailedException: Migration failed for change set classpath:config/liquibase/changelog/00000000000000_initial_schema.xml::00000000000001::jhipster:
2017-02-14T13:13:21.51-0700 [APP/PROC/WEB/0]OUT      Reason: liquibase.exception.DatabaseException: ERROR: syntax error at or near "$"
2017-02-14T13:13:21.51-0700 [APP/PROC/WEB/0]OUT   Position: 382 [Failed SQL: CREATE TABLE public.jhi_user (id BIGSERIAL NOT NULL, login VARCHAR(50) NOT NULL, password_hash VARCHAR(60), first_name VARCHAR(50), last_name VARCHAR(50), email VARCHAR(100), image_url VARCHAR(256), activated BOOLEAN NOT NULL, lang_key VARCHAR(5), activation_key VARCHAR(20), reset_key VARCHAR(20), created_by VARCHAR(50) NOT NULL, created_date TIMESTAMP WITHOUT TIME ZONE DEFAULT ${now} NOT NULL, reset_date TIMESTAMP WITHOUT TIME ZONE, last_modified_by VARCHAR(50), last_modified_date TIMESTAMP WITHOUT TIME ZONE, CONSTRAINT PK_JHI_USER PRIMARY KEY (id), UNIQUE (email), UNIQUE (login))]
2017-02-14T13:13:21.51-0700 [APP/PROC/WEB/0]OUT 	at liquibase.changelog.ChangeSet.execute(ChangeSet.java:619)
2017-02-14T13:13:21.51-0700 [APP/PROC/WEB/0]OUT 	at liquibase.changelog.visitor.UpdateVisitor.visit(UpdateVisitor.java:51)
2017-02-14T13:13:21.51-0700 [APP/PROC/WEB/0]OUT 	at liquibase.changelog.ChangeLogIterator.run(ChangeLogIterator.java:79)
2017-02-14T13:13:21.51-0700 [APP/PROC/WEB/0]OUT 	at liquibase.Liquibase.update(Liquibase.java:214)
2017-02-14T13:13:21.51-0700 [APP/PROC/WEB/0]OUT 	at liquibase.Liquibase.update(Liquibase.java:192)
2017-02-14T13:13:21.51-0700 [APP/PROC/WEB/0]OUT 	at liquibase.integration.spring.SpringLiquibase.performUpdate(SpringLiquibase.java:431)
2017-02-14T13:13:21.51-0700 [APP/PROC/WEB/0]OUT 	at liquibase.integration.spring.SpringLiquibase.afterPropertiesSet(SpringLiquibase.java:388)
2017-02-14T13:13:21.51-0700 [APP/PROC/WEB/0]OUT 	at io.github.jhipster.config.liquibase.AsyncSpringLiquibase.initDb(AsyncSpringLiquibase.java:79)
2017-02-14T13:13:21.51-0700 [APP/PROC/WEB/0]OUT 	at io.github.jhipster.config.liquibase.AsyncSpringLiquibase.afterPropertiesSet(AsyncSpringLiquibase.java:69)
2017-02-14T13:13:21.51-0700 [APP/PROC/WEB/0]OUT 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1687)
2017-02-14T13:13:21.51-0700 [APP/PROC/WEB/0]OUT 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1624)
2017-02-14T13:13:21.51-0700 [APP/PROC/WEB/0]OUT 	... 24 common frames omitted
2017-02-14T13:13:21.51-0700 [APP/PROC/WEB/0]OUT Caused by: liquibase.exception.DatabaseException: ERROR: syntax error at or near "$"
2017-02-14T13:13:21.51-0700 [APP/PROC/WEB/0]OUT   Position: 382 [Failed SQL: CREATE TABLE public.jhi_user (id BIGSERIAL NOT NULL, login VARCHAR(50) NOT NULL, password_hash VARCHAR(60), first_name VARCHAR(50), last_name VARCHAR(50), email VARCHAR(100), image_url VARCHAR(256), activated BOOLEAN NOT NULL, lang_key VARCHAR(5), activation_key VARCHAR(20), reset_key VARCHAR(20), created_by VARCHAR(50) NOT NULL, created_date TIMESTAMP WITHOUT TIME ZONE DEFAULT ${now} NOT NULL, reset_date TIMESTAMP WITHOUT TIME ZONE, last_modified_by VARCHAR(50), last_modified_date TIMESTAMP WITHOUT TIME ZONE, CONSTRAINT PK_JHI_USER PRIMARY KEY (id), UNIQUE (email), UNIQUE (login))]
2017-02-14T13:13:21.51-0700 [APP/PROC/WEB/0]OUT 	at liquibase.executor.jvm.JdbcExecutor$ExecuteStatementCallback.doInStatement(JdbcExecutor.java:309)
2017-02-14T13:13:21.51-0700 [APP/PROC/WEB/0]OUT 	at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:55)
2017-02-14T13:13:21.51-0700 [APP/PROC/WEB/0]OUT 	at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:113)
2017-02-14T13:13:21.51-0700 [APP/PROC/WEB/0]OUT 	at liquibase.database.AbstractJdbcDatabase.execute(AbstractJdbcDatabase.java:1277)
2017-02-14T13:13:21.51-0700 [APP/PROC/WEB/0]OUT 	at liquibase.database.AbstractJdbcDatabase.executeStatements(AbstractJdbcDatabase.java:1259)
2017-02-14T13:13:21.51-0700 [APP/PROC/WEB/0]OUT 	at liquibase.changelog.ChangeSet.execute(ChangeSet.java:582)
2017-02-14T13:13:21.51-0700 [APP/PROC/WEB/0]OUT 	... 34 common frames omitted
2017-02-14T13:13:21.51-0700 [APP/PROC/WEB/0]OUT Caused by: org.postgresql.util.PSQLException: ERROR: syntax error at or near "$"
2017-02-14T13:13:21.51-0700 [APP/PROC/WEB/0]OUT   Position: 382
2017-02-14T13:13:21.51-0700 [APP/PROC/WEB/0]OUT 	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2455)
2017-02-14T13:13:21.51-0700 [APP/PROC/WEB/0]OUT 	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2155)
2017-02-14T13:13:21.51-0700 [APP/PROC/WEB/0]OUT 	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:288)
2017-02-14T13:13:21.51-0700 [APP/PROC/WEB/0]OUT 	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:430)
2017-02-14T13:13:21.51-0700 [APP/PROC/WEB/0]OUT 	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:356)
2017-02-14T13:13:21.51-0700 [APP/PROC/WEB/0]OUT 	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:303)
2017-02-14T13:13:21.51-0700 [APP/PROC/WEB/0]OUT 	at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:289)
2017-02-14T13:13:21.51-0700 [APP/PROC/WEB/0]OUT 	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:266)
2017-02-14T13:13:21.51-0700 [APP/PROC/WEB/0]OUT 	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:262)
2017-02-14T13:13:21.51-0700 [APP/PROC/WEB/0]OUT 	at liquibase.executor.jvm.JdbcExecutor$ExecuteStatementCallback.doInStatement(JdbcExecutor.java:307)
2017-02-14T13:13:21.51-0700 [APP/PROC/WEB/0]OUT 	... 39 common frames omitted
2017-02-14T13:13:21.84-0700 [APP/PROC/WEB/0]OUT Exit status 1
2017-02-14T13:13:21.85-0700 [CELL/0]     OUT Exit status 0
2017-02-14T13:13:21.86-0700 [CELL/0]     OUT Destroying container
2017-02-14T13:13:21.86-0700 [API/5]      OUT Process has crashed with type: "web"
2017-02-14T13:13:21.88-0700 [API/5]      OUT App instance exited with guid a1197eef-5141-4ec2-a165-d27b51649d12 payload: {"instance"=>"", "index"=>0, "reason"=>"CRASHED", "exit_description"=>"2 error(s) occurred:\n\n* 2 error(s) occurred:\n\n* Exited with status 1\n* cancelled\n* cancelled", "crash_count"=>6, "crash_timestamp"=>1487103201857574996, "version"=>"2cdc4034-7822-4950-827f-859adf3ac286"}
2017-02-14T13:13:22.87-0700 [CELL/0]     OUT Successfully destroyed container
```

##### **Motivation for or Use Case**

I'd like to be able to deploy an app to Cloud Foundy.

##### **Reproduce the error**

Create an app with H2Disk and MySQL for production.

Use `yo jhipster:cloudfoundry`.

The app will fail to deploy.

##### **Suggest a Fix**

Detect MySQL instead of assuming PostgreSQL.

##### **JHipster Version(s)**

```
blog@0.0.0 /Users/mraible/blog
└── generator-jhipster@4.0.3

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

```yaml
{
  "generator-jhipster": {
    "jhipsterVersion": "4.0.3",
    "baseName": "blog",
    "packageName": "org.jhipster.blog",
    "packageFolder": "org/jhipster/blog",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "jwtSecretKey": "2ed80e37e25d5cb52f5124f3684676bb79e0f0c5",
    "useSass": true,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "testFrameworks": [
      "protractor"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en",
      "fr"
    ],
    "clientFramework": "angular2"
  }
}
```

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

ls: no such file or directory: .jhipster/*.json

##### **Browsers and Operating System**

java version "1.8.0_112"
Java(TM) SE Runtime Environment (build 1.8.0_112-b16)
Java HotSpot(TM) 64-Bit Server VM (build 25.112-b16, mixed mode)

git version 2.10.2

node: v6.9.5

npm: 3.10.10

yeoman: 1.8.5

yarn: 0.19.1

Docker version 1.13.0, build 49bf474

docker-compose version 1.10.0, build 4bd6f1a

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by jdubois** [comment]
@mraible in your stacktrace, you have the PostgreSQL driver :-)

**Comment by mraible** [comment]
@jdubois You are correct. The sub-generator selects PostgreSQL rather detecting that I have MySQL. That's the bug!

**Comment by jdubois** [comment]
By default it uses Postgresql - I know it could detect your database, but I didn't do it, as the service names depend on your specific installation.
So you need to do 'cf marketplace' and input the correct service manually.

**Comment by mraible** [comment]
It'd be awesome if `yo jhipster:cloudfoundry` detected the database like `yo jhipster:heroku` does. At the very least, we should document it. There's no mention of this extra step on https://jhipster.github.io/cloudfoundry/.

**Comment by jdubois** [comment]
We can't auto detect it: it depends on your CloudFoundry instance. For example, people using BlueMix have a totally different marketplace, with Watson, etc.
