### ISSUE TITLE
Unit Test failire: javax.persistence.TransactionRequiredException: No EntityManager with actual transaction available for current thread

### ISSUE THREAD

**Issue by Falkurk** [jhipster/generator-jhipster#5391]
##### **Overview of the issue**
I am using JHipster Generator v4.0.7 and I create an entity like that:

```
entity Country {
	id Long, 
	name String required
}

entity Zone {
	id Long, 
	name String required 
}

relationship OneToMany {

  Zone to Country{zone(name) required},
}
```
When I generate the code, JHipster generator generate failed unit test. I have this stacktrace:

```
 -------------------------------------------------------------------------------
Test set: xxx.yyy.zzz.CountryResourceIntTest
-------------------------------------------------------------------------------
Tests run: 11, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 1.134 sec <<< FAILURE! - in xxx.yyy.zzz.web.rest.CountryResourceIntTest
equalsVerifier(xxx.yyy.zzz.web.rest.CountryResourceIntTest)  Time elapsed: 0.054 sec  <<< ERROR!
javax.persistence.TransactionRequiredException: No EntityManager with actual transaction available for current thread - cannot reliably process 'persist' call
	at org.springframework.orm.jpa.SharedEntityManagerCreator$SharedEntityManagerInvocationHandler.invoke(SharedEntityManagerCreator.java:282)
	at com.sun.proxy.$Proxy165.persist(Unknown Source)
	at fr.accs.advalorem.web.rest.CountryResourceIntTest.createEntity(CountryResourceIntTest.java:101)
	at xxx.yyy.zzz.web.rest.CountryResourceIntTest.initTest(CountryResourceIntTest.java:115)
```

It seems that equalsVerifier method should be @Transactional because it call the @Before method

##### **Suggest a Fix**

Replace 

~~~java
    @Test
    public void equalsVerifier() throws Exception {
        TestUtil.equalsVerifier(Country.class);
    }
~~~

By

~~~java
    @Test
    @Transactional
    public void equalsVerifier() throws Exception {
        TestUtil.equalsVerifier(Country.class);
    }
~~~

##### **JHipster Version(s)**

JHipster generator v4.0.7

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

Country.json:

~~~
{
    "fluentMethods": true,
    "relationships": [
        {
            "relationshipType": "many-to-one",
            "relationshipValidateRules": "required",
            "relationshipName": "zone",
            "otherEntityName": "zone",
            "otherEntityField": "name"
        }
    ],
    "fields": [
        {
            "fieldName": "name",
            "fieldType": "String",
            "fieldValidateRules": [
                "required"
            ]
        }
    ],
    "changelogDate": "20170307151049",
    "entityTableName": "country",
    "dto": "no",
    "pagination": "pager",
    "service": "serviceImpl"
}
~~~

Zone.json
~~~
{
    "fluentMethods": true,
    "relationships": [
        {
            "relationshipType": "one-to-many",
            "relationshipName": "country",
            "otherEntityName": "country",
            "otherEntityRelationshipName": "zone"
        }
    ],
    "fields": [
        {
            "fieldName": "name",
            "fieldType": "String",
            "fieldValidateRules": [
                "required"
            ]
        }
    ],
    "changelogDate": "20170307151049",
    "entityTableName": "zone",
    "dto": "no",
    "pagination": "pager",
    "service": "serviceImpl"
}
~~~

- [ X] Checking this box is mandatory (this is just to show you read everything)

**Comment by jdubois** [comment]
Please follow the guidelines:

- you didn't give your `.yo-rc.json`
- you didn't give your full JDL, as you have a comma missing at the end...

I'm still trying to test it

**Comment by jdubois** [comment]
Oh, and indeed I confirm the issue!!!

**Comment by jdubois** [comment]
Good catch!!! I don't understand how this could have passed our tests!!! A new release would be necessary, this is an important bug.

**Comment by pascalgrimaud** [comment]
Very strange!
I will check our Travis build. It shouldn't pass as we have a lot of entities which are in the same relationship than your country + zone

**Comment by pascalgrimaud** [comment]
And the ` UserResourceIntTest` which is refactored recently, is correct:
https://github.com/jhipster/generator-jhipster/blob/master/generators/server/templates/src/test/java/package/web/rest/_UserResourceIntTest.java#L665-L668

**Comment by pascalgrimaud** [comment]
I understand why our Travis build didn't detect that:
- there are no test on `"relationshipValidateRules": "required"` in our entities in sample/.jhipster/
- see the search: https://github.com/jhipster/generator-jhipster/search?utf8=%E2%9C%93&q=relationshipValidateRules
- clearly, we have to add that

**Comment by jdubois** [comment]
Thanks @pascalgrimaud !!! This was worrying me, I'm happy to have the answer.
