### ISSUE TITLE
Sequence doesn't exist in SqlServer 2008

### ISSUE THREAD

**Issue by christelleC** [jhipster/generator-jhipster#5474]
- Please follow the issue template below for bug reports and feature requests.
- Tickets opened without any of these informations will be **closed** without any explanation.

##### **Overview of the issue**

My Project works with SQL Server 2008
But sequence have been created only for SQL Server 2012.
So the save fonction create error.

The table sould be created with IDENTITY

##### **Reproduce the error**

2017-03-23 15:03:32.162 ERROR 13120 --- [  XNIO-3 task-7] c.caagis.osd.aop.logging.LoggingAspect   : Exception in com.caagis.osd.service.BanqueService.save() with cause = 'org.hibernate.exception.ConstraintViolationException: could not execute statement' and exception = 'could not execute statement; SQL [n/a]; constraint [null]; nested exception is org.hibernate.exception.ConstraintViolationException: could not execute statement'

org.springframework.dao.DataIntegrityViolationException: could not execute statement; SQL [n/a]; constraint [null]; nested exception is org.hibernate.exception.ConstraintViolationException: could not execute statement
	at org.springframework.orm.jpa.vendor.HibernateJpaDialect.convertHibernateAccessException(HibernateJpaDialect.java:278)
	at org.springframework.orm.jpa.vendor.HibernateJpaDialect.translateExceptionIfPossible(HibernateJpaDialect.java:244)
	at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.translateExceptionIfPossible(AbstractEntityManagerFactoryBean.java:488)
	at org.springframework.dao.support.ChainedPersistenceExceptionTranslator.translateExceptionIfPossible(ChainedPersistenceExceptionTranslator.java:59)
	at org.springframework.dao.support.DataAccessUtils.translateIfNecessary(DataAccessUtils.java:213)
	at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:147)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.data.jpa.repository.support.CrudMethodMetadataPostProcessor$CrudMethodMetadataPopulatingMethodInterceptor.invoke(CrudMethodMetadataPostProcessor.java:133)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.data.repository.core.support.SurroundingTransactionDetectorMethodInterceptor.invoke(SurroundingTransactionDetectorMethodInterceptor.java:57)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:213)
	at com.sun.proxy.$Proxy207.save(Unknown Source)
	at com.caagis.osd.service.BanqueService.save(BanqueService.java:35)
##### **Suggest a Fix**
Add a choice Sqlserver 2012 or sql Server 2008
Modify the _entity.java file to not create a sequence for sqlserver2008
generate another create fonction for application working with Sql Server 2008
CREATE TABLE Persons (
    ID int IDENTITY(1,1) PRIMARY KEY,
    LastName varchar(255) NOT NULL,
    FirstName varchar(255),
    Age int
);

##### **JHipster Version(s)**
21/03/2017

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

I use JDL
##### **Browsers and Operating System**

Windows 7
- [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by jdubois** [comment]
I'm sorry, but we can't support old releases of SQL Server. We don't support old releases of other databases (like MySQL and Oracle, where we had some similar issues), so it's really nothing against you, just that we can't maintain so many options.
Besides, SQL Server 2008 has been EOL'd for nearly 3 years now, so we can't support a software that isn't supported by its own editor. You should ask your vendor for a more recent version.
