### ISSUE TITLE
Liquibase Error

### ISSUE THREAD

**Issue by jboss42** [jhipster/generator-jhipster#5528]
##### **Overview of the issue**
Liquibase error

##### **Motivation for or Use Case**

`Caused by: java.lang.IllegalStateException: All Hibernate caches should be created upfront. Please update CacheConfiguration.java with the missing cache
	at io.github.jhipster.config.jcache.NoDefaultJCacheRegionFactory.createCache(NoDefaultJCacheRegionFactory.java:34)
	at org.hibernate.cache.jcache.JCacheRegionFactory.getOrCreateCache(JCacheRegionFactory.java:190)
	at org.hibernate.cache.jcache.JCacheRegionFactory.buildCollectionRegion(JCacheRegionFactory.java:127)
	at org.hibernate.cache.spi.RegionFactory.buildCollectionRegion(RegionFactory.java:199)
	at org.hibernate.internal.CacheImpl.determineCollectionRegionAccessStrategy(CacheImpl.java:496)
	at org.hibernate.metamodel.internal.MetamodelImpl.initialize(MetamodelImpl.java:167)
	at org.hibernate.internal.SessionFactoryImpl.<init>(SessionFactoryImpl.java:297)
	at org.hibernate.boot.internal.SessionFactoryBuilderImpl.build(SessionFactoryBuilderImpl.java:445)
	at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.build(EntityManagerFactoryBuilderImpl.java:889)
	... 25 common frames omitted`

##### **JHipster Version(s)**

4.1.1

**Comment by deepu105** [comment]
This ticket has been closed as the guidelines are not followed.

Tickets must follow our [Guidelines](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md#submitting-an-issue), as mentioned in:

1. our [Readme file on the front page of the project](https://github.com/jhipster/generator-jhipster/blob/master/README.md), 
2. the ["create a new ticket" page](https://github.com/jhipster/generator-jhipster/issues/new) and
3. our [Help page](http://jhipster.github.io/help/)

We have also created a template on the ["create a new ticket" page](https://github.com/jhipster/generator-jhipster/issues/new) to help you follow those guidelines.

Open a new issue with proper details or update this issue with all details and request to re open.
Issues opened without proper details will be closed without explanation.

**Comment by progbishoy** [comment]
deepu anta bdaaaaaaaan awy ya akheeey

**Comment by deepu105** [comment]
@progbishoy what is that supposed to mean?

First of all don't comment on long closed tickets 
Second am I suppose to guess the language and translate it? Its no way to ask for help

**Comment by jdubois** [comment]
@progbishoy please, there are nearly 700 people watching this repo, don't spam everyone with random words, or I'll block you.
Have a look at our [code of conduct](https://github.com/jhipster/generator-jhipster/blob/master/CODE_OF_CONDUCT.md).

**Comment by progbishoy** [comment]
Sorry comment removed i was write in english and keyboard was in arabic 
i was asking him about bug if it's solved in another ticket cause i have the same bug

**Comment by progbishoy** [comment]
@deepu105 @jdubois  do anyone have answer
