### ISSUE TITLE
Problem with mariadb max_allow_packet

### ISSUE THREAD

**Issue by amrnablus** [jhipster/generator-jhipster#5611]
Hello,
I'm using jhipster with mariadb as the production database, things work fine for a while then i start getting this exception:
Caused by: java.sql.SQLTransientException: (conn:1851) Could not send query: query size 2365 is >= to max_allowed_packet (1024)
```
Query is : SELECT TABLE_SCHEMA TABLE_CAT, NULL TABLE_SCHEM, TABLE_NAME, COLUMN_NAME, CASE data_type WHEN 'bit' THEN -7 WHEN 'tinyblob' THEN -3 WHEN 'mediumblob' THEN -4 WHEN 'longblob' THEN -4 WHEN 'blob' THEN -4 WHEN 'tinytext' THEN 12 WHEN 'mediumtext' THEN -1 WHEN 'longtext' THEN -1 WHEN 'text' THEN -1 WHEN 'date' THEN 91 WHEN 'datetime' THEN 93 WHEN 'decimal' THEN 3 WHEN 'double' THEN 8 WHEN 'enum' THEN 12 WHEN 'float' THEN 7 WHEN 'int' THEN IF( COLUMN_TYPE like '%unsigned%', 4,4) WHEN 'bigint' THEN -5 WHEN 'mediumint' THEN 4 WHEN 'null' THEN 0 WHEN 'set' THEN 12 WHEN 'smallint' THEN IF( COLUMN_TYPE like '%unsigned%', 5,5) WHEN 'varchar' THEN 12 WHEN 'varbinary' THEN -3 WHEN 'char' THEN 1 WHEN 'binary' THEN -2 WHEN 'time' THEN 92 WHEN 'timestamp' THEN 93 WHEN 'tinyint' THEN IF(COLUMN_TYPE='tinyint(1)',-7,-6)  WHEN 'year' THEN 91 ELSE 1111 END  DATA_TYPE, IF(COLUMN_TYPE = 'tinyint(1)', 'BIT',  UCASE(IF( COLUMN_TYPE LIKE '%(%)%', CONCAT(SUBSTRING( COLUMN_TYPE,1, LOCATE('(',COLUMN_TYPE) - 1 ), SUBSTRING(COLUMN_TYPE ...
        at org.mariadb.jdbc.internal.util.ExceptionMapper.get(ExceptionMapper.java:145)
        at org.mariadb.jdbc.internal.util.ExceptionMapper.getException(ExceptionMapper.java:101)
        at org.mariadb.jdbc.internal.util.ExceptionMapper.throwAndLogException(ExceptionMapper.java:77)
        at org.mariadb.jdbc.MariaDbStatement.executeQueryEpilog(MariaDbStatement.java:224)
        at org.mariadb.jdbc.MariaDbStatement.executeInternal(MariaDbStatement.java:253)
        at org.mariadb.jdbc.MariaDbStatement.executeQuery(MariaDbStatement.java:366)
        at org.mariadb.jdbc.MariaDbDatabaseMetaData.executeQuery(MariaDbDatabaseMetaData.java:424)
        at org.mariadb.jdbc.MariaDbDatabaseMetaData.getColumns(MariaDbDatabaseMetaData.java:664)
        at liquibase.snapshot.JdbcDatabaseSnapshot$CachingDatabaseMetaData$3.fastFetchQuery(JdbcDatabaseSnapshot.java:362)
        at liquibase.snapshot.ResultSetCache$SingleResultSetExtractor.fastFetch(ResultSetCache.java:289)
        at liquibase.snapshot.ResultSetCache.get(ResultSetCache.java:57)

```

The fix from mariadb's side is simple, which is changing the max_allowed_pack config, the strange thing, however, is that even after I change it goes back to being 1024 without restarting the container or any change from my side, I was wondering if anyone is facing a similar problem and/or if jhipster or any of it's dependencies could be changing this config. 
If not, then I suggest we add an init query that could change the max_allowed_packet in the generated code to avoid such issue

**Comment by gmarziou** [comment]
This ticket has been closed as the guidelines are not followed.

Tickets must follow our [Guidelines](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md#submitting-an-issue), as mentioned in:

1. our [Readme file on the front page of the project](https://github.com/jhipster/generator-jhipster/blob/master/README.md), 
2. the ["create a new ticket" page](https://github.com/jhipster/generator-jhipster/issues/new) and
3. our [Help page](http://jhipster.github.io/help/)

We have also created a template on the ["create a new ticket" page](https://github.com/jhipster/generator-jhipster/issues/new) to help you follow those guidelines.
