### ISSUE TITLE
LoggingAspect causing OutOfMemoryError

### ISSUE THREAD

**Issue by Metavirulent** [jhipster/generator-jhipster#5715]
##### **Overview of the issue**

`LoggingAspect` logs all method calls in the .repository..*, .service..* and .rest..* packages. However, this is not limited to the actual repositories, services and resources but also includes all helper classes. This is particularly bad for DTOs and MapStruct mappers that can potentially be called a lot for REST endpoints with arrays.

This clogs up the logs with setters and - in our case - even caused an `OutOfMemoryError` from all the logging burden

##### **Motivation for or Use Case**

Not only is it undesirable to have every getter and setter on a DTO in the logs, but the memory consumption can be a serious issue.

##### **Reproduce the error**

Create a REST Resource that takes a retrieves a fairly large array of entities from the database and maps it to DTOs. Calls on DTOs and Mappers trigger the pointcut and either flood the trace or even cause an `OutOfMemoryError`.

	2017-05-05 12:06:38.557 ERROR 16504 --- [  XNIO-2 task-2] c.u.p.c.s.aop.logging.LoggingAspect      : Exception in com.unycom.platform.csp.service.web.rest.mapper.LineItemMapperImpl.lineItemsToLineItemDTOs() with cause = 'NULL' and exception = 'Java heap space'

	java.lang.OutOfMemoryError: Java heap space
		at java.util.Arrays.copyOf(Arrays.java:3332)
		at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:124)
		at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:448)
		at java.lang.StringBuilder.append(StringBuilder.java:136)
		at java.lang.StringBuilder.append(StringBuilder.java:131)
		at java.util.AbstractCollection.toString(AbstractCollection.java:462)
		at java.lang.String.valueOf(String.java:2994)
		at java.util.Arrays.toString(Arrays.java:4571)
		at com.unycom.platform.csp.service.aop.logging.LoggingAspect.logAround(LoggingAspect.java:70)
		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.lang.reflect.Method.invoke(Method.java:498)
		at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:629)
		at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:618)
		at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:70)
		at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
		at org.springframework.aop.aspectj.AspectJAfterThrowingAdvice.invoke(AspectJAfterThrowingAdvice.java:62)
		at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
		at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92)
		at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
		at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:656)
		at com.unycom.platform.csp.service.web.rest.mapper.LineItemMapperImpl$$EnhancerBySpringCGLIB$$2c93b379.lineItemsToLineItemDTOs(<generated>)
		at com.unycom.platform.csp.service.service.database.DatabaseReminderService.getLineItems(DatabaseReminderService.java:59)
		at com.unycom.platform.csp.service.service.database.DatabaseReminderService$$FastClassBySpringCGLIB$$a211aef0.invoke(<generated>)
		at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
		at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:721)
		at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
		at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:85)
		at com.unycom.platform.csp.service.aop.logging.LoggingAspect.logAround(LoggingAspect.java:73)
		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

##### **Related issues**

n/a

##### **Suggest a Fix**

The pointcut should include bean names so only *Service, *Repository and *Resource are affected.

So, in _LoggingAspect.java, the @Pointcut shall be changed from

    @Pointcut("within(<%=packageName%>.repository..*) || within(<%=packageName%>.service..*) || within(<%=packageName%>.web.rest..*)")

to

    @Pointcut("(within(<%=packageName%>.repository..*) && bean(*Repository))"+
                  " || (within(<%=packageName%>.service..*) && bean(*Service))"+
                  " || (within(<%=packageName%>.web.rest..*) && bean(*Resource))")

##### **JHipster Version(s)**

4.3.0

##### **JHipster configuration**

n/a since LoggingAspect gets picked up for all configurations

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

n/a

##### **Browsers and Operating System**

n/a

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by jdubois** [comment]
This makes sense.

- Instead of using the bean name, we could use the @Service @Controller @Repository annotations, as those are type safe.
- We could also do it the other way around, as the issue is only with DTOs: we could exclude all beans marked "@Mapper"

**Comment by Metavirulent** [comment]
I could imagine other similar issues with classes added to the service layer by users so it's probably safer to restrict it to the actual services/repositories/resources.

**Comment by gzsombor** [comment]
And of course, writing sane toString methods would help.

**Comment by jdubois** [comment]
@Metavirulent my only issue is that it checks the class name, and that's not really obvious for people to understand what's monitored and what's not monitored.

I totally agree on this, I just want some feedback, and maybe a better idea on the pointcut that is being rewritten

**Comment by stevehouel** [comment]
@Metavirulent & @jdubois  maybe we can restrict the pointcut using an "@annotation" condition. 

Example : 

```
@Pointcut("(within(<%=packageName%>.repository..*) && && bean(*Repository))"+
              " || (within(<%=packageName%>.service..*) && @annotation(*Service))"+
              " || (within(<%=packageName%>.web.rest..*) && @annotation(*Resource))")
```

There is only one issue, it s regarding Repository who actually does not have any annotation on it (@Repository).

**Comment by gmarziou** [comment]
In my projects, I define a specific annotation, it helps simplifying the pointcut definition and also enables not using the aspect on some services.
