### ISSUE TITLE
generator-jhipster function (...args)  SyntaxError

### ISSUE THREAD

**Issue by korrident** [jhipster/generator-jhipster#5780]
##### **Overview of the issue**
Can't use generator at all (first use)

##### **Reproduce the error**
```
> yo jhipster

/usr/lib/node_modules/generator-jhipster/generators/app/index.js:33
    constructor: function (...args) { // eslint-disable-line object-shorthand
                           ^^^

SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:20:19)
    at Object.defineProperty.get [as jhipster:app] (/usr/local/share/.config/yarn/global/node_modules/yeoman-enviro
    at Store.get (/usr/local/share/.config/yarn/global/node_modules/yeoman-environment/lib/store.js:64:35)
    at Environment.get (/usr/local/share/.config/yarn/global/node_modules/yeoman-environment/lib/environment.js:262
```

##### **Related issues**
same kind of error as closed https://github.com/jhipster/generator-jhipster/issues/404
(same error as @rafuch01 but he did not open new issue)

##### **JHipster Version(s)**
dans /usr/lib/node_modules/generator-jhipster/package.json
```` 
"_id": "generator-jhipster@4.4.1",
"_npmOperationalInternal": {
    "host": "packages-18-east.internal.npmjs.com",
    "tmp": "tmp/generator-jhipster-4.4.1.tgz_1494276332830_0.7504458287730813"
  },
"version": "4.4.1",
````
##### **Browsers and Operating System**
yo --version
1.8.5

uname -a
Linux  4.4.0-45-generic #66~14.04.1-Ubuntu SMP Wed Oct 19 15:05:38 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

npm@4.6.1

node --version
v5.12.0

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by jdubois** [comment]
Can you use a supported Node version? Use a LTS (6.x), or the latest 7.x release, but not a 5.x, that's too old.

**Comment by korrident** [comment]
I confirm that using last version of node solved this issue.

````
wget -qO- https://deb.nodesource.com/setup_7.x | sudo bash -
sudo apt-get install -y nodejs
````

Thank you, I close the subject.
