### ISSUE TITLE
Error when choosing to install other generator from the JHipster Marketplace

### ISSUE THREAD

**Issue by mtdx** [jhipster/generator-jhipster#5845]
SyntaxError: Unexpected token I in JSON at position 0
    at Object.parse (native)
    at generator.httpsGet (/Users/user/.config/yarn/global/node_modules/generator-jhipster/generators/app/prompts.js:159:37)
    at IncomingMessage.res.on (/Users/user/.config/yarn/global/node_modules/generator-jhipster/generators/generator-base.js:2097:17)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)

**Comment by pascalgrimaud** [comment]
This ticket has been closed as the guidelines are not followed.

Tickets must follow our [Guidelines](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md#submitting-an-issue), as mentioned in:

1. our [Readme file on the front page of the project](https://github.com/jhipster/generator-jhipster/blob/master/README.md), 
2. the ["create a new ticket" page](https://github.com/jhipster/generator-jhipster/issues/new) and
3. our [Help page](http://jhipster.github.io/help/)

We have also created a template on the ["create a new ticket" page](https://github.com/jhipster/generator-jhipster/issues/new) to help you follow those guidelines.
