### ISSUE TITLE
Heroku sub-generator fails: heroku-cli-deploy is already installed

### ISSUE THREAD

**Issue by mraible** [jhipster/generator-jhipster#5902]
```
$ yo jhipster:heroku
Heroku configuration is starting
? Name to deploy as: health-by-points
? On which region do you want to deploy ? us

Using existing Git repository

Installing Heroku CLI deployment plugin
✖ { Error: Command failed: heroku plugins:install heroku-cli-deploy
Installing plugin heroku-cli-deploy... !
 ▸    Plugin heroku-cli-deploy is already installed

    at ChildProcess.exithandler (child_process.js:252:12)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at maybeClose (internal/child_process.js:887:16)
    at Socket.stream.socket.on (internal/child_process.js:340:11)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at Pipe._handle.close [as _onclose] (net.js:546:12)
  killed: false,
  code: 1,
  signal: null,
  cmd: 'heroku plugins:install heroku-cli-deploy' }
identical build.gradle
```

My project's information:

```
yo jhipster:info
Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
twenty-one-points@0.0.0 /Users/mraible/dev/21-points
└── generator-jhipster@4.5.2

```


##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

```yaml
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "org.jhipster.health",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "4.5.2",
    "baseName": "TwentyOnePoints",
    "packageName": "org.jhipster.health",
    "packageFolder": "org/jhipster/health",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "postgresql",
    "searchEngine": "elasticsearch",
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "gradle",
    "enableSocialSignIn": false,
    "jwtSecretKey": "51b88e52708cfa62c9bc4a7e6c50eff6143ad55c",
    "clientFramework": "angular2",
    "useSass": true,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "testFrameworks": [
      "gatling",
      "protractor"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en",
      "fr"
    ]
  }
}
```

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

ls: no such file or directory: .jhipster/*.json

##### **Browsers and Operating System**

java version "1.8.0_121"
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)

git version 2.12.2

node: v8.0.0

npm: 5.0.0

yeoman: 1.8.5

yarn: 0.24.4

Docker version 17.03.1-ce, build c6d412e

docker-compose version 1.11.2, build dfed245
```

**Comment by jkutner** [comment]
This should be fixed by #5853. Has that not been released yet?

**Comment by mraible** [comment]
Looks like that's in 4.5.3, I'm using 4.5.2. Will try upgrading and close if it's solved.

**Comment by jkutner** [comment]
Ugh, this is going to be a bad experience for a lot of people who don't know to upgrade. If you have any ideas for better remediation plz let me know.

**Comment by jdubois** [comment]
Yes that should be in 4.5.3, released a few hours ago
