### ISSUE TITLE
JHipster - Cassandra embedded cluster configuration

### ISSUE THREAD

**Issue by levioza** [jhipster/generator-jhipster#5992]
##### **Overview of the issue**

When I use JHipster to generate an application with Cassandra support. I get the following error when I run the tests.

```
2017-06-26 14:21:02.436  WARN 62002 --- [r2-nio-worker-0] io.netty.channel.DefaultChannelPipeline  : An exception was thrown by a user handler's exceptionCaught() method while handling the following exception:

java.io.IOException: Connection reset by peer
        at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
        at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
        at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
        at sun.nio.ch.IOUtil.read(IOUtil.java:192)
        at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:375)
        at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:221)
        at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:897)
        at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:242)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:119)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:564)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:505)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:419)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:391)
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112)
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:145)
        at java.lang.Thread.run(Thread.java:745)

2017-06-26 14:21:02.436 ERROR 62002 --- [-reconnection-0] c.d.driver.core.ControlConnection        : [Control connection] Cannot connect to any host, scheduling retry in 1000 milliseconds
2017-06-26 14:21:03.440 ERROR 62002 --- [-reconnection-0] c.d.driver.core.ControlConnection        : [Control connection] Cannot connect to any host, scheduling retry in 2000 milliseconds`
```

##### **Motivation for or Use Case**

 I believe that there is an error with the embedded cluster configuration.

##### **Reproduce the error**

1. Generate a new JHipster application with Cassandra support.
2. Run './gradlew test' 

##### **JHipster Version(s)**

JHipster v4.5.6

##### **JHipster configuration**

```yaml
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "xxxxx"
    },
    "jhipsterVersion": "xxxxx",
    "baseName": "xxxxx",
    "packageName": "xxxxx",
    "packageFolder": "xxxxx",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "no",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "cassandra",
    "devDatabaseType": "cassandra",
    "prodDatabaseType": "cassandra",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "gradle",
    "enableSocialSignIn": false,
    "jwtSecretKey": "553949af6823e331cf4f2837efacb020329f2a92",
    "clientFramework": "angular2",
    "useSass": true,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": false
  }
}

##### **Browsers and Operating System**

java version "1.8.0_05"
Java(TM) SE Runtime Environment (build 1.8.0_05-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.5-b02, mixed mode)

git version 2.11.0 (Apple Git-81)

node: v8.1.2

npm: 5.0.3

bower: 1.8.0

gulp:
[14:38:23] CLI version 3.9.1

yeoman: 1.8.5

yarn: 0.24.6

Docker version 1.12.5, build 7392c3b

docker-compose version 1.9.0, build 2585387
```

##### **Operating System**

Mac OS Sierra

**Comment by jdubois** [comment]
Do you just have this at the end of the tests, or does that make all your tests fail?

**Comment by pascalgrimaud** [comment]
I already notice that and we have the same at the end of the tests, in Travis builds: https://travis-ci.org/jhipster/generator-jhipster/jobs/247047018 but with a "build success'.

```
2017-06-26 21:06:47.961  WARN 8745 --- [r2-nio-worker-0] io.netty.channel.DefaultChannelPipeline  : An exception was thrown by a user handler's exceptionCaught() method while handling the following exception:
java.io.IOException: Connection reset by peer
	at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:192)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
	at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:221)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:897)
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:242)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:119)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:564)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:505)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:419)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:391)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:145)
	at java.lang.Thread.run(Thread.java:748)
2017-06-26 21:06:48.016 ERROR 8745 --- [-reconnection-0] c.d.driver.core.ControlConnection        : [Control connection] Cannot connect to any host, scheduling retry in 1000 milliseconds
2017-06-26 21:06:49.021 ERROR 8745 --- [-reconnection-0] c.d.driver.core.ControlConnection        : [Control connection] Cannot connect to any host, scheduling retry in 2000 milliseconds
Results :
Tests run: 171, Failures: 0, Errors: 0, Skipped: 0
[INFO] 
[INFO] --- jacoco-maven-plugin:0.7.9:report (post-unit-test) @ travis-cassandra ---
[INFO] Loading execution data file /home/travis/app/target/test-results/coverage/jacoco/jacoco.exec
[INFO] Analyzed bundle 'Travis Cassandra' with 72 classes
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:23 min
[INFO] Finished at: 2017-06-26T21:06:51+10:00
[INFO] Final Memory: 57M/568M
[INFO] ------------------------------------------------------------------------
```

**Comment by jdubois** [comment]
Yes if that's only at the end it's "normal", it's because we force the shut down of the test cluster. Cassandra isn't supposed to work like that, normally you can't run it "embedded" and that's some custom code.

**Comment by levioza** [comment]
@jdubois @pascalgrimaud Thank you for your replies.

**Comment by levioza** [comment]
@jdubois I don't know if I should close the issue or you could handle the thrown exception.

**Comment by jdubois** [comment]
No we won't handle this - I don't know if that's possible, and it's not really worth spending time on this
