### ISSUE TITLE
The parsed JDL content and the database type must be passed (app without server)

### ISSUE THREAD

**Issue by alesisjoan** [jhipster/generator-jhipster#6009]
##### **Overview of the issue**

I had created an app with --skip-server command in order to make only the client stack. When trying to import the JDL-Studio file (that worked fine in a app created with server side), throws this message:

'The parsed JDL content and the database type must be passed.'

This is the stack trace:
`
$ jhipster import-jdl ~/Downloads/jhipster-jdl.jh
Executing jhipster:import-jdl /home/amanzano/Downloads/jhipster-jdl.jh
The jdl is being parsed.
{ name: 'NullPointerException',
  message: 'The parsed JDL content and the database type must be passed.',
  prototype: 
   Error
       at new buildException (/usr/local/share/.config/yarn/global/node_modules/jhipster-core/lib/exceptions/exception_factory.js:44:25)
       at Object.parse [as convertToJDL] (/usr/local/share/.config/yarn/global/node_modules/jhipster-core/lib/parser/jdl_parser.js:36:11)
       at constructor.parseJDL (/usr/local/share/.config/yarn/global/node_modules/generator-jhipster/generators/import-jdl/index.js:77:43)
       at Object.<anonymous> (/usr/local/share/.config/yarn/global/node_modules/yeoman-generator/lib/index.js:417:23)
       at /usr/local/share/.config/yarn/global/node_modules/yeoman-generator/node_modules/run-async/index.js:25:25
       at /usr/local/share/.config/yarn/global/node_modules/yeoman-generator/node_modules/run-async/index.js:24:19
       at /usr/local/share/.config/yarn/global/node_modules/yeoman-generator/lib/index.js:418:9
       at runCallback (timers.js:672:20)
       at tryOnImmediate (timers.js:645:5)
       at processImmediate [as _immediateCallback] (timers.js:617:5) }
events.js:160
      throw er; // Unhandled 'error' event
      ^
Error: ERROR! 
Error while parsing entities from JDL
    at Environment.error (/usr/local/share/.config/yarn/global/node_modules/yeoman-environment/lib/environment.js:89:38)
    at constructor.error (/usr/local/share/.config/yarn/global/node_modules/generator-jhipster/generators/generator-base.js:1514:18)
    at constructor.parseJDL (/usr/local/share/.config/yarn/global/node_modules/generator-jhipster/generators/import-jdl/index.js:86:22)
    at Object.<anonymous> (/usr/local/share/.config/yarn/global/node_modules/yeoman-generator/lib/index.js:417:23)
    at /usr/local/share/.config/yarn/global/node_modules/yeoman-generator/node_modules/run-async/index.js:25:25
    at /usr/local/share/.config/yarn/global/node_modules/yeoman-generator/node_modules/run-async/index.js:24:19
    at /usr/local/share/.config/yarn/global/node_modules/yeoman-generator/lib/index.js:418:9
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
`

##### **Motivation for or Use Case**

I want to create a client side application in order to consume an API-REST backend.

##### **Suggest a Fix**

If this is not a bug, I suggest to validate this operation before executing.

##### **JHipster Version(s)**

4.5.2

##### **JHipster configuration**

`{
  "generator-jhipster": {
    "clientFramework": "angular1",
    "useSass": false,
    "clientPackageManager": "yarn",
    "jhipsterVersion": "4.5.2",
    "applicationType": "monolith",
    "baseName": "socios_client",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "skipServer": true,
    "enableTranslation": false
  }`
##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**
my jdl file:

`entity Socio {
	name String,
    dni String,
}

entity Cuota {
	periodo String,
    monto Float,
	pagada Boolean,
    grupo String,
    plan String,
    name String,
}

enum FormaPago{
	EFECTIVO, TARJETA, CHEQUE
}

entity Socio{
	dni String,
    name String,
	grupo String,
	plan String,
}

entity DetallePago{
	monto_pago Float,
    forma_pago FormaPago,
    vuelto Float
}

entity Pago{
	monto_pagar Float,
    fecha LocalDate,
    cajero String
}

entity Grupo{
	name String,
	plan String
}

relationship ManyToOne{
	DetallePago{pago} to Pago{detalle},
    Pago{cuota(name)} to Cuota{pago}
}`

##### **Browsers and Operating System**

OS is Linux Mint. Browser is Chrome.

Thanks all you.

**Comment by xetys** [comment]
have you tried to add the microservice notation for your JDL? This is needed for JHipster to know you want to generate client files, rather than server files.

add

```
microservice Socio with SomeMicroService
microservice DetallePago with SomeMicroService
microservice Pago with SomeMicroService
microservice Grupo with SomeMicroService
```

to your JDL

**Comment by deepu105** [comment]
Also if you skip server you still need to pass some of the required data like database type to use etc. I'm gonna add a validation for this

**Comment by alesisjoan** [comment]
@xetys I didn't consider that. That is a good idea. However, I want to use Odoo as backend, not an jhipster microservice.
