### ISSUE TITLE
installation javamelody with spring boot

### ISSUE THREAD

**Issue by khdaddou** [jhipster/generator-jhipster#6053]
I'm installing javamelody in springboot projet (according to this tutorial: https://github.com/javamelody/javamelody/wiki/SpringBootStarter  : installation without spring-boot-starter) but when runnig server, I got this error:

017-07-07 14:55:20.582  WARN 10056 --- [  restartedMain] ationConfigEmbeddedWebApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'com.ryantenney.metrics.spring.config.annotation.DelegatingMetricsConfiguration': Unsatisfied dependency expressed through method 'setMetricsConfigurers' parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'metricsConfiguration': Unsatisfied dependency expressed through field 'hikariDataSource'; nested exception is org.springframework.beans.factory.BeanNotOfRequiredTypeException: Bean named 'dataSource' is expected to be of type 'com.zaxxer.hikari.HikariDataSource' but was actually of type 'com.sun.proxy.$Proxy132'
2017-07-07 14:55:20.585 ERROR 10056 --- [  restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Destroy method on bean with name 'dataSourceInitializer' threw an exception

java.lang.IllegalStateException: ApplicationEventMulticaster not initialized - call 'refresh' before multicasting events via the context: org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@7d8e76e9: startup date [Fri Jul 07 14:55:14 CEST 2017]; root of context hierarchy
	at org.springframework.context.support.AbstractApplicationContext.getApplicationEventMulticaster(AbstractApplicationContext.java:404)
	at org.springframework.context.support.ApplicationListenerDetector.postProcessBeforeDestruction(ApplicationListenerDetector.java:97)
	at org.springframework.beans.factory.support.DisposableBeanAdapter.destroy(DisposableBeanAdapter.java:253)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroyBean(DefaultSingletonBeanRegistry.java:578)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroySingleton(DefaultSingletonBeanRegistry.java:554)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.destroySingleton(DefaultListableBeanFactory.java:954)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroySingletons(DefaultSingletonBeanRegistry.java:523)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.destroySingletons(DefaultListableBeanFactory.java:961)
	at org.springframework.context.support.AbstractApplicationContext.destroyBeans(AbstractApplicationContext.java:1033)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:555)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:761)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:371)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315)
	at net.viamedis.kalivia.osteo.KaliviaOsteoApp.main(KaliviaOsteoApp.java:77)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.devtools.restart.RestartLauncher.run(RestartLauncher.java:49)

2017-07-07 14:55:20.587 DEBUG 10056 --- [  restartedMain] E.v.k.o.d.P.collectionHorairesOuvertures : Close successful.
2017-07-07 14:55:20.588 DEBUG 10056 --- [  restartedMain] c.e.c.E.v.k.osteo.domain.Honoraires      : Close successful.
2017-07-07 14:55:20.588 DEBUG 10056 --- [  restartedMain] c.e.c.E.v.k.o.domain.HorairesOuvertures  : Close successful.
2017-07-07 14:55:20.588 DEBUG 10056 --- [  restartedMain] c.e.c.E.v.k.osteo.domain.ParamEcole      : Close successful.
2017-07-07 14:55:20.589 DEBUG 10056 --- [  restartedMain] c.e.c.E.v.k.o.domain.PlsInfosCabinet     : Close successful.
2017-07-07 14:55:20.589 DEBUG 10056 --- [  restartedMain] c.e.c.E.v.k.osteo.domain.Beneficiaire    : Close successful.
2017-07-07 14:55:20.589 DEBUG 10056 --- [  restartedMain] c.e.c.E.v.k.o.domain.ParamMotifContact   : Close successful.
2017-07-07 14:55:20.589 DEBUG 10056 --- [  restartedMain] c.e.c.E.v.k.o.domain.PersistentToken     : Close successful.
2017-07-07 14:55:20.590 DEBUG 10056 --- [  restartedMain] c.e.c.E.v.k.osteo.domain.ParamNbConsult  : Close successful.
2017-07-07 14:55:20.590 DEBUG 10056 --- [  restartedMain] c.e.c.E.v.k.o.domain.User.authorities    : Close successful.
2017-07-07 14:55:20.590 DEBUG 10056 --- [  restartedMain] c.e.c.E.v.k.osteo.domain.Authority       : Close successful.
2017-07-07 14:55:20.590 DEBUG 10056 --- [  restartedMain] c.e.c.E.v.kalivia.osteo.domain.Contact   : Close successful.
2017-07-07 14:55:20.591 DEBUG 10056 --- [  restartedMain] c.e.c.E.v.k.o.domain.ParamMotifConsult   : Close successful.
2017-07-07 14:55:20.591 DEBUG 10056 --- [  restartedMain] c.e.c.E.v.k.o.d.P.collectionHonoraires   : Close successful.
2017-07-07 14:55:20.591 DEBUG 10056 --- [  restartedMain] c.e.c.E.v.k.o.domain.ParamTempsPratique  : Close successful.
2017-07-07 14:55:20.592 DEBUG 10056 --- [  restartedMain] c.e.c.E.v.k.o.d.MotifDeconventionnement  : Close successful.
2017-07-07 14:55:20.592 DEBUG 10056 --- [  restartedMain] c.e.c.E.v.kalivia.osteo.domain.Ville     : Close successful.
2017-07-07 14:55:20.592 DEBUG 10056 --- [  restartedMain] c.e.c.E.v.kalivia.osteo.domain.User      : Close successful.
2017-07-07 14:55:20.592 DEBUG 10056 --- [  restartedMain] c.e.c.E.v.k.osteo.domain.PlsCoordonnees  : Close successful.
2017-07-07 14:55:20.592 DEBUG 10056 --- [  restartedMain] c.e.c.E.v.k.osteo.domain.PlsAdhesion     : Close successful.
2017-07-07 14:55:20.593 DEBUG 10056 --- [  restartedMain] c.e.c.E.v.k.o.d.M.plsAdhesions           : Close successful.
2017-07-07 14:55:20.599 DEBUG 10056 --- [  restartedMain] c.e.c.E.v.k.osteo.domain.ParamOcam       : Close successful.
2017-07-07 14:55:20.599 DEBUG 10056 --- [  restartedMain] c.e.c.E.v.k.o.domain.ParamDureeConsult   : Close successful.
2017-07-07 14:55:20.600 DEBUG 10056 --- [  restartedMain] c.e.c.E.v.k.osteo.domain.PlsStatus       : Close successful.
2017-07-07 14:55:20.600 DEBUG 10056 --- [  restartedMain] c.e.c.E.v.k.o.domain.PlsComplementInfos  : Close successful.
2017-07-07 14:55:20.600 DEBUG 10056 --- [  restartedMain] c.e.c.E.v.k.o.d.User.persistentTokens    : Close successful.
2017-07-07 14:55:20.600 DEBUG 10056 --- [  restartedMain] c.e.c.E.v.k.osteo.domain.PlsContact      : Close successful.
2017-07-07 14:55:20.601 DEBUG 10056 --- [  restartedMain] c.e.c.E.v.kalivia.osteo.domain.Pls       : Close successful.
2017-07-07 14:55:20.601 DEBUG 10056 --- [  restartedMain] c.e.c.E.v.k.o.domain.ParamTypeExercice   : Close successful.
2017-07-07 14:55:20.601 DEBUG 10056 --- [  restartedMain] c.e.c.E.v.k.osteo.domain.ParamZone       : Close successful.
2017-07-07 14:55:20.601 DEBUG 10056 --- [  restartedMain] c.e.c.E.v.k.o.d.P.horairesOuvertures     : Close successful.
2017-07-07 14:55:20.602 ERROR 10056 --- [  restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Destroy method on bean with name 'org.springframework.context.annotation.internalScheduledAnnotationProcessor' threw an exception

java.lang.IllegalStateException: ApplicationEventMulticaster not initialized - call 'refresh' before multicasting events via the context: org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@7d8e76e9: startup date [Fri Jul 07 14:55:14 CEST 2017]; root of context hierarchy
	at org.springframework.context.support.AbstractApplicationContext.getApplicationEventMulticaster(AbstractApplicationContext.java:404)
	at org.springframework.context.support.ApplicationListenerDetector.postProcessBeforeDestruction(ApplicationListenerDetector.java:97)
	at org.springframework.beans.factory.support.DisposableBeanAdapter.destroy(DisposableBeanAdapter.java:253)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroyBean(DefaultSingletonBeanRegistry.java:578)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroySingleton(DefaultSingletonBeanRegistry.java:554)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.destroySingleton(DefaultListableBeanFactory.java:954)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroySingletons(DefaultSingletonBeanRegistry.java:523)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.destroySingletons(DefaultListableBeanFactory.java:961)
	at org.springframework.context.support.AbstractApplicationContext.destroyBeans(AbstractApplicationContext.java:1033)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:555)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:761)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:371)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315)
	at net.viamedis.kalivia.osteo.KaliviaOsteoApp.main(KaliviaOsteoApp.java:77)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.devtools.restart.RestartLauncher.run(RestartLauncher.java:49)

2017-07-07 14:55:20.602 ERROR 10056 --- [  restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Destroy method on bean with name 'org.springframework.boot.context.properties.ConfigurationPropertiesBindingPostProcessor' threw an exception

java.lang.IllegalStateException: ApplicationEventMulticaster not initialized - call 'refresh' before multicasting events via the context: org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@7d8e76e9: startup date [Fri Jul 07 14:55:14 CEST 2017]; root of context hierarchy
	at org.springframework.context.support.AbstractApplicationContext.getApplicationEventMulticaster(AbstractApplicationContext.java:404)
	at org.springframework.context.support.ApplicationListenerDetector.postProcessBeforeDestruction(ApplicationListenerDetector.java:97)
	at org.springframework.beans.factory.support.DisposableBeanAdapter.destroy(DisposableBeanAdapter.java:253)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroyBean(DefaultSingletonBeanRegistry.java:578)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroySingleton(DefaultSingletonBeanRegistry.java:554)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.destroySingleton(DefaultListableBeanFactory.java:954)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroySingletons(DefaultSingletonBeanRegistry.java:523)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.destroySingletons(DefaultListableBeanFactory.java:961)
	at org.springframework.context.support.AbstractApplicationContext.destroyBeans(AbstractApplicationContext.java:1033)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:555)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:761)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:371)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315)
	at net.viamedis.kalivia.osteo.KaliviaOsteoApp.main(KaliviaOsteoApp.java:77)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.devtools.restart.RestartLauncher.run(RestartLauncher.java:49)

2017-07-07 14:55:20.603 ERROR 10056 --- [  restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Destroy method on bean with name 'org.springframework.boot.autoconfigure.internalCachingMetadataReaderFactory' threw an exception

java.lang.IllegalStateException: ApplicationEventMulticaster not initialized - call 'refresh' before multicasting events via the context: org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@7d8e76e9: startup date [Fri Jul 07 14:55:14 CEST 2017]; root of context hierarchy
	at org.springframework.context.support.AbstractApplicationContext.getApplicationEventMulticaster(AbstractApplicationContext.java:404)
	at org.springframework.context.support.ApplicationListenerDetector.postProcessBeforeDestruction(ApplicationListenerDetector.java:97)
	at org.springframework.beans.factory.support.DisposableBeanAdapter.destroy(DisposableBeanAdapter.java:253)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroyBean(DefaultSingletonBeanRegistry.java:578)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroySingleton(DefaultSingletonBeanRegistry.java:554)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.destroySingleton(DefaultListableBeanFactory.java:954)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroySingletons(DefaultSingletonBeanRegistry.java:523)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.destroySingletons(DefaultListableBeanFactory.java:961)
	at org.springframework.context.support.AbstractApplicationContext.destroyBeans(AbstractApplicationContext.java:1033)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:555)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:761)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:371)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315)
	at net.viamedis.kalivia.osteo.KaliviaOsteoApp.main(KaliviaOsteoApp.java:77)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.devtools.restart.RestartLauncher.run(RestartLauncher.java:49)

2017-07-07 14:55:20.610 ERROR 10056 --- [  restartedMain] o.s.b.d.LoggingFailureAnalysisReporter   : 

***************************
APPLICATION FAILED TO START
***************************

Description:

The bean 'dataSource' could not be injected as a 'com.zaxxer.hikari.HikariDataSource' because it is a JDK dynamic proxy that implements:
	javax.sql.DataSource
	java.io.Closeable

Action:

Consider injecting the bean as one of its interfaces or forcing the use of CGLib-based proxies by setting proxyTargetClass=true on @EnableAsync and/or @EnableCaching.

**Comment by PierreBesson** [comment]
This ticket has been closed as the guidelines are not followed.

Tickets must follow our [Guidelines](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md#submitting-an-issue), as mentioned in:

1. our [Readme file on the front page of the project](https://github.com/jhipster/generator-jhipster/blob/master/README.md), 
2. the ["create a new ticket" page](https://github.com/jhipster/generator-jhipster/issues/new) and
3. our [Help page](http://jhipster.github.io/help/)

---
Please use this tracker only for bugs about JHipster itself not third party tools.

**Comment by jdubois** [comment]
@khdaddou please use Stackoverflow for general dev questions, this is the bug tracker
