### ISSUE TITLE
Webpack fails to build when having the ! String in the path

### ISSUE THREAD

**Issue by mcka-dev** [jhipster/generator-jhipster#6203]
##### **Overview of the issue**

Error when creating a new project. 
The error occurs if I run `yo jhipster` from directory `d:\!Test` (with `!`) then the application does not work.
Successful launch if I run `yo jhipster` from directory `d:\Test` (without symbol `!`) then the application is successfully functioning.

Errors:
```
[./..!./Test/src/main/webapp/manifest.webapp] ./src/main/webapp/manifest.webapp 2.86 kB {2} [built] [failed] [1 error]
       [] -> factory:969ms building:451ms = 1420ms
    + 627 hidden modules

ERROR in   Error: Child compilation failed:
  Entry module not found: Error: Can't resolve 'Test\Test\src\main\webapp\index.html' in 'd:\!Test':
  Error: Can't resolve 'Test\Test\src\main\webapp\index.html' in 'd:\!Test'

  - compiler.js:76
    [!Test]/[html-webpack-plugin]/lib/compiler.js:76:16

  - Compiler.js:304 compile
    [!Test]/[webpack]/lib/Compiler.js:304:11

  - Compiler.js:520 applyPluginsAsync.err
    [!Test]/[webpack]/lib/Compiler.js:520:14

  - Tapable.js:202 next
    [!Test]/[tapable]/lib/Tapable.js:202:11

  - CachePlugin.js:62 Compiler.<anonymous>
    [!Test]/[webpack]/lib/CachePlugin.js:62:5

  - Tapable.js:206 Compiler.applyPluginsAsyncSeries
    [!Test]/[tapable]/lib/Tapable.js:206:13

  - Compiler.js:517 compilation.seal.err
    [!Test]/[webpack]/lib/Compiler.js:517:11

  - Tapable.js:195 Compilation.applyPluginsAsyncSeries
    [!Test]/[tapable]/lib/Tapable.js:195:46

  - Compilation.js:654 self.applyPluginsAsync.err
    [!Test]/[webpack]/lib/Compilation.js:654:19

  - Tapable.js:195 Compilation.applyPluginsAsyncSeries
    [!Test]/[tapable]/lib/Tapable.js:195:46

  - Compilation.js:645 self.applyPluginsAsync.err
    [!Test]/[webpack]/lib/Compilation.js:645:11

  - Tapable.js:195 Compilation.applyPluginsAsyncSeries
    [!Test]/[tapable]/lib/Tapable.js:195:46

  - Compilation.js:640 self.applyPluginsAsync.err
    [!Test]/[webpack]/lib/Compilation.js:640:10

  - Tapable.js:195 Compilation.applyPluginsAsyncSeries
    [!Test]/[tapable]/lib/Tapable.js:195:46

  - Compilation.js:636 sealPart2
    [!Test]/[webpack]/lib/Compilation.js:636:9

  - Tapable.js:195 Compilation.applyPluginsAsyncSeries
    [!Test]/[tapable]/lib/Tapable.js:195:46

  - Compilation.js:579 Compilation.seal
    [!Test]/[webpack]/lib/Compilation.js:579:8

  - Compiler.js:514 applyPluginsParallel.err
    [!Test]/[webpack]/lib/Compiler.js:514:17

  - Tapable.js:289
    [!Test]/[tapable]/lib/Tapable.js:289:11

  - Compilation.js:481 _addModuleChain
    [!Test]/[webpack]/lib/Compilation.js:481:11

  - Compilation.js:370 Compilation.errorAndCallback
    [!Test]/[webpack]/lib/Compilation.js:370:4

  - Compilation.js:391 moduleFactory.create
    [!Test]/[webpack]/lib/Compilation.js:391:12

  - NormalModuleFactory.js:247 factory
    [!Test]/[webpack]/lib/NormalModuleFactory.js:247:20

  - NormalModuleFactory.js:65 resolver
    [!Test]/[webpack]/lib/NormalModuleFactory.js:65:21

  - NormalModuleFactory.js:138 asyncLib.parallel.e
    [!Test]/[webpack]/lib/NormalModuleFactory.js:138:21

  - async.js:3861
    [!Test]/[webpack]/[async]/dist/async.js:3861:9

  - async.js:421
    [!Test]/[webpack]/[async]/dist/async.js:421:16

  - async.js:996 iteratorCallback
    [!Test]/[webpack]/[async]/dist/async.js:996:13

  - async.js:906
    [!Test]/[webpack]/[async]/dist/async.js:906:16

  - async.js:3858
    [!Test]/[webpack]/[async]/dist/async.js:3858:13



ERROR in ./src/main/webapp/content/css/global.css
Module not found: Error: Can't resolve '../../../../../..' in 'd:\!Test\src\main\webapp\content\css'
 @ ./src/main/webapp/content/css/global.css 4:14-144

ERROR in ./src/main/webapp/content/css/global.css
Module not found: Error: Can't resolve '../../../../../..' in 'd:\!Test\src\main\webapp\content\css'
 @ ./src/main/webapp/content/css/global.css 12:13-90

ERROR in ./src/main/webapp/app/blocks/config/prod.config.ts
Module not found: Error: Can't resolve 'd:\' in 'd:\!Test'
 @ ./src/main/webapp/app/blocks/config/prod.config.ts 4:22-52
 @ ./src/main/webapp/app/app.main.ts

ERROR in ./src/main/webapp/content/css/vendor.css
Module not found: Error: Can't resolve 'Test/node_modules/css-loader/index.js' in 'd:\!Test\src\main\webapp\content\css'
 @ ./src/main/webapp/content/css/vendor.css 4:14-144
 @ ./src/main/webapp/app/vendor.ts
 @ ./src/main/webapp/app/app.module.ts
 @ ./src/main/webapp/app/app.main.ts

ERROR in ./src/main/webapp/content/css/vendor.css
Module not found: Error: Can't resolve '../../../../../..' in 'd:\!Test\src\main\webapp\content\css'
 @ ./src/main/webapp/content/css/vendor.css 12:13-90
 @ ./src/main/webapp/app/vendor.ts
 @ ./src/main/webapp/app/app.module.ts
 @ ./src/main/webapp/app/app.main.ts

ERROR in ./src/main/webapp/manifest.webapp
Module not found: Error: Can't resolve 'd:\' in 'd:\!Test\src\main\webapp'
 @ ./src/main/webapp/manifest.webapp
 @ ./src/main/webapp/app/polyfills.ts

ERROR in ./src/main/webapp/manifest.webapp
Module not found: Error: Can't resolve 'd:\' in 'd:\!Test\src\main\webapp'
 @ ./src/main/webapp/manifest.webapp
 @ ./src/main/webapp/app/polyfills.ts

ERROR in ./src/main/webapp/manifest.webapp
Module not found: Error: Can't resolve 'd:\' in 'd:\!Test\src\main\webapp'
 @ ./src/main/webapp/manifest.webapp
 @ ./src/main/webapp/app/polyfills.ts

ERROR in ./src/main/webapp/manifest.webapp
Module not found: Error: Can't resolve 'd:\' in 'd:\!Test\src\main\webapp'
 @ ./src/main/webapp/manifest.webapp
 @ ./src/main/webapp/app/polyfills.ts

ERROR in ./src/main/webapp/manifest.webapp
Module build failed: ModuleNotFoundError: Module not found: Error: Can't resolve 'd:\' in 'd:\!Test\src\main\webapp'
    at factoryCallback (d:\!Test\node_modules\webpack\lib\Compilation.js:264:39)
    at factory (d:\!Test\node_modules\webpack\lib\NormalModuleFactory.js:247:20)
    at resolver (d:\!Test\node_modules\webpack\lib\NormalModuleFactory.js:65:21)
    at asyncLib.parallel.e (d:\!Test\node_modules\webpack\lib\NormalModuleFactory.js:138:21)
    at d:\!Test\node_modules\webpack\node_modules\async\dist\async.js:3861:9
    at d:\!Test\node_modules\webpack\node_modules\async\dist\async.js:421:16
    at iteratorCallback (d:\!Test\node_modules\webpack\node_modules\async\dist\async.js:996:13)
    at d:\!Test\node_modules\webpack\node_modules\async\dist\async.js:906:16
    at d:\!Test\node_modules\webpack\node_modules\async\dist\async.js:3858:13
    at d:\!Test\node_modules\webpack\node_modules\async\dist\async.js:1074:9
    at d:\!Test\node_modules\webpack\node_modules\async\dist\async.js:421:16
    at iteratorCallback (d:\!Test\node_modules\webpack\node_modules\async\dist\async.js:996:13)
    at d:\!Test\node_modules\webpack\node_modules\async\dist\async.js:906:16
    at d:\!Test\node_modules\webpack\node_modules\async\dist\async.js:1071:13
    at resolver.resolve.err2 (d:\!Test\node_modules\webpack\lib\NormalModuleFactory.js:270:7)
    at onError (d:\!Test\node_modules\enhanced-resolve\lib\Resolver.js:65:10)
    at loggingCallbackWrapper (d:\!Test\node_modules\enhanced-resolve\lib\createInnerCallback.js:31:19)
    at runAfter (d:\!Test\node_modules\enhanced-resolve\lib\Resolver.js:158:4)
    at innerCallback (d:\!Test\node_modules\enhanced-resolve\lib\Resolver.js:146:3)
    at loggingCallbackWrapper (d:\!Test\node_modules\enhanced-resolve\lib\createInnerCallback.js:31:19)
    at next (d:\!Test\node_modules\tapable\lib\Tapable.js:252:11)
    at d:\!Test\node_modules\enhanced-resolve\lib\UnsafeCachePlugin.js:40:4
    at loggingCallbackWrapper (d:\!Test\node_modules\enhanced-resolve\lib\createInnerCallback.js:31:19)
    at runAfter (d:\!Test\node_modules\enhanced-resolve\lib\Resolver.js:158:4)
    at innerCallback (d:\!Test\node_modules\enhanced-resolve\lib\Resolver.js:146:3)
    at loggingCallbackWrapper (d:\!Test\node_modules\enhanced-resolve\lib\createInnerCallback.js:31:19)
    at next (d:\!Test\node_modules\tapable\lib\Tapable.js:252:11)
    at innerCallback (d:\!Test\node_modules\enhanced-resolve\lib\Resolver.js:144:11)
    at loggingCallbackWrapper (d:\!Test\node_modules\enhanced-resolve\lib\createInnerCallback.js:31:19)
    at next (d:\!Test\node_modules\tapable\lib\Tapable.js:249:35)
 @ ./src/main/webapp/app/polyfills.ts 6:0-29

ERROR in ./src/main/webapp/app/layouts/navbar/navbar.component.ts
Module not found: Error: Can't resolve 'd:\' in 'd:\!Test'
 @ ./src/main/webapp/app/layouts/navbar/navbar.component.ts 17:22-52
 @ ./src/main/webapp/app/layouts/index.ts
 @ ./src/main/webapp/app/app.module.ts
 @ ./src/main/webapp/app/app.main.ts

ERROR in ./src/main/webapp/app/home/home.css
Module not found: Error: Can't resolve 'Test/node_modules/css-loader/index.js' in 'd:\!Test\src\main\webapp\app\home'
 @ ./src/main/webapp/app/home/home.css 2:21-146
 @ ./src/main/webapp/app/home/home.component.ts
 @ ./src/main/webapp/app/home/index.ts
 @ ./src/main/webapp/app/home/home.module.ts
 @ ./src/main/webapp/app/app.module.ts
 @ ./src/main/webapp/app/app.main.ts

ERROR in ./src/main/webapp/app/layouts/navbar/navbar.css
Module not found: Error: Can't resolve 'Test/node_modules/css-loader/index.js' in 'd:\!Test\src\main\webapp\app\layouts\navbar'
 @ ./src/main/webapp/app/layouts/navbar/navbar.css 2:21-164
 @ ./src/main/webapp/app/layouts/navbar/navbar.component.ts
 @ ./src/main/webapp/app/layouts/index.ts
 @ ./src/main/webapp/app/app.module.ts
 @ ./src/main/webapp/app/app.main.ts

ERROR in ./src/main/webapp/app/layouts/profiles/page-ribbon.css
Module not found: Error: Can't resolve 'Test/node_modules/css-loader/index.js' in 'd:\!Test\src\main\webapp\app\layouts\profiles'
 @ ./src/main/webapp/app/layouts/profiles/page-ribbon.css 2:21-171
 @ ./src/main/webapp/app/layouts/profiles/page-ribbon.component.ts
 @ ./src/main/webapp/app/layouts/index.ts
 @ ./src/main/webapp/app/app.module.ts
 @ ./src/main/webapp/app/app.main.ts

ERROR in ./src/main/webapp/app/account/password/password-strength-bar.css
Module not found: Error: Can't resolve 'Test/node_modules/css-loader/index.js' in 'd:\!Test\src\main\webapp\app\account\password'
 @ ./src/main/webapp/app/account/password/password-strength-bar.css 2:21-181
 @ ./src/main/webapp/app/account/password/password-strength-bar.component.ts
 @ ./src/main/webapp/app/account/index.ts
 @ ./src/main/webapp/app/account/account.module.ts
 @ ./src/main/webapp/app/app.module.ts
 @ ./src/main/webapp/app/app.main.ts
error Command failed with exit code 2.
error Command failed with exit code 1.
error Command failed with exit code 1.
```

##### **Reproduce the error**

Run `cmd.exe`
```
d:
mkdir !Test
cd !Test
copy d:\PATH_TO_MY_CONFIGURATION\.yo-rc.json .yo-rc.json
yo jhipster
// here we will get an error.
```

##### **Related issues**

The directory name affects the build. 

##### **JHipster Version(s)**
v4.6.2

##### **Package Version(s)**
npm -v
5.3.0

node -v
v6.11.2

##### **JHipster configuration**
`.yo-rc.json` file:
```
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.example.app",
      "nativeLanguage": "ru"
    },
    "jhipsterVersion": "4.6.2",
    "baseName": "MyApp",
    "packageName": "com.example.app",
    "packageFolder": "com/example/app",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Memory",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "jwtSecretKey": "3707529474a2aa8ee00ccad0606e6a4cb1528e2e",
    "clientFramework": "angularX",
    "useSass": false,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "otherModules": [
      {
        "name": "generator-jhipster-bootstrap-material-design",
        "version": "3.5.1"
      },
      {
        "name": "generator-jhipster-google-maps",
        "version": "0.0.1"
      }
    ],
    "enableTranslation": true,
    "nativeLanguage": "ru",
    "languages": [
      "ru"
    ]
  }
}
```

##### **Browsers and Operating System**
Windows 10.0.15063 x64 
File System: NTFS

**Comment by gmarziou** [comment]
Excuse my ignorance but is there any special meaning of `!` in file paths in Windows?
Have you been to run successfully other node commands with this unusual path?

**Comment by mcka-dev** [comment]
for Windows `d:\!Test` this is the usual path.
![2017-08-05 19_49_18-works d_](https://user-images.githubusercontent.com/16173503/28997197-52b5f186-7a17-11e7-89b3-bbe521e6f2d6.png)
All other commands work perfectly in this directory.

**Comment by mcka-dev** [comment]
I decided to check on `Debian 9` and I got the same error:
![2017-08-05 20_18_29-debian eng x86-64 - oracle vm virtualbox](https://user-images.githubusercontent.com/16173503/28997390-c7b7ba7e-7a1b-11e7-969e-42af7450ac27.png)
![2017-08-05 20_20_05-debian eng x86-64 - oracle vm virtualbox](https://user-images.githubusercontent.com/16173503/28997391-c7b88b84-7a1b-11e7-8deb-bfcda4467fe2.png)

**Comment by mcka-dev** [comment]
Reproduce the error on Debian 9:
![2017-08-05 20_30_44-debian eng x86-64 - oracle vm virtualbox](https://user-images.githubusercontent.com/16173503/28997455-f979ac8c-7a1d-11e7-8e64-fc5a28280305.png)

As a result, an error occurred:
![2017-08-05 20_38_52-debian eng x86-64 - oracle vm virtualbox](https://user-images.githubusercontent.com/16173503/28997466-23b1838a-7a1e-11e7-8791-e2fdeea2c7e1.png)

**Comment by mcka-dev** [comment]
I checked this:
```
osboxes@osboxes:~/Downloads$ mkdir path\ with\ spaces
osboxes@osboxes:~/Downloads$ cd path\ with\ spaces/
osboxes@osboxes:~/Downloads/path with spaces$ yo jhipster
```
It's perfect to work!

**Comment by delverdev** [comment]
Earlier I had a project that was started by `!` and it was working (version ~3.5).

**Comment by jdubois** [comment]
Could you write a better title? This seems linked to having the `!` String in the path, and might be caused by Node or npm

**Comment by mcka-dev** [comment]
@delverde I verified `generator-jhipster@3.5.0` It's perfect to work!
Also `generator-jhipster@4.6.2`  It's perfect to work if you choose: 
`? (12/16) Which *Framework* would you like to use for the client?` *AngularJS 1.x*.
The problem is only if you choose *Angular 4*.

**Comment by deepu105** [comment]
This seems like something going wrong during webpack compilation. `!` is used in glob patterns as negation and I'm wondering if this might be causing an issue. But Its hard to tell just from the logs here.

@mcka-dev can you try to run any [angular-webpack](https://github.com/AngularClass/angular-starter) starter from such a folder?

**Comment by mcka-dev** [comment]
@deepu105 The problem is present in `angular-webpack` if starter from such a folder.
![2017-08-05 23_21_50-c__windows_system32_cmd exe](https://user-images.githubusercontent.com/16173503/28998511-9fc86f30-7a35-11e7-9404-1973ee3ea735.png)

**Comment by deepu105** [comment]
So this is definitely either a webpack or typescript issue. I guess you should open a ticket for this in Webpack.
@TheLarkinn do you think this is coming from webpack?

**Comment by gmarziou** [comment]
> for Windows d:\!Test this is the usual path.

I don't understand this sentence, is it a convention of your company or is it widely used in some community and what is the benefit?

**Comment by mcka-dev** [comment]
@gmarziou I did nothing against law. I use for to appear first in directory listing by name. 

Allowed characters in file or directory names for file systems
**NTFS**: any [UTF-16](https://en.wikipedia.org/wiki/UTF-16) code unit (case-insensitive) except `/\:*"?<>|` as well as `NUL`.
**ext4**:  All bytes except `NUL` and `/` and the special file names `.` and `..` which are not forbidden but are always used for a respective special purpose.

**Comment by sendilkumarn** [comment]
@mcka-dev 
This is because webpack will not allow you to have a `!` in the file path. There is an option to separate loaders with `!` 

Note: In 3.5 we don't have webpack, we only had gulp so yes we were able to create an application in a folder with `!` in it.

I am wondering why this is being discussed here.  🤔

**Comment by mcka-dev** [comment]
@sendilkumarn `jhipster` could not build a project, we did not immediately realize that the problem is in `Webpack`.
