### ISSUE TITLE
Cyclic dependency: "[object Object]"

### ISSUE THREAD

**Issue by yarax** [jhipster/generator-jhipster#6455]
Hi!

During the installation of bootstrap app (jhipster command) I'm getting the error
```
[at-loader] Checking started in a separate process...

[at-loader] Ok, 0.105 sec.
Unhandled rejection Error: Cyclic dependency: "[object Object]"
    at visit (/home/roman/cocomore/node_modules/toposort/index.js:32:13)
    at visit (/home/roman/cocomore/node_modules/toposort/index.js:48:9)
    at Function.toposort [as array] (/home/roman/cocomore/node_modules/toposort/index.js:25:22)
```
```
node -v
v8.1.4
cat /proc/version
Linux version 4.4.0-96-generic (buildd@lgw01-10) (gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.4) ) #119-Ubuntu SMP Tue Sep 12 14:59:54 UTC 2017
```

**Comment by mraible** [comment]
Can you please try with Node 6.11? That's the latest version we've tested with extensively.

**Comment by yarax** [comment]
I guess the problem was having jhipster project being installed in the parent directory, I created one more nested one and it finished without errors. 
But thanks for the answer, maybe this issue will help someone else
