### ISSUE TITLE
Cyclic dependency: "[object Object]" When Generating a new JHipster project

### ISSUE THREAD

**Issue by kyeljmd** [jhipster/generator-jhipster#6457]
##### **Overview of the issue**

I started to generate   a project using jhipster, after selecting in the approriate options. I proceeded and waited for the application generation to finish. Here's the stacktrace generated by the build.

```
Unhandled rejection Error: Cyclic dependency: "[object Object]"
    at visit (C:\Users\kyel\projects\triumphlife\node_modules\toposort\index.js:32:13)
    at visit (C:\Users\kyel\projects\triumphlife\node_modules\toposort\index.js:48:9)
    at Function.toposort [as array] (C:\Users\kyel\projects\triumphlife\node_modules\toposort\index.js:25:22)
    at Object.module.exports.dependency (C:\Users\kyel\projects\triumphlife\node_modules\html-webpack-plugin\lib\chunksorter.js:55:19)
    at HtmlWebpackPlugin.sortChunks (C:\Users\kyel\projects\triumphlife\node_modules\html-webpack-plugin\index.js:347:33)
    at Compiler.<anonymous> (C:\Users\kyel\projects\triumphlife\node_modules\html-webpack-plugin\index.js:72:19)
    at next (C:\Users\kyel\projects\triumphlife\node_modules\tapable\lib\Tapable.js:204:14)
    at callback (C:\Users\kyel\projects\triumphlife\node_modules\copy-webpack-plugin\dist\index.js:71:17)
    at Object.finallyHandler (C:\Users\kyel\projects\triumphlife\node_modules\copy-webpack-plugin\node_modules\bluebird\js\main\finally.js:39:23)
    at Object.tryCatcher (C:\Users\kyel\projects\triumphlife\node_modules\copy-webpack-plugin\node_modules\bluebird\js\main\util.js:26:23)
    at Promise._settlePromiseFromHandler (C:\Users\kyel\projects\triumphlife\node_modules\copy-webpack-plugin\node_modules\bluebird\js\main\promise.js:510:31)
    at Promise._settlePromiseAt (C:\Users\kyel\projects\triumphlife\node_modules\copy-webpack-plugin\node_modules\bluebird\js\main\promise.js:584:18)
    at Promise._settlePromises (C:\Users\kyel\projects\triumphlife\node_modules\copy-webpack-plugin\node_modules\bluebird\js\main\promise.js:700:14)
    at Async._drainQueue (C:\Users\kyel\projects\triumphlife\node_modules\copy-webpack-plugin\node_modules\bluebird\js\main\async.js:123:16)
    at Async._drainQueues (C:\Users\kyel\projects\triumphlife\node_modules\copy-webpack-plugin\node_modules\bluebird\js\main\async.js:133:10)
    at Immediate.Async.drainQueues (C:\Users\kyel\projects\triumphlife\node_modules\copy-webpack-plugin\node_modules\bluebird\js\main\async.js:15:14)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
```

##### **Motivation for or Use Case**

This is the bug since I've followed all of the necessary steps when generatin an app. and I believe I have the latest dependencies installed.

node 
v 6.11.3

yarn v1.1.0

##### **Reproduce the error**

Enter JHipster command and wait for the project to generate completely and wait for the build to finish

##### **JHipster Version(s)**

JHipster version 4.9.0

`##### **JHipster Version(s)**

```
triumphlife@0.0.0 C:\Users\kyel\projects\triumphlife
+-- generator-jhipster@4.9.0
`-- UNMET PEER DEPENDENCY popper.js@^1.11.0

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.corpio.triumphlife"
    },
    "jhipsterVersion": "4.9.0",
    "baseName": "triumphlife",
    "packageName": "com.corpio.triumphlife",
    "packageFolder": "com/corpio/triumphlife",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "postgresql",
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSocialSignIn": true,
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "replaced-by-jhipster-info",
    "clientFramework": "angularX",
    "useSass": false,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": false
  }
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_121"
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)

git version 2.9.0.windows.1

node: v6.11.3

npm: 3.10.10

yeoman: 2.0.0

yarn: 1.1.0

Docker version 17.04.0-ce, build 4845c56

docker-compose version 1.12.0, build ee0f34e1`
##### **Browsers and Operating System**

I'm on windows 10

- [X] Checking this box is mandatory (this is just to show you read everything)

**Comment by jdubois** [comment]
I just generated an application with your `.yo-rc.json` file and had no problem at all... Did you see any error when generating, for example a network error? You could try deleting your `node_modules`, but if you use Yarn that shouldn't do much difference.
And you haven't done anything else than generating the application? No entity at all?

**Comment by jdubois** [comment]
Closing as we don't have enough info to reproduce.
