### ISSUE TITLE
gradle build after generation does not work.

### ISSUE THREAD

**Issue by Mazorius** [jhipster/generator-jhipster#6503]
##### **Overview of the issue**

Running:

```
./gradlew
```

directly after generation of a microservice gateway fails.
Stacktrace:
```
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'cluster' defined in class path resource [org/springframework/boot/autoconfigure/cassandra/CassandraAutoConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.datastax.driver.core.Cluster]: Factory method 'cluster' threw exception; nested exception is java.lang.NoClassDefFoundError: com/google/common/util/concurrent/FutureFallback
        at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:599)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1173)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1067)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:513)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:483)
        at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:761)
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:867)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:543)
        at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122)
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:693)
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:360)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:303)
        at my.company.TestApp.main(TestApp.java:71)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.boot.devtools.restart.RestartLauncher.run(RestartLauncher.java:49)
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.datastax.driver.core.Cluster]: Factory method 'cluster' threw exception; nested exception is java.lang.NoClassDefFoundError: com/google/common/util/concurrent/FutureFallback
        at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:189)
        at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:588)
        ... 21 common frames omitted
Caused by: java.lang.NoClassDefFoundError: com/google/common/util/concurrent/FutureFallback
        at org.springframework.boot.autoconfigure.cassandra.CassandraAutoConfiguration.cluster(CassandraAutoConfiguration.java:66)
        at org.springframework.boot.autoconfigure.cassandra.CassandraAutoConfiguration$$EnhancerBySpringCGLIB$$2708c5d5.CGLIB$cluster$0(<generated>)
        at org.springframework.boot.autoconfigure.cassandra.CassandraAutoConfiguration$$EnhancerBySpringCGLIB$$2708c5d5$$FastClassBySpringCGLIB$$d3ca9fb8.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228)
        at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:358)
        at org.springframework.boot.autoconfigure.cassandra.CassandraAutoConfiguration$$EnhancerBySpringCGLIB$$2708c5d5.cluster(<generated>)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:162)
        ... 22 common frames omitted
Caused by: java.lang.ClassNotFoundException: com.google.common.util.concurrent.FutureFallback
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 33 common frames omitted
```

##### **Motivation for or Use Case**

I think a fresh generated application should work without the need of fixing issues.

##### **Reproduce the error**

1. Run `jhipster app`
2. Set following configuration
```
Welcome to the JHipster Generator v4.9.0
Documentation for creating an application: http://www.jhipster.tech/creating-an-app/
Application files will be generated in folder: /Users/rog/Software/workspace/him/test/test
? (1/16) Which *type* of application would you like to create? Microservice gateway
? (2/16) What is the base name of your application? test
? (3/16) As you are running in a microservice architecture, on which port would like your server to run? It should be unique to avoid port conflicts. 8080
? (4/16) What is your default Java package name? my.company
? (5/16) Do you want to use the JHipster Registry to configure, monitor and scale your microservices and gateways? Yes
? (6/16) Which *type* of authentication would you like to use? Authentication with JHipster UAA server (the server must be generated separately)
? (7/16) What is the folder path of your UAA application? ../uaa
? (8/16) Which *type* of database would you like to use? MongoDB
? (9/16) Would you like to use Maven or Gradle for building the backend? Gradle
? (10/16) Which other technologies would you like to use? API first development using swagger-codegen
? (11/16) Which *Framework* would you like to use for the client? Angular 4
? (12/16) Would you like to use the LibSass stylesheet preprocessor for your CSS? No
? (13/16) Would you like to enable internationalization support? Yes
? Please choose the native language of the application German
? Please choose additional languages to install English
? (14/16) Besides JUnit and Karma, which testing frameworks would you like to use? 
? (15/16) Would you like to install other generators from the JHipster Marketplace? No
```
3. Run './gradlew'

##### **Related issues**

I do not found one.

##### **Suggest a Fix**

The version of guava should be changed from 23 to 19.
After that it works well.

##### **JHipster Version(s)**

```
Using JHipster version installed globally
4.9.0
```
##### **JHipster configuration**

Using JHipster version installed locally in current project's node_modules
Executing jhipster:info
Options: 
Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
test@0.0.0 *
└── generator-jhipster@4.9.0 

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "my.company",
      "nativeLanguage": "de"
    },
    "jhipsterVersion": "4.9.0",
    "baseName": "test",
    "packageName": "my.company",
    "packageFolder": "my/company",
    "serverPort": "8080",
    "authenticationType": "uaa",
    "uaaBaseName": "uaa",
    "hibernateCache": "hazelcast",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "mongodb",
    "devDatabaseType": "mongodb",
    "prodDatabaseType": "mongodb",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": "eureka",
    "buildTool": "gradle",
    "enableSocialSignIn": false,
    "enableSwaggerCodegen": true,
    "clientFramework": "angularX",
    "useSass": false,
    "clientPackageManager": "yarn",
    "applicationType": "gateway",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "de",
    "languages": [
      "de",
      "en"
    ]
  }
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_144"
Java(TM) SE Runtime Environment (build 1.8.0_144-b01)
Java HotSpot(TM) 64-Bit Server VM (build 25.144-b01, mixed mode)

git version 2.14.2

node: v8.6.0

npm: 5.3.0

bower: 1.8.2

gulp:
[16:02:16] CLI version 1.4.0

yeoman: 2.0.0

yarn: 1.2.0

Docker version 17.09.0-ce, build afdb6d4

docker-compose version 1.16.1, build 6d1ac21

Execution complete

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

I did do nothing with jdl

##### **Browsers and Operating System**

MacBook Pro (Retina, 15', Mitte 2015)
High Sierra: 10.13 (17A405)

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by Mazorius** [comment]
I'm very sure.

I run directly after creating the project `./gradlew`.
During compilation the error occurs.

**Comment by jdubois** [comment]
This does not make any sense, you have an issue with `CassandraAutoConfiguration` but selected MongoDB! I need to test with your config.

**Comment by cbornet** [comment]
There is also hazelcast `hibernateCache` with mongoDB ?

**Comment by cbornet** [comment]
@jdubois isn't there cassandra in the gateway for the rate limiting filter ?

**Comment by jdubois** [comment]
@cbornet not any more, since we use Bucket4J. Maybe we did a bug there. Best test is to generate an app with the config and test.

**Comment by jdubois** [comment]
And I confirm your issue! I'm having a look

**Comment by Mazorius** [comment]
Thank you @jdubois 👍 

I look forward to your solution. :)

**Comment by jdubois** [comment]
I'm fixing this, it will be in the next release, thanks a lot!!!!

**Comment by jdubois** [comment]
I totally messed up my commit message, so here it is: https://github.com/jhipster/generator-jhipster/commit/1e4730c7a385e207222c7229646a2b0f994f4e2a
And I'm closing this manually (and should get some sleep!)

**Comment by Mazorius** [comment]
Have a good night ;-)

Thanks a lot!
