### ISSUE TITLE
error when importing JDL entities

### ISSUE THREAD

**Issue by lucaGazzola** [jhipster/generator-jhipster#6524]
Hello, using the command  `jhipster import-jdl jdl-entities.h -debug` what I obtain is the following error:

```
Using JHipster version installed locally in current project's node_modules
DEBUG!  cmd: import-jdl
DEBUG!  args: jdl-entities.h, commands: Object, options: Object, _execs: Object, _allowUnknownOption: true, _args: Object, _name: import-jdl, _noHelp: false, parent: Object, _description: Create entities from the JDL file passed in argument, _events: Object, _eventsCount: 1
DEBUG!  opts: argument: Object, desc: Create entities from the JDL file passed in argument
DEBUG!  Arguments found
DEBUG!  cmdArgs: jdl-entities.h
Executing jhipster:import-jdl jdl-entities.h
Options: d: true, e: true, b: true, u: true, g: true
The jdl is being parsed.
events.js:182
      throw er; // Unhandled 'error' event
      ^

Error: ERROR! 
Error while parsing entities from JDL

    at Environment.error (/home/gianni/work/microservices/blog/node_modules/yeoman-environment/lib/environment.js:157:40)
    at module.exports.error (/home/gianni/work/microservices/blog/node_modules/generator-jhipster/generators/generator-base.js:1676:18)
    at module.exports.parseJDL (/home/gianni/work/microservices/blog/node_modules/generator-jhipster/generators/import-jdl/index.js:105:26)
    at Object.<anonymous> (/home/gianni/work/microservices/blog/node_modules/yeoman-generator/lib/index.js:399:25)
    at /home/gianni/work/microservices/blog/node_modules/run-async/index.js:25:25
    at Promise (<anonymous>)
    at /home/gianni/work/microservices/blog/node_modules/run-async/index.js:24:19
    at self.env.runLoop.add.completed (/home/gianni/work/microservices/blog/node_modules/yeoman-generator/lib/index.js:400:11)
    at runCallback (timers.js:781:20)
    at tryOnImmediate (timers.js:743:5)

```
this is the entity file I am using:

```
entity Blog {
    name String required minlength(3),
    handle String required minlength(2)
}

entity Entry {
    title String required,
    content TextBlob required,
    date ZonedDateTime required
}

entity Tag {
    name String required minlength(2)
}

relationship ManyToOne {
    Blog{user(login)} to User,
    Entry{blog(name)} to Blog
}

relationship ManyToMany {
    Entry{tag(name)} to Tag{entry}
}

paginate Entry, Tag with infinite-scroll
```
and this is what jhipster info shows:

```
Using JHipster version installed locally in current project's node_modules
Executing jhipster:info
Options: 
Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

blog@0.0.0 /home/gianni/work/microservices/blog
└── generator-jhipster@4.9.0 

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**


<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "org.jhipster.blog",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "4.9.0",
    "baseName": "blog",
    "packageName": "org.jhipster.blog",
    "packageFolder": "org/jhipster/blog",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "hazelcast",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "postgresql",
    "searchEngine": "elasticsearch",
    "messageBroker": false,
    "serviceDiscoveryType": "eureka",
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "replaced-by-jhipster-info",
    "clientFramework": "angularX",
    "useSass": true,
    "clientPackageManager": "yarn",
    "applicationType": "gateway",
    "testFrameworks": [
      "gatling",
      "protractor"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en",
      "es"
    ]
  }
}
</pre>
</details>


##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>





</pre>
</details>


##### **Environment and Tools**

java version "1.8.0_144"
Java(TM) SE Runtime Environment (build 1.8.0_144-b01)
Java HotSpot(TM) 64-Bit Server VM (build 25.144-b01, mixed mode)

git version 2.7.4

node: v8.4.0

npm: 5.4.2

bower: 1.8.2

gulp:
[13:30:39] CLI version 1.4.0

yeoman: 2.0.0

yarn: 1.1.0

Docker version 17.09.0-ce, build afdb6d4

docker-compose version 1.8.0, build unknown

Execution complete

```

**Comment by deepu105** [comment]
`jdl-entities.h` is not a valid file name, valid extensions are `.jh` and `.jdl` also its not `-debug` its `--debug`
