### ISSUE TITLE
yarn start issue

### ISSUE THREAD

**Issue by alexsintoni** [jhipster/generator-jhipster#6582]
##### **Overview of the issue**

When I run "yarn start" I get the following error:
```
yarn start
yarn run v1.2.1
$ yarn run webpack:dev
warning From Yarn 1.0 onwards, scripts don't require "--" for options to be forwarded. In a future version, any explicit "--" will be forwarded as-is to the scripts.
 10% building modules 3/3 modules 0 active[HPM] Proxy created: [ '/api',
  '/management',
  '/swagger-resources',
  '/v2/api-docs',
  '/h2-console',
  '/auth' ]  ->  http://127.0.0.1:8080
events.js:182
      throw er; // Unhandled 'error' event
      ^

Error: watch target/www ENOSPC
    at _errnoException (util.js:1019:11)
    at FSWatcher.start (fs.js:1383:19)
    at Object.fs.watch (fs.js:1409:11)
    at createFsWatchInstance (/home/alex/Development/workspace/java/jqhipster-v4.10.0/node_modules/chokidar/lib/nodefs-handler.js:37:15)
    at setFsWatchListener (/home/alex/Development/workspace/java/jqhipster-v4.10.0/node_modules/chokidar/lib/nodefs-handler.js:80:15)
    at FSWatcher.NodeFsHandler._watchWithNodeFs (/home/alex/Development/workspace/java/jqhipster-v4.10.0/node_modules/chokidar/lib/nodefs-handler.js:228:14)
    at FSWatcher.NodeFsHandler._handleDir (/home/alex/Development/workspace/java/jqhipster-v4.10.0/node_modules/chokidar/lib/nodefs-handler.js:407:19)
    at FSWatcher.<anonymous> (/home/alex/Development/workspace/java/jqhipster-v4.10.0/node_modules/chokidar/lib/nodefs-handler.js:455:19)
    at FSWatcher.<anonymous> (/home/alex/Development/workspace/java/jqhipster-v4.10.0/node_modules/chokidar/lib/nodefs-handler.js:460:16)
    at FSReqWrap.oncomplete (fs.js:154:5)
error Command failed with exit code 1.
error Command failed with exit code 1.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

##### **Reproduce the error**

Run the command "yarn start" inside the JHipster project

##### **Related issues**

Not sure

##### **JHipster Version(s)**
```
jhipster --version
Using JHipster version installed locally in current project's node_modules
4.10.0
```

##### **JHipster configuration**
```
jhipster info
Using JHipster version installed locally in current project's node_modules
Executing jhipster:info
Options:
Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
mystaff@0.0.0 /home/alex/Development/workspace/java/jqhipster-v4.10.0
└── generator-jhipster@4.10.0

```


##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**


<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.mycompany.mystaff",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "4.10.0",
    "baseName": "mystaff",
    "packageName": "com.mycompany.mystaff",
    "packageFolder": "com/mycompany/mystaff",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "mysql",
    "prodDatabaseType": "mysql",
    "searchEngine": "elasticsearch",
    "messageBroker": false,
    "serviceDiscoveryType": "eureka",
    "buildTool": "maven",
    "enableSocialSignIn": true,
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "replaced-by-jhipster-info",
    "clientFramework": "angularX",
    "useSass": true,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "testFrameworks": [
      "gatling",
      "protractor"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en",
      "ar-ly",
      "ca",
      "zh-cn",
      "cs",
      "da",
      "nl",
      "et",
      "fr",
      "gl",
      "de",
      "el",
      "hu",
      "it",
      "ko",
      "pl",
      "pt-br",
      "pt-pt",
      "ro",
      "ru",
      "sk",
      "sr",
      "es",
      "sv",
      "tr",
      "ua"
    ]
  }
}
</pre>
</details>


##### **Environment and Tools**

java version "1.8.0_144"
Java(TM) SE Runtime Environment (build 1.8.0_144-b01)
Java HotSpot(TM) 64-Bit Server VM (build 25.144-b01, mixed mode)

git version 2.7.4

node: v8.6.0

npm: 5.5.1

gulp:
[17:51:24] CLI version 1.4.0

yeoman: 2.0.0

yarn: 1.2.1

Congratulations, JHipster execution is complete!
```

##### **Browsers and Operating System**

Ubuntu 16.04

- [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by alexsintoni** [comment]
Fixet after running "mvn clean install"
