### ISSUE TITLE
Problems importing JDL

### ISSUE THREAD

**Issue by ccornchip** [jhipster/generator-jhipster#6587]
##### **Overview of the issue**

I cannot import a JDL file. I get the following problem :
```
C:\Users\cornetc\jhipster\JDLexample_2>jhipster import-jdl blog-jdl.jh
Using JHipster version installed globally
Executing jhipster:import-jdl blog-jdl.jh
Options:
The jdl is being parsed.
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: ←[31m←[1mERROR!←[22m←[39m
Error while parsing entities from JDL

    at Environment.error (C:\Users\cornetc\AppData\Local\Yarn\config\global\node_modules\yeoman-environment\lib\environment.js:157:40)
    at error (C:\Users\cornetc\AppData\Local\Yarn\config\global\node_modules\generator-jhipster\generators\generator-base.js:1676:18)
    at parseJDL (C:\Users\cornetc\AppData\Local\Yarn\config\global\node_modules\generator-jhipster\generators\import-jdl\index.js:105:26)
    at Object.<anonymous> (C:\Users\cornetc\AppData\Local\Yarn\config\global\node_modules\yeoman-generator\lib\index.js:399:25)
    at C:\Users\cornetc\AppData\Local\Yarn\config\global\node_modules\run-async\index.js:25:25
    at C:\Users\cornetc\AppData\Local\Yarn\config\global\node_modules\run-async\index.js:24:19
    at self.env.runLoop.add.completed (C:\Users\cornetc\AppData\Local\Yarn\config\global\node_modules\yeoman-generator\lib\index.js:400:11)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)

C:\Users\cornetc\jhipster\JDLexample_2>
```

##### **Motivation for or Use Case**

I would really like to use JDL to create my entities as I am actually creating them manually and as the project is growing it's beginning to get quite tedious.

##### **Reproduce the error**

I tried to follow the tutorial on https://www.youtube.com/watch?v=-4gUDncO11U 

- I am on windows, I do "yo jhipster" and everything is ok.
- I then create a text file blog-jdh.jh (attatched below as blog-jdh.jh.txt):
- Finally, I run "jhipster import-jdl blog-jdh.jh" and I get the output described above

##### **Related issues**

I seem to be having the same problem as this : https://github.com/jhipster/generator-jhipster/issues/4979

##### **Suggest a Fix**

Unfortunately I am a beginner, I am still learning how all this works. One day I'll be able to find and repair bugs (I hope)

##### **JHipster Version(s)**

jhipter version 4.9.0 
It probably is a regression as it seems to work on the youtube video mentioned above.

##### **JHipster configuration**

Result from `jhipster info`
[jhipster.info.txt](https://github.com/jhipster/generator-jhipster/files/1410081/jhipster.info.txt)

.yo-rc.json is here (with the jwtSecretKey bleeped out)
[.yo-rc.json.txt](https://github.com/jhipster/generator-jhipster/files/1410091/default.yo-rc.json.txt)

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

I have no .jhipster directory. But here's the jdl file I try to import :
[blog-jdl.jh.txt](https://github.com/jhipster/generator-jhipster/files/1410104/blog-jdl.jh.txt)

##### **Browsers and Operating System**

I am on windows 7, my browser is chrome.

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by deepu105** [comment]
There might be error in your JDL. run the command with `--debug` flag like `jhipster import-jdl blog-jdl.jh --debug` it will tell you what exactly is wrong. Else upgrade to latest JHipster version where this is fixed.

**Comment by ccornchip** [comment]
I also tried it with the "by default" project on http://www.jhipster.tech/jdl-studio/ and have the same problem.

Running with the `--debug` flag I get this :
```
C:\Users\cornetc\jhipster\JDLexample_2>jhipster import-jdl blog-jdl.jh --debug
Using JHipster version installed globally
DEBUG!  cmd: import-jdl
DEBUG!  args: blog-jdl.jh, commands: Object, options: Object, _execs: Object, _allowUnknownOption: true, _args: Object, _name: import-jdl, _noHelp: false, parent: Object, _description: Create entities
 from the JDL file passed in argument, _events: Object, _eventsCount: 1
DEBUG!  opts: argument: Object, desc: Create entities from the JDL file passed in argument
DEBUG!  Arguments found
DEBUG!  cmdArgs: blog-jdl.jh
Executing jhipster:import-jdl blog-jdl.jh
Options: debug: true
The jdl is being parsed.
DEBUG! Error:
{ name: 'NoSQLModelingException',
  message: 'NoSQL entities don\'t have relationships.',
  prototype:
   Error
       at new BuildException (C:\Users\cornetc\AppData\Local\Yarn\config\global\node_modules\jhipster-core\lib\exceptions\exception_factory.js:42:25)
       at checkNoSQLModeling (C:\Users\cornetc\AppData\Local\Yarn\config\global\node_modules\jhipster-core\lib\parser\entity_parser.js:70:11)
       at Object.parse [as convertToJHipsterJSON] (C:\Users\cornetc\AppData\Local\Yarn\config\global\node_modules\jhipster-core\lib\parser\entity_parser.js:40:5)
       at parseJDL (C:\Users\cornetc\AppData\Local\Yarn\config\global\node_modules\generator-jhipster\generators\import-jdl\index.js:90:46)
       at Object.<anonymous> (C:\Users\cornetc\AppData\Local\Yarn\config\global\node_modules\yeoman-generator\lib\index.js:399:25)
       at C:\Users\cornetc\AppData\Local\Yarn\config\global\node_modules\run-async\index.js:25:25
       at C:\Users\cornetc\AppData\Local\Yarn\config\global\node_modules\run-async\index.js:24:19
       at self.env.runLoop.add.completed (C:\Users\cornetc\AppData\Local\Yarn\config\global\node_modules\yeoman-generator\lib\index.js:400:11)
       at runCallback (timers.js:672:20)
       at tryOnImmediate (timers.js:645:5) }
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: ?[31m?[1mERROR!?[22m?[39m
Error while parsing entities from JDL

    at Environment.error (C:\Users\cornetc\AppData\Local\Yarn\config\global\node_modules\yeoman-environment\lib\environment.js:157:40)
    at error (C:\Users\cornetc\AppData\Local\Yarn\config\global\node_modules\generator-jhipster\generators\generator-base.js:1676:18)
    at parseJDL (C:\Users\cornetc\AppData\Local\Yarn\config\global\node_modules\generator-jhipster\generators\import-jdl\index.js:105:26)
    at Object.<anonymous> (C:\Users\cornetc\AppData\Local\Yarn\config\global\node_modules\yeoman-generator\lib\index.js:399:25)
    at C:\Users\cornetc\AppData\Local\Yarn\config\global\node_modules\run-async\index.js:25:25
    at C:\Users\cornetc\AppData\Local\Yarn\config\global\node_modules\run-async\index.js:24:19
    at self.env.runLoop.add.completed (C:\Users\cornetc\AppData\Local\Yarn\config\global\node_modules\yeoman-generator\lib\index.js:400:11)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)

C:\Users\cornetc\jhipster\JDLexample_2>
```

**Comment by ruddell** [comment]
You are trying to generate entities that use relationships in a NoSQL project.  Relations are not supported by JHipster for NoSQL projects.  For more information on how JHipster handles relationships, see the docs on [Managing Relationships][1]:
>Relationships only work when JPA is used. If you choose to use Cassandra or MongoDB, they won’t be available.

Removing the relationships allows the JDL to be imported.  You can also try with a project using an SQL database option.

  [1]: http://www.jhipster.tech/managing-relationships/
