### ISSUE TITLE
jhipster update failed

### ISSUE THREAD

**Issue by amychta** [jhipster/generator-jhipster#6596]
##### **Overview of the issue**

I installed jhipster on my pc about a week ago (~20 of October 2017). Today I saw that new version released (4.10.1), so I decided to upgrade my installed version. I got an error during upgrate.

##### **Reproduce the error**

Following instructions from http://www.jhipster.tech/2017/10/25/jhipster-release-4.10.1.html  
I updated yarn to the latest version

```
C:\Users\Anatolii>yarn --version
1.2.1

```
and then I run upgrade

```
C:\Users\Anatolii>jhipster upgrade
Using JHipster version installed globally
Executing jhipster:upgrade
Options:
Welcome to the JHipster Upgrade Sub-Generator
This will upgrade your current application codebase to the latest JHipster version
Looking for latest generator-jhipster version...
4.10.1
C:\Users\Anatolii\AppData\Local\Yarn\config\global\node_modules\semver\semver.js:279
    throw new TypeError('Invalid Version: ' + version);
    ^

TypeError: Invalid Version: undefined
    at new SemVer (C:\Users\Anatolii\AppData\Local\Yarn\config\global\node_modules\semver\semver.js:279:11)
    at compare (C:\Users\Anatolii\AppData\Local\Yarn\config\global\node_modules\semver\semver.js:566:10)
    at Function.lt (C:\Users\Anatolii\AppData\Local\Yarn\config\global\node_modules\semver\semver.js:600:10)
    at shelljs.exec (C:\Users\Anatolii\AppData\Local\Yarn\config\global\node_modules\generator-jhipster\generators\upgrade\index.js:149:32)
    at C:\Users\Anatolii\AppData\Local\Yarn\config\global\node_modules\shelljs\src\exec.js:199:9
    at ChildProcess.exithandler (child_process.js:189:7)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:920:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:230:5)

```

Do not know for sure if it is installed correctly or not.
Then I checked current version of intalled jhipster: 

```
C:\Users\Anatolii>jhipster  --version
Using JHipster version installed globally
4.10.1
```

##### **Browsers and Operating System**

Windows 10 Enterprise
CMD application
- [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by jdubois** [comment]
`jhipster upgrade` is used to upgrade an existing application to the latest JHipster release. As you are running it from your home directory, I don't think you are in the right directory :-)
If you just want to upgrade the generator itself, use the normal Yarn or NPM command.

**Comment by amychta** [comment]
Now I got you. Thank you!
