### ISSUE TITLE
Eclipse + buildship: broken since JH 4.10.0

### ISSUE THREAD

**Issue by FireWolf2007** [jhipster/generator-jhipster#6598]
##### **Overview of the issue**
Eclipse show exception and project does not initialized correctly.
Exception:
```Java Model Exception: Java Model Status [Cannot nest 'jhipster/src/test/gatling/user-files/simulations' inside 'jhipster/src/test/gatling'. To enable the nesting exclude 'user-files/' from 'jhipster/src/test/gatling']```

In Eclipse "Gradle->Refresh Gradle Project" works only if next line removed from build.gradle:
```apply from: 'gradle/gatling.gradle'```

##### **Reproduce the error**

Create new empty project with JH4.10.0 or 4.10.1 and import into eclipse.
Eclipse 4.6.3 + buildship v2.1.2 20170807-1321

##### **JHipster Version(s)**

4.10.0, 4.10.1

##### **JHipster configuration**
```
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.mycompany.myapp",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "4.10.1",
    "baseName": "jhipster",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "8080",
    "authenticationType": "session",
    "hibernateCache": "hazelcast",
    "clusteredHttpSession": "hazelcast",
    "websocket": "spring-websocket",
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mariadb",
    "searchEngine": false,
    "messageBroker": "kafka",
    "serviceDiscoveryType": false,
    "buildTool": "gradle",
    "enableSocialSignIn": false,
    "enableSwaggerCodegen": true,
    "rememberMeKey": "18576f0bea34be439e27234b18bd7ed521d4c3d4",
    "clientFramework": "angularX",
    "useSass": true,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "testFrameworks": [
      "gatling",
      "cucumber",
      "protractor"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en"
    ]
  }
}
```
- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by atomfrede** [comment]
Can you build via command line? Is eclipse using the gradle wrapper or a locally installed gradle?

**Comment by FireWolf2007** [comment]
> Can you build via command line?
Yes, build working in command line.
> Is eclipse using the gradle wrapper or a locally installed gradle?
using locally installed gradle v4.2.1

**Comment by atomfrede** [comment]
So basically it seems like a buildship problem. Nevertheless I will try to find a solution.

**Comment by deepu105** [comment]
We do not support buildship by default hence IMO not our bug but ofcourse if there can be something on our side which will help we can do it. But im closing the ticket as its not a JHIPSTER bug

**Comment by knavadiya** [comment]
I have generated JHipster project through command and selected build tool Gradle And I am importing this project in eclipse but I got error 




Java Model Exception: Java Model Status [Cannot nest 'cpqgenerator/src/test/gatling/user-files/simulations' inside 'cpqgenerator/src/test/gatling'. To enable the nesting exclude 'user-files/' from 'cpqgenerator/src/test/gatling']
	at org.eclipse.jdt.internal.core.JavaModelOperation.runOperation(JavaModelOperation.java:786)
	at org.eclipse.jdt.internal.core.JavaProject.setRawClasspath(JavaProject.java:3097)
	at org.eclipse.jdt.internal.core.JavaProject.setRawClasspath(JavaProject.java:3059)
	at org.eclipse.jdt.internal.core.JavaProject.setRawClasspath(JavaProject.java:3112)
	at org.eclipse.buildship.core.workspace.internal.SourceFolderUpdater.updateSourceFolders(SourceFolderUpdater.java:72)
	at org.eclipse.buildship.core.workspace.internal.SourceFolderUpdater.update(SourceFolderUpdater.java:174)
	at org.eclipse.buildship.core.workspace.internal.SynchronizeGradleBuildOperation.synchronizeJavaProjectInTransaction(SynchronizeGradleBuildOperation.java:233)
	at org.eclipse.buildship.core.workspace.internal.SynchronizeGradleBuildOperation.access$200(SynchronizeGradleBuildOperation.java:99)
	at org.eclipse.buildship.core.workspace.internal.SynchronizeGradleBuildOperation$4.run(SynchronizeGradleBuildOperation.java:222)
	at org.eclipse.jdt.internal.core.BatchOperation.executeOperation(BatchOperation.java:39)
	at org.eclipse.jdt.internal.core.JavaModelOperation.run(JavaModelOperation.java:724)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2240)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2267)
	at org.eclipse.jdt.core.JavaCore.run(JavaCore.java:5521)
	at org.eclipse.jdt.core.JavaCore.run(JavaCore.java:5478)
	at org.eclipse.buildship.core.workspace.internal.SynchronizeGradleBuildOperation.synchronizeJavaProject(SynchronizeGradleBuildOperation.java:218)
	at org.eclipse.buildship.core.workspace.internal.SynchronizeGradleBuildOperation.synchronizeOpenWorkspaceProject(SynchronizeGradleBuildOperation.java:209)
	at org.eclipse.buildship.core.workspace.internal.SynchronizeGradleBuildOperation.addExistingEclipseProjectToWorkspace(SynchronizeGradleBuildOperation.java:268)
	at org.eclipse.buildship.core.workspace.internal.SynchronizeGradleBuildOperation.synchronizeNonWorkspaceProject(SynchronizeGradleBuildOperation.java:256)
	at org.eclipse.buildship.core.workspace.internal.SynchronizeGradleBuildOperation.synchronizeGradleProjectWithWorkspaceProject(SynchronizeGradleBuildOperation.java:175)
	at org.eclipse.buildship.core.workspace.internal.SynchronizeGradleBuildOperation.access$000(SynchronizeGradleBuildOperation.java:99)
	at org.eclipse.buildship.core.workspace.internal.SynchronizeGradleBuildOperation$1.run(SynchronizeGradleBuildOperation.java:134)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2240)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2262)
	at org.eclipse.buildship.core.workspace.internal.SynchronizeGradleBuildOperation.synchronizeProjectsWithWorkspace(SynchronizeGradleBuildOperation.java:131)
	at org.eclipse.buildship.core.workspace.internal.SynchronizeGradleBuildOperation.run(SynchronizeGradleBuildOperation.java:115)
	at org.eclipse.buildship.core.workspace.internal.SynchronizeGradleBuildsJob.synchronizeBuild(SynchronizeGradleBuildsJob.java:81)
	at org.eclipse.buildship.core.workspace.internal.SynchronizeGradleBuildsJob.runToolingApiJob(SynchronizeGradleBuildsJob.java:72)
	at org.eclipse.buildship.core.util.progress.ToolingApiJob$1.run(ToolingApiJob.java:73)
	at org.eclipse.buildship.core.util.progress.ToolingApiInvoker.invoke(ToolingApiInvoker.java:62)
	at org.eclipse.buildship.core.util.progress.ToolingApiJob.run(ToolingApiJob.java:70)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
