### ISSUE TITLE
Entity with unique field test failure

### ISSUE THREAD

**Issue by cbornet** [jhipster/generator-jhipster#6860]
##### **Overview of the issue**

Entity tests fail if an entity has 2 `required` relationships to an entity that has a `unique` field

Stacktrace:
<details>
<pre>
insert into foo (id, my_string) values (null, ?) [23505-196]
2017-12-13 12:54:54.328  WARN 19927 --- [           main] o.h.engine.jdbc.spi.SqlExceptionHelper   : SQL Error: 23505, SQLState: 23505
2017-12-13 12:54:54.332 ERROR 19927 --- [           main] o.h.engine.jdbc.spi.SqlExceptionHelper   : Unique index or primary key violation: "CONSTRAINT_INDEX_1 ON PUBLIC.FOO(MY_STRING) VALUES ('AAAAAAAAAA', 17)"; SQL statement:
insert into foo (id, my_string) values (null, ?) [23505-196]
Tests run: 9, Failures: 0, Errors: 9, Skipped: 0, Time elapsed: 0.385 sec <<< FAILURE! - in com.mycompany.myapp.web.rest.BarResourceIntTest
getNonExistingBar(com.mycompany.myapp.web.rest.BarResourceIntTest)  Time elapsed: 0.053 sec  <<< ERROR!
javax.persistence.PersistenceException: org.hibernate.exception.ConstraintViolationException: could not execute statement
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.index.BaseIndex.getDuplicateKeyException(BaseIndex.java:103)
	at org.h2.mvstore.db.MVSecondaryIndex.checkUnique(MVSecondaryIndex.java:231)
	at org.h2.mvstore.db.MVSecondaryIndex.add(MVSecondaryIndex.java:190)
	at org.h2.mvstore.db.MVTable.addRow(MVTable.java:705)
	at org.h2.command.dml.Insert.insertRows(Insert.java:156)
	at org.h2.command.dml.Insert.update(Insert.java:114)
	at org.h2.command.CommandContainer.update(CommandContainer.java:101)
	at org.h2.command.Command.executeUpdate(Command.java:260)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(JdbcPreparedStatement.java:164)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:150)
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java)
	at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.executeUpdate(ResultSetReturnImpl.java:175)
	at org.hibernate.dialect.identity.GetGeneratedKeysDelegate.executeAndExtract(GetGeneratedKeysDelegate.java:57)
	at org.hibernate.id.insert.AbstractReturningDelegate.performInsert(AbstractReturningDelegate.java:42)
	at org.hibernate.persister.entity.AbstractEntityPersister.insert(AbstractEntityPersister.java:2919)
	at org.hibernate.persister.entity.AbstractEntityPersister.insert(AbstractEntityPersister.java:3490)
	at org.hibernate.action.internal.EntityIdentityInsertAction.execute(EntityIdentityInsertAction.java:81)
	at org.hibernate.engine.spi.ActionQueue.execute(ActionQueue.java:626)
	at org.hibernate.engine.spi.ActionQueue.addResolvedEntityInsertAction(ActionQueue.java:280)
	at org.hibernate.engine.spi.ActionQueue.addInsertAction(ActionQueue.java:261)
	at org.hibernate.engine.spi.ActionQueue.addAction(ActionQueue.java:306)
	at org.hibernate.event.internal.AbstractSaveEventListener.addInsertAction(AbstractSaveEventListener.java:318)
	at org.hibernate.event.internal.AbstractSaveEventListener.performSaveOrReplicate(AbstractSaveEventListener.java:275)
	at org.hibernate.event.internal.AbstractSaveEventListener.performSave(AbstractSaveEventListener.java:182)
	at org.hibernate.event.internal.AbstractSaveEventListener.saveWithGeneratedId(AbstractSaveEventListener.java:113)
	at org.hibernate.jpa.event.internal.core.JpaPersistEventListener.saveWithGeneratedId(JpaPersistEventListener.java:67)
	at org.hibernate.event.internal.DefaultPersistEventListener.entityIsTransient(DefaultPersistEventListener.java:189)
	at org.hibernate.event.internal.DefaultPersistEventListener.onPersist(DefaultPersistEventListener.java:132)
	at org.hibernate.event.internal.DefaultPersistEventListener.onPersist(DefaultPersistEventListener.java:58)
	at org.hibernate.internal.SessionImpl.firePersist(SessionImpl.java:782)
	at org.hibernate.internal.SessionImpl.persist(SessionImpl.java:767)
	at sun.reflect.GeneratedMethodAccessor296.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.orm.jpa.SharedEntityManagerCreator$SharedEntityManagerInvocationHandler.invoke(SharedEntityManagerCreator.java:298)
	at com.sun.proxy.$Proxy150.persist(Unknown Source)
	at com.mycompany.myapp.web.rest.BarResourceIntTest.createEntity(BarResourceIntTest.java:88)
	at com.mycompany.myapp.web.rest.BarResourceIntTest.initTest(BarResourceIntTest.java:96)
</pre>
</details>

##### **Reproduce the error**

Generate with .yo-rc.json and jdl below then
`./mvnw test`

##### **Related issues**

Same as #6521 but this time for entities other than User
Since the relationship is required we try to create 2 Foos, one for each field but these Foos use the same DEFAULT_MY_STRING at creation hence the unique constraint failure
```java
    public static Bar createEntity(EntityManager em) {
        Bar bar = new Bar();
        // Add required entity
        Foo foo = FooResourceIntTest.createEntity(em);
        em.persist(foo);
        em.flush();
        bar.setFoo(foo);
        // Add required entity
        Foo otherFoo = FooResourceIntTest.createEntity(em);
        em.persist(otherFoo);
        em.flush();
        bar.setOtherFoo(otherFoo);
        return bar;
    }
```
```java
    private static final String DEFAULT_MY_STRING = "AAAAAAAAAA";

    public static Foo createEntity(EntityManager em) {
        Foo foo = new Foo()
            .myString(DEFAULT_MY_STRING);
        return foo;
    }
```
##### **Suggest a Fix**

Generate random values for each test field ? Remove unique constraint option :trollface: ?

##### **JHipster Version(s)**

master at 5b58a9adc1bd0a54dd97e6b6c6becc3fb36b11a4

##### **JHipster configuration**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.mycompany.myapp",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "4.12.0",
    "baseName": "jhipster",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "replaced-by-jhipster-info",
    "clientFramework": "angularX",
    "useSass": false,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en"
    ]
  }
}
</pre>
</details>

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**
Bar.json
```json
{
    "fluentMethods": true,
    "relationships": [
        {
            "relationshipName": "foo",
            "otherEntityName": "foo",
            "relationshipType": "many-to-one",
            "relationshipValidateRules": [
                "required"
            ],
            "otherEntityField": "id"
        },
        {
            "relationshipName": "otherFoo",
            "otherEntityName": "foo",
            "relationshipType": "many-to-one",
            "relationshipValidateRules": [
                "required"
            ],
            "otherEntityField": "id"
        }
    ],
    "fields": [],
    "changelogDate": "20171213124802",
    "dto": "no",
    "service": "no",
    "entityTableName": "bar",
    "jpaMetamodelFiltering": false,
    "pagination": "no"
}
```
Foo.json
```json
{
    "fluentMethods": true,
    "relationships": [],
    "fields": [
        {
            "fieldName": "myString",
            "fieldType": "String",
            "fieldValidateRules": [
                "unique"
            ]
        }
    ],
    "changelogDate": "20171213124638",
    "dto": "no",
    "service": "no",
    "entityTableName": "foo",
    "jpaMetamodelFiltering": false,
    "pagination": "no"
}
```

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by taurus227** [comment]
What is the purpose of the test, what's the use case? Of course if you want unique Foos, then you cannot have twice the same Foo. This has nothing to do with the relationships. Bar can have two fields linking to the same Foo or linking to 2 different Foos.

**Comment by taurus227** [comment]
Oh, OK, I looked at the other User-related issue. The solution there was to create two different Foos and link to those.

**Comment by FireWolf2007** [comment]
Our example how to fix it:
web/rest/CloudPBXResourceIntTest.java:
```
...
    static AtomicInteger cloudPBXNumberSequence = new AtomicInteger(0);
    /**
     * Create an entity for this test.
     *
     * This is a static method, as tests for other entities might also need it,
     * if they test an entity which requires the current entity.
     */
    public static CloudPBX createEntity(EntityManager em) {
        int cloudPBXNumber = cloudPBXNumberSequence.incrementAndGet();
        CloudPBX cloudPBX = new CloudPBX()
            .name(DEFAULT_NAME+cloudPBXNumber);
        return cloudPBX;
    }
...
```

and in tests following examples:
```
 .andExpect(jsonPath("$.name").value(DEFAULT_NAME.toString()+cloudPBXNumberSequence.get()))

.andExpect(jsonPath("$.[*].name").value(hasItem(DEFAULT_NAME.toString()+cloudPBXNumberSequence.get())))

```

**Comment by cbornet** [comment]
Yes, you'll need to do it for all data types. doable but lot of work... A random can also be used.

**Comment by MathieuAA** [comment]
@jdubois Sorry, I didn't follow the thread on uniques. Is it officially supported in the generator? I have a branch on JCore for this feature and I'm wondering whether to merge it.

**Comment by ruddell** [comment]
It's [not selectable](https://github.com/jhipster/generator-jhipster/pull/6850#issuecomment-351420007) in the prompts as it was disabled so we could have a smooth release a while ago.  So the code is there but you can't enable it.  The outstanding issue is displaying validation messages when saving an entity fails.

**Comment by MathieuAA** [comment]
Thanks Jon, that's what I noticed... I'll let my branch live a while longer.

**Comment by agoncal** [comment]
@MathieuAA So does this means that the JDL does not have a `unique` keyword yet ?

**Comment by MathieuAA** [comment]
Hi Antonio, it does. When the option is available in the generator, I'll merge the branch where I added the `unique` keyword and release.

**Comment by mhoennig** [comment]
I don't understand why this issue was closed. The referred issue #8403 only officially documents the feature which is described here (#6860) not fully working. For required relationships including unique fields, I am pretty sure that the *InTest templates need to be able to create more than just a default entity in createEntity(), maybe even multiple. Not for the test itself, but for  tests of the related entities, which also use this method. So, if I don't miss anything important, I would open a new issue for this.
