### ISSUE TITLE
IntelliJ Karma Plugin does not work with jHipster unit tests

### ISSUE THREAD

**Issue by ramden** [jhipster/generator-jhipster#6995]
After installing the Karma plugin in Intellij (https://plugins.jetbrains.com/plugin/7287-karma) and setting up configuration unexpected results occur.

Testing via **yarn test** works

##### **Overview of the issue**

After configuring the karma plugin (see -> Reproduce the error) following output occures and test do not run:

`
Failed: Can't resolve all parameters for ActivateService: (?).
	Error: Can't resolve all parameters for ActivateService: (?).
	    at syntaxError (webpack:///PROJECTPATH/node_modules/@angular/compiler/esm5/compiler.js:485:21 <- spec/entry.ts:62939:34)
	    at CompileMetadataResolver._getDependenciesMetadata (webpack:///PROJECTPATH/node_modules/@angular/compiler/esm5/compiler.js:15664:0 <- spec/entry.ts:78118:35)
	    at CompileMetadataResolver._getTypeMetadata (webpack:///PROJECTPATH/node_modules/@angular/compiler/esm5/compiler.js:15499:0 <- spec/entry.ts:77953:26)
	    at CompileMetadataResolver._getInjectableMetadata (webpack:///PROJECTPATH/node_modules/@angular/compiler/esm5/compiler.js:15479:0 <- spec/entry.ts:77933:21)
	    at CompileMetadataResolver.getProviderMetadata (webpack:///PROJECTPATH/node_modules/@angular/compiler/esm5/compiler.js:15839:0 <- spec/entry.ts:78293:40)
	    at webpack:///PROJECTPATH/node_modules/@angular/compiler/esm5/compiler.js:15750:0 <- spec/entry.ts:78204:49
	    at Array.forEach (<anonymous>)
	    at CompileMetadataResolver._getProvidersMetadata (webpack:///PROJECTPATH/node_modules/@angular/compiler/esm5/compiler.js:15710:0 <- spec/entry.ts:78164:19)
	    at CompileMetadataResolver.getNgModuleMetadata (webpack:///PROJECTPATH/node_modules/@angular/compiler/esm5/compiler.js:15278:0 <- spec/entry.ts:77732:50)
	    at JitCompiler._loadModules (webpack:///PROJECTPATH/node_modules/@angular/compiler/esm5/compiler.js:34226:57 <- spec/entry.ts:96680:87)
`

##### **Reproduce the error**

Configure the plugin and start tests by play button:

![2018-01-17_0-27-48](https://user-images.githubusercontent.com/630532/35017548-924f9a68-fb1d-11e7-8642-598fc26263fe.png)

##### **Suggest a Fix**

- Find the correct configuration for the karma plugin
- Changes in the setup of testing to work on command line and via plugin

##### **JHipster Version(s)**

4.13.3

**Comment by ramden** [comment]
Update: After disabling Kaspersky Antivirus it worked. Issue can be closed
