### ISSUE TITLE
Microservices with Spring Boot 2

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/generator-jhipster#7089]
I open this ticket, as currently, in **Master branch**, the MicroServices don't work with Spring Boot 2:
https://travis-ci.org/jhipster/generator-jhipster/builds/338220178

I just started to work on it.

For **Eureka**:

In [jhipster-dependencies](https://github.com/jhipster/jhipster-dependencies) project:

```diff
-        <spring-cloud.version>Finchley.M5</spring-cloud.version>
+        <spring-cloud.version>Finchley.BUILD-SNAPSHOT</spring-cloud.version>
         <!-- The netflix version should match the one in
         https://github.com/spring-cloud/spring-cloud-release/blob/v${spring-cloud.version}/spring-cloud-dependencies/pom.xml -->
-        <spring-cloud-netflix.version>2.0.0.M5</spring-cloud-netflix.version>
-        <spring-cloud-stream.version>Elmhurst.M4</spring-cloud-stream.version>
+        <spring-cloud-netflix.version>2.0.0.BUILD-SNAPSHOT</spring-cloud-netflix.version>
+        <spring-cloud-stream.version>Elmhurst.BUILD-SNAPSHOT</spring-cloud-stream.version>
```

For Gateway Eureka, I had to add this bean, otherwise, the application won't start:

```diff
+    @Bean
+    @Qualifier("cachingSpringLoadBalancerFactory")
+    public CachingSpringLoadBalancerFactory cachingSpringLoadBalancerFactory(SpringClientFactory factory) {
+        return new CachingSpringLoadBalancerFactory(factory);
+    }
```

For **Consul**

It doesn't work yet.

**Comment by pascalgrimaud** [comment]
For Consul, link to https://github.com/jhipster/generator-jhipster/pull/6970

**Comment by jdubois** [comment]
I **swear** it was working when I merged the branch.... Let me have a look, but that's maybe because we use SNAPSHOT releases

**Comment by jdubois** [comment]
Oh in fact it's my fault, at least for the Eureka error. Let me check this.

**Comment by jdubois** [comment]
I fact I was wrong.
There is an issue with `ConfigurationBeanFactoryMetaData`, which has a `NoClassDefFoundError`. I have absolutely no idea what happens here, and I just lost 2 hours on this.

- It works without Spring Cloud
- As soon as you add Spring Cloud, you get the `NoClassDefFoundError`. Intellij confirms the class isn't here (you can't import it), but you can easily access it as it's in the classpath. This doesn't make any sense at all, I know.

I found a few cleanups and tunings so I'll commit them and link them here, but still I can't find the solution.

**Comment by deepu105** [comment]
Actually, When I tried to create an app for my demo yesterday using master
with React, I found even the monolith doesn't start up. There was a bean
creation error, But I didn't open an issue as I wanted to confirm it again.


Thanks & Regards,
Deepu

**Comment by pascalgrimaud** [comment]
I confirm your issue @jdubois
I'm having a look too. Here the full stacktrace:

```
2018-02-09 08:20:26.810 ERROR 10511 --- [  restartedMain] o.s.boot.SpringApplication               : Application run failed

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'configurationPropertiesBeans' defined in org.springframework.cloud.autoconfigure.ConfigurationPropertiesRebinderAutoConfiguration: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.cloud.context.properties.ConfigurationPropertiesBeans]: Factory method 'configurationPropertiesBeans' threw exception; nested exception is java.lang.NoClassDefFoundError: org/springframework/boot/context/properties/ConfigurationBeanFactoryMetaData
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:587)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1250)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1099)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:545)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:502)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:312)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:228)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:310)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:205)
	at org.springframework.context.support.PostProcessorRegistrationDelegate.registerBeanPostProcessors(PostProcessorRegistrationDelegate.java:238)
	at org.springframework.context.support.AbstractApplicationContext.registerBeanPostProcessors(AbstractApplicationContext.java:709)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:534)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:752)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:388)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:327)
	at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:136)
	at org.springframework.cloud.bootstrap.BootstrapApplicationListener.bootstrapServiceContext(BootstrapApplicationListener.java:197)
	at org.springframework.cloud.bootstrap.BootstrapApplicationListener.onApplicationEvent(BootstrapApplicationListener.java:104)
	at org.springframework.cloud.bootstrap.BootstrapApplicationListener.onApplicationEvent(BootstrapApplicationListener.java:70)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:127)
	at org.springframework.boot.context.event.EventPublishingRunListener.environmentPrepared(EventPublishingRunListener.java:74)
	at org.springframework.boot.SpringApplicationRunListeners.environmentPrepared(SpringApplicationRunListeners.java:54)
	at org.springframework.boot.SpringApplication.prepareEnvironment(SpringApplication.java:351)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:317)
	at io.github.pascalgrimaud.GatewayApp.main(GatewayApp.java:67)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.devtools.restart.RestartLauncher.run(RestartLauncher.java:49)
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.cloud.context.properties.ConfigurationPropertiesBeans]: Factory method 'configurationPropertiesBeans' threw exception; nested exception is java.lang.NoClassDefFoundError: org/springframework/boot/context/properties/ConfigurationBeanFactoryMetaData
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:579)
	... 32 common frames omitted
Caused by: java.lang.NoClassDefFoundError: org/springframework/boot/context/properties/ConfigurationBeanFactoryMetaData
	at org.springframework.cloud.autoconfigure.ConfigurationPropertiesRebinderAutoConfiguration.configurationPropertiesBeans(ConfigurationPropertiesRebinderAutoConfiguration.java:52)
	at org.springframework.cloud.autoconfigure.ConfigurationPropertiesRebinderAutoConfiguration$$EnhancerBySpringCGLIB$$ccdf05a8.CGLIB$configurationPropertiesBeans$0(<generated>)
	at org.springframework.cloud.autoconfigure.ConfigurationPropertiesRebinderAutoConfiguration$$EnhancerBySpringCGLIB$$ccdf05a8$$FastClassBySpringCGLIB$$6383cf3f.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228)
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:361)
	at org.springframework.cloud.autoconfigure.ConfigurationPropertiesRebinderAutoConfiguration$$EnhancerBySpringCGLIB$$ccdf05a8.configurationPropertiesBeans(<generated>)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154)
	... 33 common frames omitted
Caused by: java.lang.ClassNotFoundException: org.springframework.boot.context.properties.ConfigurationBeanFactoryMetaData
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 44 common frames omitted
```

**Comment by pascalgrimaud** [comment]
Ok understood.
It's because the class `ConfigurationBeanFactoryMetaData` has been renamed to `ConfigurationBeanFactoryMetadata`:
Here the commit from spring-boot team, 1 day ago: https://github.com/spring-projects/spring-boot/commit/dd3bcc5691d875fcce11056017fec55e90ced121#diff-6f4a21fd21213974be90765e541a69e1

**Comment by jdubois** [comment]
Yes I saw that commit yesterday - but I don't understand at all, it's the same name for me??? I see a difference in Git, but I can't see what changed. Am I blind? Is there a hidden character?

**Comment by jdubois** [comment]
I see this change was done by @mbhave so I'm notifying her - maybe there's some issue here we need to report.

**Comment by pascalgrimaud** [comment]
Data -> data

Le 9 févr. 2018 9:37 AM, "Julien Dubois" <notifications@github.com> a
écrit :

**Comment by jdubois** [comment]
OK, I'm blind then :-)
But then this is a breaking change for Spring Cloud, which explains why everything fails.

**Comment by jdubois** [comment]
We need to force the use of Spring Boot RC1, I'm trying to do that

**Comment by jdubois** [comment]
Hey, green build! This is a bit unstable as there are lots of API incompatibilities between the Spring sub-projects

**Comment by pascalgrimaud** [comment]
nice @jdubois !!
