### ISSUE TITLE
Cannot create entity with name Package

### ISSUE THREAD

**Issue by mhewedy** [jhipster/generator-jhipster#7104]
However It is allowed to have java POJO with name package, but jhipster prevents it

```
Using JHipster version installed locally in current project's node_modules
Executing jhipster:entity Package
Options:
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: ERROR! The entity name cannot contain a Java or JHipster reserved keyword
    at Environment.error (C:\work\code\java\myproject\node_modules\yeoman-environment\lib\environment.js:157:40)
    at module.exports.error (C:\work\code\java\myproject\node_modules\generator-jhipster\generators\generator-base.js:1852:18)
    at module.exports.validateEntityName (C:\work\code\java\myproject\node_modules\generator-jhipster\generators\entity\index.js:178:26)
    at Object.<anonymous> (C:\work\code\java\myproject\node_modules\yeoman-generator\lib\index.js:399:25)
    at C:\work\code\java\myproject\node_modules\run-async\index.js:25:25
    at new Promise (<anonymous>)
    at C:\work\code\java\myproject\node_modules\run-async\index.js:24:19
    at self.env.runLoop.add.completed (C:\work\code\java\myproject\node_modules\yeoman-generator\lib\index.js:400:11)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)


```

**Comment by deepu105** [comment]
I'm pretty sure we didn't add it to reserved keyword by mistake. Each reserved keyword was added since it was failing at some part of the generated code. You could try to generate something like appPackage and then refactor it to package using the IDE

**Comment by jdubois** [comment]
It's forbidden as it's a Java reserved keyword. In fact it's forbidden in Java.

**Comment by sendilkumarn** [comment]
and in javascript too 😉

**Comment by deepu105** [comment]
I think he is talking about Package with an uppercase P, but anyway doesnt
matter as it will still cause issue when we generate instance names.


Thanks & Regards,
Deepu

**Comment by sendilkumarn** [comment]
Oh is it deepu we care keywords only with an uppercase. 

It will cause an issue if used, no matter if it has a "P" or "p" in that.

**Comment by mhewedy** [comment]
So, because jhipster cannot deal with `Package`, I cannot use it in my code??!!

**Comment by gmarziou** [comment]
You can always do what you want with generated code, it's all yours.

**Comment by deepu105** [comment]
@mhewedy again, you can generate with another name and refactor class names to `Package` if you want, but you cant use `package` as variable names both in java and js/ts and that's why we don't do it.
