### ISSUE TITLE
Issues with ejs file extension

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/generator-jhipster#7163]
##### **Overview of the issue**

When generating a new project, choosing `no translation`, there are some issues in console.

##### **Motivation for or Use Case**

Full log: https://travis-ci.org/jhipster/generator-jhipster/jobs/345224839
An extract of Travis log:

```
Error in file: ../../languages/templates/src/main/webapp/i18n/en/_global.json
{ Error: ENOENT: no such file or directory, open '/home/travis/.config/yarn/global/node_modules/generator-jhipster/generators/languages/templates/src/main/webapp/i18n/en/_global.json'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.readFileSync (fs.js:551:33)
    at Object.readFileAsString (/home/travis/.config/yarn/global/node_modules/generator-jhipster/node_modules/html-wiring/index.js:281:13)
    at geti18nJson (/home/travis/.config/yarn/global/node_modules/generator-jhipster/generators/utils.js:261:25)
    at replacePlaceholders (/home/travis/.config/yarn/global/node_modules/generator-jhipster/generators/utils.js:235:26)
    at renderContent (/home/travis/.config/yarn/global/node_modules/generator-jhipster/generators/utils.js:166:24)
    at ejs.renderFile (/home/travis/.config/yarn/global/node_modules/generator-jhipster/generators/utils.js:191:13)
    at tryHandleCache (/home/travis/.config/yarn/global/node_modules/generator-jhipster/node_modules/ejs/lib/ejs.js:228:10)
    at Object.exports.renderFile (/home/travis/.config/yarn/global/node_modules/generator-jhipster/node_modules/ejs/lib/ejs.js:437:10)
    at renderContent (/home/travis/.config/yarn/global/node_modules/generator-jhipster/generators/utils.js:189:9)
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/home/travis/.config/yarn/global/node_modules/generator-jhipster/generators/languages/templates/src/main/webapp/i18n/en/_global.json' }
```

##### **Reproduce the error**

Simply generate a new project, then choose N at this question:

```
Would you like to enable internationalization support? (Y/n) n
```

##### **Suggest a Fix**

This [function](https://github.com/jhipster/generator-jhipster/blob/master/generators/utils.js#L250-L272) need to be rework, specially, adding .ejs extension when the file is: 'activate' or 'global' or 'health' or 'reset'.

The fix would be:

```javascript
function geti18nJson(key, generator) {
    const i18nDirectory = `${LANGUAGES_MAIN_SRC_DIR}i18n/en/`;
    const name = _.kebabCase(key.split('.')[0]);
    let filename;
    let render;    
    if (['activate', 'global', 'health', 'reset'].indexOf(name) !== -1) {
        filename = `${i18nDirectory + name}.json.ejs`;
        render = true;
    } else {
        filename = `${i18nDirectory + name}.json`;
    }
    if (!shelljs.test('-f', path.join(generator.sourceRoot(), filename))) {
        filename = `${i18nDirectory}_${name}.json`;
        render = true;
    }
    try {
        let file = html.readFileAsString(path.join(generator.sourceRoot(), filename));

        file = render ? ejs.render(file, generator, {}) : file;
        file = JSON.parse(file);
        return file;
    } catch (err) {
        generator.log(err);
        generator.log(`Error in file: ${filename}`);
        // 'Error reading translation file!'
        return undefined;
    }
}
```

For the moment, I don't know if there are any impacts.
Are you ok this change @deepu105 ?

##### **JHipster Version(s)**

```
jhipster@0.0.0 /home/pgrimaud/tmp/46-toto
└── generator-jhipster@4.14.0  -> /home/pgrimaud/projects/jhipster/generator-jhipster

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "io.github.pascalgrimaud"
    },
    "jhipsterVersion": "4.14.0",
    "baseName": "jhipster",
    "packageName": "io.github.pascalgrimaud",
    "packageFolder": "io/github/pascalgrimaud",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "replaced-by-jhipster-info",
    "clientFramework": "angularX",
    "useSass": false,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": false
  }
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

openjdk version "1.8.0_151"
OpenJDK Runtime Environment (build 1.8.0_151-8u151-b12-0ubuntu0.17.10.2-b12)
OpenJDK 64-Bit Server VM (build 25.151-b12, mixed mode)

git version 2.14.1

node: v8.9.3

npm: 5.6.0

yeoman: 2.0.1

yarn: 1.3.2

Docker version 17.09.0-ce, build afdb6d4

docker-compose version 1.16.1, build 6d1ac21

Congratulations, JHipster execution is complete!

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by pascalgrimaud** [comment]
Another issue:
- when selecting gateway, oauth2, no database:

```
Error: ERROR! Copying template src/main/docker/no.yml.ejs failed. [Error: ENOENT: no such file or directory, open '/home/pgrimaud/projects/jhipster/generator-jhipster/generators/server/templates/src/main/docker/no.yml.ejs']
    at Environment.error (/home/pgrimaud/projects/jhipster/generator-jhipster/node_modules/yeoman-environment/lib/environment.js:157:40)
    at module.exports.error (/home/pgrimaud/projects/jhipster/generator-jhipster/generators/generator-base.js:2016:18)
    at ejs.renderFile (/home/pgrimaud/projects/jhipster/generator-jhipster/generators/utils.js:193:23)
    at tryHandleCache (/home/pgrimaud/projects/jhipster/generator-jhipster/node_modules/ejs/lib/ejs.js:226:12)
    at Object.exports.renderFile (/home/pgrimaud/projects/jhipster/generator-jhipster/node_modules/ejs/lib/ejs.js:437:10)
    at Object.renderContent (/home/pgrimaud/projects/jhipster/generator-jhipster/generators/utils.js:189:9)
    at module.exports.template (/home/pgrimaud/projects/jhipster/generator-jhipster/generators/generator-base-private.js:536:23)
    at module.exports.writeDockerFiles (/home/pgrimaud/projects/jhipster/generator-jhipster/generators/server/files.js:61:18)
    at Object.<anonymous> (/home/pgrimaud/projects/jhipster/generator-jhipster/node_modules/yeoman-generator/lib/index.js:399:25)
    at /home/pgrimaud/projects/jhipster/generator-jhipster/node_modules/run-async/index.js:25:25
```

I can try to fix them later, as I'm currently working on jhipster-registry and found these issues
