### ISSUE TITLE
java.lang.IllegalStateException: Cannot load configuration class: io.github.jhipster.config.metrics.PrometheusRegistry

### ISSUE THREAD

**Issue by AbderrahimRayes** [jhipster/generator-jhipster#7182]
##### **Overview of the issue**

I connected to my heroku server and i found that suddenly after app restart it crashed, i did not change anything i did not push any changes, after inspecting the log i found out that the app couldn't find the class io.github.jhipster.config.metrics.PrometheusRegistry
so i looked for the class and i found that class does'nt exist anymore after the commit "f1d1f9c" that was made 6 days ago .   

##### **Motivation for or Use Case**

i think it's a bug because everything was working fine until the server restarted after the commit "f1d1f9c " and the metrics folder in the config folder was removed 

##### **logs**
<pre>
2018-02-27T10:58:21.322583+00:00 app[web.1]: java.lang.IllegalStateException: Cannot load configuration class: io.github.jhipster.config.metrics.PrometheusRegistry
2018-02-27T10:58:21.322585+00:00 app[web.1]: 	at org.springframework.context.annotation.ConfigurationClassPostProcessor.enhanceConfigurationClasses(ConfigurationClassPostProcessor.java:403)
2018-02-27T10:58:21.322587+00:00 app[web.1]: 	at org.springframework.context.annotation.ConfigurationClassPostProcessor.postProcessBeanFactory(ConfigurationClassPostProcessor.java:249)
2018-02-27T10:58:21.322588+00:00 app[web.1]: 	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:281)
2018-02-27T10:58:21.322589+00:00 app[web.1]: 	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:125)
2018-02-27T10:58:21.322591+00:00 app[web.1]: 	at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:687)
2018-02-27T10:58:21.322592+00:00 app[web.1]: 	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:525)
2018-02-27T10:58:21.322593+00:00 app[web.1]: 	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122)
2018-02-27T10:58:21.322595+00:00 app[web.1]: 	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:693)
2018-02-27T10:58:21.322597+00:00 app[web.1]: 	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:360)
2018-02-27T10:58:21.322598+00:00 app[web.1]: 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:303)
2018-02-27T10:58:21.322600+00:00 app[web.1]: 	at com.forsyslab.sonar.web.SonarApp.main(SonarApp.java:74)
2018-02-27T10:58:21.322601+00:00 app[web.1]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2018-02-27T10:58:21.322602+00:00 app[web.1]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2018-02-27T10:58:21.322603+00:00 app[web.1]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2018-02-27T10:58:21.322605+00:00 app[web.1]: 	at java.lang.reflect.Method.invoke(Method.java:498)
2018-02-27T10:58:21.322606+00:00 app[web.1]: 	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
2018-02-27T10:58:21.322607+00:00 app[web.1]: 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
2018-02-27T10:58:21.322608+00:00 app[web.1]: 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
2018-02-27T10:58:21.322609+00:00 app[web.1]: 	at org.springframework.boot.loader.WarLauncher.main(WarLauncher.java:59)
2018-02-27T10:58:21.322611+00:00 app[web.1]: Caused by: java.lang.IllegalStateException: Unable to load cache item
2018-02-27T10:58:21.322613+00:00 app[web.1]: 	at org.springframework.cglib.core.internal.LoadingCache.createEntry(LoadingCache.java:79)
2018-02-27T10:58:21.322614+00:00 app[web.1]: 	at org.springframework.cglib.core.internal.LoadingCache.get(LoadingCache.java:34)
2018-02-27T10:58:21.322615+00:00 app[web.1]: 	at org.springframework.cglib.core.AbstractClassGenerator$ClassLoaderData.get(AbstractClassGenerator.java:116)
2018-02-27T10:58:21.322616+00:00 app[web.1]: 	at org.springframework.cglib.core.AbstractClassGenerator.create(AbstractClassGenerator.java:291)
2018-02-27T10:58:21.322618+00:00 app[web.1]: 	at org.springframework.cglib.proxy.Enhancer.createHelper(Enhancer.java:480)
2018-02-27T10:58:21.322619+00:00 app[web.1]: 	at org.springframework.cglib.proxy.Enhancer.createClass(Enhancer.java:337)
2018-02-27T10:58:21.322620+00:00 app[web.1]: 	at org.springframework.context.annotation.ConfigurationClassEnhancer.createClass(ConfigurationClassEnhancer.java:138)
2018-02-27T10:58:21.322621+00:00 app[web.1]: 	at org.springframework.context.annotation.ConfigurationClassEnhancer.enhance(ConfigurationClassEnhancer.java:110)
2018-02-27T10:58:21.322623+00:00 app[web.1]: 	at org.springframework.context.annotation.ConfigurationClassPostProcessor.enhanceConfigurationClasses(ConfigurationClassPostProcessor.java:393)
2018-02-27T10:58:21.322624+00:00 app[web.1]: 	... 18 common frames omitted
2018-02-27T10:58:21.322625+00:00 app[web.1]: Caused by: java.lang.NoClassDefFoundError: io/prometheus/client/dropwizard/DropwizardExports
2018-02-27T10:58:21.322627+00:00 app[web.1]: 	at java.lang.Class.getDeclaredConstructors0(Native Method)
2018-02-27T10:58:21.322628+00:00 app[web.1]: 	at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671)
2018-02-27T10:58:21.322629+00:00 app[web.1]: 	at java.lang.Class.getDeclaredConstructors(Class.java:2020)
2018-02-27T10:58:21.322630+00:00 app[web.1]: 	at org.springframework.cglib.proxy.Enhancer.generateClass(Enhancer.java:566)
2018-02-27T10:58:21.322632+00:00 app[web.1]: 	at org.springframework.cglib.transform.TransformingClassGenerator.generateClass(TransformingClassGenerator.java:33)
2018-02-27T10:58:21.322633+00:00 app[web.1]: 	at org.springframework.cglib.core.DefaultGeneratorStrategy.generate(DefaultGeneratorStrategy.java:25)
2018-02-27T10:58:21.322634+00:00 app[web.1]: 	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanFactoryAwareGeneratorStrategy.generate(ConfigurationClassEnhancer.java:252)
2018-02-27T10:58:21.322635+00:00 app[web.1]: 	at org.springframework.cglib.core.AbstractClassGenerator.generate(AbstractClassGenerator.java:329)
2018-02-27T10:58:21.322636+00:00 app[web.1]: 	at org.springframework.cglib.proxy.Enhancer.generate(Enhancer.java:492)
2018-02-27T10:58:21.322645+00:00 app[web.1]: 	at org.springframework.cglib.core.AbstractClassGenerator$ClassLoaderData$3.apply(AbstractClassGenerator.java:93)
2018-02-27T10:58:21.322646+00:00 app[web.1]: 	at org.springframework.cglib.core.AbstractClassGenerator$ClassLoaderData$3.apply(AbstractClassGenerator.java:91)
2018-02-27T10:58:21.322648+00:00 app[web.1]: 	at org.springframework.cglib.core.internal.LoadingCache$2.call(LoadingCache.java:54)
2018-02-27T10:58:21.322649+00:00 app[web.1]: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
2018-02-27T10:58:21.322650+00:00 app[web.1]: 	at org.springframework.cglib.core.internal.LoadingCache.createEntry(LoadingCache.java:61)
2018-02-27T10:58:21.322651+00:00 app[web.1]: 	... 26 common frames omitted
2018-02-27T10:58:21.322653+00:00 app[web.1]: Caused by: java.lang.ClassNotFoundException: io.prometheus.client.dropwizard.DropwizardExports
2018-02-27T10:58:21.322654+00:00 app[web.1]: 	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
2018-02-27T10:58:21.322655+00:00 app[web.1]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
2018-02-27T10:58:21.322656+00:00 app[web.1]: 	at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:94)
2018-02-27T10:58:21.322657+00:00 app[web.1]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
2018-02-27T10:58:21.322658+00:00 app[web.1]: 	... 40 common frames omitted
2018-02-27T10:58:21.322660+00:00 app[web.1]: 
2018-02-27T10:58:21.333223+00:00 app[web.1]: 2018-02-27 10:58:21.332  WARN 3 --- [           main] ationConfigEmbeddedWebApplicationContext : Exception thrown from LifecycleProcessor on context close
2018-02-27T10:58:21.333225+00:00 app[web.1]: 
2018-02-27T10:58:21.333230+00:00 app[web.1]: java.lang.IllegalStateException: LifecycleProcessor not initialized - call 'refresh' before invoking lifecycle methods via the context: org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@32b260fa: startup date [Tue Feb 27 10:58:17 UTC 2018]; parent: org.springframework.context.annotation.AnnotationConfigApplicationContext@100fc185
2018-02-27T10:58:21.333232+00:00 app[web.1]: 	at org.springframework.context.support.AbstractApplicationContext.getLifecycleProcessor(AbstractApplicationContext.java:427)
2018-02-27T10:58:21.333233+00:00 app[web.1]: 	at org.springframework.context.support.AbstractApplicationContext.doClose(AbstractApplicationContext.java:999)
2018-02-27T10:58:21.333234+00:00 app[web.1]: 	at org.springframework.context.support.AbstractApplicationContext.close(AbstractApplicationContext.java:958)
2018-02-27T10:58:21.333236+00:00 app[web.1]: 	at org.springframework.boot.SpringApplication.handleRunFailure(SpringApplication.java:750)
2018-02-27T10:58:21.333237+00:00 app[web.1]: 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:314)
2018-02-27T10:58:21.333239+00:00 app[web.1]: 	at com.forsyslab.sonar.web.SonarApp.main(SonarApp.java:74)
2018-02-27T10:58:21.333240+00:00 app[web.1]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2018-02-27T10:58:21.333241+00:00 app[web.1]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2018-02-27T10:58:21.333242+00:00 app[web.1]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2018-02-27T10:58:21.333243+00:00 app[web.1]: 	at java.lang.reflect.Method.invoke(Method.java:498)
2018-02-27T10:58:21.333245+00:00 app[web.1]: 	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
2018-02-27T10:58:21.333246+00:00 app[web.1]: 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
2018-02-27T10:58:21.333247+00:00 app[web.1]: 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
2018-02-27T10:58:21.333248+00:00 app[web.1]: 	at org.springframework.boot.loader.WarLauncher.main(WarLauncher.java:59)
2018-02-27T10:58:21.333249+00:00 app[web.1]: 
2018-02-27T10:58:21.334927+00:00 app[web.1]: 2018-02-27 10:58:21.334 ERROR 3 --- [           main] o.s.b.f.s.DefaultListableBeanFactory     : Destroy method on bean with name 'org.springframework.boot.autoconfigure.internalCachingMetadataReaderFactory' threw an exception
2018-02-27T10:58:21.334929+00:00 app[web.1]: 
2018-02-27T10:58:21.334931+00:00 app[web.1]: java.lang.IllegalStateException: ApplicationEventMulticaster not initialized - call 'refresh' before multicasting events via the context: org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@32b260fa: startup date [Tue Feb 27 10:58:17 UTC 2018]; parent: org.springframework.context.annotation.AnnotationConfigApplicationContext@100fc185
2018-02-27T10:58:21.334932+00:00 app[web.1]: 	at org.springframework.context.support.AbstractApplicationContext.getApplicationEventMulticaster(AbstractApplicationContext.java:414)
2018-02-27T10:58:21.334934+00:00 app[web.1]: 	at org.springframework.context.support.ApplicationListenerDetector.postProcessBeforeDestruction(ApplicationListenerDetector.java:97)
2018-02-27T10:58:21.334935+00:00 app[web.1]: 	at org.springframework.beans.factory.support.DisposableBeanAdapter.destroy(DisposableBeanAdapter.java:253)
2018-02-27T10:58:21.334936+00:00 app[web.1]: 	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroyBean(DefaultSingletonBeanRegistry.java:578)
2018-02-27T10:58:21.334950+00:00 app[web.1]: 	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroySingleton(DefaultSingletonBeanRegistry.java:554)
2018-02-27T10:58:21.334952+00:00 app[web.1]: 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.destroySingleton(DefaultListableBeanFactory.java:961)
2018-02-27T10:58:21.334953+00:00 app[web.1]: 	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroySingletons(DefaultSingletonBeanRegistry.java:523)
2018-02-27T10:58:21.334955+00:00 app[web.1]: 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.destroySingletons(DefaultListableBeanFactory.java:968)
2018-02-27T10:58:21.334956+00:00 app[web.1]: 	at org.springframework.context.support.AbstractApplicationContext.destroyBeans(AbstractApplicationContext.java:1030)
2018-02-27T10:58:21.334957+00:00 app[web.1]: 	at org.springframework.context.support.AbstractApplicationContext.doClose(AbstractApplicationContext.java:1006)
2018-02-27T10:58:21.334958+00:00 app[web.1]: 	at org.springframework.context.support.AbstractApplicationContext.close(AbstractApplicationContext.java:958)
2018-02-27T10:58:21.334960+00:00 app[web.1]: 	at org.springframework.boot.SpringApplication.handleRunFailure(SpringApplication.java:750)
2018-02-27T10:58:21.334961+00:00 app[web.1]: 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:314)
2018-02-27T10:58:21.334962+00:00 app[web.1]: 	at com.forsyslab.sonar.web.SonarApp.main(SonarApp.java:74)
2018-02-27T10:58:21.334964+00:00 app[web.1]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2018-02-27T10:58:21.334965+00:00 app[web.1]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2018-02-27T10:58:21.334966+00:00 app[web.1]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2018-02-27T10:58:21.334967+00:00 app[web.1]: 	at java.lang.reflect.Method.invoke(Method.java:498)
2018-02-27T10:58:21.334973+00:00 app[web.1]: 	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
2018-02-27T10:58:21.334975+00:00 app[web.1]: 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
2018-02-27T10:58:21.334976+00:00 app[web.1]: 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
2018-02-27T10:58:21.334977+00:00 app[web.1]: 	at org.springframework.boot.loader.WarLauncher.main(WarLauncher.java:59)
</pre>

##### **Reproduce the error**

i'm sorry but i don't know how to reporduce the error 

##### **JHipster Version(s)**
"4.6.2"

##### **JHipster configuration**
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "************",
      "nativeLanguage": "en",
      "microservicePath": "*************"
    },
    "jhipsterVersion": "4.6.2",
    "baseName": "********",
    "packageName": "************",
    "packageFolder": "************",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "hazelcast",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "mongodb",
    "devDatabaseType": "mongodb",
    "prodDatabaseType": "mongodb",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": "eureka",
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "jwtSecretKey": "************",
    "clientFramework": "angularX",
    "useSass": false,
    "clientPackageManager": "yarn",
    "applicationType": "gateway",
    "testFrameworks": [
      "gatling"
    ],
    "jhiPrefix": "************",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en",
      "fr"
    ],
    "herokuAppName": "************"
  }
}
</pre>
</details>
</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_144"
Java(TM) SE Runtime Environment (build 1.8.0_144-b01)
Java HotSpot(TM) 64-Bit Server VM (build 25.144-b01, mixed mode)

git version 2.14.2

node: v9.5.0

npm: 5.6.0

yeoman: 2.0.0

yarn: 1.5.1

Docker version 17.12.0-ce, build c97c6d6

docker-compose version 1.18.0, build 8dd22a9

**Comment by ruddell** [comment]
Just for reference, the commit you are referring to is https://github.com/jhipster/jhipster/commit/f1d1f9c6f415abf2b417d57ddc15814a657573a9 but that shouldn't have affected your project as you use JHipster v4.6.2 ([which uses v1.1.8 of the jhipster server library](https://github.com/jhipster/generator-jhipster/blob/v4.6.2/generators/server/tempates/_pom.xml#L100))

So this issue started happening after you restarted your app on Heroku?

**Comment by AbderrahimRayes** [comment]
yup the issue started after the daily restart of monday 26

**Comment by ruddell** [comment]
Restarting your app wouldn't update your dependencies, so I'm not sure there's an issue on our end here.  Can you tell us your version of `jhipster-server` from your pom.xml please?

**Comment by AbderrahimRayes** [comment]
Yes @ruddell thank you very much for your support it was an error due to heroku enabled feature i'm closing the issue , sorry my bad.

**Comment by kevinbbd** [comment]
Hi @AbderrahimRayes, we are experiencing the same exception on Heroku... Would you be able to elaborate on which heroku feature was causing the issue? Thanks in advance!

**Comment by AbderrahimRayes** [comment]
Hello @kevinbbd i'm sorry for not clarifying the issue , the features was runtime-heroku-exec and runtime-heroku-metrics you can disable it by :    
heroku features:disable runtime-heroku-exec -a yourapp
heroku features:disable runtime-heroku-metrics -a yourapp

**Comment by kevinbbd** [comment]
Thanks @AbderrahimRayes!! The `heroku features:disable runtime-heroku-metrics` command is what fixed it for us. What we were experiencing was the `Picked up JAVA_TOOL_OPTIONS: -javaagent:/app/.heroku/bin/heroku-metrics-agent.jar ` was showing showing up in the logs when the application was attempting to boot. Which resulted in the following exception:

`java.lang.IllegalStateException: Cannot load configuration class: io.github.jhipster.config.metrics.PrometheusRegistry at org.springframework.context.annotation.ConfigurationClassPostProcessor.enhanceConfigurationClasses(ConfigurationClassPostProcessor.java:403)`

The [Heroku Java Metric Agent](https://github.com/heroku/heroku-java-metrics-agent) exposes a Prometheus Java client and the JHipster PrometheusRegistry is doing a `@ConditionalOnClass` to `io.prometheus.client.CollectorRegistry` which the Heroku agent is supplying, however the dependencies of the Heroku agent is different from JHipster, such as DropdownWizard metrics. This results in the `java.lang.NoClassDefFoundError: io/prometheus/client/dropwizard/DropwizardExports`
