### ISSUE TITLE
Angular Prod Webpack Build Failing v4.14.0

### ISSUE THREAD

**Issue by ruddell** [jhipster/generator-jhipster#7187]
##### **Overview of the issue**
Originally reported in gitter.  The production webpack build started failing sometime recently (maybe last 24 hours?) with the following error:
```
[INFO] --- frontend-maven-plugin:1.6:yarn (webpack build prod) @ jhipster ---
[INFO] yarn not inheriting proxy config from Maven
[INFO] Running 'yarn run webpack:prod' in /private/tmp/jh/dependency-issue
[INFO] yarn run v1.3.2
[INFO] $ yarn run cleanup && yarn run webpack:prod:main && yarn run clean-www
[INFO] $ rimraf target/{aot,www}
[INFO] $ yarn run webpack -- --config webpack/webpack.prod.js --profile
[ERROR] warning From Yarn 1.0 onwards, scripts don't require "--" for options to be forwarded. In a future version, any explicit "--" will be forwarded as-is to the scripts.
[INFO] $ node --max_old_space_size=4096 node_modules/webpack/bin/webpack.js --config webpack/webpack.prod.js --profile
[INFO] MergetJsonsWebpackPlugin compilation started...
[INFO] MergetJsonsWebpackPlugin compilation completed...
[ERROR] buffer.js:202
[ERROR]   throw new TypeError(kFromErrorMsg);
[ERROR]   ^
[ERROR] 
[ERROR] TypeError: First argument must be a string, Buffer, ArrayBuffer, Array, or array-like object.
[ERROR]     at Function.Buffer.from (buffer.js:202:9)
[ERROR]     at new Buffer (buffer.js:158:17)
[ERROR]     at writeOut (/private/tmp/jh/dependency-issue/node_modules/webpack/lib/Compiler.js:334:17)
[ERROR]     at require.forEach (/private/tmp/jh/dependency-issue/node_modules/webpack/lib/Compiler.js:345:12)
[ERROR]     at /private/tmp/jh/dependency-issue/node_modules/async/dist/async.js:3096:16
[ERROR]     at eachOfArrayLike (/private/tmp/jh/dependency-issue/node_modules/async/dist/async.js:1055:9)
[ERROR]     at eachOf (/private/tmp/jh/dependency-issue/node_modules/async/dist/async.js:1103:5)
[ERROR]     at Object.eachLimit (/private/tmp/jh/dependency-issue/node_modules/async/dist/async.js:3158:5)
[ERROR]     at emitFiles (/private/tmp/jh/dependency-issue/node_modules/webpack/lib/Compiler.js:315:21)
[ERROR]     at /private/tmp/jh/dependency-issue/node_modules/mkdirp/index.js:30:20
[ERROR]     at FSReqWrap.oncomplete (fs.js:135:15)
[ERROR] error Command failed with exit code 1.
[INFO] info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
[ERROR] error Command failed with exit code 1.
[INFO] info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
[ERROR] error Command failed with exit code 1.
[INFO] info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

##### **Reproduce the error**
Generate a project and build for prod
```
jhipster
./mvnw package -Pprod -DskipTests 
```

##### **Suggest a Fix**
Probably an npm dependency issue?

##### **JHipster Version(s)**
v4.14.0 and master 3eec6f9e9035fb99705551b4f49c8b3d7b6e9464

##### **JHipster Version(s)**

```
jhipster@0.0.0 /private/tmp/jh/dependency-issue
└── generator-jhipster@4.14.0 

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.mycompany.myapp",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "4.14.0",
    "baseName": "jhipster",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "replaced-by-jhipster-info",
    "clientFramework": "angularX",
    "useSass": false,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en"
    ]
  }
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_144"
Java(TM) SE Runtime Environment (build 1.8.0_144-b01)
Java HotSpot(TM) 64-Bit Server VM (build 25.144-b01, mixed mode)

git version 2.14.3 (Apple Git-98)

node: v8.9.3

npm: 5.6.0

bower: 1.8.2

gulp:
[13:28:05] CLI version 3.9.0

yeoman: 2.0.0

yarn: 1.3.2

Docker version 18.02.0-ce, build fc4de44

docker-compose version 1.19.0, build 9e633ef

Congratulations, JHipster execution is complete!

##### **Browsers and Operating System**

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by ruddell** [comment]
See https://github.com/jhipster/generator-jhipster/issues/7188
