### ISSUE TITLE
Unable to setup  jhipster 4.14.1 application

### ISSUE THREAD

**Issue by prasad29a** [jhipster/generator-jhipster#7212]
New to Jhipster and had follow documentation for basic installation as set on jhipster official website. 

Was not able to trace any similar issue. 

tried to setup the upgraded jhipster and repeatedly failed with error logs.
Also tried to setup new app still it  failed

Which version of JHipster are you using, is it a regression?
MVN 3.5.2
GIT 2.16.2
node v8.9.4
npm 5.6.0
jhipster 4.14.1

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**
yes, yo-rc the file is generated in directory.

If the error is during an entity creation or associated with a specific entity.
No error during entity creation had not recahed till that process.

If you are using JDL, please share that configuration as well.
Not used JDL.

What OS are you on? is this a problem with all browsers or only IE8? 
Windows 2007, chrome

- [Y ] Checking this box is mandatory (this is just to show you read everything)

Error displayed:

The Class-Path manifest attribute in C:\Users\Mitesh\.m2\repository\org\liquibase\liquibase-core\3.5.3\liquibase-core-3.5.3.jar referenced one or
 more files that do not exist: file:/C:/Users/Mitesh/.m2/repository/org/liquibase/liquibase-core/3.5.3/lib/snakeyaml-1.13.jar
16:50:42.075 [main] DEBUG org.springframework.boot.devtools.settings.DevToolsSettings - Included patterns for restart : []
16:50:42.129 [main] DEBUG org.springframework.boot.devtools.settings.DevToolsSettings - Excluded patterns for restart : [/spring-boot-starter/tar
get/classes/, /spring-boot-autoconfigure/target/classes/, /spring-boot-starter-[\w-]+/, /spring-boot/target/classes/, /spring-boot-actuator/targe
t/classes/, /spring-boot-devtools/target/classes/]
16:50:42.145 [main] DEBUG org.springframework.boot.devtools.restart.ChangeableUrls - Matching URLs for reloading : [file:/D:/Jhipster/new1/target
/classes/]
2018-03-02 16:51:23.684 ERROR 4084 --- [  restartedMain] o.s.boot.SpringApplication               : Application startup failed

java.lang.IllegalStateException: Logback configuration error detected:
ERROR in ch.qos.logback.core.rolling.RollingFileAppender[FILE] - openFile(C:\Users\Mitesh\AppData\Local\Temp\/spring.log,true) call failed. java.
io.FileNotFoundException: C:\Users\Mitesh\AppData\Local\Temp\spring.log (Access is denied)
        at org.springframework.boot.logging.logback.LogbackLoggingSystem.loadConfiguration(LogbackLoggingSystem.java:162)
        at org.springframework.boot.logging.AbstractLoggingSystem.initializeWithConventions(AbstractLoggingSystem.java:81)
        at org.springframework.boot.logging.AbstractLoggingSystem.initialize(AbstractLoggingSystem.java:59)
        at org.springframework.boot.logging.logback.LogbackLoggingSystem.initialize(LogbackLoggingSystem.java:115)
        at org.springframework.boot.logging.LoggingApplicationListener.initializeSystem(LoggingApplicationListener.java:303)
        at org.springframework.boot.logging.LoggingApplicationListener.initialize(LoggingApplicationListener.java:276)
        at org.springframework.boot.logging.LoggingApplicationListener.onApplicationEnvironmentPreparedEvent(LoggingApplicationListener.java:239)

        at org.springframework.boot.logging.LoggingApplicationListener.onApplicationEvent(LoggingApplicationListener.java:212)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:122)
        at org.springframework.boot.context.event.EventPublishingRunListener.environmentPrepared(EventPublishingRunListener.java:74)
        at org.springframework.boot.SpringApplicationRunListeners.environmentPrepared(SpringApplicationRunListeners.java:54)
        at org.springframework.boot.SpringApplication.prepareEnvironment(SpringApplication.java:325)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:296)
        at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:134)
        at org.springframework.cloud.bootstrap.BootstrapApplicationListener.bootstrapServiceContext(BootstrapApplicationListener.java:175)
        at org.springframework.cloud.bootstrap.BootstrapApplicationListener.onApplicationEvent(BootstrapApplicationListener.java:98)
        at org.springframework.cloud.bootstrap.BootstrapApplicationListener.onApplicationEvent(BootstrapApplicationListener.java:64)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:122)
        at org.springframework.boot.context.event.EventPublishingRunListener.environmentPrepared(EventPublishingRunListener.java:74)
        at org.springframework.boot.SpringApplicationRunListeners.environmentPrepared(SpringApplicationRunListeners.java:54)
        at org.springframework.boot.SpringApplication.prepareEnvironment(SpringApplication.java:325)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:296)
        at com.mycompany.myapp.New1App.main(New1App.java:68)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.boot.devtools.restart.RestartLauncher.run(RestartLauncher.java:49)

2018-03-02 16:51:23.811 ERROR 4084 --- [  restartedMain] o.s.boot.SpringApplication               : Application startup failed

java.lang.IllegalStateException: Logback configuration error detected:
ERROR in ch.qos.logback.core.rolling.RollingFileAppender[FILE] - openFile(C:\Users\Mitesh\AppData\Local\Temp\/spring.log,true) call failed. java.
io.FileNotFoundException: C:\Users\Mitesh\AppData\Local\Temp\spring.log (Access is denied)
        at org.springframework.boot.logging.logback.LogbackLoggingSystem.loadConfiguration(LogbackLoggingSystem.java:162)
        at org.springframework.boot.logging.AbstractLoggingSystem.initializeWithConventions(AbstractLoggingSystem.java:81)
        at org.springframework.boot.logging.AbstractLoggingSystem.initialize(AbstractLoggingSystem.java:59)
        at org.springframework.boot.logging.logback.LogbackLoggingSystem.initialize(LogbackLoggingSystem.java:115)
        at org.springframework.boot.logging.LoggingApplicationListener.initializeSystem(LoggingApplicationListener.java:303)
        at org.springframework.boot.logging.LoggingApplicationListener.initialize(LoggingApplicationListener.java:276)
        at org.springframework.boot.logging.LoggingApplicationListener.onApplicationEnvironmentPreparedEvent(LoggingApplicationListener.java:239)

        at org.springframework.boot.logging.LoggingApplicationListener.onApplicationEvent(LoggingApplicationListener.java:212)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:122)
        at org.springframework.boot.context.event.EventPublishingRunListener.environmentPrepared(EventPublishingRunListener.java:74)
        at org.springframework.boot.SpringApplicationRunListeners.environmentPrepared(SpringApplicationRunListeners.java:54)
        at org.springframework.boot.SpringApplication.prepareEnvironment(SpringApplication.java:325)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:296)
        at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:134)
        at org.springframework.cloud.bootstrap.BootstrapApplicationListener.bootstrapServiceContext(BootstrapApplicationListener.java:175)
        at org.springframework.cloud.bootstrap.BootstrapApplicationListener.onApplicationEvent(BootstrapApplicationListener.java:98)
        at org.springframework.cloud.bootstrap.BootstrapApplicationListener.onApplicationEvent(BootstrapApplicationListener.java:64)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:122)
        at org.springframework.boot.context.event.EventPublishingRunListener.environmentPrepared(EventPublishingRunListener.java:74)
        at org.springframework.boot.SpringApplicationRunListeners.environmentPrepared(SpringApplicationRunListeners.java:54)
        at org.springframework.boot.SpringApplication.prepareEnvironment(SpringApplication.java:325)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:296)
        at com.mycompany.myapp.New1App.main(New1App.java:68)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.boot.devtools.restart.RestartLauncher.run(RestartLauncher.java:49)

[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 07:55 min
[INFO] Finished at: 2018-03-02T16:51:25+05:30
[INFO] Final Memory: 63M/398M
[INFO] ------------------------------------------------------------------------

D:\Jhipster\new1>spring-boot-starter
'spring-boot-starter' is not recognized as an internal or external command,
operable program or batch file.

D:\Jhipster\new1>yarn start
yarn run v1.5.1
$ yarn run webpack:dev
$ yarn run webpack-dev-server -- --config webpack/webpack.dev.js --progress --inline --hot --profile --port=9060 --watch-content-base
warning From Yarn 1.0 onwards, scripts don't require "--" for options to be forwarded. In a future version, any explicit "--" will be forwarded a
s-is to the scripts.
$ node --max_old_space_size=4096 node_modules/webpack-dev-server/bin/webpack-dev-server.js --config webpack/webpack.dev.js --progress --inline --
hot --profile --port=9060 --watch-content-base
module.js:540
    throw err;
    ^

Error: Cannot find module 'D:\Jhipster\new1\node_modules\webpack-dev-server\bin\webpack-dev-server.js'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.Module._load (module.js:468:25)
    at Function.Module.runMain (module.js:684:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
error An unexpected error occurred: "Command failed.
Exit code: 1
Command: C:\\Windows\\system32\\cmd.exe
Arguments: /d /s /c node --max_old_space_size=4096 node_modules/webpack-dev-server/bin/webpack-dev-server.js --config webpack/webpack.dev.js --pr
ogress --inline --hot --profile --port=9060 --watch-content-base
Directory: D:\\Jhipster\
ew1
Output:
".
info If you think this is a bug, please open a bug report with the information provided in "D:\\Jhipster\
ew1\\yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error An unexpected error occurred: "Command failed.
Exit code: 1
Command: C:\\Windows\\system32\\cmd.exe
Arguments: /d /s /c yarn run webpack-dev-server -- --config webpack/webpack.dev.js --progress --inline --hot --profile --port=9060 --watch-conten
t-base
Directory: D:\\Jhipster\
ew1
Output:
".
info If you think this is a bug, please open a bug report with the information provided in "D:\\Jhipster\
ew1\\yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error An unexpected error occurred: "Command failed.
Exit code: 1
Command: C:\\Windows\\system32\\cmd.exe
Arguments: /d /s /c yarn run webpack:dev
Directory: D:\\Jhipster\
ew1
Output:
".
info If you think this is a bug, please open a bug report with the information provided in "D:\\Jhipster\
ew1\\yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
[rc.txt](https://github.com/jhipster/generator-jhipster/files/1775010/rc.txt)

**Comment by jdubois** [comment]
The first error message you have is:

    C:\Users\Mitesh\AppData\Local\Temp\spring.log (Access is denied)

So 2 things here:

- You need to have the correct permissions on your filesystem to write your log file
- This is not configured by JHipster, as we follow the 12Factors and log to the console -> where does this file come from, did you configure anything?

You then run commands like `spring-boot-starter` and I have no idea where they come from... So I can't help you there, but those are not from JHipster

**Comment by prasad29a** [comment]
As pointed, 
[Path File.docx](https://github.com/jhipster/generator-jhipster/files/1775558/Path.File.docx)

After changing the status of permission i was able to carry process. 
I went through permission set for users and change access as "Full Control". As permission was chnaged i  created a new app which build was successful.

new project app created:
Even when build was successful the warning which i face was, after running command  jhipster

Warning occur:

yarn install v1.5.1
info No lockfile found.
[1/5] Validating package.json...
[2/5] Resolving packages...
warning Resolution field "source-map@0.6.1" is incompatible with requested version "source-map@^0.5.6"
warning Resolution field "source-map@0.6.1" is incompatible with requested version "source-map@0.5.x"
warning Resolution field "source-map@0.6.1" is incompatible with requested version "source-map@^0.5.3"
warning Resolution field "source-map@0.6.1" is incompatible with requested version "source-map@^0.5.6"
warning Resolution field "source-map@0.6.1" is incompatible with requested version "source-map@0.1.x"
warning Resolution field "source-map@0.6.1" is incompatible with requested version "source-map@^0.5.3"
warning Resolution field "source-map@0.6.1" is incompatible with requested version "source-map@^0.5.6"
warning Resolution field "source-map@0.6.1" is incompatible with requested version "source-map@^0.5.6"
warning Resolution field "source-map@0.6.1" is incompatible with requested version "source-map@^0.5.6"
warning Resolution field "source-map@0.6.1" is incompatible with requested version "source-map@^0.5.6"
warning Resolution field "source-map@0.6.1" is incompatible with requested version "source-map@~0.5.1"
warning Resolution field "source-map@0.6.1" is incompatible with requested version "source-map@~0.4.1"
warning Resolution field "source-map@0.6.1" is incompatible with requested version "source-map@0.5.x"
warning Resolution field "source-map@0.6.1" is incompatible with requested version "source-map@^0.5.7"
warning Resolution field "source-map@0.6.1" is incompatible with requested version "source-map@^0.4.2"
warning Resolution field "source-map@0.6.1" is incompatible with requested version "source-map@^0.5.3"
warning Resolution field "source-map@0.6.1" is incompatible with requested version "source-map@^0.5.6"
warning Resolution field "source-map@0.6.1" is incompatible with requested version "source-map@^0.5.6"
warning Resolution field "source-map@0.6.1" is incompatible with requested version "source-map@^0.5.6"
warning browser-sync > browser-sync-ui > weinre > express@2.5.11: express 2.x series is deprecated
warning browser-sync > browser-sync-ui > weinre > express > connect@1.9.2: connect 1.x series is deprecated
warning Resolution field "source-map@0.6.1" is incompatible with requested version "source-map@^0.5.6"
warning Resolution field "source-map@0.6.1" is incompatible with requested version "source-map@~0.5.0"
warning Resolution field "source-map@0.6.1" is incompatible with requested version "source-map@^0.5.3"
warning Resolution field "source-map@0.6.1" is incompatible with requested version "source-map@^0.5.1"
warning Resolution field "source-map@0.6.1" is incompatible with requested version "source-map@~0.2.0"
warning Resolution field "source-map@0.6.1" is incompatible with requested version "source-map@^0.4.4"
warning karma-remap-istanbul > remap-istanbul > gulp-util@3.0.7: gulp-util is deprecated - replace it, following the guidelines at https://medium
.com/gulpjs/gulp-util-ca3b1f9f9ac5
warning Resolution field "source-map@0.6.1" is incompatible with requested version "source-map@^0.1.41"
warning Resolution field "source-map@0.6.1" is incompatible with requested version "source-map@^0.4.2"
[3/5] Fetching packages...
info fsevents@1.1.3: The platform "win32" is incompatible with this module.
info "fsevents@1.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
[4/5] Linking dependencies...
warning " > bootstrap@4.0.0" has unmet peer dependency "popper.js@^1.12.9".
[5/5] Building fresh packages...
success Saved lockfile.
$ node node_modules/phantomjs-prebuilt/install.js
Found PhantomJS at D:\Jhipster\project8\node_modules\phantomjs-prebuilt\lib\phantom\bin\phantomjs.exe ...verifying
PhantomJS is previously installed at D:\Jhipster\project8\node_modules\phantomjs-prebuilt\lib\phantom\bin\phantomjs.exe
Done in 488.26s.
yarn run v1.5.1
$ yarn run cleanup && yarn run webpack:build:main
$ rimraf target/{aot,www}
$ yarn run webpack -- --config webpack/webpack.dev.js --progress --profile
warning From Yarn 1.0 onwards, scripts don't require "--" for options to be forwarded. In a future version, any explicit "--" will be forwarded a
s-is to the scripts.
$ node --max_old_space_size=4096 node_modules/webpack/bin/webpack.js --config webpack/webpack.dev.js --progress --profile
 10% building modules 1/4 modules 3 active ...\main\webapp\content\scss\global.scssWarning: The 'no-unused-variable' rule requires type infomatio
n.


I ran command mvnw which build status was success but here error occure :

The Class-Path manifest attribute in C:\Users\Mitesh\.m2\repository\org\liquibase\liquibase-core\3.5.3\liquibase-core-3.5.3.jar referenced one or
 more files that do not exist: file:/C:/Users/Mitesh/.m2/repository/org/liquibase/liquibase-core/3.5.3/lib/snakeyaml-1.13.jar
19:56:58.390 [main] DEBUG org.springframework.boot.devtools.settings.DevToolsSettings - Included patterns for restart : []
19:56:58.393 [main] DEBUG org.springframework.boot.devtools.settings.DevToolsSettings - Excluded patterns for restart : [/spring-boot-starter/tar
get/classes/, /spring-boot-autoconfigure/target/classes/, /spring-boot-starter-[\w-]+/, /spring-boot/target/classes/, /spring-boot-actuator/targe
t/classes/, /spring-boot-devtools/target/classes/]
19:56:58.393 [main] DEBUG org.springframework.boot.devtools.restart.ChangeableUrls - Matching URLs for reloading : [file:/D:/Jhipster/project8/ta
rget/classes/]
2018-03-02 19:57:00.346 ERROR 4860 --- [  restartedMain] o.s.boot.SpringApplication               : Application startup failed

java.lang.IllegalStateException: Logback configuration error detected:
ERROR in ch.qos.logback.core.rolling.RollingFileAppender[FILE] - openFile(C:\Users\Mitesh\AppData\Local\Temp\/spring.log,true) call failed. java.
io.FileNotFoundException: C:\Users\Mitesh\AppData\Local\Temp\spring.log (Access is denied)
        at org.springframework.boot.logging.logback.LogbackLoggingSystem.loadConfiguration(LogbackLoggingSystem.java:162)
        at org.springframework.boot.logging.AbstractLoggingSystem.initializeWithConventions(AbstractLoggingSystem.java:81)
        at org.springframework.boot.logging.AbstractLoggingSystem.initialize(AbstractLoggingSystem.java:59)
        at org.springframework.boot.logging.logback.LogbackLoggingSystem.initialize(LogbackLoggingSystem.java:115)
        at org.springframework.boot.logging.LoggingApplicationListener.initializeSystem(LoggingApplicationListener.java:303)
        at org.springframework.boot.logging.LoggingApplicationListener.initialize(LoggingApplicationListener.java:276)
        at org.springframework.boot.logging.LoggingApplicationListener.onApplicationEnvironmentPreparedEvent(LoggingApplicationListener.java:239)

        at org.springframework.boot.logging.LoggingApplicationListener.onApplicationEvent(LoggingApplicationListener.java:212)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:122)
        at org.springframework.boot.context.event.EventPublishingRunListener.environmentPrepared(EventPublishingRunListener.java:74)
        at org.springframework.boot.SpringApplicationRunListeners.environmentPrepared(SpringApplicationRunListeners.java:54)
        at org.springframework.boot.SpringApplication.prepareEnvironment(SpringApplication.java:325)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:296)
        at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:134)
        at org.springframework.cloud.bootstrap.BootstrapApplicationListener.bootstrapServiceContext(BootstrapApplicationListener.java:175)
        at org.springframework.cloud.bootstrap.BootstrapApplicationListener.onApplicationEvent(BootstrapApplicationListener.java:98)
        at org.springframework.cloud.bootstrap.BootstrapApplicationListener.onApplicationEvent(BootstrapApplicationListener.java:64)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:122)
        at org.springframework.boot.context.event.EventPublishingRunListener.environmentPrepared(EventPublishingRunListener.java:74)
        at org.springframework.boot.SpringApplicationRunListeners.environmentPrepared(SpringApplicationRunListeners.java:54)
        at org.springframework.boot.SpringApplication.prepareEnvironment(SpringApplication.java:325)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:296)
        at com.mycompany.myapp.Project8App.main(Project8App.java:68)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.boot.devtools.restart.RestartLauncher.run(RestartLauncher.java:49)

2018-03-02 19:57:00.365 ERROR 4860 --- [  restartedMain] o.s.boot.SpringApplication

**Comment by jdubois** [comment]
I'm sorry but what is the issue here? And I can't open a Word document, could you format this correctly in the ticket?

**Comment by gmarziou** [comment]
I opened the word file and there's just screenshots showing that the jar files exist in~/ .m2

I would suggest that you cleanup our .m2 repository and re-try

> The Class-Path manifest attribute in C:\Users\Mitesh.m2\repository\org\liquibase\liquibase-core\3.5.3\liquibase-core-3.5.3.jar referenced one or
more files that do not exist: file:/C:/Users/Mitesh/.m2/repository/org/liquibase/liquibase-core/3.5.3/lib/snakeyaml-1.13.jar

I know @henri-tremblay had similar error yesterday on gitter, maybe he could help.

**Comment by henri-tremblay** [comment]
It is really a weirdness of liquibase and I will consider it to be a bug on their side. The `liquibase-core` jar having a classpath entry in the manifest `lib/snakeyaml-1.13.jar`. Thus the error. Version 3.3.5 has the same issue. The dependency probably comes from the bundling. There is a `Main-Class` specified as well.

**Comment by prasad29a** [comment]
@henri-tremblay  I tried by deleting  files inside  .m2 . ran mvnw,  files were downloaded but same error occured,

The Class-Path manifest attribute in C:\Users\Mitesh.m2\repository\org\liquibase\liquibase-core\3.5.3\liquibase-core-3.5.3.jar referenced one or
more files that do not exist: file:/C:/Users/Mitesh/.m2/repository/org/liquibase/liquibase-core/3.5.3/lib/snakeyaml-1.13.jar

so i tried unsitalling maven and installing apache-maven-3.5.2 but still in vain. 
Can you guide how you were able to solve it.

**Comment by gmarziou** [comment]
This [Liquibase issue](https://liquibase.jira.com/browse/CORE-3046) links to Spring Boot with a trick that you could try:
add `liquibase.change-log: classpath:config/liquibase/master.xml` to application.yml in src/main/resources and src/test/resources. Although I'm not sure it could work as it is already done in code in [DatabaseConfiguration.java](https://github.com/jhipster/jhipster-sample-app/blob/master/src/main/java/io/github/jhipster/sample/config/DatabaseConfiguration.java#L81).

The fact is that I don't understand why only few users like you have this issue.

If it does not work, then you can try hackier ways:

- download snakeyaml-1.13.jar and copy it to where liquibase expects it:
~~~
   mkdir C:\Users\Mitesh.m2\repository\org\liquibase\liquibase-core\3.5.3\lib
   copy snakeyaml-1.13.jar C:\Users\Mitesh.m2\repository\org\liquibase\liquibase-core\3.5.3\lib
~~~
- clone the Liquibase git repo, checkout 3.5.3 branch, delete the [snakeyaml line from manifest](https://github.com/liquibase/liquibase/blob/liquibase-parent-3.5.3/liquibase-core/src/main/resources/META-INF/MANIFEST.MF#L3), build it locally and copy it to your .m2
- unzip the liquibase-core jar file in your .m2, edit manifest and re-zip

**Comment by prasad29a** [comment]
@gmarziou  both the build were successful for yarn and maven. 
but now when i tried for new application build error displayed  jhipster is not recognized as an internal or external command. Java, Git, Node.js, Yarn and Yeoman are are installed.

**Comment by gmarziou** [comment]
Look at your `PATH` environment variable and ensure it includes the location returned by `yarn global bin`. This is where the `jhipster.cmd` file (and other global node binaries) must have been installed.

**Comment by prasad29a** [comment]
Issue:
The Class-Path manifest attribute in C:\Users\Mitesh.m2\repository\org\liquibase\liquibase-core\3.5.3\liquibase-core-3.5.3.jar referenced one or
more files that do not exist: file:/C:/Users/Mitesh/.m2/repository/org/liquibase/liquibase-core/3.5.3/lib/snakeyaml-1.13.jar
16:50:42.075 [main] DEBUG org.springframework.boot.devtools.settings.DevToolsSettings - Included patterns for restart : []
16:50:42.129 [main] DEBUG org.springframework.boot.devtools.settings.DevToolsSettings - Excluded patterns for restart : [/spring-boot-starter/tar
get/classes/, /spring-boot-autoconfigure/target/classes/, /spring-boot-starter-[\w-]+/, /spring-boot/target/classes/, /spring-boot-actuator/targe
t/classes/, /spring-boot-devtools/target/classes/]
16:50:42.145 [main] DEBUG org.springframework.boot.devtools.restart.ChangeableUrls - Matching URLs for reloading : [file:/D:/Jhipster/new1/target
/classes/]
2018-03-02 16:51:23.684 ERROR 4084 --- [ restartedMain] o.s.boot.SpringApplication : Application startup failed


Solution tried:

download snakeyaml-1.13.jar and copy it to where liquibase expects it:
mkdir C:\Users\Mitesh.m2\repository\org\liquibase\liquibase-core\3.5.3\lib
copy snakeyaml-1.13.jar C:\Users\Mitesh.m2\repository\org\liquibase\liquibase-core\3.5.3\lib
clone the Liquibase git repo, checkout 3.5.3 branch, delete the snakeyaml line from manifest, build it locally and copy it to your .m2
unzip the liquibase-core jar file in your .m2, edit manifest and re-zip


In environment variables added a path to:

C:\Users\Mitesh\.m2\repository\org\liquibase\liquibase-core\3.5.3\;


Thnx @gmarziou , It works.
hope it will help you for future issue raised.
