### ISSUE TITLE
" Cannot find module 'gulp-filter' " when using jhipster command

### ISSUE THREAD

**Issue by chrisdns** [jhipster/generator-jhipster#7275]
##### **Overview of the issue**
It is no longer possible to generate an app, it stops right after using 'jhipster' command :

``ERROR! Cannot find module 'gulp-filter'
{ Error: Cannot find module 'gulp-filter'
    at Function.Module._resolveFilename (module.js:557:15)
    at Function.Module._load (module.js:484:25)
    at Module.require (module.js:606:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/ippon/Documents/generator-jhipster/generators/generator-base-private.js:31:16)
    at Module._compile (module.js:662:30)
    at Object.Module._extensions..js (module.js:673:10)
    at Module.load (module.js:575:32)
    at tryModuleLoad (module.js:515:12)
    at Function.Module._load (module.js:507:3) code: 'MODULE_NOT_FOUND' }
``

##### **Reproduce the error**
`mkdir test-app`
`cd test-app`
`jhipster`

##### **Related issues**
This issue may be related to the commit 8d55cd945e0ad2ed7c6da2779a35c536ccaea55c

##### **JHipster Version(s)**
Latest version of JHipster

##### **Browsers and Operating System**
- Firefox Quantum
- Ubuntu 17.10 

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by sendilkumarn** [comment]
@chrisdns Just try to run yarn install in your local generator and then re-link it 

It should fix the problem.

**Comment by chrisdns** [comment]
Thank you


2018-03-12 10:29 GMT+01:00 Sendil Kumar N <notifications@github.com>:
