### ISSUE TITLE
Kafka UnknownHostException exception in Kubernetes

### ISSUE THREAD

**Issue by pavankjadda** [jhipster/generator-jhipster#7334]
##### **Overview of the issue**
I have a project with two microservices and gateway generated through JHipster. I deployed the project in AWS cloud using [Kubernetes by Heptio on AWS](https://aws.amazon.com/quickstart/architecture/heptio-kubernetes/). Kafka container failed to start after several attempts. When I logged into the container through `kubectl`, I found out that Kafka unable to recognize the zookeeper hostname. Kafka and Zookeeper configuration files generated by JHipster.

##### **Motivation for or Use Case**

I think this bug is caused by `chargecodes-kafka.yml` file (copied below) generated by jhipster for kubernetes

##### **Reproduce the error**

1. Clone the [repository](https://github.com/pavankjadda/Kubernetes-SpringCloudStream-Kafka-Docker) and deploy in local machine or cloud 

##### **Suggest a Fix**

Exception:
```

pjadda$ kubectl attach -it chargecodes-kafka-5799d8f99b-wnqhc  -n duppoc
Unable to use a TTY - container kafka did not allocate one
If you don't see a command prompt, try pressing enter.
waiting for kafka to be ready
waiting for kafka to be ready
[2018-03-21 00:22:29,263] INFO Terminate ZkClient event thread. (org.I0Itec.zkclient.ZkEventThread)
[2018-03-21 00:22:29,265] FATAL Fatal error during KafkaServer startup. Prepare to shutdown (kafka.server.KafkaServer)
org.I0Itec.zkclient.exception.ZkException: Unable to connect to chargecodes-zookeeper.duppoc.svc.cluster.local:2181
	at org.I0Itec.zkclient.ZkConnection.connect(ZkConnection.java:72)
	at org.I0Itec.zkclient.ZkClient.connect(ZkClient.java:1228)
	at org.I0Itec.zkclient.ZkClient.<init>(ZkClient.java:157)
	at org.I0Itec.zkclient.ZkClient.<init>(ZkClient.java:131)
	at kafka.utils.ZkUtils$.createZkClientAndConnection(ZkUtils.scala:115)
	at kafka.utils.ZkUtils$.withMetrics(ZkUtils.scala:92)
	at kafka.server.KafkaServer.initZk(KafkaServer.scala:350)
	at kafka.server.KafkaServer.startup(KafkaServer.scala:194)
	at kafka.server.KafkaServerStartable.startup(KafkaServerStartable.scala:38)
	at kafka.Kafka$.main(Kafka.scala:92)
	at kafka.Kafka.main(Kafka.scala)
Caused by: java.net.UnknownHostException: chargecodes-zookeeper.duppoc.svc.cluster.local: System error
	at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
	at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:928)
	at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1323)
	at java.net.InetAddress.getAllByName0(InetAddress.java:1276)
	at java.net.InetAddress.getAllByName(InetAddress.java:1192)
	at java.net.InetAddress.getAllByName(InetAddress.java:1126)
	at org.apache.zookeeper.client.StaticHostProvider.<init>(StaticHostProvider.java:61)
	at org.apache.zookeeper.ZooKeeper.<init>(ZooKeeper.java:445)
	at org.apache.zookeeper.ZooKeeper.<init>(ZooKeeper.java:380)
	at org.I0Itec.zkclient.ZkConnection.connect(ZkConnection.java:70)
	... 10 more
[2018-03-21 00:22:29,269] INFO shutting down (kafka.server.KafkaServer)
[2018-03-21 00:22:29,280] INFO shut down completed (kafka.server.KafkaServer)
[2018-03-21 00:22:29,281] FATAL Exiting Kafka. (kafka.server.KafkaServerStartable)
[2018-03-21 00:22:29,283] INFO shutting down (kafka.server.KafkaServer)
```

Kubernetes Pods:

```
NAME                                     READY     STATUS             RESTARTS   AGE
chargecodes-56fdf7cd49-fsrhb             0/1       CrashLoopBackOff   7          14m
chargecodes-kafka-5799d8f99b-wnqhc       0/1       CrashLoopBackOff   7          14m
chargecodes-mysql-5d8f4c9484-hxlrl       1/1       Running            0          14m
chargecodes-zookeeper-85d59f6759-lf4mh   1/1       Running            0          14m
jhipster-registry-0                      1/1       Running            0          14m
jhipster-registry-1                      1/1       Running            0          14m

```

chargecodes-kafka.yml

```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: chargecodes-kafka
  namespace: duppoc
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: chargecodes-kafka
    spec:
      containers:
      - name: kafka
        image: wurstmeister/kafka:1.0.0
        env:
        - name: KAFKA_ADVERTISED_HOST_NAME
          value: chargecodes-kafka.duppoc.svc.cluster.local
        - name: KAFKA_ADVERTISED_PORT
          value: '9092'
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: chargecodes-zookeeper.duppoc.svc.cluster.local:2181
        - name: KAFKA_CREATE_TOPICS
          value: 'topic-jhipster:1:1'
        ports:
        - containerPort: 9092
---
apiVersion: v1
kind: Service
metadata:
  name: chargecodes-kafka
  namespace: duppoc
spec:
  selector:
    app: chargecodes-kafka
  ports:
  - port: 9092
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: chargecodes-zookeeper
  namespace: duppoc
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: chargecodes-zookeeper
    spec:
      containers:
      - name: zookeeper
        image: wurstmeister/zookeeper:3.4.6
        ports:
        - containerPort: 2181
---
apiVersion: v1
kind: Service
metadata:
  name: chargecodes-zookeeper
  namespace: duppoc
spec:
  selector:
    app: chargecodes-zookeeper
  ports:
  - port: 2181
```

##### **JHipster Version(s)**
4.14.1
##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

```

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "appsFolders": [
      "chargecodes",
      "gateway",
      "projects"
    ],
    "directoryPath": "../",
    "serviceDiscoveryType": "eureka",
    "jwtSecretKey": "replaced-by-jhipster-info",
    "dockerRepositoryName": "645729154151.dkr.ecr.us-west-2.amazonaws.com/duppoc",
    "dockerPushCommand": "docker push",
    "kubernetesNamespace": "duppoc",
    "kubernetesServiceType": "LoadBalancer"
  }
}
</pre>
</details>


##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>




</pre>
</details>


##### **Environment and Tools**

java version "1.8.0_144"
Java(TM) SE Runtime Environment (build 1.8.0_144-b01)
Java HotSpot(TM) 64-Bit Server VM (build 25.144-b01, mixed mode)

git version 2.13.1

node: v8.9.4

bower: 1.8.2

gulp:
[20:46:44] CLI version 3.9.1

yarn: 1.5.1

Docker version 17.12.0-ce, build c97c6d6

docker-compose version 1.18.0, build 8dd22a9

```

##### **Browsers and Operating System**

Chrome 65, macOS 10.13.4

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by pavankjadda** [comment]
Wrong github repository. Created issue in Kubernetes repo.

**Comment by pavankjadda** [comment]
@deskera-ci https://github.com/kubernetes/kubernetes/issues/61232
