### ISSUE TITLE
Travis: random failures for e2e, caused by chromedriver

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/generator-jhipster#7388]
##### **Overview of the issue**

When launching e2e in Travis builds, there are some random errors:

```
[10:00:40] I/launcher - Running 1 instances of WebDriver
[10:00:40] I/direct - Using ChromeDriver directly...
[10:00:40] E/direct - Error code: 135
[10:00:40] E/direct - Error message: Could not find chromedriver at /home/travis/.config/yarn/global/node_modules/webdriver-manager/selenium/chromedriver_2.37. Run 'webdriver-manager update' to download binaries.
[10:00:40] E/direct - Error: Could not find chromedriver at /home/travis/.config/yarn/global/node_modules/webdriver-manager/selenium/chromedriver_2.37. Run 'webdriver-manager update' to download binaries.
    at Direct.getNewDriver (/home/travis/app/node_modules/protractor/lib/driverProviders/direct.ts:78:17)
    at Runner.createBrowser (/home/travis/app/node_modules/protractor/lib/runner.ts:225:39)
    at q.then.then (/home/travis/app/node_modules/protractor/lib/runner.ts:391:27)
    at _fulfilled (/home/travis/app/node_modules/protractor/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/home/travis/app/node_modules/protractor/node_modules/q/q.js:863:30)
    at Promise.promise.promiseDispatch (/home/travis/app/node_modules/protractor/node_modules/q/q.js:796:13)
    at /home/travis/app/node_modules/protractor/node_modules/q/q.js:556:49
    at runSingle (/home/travis/app/node_modules/protractor/node_modules/q/q.js:137:13)
    at flush (/home/travis/app/node_modules/protractor/node_modules/q/q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
[10:00:40] E/launcher - Process exited with error code 135
error An unexpected error occurred: "Command failed.
Exit code: 135
```

##### **Motivation for or Use Case**

It's strange because we have a `postinstall` in `package.json` file:

https://github.com/jhipster/generator-jhipster/blob/master/generators/client/templates/angular/package.json.ejs#L157

Here the logs of this `postinstall` step, when it's KO:

```
$ webdriver-manager update
[05:02:01] I/file_manager - creating folder /home/travis/app/node_modules/webdriver-manager/selenium
(node:8164) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Failed to make Github request, rate limit reached.
(node:8164) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[05:02:01] I/update - chromedriver: unzipping chromedriver_2.37.zip
[05:02:01] I/update - chromedriver: setting permissions to 0755 for /home/travis/app/node_modules/webdriver-manager/selenium/chromedriver_2.37
```

When it's OK:

```
$ webdriver-manager update
[04:42:19] I/file_manager - creating folder /home/travis/app/node_modules/webdriver-manager/selenium
[04:42:20] I/update - chromedriver: unzipping chromedriver_2.37.zip
[04:42:20] I/update - chromedriver: setting permissions to 0755 for /home/travis/app/node_modules/webdriver-manager/selenium/chromedriver_2.37
[04:42:21] I/update - geckodriver: unzipping geckodriver-v0.20.0.tar.gz
[04:42:21] I/update - geckodriver: setting permissions to 0755 for /home/travis/app/node_modules/webdriver-manager/selenium/geckodriver-v0.20.0
```

##### **Related issues**

@JulioJu tried to find a solution in this PR https://github.com/jhipster/generator-jhipster/pull/7311

##### **Suggest a Fix**

https://help.appveyor.com/discussions/problems/6628-protractor-webdriver-manager-update-fails-due-to-github-api-limits

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by pascalgrimaud** [comment]
@JulioJu : I'm trying your fix, but directly in `package.json` -> https://github.com/pascalgrimaud/generator-jhipster/commit/b9c529de4b454778897fcc676c4710ebdd2dfccc

Let's wait my Travis build: https://travis-ci.org/pascalgrimaud/generator-jhipster/builds/360816204

**Comment by gmarziou** [comment]
It might not solve this issue but I think we should not use a postinstall script to update webdriver-manager, I have seen several projects where they changed to a simple run script not an npm hook. The benefit for Travis builds is that we could have a different setup than for our users. For users build, this could be covered by instructions and by modifying the prod build in maven and gradle.

**Comment by JulioJu** [comment]
@pascalgrimaud 
If I understand well the code, `yarn postinstall` is never called. `webdriver-manager update` seems to be launch by `protractor`, not by `yarn`. It is launch each time the command `yarn e2e` a.k.a `protractor src/test/javascript/protractor.conf.js`. 

I don't understand why 4da25651ef9f6d04ade33e85e0ba77d019f2271d doesn't work (the build of this night). At https://travis-ci.org/jhipster/generator-jhipster/jobs/360742977, line 610 we could read « [09:46:21] I/update - chromedriver: setting permissions to 0755 for /home/travis/.config/yarn/global/node_modules/webdriver-manager/selenium/chromedriver_2.37 ». Line 4996 we could read « [10:00:40] E/direct - Error message: Could not find chromedriver at /home/travis/.config/yarn/global/node_modules/webdriver-manager/selenium/chromedriver_2.37. ». It's strange…

**Comment by gmarziou** [comment]
postinstall is an npm hook, it's called automatically by yarn or npm after an npm install or yarn install.

**Comment by pascalgrimaud** [comment]
@gmarziou : is it mandatory to use this postinstall ? Can we remove it ? Or replace this postinstall and put the update in another place ?

**Comment by gmarziou** [comment]
@pascalgrimaud I'm not an expert. In few projects I looked at, they define a selenium entry in package.json scripts that updates the driver and starts it :

~~~json
    "selenium": "webdriver-manager update && webdriver-manager start",
~~~

One thing I notice, is that in our current setup, we don't call "webdriver-manager start" so I don't understand how it works now.

This way, to run protractor, we would have to run this sequence

~~~
yarn run selenium
yarn e2e
~~~

In interactive run, selenium would be run only once while e2e would be run as offten.

This sequence could be added to maven and gradle

**Comment by pascalgrimaud** [comment]
Ok, I'm like you, not expert in this part :)
I'm trying to put `gecko --false` in my PR, but I don't understand what it is, just followed some suggestions in tickets / blog. Hope it will fix the issue

**Comment by JulioJu** [comment]
@pascalgrimaud and @gmarziou 

If I understand well, the problem is than geckodriver is hosted by Github. So each time we launch a Travis build, we dowload the gecko driver on Github. So «  Github's API's rate limit is being hit. » (see [this](https://github.com/angular/webdriver-manager/issues/216#issuecomment-284295409)). Or « The Search API has a custom rate limit. For requests using Basic Authentication, OAuth, or client ID and secret, you can make up to 30 requests per minute. For unauthenticated requests, the rate limit allows you to make up to 10 requests per minute. » (see [this](https://developer.github.com/v3/search/#rate-limit). There is no problem with Chromedriver), because it's not hosted by Github. 

There is an other solution: to use the `--out-dir` argument. (`webdriver-manager update --out_dir /some/path/to/selenium`  (https://github.com/angular/webdriver-manager/issues/216#issuecomment-293648769)

**Comment by JulioJu** [comment]
Note. If there is others random download problems, maybe we could investigate this solution again. I don't know if there is others npm_package than hit GitHub. But a radical solution could be to use only one per Travis build, then link all generator-jhipster/travis/samples/**ngx**sample/node_modules to it.

**Comment by jdubois** [comment]
Very good catch @JulioJu !
We should try to find a mirror and not rely on Github.

**Comment by pascalgrimaud** [comment]
@JulioJu : good idea, I think we can do this:
- at the end of build, if `node_modules/webdriver-manager/selenium/` is not empty, save in another folder and use Travis cache
- next build, if `node_modules/webdriver-manager/selenium/` is empty, use the cache folder, so `yarn e2e` won't fail
