### ISSUE TITLE
Move EntityResolvePagingParams to ng-jhipster

### ISSUE THREAD

**Issue by azizkhani** [jhipster/generator-jhipster#7403]
Why each entity that have pagination will add this Resolver ?

```
@Injectable()
export class UserResolvePagingParams implements Resolve<any> {

    constructor(private paginationUtil: JhiPaginationUtil) {}

    resolve(route: ActivatedRouteSnapshot, state: RouterStateSnapshot) {
        const page = route.queryParams['page'] ? route.queryParams['page'] : '1';
        const sort = route.queryParams['sort'] ? route.queryParams['sort'] : 'id,asc';
        return {
            page: this.paginationUtil.parsePage(page),
            predicate: this.paginationUtil.parsePredicate(sort),
            ascending: this.paginationUtil.parseAscending(sort)
        };
    }
}
```

I think sort order , maybe different from entity to another entity that developer need to change after generated code  . 
We can send data to resolver and read this data in resolver 

Like This 

```
export const userMgmtRoute: Routes = [
    {
        path: 'user-management',
        component: UserMgmtComponent,
        resolve: {
            'pagingParams': UserResolvePagingParams
        },
        data: {
            pageTitle: 'userManagement.home.title'
        }
    }
];
```

to this 

```
// in ng-jhipster
@Injectable()
export class EntityResolvePagingParams implements Resolve<any> {

    constructor(private paginationUtil: JhiPaginationUtil) {}

    resolve(route: ActivatedRouteSnapshot, state: RouterStateSnapshot) {
        const page = route.queryParams['page'] ? route.queryParams['page'] : '1';
        const sort = route.queryParams['sort'] ? route.queryParams['sort'] : route.data['defaultSort'];
        return {
            page: this.paginationUtil.parsePage(page),
            predicate: this.paginationUtil.parsePredicate(sort),
            ascending: this.paginationUtil.parseAscending(sort)
        };
    }
}


// in entity.route.ts
export const userMgmtRoute: Routes = [
    {
        path: 'user-management',
        component: UserMgmtComponent,
        resolve: {
            'pagingParams': EntityResolvePagingParams
        },
        data: {
            pageTitle: 'userManagement.home.title',
            defaultSort: 'id,asc'
        }
    }
];
```

**Comment by deepu105** [comment]
Yes we can move it. Can you do PR?

Thanks & Regards,
Deepu

**Comment by azizkhani** [comment]
@deepu105 
create entity-resolvePagingParams.ts in which directory? service directory? what  is ts and class  name?

**Comment by deepu105** [comment]
It could be service I guess and use the same name as original

**Comment by azizkhani** [comment]
@deepu105 can i test with yarn link in sample-app?

**Comment by deepu105** [comment]
yarn link works pretty weird, you could try, what i do is run npm pack to make a tarball and then npm install it on the generated project from the tarball

**Comment by azizkhani** [comment]
I think all my change is ok . but get this exception 

https://github.com/azizkhani/ng-jhipster

`TS2305: Module '"/Users/azizkhani/Data/git/ng-jhipster/index"' has no exported member 'JhiResolvePagingParams'.`

**Comment by azizkhani** [comment]
@deepu105 https://github.com/azizkhani/ng-jhipster/commit/f8f8cdc69d5b4203dbae870e993d50aa1f8d89cd

**Comment by azizkhani** [comment]
I write test and complete source but after run test i get exception in language service 

```
 LanguageService Test
    ✖ should change Language
      Chrome 65.0.3325 (Mac OS X 10.13.3)
    Expected [object Promise] to equal [object Promise].
        at UserContext.<anonymous> (webpack:///tests/language/language.service.spec.ts:22:0 <- config/spec-bundle.js:114651:38)
        at TestBed.execute (webpack:///~/@angular/core/esm5/testing.js:1063:0 <- config/spec-bundle.js:22029:19)
        at UserContext.<anonymous> (webpack:///~/@angular/core/esm5/testing.js:1207:28 <- config/spec-bundle.js:22173:45)
        at ZoneDelegate.invoke (webpack:///~/zone.js/dist/zone.js:388:0 <- config/spec-bundle.js:91284:26)
        at ProxyZoneSpec.onInvoke (webpack:///~/zone.js/dist/proxy.js:128:0 <- config/spec-bundle.js:90780:39)
        at ZoneDelegate.invoke (webpack:///~/zone.js/dist/zone.js:387:0 <- config/spec-bundle.js:91283:32)
        at Zone.run (webpack:///~/zone.js/dist/zone.js:138:0 <- config/spec-bundle.js:91034:43)
        at runInTestZone (webpack:///~/zone.js/dist/jasmine-patch.js:139:0 <- config/spec-bundle.js:90353:34)
        at UserContext.<anonymous> (webpack:///~/zone.js/dist/jasmine-patch.js:154:0 <- config/spec-bundle.js:90368:20)
        at ZoneQueueRunner.jasmine.QueueRunner.ZoneQueueRunner.execute (webpack:///~/zone.js/dist/jasmine-patch.js:244:0 <- config/spec-bundle.js:90458:42)
        at ZoneQueueRunner.jasmine.QueueRunner.ZoneQueueRunner.execute (webpack:///~/zone.js/dist/jasmine-patch.js:244:0 <- config/spec-bundle.js:90458:42)
        at ZoneDelegate.invokeTask (webpack:///~/zone.js/dist/zone.js:421:0 <- config/spec-bundle.js:91317:31)
        at Zone.runTask (webpack:///~/zone.js/dist/zone.js:188:0 <- config/spec-bundle.js:91084:47)
        at drainMicroTaskQueue (webpack:///~/zone.js/dist/zone.js:595:0 <- config/spec-bundle.js:91491:35)

    ✖ should retain changed language even after force refresh
      Chrome 65.0.3325 (Mac OS X 10.13.3)
    Expected [object Promise] to equal [object Promise].
        at UserContext.<anonymous> (webpack:///tests/language/language.service.spec.ts:27:0 <- config/spec-bundle.js:114656:38)
        at TestBed.execute (webpack:///~/@angular/core/esm5/testing.js:1063:0 <- config/spec-bundle.js:22029:19)
        at UserContext.<anonymous> (webpack:///~/@angular/core/esm5/testing.js:1207:28 <- config/spec-bundle.js:22173:45)
        at ZoneDelegate.invoke (webpack:///~/zone.js/dist/zone.js:388:0 <- config/spec-bundle.js:91284:26)
        at ProxyZoneSpec.onInvoke (webpack:///~/zone.js/dist/proxy.js:128:0 <- config/spec-bundle.js:90780:39)
        at ZoneDelegate.invoke (webpack:///~/zone.js/dist/zone.js:387:0 <- config/spec-bundle.js:91283:32)
        at Zone.run (webpack:///~/zone.js/dist/zone.js:138:0 <- config/spec-bundle.js:91034:43)
        at runInTestZone (webpack:///~/zone.js/dist/jasmine-patch.js:139:0 <- config/spec-bundle.js:90353:34)
        at UserContext.<anonymous> (webpack:///~/zone.js/dist/jasmine-patch.js:154:0 <- config/spec-bundle.js:90368:20)
        at ZoneQueueRunner.jasmine.QueueRunner.ZoneQueueRunner.execute (webpack:///~/zone.js/dist/jasmine-patch.js:244:0 <- config/spec-bundle.js:90458:42)
        at ZoneDelegate.invokeTask (webpack:///~/zone.js/dist/zone.js:421:0 <- config/spec-bundle.js:91317:31)
        at Zone.runTask (webpack:///~/zone.js/dist/zone.js:188:0 <- config/spec-bundle.js:91084:47)
        at drainMicroTaskQueue (webpack:///~/zone.js/dist/zone.js:595:0 <- config/spec-bundle.js:91491:35)


```

**Comment by deepu105** [comment]
closing the issue as we have the PR to track in the lib

**Comment by azizkhani** [comment]
I just create resolver in ng-jhipster but generator dose not change yet .why did you closed this issue ?

**Comment by deepu105** [comment]
@azizkhani its ok, since you are working on it anyway and i'm sure you will do a PR here as well :)

**Comment by azizkhani** [comment]
@deepu105 I changed generator but can not test ,
I think  package.json of  ng-jhipster that i change that, have problem and not correct .
can you see that ?
