### ISSUE TITLE
TestCase error when generating  microservice project with oauth2 authentication type

### ISSUE THREAD

**Issue by tianlinzx** [jhipster/generator-jhipster#7487]
##### **Overview of the issue**
TestCase error when generating  microservice project with oauth2 authentication type

##### **Motivation for or Use Case**

When running jhpack on new generated project,can't pass the test.
##### **Related issues**

TestCase error when using ODIC.See below:
[ERROR] Failures:
[ERROR]   AccountResourceIntTest.testGetExistingAccount:116 Status expected:<200> but was:<500>
[INFO]
[ERROR] Tests run: 95, Failures: 1, Errors: 0, Skipped: 0
##### **JHipster Version(s)**

5.0.0@beta.0

##### **JHipster configuration**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.gzs.audit",
      "nativeLanguage": "zh-cn"
    },
    "jhipsterVersion": "5.0.0-beta.0",
    "baseName": "onlineshop",
    "reactive": false,
    "packageName": "com.gzs.audit",
    "packageFolder": "com/gzs/audit",
    "serverPort": "8081",
    "authenticationType": "oauth2",
    "cacheProvider": "hazelcast",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": "eureka",
    "buildTool": "maven",
    "enableSwaggerCodegen": true,
    "jwtSecretKey": "replaced-by-jhipster-info",
    "enableTranslation": true,
    "applicationType": "microservice",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "nativeLanguage": "zh-cn",
    "languages": [
      "zh-cn"
    ],
    "clientPackageManager": "yarn",
    "skipClient": true,
    "skipUserManagement": true
  }
}
</pre>
</details>
##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

[simple-online-shop.jh.zip](https://github.com/jhipster/generator-jhipster/files/1910456/simple-online-shop.jh.zip)

##### **Browsers and Operating System**

macos 10.13.4
 [-] Checking this box is mandatory (this is just to show you read everything)

**Comment by pascalgrimaud** [comment]
I confirm the issue.
Here the full log: https://travis-ci.org/hipster-labs/jhipster-travis-build/jobs/366427357

**Comment by TonyLuo** [comment]
@tianlinzx +1

**Comment by mraible** [comment]
This test errors in a monolith too, but it doesn't register as a failure:

```
2018-04-15 11:23:42.224  INFO 18463 --- [           main] c.o.d.s.web.rest.AccountResourceIntTest  : Started AccountResourceIntTest in 17.434 seconds (JVM running for 19.878)
2018-04-15 11:23:42.660 ERROR 18463 --- [           main] o.z.p.spring.web.advice.AdviceTrait      : Internal Server Error

com.okta.developer.store.web.rest.errors.InternalServerErrorException: User could not be found
	at com.okta.developer.store.web.rest.AccountResource.getAccount(AccountResource.java:67)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:209)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:136)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:102)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:877)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:783)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:991)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:925)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:974)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:866)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:851)
	at org.springframework.test.web.servlet.TestDispatcherServlet.service(TestDispatcherServlet.java:68)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.springframework.mock.web.MockFilterChain$ServletFilterProxy.doFilter(MockFilterChain.java:166)
	at org.springframework.mock.web.MockFilterChain.doFilter(MockFilterChain.java:133)
	at org.springframework.test.web.servlet.MockMvc.perform(MockMvc.java:165)
	at com.okta.developer.store.web.rest.AccountResourceIntTest.testGetUnknownAccount(AccountResourceIntTest.java:129)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.springframework.test.context.junit4.statements.RunBeforeTestExecutionCallbacks.evaluate(RunBeforeTestExecutionCallbacks.java:73)
	at org.springframework.test.context.junit4.statements.RunAfterTestExecutionCallbacks.evaluate(RunAfterTestExecutionCallbacks.java:83)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.springframework.test.context.junit4.statements.RunBeforeTestMethodCallbacks.evaluate(RunBeforeTestMethodCallbacks.java:75)
	at org.springframework.test.context.junit4.statements.RunAfterTestMethodCallbacks.evaluate(RunAfterTestMethodCallbacks.java:86)
	at org.springframework.test.context.junit4.statements.SpringRepeat.evaluate(SpringRepeat.java:84)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:251)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:97)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:70)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:190)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:365)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:273)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:159)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:379)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:340)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:125)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:413)

[INFO] Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 21.351 s - in com.okta.developer.store.web.rest.AccountResourceIntTest
2018-04-15 11:23:45.295  WARN 18463 --- [       Thread-7] o.s.b.f.support.DisposableBeanAdapter    : Invocation of destroy method failed on bean with name 'inMemoryDatabaseShutdownExecutor': org.h2.jdbc.JdbcSQLException: Database is already closed (to disable automatic closing at VM shutdown, add ";DB_CLOSE_ON_EXIT=FALSE" to the db URL) [90121-197]
[INFO]
[INFO] Results:
[INFO]
[INFO] Tests run: 4, Failures: 0, Errors: 0, Skipped: 0
```

The problem seems to be that `Principal` isn't populated by the test. It used to be with Spring Security 4.x, so it seems something might've changed.

**Comment by mraible** [comment]
@jgrandja Any idea why the following test works fine when using `@EnableOAuth2Sso`, but not with `@EnableResourceServer`? For context, we have this test in both a monolith environment (that uses `EnableOAuth2Sso`) and a microservices environment (that uses `EnableResourceServer`). 

You can see the configuration classes for each in the JHipster project on GitHub:

* monolith: [SecurityConfiguration.java](https://github.com/jhipster/generator-jhipster/blob/master/generators/server/templates/src/main/java/package/config/SecurityConfiguration.java.ejs)
* microservice: [MicroserviceSecurityConfiguration.java](https://github.com/jhipster/generator-jhipster/blob/master/generators/server/templates/src/main/java/package/config/MicroserviceSecurityConfiguration.java.ejs)

```java
@Test
@Transactional
public void testGetExistingAccount() throws Exception {
    Set<Authority> authorities = new HashSet<>();
    Authority authority = new Authority();
    authority.setName(AuthoritiesConstants.ADMIN);
    authorities.add(authority);

    User user = new User();
    user.setId(RandomStringUtils.randomAlphanumeric(50));
    user.setLogin("test");
    user.setFirstName("john");
    user.setLastName("doe");
    user.setEmail("john.doe@jhipster.com");
    user.setImageUrl("http://placehold.it/50x50");
    user.setLangKey("en");
    user.setAuthorities(authorities);
    userRepository.save(user);

    // create security-aware mockMvc
    restUserMockMvc = MockMvcBuilders
        .webAppContextSetup(context)
        .apply(springSecurity())
        .build();

    restUserMockMvc.perform(get("/api/account")
        .with(user(user.getLogin()).roles("ADMIN"))
        .accept(MediaType.APPLICATION_JSON))
        .andExpect(status().isOk())
        .andExpect(content().contentType(MediaType.APPLICATION_JSON_UTF8_VALUE))
        .andExpect(jsonPath("$.login").value("test"))
        .andExpect(jsonPath("$.firstName").value("john"))
        .andExpect(jsonPath("$.lastName").value("doe"))
        .andExpect(jsonPath("$.email").value("john.doe@jhipster.com"))
        .andExpect(jsonPath("$.imageUrl").value("http://placehold.it/50x50"))
        .andExpect(jsonPath("$.langKey").value("en"))
        .andExpect(jsonPath("$.authorities").value(AuthoritiesConstants.ADMIN));
}
```

The method this test hits is as follows:

```java
/**
 * GET  /account : get the current user.
 *
 * @param principal the current user; resolves to null if not authenticated
 * @return the current user
 * @throws InternalServerErrorException 500 (Internal Server Error) if the user couldn't be returned
 */
@GetMapping("/account")
@Timed
@SuppressWarnings("unchecked")
public UserDTO getAccount(Principal principal) {
    if (principal != null) {
        if (principal instanceof OAuth2Authentication) {
            return userService.getUserFromAuthentication((OAuth2Authentication) principal);
        } else {
            // Allow Spring Security Test to be used to mock users in the database
            return userService.getUserWithAuthorities()
                .map(UserDTO::new)
                .orElseThrow(() -> new InternalServerErrorException("User could not be found"));
        }
    } else {
        throw new InternalServerErrorException("User could not be found");
    }
}
```

In a microservices environment, the `Principal` is null. Thanks in advance for any advice!

**Comment by mraible** [comment]
I'm not sure `AccountResource` and `AccountResourceIntTest` should exist when `applicationType === 'microservice'` because `account.service.ts` only exists on the gateway. I'll make a PR to remove it.

**Comment by jgrandja** [comment]
@mraible If you could put together a minimal sample the reproduces the issue that would be more efficient on my end. I will say that `@EnableOAuth2Sso` can be tricky at times as it applies a number of conditional checks on properties rooted at `security.oauth2.resource.*`. 

Are you able to use `@EnableResourceServer` exclusively?

**Comment by mraible** [comment]
@jgrandja It's probably something in JHipster's configuration that causes this, so I'm not sure a minimal sample would help. I think these steps are pretty simple though! ;)

```
git clone https://github.com/mraible/jhipster5-ms-user.git
cd jhipster5-ms-user/blog
./mvnw test -Dtest=AccountResourceIntTest
```

The test will fail:

```
[ERROR] Failures:
[ERROR]   AccountResourceIntTest.testGetExistingAccount:127 Status expected:<200> but was:<500>
```

Change from `@EnableResourceServer` to `@EnableOAuth2Sso` in `blog/src/main/java/com/okta/developer/blog/config/MicroserviceSecurityConfiguration.java` and it passes.

**Comment by jgrandja** [comment]
@mraible The reason `@EnableResourceServer` results in a `null` `Principal` in `getAccount(Principal principal)` is because of the configured `RequestMatcher` in `MicroserviceSecurityConfiguration`:

```
            .requestMatcher(authorizationHeaderRequestMatcher())
               .authorizeRequests()
                 .antMatchers("/api/profile-info").permitAll()
                .antMatchers("/api/**").authenticated()
```

The `RequestHeaderRequestMatcher("Authorization")` is configured but the request in the test does not set the `Authorization` which results in no matching `FilterChain`. So the request passes through without going through any of the Spring Security filters and therefore the `Authentication` doesn't get resolved.

However, even if you comment out `.requestMatcher(authorizationHeaderRequestMatcher())` which will match on a `FilterChain` (`AnyRequestMatcher`) a 401 error will occur. So other things will need to be changed in that test to make it pass.

**Comment by mraible** [comment]
@jgrandja I suspected that might be the case. There's nothing in `spring-security-test` that allows you to auto-send a `Bearer` token in an `Authorization` header is there? I was hoping `@WithMockUser` or `.with(user(user.getLogin()).roles("ADMIN"))` could do that somehow.

**Comment by jgrandja** [comment]
> There's nothing in spring-security-test that allows you to auto-send a Bearer token in an Authorization header is there?

No there isn't. However, we plan on adding oauth test support in Spring Security 5.x
