### ISSUE TITLE
When adding JHipster Entity Audit Generator v3.1.0 to a JHipster application v 4.14.3 turning on Hibernate Level 2 cache throws error on server startup.

### ISSUE THREAD

**Issue by ssavageVT** [jhipster/generator-jhipster#7515]
##### **Overview of the issue**

When adding JHipster Entity Audit Generator v3.1.0 to a JHipster application v 4.14.3 turning on Hibernate Level 2 cache throws error on server startup.

##### **Motivation for or Use Case**

Client needs to audit all entities with an application using the most current version of JHipster

##### **Reproduce the error**

-Generate a JHipster app, Hibernate Level 2 cache enabled

Welcome to the JHipster Generator v4.14.3
 _______________________________________________________________________________________________________________

  If you find JHipster useful consider supporting our collective https://opencollective.com/generator-jhipster
  Documentation for creating an application: http://www.jhipster.tech/creating-an-app/
 _______________________________________________________________________________________________________________

Application files will be generated in folder: /Users/ssavage/webdev/bugfix
? Which *type* of application would you like to create? Monolithic application (recommended for simple projects)
? What is the base name of your application? bugfix
? What is your default Java package name? com.ipponusa
? Do you want to use the JHipster Registry to configure, monitor and scale your application? No
? Which *type* of authentication would you like to use? JWT authentication (stateless, with a token)
? Which *type* of database would you like to use? SQL (H2, MySQL, MariaDB, PostgreSQL, Oracle, MSSQL)
? Which *production* database would you like to use? MySQL
? Which *development* database would you like to use? H2 with disk-based persistence
? Do you want to use the Spring cache abstraction? Yes, with the Ehcache implementation (local cache, for a single node)
? Do you want to use Hibernate 2nd level cache? Yes
? Would you like to use Maven or Gradle for building the backend? Maven
? Which other technologies would you like to use? 
? Which *Framework* would you like to use for the client? Angular 5
? Would you like to enable *SASS* support using the LibSass stylesheet preprocessor? No
? Would you like to enable internationalization support? No
? Besides JUnit and Karma, which testing frameworks would you like to use? 
? Would you like to install other generators from the JHipster Marketplace? No

(probably optional)
-Import a sample JDL file, overwrite all files
-Use default example here: https://start.jhipster.tech/jdl-studio/

$ jhipster import-jdl jhipster-jdl.jh
Using JHipster version installed locally in current project's node_modules
Executing jhipster:import-jdl jhipster-jdl.jh

-Install generator-hipster-entity-audit

npm install -g generator-jhipster-entity-audit

-Run Entity Audit Generator and overwrite all

$ yo jhipster-entity-audit
Welcome to the JHipster Entity Audit Generator! v3.1.0

? Choose which audit framework you would like to use. Custom JHipster auditing (works with SQL)
? Do you want to enable audit for all existing entities? Yes, update all
? Do you want to add an audit log page for entities? Yes

I'm Updating selected entities Country,Department,Employee,Job,JobHistory,Location,Region,Task

Make sure these classes does not extend any other class to avoid any errors during compilation.

-Run ./mvnw and observe the stack trace:

2018-04-20 14:02:53.184  WARN 40171 --- [  restartedMain] ationConfigEmbeddedWebApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'entityManagerFactory' defined in class path resource [org/springframework/boot/autoconfigure/orm/jpa/HibernateJpaAutoConfiguration.class]: Invocation of init method failed; nested exception is javax.persistence.PersistenceException: [PersistenceUnit: default] Unable to build Hibernate SessionFactory; nested exception is java.lang.IllegalStateException: All Hibernate caches should be created upfront. Please update CacheConfiguration.java to add com.ipponusa.domain.EntityAuditEvent
2018-04-20 14:02:53.217 DEBUG 40171 --- [  restartedMain] c.ehcache.core.Ehcache-usersByEmail      : Close successful.
2018-04-20 14:02:53.229 DEBUG 40171 --- [  restartedMain] c.e.c.E.i.domain.Department.employees    : Close successful.
2018-04-20 14:02:53.230 DEBUG 40171 --- [  restartedMain] c.e.c.Ehcache-com.ipponusa.domain.User   : Close successful.
2018-04-20 14:02:53.231 DEBUG 40171 --- [  restartedMain] c.e.c.Ehcache-com.ipponusa.domain.Task   : Close successful.
2018-04-20 14:02:53.232 DEBUG 40171 --- [  restartedMain] c.e.c.E.ipponusa.domain.Authority        : Close successful.
2018-04-20 14:02:53.233 DEBUG 40171 --- [  restartedMain] c.e.c.E.ipponusa.domain.Employee.jobs    : Close successful.
2018-04-20 14:02:53.234 DEBUG 40171 --- [  restartedMain] c.e.c.E.ipponusa.domain.Task.jobs        : Close successful.
2018-04-20 14:02:53.235 DEBUG 40171 --- [  restartedMain] c.e.c.E.ipponusa.domain.Employee         : Close successful.
2018-04-20 14:02:53.236 DEBUG 40171 --- [  restartedMain] c.e.c.Ehcache-com.ipponusa.domain.Job    : Close successful.
2018-04-20 14:02:53.236 DEBUG 40171 --- [  restartedMain] c.e.c.E.ipponusa.domain.JobHistory       : Close successful.
2018-04-20 14:02:53.237 DEBUG 40171 --- [  restartedMain] c.e.c.E.ipponusa.domain.Department       : Close successful.
2018-04-20 14:02:53.238 DEBUG 40171 --- [  restartedMain] c.e.c.E.ipponusa.domain.Location         : Close successful.
2018-04-20 14:02:53.239 DEBUG 40171 --- [  restartedMain] c.ehcache.core.Ehcache-usersByLogin      : Close successful.
2018-04-20 14:02:53.240 DEBUG 40171 --- [  restartedMain] c.e.c.E.ipponusa.domain.Job.tasks        : Close successful.
2018-04-20 14:02:53.241 DEBUG 40171 --- [  restartedMain] c.e.c.E.i.domain.User.authorities        : Close successful.
2018-04-20 14:02:53.241 DEBUG 40171 --- [  restartedMain] c.e.c.E.ipponusa.domain.Region           : Close successful.
2018-04-20 14:02:53.242 DEBUG 40171 --- [  restartedMain] c.e.c.E.ipponusa.domain.Country          : Close successful.
2018-04-20 14:02:53.359 ERROR 40171 --- [  restartedMain] o.s.boot.SpringApplication               : Application startup failed

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'entityManagerFactory' defined in class path resource [org/springframework/boot/autoconfigure/orm/jpa/HibernateJpaAutoConfiguration.class]: Invocation of init method failed; nested exception is javax.persistence.PersistenceException: [PersistenceUnit: default] Unable to build Hibernate SessionFactory; nested exception is java.lang.IllegalStateException: All Hibernate caches should be created upfront. Please update CacheConfiguration.java to add com.ipponusa.domain.EntityAuditEvent
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1630)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:555)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:483)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:312)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:308)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
	at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1080)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:857)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:543)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:693)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:360)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:303)
	at com.ipponusa.BugfixApp.main(BugfixApp.java:66)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.devtools.restart.RestartLauncher.run(RestartLauncher.java:49)
Caused by: javax.persistence.PersistenceException: [PersistenceUnit: default] Unable to build Hibernate SessionFactory; nested exception is java.lang.IllegalStateException: All Hibernate caches should be created upfront. Please update CacheConfiguration.java to add com.ipponusa.domain.EntityAuditEvent
	at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.buildNativeEntityManagerFactory(AbstractEntityManagerFactoryBean.java:396)
	at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.afterPropertiesSet(AbstractEntityManagerFactoryBean.java:371)
	at org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean.afterPropertiesSet(LocalContainerEntityManagerFactoryBean.java:336)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1688)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1626)
	... 19 common frames omitted
Caused by: java.lang.IllegalStateException: All Hibernate caches should be created upfront. Please update CacheConfiguration.java to add com.ipponusa.domain.EntityAuditEvent
	at io.github.jhipster.config.jcache.NoDefaultJCacheRegionFactory.createCache(NoDefaultJCacheRegionFactory.java:41)
	at org.hibernate.cache.jcache.JCacheRegionFactory.getOrCreateCache(JCacheRegionFactory.java:190)
	at org.hibernate.cache.jcache.JCacheRegionFactory.buildEntityRegion(JCacheRegionFactory.java:113)
	at org.hibernate.cache.spi.RegionFactory.buildEntityRegion(RegionFactory.java:132)
	at org.hibernate.internal.CacheImpl.determineEntityRegionAccessStrategy(CacheImpl.java:439)
	at org.hibernate.metamodel.internal.MetamodelImpl.initialize(MetamodelImpl.java:120)
	at org.hibernate.internal.SessionFactoryImpl.<init>(SessionFactoryImpl.java:301)
	at org.hibernate.boot.internal.SessionFactoryBuilderImpl.build(SessionFactoryBuilderImpl.java:452)
	at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.build(EntityManagerFactoryBuilderImpl.java:889)
	at org.springframework.orm.jpa.vendor.SpringHibernateJpaPersistenceProvider.createContainerEntityManagerFactory(SpringHibernateJpaPersistenceProvider.java:60)
	at org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean.createNativeEntityManagerFactory(LocalContainerEntityManagerFactoryBean.java:360)
	at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.buildNativeEntityManagerFactory(AbstractEntityManagerFactoryBean.java:384)
	... 23 common frames omitted

##### **Suggest a Fix**

-update com.xxx.config.CacheConfiguration and add the following lines:
	
            cm.createCache(com.xxx.domain.EntityAuditEvent.class.getName(), jcacheConfiguration);

On this method:
public JCacheManagerCustomizer cacheManagerCustomizer() {
        return cm -> {
                    // jhipster-needle-ehcache-add-entry
        };
    }

##### **JHipster Version(s)**

JHipster Generator v4.14.3

##### **JHipster configuration**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.ipponusa"
    },
    "jhipsterVersion": "4.14.3",
    "baseName": "bugfix",
    "packageName": "com.ipponusa",
    "packageFolder": "com/ipponusa",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "replaced-by-jhipster-info",
    "clientFramework": "angularX",
    "useSass": false,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": false
  },
  "generator-jhipster-entity-audit": {
    "auditFramework": "custom"
  }
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity Region (region) {
  regionName String
}
entity Country (country) {
  countryName String
}
/**
 * not an ignored comment
 */
entity Location (location) {
  streetAddress String,
  postalCode String,
  city String,
  stateProvince String
}
entity Department (department) {
  departmentName String required
}
/**
 * Task entity.
 * @author The JHipster team.
 */
entity Task (task) {
  title String,
  description String
}
/**
 * The Employee entity.
 */
entity Employee (employee) {
  /**
   * The firstname attribute.
   */
  firstName String,
  lastName String,
  email String,
  phoneNumber String,
  hireDate Instant,
  salary Long,
  commissionPct Long
}
entity Job (job) {
  jobTitle String,
  minSalary Long,
  maxSalary Long
}
entity JobHistory (job_history) {
  startDate Instant,
  endDate Instant,
  language Language
}

enum Language {
  FRENCH,
  ENGLISH,
  SPANISH
}

relationship OneToOne {
  Country{region} to Region,
  Location{country} to Country,
  Department{location} to Location,
  JobHistory{job} to Job,
  JobHistory{department} to Department,
  JobHistory{employee} to Employee
}
relationship OneToMany {
  /**
   * A relationship
   */
  Department{employee} to Employee{department},
  Employee{job} to Job{employee}
}
relationship ManyToOne {
  Employee{manager} to Employee
}
relationship ManyToMany {
  Job{task(title)} to Task{job}
}

dto Region, Country, Location, Department, Task, Employee, Job, JobHistory with mapstruct
service Region, Country, Location, Department, Task, JobHistory with serviceImpl
angularSuffix Region, Country, Location, Department, Task, Employee, Job, JobHistory with mySuffix
paginate Employee, JobHistory with infinite-scroll
paginate Job with pagination

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_101"
Java(TM) SE Runtime Environment (build 1.8.0_101-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.101-b13, mixed mode)

git version 2.10.0

node: v7.10.0

npm: 4.2.0

bower: 1.8.0

gulp:
[14:04:39] CLI version 1.2.2

yeoman: 2.0.2

yarn: 0.24.6

Docker version 1.12.0, build 8eab29e

docker-compose version 1.8.0, build f3628c7

##### **Browsers and Operating System**

- [ X] Checking this box is mandatory (this is just to show you read everything)

**Comment by pascalgrimaud** [comment]
Your issue is related to another project and not about generator-jhipster that's why I'm closing this. 

Have a look at https://github.com/hipster-labs/generator-jhipster-entity-audit/issues

**Comment by ssavageVT** [comment]
Sorry about that!  Will submit it over there.  Thanks!
