### ISSUE TITLE
Error during yarn install when there is yarn link

### ISSUE THREAD

**Issue by saturnism** [jhipster/generator-jhipster#7693]
##### **Overview of the issue**
`yarn install` failed on gateway.

##### **Motivation for or Use Case**
Unable to package gateway into a Docker image.

##### **Reproduce the error**

1. Created 2 microservices, 1 entity in each microservice.
1. Created 1 Gateway
1. Imported both entites into the Gateway
1. In Gateway, run `./mvnw`, this starts fine
1. In Gateway, run `/mvnw verify -Pprod dockerfile:build`

```
[INFO] [4/5] Linking dependencies...
[ERROR] warning " > @fortawesome/angular-fontawesome@0.1.0-9" has incorrect peer dependency "@angular/common@^5.0.0".
[ERROR] warning " > @fortawesome/angular-fontawesome@0.1.0-9" has incorrect peer dependency "@angular/compiler@^5.0.0".
[ERROR] warning " > @fortawesome/angular-fontawesome@0.1.0-9" has incorrect peer dependency "@angular/core@^5.0.0".
[ERROR] warning " > @fortawesome/angular-fontawesome@0.1.0-9" has incorrect peer dependency "@angular/platform-browser@^5.0.0".
[ERROR] warning " > @fortawesome/angular-fontawesome@0.1.0-9" has incorrect peer dependency "@angular/platform-browser-dynamic@^5.0.0".
[ERROR] warning " > @fortawesome/angular-fontawesome@0.1.0-9" has incorrect peer dependency "rxjs@^5.5.2".
[ERROR] warning " > bootstrap@4.0.0" has unmet peer dependency "popper.js@^1.12.9".
[ERROR] warning " > ng-jhipster@0.5.3" has incorrect peer dependency "@angular/core@^5.0.0".
[ERROR] warning " > ng-jhipster@0.5.3" has incorrect peer dependency "@angular/router@^5.0.0".
[ERROR] warning " > ngx-webstorage@2.0.1" has incorrect peer dependency "@angular/core@^5.0.0".
[ERROR] error An unexpected error occurred: "Reduce of empty array with no initial value".
[INFO] info If you think this is a bug, please open a bug report with the information provided in "/Users/rayt/tmp/gateway/yarn-error.log".
[INFO] info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
```

Log is here: https://gist.github.com/saturnism/fac55a76256db553e8157fbf14524933
```
...
Trace: 
  TypeError: Reduce of empty array with no initial value
      at Array.reduce (<anonymous>)
      at PackageLinker.<anonymous> (/Users/rayt/tmp/gateway/node/yarn/dist/lib/cli.js:50461:43)
      at Generator.next (<anonymous>)
      at step (/Users/rayt/tmp/gateway/node/yarn/dist/lib/cli.js:98:30)
      at /Users/rayt/tmp/gateway/node/yarn/dist/lib/cli.js:109:13
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)

...
```

##### **JHipster Version(s)**

latest greatest from `master` :)

##### **JHipster configuration**
```

Using JHipster version installed globally
Executing jhipster:info
Options: 
##### **JHipster Version(s)**

gateway@0.0.0 /Users/rayt/tmp/gateway
└── generator-jhipster@5.0.0-beta.1  -> /Users/rayt/Projects/git/generator-jhipster


##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**


<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.mycompany.myapp",
      "microservicePath": "../ms2"
    },
    "jhipsterVersion": "5.0.0-beta.1",
    "baseName": "gateway",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "hazelcast",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "replaced-by-jhipster-info",
    "clientFramework": "angularX",
    "useSass": false,
    "clientPackageManager": "yarn",
    "applicationType": "gateway",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": false
  }
}
</pre>
</details>


##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>


##### **Environment and Tools**

java version "1.8.0_162"
Java(TM) SE Runtime Environment (build 1.8.0_162-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.162-b12, mixed mode)

git version 2.17.0.441.gb46fe60e1d-goog

node: v10.2.1

npm: 5.6.0

yarn: 1.7.0

Docker version 18.04.0-ce, build 3d479c0

docker-compose version 1.21.0, build unknown

Congratulations, JHipster execution is complete!
```

`yo-rc.json`:
```
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.mycompany.myapp",
      "microservicePath": "../ms2"
    },
    "jhipsterVersion": "5.0.0-beta.1",
    "baseName": "gateway",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "hazelcast",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "...",
    "clientFramework": "angularX",
    "useSass": false,
    "clientPackageManager": "yarn",
    "applicationType": "gateway",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": false
  }
}
```

##### **Browsers and Operating System**

OSX

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by deepu105** [comment]
Seems like an issue from Yarn itself. Can you try with npm instead using the `--clientPackageManager` flag during generation

**Comment by pascalgrimaud** [comment]
Oh, I had the same issue this morning and thought it was a problem with my machine.

What I don't understand is our Travis builds...

**Comment by pascalgrimaud** [comment]
In fact, it failed for all configurations. It comes from `Yarn` as I don't have the issue, using `NPM`.
The related ticket is here: https://github.com/yarnpkg/yarn/issues/5876

**Comment by deepu105** [comment]
Is there anything we can do here?

Thanks & Regards,
Deepu

**Comment by pascalgrimaud** [comment]
At least, revert Yarn to 1.6.0 and waiting 1.7.1+
For developer, simply use yarn link after the generation.

I'll do it in few minutes

**Comment by PierreBesson** [comment]
So @saturnism you can fix it for you by changing the yarn version refered in your pom.xml to 1.6.0.
