### ISSUE TITLE
React: fix commented out flaky e2e tests in account module

### ISSUE THREAD

**Issue by deepu105** [jhipster/generator-jhipster#7694]
Some e2e tests in account module are commented out in the templates as they are very flaky and fails in Travis builds, they are difficult to reproduce locally and hence tricky to fix

https://github.com/jhipster/generator-jhipster/blob/master/generators/client/templates/react/src/test/javascript/e2e/modules/account/account.spec.ts.ejs#L116

**Comment by pascalgrimaud** [comment]
FYI, I added Protractor tests for React yesterday.
Here the results: https://travis-ci.org/hipster-labs/jhipster-travis-build/builds/384889812

It seems to work well for all configurations, excepting: Cassandra and OAuth2

Cassandra: https://travis-ci.org/hipster-labs/jhipster-travis-build/jobs/384889818

```
  Administration
    ✓ should load metrics
    ✓ should load health
    ✓ should load configuration
    1) should load audits
    2) should load logs
    User management
      ✓ should load user management
  CassBankAccount e2e test
    ✓ should load CassBankAccounts
    ✓ should load create CassBankAccount page
    3) should create and save CassBankAccounts
```

OAuth2: https://travis-ci.org/hipster-labs/jhipster-travis-build/jobs/384889820 -> not sure it's a real issue, maybe a random failure

```
1) Administration
       "before all" hook: ret:
     NoSuchElementError: No element found using locator: By(css selector, #login-item)
      at elementArrayFinder.getWebElements.then (node_modules/protractor/lib/element.ts:851:17)
      at ManagedPromise.invokeCallback_ (node_modules/selenium-webdriver/lib/promise.js:1366:14)
      at TaskQueue.execute_ (node_modules/selenium-webdriver/lib/promise.js:2970:14)
      at TaskQueue.executeNext_ (node_modules/selenium-webdriver/lib/promise.js:2953:27)
      at asyncRun (node_modules/selenium-webdriver/lib/promise.js:2813:27)
      at /home/travis/app/node_modules/selenium-webdriver/lib/promise.js:676:7
      at <anonymous>
```

**Comment by mraible** [comment]
I wonder if moving Protractor tests to use async/await would help with this: https://github.com/angular/protractor/issues/4307#issuecomment-386112285

**Comment by deepu105** [comment]
@mraible this issue is for React and we already use async/await everywhere
