### ISSUE TITLE
AuthorizedFeignClient fail with 401 Unauthorized

### ISSUE THREAD

**Issue by Tarekajaj** [jhipster/generator-jhipster#7711]
##### **Overview of the issue**
started registry, uaa server and gateway then created 2 micro-services service1, service2.
service1 need to get some data from service2 so I created Service2Client in service 1 like the following:
```
@AuthorizedFeignClient(name = "service2")
public interface Service2Client {
	@RequestMapping(value = "/api/data", method = RequestMethod.GET)
	String getData();
}
```
then in my service I injected Service2Client

```
@Service
public class SomeService {
	private Service2Client service2Client;
	@Inject
	public SomeService(Service2Client service2Client) {
		this.Service2Client = service2Client;
	}
}
```
In service2 the RestController was added to handle /api/data

Whenever I invoke service2Client.getData() I get the following error:

```
org.springframework.security.oauth2.client.resource.OAuth2AccessDeniedException: Error requesting access token.
	at org.springframework.security.oauth2.client.token.OAuth2AccessTokenSupport.retrieveToken(OAuth2AccessTokenSupport.java:145)
	at org.springframework.security.oauth2.client.token.grant.client.ClientCredentialsAccessTokenProvider.obtainAccessToken(ClientCredentialsAccessTokenProvider.java:44)
	at org.springframework.security.oauth2.client.token.AccessTokenProviderChain.obtainNewAccessTokenInternal(AccessTokenProviderChain.java:148)
	at org.springframework.security.oauth2.client.token.AccessTokenProviderChain.obtainAccessToken(AccessTokenProviderChain.java:121)
	at org.springframework.cloud.security.oauth2.client.feign.OAuth2FeignRequestInterceptor.acquireAccessToken(OAuth2FeignRequestInterceptor.java:171)
	at org.springframework.cloud.security.oauth2.client.feign.OAuth2FeignRequestInterceptor.getToken(OAuth2FeignRequestInterceptor.java:127)
	at org.springframework.cloud.security.oauth2.client.feign.OAuth2FeignRequestInterceptor.extract(OAuth2FeignRequestInterceptor.java:112)
	at org.springframework.cloud.security.oauth2.client.feign.OAuth2FeignRequestInterceptor.apply(OAuth2FeignRequestInterceptor.java:100)
.....
Caused by: org.springframework.web.client.HttpClientErrorException: 401 Unauthorized
	at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:94)
	at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:79)
	at org.springframework.security.oauth2.client.token.OAuth2AccessTokenSupport$AccessTokenErrorHandler.handleError(OAuth2AccessTokenSupport.java:246)
	at org.springframework.web.client.ResponseErrorHandler.handleError(ResponseErrorHandler.java:63)
	at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:775)

```

When the error is throws this message is logged in the uaa server
`WARN 14553 --- [  XNIO-2 task-4] o.s.s.c.bcrypt.BCryptPasswordEncoder     : Encoded password does not look like BCrypt`

##### **Motivation for or Use Case**
Secure inter-services communication

##### **Reproduce the error**
Same as the steps described above

##### **Related issues**
Unknown

##### **Suggest a Fix**
Unknown

##### **JHipster Version(s)**
generator-jhipster@5.0.0-beta.1 

##### **JHipster configuration**
```
<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.example.app",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "5.0.0-beta.1",
    "baseName": "service1", //same for service2
    "packageName": "com.example.app",
    "packageFolder": "com/example/app",
    "serverPort": "8090",
    "authenticationType": "uaa",
    "uaaBaseName": "uaa",
    "cacheProvider": "hazelcast",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": "elasticsearch",
    "messageBroker": "kafka",
    "serviceDiscoveryType": "eureka",
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "replaced-by-jhipster-info",
    "enableTranslation": true,
    "applicationType": "microservice",
    "testFrameworks": [
      "gatling"
    ],
    "jhiPrefix": "jhi",
    "nativeLanguage": "en",
    "languages": [
      "en",
      "ar-ly"
    ],
    "clientPackageManager": "yarn",
    "skipClient": true,
    "skipUserManagement": true
  }
}
</pre>
</details>
##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**
<details>
<summary>JDL entity definitions</summary>
<pre>
</pre>
</details>
##### **Environment and Tools**
openjdk version "1.8.0_171"
OpenJDK Runtime Environment (build 1.8.0_171-8u171-b11-0ubuntu0.17.10.1-b11)
OpenJDK 64-Bit Server VM (build 25.171-b11, mixed mode)
git version 2.14.1
node: v8.11.1
npm: 6.0.1
yeoman: 2.0.2
yarn: 1.6.0
Docker version 18.05.0-ce, build f150324
docker-compose version 1.21.2, build a133471
```

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**
None

##### **Browsers and Operating System**
Ubuntu 17.10

**Comment by Tarekajaj** [comment]
updated the line 
`.secret(HipsterProperties.getSecurity().getClientAuthorization().getClientSecret())`
to 
`.secret(passwordEncoder.encode(jHipsterProperties.getSecurity().getClientAuthorization().getClientSecret()))`
in  `UaaConfiguration -> configure(ClientDetailsServiceConfigurer clients) ` in the uaa server
and the error is gone.
Is it valid what I did? could it break something else? or I just found a bug?

**Comment by Tarekajaj** [comment]
Unfortunately now I'm facing a **403 Access is denied**
Any idea what's the cause?

**Comment by ruddell** [comment]
The change you mentioned is already in the [generated code](https://github.com/jhipster/generator-jhipster/blob/master/generators/server/templates/src/main/java/package/config/UaaConfiguration.java.ejs#L149) for v5.  Usually, a 403 means the API routes are restricted.

**Comment by Tarekajaj** [comment]
@ruddell it was this [this line](https://github.com/jhipster/generator-jhipster/blob/da01afdeaa969117c0570ab23940b78e85c6d4dc/generators/server/templates/src/main/java/package/config/UaaConfiguration.java.ejs#L157)

Why are the /api outes restricted? isn't that what AuthorizedFeignClient should solve? if not what to do to allow the client to access those route?

I tried changing `.antMatchers("/api/**").authenticated()` to `.antMatchers("/api/**").permitAll()` and the route became accessible directly from any browser but still throw a 403 when accessed using AuthorizedFeignClient.

**Comment by Tarekajaj** [comment]
Found the root cause of the 403 error,
It seems feign is converting my GET request to POST for some reason.
