### ISSUE TITLE
Trying to run yarn e2e fails with React (on master)

### ISSUE THREAD

**Issue by mraible** [jhipster/generator-jhipster#7764]
```
> gallery@0.0.0 e2e /home/mraible/dev/okta-react-photo-gallery-example
> protractor src/test/javascript/protractor.conf.js

(node:8995) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
[11:17:01] W/configParser - pattern ./e2e/entities/**/*.spec.ts did not match any files.
[11:17:01] I/launcher - Running 1 instances of WebDriver
[11:17:01] I/direct - Using ChromeDriver directly...
[11:17:01] E/direct - Error code: 135
[11:17:01] E/direct - Error message: Could not find update-config.json. Run 'webdriver-manager update' to download binaries.
[11:17:01] E/direct - Error: Could not find update-config.json. Run 'webdriver-manager update' to download binaries.
```

Manually run `npx webdriver-manager update` fixes the issue.

**Comment by deepu105** [comment]
@mraible I dont see the issue. This should be triggered during `npm install` What config are you trying with also did you do `npm install` on the project? coz if you did `yarn install` instead of `npm install` then the binaries may have not been updated exactly where npm might look for

**Comment by mraible** [comment]
@deepu105 I changed the title to say "yarn" rather than "npm" since that's what I have installed on my system. I just tried again and it still happens after creating a project from scratch. Full output below:

```
➜  dev cd foo
➜  foo jhipster 
Using JHipster version installed globally
Running default command
Executing jhipster:app
Options: 


        ██╗ ██╗   ██╗ ████████╗ ███████╗   ██████╗ ████████╗ ████████╗ ███████╗
        ██║ ██║   ██║ ╚══██╔══╝ ██╔═══██╗ ██╔════╝ ╚══██╔══╝ ██╔═════╝ ██╔═══██╗
        ██║ ████████║    ██║    ███████╔╝ ╚█████╗     ██║    ██████╗   ███████╔╝
  ██╗   ██║ ██╔═══██║    ██║    ██╔════╝   ╚═══██╗    ██║    ██╔═══╝   ██╔══██║
  ╚██████╔╝ ██║   ██║ ████████╗ ██║       ██████╔╝    ██║    ████████╗ ██║  ╚██╗
   ╚═════╝  ╚═╝   ╚═╝ ╚═══════╝ ╚═╝       ╚═════╝     ╚═╝    ╚═══════╝ ╚═╝   ╚═╝

                            https://www.jhipster.tech

JDL!!! Welcome to the JHipster Generator v5.0.0-beta.1
 _______________________________________________________________________________________________________________

  If you find JHipster useful consider supporting our collective https://opencollective.com/generator-jhipster
  Documentation for creating an application: https://www.jhipster.tech/creating-an-app/
 _______________________________________________________________________________________________________________

Application files will be generated in folder: /home/mraible/dev/foo
? Which *type* of application would you like to create? Monolithic application (recommended for simp
le projects)
? What is the base name of your application? foo
? What is your default Java package name? com.okta.developer
? Do you want to use the JHipster Registry to configure, monitor and scale your application? No
? Which *type* of authentication would you like to use? OAuth 2.0 / OIDC Authentication (stateful, w
orks with Keycloak and Okta)
? Which *type* of database would you like to use? SQL (H2, MySQL, MariaDB, PostgreSQL, Oracle, MSSQL
)
? Which *production* database would you like to use? PostgreSQL
? Which *development* database would you like to use? H2 with disk-based persistence
? Do you want to use the Spring cache abstraction? Yes, with the Ehcache implementation (local cache
, for a single node)
? Do you want to use Hibernate 2nd level cache? Yes
? Would you like to use Maven or Gradle for building the backend? Maven
? Which other technologies would you like to use? 
? Which *Framework* would you like to use for the client? React
? Would you like to enable *SASS* support using the LibSass stylesheet preprocessor? Yes
? Would you like to enable internationalization support? Yes
? Please choose the native language of the application English
? Please choose additional languages to install French
? Besides JUnit and Karma, which testing frameworks would you like to use? Protractor
? Would you like to install other generators from the JHipster Marketplace? No

Installing languages: en, fr
   create package.json
   create src/main/resources/i18n/messages.properties
   create README.md
   create .gitignore
   create .gitattributes
   create .editorconfig
   create src/main/docker/Dockerfile
   create src/main/docker/entrypoint.sh
   create src/main/docker/.dockerignore
   create src/main/docker/app.yml
   create src/main/docker/sonar.yml
   create src/main/docker/postgresql.yml
   create src/main/docker/keycloak.yml
   create src/main/docker/realm-config/jhipster-realm.json
   create src/main/docker/realm-config/jhipster-users-0.json
   create mvnw
   create mvnw.cmd
   create .mvn/wrapper/maven-wrapper.jar
   create .mvn/wrapper/maven-wrapper.properties
   create pom.xml
   create src/main/resources/banner.txt
   create src/main/resources/.h2.server.properties
   create src/main/resources/templates/error.html
   create src/main/resources/logback-spring.xml
   create src/main/resources/config/application.yml
   create src/main/resources/config/application-dev.yml
   create src/main/resources/config/application-prod.yml
   create src/main/resources/config/liquibase/changelog/00000000000000_initial_schema.xml
   create src/main/resources/config/liquibase/master.xml
   create src/main/java/com/okta/developer/security/SpringSecurityAuditorAware.java
   create src/main/java/com/okta/developer/security/SecurityUtils.java
   create src/main/java/com/okta/developer/security/AuthoritiesConstants.java
   create src/main/java/com/okta/developer/security/package-info.java
   create src/main/java/com/okta/developer/config/SecurityConfiguration.java
   create src/main/java/com/okta/developer/config/OAuth2Configuration.java
   create src/main/java/com/okta/developer/security/OAuth2AuthenticationSuccessHandler.java
   create src/main/java/com/okta/developer/FooApp.java
   create src/main/java/com/okta/developer/ApplicationWebXml.java
   create src/main/java/com/okta/developer/aop/logging/LoggingAspect.java
   create src/main/java/com/okta/developer/config/DefaultProfileUtil.java
   create src/main/java/com/okta/developer/config/package-info.java
   create src/main/java/com/okta/developer/config/AsyncConfiguration.java
   create src/main/java/com/okta/developer/config/Constants.java
   create src/main/java/com/okta/developer/config/DateTimeFormatConfiguration.java
   create src/main/java/com/okta/developer/config/LoggingConfiguration.java
   create src/main/java/com/okta/developer/config/ApplicationProperties.java
   create src/main/java/com/okta/developer/config/JacksonConfiguration.java
   create src/main/java/com/okta/developer/config/LocaleConfiguration.java
   create src/main/java/com/okta/developer/config/LoggingAspectConfiguration.java
   create src/main/java/com/okta/developer/config/MetricsConfiguration.java
   create src/main/java/com/okta/developer/config/WebConfigurer.java
   create src/main/java/com/okta/developer/config/CacheConfiguration.java
   create src/main/java/com/okta/developer/config/CloudDatabaseConfiguration.java
   create src/main/java/com/okta/developer/config/DatabaseConfiguration.java
   create src/main/java/com/okta/developer/config/audit/package-info.java
   create src/main/java/com/okta/developer/config/audit/AuditEventConverter.java
   create src/main/java/com/okta/developer/domain/package-info.java
   create src/main/java/com/okta/developer/domain/AbstractAuditingEntity.java
   create src/main/java/com/okta/developer/domain/PersistentAuditEvent.java
   create src/main/java/com/okta/developer/repository/package-info.java
   create src/main/java/com/okta/developer/service/package-info.java
   create src/main/java/com/okta/developer/web/rest/errors/package-info.java
   create src/main/java/com/okta/developer/web/rest/errors/InternalServerErrorException.java
   create src/main/java/com/okta/developer/web/rest/errors/BadRequestAlertException.java
   create src/main/java/com/okta/developer/web/rest/errors/CustomParameterizedException.java
   create src/main/java/com/okta/developer/web/rest/errors/EmailAlreadyUsedException.java
   create src/main/java/com/okta/developer/web/rest/errors/EmailNotFoundException.java
   create src/main/java/com/okta/developer/web/rest/errors/ErrorConstants.java
   create src/main/java/com/okta/developer/web/rest/errors/ExceptionTranslator.java
   create src/main/java/com/okta/developer/web/rest/errors/FieldErrorVM.java
   create src/main/java/com/okta/developer/web/rest/errors/InvalidPasswordException.java
   create src/main/java/com/okta/developer/web/rest/errors/LoginAlreadyUsedException.java
   create src/main/java/com/okta/developer/web/rest/vm/package-info.java
   create src/main/java/com/okta/developer/web/rest/vm/LoggerVM.java
   create src/main/java/com/okta/developer/web/rest/util/HeaderUtil.java
   create src/main/java/com/okta/developer/web/rest/util/PaginationUtil.java
   create src/main/java/com/okta/developer/web/rest/package-info.java
   create src/main/java/com/okta/developer/web/rest/LogsResource.java
   create src/test/java/com/okta/developer/config/WebConfigurerTest.java
   create src/test/java/com/okta/developer/config/WebConfigurerTestController.java
   create src/test/java/com/okta/developer/web/rest/TestUtil.java
   create src/test/java/com/okta/developer/web/rest/LogsResourceIntTest.java
   create src/test/java/com/okta/developer/web/rest/errors/ExceptionTranslatorIntTest.java
   create src/test/java/com/okta/developer/web/rest/errors/ExceptionTranslatorTestController.java
   create src/test/java/com/okta/developer/web/rest/util/PaginationUtilUnitTest.java
   create src/test/resources/config/application.yml
   create src/test/resources/logback.xml
   create src/main/resources/config/liquibase/users.csv
   create src/main/resources/config/liquibase/authorities.csv
   create src/main/resources/config/liquibase/users_authorities.csv
   create src/main/java/com/okta/developer/domain/User.java
   create src/main/java/com/okta/developer/domain/Authority.java
   create src/main/java/com/okta/developer/service/UserService.java
   create src/main/java/com/okta/developer/service/dto/package-info.java
   create src/main/java/com/okta/developer/service/dto/UserDTO.java
   create src/main/java/com/okta/developer/service/mapper/package-info.java
   create src/main/java/com/okta/developer/service/mapper/UserMapper.java
   create src/main/java/com/okta/developer/repository/UserRepository.java
   create src/main/java/com/okta/developer/repository/AuthorityRepository.java
   create src/main/java/com/okta/developer/web/rest/UserResource.java
   create src/main/java/com/okta/developer/web/rest/vm/ManagedUserVM.java
   create src/main/java/com/okta/developer/web/rest/AccountResource.java
   create src/test/java/com/okta/developer/security/SecurityUtilsUnitTest.java
   create src/test/java/com/okta/developer/service/UserServiceIntTest.java
   create src/test/java/com/okta/developer/web/rest/UserResourceIntTest.java
   create src/test/java/com/okta/developer/web/rest/AccountResourceIntTest.java
   create src/main/java/com/okta/developer/repository/CustomAuditEventRepository.java
   create src/main/java/com/okta/developer/repository/PersistenceAuditEventRepository.java
   create src/main/java/com/okta/developer/service/AuditEventService.java
   create src/main/java/com/okta/developer/web/rest/AuditResource.java
   create src/test/java/com/okta/developer/repository/CustomAuditEventRepositoryIntTest.java
   create src/test/java/com/okta/developer/web/rest/AuditResourceIntTest.java
   create .prettierrc
   create .prettierignore
   create tslint.json
   create tsconfig.json
   create webpack/logo-jhipster.png
   create webpack/webpack.common.js
   create webpack/webpack.dev.js
   create webpack/webpack.prod.js
   create webpack/utils.js
   create postcss.config.js
   create src/main/webapp/static/images/hipster.png
   create src/main/webapp/static/images/hipster2x.png
   create src/main/webapp/static/images/logo-jhipster.png
   create src/main/webapp/static/images/logo-jhipster-react.svg
   create src/main/webapp/swagger-ui/index.html
   create src/main/webapp/swagger-ui/dist/images/throbber.gif
   create src/main/webapp/favicon.ico
   create src/main/webapp/robots.txt
   create src/main/webapp/404.html
   create src/main/webapp/index.html
   create src/main/webapp/manifest.webapp
   create src/main/webapp/app/app.tsx
   create src/main/webapp/app/index.tsx
   create src/main/webapp/app/routes.tsx
   create src/main/webapp/app/typings.d.ts
   create src/main/webapp/app/config/constants.ts
   create src/main/webapp/app/config/axios-interceptor.ts
   create src/main/webapp/app/config/devtools.tsx
   create src/main/webapp/app/config/error-middleware.ts
   create src/main/webapp/app/config/logger-middleware.ts
   create src/main/webapp/app/config/notification-middleware.ts
   create src/main/webapp/app/config/store.ts
   create src/main/webapp/app/config/icon-loader.ts
   create src/main/webapp/app/config/translation.ts
   create src/main/webapp/app/app.scss
   create src/main/webapp/app/_bootstrap-variables.scss
   create src/main/webapp/app/entities/index.tsx
   create src/main/webapp/app/modules/home/home.tsx
   create src/main/webapp/app/modules/login/logout.tsx
   create src/main/webapp/app/modules/home/home.scss
   create src/main/webapp/app/shared/reducers/index.ts
   create src/main/webapp/app/shared/reducers/action-type.util.ts
   create src/main/webapp/app/shared/reducers/authentication.ts
   create src/main/webapp/app/shared/reducers/application-profile.ts
   create src/main/webapp/app/shared/reducers/locale.ts
   create src/main/webapp/app/shared/reducers/user-management.ts
   create src/main/webapp/app/modules/administration/index.tsx
   create src/main/webapp/app/modules/administration/audits/audits.tsx
   create src/main/webapp/app/modules/administration/configuration/configuration.tsx
   create src/main/webapp/app/modules/administration/docs/docs.tsx
   create src/main/webapp/app/modules/administration/health/health.tsx
   create src/main/webapp/app/modules/administration/health/health-modal.tsx
   create src/main/webapp/app/modules/administration/logs/logs.tsx
   create src/test/javascript/jest.conf.js
   create src/main/webapp/app/modules/administration/metrics/metrics.tsx
   create src/main/webapp/app/modules/administration/metrics/metrics-modal.tsx
   create src/main/webapp/app/modules/administration/metrics/thread-item.tsx
   create src/main/webapp/app/modules/administration/administration.reducer.ts
   create src/main/webapp/app/shared/layout/footer/footer.tsx
   create src/main/webapp/app/shared/layout/header/header.tsx
   create src/main/webapp/app/shared/layout/header/header-components.tsx
   create src/main/webapp/app/shared/layout/header/menus/index.ts
   create src/main/webapp/app/shared/layout/header/menus/admin.tsx
   create src/main/webapp/app/shared/layout/header/menus/account.tsx
   create src/main/webapp/app/shared/layout/header/menus/entities.tsx
   create src/main/webapp/app/shared/layout/password/password-strength-bar.tsx
   create src/main/webapp/app/shared/util/date-utils.ts
   create src/main/webapp/app/shared/util/pagination.constants.ts
   create src/main/webapp/app/shared/util/url-utils.ts
   create src/main/webapp/app/shared/util/entity-utils.ts
   create src/test/javascript/protractor.conf.js
   create src/test/javascript/tsconfig.e2e.json
   create src/main/webapp/i18n/en/audits.json
   create src/main/webapp/i18n/en/configuration.json
   create src/main/webapp/i18n/en/error.json
   create src/main/webapp/i18n/en/gateway.json
   create src/main/webapp/i18n/en/login.json
   create src/main/webapp/i18n/en/home.json
   create src/main/webapp/i18n/en/metrics.json
   create src/main/webapp/i18n/en/logs.json
   create src/main/webapp/i18n/en/password.json
   create src/main/webapp/i18n/en/register.json
   create src/main/webapp/i18n/en/sessions.json
   create src/main/webapp/i18n/en/settings.json
   create src/main/webapp/i18n/en/user-management.json
   create src/main/webapp/i18n/en/activate.json
   create src/main/webapp/i18n/en/global.json
   create src/main/webapp/i18n/en/health.json
   create src/main/webapp/i18n/en/reset.json
   create src/main/resources/i18n/messages_en.properties
   create src/main/webapp/i18n/fr/audits.json
   create src/main/webapp/i18n/fr/configuration.json
   create src/main/webapp/i18n/fr/error.json
   create src/main/webapp/i18n/fr/gateway.json
   create src/main/webapp/i18n/fr/login.json
   create src/main/webapp/i18n/fr/home.json
   create src/main/webapp/i18n/fr/metrics.json
   create src/main/webapp/i18n/fr/logs.json
   create src/main/webapp/i18n/fr/password.json
   create src/main/webapp/i18n/fr/register.json
   create src/main/webapp/i18n/fr/sessions.json
   create src/main/webapp/i18n/fr/settings.json
   create src/main/webapp/i18n/fr/user-management.json
   create src/main/webapp/i18n/fr/activate.json
   create src/main/webapp/i18n/fr/global.json
   create src/main/webapp/i18n/fr/health.json
   create src/main/webapp/i18n/fr/reset.json
   create src/main/resources/i18n/messages_fr.properties
   create src/main/webapp/app/shared/auth/private-route.tsx
   create src/main/webapp/app/shared/model/user.model.ts
   create src/main/webapp/app/shared/layout/header/menus/locale.tsx
   create src/main/webapp/app/shared/layout/header/header.scss
   create src/main/webapp/app/shared/layout/footer/footer.scss
   create src/main/webapp/app/shared/layout/password/password-strength-bar.scss
   create src/test/javascript/spec/app/utils.ts
   create src/test/javascript/spec/app/config/notification-middleware.spec.ts
   create src/test/javascript/spec/app/shared/reducers/application-profile.spec.ts
   create src/test/javascript/spec/app/shared/reducers/authentication.spec.ts
   create src/test/javascript/spec/app/shared/util/entity-utils.spec.ts
   create src/test/javascript/spec/app/shared/auth/private-route.spec.tsx
   create src/test/javascript/spec/app/shared/layout/header/header.spec.tsx
   create src/test/javascript/spec/app/shared/layout/header/menus/account.spec.tsx
   create src/test/javascript/spec/app/modules/administration/administration.reducer.spec.ts
   create src/test/javascript/spec/app/shared/reducers/user-management.spec.ts
   create src/test/javascript/e2e/modules/account/account.spec.ts
   create src/test/javascript/e2e/modules/administration/administration.spec.ts
   create src/test/javascript/e2e/util/utils.ts
   create src/test/javascript/e2e/page-objects/base-component.ts
   create src/test/javascript/e2e/page-objects/navbar-page.ts
   create src/test/javascript/e2e/page-objects/signin-page.ts


I'm all done. Running yarn install for you to install the required dependencies. If this fails, try running the command yourself.


yarn install v1.6.0
info No lockfile found.
[1/5] Validating package.json...
[2/5] Resolving packages...
warning browser-sync > socket.io > engine.io > uws@9.14.0: stop using this version
warning enzyme > rst-selector-parser > nearley > nomnom@1.6.2: Package no longer supported. Contact support@npmjs.com for more info.
warning image-webpack-loader > imagemin-webp > cwebp-bin > bin-wrapper > download > gulp-decompress > gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
warning jest > jest-cli > istanbul-api > istanbul-lib-hook@1.2.1: 1.2.0 should have been a major version bump
warning redux-mock-store@1.5.1: breaking changes in minor version
warning webpack-cli > jscodeshift > nomnom@1.8.1: Package no longer supported. Contact support@npmjs.com for more info.
warning webpack-cli > webpack-addons > jscodeshift > nomnom@1.8.1: Package no longer supported. Contact support@npmjs.com for more info.
warning webpack-cli > jscodeshift > babel-preset-es2015@6.24.1: 🙌  Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update! 
warning webpack-cli > webpack-addons > jscodeshift > babel-preset-es2015@6.24.1: 🙌  Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update! 
[3/5] Fetching packages...
info fsevents@1.2.4: The platform "linux" is incompatible with this module.
info "fsevents@1.2.4" is an optional dependency and failed compatibility check. Excluding it from installation.
[4/5] Linking dependencies...
warning " > @fortawesome/react-fontawesome@0.0.18" has unmet peer dependency "prop-types@15.x".
warning " > bootstrap@4.0.0" has unmet peer dependency "jquery@1.9.1 - 3".
warning " > bootstrap@4.0.0" has unmet peer dependency "popper.js@^1.12.9".
[5/5] Building fresh packages...
[9/9] ⠄ node-sass: Downloading binary from https://github.com/sass/node-sass/releases/downl
[6/9] ⠄ pngquant-bin:   ✔ pngquant pre-build test passed successfully
[-/9] ⠄ waiting...
[-/9] ⠄ waiting...
error /home/mraible/dev/foo/node_modules/pngquant-bin: Command failed.
Exit code: 1
Command: node lib/install.js
Arguments: 
Directory: /home/mraible/dev/foo/node_modules/pngquant-bin
Output:
⚠ The `/home/mraible/dev/foo/node_modules/pngquant-bin/vendor/pngquant` binary doesn't seem to work correctly
  ⚠ pngquant pre-build test failed
  ℹ compiling from source
  ✔ pngquant pre-build test passed successfully
  ✖ Error: pngquant failed to build, make sure that libpng-dev is installed
    at Promise.all.then.arr (/home/mraible/dev/foo/node_modules/pngquant-bin/node_modules/bin-build/



yarn run v1.6.0
$ yarn run cleanup && yarn run webpack:build:main
$ rimraf target/www
$ yarn run webpack --config webpack/webpack.dev.js --progress --profile
$ node --max_old_space_size=4096 node_modules/webpack/bin/webpack.js --config webpack/webpack.dev.js --progress --profile
Starting type checking and linting service...
Using 1 worker with 2048MB memory limit
 10% building modules 1/1 modules 0 active(node:10826) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
10253ms building modules                                                                  
10ms finish module graph                            
3ms sealing                                
0ms basic dependencies optimization 
0ms dependencies optimization 
0ms advanced dependencies optimization 
14ms after dependencies optimization
1ms optimizing 
0ms basic module optimization 
0ms module optimization 
0ms advanced module optimization 
0ms after module optimization 
0ms basic chunk optimization                             
1ms chunk optimization 
25ms advanced chunk optimization                  
1ms after chunk optimization 
0ms module and chunk tree optimization 
0ms after module and chunk tree optimization 
0ms basic chunk modules optimization 
0ms chunk modules optimization 
0ms advanced chunk modules optimization 
0ms after chunk modules optimization 
0ms module reviving                 
0ms module order optimization 
0ms advanced module order optimization 
6ms before module ids                    
1ms module ids 
5ms module id optimization 
0ms chunk reviving                 
1ms chunk order optimization 
0ms before chunk ids                   
0ms chunk id optimization 
3ms after chunk id optimization 
2ms record modules                 
0ms record chunks                 
30ms hashing
1ms after hashing                            
0ms record hash 
0ms module assets processing 
61ms chunk assets processing
7ms additional chunk assets processing                            
28ms recording                           
0ms additional asset processing 
0ms chunk asset optimization 
240ms after chunk asset optimization                                                            
0ms asset optimization 
0ms after asset optimization 
0ms after seal 
162ms emitting                              
Hash: 52c12cbef984c4bc40de
Version: webpack 4.4.1
Time: 10871ms
Built at: 6/12/2018 12:26:21 PM
                                               Asset       Size  Chunks             Chunk Names
             swagger-ui/dist/lib/handlebars-4.0.5.js   69.8 KiB          [emitted]  
        content/4d7a941186721ef8150a081fa7cfa010.svg   36.5 KiB          [emitted]  
                              app/main.bundle.js.map   5.13 MiB    main  [emitted]  main
               static/images/logo-jhipster-react.svg   36.5 KiB          [emitted]  
                   swagger-ui/dist/swagger-ui.min.js    442 KiB          [emitted]  
                                         favicon.ico    5.3 KiB          [emitted]  
                                     manifest.webapp  731 bytes          [emitted]  
                                          robots.txt  168 bytes          [emitted]  
                       swagger-ui/dist/css/reset.css  773 bytes          [emitted]  
                       swagger-ui/dist/css/print.css   40.7 KiB          [emitted]  
                       swagger-ui/dist/css/style.css   3.41 KiB          [emitted]  
                      swagger-ui/dist/css/screen.css   42.6 KiB          [emitted]  
                  swagger-ui/dist/css/typography.css    0 bytes          [emitted]  
                 swagger-ui/dist/lib/backbone-min.js   18.9 KiB          [emitted]  
                     swagger-ui/dist/lib/es5-shim.js   22.2 KiB          [emitted]  
swagger-ui/dist/lib/highlight.9.1.0.pack_extended.js  310 bytes          [emitted]  
         swagger-ui/dist/lib/highlight.9.1.0.pack.js   10.7 KiB          [emitted]  
                                  app/main.bundle.js   5.19 MiB    main  [emitted]  main
            swagger-ui/dist/lib/jquery.ba-bbq.min.js   3.44 KiB          [emitted]  
           swagger-ui/dist/lib/jquery.slideto.min.js  365 bytes          [emitted]  
            swagger-ui/dist/lib/jquery.wiggle.min.js  536 bytes          [emitted]  
             swagger-ui/dist/lib/jquery-1.8.0.min.js   89.9 KiB          [emitted]  
                  swagger-ui/dist/lib/js-yaml.min.js   42.5 KiB          [emitted]  
               swagger-ui/dist/lib/jsoneditor.min.js    127 KiB          [emitted]  
                       swagger-ui/dist/lib/marked.js   15.4 KiB          [emitted]  
      swagger-ui/dist/lib/object-assign-pollyfill.js  349 bytes          [emitted]  
                   swagger-ui/dist/lib/lodash.min.js   50.7 KiB          [emitted]  
                swagger-ui/dist/lib/swagger-oauth.js   6.88 KiB          [emitted]  
            swagger-ui/dist/lib/sanitize-html.min.js    127 KiB          [emitted]  
                           static/images/hipster.png   9.28 KiB          [emitted]  
                         static/images/hipster2x.png   18.4 KiB          [emitted]  
                     static/images/logo-jhipster.png   4.35 KiB          [emitted]  
                 swagger-ui/dist/images/throbber.gif   9.04 KiB          [emitted]  
                               swagger-ui/index.html   7.49 KiB          [emitted]  
                                          index.html   1.82 KiB          [emitted]  
Entrypoint main = app/main.bundle.js app/main.bundle.js.map
[./src/main/webapp/app/app.tsx] 3.94 KiB {main} [built]
       [0] 3ms -> [./src/main/webapp/app/index.tsx] 1619ms -> factory:74ms building:3027ms dependencies:211ms = 4934ms
[./src/main/webapp/app/config/axios-interceptor.ts] 2.1 KiB {main} [built]
       [0] 3ms -> [./src/main/webapp/app/index.tsx] 1619ms -> factory:74ms building:3027ms dependencies:211ms = 4934ms
[./src/main/webapp/app/config/devtools.tsx] 1.58 KiB {main} [built]
       [0] 3ms -> [./src/main/webapp/app/index.tsx] 1619ms -> factory:74ms building:3027ms dependencies:211ms = 4934ms
[./src/main/webapp/app/config/error-middleware.ts] 2.35 KiB {main} [built]
       [0] 3ms -> [./src/main/webapp/app/index.tsx] 1619ms -> [./src/main/webapp/app/config/store.ts] 3101ms -> factory:187ms building:1950ms dependencies:13ms = 6873ms
[./src/main/webapp/app/config/icon-loader.ts] 2.09 KiB {main} [built]
       [0] 3ms -> [./src/main/webapp/app/index.tsx] 1619ms -> factory:74ms building:3027ms dependencies:211ms = 4934ms
[./src/main/webapp/app/config/notification-middleware.ts] 6.04 KiB {main} [built]
       [0] 3ms -> [./src/main/webapp/app/index.tsx] 1619ms -> [./src/main/webapp/app/config/store.ts] 3101ms -> factory:187ms building:1950ms dependencies:13ms = 6873ms
   [0] multi react-hot-loader/patch ./src/main/webapp/app/index 40 bytes {main} [built]
       factory:1ms building:2ms = 3ms
[./src/main/webapp/app/config/store.ts] 2.29 KiB {main} [built]
       [0] 3ms -> [./src/main/webapp/app/index.tsx] 1619ms -> factory:74ms building:3027ms dependencies:211ms = 4934ms
[./src/main/webapp/app/config/translation.ts] 2.51 KiB {main} [built]
       [0] 3ms -> [./src/main/webapp/app/index.tsx] 1619ms -> factory:74ms building:3027ms dependencies:211ms = 4934ms
[./src/main/webapp/app/index.tsx] 2.54 KiB {main} [built]
       [0] 3ms -> factory:59ms building:1560ms dependencies:3ms = 1625ms
[./src/main/webapp/app/routes.tsx] 2.06 KiB {main} [built]
       [0] 3ms -> [./src/main/webapp/app/index.tsx] 1619ms -> [./src/main/webapp/app/app.tsx] 3101ms -> factory:932ms building:186ms dependencies:79ms = 5920ms
[./src/main/webapp/app/shared/auth/private-route.tsx] 3.63 KiB {main} [built]
       [0] 3ms -> [./src/main/webapp/app/index.tsx] 1619ms -> [./src/main/webapp/app/app.tsx] 3101ms -> factory:932ms building:186ms dependencies:79ms = 5920ms
[./src/main/webapp/app/shared/layout/footer/footer.tsx] 1.55 KiB {main} [built]
       [0] 3ms -> [./src/main/webapp/app/index.tsx] 1619ms -> [./src/main/webapp/app/app.tsx] 3101ms -> factory:932ms building:186ms dependencies:79ms = 5920ms
[./src/main/webapp/app/shared/layout/header/header.tsx] 3.89 KiB {main} [built]
       [0] 3ms -> [./src/main/webapp/app/index.tsx] 1619ms -> [./src/main/webapp/app/app.tsx] 3101ms -> factory:932ms building:186ms dependencies:79ms = 5920ms
[./src/main/webapp/app/shared/reducers/authentication.ts] 3.8 KiB {main} [built]
       [0] 3ms -> [./src/main/webapp/app/index.tsx] 1619ms -> factory:74ms building:3027ms dependencies:211ms = 4934ms
    + 1096 hidden modules
Done in 14.70s.
If you find JHipster useful consider supporting our collective https://opencollective.com/generator-jhipster

Server application generated successfully.

Run your Spring Boot application:
 ./mvnw

Client application generated successfully.

Start your Webpack development server with:
 yarn start

Congratulations, JHipster execution is complete!
Application successfully committed to Git.
Execution time: 1 min. 44 s. sec                                                                    
➜  foo git:(master) yarn e2e
yarn run v1.6.0
$ protractor src/test/javascript/protractor.conf.js
(node:10959) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
[12:27:02] W/configParser - pattern ./e2e/entities/**/*.spec.ts did not match any files.
[12:27:02] I/launcher - Running 1 instances of WebDriver
[12:27:02] I/direct - Using ChromeDriver directly...
[12:27:02] E/direct - Error code: 135
[12:27:02] E/direct - Error message: Could not find update-config.json. Run 'webdriver-manager update' to download binaries.
[12:27:02] E/direct - Error: Could not find update-config.json. Run 'webdriver-manager update' to download binaries.
    at Direct.getNewDriver (/home/mraible/dev/foo/node_modules/protractor/lib/driverProviders/direct.ts:70:19)
    at Runner.createBrowser (/home/mraible/dev/foo/node_modules/protractor/lib/runner.ts:225:39)
    at q.then.then (/home/mraible/dev/foo/node_modules/protractor/lib/runner.ts:391:27)
    at _fulfilled (/home/mraible/dev/foo/node_modules/protractor/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/home/mraible/dev/foo/node_modules/protractor/node_modules/q/q.js:863:30)
    at Promise.promise.promiseDispatch (/home/mraible/dev/foo/node_modules/protractor/node_modules/q/q.js:796:13)
    at /home/mraible/dev/foo/node_modules/protractor/node_modules/q/q.js:556:49
    at runSingle (/home/mraible/dev/foo/node_modules/protractor/node_modules/q/q.js:137:13)
    at flush (/home/mraible/dev/foo/node_modules/protractor/node_modules/q/q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
[12:27:02] E/launcher - Process exited with error code 135
error Command failed with exit code 135.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
➜  foo git:(master) 
```

**Comment by deepu105** [comment]
@mraible may be this is your issue
```
[5/5] Building fresh packages...
[9/9] ⠄ node-sass: Downloading binary from https://github.com/sass/node-sass/releases/downl
[6/9] ⠄ pngquant-bin:   ✔ pngquant pre-build test passed successfully
[-/9] ⠄ waiting...
[-/9] ⠄ waiting...
error /home/mraible/dev/foo/node_modules/pngquant-bin: Command failed.
Exit code: 1
Command: node lib/install.js
Arguments: 
Directory: /home/mraible/dev/foo/node_modules/pngquant-bin
Output:
⚠ The `/home/mraible/dev/foo/node_modules/pngquant-bin/vendor/pngquant` binary doesn't seem to work correctly
  ⚠ pngquant pre-build test failed
  ℹ compiling from source
  ✔ pngquant pre-build test passed successfully
  ✖ Error: pngquant failed to build, make sure that libpng-dev is installed
    at Promise.all.then.arr (/home/mraible/dev/foo/node_modules/pngquant-bin/node_modules/bin-build/
```
The post install step for `pngquant` failed and hence the remaining post install steps(inclusing that of webdriver) didnt complete

I tried your config and it works fine for me

**Comment by deepu105** [comment]
do you have libpng-dev installed?

**Comment by mraible** [comment]
I guess I just expected things to work out-of-the-box on Linux. After installing libpng-dev (with `sudo apt-get install libpng-dev`), everything works. I'll close this ticket since it's obvious now that I look at the error message.

Fun sidenote: creating a new app on my Linux laptop takes 1m55s. On my MacBook Pro, it takes 9m30s. 😳

**Comment by deepu105** [comment]
@mraible welcome to the beautiful world(unwalled) of Linux :clinking_glasses:
