### ISSUE TITLE
Error: Cannot find module 'escape-string-regexp' when generating jhipster-react project

### ISSUE THREAD

**Issue by ElsayedAwdElsayed** [jhipster/generator-jhipster#7808]
I want to create jhipster-react project via this link [generator-jhipster-react](https://www.jhipster.tech/modules/marketplace/#/details/generator-jhipster-react)

I followed all steps but while executing below step

 **yo jhipster-react**

I have got this exception 

```
module.js:549
    throw err;
    ^

Error: Cannot find module 'escape-string-regexp'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (myHomeFolder\AppData\Roaming\npm\node_modules\generator-jhipster-react\node_modules\chalk\index.js:2:26)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)

```

**Comment by deepu105** [comment]
@ElsayedAwdElsayed that project is abandoned(Its stated clearly on its Readme). React support is now in the main generatoir. Pleasde use the latest JHipster version and choose React as the client side.
