### ISSUE TITLE
A fresh new Gateway in v5 with react failed to build the front-end

### ISSUE THREAD

**Issue by DjayDev** [jhipster/generator-jhipster#7830]
##### **Overview of the issue**
Hello,

I know it's definetley not the place here to say thanks for the conf so I won't say it, but thanks.

I have upgraded my generator to the v5 and I've generated a new Gateway with React (at the bottom are the inof of the project).

When it tries to compile when at the end of the generation, it gives the error below: 

```
ERROR in /XXX/05_JHIPSTER/GatewayReact/src/main/webapp/app/modules/administration/gateway/gateway.tsx
(126,61): Argument of type 'typeof GatewayPage' is not assignable to parameter of type 'ComponentType<{ routes: any; account: any; } & { gatewayRoutes: () => { type: string; payload: Ax...'.
  Type 'typeof GatewayPage' is not assignable to type 'StatelessComponent<{ routes: any; account: any; } & { gatewayRoutes: () => { type: string; payloa...'.
    Type 'typeof GatewayPage' provides no match for the signature '(props: { routes: any; account: any; } & { gatewayRoutes: () => { type: string; payload: AxiosPromise<any>; }; } & { children?: ReactNode; }, context?: any): ReactElement<any>'.
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
If you find JHipster useful consider supporting our collective https://opencollective.com/generator-jhipster

Server application generated successfully.

Run your Spring Boot application:
 ./mvnw
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: ERROR! webpack:build failed.
    at Environment.error (/XXX/.config/yarn/global/node_modules/yeoman-environment/lib/environment.js:157:40)
    at module.exports.error (/XXX/.config/yarn/global/node_modules/generator-jhipster/generators/generator-base.js:1981:18)
    at module.exports.end (/XXX/.config/yarn/global/node_modules/generator-jhipster/generators/client/index.js:449:26)
    at Object.<anonymous> (/XXX/.config/yarn/global/node_modules/yeoman-generator/lib/index.js:399:25)
    at /XXX/.config/yarn/global/node_modules/run-async/index.js:25:25
    at new Promise (<anonymous>)
    at /XXX/.config/yarn/global/node_modules/run-async/index.js:24:19
    at self.env.runLoop.add.completed (/XXX/.config/yarn/global/node_modules/yeoman-generator/lib/index.js:400:11)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
```

And so as it is pointed out by the error message, the error is in the Gateway.tsx file
![image](https://user-images.githubusercontent.com/7959058/41762613-99e4581e-75fb-11e8-9fe9-94e31a3d0fe8.png)

##### **Reproduce the error**

* Create a new simple Gateway 
* Select React for the front-end

##### **JHipster Version(s)**
v5.0.0.0
(no beta)

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.djay.demo",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "5.0.0",
    "applicationType": "gateway",
    "baseName": "GatewayReact",
    "packageName": "com.djay.demo",
    "packageFolder": "com/djay/demo",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "hazelcast",
    "enableHibernateCache": false,
    "websocket": false,
    "databaseType": "no",
    "devDatabaseType": "no",
    "prodDatabaseType": "no",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": "eureka",
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "replaced-by-jhipster-info",
    "clientFramework": "react",
    "useSass": false,
    "clientPackageManager": "yarn",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en"
    ]
  }
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

openjdk version "1.8.0_171"
OpenJDK Runtime Environment (build 1.8.0_171-8u171-b11-0ubuntu0.17.10.1-b11)
OpenJDK 64-Bit Server VM (build 25.171-b11, mixed mode)

git version 2.14.1

node: v8.11.3

npm: 5.6.0

yeoman: 1.8.5

yarn: 1.3.2

Docker version 18.03.1-ce, build 9ee9f40

docker-compose version 1.8.0, build unknown

Congratulations, JHipster execution is complete!

##### **Browsers and Operating System**

Linux

- [ X] Checking this box is mandatory (this is just to show you read everything)

**Comment by DjayDev** [comment]
Forget it, I just saw the PR #7826 it fixes this issue.
