### ISSUE TITLE
java.lang.StringIndexOutOfBoundsException in UserService.java

### ISSUE THREAD

**Issue by vcupelloni** [jhipster/generator-jhipster#7866]
##### **Overview of the issue**

Gateway generated with JHipster5 and configured to work with Okta have issues in UserService

`java.lang.StringIndexOutOfBoundsException: String index out of range: -1`
	at java.lang.String.substring(String.java:1967)
	at `com.mycompany.myapp.service.UserService.getUser(UserService.java:261)`
	at com.mycompany.myapp.service.UserService.getUserFromAuthentication(UserService.java:154)
	at com.mycompany.myapp.service.UserService$$FastClassBySpringCGLIB$$2169c3ce.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:746)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:88)
	at `com.mycompany.myapp.aop.logging.LoggingAspect.logAround(LoggingAspect.java:85)

##### **Motivation for or Use Case**

Cannot login to the gateway.

##### **Reproduce the error**

Create a fresh new gateway.
Configure to use Okta authentication.
Try to login.

##### **Suggest a Fix**

It seems that the user locale provided by Okta is like 'en_US' but at line 261 there is a substring on '-' that cause the exception.

##### **JHipster Version(s)**

5.0.1

##### **Browsers and Operating System**

- [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by gmarziou** [comment]
Please paste output of `jhipster info`

**Comment by vcupelloni** [comment]
✘ vcupelloni@ROMLAPA0693  ~/test/gateway> jhipster info
Using JHipster version installed locally in current project's node_modules
Executing jhipster:info
Options: 
Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
gateway@0.0.0 /home/vcupelloni/test/gateway
└── generator-jhipster@5.0.1 

```


##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**


<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.mycompany.myapp"
    },
    "jhipsterVersion": "5.0.1",
    "applicationType": "gateway",
    "baseName": "gateway",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "8080",
    "authenticationType": "oauth2",
    "cacheProvider": "hazelcast",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": "eureka",
    "buildTool": "gradle",
    "enableSwaggerCodegen": false,
    "clientFramework": "angularX",
    "useSass": true,
    "clientPackageManager": "yarn",
    "testFrameworks": [
      "cucumber"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": false
  }
}
</pre>
</details>


##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>


##### **Environment and Tools**

openjdk version "1.8.0_172"
OpenJDK Runtime Environment (build 1.8.0_172-b11)
OpenJDK 64-Bit Server VM (build 25.172-b11, mixed mode)

git version 2.18.0

node: v8.11.3

npm: 6.1.0

yeoman: 2.0.2

yarn: 1.7.0

Docker version 18.05.0-ce, build f150324782

docker-compose version 1.21.2, build unknown

Congratulations, JHipster execution is complete!

**Comment by clarenced** [comment]
Can I provide help for this issue ?

**Comment by vcupelloni** [comment]
Hi, I haven't said anything before because I don't know the reason behind the use of '-' instead of '_' to split the locale code.

As far as I know the standard is the IETF Language Tag, so en-US, but is also true that, for instance, POSIX format is en_US and this is exactly the same validation made by Okta on their Profile Management page:

![image](https://user-images.githubusercontent.com/12106367/42229779-8f476a0a-7ee7-11e8-822b-da59f6910d54.png)

Could it be acceptable to insert a simple control on the locale string to check if it contains a dash or an underscore and then substring on the right element?

**Comment by mraible** [comment]
@vcupelloni If you'd like to submit a pull request with your suggested fix, I'd be happy to merge it.

**Comment by vcupelloni** [comment]
@mraible with great pleasure! 
Just give me some time to read the guideline ;)

**Comment by lmbai** [comment]
for `Okta`, they are using `en-US`. but in keycloak, they are using `en`. the current logic will not set the langKey anymore. 

for the keycloak, they have `zh-CN', but in jhipster, we are using `zh-cn` ...
here we can't cater for all the senarios. we should let the developer to adjust the format themself.
