### ISSUE TITLE
Error using liquibase with H2Memory

### ISSUE THREAD

**Issue by DanielFran** [jhipster/generator-jhipster#7870]
##### **Overview of the issue**

Creating new microservice v.5.0.1 with H2Memory in Dev result with an error executing liquibase scripts.

##### **Motivation for or Use Case**

See stackstrace:
```
        ██╗ ██╗   ██╗ ████████╗ ███████╗   ██████╗ ████████╗ ████████╗ ███████╗
        ██║ ██║   ██║ ╚══██╔══╝ ██╔═══██╗ ██╔════╝ ╚══██╔══╝ ██╔═════╝ ██╔═══██╗
        ██║ ████████║    ██║    ███████╔╝ ╚█████╗     ██║    ██████╗   ███████╔╝
  ██╗   ██║ ██╔═══██║    ██║    ██╔════╝   ╚═══██╗    ██║    ██╔═══╝   ██╔══██║
  ╚██████╔╝ ██║   ██║ ████████╗ ██║       ██████╔╝    ██║    ████████╗ ██║  ╚██╗
   ╚═════╝  ╚═╝   ╚═╝ ╚═══════╝ ╚═╝       ╚═════╝     ╚═╝    ╚═══════╝ ╚═╝   ╚═╝

:: JHipster 🤓  :: Running Spring Boot 2.0.3.RELEASE ::
:: https://www.jhipster.tech ::

2018-06-27 10:05:10.607  INFO 13483 --- [  restartedMain] i.r.m.s.m.MyapplicationApp    		   : The following profiles are active: dev,swagger
2018-06-27 10:05:15.497 DEBUG 13483 --- [  restartedMain] i.r.m.s.m.config.AsyncConfiguration      : Creating Async Task Executor
2018-06-27 10:05:16.863 DEBUG 13483 --- [  restartedMain] i.r.m.s.m.config.MetricsConfiguration    : Registering JVM gauges
2018-06-27 10:05:16.970 DEBUG 13483 --- [  restartedMain] i.r.m.s.m.config.MetricsConfiguration    : Monitoring the datasource
2018-06-27 10:05:16.988 DEBUG 13483 --- [  restartedMain] i.r.m.s.m.config.MetricsConfiguration    : Initializing Metrics JMX reporting
2018-06-27 10:05:19.924  INFO 13483 --- [  restartedMain] i.r.m.s.m.config.WebConfigurer           : Web application configuration, using profiles: dev
2018-06-27 10:05:19.927 DEBUG 13483 --- [  restartedMain] i.r.m.s.m.config.WebConfigurer           : Initializing Metrics registries
2018-06-27 10:05:19.934 DEBUG 13483 --- [  restartedMain] i.r.m.s.m.config.WebConfigurer           : Registering Metrics Filter
2018-06-27 10:05:19.935 DEBUG 13483 --- [  restartedMain] i.r.m.s.m.config.WebConfigurer           : Registering Metrics Servlet
2018-06-27 10:05:19.942 DEBUG 13483 --- [  restartedMain] i.r.m.s.m.config.WebConfigurer           : Initialize H2 console
2018-06-27 10:05:19.945  INFO 13483 --- [  restartedMain] i.r.m.s.m.config.WebConfigurer           : Web application fully configured
2018-06-27 10:05:20.459 DEBUG 13483 --- [  restartedMain] i.r.m.s.m.config.DatabaseConfiguration   : Configuring Liquibase
2018-06-27 10:05:20.834  WARN 13483 --- [tion-Executor-1] i.g.j.c.liquibase.AsyncSpringLiquibase   : Starting Liquibase asynchronously, your database might not be ready at startup!
2018-06-27 10:05:24.164  WARN 13483 --- [  restartedMain] ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'entityManagerFactory' defined in class path resource [org/springframework/boot/autoconfigure/orm/jpa/HibernateJpaConfiguration.class]: Invocation of init method failed; nested exception is javax.persistence.PersistenceException: [PersistenceUnit: default] Unable to build Hibernate SessionFactory; nested exception is org.hibernate.cfg.beanvalidation.IntegrationException: Error activating Bean Validation integration
2018-06-27 10:05:24.177  WARN 13483 --- [  restartedMain] o.s.b.f.support.DisposableBeanAdapter    : Invocation of destroy method failed on bean with name 'inMemoryDatabaseShutdownExecutor': org.h2.jdbc.JdbcSQLException: Database is already closed (to disable automatic closing at VM shutdown, add ";DB_CLOSE_ON_EXIT=FALSE" to the db URL) [90121-197]
2018-06-27 10:05:24.218 ERROR 13483 --- [tion-Executor-1] liquibase                                : Could not release lock

liquibase.exception.LockException: liquibase.exception.DatabaseException: liquibase.exception.DatabaseException: org.h2.jdbc.JdbcSQLException: Database is already closed (to disable automatic closing at VM shutdown, add ";DB_CLOSE_ON_EXIT=FALSE" to the db URL) [90121-197]
	at liquibase.lockservice.StandardLockService.releaseLock(StandardLockService.java:283)
	at liquibase.Liquibase.update(Liquibase.java:218)
	at liquibase.Liquibase.update(Liquibase.java:192)
	at liquibase.integration.spring.SpringLiquibase.performUpdate(SpringLiquibase.java:431)
	at liquibase.integration.spring.SpringLiquibase.afterPropertiesSet(SpringLiquibase.java:388)
	at io.github.jhipster.config.liquibase.AsyncSpringLiquibase.initDb(AsyncSpringLiquibase.java:103)
	at io.github.jhipster.config.liquibase.AsyncSpringLiquibase.lambda$afterPropertiesSet$0(AsyncSpringLiquibase.java:83)
	at io.github.jhipster.async.ExceptionHandlingAsyncTaskExecutor.lambda$createWrappedRunnable$1(ExceptionHandlingAsyncTaskExecutor.java:68)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: liquibase.exception.DatabaseException: liquibase.exception.DatabaseException: org.h2.jdbc.JdbcSQLException: Database is already closed (to disable automatic closing at VM shutdown, add ";DB_CLOSE_ON_EXIT=FALSE" to the db URL) [90121-197]
	at liquibase.database.AbstractJdbcDatabase.rollback(AbstractJdbcDatabase.java:1168)
	at liquibase.lockservice.StandardLockService.releaseLock(StandardLockService.java:266)
	... 10 common frames omitted
Caused by: liquibase.exception.DatabaseException: org.h2.jdbc.JdbcSQLException: Database is already closed (to disable automatic closing at VM shutdown, add ";DB_CLOSE_ON_EXIT=FALSE" to the db URL) [90121-197]
	at liquibase.database.jvm.JdbcConnection.rollback(JdbcConnection.java:340)
	at liquibase.database.AbstractJdbcDatabase.rollback(AbstractJdbcDatabase.java:1166)
	... 11 common frames omitted
Caused by: org.h2.jdbc.JdbcSQLException: Database is already closed (to disable automatic closing at VM shutdown, add ";DB_CLOSE_ON_EXIT=FALSE" to the db URL) [90121-197]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:357)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.message.DbException.get(DbException.java:144)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1526)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1502)
	at org.h2.jdbc.JdbcConnection.getAutoCommit(JdbcConnection.java:476)
	at com.zaxxer.hikari.pool.HikariProxyConnection.getAutoCommit(HikariProxyConnection.java)
	at liquibase.database.jvm.JdbcConnection.rollback(JdbcConnection.java:336)
	... 12 common frames omitted

2018-06-27 10:05:24.230  WARN 13483 --- [tion-Executor-1] liquibase                                : Failed to restore the auto commit to true
2018-06-27 10:05:24.231 ERROR 13483 --- [tion-Executor-1] i.g.j.c.liquibase.AsyncSpringLiquibase   : Liquibase could not start correctly, your database is NOT ready: org.h2.jdbc.JdbcSQLException: Database is already closed (to disable automatic closing at VM shutdown, add ";DB_CLOSE_ON_EXIT=FALSE" to the db URL) [90121-197]

liquibase.exception.DatabaseException: org.h2.jdbc.JdbcSQLException: Database is already closed (to disable automatic closing at VM shutdown, add ";DB_CLOSE_ON_EXIT=FALSE" to the db URL) [90121-197]
	at liquibase.database.jvm.JdbcConnection.setAutoCommit(JdbcConnection.java:363)
	at liquibase.database.AbstractJdbcDatabase.close(AbstractJdbcDatabase.java:1202)
	at liquibase.integration.spring.SpringLiquibase.afterPropertiesSet(SpringLiquibase.java:397)
	at io.github.jhipster.config.liquibase.AsyncSpringLiquibase.initDb(AsyncSpringLiquibase.java:103)
	at io.github.jhipster.config.liquibase.AsyncSpringLiquibase.lambda$afterPropertiesSet$0(AsyncSpringLiquibase.java:83)
	at io.github.jhipster.async.ExceptionHandlingAsyncTaskExecutor.lambda$createWrappedRunnable$1(ExceptionHandlingAsyncTaskExecutor.java:68)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.h2.jdbc.JdbcSQLException: Database is already closed (to disable automatic closing at VM shutdown, add ";DB_CLOSE_ON_EXIT=FALSE" to the db URL) [90121-197]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:357)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.message.DbException.get(DbException.java:144)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1526)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1502)
	at org.h2.jdbc.JdbcConnection.setAutoCommit(JdbcConnection.java:455)
	at com.zaxxer.hikari.pool.ProxyConnection.setAutoCommit(ProxyConnection.java:395)
	at com.zaxxer.hikari.pool.HikariProxyConnection.setAutoCommit(HikariProxyConnection.java)
	at liquibase.database.jvm.JdbcConnection.setAutoCommit(JdbcConnection.java:361)
	... 8 common frames omitted

2018-06-27 10:05:24.282 ERROR 13483 --- [  restartedMain] o.s.boot.SpringApplication               : Application run failed

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'entityManagerFactory' defined in class path resource [org/springframework/boot/autoconfigure/orm/jpa/HibernateJpaConfiguration.class]: Invocation of init method failed; nested exception is javax.persistence.PersistenceException: [PersistenceUnit: default] Unable to build Hibernate SessionFactory; nested exception is org.hibernate.cfg.beanvalidation.IntegrationException: Error activating Bean Validation integration
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1708)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:581)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:503)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:317)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:315)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
	at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1089)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:859)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:550)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:140)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:759)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:395)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:327)
	at io.test.myapplication.MyapplicationApp.main(MyapplicationApp.java:63)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.devtools.restart.RestartLauncher.run(RestartLauncher.java:49)
Caused by: javax.persistence.PersistenceException: [PersistenceUnit: default] Unable to build Hibernate SessionFactory; nested exception is org.hibernate.cfg.beanvalidation.IntegrationException: Error activating Bean Validation integration
	at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.buildNativeEntityManagerFactory(AbstractEntityManagerFactoryBean.java:402)
	at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.afterPropertiesSet(AbstractEntityManagerFactoryBean.java:377)
	at org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean.afterPropertiesSet(LocalContainerEntityManagerFactoryBean.java:341)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1767)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1704)
	... 19 common frames omitted
Caused by: org.hibernate.cfg.beanvalidation.IntegrationException: Error activating Bean Validation integration
	at org.hibernate.cfg.beanvalidation.BeanValidationIntegrator.integrate(BeanValidationIntegrator.java:138)
	at org.hibernate.internal.SessionFactoryImpl.<init>(SessionFactoryImpl.java:281)
	at org.hibernate.boot.internal.SessionFactoryBuilderImpl.build(SessionFactoryBuilderImpl.java:462)
	at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.build(EntityManagerFactoryBuilderImpl.java:892)
	at org.springframework.orm.jpa.vendor.SpringHibernateJpaPersistenceProvider.createContainerEntityManagerFactory(SpringHibernateJpaPersistenceProvider.java:57)
	at org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean.createNativeEntityManagerFactory(LocalContainerEntityManagerFactoryBean.java:365)
	at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.buildNativeEntityManagerFactory(AbstractEntityManagerFactoryBean.java:390)
	... 23 common frames omitted
Caused by: java.lang.annotation.AnnotationFormatError: Duplicate annotation for class: interface javax.validation.constraints.NotNull: @javax.validation.constraints.NotNull(message={javax.validation.constraints.NotNull.message}, payload=[], groups=[])
	at sun.reflect.annotation.TypeAnnotationParser.mapTypeAnnotations(TypeAnnotationParser.java:360)
	at sun.reflect.annotation.AnnotatedTypeFactory$AnnotatedTypeBaseImpl.<init>(AnnotatedTypeFactory.java:139)
	at sun.reflect.annotation.AnnotatedTypeFactory.buildAnnotatedType(AnnotatedTypeFactory.java:65)
	at sun.reflect.annotation.TypeAnnotationParser.buildAnnotatedType(TypeAnnotationParser.java:79)
	at java.lang.reflect.Field.getAnnotatedType(Field.java:1170)
	at org.hibernate.validator.internal.metadata.provider.AnnotationMetaDataProvider.findCascadingMetaData(AnnotationMetaDataProvider.java:614)
	at org.hibernate.validator.internal.metadata.provider.AnnotationMetaDataProvider.findPropertyMetaData(AnnotationMetaDataProvider.java:236)
	at org.hibernate.validator.internal.metadata.provider.AnnotationMetaDataProvider.getFieldMetaData(AnnotationMetaDataProvider.java:225)
	at org.hibernate.validator.internal.metadata.provider.AnnotationMetaDataProvider.retrieveBeanConfiguration(AnnotationMetaDataProvider.java:133)
	at org.hibernate.validator.internal.metadata.provider.AnnotationMetaDataProvider.getBeanConfiguration(AnnotationMetaDataProvider.java:124)
	at org.hibernate.validator.internal.metadata.BeanMetaDataManager.getBeanConfigurationForHierarchy(BeanMetaDataManager.java:220)
	at org.hibernate.validator.internal.metadata.BeanMetaDataManager.createBeanMetaData(BeanMetaDataManager.java:187)
	at org.hibernate.validator.internal.metadata.BeanMetaDataManager.lambda$getBeanMetaData$0(BeanMetaDataManager.java:160)
	at java.util.concurrent.ConcurrentMap.computeIfAbsent(ConcurrentMap.java:324)
	at org.hibernate.validator.internal.metadata.BeanMetaDataManager.getBeanMetaData(BeanMetaDataManager.java:159)
	at org.hibernate.validator.internal.engine.ValidatorImpl.getConstraintsForClass(ValidatorImpl.java:294)
	at org.hibernate.cfg.beanvalidation.TypeSafeActivator.applyDDL(TypeSafeActivator.java:207)
	at org.hibernate.cfg.beanvalidation.TypeSafeActivator.applyRelationalConstraints(TypeSafeActivator.java:191)
	at org.hibernate.cfg.beanvalidation.TypeSafeActivator.applyRelationalConstraints(TypeSafeActivator.java:150)
	at org.hibernate.cfg.beanvalidation.TypeSafeActivator.activate(TypeSafeActivator.java:98)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.hibernate.cfg.beanvalidation.BeanValidationIntegrator.integrate(BeanValidationIntegrator.java:132)
	... 29 common frames omitted
```

##### **Reproduce the error**

Create new microservice and import jdl.
Start microservice in dev profile and error happens.

##### **Suggest a Fix**

Add ';DB_CLOSE_ON_EXIT=FALSE' to url.

##### **JHipster Version(s)**

v.5.0.1

##### **JHipster configuration**

Using JHipster version installed globally
Executing jhipster:info
Options: 
Welcome to the JHipster Information Sub-Generator

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "io.test.myapplication"
    },
    "jhipsterVersion": "5.0.1",
    "applicationType": "microservice",
    "baseName": "myapplication",
    "packageName": "io.test.myapplication",
    "packageFolder": "io/test/myapplication",
    "serverPort": "8010",
    "authenticationType": "jwt",
    "cacheProvider": "no",
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Memory",
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "replaced-by-jhipster-info",
    "enableTranslation": false,
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "clientPackageManager": "npm",
    "skipClient": true,
    "skipUserManagement": true
  }
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
/**
 * Category entity
 */
entity Category (category) {
  /**
   * Description
   */
  description String required,
  /**
   * Sort order
   */
  sortOrder Integer,
  /**
   * Creation date
   */
  dateAdded Instant,
  /**
   * Update date
   */
  dateModified Instant,
  /**
   * Status
   */
  status CategoryStatus
}
/**
 * Product entity
 */
entity Product (product) {
  /**
   * Title
   */
  title String required,
  /**
   * Keywords
   */
  keywords String,
  /**
   * Description
   */
  description String,
  /**
   * Rating
   */
  rating Integer,
  /**
   * Creation date
   */
  dateAdded Instant,
  /**
   * Update date
   */
  dateModified Instant
}
/**
 * Customer entity
 */
entity Customer (customer) {
  /**
   * First name
   */
  firstName String,
  /**
   * Last name
   */
  lastName String,
  /**
   * Email
   */
  email String,
  /**
   * Telephone
   */
  telephone String
}
/**
 * Address entity
 */
entity Address (address) {
  /**
   * Address line 1
   */
  address1 String,
  /**
   * Address line 2
   */
  address2 String,
  /**
   * City
   */
  city String,
  /**
   * Zip code
   */
  postcode String required maxlength(10),
  /**
   * Country
   */
  country String required maxlength(2)
}

enum CategoryStatus {
  AVAILABLE,
  RESTRICTED,
  DISABLED
}

relationship OneToMany {
  /**
   * Addresses
   */
  Customer{address} to
  /**
   * Customer
   */
  Address{customer}
}
relationship ManyToOne {
  /**
   * Parent category
   */
  Category{parent} to Category
}
relationship ManyToMany {
  /**
   * Titles
   */
  Category{product(title)} to
  /**
   * Categories
   */
  Product{category}
}

dto Category, Product, Customer, Address with mapstruct
paginate Category, Product, Customer, Address with pagination
service Category, Product, Customer, Address with serviceClass
microservice Category, Product, Customer, Address with myciServiceMyapplication
filter Category, Product, Customer, Address

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_152"
Java(TM) SE Runtime Environment (build 1.8.0_152-b16)
Java HotSpot(TM) 64-Bit Server VM (build 25.152-b16, mixed mode)

git version 1.8.3.1
node: v8.11.1
npm: 5.6.0
yeoman: 2.0.1
Docker version 17.12.0-ce, build c97c6d6
docker-compose version 1.9.0, build 2585387

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by PierreBesson** [comment]
Thank you for respecting our guidelines but next time please enclose your stacktrace with  ```. I have edited your post for you.

**Comment by DanielFran** [comment]
@PierreBesson thanks for the update.

This is strange, adding even ';DB_CLOSE_ON_EXIT=FALSE' to the url, sometimes it works, sometimes it don't !?!

Are you able to confirm the issue?

**Comment by PierreBesson** [comment]
Can you make sure you run `mvn clean` as this is using h2 disk, the data is stored in `target`

**Comment by DanielFran** [comment]
Obviously, what a dumb! 👍 

Will do the PR...

Thanks

**Comment by jdubois** [comment]
Liquibase with H2 in memory doesn't work as far as I know.
Liquibase needs to access your running instance, and for this you need an opened port to H2, and I don't think it's available, at least not by default.

-> if you have this running it's great news, because I couldn't make it work!! So this needs to be documented

**Comment by PierreBesson** [comment]
@jdubois I think what you mean is `mvn liquibase:diff` doesn't work with H2. For liquibase itself it is supposed to work.

**Comment by jdubois** [comment]
Oh sorry I read too quickly, indeed @PierreBesson you are correct

**Comment by pascalgrimaud** [comment]
Just tried it, I confirm the issue
