### ISSUE TITLE
TypeError: this.http.get(...).map is not a function in *new entity service with date attribute*

### ISSUE THREAD

**Issue by luisRubiera** [jhipster/generator-jhipster#7998]
##### **Overview of the issue**
`yarn run webpack:test` fails on services that have a `.map` in the response . with the following error : 
```
  ● Service Tests › BridgeTransaction Service › Service methods › should propagate not found response

    TypeError: this.http.get(...).map is not a function

      35 |         return this.http
      36 |             .get<IBridgeTransaction>(`${this.resourceUrl}/${id}`, { observe: 'response' })
    > 37 |             .map((res: EntityResponseType) => this.convertDateFromServer(res));
      38 |     }
      39 | 
      40 |     query(req?: any): Observable<EntityArrayResponseType> {
      
      at BridgeTransactionService.Object.<anonymous>.BridgeTransactionService.find (src/main/webapp/app/entities/bridge-transaction/bridge-transaction.service.ts:37:14)
      at src/test/javascript/spec/app/entities/bridge-transaction/bridge-transaction.service.spec.ts:79:25
      at ZoneDelegate.Object.<anonymous>.ZoneDelegate.invoke (node_modules/zone.js/dist/zone.js:388:26)
      at ProxyZoneSpec.Object.<anonymous>.ProxyZoneSpec.onInvoke (node_modules/zone.js/dist/proxy.js:128:39)
      at ZoneDelegate.Object.<anonymous>.ZoneDelegate.invoke (node_modules/zone.js/dist/zone.js:387:32)
      at Zone.Object.<anonymous>.Zone.run (node_modules/zone.js/dist/zone.js:138:43)
      at Object.testBody.length (node_modules/jest-zone-patch/index.js:50:27)
```

##### **Motivation for or Use Case**

i want to be able to generate entities and then never touch the generated code and use it in extended classes, to correct this i have to modify the test and this does not respect the constraint (as it is a best practice ) . 
##### **Reproduce the error**
generate a project, then add a new entity and set an attribute of type date (e.g. updatetAt,createdAt,etc..) and then do `yarn run webpack:test` 

##### **Suggest a Fix**
just add 
`import 'rxjs/add/operator/map';` 
in all front services (or only in needed ones )
https://stackoverflow.com/questions/34515173/angular-http-get-with-typescript-error-http-get-map-is-not-a-function-in-n

##### **JHipster Version(s)**
 5.0.2 ( tried to upgrade to 5.1.0 but this didnt work at all, even with `jhipster upgrade --target-version=5.1.0` 

##### **JHipster configuration**

Jhipster info: 
```
Using JHipster version installed locally in current project's node_modules
Executing jhipster:info
Options: 
Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
my-project@0.0.0 /home/luis/Projects/myproject
└── generator-jhipster@5.0.2 

```


##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**


<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.myproject",
      "nativeLanguage": "fr"
    },
    "jhipsterVersion": "5.0.2",
    "applicationType": "monolith",
    "baseName": "MyProject",
    "packageName": "com.myproject",
    "packageFolder": "com/myproject",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "replaced-by-jhipster-info",
    "clientFramework": "angularX",
    "useSass": true,
    "clientPackageManager": "yarn",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "fr",
    "languages": [
      "fr",
      "en"
    ]
  }
}

</pre>
</details>


##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity BridgeUser (bridge_user) {
  uuidBridge String,
  email String,
  password String
}
entity BridgeBank (bridge_bank) {
  idBridge Long,
  name String,
  countryCode String
}
entity BridgeAccountBank (bridge_account_bank) {
  idBridge Long,
  name String,
  type String,
  currencyCode String,
  itemStatus Long,
  updatedAt ZonedDateTime
}
entity BridgeAccountOnlineBank (bridge_account_online_bank) {
  idBridge Long,
  status Long
}
entity AccountBankStat (account_bank_stat) {
  balance Double,
  lastRefresh ZonedDateTime
}
entity BridgeTransaction (bridge_transaction) {
  idBridge Long,
  description String,
  rawDescription String,
  date LocalDate,
  updatedAt ZonedDateTime,
  isDeleted Boolean
}
entity BridgeCategory (bridge_category) {
  idBridge Long,
  name String
}
relationship OneToOne {
  BridgeUser{user} to User
}
relationship OneToMany {
  BridgeAccountOnlineBank{bridgeAccountsBank} to BridgeAccountBank{bridgeAccountOnlineBank},
  BridgeUser{bridgeAccountsOnlineBank} to BridgeAccountOnlineBank{bridgeUser},
  BridgeAccountBank{bridgeAccountBankStats} to AccountBankStat{bridgeAccountBank},
  BridgeAccountBank{bridgeTransactions} to BridgeTransaction{bridgeAccountBank}
}
relationship ManyToOne {
  BridgeAccountBank{bridgeBank} to BridgeBank,
  BridgeAccountOnlineBank{bridgeBank} to BridgeBank,
  BridgeTransaction{bridgeCategory} to BridgeCategory,
  BridgeCategory{bridgeCategoryParent} to BridgeCategory
}

service BridgeUser, BridgeBank, BridgeAccountBank, BridgeAccountOnlineBank, AccountBankStat, BridgeTransaction, BridgeCategory with serviceClass

</pre>
</details>


##### **Environment and Tools**

java version "1.8.0_171"
Java(TM) SE Runtime Environment (build 1.8.0_171-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.171-b11, mixed mode)

git version 2.7.4

node: v9.11.1

npm: 5.6.0

yeoman: 2.0.3

yarn: 1.6.0

Docker version 18.03.1-ce, build 9ee9f40

docker-compose version 1.21.2, build a133471

Congratulations, JHipster execution is complete!
```

##### **Browsers and Operating System**

```
uname -a
Linux luis-GL62M-7RDX 4.15.0-041500-lowlatency #201802011154 SMP PREEMPT Thu Feb 1 11:58:07 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```
- [x] Checking this box is mandatory (this is just to show you read everything)

##### **Notes**
I modified the Jhipster info result to respect the privacy of my client  ( PackaName / ProjectName )

**Comment by ruddell** [comment]
The code in your error message is from an entity generated with `generator-jhipster` version `<= v5.0.1`, in `>=v5.0.2` it has a call to `pipe` around the call to `map` ([see v5.0.2 template](https://github.com/jhipster/generator-jhipster/blob/v5.0.2/generators/entity-client/templates/angular/src/main/webapp/app/entities/entity.service.ts.ejs#L67)).  Make sure when you run the `entity` generator it uses the same version of JHipster as your project used when generating.

**Comment by luisRubiera** [comment]
thanks for the answer, is there anyway to upgrade the generators generated code or we have to rollback?

**Comment by ruddell** [comment]
The `upgrade` generator should upgrade your entities along with your project.  You can also manually upgrade your entity's generated code by re-generating the entity.

Here's an example upgrade from v5.0.2 -> v5.1.0 using `jhipster upgrade`: https://github.com/ruddell/jhipster-examples/commit/bc942df68ac7f62d9f240115e018afbab8a39dd8#diff-d8e8adb6035ee8b7b2b11d0c471cfe22

**Comment by priyeshjaiswal** [comment]
dsd
