### ISSUE TITLE
Cloud foundry deployment fails with "No suitable cloud connector found"

### ISSUE THREAD

**Issue by nadworny** [jhipster/generator-jhipster#8169]
##### **Overview of the issue**
After generating jhipster monolithic project and deploying it to cloud foundry (IBM cloud) I'm getting the following error:
```Error creating bean with name 'cloudDatabaseConfiguration' defined in file [/home/vcap/app/WEB-INF/classes/com/example/config/CloudDatabaseConfiguration.class]: Initialization of bean failed; nested exception is org.springframework.cloud.CloudException: No suitable cloud connector found```

##### **Reproduce the error**
With default configuration execute the following:
- mvn -Pprod clean install
- yo jhipster:cloudfoundry
  - default name
  - Postgres database service (IBM cloud: compose-for-postgresql)
  - dataplan (IBM cloud: Standard)

##### **Suggest a Fix**
No idea :/

##### **JHipster Version(s)**
```{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.example",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "5.1.0",
    "applicationType": "monolith",
    "baseName": "example",
    "packageName": "com.example",
    "packageFolder": "com/example",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "no",
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "205ac032a9a357cdc618948fec77f80eaa4e9347",
    "clientFramework": "angularX",
    "useSass": false,
    "clientPackageManager": "yarn",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en"
    ]
  }
}
```

##### **Browsers and Operating System**
MacOs

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by nadworny** [comment]
Full stack trace
```2018-08-27T21:00:40.50+0200 [APP/PROC/WEB/0] OUT :: JHipster 🤓  :: Running Spring Boot 2.0.3.RELEASE ::
   2018-08-27T21:00:40.50+0200 [APP/PROC/WEB/0] OUT :: https://www.jhipster.tech ::
   2018-08-27T21:00:41.06+0200 [APP/PROC/WEB/0] OUT 2018-08-27 19:00:41.059  INFO 11 --- [           main] pertySourceApplicationContextInitializer : 'cloud' property source added
   2018-08-27T21:00:41.07+0200 [APP/PROC/WEB/0] OUT 2018-08-27 19:00:41.069  INFO 11 --- [           main] nfigurationApplicationContextInitializer : Reconfiguration enabled
   2018-08-27T21:00:41.08+0200 [APP/PROC/WEB/0] OUT 2018-08-27 19:00:41.086  INFO 11 --- [           main] com.example.ExampleApp                    : Starting ExampleApp on 1cca3dad-ac8a-4b4f-507c-184c with PID 11 (/home/vcap/app/WEB-INF/classes started by vcap in /home/vcap/app)
   2018-08-27T21:00:41.08+0200 [APP/PROC/WEB/0] OUT 2018-08-27 19:00:41.089  INFO 11 --- [           main] com.example.ExampleApp                    : The following profiles are active: prod,cloudfoundry,cloud
   2018-08-27T21:00:45.80+0200 [APP/PROC/WEB/0] OUT 2018-08-27 19:00:45.800  INFO 11 --- [           main] eReconfigurationBeanFactoryPostProcessor : Skipping reconfiguration because cloud services already configured
   2018-08-27T21:00:50.61+0200 [APP/PROC/WEB/0] OUT 2018-08-27 19:00:50.609  WARN 11 --- [           main] ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.context.ApplicationContextException: Unable to start web server; nested exception is java.lang.RuntimeException: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'servletEndpointRegistrar' defined in class path resource [org/springframework/boot/actuate/autoconfigure/endpoint/web/ServletEndpointManagementContextConfiguration$WebMvcServletEndpointManagementContextConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.boot.actuate.endpoint.web.ServletEndpointRegistrar]: Factory method 'servletEndpointRegistrar' threw exception; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'auditEventsEndpoint' defined in class path resource [org/springframework/boot/actuate/autoconfigure/audit/AuditEventsEndpointAutoConfiguration.class]: Unsatisfied dependency expressed through method 'auditEventsEndpoint' parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'customAuditEventRepository' defined in file [/home/vcap/app/WEB-INF/classes/com/example/repository/CustomAuditEventRepository.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'persistenceAuditEventRepository': Cannot create inner bean '(inner bean)#5ee2b6f9' of type [org.springframework.orm.jpa.SharedEntityManagerCreator] while setting bean property 'entityManager'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name '(inner bean)#5ee2b6f9': Cannot resolve reference to bean 'entityManagerFactory' while setting constructor argument; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'liquibase' defined in class path resource [com/example/config/LiquibaseConfiguration.class]: Unsatisfied dependency expressed through method 'liquibase' parameter 1; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'cloudDatabaseConfiguration' defined in file [/home/vcap/app/WEB-INF/classes/com/example/config/CloudDatabaseConfiguration.class]: Initialization of bean failed; nested exception is org.springframework.cloud.CloudException: No suitable cloud connector found
   2018-08-27T21:00:50.66+0200 [APP/PROC/WEB/0] OUT 2018-08-27 19:00:50.664 ERROR 11 --- [           main] o.s.boot.SpringApplication               : Application run failed
   2018-08-27T21:00:50.66+0200 [APP/PROC/WEB/0] OUT org.springframework.context.ApplicationContextException: Unable to start web server; nested exception is java.lang.RuntimeException: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'servletEndpointRegistrar' defined in class path resource [org/springframework/boot/actuate/autoconfigure/endpoint/web/ServletEndpointManagementContextConfiguration$WebMvcServletEndpointManagementContextConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.boot.actuate.endpoint.web.ServletEndpointRegistrar]: Factory method 'servletEndpointRegistrar' threw exception; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'auditEventsEndpoint' defined in class path resource [org/springframework/boot/actuate/autoconfigure/audit/AuditEventsEndpointAutoConfiguration.class]: Unsatisfied dependency expressed through method 'auditEventsEndpoint' parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'customAuditEventRepository' defined in file [/home/vcap/app/WEB-INF/classes/com/example/repository/CustomAuditEventRepository.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'persistenceAuditEventRepository': Cannot create inner bean '(inner bean)#5ee2b6f9' of type [org.springframework.orm.jpa.SharedEntityManagerCreator] while setting bean property 'entityManager'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name '(inner bean)#5ee2b6f9': Cannot resolve reference to bean 'entityManagerFactory' while setting constructor argument; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'liquibase' defined in class path resource [com/example/config/LiquibaseConfiguration.class]: Unsatisfied dependency expressed through method 'liquibase' parameter 1; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'cloudDatabaseConfiguration' defined in file [/home/vcap/app/WEB-INF/classes/com/example/config/CloudDatabaseConfiguration.class]: Initialization of bean failed; nested exception is org.springframework.cloud.CloudException: No suitable cloud connector found
   2018-08-27T21:00:50.66+0200 [APP/PROC/WEB/0] OUT 	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.onRefresh(ServletWebServerApplicationContext.java:155)
   2018-08-27T21:00:50.66+0200 [APP/PROC/WEB/0] OUT 	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:544)
   2018-08-27T21:00:50.66+0200 [APP/PROC/WEB/0] OUT 	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:140)
   2018-08-27T21:00:50.66+0200 [APP/PROC/WEB/0] OUT 	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:759)
   2018-08-27T21:00:50.66+0200 [APP/PROC/WEB/0] OUT 	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:395)
   2018-08-27T21:00:50.66+0200 [APP/PROC/WEB/0] OUT 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:327)
   2018-08-27T21:00:50.66+0200 [APP/PROC/WEB/0] OUT 	at com.example.ExampleApp.main(ExampleApp.java:61)
   2018-08-27T21:00:50.66+0200 [APP/PROC/WEB/0] OUT 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
   2018-08-27T21:00:50.66+0200 [APP/PROC/WEB/0] OUT 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
   2018-08-27T21:00:50.66+0200 [APP/PROC/WEB/0] OUT 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
   2018-08-27T21:00:50.66+0200 [APP/PROC/WEB/0] OUT 	at java.lang.reflect.Method.invoke(Method.java:498)
   2018-08-27T21:00:50.66+0200 [APP/PROC/WEB/0] OUT 	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
   2018-08-27T21:00:50.66+0200 [APP/PROC/WEB/0] OUT 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
   2018-08-27T21:00:50.66+0200 [APP/PROC/WEB/0] OUT 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
   2018-08-27T21:00:50.66+0200 [APP/PROC/WEB/0] OUT 	at org.springframework.boot.loader.WarLauncher.main(WarLauncher.java:58)```

**Comment by jdubois** [comment]
Maybe the cloud database wasn't ready when the application started, I have no idea what IBM has done here...

- can you see the database, is it binded to the application?
- if yes, then can you try deploying again?

**Comment by nadworny** [comment]
Yes, I could see the application as well as the database... And the db service was bound. 
After restarting the app it was still getting the same error...
I've deleted everything and re-deployed - boom it works! :D I guess IBM cloud was having difficulties yesterday...
