### ISSUE TITLE
I can't generate entity from JSON File.

### ISSUE THREAD

**Issue by tomj0101** [jhipster/generator-jhipster#8210]
##### **Overview of the issue**

I can't generate entity from JSON File. when I create an application (generator-jhipster version 5.3.0) generated good, but if I try to run the entity command. ( yo jhipster:entity Contacts) I get an error.

##### **Motivation for or Use Case**

I still used create entity .jhipster/Contacts.json file.

##### **Reproduce the error**

developer@dev-pc:~/Documents/Project/contact-list-in-action/contact-list-spring-reactjs$ yo jhipster:entity Contacts
module.js:549
    throw err;
    ^

Error: Cannot find module 'nice-try'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/developer/Documents/Project/contact-list-in-action/contact-list-spring-reactjs/node_modules/cross-spawn/lib/parse.js:4:17)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)

##### **Related issues**

No Apply

##### **Suggest a Fix**

Somo soluction can be install libpng-dev

This is required by pngquant-bin, which is required by laravel-mix. This somehow disturbed the installation of shebang-command and laravel-mix.

Solution:

$sudo apt install ligpng-dev
And on laravel project
$ rm -rf node_modules
$ npm cache clear
$ npm install
$ npm run dev

##### **JHipster Version(s)**

5.3.0

##### **JHipster configuration**

File:.yo-rc.json
Content:
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.github.tomj0101.contactlist"
    },
    "jhipsterVersion": "5.3.0",
    "applicationType": "monolith",
    "baseName": "contactlist",
    "packageName": "com.github.tomj0101.contactlist",
    "packageFolder": "com/github/tomj0101/contactlist",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "no",
    "enableHibernateCache": false,
    "websocket": false,
    "databaseType": "mongodb",
    "devDatabaseType": "mongodb",
    "prodDatabaseType": "mongodb",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "ZTcxZGI0Y2JhYjRhYzQ1MzI2YWI3MWY1YjY5ODhjNjRlNzJiMzk0NTY3Y2RjMTRiYmQ3NDdkMDMxMWExODA4MWNiNmY1YWRkMDY3Y2I1NDFjN2IxMzhhMDU3NjI0YWIxYmYzZjViOTM4NTE5ZWY4M2IyOTUyODc1MTcxYmU4ZDE=",
    "clientFramework": "react",
    "useSass": false,
    "clientPackageManager": "npm",
    "testFrameworks": [
      "gatling",
      "protractor"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": false
  }
}
##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

Contacts.json
{
    "fluentMethods": true,
    "clientRootFolder": "",
    "relationships": [],
    "fields": [
        {
            "fieldName": "firstName",
            "fieldType": "String",
            "fieldValidateRules": [
                "required",
                "minlength",
                "maxlength"
            ],
            "fieldValidateRulesMinlength": "1",
            "fieldValidateRulesMaxlength": "100"
        },
        {
            "fieldName": "lastName",
            "fieldType": "String"
        },
        {
            "fieldName": "email",
            "fieldType": "String",
            "fieldValidateRules": [
                "pattern"
            ],
            "fieldValidateRulesPattern": "^[a-zA-Z0-9]*$"
        },
        {
            "fieldName": "phoneNumber",
            "fieldType": "String"
        },
        {
            "fieldName": "callPrices",
            "fieldType": "Long"
        },
        {
            "fieldName": "device",
            "fieldType": "Device",
            "fieldValues": "WEB,DESKTOP,MOVIL,CONSOLE,API"
        },
        {
            "fieldName": "note",
            "fieldType": "byte[]",
            "fieldTypeBlobContent": "text"
        },
        {
            "fieldName": "photo",
            "fieldType": "byte[]",
            "fieldTypeBlobContent": "image"
        },
        {
            "fieldName": "attachment",
            "fieldType": "byte[]",
            "fieldTypeBlobContent": "any"
        },
        {
            "fieldName": "counter",
            "fieldType": "Integer"
        },
        {
            "fieldName": "createdDate",
            "fieldType": "ZonedDateTime"
        },
        {
            "fieldName": "status",
            "fieldType": "Boolean"
        }
    ],
    "dto": "no",
    "searchEngine": false,
    "service": "serviceImpl",
    "entityTableName": "contacts",
    "jpaMetamodelFiltering": false,
    "pagination": "pagination"
}

##### **Browsers and Operating System**

Browsers: Google Chromium - Version 68.0.3440.106 (Official Build) Built on Ubuntu
OS: Linux Ubuntu 18.04 (64-bit)

**Comment by deepu105** [comment]
Maybe its a good idea to deprecate the use of `yo jhipste:commands` and add
warning if someone uses that directly. I'll do this this weekend

Thanks & Regards,
Deepu

**Comment by tomj0101** [comment]
Hi @jdubois 
#1 - I removed npm folder fix this error, thanks.
#2 - This project is a sample, is not my real prod public package name, JWT secret key, but thank for the advice.!

Hi @deepu105 I install jhipster with yarn in my laptop with Ubuntu 18.04 but I won't be available to run just `jhipster` for this reason I run `yo jhipster`, but this is my bad, I need to fix my environment problem.

Thanks, for the quick and fast response!


-Tomas Jimenez

**Comment by pascalgrimaud** [comment]
@tomj0101 : about jhipster with yarn, can you have a look at https://www.jhipster.tech/installation/

> If you have problems using Yarn globally, be sure to have $HOME/.config/yarn/global/node_modules/.bin in your path.

> On Mac or Linux: export PATH="$PATH:`yarn global bin`:$HOME/.config/yarn/global/node_modules/.bin"

**Comment by tomj0101** [comment]
@pascalgrimaud  excellent, I followed the installation step for Linux, and my generator work running  `jhipster` without the need to use `yo jhipster`. thanks, everyone !
