### ISSUE TITLE
Error creating microservice project in 5.3.0

### ISSUE THREAD

**Issue by DanielFran** [jhipster/generator-jhipster#8216]
##### **Reproduce the error**

$ jhipster
Using JHipster version installed globally
Running default command
Executing jhipster:app
Options: 

        ██╗ ██╗   ██╗ ████████╗ ███████╗   ██████╗ ████████╗ ████████╗ ███████╗
        ██║ ██║   ██║ ╚══██╔══╝ ██╔═══██╗ ██╔════╝ ╚══██╔══╝ ██╔═════╝ ██╔═══██╗
        ██║ ████████║    ██║    ███████╔╝ ╚█████╗     ██║    ██████╗   ███████╔╝
  ██╗   ██║ ██╔═══██║    ██║    ██╔════╝   ╚═══██╗    ██║    ██╔═══╝   ██╔══██║
  ╚██████╔╝ ██║   ██║ ████████╗ ██║       ██████╔╝    ██║    ████████╗ ██║  ╚██╗
   ╚═════╝  ╚═╝   ╚═╝ ╚═══════╝ ╚═╝       ╚═════╝     ╚═╝    ╚═══════╝ ╚═╝   ╚═╝

                            https://www.jhipster.tech

Welcome to JHipster v5.3.0
Application files will be generated in folder: /home/dev/workspace/jhipster/test 5.3.0
 _______________________________________________________________________________________________________________

  Documentation for creating an application is at https://www.jhipster.tech/creating-an-app/
  If you find JHipster useful, consider sponsoring the project at https://opencollective.com/generator-jhipster
 _______________________________________________________________________________________________________________

? Which *type* of application would you like to create? Microservice application

? What is the base name of your application? jhipster
? As you are running in a microservice architecture, on which port would like yo
ur server to run? It should be unique to avoid port conflicts. 8081
? What is your default Java package name? com.mycompany.myapp
? Which service discovery server do you want to use? No service discovery
? Which *type* of authentication would you like to use? JWT authentication (stat
eless, with a token)
? Which *type* of database would you like to use? SQL (H2, MySQL, MariaDB, Postg
reSQL, Oracle, MSSQL)
? Which *production* database would you like to use? PostgreSQL
? Which *development* database would you like to use? H2 with in-memory persistence
? Do you want to use the Spring cache abstraction? No - Warning, when using an SQL database, this will disable the Hibernate 2nd level cache!
? Would you like to use Maven or Gradle for building the backend? Maven
? Which other technologies would you like to use? 
? Would you like to enable internationalization support? No
? Besides JUnit and Jest, which testing frameworks would you like to use? 
? Would you like to install other generators from the JHipster Marketplace? No
/bin/sh: keytool: command not found
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: ERROR! 
Failed to create a KeyStore with 'keytool'
    at Environment.error (/usr/lib/node_modules/generator-jhipster/node_modules/yeoman-environment/lib/environment.js:157:40)
    at module.exports.error (/usr/lib/node_modules/generator-jhipster/generators/generator-base.js:2058:18)
    at shelljs.exec (/usr/lib/node_modules/generator-jhipster/generators/generator-base.js:2118:30)
    at /usr/lib/node_modules/generator-jhipster/node_modules/shelljs/src/exec.js:124:9
    at ChildProcess.exithandler (child_process.js:282:5)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Socket.stream.socket.on (internal/child_process.js:346:11)
    at emitOne (events.js:116:13)
##### **JHipster Version(s)**

$ jhipster info
Using JHipster version installed globally
Executing jhipster:info
Options: 
Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
/home/dev/workspace/jhipster/test 5.3.0
└── (empty)

```

cat: no such file or directory: .yo-rc.json

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_152"
Java(TM) SE Runtime Environment (build 1.8.0_152-b16)
Java HotSpot(TM) 64-Bit Server VM (build 25.152-b16, mixed mode)

git version 1.8.3.1

node: v8.11.1

npm: 5.6.0

yeoman: 2.0.1

Docker version 17.12.0-ce, build c97c6d6

docker-compose version 1.9.0, build 2585387

Congratulations, JHipster execution is complete!

##### **Browsers and Operating System**

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by jdubois** [comment]
Oh that's because we are now trying to generate a self-signed certificate for you, this is not just for microservices.

Then keytool should be installed with Java, and as we test Java before running the generator that should be fine - there's something not good here, and we should indeed ignore the error (no certificate for you, but no big deal...).

cc @PierreBesson as he works on this.

**Comment by pascalgrimaud** [comment]
it concerns all projects and all configuration, when no keytool found -> I renamed the title

**Comment by DanielFran** [comment]
@jdubois Will you make soon a 5.3.1 due to this blocking issue?

**Comment by PierreBesson** [comment]
Yes it is a blocker for a minority of poeple but it takes a long time to make a release so I'm against doing the release so soon.

**Comment by jdubois** [comment]
Oh I could do one tomorrow, we also have an issue with Heroku but I'm waiting a little bit for some feedback from their team (as discussed with @jkutner privately)

**Comment by pascalgrimaud** [comment]
Another blocking issue: Gradle is broken with NoSQL database. See my fix: https://github.com/jhipster/generator-jhipster/pull/8212

**Comment by DanielFran** [comment]
@jdubois And it seems that in jhipster-core project it was missing some changes with jwt, and new project created with jdl keep creating key with short size.
https://github.com/jhipster/jhipster-core/pull/253

**Comment by jdubois** [comment]
Indeed I have something similar with JHipster Online, cc @MathieuAA
