### ISSUE TITLE
Uploading an image bigger than 65,535 bytes causes SQLException

### ISSUE THREAD

**Issue by amatosg** [jhipster/generator-jhipster#8274]
##### **Overview of the issue**

Entity created through JDL. Field is `ImageBlog` which creates column type `blob`. The max size for a blob column is `65,535` bytes. If I upload a file bigger than that, it causes an exception:

<details>
<summary>SQLException</summary>
<pre>
Caused by: java.sql.SQLException: Data too long for column 'avatar' at row 1
Query is: insert into test_entity (avatar, avatar_content_type) values (?, ?), parameters [ bytearray:����JFIF��
                                                                                                                XICC_PROFILE
                                                                                                                            HLinomntrRGB XYZ �	1acspMSFTIEC sRGB���-HP  cprtP3desc�lwtpt�bkptrXYZgXYZ,bXYZ@dmndTpdmdd��vuedL�view�$lumi�meas
                                                                     $tech0
                                                                           rTRC<
                                                                               gTRC<
                                                                                   bTRC<
                                                                                       textCopyright (c) 1998 Hewlett-Packard CompanydescsRGB IEC61966-2.1sRGB IEC61966-2.1XYZ �Q�XYZ XYZ o�8��XYZ b����XYZ $����descIEC http://www.iec.chIEC http://www.iec.chdesc.IEC 61966-2.1 Default RGB colour space - sRGB.IEC 61966-2.1 Default RGB colour space - sRGBdesc,Reference Viewing Condition in IEC6...
	at org.mariadb.jdbc.internal.util.LogQueryTool.exceptionWithQuery(LogQueryTool.java:153)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executePreparedQuery(AbstractQueryProtocol.java:972)
	at org.mariadb.jdbc.MariaDbPreparedStatementServer.executeInternal(MariaDbPreparedStatementServer.java:376)
	... 197 common frames omitted

2018-09-11 00:06:01.764  WARN 22705 --- [  XNIO-2 task-7] .m.m.a.ExceptionHandlerExceptionResolver : Resolved exception caused by Handler execution: org.springframework.dao.DataIntegrityViolationException: could not execute statement; SQL [n/a]; nested exception is org.hibernate.exception.DataException: could not execute statement
</pre>
</details>

In the front end it only shows `Internal Server Error` and entity cannot be saved.

##### **Motivation for or Use Case**

User should get a reason why the entity is not being saved.

##### **Reproduce the error**

Generate Entity with a field ImageBlog
Create an entity and add a file bigger that 65535 bytes.

##### **Related issues**

Searched, but none found.

##### **Suggest a Fix**

There could be 3 solutions:
1. Change from blob (67kb) to mediumblob (16mb). This could increase the db size, but there could also be a configuration to set the max size allowed, like 1, 5, 10, 15MB. Again, this could be configured in JDL, something lile `avatar ImageBlob 5M`
2. Resize the image on the fly just before uploading to < 65KB.
3. Raise an error indicating that the file must be smaller than 65kb (I think this is too small)

##### **JHipster Version(s)**

```
test@0.0.0 /Users/alejandro/IdeaProjects/test
└── generator-jhipster@5.3.1

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.tester.testering",
      "nativeLanguage": "es"
    },
    "jhipsterVersion": "5.3.1",
    "applicationType": "monolith",
    "baseName": "test",
    "packageName": "com.tester.testering",
    "packageFolder": "com/tester/testering",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "mariadb",
    "prodDatabaseType": "mariadb",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": "eureka",
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "bXktc2VjcmV0LXRva2VuLXRvLWNoYW5nZS1pbi1wcm9kdWN0aW9uLWFuZC10by1rZWVwLWluLWEtc2VjdXJlLXBsYWNl",
    "clientFramework": "angularX",
    "useSass": true,
    "clientPackageManager": "npm",
    "testFrameworks": [
      "gatling"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "es",
    "languages": [
      "es"
    ]
  }
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity TestEntity {
  avatar ImageBlob
}

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_181"
Java(TM) SE Runtime Environment (build 1.8.0_181-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.181-b13, mixed mode)

git version 2.16.2

node: v8.11.3

npm: 6.4.1

yeoman: 2.0.5

Docker version 18.06.1-ce, build e68fc7a

docker-compose version 1.22.0, build f46880f
##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>TestEntity</summary>
<pre>
{
    "name": "TestEntity",
    "fields": [
        {
            "fieldName": "avatar",
            "fieldType": "byte[]",
            "fieldTypeBlobContent": "image"
        }
    ],
    "relationships": [],
    "changelogDate": "20180911045959",
    "entityTableName": "test_entity",
    "dto": "no",
    "pagination": "no",
    "service": "no",
    "jpaMetamodelFiltering": false,
    "fluentMethods": true,
    "clientRootFolder": "",
    "applications": "*"
}
</pre>
</details>

##### **Browsers and Operating System**

macOS & Chrome, but it's irrelevant.

- [X] Checking this box is mandatory (this is just to show you read everything)

**Comment by ruddell** [comment]
`mariadb` needs to be added to [this condition](https://github.com/jhipster/generator-jhipster/blob/6aaac5aaedf6a50f1ef1cd65329603728c8ce0ef/generators/entity-server/templates/src/main/resources/config/liquibase/changelog/added_entity.xml.ejs#L93) in the entity liquibase xml file

**Comment by amatosg** [comment]
should I just merge the pull request? Or wait for a team member?

**Comment by ruddell** [comment]
The pull request should be opened on this repository, it's currently open on your fork

**Comment by amatosg** [comment]
yes, what I mean is that the PR has the "merge" button available but I don't know what's the policy for PRs, should I just merge it myself? or it has to be approved by a team member?

**Comment by ruddell** [comment]
Your pull request is on `amatosg/generator-jhipster` when it needs to be on the `jhipster/generator-jhipster` repository.  If you merge your PR it only goes onto your master branch and not here

You can go here to open it on the correct repository: https://github.com/jhipster/generator-jhipster/compare/master...amatosg:fix-mariadb-blob

**Comment by amatosg** [comment]
> Your pull request is on `amatosg/generator-jhipster` when it needs to be on the `jhipster/generator-jhipster` repository. If you merge your PR it only goes onto your master branch and not here
> 
> You can go here to open it on the correct repository: [master...amatosg:fix-mariadb-blob](https://github.com/jhipster/generator-jhipster/compare/master...amatosg:fix-mariadb-blob)

thank you, I'm unfamiliar with github
