### ISSUE TITLE
UserServiceIntTest fails in microservice with OAuth 2.0

### ISSUE THREAD

**Issue by mraible** [jhipster/generator-jhipster#8313]
##### **Overview of the issue**

I created a microservice with OAuth 2.0 and MongoDB and `UserServiceIntTest.assertThatUserLocaleIsCorrectlySetFromAuthenticationDetails()` fails when I run `mvn test`.

```
[INFO] Scanning for projects...
[INFO] 
[INFO] -------------------< com.okta.developer.store:store >-------------------
[INFO] Building Store 0.0.1-SNAPSHOT
[INFO] --------------------------------[ war ]---------------------------------
[INFO] 
[INFO] --- maven-resources-plugin:3.1.0:copy-resources (default-resources) @ store ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 6 resources
[INFO] Copying 7 resources
[INFO] 
[INFO] --- maven-resources-plugin:3.1.0:resources (default-resources) @ store ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 6 resources
[INFO] Copying 7 resources
[INFO] 
[INFO] --- maven-enforcer-plugin:3.0.0-M2:enforce (enforce-versions) @ store ---
[INFO] 
[INFO] --- maven-resources-plugin:3.1.0:copy-resources (docker-resources) @ store ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 6 resources
[INFO] 
[INFO] --- jacoco-maven-plugin:0.8.2:prepare-agent (pre-unit-tests) @ store ---
[INFO] argLine set to -javaagent:/Users/mraible/.m2/repository/org/jacoco/org.jacoco.agent/0.8.2/org.jacoco.agent-0.8.2-runtime.jar=destfile=/Users/mraible/apps/store/target/test-results/coverage/jacoco/jacoco.exec -Djava.security.egd=file:/dev/./urandom -Xmx256m
[INFO] 
[INFO] --- maven-compiler-plugin:3.7.0:compile (default-compile) @ store ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 79 source files to /Users/mraible/apps/store/target/classes
[INFO] /Users/mraible/apps/store/src/main/java/com/okta/developer/store/security/oauth2/SimpleAuthoritiesExtractor.java: /Users/mraible/apps/store/src/main/java/com/okta/developer/store/security/oauth2/SimpleAuthoritiesExtractor.java uses unchecked or unsafe operations.
[INFO] /Users/mraible/apps/store/src/main/java/com/okta/developer/store/security/oauth2/SimpleAuthoritiesExtractor.java: Recompile with -Xlint:unchecked for details.
[INFO] 
[INFO] --- maven-resources-plugin:3.1.0:testResources (default-testResources) @ store ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 3 resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.7.0:testCompile (default-testCompile) @ store ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 15 source files to /Users/mraible/apps/store/target/test-classes
[INFO] 
[INFO] --- maven-surefire-plugin:2.22.0:test (default-test) @ store ---
[INFO] 
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running com.okta.developer.store.service.UserServiceIntTest

        ██╗ ██╗   ██╗ ████████╗ ███████╗   ██████╗ ████████╗ ████████╗ ███████╗
        ██║ ██║   ██║ ╚══██╔══╝ ██╔═══██╗ ██╔════╝ ╚══██╔══╝ ██╔═════╝ ██╔═══██╗
        ██║ ████████║    ██║    ███████╔╝ ╚█████╗     ██║    ██████╗   ███████╔╝
  ██╗   ██║ ██╔═══██║    ██║    ██╔════╝   ╚═══██╗    ██║    ██╔═══╝   ██╔══██║
  ╚██████╔╝ ██║   ██║ ████████╗ ██║       ██████╔╝    ██║    ████████╗ ██║  ╚██╗
   ╚═════╝  ╚═╝   ╚═╝ ╚═══════╝ ╚═╝       ╚═════╝     ╚═╝    ╚═══════╝ ╚═╝   ╚═╝

:: JHipster 🤓  :: Running Spring Boot 2.0.4.RELEASE ::
:: https://www.jhipster.tech ::

2018-09-13 12:00:34.130  INFO 86449 --- [           main] c.o.d.store.config.MetricsConfiguration  : Initializing Metrics Log reporting
2018-09-13 12:00:37.316  WARN 86449 --- [           main] c.o.d.store.config.CacheConfiguration    : No discovery service is set up, Hazelcast cannot create a cluster.
2018-09-13 12:00:38.771  WARN 86449 --- [           main] com.hazelcast.instance.Node              : [10.130.0.63]:5701 [dev] [3.9.4] No join method is enabled! Starting standalone.
2018-09-13 12:00:40.457  WARN 86449 --- [           main] c.n.c.sources.URLConfigurationSource     : No URLs will be polled as dynamic configuration sources.
2018-09-13 12:00:40.467  WARN 86449 --- [           main] c.n.c.sources.URLConfigurationSource     : No URLs will be polled as dynamic configuration sources.
2018-09-13 12:00:49.488  INFO 86449 --- [           main] c.o.d.store.config.LoggingConfiguration  : Initializing Logstash logging
2018-09-13 12:00:49.561  INFO 86449 --- [           main] c.o.d.store.config.LoggingConfiguration  : Filtering metrics logs from all appenders except the LOGSTASH appender
[ERROR] Tests run: 2, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 21.249 s <<< FAILURE! - in com.okta.developer.store.service.UserServiceIntTest
[ERROR] assertThatUserLocaleIsCorrectlySetFromAuthenticationDetails(com.okta.developer.store.service.UserServiceIntTest)  Time elapsed: 0.1 s  <<< ERROR!
org.springframework.dao.IncorrectResultSizeDataAccessException: Query { "$java" : Query: { "login" : "anonymoususer" }, Fields: { }, Sort: { } } returned non unique result.
	at com.okta.developer.store.service.UserServiceIntTest.assertThatUserLocaleIsCorrectlySetFromAuthenticationDetails(UserServiceIntTest.java:116)

2018-09-13 12:00:50.808  INFO 86449 --- [      Thread-14] c.o.d.store.config.CacheConfiguration    : Closing Cache Manager
[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Errors: 
[ERROR]   UserServiceIntTest.assertThatUserLocaleIsCorrectlySetFromAuthenticationDetails:116 » IncorrectResultSizeDataAccess
[INFO] 
[ERROR] Tests run: 2, Failures: 0, Errors: 1, Skipped: 0
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 28.193 s
[INFO] Finished at: 2018-09-13T12:00:51+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.22.0:test (default-test) on project store: There are test failures.
[ERROR] 
[ERROR] Please refer to /Users/mraible/apps/store/target/surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date]-jvmRun[N].dump, [date].dumpstream and [date]-jvmRun[N].dumpstream.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

```

##### **Motivation for or Use Case**

All tests should pass after creating a new app.

##### **Reproduce the error**

Create a microservices app with OAuth 2.0, MongoDB, and Elasticsearch, then run `mvn test`.

##### **JHipster Version(s)**

master branch

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.okta.developer.store",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "5.3.1",
    "applicationType": "microservice",
    "baseName": "store",
    "packageName": "com.okta.developer.store",
    "packageFolder": "com/okta/developer/store",
    "serverPort": "8082",
    "authenticationType": "oauth2",
    "cacheProvider": "hazelcast",
    "enableHibernateCache": false,
    "websocket": false,
    "databaseType": "mongodb",
    "devDatabaseType": "mongodb",
    "prodDatabaseType": "mongodb",
    "searchEngine": "elasticsearch",
    "messageBroker": false,
    "serviceDiscoveryType": "eureka",
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "bXktc2VjcmV0LXRva2VuLXRvLWNoYW5nZS1pbi1wcm9kdWN0aW9uLWFuZC10by1rZWVwLWluLWEtc2VjdXJlLXBsYWNl",
    "enableTranslation": true,
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "clientPackageManager": "npm",
    "nativeLanguage": "en",
    "languages": [
      "en"
    ],
    "skipClient": true,
    "skipUserManagement": true
  }
}
</pre>
</details>

NOTE: the rest of `jhipster info` fails with the following error message:

```
##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

The passed validation must be valid to be added to the field.
Errors: No value
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: ERROR!
Error while parsing entities to JDL

    at Environment.error (/Users/mraible/dev/generator-jhipster/node_modules/yeoman-environment/lib/environment.js:157:40)
    at module.exports.error (/Users/mraible/dev/generator-jhipster/generators/generator-base.js:2058:18)
    at module.exports.generateJDLFromEntities (/Users/mraible/dev/generator-jhipster/generators/generator-base-private.js:1003:18)
    at module.exports.displayEntities (/Users/mraible/dev/generator-jhipster/generators/info/index.js:57:34)
    at Object.<anonymous> (/Users/mraible/dev/generator-jhipster/node_modules/yeoman-generator/lib/index.js:418:27)
    at /Users/mraible/dev/generator-jhipster/node_modules/run-async/index.js:25:25
    at new Promise (<anonymous>)
    at /Users/mraible/dev/generator-jhipster/node_modules/run-async/index.js:24:19
    at self.env.runLoop.add.completed (/Users/mraible/dev/generator-jhipster/node_modules/yeoman-generator/lib/index.js:419:13)
    at runCallback (timers.js:810:20)
Execution time: 3 s.
```

My `.jhipster` directory contains a `Product.json`:

```json
{
    "fluentMethods": true,
    "clientRootFolder": "store",
    "relationships": [],
    "fields": [
        {
            "fieldName": "name",
            "fieldType": "String",
            "fieldValidateRules": [
                "required"
            ]
        },
        {
            "fieldName": "price",
            "fieldType": "Double",
            "fieldValidateRules": [
                "required",
                "min"
            ],
            "fieldValidateRulesMin": 0
        },
        {
            "fieldName": "image",
            "fieldType": "byte[]",
            "fieldTypeBlobContent": "image"
        }
    ],
    "dto": "no",
    "searchEngine": "elasticsearch",
    "service": "no",
    "entityTableName": "product",
    "jpaMetamodelFiltering": false,
    "pagination": "pagination",
    "microserviceName": "store"
}
```

**Comment by deepu105** [comment]
@MathieuAA seems like export JDL is failing for some cases. I also noticed it recently

**Comment by pascalgrimaud** [comment]
I reopen this ticket as it is not fixed.
See https://travis-ci.org/hipster-labs/jhipster-travis-build/branches

@deepu105 : can you check the statut about bounty on this ticket as you added and removed it.

Here my jhipster info:

➜ jhinfo  
Using JHipster version installed locally in current project's node_modules
Executing jhipster:info
Options: from-cli: true
Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
travis-microservice-eureka@0.0.0 /home/pgrimaud/tmp/23-oauth2
└── generator-jhipster@5.3.4 

```


##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**


<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "applicationType": "microservice",
    "baseName": "travisMicroserviceEureka",
    "packageName": "io.github.jhipster.travis",
    "packageFolder": "io/github/jhipster/travis",
    "authenticationType": "oauth2",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "serviceDiscoveryType": "eureka",
    "buildTool": "maven",
    "jwtSecretKey": "bXktc2VjcmV0LXRva2VuLXRvLWNoYW5nZS1pbi1wcm9kdWN0aW9uLWFuZC10by1rZWVwLWluLWEtc2VjdXJlLXBsYWNl",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en",
      "fr"
    ],
    "testFrameworks": [
      "gatling",
      "protractor"
    ],
    "skipClient": true,
    "skipUserManagement": true,
    "serverPort": "8081",
    "jhiPrefix": "jhi",
    "travis": true,
    "websocket": false,
    "messageBroker": false,
    "clientFramework": "angular1",
    "clientPackageManager": "npm",
    "jhipsterVersion": "5.3.4"
  }
}
</pre>
</details>


##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>


##### **Environment and Tools**

openjdk version "1.8.0_181"
OpenJDK Runtime Environment (build 1.8.0_181-8u181-b13-0ubuntu0.18.04.1-b13)
OpenJDK 64-Bit Server VM (build 25.181-b13, mixed mode)

git version 2.19.0

node: v8.12.0

npm: 6.4.1

yeoman: 2.0.5

yarn: 1.10.1

Docker version 18.03.0-ce, build 0520e24

docker-compose version 1.21.2, build a133471

Congratulations, JHipster execution is complete!

**Comment by jdubois** [comment]
I'm fixing this
