### ISSUE TITLE
Swagger UI doesnt work on Gateways and Registry for microservices

### ISSUE THREAD

**Issue by deepu105** [jhipster/generator-jhipster#8328]
Issue separated from https://github.com/jhipster/generator-jhipster/issues/8301 see #8301 for details

**Comment by jsm174** [comment]
For research:

I created a dummy microservice `token`. I turned on zuul debugging: `central-server-config/application.yml`:

```
logging:
    level:
         org:
             springframework:
                  cloud:
                       netflix:
                           zuul: debug
```

In the browser, when accessing the service via the gateway's swagger UI for the first time, it errors within a few seconds:

`504 : {"timestamp":"2018-09-17T20:47:25.841+0000","status":504,"error":"Gateway Timeout","message":"com.netflix.zuul.exception.ZuulException: Hystrix Readed time out"} http://localhost:8080/token/v2/api-docs`

All future accesses immediately return:

`Can't read from server. It may not have the appropriate access-control-origin settings.`

I also tried to bump up the hystrix timeout in `central-server-config/application.yml`:

```
hystrix:
    command:
        default:
            execution:
                isolation:
                    thread:
                        timeoutInMilliseconds: 60000
```

The only place I could find that time out message is at:

https://github.com/spring-cloud/spring-cloud-netflix/blob/master/spring-cloud-netflix-zuul/src/main/java/org/springframework/cloud/netflix/zuul/filters/post/SendErrorFilter.java#L114

Here is the tail of `docker-compose`:

```
gateway-app_1             | 2018-09-17 20:47:24.505 DEBUG 1 --- [ XNIO-2 task-30] o.s.c.n.zuul.filters.SimpleRouteLocator  : route matched=ZuulRoute{id='token', path='/token/**', serviceId='token', url='null', stripPrefix=true, retryable=null, sensitiveHeaders=[], customSensitiveHeaders=false, }
gateway-app_1             | 2018-09-17 20:47:24.505 DEBUG 1 --- [ XNIO-2 task-30] o.s.c.n.zuul.web.ZuulHandlerMapping      : Matching patterns for request [/token/v2/api-docs] are [/token/**]
gateway-app_1             | 2018-09-17 20:47:24.506 DEBUG 1 --- [ XNIO-2 task-30] o.s.c.n.zuul.web.ZuulHandlerMapping      : URI Template variables for request [/token/v2/api-docs] are {}
gateway-app_1             | 2018-09-17 20:47:24.506 DEBUG 1 --- [ XNIO-2 task-30] o.s.c.n.zuul.web.ZuulHandlerMapping      : Mapping [/token/v2/api-docs] to HandlerExecutionChain with handler [org.springframework.cloud.netflix.zuul.web.ZuulController@4f379769] and 1 interceptor
gateway-app_1             | 2018-09-17 20:47:24.510 DEBUG 1 --- [ XNIO-2 task-30] o.s.c.n.zuul.web.ZuulHandlerMapping      : Matching patterns for request [/token/v2/api-docs] are [/token/**]
gateway-app_1             | 2018-09-17 20:47:24.510 DEBUG 1 --- [ XNIO-2 task-30] o.s.c.n.zuul.web.ZuulHandlerMapping      : URI Template variables for request [/token/v2/api-docs] are {}
gateway-app_1             | 2018-09-17 20:47:24.510 DEBUG 1 --- [ XNIO-2 task-30] o.s.c.n.zuul.web.ZuulHandlerMapping      : Mapping [/token/v2/api-docs] to HandlerExecutionChain with handler [org.springframework.cloud.netflix.zuul.web.ZuulController@4f379769] and 1 interceptor
gateway-app_1             | 2018-09-17 20:47:24.511 DEBUG 1 --- [ XNIO-2 task-30] o.s.c.n.zuul.filters.SimpleRouteLocator  : route matched=ZuulRoute{id='reservation', path='/reservation/**', serviceId='reservation', url='null', stripPrefix=true, retryable=null, sensitiveHeaders=[], customSensitiveHeaders=false, }
gateway-app_1             | 2018-09-17 20:47:24.512 DEBUG 1 --- [ XNIO-2 task-30] o.s.c.n.zuul.filters.SimpleRouteLocator  : route matched=ZuulRoute{id='token', path='/token/**', serviceId='token', url='null', stripPrefix=true, retryable=null, sensitiveHeaders=[], customSensitiveHeaders=false, }
gateway-app_1             | 2018-09-17 20:47:24.512 DEBUG 1 --- [ XNIO-2 task-30] o.s.c.n.zuul.filters.SimpleRouteLocator  : Finding route for path: /token/v2/api-docs
gateway-app_1             | 2018-09-17 20:47:24.513 DEBUG 1 --- [ XNIO-2 task-30] o.s.c.n.zuul.filters.SimpleRouteLocator  : servletPath=/
gateway-app_1             | 2018-09-17 20:47:24.513 DEBUG 1 --- [ XNIO-2 task-30] o.s.c.n.zuul.filters.SimpleRouteLocator  : zuulServletPath=/zuul
gateway-app_1             | 2018-09-17 20:47:24.514 DEBUG 1 --- [ XNIO-2 task-30] o.s.c.n.zuul.filters.SimpleRouteLocator  : RequestUtils.isDispatcherServletRequest()=true
gateway-app_1             | 2018-09-17 20:47:24.514 DEBUG 1 --- [ XNIO-2 task-30] o.s.c.n.zuul.filters.SimpleRouteLocator  : RequestUtils.isZuulServletRequest()=false
gateway-app_1             | 2018-09-17 20:47:24.515 DEBUG 1 --- [ XNIO-2 task-30] o.s.c.n.zuul.filters.SimpleRouteLocator  : adjustedPath=/token/v2/api-docs
gateway-app_1             | 2018-09-17 20:47:24.515 DEBUG 1 --- [ XNIO-2 task-30] o.s.c.n.zuul.filters.SimpleRouteLocator  : Matching pattern:/reservation/**
gateway-app_1             | 2018-09-17 20:47:24.515 DEBUG 1 --- [ XNIO-2 task-30] o.s.c.n.zuul.filters.SimpleRouteLocator  : Matching pattern:/token/**
gateway-app_1             | 2018-09-17 20:47:24.516 DEBUG 1 --- [ XNIO-2 task-30] o.s.c.n.zuul.filters.SimpleRouteLocator  : route matched=ZuulRoute{id='token', path='/token/**', serviceId='token', url='null', stripPrefix=true, retryable=null, sensitiveHeaders=[], customSensitiveHeaders=false, }
gateway-app_1             | 2018-09-17 20:47:25.834  WARN 1 --- [ XNIO-2 task-30] o.s.c.n.z.filters.post.SendErrorFilter   : Error during filtering
gateway-app_1             |
gateway-app_1             | com.netflix.zuul.exception.ZuulException:
gateway-app_1             | 	at org.springframework.cloud.netflix.zuul.filters.post.SendErrorFilter.findZuulException(SendErrorFilter.java:114)
gateway-app_1             | 	at org.springframework.cloud.netflix.zuul.filters.post.SendErrorFilter.run(SendErrorFilter.java:76)
gateway-app_1             | 	at com.netflix.zuul.ZuulFilter.runFilter(ZuulFilter.java:117)
gateway-app_1             | 	at com.netflix.zuul.FilterProcessor.processZuulFilter(FilterProcessor.java:193)
gateway-app_1             | 	at com.netflix.zuul.FilterProcessor.runFilters(FilterProcessor.java:157)
gateway-app_1             | 	at com.netflix.zuul.FilterProcessor.error(FilterProcessor.java:105)
gateway-app_1             | 	at com.netflix.zuul.ZuulRunner.error(ZuulRunner.java:112)
gateway-app_1             | 	at com.netflix.zuul.http.ZuulServlet.error(ZuulServlet.java:145)
gateway-app_1             | 	at com.netflix.zuul.http.ZuulServlet.service(ZuulServlet.java:83)
gateway-app_1             | 	at org.springframework.web.servlet.mvc.ServletWrappingController.handleRequestInternal(ServletWrappingController.java:165)
gateway-app_1             | 	at org.springframework.cloud.netflix.zuul.web.ZuulController.handleRequest(ZuulController.java:44)
gateway-app_1             | 	at org.springframework.web.servlet.mvc.SimpleControllerHandlerAdapter.handle(SimpleControllerHandlerAdapter.java:52)
gateway-app_1             | 	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:991)
gateway-app_1             | 	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:925)
gateway-app_1             | 	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:974)
gateway-app_1             | 	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:866)
gateway-app_1             | 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
gateway-app_1             | 	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:851)
gateway-app_1             | 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
gateway-app_1             | 	at io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:74)
gateway-app_1             | 	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:129)
gateway-app_1             | 	at com.codahale.metrics.servlet.AbstractInstrumentedFilter.doFilter(AbstractInstrumentedFilter.java:111)
gateway-app_1             | 	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
gateway-app_1             | 	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
gateway-app_1             | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:101)
gateway-app_1             | 	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
gateway-app_1             | 	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
gateway-app_1             | 	at org.springframework.boot.actuate.web.trace.servlet.HttpTraceFilter.doFilterInternal(HttpTraceFilter.java:90)
gateway-app_1             | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
gateway-app_1             | 	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
gateway-app_1             | 	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
gateway-app_1             | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:320)
gateway-app_1             | 	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:127)
gateway-app_1             | 	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:91)
gateway-app_1             | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
gateway-app_1             | 	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:119)
gateway-app_1             | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
gateway-app_1             | 	at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:137)
gateway-app_1             | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
gateway-app_1             | 	at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:111)
gateway-app_1             | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
gateway-app_1             | 	at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:170)
gateway-app_1             | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
gateway-app_1             | 	at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:63)
gateway-app_1             | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
gateway-app_1             | 	at com.optimoit.ia.gateway.security.jwt.JWTFilter.doFilter(JWTFilter.java:38)
gateway-app_1             | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
gateway-app_1             | 	at org.springframework.web.filter.CorsFilter.doFilterInternal(CorsFilter.java:96)
gateway-app_1             | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
gateway-app_1             | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
gateway-app_1             | 	at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:116)
gateway-app_1             | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
gateway-app_1             | 	at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:66)
gateway-app_1             | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
gateway-app_1             | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
gateway-app_1             | 	at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:105)
gateway-app_1             | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
gateway-app_1             | 	at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:56)
gateway-app_1             | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
gateway-app_1             | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
gateway-app_1             | 	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:215)
gateway-app_1             | 	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:178)
gateway-app_1             | 	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:357)
gateway-app_1             | 	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:270)
gateway-app_1             | 	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
gateway-app_1             | 	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
gateway-app_1             | 	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99)
gateway-app_1             | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
gateway-app_1             | 	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
gateway-app_1             | 	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
gateway-app_1             | 	at org.springframework.web.filter.HttpPutFormContentFilter.doFilterInternal(HttpPutFormContentFilter.java:109)
gateway-app_1             | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
gateway-app_1             | 	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
gateway-app_1             | 	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
gateway-app_1             | 	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:93)
gateway-app_1             | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
gateway-app_1             | 	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
gateway-app_1             | 	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
gateway-app_1             | 	at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.filterAndRecordMetrics(WebMvcMetricsFilter.java:155)
gateway-app_1             | 	at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.filterAndRecordMetrics(WebMvcMetricsFilter.java:123)
gateway-app_1             | 	at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:108)
gateway-app_1             | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
gateway-app_1             | 	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
gateway-app_1             | 	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
gateway-app_1             | 	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:200)
gateway-app_1             | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
gateway-app_1             | 	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
gateway-app_1             | 	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
gateway-app_1             | 	at io.undertow.servlet.handlers.FilterHandler.handleRequest(FilterHandler.java:84)
gateway-app_1             | 	at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62)
gateway-app_1             | 	at io.undertow.servlet.handlers.ServletChain$1.handleRequest(ServletChain.java:64)
gateway-app_1             | 	at io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36)
gateway-app_1             | 	at io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:132)
gateway-app_1             | 	at io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57)
gateway-app_1             | 	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
gateway-app_1             | 	at io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46)
gateway-app_1             | 	at io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:64)
gateway-app_1             | 	at io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:60)
gateway-app_1             | 	at io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:77)
gateway-app_1             | 	at io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43)
gateway-app_1             | 	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
gateway-app_1             | 	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
gateway-app_1             | 	at io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:292)
gateway-app_1             | 	at io.undertow.servlet.handlers.ServletInitialHandler.access$100(ServletInitialHandler.java:81)
gateway-app_1             | 	at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:138)
gateway-app_1             | 	at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:135)
gateway-app_1             | 	at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:48)
gateway-app_1             | 	at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
gateway-app_1             | 	at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:272)
gateway-app_1             | 	at io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:81)
gateway-app_1             | 	at io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:104)
gateway-app_1             | 	at io.undertow.server.Connectors.executeRootHandler(Connectors.java:336)
gateway-app_1             | 	at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:830)
gateway-app_1             | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
gateway-app_1             | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
gateway-app_1             | 	at java.lang.Thread.run(Thread.java:748)
```

**Comment by PierreBesson** [comment]
Okay basically this seems to be a problem with the RewrittingFilter in prod mode (since the payload must be deziped and rezipped properly with Zuul and it seems that Zuul changed its  behavior in a newer version).

**Comment by TonyLuo** [comment]
have the same issue after upgrade from jhipster5.2.1 to jhipster5.3.4

**Comment by PierreBesson** [comment]
@TonyLuo Definitely it seems the problem is happening since we upgraded to Spring Cloud Finchley. Probably downgrading the gateway to Edgware is a temporary fix.

**Comment by TonyLuo** [comment]
it works in dev mode in local...
 the problem happens in prod mode after packaging and deploying to the server.

**Comment by TonyLuo** [comment]
@PierreBesson I try to downgrade the gateway ,but it doesn't work.
Could you pls advise how to downgrade the gateway as a  temporary fix? thanks

**Comment by pascalgrimaud** [comment]
@TonyLuo : downgrading Spring Cloud Finchley to use a previous version is a solution.

But after spending hours on this, I got the solution! I will PR soon to fix this

**Comment by TonyLuo** [comment]
well done ! 
I was struggling on this for days.....thanks so much.
 hope to see the update soon

**Comment by pascalgrimaud** [comment]
@TonyLuo : see the 2 related PR

**Comment by pascalgrimaud** [comment]
Some explainations.

I thought the problem comes from Docker with different network, because of "CORS" error message, but it was not. You could reproduce the issue by:
- cloning and starting the Registry (master branch)
- generate and start a microservice with prod profile (it works for dev)
- try to access to Swagger API in the Registry: you can't see the microservice

So it seems to be related to Swagger only in prod profile, because of the `compression`:

```yaml
server:
    port: 8080
    compression:
        enabled: true
        mime-types: text/html,text/xml,text/plain,text/css, application/javascript, application/json
min-response-size: 1024
```

A first solution is to test without the `compression` and it works!

So I saw that the `SwaggerBasePathRewritingFilter` was initially added by this PR https://github.com/jhipster/generator-jhipster/pull/3113 for fixing https://github.com/jhipster/generator-jhipster/issues/3046
This class was added 3 years ago and extends [SendResponseFilter](https://github.com/spring-cloud/spring-cloud-netflix/blob/2.0.x/spring-cloud-netflix-zuul/src/main/java/org/springframework/cloud/netflix/zuul/filters/post/SendResponseFilter.java) (from Zuul), including some method to handle GZip:
- https://github.com/jhipster/jhipster-sample-app-gateway/blob/master/src/main/java/io/github/jhipster/sample/gateway/responserewriting/SwaggerBasePathRewritingFilter.java#L53-L55
- https://github.com/jhipster/jhipster-sample-app-gateway/blob/master/src/main/java/io/github/jhipster/sample/gateway/responserewriting/SwaggerBasePathRewritingFilter.java#L67-L69

And as [SendResponseFilter](https://github.com/spring-cloud/spring-cloud-netflix/blob/2.0.x/spring-cloud-netflix-zuul/src/main/java/org/springframework/cloud/netflix/zuul/filters/post/SendResponseFilter.java) (from Zuul) has changed recently (see [history](https://github.com/spring-cloud/spring-cloud-netflix/commits/2.0.x/spring-cloud-netflix-zuul/src/main/java/org/springframework/cloud/netflix/zuul/filters/post/SendResponseFilter.java)), I tried to remove this class and it seems to work.

I let @PierreBesson having a look to my 2 PR.

**Comment by TonyLuo** [comment]
after disable the compression for the microservices, the swagger api json doc can be loaded in prod profile .
 but the basePath in  swagger ui is missing when try to do some testing
 
![image](https://user-images.githubusercontent.com/3250305/46211553-65650580-c366-11e8-95dc-d9fa653d56c0.png)

**Comment by pascalgrimaud** [comment]
@TonyLuo : can you try to remove the `SwaggerBasePathRewritingFilter.java` instead ? (and all related config / test classes)

**Comment by TonyLuo** [comment]
I have removed SwaggerBasePathRewritingFilter.java and try again, and the result is the same...
I tested it from gateway instead of jhipster-registry

**Comment by pascalgrimaud** [comment]
Strange ! Everything works fine for me, so I'm pretty sure we're not doing the same thing. See all my tests in my PR: https://github.com/jhipster/generator-jhipster/pull/8416

I will test it again and push my project to Github so you will be able to try !

**Comment by TonyLuo** [comment]
it works from jhipster-registry when test it in prod profile, but fail in gateway...
 i am sure I didn't change anything on swagger ui html and js, just tested it with the generated swagger code

**Comment by pascalgrimaud** [comment]
@TonyLuo : if you can push a sample project to Github, I can test on my side too

**Comment by TonyLuo** [comment]
i just tested it again, it works when the base path is ip address or localhost, but it doesn't work when the base path is domain name :(

**Comment by pascalgrimaud** [comment]
oh fine, now I understand why the base path must be kept, as @PierreBesson said

**Comment by TonyLuo** [comment]
in the nginx reverse proxy case, the base path in request url is missing  with/without SwaggerBasePathRewritingFilter.java

**Comment by pascalgrimaud** [comment]
I already saw the problem, when using nginx or httpd as reverse proxy -> we had this, when working for my previous customer with @PierreBesson
Not sure we can do something about that.

Just try another solution (which won't work with nginx) but should work in dev, prod, docker !
