### ISSUE TITLE
Error in maven production build

### ISSUE THREAD

**Issue by arabbani** [jhipster/generator-jhipster#8374]
##### **Overview of the issue**
I've recently upgraded to JHipster v5.3.4. The production build is producing the fillowing error:

```
[INFO]                                                                                                                                                                  
    [INFO] --- frontend-maven-plugin:1.6:npm (webpack build prod) @ fb-quiz ---                                                                                             
    [INFO] npm not inheriting proxy config from Maven                                                                                                                       
[INFO] Running 'npm run webpack:prod' in D:\Projects\arif\fb-quiz                                                                                                       
[INFO]                                                                                                                                                                  
[INFO] > fb-quiz@0.0.0 webpack:prod D:\Projects\arif\fb-quiz                                                                                                            
[INFO] > npm run cleanup && npm run webpack:prod:main && npm run clean-www                                                                                              
[INFO]                                                                                                                                                                  
[INFO]                                                                                                                                                                  
[INFO] > fb-quiz@0.0.0 cleanup D:\Projects\arif\fb-quiz                                                                                                                 
[INFO] > rimraf target/{aot,www}                                                                                                                                        
[INFO]                                                                                                                                                                  
[INFO]                                                                                                                                                                  
[INFO] > fb-quiz@0.0.0 webpack:prod:main D:\Projects\arif\fb-quiz                                                                                                       
[INFO] > npm run webpack -- --config webpack/webpack.prod.js --profile                                                                                                  
[INFO]                                                                                                                                                                  
[INFO]                                                                                                                                                                  
[INFO] > fb-quiz@0.0.0 webpack D:\Projects\arif\fb-quiz                                                                                                                 
[INFO] > node --max_old_space_size=4096 node_modules/webpack/bin/webpack.js "--config" "webpack/webpack.prod.js" "--profile"                                            
[INFO]                                                                                                                                                                  
[ERROR] (node:8620) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead                                                                   
[ERROR] Error: Parse error on line 1:                                                                                                                                   
[ERROR] (* 1.25) + 4px                                                                                                                                                  
[ERROR] -^                                                                                                                                                              
[ERROR] Expecting 'SUB', 'LPAREN', 'NESTED_CALC', 'NUMBER', 'CSS_VAR', 'LENGTH', 'ANGLE', 'TIME', 'FREQ', 'RES', 'EMS', 'EXS', 'CHS', 'REMS', 'VHS', 'VWS', 'VMINS', 'VM
AXS', 'PERCENTAGE', got 'MUL'                                                                                                                                           
[ERROR]     at Parser.parseError (D:\Projects\arif\fb-quiz\node_modules\cssnano-preset-default\node_modules\reduce-css-calc\dist\parser.js:160:21)                      
[ERROR]     at Parser.parse (D:\Projects\arif\fb-quiz\node_modules\cssnano-preset-default\node_modules\reduce-css-calc\dist\parser.js:226:22)                           
[ERROR]     at D:\Projects\arif\fb-quiz\node_modules\cssnano-preset-default\node_modules\reduce-css-calc\dist\index.js:35:30                                            
[ERROR]     at walk (D:\Projects\arif\fb-quiz\node_modules\postcss-value-parser\lib\walk.js:15:13)                                                                      
[ERROR]     at ValueParser.walk (D:\Projects\arif\fb-quiz\node_modules\postcss-value-parser\lib\index.js:18:5)                                                          
[ERROR]     at exports.default (D:\Projects\arif\fb-quiz\node_modules\cssnano-preset-default\node_modules\reduce-css-calc\dist\index.js:29:51)                          
[ERROR]     at transformValue (D:\Projects\arif\fb-quiz\node_modules\cssnano-preset-default\node_modules\postcss-calc\dist\lib\transform.js:24:45)                      
[ERROR]     at exports.default (D:\Projects\arif\fb-quiz\node_modules\cssnano-preset-default\node_modules\postcss-calc\dist\lib\transform.js:54:100)                    
[ERROR]     at D:\Projects\arif\fb-quiz\node_modules\cssnano-preset-default\node_modules\postcss-calc\dist\index.js:28:52                                               
[ERROR]     at D:\Projects\arif\fb-quiz\node_modules\optimize-css-assets-webpack-plugin\node_modules\postcss\lib\container.js:144:26                                    
[ERROR]     at Rule.each (D:\Projects\arif\fb-quiz\node_modules\optimize-css-assets-webpack-plugin\node_modules\postcss\lib\container.js:110:22)                        
[ERROR]     at Rule.walk (D:\Projects\arif\fb-quiz\node_modules\optimize-css-assets-webpack-plugin\node_modules\postcss\lib\container.js:143:21)                        
[ERROR]     at D:\Projects\arif\fb-quiz\node_modules\optimize-css-assets-webpack-plugin\node_modules\postcss\lib\container.js:146:32                                    
[ERROR]     at Root.each (D:\Projects\arif\fb-quiz\node_modules\optimize-css-assets-webpack-plugin\node_modules\postcss\lib\container.js:110:22)                        
[ERROR]     at Root.walk (D:\Projects\arif\fb-quiz\node_modules\optimize-css-assets-webpack-plugin\node_modules\postcss\lib\container.js:143:21)                        
[ERROR]     at D:\Projects\arif\fb-quiz\node_modules\cssnano-preset-default\node_modules\postcss-calc\dist\index.js:25:9                                                
[ERROR]     at initializePlugin (D:\Projects\arif\fb-quiz\node_modules\optimize-css-assets-webpack-plugin\node_modules\cssnano\dist\index.js:35:51)                     
[ERROR]     at <anonymous>                                                                                                                                              
[ERROR] npm ERR! code ELIFECYCLE                                                                                                                                        
[ERROR] npm ERR! errno 1                                                                                                                                                
[ERROR] npm ERR! fb-quiz@0.0.0 webpack: `node --max_old_space_size=4096 node_modules/webpack/bin/webpack.js "--config" "webpack/webpack.prod.js" "--profile"`           
[ERROR] npm ERR! Exit status 1                                                                                                                                          
[ERROR] npm ERR!                                                                                                                                                        
[ERROR] npm ERR! Failed at the fb-quiz@0.0.0 webpack script.                                                                                                            
[ERROR] npm ERR! This is probably not a problem with npm. There is likely additional logging output above.                                                              
[ERROR]                                                                                                                                                                 
[ERROR] npm ERR! A complete log of this run can be found in:                                                                                                            
[ERROR] npm ERR!     C:\Users\Arif Rabbani\AppData\Roaming\npm-cache\_logs\2018-09-20T17_31_45_600Z-debug.log                                                           
[ERROR] npm ERR! code ELIFECYCLE                                                                                                                                        
[ERROR] npm ERR! errno 1                                                                                                                                                
[ERROR] npm ERR! fb-quiz@0.0.0 webpack:prod:main: `npm run webpack -- --config webpack/webpack.prod.js --profile`                                                       
[ERROR] npm ERR! Exit status 1                                                                                                                                          
[ERROR] npm ERR!                                                                                                                                                        
[ERROR] npm ERR! Failed at the fb-quiz@0.0.0 webpack:prod:main script.                                                                                                  
[ERROR] npm ERR! This is probably not a problem with npm. There is likely additional logging output above.                                                              
[ERROR]                                                                                                                                                                 
[ERROR] npm ERR! A complete log of this run can be found in:                                                                                                            
[ERROR] npm ERR!     C:\Users\Arif Rabbani\AppData\Roaming\npm-cache\_logs\2018-09-20T17_31_45_782Z-debug.log                                                           
[ERROR] npm ERR! code ELIFECYCLE                                                                                                                                        
[ERROR] npm ERR! errno 1                                                                                                                                                
[ERROR] npm ERR! fb-quiz@0.0.0 webpack:prod: `npm run cleanup && npm run webpack:prod:main && npm run clean-www`                                                        
[ERROR] npm ERR! Exit status 1                                                                                                                                          
[ERROR] npm ERR!                                                                                                                                                        
[ERROR] npm ERR! Failed at the fb-quiz@0.0.0 webpack:prod script.                                                                                                       
[ERROR] npm ERR! This is probably not a problem with npm. There is likely additional logging output above.                                                              
[ERROR]                                                                                                                                                                 
[ERROR] npm ERR! A complete log of this run can be found in:                                                                                                            
[ERROR] npm ERR!     C:\Users\Arif Rabbani\AppData\Roaming\npm-cache\_logs\2018-09-20T17_31_45_922Z-debug.log                                                           
[INFO] ------------------------------------------------------------------------                                                                                         
[INFO] BUILD FAILURE                                                                                                                                                    
[INFO] ------------------------------------------------------------------------                                                                                         
[INFO] Total time: 06:26 min                                                                                                                                            
[INFO] Finished at: 2018-09-20T23:01:46+05:30                                                                                                                           
[INFO] ------------------------------------------------------------------------                                                                                         
[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.6:npm (webpack build prod) on project fb-quiz: Failed to run task: 'npm run webpack:prod' fai
led. org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1) -> [Help 1]                                                              
[ERROR]                                                                                                                                                                 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.                                                                                     
[ERROR] Re-run Maven using the -X switch to enable full debug logging.                                                                                                  
[ERROR] 
```

##### **JHipster Version(s)**

```
fb-quiz@0.0.0 D:\Projects\arif\fb-quiz
`-- generator-jhipster@5.3.4

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.creatives.apsstr"
    },
    "jhipsterVersion": "5.3.4",
    "applicationType": "monolith",
    "baseName": "FbQuiz",
    "packageName": "com.creatives.apsstr",
    "packageFolder": "com/creatives/apsstr",
    "serverPort": "8080",
    "authenticationType": "session",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "mysql",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "rememberMeKey": "YourJWTSecretKeyWasReplacedByThisMeaninglessTextByTheJHipsterInfoCommandForObviousSecurityReasons",
    "clientFramework": "angularX",
    "useSass": true,
    "clientPackageManager": "npm",
    "testFrameworks": [],
    "jhiPrefix": "apsstr",
    "enableTranslation": false
  }
}
</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_144"
Java(TM) SE Runtime Environment (build 1.8.0_144-b01)
Java HotSpot(TM) 64-Bit Server VM (build 25.144-b01, mixed mode)

git version 2.11.0.windows.1

node: v8.12.0

npm: 6.4.1

##### **Browsers and Operating System**

- [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by mraible** [comment]
You need to include the output from `jhipster info` or we can't help you. I created several apps with JHipster v4.5.4 yesterday and didn't have ay issues with Maven.

**Comment by arabbani** [comment]
Just included

**Comment by gmarziou** [comment]
Please don't crosspost https://stackoverflow.com/questions/52430083/jhipster-is-producing-error-while-building-for-production
