### ISSUE TITLE
Failed to upgrade front-end, get error: ENOENT: no such file or directory, open '.gitignore'

### ISSUE THREAD

**Issue by waincent** [jhipster/generator-jhipster#8504]
##### **Overview of the issue**
I want upgrade the front-end from jhipster version 5.3.4 to 5.4.2, execute the command:
```
~ jhipster upgrade --skip-server   
```

The upgrade process
```
Using JHipster version installed globally
Executing jhipster:upgrade
Options: skipServer: true, from-cli: true, skip-server: true
Welcome to the JHipster Upgrade Sub-Generator
This will upgrade your current application codebase to the latest JHipster version
Looking for latest generator-jhipster version...
5.4.2
✔ New generator-jhipster version found: 5.4.2
     info git rev-parse -q --is-inside-work-tree
true
✔ Git repository detected
     info git status --porcelain
     info git rev-parse -q --abbrev-ref HEAD
master
     info git rev-parse -q --verify jhipster_upgrade
64bc9256895a5a184d3ad7be67081e026e1772c6
     info git checkout -q jhipster_upgrade
✔ Checked out branch "jhipster_upgrade"
Updating generator-jhipster to 5.4.2 . This might take some time...
     info npm install generator-jhipster@5.4.2 --dev --no-lockfile --ignore-scripts
npm WARN install Usage of the `--dev` option is deprecated. Use `--only=dev` instead.
+ generator-jhipster@5.4.2
removed 23 packages, updated 1 package and audited 3744 packages in 8.065s
found 0 vulnerabilities
```
get the error info

```
✔ Updated generator-jhipster to version 5.4.2
events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, open '.gitignore'
    at Object.openSync (fs.js:436:3)
    at Object.readFileSync (fs.js:341:35)
    at module.exports._cleanUp (/usr/local/lib/node_modules/generator-jhipster/generators/upgrade/index.js:106:43)
    at module.exports.generateWithLatestVersion (/usr/local/lib/node_modules/generator-jhipster/generators/upgrade/index.js:346:22)
    at Object.<anonymous> (/usr/local/lib/node_modules/generator-jhipster/node_modules/yeoman-generator/lib/index.js:418:27)
    at /usr/local/lib/node_modules/generator-jhipster/node_modules/run-async/index.js:25:25
    at new Promise (<anonymous>)
    at /usr/local/lib/node_modules/generator-jhipster/node_modules/run-async/index.js:24:19
    at self.env.runLoop.add.completed (/usr/local/lib/node_modules/generator-jhipster/node_modules/yeoman-generator/lib/index.js:419:13)
    at runCallback (timers.js:694:18)
Emitted 'error' event at:
    at Immediate.setImmediate (/usr/local/lib/node_modules/generator-jhipster/node_modules/yeoman-generator/lib/index.js:427:22)
    at runCallback (timers.js:694:18)
    at tryOnImmediate (timers.js:665:5)
    at processImmediate (timers.js:647:5)
exit 1
```
##### **JHipster Version(s)**
5.4.2
##### **JHipster configuration**
.yo-rc.json
```json
{
  "generator-jhipster": {
    "jhipsterVersion": "5.3.4",
    "applicationType": "monolith",
    "baseName": "IOTPlatform",
    "clientFramework": "angularX",
    "useSass": true,
    "clientPackageManager": "npm",
    "authenticationType": "true",
    "cacheProvider": "no",
    "databaseType": "mysql",
    "devDatabaseType": "mysql",
    "prodDatabaseType": "mysql",
    "testFrameworks": [
      "protractor"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": false,
    "skipServer": true
  }
}
```

**Comment by deepu105** [comment]
What is the issue? If you don't atleast specify a clear title or description what are we suppose to understand just from stacktrace, please follow our guidelines and add required info

**Comment by gmarziou** [comment]
The issue is that `.gitignore` is generated for server so when you use --skip-server  you don't have one.
The upgrade generator should not fail when there is no .gitignore.

**Comment by gmarziou** [comment]
Related to #8544

**Comment by deepu105** [comment]
closing as duplicate of #8544 it will be tracked there
