### ISSUE TITLE
jhipster info broken for nosql

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/generator-jhipster#8572]
##### **Overview of the issue**

It seems jhipster info is broken for nosql database, since the v5.4.2

##### **Reproduce the error**

```
git clone https://github.com/jhipster/jhipster-sample-app-mongodb.git
npm install
jhipster info
```

##### **JHipster Version(s)**

```
jhipster-mongodb-sample-application@0.0.0 /home/pgrimaud/tmp/jhipster-sample-app-mongodb
└── generator-jhipster@5.4.2 

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "baseName": "jhipsterMongodbSampleApplication",
    "packageName": "io.github.jhipster.sample",
    "packageFolder": "io/github/jhipster/sample",
    "authenticationType": "jwt",
    "hibernateCache": "no",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "mongodb",
    "devDatabaseType": "mongodb",
    "prodDatabaseType": "mongodb",
    "searchEngine": false,
    "useCompass": false,
    "buildTool": "maven",
    "enableTranslation": true,
    "applicationType": "monolith",
    "testFrameworks": [
      "gatling",
      "protractor"
    ],
    "languages": [
      "en"
    ],
    "serverPort": 8080,
    "jhipsterVersion": "5.4.2",
    "enableSocialSignIn": false,
    "useSass": false,
    "jhiPrefix": "jhi",
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "clientPackageManager": "npm",
    "clientFramework": "angularX",
    "jwtSecretKey": "bXktc2VjcmV0LXRva2VuLXRvLWNoYW5nZS1pbi1wcm9kdWN0aW9uLWFuZC10by1rZWVwLWluLWEtc2VjdXJlLXBsYWNl",
    "cacheProvider": "no",
    "enableHibernateCache": false,
    "reactive": false
  }
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

Cannot read property 'forEach' of undefined
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: ERROR! 
Error while parsing entities to JDL

    at Environment.error (/home/pgrimaud/tmp/jhipster-sample-app-mongodb/node_modules/yeoman-environment/lib/environment.js:157:40)
    at module.exports.error (/home/pgrimaud/tmp/jhipster-sample-app-mongodb/node_modules/generator-jhipster/generators/generator-base.js:2443:18)
    at module.exports.generateJDLFromEntities (/home/pgrimaud/tmp/jhipster-sample-app-mongodb/node_modules/generator-jhipster/generators/generator-base-private.js:1093:18)
    at module.exports.displayEntities (/home/pgrimaud/tmp/jhipster-sample-app-mongodb/node_modules/generator-jhipster/generators/info/index.js:65:34)
    at Object.<anonymous> (/home/pgrimaud/tmp/jhipster-sample-app-mongodb/node_modules/yeoman-generator/lib/index.js:418:27)
    at /home/pgrimaud/tmp/jhipster-sample-app-mongodb/node_modules/run-async/index.js:25:25
    at new Promise (<anonymous>)
    at /home/pgrimaud/tmp/jhipster-sample-app-mongodb/node_modules/run-async/index.js:24:19
    at self.env.runLoop.add.completed (/home/pgrimaud/tmp/jhipster-sample-app-mongodb/node_modules/yeoman-generator/lib/index.js:419:13)
    at runCallback (timers.js:810:20

-   [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by pascalgrimaud** [comment]
Bounty claimed https://opencollective.com/generator-jhipster/expenses/5360

**Comment by jdubois** [comment]
Thanks @pascalgrimaud ! Bounty approved!
