### ISSUE TITLE
jhipster generator: TypeError: Cannot read property 'blueprint' of undefined

### ISSUE THREAD

**Issue by xiaods** [jhipster/generator-jhipster#8795]
##### **Motivation for or Use Case**

when i brew install jhipster geneartor, i run it on macos environment. it raised error for me. i have reinstall the node version to 8.x
```
$ node -v
v8.12.0
```

##### **Reproduce the error**

```
Executing jhipster:app
Options: from-cli: true

Just found a `.yo-rc.json` in a parent directory.
Setting the project root at: /Users/xiaods/Documents/Code


        ██╗ ██╗   ██╗ ████████╗ ███████╗   ██████╗ ████████╗ ████████╗ ███████╗
        ██║ ██║   ██║ ╚══██╔══╝ ██╔═══██╗ ██╔════╝ ╚══██╔══╝ ██╔═════╝ ██╔═══██╗
        ██║ ████████║    ██║    ███████╔╝ ╚█████╗     ██║    ██████╗   ███████╔╝
  ██╗   ██║ ██╔═══██║    ██║    ██╔════╝   ╚═══██╗    ██║    ██╔═══╝   ██╔══██║
  ╚██████╔╝ ██║   ██║ ████████╗ ██║       ██████╔╝    ██║    ████████╗ ██║  ╚██╗
   ╚═════╝  ╚═╝   ╚═╝ ╚═══════╝ ╚═╝       ╚═════╝     ╚═╝    ╚═══════╝ ╚═╝   ╚═╝

                            https://www.jhipster.tech

Welcome to JHipster v5.6.1
Application files will be generated in folder: /Users/xiaods/Documents/Code
 _______________________________________________________________________________________________________________

  Documentation for creating an application is at https://www.jhipster.tech/creating-an-app/
  If you find JHipster useful, consider sponsoring the project at https://opencollective.com/generator-jhipster
 _______________________________________________________________________________________________________________

? Which *type* of application would you like to create? Microservice application
? What is the base name of your application? regis
events.js:183
      throw er; // Unhandled 'error' event
      ^

TypeError: Cannot read property 'blueprint' of undefined
    at Object.getAllJhipsterConfig (/usr/local/Cellar/jhipster/5.6.1/libexec/lib/node_modules/generator-jhipster/generators/utils.js:419:27)
    at module.exports.getAllJhipsterConfig (/usr/local/Cellar/jhipster/5.6.1/libexec/lib/node_modules/generator-jhipster/generators/generator-base.js:2970:30)
    at module.exports.setupConsts (/usr/local/Cellar/jhipster/5.6.1/libexec/lib/node_modules/generator-jhipster/generators/common/index.js:69:44)
    at Object.<anonymous> (/usr/local/Cellar/jhipster/5.6.1/libexec/lib/node_modules/generator-jhipster/node_modules/yeoman-generator/lib/index.js:418:27)
    at /usr/local/Cellar/jhipster/5.6.1/libexec/lib/node_modules/generator-jhipster/node_modules/run-async/index.js:25:25
    at new Promise (<anonymous>)
    at /usr/local/Cellar/jhipster/5.6.1/libexec/lib/node_modules/generator-jhipster/node_modules/run-async/index.js:24:19
    at self.env.runLoop.add.completed (/usr/local/Cellar/jhipster/5.6.1/libexec/lib/node_modules/generator-jhipster/node_modules/yeoman-generator/lib/index.js:419:13)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
```

##### **Suggest a Fix**

any clues welcome, i don't found any helpful info for this.
##### **JHipster Version(s)**
JHipster v5.6.1

##### **Browsers and Operating System**

-   [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by pascalgrimaud** [comment]
Look at your log: `Just found a `.yo-rc.json` in a parent directory.`
It seems like you have a  `.yo-rc.json` file in your `/Users/xiaods/Documents` folder.
You can't generate a JHipster project in a sub folder of an already one

**Comment by xiaods** [comment]
@pascalgrimaud thanks for your hints, it works like a charm now. thanks a lot.
