### ISSUE TITLE
when run ./mvnw ,throw ZipException:error in opening zip file

### ISSUE THREAD

**Issue by Xsxdot** [jhipster/generator-jhipster#8821]
##### **Overview of the issue**

~/D/W/J/question git:master ❯❯❯ ./mvnw                                                                              
Exception in thread "main" java.util.zip.ZipException: error in opening zip file
	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(ZipFile.java:225)
	at java.util.zip.ZipFile.<init>(ZipFile.java:155)
	at java.util.zip.ZipFile.<init>(ZipFile.java:169)
	at org.apache.maven.wrapper.Installer.unzip(Installer.java:161)
	at org.apache.maven.wrapper.Installer.createDist(Installer.java:78)
	at org.apache.maven.wrapper.WrapperExecutor.execute(WrapperExecutor.java:121)
	at org.apache.maven.wrapper.MavenWrapperMain.main(MavenWrapperMain.java:55)

##### **Reproduce the error**

When I saw it , I remove my m2 repository.  But no help.
##### **JHipster Version(s)**

```
question@0.0.0 /Users/frank/Documents/Workspace/JHipster/question
└── generator-jhipster@5.7.0

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.jianyi.out.question"
    },
    "jhipsterVersion": "5.7.0",
    "applicationType": "monolith",
    "baseName": "question",
    "packageName": "com.jianyi.out.question",
    "packageFolder": "com/jianyi/out/question",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "no",
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "mysql",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "bXktc2VjcmV0LXRva2VuLXRvLWNoYW5nZS1pbi1wcm9kdWN0aW9uLWFuZC10by1rZWVwLWluLWEtc2VjdXJlLXBsYWNl",
    "clientFramework": "angularX",
    "useSass": true,
    "clientPackageManager": "npm",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "otherModules": [],
    "enableTranslation": false
  }
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_144"
Java(TM) SE Runtime Environment (build 1.8.0_144-b01)
Java HotSpot(TM) 64-Bit Server VM (build 25.144-b01, mixed mode)

git version 2.15.1 (Apple Git-101)

node: v10.13.0

npm: 6.4.1

yeoman: 2.0.0

yarn: 1.5.1

##### **Browsers and Operating System**

OS X

-   [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by Xsxdot** [comment]
When run sudo ./mvnw , nothing show ....

**Comment by Xsxdot** [comment]
I deleted m2 wrapper, then run ./mvnw , no exception, but nothing too.....

**Comment by Xsxdot** [comment]
After a long time, something appeared. But running very slowly
