### ISSUE TITLE
first run 'jhipster' command I get error :The "path" argument must be of type string. Received type undefined

### ISSUE THREAD

**Issue by freeabyss** [jhipster/generator-jhipster#9031]
##### **Overview of the issue**

```shell
KeyStore 'src/main/resources/config/tls/keystore.p12' generated successfully.

events.js:167
      throw er; // Unhandled 'error' event
      ^

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
    at assertPath (path.js:39:11)
    at Object.join (path.js:1152:7)
    at getPath (/Users/abyss/.nvm/versions/node/v10.15.0/lib/node_modules/generator-jhipster/node_modules/dir-glob/index.js:6:41)
    at globs.concat.map.x (/Users/abyss/.nvm/versions/node/v10.15.0/lib/node_modules/generator-jhipster/node_modules/dir-glob/index.js:47:59)
    at Array.map (<anonymous>)
    at module.exports.sync (/Users/abyss/.nvm/versions/node/v10.15.0/lib/node_modules/generator-jhipster/node_modules/dir-glob/index.js:47:33)
    at globDirs (/Users/abyss/.nvm/versions/node/v10.15.0/lib/node_modules/generator-jhipster/node_modules/globby/index.js:58:9)
    at getPattern (/Users/abyss/.nvm/versions/node/v10.15.0/lib/node_modules/generator-jhipster/node_modules/globby/index.js:61:64)
    at globTasks.reduce (/Users/abyss/.nvm/versions/node/v10.15.0/lib/node_modules/generator-jhipster/node_modules/globby/index.js:107:19)
    at Array.reduce (<anonymous>)
Emitted 'error' event at:
    at Immediate.setImmediate (/Users/abyss/.nvm/versions/node/v10.15.0/lib/node_modules/generator-jhipster/node_modules/yeoman-generator/lib/index.js:427:22)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
```

##### **Reproduce the error**

after install jhipster ,I run the following commands
```shell
mkdir demo 
cd demo
jhipster
```

##### **JHipster Version(s)**

5.7.2

##### **JHipster configuration**

INFO! Using JHipster version installed globally
INFO! Executing jhipster:info
INFO! Options: from-cli: true
Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
/Users/abyss
└── (empty)

```

cat: no such file or directory: .yo-rc.json

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_191"
Java(TM) SE Runtime Environment (build 1.8.0_191-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.191-b12, mixed mode)

git version 2.19.1

node: v10.15.0

npm: 6.4.1

Docker version 18.09.0, build 4d60db4

docker-compose version 1.23.2, build 1110ad01

INFO! Congratulations, JHipster execution is complete!

**Comment by freeabyss** [comment]
I install jhipster with npm before. 
This time I uninstalled jhipster and reinstall it with yarn. 
run `yo jhipster`, It worked successfully without error.

**Comment by gmarziou** [comment]
Never mix yarn and npm, they use different paths for binaries like `jhipster`command. Unistall generator-jhipster from npm, if you plan to use yarn
