### ISSUE TITLE
blueprint doesn't support no-i18n

### ISSUE THREAD

**Issue by xetys** [jhipster/generator-jhipster#9058]
##### **Overview of the issue**

When a user generates an angular client without translation enabled, we use some scripting to replace the language keys with the actual string from the target language. This, however, doesn't work in a blueprint. When trying this use see a bunch of errors like this:

```
Error in file: ../../languages/templates/src/main/webapp/i18n/en/metrics.json.ejs
Error: /home/david/kloud/generator-jhipster-ktelizer/generators/languages/templates/src/main/webapp/i18n/en/user-management.json.ejs doesn't exist
    at EditionInterface.module.exports [as read] (/home/david/kloud/generator-jhipster-ktelizer/node_modules/mem-fs-editor/lib/actions/read.js:12:11)
    at geti18nJson (/home/david/kloud/generator-jhipster-ktelizer/node_modules/generator-jhipster/generators/utils.js:313:33)
    at replaceTitle (/home/david/kloud/generator-jhipster-ktelizer/node_modules/generator-jhipster/generators/utils.js:226:26)
    at body (/home/david/kloud/generator-jhipster-ktelizer/node_modules/generator-jhipster/generators/utils.js:179:28)
    at ejs.renderFile (/home/david/kloud/generator-jhipster-ktelizer/node_modules/generator-jhipster/generators/utils.js:204:13)
    at tryHandleCache (/home/david/kloud/generator-jhipster-ktelizer/node_modules/ejs/lib/ejs.js:257:5)
    at Object.exports.renderFile (/home/david/kloud/generator-jhipster-ktelizer/node_modules/ejs/lib/ejs.js:482:10)
    at renderContent (/home/david/kloud/generator-jhipster-ktelizer/node_modules/generator-jhipster/generators/utils.js:202:9)
    at Object.copyWebResource (/home/david/kloud/generator-jhipster-ktelizer/node_modules/generator-jhipster/generators/utils.js:172:9)
    at module.exports.copyTemplate (/home/david/kloud/generator-jhipster-ktelizer/node_modules/generator-jhipster/generators/generator-base.js:1773:31)
Error in file: ../../languages/templates/src/main/webapp/i18n/en/user-management.json.ejs
Error: /home/david/kloud/generator-jhipster-ktelizer/generators/languages/templates/src/main/webapp/i18n/en/user-management.json.ejs doesn't exist
    at EditionInterface.module.exports [as read] (/home/david/kloud/generator-jhipster-ktelizer/node_modules/mem-fs-editor/lib/actions/read.js:12:11)
    at geti18nJson (/home/david/kloud/generator-jhipster-ktelizer/node_modules/generator-jhipster/generators/utils.js:313:33)
    at replaceTitle (/home/david/kloud/generator-jhipster-ktelizer/node_modules/generator-jhipster/generators/utils.js:226:26)
    at body (/home/david/kloud/generator-jhipster-ktelizer/node_modules/generator-jhipster/generators/utils.js:179:28)
    at ejs.renderFile (/home/david/kloud/generator-jhipster-ktelizer/node_modules/generator-jhipster/generators/utils.js:204:13)
    at tryHandleCache (/home/david/kloud/generator-jhipster-ktelizer/node_modules/ejs/lib/ejs.js:257:5)
    at Object.exports.renderFile (/home/david/kloud/generator-jhipster-ktelizer/node_modules/ejs/lib/ejs.js:482:10)
    at renderContent (/home/david/kloud/generator-jhipster-ktelizer/node_modules/generator-jhipster/generators/utils.js:202:9)
    at Object.copyWebResource (/home/david/kloud/generator-jhipster-ktelizer/node_modules/generator-jhipster/generators/utils.js:172:9)
    at module.exports.copyTemplate (/home/david/kloud/generator-jhipster-ktelizer/node_modules/generator-jhipster/generators/generator-base.js:1773:31)
```

##### **Motivation for or Use Case**
I want to use blueprints for non-i18n project, too

##### **Reproduce the error**

Create a client blueprint without own client implementation (like Vue), if you just want to extend the existing one. Choose not to use translation.

##### **Suggest a Fix**

If I copy the entire language folder from the main generator into actual blueprint, this works.

Maybe this has to be solved in the blueprint generator?

##### **Browsers and Operating System**

-   [X] Checking this box is mandatory (this is just to show you read everything)

**Comment by pascalgrimaud** [comment]
@xetys : blueprint doesn't support language. That's why I did this PR: https://github.com/jhipster/generator-jhipster/pull/9049

**Comment by DanielFran** [comment]
@pascalgrimaud Since https://github.com/jhipster/generator-jhipster/pull/9049 has been merged, can you confirm this issue can be closed?

**Comment by pascalgrimaud** [comment]
yes we can close
