### ISSUE TITLE
Liquibase - Configure property interpolation for mariadb for the ${floatType} property

### ISSUE THREAD

**Issue by pvliss** [jhipster/generator-jhipster#9061]
##### **Overview of the issue**
Maria DB  is missing from dbms list for property `floatType` in `generators/entity-server/templates/src/main/resources/config/liquibase/changelog/added_entity.xml.ejs`

##### **Motivation for or Use Case**
This results in failing to start the server when using Maria DB and have at least one entity with at least one entity of type `Float`.
More specifically I was getting the following error as the property could not be parsed:
```
2019-01-14 19:06:58.772 ERROR 1724 --- [finispan-task-1] g.j.a.ExceptionHandlingAsyncTaskExecutor : Caught async exception

java.lang.ArrayIndexOutOfBoundsException: 1
        at liquibase.datatype.DataTypeFactory.fromDescription(DataTypeFactory.java:251)
        at liquibase.change.core.CreateTableChange.generateStatements(CreateTableChange.java:70)
        at liquibase.change.AbstractChange.generateStatementsVolatile(AbstractChange.java:287)
        at liquibase.change.AbstractChange.warn(AbstractChange.java:358)
        at liquibase.changelog.visitor.ValidatingVisitor.visit(ValidatingVisitor.java:109)
        at liquibase.changelog.ChangeLogIterator.run(ChangeLogIterator.java:78)
        at liquibase.changelog.DatabaseChangeLog.validate(DatabaseChangeLog.java:269)
        at liquibase.Liquibase.update(Liquibase.java:198)
        at liquibase.Liquibase.update(Liquibase.java:179)
        at liquibase.integration.spring.SpringLiquibase.performUpdate(SpringLiquibase.java:353)
        at liquibase.integration.spring.SpringLiquibase.afterPropertiesSet(SpringLiquibase.java:305)
        at io.github.jhipster.config.liquibase.AsyncSpringLiquibase.initDb(AsyncSpringLiquibase.java:103)
        at io.github.jhipster.config.liquibase.AsyncSpringLiquibase.lambda$afterPropertiesSet$0(AsyncSpringLiquibase.java:83)
        at io.github.jhipster.async.ExceptionHandlingAsyncTaskExecutor.lambda$createWrappedRunnable$1(ExceptionHandlingAsyncTaskExecutor.java:68)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

```

##### **Reproduce the error**
Execute the `ngx-mariadb-oauth2-sass-infinispan` test with the `sql` sample

##### **Related issues**
None that I could find

##### **Suggest a Fix**
Change the property to:
```xml
<property name="floatType" value="float" dbms="mysql, oracle, mssql, mariadb"/>
```

Will provide a PR as already fixed locally.

##### **JHipster Version(s)**
Current trunk(5.7.3)

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by DanielFran** [comment]
PR merged, so closing
