### ISSUE TITLE
v581 UAA doesn't compile with 'mvn clean install'

### ISSUE THREAD

**Issue by alexsintoni** [jhipster/generator-jhipster#9158]
##### **Overview of the issue**

I have just created a new UAA component with last version `generator-jhipster` (v5.8.1) and launched `mvn clean install`.
In previous version, it was working straight away without changing anything.
With this version I get the following error:

```
2019-01-31 07:45:52.610 ERROR 5739 --- [           main] o.s.boot.SpringApplication               : Application run failed

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'tokenStore' defined in class path resource [com/kekse/mystaff/config/UaaConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.security.oauth2.provider.token.store.JwtTokenStore]: Factory method 'tokenStore' threw exception; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'jwtAccessTokenConverter' defined in class path resource [com/kekse/mystaff/config/UaaConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.security.oauth2.provider.token.store.JwtAccessTokenConverter]: Factory method 'jwtAccessTokenConverter' threw exception; nested exception is java.lang.IllegalStateException: Cannot load keys from store: class path resource [config/tls/keystore.p12]

[...]

Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.security.oauth2.provider.token.store.JwtAccessTokenConverter]: Factory method 'jwtAccessTokenConverter' threw exception; nested exception is java.lang.IllegalStateException: Cannot load keys from store: class path resource [config/tls/keystore.p12]
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:583)
	... 67 common frames omitted
Caused by: java.lang.IllegalStateException: Cannot load keys from store: class path resource [config/tls/keystore.p12]
	at org.springframework.security.oauth2.provider.token.store.KeyStoreKeyFactory.getKeyPair(KeyStoreKeyFactory.java:67)
	at org.springframework.security.oauth2.provider.token.store.KeyStoreKeyFactory.getKeyPair(KeyStoreKeyFactory.java:48)
	at com.kekse.mystaff.config.UaaConfiguration.jwtAccessTokenConverter(UaaConfiguration.java:183)
	at com.kekse.mystaff.config.UaaConfiguration$$EnhancerBySpringCGLIB$$7301c9b2.CGLIB$jwtAccessTokenConverter$5(<generated>)
	at com.kekse.mystaff.config.UaaConfiguration$$EnhancerBySpringCGLIB$$7301c9b2$$FastClassBySpringCGLIB$$53f1a041.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228)
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:365)
	at com.kekse.mystaff.config.UaaConfiguration$$EnhancerBySpringCGLIB$$7301c9b2.jwtAccessTokenConverter(<generated>)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154)
	... 68 common frames omitted
Caused by: java.io.FileNotFoundException: class path resource [config/tls/keystore.p12] cannot be opened because it does not exist
	at org.springframework.core.io.ClassPathResource.getInputStream(ClassPathResource.java:180)
	at org.springframework.security.oauth2.provider.token.store.KeyStoreKeyFactory.getKeyPair(KeyStoreKeyFactory.java:57)
	... 80 common frames omitted
```

##### **Motivation for or Use Case**

I want to start a new project using UAA for authentication mechanism with last version of `generator-jhipster`.
In previous project I could simply use in development environment the UAA without setting up any `config/tls/keystore.p12` file. It was working straight away.
From this version on shall I have to set it up?
Where can  I find documentation about it?

##### **Reproduce the error**

Simply create a new UAA micro-service with last version 5.8.1 of `generator-jhipster` and in the same folder run `mvn clean install`

##### **Related issues**

It is the first issue with this new version.

##### **Suggest a Fix**

-

##### **JHipster Version(s)**

v5.8.1

##### **JHipster configuration**

```
jhipster info
INFO! Using JHipster version installed locally in current project's node_modules
INFO! Executing jhipster:info
INFO! Options: from-cli: true
Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
test-uaa-581@0.0.0 /home/alex/Development/workspace/jhipster/test-uaa-581
└── generator-jhipster@5.8.1 

```


##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**


<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.mycomany.test",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "5.8.1",
    "applicationType": "uaa",
    "baseName": "TestUaa581",
    "packageName": "com.mycomany.test",
    "packageFolder": "com/mycomany/test",
    "serverPort": "9999",
    "authenticationType": "uaa",
    "cacheProvider": "hazelcast",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "mysql",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": "eureka",
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "xyz",
    "testFrameworks": [
      "gatling"
    ],
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [],
    "enableTranslation": true,
    "clientPackageManager": "npm",
    "nativeLanguage": "en",
    "languages": [
      "en",
      "al",
      "ar-ly",
      "hy",
      "by",
      "bn",
      "ca",
      "zh-cn",
      "zh-tw",
      "cs",
      "da",
      "nl",
      "et",
      "fa",
      "fr",
      "gl",
      "de",
      "el",
      "hi",
      "hu",
      "id",
      "it",
      "ja",
      "ko",
      "mr",
      "my",
      "pl",
      "pt-br",
      "pt-pt",
      "ro",
      "ru",
      "sk",
      "sr",
      "es",
      "sv",
      "tr",
      "ta",
      "te",
      "th",
      "ua",
      "uz-lat",
      "vi"
    ],
    "skipClient": true
  }
}
</pre>
</details>


##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>


##### **Environment and Tools**

openjdk version "1.8.0_191"
OpenJDK Runtime Environment (build 1.8.0_191-8u191-b12-0ubuntu0.18.04.1-b12)
OpenJDK 64-Bit Server VM (build 25.191-b12, mixed mode)

git version 2.17.1

node: v8.11.4

npm: 6.5.0

yeoman: 2.0.5

yarn: 1.9.4

Docker version 18.06.1-ce, build e68fc7a

docker-compose version 1.17.1, build unknown

INFO! Congratulations, JHipster execution is complete!
```

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

No applicable for UAA

##### **Browsers and Operating System**

Not important for this issue

-   [ x] Checking this box is mandatory (this is just to show you read everything)

**Comment by pascalgrimaud** [comment]
@alexsintoni : during the generation, be sure the `keystore.p12` is correctly generated:

```
This is an existing project, using the configuration from your .yo-rc.json file 
to re-generate the project...


Installing languages: en, al, ar-ly, hy, by, bn, ca, zh-cn, zh-tw, cs, da, nl, et, fa, fr, gl, de, el, hi, hu, id, it, ja, ko, mr, my, pl, pt-br, pt-pt, ro, ru, sk, sr, es, sv, tr, ta, te, th, ua, uz-lat, vi for server
Git repository initialized.

KeyStore 'src/main/resources/config/tls/keystore.p12' generated successfully.
```

I used your config and I don't have any issue, the `mvn clean install` works well.
But if I deleted this file, it will fail with the same stacktrace like you.

**Comment by alexsintoni** [comment]
Hi @pascalgrimaud 
first of all thanks a million for the very fast reply.

How could you use that configuration to generate a new project?

I tried for 3 or 4 times the same procedure:

1. create a new folder
2. run `jhipster` inside the new folder
3. chose the same options (same `.yo-rc.json` configuration result)

and all those tests ended with missing file.

Maybe I have to generate the project using the `.yo-rc.json` as you did, but I don't know how.
Usually I simply create new projects

**Comment by alexsintoni** [comment]
Again thanks a million @pascalgrimaud 

I think you are totally right that my `keytool` doesn't work.

I try to fix it ;)

Anyway, it was useful for me to learn about the trick 
- create empty folder
- I create an empty file .yo-rc.json and copy paste your config inside it
- then, launch `jhipster` : no question, it will generate a new project immediately

I did't know it before.

I guess with this you can close this ticket.
Thanks a million
