### ISSUE TITLE
Cannot upgrade from 5.7.2 to 5.8.1

### ISSUE THREAD

**Issue by smulhall1337** [jhipster/generator-jhipster#9200]
##### **Overview of the issue**

When attempting to upgrade my Jhipster app from 5.7.2 to 5.8.1, I can an error complaining that all of the relationships in my 'Participant' entity are lacking the otherEntityRelationshipName.

 ```
WARNING! otherEntityRelationshipName is missing in .jhipster/Participant.json for relationship {
    "relationshipName": "contactStatus",
    "otherEntityName": "contactStatus",
    "relationshipType": "many-to-one",
    "otherEntityField": "name",
    "otherEntityRelationshipNameUndefined": true,
    "otherEntityRelationshipName": "participant"
}, using participant as fallback
WARNING! otherEntityRelationshipName is missing in .jhipster/Participant.json for relationship {
    "relationshipName": "contactSubStatus",
    "otherEntityName": "contactSubStatus",
    "relationshipType": "many-to-one",
    "otherEntityField": "name",
    "otherEntityRelationshipNameUndefined": true,
    "otherEntityRelationshipName": "participant"
}, using participant as fallback
WARNING! otherEntityRelationshipName is missing in .jhipster/Participant.json for relationship {
    "relationshipName": "mco",
    "otherEntityName": "mCO",
    "relationshipType": "many-to-one",
    "otherEntityField": "name",
    "otherEntityRelationshipNameUndefined": true,
    "otherEntityRelationshipName": "participant"
}, using participant as fallback
WARNING! otherEntityRelationshipName is missing in .jhipster/Participant.json for relationship {
    "relationshipName": "referralType",
    "otherEntityName": "referralType",
    "relationshipType": "many-to-one",
    "otherEntityField": "name",
    "otherEntityRelationshipNameUndefined": true,
    "otherEntityRelationshipName": "participant"
}, using participant as fallback
WARNING! otherEntityRelationshipName is missing in .jhipster/Participant.json for relationship {
    "relationshipName": "referralSource",
    "otherEntityName": "referralSource",
    "relationshipType": "many-to-one",
    "otherEntityField": "name",
    "otherEntityRelationshipNameUndefined": true,
    "otherEntityRelationshipName": "participant"
}, using participant as fallback
WARNING! relationshipName is missing in .jhipster/Participant.json for relationship {}, using undefined as fallback
events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: ERROR! otherEntityName is missing in .jhipster/Participant.json for relationship {}
    at Environment.error (/home/vagrant/Documents/CWCRM2/node_modules/yeoman-environment/lib/environment.js:157:40)
    at module.exports.error (/home/vagrant/Documents/CWCRM2/node_modules/generator-jhipster/generators/generator-base.js:1516:18)
    at context.relationships.forEach.relationship (/home/vagrant/Documents/CWCRM2/node_modules/generator-jhipster/generators/entity/index.js:511:30)
    at Array.forEach (<anonymous>)
    at module.exports.validateFile (/home/vagrant/Documents/CWCRM2/node_modules/generator-jhipster/generators/entity/index.js:498:39)
    at Object.<anonymous> (/home/vagrant/Documents/CWCRM2/node_modules/yeoman-generator/lib/index.js:418:27)
    at /home/vagrant/Documents/CWCRM2/node_modules/run-async/index.js:25:25
    at new Promise (<anonymous>)
    at /home/vagrant/Documents/CWCRM2/node_modules/run-async/index.js:24:19
    at self.env.runLoop.add.completed (/home/vagrant/Documents/CWCRM2/node_modules/yeoman-generator/lib/index.js:419:13)
Emitted 'error' event at:
    at Immediate.setImmediate (/home/vagrant/Documents/CWCRM2/node_modules/yeoman-generator/lib/index.js:427:22)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
events.js:167
      throw er; // Unhandled 'error' event
```

upon running the jhipster upgrade generator, I noticed it changed my participant.json from
```
{
    "fluentMethods": true,
    "clientRootFolder": "",
    "relationships": [
        {
            "relationshipName": "contactStatus",
            "otherEntityName": "contactStatus",
            "relationshipType": "many-to-one",
            "otherEntityField": "name"
        },
        {
            "relationshipName": "contactSubStatus",
            "otherEntityName": "contactSubStatus",
            "relationshipType": "many-to-one",
            "otherEntityField": "name"
        },
        {
            "relationshipName": "mco",
            "otherEntityName": "mCO",
            "relationshipType": "many-to-one",
            "otherEntityField": "name"
        },
        {
            "relationshipName": "referralType",
            "otherEntityName": "referralType",
            "relationshipType": "many-to-one",
            "otherEntityField": "name"
        },
        {
            "relationshipName": "referralSource",
            "otherEntityName": "referralSource",
            "relationshipType": "many-to-one",
            "otherEntityField": "name"
        },
        {
            "relationshipName": "assignedTo",
            "otherEntityName": "user",
            "relationshipType": "many-to-one",
            "otherEntityField": "login",
            "ownerSide": true,
            "otherEntityRelationshipName": "participant"
        }
    ],
    "fields": [
        {
            "fieldName": "firstName",
            "fieldType": "String",
            "fieldValidateRules": [
                "required"
            ]
        },
        {
            "fieldName": "middleInitial",
            "fieldType": "String"
        },
        {
            "fieldName": "lastName",
            "fieldType": "String",
            "fieldValidateRules": [
                "required"
            ]
        },
        {
            "fieldName": "title",
            "fieldType": "String"
        },
        {
            "fieldName": "registrationDate",
            "fieldType": "LocalDate"
        },
        {
            "fieldName": "address",
            "fieldType": "String"
        },
        {
            "fieldName": "city",
            "fieldType": "String"
        },
        {
            "fieldName": "state",
            "fieldType": "String"
        },
        {
            "fieldName": "country",
            "fieldType": "String"
        },
        {
            "fieldName": "dob",
            "fieldType": "LocalDate"
        },
        {
            "fieldName": "primaryPhone",
            "fieldType": "String"
        },
        {
            "fieldName": "primaryPhoneType",
            "fieldType": "String"
        },
        {
            "fieldName": "secondaryPhone",
            "fieldType": "String"
        },
        {
            "fieldName": "secondaryPhoneType",
            "fieldType": "String"
        },
        {
            "fieldName": "email",
            "fieldType": "String"
        },
        {
            "fieldName": "zip",
            "fieldType": "String"
        },
        {
            "fieldName": "medicareIdNumber",
            "fieldType": "String"
        },
        {
            "fieldName": "medicaidIdNumber",
            "fieldType": "String"
        },
        {
            "fieldName": "gender",
            "fieldType": "String"
        }
    ],
    "changelogDate": "20190104174613",
    "dto": "mapstruct",
    "searchEngine": false,
    "service": "serviceImpl",
    "entityTableName": "participant",
    "jpaMetamodelFiltering": false,
    "pagination": "infinite-scroll"
}
```

to

```
{
    "fluentMethods": true,
    "clientRootFolder": "",
    "relationships": [
        {
            "relationshipName": "contactStatus",
            "otherEntityName": "contactStatus",
            "relationshipType": "many-to-one",
            "otherEntityField": "name"
        },
        {
            "relationshipName": "contactSubStatus",
            "otherEntityName": "contactSubStatus",
            "relationshipType": "many-to-one",
            "otherEntityField": "name"
        },
        {
            "relationshipName": "mco",
            "otherEntityName": "mCO",
            "relationshipType": "many-to-one",
            "otherEntityField": "name"
        },
        {
            "relationshipName": "referralType",
            "otherEntityName": "referralType",
            "relationshipType": "many-to-one",
            "otherEntityField": "name"
        },
        {
            "relationshipName": "referralSource",
            "otherEntityName": "referralSource",
            "relationshipType": "many-to-one",
            "otherEntityField": "name"
        },
        {
            "relationshipName": "assignedTo",
            "otherEntityName": "user",
            "relationshipType": "many-to-one",
            "otherEntityField": "login",
            "ownerSide": true,
            "otherEntityRelationshipName": "participant"
        },
        {

        }
    ],
    "fields": [
        {
            "fieldName": "firstName",
            "fieldType": "String",
            "fieldValidateRules": [
                "required"
            ]
        },
        {
            "fieldName": "middleInitial",
            "fieldType": "String"
        },
        {
            "fieldName": "lastName",
            "fieldType": "String",
            "fieldValidateRules": [
                "required"
            ]
        },
        {
            "fieldName": "title",
            "fieldType": "String"
        },
        {
            "fieldName": "registrationDate",
            "fieldType": "LocalDate"
        },
        {
            "fieldName": "address",
            "fieldType": "String"
        },
        {
            "fieldName": "city",
            "fieldType": "String"
        },
        {
            "fieldName": "state",
            "fieldType": "String"
        },
        {
            "fieldName": "country",
            "fieldType": "String"
        },
        {
            "fieldName": "dob",
            "fieldType": "LocalDate"
        },
        {
            "fieldName": "primaryPhone",
            "fieldType": "String"
        },
        {
            "fieldName": "primaryPhoneType",
            "fieldType": "String"
        },
        {
            "fieldName": "secondaryPhone",
            "fieldType": "String"
        },
        {
            "fieldName": "secondaryPhoneType",
            "fieldType": "String"
        },
        {
            "fieldName": "email",
            "fieldType": "String"
        },
        {
            "fieldName": "zip",
            "fieldType": "String"
        },
        {
            "fieldName": "medicareIdNumber",
            "fieldType": "String"
        },
        {
            "fieldName": "medicaidIdNumber",
            "fieldType": "String"
        },
        {
            "fieldName": "gender",
            "fieldType": "String"
        }
    ],
    "changelogDate": "20190104174613",
    "dto": "mapstruct",
    "searchEngine": false,
    "service": "serviceImpl",
    "entityTableName": "participant",
    "jpaMetamodelFiltering": false,
    "pagination": "infinite-scroll"
}
```

##### **Motivation for or Use Case**

I wish to upgrade my app to the latest version 

##### **Related issues**

this was the only issue i could find that resembled mine. I regenerated the json files and tried to upgrade again. I got the same results
https://github.com/jhipster/generator-jhipster/issues/7852

##### **JHipster Version(s)**

5.7.2

##### **JHipster configuration**

```
Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
cwcrm-2@0.0.0 /home/vagrant/Documents/CWCRM2
└── generator-jhipster@5.7.2 

```


##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**


<details>
<summary>.yo-rc.json file</summary>
<pre>
{
    "generator-jhipster": {
        "promptValues": {
            "packageName": "com.cw.crm",
            "nativeLanguage": "en"
        },
        "jhipsterVersion": "5.7.2",
        "applicationType": "monolith",
        "baseName": "CWCRM2",
        "packageName": "com.cw.crm",
        "packageFolder": "com/cw/crm",
        "serverPort": "8080",
        "authenticationType": "jwt",
        "cacheProvider": "ehcache",
        "enableHibernateCache": true,
        "websocket": false,
        "databaseType": "sql",
        "devDatabaseType": "h2Disk",
        "prodDatabaseType": "mysql",
        "searchEngine": false,
        "messageBroker": false,
        "serviceDiscoveryType": false,
        "buildTool": "maven",
        "enableSwaggerCodegen": false,
        "jwtSecretKey": "bXktc2VjcmV0LXRva2VuLXRvLWNoYW5nZS1pbi1wcm9kdWN0aW9uLWFuZC10by1rZWVwLWluLWEtc2VjdXJlLXBsYWNl",
        "clientFramework": "angularX",
        "useSass": true,
        "clientPackageManager": "npm",
        "testFrameworks": ["gatling", "cucumber", "protractor"],
        "jhiPrefix": "jhi",
        "otherModules": [],
        "enableTranslation": true,
        "nativeLanguage": "en",
        "languages": ["en"]
    }
}

</pre>
</details>


##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity Participant {
  firstName String required,
  middleInitial String,
  lastName String required,
  title String,
  registrationDate LocalDate,
  address String,
  city String,
  state String,
  country String,
  dob LocalDate,
  primaryPhone String,
  primaryPhoneType String,
  secondaryPhone String,
  secondaryPhoneType String,
  email String,
  zip String,
  medicareIdNumber String,
  medicaidIdNumber String,
  gender String
}
entity Action {
  dueDate LocalDate,
  startDateTime Instant,
  endDateTime Instant,
  notes TextBlob
}
entity SupportCoordinator {
  firstName String required,
  lastName String required,
  phone String required,
  emailId String required,
  dateHired LocalDate required,
  userName String required
}
entity Waiver {
  name String required
}
entity Department {
  name String required
}
entity EmployeeType {
  name String required
}
entity EmployeeSubType {
  name String required
}
entity ContactStatus {
  name String required
}
entity ContactSubStatus {
  name String required
}
entity Priority {
  name String required
}
entity MCO {
  name String required
}
entity Physician {
  firstName String,
  lastName String,
  phone String,
  fax String,
  address String,
  notes TextBlob,
  disability String
}
entity EnrollmentAgency {
  name String,
  office String,
  recordNumber String,
  phone String
}
entity ContactHistory {
  date LocalDate,
  notes TextBlob
}
entity ParticipantNotes {
  notes TextBlob
}
entity ContactType {
  name String required
}
entity ExtendedUser
entity ReferralType {
  name String required
}
entity ReferralSource {
  name String required
}
entity ActionType {
  name String
}
entity ActionSubType {
  name String
}
entity ActionStatus {
  name String
}
entity ContactSubType {
  name String required unique
}
relationship OneToOne {
  SupportCoordinator{department(name) required} to Department,
  SupportCoordinator{employeeType(name) required} to EmployeeType,
  SupportCoordinator{employeeSubType(name) required} to EmployeeSubType,
  ExtendedUser{department(name)} to Department,
  ExtendedUser{employeeType(name)} to EmployeeType,
  ExtendedUser{employeeSubType(name)} to EmployeeSubType,
  ExtendedUser{user} to User
}
relationship ManyToOne {
  Participant{contactStatus(name)} to ContactStatus,
  Participant{contactSubStatus(name)} to ContactSubStatus,
  Participant{mco(name)} to MCO,
  Participant{referralType(name)} to ReferralType,
  Participant{referralSource(name)} to ReferralSource,
  Participant{assignedTo(login)} to User,
  Action{participant(firstName)} to Participant,
  Action{user(login)} to User,
  Action{actionSubType(name)} to ActionSubType,
  Action{actionType(name)} to ActionType,
  Action{actionStatus(name)} to ActionStatus,
  ContactSubStatus{subTypeOf(name) required} to ContactStatus,
  ContactHistory{participant(firstName)} to Participant,
  ContactHistory{user(login)} to User,
  ContactHistory{contactType(name)} to ContactType,
  ContactHistory{contactSubType(name) required} to ContactSubType,
  ParticipantNotes{user(login)} to User,
  ParticipantNotes{participant(firstName) required} to Participant,
  ActionSubType{subTypeOf(name)} to ActionType
}

dto Participant, Action, SupportCoordinator, Waiver, Department, EmployeeType, EmployeeSubType, ContactStatus, ContactSubStatus, Priority, MCO, Physician, EnrollmentAgency, ContactHistory, ParticipantNotes, ContactType, ExtendedUser, ReferralType, ReferralSource, ActionType, ActionSubType, ActionStatus, ContactSubType with mapstruct
paginate Participant, SupportCoordinator with infinite-scroll
service Participant, Action, SupportCoordinator, Waiver, Department, EmployeeType, EmployeeSubType, ContactStatus, ContactSubStatus, Priority, MCO, Physician, EnrollmentAgency, ContactHistory, ParticipantNotes, ContactType, ExtendedUser, ReferralType, ReferralSource, ActionType, ActionSubType, ActionStatus, ContactSubType with serviceImpl

</pre>
</details>


##### **Environment and Tools**

openjdk version "1.8.0_191"
OpenJDK Runtime Environment (build 1.8.0_191-8u191-b12-0ubuntu0.18.04.1-b12)
OpenJDK 64-Bit Server VM (build 25.191-b12, mixed mode)

git version 2.17.1

node: v10.14.1

npm: 6.5.0

yeoman: 2.0.5

yarn: 1.12.3

Docker version 18.09.0, build 4d60db4

docker-compose version 1.23.2, build 1110ad01

```

-   [x ] Checking this box is mandatory (this is just to show you read everything)

**Comment by pascalgrimaud** [comment]
It looks like the same issue than https://github.com/jhipster/generator-jhipster/issues/9202
It will be fixed by https://github.com/jhipster/jhipster-core/pull/304

That's why I'm closing this.
Thanks for reporting this.
