### ISSUE TITLE
Unable to start project generated using Jhipster in STS / Eclipse

### ISSUE THREAD

**Issue by amolpshinde07** [jhipster/generator-jhipster#9366]
##### **Overview of the issue**

I have created project using jhipster. I am able to run it using gradlew command but when I am trying to run it from eclipse then it throws below error and exists

`2019-03-03 18:38:29.955 DEBUG 5244 --- [  restartedMain] c.ehcache.core.Ehcache-usersByEmail      : Close successful.
2019-03-03 18:38:29.956 DEBUG 5244 --- [  restartedMain] c.ehcache.core.Ehcache-usersByLogin      : Close successful.
18:38:30.698 [restartedMain] ERROR org.springframework.boot.SpringApplication - Application run failed
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'companyService' defined in file [C:\Users\amolpshinde07\zWorkspace\clinic_mgmt\bin\main\com\clinic\app\service\CompanyService.class]: Unsatisfied dependency expressed through constructor parameter 1; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'com.clinic.app.service.mapper.CompanyMapper' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {}
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:733) ~[spring-beans-5.0.12.RELEASE.jar:5.0.12.RELEASE]
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:198) ~[spring-beans-5.0.12.RELEASE.jar:5.0.12.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1266) ~[spring-beans-5.0.12.RELEASE.jar:5.0.12.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1123) ~[spring-beans-5.0.12.RELEASE.jar:5.0.12.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:535) ~[spring-beans-5.0.12.RELEASE.jar:5.0.12.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:495) ~[spring-beans-5.0.12.RELEASE.jar:5.0.12.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:317) ~[spring-beans-5.0.12.RELEASE.jar:5.0.12.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222) ~[spring-beans-5.0.12.RELEASE.jar:5.0.12.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:315) ~[spring-beans-5.0.12.RELEASE.jar:5.0.12.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199) ~[spring-beans-5.0.12.RELEASE.jar:5.0.12.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:759) ~[spring-beans-5.0.12.RELEASE.jar:5.0.12.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:867) ~[spring-context-5.0.12.RELEASE.jar:5.0.12.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:548) ~[spring-context-5.0.12.RELEASE.jar:5.0.12.RELEASE]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:142) ~[spring-boot-2.0.8.RELEASE.jar:2.0.8.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:754) [spring-boot-2.0.8.RELEASE.jar:2.0.8.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:386) [spring-boot-2.0.8.RELEASE.jar:2.0.8.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:307) [spring-boot-2.0.8.RELEASE.jar:2.0.8.RELEASE]
	at com.clinic.app.ClinicMgmtApp.main(ClinicMgmtApp.java:65) [main/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_191]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_191]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_191]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_191]
	at org.springframework.boot.devtools.restart.RestartLauncher.run(RestartLauncher.java:49) [spring-boot-devtools-2.0.8.RELEASE.jar:2.0.8.RELEASE]
Caused by: org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'com.clinic.app.service.mapper.CompanyMapper' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {}
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.raiseNoMatchingBeanFound(DefaultListableBeanFactory.java:1506) ~[spring-beans-5.0.12.RELEASE.jar:5.0.12.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1101) ~[spring-beans-5.0.12.RELEASE.jar:5.0.12.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1062) ~[spring-beans-5.0.12.RELEASE.jar:5.0.12.RELEASE]
	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:819) ~[spring-beans-5.0.12.RELEASE.jar:5.0.12.RELEASE]
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:725) ~[spring-beans-5.0.12.RELEASE.jar:5.0.12.RELEASE]
	... 22 more`

##### **JHipster Version(s)**
5.8.1

##### **JHipster configuration**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
    "generator-jhipster": {
        "promptValues": {
            "packageName": "com.clinic.app",
            "nativeLanguage": "en"
        },
        "jhipsterVersion": "5.8.1",
        "applicationType": "monolith",
        "baseName": "clinic_mgmt",
        "packageName": "com.clinic.app",
        "packageFolder": "com/clinic/app",
        "serverPort": "8080",
        "authenticationType": "jwt",
        "cacheProvider": "ehcache",
        "enableHibernateCache": false,
        "websocket": false,
        "databaseType": "sql",
        "devDatabaseType": "h2Disk",
        "prodDatabaseType": "postgresql",
        "searchEngine": "elasticsearch",
        "messageBroker": false,
        "serviceDiscoveryType": "eureka",
        "buildTool": "gradle",
        "enableSwaggerCodegen": false,
        "clientFramework": "angularX",
        "useSass": true,
        "clientPackageManager": "npm",
        "testFrameworks": ["protractor"],
        "jhiPrefix": "jhi",
        "entitySuffix": "",
        "dtoSuffix": "DTO",
        "otherModules": [],
        "enableTranslation": true,
        "nativeLanguage": "en",
        "languages": ["en", "hi", "mr"]
    }
}

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in
 the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity PaymentRecipt {
  payee ReceiptEntity required,
  recipient ReceiptEntity required,
  payeeId Long required,
  recipientId Long required,
  amount Float required,
  paymentMode PaymentMode required,
  description String
}
entity Person {
  personType PersonType required,
  name String required,
  address String required minlength(5) maxlength(50),
  mobileNo String required minlength(10) maxlength(13) pattern(/[0-9]+/),
  emailId String
}
entity Company {
  companyName String required,
  address String required minlength(1) maxlength(50) pattern(/[A-Z]+/),
  mobileNo String required minlength(10) maxlength(10) pattern(/[0-9]+/),
  panNumber String,
  gstNumber String,
  emailId String,
  bankAccountNo Long,
  bankIfscCode String,
  stateCode Integer
}
entity Product {
  name String required,
  modelNumber String required,
  mrp Float required,
  hsnCode String required,
  productType ProductType required
}
entity PurchaseInvoiceProduct {
  serialNumber String required minlength(10) maxlength(10),
  quantity Integer required,
  purchasePrice Float required,
  mrp Float required,
  hsnCode String required,
  status ProductStatus required,
  cgst Float required,
  sgst Float required,
  igst Float required,
  returnDate LocalDate,
  returnInvNo Long
}
entity PurchaseInvoice {
  invoiceDate LocalDate required,
  dueDate LocalDate,
  billNo Integer required,
  deliveryMode DeliveryType,
  paidAmount Float,
  otherCharges Float
}
entity ProductDetails {
  key String required,
  value String required
}
entity SalesDetails {
  key String required,
  value String required
}
entity PurchaseDetails {
  key String required,
  value String required
}
entity PersonDetails {
  key String required,
  value String required
}
entity PurchaseInvoiceDetails {
  key String required,
  value String required
}
entity SalesInvoiceDetails {
  key String required,
  value String required
}
entity SalesInvoiceProduct {
  salePrice Float required,
  cutPrice Float required,
  status SalesProductStatus required,
  quantity Integer,
  cgst Float required,
  sgst Float required,
  igst Float required
}
entity SalesInvoice {
  dueDate LocalDate,
  totalAmount Float,
  otherCharges Float,
  deliveryMode DeliveryType,
  returnDate LocalDate,
  returnInvNo Long
}
entity Therapy {
  therapyCharges Float required,
  comments String required minlength(10) maxlength(300),
  referalCut Float required,
  therapistCut Float required
}

enum ReceiptEntity {
  COMPANY,
  CLINIC,
  PATIENT,
  THERAPIST
}

enum PaymentMode {
  CASH,
  CHEQUE,
  NEFT,
  IMPS,
  RTGS,
  CC,
  DC,
  OTHER
}

enum PersonType {
  PATIENT,
  THERAPIST,
  REFERAL
}

enum ProductType {
  HEARING_SET,
  MODEL,
  BATTERY
}

enum ProductStatus {
  AVAILABLE,
  SOLD,
  USER_RETURNED,
  USER_EXCHANGE,
  FAULTY,
  COMPANY_RETURNED
}

enum DeliveryType {
  BY_HAND,
  COURIER
}

enum SalesProductStatus {
  SOLD,
  USER_RETURNED,
  USER_EXCHANGE
}

relationship OneToOne {
  PurchaseInvoiceProduct{product required} to Product,
  PurchaseInvoice{company required} to Company,
  SalesInvoiceProduct{product required} to PurchaseInvoiceProduct,
  SalesInvoiceProduct{patient required} to Person,
  SalesInvoiceProduct{referal required} to Person,
  SalesInvoice{customer required} to Person,
  Therapy{therapist required} to Person,
  Therapy{patient required} to Person,
  Therapy{referal required} to Person
}
relationship OneToMany {
  Company{products} to Product{company},
  PurchaseInvoice{products required} to PurchaseInvoiceProduct{purchaseInvoice},

  Product{details} to ProductDetails{product},
  SalesInvoiceProduct{details} to SalesDetails{salesInvoiceProduct},
  PurchaseInvoiceProduct{details} to PurchaseDetails{purchaseInvoiceProduct},
  Person{details} to PersonDetails{person},
  PurchaseInvoice{details} to PurchaseInvoiceDetails{purchaseInvoice},
  SalesInvoice{details} to SalesInvoiceDetails{salesInvoice},
  SalesInvoice{products required} to SalesInvoiceProduct{salesInvoice}
}

dto PaymentRecipt, Person, Company, Product, PurchaseInvoiceProduct, PurchaseInv
oice, ProductDetails, SalesDetails, PurchaseDetails, PersonDetails, PurchaseInvo
iceDetails, SalesInvoiceDetails, SalesInvoiceProduct, SalesInvoice, Therapy with
 mapstruct
paginate PaymentRecipt, Person, Company, Product, PurchaseInvoiceProduct, Purcha
seInvoice, ProductDetails, SalesDetails, PurchaseDetails, PersonDetails, Purchas
eInvoiceDetails, SalesInvoiceDetails, SalesInvoiceProduct, SalesInvoice, Therapy
 with pager
service PaymentRecipt, Person, Company, Product, PurchaseInvoiceProduct, Purchas
eInvoice, ProductDetails, SalesDetails, PurchaseDetails, PersonDetails, Purchase
InvoiceDetails, SalesInvoiceDetails, SalesInvoiceProduct, SalesInvoice, Therapy
with serviceClass

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_191"
Java(TM) SE Runtime Environment (build 1.8.0_191-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.191-b12, mixed mode)

git version 2.19.1.windows.1

node: v10.15.1

npm: 6.4.1

yeoman: 2.0.5

yarn: 1.10.1

INFO! Congratulations, JHipster execution is complete!

##### **Browsers and Operating System**

-   [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by pmverma** [comment]
Have you tried to configure your IDE for annotation processors? Running from command line will work because gradle will take care of it. But for running from IDE, you have to configure the IDE so that it take care of annotation processors.

This should be a question on stackoverflow.

**Comment by jdubois** [comment]
Yes this is an annotation processor issue, you should configure it in your IDE, have a look at:

https://www.jhipster.tech/configuring-ide/

And if the documentation there is not correct, please tell us so we can improve it.
