### ISSUE TITLE
Jhipster 5.8.1,MSSQL-2005,hibernate_sequence Error

### ISSUE THREAD

**Issue by jiangzhixiao** [jhipster/generator-jhipster#9399]
##### **Overview of the issue**

Jhipster 5.8.1 doesn't work  with MSSQL2008 Database

##### **Reproduce the error**

1:If chose  MSSQL,And I'm using MSSQL-2008 R2
2:I'm not generate Any Entity,
3:run gradlew in command line
4:visit the login page,input username:admin,password:admin
5:error happend

` 
Hibernate: select next value for hibernate_sequenceoke(NativeMethodAccessorImpl.java:62)
2019-03-08 22:50:21.920  WARN 3044 --- [ XNIO-2 task-15] o.h.engine.jdbc.spi.SqlExceptionHelper   : SQL Error: 102, SQLState: S0001
2019-03-08 22:50:21.920 ERROR 3044 --- [ XNIO-2 task-15] o.h.engine.jdbc.spi.SqlExceptionHelper   : 'hibernate_sequence' 附近有语法错误。
2019-03-08 22:50:21.923 ERROR 3044 --- [ XNIO-2 task-15] com.rmyy.pe.aop.logging.LoggingAspect    : Exception in com.rmyy.pe.repository.CustomAuditEventRepository.add() with cause = 'org.hibernate.exception.SQLGrammarException: could not extract ResultSet' and exception = 'could not extract ResultSet; SQL [n/a]; nested exception is org.hibernate.exception.SQLGrammarException: could not extract ResultSet'actorySupport$ImplementationMethodExecutionInterceptor.invoke(RepositoryFactorySupport.java:641)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185)
org.springframework.dao.InvalidDataAccessResourceUsageException: could not extract ResultSet; SQL [n/a]; nested exception is org.hibernate.exception.SQLGrammarException: could not extract ResultSetk.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.invoke(RepositoryFactorySupport.java:590)
        at org.springframework.orm.jpa.vendor.HibernateJpaDialect.convertHibernateAccessException(HibernateJpaDialect.java:240)
        at org.springframework.orm.jpa.vendor.HibernateJpaDialect.translateExceptionIfPossible(HibernateJpaDialect.java:223)rceptor.java:59)
        at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.translateExceptionIfPossible(AbstractEntityManagerFactoryBean.java:527)
        at org.springframework.dao.support.ChainedPersistenceExceptionTranslator.translateExceptionIfPossible(ChainedPersistenceExceptionTranslator.java:61)
        at org.springframework.dao.support.DataAccessUtils.translateIfNecessary(DataAccessUtils.java:242)or.java:98)
        at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:153)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185)nslationInterceptor.java:139)
        at org.springframework.data.jpa.repository.support.CrudMethodMetadataPostProcessor$CrudMethodMetadataPopulatingMethodInterceptor.invoke(CrudMethodMetadataPostProcessor.java:135)0% EXECUTING [3m 32s]c.SQLServerException: 'hibernate_sequence' 附近有语法错误。
`
##### **JHipster Version(s)**

5.8.1

##### **JHipster configuration**
{
    "generator-jhipster": {
        "promptValues": {
            "packageName": "com.rmyy.pe"
        },
        "jhipsterVersion": "5.8.1",
        "applicationType": "monolith",
        "baseName": "lygyy",
        "packageName": "com.rmyy.pe",
        "packageFolder": "com/rmyy/pe",
        "serverPort": "8080",
        "authenticationType": "jwt",
        "cacheProvider": "no",
        "websocket": false,
        "databaseType": "sql",
        "devDatabaseType": "mssql",
        "prodDatabaseType": "mssql",
        "searchEngine": false,
        "messageBroker": false,
        "serviceDiscoveryType": false,
        "buildTool": "gradle",
        "enableSwaggerCodegen": false,
        "jwtSecretKey": "OTk5MWYzNGQxNzJmZTRiZTJhYjU5YjFmZTQ3NmQ5YTcwYTdkYWE0NWMwNmE2NDUyNzgxYjlmZWYxYzU3MWZmN2IwODBhM2FjYzRiZWYyNzg1OGQwYzc0NDZmZDdmMjkzZWJiNDVlYjI3NDY4ZDhiNmI2MDZkZDNkMWQ3YmI3OWU=",
        "clientFramework": "angularX",
        "useSass": false,
        "clientPackageManager": "npm",
        "testFrameworks": [],
        "jhiPrefix": "jhi",
        "entitySuffix": "",
        "dtoSuffix": "DTO",
        "otherModules": [],
        "enableTranslation": false
    }
}

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**
I havent generated any Entity!

**Comment by PierreBesson** [comment]
@jiangzhixiao Did you check that the Liquibase migration worked properly ? Can you paste the logs of this part (from the start of the app). But I probably won't be able to help you as I don't know anything about MSSQL.

**Comment by jiangzhixiao** [comment]
@PierreBesson I think Liquibase worked succesfully!


```2019-03-09 08:44:14.401 DEBUG 12876 --- [  restartedMain] com.rmyy.pe.LygyyApp                     : Running with Spring Boot v2.0.8.RELEASE, Spring v5.0.12.RELEASE
2019-03-09 08:44:14.401  INFO 12876 --- [  restartedMain] com.rmyy.pe.LygyyApp                     : The following profiles are active: dev,swagger
2019-03-09 08:44:19.932 DEBUG 12876 --- [  restartedMain] com.rmyy.pe.config.AsyncConfiguration    : Creating Async Task Executor
2019-03-09 08:44:23.291 DEBUG 12876 --- [  restartedMain] c.rmyy.pe.config.LiquibaseConfiguration  : Configuring Liquibase
2019-03-09 08:44:24.400  WARN 12876 --- [ygyy-Executor-1] i.g.j.c.liquibase.AsyncSpringLiquibase   : Starting Liquibase asynchronously, your database might not be ready at startup!
2019-03-09 08:44:28.619 DEBUG 12876 --- [ygyy-Executor-1] i.g.j.c.liquibase.AsyncSpringLiquibase   : Liquibase has updated your database in 4187 ms
2019-03-09 08:44:29.900 DEBUG 12876 --- [  restartedMain] com.rmyy.pe.config.WebConfigurer         : Registering CORS filter
2019-03-09 08:44:30.056  INFO 12876 --- [  restartedMain] com.rmyy.pe.config.WebConfigurer         : Web application configuration, using profiles: dev
2019-03-09 08:44:30.056  INFO 12876 --- [  restartedMain] com.rmyy.pe.config.WebConfigurer         : Web application fully configured
2019-03-09 08:44:30.369 DEBUG 12876 --- [  restartedMain] com.rmyy.pe.security.jwt.TokenProvider   : Using a Base64-encoded JWT secret key
2019-03-09 08:44:34.525 DEBUG 12876 --- [  restartedMain] i.g.j.c.apidoc.SwaggerAutoConfiguration  : Starting Swagger
2019-03-09 08:44:34.587 DEBUG 12876 --- [  restartedMain] i.g.j.c.apidoc.SwaggerAutoConfiguration  : Started Swagger in 62 ms
2019-03-09 08:44:36.149  INFO 12876 --- [  restartedMain] com.rmyy.pe.LygyyApp                     : Started LygyyApp in 24.279 seconds (JVM running for 25.511)
2019-03-09 08:44:36.181  INFO 12876 --- [  restartedMain] com.rmyy.pe.LygyyApp                     :

        Application 'lygyy' is running! Access URLs:
        Local:          http://localhost:8080/
        External:       http://10.0.0.8:8080/
```

**Comment by jiangzhixiao** [comment]
ok,i resolved it!
just create table **hibernate_sequence**  by manual!
```
CREATE TABLE [dbo].[hibernate_sequence] (
  [next_val] int NULL,
  [sequence_name] varchar(255) COLLATE Chinese_PRC_CI_AS NULL
)
GO
```
so,i guess the liquibase not create this table，is it related to this ???
```
   <changeSet id="00000000000000" author="jhipster">
        <createSequence sequenceName="hibernate_sequence" startValue="1000" incrementBy="50"/>
    </changeSet>
```

@PierreBesson
