### ISSUE TITLE
jhipster app creation faild with jhipster cloudfounry  

### ISSUE THREAD

**Issue by cyrano007** [jhipster/generator-jhipster#9434]
##### **Overview of the issue**

burner:~/DEV/jh$ jhipster cloudfoundry
INFO! Using JHipster version installed globally
INFO! Executing jhipster:cloudfoundry
INFO! Options: from-cli: true
CloudFoundry configuration is starting
events.js:174
      throw er; // Unhandled 'error' event
      ^

TypeError: Cannot read property 'endsWith' of undefined
    at module.exports.getAngularAppName (/usr/lib/node_modules/generator-jhipster/generators/generator-base.js:1647:56)
    at module.exports.initializing (/usr/lib/node_modules/generator-jhipster/generators/cloudfoundry/index.js:46:36)
    at Object.<anonymous> (/usr/lib/node_modules/generator-jhipster/node_modules/yeoman-generator/lib/index.js:418:27)
    at /usr/lib/node_modules/generator-jhipster/node_modules/run-async/index.js:25:25
    at new Promise (<anonymous>)
    at /usr/lib/node_modules/generator-jhipster/node_modules/run-async/index.js:24:19
    at self.env.runLoop.add.completed (/usr/lib/node_modules/generator-jhipster/node_modules/yeoman-generator/lib/index.js:419:13)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
Emitted 'error' event at:
    at Immediate.setImmediate (/usr/lib/node_modules/generator-jhipster/node_modules/yeoman-generator/lib/index.js:427:22)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)

##### **Motivation for or Use Case**

i will create an app for cloudfoundry

##### **Reproduce the error**

jhipster cloudfoundry

##### **JHipster Version(s)**

INFO! Using JHipster version installed globally
5.8.2

##### **Browsers and Operating System**

-   [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by gmarziou** [comment]
> burner:~/DEV/jh$ jhipster cloudfoundry
> INFO! Using JHipster version installed globally

means that you are running `jhipster cloudfoundry` ,from a directory that has not jhipster installed cloally in local node_modules sub directory, this raises the question: did you first generate an app with `jhipster`command in this directory before running `jhipster cloudfoundry`sub generator ?
