### ISSUE TITLE
Upgrade sub generator: remove or not ?

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/generator-jhipster#9534]
##### **Overview of the issue**

The current `npm test` failed because of this: [upgrade.spec.js](https://github.com/jhipster/generator-jhipster/blob/master/test/upgrade.spec.js)

Here an extract of logs:

```
  712 passing (6m)
  3 failing
  1) JHipster upgrade generator
       default application
         creates expected files for default configuration:
      AssertionError [ERR_ASSERTION]: src/test/java/com/mycompany/myapp/web/rest/LogsResourceIT.java, no such file or directory
      + expected - actual
      -false
      +true
      
      at convertArgs.forEach.file (node_modules/yeoman-assert/index.js:56:12)
      at Array.forEach (<anonymous>)
      at Function.assert.file (node_modules/yeoman-assert/index.js:54:26)
      at Context.it (test/upgrade.spec.js:59:20)
  2) JHipster upgrade generator
       blueprint application
         creates expected files for default configuration:
      AssertionError [ERR_ASSERTION]: src/test/java/com/mycompany/myapp/web/rest/LogsResourceIT.java, no such file or directory
      + expected - actual
      -false
      +true
      
      at convertArgs.forEach.file (node_modules/yeoman-assert/index.js:56:12)
      at Array.forEach (<anonymous>)
      at Function.assert.file (node_modules/yeoman-assert/index.js:54:26)
      at Context.it (test/upgrade.spec.js:133:20)
  3) JHipster upgrade generator
       blueprint application
         generates expected number of commits:
      AssertionError: expected '3' to equal '5'
      + expected - actual
      -3
      +5
      
      at Context.it (test/upgrade.spec.js:146:37)

```

Here the `tmp` folder, with git conflicts:

```
22:22:11 in /tmp/d220f331997df7bae072fd614bdf8200f097a29a on   (git)-[master|merge]- [=✘»+] 
➜ gst
Sur la branche master
Vous avez des chemins non fusionnés.
  (réglez les conflits puis lancez "git commit")
  (utilisez "git merge --abort" pour annuler la fusion)

Modifications qui seront validées :

	modifié :         .editorconfig
	modifié :         .gitignore
	modifié :         .prettierignore
	modifié :         .prettierrc
	modifié :         README.md
	modifié :         pom.xml
	supprimé :        sonar-project.properties
	modifié :         src/main/docker/.dockerignore
	modifié :         src/main/docker/Dockerfile
	modifié :         src/main/docker/app.yml
	modifié :         src/main/docker/entrypoint.sh
	supprimé :        src/main/docker/grafana/provisioning/dashboards/JVM.json
	supprimé :        src/main/docker/grafana/provisioning/dashboards/dashboard.yml
	supprimé :        src/main/docker/grafana/provisioning/datasources/datasource.yml
	supprimé :        src/main/docker/monitoring.yml
	modifié :         src/main/docker/mysql.yml
	supprimé :        src/main/docker/prometheus/prometheus.yml
	modifié :         src/main/docker/sonar.yml
	modifié :         src/main/java/com/mycompany/myapp/ApplicationWebXml.java
	modifié :         src/main/java/com/mycompany/myapp/JhipsterApp.java
	modifié :         src/main/java/com/mycompany/myapp/aop/logging/LoggingAspect.java
	modifié :         src/main/java/com/mycompany/myapp/config/ApplicationProperties.java
	modifié :         src/main/java/com/mycompany/myapp/config/AsyncConfiguration.java
	modifié :         src/main/java/com/mycompany/myapp/config/CacheConfiguration.java
	modifié :         src/main/java/com/mycompany/myapp/config/DatabaseConfiguration.java
	modifié :         src/main/java/com/mycompany/myapp/config/DefaultProfileUtil.java
	modifié :         src/main/java/com/mycompany/myapp/config/JacksonConfiguration.java
	modifié :         src/main/java/com/mycompany/myapp/config/LiquibaseConfiguration.java
	modifié :         src/main/java/com/mycompany/myapp/config/LoggingConfiguration.java
	modifié :         src/main/java/com/mycompany/myapp/config/SecurityConfiguration.java
	modifié :         src/main/java/com/mycompany/myapp/config/WebConfigurer.java
	modifié :         src/main/java/com/mycompany/myapp/config/audit/AuditEventConverter.java
	modifié :         src/main/java/com/mycompany/myapp/domain/Authority.java
	modifié :         src/main/java/com/mycompany/myapp/domain/PersistentAuditEvent.java
	modifié :         src/main/java/com/mycompany/myapp/domain/User.java
	modifié :         src/main/java/com/mycompany/myapp/repository/AuthorityRepository.java
	modifié :         src/main/java/com/mycompany/myapp/repository/CustomAuditEventRepository.java
	modifié :         src/main/java/com/mycompany/myapp/repository/PersistenceAuditEventRepository.java
	modifié :         src/main/java/com/mycompany/myapp/repository/UserRepository.java
	modifié :         src/main/java/com/mycompany/myapp/security/SecurityUtils.java
	modifié :         src/main/java/com/mycompany/myapp/security/SpringSecurityAuditorAware.java
	modifié :         src/main/java/com/mycompany/myapp/security/jwt/TokenProvider.java
	modifié :         src/main/java/com/mycompany/myapp/service/AuditEventService.java
	modifié :         src/main/java/com/mycompany/myapp/service/MailService.java
	modifié :         src/main/java/com/mycompany/myapp/service/UserService.java
	modifié :         src/main/java/com/mycompany/myapp/service/mapper/UserMapper.java
	modifié :         src/main/java/com/mycompany/myapp/service/util/RandomUtil.java
	modifié :         src/main/java/com/mycompany/myapp/web/rest/AccountResource.java
	modifié :         src/main/java/com/mycompany/myapp/web/rest/AuditResource.java
	supprimé :        src/main/java/com/mycompany/myapp/web/rest/ClientForwardController.java
	modifié :         src/main/java/com/mycompany/myapp/web/rest/UserResource.java
	modifié :         src/main/java/com/mycompany/myapp/web/rest/errors/ExceptionTranslator.java
	nouveau fichier : src/main/java/com/mycompany/myapp/web/rest/util/HeaderUtil.java
	nouveau fichier : src/main/java/com/mycompany/myapp/web/rest/util/PaginationUtil.java
	modifié :         src/main/jib/entrypoint.sh
	modifié :         src/main/resources/config/application-dev.yml
	modifié :         src/main/resources/config/application-prod.yml
	modifié :         src/main/resources/config/application-tls.yml
	modifié :         src/main/resources/config/application.yml
	renommé :         src/main/resources/config/liquibase/data/authority.csv -> src/main/resources/config/liquibase/authorities.csv
	modifié :         src/main/resources/config/liquibase/changelog/00000000000000_initial_schema.xml
	modifié :         src/main/resources/config/liquibase/master.xml
	renommé :         src/main/resources/config/liquibase/data/user.csv -> src/main/resources/config/liquibase/users.csv
	renommé :         src/main/resources/config/liquibase/data/user_authority.csv -> src/main/resources/config/liquibase/users_authorities.csv
	modifié :         src/main/resources/logback-spring.xml
	modifié :         src/main/resources/templates/mail/activationEmail.html
	modifié :         src/main/resources/templates/mail/creationEmail.html
	modifié :         src/main/resources/templates/mail/passwordResetEmail.html
	modifié :         src/main/webapp/i18n/en/activate.json
	modifié :         src/main/webapp/i18n/en/audits.json
	modifié :         src/main/webapp/i18n/en/configuration.json
	modifié :         src/main/webapp/i18n/en/error.json
	modifié :         src/main/webapp/i18n/en/global.json
	modifié :         src/main/webapp/i18n/en/health.json
	modifié :         src/main/webapp/i18n/en/home.json
	modifié :         src/main/webapp/i18n/en/login.json
	modifié :         src/main/webapp/i18n/en/logs.json
	modifié :         src/main/webapp/i18n/en/metrics.json
	modifié :         src/main/webapp/i18n/en/password.json
	modifié :         src/main/webapp/i18n/en/register.json
	modifié :         src/main/webapp/i18n/en/reset.json
	modifié :         src/main/webapp/i18n/en/sessions.json
	modifié :         src/main/webapp/i18n/en/settings.json
	modifié :         src/main/webapp/i18n/en/user-management.json
	modifié :         src/main/webapp/i18n/fr/activate.json
	modifié :         src/main/webapp/i18n/fr/audits.json
	modifié :         src/main/webapp/i18n/fr/configuration.json
	modifié :         src/main/webapp/i18n/fr/error.json
	modifié :         src/main/webapp/i18n/fr/global.json
	modifié :         src/main/webapp/i18n/fr/health.json
	modifié :         src/main/webapp/i18n/fr/home.json
	modifié :         src/main/webapp/i18n/fr/login.json
	modifié :         src/main/webapp/i18n/fr/logs.json
	modifié :         src/main/webapp/i18n/fr/metrics.json
	modifié :         src/main/webapp/i18n/fr/password.json
	modifié :         src/main/webapp/i18n/fr/register.json
	modifié :         src/main/webapp/i18n/fr/reset.json
	modifié :         src/main/webapp/i18n/fr/sessions.json
	modifié :         src/main/webapp/i18n/fr/settings.json
	modifié :         src/main/webapp/i18n/fr/user-management.json
	modifié :         src/test/java/com/mycompany/myapp/config/WebConfigurerTest.java
	renommé :         src/test/java/com/mycompany/myapp/config/timezone/HibernateTimeZoneIT.java -> src/test/java/com/mycompany/myapp/config/timezone/HibernateTimeZoneTest.java
	renommé :         src/test/java/com/mycompany/myapp/repository/CustomAuditEventRepositoryIT.java -> src/test/java/com/mycompany/myapp/repository/CustomAuditEventRepositoryIntTest.java
	modifié :         src/test/java/com/mycompany/myapp/repository/timezone/DateTimeWrapperRepository.java
	renommé :         src/test/java/com/mycompany/myapp/security/DomainUserDetailsServiceIT.java -> src/test/java/com/mycompany/myapp/security/DomainUserDetailsServiceIntTest.java
	modifié :         src/test/java/com/mycompany/myapp/security/SecurityUtilsUnitTest.java
	modifié :         src/test/java/com/mycompany/myapp/security/jwt/TokenProviderTest.java
	renommé :         src/test/java/com/mycompany/myapp/service/MailServiceIT.java -> src/test/java/com/mycompany/myapp/service/MailServiceIntTest.java
	renommé :         src/test/java/com/mycompany/myapp/service/UserServiceIT.java -> src/test/java/com/mycompany/myapp/service/UserServiceIntTest.java
	renommé :         src/test/java/com/mycompany/myapp/service/mapper/UserMapperIT.java -> src/test/java/com/mycompany/myapp/service/mapper/UserMapperTest.java
	renommé :         src/test/java/com/mycompany/myapp/web/rest/AccountResourceIT.java -> src/test/java/com/mycompany/myapp/web/rest/AccountResourceIntTest.java
	renommé :         src/test/java/com/mycompany/myapp/web/rest/AuditResourceIT.java -> src/test/java/com/mycompany/myapp/web/rest/AuditResourceIntTest.java
	supprimé :        src/test/java/com/mycompany/myapp/web/rest/ClientForwardControllerIT.java
	renommé :         src/test/java/com/mycompany/myapp/web/rest/LogsResourceIT.java -> src/test/java/com/mycompany/myapp/web/rest/LogsResourceIntTest.java
	modifié :         src/test/java/com/mycompany/myapp/web/rest/TestUtil.java
	renommé :         src/test/java/com/mycompany/myapp/web/rest/UserJWTControllerIT.java -> src/test/java/com/mycompany/myapp/web/rest/UserJWTControllerIntTest.java
	renommé :         src/test/java/com/mycompany/myapp/web/rest/UserResourceIT.java -> src/test/java/com/mycompany/myapp/web/rest/UserResourceIntTest.java
	renommé :         src/test/java/com/mycompany/myapp/web/rest/errors/ExceptionTranslatorIT.java -> src/test/java/com/mycompany/myapp/web/rest/errors/ExceptionTranslatorIntTest.java
	modifié :         src/test/java/com/mycompany/myapp/web/rest/errors/ExceptionTranslatorTestController.java
	nouveau fichier : src/test/java/com/mycompany/myapp/web/rest/util/PaginationUtilUnitTest.java
	modifié :         src/test/resources/config/application.yml

Chemins non fusionnés :
  (utilisez "git add <fichier>..." pour marquer comme résolu)

	modifié des deux côtés :  .yo-rc.json


22:25:59 in /tmp/d220f331997df7bae072fd614bdf8200f097a29a on   (git)-[master|merge]- [=✘»+] 
```

##### **Motivation for or Use Case**

Each release, we have some `upgrade` issues.
It is impossible to test in advance, all use cases until the release, and now, we have a release with failed builds....

##### **Reproduce the error**

Launch `npm test` at the release commit v6.0.0.beta.0: https://github.com/jhipster/generator-jhipster/commit/c1c6ee7f21256477bf1c0265cafc8248cf2b1a6c

##### **Related issues**

https://github.com/jhipster/generator-jhipster/issues?q=is%3Aissue+label%3Aupgrade+is%3Aclosed

##### **Suggest a Fix**

I would suggest to simply remove the upgrade sub generator.
It was coded by a contributor, which didn't contribute any more and now, the team needs to maintain this, with all new issues at each release.

For me, it should go to a new project, using shell / bash, instead of yeoman/javascript, because it is used with git command.

@jhipster/developers : what do you think ? Should we keep this sub generator or not ?
On my part, I'm fed up with this sub gen.

**Comment by murdos** [comment]
I vote for keeping it, to my experience it's useful.
However I'm the guilty one that added this unit test when I worked on making this generator compatible with blueprint, I see no issue if you want to disable it. When I'll have some time, I may try to fix these edged cases.

**Comment by pascalgrimaud** [comment]
The test was added to try to secure this sub gen. So it is a very good thing, don't feel guilty.

**Comment by jdubois** [comment]
Yes I know about this, we had the same issue for JHipster 5 :-D
We should just disable it, until we have a stable 6.0.0 release, that's just a temporary issue. Or maybe we should change the check so it doesn't fail when it doesn't find its tag.

**Comment by pascalgrimaud** [comment]
Oh I think I understand. So the problem comes from the beta release !

**Comment by jdubois** [comment]
@pascalgrimaud yes, it tests if it can do the update, but does not find the release, as it's a beta (so it's hidden, you need to use the "beta" tag)

**Comment by pascalgrimaud** [comment]
As @murdos said, we need to find a way to disable this test until a final release, so the new pull requests won't fail

**Comment by deepu105** [comment]
Another idea is to detect version and support this subgen only for minor
version upgrades. If the someone tries to upgrade a major version we just
print an error saying major version upgrade is not supported. This way we
can save some headaches. WDYT?

Thanks & Regards,
Deepu
