### ISSUE TITLE
Incorrect fake data is being generated for blob

### ISSUE THREAD

**Issue by pmverma** [jhipster/generator-jhipster#9660]
##### **Overview of the issue**

When liquibase load image data, it fails due to type mismatch.

```
2019-05-04 14:48:30.932 ERROR 17765 --- [datatype-task-1] liquibase.changelog.ChangeSet            : Change Set config/liquibase/changelog/20190504073238_added_entity_Entity3.xml::20190504073238-1-data::jhipster failed.  Error: java.sql.BatchUpdateException: Batch entry 0 INSERT INTO public.entity3(id, my_image, my_image_content_type) VALUES(1, '486f6d65204c6f616e204163636f756e74205461626c6520436f6d7075746572', 'image/png') was aborted: ERROR: column "my_image" is of type bytea but expression is of type character varying
  Hint: You will need to rewrite or cast the expression.
  Position: 76  Call getNextException to see other errors in the batch.
2019-05-04 14:48:30.974 ERROR 17765 --- [datatype-task-1] i.g.j.c.liquibase.AsyncSpringLiquibase   : Liquibase could not start correctly, your database is NOT ready: Migration failed for change set config/liquibase/changelog/20190504073238_added_entity_Entity3.xml::20190504073238-1-data::jhipster:
     Reason: liquibase.exception.DatabaseException: java.sql.BatchUpdateException: Batch entry 0 INSERT INTO public.entity3(id, my_image, my_image_content_type) VALUES(1, '486f6d65204c6f616e204163636f756e74205461626c6520436f6d7075746572', 'image/png') was aborted: ERROR: column "my_image" is of type bytea but expression is of type character varying
  Hint: You will need to rewrite or cast the expression.
  Position: 76  Call getNextException to see other errors in the batch.

liquibase.exception.MigrationFailedException: Migration failed for change set config/liquibase/changelog/20190504073238_added_entity_Entity3.xml::20190504073238-1-data::jhipster:
     Reason: liquibase.exception.DatabaseException: java.sql.BatchUpdateException: Batch entry 0 INSERT INTO public.entity3(id, my_image, my_image_content_type) VALUES(1, '486f6d65204c6f616e204163636f756e74205461626c6520436f6d7075746572', 'image/png') was aborted: ERROR: column "my_image" is of type bytea but expression is of type character varying
  Hint: You will need to rewrite or cast the expression.
  Position: 76  Call getNextException to see other errors in the batch.
	at liquibase.changelog.ChangeSet.execute(ChangeSet.java:637)
	at liquibase.changelog.visitor.UpdateVisitor.visit(UpdateVisitor.java:53)
	at liquibase.changelog.ChangeLogIterator.run(ChangeLogIterator.java:83)
	at liquibase.Liquibase.update(Liquibase.java:202)
	at liquibase.Liquibase.update(Liquibase.java:179)
	at liquibase.integration.spring.SpringLiquibase.performUpdate(SpringLiquibase.java:353)
	at liquibase.integration.spring.SpringLiquibase.afterPropertiesSet(SpringLiquibase.java:305)
	at io.github.jhipster.config.liquibase.AsyncSpringLiquibase.initDb(AsyncSpringLiquibase.java:100)
	at io.github.jhipster.config.liquibase.AsyncSpringLiquibase.lambda$afterPropertiesSet$0(AsyncSpringLiquibase.java:80)
	at io.github.jhipster.async.ExceptionHandlingAsyncTaskExecutor.lambda$createWrappedRunnable$1(ExceptionHandlingAsyncTaskExecutor.java:68)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: liquibase.exception.DatabaseException: java.sql.BatchUpdateException: Batch entry 0 INSERT INTO public.entity3(id, my_image, my_image_content_type) VALUES(1, '486f6d65204c6f616e204163636f756e74205461626c6520436f6d7075746572', 'image/png') was aborted: ERROR: column "my_image" is of type bytea but expression is of type character varying
  Hint: You will need to rewrite or cast the expression.
  Position: 76  Call getNextException to see other errors in the batch.
	at liquibase.statement.ExecutablePreparedStatementBase.execute(ExecutablePreparedStatementBase.java:86)
	at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:115)
	at liquibase.database.AbstractJdbcDatabase.execute(AbstractJdbcDatabase.java:1229)
	at liquibase.database.AbstractJdbcDatabase.executeStatements(AbstractJdbcDatabase.java:1211)
	at liquibase.changelog.ChangeSet.execute(ChangeSet.java:600)
	... 12 common frames omitted
Caused by: java.sql.BatchUpdateException: Batch entry 0 INSERT INTO public.entity3(id, my_image, my_image_content_type) VALUES(1, '486f6d65204c6f616e204163636f756e74205461626c6520436f6d7075746572', 'image/png') was aborted: ERROR: column "my_image" is of type bytea but expression is of type character varying
  Hint: You will need to rewrite or cast the expression.
  Position: 76  Call getNextException to see other errors in the batch.
	at org.postgresql.jdbc.BatchResultHandler.handleError(BatchResultHandler.java:148)
	at org.postgresql.core.ResultHandlerDelegate.handleError(ResultHandlerDelegate.java:50)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2184)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:481)
	at org.postgresql.jdbc.PgStatement.executeBatch(PgStatement.java:840)
	at org.postgresql.jdbc.PgPreparedStatement.executeBatch(PgPreparedStatement.java:1538)
	at com.zaxxer.hikari.pool.ProxyStatement.executeBatch(ProxyStatement.java:128)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeBatch(HikariProxyPreparedStatement.java)
	at liquibase.statement.BatchDmlExecutablePreparedStatement.executePreparedStatement(BatchDmlExecutablePreparedStatement.java:65)
	at liquibase.statement.ExecutablePreparedStatementBase.execute(ExecutablePreparedStatementBase.java:84)
	... 16 common frames omitted
Caused by: org.postgresql.util.PSQLException: ERROR: column "my_image" is of type bytea but expression is of type character varying
  Hint: You will need to rewrite or cast the expression.
  Position: 76
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2440)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2183)
	... 23 common frames omitted

```
When I change column data type from

`            <column name="my_image" type="string"/>
`
to 
`            <column name="my_image" type="blob"/>
`, 
it expects some local file to be loaded.

```
2019-05-04 14:55:00.465 ERROR 18061 --- [datatype-task-1] liquibase.changelog.ChangeSet            : Change Set config/liquibase/changelog/20190504073238_added_entity_Entity3.xml::20190504073238-1-data::jhipster failed.  Error: class path resource [config/liquibase/changelog/486f6d65204c6f616e204163636f756e74205461626c6520436f6d7075746572] cannot be resolved to URL because it does not exist
2019-05-04 14:55:00.515 ERROR 18061 --- [datatype-task-1] i.g.j.c.liquibase.AsyncSpringLiquibase   : Liquibase could not start correctly, your database is NOT ready: Migration failed for change set config/liquibase/changelog/20190504073238_added_entity_Entity3.xml::20190504073238-1-data::jhipster:
     Reason: liquibase.exception.DatabaseException: class path resource [config/liquibase/changelog/486f6d65204c6f616e204163636f756e74205461626c6520436f6d7075746572] cannot be resolved to URL because it does not exist

liquibase.exception.MigrationFailedException: Migration failed for change set config/liquibase/changelog/20190504073238_added_entity_Entity3.xml::20190504073238-1-data::jhipster:
     Reason: liquibase.exception.DatabaseException: class path resource [config/liquibase/changelog/486f6d65204c6f616e204163636f756e74205461626c6520436f6d7075746572] cannot be resolved to URL because it does not exist
	at liquibase.changelog.ChangeSet.execute(ChangeSet.java:637)
	at liquibase.changelog.visitor.UpdateVisitor.visit(UpdateVisitor.java:53)
	at liquibase.changelog.ChangeLogIterator.run(ChangeLogIterator.java:83)
	at liquibase.Liquibase.update(Liquibase.java:202)
	at liquibase.Liquibase.update(Liquibase.java:179)
	at liquibase.integration.spring.SpringLiquibase.performUpdate(SpringLiquibase.java:353)
	at liquibase.integration.spring.SpringLiquibase.afterPropertiesSet(SpringLiquibase.java:305)
	at io.github.jhipster.config.liquibase.AsyncSpringLiquibase.initDb(AsyncSpringLiquibase.java:100)
	at io.github.jhipster.config.liquibase.AsyncSpringLiquibase.lambda$afterPropertiesSet$0(AsyncSpringLiquibase.java:80)
	at io.github.jhipster.async.ExceptionHandlingAsyncTaskExecutor.lambda$createWrappedRunnable$1(ExceptionHandlingAsyncTaskExecutor.java:68)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: liquibase.exception.DatabaseException: class path resource [config/liquibase/changelog/486f6d65204c6f616e204163636f756e74205461626c6520436f6d7075746572] cannot be resolved to URL because it does not exist
	at liquibase.statement.ExecutablePreparedStatementBase.applyColumnParameter(ExecutablePreparedStatementBase.java:184)
	at liquibase.statement.ExecutablePreparedStatementBase.attachParams(ExecutablePreparedStatementBase.java:111)
	at liquibase.statement.BatchDmlExecutablePreparedStatement.attachParams(BatchDmlExecutablePreparedStatement.java:51)
	at liquibase.statement.ExecutablePreparedStatementBase.execute(ExecutablePreparedStatementBase.java:82)
	at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:115)
	at liquibase.database.AbstractJdbcDatabase.execute(AbstractJdbcDatabase.java:1229)
	at liquibase.database.AbstractJdbcDatabase.executeStatements(AbstractJdbcDatabase.java:1211)
	at liquibase.changelog.ChangeSet.execute(ChangeSet.java:600)
	... 12 common frames omitted
Caused by: java.io.FileNotFoundException: class path resource [config/liquibase/changelog/486f6d65204c6f616e204163636f756e74205461626c6520436f6d7075746572] cannot be resolved to URL because it does not exist
	at org.springframework.core.io.ClassPathResource.getURL(ClassPathResource.java:195)
	at liquibase.integration.spring.SpringLiquibase$SpringResourceOpener.getResourcesAsStream(SpringLiquibase.java:599)
	at liquibase.statement.ExecutablePreparedStatementBase.getResourceAsStream(ExecutablePreparedStatementBase.java:286)
	at liquibase.statement.ExecutablePreparedStatementBase.toBinaryStream(ExecutablePreparedStatementBase.java:206)
	at liquibase.statement.ExecutablePreparedStatementBase.applyColumnParameter(ExecutablePreparedStatementBase.java:177)
	... 19 common frames omitted

```

##### **Motivation for or Use Case**

Fake data should be generated and loaded correctly.

##### **Reproduce the error**

1. Generate an app
2. Generate an entity with a blog->image field
3. Start the app

~~I havn't tried other sub types which are under blog (during question) but guess it will be similar situation.~~

##### **Related issues**

#9654 

##### **Suggest a Fix**

- 

##### **JHipster Version(s)**

```
datatype@0.0.0 /Users/sierra/github/temp/datatype
└── generator-jhipster@6.0.0 

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.mycompany.myapp"
    },
    "jhipsterVersion": "6.0.0",
    "applicationType": "monolith",
    "baseName": "datatype",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "no",
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "postgresql",
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "bXktc2VjcmV0LXRva2VuLXRvLWNoYW5nZS1pbi1wcm9kdWN0aW9uLWFuZC10by1rZWVwLWluLWEtc2VjdXJlLXBsYWNl",
    "clientFramework": "angularX",
    "clientTheme": "none",
    "clientThemeVariant": "",
    "useSass": true,
    "clientPackageManager": "npm",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [],
    "enableTranslation": false
  }
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity Entity1 {
  name String
}
entity Entity2 {
  name String
}
entity Entity3 {
  myImage ImageBlob required
}
relationship ManyToOne {
  Entity2{entity1(name) required} to Entity1
}

dto Entity1, Entity2, Entity3 with mapstruct
service Entity1, Entity2, Entity3 with serviceImpl

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_172"
Java(TM) SE Runtime Environment (build 1.8.0_172-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.172-b11, mixed mode)

git version 2.20.1 (Apple Git-117)

node: v10.14.2

npm: 6.7.0

yeoman: 2.0.6

Docker version 18.09.1, build 4c52b90

docker-compose version 1.23.2, build 1110ad01

##### **Browsers and Operating System**

-   [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by pmverma** [comment]
I am trying to fix this issue but thought to put a note here first.

For blob, we have three categories: `image, any, text`
Let's say I have following fake data record,
```
id;my_image;my_image_content_type;my_any;my_any_content_type;my_text

1;486f6d65204c6f616e204163636f756e74205461626c6520436f6d7075746572;image/png;536176696e6773204163636f756e7420616c61726d;image/png;54617374

```
1. To load `image` data I had to put an image file named `486f6d65204c6f616e204163636f756e74205461626c6520436f6d7075746572` under `changelog` folder and it will picked up. I believe path can be changed but have not tested yet.

1. To load `any` data, it is same as above

1. To load `text` data, it is same as above. But have following db specific issue.

Postgres is not same as other databases. Postgres stores the actual text somewhere and store its `long` reference value in the column.
FYI http://www.solewing.org/blog/2015/08/hibernate-postgresql-and-lob-string/. For now, think opposite of that blog - insert using sql and load using hibernate.

Example content of `54617374` file
```
This is a very large text
```
So if we insert some text using native sql without using hibernate(which I believe liquibase is doing same way), insertion will be fine but loading the same data using hibernate is throwing following error.

```
Caused by: org.hibernate.exception.DataException: could not execute query
	at org.hibernate.exception.internal.SQLStateConversionDelegate.convert(SQLStateConversionDelegate.java:118)
	at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:42)
	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:113)
	at org.hibernate.loader.Loader.doList(Loader.java:2692)
	at org.hibernate.loader.Loader.doList(Loader.java:2672)
	at org.hibernate.loader.Loader.listIgnoreQueryCache(Loader.java:2506)
	at org.hibernate.loader.Loader.list(Loader.java:2501)
	at org.hibernate.loader.hql.QueryLoader.list(QueryLoader.java:504)
	at org.hibernate.hql.internal.ast.QueryTranslatorImpl.list(QueryTranslatorImpl.java:395)
	at org.hibernate.engine.query.spi.HQLQueryPlan.performList(HQLQueryPlan.java:220)
	at org.hibernate.internal.SessionImpl.list(SessionImpl.java:1507)
	at org.hibernate.query.internal.AbstractProducedQuery.doList(AbstractProducedQuery.java:1537)
	at org.hibernate.query.internal.AbstractProducedQuery.list(AbstractProducedQuery.java:1505)
	at org.hibernate.query.Query.getResultList(Query.java:132)
	at org.hibernate.query.criteria.internal.compile.CriteriaQueryTypeQueryAdapter.getResultList(CriteriaQueryTypeQueryAdapter.java:74)
	at org.springframework.data.jpa.repository.support.SimpleJpaRepository.findAll(SimpleJpaRepository.java:306)
	at org.springframework.data.jpa.repository.support.SimpleJpaRepository.findAll(SimpleJpaRepository.java:73)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.data.repository.core.support.RepositoryComposition$RepositoryFragments.invoke(RepositoryComposition.java:359)
	at org.springframework.data.repository.core.support.RepositoryComposition.invoke(RepositoryComposition.java:200)
	at org.springframework.data.repository.core.support.RepositoryFactorySupport$ImplementationMethodExecutionInterceptor.invoke(RepositoryFactorySupport.java:644)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.doInvoke(RepositoryFactorySupport.java:608)
	at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.lambda$invoke$3(RepositoryFactorySupport.java:595)
	at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.invoke(RepositoryFactorySupport.java:595)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.data.projection.DefaultMethodInvokingMethodInterceptor.invoke(DefaultMethodInvokingMethodInterceptor.java:59)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:294)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:98)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:139)
	... 165 common frames omitted
Caused by: org.postgresql.util.PSQLException: Bad value for type long : This is a very large text
	at org.postgresql.jdbc.PgResultSet.toLong(PgResultSet.java:2873)
	at org.postgresql.jdbc.PgResultSet.getLong(PgResultSet.java:2099)
	at org.postgresql.jdbc.PgResultSet.getClob(PgResultSet.java:459)
	at org.postgresql.jdbc.PgResultSet.getClob(PgResultSet.java:445)
	at com.zaxxer.hikari.pool.HikariProxyResultSet.getClob(HikariProxyResultSet.java)
	at org.hibernate.type.descriptor.sql.ClobTypeDescriptor$1.doExtract(ClobTypeDescriptor.java:44)
	at org.hibernate.type.descriptor.sql.BasicExtractor.extract(BasicExtractor.java:47)
	at org.hibernate.type.AbstractStandardBasicType.nullSafeGet(AbstractStandardBasicType.java:257)
	at org.hibernate.type.AbstractStandardBasicType.nullSafeGet(AbstractStandardBasicType.java:253)
	at org.hibernate.type.AbstractStandardBasicType.nullSafeGet(AbstractStandardBasicType.java:243)
	at org.hibernate.type.AbstractStandardBasicType.hydrate(AbstractStandardBasicType.java:329)
	at org.hibernate.persister.entity.AbstractEntityPersister.hydrate(AbstractEntityPersister.java:3010)
	at org.hibernate.loader.Loader.loadFromResultSet(Loader.java:1746)
	at org.hibernate.loader.Loader.instanceNotYetLoaded(Loader.java:1672)
	at org.hibernate.loader.Loader.getRow(Loader.java:1561)
	at org.hibernate.loader.Loader.getRowFromResultSet(Loader.java:731)
	at org.hibernate.loader.Loader.processResultSet(Loader.java:990)
	at org.hibernate.loader.Loader.doQuery(Loader.java:948)
	at org.hibernate.loader.Loader.doQueryAndInitializeNonLazyCollections(Loader.java:340)
	at org.hibernate.loader.Loader.doList(Loader.java:2689)
	... 196 common frames omitted

```

Loading `image` and `any` blob types can be fixed using local files but there will be **many files** depending on the entities.
For `text` I have not tested other DB than Postgres. For postgres also I don't currently have any idea to sync the column value between sql and hibernate.
@jhipster/developers I need your suggestions here.

**Comment by pascalgrimaud** [comment]
As we know there are some issues with Faker.js, shouldn't we regroup this ticket in https://github.com/jhipster/generator-jhipster/issues/9579 ?

**Comment by pmverma** [comment]
Yes, I think #9579, #9660, #9665 can be regroup and fixed together.
