### ISSUE TITLE
ClassNotFoundException for EndpointMBean, DataEndpointMBean and LiveBeansView 

### ISSUE THREAD

**Issue by sometxdude** [jhipster/generator-jhipster#9723]
I am getting ClassNotFoundExceptions when running a freshly generated, unmodified JHipster project on Windows using JDK 11.0.3

 EndpointMBean, DataEndpointMBean and LiveBeansView are all showing up as class not found
when running ./gradlew.bat

This could be a Spring Boot issue that was raised here by someone else:
https://github.com/spring-projects/spring-boot/issues/16806

Code to reproduce the issue is at https://github.com/sometxdude/issue-16806-example

Its not a showstopper as the app still functions, but the stacktraces litter up the console pretty bad.

An example stacktrace:
`java.lang.ClassNotFoundException: org/springframework/boot/actuate/endpoint/jmx/EndpointMBean
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:398)
	at java.management/com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.isInstanceOf(DefaultMBeanServerInterceptor.java:1394)
	at java.management/com.sun.jmx.mbeanserver.JmxMBeanServer.isInstanceOf(JmxMBeanServer.java:1091)
	at java.management/javax.management.InstanceOfQueryExp.apply(InstanceOfQueryExp.java:107)
	at java.management/javax.management.OrQueryExp.apply(OrQueryExp.java:97)
	at java.management/javax.management.OrQueryExp.apply(OrQueryExp.java:97)
	at java.management/com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.objectNamesFromFilteredNamedObjects(DefaultMBeanServerInterceptor.java:1496)
	at java.management/com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.queryNamesImpl(DefaultMBeanServerInterceptor.java:560)
	at java.management/com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.queryNames(DefaultMBeanServerInterceptor.java:550)
	at java.management/com.sun.jmx.mbeanserver.JmxMBeanServer.queryNames(JmxMBeanServer.java:619)
	at java.management.rmi/javax.management.remote.rmi.RMIConnectionImpl.doOperation(RMIConnectionImpl.java:1485)
	at java.management.rmi/javax.management.remote.rmi.RMIConnectionImpl$PrivilegedOperation.run(RMIConnectionImpl.java:1307)
	at java.management.rmi/javax.management.remote.rmi.RMIConnectionImpl.doPrivilegedOperation(RMIConnectionImpl.java:1399)
	at java.management.rmi/javax.management.remote.rmi.RMIConnectionImpl.queryNames(RMIConnectionImpl.java:570)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at java.rmi/sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:359)
	at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:200)
	at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:197)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.rmi/sun.rmi.transport.Transport.serviceCall(Transport.java:196)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:562)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:796)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:677)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:676)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)`

**Comment by pascalgrimaud** [comment]
It's very nice to have the code on GitHub.
But can you post your `jhipster info` too ? So we have your tools and configuration too, to try to reproduce.

Thanks in advance

**Comment by sometxdude** [comment]
I wasn't aware of that command.  That's a keeper.  Here is the output:

INFO! Using JHipster version installed locally in current project's node_modules
INFO! Executing jhipster:info
INFO! Options: from-cli: true
##### **JHipster Version(s)**

```
foobar@0.0.0 C:\Users\tjklm\workspace\foobar
`-- generator-jhipster@6.0.0 

```


##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**


<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.foobar"
    },
    "jhipsterVersion": "6.0.0",
    "applicationType": "monolith",
    "baseName": "foobar",
    "packageName": "com.foobar",
    "packageFolder": "com/foobar",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "gradle",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "bXktc2VjcmV0LXRva2VuLXRvLWNoYW5nZS1pbi1wcm9kdWN0aW9uLWFuZC10by1rZWVwLWluLWEtc2VjdXJlLXBsYWNl",
    "clientFramework": "react",
    "clientTheme": "none",
    "clientThemeVariant": "",
    "useSass": true,
    "clientPackageManager": "npm",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [],
    "enableTranslation": false
  }
}

</pre>
</details>


##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>


##### **Environment and Tools**

java version "11.0.3" 2019-04-16 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.3+12-LTS)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.3+12-LTS, mixed mode)

git version 2.21.0.windows.1

node: v10.15.3

npm: 6.4.1

INFO! Congratulations, JHipster execution is complete!

**Comment by pascalgrimaud** [comment]
I tried to reproduce your issue but didn't manage.
Everything works fine with JDK11 for me.

Here what I did:
- start a Docker container with JDK11: `docker run --rm -it jhipster/jhipster:v6.0.1 bash`
- once inside the container, clone your project: `git clone https://github.com/sometxdude/issue-16806-example`
- `cd issue-16806-example/`
- `chmod +x gradlew`
- `./gradlew`

Here the output logs:

```jhipster@7d1627284eec:~/app/issue-16806-example$ ll
total 776
drwxr-xr-x 6 jhipster jhipster   4096 May 13 17:00 ./
drwxr-xr-x 3 jhipster jhipster   4096 May 13 17:00 ../
-rw-r--r-- 1 jhipster jhipster    465 May 13 17:00 .editorconfig
drwxr-xr-x 8 jhipster jhipster   4096 May 13 17:00 .git/
-rw-r--r-- 1 jhipster jhipster   3353 May 13 17:00 .gitattributes
-rw-r--r-- 1 jhipster jhipster   1937 May 13 17:00 .gitignore
-rw-r--r-- 1 jhipster jhipster     54 May 13 17:00 .huskyrc
-rw-r--r-- 1 jhipster jhipster     43 May 13 17:00 .prettierignore
-rw-r--r-- 1 jhipster jhipster    174 May 13 17:00 .prettierrc
-rw-r--r-- 1 jhipster jhipster   1151 May 13 17:00 .yo-rc.json
-rw-r--r-- 1 jhipster jhipster   6586 May 13 17:00 README.md
-rw-r--r-- 1 jhipster jhipster  10049 May 13 17:00 build.gradle
drwxr-xr-x 3 jhipster jhipster   4096 May 13 17:00 gradle/
-rw-r--r-- 1 jhipster jhipster   2388 May 13 17:00 gradle.properties
-rwxr-xr-x 1 jhipster jhipster   5305 May 13 17:00 gradlew*
-rw-r--r-- 1 jhipster jhipster   2269 May 13 17:00 gradlew.bat
-rw-r--r-- 1 jhipster jhipster 664693 May 13 17:00 package-lock.json
-rw-r--r-- 1 jhipster jhipster   5192 May 13 17:00 package.json
-rw-r--r-- 1 jhipster jhipster     67 May 13 17:00 postcss.config.js
-rw-r--r-- 1 jhipster jhipster     28 May 13 17:00 settings.gradle
-rw-r--r-- 1 jhipster jhipster   2338 May 13 17:00 sonar-project.properties
drwxr-xr-x 4 jhipster jhipster   4096 May 13 17:00 src/
-rw-r--r-- 1 jhipster jhipster    858 May 13 17:00 tsconfig.json
-rw-r--r-- 1 jhipster jhipster    126 May 13 17:00 tsconfig.test.json
-rw-r--r-- 1 jhipster jhipster   5538 May 13 17:00 tslint.json
drwxr-xr-x 2 jhipster jhipster   4096 May 13 17:00 webpack/
jhipster@7d1627284eec:~/app/issue-16806-example$ ./gradlew 
Downloading https://services.gradle.org/distributions/gradle-5.4.1-bin.zip
...................................................................................

Welcome to Gradle 5.4.1!

Here are the highlights of this release:
 - Run builds with JDK12
 - New API for Incremental Tasks
 - Updates to native projects, including Swift 5 support

For more details see https://docs.gradle.org/5.4.1/release-notes.html

Starting a Gradle Daemon (subsequent builds will be faster)

> Task :npmInstall

> husky@1.3.1 install /home/jhipster/app/issue-16806-example/node_modules/husky
> node husky install

husky > setting up git hooks
husky > done

> spawn-sync@1.0.15 postinstall /home/jhipster/app/issue-16806-example/node_modules/spawn-sync
> node postinstall

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

added 1918 packages from 1519 contributors and audited 886862 packages in 58.066s
found 0 vulnerabilities


> Task :webpackBuildDev

> foobar@0.0.0 webpack:build /home/jhipster/app/issue-16806-example
> npm run cleanup && npm run webpack:build:main


> foobar@0.0.0 cleanup /home/jhipster/app/issue-16806-example
> rimraf build/resources/main/static/


> foobar@0.0.0 webpack:build:main /home/jhipster/app/issue-16806-example
> npm run webpack -- --config webpack/webpack.dev.js --env.stats=minimal


> foobar@0.0.0 webpack /home/jhipster/app/issue-16806-example
> node --max_old_space_size=4096 node_modules/webpack/bin/webpack.js "--config" "webpack/webpack.dev.js" "--env.stats=minimal"

Webpack: Starting ...
Starting type checking and linting service...
Webpack: Starting ...

   ??? Compile modules
   ??? Build modules
   ??? Optimize modules
   ??? Emit files

Webpack: Finished after 14.879 seconds.
> IDLE
 DONE  Compiled successfully in 14900ms5:06:08 PM
> IDLE
   1152 modulesDev

> Task :compileJava
Note: Hibernate JPA 2 Static-Metamodel Generator 5.3.9.Final

> Task :bootRun

        ??? ???   ??? ????????? ????????   ??????? ????????? ????????? ????????
        ??? ???   ??? ????????? ????????? ???????? ????????? ????????? ?????????
        ??? ?????????    ???    ????????? ???????     ???    ???????   ?????????
  ???   ??? ?????????    ???    ????????   ???????    ???    ???????   ????????
  ????????? ???   ??? ????????? ???       ????????    ???    ????????? ???  ????
   ???????  ???   ??? ????????? ???       ???????     ???    ????????? ???   ???

:: JHipster ?  :: Running Spring Boot 2.1.4.RELEASE ::
:: https://www.jhipster.tech ::

2019-05-13 17:08:28.811  INFO 415 --- [  restartedMain] com.foobar.FoobarApp                     : Starting FoobarApp on 7d1627284eec with PID 415 (/home/jhipster/app/issue-16806-example/build/classes/java/main started by jhipster in /home/jhipster/app/issue-16806-example)
2019-05-13 17:08:28.812 DEBUG 415 --- [  restartedMain] com.foobar.FoobarApp                     : Running with Spring Boot v2.1.4.RELEASE, Spring v5.1.6.RELEASE
2019-05-13 17:08:28.812  INFO 415 --- [  restartedMain] com.foobar.FoobarApp                     : The following profiles are active: dev,swagger
2019-05-13 17:08:32.036 DEBUG 415 --- [  restartedMain] c.ehcache.core.Ehcache-usersByLogin      : Initialize successful.
2019-05-13 17:08:32.060 DEBUG 415 --- [  restartedMain] c.ehcache.core.Ehcache-usersByEmail      : Initialize successful.
2019-05-13 17:08:32.067 DEBUG 415 --- [  restartedMain] c.e.core.Ehcache-com.foobar.domain.User  : Initialize successful.
2019-05-13 17:08:32.074 DEBUG 415 --- [  restartedMain] c.e.c.E.foobar.domain.Authority          : Initialize successful.
2019-05-13 17:08:32.081 DEBUG 415 --- [  restartedMain] c.e.c.E.foobar.domain.User.authorities   : Initialize successful.
2019-05-13 17:08:32.110 DEBUG 415 --- [  restartedMain] com.foobar.config.AsyncConfiguration     : Creating Async Task Executor
2019-05-13 17:08:32.212 DEBUG 415 --- [  restartedMain] c.foobar.config.LiquibaseConfiguration   : Configuring Liquibase
2019-05-13 17:08:32.423  WARN 415 --- [  foobar-task-1] i.g.j.c.liquibase.AsyncSpringLiquibase   : Starting Liquibase asynchronously, your database might not be ready at startup!
2019-05-13 17:08:34.554 DEBUG 415 --- [  foobar-task-1] i.g.j.c.liquibase.AsyncSpringLiquibase   : Liquibase has updated your database in 2129 ms
2019-05-13 17:08:34.632 DEBUG 415 --- [  restartedMain] com.foobar.config.WebConfigurer          : Registering CORS filter
2019-05-13 17:08:34.706  INFO 415 --- [  restartedMain] com.foobar.config.WebConfigurer          : Web application configuration, using profiles: dev
2019-05-13 17:08:34.706 DEBUG 415 --- [  restartedMain] com.foobar.config.WebConfigurer          : Initialize H2 console
2019-05-13 17:08:34.709  INFO 415 --- [  restartedMain] com.foobar.config.WebConfigurer          : Web application fully configured
2019-05-13 17:08:34.791 DEBUG 415 --- [  restartedMain] com.foobar.security.jwt.TokenProvider    : Using a Base64-encoded JWT secret key
2019-05-13 17:08:35.941 DEBUG 415 --- [  restartedMain] com.foobar.config.DatabaseConfiguration  : H2 database is available on port 18080
2019-05-13 17:08:36.329 DEBUG 415 --- [  restartedMain] i.g.j.c.apidoc.SwaggerAutoConfiguration  : Starting Swagger
2019-05-13 17:08:36.339 DEBUG 415 --- [  restartedMain] i.g.j.c.apidoc.SwaggerAutoConfiguration  : Started Swagger in 10 ms
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.xnio.nio.NioXnio$2 (file:/home/jhipster/.gradle/caches/modules-2/files-2.1/org.jboss.xnio/xnio-nio/3.3.8.Final/8dafaf230666e526c53e544ab6a9d6ecfcbab4ee/xnio-nio-3.3.8.Final.jar) to constructor sun.nio.ch.EPollSelectorProvider()
WARNING: Please consider reporting this to the maintainers of org.xnio.nio.NioXnio$2
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
2019-05-13 17:08:36.956  INFO 415 --- [  restartedMain] com.foobar.FoobarApp                     : Started FoobarApp in 8.753 seconds (JVM running for 9.206)
2019-05-13 17:08:36.965  INFO 415 --- [  restartedMain] com.foobar.FoobarApp                     : 
----------------------------------------------------------
        Application 'foobar' is running! Access URLs:
        Local:          http://localhost:8080/
        External:       http://172.17.0.2:8080/
        Profile(s):     [dev, swagger]
----------------------------------------------------------
```

Here the Java version inside the container:

```
jhipster@7d1627284eec:~/app/issue-16806-example$ java -version
openjdk version "11.0.2" 2019-01-15
OpenJDK Runtime Environment (build 11.0.2+9-Ubuntu-3ubuntu118.04.3)
OpenJDK 64-Bit Server VM (build 11.0.2+9-Ubuntu-3ubuntu118.04.3, mixed mode, sharing)
```

I suspect your Java version. Here some things you can try to solve your issue:
- change and try another Java 11 version
- maybe you can try with JDK8
- try our Docker image, following my previous command
- our Devbox -> https://github.com/jhipster/jhipster-devbox

**Comment by PierreBesson** [comment]
It seems your JDK is from Oracle, could you try with the one from : https://adoptopenjdk.net/

**Comment by pascalgrimaud** [comment]
As I couldn't reproduce, I let you try to change your JDK version.
Don't hesitate to comment this ticket, if you have additional information to help us to reproduce. 
For now, let's close this

**Comment by freynder** [comment]
FWIW: I had a similar issue. Following this response: https://stackoverflow.com/a/45102852 , I cleared my .m2 folder and it solved the issue. I suspect there was an issue with the proxy server when initially downloading dependencies.

**Comment by mikebaxley** [comment]
Thanks for this comment.  I was having the same issue and clearing my .m2 solved the issue on my workstation as well.

**Comment by freynder** [comment]
I continued to experience the issue on multiple occasions. The issue occurs when using Eclipse (sts-4.3.2) so I guess the Eclipse JDT core compiler may be involved? When closing editors and running mvn clean && mvn from the command line, there is no error.

For my particular case, I also experienced errors with Lombok from command line when using JDK 11 but have removed it since.

**Comment by gzsombor** [comment]
This issue drove me crazy for an hour, until I finally understand what's going on (and why @pascalgrimaud couldn't reproduce this issue ;-) ). This actually a feature of Spring Boot Tools! It tries to detect the beans which are running in Spring applications (why, I don't know ... ), and thinks, that connecting to a Java application is perfectly fine thing to do over JMX. To disable this, in open the **Preferences > Spring Boot Lanuage Server** and uncheck the 'Live information - Automatic Process Tracking Enabled' switch. And no more annoying exceptions!

**Comment by freynder** [comment]
@gzsombor : Great find! Thank you very much for sharing this.

**Comment by pascalgrimaud** [comment]
@gzsombor : thanks for the information and sharing this. So is it only with Eclipse IDE ?

**Comment by sometxdude** [comment]
I was also using STS/Eclipse when I encountered this issue.  I think @gzsombor has likely solved this one.

**Comment by gzsombor** [comment]
The 'feature' comes from Spring Tools - and now, you can install STS4 ( https://github.com/spring-projects/sts4 ) even into VSCode or Eclipse Theia/Che, so maybe that ones are also affected, however I haven't tried it.

**Comment by pmverma** [comment]
Last time I had this same issue and after updating to latest STS, 4.9.0 I
think, the error was no longer showing up.

**Comment by helloaneeskhan** [comment]
@gzsombor  Thank you, problem solved :)

**Comment by PC-Chiu** [comment]
@gzsombor Great find! Thank you very much for sharing this.
